### ISSUE TITLE
Linux: multiple processes fighting over writing to `/etc/resolv.conf`

### ISSUE THREAD

**Issue by geekyouth** [tailscale/tailscale#6979] opened 2023-01-16 16:27 UTC
### What is the issue?

```
1月 17 00:08:55 sz tailscaled[24976]: control: Client.Shutdown done.
1月 17 00:08:55 sz tailscaled[24976]: magicsock: closing connection to derp-7 (conn-close), age 1m48s
1月 17 00:08:55 sz tailscaled[24976]: magicsock: 0 active derp conns
1月 17 00:08:55 sz tailscaled[24976]: monitor: RTM_DELROUTE: src=, dst=fe80::/64, gw=, outif=17, table=254
1月 17 00:08:55 sz tailscaled[24976]: monitor: RTM_DELROUTE: src=, dst=ff00::/8, gw=, outif=17, table=255
1月 17 00:08:55 sz tailscaled[24976]: monitor: RTM_DELROUTE: src=, dst=fe80::/128, gw=, outif=1, table=255
1月 17 00:08:55 sz tailscaled[24976]: monitor: RTM_DELROUTE: src=, dst=fe80::.... ad8/128, gw=, outif=1, table=255
1月 17 00:08:55 sz tailscaled[24976]: monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:254 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gatew
1月 17 00:08:55 sz tailscaled[24976]: monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:253 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gatew
1月 17 00:08:55 sz tailscaled[24976]: monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:0 Protocol:0 Scope:0 Type:7 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway
1月 17 00:08:55 sz tailscaled[24976]: monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:52 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gatewa
1月 17 00:08:55 sz tailscaled[24976]: flushing log.
1月 17 00:08:55 sz tailscaled[24976]: logger closing down
1月 17 00:08:55 sz tailscaled[25447]: logtail started
1月 17 00:08:55 sz tailscaled[25447]: Program starting: v1.34.2-t1f0817693-g56304b539, Go 1.19.4-tse6ce5b5003: []string{"/usr/sbin/tailscaled", "--cleanup"}
1月 17 00:08:55 sz tailscaled[25447]: LogID: ...
1月 17 00:08:55 sz tailscaled[25447]: logpolicy: using system state directory "/var/lib/tailscale"
1月 17 00:08:55 sz tailscaled[25447]: dns: resolvedIsActuallyResolver error: resolv.conf doesn't point to systemd-resolved; points to [192.168.8.1]
1月 17 00:08:55 sz tailscaled[25447]: dns: [rc=nm resolved=not-in-use ret=direct]
1月 17 00:08:55 sz tailscaled[25447]: dns: using "direct" mode
1月 17 00:08:55 sz tailscaled[25447]: dns: using *dns.directManager
1月 17 00:08:55 sz tailscaled[25447]: flushing log.
1月 17 00:08:55 sz tailscaled[25447]: logger closing down
1月 17 00:08:56 sz tailscaled[25447]: logtail: upload: log upload of 1440 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/e0f7c8440a022be8131dd780713
1月 17 00:08:56 sz systemd[1]: Stopped Tailscale node agent.

```

then i can't connect this host through ssh port

after i `systemctl stop tailscaled`, i can connect the host through ssh port

### Steps to reproduce

yum install yum-utils -y
yum-config-manager --add-repo https://pkgs.tailscale.com/stable/centos/7/tailscale.repo
yum install tailscale -y
systemctl enable --now tailscaled
tailscale up

...

### OS

Linux

### OS version

CentOS Linux 7 (Core)

### Tailscale version

1.34.2

### Bug report

BUG-03d137fce54692e24ac94cecdefd164f7762d56e9e8d26ebc58c61f4f56eb551-20230116162657Z-dbf6373c5d0bca81

**Comment by geekyouth** [comment] 2023-01-16 16:41
https://tailscale.com/kb/1188/linux-dns/#networkmanager--systemd-resolved

ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
systemctl restart systemd-resolved
systemctl restart NetworkManager
systemctl restart tailscaled

then after i login tailscale on linux , the linux host is Unreachable

**Comment by geekyouth** [comment] 2023-01-16 16:43
after i logout my tailscale account on the linux host, the linux host is reachable...

why???

**Comment by bradfitz** [comment] 2023-01-16 17:21
How is the linux host "unreachable"?

Sounds like you might have a mix of software all fighting over `/etc/resolv.conf`, and then Tailscale joins the fight too because there doesn't appear to be any other option.

Your best bet is to get `systemd-resolved` working first and then use Tailscale.

We'd ideally want a `tailscale bugreport` at different stages, annotated to say which stage corresponds to what action on your part.

**Comment by DentonGentry** [comment] 2023-02-11 18:10
We'll assume the issue is multiple processes fighting over writing to /etc/resolv.conf and that `systemd-resolved` is the way to solve it. Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by mostlyvirtual** [comment] 2023-05-16 14:29
I might have the same issue, though it does look like it might be different, but I don't want to open a new issue if it's indeed related.

This happened twice now, seemingly randomly, but it could be triggered by something else that I can't find in the logs. No cronjobs running around the times this happened FYI.

Submitted a bug report, but alas it was after I power cycled the machine, so hopefully the log is useful.
BUG-d83782eeb24d80fc5d267bd22ce3b0c4182023e24a0679527ed27bee6adfb34c-20230516135041Z-f6a3bb8c5dc2a5fb

OS: Debian 11
tailscale version
1.40.0
  tailscale commit: 105be684dd04727a58ed213ec9499d071a377ece
  other commit: 4c70014a47f1816e1573a8cef58cdaf96f78a264
  go version: go1.20.3-tsddff070

---

Here's the log file:

```shell
May 16 13:42:59 mighty tailscaled[604]: [RATELIMIT] format("monitor: %s: src=%v, dst=%v, gw=%v, outif=%v, table=%v") (4 dropped)
May 16 13:42:59 mighty tailscaled[604]: monitor: RTM_DELROUTE: src=10.10.10.10/0, dst=10.10.10.255/32, gw=, outif=2, table=255
May 16 13:42:59 mighty tailscaled[604]: monitor: RTM_DELROUTE: src=10.10.10.10/0, dst=10.10.10.10/32, gw=, outif=2, table=255
May 16 13:42:59 mighty avahi-daemon[398]: Withdrawing address record for 10.10.10.10 on eth0.
May 16 13:42:59 mighty avahi-daemon[398]: Leaving mDNS multicast group on interface eth0.IPv4 with address 10.10.10.10.
May 16 13:42:59 mighty avahi-daemon[398]: Interface eth0.IPv4 no longer relevant for mDNS.
May 16 13:42:59 mighty tailscaled[604]: LinkChange: major, rebinding. New state: interfaces.State{defaultRoute= ifs={br-101619766d0b:[1
72.30.0.1/16] br-1194c7d35a18:[172.27.0.1/16] br-5b191d09e896:[172.31.0.1/16] br-602eb1f19ec9:[192.168.224.1/20] br-68dd065de299:[172.2
2.0.1/16] br-7c6747c29782:[172.23.0.1/16] br-8b01b96569e7:[192.168.16.1/20] br-a54bb7617c97:[172.19.0.1/16] br-f01faa842e08:[172.29.0.1
/16] docker0:[172.17.0.1/16] tailscale0:[100.111.236.106/32 fd7a:115c:a1e0:ab12:4843:cd96:626f:ec6a/128]} v4=true v6=false}
May 16 13:42:59 mighty tailscaled[604]: dns: Set: {DefaultResolvers:[1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001] Routes:
{tailbc24.ts.net.:[] ts.net.:[199.247.155.53 2620:111:8007::53]}+65arpa SearchDomains:[tailbc24.ts.net.] Hosts:12}
May 16 13:42:59 mighty tailscaled[604]: dns: Resolvercfg: {Routes:{.:[1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001] ts.net
.:[199.247.155.53 2620:111:8007::53]} Hosts:12 LocalDomains:[tailbc24.ts.net.]+65arpa}
May 16 13:42:59 mighty tailscaled[604]: Received error: PollNetMap: read tcp 10.10.10.10:41976->18.156.90.224:80: use of closed network
 connection
May 16 13:42:59 mighty tailscaled[604]: dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[tailbc24.ts.net.] MatchDomains:[] Hos
ts:[]}
May 16 13:42:59 mighty tailscaled[604]: wgengine: set DNS config again after major link change
May 16 13:42:59 mighty tailscaled[604]: Rebind; defIf="", ips=[]
May 16 13:42:59 mighty tailscaled[604]: magicsock: closing connection to derp-14 (rebind-default-route-change), age 57s
May 16 13:42:59 mighty tailscaled[604]: magicsock: closing connection to derp-4 (rebind-default-route-change), age 8m28s
May 16 13:42:59 mighty tailscaled[604]: magicsock: 0 active derp conns
May 16 13:42:59 mighty tailscaled[604]: magicsock: adding connection to derp-4 for home-keep-alive
May 16 13:42:59 mighty tailscaled[604]: magicsock: 1 active derp conns: derp-4=cr0s,wr0s
May 16 13:42:59 mighty tailscaled[604]: derphttp.Client.Recv: connecting to derp-4 (fra)
May 16 13:42:59 mighty tailscaled[604]: health("overall"): error: not connected to home DERP region 4
May 16 13:42:59 mighty tailscaled[604]: magicsock: [0x40035fe800] derp.Recv(derp-4): derphttp.Client.Recv connect to region 4 (fra): dial tcp4 185.40.234.77:443: connect: network is unreachable
May 16 13:42:59 mighty tailscaled[604]: derphttp.Client.Recv: connecting to derp-4 (fra)
May 16 13:42:59 mighty tailscaled[604]: magicsock: [0x40035fe800] derp.Recv(derp-4): derphttp.Client.Recv connect to region 4 (fra): dial tcp4 185.40.234.77:443: connect: network is unreachable
``` 

It could be possible that the eth0 interface was reset for some reason and it had no connection to tailscale, but according to dhcpd it was running at 14:17, but tailscale didn't recover.

**Comment by DentonGentry** [comment] 2023-06-02 23:19
@mostlyvirtual I don't immediately see that as being the same issue, there it no indication that /etc/resolv.conf is involved. I've opened https://github.com/tailscale/tailscale/issues/8261 using that comment, and will close this bug as mentioned earlier.

**Closed by DentonGentry** 2023-06-02 23:19 UTC
Labels: OS-linux, L2 Few, P2 Aggravating, T5 Usability, waiting-for-info, dns, bug
