### ISSUE TITLE
Package tailscale_1.46.1_x86_64.rpm is not signed

### ISSUE THREAD

**Issue by bjsbx** [tailscale/tailscale#8944] opened 2023-08-17 22:23 UTC
### What is the issue?

While attempting to install tailscale on Amazon Linux 2, we receive error `Package tailscale_1.46.1_x86_64.rpm is not signed`.

### Steps to reproduce

```
$ yum-config-manager --add-repo https://pkgs.tailscale.com/stable/amazon-linux/2/tailscale.repo

Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
adding repo from: https://pkgs.tailscale.com/stable/amazon-linux/2/tailscale.repo
grabbing file https://pkgs.tailscale.com/stable/amazon-linux/2/tailscale.repo to /etc/yum.repos.d/tailscale.repo
repo saved to /etc/yum.repos.d/tailscale.repo

$ yum install tailscale -y
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
tailscale-stable/x86_64/signature                                                              |  832 B  00:00:00

tailscale-stable/x86_64/signature                                                              | 3.0 kB  00:00:00 !!!
Resolving Dependencies
--> Running transaction check
---> Package tailscale.x86_64 0:1.46.1-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

======================================================================================================================
 Package                    Arch                    Version                   Repository                         Size
======================================================================================================================
Installing:
 tailscale                  x86_64                  1.46.1-1                  tailscale-stable                   24 M

Transaction Summary
======================================================================================================================
Install  1 Package

Total size: 24 M
Installed size: 45 M
Downloading packages:


Package tailscale_1.46.1_x86_64.rpm is not signed

$ uname -a
22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64
```

### OS

Linux

### OS version

Amazon Linux 2

### Tailscale version

1.46.1

**Comment by DentonGentry** [comment] 2023-08-17 22:27
Duplicate of https://github.com/tailscale/tailscale/issues/1882

Expected to be fixed in a 1.48 release. We had to withdraw 1.48.0 due to a regression in `ufw` handling, but expect to build 1.48.1 next week.

**Closed by DentonGentry** 2023-08-17 22:27 UTC
Labels: needs-triage, bug
