### ISSUE TITLE
Auto disable the Tailscale while detected the home network.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2943] opened 2021-09-27 15:17 UTC
The user requested the feature :

`It would be terrific if there was an option in the mobile app to automatically disable the VPN while on configured and trusted home WiFi network. This could save a bit more on the battery and the private network is available at home! :)`

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3l5xt)

**Comment by bradfitz** [comment] 2021-09-27 15:32
Dup of #1227, etc?

**Comment by DentonGentry** [comment] 2021-09-28 23:37
Duplicate of #1227

**Closed by DentonGentry** 2021-09-28 23:37 UTC
Labels: needs-triage

**Comment by taisph** [comment] 2024-08-16 16:18
The Google VPN on Pixel app simply disables the VPN on user selected SSIDs. #1227 seems a lot more complex than necessary to solve the feature request here.
