### ISSUE TITLE
File is getting stuck with taildrop while transferring from macOS to windows.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2358] opened 2021-07-08 15:29 UTC
Customer try to transfer files from macOS to windows and running into issue where transfer creates multiple files. and it cannot be deleted , if we deletes it , it reappears by itself unless we delete from files folder under tailscale.

steps to reproduce:
1) Connect macOS and Windows to same tailnet.
2) try to transfer the file which is 2 MB or more than 2 MB or larger files from macOS to windows.
3) you will find that it creates chunk of 9 files with 0bytes on windows end and if you try deleting it it reappears or complains that Tailscale is using these files.

macOS Tailscale version. : 1.10.0 
Windows Tailscale version. : 1.10.1

Windows 10 
macOS : 11.4

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3csgh)

**Comment by DentonGentry** [comment] 2021-07-08 15:35
Oh.

https://user-images.githubusercontent.com/1140756/124950612-6de2d400-dfc7-11eb-94e9-eeeb203f6281.mov

**Comment by DentonGentry** [comment] 2021-07-08 16:04
On the system where that video was recorded half an hour ago, the frontend logs are still logging this over and over:

```
2021-07-08 09:02:39.2314218 -0700 PDT: ui: UI still alive.
2021-07-08 09:02:40.2429009 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:02:42.2425216 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:02:43.6395245 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:02:44.240559 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:02:46.2500267 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:02:48.2413175 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:02:50.2417822 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:02:52.236185 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:02:54.2316076 -0700 PDT: ui: UI still alive.
2021-07-08 09:02:54.2389229 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:02:56.2358222 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:02:58.2445212 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:03:00.2547113 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:03:02.2441813 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:03:04.2395829 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:03:06.2507832 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:03:08.240615 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:03:09.2357649 -0700 PDT: ui: UI still alive.
2021-07-08 09:03:10.2476203 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:03:12.2349913 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 09:03:14.2439124 -0700 PDT: fetchFiles: couldn't find free filename
```

**Comment by bradfitz** [comment] 2021-07-08 16:09
@DentonGentry, that's what's stopping it from creating an infinite number of files on the desktop. It only tries 10 number-in-parens suffixes before it stops. The bug is why it made it to the 2nd file, not stopping after the 1st.

**Comment by bradfitz** [comment] 2021-07-08 16:10
Do you see this log print anywhere:

```
                        if err := tailscale.DeleteWaitingFile(ctx, wf.Name); err != nil {
                                log.Printf("deleting file post-copy: %v", err)
                                return
                        }
```

**Comment by bradfitz** [comment] 2021-07-08 16:22
Ah, 500 error from GetWaitingFile, and that error path doesn't clean up the `of` it created earlier. Sent https://github.com/tailscale/corp/pull/2174 for that part.

```
2021-07-08 08:31:58.2494007 -0700 PDT: fetchFiles: HTTP 500 Internal Server Error: open redacted: The system cannot find the file specified.
2021-07-08 08:32:00.2514074 -0700 PDT: fetchFiles: HTTP 500 Internal Server Error: open redacted: The system cannot find the file specified.
2021-07-08 08:32:02.250089 -0700 PDT: fetchFiles: couldn't find free filename
2021-07-08 08:32:04.2603331 -0700 PDT: fetchFiles: couldn't find free filename
```

**Comment by DentonGentry** [comment] 2021-07-08 16:57
After patching in https://github.com/tailscale/corp/commit/7b8722aa5e993808884a89edf517810e73a2b09b and building for Windows, the symptoms have changed: Taildropped files no longer appear on the desktop at all. The MacOS system shows its usual progress bar and checkmark as it sends the file, but nothing appears on the Windows desktop.

I rebooted the Windows system, and upon the next boot I did have file.mov and file(1).mov files appear on the desktop. I've rebooted the Windows system a number of times since, and no more files have appeared despite sending several from the MacOS system.

**Comment by bradfitz** [comment] 2021-07-08 17:01
And now your frontend just says:

```
2021-07-08 09:59:19.9120281 -0700 PDT: fetchFiles: HTTP 500 Internal Server Error: open redacted: The system cannot find the file specified.
2021-07-08 09:59:20.0660268 -0700 PDT: fetchFiles: HTTP 500 Internal Server Error: open redacted: The system cannot find the file specified.
2021-07-08 09:59:22.075605 -0700 PDT: fetchFiles: HTTP 500 Internal Server Error: open redacted: The system cannot find the file specified.
2021-07-08 09:59:24.062039 -0700 PDT: fetchFiles: HTTP 500 Internal Server Error: open redacted: The system cannot find the file specified.
2021-07-08 09:59:26.0625618 -0700 PDT: fetchFiles: HTTP 500 Internal Server Error: open redacted: The system cannot find the file specified.
2021-07-08 09:59:28.0688644 -0700 PDT: fetchFiles: HTTP 500 Internal Server Error: open redacted: The system cannot find the file specified.
2021-07-08 09:59:30.0634055 -0700 PDT: fetchFiles: HTTP 500 Internal Server Error: open redacted: The system cannot find the file specified.
2021-07-08 09:59:32.073943 -0700 PDT: fetchFiles: HTTP 500 Internal Server Error: open redacted: The system cannot find the file specified.
```

But I see nothing interesting in the backend logs.

**Comment by bradfitz** [comment] 2021-07-08 17:10
@DentonGentry, it's hitting one of these two exit paths in `peerapi.go`:

```go
        if fi, err := os.Stat(path + deletedSuffix); err == nil && fi.Mode().IsRegular() {
                tryDeleteAgain(path)
                return nil, 0, &fs.PathError{Op: "open", Path: redacted, Err: fs.ErrNotExist}
        }
        f, err := os.Open(path)
        if err != nil {
                return nil, 0, redactErr(err)
        }
```

Do you have a `foo.deleted` file in your `C:\Windows\System32\config\systemprofile\AppData\Local\Tailscale\files\$USER\` directory?

**Comment by DentonGentry** [comment] 2021-07-08 17:12
There is not a *.deleted file. climate.new.* is the one which was appearing as file(1)...file(9), and tailscale-ipn-setup.exe is a file which I tried to copy subsequently and has not appeared on the Desktop.

```
C:\Users\DGentry>dir C:\Windows\System32\config\systemprofile\AppData\Local\Tailscale\files\denny-geekhold.com-uid-59667916876184027
 Volume in drive C has no label.
 Volume Serial Number is 5829-FEE3

Directory of C:\Windows\System32\config\systemprofile\AppData\Local\Tailscale\files\denny-geekhold.com-uid-59667916876184027

07/08/2021  09:50 AM    <DIR>          .
07/08/2021  09:50 AM    <DIR>          ..
07/08/2021  09:50 AM        12,009,527 climate.new%20demo%201.2021.mov
07/08/2021  09:41 AM        24,059,187 tailscale-ipn-setup.exe
               2 File(s)     36,068,714 bytes
               2 Dir(s)  17,828,691,968 bytes free

C:\Users\DGentry>
```

**Comment by bradfitz** [comment] 2021-07-08 17:33
Is this a URL/path escaping thing again? (IIRC another bug is open about that)

Can you stop Tailscale, delete those files, and then repro with another file that doesn't contain any URL-special characters ("foo.txt")?

**Comment by DentonGentry** [comment] 2021-07-08 17:40
That works. I deleted all files from C:\Windows\System32\config\systemprofile\AppData\Local\Tailscale\files\denny-geekhold.com-uid-59667916876184027, and was then able to copy tailscale-ipn-setup.exe from the MacOS system and have it appear on the Windows desktop.

**Comment by bradfitz** [comment] 2021-07-08 18:02
But does the same file named with a space in it fail?

**Comment by DentonGentry** [comment] 2021-07-08 18:13
Copying "climate.new demo 1.2021.mov" from Linux works, the file appears on the Windows desktop with the spaces in its filename.

Copying "climate.new demo 1.2021.mov" from MacOS results in a C:\Windows\System32\config\systemprofile\AppData\Local\Tailscale\files\denny-geekhold.com-uid-59667916876184027\climate.new%20demo%201.2021.mov appearing, which never appears on the desktop.

**Comment by bradfitz** [comment] 2021-07-08 20:59
@DentonGentrym, I think we can close this as a dup of #2288? In particular, see https://github.com/tailscale/tailscale/issues/2288#issuecomment-872968481

**Comment by DentonGentry** [comment] 2021-07-08 21:11
Dup of #2288

**Closed by DentonGentry** 2021-07-08 21:11 UTC
Labels: L3 Some users, OS-windows, P2 Aggravating, T5 Usability

**Comment by Noobgamer0111** [comment] 2024-10-28 07:05
Hey guys, not opening this issue up again, but just reporting this behaviour with TailDrop is still occuring on stable versions.

I'm noticing this same behaviour with 'URL-encoded' style files/files with special characters in it.

E.g. The file "Call of Duty Black Ops 6 Campaign Walkthrough (FULL GAME).webm" would then duplicate into nine more files with a 0KB file size. But removing the parentheses will result in a single file (intended behaviour).
