### ISSUE TITLE
iOS internet problems, when connected to Tailscale

### ISSUE THREAD

**Issue by Jarod000000** [tailscale/tailscale#8806] opened 2023-08-07 13:33 UTC
### What is the issue?

I only have a free tier with my Macbook, my iPhone, my Synology NAS and my private linux server.

When I have Tailscale running on my iOS device (iPhone 13 Pro Max, iOS 16.6), sometimes I have connection problems. Websites don't load, and the device can't connect to any online services. When I disable the VPN, everything works instantly. I don't have exit nodes configured or anything like this. It is happening on both, cellular and WiFi.

### Steps to reproduce

1. enable Tailscale on the iOS device
2. surf the internet
3. encounter the problem

### Are there any recent changes that introduced the issue?

I only started using Tailscale recently, so I kinda having this problem, since the beginning.

### OS

iOS

### OS version

16.6

### Tailscale version

1.46.1

### Bug report

BUG-f4f1e69695263dd12c5c0454d1ed0cc3b338e08a05fe2c640285a9e8e8031bb5-20230807133254Z-95b3a65234479039

**Comment by owohub** [comment] 2023-08-09 09:02
This has been present for me for a while as well, in the stable App Store build as well as in the latest testflight one. This needs to be looked at as it completely breaks the experience. Thank you.

**Comment by michaelperros** [comment] 2023-08-15 10:46
Hello, I had a similar issue, but eventually got it all to work with my iPhone after a few weeks of tinkering. The issue was essentially due to my firewall settings on my pi-hole server, and some other misc settings. If you want I can try to help you. Post your firewall settings and let's go from there.

**Comment by danmarg** [comment] 2023-09-10 09:48
I am seeing the same on 1.48.1 on iOS 17.0 beta. 

I *thought* it was most reproducible when switching between wifi and cellular data while using a Mullvad exit node, but it doesn't repro 100% of the time when I do that. 

Notably, once the Tailscale network stops working, even if I turn off exit nodes the Internet in general doesn't work (which could just be DNS resolution not working; I don't know how to check this on iOS, and it requires turning off Tailscale entirely and back in to get it to work. 

I know this isn't a very helpful bug report--I'm not an iOS developer and not sure what logs exist, but happy to do anything that helps track this down.

**Comment by 0adapter** [comment] 2023-09-11 19:42
Same issue on my end. 1.48.1 on iOS 17.0 beta. The issue appears to occur when I close the Tailscale app. When I leave it open, it seems to stay connected.

**Comment by danmarg** [comment] 2023-09-17 13:18
I never see this on an iPad which always has the same wifi connection; I often see this on an iPhone which goes between various wifi and cell connections. So my guess is that this is related to resuming connections on network changes, or something like that?

FWIW, I also never see this with raw Wireguard.

Sorry for the lack of a clean repro.

**Comment by wingcomm** [comment] 2023-09-25 02:26
I see this all the time as well on my iPhone. Appreciate the feedback on Wi-Fi @danmarg. Only workaround is to switch to tailscale abd disable/re-enable the VPN.

Currently on iOS 17.0.2 and Tailscale 1.48.2.

**Comment by gymshoe** [comment] 2023-10-04 04:43
Same problem on my iphone12 (iOS 16.7) w/ Tailscale 1.50.0: If I have Tailscale connected while on cellular it works. When I change to wifi it still works. But when I go back to cellular, then internet connection fails (reliably). Sometimes, disconnecting and reconnecting Tailscale fixes the problem, but sometimes it doesn't. In those cases what fixes the problem is also disabling the exit node along with disabling Tailscale. The exit node I am using is the Apple TV  and tailscale 1.50.0.   (When I reconnect the exit node, it still works - until I have do the cellular-wifi-cellular thing.)  

Also, I am seeing the same kind of intermittent internet connection loss on my macOS(12.6.8) and Tailscale1.48.2.  This was fixed when I disconnected and reconnected tailscale, although sometimes required also disabling the exit node in the control panel (and then reenabling the exit node), like for the iphone. 

Interestingly, when I have the internet connection problem, the iOS Tailscale app and the tailscale admin panel do not show the same status of the exit node - they are not in sync.

**Comment by purple-emily** [comment] 2024-01-08 13:28
I am also having this issue. My internet access will completely stop. I have to disconnect and reconnect to Tailscale to get it working again.

**Comment by agottardo** [comment] 2024-01-11 00:24
Duplicate of #8022 

This is already fixed [on TestFlight](https://tailscale.com/kb/1083/install-unstable) if you want to try the unstable builds there. Otherwise, the fix will roll out to everyone in the next app update.

**Closed by agottardo** 2024-01-11 00:24 UTC
Labels: needs-triage, bug

**Comment by purple-emily** [comment] 2024-01-11 00:50
> Duplicate of #8022
> 
> This is already fixed [on TestFlight](https://tailscale.com/kb/1083/install-unstable) if you want to try the unstable builds there. Otherwise, the fix will roll out to everyone in the next app update.

I’m on this version. So it isn’t fixed

**Comment by deardaniel** [comment] 2024-01-13 23:22
Same here.

**Comment by DentonGentry** [comment] 2024-01-14 00:52
The root cause of https://github.com/tailscale/tailscale/issues/8022 was identified and is fixed. If you are having connectivity issues on iOS please open a new bug and include a bugreport from the app. We will need to be able to look at telemetry to diagnose anything.
