### ISSUE TITLE
Android with one non-responsive DNS server fails DNS lookups

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3816] opened 2022-01-26 04:43 UTC
https://twitter.com/Jesb1n/status/1486182893127090178 (@jesb1n) says:

> Hi there 👋, Any one using @Tailscale on android?. I am using pihole🍓 as DNS server on my tailscale network. DNS resolution works seamlessly on my 🖥, but not on my android 📱. Any idea what's causing this or why this is happening?🤔

Later replied with bug:

BUG-dc4ba901ab3b5360d03e50007754fbe45570bec63755543f48ed986a0d6499d1-20220126042507Z-d35bf18656d76369 from 

Android 11, Tailscale 1.20.2-t8e643357d-ge1751fa2802.

Easy NAT, UDP.

From logs I see:
```
2022-01-26 04:21:09.751237798 +0000 UTC: 8.7M/180.9M dns: Set: {DefaultResolvers:[100.102.179.111:53 100.111.205.93:53] Routes:{} SearchDomains:[] Hosts:4}
2022-01-26 04:21:09.751595145 +0000 UTC: 8.7M/180.9M dns: Resolvercfg: {Routes:{} Hosts:4 LocalDomains:[]}
2022-01-26 04:21:09.751841337 +0000 UTC: 8.7M/180.9M dns: OScfg: {Nameservers:[100.102.179.111 100.111.205.93] SearchDomains:[] MatchDomains:[]}
```

Notably, two Tailscale IPs as DNS.

But then we hand them directly to the OS, so the OS is probably handling them in serial (and 100.102.179.111 looks like it's currently down, but 100.111.205.93 is up).

So perhaps it was the order or perhaps it was a 50% chance.

But in this case, when there's more than 1, we should probably set the OScfg to 100.100.100.100 so the Tailscale DNS forwarder handles it, then we can race the two like normal.

Thoughts, @danderson?

@jesb1n, does it work meanwhile if you only list one DNS server in the admin panel? (to one that's up)

/cc @DentonGentry

**Comment by DentonGentry** [comment] 2022-01-26 04:52
Did this device work better with 1.18? (assuming that one of the DNS servers was down even then).

This tailnet must have "Override local DNS" set in https://login.tailscale.com/admin/dns, so I don't really understand why the behavior in setting the DNS servers would be different in 1.20 versus 1.18.

**Comment by jesb1n** [comment] 2022-01-26 05:18
> https://twitter.com/Jesb1n/status/1486182893127090178 (@jesb1n) says:
> 
> > Hi there 👋, Any one using @tailscale on android?. I am using pihole🍓 as DNS server on my tailscale network. DNS resolution works seamlessly on my 🖥, but not on my android 📱. Any idea what's causing this or why this is happening?🤔
> 
> Later replied with bug:
> 
> BUG-dc4ba901ab3b5360d03e50007754fbe45570bec63755543f48ed986a0d6499d1-20220126042507Z-d35bf18656d76369 from
> 
> Android 11, Tailscale 1.20.2-t8e643357d-ge1751fa2802.
> 
> Easy NAT, UDP.
> 
> From logs I see:
> 
> ```
> 2022-01-26 04:21:09.751237798 +0000 UTC: 8.7M/180.9M dns: Set: {DefaultResolvers:[100.102.179.111:53 100.111.205.93:53] Routes:{} SearchDomains:[] Hosts:4}
> 2022-01-26 04:21:09.751595145 +0000 UTC: 8.7M/180.9M dns: Resolvercfg: {Routes:{} Hosts:4 LocalDomains:[]}
> 2022-01-26 04:21:09.751841337 +0000 UTC: 8.7M/180.9M dns: OScfg: {Nameservers:[100.102.179.111 100.111.205.93] SearchDomains:[] MatchDomains:[]}
> ```
> 
> Notably, two Tailscale IPs as DNS.
> 
> But then we hand them directly to the OS, so the OS is probably handling them in serial (and 100.102.179.111 looks like it's currently down, but 100.111.205.93 is up).
> 
> So perhaps it was the order or perhaps it was a 50% chance.
> 
> But in this case, when there's more than 1, we should probably set the OScfg to 100.100.100.100 so the Tailscale DNS forwarder handles it, then we can race the two like normal.
> 
> Thoughts, @danderson?
> 
> @jesb1n, does it work meanwhile if you only list one DNS server in the admin panel? (to one that's up)
> 
> /cc @DentonGentry

Now, one of my DNS servers is down due to power outage⚡ and DNS resolution on all devices isn't working😶(local DNS) . 
![image](https://user-images.githubusercontent.com/52061387/151107020-21f8785a-136b-45c4-af59-e1231021c53b.png)
![image](https://user-images.githubusercontent.com/52061387/151107073-dbfa0a84-439f-4796-b2c9-f3551766ba9a.png)
![image](https://user-images.githubusercontent.com/52061387/151107104-eaf06245-1e08-46e0-b485-ab335051e187.png)
![image](https://user-images.githubusercontent.com/52061387/151107140-56c4f2ae-dbc6-4060-b6f1-e978e36826ed.png)

Note: I have been using 100.111.205.93 as my Exit node on PC

**Comment by jesb1n** [comment] 2022-01-26 05:29
Once I removed the exit node from my PC  and the second DNS server(100.102.179.111), DNS resolution starts to work again on my PC,
![image](https://user-images.githubusercontent.com/52061387/151108685-02d62e66-f468-4462-8da4-805f037d5cd9.png)
But still nothing on my android,
![Screenshot_20220126-110031~2](https://user-images.githubusercontent.com/52061387/151108836-294dc18e-e9b8-4f06-aba1-3251bc6ae276.png)

**Comment by jesb1n** [comment] 2022-01-26 05:42
> https://twitter.com/Jesb1n/status/1486182893127090178 (@jesb1n) says:
> 
> > Hi there 👋, Any one using @tailscale on android?. I am using pihole🍓 as DNS server on my tailscale network. DNS resolution works seamlessly on my 🖥, but not on my android 📱. Any idea what's causing this or why this is happening?🤔
> 
> Later replied with bug:
> 
> BUG-dc4ba901ab3b5360d03e50007754fbe45570bec63755543f48ed986a0d6499d1-20220126042507Z-d35bf18656d76369 from
> 
> Android 11, Tailscale 1.20.2-t8e643357d-ge1751fa2802.
> 
> Easy NAT, UDP.
> 
> From logs I see:
> 
> ```
> 2022-01-26 04:21:09.751237798 +0000 UTC: 8.7M/180.9M dns: Set: {DefaultResolvers:[100.102.179.111:53 100.111.205.93:53] Routes:{} SearchDomains:[] Hosts:4}
> 2022-01-26 04:21:09.751595145 +0000 UTC: 8.7M/180.9M dns: Resolvercfg: {Routes:{} Hosts:4 LocalDomains:[]}
> 2022-01-26 04:21:09.751841337 +0000 UTC: 8.7M/180.9M dns: OScfg: {Nameservers:[100.102.179.111 100.111.205.93] SearchDomains:[] MatchDomains:[]}
> ```
> 
> Notably, two Tailscale IPs as DNS.
> 
> But then we hand them directly to the OS, so the OS is probably handling them in serial (and 100.102.179.111 looks like it's currently down, but 100.111.205.93 is up).
> 
> So perhaps it was the order or perhaps it was a 50% chance.
> 
> But in this case, when there's more than 1, we should probably set the OScfg to 100.100.100.100 so the Tailscale DNS forwarder handles it, then we can race the two like normal.
> 
> Thoughts, @danderson?
> 
> @jesb1n, does it work meanwhile if you only list one DNS server in the admin panel? (to one that's up)
> 
> /cc @DentonGentry

Yes, It works on PC. But never got DNS resolution on android working.

**Comment by jesb1n** [comment] 2022-01-26 05:44
https://forum.tailscale.com/t/cname-aliases-to-magicdns-dont-seem-to-work-on-android/1584/5

**Comment by jesb1n** [comment] 2022-01-26 05:45
https://forum.tailscale.com/t/android-issue-tailscale-vpn-no-longer-setting-dns-on-google-pixel-5/659

**Comment by DentonGentry** [comment] 2022-01-26 05:49
You're linking to every forum issue mentioning Android DNS?

**Comment by jesb1n** [comment] 2022-01-26 05:51
I am having  similar issues as mentioned in those,
1. never got magic DNS working on my android.
2. never got local DNS resolution working on my android.

**Comment by DentonGentry** [comment] 2022-01-26 05:55
If Android DNS has never worked with Tailscale at all on your device: do you have Private DNS set to "On"?

https://github.com/tailscale/tailscale/issues/915 has a description: Android sets a StrictMode filter that requires DNS-over-TLS, but we haven't had a way to issue a certificate for 100.100.100.100 so couldn't make it work.

**Comment by jesb1n** [comment] 2022-01-26 05:57
![Screenshot_20220126-112642~2](https://user-images.githubusercontent.com/52061387/151111289-fe8acaf9-d8b2-4d4e-bd1a-8c327691bcdb.png)

**Comment by DentonGentry** [comment] 2022-01-26 06:17
When it was set to something.cloudflare-gateway.com with Private DNS on, it was probably not working because the Tailscale DNS config tried to set a DNS server which didn't work with Private DNS https://github.com/tailscale/tailscale/issues/915.

After turning the Private DNS off but having two DNS servers where one was off, it was likely failing due to the explanation in the initial report. Android appears to be trying them in order. We can address this later by using 100.100.100.100 instead.

With just the one functioning DNS server, DNS is still broken? Please do some DNS lookups using the device and send another bug report.

**Comment by jesb1n** [comment] 2022-01-26 06:58
* Private DNS: off
* Global nameservers : 100.111.205.93

still,
This site can’t be reached.
Check if there is a typo in pihole.....
DNS_PROBE_FINISHED_NXDOMAIN

Bug report:
BUG-dc4ba901ab3b5360d03e50007754fbe45570bec63755543f48ed986a0d6499d1-20220126065745Z-5ac530fb1dfe7625

**Comment by DentonGentry** [comment] 2022-01-26 07:06
Right before the bug report we see what looks like normal DNS activity, sending queries and receiving responses:

```
2022-01-26 06:57:36.732663035 +0000 UTC: 11.7M/198.9M Accept: UDP{100.102.127.59:50741 > 100.111.205.93:53} 65 ok out
2022-01-26 06:57:36.735022458 +0000 UTC: 11.8M/198.9M Accept: UDP{100.102.127.59:2023 > 100.111.205.93:53} 65 ok out
2022-01-26 06:57:36.971160943 +0000 UTC: 11.7M/198.9M Accept: UDP{100.111.205.93:53 > 100.102.127.59:50741} 202 cached
```

The symptom you see is DNS_PROBE_FINISHED_NXDOMAIN in Chrome?

**Comment by jesb1n** [comment] 2022-01-26 07:11
yes.

**Comment by jesb1n** [comment] 2022-01-26 07:21
Finally got it working with one DNS server on android. chrome browser has a its own secure DNS settings, once I turned it off, the site started working. Thanks you ♥.

**Comment by DentonGentry** [comment] 2022-01-26 07:44
Reopening because we should still consider whether to set 100.100.100.100 and let it arbitrate between upstreams.

**Comment by DentonGentry** [comment] 2022-03-27 05:43
The remaining symptom is a duplicate of https://github.com/tailscale/tailscale/issues/2285

**Closed by DentonGentry** 2022-03-27 05:43 UTC
Labels: OS-android, L2 Few, P1 Nuisance, T3 Performance/Debugging, dns
