### ISSUE TITLE
Tunnelbear breaks Tailscale's DNS configuration on macOS

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#2000] opened 2021-05-27 21:36 UTC
Reported by a user. Their only configuration is to enable MagicDNS. As a result of that, we push into the OS a split-DNS config to capture the MagicDNS domain name. However, their scutil --dns output shows that this _somehow_ translates to macOS sending _all_ DNS traffic to the machine's Tailscale IP address. Our match domains and other configuration is nowhere to be found. Nothing in the Tailscale code _ever_ sends DNS requests to a machine's tailscale IP by itself, so something very, very broken is going on here somehow.

**Comment by fforootd** [comment] 2021-05-27 21:47
The behaviour was as follows:

## First Try

- Installed Tailscale on macOS 11.4
- Enabled MagicDNS and Set Public DNS Server
- Logged in on Mac
- Connected the Mac

**Result**: DNS resolution totally broken on this machine

## Second Try

- Disabled MagicDNS
- Rebooted the machine
- Connected the Mac

**Result**: DNS resolution works fine

## Third Try

- Enabled MagicDNS and Set Public DNS Server
- Rebooted the machine
- Connected the Mac

**Result**: DNS resolution works fine

**Comment by danderson** [comment] 2021-05-27 23:24
Hmm, very strange. I wonder how I can test that, my dev mac definitely has a lot of tailscale installed right now...

On your first try, were you already on macOS 11.4? Or was it 11.3.x? Maybe something changed in the latest update, I haven't installed it yet.

**Comment by poswald** [comment] 2021-05-28 00:20
I was just coming here to report a DNS issue and I saw this which seems pretty similar to what I'm seeing. I originally reported issues in issue #1647 which was later being tracked in #1713 and I thought fixed in version 1.8.x of tailscale. I upgraded my whole network and everything seemed great for a while. However, now I am starting to see issues again where DNS resolution in a browser gets hung up until I disconnect tailscale at which point it loads a page easily.

My Mac is on 1.8.5 now. I have MagicDNS enabled, and one exit node on the network which I am not currently set to use.

I am not 100% sure but I feel like it was working after I initially upgraded to 1.8.x branch and then broke sometime after. It's possible that it only stopped working after I rebooted? or perhaps after a point release? My memory of what happened when is fuzzy.

Here's the difference of what I see when it is enable vs. disabled when the issue is happening while enabled:
```
synthetica:Projects poswald $ scutil --dns > enabled.dns
synthetica:Projects poswald $ scutil --dns > disabled.dns
synthetica:Projects poswald $ diff enabled.dns disabled.dns
4,11d3
<   search domain[0] : pauloswald.gmail.com.beta.tailscale.net
<   nameserver[0] : 100.100.100.100
<   if_index : 17 (utun2)
<   flags    : Supplemental, Request A records, Request AAAA records
<   reach    : 0x00000003 (Reachable,Transient Connection)
<   order    : 101000
<
< resolver #2
16,24d7
<   order    : 200000
<
< resolver #3
<   domain   : pauloswald.gmail.com.beta.tailscale.net.
<   nameserver[0] : 100.100.100.100
<   if_index : 17 (utun2)
<   flags    : Supplemental, Request A records, Request AAAA records
<   reach    : 0x00000003 (Reachable,Transient Connection)
<   order    : 101001
26c9
< resolver #4
---
> resolver #2
34c17
< resolver #5
---
> resolver #3
42c25
< resolver #6
---
> resolver #4
50c33
< resolver #7
---
> resolver #5
58c41
< resolver #8
---
> resolver #6
66c49
< resolver #9
---
> resolver #7
87,93d69
<
< resolver #3
<   search domain[0] : pauloswald.gmail.com.beta.tailscale.net
<   nameserver[0] : 100.100.100.100
<   if_index : 17 (utun2)
<   flags    : Scoped, Request A records, Request AAAA records
<   reach    : 0x00000003 (Reachable,Transient Connection)
```

**Comment by danderson** [comment] 2021-05-28 00:22
That config diff looks fine and mostly expected, so if you're having DNS issues it would be something other than this, afaict.

**Comment by poswald** [comment] 2021-05-28 00:30
Yeah I thought so too... Let me know if you have any ideas of what to look for to get better debugging output for you.

**Comment by danderson** [comment] 2021-05-28 00:53
If you can open a new bug, that'd be great, with a description of how things seem to break, how you configured your DNS in the admin panel (i.e. what configuration you're trying to set) and the tailscale IP of the device in question, I can poke at our debug logs and see if anything stands out. Or you can write in to support@tailscale.com if you'd rather do the initial triage off-github - cc danderson@tailscale.com so I can grab it out of the general support queue.

**Comment by danderson** [comment] 2021-05-29 01:01
Update: turns out this is because of Tunnelbear. Somehow, their software completely mangles Tailscale's DNS configuration on shutdown, even though it doesn't own that interface at all.

Bluntly, this reduces the priority a bit, because a fix is probably going to involve asking Tunnelbear to stop doing whatever it is they're doing to our configuration.

**Comment by zenyui** [comment] 2022-07-20 16:45
**Temporary workaround:** Tailscale and normal DNS seem to work fine if you fully quit Tunnelbear and reboot Mac.

**Comment by DentonGentry** [comment] 2023-02-12 15:24
Also relevant: https://github.com/tailscale/tailscale/issues/2231

**Comment by wolever** [comment] 2023-03-13 05:45
In case it's helpful to anyone who stumbles across this issue, here's what I experienced:
* On a clean boot: when Tailscale connects, it sets `nameserver 100.100.100.100` in `/etc/resolv.conf`, and everything works as expected.
* After using TunnelBear (connecting, disconnecting, quitting): when Tailscale connects, it sets `nameserver 100.123.176.1` in `/etc/resolv.conf`, but while this address is routable, requests (dns, ping) don't receive a response, so DNS does not work.

And it can be "fixed" by manually overriding the DNS server:

```
$ networksetup -setdnsservers "Tailscale Tunnel" 100.100.100.100
```

**Comment by kainosnoema** [comment] 2023-03-13 21:40
Also ran into this issue. @wolever's suggestion fixed it for me as well. Can also just ensure that TunnelBear doesn't start on boot, then do a clean reboot and Tailscale's interface seems to be fixed.

**Comment by fortran01** [comment] 2023-03-22 19:32
@wolever's manual approach works but it reverts back to the wrong DNS server when you switch to an exit node for example.

**Comment by agottardo** [comment] 2024-09-24 17:37
Closing this stale issue as we have no control over what TunnelBear does with DNS settings. If you're still experiencing this issue, please contact TunnelBear as this appears to be happening on their end.

**Closed by agottardo** 2024-09-24 17:37 UTC
Labels: L1 Very few, P2 Aggravating, T5 Usability, dns, vpn-interop
