### ISSUE TITLE
Getting `failed to lookup user from userid` error on Windows connected to Active Directory.

### ISSUE THREAD

**Issue by abdusco** [tailscale/tailscale#2177] opened 2021-06-19 07:06 UTC
I'm trying to run Tailscale on a Windows machine connected to company domain. When it's connected to the company VPN, Tailscale starts without errors, and I'm able to connect to Tailscale network.

But if it's not connected to company VPN, Tailscale fails with this error:

```
---------------------------
Tailscale Error
---------------------------
Tailscale backend error:

failed to look up user from userid: The trust relationship between this workstation and the primary domain failed.
---------------------------
OK   
---------------------------
```

Am I doing something wrong? How can I bypass user lookup and get rid of this error?

https://github.com/tailscale/tailscale/blob/297b3d6fa438c6953c5a032c7d6ae2f2c6bd4eb1/ipn/ipnserver/server.go#L174

![image](https://user-images.githubusercontent.com/3243482/122634244-bbb19e00-d0e5-11eb-8540-d664f6444f67.png)

---
```
Tailscale Version 1.8.7 (te1571ed7e-g2f595b1b6)
Windows 10.0.21318 Build 21318
```

**Comment by DentonGentry** [comment] 2021-06-19 07:10
There is a second VPN product installed on the computer? I don't understand from the description: Tailscale gets a backend error when the other VPN is connected, or when the other VPN is not connected?

**Comment by abdusco** [comment] 2021-06-19 07:30
@DentonGentry Yes, there's a second VPN that lets me connect to company network. I'm getting an error only when the PC is connected to company VPN.

**Comment by abdusco** [comment] 2021-06-19 07:51
Here are the logs from `tailscale-ipn.exe`:

```
PS C:\Program Files (x86)\Tailscale IPN> .\tailscale-ipn.exe
PS C:\Program Files (x86)\Tailscale IPN> logtail started
Program starting: v1.8.7-te1571ed7e-g2f595b1b6, Go 1.16.4-ts1b677aa: []string{"C:\\Program Files (x86)\\Tailscale IPN\\tailscale-ipn.exe"}
LogID: 9f94f1660fc148f24815f9ca678b36fa67dee2b0ea24387c63b3c55632b3f79a
logpolicy: using system state directory "C:\\Users\\923044\\AppData\\Local\\Tailscale"
stdout ok.
stderr ok.
log ok.
Running UI client...
ui: creating mainWindow
ui: creating tray
logtail: dialed "log.tailscale.io:443" in 265ms
ui: latest version check: "1.8.7", <nil>
backend error: failed to look up user from userid: The trust relationship between this workstation and the primary domain failed.
```

**Comment by DentonGentry** [comment] 2021-06-19 13:16
The error comes from https://github.com/tailscale/tailscale/blob/ad288baaeab55e16cc43f7dadbadaa0303b92c52/ipn/ipnserver/server.go#L174

In this case, it happens because the DB of users for the workstation resides in Active Directory, but Active Directory cannot be reached because the corporate network is not connected.

Tailscale only looks up the user during initialization. If the corp VPN is connected and Tailscale is able to look up the userid, it never needs to do so again. Disconnecting the corporate VPN after that point doesn't impact it.

In general we can't support having multiple VPN products on a device. Having a remote Active Directory is just one example, VPN products also tend to fight over routing table entries and nameserver configuration.

**Comment by DentonGentry** [comment] 2021-06-20 00:28
As the root cause is due to the interaction of multiple VPNs, going to close this now.

**Closed by DentonGentry** 2021-06-20 00:28 UTC
Labels: L2 Few, OS-windows, P2 Aggravating, T5 Usability
