### ISSUE TITLE
Add device names behind a relay node to integrated DNS via ARP/neighbour discovery

### ISSUE THREAD

**Issue by renne** [tailscale/tailscale#1867] opened 2021-05-06 16:44 UTC
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I manually have to add hostnames of different VPN locations to  the DNS configuration.

**Describe the solution you'd like**

A Tailscale relay node should listen to ARP/neighbour discovery messages and add hostname/IP-address tuples to the internal DNS system of Tailscale.

**Describe alternatives you've considered**
1. Using DynDNS on each host (a lot of embedded and multimedia hosts do not support DynDNS)
2. Deploying a network-scanner-script on each relay node (no task for John-Does)

**Comment by DentonGentry** [comment] 2021-06-05 14:43
Duplicate of https://github.com/tailscale/tailscale/issues/1482

**Closed by DentonGentry** 2021-06-05 14:43 UTC
Labels: L1 Some users, P1 Nuisance, T2 Visual Polish
