### ISSUE TITLE
Using K8s secret state backend sets TailscaleVarRoot to null

### ISSUE THREAD

**Issue by devinbedari** [tailscale/tailscale#5411] opened 2022-08-22 02:58 UTC
### What is the issue?

Passing just:
```sh
--state=...
```
to `tailscaled` without a `---statedir` results in `TailscaleVarRoot` being set to `null`. This seems to break a subset of tailscale cli commands:
```sh
$ tailscale --socket=<socket_file_location> cert ...
500 Internal Server Error: failed to get cert dir 
```
With the corresponding entry in the `tailscaled` logs:
```sh
YYYY/MM/DD HH:MM:SS certDir: no TailscaleVarRoot
```
My only use case is the cert feature. I'm unsure about which other features are broken too, but the logs seem to suggest taildrop too? 
```sh
YYYY/MM/DD HH:MM:SS Taildrop disabled; no state directory
```

### Steps to reproduce

1. Run `tailscaled` with just `--state=mem:`
3. Run `tailscale cert`
```sh
$ tailscale cert <any_domain_really>
```
I had this issue as well using a kubernetes secret as the state backend. If the plan is to not support having pods run commnads like `tailscale cert`, then it would be nice if that were documented somewhere.

### Are there any recent changes that introduced the issue?

N/A

### OS

Linux, Windows

### OS version

Windows 10/Ubuntu 22.04 LTS

### Tailscale version

1.28.0

### Bug report

BUG-5d3ab6c28e90e40c248b4f01cb820c8ed5c3fb017c78fa14e297428aa010329d-20220822025815Z-78f5c0268ced5b70

**Comment by devinbedari** [comment] 2022-08-22 03:04
fwiw, I've been overriding `run,sh` to set both `--state=kube:...` and `--statedir=...` and just discarding the temp data, since I'm going to try to use ephemeral keys. So i replace [this](https://github.com/tailscale/tailscale/blob/main/docs/k8s/run.sh#L27) with this:
```
    if [[ ! -z "${KUBERNETES_SERVICE_HOST}" ]]; then
      TAILSCALED_ARGS="${TAILSCALED_ARGS} --state=kube:${TS_KUBE_SECRET}"
    fi

    if [[ ! -z "${TS_STATE_DIR}" ]]; then
      TAILSCALED_ARGS="${TAILSCALED_ARGS} --statedir=${TS_STATE_DIR}"
    else
      TAILSCALED_ARGS="${TAILSCALED_ARGS} --state=mem:"
    fi
```
It works fine, but that means I have to regen my certs every time I restart my container instead of relying on them just being saved in the secret.

**Comment by DentonGentry** [comment] 2022-08-28 00:17
Duplicate of https://github.com/tailscale/tailscale/issues/3974

**Closed by DentonGentry** 2022-08-28 00:17 UTC
Labels: needs-triage, bug
