### ISSUE TITLE
Can't connect to mullvad exit node on windows 11

### ISSUE THREAD

**Issue by des0lat10n** [tailscale/tailscale#13864] opened 2024-10-20 06:19 UTC
### What is the issue?

When I go to tray to connect to a mullvad node, the dropdown doesn't appear.
![image](https://github.com/user-attachments/assets/dbc1e393-0b1f-4822-9f75-ce1cf5b1a642)

### Steps to reproduce

Literally anything. Open the program. Reinstall it. It does it no matter what for me and support hasn't answered back.

### Are there any recent changes that introduced the issue?

The last update lol.

### OS

Windows

### OS version

11

### Tailscale version

Latest (1.76.1)

### Other software

Nothing that would tamper with my network and interfere with tailscale.

### Bug report

BUG-8114d3d7c7450ac49e6be74667e175af190e07611a49c7cefef5852a6d91d703-20241020061903Z-bf0e73a0ec1fb95f

**Comment by kelivel** [comment] 2024-10-20 13:21
Hi @des0lat10n, this is a duplicate of the tracking but we've filed over at https://github.com/tailscale/tailscale/issues/13845. I'll go ahead and close this one, but please keep an eye on #13845 and we'll post an update as soon as we have one!

In the meantime, you can two one of two things:

* Downgrade to stable 1.74.0 at https://pkgs.tailscale.com/stable/?v=1.74.0#windows
* Connect via cmd.exe: `tailscale exit-node-list`, find the exit node you want to use (I'll use NYC for example), then run `tailscale set --exit-node=us-nyc-wg-301.mullvad.ts.net`.

**Closed by kelivel** 2024-10-20 13:21 UTC
Labels: needs-triage, bug
