### ISSUE TITLE
-

### ISSUE THREAD

**Issue by gh67uyyghj** [tailscale/tailscale#217] opened 2020-03-25 09:42 UTC
How do you guys manage to do such an extensive astroturfing on HN? I knew that DDG had insiders and do organized upvoting for their posts. But I've never seen anything like you're doing, people pay hundreds of thousands for less effective advertising. I am really stunned, especially with a low quality project like yours can milk HN so much.

**Comment by crawshaw** [comment] 2020-03-25 09:53
The original title of this issue did not meet the project's code of conduct, so I have removed it.

The content of this issue is not productive. It is not a bug report or a feature request. So I am closing it.

**Closed by crawshaw** 2020-03-25 09:53 UTC

**Comment by gh67uyyghj** [comment] 2020-03-25 10:06
answer the question. How do you corrupt people manage to do such an organized and extensive shilling party for Tailscale on HN on a daily basis?
