### ISSUE TITLE
Override local DNS not working in Android 9 due to automatically enabling Private DNS

### ISSUE THREAD

**Issue by tboby** [tailscale/tailscale#5239] opened 2022-07-30 18:40 UTC
### What is the issue?

I have a private DNS server which provides tailscale clients with the correct IP for reaching web services through a dedicated docker network. I use subnet routing + a global nameserver set to override local dns which should force tailscale clients to use the private DNS server when connected to tailscale.

On one android device this works fine, on another it does not. "Network analyzer" shows that the DNS server is set for the VPN, but even with Always On VPN the "Cell" DNS server is taking precedence. As my domain name resolves to a different IP publicly, this breaks the VPN. Manually querying the DNS server works fine.

The working android device is a Pixel 3a, Android 12.

The non-working android device is an Xperia XA2, Android 9.

### Steps to reproduce

1. Create DNS server with IP 10.0.5.101, and dnsmasq address=/.example.domain/10.0.5.100
2. Create web server with IP 10.0.5.100
1. Add server to tailscale
3. Add subnet routing (10.0.5.0/24)
4. Set global nameserver 10.0.5.101
5. Set override local DNS
6. Add Android device 1, enable tailscale
7. Add Android device 2, enable tailscale
8. Browse to example.domain

Expected:
DNS resolves through 10.0.5.101 on both devices.

Actual:
DNS resolves through 10.0.5.101 on one device, but not on the other.

### OS

Android

### OS version

9, 12

### Tailscale version

1.28.0

### Bug report

BUG-b790abe27639fe2eed5bd274cf71d2835470371b67df813d1b62b3d89211e8cd-20220730182751Z-2de2011cf3ae4a94

**Comment by DentonGentry** [comment] 2022-07-30 18:56
Near `BUG-b790abe27639fe2eed5bd274cf71d2835470371b67df813d1b62b3d89211e8cd-20220730182751Z-2de2011cf3ae4a94`:

`2022-07-30 18:27:24.523607645 +0000 UTC: 15.8M/118.2M tstun: [unexpected] received self disco out packet over tstun; dropping`
which might be unrelated but is weird.

--------

We do see the DNS server IP address being pushed as expected, but most of the time it is not setting any SearchDomains:
```
2022-07-30 18:22:04.989683653 +0000 UTC: 18.6M/118.8M dns: Resolvercfg: {Routes:{} Hosts:3 LocalDomains:[]}
2022-07-30 18:22:04.990094746 +0000 UTC: 18.6M/118.8M dns: OScfg: {Nameservers:[10.0.5.101] SearchDomains:[] MatchDomains:[]}
2022-07-30 18:23:51.385218612 +0000 UTC: 16.6M/118.8M dns: Set: {DefaultResolvers:[10.0.5.101] Routes:{} SearchDomains:[] Hosts:3}
```

I only see one instance of setting a search domain, about half an hour before the bug was filed:
```
2022-07-30 18:14:29.472770919 +0000 UTC: 19.8M/118.8M dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
2022-07-30 18:14:30.629528992 +0000 UTC: 20.2M/118.8M dns: Set: {DefaultResolvers:[10.0.5.101] Routes:{beta.tailscale.net.:[] REDACTED.beta.tailscale.net.:[] ts.net.:[]}+65arpa SearchDomains:[REDACTED.beta.tailscale.net.] Hosts:N}
2022-07-30 18:14:30.63698045 +0000 UTC: 20.2M/118.8M dns: Resolvercfg: {Routes:{.:[10.0.5.101]} Hosts:N LocalDomains:[beta.tailscale.net. REDACTED.beta.tailscale.net. ts.net.]+65arpa}
```

Was MagicDNS toggled on or off about half an hour before filing this?

**Comment by tboby** [comment] 2022-07-30 19:00
I tried turning MagicDNS on and off again as a last resort as many similar sounding issues referred to it as being related.

I've just turned on the failing client to check again if that's any use: still not overwriting, but can still manually query the 10.0.5.101 DNS server.

**Comment by DentonGentry** [comment] 2022-07-30 19:03
Right offhand I don't see why the DNS server isn't being set on the Android 9 device. We see the config being pushed, the `Nameservers:[10.0.5.101]` should do it.

If you are comfortable using ADB, connecting a cable to it and running `adb logcat` while toggling the Tailscale VPN off and back on may turn up an error or traceback which isn't being reported to us as an error.

**Comment by tboby** [comment] 2022-07-30 19:03
If I compare the info page of "Network Analyzer", the only significant difference I can see is that the working device says "Connection Type VPN" and the other "Cell" even though both have a "VPN" section. To my knowledge it's not possible to influence this as a user.

I'll give ADB a try.

**Comment by tboby** [comment] 2022-07-30 19:35
```
07-30 20:09:42.510  1727  3144 D Vpn     : setting state=CONNECTING, reason=establish
07-30 20:09:42.510  1727  1993 I EthernetTracker: maybeTrackInterface tun0
07-30 20:09:42.511  1727  1797 I EthernetTracker: interfaceLinkStateChanged, iface: tun0, up: false
07-30 20:09:42.512  1727  1797 I EthernetTracker: interfaceLinkStateChanged, iface: tun0, up: true
07-30 20:09:42.516  1727  3144 D ConnectivityService: registerNetworkAgent NetworkAgentInfo{ ni{[type: VPN[], state: CONNECTING/CONNECTING, reason: (unspecified), extra: (none), failover: false, available: false, roaming: false]}  network{106}  nethandle{458672230413}  lp{{InterfaceName: tun0 LinkAddresses: [100.110.175.65/32,fd7a:115c:a1e0:ab12:4843:cd96:626e:af41/128,]  Routes: [10.0.5.0/24 -> 0.0.0.0 tun0,100.90.205.126/32 -> 0.0.0.0 tun0,100.120.42.93/32 -> 0.0.0.0 tun0,fd7a:115c:a1e0::/48 -> :: tun0,100.100.100.100/32 -> 0.0.0.0 tun0,100.110.175.65/32 -> 0.0.0.0 tun0,fd7a:115c:a1e0:ab12:4843:cd96:626e:af41/128 -> :: tun0,] DnsAddresses: [10.0.5.101,] UsePrivateDns: false PrivateDnsServerName: null Domains:  MTU: 0}}  nc{[ Transports: VPN Capabilities: NOT_RESTRICTED&TRUSTED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED Unwanted:  Uids: <{0-99999}> EstablishingAppUid: 10177]}  Score{101}  everValidated{false}  lastValidated{false}  created{false} lingering{false} explicitlySelected{false} acceptUnval...
07-30 20:09:42.513  1727  1797 I chatty  : uid=1000(system) android.fg identical 1 line
07-30 20:09:42.514  1727  1797 I EthernetTracker: interfaceLinkStateChanged, iface: tun0, up: true
07-30 20:09:42.516  1727  3144 D Vpn     : setting state=CONNECTED, reason=agentConnect
07-30 20:09:42.516  1727  3144 I Vpn     : Established by com.tailscale.ipn on tun0
07-30 20:09:42.516  1727  1974 D ConnectivityService: NetworkAgentInfo [VPN () - 106] EVENT_NETWORK_INFO_CHANGED, going from null to CONNECTING
07-30 20:09:42.524   736   759 I Netd    : Destroyed 7 sockets for UidRanges{ 0-99999 } skip={1016 10177} in 1.0 ms
07-30 20:09:42.525  2597 14876 V NativeCrypto: Read error: ssl=0x7837274e48: I/O error during system call, Software caused connection abort
07-30 20:09:42.526  4690 17271 W fbservices:MqttClient: connection/disconnecting; reason=READ_SOCKET, operation=NETWORK_THREAD_LOOP
07-30 20:09:42.526  4690 17271 W System.err: DEBUG: com.whatsapp.net.logging.a.a(WtLog.java:16) : Sending Alert : type : WARNING description : close_notify(0) exception :
07-30 20:09:42.527  1727  1974 D ConnectivityService: NetworkAgentInfo [VPN () - 106] EVENT_NETWORK_INFO_CHANGED, going from CONNECTING to CONNECTED
07-30 20:09:42.527  4690 17271 W System.err: ERROR: com.whatsapp.net.logging.a.a(WtLog.java:10) : Encountered exception. Nothing much can be done here. com.whatsapp.net.alerts.WtAlertException
07-30 20:09:42.527  1727  1974 W DnsManager: updatePrivateDns(106, PrivateDnsConfig{false:/[]})
07-30 20:09:42.527  1727  1974 D ConnectivityService: Setting DNS servers for network 106 to [/10.0.5.101]
07-30 20:09:42.527  1727  1974 D DnsManager: setDnsConfigurationForNetwork(106, [10.0.5.101], [], [1800, 25, 8, 64], , [])
07-30 20:09:42.529  1727  1974 D ConnectivityService: Adding iface tun0 to network 106
07-30 20:09:42.534  2597 17404 V NativeCrypto: SSL shutdown failed: ssl=0x7837274e48: I/O error during system call, Broken pipe
07-30 20:09:42.536  2597 17404 E WakeLock: GCM_HB_ALARM release without a matched acquire!
07-30 20:09:42.536  2597 17404 W WakeLock: GCM_HB_ALARM counter does not exist
07-30 20:09:42.547  2597 17404 E WakeLock: GCM_CONN_ALARM release without a matched acquire!
07-30 20:09:42.547  2597 17404 W WakeLock: GCM_CONN_ALARM counter does not exist
07-30 20:09:42.549 17431 17447 I com.tailscale.ipn: 19.1M/109.4M control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
07-30 20:09:42.556  2597  2597 D CloudSync: gcm disconnected, disabling cloud route.
07-30 20:09:42.560  1727  1974 D ConnectivityService: Setting DNS servers for network 106 to [/10.0.5.101]
07-30 20:09:42.560  1727  1974 D DnsManager: setDnsConfigurationForNetwork(106, [10.0.5.101], [], [1800, 25, 8, 64], , [])
07-30 20:09:42.581 17431 17447 I com.tailscale.ipn: 19.0M/109.4M magicsock: adding connection to derp-8 for [wUG+V]
07-30 20:09:42.581 17431 17447 I com.tailscale.ipn: 19.0M/109.4M magicsock: 2 active derp conns: derp-4=cr117ms,wr117ms derp-8=cr0s,wr0s
07-30 20:09:42.582 17431 17449 I com.tailscale.ipn: 19.1M/109.4M derphttp.Client.Recv: connecting to derp-8 (lhr)
07-30 20:09:42.588 17431 17484 I com.tailscale.ipn: 19.1M/109.4M tstun: [unexpected] received self disco out packet over tstun; dropping
07-30 20:09:42.592  4690 17518 W System.err: INFO: com.whatsapp.net.logging.a.a(WtLog.java:10) : Start handshake.
07-30 20:09:42.602  1727  1974 D ConnectivityService: Sending CONNECTED broadcast for type 17 NetworkAgentInfo [VPN () - 106] isDefaultNetwork=false
07-30 20:09:42.603  1727 17517 D NetworkMonitor/NetworkAgentInfo [VPN () - 106]: Network would not satisfy default request, resolving private DNS
07-30 20:09:42.607  1727  3749 V LocSvc_HIDL_Subscription_jni: networkinfo_update
07-30 20:09:42.607  1727  3749 V LocSvc_HIDL_Subscription_jni: [networkinfo_update][325] [HC] =>> [HS]
07-30 20:09:42.608   805   805 V LocSvc_HIDL_IzatSubscription: [networkinfoUpdate][321] [HS] <<<<= [HC]
07-30 20:09:42.609  1727  3749 V LocSvc_HIDL_Subscription_jni: Exit Result 0
07-30 20:09:42.609  1727  1974 D ConnectivityService: reportNetworkConnectivity(103, false) by 10056
07-30 20:09:42.621  1727  1974 D ConnectivityService: NetworkAgentInfo [VPN () - 106] validation passed
07-30 20:09:42.621  1727 15349 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 103]: Forcing reevaluation for UID 10056
07-30 20:09:42.626 17431 17445 I com.tailscale.ipn: 19.3M/109.4M magicsock: home is now derp-8 (lhr)
07-30 20:09:42.629 17431 17447 I com.tailscale.ipn: 19.3M/109.4M control: NetInfo: NetInfo{varies=false hairpin=false ipv6=false udp=true derp=#8 portmap= link=""}
07-30 20:09:42.631  1727 17520 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 103]: PROBE_DNS www.google.com 5ms OK 216.239.38.120
07-30 20:09:42.638  1727 17521 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 103]: PROBE_DNS connectivitycheck.gstatic.com 3ms OK 142.250.178.3
07-30 20:09:42.642  4690 17518 W System.err: INFO: com.whatsapp.net.logging.a.a(WtLog.java:10) : Handshake complete : session_resumed true early_data_sent false early_data_accepted false client_cert_requested false time_ms 50
07-30 20:09:42.645  2597  7136 I NearbyDiscovery: FastPairHandler: Received action android.net.conn.CONNECTIVITY_CHANGE [CONTEXT service_id=49 ]
07-30 20:09:42.645 10881 10881 I a.a.d.a.m.p.MainPresent: setDeviceConnectivity: ConnectivityInfo{type=MOBILE, state=CONNECTED}
07-30 20:09:42.645 10881 10881 I aghd    : setDeviceConnectivity: ConnectivityInfo{type=MOBILE, state=CONNECTED}
```

There were no obvious errors related to tailscale or networking other than interrupted connections when it was enabled/disabled.

The bunch of logs from tailscale when the vpn was enable looked fine, and seemed to send the right dns server. From my completely naive analysis it looks like the android network manager is rejecting the VPN network for something to do with private dns, even though that feature is disabled...

**Comment by DentonGentry** [comment] 2022-07-31 14:11
In Android-9 NetworkMonitor.java prints `Network would not satisfy default request, resolving private DNS` if NetworkMonitorUtils.java:isPrivateDnsValidationRequired() returns true.

In Android-9 I think this is:

```
    /**
     * Return whether validation is required for private DNS in strict mode.
     * @param nc Network capabilities of the network to test.
     */
    public static boolean isPrivateDnsValidationRequired(NetworkCapabilities nc) {
        // TODO: Consider requiring validation for DUN networks.
        return nc != null
                && nc.hasCapability(NET_CAPABILITY_INTERNET)
                && nc.hasCapability(NET_CAPABILITY_NOT_RESTRICTED)
                && nc.hasCapability(NET_CAPABILITY_TRUSTED);
    }
```

**Comment by watermelonpizza** [comment] 2022-09-05 11:23
I am recieving a potentially similar issue on my Android 12 phone. The DNS is always set to 100.100.100.100 (as reported by [the Network Analyzer app](https://play.google.com/store/apps/details?id=net.techet.netanalyzerlite.an&gl=US), not sure how reliable that is however) even if I have override local DNS set to on in the DNS page.

Bug report `BUG-3a03dcb4b6c5a30ec1830dae90a0472ddc81fdb35ff8871f6638a673fccd1ee2-20220905110955Z-4ec11ba799664fc6`

I have a global nameserver set to one of my devices in my tailnet which is a pihole and other machines pick up on the `override local DNS` setting just fine, however, my Android device isn't resolving any domains unless I'm on the Wi-Fi but that might be because it's using the DHCP DNS set server (my DHCP DNS is set to a local 10.x address not a tailscale address)?

**Comment by DentonGentry** [comment] 2022-09-14 02:18
@watermelonpizza The implementation of DNS support varies by platform:
- On Windows and Linux with systemd-resolved, the global DNS resolvers with "Override local DNS" can often be set as the platform's DNS resolvers with any SplitDNS or MagicDNS domains set up separately
- on macOS and iOS depending on how many SplitDNS domains or other factors are used, the global DNS resolvers might be set in the platform or it might need to use the 100.100.100.100 resolver
- Linux using /etc/resolv.conf or other DNS implementations use 100.100.100.100
- Android has no ability to set a resolver per domain. It always uses 100.100.100.100.

If your observation is that the Android device uses 100.100.100.100, that is normal.

If you have something else to be looked at, please file a new bug. This issue is about Android 9 and `Network would not satisfy default request, resolving private DNS`

**Comment by DentonGentry** [comment] 2023-06-03 19:14
I believe https://github.com/tailscale/tailscale/issues/915 is the root cause and the issue to be solved for this to work.

Duplicate of https://github.com/tailscale/tailscale/issues/915

**Closed by DentonGentry** 2023-06-03 19:14 UTC
Labels: OS-android, L1 Very few, P2 Aggravating, T5 Usability, bug
