### ISSUE TITLE
k8s-operator certificates not being persistently stored

### ISSUE THREAD

**Issue by uhthomas** [tailscale/tailscale#7685] opened 2023-03-24 18:55 UTC
### What is the issue?

I can no longer connect to the apiserver with the operator. Not sure how this is possible given the image (`tailscale/k8s-operator:unstable-v1.37.260`) didn't change. The load balancer services are okay, though.

```
operator-657745db9c-vsfg5 operator 2023/03/24 18:49:58 http: TLS handshake error from 100.119.63.109:59146: Get "http://local-tailscaled.sock/localapi/v0/cert/tailscale-operator.tailnet-fbec.ts.net?type=pair": context deadline exceeded
operator-657745db9c-vsfg5 operator 2023/03/24 18:50:08 http: TLS handshake error from 100.119.63.109:43138: Get "http://local-tailscaled.sock/localapi/v0/cert/tailscale-operator.tailnet-fbec.ts.net?type=pair": context deadline exceeded
operator-657745db9c-vsfg5 operator 2023/03/24 18:50:18 http: TLS handshake error from 100.119.63.109:43580: Get "http://local-tailscaled.sock/localapi/v0/cert/tailscale-operator.tailnet-fbec.ts.net?type=pair": context deadline exceeded
operator-657745db9c-vsfg5 operator 2023/03/24 18:50:28 http: TLS handshake error from 100.119.63.109:33952: Get "http://local-tailscaled.sock/localapi/v0/cert/tailscale-operator.tailnet-fbec.ts.net?type=pair": context deadline exceeded
```

### OS

Linux, Other

### OS version

Kubernetes 1.26.2

### Tailscale version

ailscale/k8s-operator:unstable-v1.37.260

**Comment by uhthomas** [comment] 2023-03-24 19:21
Sorry, I should have been clearer in the original issue. This means the apiserver proxy is not working. Strangely, it is connected and will communicate.

```
❯ tailscale ping tailscale-operator-unwind
pong from tailscale-operator-unwind (100.119.53.112) via DERP(lhr) in 45ms
pong from tailscale-operator-unwind (100.119.53.112) via DERP(lhr) in 36ms
pong from tailscale-operator-unwind (100.119.53.112) via DERP(lhr) in 32ms
pong from tailscale-operator-unwind (100.119.53.112) via 192.168.1.28:32605 in 1ms
❯ tailscale configure kubeconfig tailscale-operator-unwind
kubeconfig configured for "tailscale-operator-unwind"
❯ k get no
E0324 19:20:32.286014  966426 memcache.go:265] couldn't get current server API group list: Get "https://tailscale-operator-unwind.tailnet-fbec.ts.net/api?timeout=32s": net/http: TLS handshake timeout
E0324 19:20:42.288241  966426 memcache.go:265] couldn't get current server API group list: Get "https://tailscale-operator-unwind.tailnet-fbec.ts.net/api?timeout=32s": net/http: TLS handshake timeout
E0324 19:20:52.290487  966426 memcache.go:265] couldn't get current server API group list: Get "https://tailscale-operator-unwind.tailnet-fbec.ts.net/api?timeout=32s": net/http: TLS handshake timeout
E0324 19:21:02.292547  966426 memcache.go:265] couldn't get current server API group list: Get "https://tailscale-operator-unwind.tailnet-fbec.ts.net/api?timeout=32s": net/http: TLS handshake timeout
E0324 19:21:12.294667  966426 memcache.go:265] couldn't get current server API group list: Get "https://tailscale-operator-unwind.tailnet-fbec.ts.net/api?timeout=32s": net/http: TLS handshake timeout
Unable to connect to the server: net/http: TLS handshake timeout
```

**Comment by uhthomas** [comment] 2023-03-24 19:35
Some debug logs

```
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686423.3073416,"logger":"tailscaled","msg":"netcheck: [v1] report: udp=true v6=false v6os=true mapvarydest=true hair=false portmap= v4a=81.96.205.97:1959 derp=8 derpdist=8v4:21ms,14v4:28ms,18v4:29ms"}
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686426.975229,"logger":"tailscaled","msg":"Accept: TCP{100.119.63.109:60260 > 100.119.53.112:443} 52 tcp non-syn\n"}
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686436.97862,"logger":"tailscaled","msg":"wg: [v2] [F0kmQ] - Receiving keepalive packet"}
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686436.9787214,"logger":"tailscaled","msg":"Accept: TCP{100.119.63.109:34354 > 100.119.53.112:443} 52 tcp non-syn\n"}
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686445.3941514,"logger":"tailscaled","msg":"netcheck: [v1] report: udp=true v6=false v6os=true mapvarydest=true hair=false portmap= v4a=81.96.205.97:1959 derp=8 derpdist=8v4:22ms,14v4:28ms,18v4:26ms"}
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686446.9814146,"logger":"tailscaled","msg":"Accept: TCP{100.119.63.109:45164 > 100.119.53.112:443} 52 tcp non-syn\n"}
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686456.984141,"logger":"tailscaled","msg":"Accept: TCP{100.119.63.109:50670 > 100.119.53.112:443} 52 tcp non-syn\n"}
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686466.9731648,"logger":"tailscaled","msg":"cert(\"tailscale-operator.tailnet-fbec.ts.net\"): getCertPEM: 429 urn:ietf:params:acme:error:rateLimited: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: tailscale-operator.tailnet-fbec.ts.net, retry after 2023-03-25T06:33:30Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/"}
operator-6999fbc58b-5lts4 operator 2023/03/24 19:34:26 http: TLS handshake error from 100.119.63.109:35170: Get "http://local-tailscaled.sock/localapi/v0/cert/tailscale-operator.tailnet-fbec.ts.net?type=pair": context deadline exceeded
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686466.974327,"logger":"tailscaled","msg":"Accept: TCP{100.119.63.109:35170 > 100.119.53.112:443} 40 tcp non-syn\n"}
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686467.3499453,"logger":"tailscaled","msg":"cert(\"tailscale-operator.tailnet-fbec.ts.net\"): already had ACME account."}
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686471.1737084,"logger":"tailscaled","msg":"netcheck: [v1] report: udp=true v6=false v6os=true mapvarydest=true hair=false portmap= v4a=81.96.205.97:1959 derp=8 derpdist=8v4:21ms,14v4:24ms,18v4:29ms"}
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686475.783786,"logger":"tailscaled","msg":"[v1] v0x1467b40 peers: 0/0 3908/1724"}
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686476.9756403,"logger":"tailscaled","msg":"cert(\"tailscale-operator.tailnet-fbec.ts.net\"): getCertPEM: 429 urn:ietf:params:acme:error:rateLimited: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: tailscale-operator.tailnet-fbec.ts.net, retry after 2023-03-25T06:33:30Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/"}
operator-6999fbc58b-5lts4 operator 2023/03/24 19:34:36 http: TLS handshake error from 100.119.63.109:60260: Get "http://local-tailscaled.sock/localapi/v0/cert/tailscale-operator.tailnet-fbec.ts.net?type=pair": context deadline exceeded
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686476.9770017,"logger":"tailscaled","msg":"Accept: TCP{100.119.63.109:60260 > 100.119.53.112:443} 40 tcp non-syn\n"}
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686477.3539774,"logger":"tailscaled","msg":"cert(\"tailscale-operator.tailnet-fbec.ts.net\"): already had ACME account."}
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686486.9783266,"logger":"tailscaled","msg":"cert(\"tailscale-operator.tailnet-fbec.ts.net\"): getCertPEM: 429 urn:ietf:params:acme:error:rateLimited: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: tailscale-operator.tailnet-fbec.ts.net, retry after 2023-03-25T06:33:30Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/"}
operator-6999fbc58b-5lts4 operator 2023/03/24 19:34:46 http: TLS handshake error from 100.119.63.109:34354: Get "http://local-tailscaled.sock/localapi/v0/cert/tailscale-operator.tailnet-fbec.ts.net?type=pair": context deadline exceeded
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686486.979704,"logger":"tailscaled","msg":"Accept: TCP{100.119.63.109:34354 > 100.119.53.112:443} 40 tcp non-syn\n"}
operator-6999fbc58b-5lts4 operator {"level":"debug","ts":1679686487.3559513,"logger":"tailscaled","msg":"cert(\"tailscale-operator.tailnet-fbec.ts.net\"): already had ACME account."}
```

**Comment by uhthomas** [comment] 2023-03-24 19:36
Could it be this?

```
cert(\"tailscale-operator.tailnet-fbec.ts.net\"): getCertPEM: 429 urn:ietf:params:acme:error:rateLimited: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: tailscale-operator.tailnet-fbec.ts.net, retry after 2023-03-25T06:33:30Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/
```

That's rough. What can we do about this? What can we do to prevent this happening in future?

**Comment by uhthomas** [comment] 2023-03-24 19:45
Okay, I see it. I changed the hostname of the operator and I can connect again.

```
❯ tailscale configure kubeconfig tailscale-operator
kubeconfig configured for "tailscale-operator"
❯ k get no
E0324 19:43:18.491230  971591 memcache.go:265] couldn't get current server API group list: Get "https://tailscale-operator.tailnet-fbec.ts.net/api?timeout=32s": net/http: TLS handshake timeout
NAME            STATUS   ROLES           AGE     VERSION
talos-3sl-aqp   Ready    control-plane   5d23h   v1.26.2
talos-avz-rb5   Ready    control-plane   5d23h   v1.26.2
talos-god-636   Ready    control-plane   5d23h   v1.26.2
talos-l94-p4c   Ready    control-plane   5d23h   v1.26.2
talos-su3-l23   Ready    control-plane   5d23h   v1.26.2
```

```
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679686988.4514081,"logger":"tailscaled","msg":"wg: [v2] [F0kmQ] - Received handshake initiation"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679686988.4514802,"logger":"tailscaled","msg":"wg: [v2] [F0kmQ] - Sending handshake response"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679686988.4521835,"logger":"tailscaled","msg":"magicsock: disco: node [F0kmQ] d:5fbcf8e5b2c4c2dc now using 192.168.1.126:41641"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679686988.468853,"logger":"tailscaled","msg":"Accept: TCP{100.119.63.109:51026 > 100.71.5.116:443} 60 tcp ok\n"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679686988.4702377,"logger":"tailscaled","msg":"Accept: TCP{100.119.63.109:51026 > 100.71.5.116:443} 52 tcp non-syn\n"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679686988.4704463,"logger":"tailscaled","msg":"Accept: TCP{100.119.63.109:51026 > 100.71.5.116:443} 356 tcp non-syn\n"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679686989.4520109,"logger":"tailscaled","msg":"cert(\"tailscale-operator.tailnet-fbec.ts.net\"): registered ACME account."}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679686989.9707007,"logger":"tailscaled","msg":"cert(\"tailscale-operator.tailnet-fbec.ts.net\"): starting SetDNS call..."}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679686998.4710674,"logger":"tailscaled","msg":"Accept: TCP{100.119.63.109:51026 > 100.71.5.116:443} 52 tcp non-syn\n"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679687000.444733,"logger":"tailscaled","msg":"cert(\"tailscale-operator.tailnet-fbec.ts.net\"): did SetDNS"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679687001.931714,"logger":"tailscaled","msg":"cert(\"tailscale-operator.tailnet-fbec.ts.net\"): requesting cert..."}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679687002.4299574,"logger":"tailscaled","msg":"cert(\"tailscale-operator.tailnet-fbec.ts.net\"): got cert"}
operator-95467c4c8-62c92 operator 2023/03/24 19:43:22 http: TLS handshake error from 100.119.63.109:51026: EOF
operator-95467c4c8-62c92 operator 2023/03/24 19:43:22 http: TLS handshake error from 100.119.63.109:36428: EOF
operator-95467c4c8-62c92 operator 2023/03/24 19:43:22 http: TLS handshake error from 100.119.63.109:36430: EOF
operator-95467c4c8-62c92 operator 2023/03/24 19:43:22 http: TLS handshake error from 100.119.63.109:36492: EOF
operator-95467c4c8-62c92 operator 2023/03/24 19:43:22 http: TLS handshake error from 100.119.63.109:36476: EOF
operator-95467c4c8-62c92 operator 2023/03/24 19:43:22 http: TLS handshake error from 100.119.63.109:36462: EOF
operator-95467c4c8-62c92 operator 2023/03/24 19:43:22 http: TLS handshake error from 100.119.63.109:36446: EOF
operator-95467c4c8-62c92 operator 2023/03/24 19:43:22 http: TLS handshake error from 100.119.63.109:36502: EOF
operator-95467c4c8-62c92 operator 2023/03/24 19:43:22 http: TLS handshake error from 100.119.63.109:36534: EOF
operator-95467c4c8-62c92 operator 2023/03/24 19:43:22 http: TLS handshake error from 100.119.63.109:36418: EOF
operator-95467c4c8-62c92 operator 2023/03/24 19:43:22 http: TLS handshake error from 100.119.63.109:36448: EOF
operator-95467c4c8-62c92 operator 2023/03/24 19:43:22 http: TLS handshake error from 100.119.63.109:36444: EOF
operator-95467c4c8-62c92 operator 2023/03/24 19:43:22 http: TLS handshake error from 100.119.63.109:36414: EOF
operator-95467c4c8-62c92 operator 2023/03/24 19:43:22 http: TLS handshake error from 100.119.63.109:36518: EOF
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679687002.7166836,"logger":"tailscaled","msg":"netcheck: [v1] report: udp=true v6=false v6os=true mapvarydest=true hair=false portmap= v4a=81.96.205.97:37977 derp=8 derpdist=8v4:21ms,14v4:31ms,18v4:29ms"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679687008.4690235,"logger":"tailscaled","msg":"Accept: TCP{100.119.63.109:33574 > 100.71.5.116:443} 52 tcp non-syn\n"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679687018.504167,"logger":"tailscaled","msg":"Accept: TCP{100.119.63.109:37806 > 100.71.5.116:443} 60 tcp ok\n"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679687025.5334778,"logger":"tailscaled","msg":"netcheck: [v1] report: udp=true v6=false v6os=true mapvarydest=true hair=false portmap= v4a=81.96.205.97:50866 derp=8 derpdist=8v4:25ms,14v4:23ms,18v4:33ms"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679687025.5341637,"logger":"tailscaled","msg":"magicsock: endpoints changed: 81.96.205.97:50866 (stun), 10.244.1.120:49864 (local)"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679687025.5342438,"logger":"tailscaled","msg":"[v1] v0x1467b40 peers: 0/0 304628/6810156"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679687025.5342867,"logger":"tailscaled","msg":"control: [v2] client.newEndpoints([81.96.205.97:50866 10.244.1.120:49864])"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679687025.534495,"logger":"tailscaled","msg":"control: [v1] PollNetMap: stream=false ep=[81.96.205.97:50866 10.244.1.120:49864]"}
operator-95467c4c8-62c92 operator {"level":"debug","ts":1679687025.581284,"logger":"tailscaled","msg":"control: [v1] successful lite map update in 47ms"}
```

It looks like it provisions the DNS certificate on the fly, which explains why it's so slow the first time it runs and times out.

It feels bad to be limited to 5 new certificates per week for something which is basically internal infrastructure. As to why so many certs were requests, I don't know.

**Comment by DentonGentry** [comment] 2023-03-25 13:03
> That's rough. What can we do about this? What can we do to prevent this happening in future?

Certificates are issued by LetsEncrypt https://tailscale.com/blog/tls-certs/
Most of the time, LetsEncrypt's ACME challenge to prove that one owns the domain is to put a file in a well-known location on a public webserver. That doesn't work for Tailscale where there isn't a public website.

Instead, Tailscale creates a DNS TXT record to answer a DNS-01 ACME challenge.

> It feels bad to be limited to 5 new certificates per week for something which is basically internal infrastructure.

Tailscale Inc is not a certificate authority and cannot issue these certificates directly, only facilitate their creation.
Any provider of free, automatic certificates (like LetsEncrypt) will impose rate limits.

--------

The root cause is that the certificate is apparently not being persisted, and the operator is being restarted frequently. The certificate is supposed to be stored in the K8S Secrets Manager, the errors to look for would be about storing secrets.

--------

> Bug report
> No response

The template asks for a `tailscale bugreport` because it allows us to look up telemetry for what is happening. Without that, we're not going to make much progress.

**Comment by maisem** [comment] 2023-03-25 15:28
This was fixed in https://github.com/tailscale/tailscale/issues/7665. Can you please try the latest unstable?

**Comment by uhthomas** [comment] 2023-03-25 22:26
> This was fixed in https://github.com/tailscale/tailscale/issues/7665. Can you please try the latest unstable?

Awesome, thank you. I'll give it a try.

**Comment by uhthomas** [comment] 2023-03-25 22:28
> > Bug report
> 
> > No response
> 
> 
> 
> The template asks for a `tailscale bugreport` because it allows us to look up telemetry for what is happening. Without that, we're not going to make much progress.

Respectfully, there is no option available to provide a bug report from the operator. There is no shell for the container and there are no tailscale binaries. Maybe this is something to take as an action item?

**Comment by DentonGentry** [comment] 2023-04-01 16:05
Believed fixed by https://github.com/tailscale/tailscale/issues/7665

**Closed by DentonGentry** 2023-04-01 16:05 UTC
Labels: OS-kubernetes, L1 Very few, P2 Aggravating, T5 Usability, bug
