### ISSUE TITLE
iOS app stuck on ‘Loading…’

### ISSUE THREAD

**Issue by kentj** [tailscale/tailscale#7291] opened 2023-02-15 13:44 UTC
### What is the issue?

After iOS upgrade, Tailscale app hangs in the loading stage. Killing the app doesn’t fix. 

### Are there any recent changes that introduced the issue?

Might be connected to recent upgrade to iOS. 

### OS

iOS

### OS version

16.2

### Tailscale version

1.36.1

### Bug report

BUG-295bdd3e8000e0e8c4ea18cee631cc642ca35aa620fd235297e3285392f6061c-20230215133444Z-778aac90f8f60d9e

**Comment by DentonGentry** [comment] 2023-02-15 13:58
We released a build to TestFlight that resolves a Keychain problem which other users have run into. If you'd like to try it out, you can install version 1.37.101 using the instructions at https://tailscale.com/kb/1083/install-unstable/.

**Comment by mihaip** [comment] 2023-02-17 00:50
Duplicate of #7188

**Closed by mihaip** 2023-02-17 00:50 UTC
Labels: needs-triage, bug
