### ISSUE TITLE
Versions after v1.10.0 (up to v1.16.0) do not allow outbound connections on DS115 (armada375) with DSM6

### ISSUE THREAD

**Issue by MightySlaytanic** [tailscale/tailscale#3115] opened 2021-10-16 21:01 UTC
I have a Synology DS115 with an armada375 CPU running DSM 6.2.4-25556 Update 2. 
With v1.10.0 everything works fine. 
I've tried more recent versions, up to the last 1.16.0) and inbound connections over tailscale work fine, while outbound connections do not work. 
Uninstalling and re-installing v1.10.0 allows outbound connections again.
I know that this platform is old (v1.16.0 works fine on my other DS218+ Synology NAS) but maybe there is something to tweak to allow outbound connections on versions after v1.10.0.
Tell me if you need some logs and where to get them.

**Comment by maisem** [comment] 2021-10-17 16:37
@MightySlaytanic can you share the kernel version of your machine?

Looks like a dupe of #2922

**Comment by MightySlaytanic** [comment] 2021-10-17 17:58
@maisem this is the output of _uname -a_
```
# uname -a
Linux MyNas 3.2.40 #25556 SMP Thu Jul 1 14:30:22 CST 2021 armv7l GNU/Linux synology_armada375_ds115
```

**Closed as completed** 2021-10-18 18:03 UTC
Labels: L2 Few, P2 Aggravating, T5 Usability, OS-synology
