### ISSUE TITLE
Mullvad exit nodes do not work with Tailnet lock

### ISSUE THREAD

**Issue by Minecraft11dude** [tailscale/tailscale#9583] opened 2023-09-29 03:43 UTC
### What is the issue?

self explanatory; Mullvad exit nodes don't work with Tailnet lock, even after disabling and re-enabling it

### Steps to reproduce

1. add Mullvad add-on to account
2. check available exit nodes (works as intended)
3. enable tailnet lock
4. check exit nodes again, this time missing the Mullvad nodes

### OS

macOS, Windows, iOS

### OS version

macOS 14 Sonoma, iOS 17, Windows 10

### Tailscale version

1.48.2, 1.50

### Bug report

BUG-2726bdd6f9cde922b021dc56d818e511b2ba7486113c1033e5ea8c94a44a5305-20230929034311Z-b5355ffad75db48a

**Comment by DentonGentry** [comment] 2023-09-29 04:02
You need to sign the Mullvad exit nodes.

Duplicate of https://github.com/tailscale/tailscale/issues/9387

**Closed by DentonGentry** 2023-09-29 04:02 UTC
Labels: needs-triage, bug
