### ISSUE TITLE
macOS App Store app split DNS domains not working with /etc/resolv.conf

### ISSUE THREAD

**Issue by dcarrion87** [tailscale/tailscale#5677] opened 2022-09-17 13:09 UTC
### What is the issue?

Extension to these:

- https://github.com/tailscale/tailscale/issues/907
- https://github.com/tailscale/tailscale/issues/1714

Go app trying to access Tailscale machine URLs and relies on resolv.conf entries.

Tailscale should be updating the name server in resolv.conf but that does not seem to be the case?

Search domains seem to be getting updated.

Is there any pre-requisites to have Tailscale add the MagicDNS name server 100.100.100.100?

### Steps to reproduce

- Connect to Tailscale on MacOS BigSur 11.7
- MagicDNS nameserver 100.100.100.100 is not added to resolv.conf

### OS

macOS

### OS version

Big Sur 11.7

### Tailscale version

1.30.0 (App Store)

**Comment by bradfitz** [comment] 2022-09-18 16:55
> Search domains seem to be getting updated.
>
> Is there any pre-requisites to have Tailscale add the MagicDNS name server 100.100.100.100?

macOS's DNS resolver supports Split DNS natively. We don't set the global DNS to 100.100.100.100 on macOS by default. Instead, we tell macOS that certain DNS suffixes (for MagicDNS domains) should go to 100.100.100.100. See `scutil --dns`.

Does MagicDNS not work for you?

What's the root problem you had?

**Comment by dcarrion87** [comment] 2022-09-19 00:02
The problem is apps that aren't compiled with `CGO_ENABLED=1`. 

At this stage coder:

https://github.com/coder/coder/issues/4097#issuecomment-1250303611

Which means the fleet of staff using this will need to be instructed on how to update their nameservers to include 100.100.100.100 when on the tailnet.

**Comment by mkmik** [comment] 2022-10-04 12:22
FWIW, having binaries not compiled with CGO is the most common problem with tailscale that we have at work. We often don't compile the tools but rely on package managers like `brew`. There have been cases where the same package is compiled with CGO on darwin-amd64 but without CGO on darwin-arm64.

We helped fix some of the packaging issues upstream, like for example in https://github.com/int128/kubelogin/pull/763 , but I suspect it would be much better if DNS just worked, you know, like magic.

**Comment by dcarrion87** [comment] 2022-10-04 22:14
@mkmik how are you getting around this for tooling when you aren't compiling. Our workarounds are a bit annoying. I'm not sure why it's not possible for tailscale app to add nameserver in as an option? I can see search domains being updated in the resolv.conf.

**Comment by DentonGentry** [comment] 2022-10-05 01:53
As mentioned the App Store version of the app does not always write 100.100.100.100 as the nameserver. If it can get the macOS resolver to handle the DNS config desired, it will configure the macOS resolver.

Because of the sandbox it runs in the App Store version cannot write to the /etc/resolver/* files like Tailscaled-on-macOS can in https://github.com/tailscale/tailscale/pull/4508. Presumably CGO_ENABLED=1 means that the compiled binary ends up using the macOS DNS framework library instead of trying to read in /etc/resolv.conf

**Comment by si14** [comment] 2022-10-27 23:26
Something that might be related:

* macos
* appstore tailscale
* docker-for-mac
* docker set up with `DOCKER_HOST` set to a magic dns domain

`docker ps` works, but `docker compose ps` doesn't, seemingly not being able to resolve the magic dns domain. I abandoned using magic dns and just changed to "classic" DNS so I don't have a minimum reproduction at the moment, but seeing the discussion above I suspect `docker` and `docker compose` (no hyphen for the new go version of it) resolve differently and I encountered the issue described above.

I guess changing to a non-appstore version would help?

**Comment by DentonGentry** [comment] 2022-11-01 12:29
@si14 if you want the Docker issue to be looked at please file it as a new issue. Please generate a bugreport shortly after `docker compose ps` fails (hold option while clicking on the Tailscale icon in the menubar, then choose Debug > Bug report).

**Comment by dcarrion87** [comment] 2022-11-09 22:05
This is probably going to solve a lot of issues in the community: https://danp.net/posts/macos-dns-change-in-go-1-20/

Looks like Coder guys are looking to implement.

@mkmik heads up.

**Comment by DentonGentry** [comment] 2023-02-18 16:49
Tailscale at `HEAD` uses Go 1.20. We expect the Tailscale 1.38 release to be built using Go 1.20.

**Comment by DentonGentry** [comment] 2023-06-03 20:41
So far as I understand:
- the problem was that Go apps prior to Go 1.20 would read /etc/resolv.conf for nameservers
- the App Store Tailscale.app runs within a sandbox which isn't allowed to write SplitDNS files into /etc/resolver/*. I don't see a way around that.

However: Go 1.20 when compiling for macOS now uses the Mac Framework and doesn't read in /etc/resolv.conf any more.

I'm going to optimistically close this as fixed by Go 1.20 for macOS.

**Closed by DentonGentry** 2023-06-03 20:41 UTC
Labels: OS-macos, L2 Few, P2 Aggravating, T5 Usability, dns, bug
