### ISSUE TITLE
logtail: limit upload size

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1108] opened 2021-01-11 23:25 UTC
A user hit an old bug (since fixed in a0a8b9d76a6b7f57618d0cf1a1f6024d2f2ca76a) in an old Tailscale version and ended up with a 368GB local `C:\Windows\System32\config\systemprofile\AppData\Local\Tailscale\tailscale-ipn.log1` logtail buffer file.

We should make sure logtail doesn't let that happen if future infinitely-logging bugs are introduced.

(Some sort of rate-limit in logtail itself?)

/cc @apenwarr @crawshaw @josharian @danderson

**Comment by danderson** [comment] 2021-01-11 23:30
The issue is in the filch on-disk buffer, which doesn't have a cutoff when log.tailscale.com is unreachable. Per the original design doc, it should eventually throw logs away, preserving some chunk of data from before the gap and some from after (before so that we can observe "what caused logs to stop working").

**Comment by apenwarr** [comment] 2021-01-12 03:06
Separately, the log rate limiter is apparently disabled on Wndows. If
it had been enabled, it would have also prevented the problem. We
should probably make both fixes.

On Mon, Jan 11, 2021 at 6:30 PM Dave Anderson <notifications@github.com> wrote:
>
> The issue is in the filch on-disk buffer, which doesn't have a cutoff when log.tailscale.com is unreachable. Per the original design doc, it should eventually throw logs away, preserving some chunk of data from before the gap and some from after (before so that we can observe "what caused logs to stop working").
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Avery Pennarun // CEO @ Tailscale

**Comment by DentonGentry** [comment] 2021-12-18 04:25
Fixed by https://github.com/tailscale/tailscale/pull/3223

**Closed by DentonGentry** 2021-12-18 04:25 UTC
Labels: optimization, L1 Very few, P2 Aggravating, T3 Performance/Debugging
