### ISSUE TITLE
android: unable to access internet while using DNS-over-TLS

### ISSUE THREAD

**Issue by rajveermalviya** [tailscale/tailscale#690] opened 2020-08-16 20:45 UTC
**Describe the bug**
I am unable to access the normal internet while using Android native
DNS-over-TLS (Android 9+) and tailscale.
Tailscale without DoT allows me to access the internet though.
But I would really like to keep DoT enabled for my internet traffic.

**To Reproduce**
1. On Android 9+, Go to network settings
2. Enable Private DNS
3. Start Tailscale
4. See error, unable to access any website

**Expected behavior**
It should work same as when DoT is disabled.

**Screenshots**
Summary in a video: https://youtu.be/5nkF2iHJATw

**Version information:**
 - Device: Oneplus 7
 - OS: Android
 - OS version: Android 10
 - Tailscale version: 0.1.19

**Additional context**
-

**Comment by eliasnaur** [comment] 2020-08-31 10:00
Hi @rajveermalviya. On both my Pixel (Android 10) and emulator (Android 10) the behaviour is different from your case: upon activating Tailscale, the "Private DNS" setting says "Couldn't connect", yet https://1.1.1.1/help displays DNS-over-TLS (DoT) as "yes". Also, both devices have internet connectivity.

May I ask you to provide the "adb logcat" logs from your device during your experiments? It would also be helpful to know whether other VPN apps work on your device with Private DNS enabled.

**Comment by ignoramous** [comment] 2021-01-22 22:33
Internet connectivity loss may be because Android can't connect to the DoT endpoint through Tailscale. Android 10+ uses only DoT when _Private DNS_ is enabled and doesn't fallback to plain text DNS (OS / Network / VPN provided DNS) like it did on Android 9 [0].

Testing https://1.1.1.1 would work because it bypasses DNS. Also note, apps like Instagram, WhatsApp, and Telegram don't need a functioning DNS either and would continue to work as well (that is, as long as there's connectivity to their servers through Tailscale).

[0] https://github.com/celzero/rethink-app/issues/25#issuecomment-674296664

**Comment by eliasnaur** [comment] 2021-01-23 11:18
I tried again, this time with an Android 9 emulator. This time setting up Private DNS didn't result in "Couldn't connect" errors, yet I failed to reproduce the error: browsing both hello.ipn.dev and external websites worked fine and https://1.1.1.1/help said "Using DNS over TLS (DoT): yes".

**Comment by normanr** [comment] 2021-02-05 04:48
I think this is the same as #915 (which has more debugging details).

**Comment by DentonGentry** [comment] 2021-02-08 14:32
Yes, this appears to be https://github.com/tailscale/tailscale/issues/915 - which was filed after this issue, sorry, but has a bunch of updates tracking down the root cause. I'll close this issue and suggest further followups on https://github.com/tailscale/tailscale/issues/915

**Closed by DentonGentry** 2021-02-08 14:32 UTC
Labels: OS-android, dns
