### ISSUE TITLE
Docker binding with exit-node

### ISSUE THREAD

**Issue by pakokrew** [tailscale/tailscale#4118] opened 2022-03-09 10:07 UTC
### What is the issue?

I have issues with a tailscale network containing docker services and exit nodes.

My network:
- Server1 with --advertise-exit-node
- Server2 with --exit-node=VPS_IP and docker containers with ports binded

The network and exit node are working great.

On Server2, when exit-node is disabled, I can access my docker services normally.
When exit-node is enabled, I can't access my docker services anymore, neither locally or remotely.

I discovered that there is an option `--exit-node-allow-lan-access` **which is not in the documentation**
When I set this option to true, it seems that routing to docker networks is not forwarded to the exit node anymore, and I get back access to my docker services, but **only locally** from Server2, **not remotely** anymore. 

After long research of existing problems, I understood that the issue was that using exit-node redirects ALL outgoing traffic to the exit node, including local and docker networks, and allowing lan access permitted communication to docker containers, but I don't understand anymore why I can access them from the machine but not from the outside. 
Are there rules that **blocks incoming** traffic too ?

### OS

Linux

### OS version

Ubuntu 20.04

### Tailscale version

1.22.0

### Bug report

BUG-4b88e34412427b0be5ed2815a5c7ab3bbc599b01f0eafdef44278dac26794476-20220309100501Z-ac1b27ec29b5cdf1

**Comment by pakokrew** [comment] 2022-03-09 10:09
related issues:
https://github.com/tailscale/tailscale/issues/3750
https://github.com/tailscale/tailscale/issues/3877
https://github.com/tailscale/tailscale/issues/1527

**Comment by DentonGentry** [comment] 2022-03-27 06:43
Duplicate of https://github.com/tailscale/tailscale/issues/3877

**Closed by DentonGentry** 2022-03-27 06:43 UTC
Labels: needs-triage, bug

**Comment by pakokrew** [comment] 2022-03-29 08:22
> Duplicate of #3877

I've read this issue before and it doesn't seem to be the same problem. I don't have issues with docker accessing the outside, but the outside accessing docker...

**Comment by madhogs** [comment] 2023-03-20 19:02
@DentonGentry I also have this issue and don't believe it is the same as #3877
Docker (and podman) containers running on a host configured to use an exit node as described in this issue cannot be contacted from anywhere.

Eg. to test this, I ran a service listening on port 8080.
1. Not using exit node + service running directly on host = reachable
2. Not using exit node + service running in docker = reachable
3. Using exit node + service running directly on host = reachable
4. Using exit node + service running in docker = NOT reachable

**Comment by 6ixfalls** [comment] 2023-08-30 06:19
@DentonGentry I am also seeing this issue (both #3877 and #4118), applying the fixes in #3877 solves the outbound and DNS connection issue. However, as mentioned above, inbound connections to the host to a container with a port mapping still don't work. Could this issue be investigated further?
