### ISSUE TITLE
FR: allow usage without iptables or iptables-nft completely

### ISSUE THREAD

**Issue by oskarirauta** [tailscale/tailscale#7170] opened 2023-02-03 06:28 UTC
### What are you trying to do?

_--netfilter-mode off_ argument on `tailscale up` allows us to use tailscale without netfilter support.
Problem is that first we need to have our server _tailscaled_, up and running. And it does not have such
feature. On startup of tailscaled, it initializes our router which holds ipt4 and ipt6, which are IPTables structs
from go-iptables - on construct, initializer executes iptables command from path with argument --version and
if it fails to whatever reason, here particularly to missing binary; it returns error and ipt4 and ipt6 will cause
server to exit with error. If --netfilter-mode off argument is used on tailscale up, netfilter usage is disabled;
but we never get there, because server does not want to start, therefor disabling netfilter mode anyway
requires that iptables is installed (or faked like I explain in commit message of proposal) - and it's a shame
that netfilter disabling does not help on situations were iptables or iptables-nft is not available.

### How should we solve this?

This could be solved by native nftables support but as it's a bit longish process, especially when propably iptables support is wanted to keep in tailscale- we could use another approach, I actually already made a PR with one approach to it in #7169
 

### What is the impact of not solving this?

Impossible to use tailscale on systems without iptables or iptables-nft, unless commands are faked which then might affect on other software that prefers iptables over nftables and doesn't check for nftables at all.

**Comment by DentonGentry** [comment] 2023-02-12 03:19
Duplicate of https://github.com/tailscale/tailscale/issues/391

**Closed by DentonGentry** 2023-02-12 03:19 UTC
Labels: needs-triage, fr
