### ISSUE TITLE
FR: macOS MDM support 

### ISSUE THREAD

**Issue by hazcod** [tailscale/tailscale#4048] opened 2022-03-01 08:41 UTC
### What are you trying to do?

When we push Tailscale to macOS devices, we want to preconfigure some settings for them.

### How should we solve this?

Allow pushing a macOS MDM profile payload to preconfigure tailscale clients.

### What is the impact of not solving this?

Leaving a part of configuration to the users which does not provide any oversight and allows for misconfigurations.

**Comment by bradfitz** [comment] 2022-03-01 15:32
This is already possible. (See existing closed bugs)

What are you trying to accomplish exactly?

Are you using Tailscale or Headscale? Headscale already supports this: https://github.com/juanfont/headscale/blob/main/apple_mobileconfig.go

If Tailscale, email support@.

**Comment by hazcod** [comment] 2022-03-01 15:37
Ah, there is? I did not find any reference of it on the Docs.

**Comment by bradfitz** [comment] 2022-03-01 15:50
What are you trying to do?

**Comment by DentonGentry** [comment] 2022-03-27 14:41
Duplicate of https://github.com/tailscale/tailscale/issues/1572

**Closed by DentonGentry** 2022-03-27 14:41 UTC
Labels: waiting-for-info, needs-triage, fr
