### ISSUE TITLE
Linux: tailscale ip rule set are discarded on every connectivity change

### ISSUE THREAD

**Issue by alteriks** [tailscale/tailscale#2325] opened 2021-07-04 18:43 UTC
Recently I've noticed that I cannot connect to my 2 home PC from ipad using tailscale vpn. 
My two PC are connected via two subnets - 192.168.1.0/24 (1gbe connection via switch) and 192.168.24.0/24 (10gbe direct link)
Both PCs use ArchLinux and systemd-networkd and have static IP configuration. 
Whenever connectivity is lost on on 10gbe link ip caused by suspending/shuting down/disconnecting cable on my workstation, tailscale ip rules are discarded on my homeserver. This doesn't happen at all if I disconnect 1gbe cable.

10gbe cable connected
```
❯ systemctl restart tailscaled                                                                                      
❯ ip a sh 10gbe                                                                                                     3: 10gbe: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000                          link/ether 24:4b:fe:ad:47:41 brd ff:ff:ff:ff:ff:ff                                                              
    inet 192.168.24.4/24 brd 192.168.24.255 scope global 10gbe                                                      
       valid_lft forever preferred_lft forever                                                                      
    inet6 fe80::264b:feff:fead:4741/64 scope link 
       valid_lft forever preferred_lft forever
❯ ip rule
0:      from all lookup local
5210:   from all fwmark 0x80000 lookup main
5230:   from all fwmark 0x80000 lookup default
5250:   from all fwmark 0x80000 unreachable
5270:   from all lookup 52
32766:  from all lookup main
32767:  from all lookup default
```

10gbe cable disconnected, tailscaled needs to be restarted to apply ip ruleset
```
❯ ip a sh 10gbe3: 10gbe: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 9000 qdisc mq state DOWN group default qlen 1000    link/ether 24:4b:fe:ad:47:41 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::264b:feff:fead:4741/64 scope link        valid_lft forever preferred_lft forever
❯ ip rule0:      from all lookup local
32766:  from all lookup main32767:  from all lookup default❯ systemctl restart tailscaled
❯ ip rule
0:      from all lookup local
5210:   from all fwmark 0x80000 lookup main
5230:   from all fwmark 0x80000 lookup default
5250:   from all fwmark 0x80000 unreachable
5270:   from all lookup 52
32766:  from all lookup main
32767:  from all lookup default
```

**Version information:**
systemd 248 (248.3-2-arch)
tailscale 1.10.1-1

**Workaround**
EDIT: I've managed to get working workaround. I've installed networkd-dispatcher (https://gitlab.com/craftyguy/networkd-dispatcher) using aur and created a script to restart tailscaled when link is down on 10gbe interface. 

```
$ yay -Syu networkd-dispatcher
$ sudo systemctl enable --now networkd-dispatcher
$ cat /etc/networkd-dispatcher/no-carrier.d/10gbe.sh
!/bin/bash

if [[ $IFACE == "10gbe" ]]; then
  systemctl restart tailscaled
fi
```
For my use case short disruption in tailscale is better if not having proper connection at all. If any one has better approach to this case please feel free to ask.

**Comment by DentonGentry** [comment] 2021-07-04 18:52
Could you check https://github.com/tailscale/tailscale/issues/1591 and whether `ManageForeignRoutingPolicyRules=false` makes a difference?

**Comment by alteriks** [comment] 2021-07-04 19:13
I've added `ManageForeignRoutingPolicyRules=false` to `/etc/systemd/networkd.conf` but got:
```
lip 04 21:02:31 nebula systemd-networkd[3164146]: /etc/systemd/networkd.conf:19: Unknown key name 'ManageForeignRoutingPolicy>
```
After short digging I found that this is option was added recently to v249-rc3
https://github.com/systemd/systemd/commit/d94dfe7053d49fa62c4bfc07b7f3fc2227c10aff

I'll be back when I install systemd-git via yay to 249.rc3.r19.g07eabc2beb-1

**Comment by alteriks** [comment] 2021-07-04 19:47
I've installed systemd from git using yay. It seems that ip rule set is persistent when `ManageForeignRoutingPolicyRules=false` is set. 

I've tried restarting systemd-networkd and unplugging cable and tailscale rules are still there!

Do you know if tailscale will manage this option on it's own interface or it should be set global in /etc/systemd/networkd.conf

**Comment by DentonGentry** [comment] 2021-07-04 20:03
We don't have a way to ask systemd-networkd to not mess with our routing table, and (at least so far) haven't wanted to change systemd-networkd's configuration file nor install our rules as `proto kernel`
So far we've been counting on the recent systemd-networkd changes to make it into distributions.

I'll close this as a duplicate of #1591

**Closed by DentonGentry** 2021-07-04 20:03 UTC
Labels: L3 Some users, OS-linux, P2 Aggravating, T5 Usability
