### ISSUE TITLE
Add an option to allow LAN access when using an exit node.

### ISSUE THREAD

**Issue by Flameeyes** [tailscale/tailscale#1527] opened 2021-03-17 21:20 UTC
**Describe the bug**

When selecting an exit node, the new routing table (52 in my case) does not include any of the local subnets, making it impossible to reach them, and reflecting the traffic due to them back onto `tailscale0`.

This pretty much means a node that selected an exit node becomes invisible to all the local clients. This can be solved by adding the local subnets back to the newly created routing table.

Now, according to the `ip rule` output, it loosk like this is meant to be addressed by `fwmark 0x80000`:

```
rule
0:      from all lookup local
5210:   from all fwmark 0x80000 lookup main
5230:   from all fwmark 0x80000 lookup default
5250:   from all fwmark 0x80000 unreachable
5270:   from all lookup 52
32766:  from all lookup main
32767:  from all lookup default
```

That forces a lookup on otable main, that includes the local routes.
But as far as I can tell nothing is setting that mark:

```
flameeyes@brentcube:~$ sudo iptables -L -v -n
Chain INPUT (policy ACCEPT 2330 packets, 241K bytes)
 pkts bytes target     prot opt in     out     source               destination
 2333  241K ts-input   all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
 1939  131K ts-forward  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 3807 packets, 523K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain ts-forward (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 MARK       all  --  tailscale0 *       0.0.0.0/0            0.0.0.0/0            MARK set 0x40000
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40000
    0     0 DROP       all  --  *      tailscale0  100.64.0.0/10        0.0.0.0/0
 1939  131K ACCEPT     all  --  *      tailscale0  0.0.0.0/0            0.0.0.0/0

Chain ts-input (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  lo     *       100.121.107.31       0.0.0.0/0
    0     0 RETURN     all  --  !tailscale0 *       100.115.92.0/23      0.0.0.0/0
    0     0 DROP       all  --  !tailscale0 *       100.64.0.0/10        0.0.0.0/0
```

This is with

```
1.6.0
  tailscale commit: ddc975fcb268a06dc39923ec5db93f1c95b8cfc4
  other commit: 995460c32665f1dab78c78512386235d275cf074
  go version: go1.16.2-ts3b83fb3
```

on Ubuntu 20.04.2.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2xjdd)

**Comment by bradfitz** [comment] 2021-03-17 21:23
This is actually a security feature. I'll let @danderson explain. :)

But we recognize this isn't what all users want, so in a future release we want to add an option to control this behavior.

/cc @crawshaw

**Comment by Flameeyes** [comment] 2021-03-17 21:25
> This is actually a security feature. I'll let @danderson explain. :)

Might be worth calling out in the docs… it took me the best part of a week debugging to boil it down to this simple set of reproducible instructions, ad you could notice by my Twitter ranting ;)

(In a similar note, the fact that v6 access is dropped when selecting an exit node without v6 makes sense… except that it also makes the connected node lose _inbound_ v6 connectivity which is not what I would have expected.)

**Comment by danderson** [comment] 2021-03-17 21:28
Yeah, this is working as intended. The way exit nodes work right now, we want to "teleport" your machine to the exit node's location as much as possible, and that implies not leaking LAN traffic.

We definitely want to add a toggle for LAN access though.

**Comment by flexzuu** [comment] 2021-03-17 22:10
Am i right in assuming this also is tru if the node that uses the exit node exposes local subnets?

More info what i try to setup here: https://forum.tailscale.com/t/pi-as-vpn-router-to-access-tailscale-and-use-exit-node/455

Also i think what might be related to my case is #1299. But i think even with masquerading it will not work to get access to internet via pi -> exit node currently because of this issue here.

**Comment by 33b5e5** [comment] 2021-03-17 22:36
Oh. I think this got me too. https://forum.tailscale.com/t/no-dns-when-using-exit-node/477

My DNS servers are on the LAN, so when I try to use an exit node, I lose DNS.

I'm not sure how to work around this, because setting external DNS on the admin panel doesn't seem to change anything in this context.

**Comment by danderson** [comment] 2021-03-17 22:48
@flexzuu by design, turning a machine into an exit node does _not_ grant access to the LAN the exit node is attached to. Think of it as guest wifi at the remote location. You can --advertise-routes the LAN if you do want access to it.

@33b5e5 Probably not the same thing. On Windows we explicitly allow DNS traffic to continue using the LAN, to handle the case you describe. Can you file a separate bug with the info you reported in the forum, and the Tailscale IPs of the two nodes in question so I can debug more?

**Comment by flexzuu** [comment] 2021-03-17 23:36
Is this true for the machine in the lan itself too?

My setup:
I have a pi and an exit node server. Pi uses the exit node. Pi advertises 198.168.178.0/24 if i try to ping a local address from the pi this does not work. Why is probably a pre condition for routing another machine's traffic via the pi through the exit to the public internet.

**Comment by mfenniak** [comment] 2021-03-17 23:46
I think this behaviour seems especially counter-intuitive in a mobile use-case.  I'd like to leave my phone with Tailscale enabled and running with a configured exit node, so that I can have zero interaction with Tailscale other than using services provided to me by my network.  But when I leave it on with an exit node, I can't use features like Chromecast to interact with the local network that I'm currently on.

In order to avoid having to turn Tailscale on and off at times, I think that good options would be either an option to leak the local subnet, or to preconfigure which networks you'd like to use the exit node capability on and which you would not.

On the other hand, the security provided by this default configuration is quite appealing if I imagine I'm on a public WiFi network... so... it does seem like a strong starting position.  It just needs a wedge to open up a bit on a slightly more trusted network?

**Comment by danderson** [comment] 2021-03-18 01:04
The problem here is that there is no one true answer to how this should work. For you, no LAN access is not what you want, but for other use cases, LAN access would be a data leak when trying to access the exit node. As a first pass, we implemented the option that defaults to being as safe as possible, which implies denying LAN access.

We definitely want to add an option on the client to permit LAN access when using an exit node, but it'll take some effort to implement on every OS (support for this kind of configuration varies wildly, and requires different hacks). I'll use this bug to track that.

As for "automatically turn things on and off depending on which network you're in", there is no way to make that safe from spoofing, unfortunately. There are a number of options that might be acceptable depending on your particular threat model, but fundamentally the local network cannot be trusted when it comes to making security decisions :(. We're still thinking about how to implement some kind of option like that for people who really need it, but there's no timeline on that yet.

**Comment by flexzuu** [comment] 2021-03-18 01:26
I just confirmed that if I do not use the exit node on my device and use the approach from #1299 my devices in the lan can access tailscale ips. Is there any iptable I could add/modify manually to allow traffic from
The lan to use the exit node?
Or any other workaround to the issue until tailscale might add an option.

**Comment by danderson** [comment] 2021-03-18 01:29
@flexzuu It sounds like you're trying to set up a LAN router that sends traffic over tailscale, which currently requires a bunch of manual configuration and network know-how, but is not what this bug is about. Let's take this back to the forum, since it's a different kind of setup.

**Comment by rfgamaral** [comment] 2021-03-18 09:42
Can someone explain me this issue like I'm 5?

The reason I'm trying to understand is that I feel like my scenario above shouldn't be working but it is:

- I have a Raspberry Pi with `tailscale` running with `--advertise-routes=10.0.10.0/24`, `--advertise-exit-node` and `--accept-dns=false`. This machine LAN IP address is `10.0.10.200`;
- On Tailscale admin I have "Subnets" and "Exit Node" enabled for the Raspberry Pi;
- I have a DNS server running on the Raspberry Pi (`10.0.10.200` / `100.x.x.x`), and an additional DNS server running on a different LAN machine (`10.0.10.205`)
- Also on Tailscale admin I have "Magic DNS" disabled, Nameservers set to the Raspberry Pi `100.x.x.x` address (notice one extra zero compared to my LAN IP address), and I also have my own custom domain on "Search Domains";
- I have updated Tailscale to the latest 1.6.0 version on my Android phone and for testing purposes connected to the LTE network from my ISP, with the "exit node" option on the Android app enabled, and my Raspberry Pi as the exit node;
- I can successfully use both DNS servers detailed above (`10.0.10.200` and `10.0.10.205`) with [Ping Tools](https://play.google.com/store/apps/details?id=ua.com.streamsoft.pingtools) (this app allows you to pick the IP address for the DNS server to use when debugging DNS lookups).

Is this in any way related to the issue here being discussed or completely different?

**Comment by hronro** [comment] 2021-03-19 04:59
Hi @danderson , I have the same issue as @33b5e5:
> My DNS servers are on the LAN, so when I try to use an exit node, I lose DNS.
> 
> I'm not sure how to work around this, because setting external DNS on the admin panel doesn't seem to change anything in this context. Is there a way to route DNS over Tailscale and out the exit node?

My exit node is in my home and uses my home's LAN DNS server(192.168.100.1), and the client is in my office and uses the office LAN DNS server(192.168.2.1). I'm not sure how to configure to let the client use the DNS server of exit node(192.168.100.1)? I try to manually change it to 192.168.100.1 in my client OS settings, but it doesn't work.

**Comment by rosszurowski** [comment] 2021-05-28 14:45
We've built the backend infrastructure for this feature, and are looking to expose it in and upcoming release. Here's some sample designs for how we can achieve this on desktop. Mobile will take a little longer, since we'll be building out a settings view to accommodate this feature, and others like it.

/cc @DentonGentry @maisem 

![allow-lan-access](https://user-images.githubusercontent.com/303731/120001008-5fa1a100-bfa1-11eb-8629-58a9e9aaa860.png)

And @maisem, since we were talking about decoupling exit node selection from enabling/disabling exit nodes, you might be surprised that the above designs follow our current pattern of picking "None" or "<exit node>". I audited a bunch of menu bar apps and couldn't find a good pattern for a nested enable/disable. Building a toggle like macOS' Wi-Fi menu bar item could work, but it'd still leave us needing a solution on Windows. For now, I think it's best to use the existing pattern of picking which exit node you want each time you activate it.

**Comment by DentonGentry** [comment] 2021-06-26 07:47
MacOS support added in 1.10 release.
Windows support expected to be added for 1.12 release.

**Comment by DentonGentry** [comment] 2021-07-21 05:23
Windows support for allowing access to Local LAN while an exit node is in use added in 1.12.
MacOS was added in 1.10.
Linux `--exit-node-allow-lan-access` added in 1.10 (I think).

Going to close this as fixed.

**Closed by DentonGentry** 2021-07-21 05:23 UTC
Labels: L1 Very few, P2 Aggravating, T0 New feature, connectivity, exit-node

**Comment by TwisX** [comment] 2021-11-08 04:54
> We've built the backend infrastructure for this feature, and are looking to expose it in and upcoming release. Here's some sample designs for how we can achieve this on desktop. Mobile will take a little longer, since we'll be building out a settings view to accommodate this feature, and others like it.
> 
> /cc @DentonGentry @maisem
> 
> ![allow-lan-access](https://user-images.githubusercontent.com/303731/120001008-5fa1a100-bfa1-11eb-8629-58a9e9aaa860.png)
> 
> And @maisem, since we were talking about decoupling exit node selection from enabling/disabling exit nodes, you might be surprised that the above designs follow our current pattern of picking "None" or "". I audited a bunch of menu bar apps and couldn't find a good pattern for a nested enable/disable. Building a toggle like macOS' Wi-Fi menu bar item could work, but it'd still leave us needing a solution on Windows. For now, I think it's best to use the existing pattern of picking which exit node you want each time you activate it.

What's the status on allowing LAN access while using an exit node for the Android client?

**Comment by DentonGentry** [comment] 2021-11-08 04:56
The mobile clients need a more extensive UI revamp to allow preferences. We have some ideas about what to do, but it is not being actively worked on at this time.

Windows, Linux, and macOS currently implement the allow-lan-access-with-exit-node feature.

**Comment by Omrigan** [comment] 2021-12-03 18:09
What can I do if I have some routes which are not part of my subnet (192.168.1.0/24), but still only accessible locally (192.168.3.0/24, where I keep all of my IoT devices). 
As I noticed, `--exit-node-allow-lan-access` adds `throw 192.168.1.0/24` to the table 52. Maybe the option should be added like `--exit-node-local-routes 192.168.0.0/16`?

Also, if I  `--advertise-routes=192.168.0.0/16` it wouldn't work, since `192.168.3.0/24` not even accessible from the host.

**Comment by boothb** [comment] 2021-12-30 14:47
Hi @Omrigan 

I would love to see an option like you suggested to add additional local routes.

For now I succesfully do it manually like this `sudo ip route add throw 192.168.0.0/12 table 52`.

**Comment by am0401** [comment] 2022-02-28 03:22
Any update on when the allow lan access feature will be coming to iOS and Android?

**Comment by marcosscriven** [comment] 2022-04-23 15:20
I'm confused if the LAN access option should be available in iOS? 

Tailscale documentation seems to suggest it is on clients > v1.6: https://tailscale.com/kb/1103/exit-nodes/

However, right now on 1.22.0 I don't see that option. The exit node is otherwise working perfectly.

**Comment by DentonGentry** [comment] 2022-04-23 15:22
The iOS UI needs a redesign to add a control for this in a reasonable way. That redesign has started, but not delivered in 1.22.

**Comment by marcosscriven** [comment] 2022-04-23 15:24
> The iOS UI needs a redesign to add a control for this in a reasonable way. That redesign has started, but not delivered in 1.22.

Thanks @DentonGentry for the amazingly swift response!

Does that mean the documentation is wrong (or I'm reading it wrong)? Was it there before and then removed?

**Comment by DentonGentry** [comment] 2022-04-24 02:04
I don't think the documentation has said that iOS can be an exit node yet. The technical capability is there, but the UI needs a redesign to add it in a reasonable way.

**Comment by MiraiSubject** [comment] 2022-05-09 20:02
It actually, in fact, does. I was scratching my head for a while trying to troubleshoot this issue, and the tooltip does not help either because the iOS app is already on version 1.24.2.

![image](https://user-images.githubusercontent.com/803255/167488014-83fc9078-f43d-41a6-af87-4f6dda7ea93e.png)

I believe the documentation should be updated accordingly until the functionality is actually available in the iOS app.

**Comment by rosszurowski** [comment] 2022-05-09 20:15
You're right, looks like that's an issue in our docs. We'll get that fixed. /cc @WalterHub

**Comment by marcosscriven** [comment] 2022-05-10 04:38
Thanks for following @MiraiSubject / @rosszurowski 

As an aside for anyone reading this, I did discover an alternative that gave me the same thing I wanted.

`tailscale up --advertise-exit-node --advertise-routes=192.168.0.0/16`

Now I have that, I'm not even sure how a client-side setting would interact with this option.
