### ISSUE TITLE
Cannot share nodes created by the Kubernetes operator with Tailnet Lock

### ISSUE THREAD

**Issue by uhthomas** [tailscale/tailscale#10633] opened 2023-12-17 11:30 UTC
### What is the issue?

It doesn't seem possible to share nodes created by Kubernetes operator when Tailnet Lock is enabled. I tried enabling Tailnet lock on the other Tailnet, and signed all nodes from both Tailnets but it didn't help. Some advice on reddit suggested that the outgoing nodes needed to be signed from the node itself, but this isn't possible because:

```sh
❯ k exec -it ts-someapp-kxrhg-0 -- tailscale lock status
failed to connect to local tailscaled (which appears to be running as tailscaled, pid 13). Got error: error: Failed to connect to local Tailscale daemon for /localapi/v0/tka/status; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
command terminated with exit code 1
```

I mentioned this in another issue, but I cannot generate a bug report because of this too.

```sh
❯ k exec -it ts-someapp-kxrhg-0 -- tailscale bugreport
Failed to connect to local Tailscale daemon for /localapi/v0/bugreport; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
command terminated with exit code 1
```

### Steps to reproduce

1. Enable Tailnet Lock.
2. Use the Tailscale Kubernetes operator with an ingress to create a node.
3. Try to share that node. 

### OS

Linux, Windows, iOS

### Tailscale version

1.54.1

**Comment by uhthomas** [comment] 2023-12-17 11:32
This is related to #9103, but IMO not the same as I have tried to sign nodes, but it still doesn't work.

**Comment by uhthomas** [comment] 2023-12-17 11:37
```sh
❯ k logs ts-someapp-kxrhg-0
2023/12/17 11:33:42 tkaSyncIfNeeded: enabled=true, head=7WYXTX3LIYYAT65CCDLN3NZAGO4BM7AG2RHFYNFFOUBUV33DUGHA
2023/12/17 11:33:42 Network lock is dropping peer nodeid:3ecdc80fef628(nCJKYX5CNTRL) due to missing signature
2023/12/17 11:33:42 [RATELIMIT] format("Network lock is dropping peer %v(%v) due to failed signature check: %v") (1 dropped)
2023/12/17 11:33:42 Network lock is dropping peer nodeid:4299ab100c402(nB8mdt6CNTRL) due to failed signature check: key: key not found
2023/12/17 11:33:42 Network lock is dropping peer nodeid:6e5b290be50fe(nTFyHs4CNTRL) due to failed signature check: key: key not found
2023/12/17 11:33:42 Network lock is dropping peer nodeid:96f4ed118b8d5(nYkPje1CNTRL) due to missing signature
2023/12/17 11:33:42 Network lock is dropping peer nodeid:135748654f0f1c(nS5XDT6CNTRL) due to missing signature
2023/12/17 11:33:42 Network lock is dropping peer nodeid:1538a14dd44bd4(nEgdRX3CNTRL) due to failed signature check: key: key not found
2023/12/17 11:33:42 Network lock is dropping peer nodeid:16eb38e4deb0b8(nJUHfW2CNTRL) due to failed signature check: key: key not found
2023/12/17 11:33:42 Network lock is dropping peer nodeid:191208d68d6617(nGq23E4CNTRL) due to failed signature check: key: key not found
2023/12/17 11:33:42 [RATELIMIT] format("Network lock is dropping peer %v(%v) due to failed signature check: %v")
```

**Comment by irbekrm** [comment] 2023-12-17 21:33
Hi @uhthomas ,

Thank you for opening the issue.

I have not tested the operator with Tailnet Lock yet, but 

> Failed to connect to local Tailscale daemon for /localapi/v0/bugreport; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory

this error is because `tailscale` cannot find the socket that the `tailscaled` daemon listens on. We added a symlink to the default socket path in https://github.com/tailscale/tailscale/pull/10518, the `v1.56.0` tag has that change, so should be able to run `tailscale` commands.

Let us know if you get it working.

**Comment by uhthomas** [comment] 2023-12-18 12:44
v1.56.0 has helped, thank you. I can now run `tailscale lock status`, but I have yet to test if it works still.

**Comment by uhthomas** [comment] 2023-12-18 12:46
I don't think it will work.

```sh
Error: Signing is not available on this device because it does not have a trusted tailnet lock key.

Try again on a signing device instead. Tailnet admins can see signing devices on the admin panel.

error: 500 Internal Server Error: signing failed: this node is not trusted by network lock
command terminated with exit code 1
```

**Comment by uhthomas** [comment] 2023-12-18 14:27
I think you're right, this is no longer a problem related to the Kubernetes operator.

However, I still think there is something strange here. The node in Kubernetes is signed, and I can access it within my Tailnet. All nodes in the destination Tailnet are signed too. The signing nodes in my Tailnet do not show anything, but the shared node does show some "unknown" nodes with just Tailscale IPs. I cannot sign them from the shared node.

Strangely, I _can_ copy the destination node keys from the shared node and sign them from a signing node in my Tailnet, even though they don't show up in `tailscale lock status`? I think there is a lot of room from UX improvement, and documentation. The behaviour I am observing though seems wrong in some way, and obscenely obtuse.

**Comment by knyar** [comment] 2023-12-18 15:21
> I think you're right, this is no longer a problem related to the Kubernetes operator.

Thank you for confirming. So far this issue looks like a duplicate of #9103, and it would be easier for us to close it, keeping only one open issue focused on a particular topic.

> Strangely, I can copy the destination node keys from the shared node and sign them from a signing node in my Tailnet

Yeah, I believe this is matching the [documented way](https://tailscale.com/kb/1226/tailnet-lock#use-the-cli-to-add-a-node) to sign specific keys via the CLI.

> even though they don't show up in tailscale lock status?

I believe they should show up in `tailscale lock status` on the node that is being shared, and other nodes shared with the same user/tailnet. Devices on your tailnet that have not been shared with those nodes, will not be aware of their keys.

**Closed** 2023-12-18 15:54 UTC
Labels: OS-kubernetes, L1 Very few, P2 Aggravating, needs-triage, bug, needs-triage-eng, tailnet-lock
