### ISSUE TITLE
Missing Env Vars via Tailscale SSH in Container

### ISSUE THREAD

**Issue by esolitos** [tailscale/tailscale#12395] opened 2024-06-07 06:42 UTC
### What is the issue?

When connected to a Docker container via Tailscale SSH, the environment variables are not accessible. However, they are accessible when opening a shell directly into the container. This issue affects environment variables set in the Dockerfile as well as those defined at container runtime.

### Steps to reproduce

1. Create a Docker container with env variables set in the Dockerfile or start a container and define an env var at launch time.
2. Open a shell directly into the container.
3. Validate that the defined environment variables are present.
4. Switch to a new shell and connect to the container _via Tailscale SSH_.
5. Attempt to access the environment variables.
6. Notice that the environment variables are not available.

### Are there any recent changes that introduced the issue?

No recent changes have been made that would introduce this issue.

### OS

Linux, macOS

### OS version

Ubuntu 22.04

### Tailscale version

1.66.4

### Other software

N/A

### Bug report

BUG-319b790b4e9094fb1b8483dcaa891b97b4e5bfb74761c512e4d0fa1842dce053-20240607064135Z-3024031d229ece8f

**Comment by timtailscale** [comment] 2024-07-03 17:12
Looks like a duplicate of #12080

**Closed by timtailscale** 2024-07-03 17:12 UTC
Labels: needs-triage, bug

**Comment by esolitos** [comment] 2024-07-05 20:40
Yeah, would like it should be the same. 👍
