### ISSUE TITLE
Intermittent system-wide DNS failures with Tailscale 1.68.1 on macOS 14.5

### ISSUE THREAD

**Issue by kurtraschke** [tailscale/tailscale#12664] opened 2024-06-29 12:59 UTC
### What is the issue?

After a connectivity change (such as changing Wi-Fi networks, especially if a captive portal is involved) or during periods of intermittent connectivity, Tailscale 1.68.1 on MacOS 14.5 seems to get into a state that interferes with DNS resolution system-wide.  On one occasion when I observed this, it seemed like MagicDNS names _would_ resolve but name resolution was broken for Internet destinations, but I have not checked this every time these symptoms appear.  In most cases I do not have time for detailed troubleshooting so I have just gotten in the habit of toggling Tailscale off and on again after connectivity changes, which is annoying.

### Steps to reproduce

1. Connect to a Wi-Fi network with a captive portal, _or_ experience intermittent connectivity.
2. Observe an apparent loss of network connectivity to Internet destinations (specifically, DNS resolution failures).
3. Toggle Tailscale off and on again.
4. Observe that connectivity is restored.

### Are there any recent changes that introduced the issue?

Unclear but this does appear to be a relatively recent issue.

### OS

macOS

### OS version

macOS Sonoma 14.5 (23F79)

### Tailscale version

1.68.1, Mac App Store variant

### Other software

None.

### Bug report

BUG-48e23177c9a49f29309dc01b2ab7dfbbb7bcfa76497c58b46aeb25697ec37122-20240629124501Z-e583232ef90676f3

**Comment by agottardo** [comment] 2024-06-29 17:19
Duplicate of https://github.com/tailscale/tailscale/issues/12615 

(a preliminary fix is already available in unstable)

**Closed by agottardo** 2024-06-29 17:19 UTC
Labels: needs-triage, bug

**Comment by kurtraschke** [comment] 2024-10-31 16:53
I get that this was closed as a dupe of #12615 but I am still experiencing the same symptoms as in the original report with Tailscale 1.76.1

**Comment by agottardo** [comment] 2024-10-31 17:59
@kurtraschke hey thanks for replying! First of all, please switch to the Standalone variant of the client if you haven't yet done so.

Then, if the issue persists, please file a *new* issue with a bug report identifier and any diagnostics you can collect so that we can identify the root cause of the problem on _your_ setup. Look for log entries in Console.app for the `io.tailscale.ipn.macsys.network-extension` process that mention DNS issues.
