### ISSUE TITLE
Synology can not reauth when key is expired

### ISSUE THREAD

**Issue by skarra** [tailscale/tailscale#7271] opened 2023-02-13 00:12 UTC
### What is the issue?

I realized I could not connect to my Synology any longer; turned out although Tailscale was running the auth had expired (first screenshot). When I tried to click 'Open' from the synology admin console, I get take taken to a screen  with a Login button, which I expect would start an oAuth flow (roughly what I recall from the last time I did this). However clicking on the Login button has no effect, and it eventually times out with an error message. (second screenshot attached). There is nothing of note in Console

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/633395/218345280-8a55e0eb-dc70-4539-b749-7f930950d853.png">

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/633395/218345617-899b7a2c-d1e4-4ef4-b2a1-cdc23ac1bcda.png">

### Steps to reproduce

I am not sure I know specific instructions to repro the bug in a new environment, but the bug is present always on my Synology and currently preventing me from auth-ing to tailscale on the device.

### OS

Synology

### OS version

macOS Ventura; Synology 7.1.1

### Tailscale version

1.30.2 on Synology; 1.36.0 on the macOS

### Bug report

BUG-d62ca7b2223acaa6f8def36043fc4ec13f9f2e0e0548594fc9727a72d78676dd-20230212235855Z-5bbd371fe385a0e9

**Comment by skarra** [comment] 2023-02-13 00:31
A random thought; I have a suspicious the login failures have something to do with a transfer of a Time Machine backup to a new macbook I got. There is  no "duplicate key note" label under the machines in the admin console. Still I tried uninstalling and reinstalling Tailscale on both the Synology and the mac, but the problem persists. Two questions:

1. Is it enough to move the application to Trash and reinstall from the App Store to get a full clean reinstall, or is some manual cleanup still required?
2. Where are the Tailscale config files stored on the mac - are all of them somewhere in /Applications/Tailscale.app?

**Comment by DentonGentry** [comment] 2023-02-13 00:37
> Where are the Tailscale config files stored on the mac - are all of them somewhere in /Applications/Tailscale.app?

It is stored in a few places including the keychain, https://tailscale.com/kb/1069/uninstall/?tab=macos explains how to clear it all.

--------

As for the original problem, SSH to the LAN address of the synology followed by the CLI command to bring the interface up will likely get the system functional again:
`/var/packages/Tailscale/target/bin/tailscale up --force-reauth`

**Comment by skarra** [comment] 2023-02-13 02:56
Thank you; doing a force-reauth on the synology fixed it.

**Comment by DentonGentry** [comment] 2023-02-19 04:52
Duplicate of https://github.com/tailscale/tailscale/issues/5062

**Closed by DentonGentry** 2023-02-19 04:52 UTC
Labels: L1 Very few, P3 Can't get started, T5 Usability, bug

**Comment by jstewart1988** [comment] 2025-01-20 23:22
I am dealing with the same problem. The security key for Tailscale on my Synology NAS has expired and I am not able to authenticate.

Can someone provide detailed instructions to SHH to the LAN address of the Synology?  The information below worked for skarra. Thanks in advance.

As for the original problem, SSH to the LAN address of the synology followed by the CLI command to bring the interface up will likely get the system functional again:
/var/packages/Tailscale/target/bin/tailscale up --force-reauth
