### ISSUE TITLE
iOS App disconnects every night/early morning at 3am and has to be manually restarted

### ISSUE THREAD

**Issue by hutchisr** [tailscale/tailscale#5030] opened 2022-07-09 19:30 UTC
### What is the issue?

iOS app disconnects every night within a few minutes of 3am. Launching the tailscale app will cause it to reconnect.

Filing this as a new bug report since the other iOS disconnection bugs I saw seemed random or crashes while this seems like the tunnel is consistently getting killed at the same time and not recovering.

### Steps to reproduce

1. Install Tailscale and connect to tailnet.
2. Leave tailscale connected overnight.

### OS

iOS

### OS version

15

### Tailscale version

1.26.1

### Bug report

BUG-c22531b355d4ae7203f70d89b00cc1e46459a3599813e5b74f90510d3b7e0b2d-20220709192710Z-c80db9427f91778f

**Comment by bigbeka** [comment] 2022-07-11 17:16
+1 from me.

This happens very often for me, sometimes if the app is not opened, it also disconnects. It gets extra difficult with DNS enabled for Tailscale network.

**Comment by DentonGentry** [comment] 2022-07-11 17:23
@bigbeka iOS 15, or before?

iOS releases prior to 15 gave far less memory to Neetwork Extensions like Tailscale. The app was much more likely to run out of RAM and be killed. https://tailscale.com/blog/go-linker/

**Comment by bigbeka** [comment] 2022-07-11 17:49
@DentonGentry iOS 15.5 on iPhone 11 Pro Max.

I have setup an Uptime Kuma which will Ping my iPhone vie Tailscale IP every 20 seconds and notify if my iPhone doesn’t respond to the ping.

I will comment here tue next time the app goes down and I am notified.

**Comment by mihaip** [comment] 2022-07-11 18:49
@hutchisr / @bigbeka: If you go the iOS Settings app -> Privacy -> Analytics & Improvements -> Analytics Data (where [iOS crash reports](https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs) are stored), do you have any Tailscale crashes there? If iOS is killing them due to high CPU usage I believe it should be recorded as a crash.

**Comment by bigbeka** [comment] 2022-07-11 21:24
@mihaip I am not sure if it is #4760 (or goland/go#51654), I will have to run an iOS Crash Report at 3:00am, if nothing helps. 

> Analytics Data
But the Data search did not return anything for Tailscale. There are reports for other apps (Instagram and what not) but nothing for Tailscale. Unless one needs to look into the file content themselves. I am not sure if the "Analytics Data" indexes the contents of each file/report.

**Comment by digitaldan** [comment] 2022-09-29 18:26
Pretty sure this is a DUP of #4646 , see specifically see https://github.com/tailscale/tailscale/issues/4646#issuecomment-1257251332

**Comment by DentonGentry** [comment] 2022-09-30 22:54
Duplicate of https://github.com/tailscale/tailscale/issues/4646

**Closed by DentonGentry** 2022-09-30 22:54 UTC
Labels: OS-ios, L1 Very few, P1 Nuisance, T5 Usability, bug
