### ISSUE TITLE
Split DNS configuration is pointing at a DNS server hosted on Tailscale.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2224] opened 2021-06-22 20:17 UTC
DNS/split DNS  is failing after upgrading to 1.8.7 on macOS/IOS.

Failed to resolve the split Domain. 

Workaround: Disable the "Override Local DNS " option from the admin console. (please verify another node of windows/android/Linux/etc while you change the DNS config)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3ajwx)

**Comment by darshinimashar** [comment] 2021-06-22 20:18
[https://github.com/tailscale/corp/issues/2045](url)

**Comment by crawshaw** [comment] 2021-06-22 20:20
Is this the issue where the Split DNS configuration is pointing at a DNS server hosted on Tailscale? If so:
1. please update the subject to mention that
2. make it clear that it's not the upgrade to 1.8.7 that is causing the problem: no client today can correctly handle this split DNS configuration
3. Is the fix really to _disable_ "Override Local DNS"? I believe the fix is to enable it.

**Comment by darshinimashar** [comment] 2021-06-22 20:24
Disable override local DNS fix it as workaround, but looks like it breaks the DNS for Windows, as reported by one of the customer.

**Comment by crawshaw** [comment] 2021-06-22 20:27
I don't understand that fix. Override local DNS is off in our tailscale.com tailnet and split DNS is broken on macOS 1.8.7.

Turning "Override Local DNS" on would set the OS resolver to an IP allowing the use of a DNS over Tailscale. If turning "Override Local DNS" is not the fix, then the bug must be something other than what was discussed today.

**Comment by DentonGentry** [comment] 2021-06-22 20:33
For one customer we were working with yesterday:
1. the DNS server 10.0.x.x is reached via a Tailscale subnet router
2. turning on "Override Local DNS" results in a MacOS DNS config which says to use 100.100.100.100, expecting MagicDNS to forward the query to 10.0.x.x. MagicDNS cannot do this because of it is the Network Extension sending to a Tailscale IP address.
3. turning off "Override local DNS" and adding 10.0.x.x manually to the Settings > Network > DNS means that the MacOS resolver is sending to 10.0.x.x, which is fine.
4. unfortunately turning off "Override local DNS" broke that customer's Windows systems, because they were relying on Tailscale's DNS config.

**Comment by crawshaw** [comment] 2021-06-22 20:37
OK that's a more subtle bug than the one we discussed in the last meeting. I believe the upgrade is causing a problem there, as we used to push global DNS into the OS resolver but now we push quad100. But luckily I believe it is fixed by the same plan of making DNS to tailscale devices work from the networkextension.

**Comment by DentonGentry** [comment] 2021-06-22 20:40
Separately, I'd like to reconsider pushing 100.100.100.100. I'd prefer we push the real address to the OS resolver whenever possible. However that is a topic for another day.

**Comment by crawshaw** [comment] 2021-06-22 20:44
On your aside topic: do we push the real DNS IP if all split DNS entries are removed and MagicDNS is turned off? (Any of those settings require replacing the DNS IP with quad100.)

**Comment by stevelitras** [comment] 2021-06-22 22:39
I'm one of the customers running into this - I turned off override local DNS, and it solved the problem of people being able to resolve most addresses, but obviously they can't resolve our "internal" address (the RFC1918 space we've allocated for our AWS env). I generally don't like to have users touch the network configuration (way too easy to cause more trouble than help), so instead, I'll ask - what other data that I can provide would help you guys figure what the root cause is?

**Comment by DentonGentry** [comment] 2021-06-22 23:11
At this point I think the root cause is understood: a series of unfortunate events led to pushing a DNS config that expected Magic DNS to do the impossible.

We are actively working on a code change which will allow Magic DNS to forward DNS queries in this environment, and make the impossible be possible.

**Closed** 2021-06-23 23:04 UTC
Labels: dns
