### ISSUE TITLE
Tailscale incorrectly detecting systemd-resolved

### ISSUE THREAD

**Issue by BluishHumility** [tailscale/tailscale#9687] opened 2023-10-06 15:59 UTC
### What is the issue?

I have an EndeavourOS VM which has been running Tailscale for a few months. It uses a remote exit node and generally works great.

At some point over the last few weeks it stopped overwriting `/etc/resolv.conf` when the system would start up. From what I understand from reading through forums and issue threads, it appears to be detecting `systemd-resolved` is in use, although I do not use it--I use NetworkManager.

```
❯ systemctl status systemd-resolved
○ systemd-resolved.service - Network Name Resolution
     Loaded: loaded (/usr/lib/systemd/system/systemd-resolved.service; disabled; preset: enabled)
     Active: inactive (dead)
       Docs: man:systemd-resolved.service(8)
             man:org.freedesktop.resolve1(5)
             https://www.freedesktop.org/wiki/Software/systemd/writing-network-configuration-managers
             https://www.freedesktop.org/wiki/Software/systemd/writing-resolver-clients

```
The bottom of my `tailscale status` output has these lines:
```
# Health check:
#     - dns-manager: systemd-resolved and NetworkManager are wired together incorrectly; MagicDNS will probably not work. For more info, see https://tailscale.com/s/resolved-nm
#     - dns-os: setLinkDNS: Unit dbus-org.freedesktop.resolve1.service not found.
#     - dns: setLinkDNS: Unit dbus-org.freedesktop.resolve1.service not found.
```
I am able to work around the issue by manually overwriting `/etc/resolv.conf` like this:
```
❯ echo 'nameserver 100.100.100.100' | sudo tee /etc/resolv.conf
```
After overwriting `resolv.conf`, everything works great. The exit node is in use and I can access local resources on the LAN of the exit node, etc.

It's no huge bother to manually overwrite `/etc/resolv.conf` at boot, but I just can't seem to figure out why it is needed. When I first set up the VM Tailscale was working without this intervention. I thought I would reach out in case there is something I am missing, or perhaps I have run into a bug.

### Steps to reproduce

The issue recurs at each boot. The Tailscale service starts automatically, but fails to overwrite `/etc/resolv.conf`.

### Are there any recent changes that introduced the issue?

I believe I noticed this change after taking a normal system update and rebooting. I wish I checked if Tailscale was one of the packages that was updated, but I did not think of it at the time.

I can't think of any other changes that would have affected the networking configuration, but it is possible I changed something inadvertently.

### OS

Linux

### OS version

EndeavourOS

### Tailscale version

1.50.0

### Other software

EndeavourOS is a guest in VMware Workstation 17 Player, using NAT to share the host's IP address. This configuration has not changed between when it was working normally and now.

### Bug report

BUG-51974eeedf1d8696323400a1f5c94dbacfc0c1c17f9b563e4ce7f7990d6378f1-20231006155910Z-8290586189d4db1f

**Comment by bradfitz** [comment] 2023-10-06 16:16
In its happy state, Tailscale does NOT want to overwrite /etc/resolv.conf. (see https://tailscale.com/blog/sisyphean-dns-client-linux/ for all the gory details)

What's happening is that by you disabling systemd-resolved (the happy path) and overwriting /etc/resolv.conf manually, sometimes Tailscale starts and sees no clue via dbus or /etc/resolv.conf who's managing DNS on the machine and decides it has to go into the super legacy fight-for-overwriting-the-file mode.

But then your NetworkManager (which still thinks it's using systemd) overwrites /etc/resolv.conf later and when Tailscale starts up it says, "Oh, huh... NetworkManager says it's using systemd but systemd is disabled." and goes into a weird state where there's no good option.

Did you manually modify the EndeavourOS DNS configuration by disabling systemd-resolved?

**Comment by BluishHumility** [comment] 2023-10-06 16:40
No, by default `systemd-resolved` is not enabled in EndeavourOS (following the Arch Linux default). Since it is part of systemd, it is there if people want to set it up but it requires additional configuration (you have to replace `/etc/resolv.conf` with a symlink to `/run/systemd/resolve/stub-resolv.conf`, then other configuration if you want to set DNS servers).

At each boot, before I manually overwrite `/etc/resolv.conf` it looks like this:

```
File: /etc/resolv.conf
# Generated by NetworkManager
search localdomain
nameserver 192.168.204.2
```

From what I understand of the blog post you shared, it seems like this should be getting overwritten (as it historically has been) because of the way the file ownership is identified by the comment, and the fact that `systemd-resolved` is not in use. Or is there a race condition to write to the file?

**Comment by bradfitz** [comment] 2023-10-06 17:02
Based on your bug report, I see that sometimes Tailscale starts up and see that it's "# Generated by NetworkManager" and thus tries to go down the path of configuring DNS via NetworkManager instead but then hits errors around lack of systemd-resolved (NetworkManager sometimes works with systemd-resolved and it seems like it's detecting that's the case)

Specifically, the DNS properties it sometimes discovers:

```
2023-10-04 17:24:55.230196878 +0000 UTC: dns: ResolvConfMode error: Unit dbus-org.freedesktop.resolve1.service not found.
2023-10-04 17:24:55.230313247 +0000 UTC: dns: [rc=nm resolved=nss nm-resolved=yes nm-safe=no resolv-conf-mode=error ret=systemd-resolved]
2023-10-04 17:24:55.23035853 +0000 UTC: dns: using "systemd-resolved" mode
```

(cc @danderson)

**Comment by BluishHumility** [comment] 2023-10-06 18:06
Yes, I guess I'm not sure where it is getting the `systemd-resolved` from but it I agree that it appears to be detecting that somewhere.

Here are the first few lines from the journal at boot:

```
journalctl -b -u tailscaled
Oct 06 12:55:54 eos-vm systemd[1]: Starting Tailscale node agent...
Oct 06 12:55:54 eos-vm tailscaled[670]: logtail started
Oct 06 12:55:54 eos-vm tailscaled[670]: Program starting: v1.50.0, Go 1.21.1: []string{"/usr/sbin/tailscaled", "--cleanup"}
Oct 06 12:55:54 eos-vm tailscaled[670]: LogID: 51974eeedf1d8696323400a1f5c94dbacfc0c1c17f9b563e4ce7f7990d6378f1
Oct 06 12:55:54 eos-vm tailscaled[670]: logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
Oct 06 12:55:54 eos-vm tailscaled[670]: dns: ResolvConfMode error: Unit dbus-org.freedesktop.resolve1.service not found.
Oct 06 12:55:54 eos-vm tailscaled[670]: dns: [rc=nm resolved=nss nm-resolved=yes nm-safe=no resolv-conf-mode=error ret=systemd-resolved]
Oct 06 12:55:54 eos-vm tailscaled[670]: dns: using "systemd-resolved" mode
[...]
```

The only clue I see before it mentions there is a ResolvConfMode error is it using the referenced $STATE_DIRECTORY, `/var/lib/tailscale`. As a shot in the dark, I tried moving `/var/lib/tailscale` to backup but it didn't change anything--just made me sign in again and recreated the directory.

Please let me know if there is anything other information I can provide that would be useful for troubleshooting the issue.

**Comment by bradfitz** [comment] 2023-10-12 19:56
> The only clue I see before it mentions there is a ResolvConfMode error is it mentions using the $STATE_DIRECTORY

You're comparing the output from two different modes that tailscaled is being run in:

```
Program starting: v1.50.0, Go 1.21.1: []string{"/usr/sbin/tailscaled", "--cleanup"}
```
vs
```
Program starting: v1.50.0, Go 1.21.1: []string{"/usr/sbin/tailscaled", ....
```

(without cleanup)

The systemd unit runs it twice, with cleanup happening after the process exits. (doing cleanup in case it crashes)

**Comment by BluishHumility** [comment] 2023-10-12 20:39
I'm afraid I don't follow what you are saying. Where is the comparison you mentioned?

I was looking through the journal at NetworkManager output, and it does seem to observe Tailscale starting up although I'm not sure the significance of the log entries or if they are normal or not.

~~~
Oct 12 08:23:30 eos-vm NetworkManager[626]: <info>  [1697113410.3499] device (tailscale0): state change: unmanaged -> unavailable (reason 'connection-assumed', sys-iface-state: 'external')
Oct 12 08:23:30 eos-vm NetworkManager[626]: <info>  [1697113410.3510] device (tailscale0): state change: unavailable -> disconnected (reason 'connection-assumed', sys-iface-state: 'external')
Oct 12 08:23:30 eos-vm NetworkManager[626]: <info>  [1697113410.3663] device (tailscale0): Activation: starting connection 'tailscale0' (c91fa467-8c7d-4699-8216-d92210433f04)
Oct 12 08:23:30 eos-vm NetworkManager[626]: <info>  [1697113410.3664] device (tailscale0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'external')
Oct 12 08:23:30 eos-vm NetworkManager[626]: <info>  [1697113410.3666] device (tailscale0): state change: prepare -> config (reason 'none', sys-iface-state: 'external')
Oct 12 08:23:30 eos-vm NetworkManager[626]: <info>  [1697113410.3667] device (tailscale0): state change: config -> ip-config (reason 'none', sys-iface-state: 'external')
Oct 12 08:23:30 eos-vm NetworkManager[626]: <info>  [1697113410.3675] device (tailscale0): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'external')
Oct 12 08:23:30 eos-vm NetworkManager[626]: <info>  [1697113410.3686] device (tailscale0): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'external')
Oct 12 08:23:30 eos-vm NetworkManager[626]: <info>  [1697113410.3688] device (tailscale0): state change: secondaries -> activated (reason 'none', sys-iface-state: 'external')
Oct 12 08:23:30 eos-vm NetworkManager[626]: <info>  [1697113410.3693] device (tailscale0): Activation: successful, device activated.
~~~

I still have not figured out why Tailscale thinks `systemd-resolved` is in use.

I see this issue has a `waiting-for-info` tag applied to it now. I'm happy to pass along anything that would be helpful. Are there any logs I can gather or diagnostics I can run that would be useful for troubleshooting?

**Comment by DentonGentry** [comment] 2023-10-15 07:47
I installed EndeavourOS and can reproduce the symptoms. 100.100.100.100 does not get written to /etc/resolv.conf

```
2023-10-15 07:15:13.976800013 +0000 UTC: dns: ResolvConfMode error: Unit dbus-org.freedesktop.resolve1.service not found.
2023-10-15 07:15:13.976858064 +0000 UTC: dns: [rc=nm resolved=nss nm-resolved=yes nm-safe=no resolv-conf-mode=error ret=systemd-resolved]
2023-10-15 07:15:13.976894569 +0000 UTC: dns: using "systemd-resolved" mode
2023-10-15 07:15:13.977045926 +0000 UTC: creating dns cleanup: route ip+net: no such network interface
2023-10-15 07:15:14.6603932 +0000 UTC: dns: ResolvConfMode error: Unit dbus-org.freedesktop.resolve1.service not found.
2023-10-15 07:15:14.660480142 +0000 UTC: dns: [rc=nm resolved=nss nm-resolved=yes nm-safe=no resolv-conf-mode=error ret=systemd-resolved]
2023-10-15 07:15:14.660533774 +0000 UTC: dns: using "systemd-resolved" mode
2023-10-15 07:15:14.660725268 +0000 UTC: creating dns cleanup: route ip+net: no such network interface
2023-10-15 07:15:15.313752126 +0000 UTC: dns: ResolvConfMode error: Unit dbus-org.freedesktop.resolve1.service not found.
```

The detection of whether NetworkManager is using `systemd-resolved` happens at:
https://github.com/tailscale/tailscale/blob/56ebcd1ed4a4e6f89a009e5868d27f5f9e9bd807/net/dns/manager_linux.go#L299-L319

From what I can see, the Mode property should be returning "default" but the code is behaving like it is returning "systemd-resolved"

```
[dgentry@endeavour ~]$ busctl call org.freedesktop.NetworkManager /org/freedesktop/NetworkManager/DnsManager org.freedesktop.DBus.Properties Get ss org.freedesktop.NetworkManager.DnsManager Mode
v s "default"
```

**Comment by DentonGentry** [comment] 2023-10-15 22:51
Is it possible that though EndeavourOS has always used NetworkManager, that recently it stopped using `systemd-resolved` behind the scenes by default? https://forum.endeavouros.com/t/bad-experience-with-systemd-resolved/27437 seems to imply that `systemd-resolved` used to be the default.

The root cause appears to be that indeed, tailscaled wasn't figuring out that the combination of NetworkManager-but-not-systemd-resolved needed to use direct mode. It was trying to use the nonexistent systemd-resolved instead.

I can't figure out how EndeavourOS ever worked, unless it did use systemd-resolved until a recent update.

https://github.com/tailscale/tailscale/pull/9812 proposes a fix. I've tried it on an EndeavourOS system and it writes `100.100.100.100` to `/etc/resolv.conf`

**Closed** 2023-10-16 00:12 UTC
Labels: OS-linux, L2 Few, P2 Aggravating, T5 Usability, dns
