### ISSUE TITLE
OpenVZ hosted exit node on one provider not working

### ISSUE THREAD

**Issue by xindirama** [tailscale/tailscale#2448] opened 2021-07-18 09:52 UTC
I am trying Tailscale for the first time, and currently have only two devices configured. I have multiple other VPNs working on this Android, but when I turn on Tailscale with exit node set to my Buster server, zero network traffic seems to get out to the public net. I am however able to ping the Android from the server. These Tailscale devices are authenticated with this Github account.

The only visible error I can see is on the Buster server:

`netcheck: probePortMapServices: failed to look up gateway address`

when I run systemctl status tailscaled.service

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3eqj5)

**Comment by DentonGentry** [comment] 2021-07-18 12:24
In https://login.tailscale.com/admin/machines to the far right is a menu which can be pulled up by clicking on the three dots. One of the selections is Review Route Settings. Could you check that the routes and the exit node selection have both been approved?

<img width="547" alt="Screen Shot 2021-07-18 at 5 22 11 AM" src="https://user-images.githubusercontent.com/1140756/126066876-9ea881da-b005-445f-ac3f-dd032a3cc36a.png">

**Comment by xindirama** [comment] 2021-07-18 14:18
On the server, "use as exit node" is on. On both server and Android, under "subnet routes" there is a message "This machine does not expose any routes" and there is nothing to approve/turn on.

**Comment by xindirama** [comment] 2021-07-20 07:17
Another data point: today I tried a different Linux server on a KVM VM as an exit node, it works fine, no errors at all in systemctl status tailscaled.service. The other VM that is the subject of this bug report is an OpenVZ VM, and is still not working.

**Comment by DentonGentry** [comment] 2021-07-20 21:34
I don't immediately see what is going wrong with the OpenVZ server. If you can, what would be most helpful:
- have the LineageOS device use the OpenVZ server as an exit node, and verify that it still isn't working
- On the OpenVZ node, run "tailscale bugreport" and paste the text here.

This will give us a specific timestamp to focus on.

**Comment by xindirama** [comment] 2021-07-21 07:44
Yeah, definitely still not working. # tailscale bugreport
BUG-e9295462fa86c942e737d55eef93f0387a1f07c956594ae113ceff42080d4c88-20210721074253Z-d3f56ae0567bd12b
And one further bit, I rounded up another OpenVZ server from a different provider, and it works. So it seems not all OpenVZ configurations are equal here.

**Comment by DentonGentry** [comment] 2021-07-21 13:10
For the OpenVZ system which is not working: right before the bugreport we see it repeatedly trying to establish a direct tunnel to the LineageOS, but never succeeding.

We also see:
```
2021-07-21 03:40:47.80907455 -0400 -0400: [4DgRO] - Sending keepalive packet
2021-07-21 03:40:51.366750242 -0400 -0400: IPv4 packet with disallowed source address from [4DgRO]
2021-07-21 03:40:59.029611589 -0400 -0400: [4DgRO] - Sending keepalive packet
2021-07-21 03:41:03.670040022 -0400 -0400: IPv4 packet with disallowed source address from [4DgRO]
2021-07-21 03:41:05.775521943 -0400 -0400: IPv4 packet with disallowed source address from [4DgRO]
2021-07-21 03:41:05.775655903 -0400 -0400: IPv4 packet with disallowed source address from [4DgRO]
2021-07-21 03:41:06.334981995 -0400 -0400: IPv4 packet with disallowed source address from [4DgRO]
2021-07-21 03:41:06.466415096 -0400 -0400: IPv4 packet with disallowed source address from [4DgRO]
2021-07-21 03:41:06.466490397 -0400 -0400: [RATELIMIT] format("IPv4 packet with disallowed source address from %v")
```

[4DgRO] is the LineageOS device.

This message comes from https://github.com/tailscale/wireguard-go/blob/f68089439238e5ea3bb639d8100113fe5ae71955/device/receive.go#L451

Actually https://git.zx2c4.com/wireguard-go/tree/device/receive.go#n451 since we no longer use the Tailscale fork of wireguard-go, but I can't get a permalink to a specific version of the file there.

Since the behavior varies by OpenVZ provider, and the LineageOS device works with the other OpenVZ provider, I guess we need to assume that the problem is with the provider. Could they be rewriting source IP addresses? Surely not, there wouldn't be a reason to do that.

**Comment by tshpr** [comment] 2021-07-23 13:58
Hello guys,

I work as a technician for the provider, where this is not working. I have noticed the following difference between the two VPS.

This is the kernel on a working VPS(I bought one from the same provider, where its working):
Linux vps.server.com 4.19.0 #1 SMP Thu Apr 22 16:18:59 MSK 2021 x86_64 GNU/Linux

This is the kernel on the broken VPS:
Linux brokenvps 3.10.0-1127.18.2.vz7.163.46 #1 SMP Fri Nov 20 21:47:55 MSK 2020 i686 GNU/Linux


Our setup is pretty default, we do not do source iP rewriting - this is not a NAT VPS. For example, "curl -4 ifconfig.co" does clearly show the VPS IP.

**Comment by DentonGentry** [comment] 2021-07-23 18:53
Linux 3.10 should work.

@xindirama Are you comfortable running tcpdump on the OpenVZ instance to try to diagnose `IPv4 packet with disallowed source address from X` ?

You would need to:
1. use `/sbin/ip addr show` to find the name of the network interface. It is probably veth0.
2. run `tcpdump -i veth0 -n udp port 41641`
3. try to connect from LineageOS

We're trying to identify the IP address that Wireguard sees, and why it isn't what Wireguard expects.

----

Alternately, @tshpr  I'm willing to set up and account on that provider and try it, so it will be easier to debug. If you're not comfortable putting it on the public issue please email to support@tailscale.com.

**Comment by DentonGentry** [comment] 2021-07-25 00:32
@tshpr set up an instance for us to use, now running `Linux tailscale 3.10.0-1127.18.2.vz7.163.46 #1 SMP Fri Nov 20 21:47:55 MSK 2020 x86_64 GNU/Linux` with Debian.

@xindirama your instance has a /dev/net/tun interface, mine does not currently. Did you sign up for any kind of VPN or OpenVPN option?

**Comment by tshpr** [comment] 2021-07-25 09:02
I have enabled tun, ppp and fuse for your instance. @DentonGentry

**Comment by DentonGentry** [comment] 2021-07-25 13:20
Great!

I enabled exit node on the instance and am able to use it. whatismyipaddress.com shows my IPv4 address as that of the OpenVZ instance, in the Dallas area, but isn't able to determine an IPv6 address (and ipv6 should work from what I can see).

I'll poke around at IPv6 next, that may be part of the issue that @xindirama is seeing.

**Comment by DentonGentry** [comment] 2021-07-25 13:59
One thing of note is that the default route is zero:
```
root@tailscale:~# cat /proc/net/route
Iface	Destination	Gateway 	Flags	RefCnt	Use	Metric	Mask		MTU	Window	IRTT
venet0	00000000	00000000	0001	0	0	0	00000000	0	0	0
venet0	00D28AC0	00000000	0001	0	0	0	00FEFFFF	0	0	0
root@tailscale:~# netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         0.0.0.0         0.0.0.0         U         0 0          0 venet0
192.138.210.0   0.0.0.0         255.255.254.0   U         0 0          0 venet0
root@tailscale:~#
```

We parse /proc/net/route to figure out which interface(s) MagicSock should send probes to, trying to find a direct path. I think the gateway address being zero leads to:

```
Jul 25 15:23:40 tailscale tailscaled[320]: netcheck: probePortMapServices: failed to look up gateway address
Jul 25 15:24:03 tailscale tailscaled[320]: netcheck: probePortMapServices: failed to look up gateway address
Jul 25 15:24:24 tailscale tailscaled[320]: netcheck: probePortMapServices: failed to look up gateway address
Jul 25 15:24:48 tailscale tailscaled[320]: netcheck: probePortMapServices: failed to look up gateway address
```

**Comment by xindirama** [comment] 2021-07-26 07:23
Hi guys, sorry I dropped out of the loop, did not check the e-mail account this goes to for a couple days....

> @xindirama your instance has a /dev/net/tun interface, mine does not currently. Did you sign up for any kind of VPN or OpenVPN option?

I have Tinc VPN running on almost all my machines, up until now. I have other machines where Tinc and Tailscale both work, including the other OpenVZ node, so I would not think that Tinc is stepping on Tailscale.

**Comment by xindirama** [comment] 2021-07-26 07:33
> I'll poke around at IPv6 next, that may be part of the issue that @xindirama is seeing.

My router claims to be handing out DHCPv6 leases to several machines on my network (which I find surprising, I doubt the ISP here is supporting IPv6) but none of them are the Android devices where this exit node was failing.

**Comment by xindirama** [comment] 2021-07-26 08:06
> * run `tcpdump -i veth0 -n udp port 41641`
> * try to connect from LineageOS

Odd (not that I have played with tcpdump enough to be any judge of "odd") but when I connect from the Android there is frenzy of activity, some of them with my residential IPv4 address, some with other IPv4 addresses, and even some IPv6 addresses. Then when I switch Android Tailscale to another exit node, the traffic continues for another minute or two, finally tapering off to absolutely nothing. Is this expected behavior?

**Comment by DentonGentry** [comment] 2021-07-26 13:13
That activity sounds like MagicSock probing for a connection. It will try all IP addresses, and fall back to the DERP relay if necessary.

**Comment by DentonGentry** [comment] 2021-07-26 13:16
`Jul 25 15:23:40 tailscale tailscaled[320]: netcheck: probePortMapServices: failed to look up gateway address` is from https://github.com/tailscale/tailscale/blob/33770895831d5b9b7cff0345b6769dc9b4da993b/net/interfaces/interfaces_linux.go#L39

It is looking for a typical residential IP setup, with a default route pointing to a Private IP address. For cloud nodes like this OpenVZ node the nexthop IP is often zero, they are set up as though they sit directly on the Internet (generally with a firewall within the cloud infrastructure).

I don't think this message is actually harmful, and we should make it less scary-sounding.

**Comment by DentonGentry** [comment] 2021-07-27 01:25
Following up about likelyHomeRouterIPLinux and `probePortMapServices: failed to look up gateway address`: that code is looking for a place to send NAT-PMP and UPnP requests to, which residential gateways often support but cloud firewalls never do. Though the message is somewhat scary it shouldn't impact the OpenVZ node operation.

**Comment by bradfitz** [comment] 2021-07-27 02:47
iptables looks busted on that machine:

```
2021-07-23 06:23:16.057117304 -0400 -0400: authReconfig: ra=false dns=true 0x01: setting up nat/ts-postrouting: running [/usr/sbin/iptables -t nat -N ts-postrouting --wait]: exit status 4: iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
2021-07-23 06:24:26.512499818 -0400 -0400: authReconfig: ra=false dns=true 0x01: setting up nat/ts-postrouting: running [/usr/sbin/iptables -t nat -N ts-postrouting --wait]: exit status 4: iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
2021-07-23 06:30:54.769131503 -0400 -0400: authReconfig: ra=false dns=true 0x01: setting up nat/ts-postrouting: running [/usr/sbin/iptables -t nat -N ts-postrouting --wait]: exit status 4: iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
2021-07-23 06:31:48.981044945 -0400 -0400: authReconfig: ra=false dns=true 0x01: setting up nat/ts-postrouting: running [/usr/sbin/iptables -t nat -N ts-postrouting --wait]: exit status 4: iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
2021-07-23 09:14:46.559998017 -0400 -0400: router: failed to delete legacy rule, continuing anyway: checking for [-m comment --comment tailscale -o eth0 -j MASQUERADE] in nat/POSTROUTING: running [/usr/sbin/iptables -t nat -C POSTROUTING -m comment --comment tailscale -o eth0 -j MASQUERADE --wait]: exit status 2: iptables v1.8.2 (nf_tables): Chain 'MASQUERADE' does not exist
Try `iptables -h' or 'iptables --help' for more information.
2021-07-23 09:14:47.207167417 -0400 -0400: health("overall"): error: state=Starting, wantRunning=true
2021-07-23 09:14:47.300985437 -0400 -0400: authReconfig: ra=false dns=true 0x01: setting up nat/ts-postrouting: running [/usr/sbin/iptables -t nat -N ts-postrouting --wait]: exit status 4: iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
2021-07-23 09:14:47.301084131 -0400 -0400: health("router"): error: setting up nat/ts-postrouting: running [/usr/sbin/iptables -t nat -N ts-postrouting --wait]: exit status 4: iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
2021-07-23 09:14:47.301128246 -0400 -0400: control: controlclient: restarting map request for "router" health change to new state: setting up nat/ts-postrouting: running [/usr/sbin/iptables -t nat -N ts-postrouting --wait]: exit status 4: iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
2021-07-24 08:09:35.941504147 -0400 -0400: authReconfig: ra=false dns=true 0x01: setting up nat/ts-postrouting: running [/usr/sbin/iptables -t nat -N ts-postrouting --wait]: exit status 4: iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
2021-07-24 08:27:20.63901694 -0400 -0400: authReconfig: ra=false dns=true 0x01: setting up nat/ts-postrouting: running [/usr/sbin/iptables -t nat -N ts-postrouting --wait]: exit status 4: iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
2021-07-25 06:35:56.523129703 -0400 -0400: authReconfig: ra=false dns=true 0x01: setting up nat/ts-postrouting: running [/usr/sbin/iptables -t nat -N ts-postrouting --wait]: exit status 4: iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
```

**Comment by DentonGentry** [comment] 2021-07-27 04:42
The instance created for us behaves differently:

```
root@tailscale:~# /usr/sbin/iptables -t nat -N ts-postrouting --wait
root@tailscale:~# echo $?
0
root@tailscale:~# iptables -v
iptables v1.8.2 (legacy): no command specified
root@tailscale:~#
```

The customer-reported instance appears to be using nftables, our instance is not.

**Comment by xindirama** [comment] 2021-07-27 04:51
```
# iptables --version
iptables v1.8.2 (nf_tables)
```

Perhaps because it is nf_tables?

**Comment by tshpr** [comment] 2021-07-27 10:55
> The instance created for us behaves differently:
> 
> ```
> root@tailscale:~# /usr/sbin/iptables -t nat -N ts-postrouting --wait
> root@tailscale:~# echo $?
> 0
> root@tailscale:~# iptables -v
> iptables v1.8.2 (legacy): no command specified
> root@tailscale:~#
> ```
> 
> The customer-reported instance appears to be using nftables, our instance is not.

You should be able to install the nftables service and translate the rules?

**Comment by bradfitz** [comment] 2021-07-27 15:12
@danderson, thoughts?

**Comment by DentonGentry** [comment] 2021-08-01 00:15
The finding a few days ago is that my OpenVZ instance, on the same provider as reported in this bug, was able to function as an exit node for IPv4. IPv6 was not working, but that turns out to be unrelated to this issue (it is a regression related to Android 12, apparently: https://github.com/tailscale/tailscale/issues/2449)

This did not match the originally reported behavior that the exit node did not function at all.

We noted that my instance was using legacy iptables, where the user-reported instance was using the nf_tables variant.

----

If I change my instance to use nf_tables, my exit node stops working. I cannot contact anything on the Internet, matching the originally reported behavior.

```
systemctl stop tailscaled
update-alternatives --set iptables /usr/sbin/iptables-nft
update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
systemctl start tailscaled
```

Checking that it worked:
```
root@tailscale:~# iptables --version
iptables v1.8.2 (nf_tables)
```

----

If I switch back to legacy mode and restart tailscaled to make it configure everything again, the exit node starts working again for IPv4.

```
systemctl stop tailscaled
update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
systemctl start tailscaled
```

Checking that it worked:
```
root@tailscale:~# iptables --version
iptables v1.8.2 (legacy)
root@tailscale:~#
```

----

@xindirama I think a way to work around the issue is to use the `update-alternatives` commands shown above to set iptables to legacy mode.

----

Next step is to focus on nf_tables.

If I use legacy mode and get the exit node working, switching to nf_tables mode often continues to work.

If I set it to nf_tables and reboot, the exit node is always broken. It remains broken until I switch to legacy mode, and then the exit node will start working and continue working even after switching back to nf_tables.

 It seems like something left behind in a legacy rule is important, and allows the exit node to work.

**Comment by DentonGentry** [comment] 2021-08-01 00:59
In nf_tables mode:
```
root@tailscale:~# iptables -L -v -n
Chain INPUT (policy ACCEPT 14192 packets, 2042K bytes)
 pkts bytes target     prot opt in     out     source               destination
14181 2041K ts-input   all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
 5596  492K ts-forward  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 3700 packets, 375K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain ts-input (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  lo     *       100.126.13.128       0.0.0.0/0
    0     0 RETURN     all  --  !tailscale0 *       100.115.92.0/23      0.0.0.0/0
    0     0 DROP       all  --  !tailscale0 *       100.64.0.0/10        0.0.0.0/0

Chain ts-forward (1 references)
 pkts bytes target     prot opt in     out     source               destination
 5596  492K MARK       all  --  tailscale0 *       0.0.0.0/0            0.0.0.0/0            MARK set 0x40000
 5596  492K ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40000
    0     0 DROP       all  --  *      tailscale0  100.64.0.0/10        0.0.0.0/0
    0     0 ACCEPT     all  --  *      tailscale0  0.0.0.0/0            0.0.0.0/0
# Warning: iptables-legacy tables present, use iptables-legacy to see them

root@tailscale:~# iptables-legacy -L -v -n
Chain INPUT (policy ACCEPT 14328 packets, 2062K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 5598 packets, 493K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 3818 packets, 389K bytes)
 pkts bytes target     prot opt in     out     source               destination
root@tailscale:~#
```

---

In iptables-legacy mode:

```
root@tailscale:~# iptables -L -v -n
Chain INPUT (policy ACCEPT 900 packets, 866K bytes)
 pkts bytes target     prot opt in     out     source               destination
  900  866K ts-input   all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
 1315  856K ts-forward  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 622 packets, 113K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain ts-forward (1 references)
 pkts bytes target     prot opt in     out     source               destination
  795  794K MARK       all  --  tailscale0 *       0.0.0.0/0            0.0.0.0/0            MARK set 0x40000
  795  794K ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40000
    0     0 DROP       all  --  *      tailscale0  100.64.0.0/10        0.0.0.0/0
  520 62850 ACCEPT     all  --  *      tailscale0  0.0.0.0/0            0.0.0.0/0

Chain ts-input (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  lo     *       100.126.13.128       0.0.0.0/0
    0     0 RETURN     all  --  !tailscale0 *       100.115.92.0/23      0.0.0.0/0
    0     0 DROP       all  --  !tailscale0 *       100.64.0.0/10        0.0.0.0/0
root@tailscale:~#
```

---

nf_tables mode after having used legacy mode looks identical:
```
root@tailscale:~# iptables -L -v -n
Chain INPUT (policy ACCEPT 21999 packets, 5109K bytes)
 pkts bytes target     prot opt in     out     source               destination
 1571  581K ts-input   all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy ACCEPT 7857 packets, 3384K bytes)
 pkts bytes target     prot opt in     out     source               destination
 1323  411K ts-forward  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 9951 packets, 2547K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain ts-input (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  lo     *       100.126.13.128       0.0.0.0/0
    0     0 RETURN     all  --  !tailscale0 *       100.115.92.0/23      0.0.0.0/0
    0     0 DROP       all  --  !tailscale0 *       100.64.0.0/10        0.0.0.0/0

Chain ts-forward (1 references)
 pkts bytes target     prot opt in     out     source               destination
  779  195K MARK       all  --  tailscale0 *       0.0.0.0/0            0.0.0.0/0            MARK set 0x40000
  779  195K ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40000
    0     0 DROP       all  --  *      tailscale0  100.64.0.0/10        0.0.0.0/0
  544  215K ACCEPT     all  --  *      tailscale0  0.0.0.0/0            0.0.0.0/0
# Warning: iptables-legacy tables present, use iptables-legacy to see them

root@tailscale:~# iptables-legacy -L -v -n
Chain INPUT (policy ACCEPT 1914 packets, 651K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 1475 packets, 422K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 1488 packets, 322K bytes)
 pkts bytes target     prot opt in     out     source               destination
root@tailscale:~#
```

**Comment by DentonGentry** [comment] 2021-08-01 01:15
NAT table in nftables mode:
```
root@tailscale:~# iptables -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ts-postrouting  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain ts-postrouting (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40000
# Warning: iptables-legacy tables present, use iptables-legacy to see them

root@tailscale:~# iptables-legacy -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 1657 packets, 108K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 29 packets, 2907 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 42 packets, 4551 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 1670 packets, 109K bytes)
 pkts bytes target     prot opt in     out     source               destination
root@tailscale:~#
```

----

NAT table in iptables-legacy mode:
```
root@tailscale:~# iptables -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 78 packets, 5024 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 2 packets, 136 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 6 packets, 458 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 6 packets, 458 bytes)
 pkts bytes target     prot opt in     out     source               destination
   82  5346 ts-postrouting  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain ts-postrouting (1 references)
 pkts bytes target     prot opt in     out     source               destination
   76  4888 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40000
root@tailscale:~#
```

----

NAT table in nf_tables mode after having used legacy mode looks identical:
```
root@tailscale:~# iptables -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ts-postrouting  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain ts-postrouting (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40000
# Warning: iptables-legacy tables present, use iptables-legacy to see them

root@tailscale:~# iptables-legacy -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 16 packets, 960 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 1 packets, 60 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 24 packets, 1873 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 39 packets, 2773 bytes)
 pkts bytes target     prot opt in     out     source               destination
root@tailscale:~#
```

**Comment by xindirama** [comment] 2021-08-01 08:11
> I think a way to work around the issue is to use the update-alternatives commands shown above to set iptables to legacy mode

Sorry to report, just tried that: set ip(6)tables to legacy mode, restarted Tailscale, Tailscale up/down, rebooted the whole server: still no functioning exit node.

**Comment by xindirama** [comment] 2021-08-01 11:01
```
# iptables -t nat -L -n -v
iptables v1.8.2 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?) Perhaps iptables or your kernel needs to be upgraded
```
does not look good

**Comment by DentonGentry** [comment] 2021-08-01 14:18
That is definitely a problem. Here are all of the modules loaded on my OpenVZ instance. `nf_nat`, `nf_nat_ipv4`, and `nf_nat_masquerade_ipv4` appear to be key ones for that table.

```
root@tailscale:~# lsmod
Module                  Size  Used by
iptable_mangle          4242  -2
nft_chain_route_ipv4    4242  -2
nft_chain_nat_ipv4      4242  -2
xt_mark                 4242  -2
iptable_nat             4242  -2
nf_conntrack_ipv4       4242  -2
nf_defrag_ipv4          4242  -2 nf_conntrack_ipv4
nf_nat_ipv4             4242  -2 nft_chain_nat_ipv4,iptable_nat
ipt_MASQUERADE          4242  -2
nf_nat_masquerade_ipv4  4242  -2 ipt_MASQUERADE
nf_nat                  4242  -2 nf_nat_ipv4,nf_nat_masquerade_ipv4
nf_conntrack            4242  -2 nf_nat,nf_nat_ipv4,nf_nat_masquerade_ipv4,nf_conntrack_ipv4
nf_tables_ipv6          4242  -2
xt_comment              4242  -2
nft_meta                4242  -2
nft_counter             4242  -2
nft_compat              4242  -2
nf_tables_ipv4          4242  -2
nf_tables               4242  -2 nf_tables_ipv4,nf_tables_ipv6,nft_chain_nat_ipv4,nft_compat,nft_meta,nft_chain_route_ipv4,nft_counter
ipt_REJECT              4242  -2
nf_reject_ipv4          4242  -2 ipt_REJECT
xt_multiport            4242  -2
binfmt_misc             4242  -2
ip6table_filter         4242  -2
ip6_tables              4242  -2 ip6table_filter
iptable_filter          4242  -2
ip_tables               4242  -2 iptable_filter,iptable_mangle,iptable_nat
ebt_among               4242  -2
cls_u32                 4242  -2
sch_sfq                 4242  -2
sch_htb                 4242  -2
devlink                 4242  -2
8021q                   4242  -2
garp                    4242  -2 8021q
mrp                     4242  -2 8021q
tun                     4242  -2
ip_set                  4242  -2
nfnetlink               4242  -2 nf_tables,ip_set,nft_compat
ebtable_filter          4242  -2
ebtables                4242  -2 ebtable_filter
sunrpc                  4242  -2
dm_mirror               4242  -2
dm_region_hash          4242  -2 dm_mirror
dm_log                  4242  -2 dm_region_hash,dm_mirror
dm_mod                  4242  -2 dm_log,dm_mirror
ipmi_ssif               4242  -2
intel_powerclamp        4242  -2
coretemp                4242  -2
intel_rapl              4242  -2
iTCO_wdt                4242  -2
iosf_mbi                4242  -2 intel_rapl
iTCO_vendor_support     4242  -2 iTCO_wdt
kvm_intel               4242  -2
kvm                     4242  -2 kvm_intel
irqbypass               4242  -2 kvm
crc32_pclmul            4242  -2
ghash_clmulni_intel     4242  -2
aesni_intel             4242  -2
lrw                     4242  -2 aesni_intel
gf128mul                4242  -2 lrw
glue_helper             4242  -2 aesni_intel
ablk_helper             4242  -2 aesni_intel
cryptd                  4242  -2 ghash_clmulni_intel,aesni_intel,ablk_helper
i2c_i801                4242  -2
pcspkr                  4242  -2
lpc_ich                 4242  -2
mei_me                  4242  -2
joydev                  4242  -2
mei                     4242  -2 mei_me
sg                      4242  -2
ipmi_si                 4242  -2
ipmi_devintf            4242  -2
ipmi_msghandler         4242  -2 ipmi_ssif,ipmi_devintf,ipmi_si
video                   4242  -2
acpi_pad                4242  -2
ie31200_edac            4242  -2
libcrc32c               4242  -2 nf_nat,nf_conntrack
br_netfilter            4242  -2
veth                    4242  -2
overlay                 4242  -2
ip6_vzprivnet           4242  -2
ip6_vznetstat           4242  -2
ip_vznetstat            4242  -2
ip_vzprivnet            4242  -2 ip6_vzprivnet
vziolimit               4242  -2
vzevent                 4242  -2
vzlist                  4242  -2
vzstat                  4242  -2
vznetstat               4242  -2 tun,ip_vznetstat,ip6_vznetstat
vznetdev                4242  -2
vzmon                   4242  -2 vznetdev
vzdev                   4242  -2 vzmon,vziolimit,vznetdev,vzlist,vznetstat
bridge                  4242  -2 br_netfilter
stp                     4242  -2 garp,bridge
llc                     4242  -2 stp,garp,bridge
ext4                    4242  -2
mbcache                 4242  -2 ext4
jbd2                    4242  -2 ext4
sd_mod                  4242  -2
crc_t10dif              4242  -2 sd_mod
crct10dif_generic       4242  -2
ast                     4242  -2
drm_kms_helper          4242  -2 ast
syscopyarea             4242  -2 drm_kms_helper
sysfillrect             4242  -2 drm_kms_helper
sysimgblt               4242  -2 drm_kms_helper
fb_sys_fops             4242  -2 drm_kms_helper
ttm                     4242  -2 ast
ahci                    4242  -2
libahci                 4242  -2 ahci
drm                     4242  -2 ast,ttm,drm_kms_helper
e1000e                  4242  -2
igb                     4242  -2
libata                  4242  -2 ahci,libahci
megaraid_sas            4242  -2
crct10dif_pclmul        4242  -2
crct10dif_common        4242  -2 crct10dif_pclmul,crct10dif_generic,crc_t10dif
crc32c_intel            4242  -2
dca                     4242  -2 igb
ptp                     4242  -2 igb,e1000e
i2c_algo_bit            4242  -2 ast,igb
drm_panel_orientation_quirks     4242  -2 drm
pps_core                4242  -2 ptp
pio_kaio                4242  -2
pio_nfs                 4242  -2
pio_direct              4242  -2
pfmt_raw                4242  -2
pfmt_ploop1             4242  -2
ploop                   4242  -2 pfmt_raw,pfmt_ploop1,pio_kaio,pio_direct
root@tailscale:~#
```

**Comment by DentonGentry** [comment] 2021-08-01 15:11
I have a Digital Ocean droplet which is set up as an exit node. It had been operating iptables in legacy mode.
```
root@dgentry-do-de1:~# iptables --version
iptables v1.8.4 (legacy)
```

I switched it to use nf_tables, and rebooted it:
```
root@dgentry-do-de1:~# iptables --version
iptables v1.8.4 (nf_tables)
```

and the exit node still works. It does not show the same behavior as the OpenVZ node in this bug.

The vintage of the kernel may be a factor. The Digital Ocean droplet is:
```
root@dgentry-do-de1:~# uname -a
Linux dgentry-do-de1 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

The OpenVZ node is:
```
root@tailscale:~# uname -a
Linux tailscale 3.10.0-1127.18.2.vz7.163.46 #1 SMP Fri Nov 20 21:47:55 MSK 2020 x86_64 GNU/Linux
```

**Comment by tshpr** [comment] 2021-08-01 19:25
Maybe I need to enable some module on the non-working OpenVZ VPS?

**Comment by xindirama** [comment] 2021-08-06 07:05
If so, I cannot identify it. All the iptables / nf_ / nat modules listed in the above lsmod seem to be present and loaded on this machine.

**Comment by bradfitz** [comment] 2022-09-13 15:50
This is likely #5621?

/cc @andrew-d

**Comment by DentonGentry** [comment] 2022-10-30 12:25
This provider will be fixed when we fix https://github.com/tailscale/tailscale/issues/5621.

**Closed by DentonGentry** 2022-10-30 12:25 UTC
Labels: L1 Very few, P2 Aggravating, T5 Usability, exit-node
