### ISSUE TITLE
Android: Enable Tailscale when enabling Tailscale VPN from Android settings

### ISSUE THREAD

**Issue by arunsathiya** [tailscale/tailscale#818] opened 2020-10-13 04:02 UTC
**Is your feature request related to a problem? Please describe.**

Often, I don't use the VPN app's GUI to enable/disable the VPN connection, rather, use the VPN option under Android settings to do that. 

For some extra context, it is expected that when I choose "Always-on" option, it automatically enables the VPN on the app's GUI as well. This saves me one extra step, where I have to open the app's GUI to enable it as well. This works well with other consumer VPN apps like Cloudflare Warp and NordVPN. On Tailscale, the toggle remains disabled and it shows "Stopped" 

**Describe the solution you'd like**

When VPN is enabled from Android settings, enable the Tailscale process as well, thus switching the toggle on Tailscape app to look "enabled".

**Describe alternatives you've considered**

Not applicable, right now, I activate VPN from Android settings and then open Tailscale GUI to enable the toggle as well.

**Additional context**

My reason behind using the Android VPN settings to enable/disable Tailscale, instead of the Tailscale GUI is that, I need to use "Always-on" and sometimes "Block internet access without VPN" settings, which is only available on Android settings and not on the VPN app's GUI.

**Comment by ignoramous** [comment] 2021-03-04 17:46
Related: #1433

**Comment by mrbluecoat** [comment] 2021-11-26 16:32
Refs: https://github.com/tailscale/tailscale/issues/1698 https://github.com/tailscale/tailscale/issues/2481 https://github.com/tailscale/tailscale/issues/2231

**Comment by DentonGentry** [comment] 2023-06-03 00:08
More extensive discussion and tracking of this issue is on https://github.com/tailscale/tailscale/issues/2481, closing as a duplicate of https://github.com/tailscale/tailscale/issues/2481

**Closed by DentonGentry** 2023-06-03 00:08 UTC
Labels: OS-android, L3 Some users, P1 Nuisance
