### ISSUE TITLE
Tailscale tests don't allow specifying protocol, so they fail if a protocol-specific rule is in use

### ISSUE THREAD

**Issue by sdigit** [tailscale/tailscale#5755] opened 2022-09-26 17:52 UTC
### What is the issue?

I added some ACL blocks like so:
```
{
  "action": "allow",
  "src": "router-ipv4",
  "dst": ["server-ipv4:514"],
  "proto": "udp",
}
```

This is accepted by the ACL editor, however a test fails:

```
{"src": "router-ipv4", "dst": "server-ipv4:514"}
```

Is it planned for tests to be able to take `proto`?

### Steps to reproduce

See above

### Are there any recent changes that introduced the issue?

Unknown

### OS

Other

### OS version

macOS

### Tailscale version

several

### Bug report

BUG-bc22a6b42f434d77356ad79381e0cb562698a578be9bbb36215d8d718c6e0743-20220926175224Z-01aff749c4927b28

**Comment by DentonGentry** [comment] 2022-10-05 02:22
duplicate of https://github.com/tailscale/tailscale/issues/3561

**Closed by DentonGentry** 2022-10-05 02:22 UTC
Labels: needs-triage, bug
