### ISSUE TITLE
Android exit-node-allow-lan-access does not work

### ISSUE THREAD

**Issue by xrain0610** [tailscale/tailscale#7510] opened 2023-03-09 04:34 UTC
### What is the issue?

I use the tailscale android that install from playstore, and updated at latest version.  when I use exit-node, and select option "Allow Lan Access" , it's no effect, I can't request my local network.

### OS

Android

### OS version

Android 11

### Tailscale version

1.36.1

### Bug report

BUG-aa3cc09b08b8ea0979c7cc6d01a18ecf6cab66521fac0ffd52a224d0dac3784f-20230309043517Z-b6d35861e90ac378

**Comment by DentonGentry** [comment] 2023-03-12 12:44
The exit node not working is a different issue, this is about Allow LAN Access not working. If you want to file a new issue and include a bugreport from the Android app while it is trying to use the exit node, we can look into it.

**Comment by Craeckie** [comment] 2023-05-31 22:07
It still doesn't work on 1.40.0 on Android 13. Never worked for me also.

**Comment by Zocker1999NET** [comment] 2023-08-14 22:15
Can sadly still confirm as well, Android 13, LineageOS 20, Tailscale 1.44.1, from F-Droid.

Steps to confirm using an exit node is the problem:
1. without Tailscale, try to connect to a local device (e.g. router via browser), it works
2. turn on Tailscale with exit node & allow LAN access
3. check access to router again, does not work
4. turn off exit node, letting Tailscale itself enabled
5. check access to router again, now it works again

BUG-96dd60510d13e230547b36ccdce5902343e343e5ebf95a02cfdccbe7b7968705-20230814221041Z-efbe5d74ac146a72

**Comment by xrain0610** [comment] 2023-08-22 23:29
It seems work well at v1.48

**Comment by Craeckie** [comment] 2023-11-22 10:41
Still doesn't work for me on  the recent commit b88929e, which F-Droid version "1.55.47" appears to be built upon (see [F-Droid](https://f-droid.org/packages/com.tailscale.ipn/))

> It seems work well at v1.48

What device&OS are you using? Did you change something since your previous post? This information might help to narrow down the cause of this issue.

**Comment by Orhideous** [comment] 2023-11-27 00:52
Same issue. Android 13, Tailscale 1.53.115-t6cce5fe00-gab4a672a4eb from F-Droid. It never worked for almost a year.

**Comment by bailey-ts** [comment] 2023-12-08 22:36
While replicating this issue for a customer ([go/hs/25484](http://go/hs/21824)) I also observe this behavior on my Pixel 6a, Android 13 (LineageOS 20), client version 1.54.0-tc82fd1256-g8e8e1d0f76a

BUG-6353b40a3553a2d19d95d8bbe1aee675582c049bb4f8fb1f7f468f21ac874da7-20231208222710Z-8fb03eb670156db0

**Comment by ozmodeuz** [comment] 2024-01-14 15:00
Same issue here with Tailscale 1.5.6 on both my Pixel 8 Pro (Android 14) and on my Chromecast (Android 12). 'allow lan access' has no effect. This has the side effect of breaking casting from Android to the Chromecast/Android TV while the exit node is enabled.

**Comment by felschr** [comment] 2024-01-21 16:32
I'm also still encountering this issue using Mullvad exit nodes on Tailscale 1.57.72 for Android.
This issue sounds similar to #10526, so Android isn't the only platform affected.

**Comment by tnchan007** [comment] 2024-01-30 16:08
A user [go/hs/28841](https://secure.helpscout.net/search/?query=28841) can't access any local LAN IPs 10.x while connected to Tailscale with Mullvad exit node enabled and the Allow LAN access feature enabled. When Mullvad exit node is disabled local IPs are accessible without issue. 

BUG-be5ad7a0d9870eda1d951f5c665d25a5f530001aed2c94b387bede18e3426e5c-20240125205415Z-2f69d10686c7fa5f

**Comment by steigerm** [comment] 2024-02-04 14:07
Same problem here with latest Tailscale on my Chromecast with Google TV (Android 12). 
"Allow lan access" does not work.
Therefore no connection to my local NAS possible if tailscale is active.

**Comment by Orhideous** [comment] 2024-02-23 18:22
It looks like that this problem is more common. In a next few days I'll try to find a clue what happened.

**Comment by DTBUday** [comment] 2024-04-25 18:35
Any updates on this? This issue seems to still be a problem for version 1.60.1

**Comment by DTBUday** [comment] 2024-05-16 17:37
Seems to be fixed with version 1.66

**Comment by tradergene** [comment] 2024-05-16 19:11
Fixed for me as well on Android.  Finally!  And thank you to the Tailscale
team.

**Comment by 5310** [comment] 2024-05-18 18:12
Sadly, even on 1.66, the toggle now simple breaks the VPN (the key disappears from status bar, Tailnet no longer accessible) for me, on all of my Android devices. :cry:

**Comment by steigerm** [comment] 2024-05-21 09:07
Same here.
Even with 1.66 it does not work on my Chromecast with Google TV (Android 12).

Connect VPN
"Allow lan access" OFF
Communication using Exit Node works
Local LAN access not.

"Allow lan access" ON
Communication using Exit Node does not work
Local LAN access works.

**Comment by 5310** [comment] 2024-05-23 11:28
@steigerm are you on Android 11 by any chance?

**Comment by steigerm** [comment] 2024-05-23 11:30
> @steigerm are you on Android 11 by any chance?
Nope.
From my original post
"Same problem here with latest Tailscale on my Chromecast with Google TV (Android 12)."

**Comment by 5310** [comment] 2024-05-23 15:46
Well, that was embarrassing :blush:...

But I'm now convince Allow LAN is working on Android 13 and 14, but not on Android 12 and 11 (at least). Tested a total of twelve phones, and this holds for all of them running 1.66.3

Only one of the reports in this thread was from A14, but that was long before the fix actually landed (as with the rest of the A12 and lower, to be fair). Hope it can get fixed someday, as my phone is stuck on A11 for a year at least!

**Comment by ahmetyilmaz** [comment] 2024-06-29 01:52
I think it is more prevalent, whoever uses the newest Chromecast have the same issue. It happened to me as well and I couldn't find a solution yet.

I have some a streaming app that uses techniques involving calling LAN devices to understand if VPN is used and without this fixed, I couldn't make it work with tailscale.

**Comment by agottardo** [comment] 2024-07-08 17:05
Closing this as a stale issue, as the _original_ problem has been resolved.

If anybody here is still hitting the problem on a specific old Android version + Chromecast combo, please update to the latest version. Then, open a new issue attaching detailed information with steps to reproduce, device model, app version you're using, current Android version, and most importantly **a bug report identifier**. We need that identifier specifically to pull logs from your device. "Doesn't work on Chromecast" is unfortunately insufficient information for us to investigate the problem because we can't repro with our setup: we need to understand what is specifically broken on *your* device based on *your* logs. Please attach the date and time you are toggling the Allow LAN Access switch to your report, so that we can cross-reference with the logs. It would also help if you could use `logcat` to pull any suspicious error messages that verify when you toggle the Allow LAN access switch.

**Closed by agottardo** 2024-07-08 17:05 UTC
Labels: OS-android, L1 Very few, P2 Aggravating, T5 Usability, exit-node, bug
