### ISSUE TITLE
Fr:web72375@gmail.com

### ISSUE THREAD

**Issue by 94811924** [tailscale/tailscale#8695] opened 2023-07-24 00:43 UTC
### What are you trying to do?

I am trying to print remote from AWS EC2 Ubuntu22.04 with CUPs , I am able to print without a problem point normal ip address to  Mikrotik RouterOS, printer is behind NAT, I mainly us port forward. 
I want to closeup the public network and using Tailscale. The best is to install Tailscale to my Mikrotik Router. 
Does Tailscale offer any packages for RouterOS ver7.. and up?
Thanks
David Lee
web72735@gmail.com

**Comment by DentonGentry** [comment] 2023-07-24 04:04
There is not currently a package to support Microtik RouterOS.

Closing as a duplicate of https://github.com/tailscale/tailscale/issues/6743

**Closed by DentonGentry** 2023-07-24 04:04 UTC
Labels: needs-triage, fr
