### ISSUE TITLE
Typing in a registered email does not automatically select the correct oauth provider Microsoft.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2457] opened 2021-07-19 15:13 UTC
Customer is experiancing issue with selecting the 0auth provider MIcsodoft when they login as hotmail.com email.

Steps to reproduce,

1. Login to Tailscale.
2. enter the email xyz@homtail.com, in the first registered email space.
3. Click on "Sign In" with email. 
It should select Microsoft as oauth2 provider but its selecting Google and getting error out.
<img width="1028" alt="Screen Shot 2021-07-19 at 11 12 02 AM" src="https://user-images.githubusercontent.com/75628398/126183724-a3a4ad53-d615-46a3-8bd0-a2cbd9af5e45.png">

**Comment by DentonGentry** [comment] 2021-11-10 02:13
Duplicate of https://github.com/tailscale/tailscale/issues/942

**Closed by DentonGentry** 2021-11-10 02:13 UTC
Labels: L3 Some users, P3 Can't get started, T5 Usability, identity
