### ISSUE TITLE
Cannot SSH to Tailscale node when using OpenSSH 8.2p1

### ISSUE THREAD

**Issue by Tahutipai** [tailscale/tailscale#4382] opened 2022-04-08 06:27 UTC
### What is the issue?

I was trying to connect via ssh to a Ubuntu server in a remote location, from a both a local Raspberry Pi & Ubuntu 20.04 workstation - both on the same local home wifi connection.

The Ubuntu workstation (client) is using: 
`OpenSSH_8.2p1 Ubuntu-4ubuntu0.4, OpenSSL 1.1.1f  31 Mar 2020
`

From the Pi, ssh-over-tailscale works fine. But from Ubuntu, the connection establishes, then just hang for 120 minutes, then fails with a timeout error. Connection, ports, ACL's etc are all correct.

Last four lines of `ssh -vvv server` are:
> debug2: resolve_canonicalize: hostname 100.1.1.1 is address
> debug2: ssh_connect_direct
> debug1: Connecting to 100.1.1.1 [100.1.1.1] port 22.
> <**hangs for 120 seconds here**>
> debug1: connect to address 100.108.42.127 port 22: Connection timed out

The solution was to download and compile from source, Openssh v7.9, and then it works. i.e downgrade from 8.2>7.9

So, it looks like is an issue with combination of OpenSSH/Tailscale, that rear's it's head when on OpenSSH v8.2 is used.

For reference, the server in this case is running this version:
`OpenSSH_8.4p1 Ubuntu-5ubuntu1.2, OpenSSL 1.1.1j  16 Feb 2021
`

### Steps to reproduce

ssh from UbuntuClient1 to UbuntuServer1 (fails)
ssh from RaspberryPi1 to UbuntuServer1 (succeeds)

### Are there any recent changes that introduced the issue?

No.

### OS

Linux

### OS version

Ubuntu 20.04, Raspbian 10

### Tailscale version

1.22.2

### Bug report

BUG-39e55c94093498a0c13fdfba1a093c7a014e8289f0fa87f8603f55ab894c486f-20220408062659Z-8b94adc4d72d8537

**Comment by DentonGentry** [comment] 2022-04-08 11:25
Does OpenSSH 8.2 with the settings you are using connect to OpenSSH 8.4 when not using Tailscale?

**Comment by cpbotha** [comment] 2022-06-05 12:33
I'm unfortunately seeing exactly this behaviour SSHing to an ubuntu laptop, although it was working perfectly yesterday.

As you can see in the screenshot below, I have connectivity to tailscale node meepv3, but SSH times out after a few minutes. However, when I ssh to the meepv3's IP number on my local net, everything works as it should.

When SSH to the tailscale node times out, the tailscale log complains about "no associated peer node" involving IP number 35.224.170.84 which according to whois belongs to the google cloud.

```
Jun 05 14:26:43 meepv3 tailscaled[1199]: monitor: RTM_DELROUTE: src=, dst=, gw=192.168.1.1, outif=3, table=254
Jun 05 14:28:02 meepv3 tailscaled[1199]: Accept: TCP{100.69.95.63:57448 > 100.116.78.49:22} 60 tcp ok
Jun 05 14:28:02 meepv3 tailscaled[1199]: wgengine: Reconfig: configuring userspace wireguard config (with 1/4 peers)
Jun 05 14:28:02 meepv3 tailscaled[1199]: Accept: TCP{100.116.78.49:22 > 100.69.95.63:57448} 60 ok out
Jun 05 14:28:02 meepv3 tailscaled[1199]: Accept: TCP{100.69.95.63:57448 > 100.116.78.49:22} 52 tcp non-syn
Jun 05 14:30:01 meepv3 tailscaled[1199]: open-conn-track: timeout opening (TCP 100.116.78.49:60638 => 35.224.170.84:80); no associated peer node
Jun 05 14:30:02 meepv3 tailscaled[1199]: Accept: TCP{100.116.78.49:22 > 100.69.95.63:57448} 64 ok out
Jun 05 14:30:02 meepv3 tailscaled[1199]: Accept: TCP{100.69.95.63:57448 > 100.116.78.49:22} 100 tcp non-syn
Jun 05 14:30:02 meepv3 tailscaled[1199]: Accept: TCP{100.116.78.49:22 > 100.69.95.63:57448} 40 ok out
Jun 05 14:30:04 meepv3 tailscaled[1199]: open-conn-track: timeout opening (TCP 100.116.78.49:60638 => 35.224.170.84:80); no associated peer node
```

![image](https://user-images.githubusercontent.com/937871/172050290-4a39c913-0e43-47d0-bd51-33050e0ff469.png)

**Comment by raggi** [comment] 2022-06-06 19:23
> Jun 05 14:30:04 meepv3 tailscaled[1199]: open-conn-track: timeout opening (TCP 100.116.78.49:60638 => 35.224.170.84:80); no associated peer node

This looks like NetworkManager connectivity checks, and it's quite possible that NetworkManager is seeing this connectivity check fail and deciding to try and turn connections off, as it does.

Does `nmcli` report that the Tailscale connection is managed? If it does you can try `nmcli dev set tailscale0 managed no`

**Comment by cpbotha** [comment] 2022-06-06 20:00
Thank you @raggi -- `nmcli dev` showed it to be managed, so I set it to unmanaged and confirmed that it was then listed as unmanaged.

Unfortunately, it still times out, with the same messages on the client side, and in the tailscale log.

I'm not sure if this is new, but now I see multiple of the -> 22 tcp-non-syn with ok out reposponses before the connection finally times out.

Note that dropbear client still connects successfully from the very same host to the very same tailscale IP.

```
Jun 06 21:57:22 meepv3 tailscaled[1199]: open-conn-track: timeout opening (TCP 100.116.78.49:60894 => 35.224.170.84:80); no associated peer node
Jun 06 21:57:24 meepv3 tailscaled[1199]: Accept: TCP{100.116.78.49:22 > 100.69.95.63:55776} 64 ok out
Jun 06 21:57:24 meepv3 tailscaled[1199]: Accept: TCP{100.69.95.63:55776 > 100.116.78.49:22} 100 tcp non-syn
Jun 06 21:57:24 meepv3 tailscaled[1199]: Accept: TCP{100.116.78.49:22 > 100.69.95.63:55776} 40 ok out
Jun 06 21:57:34 meepv3 tailscaled[1199]: open-conn-track: timeout opening (TCP 100.116.78.49:60894 => 35.224.170.84:80); no associated peer node
Jun 06 21:57:53 meepv3 tailscaled[1199]: Accept: TCP{100.92.252.65:49401 > 100.116.78.49:22} 84 tcp non-syn
Jun 06 21:57:53 meepv3 tailscaled[1199]: Accept: TCP{100.116.78.49:22 > 100.92.252.65:49401} 108 ok out
Jun 06 21:58:01 meepv3 tailscaled[1199]: Accept: TCP{100.116.78.49:22 > 100.92.252.65:49401} 276 ok out
Jun 06 21:58:24 meepv3 tailscaled[1199]: Accept: TCP{100.92.252.65:49401 > 100.116.78.49:22} 84 tcp non-syn
Jun 06 21:58:24 meepv3 tailscaled[1199]: Accept: TCP{100.116.78.49:22 > 100.92.252.65:49401} 108 ok out
```

**Comment by DentonGentry** [comment] 2023-02-13 00:59
> I'm not sure if this is new, but now I see multiple of the -> 22 tcp-non-syn with ok out responses before the connection finally times out.

That happens fairly often, the flow got kicked out.

At this point I don't know what to suggest next. MTU size?

**Comment by cpbotha** [comment] 2023-02-13 07:40
With the latest tailscale 1.36.1 and the openssh 1:8.2p1-4ubuntu0.5 packages on ubuntu 20.04, I am not able anymore to reproduce this issue.

Unless @Tahutipai still experiences this, you could consider closing this issue.

**Closed** 2023-03-07 16:52 UTC
Labels: OS-linux, L1 Very few, P2 Aggravating, T5 Usability, bug
