### ISSUE TITLE
MagicDNS seems broken on Android with v1.8.3

### ISSUE THREAD

**Issue by fd** [tailscale/tailscale#1956] opened 2021-05-19 19:55 UTC
General DNS resolution works but requests are routed to the DHCP announced nameservers. My account has MagicDNS enabled and has an internal nameserver (using a 100.x.x.x address). My other devices work find (none of them are Android).

I'm not sure how to provide more detailed information...

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_36yoh)

**Comment by ccesare** [comment] 2021-05-20 11:26
I'm seeing the same (I assume) issue on Android 1.8.3.

I'm not using MagicDNS, but I do have one Tailscale device set as the DNS server. My Android device is no longer using it for name resolution.

I wasn't having any issues on 1.6.0, and my other Tailscale devices are still doing name resolution correctly.

**Comment by ccesare** [comment] 2021-05-20 13:27
For me

- Magic DNS is disabled
- I have one nameserver added
- Override local DNS is enabled

**Comment by garthski** [comment] 2021-05-20 13:35
Same issue for me too and only affecting my Android devices (Samsung Galaxy S10+ and Tab S7 on v1.8.3). Macbook, RPi and Windows machines all working fine.

- Magic DNS disabled.
- 1 Global Nameserver (set to Tailscale IP for pihole on RPi)
- Override local DNS is enabled.

**Comment by fd** [comment] 2021-05-20 13:53
My settings:

* Magic DNS is enabled
* I have one nameserver added (using a tailscale address)
* Override local DNS is enabled

**Comment by astrophena** [comment] 2021-05-20 13:58
Same issue for me too (only affects my Android 10 phone).

* Magic DNS is enabled
* I have Cloudflare nameservers added (for IPv4 and IPv6)
* Override local DNS is enabled.

**Comment by danderson** [comment] 2021-05-21 01:10
Could (at least) one of you provide the tailscale IP of your android device that's misbehaving, so I can poke at debug logs? This behavior is doubly confusing because we don't yet support split DNS on android (we always use the global resolvers when DNS managemnt is enabled), so it's kind of amazing that we somehow end up doing the opposite.

**Comment by fd** [comment] 2021-05-21 08:03
My tailscale IP `100.89.97.44`.

**Comment by garthski** [comment] 2021-05-21 09:22
Dug up my kindle fire which still had android version 1.6.0 on it and it's having the same issue so not sure it's related directly to the 1.8.3 android app version. Connecting via IP address confirmed working on both android devices.

Kindle Fire - 1.6.0 - 100.115.215.89
Galaxy S10 - 1.8.3 - 100.117.215.74

**Comment by danopia** [comment] 2021-05-21 21:06
I'm also seeing the issue of an Android phone (100.88.59.20) using its default DNS instead of the Tailscale-configured DNS server (100.106.147.120). MagicDNS is not enabled.

In a somewhat similar but more breaking fashion, a Chromebook (100.71.81.104) running Tailscale Android seemingly has DNS completely broken any time Tailscale is enabled, regardless of the DNS settings selected in Tailscale. Below is the Chromebook network diags:

![Screenshot 2021-05-21 23 05 01](https://user-images.githubusercontent.com/40628/119198093-0f9a7a00-ba89-11eb-9422-dfb4acbcafdd.png)

Both of these cases started immediately after taking the 1.8.3 upgrade; unfortunately downgrading is not feasible :( so I can't verify that downgrading resolves.

**Comment by curzonj** [comment] 2021-05-23 19:26
I have the same issue on my chromebook as @danopia with no DNS servers configured in Tailscale. Regardless of what I configure manually in ChromeOS Tailscale sets the nameservers to 0.0.0.0. I tried setting DNS servers in the Tailscale admin UI and reinstalling the Tailscale app and there was no change in behavior, network configuration for the VPN connection still had all custom DNS with 0.0.0.0.

**Comment by danopia** [comment] 2021-05-23 22:00
I set my Chromebook to allow untrusted apps in order to perform a downgrade, and can confirm that 1.6.0 still works.

The configuration difference is visible in the network config UI, without changing any Tailscale settings:

| 1.8.3 | 1.6.0 |
|---|---|
| ![Screenshot 2021-05-23 15 51 10](https://user-images.githubusercontent.com/40628/119277707-73f04180-bc21-11eb-8d05-5c87f369b728.png) | ![Screenshot 2021-05-23 23 54 36](https://user-images.githubusercontent.com/40628/119278020-152bc780-bc23-11eb-9451-0b8aaa18d6ca.png) |

Based on other evidence, it seems like real Android is forgiving and simply defaults to non-VPN DNS settings if the VPN app doesn't provide DNS. ChromeOS is apparently more picky

**Comment by garthski** [comment] 2021-05-24 18:54
Just downgraded to 1.6.0 on my android phone to test and can confirm it does still work. Must just be my fire tablet that's an issue based on my last message.

**Comment by meinside** [comment] 2021-05-25 05:04
I'm experiencing the same issue.
I have several Linux/Windows/macOS/Android machines on Tailscale,
but accessing other machines with machine names is not working only on Android devices. (1.8.3)

I have magic DNS enabled and local DNS overridden.
Removing and reinstalling the Android app did not help.

**Comment by DentonGentry** [comment] 2021-05-25 05:15
Oddly, I have not been able to produce this. I'm running Tailscale 1.8.3 on a Pixel 3a running Android 11. My https://login.tailscale.com/admin/dns has:
- Magic DNS enabled
- A split domain "example.com" configured to use 100.x.y.z, the Tailscale address of a DNS server in my home
- Another split domain "example2.com" also configured to use 100.x.y.z
- global DNS servers of 8.8.8.8, 8.8.4.4, 2001:4860:4860::8888, and 2001:4860:4860::8844.

I'm able to reach my devices using MagicDNS names.

**Comment by meinside** [comment] 2021-05-25 07:38
For more information, both machine names and auto-assigned dns names(xxx.beta.tailscale.net things) do not work for me.
Only the IP addresses do right now.

But there was no such issue on previous Android versions.

**Comment by ledakis** [comment] 2021-05-25 09:17
I have the same issue.
Magic DNS is off.
One nameserver set up (on tailscale network)
Override is enabled. (I have tried with override disabled, and it still not working).

Connecting directly by IP to other nodes works.

**Comment by DentonGentry** [comment] 2021-05-25 11:22
If you're able to produce the problem: could you try adding a Split DNS server? That changes some of the behavior in the nameserver list sent down to the devices. You can create a server for something harmless like "example.com", its mere presence changes the behavior.

<img width="501" alt="Screen Shot 2021-05-25 at 4 22 05 AM" src="https://user-images.githubusercontent.com/1140756/119489686-c8261f00-bd10-11eb-95c6-61e391019ac5.png">

**Comment by ccesare** [comment] 2021-05-25 11:25
I quickly tried this after seeing your comment about a working split DNS configuration on Android, but I still wasn't resolving names on my tailscale DNS server. I didn't investigate for too long though.

**Comment by fd** [comment] 2021-05-25 11:32
I can also confirm that the problem persists after adding a split DNS server.

**Comment by astrophena** [comment] 2021-05-25 12:32
I checked Tailscale logs through ADB (`logcat -s com.tailscale.ipn`) and noticed some interesting things:

```
05-25 15:22:21.267 15964  4679 I com.tailscale.ipn: 9.0M/93.5M control: controlclient: restarting map request for "dns" health change to new state: open /etc/resolv.conf.tmp553272162: read-only file system
05-25 15:22:21.269 15964  4679 I com.tailscale.ipn: 9.0M/93.5M Switching ipn state Starting -> Running (WantRunning=true)
05-25 15:22:21.275 15964 16008 I com.tailscale.ipn: 9.1M/93.5M health("dns"): error: open /etc/resolv.conf.tmp553272162: read-only file system
```

Also I tried to downgrade to Tailscale 1.6.0 and that resolved the problem.

**Comment by ledakis** [comment] 2021-05-25 13:10
Adding split DNS did not do the trick @DentonGentry

**Comment by lightrush** [comment] 2021-05-25 14:29
Broken on Pixel 5 with Android 11.

**Comment by DentonGentry** [comment] 2021-05-26 22:37
`health("dns"): error: open /etc/resolv.conf.tmp553272162: read-only file system` is fairly telling, in that it looks like it is trying to operate with the Linux DNS backend implementation not Android.

There are no occurrences of "/etc/resolv.conf" in the ADB logs from my Pixel3a, which is not showing any of these symptoms. So that also fits.

**Comment by DentonGentry** [comment] 2021-05-27 00:00
From a device experiencing the problem:

```
2021-05-25 12:35:36.809347673 +0000 UTC: 7.8M/100.2M SetPrefs: Prefs{ra=true dns=true want=false host="Redacted" Persist=nil}
2021-05-25 12:35:36.809546111 +0000 UTC: 7.8M/100.2M control: HostInfo: {"IPNVersion":"1.8.3-td0e86b08c-g8ea1d4ced73","BackendLogID":"REDACTED","OS":"android","OSVersion":"10","DeviceModel":"REDACTED","Hostname":"Redacted","GoArch":"arm64"}
2021-05-25 12:37:09.221005992 +0000 UTC: 5.3M/99.5M Switching ipn state NeedsLogin -> Starting (WantRunning=true)
2021-05-25 12:37:09.22162943 +0000 UTC: 5.3M/99.5M wgcfg: skipped unselected default routes from: "Redacted" ([XXXXXX])
2021-05-25 12:37:09.222875263 +0000 UTC: 5.3M/99.5M magicsock: starting endpoint update (derp-map-update)
2021-05-25 12:37:09.224191409 +0000 UTC: 5.3M/99.5M magicsock: SetPrivateKey called (init)
2021-05-25 12:37:09.225923701 +0000 UTC: 5.3M/99.5M wgengine: Reconfig: configuring userspace wireguard config (with 0/6 peers)
2021-05-25 12:37:09.228976826 +0000 UTC: 5.5M/99.5M UAPI: Updating private key
2021-05-25 12:37:09.231045576 +0000 UTC: 5.6M/99.5M wgengine: Reconfig: configuring router
2021-05-25 12:37:09.232208076 +0000 UTC: 5.6M/99.5M wgengine: Reconfig: configuring DNS
2021-05-25 12:37:09.233001305 +0000 UTC: 5.6M/99.5M dns: Set: {DefaultResolvers:[1.1.1.1:53 1.0.0.1:53 [2606:4700:4700::1111]:53 [2606:4700:4700::1001]:53] Routes:map[]
SearchDomains:[example.com.beta.tailscale.net.] Hosts:map[deploy-557.example.com.beta.tailscale.net.:[] example.com.beta.tailscale.net.:[100.1.1.1]] AuthoritativeSuffixes:[example.com.beta.tailscale.net. 0.e.1.a.c.5.1.1.a.7.d.f.ip6.arpa. 64.100.in-addr.arpa. 65.100.in-addr.arpa. 66.100.in-addr.arpa. 67.100.in-addr.arpa. 68.100.in-addr.arpa. 69.100.in-addr.arpa. 70.100.in-addr.arpa. 71.100.in-addr.arpa. 72.100.in-addr.arpa. 73.100.in-addr.arpa. 74.100.in-addr.arpa. 75.100.in-addr.arpa. 76.100.in-addr.arpa. 77.100.in-addr.arpa. 78.100.in-addr.arpa. 79.100.in-addr.arpa. 80.100.in-addr.arpa. 81.100.in-addr.arpa. 82.100.in-addr.arpa. 83.100.in-addr.arpa. 84.100.in-addr.arpa. 85.100.in-addr.arpa. 86.100.i
n-addr.arpa. 87.100.in-addr.arpa. 88.100.in-addr.arpa. 89.100.in-addr.arpa. 90.100.in-addr.arpa. 91.100.in-addr.arpa. 92.100.in-addr.arpa. 93.100.in-addr.arpa. 94.100.in-addr.arpa. 95.100.in-addr.arpa. 96.100.in-addr.arpa. 97.100.in-addr.arpa. 98.100.in-addr.arpa. 99.100.in-addr.arpa. 100.100.in-addr.arpa. 101.100.in-addr.arpa. 102.100.in-addr.arpa. 103.100.in-addr.arpa. 104.100.in-addr.arpa. 105.100.in-addr.arpa. 106.100.in-addr.arpa. 107.100.in-addr.arpa. 108.100.in-addr.arpa. 109.100.in-addr.arpa. 110.100.in-addr.arpa. 111.100.in-addr.arpa. 112.100.in-addr.arpa. 113.100.in-addr.arpa. 114.100.in-addr.arpa. 115.100.in-addr.arpa. 116.100.in-addr.arpa. 117.100.in-addr.arpa. 118.100.in-addr.arpa. 119.100.in-addr.arpa. 120.100.in-addr.arpa. 121.100.in-addr.arpa. 122.100.in-addr.arpa. 123.100.in-addr.arpa. 124.100.in-addr.arpa. 125.100.i
n-addr.arpa. 126.100.in-addr.arpa. 127.100.in-addr.arpa.]}
2021-05-25 12:37:09.233932034 +0000 UTC: 5.7M/99.5M dns: Resolvercfg: {Routes:map[.:[1.1.1.1:53 1.0.0.1:53 [2606:4700:4700::1111]:53 [2606:4700:4700::1001]:53]] Hosts:map[deploy-557.example.com.beta.tailscale.net.:[] example.com.beta.tailscale.net.:[100.1.1.1]] LocalDomains:[example.com.beta.tailscale.net. 0.e.1.a.c.5.1.1.a.7.d.f.ip6.arpa. 64.100.in-addr.arpa. 65.100.in-addr.arpa. 66.100.in-addr.arpa. 67.100.in-addr.arpa. 68.100.in-addr.arpa. 69.100.in-addr.arpa. 70.100.in-addr.arpa. 71.100.in-addr.arpa. 72.100.in-addr.arpa. 73.100.in-addr.arpa. 74.100.in-addr.arpa. 75.100.in-addr.arpa. 76.100.in-addr.arpa. 77.100.in-addr.arpa. 78.100.in-addr.arpa. 79.100.in-addr.arpa. 80.100.in-addr.arpa. 81.100.in-addr.arpa. 82.100.in-addr.arpa. 83.100.in-addr.arpa. 84.100.in-addr.arpa. 85.100.in-addr.arpa. 86.100.in-addr.arpa. 87.100.in-addr.arpa. 88.100.in-addr.arpa. 89.100.in-addr.arpa. 90.100.in-addr.arpa. 91.100.in-addr.arpa. 92.100.in-addr.arpa. 93.100.in-addr.arpa. 94.100.in-addr.arpa. 95.100.in-addr.arpa. 96.100.in-addr.arpa. 97.100.in-addr.arpa. 98.100.in-addr.arpa. 99.100.in-addr.arpa. 100.100.in-addr.arpa. 101.100.in-addr.arpa. 102.100.in-addr.arpa. 103.100.in-addr.arpa. 104.100.in-addr.arpa. 105.100.in-addr.arpa. 106.100.in-addr.arpa. 107.100.in-addr.arpa. 108.100.in-addr.arpa. 109.100.in-addr.arpa. 110.100.in-addr.arpa. 111.100.in-addr.arpa. 112.100.in-addr.arpa. 113.100.in-addr.arpa. 114.100.in-addr.arpa. 115.100.in-addr.arpa. 116.100.in--addr.arpa. 117.100.in-addr.arpa. 118.100.in-addr.arpa. 119.100.in-addr.arpa. 120.100.in-addr.arpa. 121.100.in-addr.arpa. 122.100.in-addr.arpa. 123.100.in-addr.arpa. 124.100.in-addr.arpa. 125.100.in-addr.arpa. 126.100.in-addr.arpa. 127.100.in-addr.arpa.]}
2021-05-25 12:37:09.234662763 +0000 UTC: 5.7M/99.5M dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[example.com.beta.tailscale.net.] MatchDomains:[]}
2021-05-25 12:37:09.239359117 +0000 UTC: 5.7M/99.5M magicsock: ReSTUN: endpoint update active, need another later ("set-private-key")
2021-05-25 12:37:09.240480471 +0000 UTC: 5.8M/99.5M magicsock: ReSTUN: endpoint update active, need another later ("non-zero-peers")
2021-05-25 12:37:09.242034638 +0000 UTC: 5.8M/99.5M authReconfig: ra=true dns=true 0x03: open /etc/resolv.conf.tmp940700961: read-only file system
2021-05-25 12:37:09.242649221 +0000 UTC: 5.8M/99.5M peerapi disabled; no state directory
2021-05-25 12:37:09.243803388 +0000 UTC: 5.8M/99.5M wgcfg: skipped unselected default routes from: "Redacted" ([XXXXX])
2021-05-25 12:37:09.245297659 +0000 UTC: 5.8M/99.5M health("dns"): error: open /etc/resolv.conf.tmp940700961: read-only file system
```

**Comment by DentonGentry** [comment] 2021-05-27 00:34
From a different device:
```
2021-05-27 00:09:09.037500756 +0000 UTC: 7.7M/97.3M wgengine: Reconfig: configuring router
2021-05-27 00:09:09.03835862 +0000 UTC: 7.8M/97.3M wgengine: Reconfig: configuring DNS
2021-05-27 00:09:09.039662214 +0000 UTC: 8.0M/97.3M dns: Set: {DefaultResolvers:[8.8.8.8:53 8.8.4.4:53 [2001:4860:4860::8888]:53 [2001:4860:4860::8844]:53] Routes:map[example.com.:[100.92.61.18:53]] SearchDomains:[example.com.beta.tailscale.net. example.com.] Hosts:map[...] AuthoritativeSuffixes:[example.com.beta.tailscale.net. 0.e.1.a.c.5.1.1.a.7.d.f.ip6.arpa. 64.100.in-addr.arpa. ... dns: Resolvercfg: {Routes:map[.:[8.8.8.8:53 8.8.4.4:53 [2001:4860:4860::8888]:53 [2001:4860:4860::8844]:53] example.com.:[100.92.61.18:53]] Hosts:map[...
2021-05-27 00:09:09.041497006 +0000 UTC: 8.1M/97.3M dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[example.com.beta.tailscale.net.] MatchDomains:[]}
2021-05-27 00:09:09.070433207 +0000 UTC: 8.2M/97.3M health("dns"): error: open /etc/resolv.conf.tmp166818458: read-only file system
2021-05-27 00:09:09.070600759 +0000 UTC: 8.1M/97.3M authReconfig: ra=true dns=true 0x03: open /etc/resolv.conf.tmp166818458: read-only file system
2021-05-27 00:09:09.071448103 +0000 UTC: 8.2M/97.3M peerapi disabled; no state directory
```

wgengine/userspace.go:
```
func (e *userspaceEngine) Reconfig(cfg *wgcfg.Config, routerCfg *router.Config, dnsCfg *dns.Config) error {
...
        if routerChanged {
                e.logf("wgengine: Reconfig: configuring router")
                err := e.router.Set(routerCfg)
                health.SetRouterHealth(err)
                if err != nil {
                        return err
                }
                // Keep DNS configuration after router configuration, as some                                                                                                            
                // DNS managers refuse to apply settings if the device has no
                // assigned address.
                e.logf("wgengine: Reconfig: configuring DNS")
                err = e.dns.Set(*dnsCfg)
                health.SetDNSHealth(err)
                if err != nil {
                        return err
                }
        }
```

Android expects updateTUN to be called:
```
func (b *backend) updateTUN(service jni.Object, rcfg *router.Config, dcfg *dns.OSConfig) error {
                // builder.addDnsServer
                addDnsServer := jni.GetMethodID(env, bcls, "addDnsServer", "(Ljava/lang/String;)Landroid/net/VpnService$Builder;")
                // builder.addSearchDomain.
                addSearchDomain := jni.GetMethodID(env, bcls, "addSearchDomain", "(Ljava/lang/String;)Landroid/net/VpnService$Builder;")
                if dcfg != nil {
                        nameservers := dcfg.Nameservers
                        if b.avoidEmptyDNS && len(nameservers) == 0 {
                                nameservers = fallbackNameservers
                        }
                        for _, dns := range nameservers {
                                _, err = jni.CallObjectMethod(env,
                                        builder,
                                        addDnsServer,
                                        jni.Value(jni.JavaString(env, dns.String())),
                                )
                                if err != nil {
                                        return fmt.Errorf("VpnService.Builder.addDnsServer(%v): %v", dns, err)
                                }
                        }

                        for _, dom := range dcfg.SearchDomains {
                                _, err = jni.CallObjectMethod(env,
                                        builder,
                                        addSearchDomain,
                                        jni.Value(jni.JavaString(env, dom.WithoutTrailingDot())),
                                )
                                if err != nil {
                                        return fmt.Errorf("VpnService.Builder.addSearchDomain(%v): %v", dom, err)
                                }
                        }
                }
```

**Comment by DentonGentry** [comment] 2021-05-27 04:00
I think the problem is that the Android backend.go sets wgengine.Config.DNS to dns.NewOSConfigurator()

https://github.com/tailscale/tailscale-android/blob/3d2abf0b3bcfe90e14c07a829f2aab9e196d9bb4/cmd/tailscale/backend.go#L92

There is not an Android-specific NewOSConfigurator, so it maybe ends up pulling in the Linux one?
https://github.com/tailscale/tailscale/blob/main/net/dns/manager_linux.go

The Linux NewOSConfigurator expects to be able to rewrite /etc/resolv.conf, which doesn't work on Android. This matches the error messages seen in the log.

Instead Android updates its DNS config in updateTUN(), which it calls from runBackend() in response to several different channels from the backend.

I think Android should be instantiating a dns.NewNoopManager(), as it handles its DNS configuration differently. Later it may make sense to move Android's DNS config out of updateTUN and implement a proper Android NewOSConfigurator.

**Comment by DentonGentry** [comment] 2021-05-27 04:11
I built a tailscale-debug.apk which uses NewNoopManager() instead of NewOSConfigurator(), installed it on a device which was experiencing the problem, and can now use Magic DNS names in Chrome.

**Comment by ccesare** [comment] 2021-05-28 11:06
I've upgraded to 1.8.6, and my Android device still isn't using the Global Nameserver set in the admin panel. I haven't been using Magic DNS, so maybe this is a separate issue? I've toggled Tailscale on and off and swtiched from WiFi to LTE a few times to see if it might knock things into place but no luck.

**Comment by fd** [comment] 2021-05-28 11:15
I can confirm that 1.8.6 doesn't fix the issue. I also rebooted the phone just for good measure.

**Comment by DentonGentry** [comment] 2021-05-28 11:28
Reopening issue, will look.

**Closed** 2021-05-28 23:01 UTC
Labels: L2 A few users, OS-android, P3 Can't get started, T6 Major usability, dns

**Comment by adyanth** [comment] 2021-05-29 09:23
Hi @DentonGentry 
Is this fixed now? The 1.8.6 version on play store lists this as fixed, but I still cannot access my windows dns server frontended by pihole on Android 11. 

Or will it be the next android app version that will include the fix?

**Comment by ledakis** [comment] 2021-05-29 10:37
> Hi @DentonGentry
> Is this fixed now? The 1.8.6 version on play store lists this as fixed, but I still cannot access my windows dns server frontended by pihole on Android 11.
> 
> Or will it be the next android app version that will include the fix? I do see this released: https://github.com/tailscale/tailscale-android/releases/tag/v1.8.6-t28a8f9c90-g04890797712

Yes the next update has fixed the issue for me. I joined the beta channel to get the update, it might take a couple of days I guess to come out normally. The release date shown is 29 of May

**Comment by adyanth** [comment] 2021-05-29 10:50
Thanks @ledakis I will wait.

**Comment by ccesare** [comment] 2021-05-29 11:12
Yep, the latest update also fixes the issue for me. Thanks @DentonGentry!

**Comment by DentonGentry** [comment] 2021-05-29 12:09
The first attempted fix, 1.8.6-t28a8f9c90-gff16a75a65c released 5/28, only resolved one symptom and the main problem remained.

The second fix, 1.8.6-t28a8f9c90-g04890797712 released 5/29, resolved the rest of the problem and is the one people are reporting as fixing it.

**Comment by adyanth** [comment] 2021-05-29 12:18
Yes, the update does fix it, thanks!

**Comment by diyism** [comment] 2021-05-30 10:43
It's weired, I'm trying to test  #1991 with the  1.8.6-t28a8f9c90-g04890797712 release apk on my Android 10 phone,
but it won't start, when I click the switch button on the top left, it always switch back to "Stopped".

But when I download the 1.8.3 version from f-droid, it can switch to "Active" without go back to "Stopped".

I can't figure out why

**Comment by tdalbo92** [comment] 2021-06-02 14:04
Sorry to resurrect a dead Issue, but this latest update seems to have _caused_ this issue for me.  

- MagicDNS is *not* enabled
- One global nameserver is set, the Tailscale IP of my Pi running Pihole
- Override local DNS is *not* enabled.  This formerly was, but I had to disable it last night because none of my Tailscale clients could resolve any DNS queries.  Not sure what broke this. 
- One split domain set

Since updating this morning to the latest Android app version, no DNS queries resolve on Android.

**Comment by HasseJohansen** [comment] 2021-06-02 14:15
I see the same kind of problem:

* MagicDNS is _not_ enabled
* One global nameserver set to 1.1.1.1 (as I have to provide a global one when using scoped DNS)
* Override local DNS is _not_ enabled(because I actually don't want to use the global one...it is just needed by tailscale)
* Scoped DNS enabled(what you call split dns - which I still think is a bad name) for one domain

Lookups for names in the splitted/scoped domain never reaches the nameserver set from Android

It works fine from OSX

I think I maybe read earlier that scoped dns/split dns was not supported on Android yet?

**Comment by cavedano8** [comment] 2021-06-03 09:25
I also have similar problems.

- MagicDNS enabled
- Only one global nameserver (Tailscale IP of my raspberry running Adguard)
If I set "override local dns" I can reach my devices with their name; if it is not set "override local dns", the devices can only be reached with Tailscale IP. Same behavior with both Android and PC Win

**Comment by ledakis** [comment] 2021-06-03 09:37
Ah yes, I see the behaviour @tdalbo92 and @HasseJohansen mention. With overwrite turned off and setting a split dns record, on Android latest version ( v1.8.6-t28a8f9c90-g04890797712 ) the DNS server is actually set to the tailscale magic DNS server (`100.100.100.100`) which is not resolving any domain apart from the `beta.tailscale.net` ones.

All non-tailscale DNS queries seem to hang because of this.

Regarding what @cavedano8 said, if split dns is off, it works fine for me.

I assume like @HasseJohansen said that split dns is not supported on Android since there has to be some sort of internal conditional dns forwarder on the device and it is not set currently.

**Comment by normanr** [comment] 2021-06-03 21:44
I see something similar (100.66.241.34 with v1.8.6-t28a8f9c90-g04890797712). MagicDNS enabled, global nameserver set to 192.168.1.11 (local network resolver), and override local DNS is enabled.

When I'm on the local network (192.168.1.0/24) then DNS requests like `host check.dyndns.org 100.100.100.100` work, but when I'm on mobile (AT&T) then the DNS requests do _not_ work. Requests for MagicDNS names work, so I'm guessing there's something weird going on with forwarding the non-tailscale requests "upstream", even though upstream is an address that should be fixed and routed to tailscale. `host check.dyndns.org 192.168.1.11` and `host check.dyndns.org 8.8.8.8` both work always, because 192.168.1.0/24 is routed into tailscale.

Are the upstream DNS requests made using regular UDP ports by the tailscale daemon? On Android a VPN client's connections will not be routed via the tun interface, so it's possible that the upstream DNS requests are not being sent back to tailscale. I suspect that tailscale will need to send the DNS requests internally if the upstream DNS server address is in the list of routes to route to tailscale (because the routing set up by the kernel won't do that for you).

**Comment by normanr** [comment] 2021-06-03 22:07
(also note that the logcat entry for `dns: Resolvercfg` can be very long and android only logs the first 1000 characters, so it gets truncated half-way though `LocalDomains`)

**Comment by tdalbo92** [comment] 2021-06-10 18:21
Is this eligible to be reopened?  Or do we need a separate Issue to track this?

I haven't been able to use Tailscale on my phone for a week or so because of the regression.

**Comment by DentonGentry** [comment] 2021-06-10 18:22
Ah: best to open a new issue, as this one has a long set of comments about the original issue

**Comment by tdalbo92** [comment] 2021-06-11 03:05
> Ah: best to open a new issue, as this one has a long set of comments about the original issue

Created #2102 , thanks!

**Comment by adamc199** [comment] 2022-09-06 21:26
> 

Did you get a resolution? GrapheneOS android 13 and I see the same behaviour you do in this post

**Comment by DentonGentry** [comment] 2022-09-06 21:27
It is best to open a new issue, as this one has a long set of comments about the original issue.
