### ISSUE TITLE
FR: Automatic exit node usage on unknown networks

### ISSUE THREAD

**Issue by cap10morgan** [tailscale/tailscale#4182] opened 2022-03-16 16:30 UTC
### What are you trying to do?

The exit node feature is great, but I sometimes forget to manually turn it on when I want to use it to encrypt all of my traffic over an untrusted network.

### How should we solve this?

Before Tailscale I used a VPN service called Encrypt.me that had a really nice feature where it would automatically connect to the VPN and route all traffic over it when connected to a WiFi network name that you hadn't already added to an allow list. It did this across platforms and even synced your allow list across all of your devices.

It would be great if Tailscale could be configured to behave similarly where you could add WiFi network names (and/or subnets or another way to roughly identify wired networks; it doesn't have to be foolproof) to an allow list and when connected to any of those, it could just use the network's default route but on all others it should automatically use a default exit node you select.

### What is the impact of not solving this?

I have to remember to manually activate the exit node. When I forget I worry about what I'm sharing on a public network.

### Anything else?

Here is the VPN service that does this: https://encrypt.me/ (which I guess is becoming StrongVPN soon).

**Comment by freezscholte** [comment] 2022-03-17 21:00
and to add on for local network you should check if the mac address of the firewall is known. If its not then also the exit-node should kick in.

**Comment by mayakacz** [comment] 2022-03-17 21:34
Duplicate of https://github.com/tailscale/tailscale/issues/3302

**Closed by mayakacz** 2022-03-17 21:34 UTC
Labels: needs-triage, fr
