### ISSUE TITLE
FR: Get notified on network updates

### ISSUE THREAD

**Issue by rnhurt** [tailscale/tailscale#3766] opened 2022-01-19 18:47 UTC
### What are you trying to do?

I would like to be notified if/when a new device gets added to my network.  It would ideal to allow all of my users to install and use Tailscale without have to authenticate each device but I don’t want to run the risk of a rogue device being added.

### How should we solve this?

It would be great to get an email notification when a device got added to the network.

### What is the impact of not solving this?

Our current workaround is to manually authenticate each device.  This works OK for a small team but it's not scalable; especially if your team is testing things and constantly adding/removing devices.

### Anything else?

I think an expanded notification system would come in handy for other things as well (device leaving, device not responding, keys expired, etc.)

NOTE: some of these may already be notifications; I'm not that familiar with Tailscale yet.

**Comment by DentonGentry** [comment] 2022-01-22 23:28
Duplicate of https://github.com/tailscale/tailscale/issues/312

**Closed by DentonGentry** 2022-01-22 23:28 UTC
Labels: needs-triage, fr
