### ISSUE TITLE
FR: Bypass exit node for captive portals

### ISSUE THREAD

**Issue by ppergame** [tailscale/tailscale#4085] opened 2022-03-07 16:14 UTC
### What are you trying to do?

My laptop is configured to use an exit mode. Sometimes, I connect to wifi networks with captive portals that require local LAN access for authentication. I want to launch a browser instance that bypasses tailscale DNS and routing so that I can enter hotel wifi code or w/e.

### How should we solve this?

Some of these steps are underspecified, but
1) User runs new subcommand "tailscale captive"
2) tailscale sets up a Linux network namespace with uhh routes and stuff
3) tailscale runs "google-chrome --user-data-dir=/tmp/blahblah http://captive.apple.com/" in the new namespace
4) User clicks things to log into captive portal

### What is the impact of not solving this?

Disabling tailscale or reconfiguring with no exit node is annoying and leaks traffic to potentially hostile public wifi network.

**Comment by DentonGentry** [comment] 2022-03-07 16:43
Duplicate of https://github.com/tailscale/tailscale/issues/1634

**Closed by DentonGentry** 2022-03-07 16:43 UTC
Labels: needs-triage, fr
