### ISSUE TITLE
"Connect On Demand" broken in iOS 18

### ISSUE THREAD

**Issue by aaron-trout** [tailscale/tailscale#13708] opened 2024-10-07 10:45 UTC
### What is the issue?

The connect on demand feature with "detect magic hostnames" no longer works after upgrading to iOS 18. 

### Steps to reproduce

Configure like so:

![IMG_0065](https://github.com/user-attachments/assets/94c64b85-25fd-417a-a861-b2d36203ad4b)

Do something like reboot the phone or manually disconnect tailscale, then try to access something on your tailnet with a `*.tailnet-xxxx.ts.net` hostname.

### Are there any recent changes that introduced the issue?

Yeah, seems to be broken since I updated to iOS 18. This is happening on my iPhone and iPad.

### OS

iOS

### OS version

iOS 18.1 (iPhone); iOS 18.0 (iPad)

### Tailscale version

1.74.2

### Bug report

BUG-5dc41396499592897d8e12c2c1ec160436a3b2962361e50ccc3893ac3d079dfc-20241007104504Z-f1f5bbd25ddd1bbd

**Comment by aaron-trout** [comment] 2024-10-07 10:46
Sorry if this is a dupe; there did seem to be other open issues related to "connect on demand", but not quite the same as this issue so I opened a new one. 

It was implied above, but I _think_ this stopped working with the iOS 18 update; certainly it was working fine a couple months back.

**Comment by agottardo** [comment] 2024-10-07 16:11
Duplicate of https://github.com/tailscale/tailscale/issues/12851

**Closed by agottardo** 2024-10-07 16:11 UTC
Labels: needs-triage, bug
