### ISSUE TITLE
FR: add filter to machine search for online/offline

### ISSUE THREAD

**Issue by bmizerany** [tailscale/tailscale#4512] opened 2022-04-25 06:05 UTC
### What are you trying to do?

I'm at https://login.tailscale.com/admin/machines trying to filter out offline ephemeral nodes via the search bar along with other criteria like `tag:foo`.

Example: "I want to see all nodes tagged with ("tag:foo") that are online"

### How should we solve this?

How ever you think is best. I propose a filter like: `online:true` or `status:online`, but I'm not married to either.

### What is the impact of not solving this?

In turbulent environments where ephemeral nodes come and go quickly, the list of machines becomes cluttered with offline machines and finding the few that are online proves to be cumbersome. One has to page through the list manually, or use the cli with `jq`-fu to find the online nodes.

### Anything else?

You're all rad.

NOTE: I'm using reusable, ephemeral, tagged keys.

**Comment by DentonGentry** [comment] 2022-05-07 16:17
I believe that entering a filter of `lastseen:connected tag:example` does what is requested.
https://tailscale.com/kb/1176/filter-devices/ documents the filter expressions available.
Please reopen if something else was intended, closing as fixed.

**Closed by DentonGentry** 2022-05-07 16:17 UTC
Labels: admin UI, L3 Some users, P1 Nuisance, T2 Visual Polish, fr
