### ISSUE TITLE
Android + Mullvad: Connectivity lost when moving from WiFi to cellular data

### ISSUE THREAD

**Issue by clip3101** [tailscale/tailscale#9492] opened 2023-09-20 17:56 UTC
### What is the issue?

When on WiFi and Tailscale is enabled with a Mullvad exit node, I can browse the public internet.  However, after moving out of range of the WiFi and onto cellular data, all internet connectivity is lost.  Switching Tailscale off, then switching it on again restores internet connectivity.

### Steps to reproduce

- Start on WiFi.  Enable Tailscale with a Mullvad exit node.  Internet connectivity is confirmed.
- Move out of range of WiFi and onto cellular data.  Internet connectivity is lost.
- Only switching Tailscale off and on restores internet connectivity.

### Are there any recent changes that introduced the issue?

I purchased a subscription to Mullvad through Tailscale and enabled a Mullvad exit node.

### OS

Android

### OS version

Android 13 with the latest release of GrapheneOS: https://grapheneos.org/releases#2023091800

### Tailscale version

1.48.0

### Other software

None of the listed programs.

### Bug report

BUG-39b33dcfa9969d51183d6f80ced2c896ccba6963f2968bae63be6461d0aa23eb-20230920175559Z-fad5bfe5fd7e682a

**Comment by jimeh** [comment] 2024-01-23 02:47
I have this same issue on iOS 17. If I leave it alone for 5-10 minutes internet connectivity will eventually come back. This issue along with not being able to pick specific Mullvad servers are the reasons I've had to stop using Mullvad via Tailscale.

**Comment by Lyndeno** [comment] 2024-03-27 15:50
I have this issue without Mullvad, just with transferring from WiFi to Cellular, I have to turn tailscale off and back on to get my internet back.

**Comment by codethief** [comment] 2024-05-16 12:53
I, too, have had this issue without Mullvad for a long time, see [my comment from one year ago](https://github.com/tailscale/tailscale/issues/6516#issuecomment-1546866703). I'm not even sure anymore it's related to switching between WiFi and mobile connection. It might also happen just like that. Either way, disabling & re-enabling Tailscale always seems to fix it (for a while, until it happens again).

**Comment by codethief** [comment] 2024-05-19 09:28
@clip3101 @Lyndeno Could you check whether the issue is still present in the latest release for Android? See https://github.com/tailscale/tailscale/issues/11613#issuecomment-2118726019

**Comment by clip3101** [comment] 2024-05-19 11:12
> @clip3101 @Lyndeno Could you check whether the issue is still present in the latest release for Android? See [#11613 (comment)](https://github.com/tailscale/tailscale/issues/11613#issuecomment-2118726019)

I can confirm that this issue has been resolved for me using version 1.66.3

**Comment by Lyndeno** [comment] 2024-05-19 13:49
I will give it a try

**Comment by Lyndeno** [comment] 2024-05-21 14:55
Seems to be fixed for me as well

**Comment by codethief** [comment] 2024-05-26 09:16
@clip3101 Would you close this issue then?

**Closed** 2024-05-26 14:25 UTC
Labels: needs-triage, bug
