### ISSUE TITLE
FR: Tailscale SSH username mapping macros

### ISSUE THREAD

**Issue by nward** [tailscale/tailscale#7938] opened 2023-04-21 02:05 UTC
### What are you trying to do?

We have several groups of machines, these machines all have usernames for each human, but the usernames are different in each group of machines. I.e. I, Nathan Ward, are sometimes "nward", sometimes "wardn", sometimes "nathan", sometimes "nathanw", etc.

Unfortunately, these usernames cannot be aligned to one standard, for various reasons.

We want to allow a user to ssh as themselves, but not as any other user. This would result in some very verbose SSH ACLs.

### How should we solve this?

I'm not set in stone on this, but it feels like a "ssh user mapping" would be useful, something like the following:

```json
{
  "ssh_users": {
    "some_mapping_name": {
      "nward@domain": ["nward"],
      "foobar@domain": ["fbar"],
    },
    "another_mapping_name": {
      "nward@domain": ["nathan","wardn"],
      "foobar@domain": ["foo","barf"],
      "baz@domain": ["baz"],
    }
  },
  "ssh": [
    {
      "action": "accept",
      "src": ["group:group_a_users"],
      "dst": ["tag:group_a"],
      "users": ["ssh_users:some_mapping_name"],
    },
    {
      "action": "accept",
      "src": ["group:group_b_users"],
      "dst": ["tag:group_b"],
      "users": ["ssh_users:another_mapping_name"],
    }
  ]
}
```

This would allow nward@domain to ssh as nward to group_a systems, or as nathan or wardn to group_b systems. baz@domain could only ssh to group_b systems, etc.

Perhaps multiple ssh_users could be specified per dst, which would be merged allowing any of the username mappings, for that ACL.

### What is the impact of not solving this?

Currently, we just have wide ACLs - allowing nonroot etc - which allows any user to ssh as any other user. This is OK, as it's only used in a lab environment - we currently do not have a way to promote this to production without huge ACL configuration.

**Comment by DentonGentry** [comment] 2023-04-22 08:41
There is a discussion of alternatives in this area in https://github.com/tailscale/tailscale/issues/5562
Closing as a duplicate of https://github.com/tailscale/tailscale/issues/5562

**Closed by DentonGentry** 2023-04-22 08:41 UTC
Labels: needs-triage, fr

**Comment by nward** [comment] 2023-04-22 09:04
Thanks @DentonGentry! I had searched for a while but did not come across that issue.
