### ISSUE TITLE
Multiple "tailscale up" can deadlock tailscaled

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#680] opened 2020-08-12 23:49 UTC
Debugging a customer issue, found that multiple "tailscale up" runs can deadlock a tailscaled.

```
2020/08/11 18:09:28 Program starting: v1.0.4-ge256174d6, Go 1.14.4-ts56db765: []string{"/usr/sbin/tailscaled"}
2020/08/11 18:09:28 LogID: 53753fff8c311c26e60d2fac29589351d899a9688e3d099ea2bc8e9b92efb1d6
...
2020/08/11 18:09:30 17.2M/36.9M control: client.newEndpoints(0, [xxx])
2020/08/11 18:09:30 17.3M/36.9M control: cancelMapSafely: synced=true
2020/08/11 18:09:30 16.7M/36.9M Switching ipn state Starting -> Running (WantRunning=true)
2020/08/11 18:09:30 16.7M/36.9M magicsock: starting endpoint update (non-zero-peers)
2020/08/11 18:09:30 17.3M/36.9M Start
2020/08/11 18:09:30 17.4M/36.9M control: client.Shutdown()
2020/08/11 18:09:30 17.4M/36.9M control: client.Shutdown: inSendStatus=1
2020/08/11 18:09:30 17.4M/36.9M control: authRoutine: context done.
2020/08/11 18:09:30 17.4M/36.9M control: authRoutine: state:synchronized
2020/08/11 18:09:30 17.4M/36.9M control: authRoutine: quit
2020/08/11 18:09:30 17.5M/36.9M netcheck: probePortMapServices: me 172.20.20.105 -> gw 172.20.18.108
2020/08/11 18:09:30 16.7M/36.9M netcheck: xxx
2020/08/11 18:09:30 16.8M/36.9M external route: up
2020/08/11 18:09:53 16.9M/36.9M magicsock: periodicReSTUN enabled
2020/08/11 18:09:53 16.9M/36.9M magicsock: starting endpoint update (periodic)
2020/08/11 18:09:53 16.9M/36.9M netcheck: probePortMapServices: me 172.20.20.105 -> gw 172.20.18.108
2020/08/11 18:09:53 16.7M/36.9M netcheck: xxx
2020/08/11 18:10:15 wgengine watchdog stacks:
goroutine profile: total 738
187 @ 0x437230 0x447523 0x852193 0x4671f1
#	0x852192	github.com/tailscale/wireguard-go/device.(*Peer).RoutineSequentialReceiver+0x1e2	github.com/tailscale/wireguard-go@v0.0.0/device/receive.go:543

187 @ 0x437230 0x447523 0x854ee5 0x4671f1
#	0x854ee4	github.com/tailscale/wireguard-go/device.(*Peer).RoutineNonce+0x564	github.com/tailscale/wireguard-go@v0.0.0/device/send.go:390

187 @ 0x437230 0x447523 0x8555d7 0x4671f1
#	0x8555d6	github.com/tailscale/wireguard-go/device.(*Peer).RoutineSequentialSender+0x146	github.com/tailscale/wireguard-go@v0.0.0/device/send.go:609

48 @ 0x437230 0x447523 0x850c2c 0x4671f1
#	0x850c2b	github.com/tailscale/wireguard-go/device.(*Device).RoutineDecryption+0x14b	github.com/tailscale/wireguard-go@v0.0.0/device/receive.go:245

48 @ 0x437230 0x447523 0x8511a8 0x4671f1
#	0x8511a7	github.com/tailscale/wireguard-go/device.(*Device).RoutineHandshake+0x1a7	github.com/tailscale/wireguard-go@v0.0.0/device/receive.go:335

48 @ 0x437230 0x447523 0x8551ac 0x4671f1
#	0x8551ab	github.com/tailscale/wireguard-go/device.(*Device).RoutineEncryption+0x14b	github.com/tailscale/wireguard-go@v0.0.0/device/send.go:510

1 @ 0x40b3b4 0x44c25c 0x761472 0x4671f1
#	0x44c25b	os/signal.signal_recv+0x9b	runtime/sigqueue.go:147
#	0x761471	os/signal.loop+0x21		os/signal/signal_unix.go:23

1 @ 0x437230 0x405f77 0x405c3b 0x81a6c0 0x91864a 0x91fa4a 0x91f642 0x9561f8 0x4671f1
#	0x81a6bf	tailscale.com/control/controlclient.(*Client).Shutdown+0x19f	tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:639
#	0x918649	tailscale.com/ipn.(*LocalBackend).Start+0xfe9			tailscale.com@v0.0.0-00010101000000-000000000000/ipn/local.go:352
#	0x91fa49	tailscale.com/ipn.(*BackendServer).GotCommand+0x339		tailscale.com@v0.0.0-00010101000000-000000000000/ipn/message.go:129
#	0x91f641	tailscale.com/ipn.(*BackendServer).GotCommandMsg+0xb1		tailscale.com@v0.0.0-00010101000000-000000000000/ipn/message.go:99
#	0x9561f7	tailscale.com/ipn/ipnserver.(*server).serveConn+0x1b7		tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnserver/server.go:99

1 @ 0x437230 0x405f77 0x405c3b 0x8a73a6 0x8a5cf0 0x8a6881 0x8a49a0 0x8a2594 0x8a22f0 0x8a221e 0x8af568 0x8ae0a5 0x4671f1
#	0x8a73a5	github.com/mdlayher/netlink.(*lockedNetNSGoroutine).run+0xb5	github.com/mdlayher/netlink@v1.1.0/conn_linux.go:771
#	0x8a5cef	github.com/mdlayher/netlink.(*sysSocket).read+0xdf		github.com/mdlayher/netlink@v1.1.0/conn_linux.go:377
#	0x8a6880	github.com/mdlayher/netlink.(*sysSocket).Recvmsg+0x170		github.com/mdlayher/netlink@v1.1.0/conn_linux.go:543
#	0x8a499f	github.com/mdlayher/netlink.(*conn).Receive+0xef		github.com/mdlayher/netlink@v1.1.0/conn_linux.go:147
#	0x8a2593	github.com/mdlayher/netlink.(*Conn).receive+0x73		github.com/mdlayher/netlink@v1.1.0/conn.go:288
#	0x8a22ef	github.com/mdlayher/netlink.(*Conn).lockedReceive+0x3f		github.com/mdlayher/netlink@v1.1.0/conn.go:247
#	0x8a221d	github.com/mdlayher/netlink.(*Conn).Receive+0x7d		github.com/mdlayher/netlink@v1.1.0/conn.go:240
#	0x8af567	tailscale.com/wgengine/monitor.(*nlConn).Receive+0xdc7		tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/monitor/monitor_linux.go:63
#	0x8ae0a4	tailscale.com/wgengine/monitor.(*Mon).pump+0x84			tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/monitor/monitor.go:105

1 @ 0x437230 0x405f77 0x405c7b 0x857612 0x4671f1
#	0x857611	github.com/tailscale/wireguard-go/device.(*Device).RoutineTUNEventReader+0x101	github.com/tailscale/wireguard-go@v0.0.0/device/tun.go:25

1 @ 0x437230 0x4301ea 0x42f755 0x4d0395 0x4d122b 0x4d120d 0x4d8351 0x4d8324 0x840b3c 0x9067e9 0x4671f1
#	0x42f754	internal/poll.runtime_pollWait+0x54				runtime/netpoll.go:203
#	0x4d0394	internal/poll.(*pollDesc).wait+0x44				internal/poll/fd_poll_runtime.go:87
#	0x4d122a	internal/poll.(*pollDesc).waitRead+0x19a			internal/poll/fd_poll_runtime.go:92
#	0x4d120c	internal/poll.(*FD).Read+0x17c					internal/poll/fd_unix.go:169
#	0x4d8350	os.(*File).read+0x70						os/file_unix.go:263
#	0x4d8323	os.(*File).Read+0x43						os/file.go:116
#	0x840b3b	github.com/tailscale/wireguard-go/tun.(*NativeTun).Read+0x12b	github.com/tailscale/wireguard-go@v0.0.0/tun/tun_linux.go:361
#	0x9067e8	tailscale.com/wgengine/tstun.(*TUN).poll+0x138			tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tstun/tun.go:189

1 @ 0x437230 0x4301ea 0x42f755 0x4d0395 0x4d122b 0x4d120d 0x59ea0f 0x5b191e 0x608950 0x4f3921 0x608b9c 0x607155 0x60b27b 0x60b286 0x557c93 0x558539 0x86616f 0x868996 0x86e9df 0x86e9c7 0x886819 0x886808 0x4671f1
#	0x42f754	internal/poll.runtime_pollWait+0x54				runtime/netpoll.go:203
#	0x4d0394	internal/poll.(*pollDesc).wait+0x44				internal/poll/fd_poll_runtime.go:87
#	0x4d122a	internal/poll.(*pollDesc).waitRead+0x19a			internal/poll/fd_poll_runtime.go:92
#	0x4d120c	internal/poll.(*FD).Read+0x17c					internal/poll/fd_unix.go:169
#	0x59ea0e	net.(*netFD).Read+0x4e						net/fd_unix.go:202
#	0x5b191d	net.(*conn).Read+0x8d						net/net.go:184
#	0x60894f	crypto/tls.(*atLeastReader).Read+0x5f				crypto/tls/conn.go:761
#	0x4f3920	bytes.(*Buffer).ReadFrom+0xb0					bytes/buffer.go:204
#	0x608b9b	crypto/tls.(*Conn).readFromUntil+0xeb				crypto/tls/conn.go:783
#	0x607154	crypto/tls.(*Conn).readRecordOrCCS+0x114			crypto/tls/conn.go:590
#	0x60b27a	crypto/tls.(*Conn).readRecord+0x15a				crypto/tls/conn.go:558
#	0x60b285	crypto/tls.(*Conn).Read+0x165					crypto/tls/conn.go:1234
#	0x557c92	bufio.(*Reader).fill+0x102					bufio/bufio.go:100
#	0x558538	bufio.(*Reader).ReadByte+0x38					bufio/bufio.go:252
#	0x86616e	tailscale.com/derp.readFrameHeader+0x2e				tailscale.com@v0.0.0-00010101000000-000000000000/derp/derp.go:132
#	0x868995	tailscale.com/derp.(*Client).recvTimeout+0x115			tailscale.com@v0.0.0-00010101000000-000000000000/derp/derp_client.go:354
#	0x86e9de	tailscale.com/derp.(*Client).Recv+0x9e				tailscale.com@v0.0.0-00010101000000-000000000000/derp/derp_client.go:328
#	0x86e9c6	tailscale.com/derp/derphttp.(*Client).RecvDetail+0x86		tailscale.com@v0.0.0-00010101000000-000000000000/derp/derphttp/derphttp_client.go:569
#	0x886818	tailscale.com/derp/derphttp.(*Client).Recv+0x2b8		tailscale.com@v0.0.0-00010101000000-000000000000/derp/derphttp/derphttp_client.go:558
#	0x886807	tailscale.com/wgengine/magicsock.(*Conn).runDerpReader+0x2a7	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/magicsock/magicsock.go:1166

1 @ 0x437230 0x4301ea 0x42f755 0x4d0395 0x4d122b 0x4d120d 0x59ea0f 0x5b191e 0x608950 0x4f3921 0x608b9c 0x607155 0x60b27b 0x60b286 0x55834f 0x4cd107 0x68bd57 0x68bd0a 0x68c591 0x6aca7d 0x6ac25f 0x4671f1
#	0x42f754	internal/poll.runtime_pollWait+0x54		runtime/netpoll.go:203
#	0x4d0394	internal/poll.(*pollDesc).wait+0x44		internal/poll/fd_poll_runtime.go:87
#	0x4d122a	internal/poll.(*pollDesc).waitRead+0x19a	internal/poll/fd_poll_runtime.go:92
#	0x4d120c	internal/poll.(*FD).Read+0x17c			internal/poll/fd_unix.go:169
#	0x59ea0e	net.(*netFD).Read+0x4e				net/fd_unix.go:202
#	0x5b191d	net.(*conn).Read+0x8d				net/net.go:184
#	0x60894f	crypto/tls.(*atLeastReader).Read+0x5f		crypto/tls/conn.go:761
#	0x4f3920	bytes.(*Buffer).ReadFrom+0xb0			bytes/buffer.go:204
#	0x608b9b	crypto/tls.(*Conn).readFromUntil+0xeb		crypto/tls/conn.go:783
#	0x607154	crypto/tls.(*Conn).readRecordOrCCS+0x114	crypto/tls/conn.go:590
#	0x60b27a	crypto/tls.(*Conn).readRecord+0x15a		crypto/tls/conn.go:558
#	0x60b285	crypto/tls.(*Conn).Read+0x165			crypto/tls/conn.go:1234
#	0x55834e	bufio.(*Reader).Read+0x24e			bufio/bufio.go:226
#	0x4cd106	io.ReadAtLeast+0x86				io/io.go:310
#	0x68bd56	io.ReadFull+0x86				io/io.go:329
#	0x68bd09	net/http.http2readFrameHeader+0x39		net/http/h2_bundle.go:1479
#	0x68c590	net/http.(*http2Framer).ReadFrame+0xa0		net/http/h2_bundle.go:1737
#	0x6aca7c	net/http.(*http2clientConnReadLoop).run+0x8c	net/http/h2_bundle.go:8246
#	0x6ac25e	net/http.(*http2ClientConn).readLoop+0x6e	net/http/h2_bundle.go:8174

1 @ 0x437230 0x4301ea 0x42f755 0x4d0395 0x4d122b 0x4d120d 0x59ea0f 0x5b191e 0x608950 0x4f3921 0x608b9c 0x607155 0x60b27b 0x60b286 0x6e03a5 0x557c93 0x557dff 0x6e1038 0x4671f1
#	0x42f754	internal/poll.runtime_pollWait+0x54		runtime/netpoll.go:203
#	0x4d0394	internal/poll.(*pollDesc).wait+0x44		internal/poll/fd_poll_runtime.go:87
#	0x4d122a	internal/poll.(*pollDesc).waitRead+0x19a	internal/poll/fd_poll_runtime.go:92
#	0x4d120c	internal/poll.(*FD).Read+0x17c			internal/poll/fd_unix.go:169
#	0x59ea0e	net.(*netFD).Read+0x4e				net/fd_unix.go:202
#	0x5b191d	net.(*conn).Read+0x8d				net/net.go:184
#	0x60894f	crypto/tls.(*atLeastReader).Read+0x5f		crypto/tls/conn.go:761
#	0x4f3920	bytes.(*Buffer).ReadFrom+0xb0			bytes/buffer.go:204
#	0x608b9b	crypto/tls.(*Conn).readFromUntil+0xeb		crypto/tls/conn.go:783
#	0x607154	crypto/tls.(*Conn).readRecordOrCCS+0x114	crypto/tls/conn.go:590
#	0x60b27a	crypto/tls.(*Conn).readRecord+0x15a		crypto/tls/conn.go:558
#	0x60b285	crypto/tls.(*Conn).Read+0x165			crypto/tls/conn.go:1234
#	0x6e03a4	net/http.(*persistConn).Read+0x74		net/http/transport.go:1825
#	0x557c92	bufio.(*Reader).fill+0x102			bufio/bufio.go:100
#	0x557dfe	bufio.(*Reader).Peek+0x4e			bufio/bufio.go:138
#	0x6e1037	net/http.(*persistConn).readLoop+0x1a7		net/http/transport.go:1978

1 @ 0x437230 0x4301ea 0x42f755 0x4d0395 0x4d1703 0x4d16e5 0x59eb4b 0x5bdbea 0x5bc39d 0x8961b2 0x887a2e 0x4671f1
#	0x42f754	internal/poll.runtime_pollWait+0x54					runtime/netpoll.go:203
#	0x4d0394	internal/poll.(*pollDesc).wait+0x44					internal/poll/fd_poll_runtime.go:87
#	0x4d1702	internal/poll.(*pollDesc).waitRead+0x1a2				internal/poll/fd_poll_runtime.go:92
#	0x4d16e4	internal/poll.(*FD).ReadFrom+0x184					internal/poll/fd_unix.go:219
#	0x59eb4a	net.(*netFD).readFrom+0x5a						net/fd_unix.go:208
#	0x5bdbe9	net.(*UDPConn).readFrom+0x69						net/udpsock_posix.go:47
#	0x5bc39c	net.(*UDPConn).ReadFrom+0x5c						net/udpsock.go:118
#	0x8961b1	tailscale.com/wgengine/magicsock.(*RebindingUDPConn).ReadFrom+0xb1	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/magicsock/magicsock.go:2777
#	0x887a2d	tailscale.com/wgengine/magicsock.(*Conn).awaitUDP4+0x6d			tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/magicsock/magicsock.go:1306

1 @ 0x437230 0x4301ea 0x42f755 0x4d0395 0x4d1703 0x4d16e5 0x59eb4b 0x5bdbea 0x5bc39d 0x8961b2 0x8894bf 0x8504a4 0x4671f1
#	0x42f754	internal/poll.runtime_pollWait+0x54						runtime/netpoll.go:203
#	0x4d0394	internal/poll.(*pollDesc).wait+0x44						internal/poll/fd_poll_runtime.go:87
#	0x4d1702	internal/poll.(*pollDesc).waitRead+0x1a2					internal/poll/fd_poll_runtime.go:92
#	0x4d16e4	internal/poll.(*FD).ReadFrom+0x184						internal/poll/fd_unix.go:219
#	0x59eb4a	net.(*netFD).readFrom+0x5a							net/fd_unix.go:208
#	0x5bdbe9	net.(*UDPConn).readFrom+0x69							net/udpsock_posix.go:47
#	0x5bc39c	net.(*UDPConn).ReadFrom+0x5c							net/udpsock.go:118
#	0x8961b1	tailscale.com/wgengine/magicsock.(*RebindingUDPConn).ReadFrom+0xb1		tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/magicsock/magicsock.go:2777
#	0x8894be	tailscale.com/wgengine/magicsock.(*Conn).ReceiveIPv6+0x7e			tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/magicsock/magicsock.go:1493
#	0x8504a3	github.com/tailscale/wireguard-go/device.(*Device).RoutineReceiveIncoming+0x1a3	github.com/tailscale/wireguard-go@v0.0.0/device/receive.go:127

1 @ 0x437230 0x4301ea 0x42f755 0x4d0395 0x4d2bd4 0x4d2bb6 0x59f2c2 0x5c1cd2 0x5c0414 0x957aaa 0x963a4a 0x963323 0x436e6a 0x4671f1
#	0x42f754	internal/poll.runtime_pollWait+0x54		runtime/netpoll.go:203
#	0x4d0394	internal/poll.(*pollDesc).wait+0x44		internal/poll/fd_poll_runtime.go:87
#	0x4d2bd3	internal/poll.(*pollDesc).waitRead+0x1d3	internal/poll/fd_poll_runtime.go:92
#	0x4d2bb5	internal/poll.(*FD).Accept+0x1b5		internal/poll/fd_unix.go:384
#	0x59f2c1	net.(*netFD).accept+0x41			net/fd_unix.go:238
#	0x5c1cd1	net.(*UnixListener).accept+0x31			net/unixsock_posix.go:162
#	0x5c0413	net.(*UnixListener).Accept+0x63			net/unixsock.go:260
#	0x957aa9	tailscale.com/ipn/ipnserver.Run+0xee9		tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnserver/server.go:263
#	0x963a49	main.run+0x5b9					tailscale.com@v0.0.0-00010101000000-000000000000/cmd/tailscaled/tailscaled.go:177
#	0x963322	main.main+0x4e2					tailscale.com@v0.0.0-00010101000000-000000000000/cmd/tailscaled/tailscaled.go:106
#	0x436e69	runtime.main+0x1f9				runtime/proc.go:203

1 @ 0x437230 0x4301ea 0x42f755 0x4d0395 0x4d3ad6 0x4d3ab3 0x4dd135 0x8a7b3d 0x8a9760 0x8aa49d 0x8aa15a 0x4671f1
#	0x42f754	internal/poll.runtime_pollWait+0x54					runtime/netpoll.go:203
#	0x4d0394	internal/poll.(*pollDesc).wait+0x44					internal/poll/fd_poll_runtime.go:87
#	0x4d3ad5	internal/poll.(*pollDesc).waitRead+0xf5					internal/poll/fd_poll_runtime.go:92
#	0x4d3ab2	internal/poll.(*FD).RawRead+0xd2					internal/poll/fd_unix.go:534
#	0x4dd134	os.(*rawConn).Read+0x64							os/rawconn.go:31
#	0x8a7b3c	github.com/mdlayher/netlink.fdread+0x9c					github.com/mdlayher/netlink@v1.1.0/fdcall_gteq_1.12.go:21
#	0x8a975f	github.com/mdlayher/netlink.(*sysSocket).read.func1+0x3f		github.com/mdlayher/netlink@v1.1.0/conn_linux.go:378
#	0x8aa49c	github.com/mdlayher/netlink.(*lockedNetNSGoroutine).run.func1+0x4c	github.com/mdlayher/netlink@v1.1.0/conn_linux.go:769
#	0x8aa159	github.com/mdlayher/netlink.newLockedNetNSGoroutine.func1+0x179		github.com/mdlayher/netlink@v1.1.0/conn_linux.go:742

1 @ 0x437230 0x447523 0x6e2bdc 0x4671f1
#	0x6e2bdb	net/http.(*persistConn).writeLoop+0x11b	net/http/transport.go:2277

1 @ 0x437230 0x447523 0x8289bb 0x4671f1
#	0x8289ba	tailscale.com/control/controlclient.(*Direct).PollNetMap.func1+0x13a	tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/direct.go:544

1 @ 0x437230 0x447523 0x83f2df 0x4671f1
#	0x83f2de	github.com/tailscale/wireguard-go/tun.(*NativeTun).routineHackListener+0x21e	github.com/tailscale/wireguard-go@v0.0.0/tun/tun_linux.go:79

1 @ 0x437230 0x447523 0x8874e7 0x4671f1
#	0x8874e6	tailscale.com/wgengine/magicsock.(*Conn).runDerpWriter+0x1d6	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/magicsock/magicsock.go:1244

1 @ 0x437230 0x447523 0x8882ad 0x850a11 0x4671f1
#	0x8882ac	tailscale.com/wgengine/magicsock.(*Conn).ReceiveIPv4+0x24c			tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/magicsock/magicsock.go:1386
#	0x850a10	github.com/tailscale/wireguard-go/device.(*Device).RoutineReceiveIncoming+0x710	github.com/tailscale/wireguard-go@v0.0.0/device/receive.go:125

1 @ 0x437230 0x447523 0x89029c 0x4671f1
#	0x89029b	tailscale.com/wgengine/magicsock.(*Conn).periodicReSTUN+0x2bb	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/magicsock/magicsock.go:2186

1 @ 0x437230 0x447523 0x890646 0x4671f1
#	0x890645	tailscale.com/wgengine/magicsock.(*Conn).periodicDerpCleanup+0x115	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/magicsock/magicsock.go:2211

1 @ 0x437230 0x447523 0x8ae38f 0x4671f1
#	0x8ae38e	tailscale.com/wgengine/monitor.(*Mon).debounce+0xde	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/monitor/monitor.go:133

1 @ 0x437230 0x447523 0x90360c 0x909874 0x4671f1
#	0x90360b	tailscale.com/wgengine/tsdns.(*Resolver).NextResponse+0x12b	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tsdns/tsdns.go:165
#	0x909873	tailscale.com/wgengine.(*userspaceEngine).pollResolver+0x43	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/userspace.go:423

1 @ 0x437230 0x447523 0x903a41 0x4671f1
#	0x903a40	tailscale.com/wgengine/tsdns.(*Resolver).poll+0x130	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tsdns/tsdns.go:200

1 @ 0x437230 0x447523 0x906df3 0x8543b2 0x4671f1
#	0x906df2	tailscale.com/wgengine/tstun.(*TUN).Read+0x152					tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tstun/tun.go:261
#	0x8543b1	github.com/tailscale/wireguard-go/device.(*Device).RoutineReadFromTUN+0xf1	github.com/tailscale/wireguard-go@v0.0.0/device/send.go:278

1 @ 0x437230 0x447523 0x9132ca 0x4671f1
#	0x9132c9	tailscale.com/portlist.(*Poller).Run+0x3b9	tailscale.com@v0.0.0-00010101000000-000000000000/portlist/poller.go:89

1 @ 0x437230 0x447523 0x958107 0x4671f1
#	0x958106	tailscale.com/ipn/ipnserver.Run.func1+0xb6	tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnserver/server.go:169

1 @ 0x437230 0x447523 0x95a50e 0x95a910 0x95ad3e 0x4671f1
#	0x95a50d	tailscale.com/logtail.(*logger).drainBlock+0x16d	tailscale.com@v0.0.0-00010101000000-000000000000/logtail/logtail.go:179
#	0x95a90f	tailscale.com/logtail.(*logger).drainPending+0x3bf	tailscale.com@v0.0.0-00010101000000-000000000000/logtail/logtail.go:214
#	0x95ad3d	tailscale.com/logtail.(*logger).uploading+0x22d		tailscale.com@v0.0.0-00010101000000-000000000000/logtail/logtail.go:261

1 @ 0x437230 0x447523 0x96413c 0x4671f1
#	0x96413b	main.run.func2+0xcb	tailscale.com@v0.0.0-00010101000000-000000000000/cmd/tailscaled/tailscaled.go:159

1 @ 0x437230 0x448060 0x44804b 0x447dc7 0x47338c 0x91753a 0x9171d7 0x90e6ef 0x911e82 0x4671f1
#	0x447dc6	sync.runtime_SemacquireMutex+0x46				runtime/sema.go:71
#	0x47338b	sync.(*Mutex).lockSlow+0xfb					sync/mutex.go:138
#	0x917539	sync.(*Mutex).Lock+0x4c9					sync/mutex.go:81
#	0x9171d6	tailscale.com/ipn.(*LocalBackend).setWgengineStatus+0x166	tailscale.com@v0.0.0-00010101000000-000000000000/ipn/local.go:299
#	0x90e6ee	tailscale.com/wgengine.(*userspaceEngine).RequestStatus+0xde	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/userspace.go:1047
#	0x911e81	tailscale.com/wgengine.newUserspaceEngineAdvanced.func5+0x131	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/userspace.go:326

1 @ 0x437230 0x448060 0x44804b 0x447dc7 0x47338c 0x91753a 0x9171d7 0x90e6ef 0x912832 0x912574 0x912507 0x4671f1
#	0x447dc6	sync.runtime_SemacquireMutex+0x46					runtime/sema.go:71
#	0x47338b	sync.(*Mutex).lockSlow+0xfb						sync/mutex.go:138
#	0x917539	sync.(*Mutex).Lock+0x4c9						sync/mutex.go:81
#	0x9171d6	tailscale.com/ipn.(*LocalBackend).setWgengineStatus+0x166		tailscale.com@v0.0.0-00010101000000-000000000000/ipn/local.go:299
#	0x90e6ee	tailscale.com/wgengine.(*userspaceEngine).RequestStatus+0xde		tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/userspace.go:1047
#	0x912831	tailscale.com/wgengine.(*watchdogEngine).RequestStatus.func1+0x31	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/watchdog.go:97
#	0x912573	tailscale.com/wgengine.(*watchdogEngine).watchdog.func1+0x23		tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/watchdog.go:68
#	0x912506	tailscale.com/wgengine.(*watchdogEngine).watchdogErr.func1+0x26		tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/watchdog.go:50

1 @ 0x437230 0x448060 0x44804b 0x447dc7 0x47338c 0x919e13 0x919c50 0x4671f1
#	0x447dc6	sync.runtime_SemacquireMutex+0x46			runtime/sema.go:71
#	0x47338b	sync.(*Mutex).lockSlow+0xfb				sync/mutex.go:138
#	0x919e12	sync.(*Mutex).Lock+0x362				sync/mutex.go:81
#	0x919c4f	tailscale.com/ipn.(*LocalBackend).readPoller+0x19f	tailscale.com@v0.0.0-00010101000000-000000000000/ipn/local.go:578

1 @ 0x480755 0x7aa97c 0x7a9a94 0x82e0f2 0x82e0b4 0x83f71e 0x4671f1
#	0x480754	syscall.Syscall6+0x4								syscall/asm_linux_amd64.s:41
#	0x7aa97b	golang.org/x/sys/unix.Pselect+0xbb						golang.org/x/sys@v0.0.0-20200501052902-10377860bb8e/unix/zsyscall_linux.go:1198
#	0x7a9a93	golang.org/x/sys/unix.Select+0x93						golang.org/x/sys@v0.0.0-20200501052902-10377860bb8e/unix/syscall_linux_amd64.go:54
#	0x82e0f1	github.com/tailscale/wireguard-go/rwcancel.unixSelect+0x161			github.com/tailscale/wireguard-go@v0.0.0/rwcancel/select_linux.go:11
#	0x82e0b3	github.com/tailscale/wireguard-go/rwcancel.(*RWCancel).ReadyRead+0x123		github.com/tailscale/wireguard-go@v0.0.0/rwcancel/rwcancel.go:67
#	0x83f71d	github.com/tailscale/wireguard-go/tun.(*NativeTun).routineNetlinkListener+0x17d	github.com/tailscale/wireguard-go@v0.0.0/tun/tun_linux.go:120

1 @ 0x480755 0x7aa97c 0x7a9a94 0x82e0f2 0x82e0b4 0x855b6e 0x4671f1
#	0x480754	syscall.Syscall6+0x4								syscall/asm_linux_amd64.s:41
#	0x7aa97b	golang.org/x/sys/unix.Pselect+0xbb						golang.org/x/sys@v0.0.0-20200501052902-10377860bb8e/unix/zsyscall_linux.go:1198
#	0x7a9a93	golang.org/x/sys/unix.Select+0x93						golang.org/x/sys@v0.0.0-20200501052902-10377860bb8e/unix/syscall_linux_amd64.go:54
#	0x82e0f1	github.com/tailscale/wireguard-go/rwcancel.unixSelect+0x161			github.com/tailscale/wireguard-go@v0.0.0/rwcancel/select_linux.go:11
#	0x82e0b3	github.com/tailscale/wireguard-go/rwcancel.(*RWCancel).ReadyRead+0x123		github.com/tailscale/wireguard-go@v0.0.0/rwcancel/rwcancel.go:67
#	0x855b6d	github.com/tailscale/wireguard-go/device.(*Device).routineRouteListener+0x18d	github.com/tailscale/wireguard-go@v0.0.0/device/sticky_linux.go:62

1 @ 0x755b65 0x755980 0x75271a 0x91032a 0x910549 0x910b95 0x91e38e 0x91eb79 0x91697f 0x81a03c 0x82877f 0x820152 0x819468 0x4671f1
#	0x755b64	runtime/pprof.writeRuntimeProfile+0x94					runtime/pprof/pprof.go:694
#	0x75597f	runtime/pprof.writeGoroutine+0x9f					runtime/pprof/pprof.go:656
#	0x752719	runtime/pprof.(*Profile).WriteTo+0x3d9					runtime/pprof/pprof.go:329
#	0x910329	tailscale.com/wgengine.(*watchdogEngine).watchdogErr+0x1e9		tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/watchdog.go:59
#	0x910548	tailscale.com/wgengine.(*watchdogEngine).watchdog+0x78			tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/watchdog.go:67
#	0x910b94	tailscale.com/wgengine.(*watchdogEngine).RequestStatus+0x74		tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/watchdog.go:97
#	0x91e38d	tailscale.com/ipn.(*LocalBackend).enterState+0x23d			tailscale.com@v0.0.0-00010101000000-000000000000/ipn/local.go:1094
#	0x91eb78	tailscale.com/ipn.(*LocalBackend).stateMachine+0x38			tailscale.com@v0.0.0-00010101000000-000000000000/ipn/local.go:1167
#	0x91697e	tailscale.com/ipn.(*LocalBackend).setClientStatus+0x34e			tailscale.com@v0.0.0-00010101000000-000000000000/ipn/local.go:279
#	0x81a03b	tailscale.com/control/controlclient.(*Client).sendStatus+0x35b		tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:580
#	0x82877e	tailscale.com/control/controlclient.(*Client).mapRoutine.func2+0x1be	tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:480
#	0x820151	tailscale.com/control/controlclient.(*Direct).PollNetMap+0x1c01		tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/direct.go:683
#	0x819467	tailscale.com/control/controlclient.(*Client).mapRoutine+0x2d7		tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:451

2020/08/11 18:10:15 wgengine: watchdog timeout on RequestStatus
```

/cc @danderson @josharian

**Comment by bradfitz** [comment] 2020-08-12 23:50
(The "tailscale up" is from a Kubernetes replicaset script using authkeys that has to work regardless of whether the machine is already up)

**Comment by mkramlich** [comment] 2020-08-13 17:12
@bradfitz can we distinguish in this case between whether it might be a *livelock* happening or a true *deadlock*? I ask only because they can both trigger a watchdog function timeout

**Comment by bradfitz** [comment] 2020-08-13 17:18
I don't usually make that distinction, but I guess it's a deadlock. It's a bug in any case.

**Comment by mkramlich** [comment] 2020-08-13 17:48
@bradfitz makes sense. livelocks are much more rare in general. I'm more of a Golang newb so didn't know if the watchdog's goroutine dump above gave enough to make the distinction. guessing no

**Comment by josharian** [comment] 2020-09-24 23:10
Did this happen once or repeatably? I have been unable to reproduce locally running 8 `tailscale up` processes concurrently in a loop.

**Comment by bradfitz** [comment] 2020-09-25 17:42
I've never been able to reproduce it.

It's possible it's since been fixed.

**Comment by josharian** [comment] 2020-09-25 19:21
Manual inspection of the stack trace was not enlightening. Given all that, I'm adjusting to L1. We can reprioritize if it ever happens again.

**Comment by DentonGentry** [comment] 2021-07-31 03:14
As even 10 months ago efforts to reproduce this were not successful, and this isn't a problem we've seen in a year, I'm going to close this as fixed. We've revamped the communication channel to tailscaled several times since this was filed.

**Closed by DentonGentry** 2021-07-31 03:14 UTC
Labels: L1 Very few, P5 Halts deployment, T8 Crash
