### ISSUE TITLE
Auth Keys and non-admin accounts access to admin console.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2627] opened 2021-08-10 19:35 UTC
The customer is working on a scenario where they want to provision developer infrastructure with Terraform and automatically log in and register machine to Tailscale under the developer's account.

While this is doable with auth keys, non-admin accounts cannot access this interface right now unless they temporarily give admin access to the user. 

Workaround:

Share the service account or support account access with developers.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3gglt)

**Comment by DentonGentry** [comment] 2021-11-10 01:58
Duplicate of https://github.com/tailscale/tailscale/issues/2254

**Closed by DentonGentry** 2021-11-10 01:58 UTC
Labels: admin UI, L3 Some users, P2 Aggravating, T5 Usability
