### ISSUE TITLE
Tailscale-Android - certificate signed by unknown authority

### ISSUE THREAD

**Issue by dexxter00** [tailscale/tailscale#10373] opened 2023-11-24 12:08 UTC
### What is the issue?

Tailscale won't connect to a custom control server, but only while using domain(local IP through WiFi works).
Domain is controlled by me, which points to my home server. 
Reverse proxy with nginx which serves HTTPS with ZeroSSL certificate.
After some debugging why it won't work, connected ADB and this can be seen in the logs:

`11-24 13:41:45.986 12996 13024 I com.tailscale.ipn: 20.3M/201.0M Received error: fetch control key: Get "https://controlp.domain.com/key?v=79": x509: certificate signed by unknown authority`

What I've tried is installing ZeroSSL's CA into Android, but without any change to the issue.

### Steps to reproduce

- Use Headscale
- Install and configure nginx as a reverse proxy to the headscale server using ZeroSSL certificates
- On Tailscale app, configure your custom server
- Click "Sign in with other"

### Are there any recent changes that introduced the issue?

Not aware of such, this is first time I'm using the app.

### OS

Android

### OS version

Android 13, Samsung Galaxy A34

### Tailscale version

1.52.0

**Comment by DentonGentry** [comment] 2023-11-24 12:24
We're unlikely to be able to help with this. The certificate presented by the server needs to be valid.

**Comment by DentonGentry** [comment] 2023-11-24 13:49
Duplicate of https://github.com/tailscale/tailscale/issues/8085

**Closed by DentonGentry** 2023-11-24 13:49 UTC
Labels: needs-triage, bug

**Comment by dexxter00** [comment] 2023-11-24 14:28
> The certificate presented by the server needs to be valid.

Not sure I understand you correct. Every up to date browser trusts this exact certificate and this CA, same app on iOS 17 is also connecting without any problems(confirmed).
