### ISSUE TITLE
Tailscale connected, but network traffic doesn't reach destination on Windows

### ISSUE THREAD

**Issue by alexeiz** [tailscale/tailscale#978] opened 2020-12-01 07:52 UTC
**Describe the bug**
Tailscale daemon in the status bar indicates that Tailscale is connected.  But pinging tailscale IPs from command line (or connecting via ssh) doesn't work.

**To Reproduce**
1. Make sure Tailscale is connected.
2. Open powershell, type "tailscale status", output is something like:

[vmMIl] linux   100.91.66.111   myhost             tx=    1588 rx=   11932

3. tailscale ping 100.91.66.111

pong from myhost (100.91.66.111) via real-ip-addr:41641 in 74ms

4. ping 100.91.66.111

Request timed out.

5. ssh 100.91.66.111

ssh: connect to host 100.91.66.111 port 22: Connection timed out

**Expected behavior**

ping and connect to other hosts via tailscale should succeed

**Version information:**
 - Device: laptop computer
 - OS: Windows 10 
 - OS version: Version	10.0.19042 Build 19042
 - Tailscale version: Version 1.2.9 (tdaebded28-g17e332346)

**Additional context**
Tried reinstalling Tailscale and rebooting.  Same result.

**Comment by JDLHiguera** [comment] 2020-12-01 22:54
The exact same issue is happening to me on that Tailscale version and Windows 10 19042.630.

**Comment by alexeiz** [comment] 2020-12-02 01:16
Some more context.  I installed unstable Version 1.3.72 (teccc16773-g747822ba9).  It worked for a day.  Now it exabits the same problem.  Also I added external hello.ipn.dev/100.101.102.103 machine and tailscale ping succeeds, but normal ping doesn't:

```
> tailscale ping 100.101.102.103
pong from hello.ipn.dev (100.101.102.103) via DERP(fra) in 498ms
pong from hello.ipn.dev (100.101.102.103) via DERP(fra) in 104ms
pong from hello.ipn.dev (100.101.102.103) via 18.196.71.179:41641 in 101ms

> ping 100.101.102.103
Pinging 100.101.102.103 with 32 bytes of data:
Request timed out.
```

**Comment by bradfitz** [comment] 2020-12-02 03:45
To debug connectivity issues we'll need a date, time (with timezone) and both Tailscale IP addresses: the source and destination. (they're okay to share publicly... only you can use them) In both cases above I only see the target IP address. You seem to have two Windows machines, but not sure if you're using 100.126.131.77 or 100.71.101.100.

Can you note the time and reproduce and I'll look into it?

**Comment by alexeiz** [comment] 2020-12-08 05:46
Here's the information, hope it helps:
date/time: Dec 08, 12:36am EST
source IP: 100.126.131.77 (Windows, tailscale version 1.3.72)
destination IP: 100.86.67.95 (Linux, tailscale verson 1.2.8)

Again, `tailscale ping 100.86.67.95` works, but `ping 100.86.67.95` doesn't.  Also, `tailscale status` shows increasing `rx=` and `tx=` packet counts.

**Comment by zombiezen** [comment] 2020-12-13 16:03
Same problem here. Can't ping or ssh to Tailscale machines from my Windows machine, but `tailscale ping` works.

date: Dec 13, 08:00 PST
source Tailscale IP: 100.84.123.93 (Windows, Tailscale version 1.3.105)
destination Tailscale IP: 100.89.155.117 (Linux, Tailscale version 1.2.10)

**Comment by zombiezen** [comment] 2020-12-19 04:16
Some combination of upgrading to Windows client 1.3.122 and adding a Windows firewall rule to permit incoming UDP 41641 traffic solved it for me.

**Comment by bradfitz** [comment] 2021-01-22 04:24
1.3.122 upgraded to wintun 0.10 which fixed some corruption issues in the windows drivers.

I'm going to close this as fixed, as so far it keeps seeming to be the issue that people had previously hit.

**Closed by bradfitz** 2021-01-22 04:24 UTC
Labels: OS-windows

**Comment by WilliamPrvz** [comment] 2022-03-14 10:20
I have the exact same issue on mac. Is there any other fix ?

**Comment by bradfitz** [comment] 2022-03-14 18:34
@WilliamPrvz, we don't re-use or track old bugs. Please file a new bug with details.

**Comment by iluvatar1** [comment] 2022-03-17 00:16
@WilliamPrvz  did you file a new issue? can you give me the code to check and +1 since I have the same problem btween mac and linux? thanks

**Comment by op69qs** [comment] 2023-12-27 04:27
same problem here
BUG-73ae2de3139a6b740f69a24c7130900d8a30705d02dd67f049a7ba580c7e6e67-20231227042641Z-17929a6182f4882a

**Comment by DentonGentry** [comment] 2023-12-27 04:33
@op69qs we don't re-use or track old bugs. Please file a new bug with details.
