### ISSUE TITLE
SSH tunnel breaks on flood due to MTU size issue

### ISSUE THREAD

**Issue by woganmay** [tailscale/tailscale#4140] opened 2022-03-10 22:20 UTC
### What is the issue?

This is admittedly quite an edge-case, and I have a workaround, but I thought I'd log this anyway. 

We're running an exit node that's advertising a few IPs on the public internet (we can't put those devices on tailscale yet). That works 100% in almost all cases except this one:

* Running WSL (Ubuntu) on Windows
* Opening an SSH connection from inside WSL, over the tailnet, through the exit node, to the remote machine
* Doing anything that triggers lots of output - `cat filename` does this reliably

I'll get a few lines of output, then the tunnel seems to go down. It takes a while for ssh to recognize that the pipe is broken.

This is not an issue when opening an SSH connection from Windows itself to the remote machine, and connections from inside WSL to other devices on the tailnet work just fine. Something about the combination of running inside WSL + using an exit node is triggering this.

### Steps to reproduce

In the description above

### Are there any recent changes that introduced the issue?

None that I know of - it's been doing this since we started using tailscale.

### OS

Linux, Windows

### OS version

Ubuntu 20.04.3 LTS on WSL

### Tailscale version

1.22.0 (Client) and 1.20.2 (Linux Server)

### Bug report

BUG-6585ba6ec690381d817f45b593543d1ebb8898aceb54ccb4c6bcaf70b8827607-20220310222012Z-5397be6c62288a26

**Comment by danderson** [comment] 2022-03-10 22:24
This is almost certainly a path MTU problem somewhere along the line. The classic symptom is "stuff works until I put a bit of load on it, then it falls over", which is caused by each packet getting larger until it finally exceeds the path MTU. Tailscale tries to set MTUs that work everywhere, so the main goal is going to be figuring out where in the path things are going wrong in your setup.

Have you adjusted MTU anywhere in your setup? Are you running tailscale inside WSL, or relaying through Tailscale installed on the host Windows OS? Can you provide the output of `ip link` on the exit node machine?

Thanks!

**Comment by woganmay** [comment] 2022-03-18 08:00
Hey @danderson! That actually makes sense, thanks :)

In my local setup I'm running Tailscale on the host OS:

![image](https://user-images.githubusercontent.com/225550/158960259-ec2fccbf-4d40-4fdd-b6ce-5ceccd8d912b.png)

This is what the exit node comes back with:

![image](https://user-images.githubusercontent.com/225550/158960363-f39b9cd3-1f93-4857-b6a7-9d0ca9aae0a7.png)

**Comment by franzbischoff** [comment] 2022-04-20 17:03
Hello,

I'm having the same issue here, using WSL2. This bug appeared suddenly, more precisely at March 15. I decided to dig in and found this thread.

My solution at the time for using ssh was to tunnel the connection thru another device at my intranet. Today I tested other configurations and I found:

- The "bug" only happens when using the tailscale0 interface. Direct connection from Windows host to WSL works normally.
- The tunneler device (a rasp pi 3b with tailscale) works only when I have the subnet route enabled. If not, the bug happens anyway. In both settings I'm using the magicdns, so I think that the tunneler device tries to connect to the tailscale0 IP range, with or without the subnet enabled.

My `ip link` output on WSL environment:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 12:d2:be:97:0a:b8 brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether be:d3:9a:3d:aa:87 brd ff:ff:ff:ff:ff:ff
4: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
5: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
6: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:15:5d:86:e3:a1 brd ff:ff:ff:ff:ff:ff
7: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 500
    link/none
```

**Comment by DentonGentry** [comment] 2022-04-20 17:05
If all else fails, a likely way to avoid the problem is to make the subnet router clamp the MSS:
```
iptables -t mangle -A FORWARD -i tailscale0 -o eth0 -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
```

Replace eth0 with the name of the LAN interface.

**Comment by franzbischoff** [comment] 2022-04-20 18:23
I would like to connect directly without the subnet router. Should I apply this to the tailscale0 interface in the WSL2 environment?

**Comment by DentonGentry** [comment] 2022-04-21 01:25
> I would like to connect directly without the subnet router. Should I apply this to the tailscale0 interface in the WSL2 environment?

If Tailscale is running directly within WSL there really shouldn't be an MTU size issue. The tailscale0 interface inside WSL has an MTU of 1280 bytes, the TCP MSS will be 1280 bytes.

If there is still an issue running directly inside WSL, I think there is something other than MTU size going on.

**Comment by mhlakhani** [comment] 2022-08-17 16:34
@woganmay @franzbischoff : is there any chance the issue is fixed for you after running the following from within WSL2:

`sudo ip link set dev eth0 mtu 1500`

I was running into the same issue and that command finally fixed it for me (more details in https://github.com/tailscale/tailscale/issues/4833#issuecomment-1218250645)

**Comment by franzbischoff** [comment] 2022-08-18 07:20
Hi @mhlakhani, let me check if this issue wasn't "auto-fixed" yet. Last time I remember I had not this issue. But who knows :-)

BR.

**Comment by franzbischoff** [comment] 2022-08-18 07:30
@mhlakhani still bugged.

**Comment by kevmo314** [comment] 2022-12-28 13:36
> @woganmay @franzbischoff : is there any chance the issue is fixed for you after running the following from within WSL2:
> 
> `sudo ip link set dev eth0 mtu 1500`
> 
> I was running into the same issue and that command finally fixed it for me (more details in [#4833 (comment)](https://github.com/tailscale/tailscale/issues/4833#issuecomment-1218250645))

Is there any way to make this fix more permanent? I currently have to run it every Windows reboot.

**Comment by mhlakhani** [comment] 2022-12-28 18:26
> Is there any way to make this fix more permanent? I currently have to run it every Windows reboot.

@kevmo314 the instructions in this comment are what works for me: https://github.com/tailscale/tailscale/issues/562#issuecomment-1218257594

In particular here's my `/etc/wsl.conf`:

```
[boot]
command = "bash /etc/init-wsl.sh"
systemd = true
```

and the contents of that referenced script are:

```
#!/bin/bash
ip link set dev eth0 mtu 1500
```

I did something like this to start WSL automatically on windows boot (https://techbrij.com/wsl-2-ubuntu-services-windows-10-startup)

**Comment by DentonGentry** [comment] 2023-02-13 00:11
Though https://github.com/tailscale/tailscale/issues/4833 was filed later, there is more detail about remaining steps on that bug so I want to leave it open.

Duplicate of https://github.com/tailscale/tailscale/issues/4833

**Closed by DentonGentry** 2023-02-13 00:11 UTC
Labels: OS-windows, L1 Very few, P2 Aggravating, T5 Usability, bug
