### ISSUE TITLE
FR: Show online status in mobile app

### ISSUE THREAD

**Issue by t-muehlberger** [tailscale/tailscale#7380] opened 2023-02-25 18:17 UTC
### What are you trying to do?

Hello, love your product and have it running on all my personal computers including my home-server and several rasperry pies in different locations. I find myself often using `tailscale status` to check if devices are up and running. It would be great to have a quick and easy way to check the status on my phone too. But to my knowledge the mobile app does not provide this information. 

### How should we solve this?

Display a green circle next to the names of the machines that are online right now similar to the Web-UI. 

### What is the impact of not solving this?

Only minor inconvenience. 

### Anything else?

Edit: Please excuse my in case this FR was already asked, I tried searching for similar issues and did not find any.

**Comment by DentonGentry** [comment] 2023-02-25 18:59
Duplicate of https://github.com/tailscale/tailscale/issues/2771 and https://github.com/tailscale/tailscale/issues/2317

**Closed by DentonGentry** 2023-02-25 18:59 UTC
Labels: needs-triage, fr
