### ISSUE TITLE
Allow exit-node-lan-access for other subnets, apart from local one

### ISSUE THREAD

**Issue by Omrigan** [tailscale/tailscale#4650] opened 2022-05-09 20:18 UTC
What can I do if I have some routes which are not part of my subnet (192.168.1.0/24), but still only accessible locally (192.168.3.0/24, where I keep all of my IoT devices). 
As I noticed, `--exit-node-allow-lan-access` adds `throw 192.168.1.0/24` to the table 52. Maybe the option should be added like `--exit-node-local-routes 192.168.0.0/16`?

Also, if I  `--advertise-routes=192.168.0.0/16` it wouldn't work, since `192.168.3.0/24` not even accessible from the host.

_Originally posted by @Omrigan in https://github.com/tailscale/tailscale/issues/1527#issuecomment-985725574_

**Comment by rweirtbg** [comment] 2022-08-22 02:06
We definitely need this feature! Very excited for it!

**Comment by DentonGentry** [comment] 2022-10-31 03:36
Duplicate of https://github.com/tailscale/tailscale/issues/3646

**Closed by DentonGentry** 2022-10-31 03:36 UTC
Labels: L1 Very few, P2 Aggravating, T0 New feature
