### ISSUE TITLE
FR: create a gcp cloud builder for tailscale

### ISSUE THREAD

**Issue by rojomisin** [tailscale/tailscale#8259] opened 2023-06-02 20:54 UTC
### What are you trying to do?

I am trying to use tailscaled in google cloud build to proxy to resources in the vpc easily as google networking can get complicated quickly using private service networks.  

### How should we solve this?

package up the tailscale container like it's done for GH actions
https://github.com/tailscale/github-action/blob/main/action.yml

using the cloud builder community pattern
https://github.com/GoogleCloudPlatform/cloud-builders-community

### What is the impact of not solving this?

people building their own custom containers in different ways

**Comment by DentonGentry** [comment] 2023-06-02 21:18
Duplicate of https://github.com/tailscale/tailscale/issues/8189

**Closed by DentonGentry** 2023-06-02 21:18 UTC
Labels: L2 Few, P3 Can't get started, T0 New feature, containers, fr
