### ISSUE TITLE
derp: lots of connecting / EOF messages

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#109] opened 2020-02-28 03:30 UTC
Built at HEAD with NetInfo:

```
morty:~> journalctl -fu tailscaled
-- Logs begin at Thu 2018-02-22 12:57:10 EST. --
Feb 27 22:28:49 morty tailscaled[36344]: 2020/02/27 22:28:49 derphttp.Client.Recv: connecting
Feb 27 22:28:49 morty tailscaled[36344]: 2020/02/27 22:28:49 derp.Recv: derp.Recv: EOF
Feb 27 22:28:49 morty tailscaled[36344]: 2020/02/27 22:28:49 derphttp.Client.Recv: connecting
Feb 27 22:28:49 morty tailscaled[36344]: 2020/02/27 22:28:49 derp.Recv: derp.Recv: EOF
Feb 27 22:28:50 morty tailscaled[36344]: 2020/02/27 22:28:50 derphttp.Client.Recv: connecting
Feb 27 22:28:50 morty tailscaled[36344]: 2020/02/27 22:28:50 derp.Recv: derp.Recv: EOF
Feb 27 22:28:50 morty tailscaled[36344]: 2020/02/27 22:28:50 derphttp.Client.Recv: connecting
Feb 27 22:28:50 morty tailscaled[36344]: 2020/02/27 22:28:50 derp.Recv: derp.Recv: EOF
Feb 27 22:28:51 morty tailscaled[36344]: 2020/02/27 22:28:51 derphttp.Client.Recv: connecting
Feb 27 22:28:51 morty tailscaled[36344]: 2020/02/27 22:28:51 derp.Recv: derp.Recv: EOF
Feb 27 22:28:51 morty tailscaled[36344]: 2020/02/27 22:28:51 derphttp.Client.Recv: connecting
Feb 27 22:28:51 morty tailscaled[36344]: 2020/02/27 22:28:51 derp.Recv: derp.Recv: EOF
Feb 27 22:28:52 morty tailscaled[36344]: 2020/02/27 22:28:52 derphttp.Client.Recv: connecting
Feb 27 22:28:52 morty tailscaled[36344]: 2020/02/27 22:28:52 derp.Recv: derp.Recv: EOF
Feb 27 22:28:52 morty tailscaled[36344]: 2020/02/27 22:28:52 derphttp.Client.Recv: connecting
Feb 27 22:28:52 morty tailscaled[36344]: 2020/02/27 22:28:52 derp.Recv: derp.Recv: EOF
```

cc @bradfitz

**Comment by bradfitz** [comment] 2020-02-28 04:01
I can reproduce. The server's doing a lot of kicking off connections with the same key. (it enforces that only one TCP connection per key can be connected...)

Investigating.

**Comment by bradfitz** [comment] 2020-02-28 15:50
And if I delay the net.Conn.Close on the server side by 10 seconds, then I only see the close+reconnect messages every 10 seconds, rather than non-stop:

```patch
diff --git a/derp/derp_server.go b/derp/derp_server.go
index 6e164cea..ab3721a2 100644
--- a/derp/derp_server.go
+++ b/derp/derp_server.go
@@ -132,7 +132,10 @@ func (s *Server) registerClient(c *sclient) {
        if old == nil {
                s.logf("derp: %s: client %x: adding connection", c.nc.RemoteAddr(), c.key)
        } else {
-               old.nc.Close()
+               go func() {
+                       time.Sleep(10 * time.Second)
+                       old.nc.Close()
+               }()
                s.logf("derp: %s: client %x: adding connection, replacing %s", c.nc.RemoteAddr(), c.key, old.nc.RemoteAddr())
        }
        s.clients[c.key] = c
```

The bug is likely in the the derp client(s) and how they deal with rescheduling connects.

**Comment by crawshaw** [comment] 2020-03-10 01:58
Could it be that there's more than one `*derphttp.Client` instance in the node trying to connect to the same derp server? So the first one connects, starts listening for a packet, then the second one connects and then the server disconnects the first one, then the cycle repeats?

**Comment by bradfitz** [comment] 2020-03-10 04:14
I thought this was fixed already, but I forget now what it was. Or did you just see it again, @crawshaw?

**Comment by bradfitz** [comment] 2020-03-10 04:16
Yeah, fixed by a36ccb8525c3285d31fe84b27d2a7419bd7b61b6.

**Comment by bradfitz** [comment] 2020-03-10 04:16
(But re-open if you saw it again.)

**Comment by danderson** [comment] 2020-03-10 04:21
We saw it today on the Seattle ipad pro, it was preventing me from talking to anything via DERP SFO.

**Comment by bradfitz** [comment] 2020-03-10 04:25
Got logs?

**Comment by danderson** [comment] 2020-03-10 17:42
@crawshaw had some while looking at ipad logs, but not sure where they are.

**Comment by bradfitz** [comment] 2020-03-11 20:12
I found them:


```
~/logcatcher$ grep -i -E 'derp|recv' tailnode.log.tailscale.io_25b4cbbb0557f5971ab79b912ad0e77982a3b5933f0d21b153925567741004be_2020-03-10-012525.874.logtail.partial 
{"logtail":{"client_time":"2020-03-10T01:28:43.921477Z","server_time":"2020-03-10T01:28:43.931870498Z"},"text":"derphttp.Client.Send: connecting to https://derp4.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:28:43.921604Z","server_time":"2020-03-10T01:28:43.931870498Z"},"text":"Dialing: \"derp4.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:28:47.749322Z","server_time":"2020-03-10T01:28:47.76176736Z"},"text":"derphttp.Client.Send: connecting to https://derp2.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:28:47.749381Z","server_time":"2020-03-10T01:28:47.76176736Z"},"text":"Dialing: \"derp2.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:30:54.609464Z","server_time":"2020-03-10T01:30:54.626232694Z"},"text":"derphttp.Client.Send: connecting to https://derp3.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:30:54.609661Z","server_time":"2020-03-10T01:30:54.626232694Z"},"text":"Dialing: \"derp3.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:31:46.13013Z","server_time":"2020-03-10T01:31:46.145767557Z"},"text":"derp.Recv(derp4): derp.Recv: read tcp 192.168.16.190:61404-\u003e167.172.182.26:443: i/o timeout\n"}
{"logtail":{"client_time":"2020-03-10T01:31:46.385382Z","server_time":"2020-03-10T01:31:46.396436649Z"},"text":"derphttp.Client.Recv: connecting to https://derp4.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:31:46.385765Z","server_time":"2020-03-10T01:31:46.396436649Z"},"text":"Dialing: \"derp4.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:33:38.233656Z","server_time":"2020-03-10T01:33:38.24341843Z"},"text":"derp.Recv(derp2): derp.Recv: EOF\n"}
{"logtail":{"client_time":"2020-03-10T01:33:38.489344Z","server_time":"2020-03-10T01:33:38.500941419Z"},"text":"derphttp.Client.Recv: connecting to https://derp2.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:33:38.489732Z","server_time":"2020-03-10T01:33:38.500941419Z"},"text":"Dialing: \"derp2.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:33:59.040971Z","server_time":"2020-03-10T01:33:59.057758185Z"},"text":"derphttp.Client.Send: connecting to https://derp2.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:33:59.041121Z","server_time":"2020-03-10T01:33:59.057758185Z"},"text":"Dialing: \"derp2.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:33:59.150531Z","server_time":"2020-03-10T01:33:59.159752303Z"},"text":"derp.Recv(derp3): derp.Recv: read tcp 192.168.16.190:61406-\u003e68.183.179.66:443: i/o timeout\n"}
{"logtail":{"client_time":"2020-03-10T01:33:59.405513Z","server_time":"2020-03-10T01:33:59.416415365Z"},"text":"derphttp.Client.Recv: connecting to https://derp3.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:33:59.405857Z","server_time":"2020-03-10T01:33:59.416415365Z"},"text":"Dialing: \"derp3.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:34:14.567059Z","server_time":"2020-03-10T01:34:14.57826711Z"},"text":"derphttp.Client.Send: connecting to https://derp2.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:34:14.567229Z","server_time":"2020-03-10T01:34:14.57826711Z"},"text":"Dialing: \"derp2.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:34:25.239237Z","server_time":"2020-03-10T01:34:25.26725996Z"},"text":"derphttp.Client.Send: connecting to https://derp1.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:34:25.239307Z","server_time":"2020-03-10T01:34:25.26725996Z"},"text":"Dialing: \"derp1.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:34:25.23971Z","server_time":"2020-03-10T01:34:25.26725996Z"},"text":"derphttp.Client.Recv: connecting to https://derp2.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:34:25.239774Z","server_time":"2020-03-10T01:34:25.26725996Z"},"text":"Dialing: \"derp2.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:34:26.422308Z","server_time":"2020-03-10T01:34:26.431741328Z"},"text":"derp.Recv(derp2): derp.Recv: EOF\n"}
{"logtail":{"client_time":"2020-03-10T01:34:26.677831Z","server_time":"2020-03-10T01:34:26.694498872Z"},"text":"derphttp.Client.Recv: connecting to https://derp2.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:34:26.678194Z","server_time":"2020-03-10T01:34:26.694498872Z"},"text":"Dialing: \"derp2.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:34:27.484865Z","server_time":"2020-03-10T01:34:27.49489711Z"},"text":"derp.Recv(derp2): derp.Recv: EOF\n"}
{"logtail":{"client_time":"2020-03-10T01:34:27.738066Z","server_time":"2020-03-10T01:34:27.755315015Z"},"text":"derphttp.Client.Recv: connecting to https://derp2.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:34:27.738496Z","server_time":"2020-03-10T01:34:27.770268641Z"},"text":"Dialing: \"derp2.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:34:29.777082Z","server_time":"2020-03-10T01:34:29.786935314Z"},"text":"derp.Recv(derp2): derp.Recv: EOF\n"}
{"logtail":{"client_time":"2020-03-10T01:34:30.03264Z","server_time":"2020-03-10T01:34:30.049785915Z"},"text":"derphttp.Client.Recv: connecting to https://derp2.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:34:30.032979Z","server_time":"2020-03-10T01:34:30.049785915Z"},"text":"Dialing: \"derp2.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:34:32.871367Z","server_time":"2020-03-10T01:34:32.881273796Z"},"text":"derp.Recv(derp2): derp.Recv: EOF\n"}
{"logtail":{"client_time":"2020-03-10T01:34:33.124464Z","server_time":"2020-03-10T01:34:33.14128063Z"},"text":"derphttp.Client.Recv: connecting to https://derp2.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:34:33.124725Z","server_time":"2020-03-10T01:34:33.14128063Z"},"text":"Dialing: \"derp2.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:34:37.051131Z","server_time":"2020-03-10T01:34:37.061504064Z"},"text":"derp.Recv(derp2): derp.Recv: EOF\n"}
{"logtail":{"client_time":"2020-03-10T01:34:37.306811Z","server_time":"2020-03-10T01:34:37.323760492Z"},"text":"derphttp.Client.Recv: connecting to https://derp2.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:34:37.307223Z","server_time":"2020-03-10T01:34:37.323760492Z"},"text":"Dialing: \"derp2.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:34:42.118025Z","server_time":"2020-03-10T01:34:42.130316057Z"},"text":"derp.Recv(derp2): derp.Recv: EOF\n"}
{"logtail":{"client_time":"2020-03-10T01:34:42.371163Z","server_time":"2020-03-10T01:34:42.383775184Z"},"text":"derphttp.Client.Recv: connecting to https://derp2.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:34:42.371466Z","server_time":"2020-03-10T01:34:42.383775184Z"},"text":"Dialing: \"derp2.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:34:47.297847Z","server_time":"2020-03-10T01:34:47.307276777Z"},"text":"derp.Recv(derp2): derp.Recv: EOF\n"}
{"logtail":{"client_time":"2020-03-10T01:34:47.382364Z","server_time":"2020-03-10T01:34:47.393287403Z"},"text":"derp.Recv(derp4): derp.Recv: read tcp 192.168.16.190:61407-\u003e167.172.182.26:443: i/o timeout\n"}
{"logtail":{"client_time":"2020-03-10T01:34:47.55344Z","server_time":"2020-03-10T01:34:47.564296353Z"},"text":"derphttp.Client.Recv: connecting to https://derp2.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:34:47.553843Z","server_time":"2020-03-10T01:34:47.580439046Z"},"text":"Dialing: \"derp2.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:34:47.63746Z","server_time":"2020-03-10T01:34:47.648437408Z"},"text":"derphttp.Client.Recv: connecting to https://derp4.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:34:47.637784Z","server_time":"2020-03-10T01:34:47.648437408Z"},"text":"Dialing: \"derp4.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:34:52.62792Z","server_time":"2020-03-10T01:34:52.638023912Z"},"text":"derp.Recv(derp2): derp.Recv: EOF\n"}
{"logtail":{"client_time":"2020-03-10T01:34:52.88343Z","server_time":"2020-03-10T01:34:52.894459873Z"},"text":"derphttp.Client.Recv: connecting to https://derp2.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:34:52.883692Z","server_time":"2020-03-10T01:34:52.894459873Z"},"text":"Dialing: \"derp2.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:34:57.708774Z","server_time":"2020-03-10T01:34:57.720263424Z"},"text":"derp.Recv(derp2): derp.Recv: EOF\n"}
{"logtail":{"client_time":"2020-03-10T01:34:57.964302Z","server_time":"2020-03-10T01:34:57.981289145Z"},"text":"derphttp.Client.Recv: connecting to https://derp2.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:34:57.964527Z","server_time":"2020-03-10T01:34:57.981289145Z"},"text":"Dialing: \"derp2.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:35:54.43412Z","server_time":"2020-03-10T01:35:54.452009449Z"},"text":"magicsock: Conn.Send(127.3.3.40:2): too many DERP packets queued; dropping\n"}
{"logtail":{"client_time":"2020-03-10T01:37:01.733954Z","server_time":"2020-03-10T01:37:01.749311045Z"},"text":"derp.Recv(derp3): derp.Recv: read tcp 192.168.16.190:61410-\u003e68.183.179.66:443: i/o timeout\n"}
{"logtail":{"client_time":"2020-03-10T01:37:01.989594Z","server_time":"2020-03-10T01:37:02.006806141Z"},"text":"derphttp.Client.Recv: connecting to https://derp3.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:37:01.98987Z","server_time":"2020-03-10T01:37:02.006806141Z"},"text":"Dialing: \"derp3.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:37:26.51082Z","server_time":"2020-03-10T01:37:26.526877191Z"},"text":"derp.Recv(derp1): derp.Recv: read tcp 192.168.16.190:61412-\u003e159.89.225.99:443: i/o timeout\n"}
{"logtail":{"client_time":"2020-03-10T01:37:26.766361Z","server_time":"2020-03-10T01:37:26.777798421Z"},"text":"derphttp.Client.Recv: connecting to https://derp1.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:37:26.766708Z","server_time":"2020-03-10T01:37:26.777798421Z"},"text":"Dialing: \"derp1.tailscale.com:443\"\n"}
{"logtail":{"client_time":"2020-03-10T01:37:53.140504Z","server_time":"2020-03-10T01:37:53.155817491Z"},"text":"derp.Recv(derp4): derp.Recv: read tcp 192.168.16.190:61421-\u003e167.172.182.26:443: i/o timeout\n"}
{"logtail":{"client_time":"2020-03-10T01:37:53.394719Z","server_time":"2020-03-10T01:37:53.405799018Z"},"text":"derphttp.Client.Recv: connecting to https://derp4.tailscale.com/derp\n"}
{"logtail":{"client_time":"2020-03-10T01:37:53.395136Z","server_time":"2020-03-10T01:37:53.405799018Z"},"text":"Dialing: \"derp4.tailscale.com:443\"\n"}
```

**Comment by bradfitz** [comment] 2020-03-11 22:50
@crawshaw, see the logging commit I just pushed (above).

I suspect the problem is that `closeDerpLocked` is immediately clearing the item from `activeDerp`, which means another request to send can immediately make a new connection and send, before the other is fully shut down.

Instead, closeDerpLocked should still be fast but should do something like:

* add a done channel to a new map, closed when the current two goroutines and the derphttp.Client are all fully closed.
* start a new goroutine to close that done channel when the read+write goroutines are fully shut down
* make the runDerpReader & runDerpWriter goroutines take a new optional "prevDone" channel that, if non-nil, they have to read from before continuing, so they don't start their lazy connect until the previous one is gone.

Just a theory, but seems plausible. We could probably confirm by looking at those logs above more, looking for the timeout shutdown & reconnect lines.

**Comment by bradfitz** [comment] 2020-03-12 01:02
DERP home moves don't seem correlated with replaced connections...

<img width="721" alt="Screen Shot 2020-03-11 at 6 01 09 PM" src="https://user-images.githubusercontent.com/2621/76477373-5ccd8700-63c2-11ea-8820-5c4e3fadd61b.png">

/cc @danderson

**Comment by bradfitz** [comment] 2020-03-16 05:23
I'm calling this fixed. Graphs look nice.

**Closed by bradfitz** 2020-03-16 05:23 UTC
Labels: release-blocker
