### ISSUE TITLE
[Android Beta Client] Cannot connect to alternate (self-hosted) headscale server

### ISSUE THREAD

**Issue by Ziomal12** [tailscale/tailscale#11716] opened 2024-04-13 08:12 UTC
### What is the issue?

When adding self-hosted headscale server, Tailscale's login screen appears as if it didn't register the URL provided. The login was working with Tailscale stable app (1.41.1 and 1.60.0, both tested). Clearing Tailscale's data didnt fix it. Reinstalling the app didn't fix it either.

### Steps to reproduce

Settings -> Accounts -> dot and entering an address for self-hosted headscale server, login screen for tailscale apperas (with tailscale.com domain)

### Are there any recent changes that introduced the issue?

Updating to BETA Tailscale android client.

### OS

Android

### OS version

Android 14

### Tailscale version

v1.65.0-t220764331-g50bb25aca2d

### Other software

Headscale [v0.23.0-alpha5](https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha5)

### Bug report

BUG-df78f1ff5133b886ffdfd03bdd886d8385aea68764263175d9116b7ddcef1159-20240413080756Z-9c8ffd0aa0eaa162

**Comment by arcoast** [comment] 2024-04-13 09:32
FWIW I can reproduce this too and came here to report it.

**Comment by Ziomal12** [comment] 2024-04-13 09:34
@arcoast What version of Headscale (or other control server) are you using?

**Comment by Damix48** [comment] 2024-04-13 10:11
> @arcoast What version of Headscale (or other control server) are you using?

Same setup as yours and same problem

**Comment by arcoast** [comment] 2024-04-13 10:30
> @arcoast What version of Headscale (or other control server) are you using?

I'm also using v0.23 alpha 5 of Headscale (with OIDC via Authelia)

**Comment by Ziomal12** [comment] 2024-04-13 10:42
I've just tested with v0.22.3 and still get the same result. What's interesting is that even if I provide totally bogus URL it still tries to connect to tailscale.com. I think this may be an issiue that the app doesn't use the URL provided at all.

**Comment by arcoast** [comment] 2024-04-13 10:44
> I've just tested with v0.22.3 and still get the same result. What's interesting is that even if I provide totally bogus URL it still tries to connect to tailscale.com. I think this may be an issiue that the app doesn't use the URL provided at all.

That's my conclusion too.  Whilst the box is there, it doesn't seem to have any actual functionality currently.

**Comment by martijnboers** [comment] 2024-04-13 12:56
I'm trying to leave the beta program but still get served the new app (Version 1.65.0-t220764331)

Anything else I can do which doesn't involve finding earlier builds online?

**Comment by Ziomal12** [comment] 2024-04-13 13:19
@martijnboers I've read it can take up to 4 hours for Google Play to serve you public build again. So just wait.

Or you can use fdroid.

**Comment by agottardo** [comment] 2024-04-13 15:32
Thanks for the reports, we'll get this fixed. 👍

**Comment by agottardo** [comment] 2024-04-13 19:46
Fix is up at https://github.com/tailscale/tailscale-android/pull/325, it will land in the next beta build once approved and merged.

**Comment by Ziomal12** [comment] 2024-04-13 19:51
Amazing, thank you for your work!
Is it possible to build the apk with your fix for my use?
Can I just pull the repo, merge the branch, "make dockershell", "make apk" and copy the apk to my phone and install? Or is it more complicated than that?

**Comment by agottardo** [comment] 2024-04-13 19:58
> Amazing, thank you for your work! Is it possible to build the apk with your fix for my use? Can I just pull the repo, merge the branch, "make dockershell", "make apk" and copy the apk to my phone and install? Or is it more complicated than that?

Yeah, if you checkout the branch. What I personally do:

1. Run `make libtailscale`
2. Run the `android` configuration in Android Studio

`make apk` should also work if you want, what matters is that you run `make libtailscale` first

**Comment by Ziomal12** [comment] 2024-04-13 21:09
Can confirm. Your fix works!

**Comment by MulverineX** [comment] 2024-04-15 00:41
@Ziomal12 could you upload the APK file so people can install it manually for now?

**Comment by Ziomal12** [comment] 2024-04-15 05:04
@MulverineX please remember that installing random apk is not secure and that this is intellectual property of Tailscale. That being said [here you go](https://drive.google.com/file/d/1xBgJkeLtAONTT5Lc7gEYG4ACHAYKBjzy/view?usp=drivesdk).

I would really appreciate if you could say if you experience the same problem as me and even if you don't if you'd say so and share your setup. #11731

**Comment by MulverineX** [comment] 2024-04-15 05:50
Hmm, alright I gave it a try and everything works right up until the part where I try to load a web page being hosted in my tailscale network.

**Comment by MulverineX** [comment] 2024-04-15 05:52
@Ziomal12 thank you for sharing, not sure why its not working for me :/. I don't know what version the regression was in, but I tried going back to 1.54 and it works.

**Comment by Ziomal12** [comment] 2024-04-15 05:53
What tool are you using to ping? And what version of Headscale are you using? Would you mind commenting this and some more info when you have time on the next issiue I've linked previously? So they can start working on it in time for next release.

**Comment by MulverineX** [comment] 2024-04-15 06:05
https://github.com/tailscale/tailscale/issues/11731#issuecomment-2055470378

**Closed** 2024-04-15 15:21 UTC
Labels: OS-android, bug, release-blocker

**Comment by agottardo** [comment] 2024-04-15 18:59
205 (1.65.4-t7a77a2edf-gfab2f183b34) is now rolling out on the Play Store open testing track, and should include a fix for this issue.

**Comment by Paragoumba** [comment] 2024-04-15 19:03
I have installed this exact version from the Play Store and it doesn't seem to work, entering the url and tapping add account opens tailscale.com. The version I compiled from the pull request works though

**Comment by agottardo** [comment] 2024-04-15 19:07
> I have installed this exact version from the Play Store and it doesn't seem to work, entering the url and tapping add account opens tailscale.com. The version I compiled from the pull request works though

Investigating, thanks

**Comment by Ziomal12** [comment] 2024-04-15 19:08
@Paragoumba Check the version number, I don't think it propagated yet, at least not for me (Play store still shows 1.65.0 as newest for me)

**Comment by Norodix** [comment] 2024-04-15 19:09
I see the exact release version 1.65.4-t7a77a2edf-gfab2f183b34 and still have the issue.

**Comment by agottardo** [comment] 2024-04-15 19:10
Yeah, I'm still seeing the issue as well, something went wrong in the build process and we didn't pull the commit. I'll make a new build shortly and push it out.

**Comment by Paragoumba** [comment] 2024-04-15 19:10
@Ziomal12 I have and it it the same as @Norodix (1.65.4-t7a77a2edf-gfab2f183b34)

**Comment by MulverineX** [comment] 2024-04-15 20:24
@agottardo as for the issue of not actually being able to connect to anything hosted on the nodes?

**Comment by agottardo** [comment] 2024-04-15 20:34
> @agottardo as for the issue of not actually being able to connect to anything hosted on the nodes? Can't even SSH in 😅

That is most likely some unrelated to this issue, and is already tracked in https://github.com/tailscale/tailscale/issues/11731.

**Comment by agottardo** [comment] 2024-04-15 21:31
Version 206 (1.65.4-t7a77a2edf-**gf95428f7fa4**) is rolling out on the Play Store testing track, and appears to have the fix included.

**Comment by arcoast** [comment] 2024-04-15 22:09
@agottardo Just tested and can confirm the issue is fixed for me.  Many thanks for the speedy resolution, it's much appreciated!

**Comment by Paragoumba** [comment] 2024-04-15 22:11
Works for me too! Thanks for the fix

**Comment by Snuupy** [comment] 2024-04-16 16:30
There is now a different bug, also related to connecting to self-hosted headscale server on android. The hostname is now "localhost" instead of the device hostname.

I downgraded to 1.60.1 and the device hostname registers successfully (for me, `google-pixel-6a`), but on the updated beta on play store the hostname shows `localhost`. This obviously makes it hard to identify which device is which.

**Comment by MulverineX** [comment] 2024-04-16 16:32
@agottardo as for the issue of not actually being able to connect to anything hosted on the nodes?

**Comment by MulverineX** [comment] 2024-04-16 16:33
Yeah, I reproduced that issue, that's a minor thing, mostly concerned about not being able to access any services 🤣

**Comment by GJCav** [comment] 2024-09-08 15:20
After 4 months, this bug occurs again. I installed tailscale from google play with the latest version. The exact ver number was "1.72.0-taa448d5a9-g". After tapping the "use an alternate server", the client went back to the home view, where the "Login in" did no response to any further tapping.

It did not seem to be a headscale bug, because my Win PC successfully logined to my self-host login server.

May the kind maintainers re-open the issue and investigate it further. Thanks for all your hard work

**Comment by arcoast** [comment] 2024-09-12 19:44
> After 4 months, this bug occurs again. I installed tailscale from google play with the latest version. The exact ver number was "1.72.0-taa448d5a9-g". After tapping the "use an alternate server", the client went back to the home view, where the "Login in" did no response to any further tapping.
> 
> It did not seem to be a headscale bug, because my Win PC successfully logined to my self-host login server.
> 
> May the kind maintainers re-open the issue and investigate it further. Thanks for all your hard work

I don't use headscale every day, so I checked mine, currently on version `1.73.114-t0970615b1-g` installed from Android Playstore, I wiped the cache and all the application data and was able to login successfully to my self-hosted headscale server, so it may be fixed already.

**Comment by Pierre-Brocas** [comment] 2024-09-13 20:38
> After 4 months, this bug occurs again. I installed tailscale from google play with the latest version. The exact ver number was "1.72.0-taa448d5a9-g". After tapping the "use an alternate server", the client went back to the home view, where the "Login in" did no response to any further tapping.
> 
> It did not seem to be a headscale bug, because my Win PC successfully logined to my self-host login server.
> 
> May the kind maintainers re-open the issue and investigate it further. Thanks for all your hard work

I had the same issue today and I think I found why !
I'm using the tailscale android app from F-droid (Version 1.72.0 (254))  and the headscale server run in a docker container (image headscale/headscale:0.22.3).

I enter my headscale URL  in the "use alternate server" option and then nothing happens.

When I checked the logs of my docker container, see this each time I press login in the tailscale app:
> 2024-09-13T20:02:02Z INF go/src/headscale/hscontrol/protocol_common.go:574 > Successfully sent auth url AuthURL=http://headscale.domain.name:portnumber/register/nodekey:6f93231a259a0f8952db651a3359b332f9d1868a36 machine=localhost noise=true

I I manualy enter the URL in my favorite browser, I get this response:
> Client sent an HTTP request to an HTTPS server.

Now I change the url from HTTP to HTTPS and I now get the response with the informations to connect

So I think that the problem is not the tailscale app but the headscale server that is sending http URl instead of https.

As i'm currently using the latest stable headscale version (0.22.3), this behaviour may have been changed in the more recents version of headscale. 

Even with doing the instruction from the HTTPS url, I can't make it work so I found another way than using the login button:
1) in the account setting -> the three dots in the upper right of the screen -> "Use alternate server" and enter your headscale URL server
2) generate an authkey with `headscale preauthkeys create --user myfirstuser --reusable --expiration 24h`
3) in the account setting -> the three dots in the upper right of the screen -> "use auth key"
4) enter the authkey and click "add account"
5) enjoy your headscale network !

PS: url, port, nodekey have been anonymised

**Comment by GJCav** [comment] 2024-09-15 02:57
https://github.com/tailscale/tailscale/issues/11716#issuecomment-2350121454 Great!! I think you found the correct answer.

**Comment by arcoast** [comment] 2024-09-15 19:01
@Pierre-Brocas @GJCav 

If it's any help to you guys I'm running headscale behind a traefik reverse proxy on https and I'm using the `0.23.0-beta.5` and using OIDC to auth.

**Comment by agottardo** [comment] 2024-09-15 20:01
Please refrain from restarting a conversation on older, closed issues when the root cause is different from the original. It’s best to create a new issue to ensure the problem is properly tracked and addressed without causing confusion. You may use the [Headscale issue tracker](https://github.com/juanfont/headscale/issues) for Headscale-specific matters.
