### ISSUE TITLE
Tailscale eats up my mobile network traffic, even when connected to WIFI. 

### ISSUE THREAD

**Issue by vvzvlad** [tailscale/tailscale#4967] opened 2022-06-29 12:31 UTC
### What is the issue?

I noticed the rapid end of my plan and reset the statistics to see who wastes the traffic. It turned out a strange thing: in the time from the reset of statistics (25th) to the current time (29th), i.e. 4 days, it was spent more than 7 GB of data.  Of which 100-200 MB was spent for syncing photos, zooming, streaming music, and 6.7(!!) GB was spent exclusively by Tailscale. 
I use output node, but there is no way I could spend that much traffic: my average consumption per month is about 5-10 GB for many months, and exceeded only when I connect my laptop via hotspot. But all those 4 days I didn't have my laptop connected, I didn't watch YouTube videos all day long, and so on. How did the Tailscale service waste 6.7 GB

I can't use Tailscale because my mobile traffic is finite and it just runs out after a few days. I am considering migrating our corporate network(≈300 people) to Tailscale, but with this problem this plan is just not feasible. 

![IMG_1091 Medium](https://user-images.githubusercontent.com/3315944/176437058-dd0281c8-5b62-498b-b8b1-9af533ed6980.jpeg)
![IMG_1092 Medium](https://user-images.githubusercontent.com/3315944/176437070-c5c47693-8023-43f3-9520-b755298a75f9.jpeg)

### OS

iOS

### OS version

15.5

### Tailscale version

1.26.1

### Bug report

BUG-ec31593678be05f04288445b58011106352d720daddff6b55295781a12fc084a-20220629085711Z-234b7e76da7df4b4

**Comment by DentonGentry** [comment] 2022-07-05 04:13
Duplicate of https://github.com/tailscale/tailscale/issues/4640

This may be a case of binding to the wrong interface, continuing to use the LTE after Wi-Fi is available. We've only been able to produce the problem a couple times, not reliably enough to debug how it gets into the state where it does this.

**Closed by DentonGentry** 2022-07-05 04:13 UTC
Labels: OS-ios, L2 Few, P2 Aggravating, T3 Performance/Debugging, bug
