### ISSUE TITLE
HTTPS DERP latency checks don't work correctly with proxy that does ssl mitm

### ISSUE THREAD

**Issue by normanr** [tailscale/tailscale#4377] opened 2022-04-07 22:50 UTC
### What is the issue?

I'm running a client in a restricted network, but `tailscale netcheck` shows latencies for all DERP nodes (even though the restrictive proxy denied the connection request for most (but not all) of them).

If I use a non-mitm port on the proxy (which looks at the CONNECT hostname), then only the DERP hosts that are allowed return latency information. If I use a mitm port on the proxy (which accepts the CONNECT request, starts TLS, and looks at the http headers, and then returns a 503), then latencies are shown for _all_ hosts. Also looking at the proxy logs, _all_ of the requests fail because the `Host` header is set to `derp-unused-hostname.tld`.

I think two fixes would help:
- Use `node.Hostname` to construct the url in `measureHTTPSLatency` https://github.com/tailscale/tailscale/blob/858ab8017253a870a35a72676a9c83cf5fdf2bac/net/netcheck/netcheck.go#L1039 similar to how it's used in `runHTTPOnlyChecks` https://github.com/tailscale/tailscale/blob/858ab8017253a870a35a72676a9c83cf5fdf2bac/net/netcheck/netcheck.go#L978
- Return an error if `resp.StatusCode > 299`

### Steps to reproduce

Force tailscale to connect through an https_proxy that does mitm (eg: squid with ssl_bump).

example config snippet for squid:
```
http_port 3129 ssl-bump \
  generate-host-certificates=on \
  tls-cert=/etc/squid/certs/squid-ca-cert-key.pem \
  tls-cafile=/etc/squid/certs/cacert.pem \
  options=NO_SSLv3,NO_TLSv1,NO_TLSv1_1
tls_outgoing_options min-version=1.2
ssl_bump stare all      # mimic the Client Hello, drop unsupported extensions
ssl_bump bump all       # terminate and establish new TLS connection
```

Then setup acls so that only some derp servers are allowed.

### OS

Linux

### OS version

Debian testing (proxy) and Raspberry Pi (client)

### Tailscale version

1.22.2

**Comment by normanr** [comment] 2022-04-07 23:24
also when starting tailscaled it seems to pick a derp server at random, and keeps trying that single server, and never trying any other ones.

**Comment by twitchyliquid64** [comment] 2022-04-11 22:02
Can you share a little more about your setup? in particular, how are you informing tailscale about the proxy and how are you preventing traffic from hitting the WAN except through the proxy?

I'll also note that (unlike most CLI commands) `tailscale netcheck` does not delegate to `tailscaled` over the daemon socket - it does all the check itself. As such, if you are not passing the right environment variables to tailscale as well, it will go around your proxy (hence you will see the full list of regions in the netcheck report).

I am not able to reproduce failures with a squid mitm, even with `host_verify_strict on`. I presume we arent hitting the `measureHTTPSLatency` codepath in that case.

**Comment by normanr** [comment] 2022-04-12 19:30
> how are you informing tailscale about the proxy

I have `http_proxy="http://192.168.1.11:3129/"` in `/etc/environment` (for interactive ssh) and `/etc/default/tailscaled` (for systemd tailscale.service)

> how are you preventing traffic from hitting the WAN except through the proxy?

The router to the internet has an iptables rule to reject traffic from the clients IP address. It's a Mikrotik running RouterOS and the client is configured in [Kid Control](https://wiki.mikrotik.com/wiki/Manual:Kid-control), but the effective iptables entry is `-D forward -s 192.168.1.44 -t REJECT --reject-with icmp-net-unreachable` (because linux is the underlying kernel, and there's a clear 1:1 mapping from the [firewall config](https://help.mikrotik.com/docs/display/ROS/Filter) UI to iptables)

> I'll also note that (unlike most CLI commands) tailscale netcheck does not delegate to tailscaled over the daemon socket - it does all the check itself. As such, if you are not passing the right environment variables to tailscale as well, it will go around your proxy (hence you will see the full list of regions in the netcheck report).

ack. If I don't set the environment variable then there are no derp responses (because the firewall rejects the requests).

```
$ tailscale netcheck 
Report:
	* UDP: false
	* IPv4: (no addr found)
	* IPv6: no
	* MappingVariesByDestIP: 
	* HairPinning: 
	* PortMapping: 
	* Nearest DERP: unknown (no response to latency probes)
```

via squid's non-mitm proxy port (only derp2 and derp2b are allowed):
```
$ https_proxy=http://192.168.1.11:3128 tailscale netcheck 

Report:
	* UDP: false
	* IPv4: (no addr found)
	* IPv6: no
	* MappingVariesByDestIP: 
	* HairPinning: 
	* PortMapping: 
	* Nearest DERP: San Francisco
	* DERP latency:
		- sfo: 25.7ms  (San Francisco)
		- nyc:         (New York City)
		- sin:         (Singapore)
		- fra:         (Frankfurt)
		- syd:         (Sydney)
		- blr:         (Bangalore)
		- tok:         (Tokyo)
		- lhr:         (London)
		- dfw:         (Dallas)
		- sea:         (Seattle)
		- sao:         (São Paulo)
		- ord:         (Chicago)
```

squid logs (fields are `remotehost code/status bytes method URL rfc931 peerstatus/peerhost type`):
```
192.168.1.44 NONE_NONE/500 0 CONNECT http:443 - HIER_NONE/- -
(19 lines of the same NONE_NONE/500, 21 in total, 22 lines in total)
192.168.1.44 NONE_NONE/500 0 CONNECT http:443 - HIER_NONE/- -
192.168.1.44 TCP_TUNNEL/200 5100 CONNECT derp2.tailscale.com:443 - HIER_DIRECT/167.172.206.31
```

via squid's mitm proxy port:
```
$ https_proxy=http://192.168.1.11:3129 tailscale netcheck 

Report:
	* UDP: false
	* IPv4: (no addr found)
	* IPv6: no
	* MappingVariesByDestIP: 
	* HairPinning: 
	* PortMapping: 
	* Nearest DERP: Bangalore
	* DERP latency:
		- blr: 34ms    (Bangalore)
		- sin: 83.2ms  (Singapore)
		- nyc: 142.5ms (New York City)
		- tok: 153.7ms (Tokyo)
		- dfw: 157.7ms (Dallas)
		- sea: 185.9ms (Seattle)
		- ord: 187.2ms (Chicago)
		- sfo: 202.5ms (San Francisco)
		- syd: 212.9ms (Sydney)
		- fra: 275ms   (Frankfurt)
		- sao: 313.3ms (São Paulo)
		- lhr: 403.5ms (London)
```

squid logs:
```
192.168.1.44 NONE_NONE/200 0 CONNECT derp10.tailscale.com:443 - HIER_DIRECT/137.220.36.168 -
192.168.1.44 NONE_NONE/503 4427 GET https://derp-unused-hostname.tld/derp/latency-check - HIER_DIRECT/137.220.36.168 text/html
192.168.1.44 NONE_NONE/200 0 CONNECT derp10.tailscale.com:443 - HIER_DIRECT/2001:19f0:8001:2d9:540
0:2ff:feef:bbb1 -
192.168.1.44 NONE_NONE/503 4450 GET https://derp-unused-hostname.tld/derp/latency-check - HIER_DIR
ECT/2001:19f0:8001:2d9:5400:2ff:feef:bbb1 text/html
192.168.1.44 NONE_NONE/200 0 CONNECT derp2.tailscale.com:443 - HIER_DIRECT/167.172.206.31
192.168.1.44 NONE_NONE/503 4426 GET https://derp-unused-hostname.tld/derp/latency-check - HIER_DIR
ECT/167.172.206.31 text/html
(and repeated for another 9 derp nodes, 12 in total)
```

Note that tailscaled creates the following squid entries:
For denied (request is redirected to squidGuard failure page):
```
192.168.1.44 NONE_NONE/200 0 CONNECT derp12c.tailscale.com:443 - HIER_DIRECT/149.28.119.105 -
192.168.1.44 TCP_MISS/503 4596 GET http://router/cgi-bin/squidGuard.cgi? - HIER_NONE/- text/html
```

For allowed (if I allow all derp hosts):
```
192.168.1.44 NONE_NONE/200 0 CONNECT derp12c.tailscale.com:443 - HIER_DIRECT/149.28.119.105 -
[... when I down tailscaled on the client ...]
192.168.1.44 TCP_TUNNEL/101 103 GET https://derp12c.tailscale.com/derp - HIER_DIRECT/149.28.119.105 -
```

> I am not able to reproduce failures with a squid mitm, even with host_verify_strict on. I presume we arent hitting the measureHTTPSLatency codepath in that case.

I don't have `host_verify_strict on` in my configs. I did add the public key from squid's `tls-cert` to /etc/ssl/certs (and created the hash symlink) on the client. I'm not sure if tailscale required that, but curl required it (or the `--insecure` flag to be passed).

Ahh, it looks like "setup acls so that only some derp servers are allowed" was where I need to provide more details:

I have the default `http_port 3128`, and ssl-bump on port 3129 (config as in opening comment), and I have squid configured to use squidGuard like this:
```
url_rewrite_program /usr/bin/squidGuard
# Don't rewrite CONNECT requests on the ssl_bump port,
# squid gets confused about the redirect.
acl ssl_bump_ports localport 3129
url_rewrite_access deny CONNECT ssl_bump_ports
```
(basically don't try and rewrite CONNECT requests (which set up the TLS connection), but only the sub-requests that are bumped, this could probably be done in a better way, but it's what works for me)

It [looks like](http://lists.squid-cache.org/pipermail/squid-users/2016-January/008638.html) squidGuard only looks at the `Host` header, because it doesn't get the TLS SNI via `url_rewrite_extras`. So I'm guessing you could probably reproduce it by using a `req_header Host` acl (but I have not confirmed, but would be easier than configuring squidGuard).

**Comment by twitchyliquid64** [comment] 2022-04-15 17:27
Thank you for the detailed configuration information - looks like the issue is fairly-well contained to rewriting of the connection parameters. As you suggested, it seems this can be addressed by diligently setting the correct Host in all our HTTP requests, even when we don't expect it to matter.

I'll go ahead and poke around for where we do this and submit some fixes. `netcheck` aside, I think most of the codebase has the correct behavior.

**Comment by DentonGentry** [comment] 2022-08-28 01:51
https://github.com/tailscale/tailscale/pull/4452 went into Tailscale 1.28. I'm going to optimistically say the issue is fixed, please reopen if it still fails in your environment.

**Closed by DentonGentry** 2022-08-28 01:51 UTC
Labels: L1 Very few, P3 Can't get started, T5 Usability, bug
