### ISSUE TITLE
Setting a DNS server in the admin panel makes macOS unable to resolve any DNS

### ISSUE THREAD

**Issue by myyra** [tailscale/tailscale#1723] opened 2021-04-17 14:32 UTC
**Describe the bug**
When setting a DNS server in the admin console, all DNS stops working on macOS. Even happens in real time when connected to Tailscale and setting the server. Happens with public and private DNS servers.

**To Reproduce**
(optionally: while connected to Tailscale:)
1. Go to admin console
2. Set any DNS server
3. All DNS queries will fail, connecting to IPs directly works

**Expected behavior**
System will resolve DNS with the provided config.

**Version information:**
 - Device: M1 MacBook Pro
 - OS: macOS
 - OS version: 11.2.3
 - Tailscale version: 1.6.0

**Additional context**
- `scutil --dns` shows everything is correct and exactly as configured in the admin console.
- Little Snitch shows `mDNSResponded` connecting to the set DNS server
- Problem persists even when disabling Little Snitch
- When using WireGuard, setting the DNS works fine
- No exit nodes enabled

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_32841)

**Comment by DentonGentry** [comment] 2021-04-17 14:41
Do you have an exit node enabled? This might be relevant: https://github.com/tailscale/tailscale/issues/1647

At this point we're expecting to fix https://github.com/tailscale/tailscale/issues/1647 in the 1.8 release, the changes required in DNS to make this case work better were extensive.

**Comment by myyra** [comment] 2021-04-17 14:41
@DentonGentry no exit nodes enabled

**Comment by tanuck** [comment] 2021-04-22 15:20
I've been speaking with Tailscale support over the past day and I think my issue was the same as this. I've since reproduced this today.

Reproduction was the same as OP. To further assist in tracking down the issue, we have narrowed it down to clients running on MacOS 11 only. Confirmed that members of the team running MacOS 10.14 & 10.15 don't experience this issue.

I'd also add that I was slightly misled by the docs around Nameservers and MagicDNS. I didn't realise that setting nameservers for my Tailscale network was a feature in its own right. I thought the Nameservers were merely a dependency for MagicDNS, and setting them wouldn't have an affect on my network while MagicDNS was disabled.

**Comment by tanuck** [comment] 2021-04-22 18:41
Just to clarify:

- MagicDNS was disabled
- No exit nodes
- Subnet relays present
- Our reproduction was exactly the same as OP. Add any entry to Nameservers, then all DNS queries hang on MacOS 11 clients.

**Version information**:
- Device: Various (M1 macs, Macbook pros, macbook air, mac mini)
- OS: MacOS
- OS version: 11.x
- Tailscale version: 1.4.5 & 1.6.0

**Comment by guidoiaquinti** [comment] 2021-05-14 09:30
I can confirm the same issue on:

- OS: MacOS
- OS version: 11.x
- Tailscale version: 1.8.1
- Tailscale setup: no exit nodes enabled

**Comment by DentonGentry** [comment] 2021-05-20 14:26
There is a fix coming for a MacOS MatchDomains vs SplitDomains issue in 1.8.4, which I think we'll be building today. Once built it goes to Apple for review, so I'm not exactly sure when the update will appear.

We're hoping this will resolve the issues reported here.

**Comment by fforootd** [comment] 2021-05-26 18:38
I saw this exact issues also with 1.8.5 on MacOS 11.4

Should this be fixed in that release or a later one?

**Comment by DentonGentry** [comment] 2021-05-26 21:13
Unfortunately we expected this to be resolved with the fix that went in to 1.8.5. If you send the email address of the account you use with Tailscale to support@tailscale.com, we can try to figure out what is happening.

**Comment by fforootd** [comment] 2021-05-26 21:24
Nice to hear this.

I sent you a mail with some context of what we are trying to achieve as well 😎

**Comment by DentonGentry** [comment] 2021-06-26 07:35
I think these symptoms are likely resolved by a combination of the search domain fixes delivered in 1.8.7 and https://github.com/tailscale/tailscale/pull/2226 delivered in the MacOS 1.10.0 release.

I'm going to close this, please feel free to reopen if symptoms remain after installing 1.10.0.

**Closed by DentonGentry** 2021-06-26 07:35 UTC
Labels: L3 Some users, OS-macos, P3 Can't get started, T5 Usability
