### ISSUE TITLE
Please Restart the windows Tailscale service

### ISSUE THREAD

**Issue by Cgende** [tailscale/tailscale#5544] opened 2022-09-05 00:14 UTC
### What is the issue?

After a restart of my pc, when I start Tailscale i get the message that tells me to restart the tailscale windows service. Doing this does not fix the issue. Some people have claimed that deleting C:\Users\user\AppData\Local\Tailscale fixes this. When I do this, I see the log in button but it does nothing. After waiting more than 5 minutes, the login page normally opens in my browser but after logging in the desktop app does not update.  

### Steps to reproduce

Restart PC
Launch Tailscale

### Are there any recent changes that introduced the issue?

None

### OS

Windows 10 Education 

### OS version

10.0.19044 Build 19044

### Tailscale version

1.30.0

### Bug report

BUG-40c4ae30bfae514f8456cf7eae52866389a9fb29ad43719116cc482567501847-20220905001425Z-9ed5ab96c90d9cbb

**Comment by JFX3d** [comment] 2022-09-12 09:11
having this same issue since update cant connect via my laptop to my servers which i can see online :(

**Comment by JFX3d** [comment] 2022-09-12 09:43
managed to fix myself , stopped service and App deleted the files in \AppData\Local\Tailscale under my user, connected to my 5G hotspot in case the ISP was blocking some think in the update,  login opens and sign in fine , reconnect to my min ISP and now fully working , Very odd as this was fine when updated to the 13.0 update the other day

**Comment by DentonGentry** [comment] 2022-10-05 01:02
Duplicate of https://github.com/tailscale/tailscale/issues/5531

**Closed by DentonGentry** 2022-10-05 01:02 UTC
Labels: needs-triage, bug
