### ISSUE TITLE
FR: support load balanced Tailscale exit nodes

### ISSUE THREAD

**Issue by hatahet** [tailscale/tailscale#5214] opened 2022-07-28 20:20 UTC
### What are you trying to do?

I'm trying to have a reliable exit node setup, whereby a client is able to connect to a set of load balanced exit nodes, exposed as a single IP address or DNS record. This way, if an exit node goes down, or has too heavy of a load, the client is seamlessly routed to another one in the same set.

### How should we solve this?

One way is to have a Tailscale node run in a load balancing mode, and seamlessly forward traffic to other exit nodes on the network. The clients that connect should only be aware of the IP address of the load balancing node when they connect.

### What is the impact of not solving this?

I would have to investigate how to do a manual setup, if it's possible to host my own public load balancer, which would route traffic to a set of exit nodes. I don't know if I'd be able to have the Tailscale client connect directly to the load balancer.

**Comment by DentonGentry** [comment] 2022-07-29 03:05
Duplicate of https://github.com/tailscale/tailscale/issues/2598

**Closed by DentonGentry** 2022-07-29 03:05 UTC
Labels: needs-triage, fr
