### ISSUE TITLE
FR: Openwrt and Alpine offical support

### ISSUE THREAD

**Issue by xrain0610** [tailscale/tailscale#7916] opened 2023-04-18 20:37 UTC
### What are you trying to do?

this is only third-party package found,but it not always the latest version.

**Comment by DentonGentry** [comment] 2023-04-18 20:55
OpenWRT support is tracked in https://github.com/tailscale/tailscale/issues/6252

Alpine maintains its own package, and keeps it reasonably up to date:
https://pkgs.alpinelinux.org/package/edge/community/x86/tailscale

**Comment by DentonGentry** [comment] 2023-04-19 01:33
Duplicate of https://github.com/tailscale/tailscale/issues/6252

**Closed by DentonGentry** 2023-04-19 01:33 UTC
Labels: OS-linux, L3 Some users, P2 Aggravating, T0 New feature, fr
