### ISSUE TITLE
FR: Internationalization support

### ISSUE THREAD

**Issue by chenxudong2020** [tailscale/tailscale#7856] opened 2023-04-13 04:09 UTC
### What is the issue?

Taiscale lacks internationalization support, including web backend and client. Currently, priority can be given to adding Chinese support, which is automatically displayed based on the language set by the user's browser and system language

### OS

Windows

**Comment by DentonGentry** [comment] 2023-04-13 09:32
Duplicate of https://github.com/tailscale/tailscale/issues/7771
(which focusses on Chinese language support specifically but is nonetheless an i18n feature request)

**Closed by DentonGentry** 2023-04-13 09:32 UTC
Labels: L3 Some users, P2 Aggravating, T0 New feature, fr
