### ISSUE TITLE
New netfilter conntrack state checks are too broad

### ISSUE THREAD

**Issue by protohuf** [tailscale/tailscale#12067] opened 2024-05-09 06:57 UTC
### What is the issue?

In version 1.66.0 it seems the following conntrack rule were added to tailscale:

```
	chain ts-forward { # handle 66
		iifname "tailscale0*" counter packets 0 bytes 0 meta mark set meta mark & 0xffff04ff | 0x00000400 # handle 73
		meta mark & 0x0000ff00 == 0x00000400 counter packets 0 bytes 0 accept # handle 74
		oifname "tailscale0*" ip saddr 100.64.0.0/10 counter packets 0 bytes 0 drop # handle 75
		oifname != "tailscale0*" ct state invalid,new,0x10,0x20,0x80,0x100,0x200,0x400,0x800,0x1000,0x2000,0x4000,0x8000,0x10000,0x20000,0x40000,0x80000,0x100000,0x200000,0x400000,0x800000,0x1000000,0x2000000,0x4000000,0x8000000,0x10000000,0x20000000,0x40000000,0x80000000 counter packets 685 bytes 44467 drop # handle 79
		oifname "tailscale0*" counter packets 0 bytes 0 accept # handle 76
	}
```

The offending handle is #79. It catches all NAT'ed traffic going from my subnets to the internet.

In my case; tailscale is installed on my firewall/router. The firewall is responsible for forwarding traffic between NAT'ed devices on local networks to the internet as well as traffic between networks. This new conntrack filter completely drops almost all traffic going through the forward chain.

### Steps to reproduce

Install tailscale on a device sitting between 2 subnets. Have the device forward traffic between the subnets. I didn't have time to test but in my case the traffic was masqueraded between all my networks, so it could be a requirement. You should now be able to see how most forward traffic get's caught in this rule in chain ts-forward:

`oifname != "tailscale0*" ct state invalid,new,0x10,0x20,0x80,0x100,0x200,0x400,0x800,0x1000,0x2000,0x4000,0x8000,0x10000,0x20000,0x40000,0x80000,0x100000,0x200000,0x400000,0x800000,0x1000000,0x2000000,0x4000000,0x8000000,0x10000000,0x20000000,0x40000000,0x80000000 counter packets 685 bytes 44467 drop # handle 79
`

### Are there any recent changes that introduced the issue?

The rule in ts-forward:

`oifname != "tailscale0*" ct state invalid,new,0x10,0x20,0x80,0x100,0x200,0x400,0x800,0x1000,0x2000,0x4000,0x8000,0x10000,0x20000,0x40000,0x80000,0x100000,0x200000,0x400000,0x800000,0x1000000,0x2000000,0x4000000,0x8000000,0x10000000,0x20000000,0x40000000,0x80000000 counter packets 685 bytes 44467 drop # handle 79
`

### OS

Linux

### OS version

Debian 11

### Tailscale version

1.66.0

### Other software

netfilter

**Comment by icio** [comment] 2024-05-09 08:27
Hi @protohuf, can you please share some more details about the network flow that's being disrupted here? Are these LAN devices unable to connect to the public internet through the router, e.g. a PC on 192.168.1.7 connecting to the router via eth0 cannot reach 1.1.1.1? Do these LAN devices have Tailscale installed, or is Tailscale only installed on the router?

1.66 included a change related to security-bulletin https://tailscale.com/security-bulletins#ts-2024-005 which might be affecting your setup:

[Site-to-site networking](https://tailscale.com/kb/1214/site-to-site) now also requires --stateful-filtering=false in addition to --snat-subnet-routes=false on new subnet routers. Existing subnet routers with --snat-subnet-routes=false will default to --stateful-filtering=false.
— https://tailscale.com/changelog#2024-05-08-client

I wonder whether your router is running with --snat-subnet-routes=true and what happens if you set --stateful-filtering=false?

If you can also grab a `tailscale bugreport` bug ID that will help us look at your setup.

Thanks

**Comment by fritterhoff** [comment] 2024-05-09 08:43
I've just updated 2 of my systems that where running as a subnet router and a normal firewall. Seems like the update broke some functionality affecting the normal tailscale access in combination with `nft`. Right now I am not sure where the root cause is but a downgrade to 1.64 fixes the access.

**Comment by knyar** [comment] 2024-05-09 09:42
Thank you for the report! This is a regression introduced in 1.66 as part of stateful packet filtering aimed to migitate the [TS-2024-005](https://tailscale.com/security-bulletins#ts-2024-005) issue.

I think this only impacts packet-forwarding nodes (exit nodes, subnet routers) running on Linux with nftables [firewall mode](https://tailscale.com/kb/1294/firewall-mode).

We expect to build a stable release with a fix shortly. As a workaround for systems that support `iptables` CLI, you can install `iptables` and run `tailscaled` with `TS_DEBUG_FIREWALL_MODE` environment variable set to `iptables`.

We are tracking this in #12066, so I will close this issue as a duplicate.

**Closed by knyar** 2024-05-09 09:42 UTC
Labels: needs-triage, bug

**Comment by protohuf** [comment] 2024-05-09 10:09
> Hi @protohuf, can you please share some more details about the network flow that's being disrupted here? Are these LAN devices unable to connect to the public internet through the router, e.g. a PC on 192.168.1.7 connecting to the router via eth0 cannot reach 1.1.1.1? Do these LAN devices have Tailscale installed, or is Tailscale only installed on the router?
> 
> 1.66 included a change related to security-bulletin https://tailscale.com/security-bulletins#ts-2024-005 which might be affecting your setup:
> 
> [Site-to-site networking](https://tailscale.com/kb/1214/site-to-site) now also requires --stateful-filtering=false in addition to --snat-subnet-routes=false on new subnet routers. Existing subnet routers with --snat-subnet-routes=false will default to --stateful-filtering=false. — https://tailscale.com/changelog#2024-05-08-client
> 
> I wonder whether your router is running with --snat-subnet-routes=true and what happens if you set --stateful-filtering=false?
> 
> If you can also grab a `tailscale bugreport` bug ID that will help us look at your setup.
> 
> Thanks

@icio  Hi! Here are some more details and more investigation from my side to pinpoint the problem:

Mr router/firewall is using Debian 12 with nftables. It has several local/private subnets and one WAN connection directly to the Internet via my ISP. When the tailscaled daemon is started and the tailscale specific firewall rules are appended to mine, devices behind any local/private subnet can not access Internet. Note: None of the local devices are routing via tailnet in anyway. tailscale is installed on the router purely for administrative purposes.

I have harrowed down the problem to the following line in the ts-filter chain (appended to the forward hook table:

```
oifname != "tailscale0*" ct state invalid,new,0x10,0x20,0x80,0x100,0x200,0x400,0x800,0x1000,0x2000,0x4000,0x8000,0x10000,0x200
00,0x40000,0x80000,0x100000,0x200000,0x400000,0x800000,0x1000000,0x2000000,0x4000000,0x8000000,0x10000000,0x20000000,0x40000000,0x80000000 counter packets 54 bytes 3417 drop # handle 81

```

This line traps all traffic intended from LAN to WAN (via POSTROUTING masquerade rule)

Here's my troubleshooting I did:

- Router/firewall is working as it should, tailscaled is off
- Turn on the tailscaled daemon:

`systemctl start tailscaled.service`

- list the ts-forward chain which is hooked in the forward table

```
chain ts-forward { # handle 68
        iifname "tailscale0*" counter packets 0 bytes 0 meta mark set meta mark & 0xffff04ff | 0x00000400 # handle 75
        meta mark & 0x0000ff00 == 0x00000400 counter packets 0 bytes 0 accept # handle 76
        oifname "tailscale0*" ip saddr 100.64.0.0/10 counter packets 0 bytes 0 drop # handle 77
        oifname != "tailscale0*" ct state invalid,new,0x10,0x20,0x80,0x100,0x200,0x400,0x800,0x1000,0x2000,0x4000,0x8000,0x10000,0x200
00,0x40000,0x80000,0x100000,0x200000,0x400000,0x800000,0x1000000,0x2000000,0x4000000,0x8000000,0x10000000,0x20000000,0x40000000,0x80000000 counter packets 54 bytes 3417 drop # handle 81
        oifname "tailscale0*" counter packets 0 bytes 0 accept # handle 78
}
```

- Add 2 specific rules to a google web server for testing. Note: I'm adding the same counter before (handle 81) and after (handle 78) the suspect rule (handle 81):


```
nft insert rule ip filter ts-forward position 81 ip daddr 216.58.211.14 counter
nft insert rule ip filter ts-forward position 78 ip daddr 216.58.211.14 counter

```

- This is the chain after modification:

```
chain ts-forward { # handle 68
        iifname "tailscale0*" counter packets 0 bytes 0 meta mark set meta mark & 0xffff04ff | 0x00000400 # handle 75
        meta mark & 0x0000ff00 == 0x00000400 counter packets 0 bytes 0 accept # handle 76
        oifname "tailscale0*" ip saddr 100.64.0.0/10 counter packets 0 bytes 0 drop # handle 77
        ip daddr 216.58.211.14 counter packets 0 bytes 0 # handle 82
        oifname != "tailscale0*" ct state invalid,new,0x10,0x20,0x80,0x100,0x200,0x400,0x800,0x1000,0x2000,0x4000,0x8000,0x10000,0x20000,0x40000,0x80000,0x100000,0x200000,0x400000,0x800000,0x1000000,0x2000000,0x4000000,0x8000000,0x10000000,0x20000000,0x40000000,0x80000000 counter packets 1038 bytes 70220 drop # handle 81
        ip daddr 216.58.211.14 counter packets 0 bytes 0 # handle 83
        oifname "tailscale0*" counter packets 0 bytes 0 accept # handle 78
}
```

- Try accessing the google server from a device on a subnet (which worked before the  tailscaled daemon started)

```
curl -v https://216.58.211.14
*   Trying 216.58.211.14:443...
```

- Check  the counters of the traps before/after handle 81

```
chain ts-forward { # handle 68
        iifname "tailscale0*" counter packets 0 bytes 0 meta mark set meta mark & 0xffff04ff | 0x00000400 # handle 75
        meta mark & 0x0000ff00 == 0x00000400 counter packets 0 bytes 0 accept # handle 76
        oifname "tailscale0*" ip saddr 100.64.0.0/10 counter packets 0 bytes 0 drop # handle 77
        ip daddr 216.58.211.14 counter packets 6 bytes 360 # handle 82
        oifname != "tailscale0*" ct state invalid,new,0x10,0x20,0x80,0x100,0x200,0x400,0x800,0x1000,0x2000,0x4000,0x8000,0x10000,0x20000,0x40000,0x80000,0x100000,0x200000,0x400000,0x800000,0x1000000,0x2000000,0x4000000,0x8000000,0x10000000,0x20000000,0x40000000,0x80000000 counter packets 1258 bytes 84213 drop # handle 81
        ip daddr 216.58.211.14 counter packets 0 bytes 0 # handle 83
        oifname "tailscale0*" counter packets 0 bytes 0 accept # handle 78
}
```

- Notice how handle 82 has 6 packets in its counter and handle 83 has zero packets.

I think it's safe to assume that traffic does get caught in handle 81. Note: I have not looked into the details of this rule as I'm low on time at the moment
