### ISSUE TITLE
Android & mobile carriers using CGNAT

### ISSUE THREAD

**Issue by garritfra** [tailscale/tailscale#4827] opened 2022-06-09 08:38 UTC
### What is the issue?

When I loose connection to my home wifi network while being connected to Tailscale, my android device isn't able to send and receive any data.

Please do let me know if this is a duplicate issue. I didn't find a ticket matching this description, but it might be that I'm missing some knowledge about the protocols in use.

### Steps to reproduce

1. Connect to home wifi
2. Enable Tailscale connection through Tailscale app
3. Leave wifi range, which causes a switch to mobile network

### Expected

I am able to access internet services.

### Actual

Connection is not possible.

### OS

Android

### OS version

Oxygen OS 11.10.10.AC01BA

### Tailscale version

1.24.2

### Bug report

BUG-33fc3daa0c3b386e34dcb8fc990e9e67edaf62d25120a7bea13719434f44759f-20220609083705Z-5bd6f838990ed3cd

**Comment by DentonGentry** [comment] 2022-06-10 03:39
Shortly before the BUG line:
`2022-06-09 08:33:31.25621467 +0000 UTC: 23.0M/186.1M LinkChange: major, rebinding. New state: interfaces.State{defaultRoute= ifs={rmnet_data2:[100.95.x.y/29] rmnet_data3:[2a00:20:70c3:d7ce:q:r:s:t/64] tun0:[100.87.143.114/32 fd7a:115c:a1e0:ab12:4843:cd96:6257:8f72/128] wlan0:[192.168.178.37/24]} v4=true v6=true}`

The mobile carrier uses CGNAT addresses which conflict with the Tailscale use of the range.

One possible way to work around this is to disable the use of IPv4 addresses on your tailnet (the whole tailnet), and rely on IPv6. This can be done in https://login.tailscale.com/admin/acls:
```
{
  "disableIPv4": false,
  "acls": [ { "action": "accept", "src": ["*"], "dst": ["*:*"], },
}
```

**Comment by DentonGentry** [comment] 2022-06-11 03:15
Underlying issue is a duplicate of https://github.com/tailscale/tailscale/issues/1381

**Closed by DentonGentry** 2022-06-11 03:15 UTC
Labels: connectivity, OS-android, L2 Few, P2 Aggravating, T5 Usability, bug

**Comment by garritfra** [comment] 2022-06-11 08:32
Thanks for the quick response and the workaround!
