### ISSUE TITLE
FreeBSD not negotiating portmap

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#4101] opened 2022-03-08 18:31 UTC
### What is the issue?

FreeBSD machines are not triggering the portmapper negotiation code. 

no portmapper lines in logs, no NAT-PMP or uPnP connections established. 

### Steps to reproduce

Install from BSD ports

### OS

Other

### OS version

FreeBSD 13.0

### Tailscale version

1.22.0

### Bug report

BUG-452a7aabOb4f321fbccb7816e93a2b4308bf486d0aa0ecd7947ece4ff4e0e7d7-202203081823462-e77b94be6cdadef8

**Comment by bradfitz** [comment] 2022-03-08 18:37
That bugreport is malformed. There's an `O` in there?

**Comment by JayWStapleton** [comment] 2022-03-08 18:50
@bradfitz - 12b5b0ae692b05f75d0f6e7fcbcbe294649093a3abe74534413c820a5b444981 is the logid

**Comment by bradfitz** [comment] 2022-03-08 18:59
Why does it not match the bug report's logid then? How did that BUG line get a non-hex character in it?

**Comment by JayWStapleton** [comment] 2022-03-08 19:02
transposition error. Also, ran it on the wrong window. 

That logid is from the BSD machine I reproduced the error on.

**Comment by bradfitz** [comment] 2022-03-08 19:05
What's `tailscaled debug --portmap` say?

Which port mapping services do you expect to see? You're sure that VLAN has them available?

**Comment by JayWStapleton** [comment] 2022-03-08 19:09
<img width="822" alt="image" src="https://user-images.githubusercontent.com/95231559/157307789-c58e8bbe-8fe0-4a70-a857-f8f2d3425dcc.png">

Yes. It's a VM on my workstation, a Debian VM on the same hypervisor returns UPnP addresses with that `tailscaled debug --portmap`

**Comment by bradfitz** [comment] 2022-03-08 19:19
ah. the issue is the "no gateway or self IP".  We never implemented that for FreeBSD.

```
$ git grep likelyHomeRouterIP
net/interfaces/interfaces.go:var likelyHomeRouterIP func() (netaddr.IP, bool)
net/interfaces/interfaces.go:   if likelyHomeRouterIP != nil {
net/interfaces/interfaces.go:           gateway, ok = likelyHomeRouterIP()
net/interfaces/interfaces_darwin.go:    likelyHomeRouterIP = likelyHomeRouterIPDarwinFetchRIB
net/interfaces/interfaces_darwin.go:func likelyHomeRouterIPDarwinFetchRIB() (ret netaddr.IP, ok bool) {
net/interfaces/interfaces_darwin_test.go:       syscallIP, syscallOK := likelyHomeRouterIPDarwinFetchRIB()
net/interfaces/interfaces_darwin_test.go:       netstatIP, netstatOK := likelyHomeRouterIPDarwinExec()
net/interfaces/interfaces_darwin_test.go:func likelyHomeRouterIPDarwinExec() (ret netaddr.IP, ok bool) {
net/interfaces/interfaces_darwin_test.go:               // This is why we have likelyHomeRouterIPDarwinSyscall.
net/interfaces/interfaces_linux.go:     likelyHomeRouterIP = likelyHomeRouterIPLinux
net/interfaces/interfaces_linux.go:func likelyHomeRouterIPLinux() (ret netaddr.IP, ok bool) {
net/interfaces/interfaces_linux.go:                     return likelyHomeRouterIPAndroid()
net/interfaces/interfaces_linux.go:                     return likelyHomeRouterIPAndroid()
net/interfaces/interfaces_linux.go:func likelyHomeRouterIPAndroid() (ret netaddr.IP, ok bool) {
net/interfaces/interfaces_windows.go:   likelyHomeRouterIP = likelyHomeRouterIPWindows
net/interfaces/interfaces_windows.go:func likelyHomeRouterIPWindows() (ret netaddr.IP, ok bool) {
```

**Comment by DentonGentry** [comment] 2022-03-27 06:41
This is likely fixed by https://github.com/tailscale/tailscale/commit/9fd9abfd3fd12ac91f5678fb290f3c19fda88b0d

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Closed** 2022-03-27 15:11 UTC
Labels: OS-freebsd, L1 Very few, P1 Nuisance, T0 New feature, bug

**Comment by Viper780** [comment] 2022-05-10 19:27
I have the same problem in v1.24.2 under FreeBSD 12.3 p5 in a Jail

`Program starting: v1.24.2, Go 1.18: []string{"./tailscaled"}
LogID: 60ad8d12f269063c7e168a533f84bc2d474dc01db52a8aafbb8f3fd6c7be8e0a
logpolicy: using system state directory "/var/db/tailscale"
monitor: devd dial error: dial unixpacket /var/run/devd.seqpacket.pipe: connect: no such file or directory, falling back to polling method
wgengine.NewUserspaceEngine(tun "tailscale0") ...
no TUN failure diagnostics for OS "freebsd"
wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): open /dev/tun: no such file or directory
flushing log.
logger closing down
createEngine: tstun.New("tailscale0"): open /dev/tun: no such file or directory`

` # tailscaled debug --portmap
2022/05/10 21:22:59 monitor: monitor: devd dial error: dial unixpacket /var/run/devd.seqpacket.pipe: connect: no such file or directory, falling back to polling method
2022/05/10 21:22:59 no gateway or self IP; interfaces.State{defaultRoute= ifs={lagg0:[192.168.1.56/32]} v4=true v6=false}`

**Comment by calimansi** [comment] 2022-06-07 18:39
Hi.

I'm running tailscale in OPNSense, version 1.24.2.  This is running in a VM through proxmox.

I am having this same issue.  I do have the universal plug and play plugin installed.  Sometimes the tailscale connection will be listed in the plugin status, but the portmapping line will be blank in tailscale.

Any fix for this yet?
