### ISSUE TITLE
Bad GPG signature found when using KDE Discover

### ISSUE THREAD

**Issue by t3kg33k** [tailscale/tailscale#6246] opened 2022-11-09 11:18 UTC
### What is the issue?

When attempting to complete updates in Fedora 36 KDE via Discover I get the following message and the updates fail:

```
Bad GPG signature found:<br/><br/>/var/cache/PackageKit/36/metadata/tailscale-stable-36-x86_64/packages/tailscale_1.32.2_x86_64.rpm could not be verified.
/var/cache/PackageKit/36/metadata/tailscale-stable-36-x86_64/packages/tailscale_1.32.2_x86_64.rpm:  digest:  SIGNATURE:  NOT OK
```
In order to complete updates I have to uninstall Tailscale, run updates to completion, and then reinstall Tailscale.
This is a consistent error seen and practice on my laptop and desktop.

### Steps to reproduce

Run updates in KDE Discover

### Are there any recent changes that introduced the issue?

No

### OS

Linux

### OS version

Fedora 36 KDE Plasma

### Tailscale version

1.32.1-1

### Bug report

BUG-223a942f89a47ae5f793015e80673d8ffb9d2f3fc0d97df07e6b42b0992f386c-20221109111706Z-7794eeac66a60538

**Comment by t3kg33k** [comment] 2022-11-09 11:28
Follow up:

I just attempted a _sudo dnf update_ from CLI and did NOT get the error. Updates were successful.
So, I am assuming there is an issue with the update process in KDE Discover Software Center.
If so, is that a KDE issue or a Tailscale issue?

**Comment by DentonGentry** [comment] 2022-11-10 01:03
There appear to be other packages which KDE Discover flags as having a bad signature: https://www.reddit.com/r/Fedora/comments/847jic/cant_install_bluej_on_fedora_kde_bad_gpg/

**Comment by ejnshtein** [comment] 2023-01-04 22:49
+1

Currently, I have version `1.34.1-1` and trying to update it to `1.34.2-1`.
Same Distro, its version and solution as reported earlier.

**Comment by danderson** [comment] 2023-01-04 22:53
It sounds like KDE discover might not be implementing the full rpm spec. In particular, it may be insisting on having signatures on the individual package files, whereas our package server signs the index root file, which transitively verifies the packages by virtue of the hashes in the index.

The .repo file we provide (https://pkgs.tailscale.com/stable/fedora/36/tailscale.repo) specifies to enforce signature checking on the repo index, and not on individual packages. So, I think this is a KDE Discover upstream bug?

**Comment by DentonGentry** [comment] 2023-02-18 20:03
I believe this will be resolved by signing the packages then.
Duplicate of https://github.com/tailscale/tailscale/issues/1882

**Closed by DentonGentry** 2023-02-18 20:03 UTC
Labels: OS-linux, L1 Very few, P2 Aggravating, T5 Usability, bug
