### ISSUE TITLE
DNS broken on MacOS when Tailscale Exit Node enabled

### ISSUE THREAD

**Issue by viertaxa** [tailscale/tailscale#12984] opened 2024-07-31 18:03 UTC
### What is the issue?

When running the MacOS (App Store version) client with an exit node enabled, MacOS is unable to resolve DNS queries unless the local client has "Use Tailscale DNS Settings" enabled and the Admin Console has "Override local DNS" enabled under the DNS tab. 

Note: I have not yet tested this on Windows or Linux. iOS exhibits the same behavior.

## Reproduction steps:

- Set up an exit node
- Set up a MacOS node
- Set MacOS node to not use Tailscale DNS Settings
- Enable using exit node on MacOS client
- Observe DNS does not resolve
  - `dig`, `nslookup` etc. fail in addition to user applications
- Observe network routing works as expected
  - Able to ping/connect to IP addresses without issue
- Set MacOS node to use Tailscale DNS Settings
- Observe DNS still does not resolve
- Set Admin portal DNS settings to override local DNS
- Observe DNS works correctly

## Details of MacOS Client:

**Version:** 1.70.0, Mac App Store Variant
**MacOS Version:** 14.5 (23F79)
**WiFi Configured DNS Setting:** 1.1.1.1

### Working: Use Tailscale DNS ✅ Override Local DNS ✅ 

```
DNS configuration

resolver #1
  nameserver[0] : 100.100.100.100
  if_index : 26 (utun8)
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 100600

resolver #2
  nameserver[0] : 100.100.100.100
  if_index : 26 (utun8)
  flags    : Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 200000

resolver #3

<<MDNS Entries Removed For Brevity>>

DNS configuration (for scoped queries)

resolver #1
  search domain[0] : <<redacted>>
  nameserver[0] : 1.1.1.1
  if_index : 15 (en0)
  flags    : Scoped, Request A records
  reach    : 0x00000002 (Reachable)

resolver #2
  nameserver[0] : 100.100.100.100
  if_index : 26 (utun8)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
```

### Broken: Use Tailscale DNS ✅ Override Local DNS ❌ 

```
DNS configuration

resolver #1
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)

resolver #2
  <<MDNS Resolvers Snipped>>

DNS configuration (for scoped queries)

resolver #1
  search domain[0] : <<Redacted>>
  nameserver[0] : 1.1.1.1
  if_index : 15 (en0)
  flags    : Scoped, Request A records
  reach    : 0x00000002 (Reachable)
```

### Broken: Use Talscale DNS ❌ 

```
DNS configuration

resolver #1
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)

resolver #2
  <<MDNS Resolvers Snipped>>

DNS configuration (for scoped queries)

resolver #1
  search domain[0] : <<Redacted>>
  nameserver[0] : 1.1.1.1
  if_index : 15 (en0)
  flags    : Scoped, Request A records
  reach    : 0x00000002 (Reachable)
```

## See Also

https://github.com/tailscale/tailscale/issues/1544

https://github.com/tailscale/tailscale/issues/1647

### Are there any recent changes that introduced the issue?

N/A, first pass at implementing this exact setup

### OS

macOS, iOS

### OS version

MacOS: 14.5 (23F79) iOS: 17.5.1

### Tailscale version

Mac: 1.70.0 iOS: 1.70.0

### Other software

Nothing on either the MacOS client or the iPhone client should be affecting these settings. MacOS Firewall is enabled. No MDM or other similar systems on either platform

### Bug report

BUG-8468bca6238e0dcd57625d20aec433248f8325e33029431759db7314bac53a96-20240731180346Z-eac6425c27618800

**Comment by viertaxa** [comment] 2024-07-31 20:01
Good to hear it's known!

Here's what I would expect:

Use Tailscale DNS: ❌

Unclear on what the desired outcome is here, maybe a setting is required to handle what the user wants. 

A) Default: Enable Tailscale DNS and Override local DNS to Tailscale nameservers when an exit node is active

B) Bypass Exit Node and query locally configured nameservers. (If the IP is publicly routable, I would probably expect it to go over the Exit Node.)


Use Tailscale DNS: ✅ 
Override Local DNS: ❌ 

Same as above, but for setting B, overridden domains (in the admin portal), uses those nameservers. Fails back to the global Tailscale DNS servers in the admin portal. 

Use Tailscale DNS: ✅ 
Override Local DNs: ✅ 

Uses the overridden domains and global nameservers from Tailscale exclusively. 


I am not really sure there is a great reason to not just enable Tailscale DNS and override local DNS whenever an exit node is enabled. It's a lot of complexity to support the various permutations of using the locally set nameservers and routing traffic to the local network or out of the exit node. 

Perhaps the existing "enable local network access" option could include not overriding the local DNS servers?

**Comment by agottardo** [comment] 2024-10-08 18:11
Duplicate of https://github.com/tailscale/tailscale/issues/12244, we'll be landing a fix for that shortly.

**Closed by agottardo** 2024-10-08 18:11 UTC
Labels: OS-macos, dns, needs-triage, bug
