### ISSUE TITLE
Mere presence of macOS Adult Content filter can break Tailscale connectivity

### ISSUE THREAD

**Issue by atanumaj** [tailscale/tailscale#5701] opened 2022-09-20 17:03 UTC
### What is the issue?

Installed tailscale successfully, but getting below error while making tailscale up. 
OS - Raspbery pi

Sep 13 19:32:31 VW tailscaled[2886]: control: LoginInteractive -> regen=true
Sep 13 19:32:31 VW tailscaled[2886]: control: doLogin(regen=true, hasUrl=false)
Sep 13 19:32:31 VW tailscaled[2886]: control: Generating a new nodekey.
Sep 13 19:32:31 VW tailscaled[2886]: control: RegisterReq: onode= node=[ARi4S] fup=false
Sep 13 19:32:32 VW tailscaled[2886]: Received error: register request: Post "https://controlplane.tailscale.com/machine/register": unexpected EOF
Sep 13 19:33:03 VW tailscaled[2886]: control: LoginInteractive -> regen=true
Sep 13 19:33:03 VW tailscaled[2886]: control: doLogin(regen=true, hasUrl=false)
Sep 13 19:33:03 VW tailscaled[2886]: control: Generating a new nodekey.
Sep 13 19:33:03 VW tailscaled[2886]: control: RegisterReq: onode= node=[eVXpg] fup=false
Sep 13 19:33:03 VW tailscaled[2886]: Received error: register request: Post "https://controlplane.tailscale.com/machine/register": unexpected EOF

### Steps to reproduce

tailscale up 

### OS

Linux, Other

### OS version

Raspberry pi 32

**Comment by bradfitz** [comment] 2022-09-20 17:10
If you run `tailscale debug ts2021`, what does it say?

**Comment by atanumaj** [comment] 2022-09-20 18:28
I am getting this

root@VW:~# tailscale debug ts2021
18:27:50.743508 Fetching keys from https://controlplane.tailscale.com/key?v=41 ...
18:27:51.423226 Dial("tcp", "52.29.8.43:80") ...
18:27:51.424414 Dial("tcp", "52.29.8.43:80") = 10.46.0.133:57730 / 52.29.8.43:80
18:27:51.721059 controlhttp.Dial = 0x19da210, <nil>
18:27:51.721158 did noise handshake
18:27:51.721234 final underlying conn: 10.46.0.133:57730 / 52.29.8.43:80
root@VW:~#

**Comment by atanumaj** [comment] 2022-09-20 18:28
root@VW:~# tailscale debug ts2021
18:27:50.743508 Fetching keys from https://controlplane.tailscale.com/key?v=41 ...
18:27:51.423226 Dial("tcp", "52.29.8.43:80") ...
18:27:51.424414 Dial("tcp", "52.29.8.43:80") = 10.46.0.133:57730 / 52.29.8.43:80
18:27:51.721059 controlhttp.Dial = 0x19da210, <nil>
18:27:51.721158 did noise handshake
18:27:51.721234 final underlying conn: 10.46.0.133:57730 / 52.29.8.43:80
root@VW:~#


this what i see

**Comment by atanumaj** [comment] 2022-09-20 18:29
> If you run `tailscale debug ts2021`, what does it say?

root@VW:~# tailscale debug ts2021
18:27:50.743508 Fetching keys from https://controlplane.tailscale.com/key?v=41 ...
18:27:51.423226 Dial("tcp", "52.29.8.43:80") ...
18:27:51.424414 Dial("tcp", "52.29.8.43:80") = 10.46.0.133:57730 / 52.29.8.43:80
18:27:51.721059 controlhttp.Dial = 0x19da210, <nil>
18:27:51.721158 did noise handshake
18:27:51.721234 final underlying conn: 10.46.0.133:57730 / 52.29.8.43:80
root@VW:~#

**Comment by atanumaj** [comment] 2022-09-20 18:37
> Something, likely an MITM device, is closing the connection. Do you have a deep packet inspection device of some kind between the Pi and the Internet?
> 
> If you can run a browser or curl on the Pi, what happens when you visit https://controlplane.tailscale.com/ ?

There is no such device as we know off. however not sure about ISP

**Comment by bradfitz** [comment] 2022-09-20 19:24
Can you also include the output of `tailscale bugreport`?

**Comment by atanumaj** [comment] 2022-09-21 05:48
> Can you also include the output of `tailscale bugreport`?

BUG-692620f2b2412160fb3430a3a7679d5d3d447578d1a3cd1f3ac4ff83106cf502-20220921054505Z-f51fe4fb766afec8

**Comment by macksal** [comment] 2022-09-24 12:40
I'm getting the exact same issue on a Macbook Pro: an unexpected EOF when POSTing to `/machine/register`.

Same thing happens whether I try to click Log In through the UI, or if running `tailscale up` in the CLI. I've also tried generating an authkey and passing that to the CLI but get the same problem.

It seems unrelated to my ISP or any devices on my local network as I've also tried initiating the connection while connected to my mobile phone's hotspot.

I did previously register with this account on this same Macbook, but was getting some other issues (tailscale thought it was connected, but the device showed disconnected in the Admin console). Removing the device from the admin page and relogging lead to the same state I have now: Clicking the log in button did not open the browser. It seems the root cause was the same though I did not check the logs at that time.

I did a full re-install including wiping the keychain entries as described in the docs, I even changed the hostname of the device in System Preferences.

I have another Macbook currently connected to Tailscale on the same local network (different user account) and I can log out and log back in freely with no issues. I don't want to wipe my machine key there in case it doesn't work, but the problem certainly seems specific to the one device.

`tailscale bugreport`:

`BUG-1799da44d5606f4e840c92681158b416361013f690a767f62fce562ea255f960-20220924123639Z-38c3ce73cacba8a1`

**Comment by atanumaj** [comment] 2022-09-24 18:56
> UPDATE: I've just fixed this but leaving it for reference. It was the adult content filter on OSX. Adding an exception rule did not work, I had to disable the Adult Websites filter completely. Why this was triggering the filter I do not know - maybe a tailscale IP ended up on some blacklist.
> 
> ~I'm getting the exact same issue on a Macbook Pro: an unexpected EOF when POSTing to `/machine/register`.~
> 
> ~Same thing happens whether I try to click Log In through the UI, or if running `tailscale up` in the CLI. I've also tried generating an authkey and passing that to the CLI but get the same problem.~
> 
> ~It seems unrelated to my ISP or any devices on my local network as I've also tried initiating the connection while connected to my mobile phone's hotspot.~
> 
> ~I did previously register with this account on this same Macbook, but was getting some other issues (tailscale thought it was connected, but the device showed disconnected in the Admin console). Removing the device from the admin page and relogging lead to the same state I have now: Clicking the log in button did not open the browser. It seems the root cause was the same though I did not check the logs at that time.~
> 
> ~I did a full re-install including wiping the keychain entries as described in the docs, I even changed the hostname of the device in System Preferences.~
> 
> ~I have another Macbook currently connected to Tailscale on the same local network (different user account) and I can log out and log back in freely with no issues. I don't want to wipe my machine key there in case it doesn't work, but the problem certainly seems specific to the one device.~
> 
> ~`tailscale bugreport`:~
> 
> ~`BUG-1799da44d5606f4e840c92681158b416361013f690a767f62fce562ea255f960-20220924123639Z-38c3ce73cacba8a1`~

What firewall/ content filtering you are using??Can you please provide me details?

**Comment by atanumaj** [comment] 2022-09-24 19:05
Looklike some of the tailscale ips are listed in blacklist


https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3aTailscale.com&run=toolpage

**Comment by DentonGentry** [comment] 2022-09-24 19:18
`tailscale.com` is the website. `controlplane.tailscale.com` is the one which would matter in this instance, and that mxtoolbox.com site doesn't show any blocklist entries for it.

**Comment by macksal** [comment] 2022-09-25 00:51
> What firewall/ content filtering you are using??Can you please provide me details?

It's the one built into OSX under Screen Time. There's an option to disable adult web content.

Interestingly, I can actually load that `/machine/register` endpoint in a web browser with no issues (gets an error response from the server) and also other pages on the controlplane domain. So it doesn't seem to be an IP-level ban. Maybe filtering is done on the actual content of the response during a normal registration workflow? Perhaps some keyword in there triggers some filters? Who knows.

**Comment by atanumaj** [comment] 2022-09-25 01:40
> `tailscale.com` is the website. `controlplane.tailscale.com` is the one which would matter in this instance, and that mxtoolbox.com site doesn't show any blocklist entries for it.

Yes, i am aware about it. I was thinking tailscale and control plane might shares ip's...

**Comment by atanumaj** [comment] 2022-09-25 01:44
> > What firewall/ content filtering you are using??Can you please provide me details?
> 
> It's the one built into OSX under Screen Time. There's an option to disable adult web content.
> 
> Interestingly, I can actually load that `/machine/register` endpoint in a web browser with no issues (gets an error response from the server) and also other pages on the controlplane domain. So it doesn't seem to be an IP-level ban. Maybe filtering is done on the actual content of the response during a normal registration workflow? Perhaps some keyword in there triggers some filters? Though it does go over TLS. Who knows.

Interesting...in my case I saw it did connects, but intermittently...

**Comment by DentonGentry** [comment] 2022-10-05 02:06
Since this has been identified and resolved, closing it now.

**Closed by DentonGentry** 2022-10-05 02:06 UTC
Labels: needs-triage, bug
