### ISSUE TITLE
Install fails with /usr/sbin/policy-rc.d returned 101, not running 'start tailscaled.service' on ubuntu 20.04

### ISSUE THREAD

**Issue by mdcnz** [tailscale/tailscale#990] opened 2020-12-04 06:54 UTC
**Describe the bug**
tailscale did not install correctly on a default ubuntu 20 on a brand new machine. Possibly due to a default configuration of ubuntu preventing services being created & started on install.

**To Reproduce**
Following the [installation instructions](https://tailscale.com/download/linux/ubuntu-2004):

```
$ curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.gpg | sudo apt-key add -
$ curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.list | sudo tee /etc/apt/sources.list.d/tailscale.list
$ sudo apt-get update
$ sudo apt-get install tailscale

...

Setting up tailscale (1.2.8) ...
/usr/sbin/policy-rc.d returned 101, not running 'start tailscaled.service'
```

**Expected behavior**
A clean install, and tailscaled service to be created and start running.

**Fix (hack?)**
Edit /usr/sbin/policy-rc.d file, and comment out the `exit 101` (or delete the file?):

```
#!/bin/sh
#exit 101
```
Then after uninstall, reinstall succeeds and can start:

```
$ sudo apt-get remove tailscale
$ sudo apt-get install tailescale
$ sudo tailscale up
$ service tailscaled status

● tailscaled.service - Tailscale node agent
     Loaded: loaded (/lib/systemd/system/tailscaled.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2020-12-04 19:16:11 NZDT; 23min ago
```

**Version information:**
Linux 5.4.0-56-generic
ubuntu 20.04
tailscale 1.2.8

**Additional context**
The policy-rc.d file was already on the machine, I didn't add it. 
Explanation from JPetazzo about [policy-rc.d](https://jpetazzo.github.io/2013/10/06/policy-rc-d-do-not-start-services-automatically/).

More info on [a question on stack exchange](https://serverfault.com/questions/567474/how-can-i-install-packages-without-starting-their-associated-services)

**Comment by bradfitz** [comment] 2020-12-04 15:40
Weird. I'm pretty sure most of my/our Ubuntu machines were fresh installs but I've never seen that file.

When does it get included by default? Is it only present with some extra option during the installer?

/cc @danderson

**Comment by mdcnz** [comment] 2020-12-05 21:51
Thanks for the response. I've never seen policy-rc.d before either on other machines.

I don't know enough to say when it gets included. Other than disk encryption, installation was typical. I didn't need to touch any config files. I probably did something wrong inadvertently though.

It's fixed now so I'm happy for this to be closed and maybe reopen if it happens to anyone else.

More info on the blog [Zugschlusbeobachtungen](https://blog.zugschlus.de/archives/974-Debians-Policy-rc.d-infrastructure-explained.html) (try to prounounce that!)

**Comment by DentonGentry** [comment] 2021-02-09 01:19
I'm not even clear that this is a bug. If /usr/sbin/policy-rc.d is present and exits with a non-zero code, new services will not be automatically started after install. That is the behavior noted in this report, /usr/sbin/policy-rc.d is working as intended.

I think we're pretty sure that the tailscale package did not create /usr/sbin/policy-rc.d. Something else did.

**Comment by DentonGentry** [comment] 2021-02-09 01:20
I'm going to close this as not-a-bug. Please reopen if needed.

**Closed by DentonGentry** 2021-02-09 01:20 UTC
Labels: L1 Almost no one, OS-linux, P1 Nuisance

**Comment by atriwidada** [comment] 2024-06-12 08:52
I encounter similar error, not related to tailscale at all, but maybe will be useful for others.

/usr/sbin/policy-rc.d is from livecd-rootfs package

https://packages.ubuntu.com/search?suite=focal&arch=any&mode=exactfilename&searchon=contents&keywords=policy-rc.d

seems that that file was left around because of Ubuntu initial installation not finished properly
