### ISSUE TITLE
cmd/tailscale: make CLI "up" give some more hints

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3552] opened 2021-12-11 23:11 UTC
Currently, "tailscale up --advertise-route=..." will warn on stderr when the machine's subnet routing is not configured.

But we can do more:

* [ ] warn that an advertised route or exit node isn't yet approved (or was auto-approved if it's a single-user tailnet, to educate people that approval is normally required)
* [x] tell people if there are subnets being advertised on their network that they're not accepting (mitigation for #2053)

/cc @mayakacz

**Comment by DentonGentry** [comment] 2023-02-12 20:56
The second point is done:
```
root@mc-creative:~# tailscale up
Some peers are advertising routes but --accept-routes is false
```

The first is tracked in [#2426](https://github.com/tailscale/tailscale/issues/2426).
Closing remaining work as a duplicate of [#2426](https://github.com/tailscale/tailscale/issues/2426)

**Closed by DentonGentry** 2023-02-12 20:56 UTC
Labels: OS-linux, needs-fix
