### ISSUE TITLE
FR: Sort columns on machine listing on Admin page

### ISSUE THREAD

**Issue by gabefair** [tailscale/tailscale#3789] opened 2022-01-23 04:11 UTC
### What are you trying to do?

I would like to sort the  devices by the column showing last seen online.

**Comment by DentonGentry** [comment] 2022-01-23 04:24
Could I ask the goal of sorting by time last seen online?
To identify machines which have dropped out of contact?

**Comment by DentonGentry** [comment] 2022-02-06 07:18
Duplicate of https://github.com/tailscale/tailscale/issues/2537

Note in particular https://github.com/tailscale/tailscale/issues/2537#issuecomment-888442297

**Closed by DentonGentry** 2022-02-06 07:18 UTC
Labels: admin UI, L3 Some users, P1 Nuisance, T2 Visual Polish, fr
