### ISSUE TITLE
unable to connect with a custom login server.

### ISSUE THREAD

**Issue by Retropex** [tailscale/tailscale#10596] opened 2023-12-14 11:51 UTC
### What is the issue?

Since the last update, I have been disconnected from my custom server.

### Steps to reproduce

Update to the latest version.

### OS

macOS

### OS version

14.2

### Tailscale version

1.56

**Comment by DentonGentry** [comment] 2023-12-14 13:42
Duplicate of https://github.com/tailscale/tailscale/issues/10593

**Closed by DentonGentry** 2023-12-14 13:42 UTC
Labels: needs-triage, bug
