### ISSUE TITLE
Code path in `tailscale cert` does not respect `--socket`?

### ISSUE THREAD

**Issue by Knufle** [tailscale/tailscale#10027] opened 2023-10-31 12:10 UTC
### What is the issue?

Running `tailscale cert` on the Tailscale docker container causes a "failed to connect" error.

```
$ docker exec tailscaled-${SERVICE_NAME} tailscale cert ${MY_HOSTNAME}.${MY_TS_TLS_DOMAIN}
Failed to connect to local Tailscale daemon for /localapi/v0/cert/<REDACTED>; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```
The same result occurs when running the command from a Bourne shell inside the Docker container, via a `docker exec -ti tailscaled-${SERVICE_NAME} /bin/sh` shell.

Passing the `tailscale --socket /tmp/tailscaled.sock` flag did not fix the issue. (`/tmp/tailscaled.sock` is where the Docker image keeps the socket, which I discovered looking at `ps aux` inside the container.)

What did fix the issue was the following:

```
docker exec tailscaled-${SERVICE_NAME} mkdir -p /var/run/tailscale
docker exec tailscaled-${SERVICE_NAME} ln -s /tmp/tailscaled.sock /var/run/tailscale/tailscaled.sock
```
and then proceeding as above.

I'm no Gopher, so I can't provide a PR to your code, but I suspect that there's a code path specific to the `tailscale cert` operation that doesn't respect the `--socket` flag.

### Steps to reproduce

```
$ docker exec tailscaled-${SERVICE_NAME} tailscale cert ${MY_HOSTNAME}.${MY_TS_TLS_DOMAIN}
Failed to connect to local Tailscale daemon for /localapi/v0/cert/<REDACTED>; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```
The same result occurs when running the command from a Bourne shell inside the Docker container, via a `docker exec -ti tailscaled-${SERVICE_NAME} /bin/sh` shell.

### Are there any recent changes that introduced the issue?

Not aware of any.

### OS

Linux, Other

### OS version

Debian 12

### Tailscale version

1.50.1

### Bug report

BUG-0143464cecfc011a2bbdd6d98048e94e3da96c1d38d8365f7a3ba58aa918ee6c-20231031120959Z-e28357028ea48321

**Comment by flimamacedo** [comment] 2023-11-13 00:26
Hey @Knufle  were you able to access your web app through tailscale proxy? I ran the command to generate the .key. and .crt, but I don't know what the next step is to make it work...

**Comment by DentonGentry** [comment] 2023-11-13 00:39
> Hey @Knufle were you able to access your web app through tailscale proxy?

I assume this means Funnel, where a node on the tailnet can be given a public URL?
https://tailscale.com/kb/1223/funnel/

**Comment by flimamacedo** [comment] 2023-11-13 12:49
So, I am using a proxy that has been created (`make proxy | kubectl apply -f-`) through this repo: https://github.com/tailscale/tailscale/tree/main/docs/k8s

After running this command I can see the new pod up and running. I also can see a new machine that has been added to the Tailscale admin console. But, there is working only access through HTTP. When I try to access HTTPS I get a connection refused message on the browser. 

So, I was reading the documentation https://tailscale.com/kb/1153/enabling-https/, when I got the error mentioned by @Knufle, because the original Tailscale image was not able to run `tailscale cert <hostname-domain `. So just follow up on what @Knufle shared with us and was able to generate the .crt and .key, but what should I do now?

**Comment by bradfitz** [comment] 2023-11-17 15:29
> Passing the `tailscale --socket /tmp/tailscaled.sock` flag did not fix the issue.

Can you share the exact full command you tried?

**Comment by irbekrm** [comment] 2023-11-20 09:10
If you want to expose an app running in Kubernetes over HTTPs, you can use Tailscale Kubernetes operator with Ingress resource https://tailscale.com/kb/1236/kubernetes-operator/#ingress-resource. Would that work for you?

**Comment by flimamacedo** [comment] 2023-11-20 12:11
> If you want to expose an app running in Kubernetes over HTTPs, you can use Tailscale Kubernetes operator with Ingress resource https://tailscale.com/kb/1236/kubernetes-operator/#ingress-resource. Would that work for you?

Let me check it. Thanks!

**Comment by flimamacedo** [comment] 2023-11-21 12:14
Hey @irbekrm it seems these steps are used to expose to the internet using HTTPS. I do not want to be exposed to the internet using Funnel. I just want to access the web app through a VPN using HTTPS. I am using the [official repo](https://github.com/tailscale/tailscale/tree/main/docs/k8s) to create the k8s resources to make it possible, but we only see HTTP examples using sidecar or proxy.

**Comment by irbekrm** [comment] 2023-11-21 12:31
Hi,

>  it seems these steps are used to expose to the internet using HTTPS

Are you referring to [ingress via Kubernetes operator](https://tailscale.com/kb/1236/kubernetes-operator/#ingress-resource)? No, by default it will expose it to your tailnet only. Funnel is only switched on if you [explicitly enable it](https://tailscale.com/kb/1236/kubernetes-operator/#exposing-a-service-to-the-public-internet-using-ingress-and-tailscale-funnel).
By default, we just issue LetsEncrypt cert for the ingress proxy's Tailnet FQDN, so things on your tailnet can talk HTTPS to the proxy in cluster over tailnet. So you should be able to use it- let me know if that makes sense.

> I am using the [official repo](https://github.com/tailscale/tailscale/tree/main/docs/k8s) to create the k8s resources to make it possible, but we only see HTTP examples using sidecar or proxy.

The Readme there might be out of date, you probably want to look at the docs on our website instead https://tailscale.com/kb/1185/kubernetes/

**Comment by flimamacedo** [comment] 2023-11-21 13:26
I performed exactly the same [steps](https://tailscale.com/kb/1185/kubernetes/), but there is not option to connect using HTTPS...

**Comment by irbekrm** [comment] 2023-11-21 13:56
@flimamacedo did you try it with the Ingress, like the steps outlined here https://tailscale.com/kb/1236/kubernetes-operator/?q=kubernetes#ingress-resource?

If you do that, you should see that Tailscale operator populates the `status.loadBalancer.ingress.hostname` with a Tailscale FQDN. This will be resolvable in your tailnet like any other Tailscale FQDN and the proxy serves HTTPS by default so you don't need to do anything additional to connect to your app in cluster behind the Ingress over HTTPS.

If that does not work, could you paste any errors that you get i.e if `curl` the Ingress hostname and what resources you created?

**Comment by flimamacedo** [comment] 2023-11-22 11:46
Hi @irbekrm,

I hope this message finds you well. I've outlined the steps I took to set up the Ingress resource for the nginx app, and I'd appreciate your review, as I'm encountering difficulties accessing the app over HTTPS.


Step 1: Created `nginx-ingress.yaml`

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
spec:
  defaultBackend:
    service:
      name: proxy-kubeflow
      port:
        number: 80
  ingressClassName: tailscale
  tls:
  - hosts:
    - proxy-kubeflow
```

The proxy-kubeflow backend was set up following the [provided instructions](https://github.com/tailscale/tailscale/tree/main/docs/k8s#sample-proxy), and it seems to be functioning correctly, as indicated by the attached screenshots.

![image](https://github.com/tailscale/tailscale/assets/15217899/cf7e6730-ab6c-45fb-a9bd-19bc99ef03f5)
![image](https://github.com/tailscale/tailscale/assets/15217899/4fb40ef3-9685-46fc-a238-dde1980c3186)

Step 2: Created `nginx-service.yaml`

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  type: ClusterIP
```

Is there anything I might be missing or any additional steps I should take to troubleshoot the issue? Your insights would be greatly appreciated.

Thank you for your time and assistance.

**Comment by irbekrm** [comment] 2023-11-22 12:01
Hi @flimamacedo 

Thank you for providing the yamls and the screenshots.

Could you please also paste in the status of the `Ingress` resource that you deployed?

**Comment by irbekrm** [comment] 2023-11-22 12:21
@flimamacedo the `.status` subresource of it. You could just paste in the output of `kubectl get ingress nginx -ojsonpath={.status}`

**Comment by flimamacedo** [comment] 2023-11-22 12:27
```
kubectl get ingress nginx -ojsonpath={.status}
{"loadBalancer":{}}
```

**Comment by flimamacedo** [comment] 2023-11-22 12:28
This could be a problem too:

```
kubectl describe ingress nginx
Name:             nginx
Labels:           <none>
Namespace:        default
Address:          
Ingress Class:    tailscale
Default backend:  istio-ingressgateway:80 (<error: endpoints "istio-ingressgateway" not found>)
TLS:
  SNI routes proxy-kubeflow
Rules:
  Host        Path  Backends
  ----        ----  --------
  *           *     istio-ingressgateway:80 (<error: endpoints "istio-ingressgateway" not found>)
Annotations:  <none>
Events:       <none>
```

**Comment by irbekrm** [comment] 2023-11-22 12:35
It does not look like the operator picked it up. Did you actually create the Tailscale Kubernetes operator? Also you did not need to create a tailscale sidecar proxy as well.

The steps that you should follow are:
- create the Kubernetes operator like in https://tailscale.com/kb/1236/kubernetes-operator/#setting-up-the-kubernetes-operator
- deploy your app in Kubernetes as usual (no Tailscale proxy)
- create a Service that points at your application _if you don't already have one_, for example
```
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  ports:
  - name: http
    port: 
    targetPort: 80 <- where ever your app container is listening to
  type: ClusterIP
```
- create a Tailscale Ingress that points at the Service for your app
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app
spec:
  defaultBackend:
    service:
      name: my-app
      port:
        number: 80
  ingressClassName: tailscale
```

The Tailscale Kubernetes operator will then create a proxy for you and issue certs for that proxy's tailnet FQDN

**Comment by irbekrm** [comment] 2023-11-22 12:39
If you follow these steps and still don't see an FQDN on Ingress' status, the next thing to do would be to look at the operator logs.

**Comment by DentonGentry** [comment] 2023-11-23 13:54
> Am I able to set the app URL?

[Tailscale Funnel](https://tailscale.com/blog/introducing-tailscale-funnel/) works by examining the SNI header of an incoming TLS connection to determine which tailnet it is destined for, and forwards the encrypted TLS bits to that node on that tailnet. Funnel does not possess the HTTPS certificate for your site, the node on your tailnet handles decryption and responding to any requests.

All of which is to say: Funnel cannot make any changes in the request like rewriting the URL path, it does not have the capability to decrypt the stream.

**Comment by irbekrm** [comment] 2023-11-24 05:20
@flimamacedo what does your app normally do if `/` is requested?

**Comment by flimamacedo** [comment] 2023-11-24 12:13
> @flimamacedo what does your app normally do if `/` is requested?

Loads a Dex login page like this:
![image](https://github.com/tailscale/tailscale/assets/15217899/ea87921d-66ca-442b-be38-d07459bd91c2)

**Comment by irbekrm** [comment] 2023-11-27 11:09
@flimamacedo how/where is Dex deployed and how is it exposed to your browser and to the app? is it running in the same cluster?

**Comment by flimamacedo** [comment] 2023-11-27 11:40
> @flimamacedo how/where is Dex deployed and how is it exposed to your browser and to the app? is it running in the same cluster?

Hi @irbekrm,

The app was deployed using this [repository/instructions](https://github.com/kubeflow/manifests#dex). We also have on the same repo the [instructions](https://github.com/kubeflow/manifests#port-forward) to connect to the web app using port-forward.

**Comment by irbekrm** [comment] 2023-11-27 11:51
Thanks- so just to clarify you are also using Istio?

**Comment by flimamacedo** [comment] 2023-11-27 11:52
Yes.

**Comment by irbekrm** [comment] 2023-11-27 12:42
OK, so my understanding is that the problem is that there needs to be a DNS name that both your app and your browser needs to be able to resolve by which Dex should be accessible and that also needs to be passed to Dex, see https://github.com/dexidp/dex/blob/master/config.yaml.dist#L1-L4.
I see that the default Kubeflow setup uses Kubernetes Service name https://github.com/kubeflow/manifests/blob/master/common/dex/base/config-map.yaml#L7- in that case I don't understand how you had it working before because that would not have been resolvable from your browser?

**Comment by flimamacedo** [comment] 2023-11-28 01:07
The issue was fixed after adding the missing metadata value (namespace). In my case, my ingress was defined this way:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeflow
  namespace: istio-system
spec:
  defaultBackend:
    service:
      name: istio-ingressgateway
      port:
        number: 80
  ingressClassName: tailscale
```

Thanks @irbekrm !

**Comment by irbekrm** [comment] 2023-11-29 06:56
Hi @flimamacedo `istio-system-kubeflow-ingress.tailffbf3.ts.net` is a tailnet device FQDN, it can only be resolved from within the tailnet, so a Pod running in Kubernetes cluster won't be able to resolve it. Can't you refer to the ingress gateway by its Kubernetes Service name from within the Pod?

**Comment by flimamacedo** [comment] 2023-11-29 11:45
Ok, got it. I don't think so. Let me check if there is one way to make it work.

Thanks!

**Comment by irbekrm** [comment] 2023-11-29 12:33
> Let me check if there is one way to make it work

OK, do let us know if it does not work.

We are planning to make Tailscale FQDNs resolvable from within cluster too (cc @knyar ), but are currently looking for more use cases for this functionality.

(It might be that you are hitting https://github.com/tailscale/tailscale/issues/10027#issuecomment-1827763853, however I saw that your setup was working previously (?) so I assumed that you were somehow able to expose Dex with a kube DNS name)

**Comment by flimamacedo** [comment] 2023-11-29 12:46
Nice!

Yes, it was working previously because we were not using Azure AD integration...

**Comment by flimamacedo** [comment] 2023-12-07 14:09
Hey @irbekrm, do you guys have any plans to work on Tailscale FQDNs for being resolvable from within the cluster too?

**Comment by irbekrm** [comment] 2023-12-07 15:20
@flimamacedo yes, we will do it, I don't have a timeline, but there is already an open PR that achieves that, but we still need to re-evaluate if this is the right aproach.https://github.com/tailscale/tailscale/pull/9201

Keen to learn more about your Dex setup that requires Tailscale FQDN to be resolved from within the cluster. I guess I need to take another look at the Kubeflow that you linked before?

> Yes, it was working previously because we were not using Azure AD integration

Do you have a link or something that shows how you are setting it up?

**Comment by irbekrm** [comment] 2023-12-07 17:30
@flimamacedo I've created a separate issue for resolving Tailscale FQDNs in cluster https://github.com/tailscale/tailscale/issues/10499. I've also added a possible workaround to that issue.

**Comment by flimamacedo** [comment] 2023-12-08 11:45
> @flimamacedo yes, we will do it, I don't have a timeline, but there is already an open PR that achieves that, but we still need to re-evaluate if this is the right aproach.#9201
> 
> Keen to learn more about your Dex setup that requires Tailscale FQDN to be resolved from within the cluster. I guess I need to take another look at the Kubeflow that you linked before?
> 
> > Yes, it was working previously because we were not using Azure AD integration
> 
> Do you have a link or something that shows how you are setting it up?


Hi @irbekrm below you cna find how I did the Azure AD integration:


To enable both Dex and OIDC authentication methods, the following steps can be taken:


1. Edit the file manifests/common/dex/base/config-map.yaml and include the connector section outlined below:

```yaml
  config.yaml: |
    issuer: https://istio-system-kubeflow-ingress.tailffbf3.ts.net/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    connectors:
      - type: oidc
        id: microsoft
        name: Microsoft Azure AD
        config:
          issuer: https://login.microsoftonline.com/9839fdcf-8ee5-43a6-80c3-e455057b2f1e/v2.0
          clientID: 2ecafd9f
          clientSecret: W5i8Q~
          redirectURI: https://istio-system-kubeflow-ingress.tailffbf3.ts.net/dex/callback
          tenant: 9839fdcf-8ee5-43a6-80c3-e455057b2f1e
          insecureSkipEmailVerified: true
    oauth2:
      skipApprovalScreen: true
```

2. Edit the file `manifests/common/oidc-authservice/base/secret_params.env` and update the values of CLIENT_ID and CLIENT_SECRET.

3. Edit the file `manifests/common/oidc-authservice/base/params.env` and set the variable OIDC_PROVIDER to the value `https://istio-system-kubeflow-ingress.tailffbf3.ts.net/dex`.

Apply the changes using the following commands:

```bash
kustomize build common/dex/base/ | kubectl apply -f -
kubectl rollout restart deployment dex -n auth
kustomize build common/oidc-authservice/base | kubectl apply -f -
kubectl rollout restart statefulset authservice -n istio-system
```

Presently, the Dex Login page features an additional button facilitating authentication through Azure AD.

![image](https://github.com/tailscale/tailscale/assets/15217899/b5d82958-39b8-477b-ae16-58cd64668233)

The current implementation faces functionality issues due to the unavailability of Tailscale Fully Qualified Domain Names (FQDNs) for resolution within the `authservice-0` pod or by the cluster. Presently, the encountered error is as follows:

```
time="2023-12-07T06:28:38Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get \"https://istio-system-kubeflow-ingress.tailffbf3.ts.net/dex/.well-known/openid-configuration\": dial tcp: lookup istio-system-kubeflow-ingress.tailffbf3.ts.net on 169.254.25.10:53: no such host"
````

**Comment by flimamacedo** [comment] 2023-12-08 11:46
> #9201

Yes, to my mind only `authservice` pod must be able to resolve the FQDN...

**Comment by flimamacedo** [comment] 2023-12-08 11:46
> Depending on what exactly you are trying to achieve (i.e whether just one pod needs to resolve it) there might be short term workarounds that you could use till #9201 gets merged in some form.

Yes, to my mind only authservice pod must be able to resolve the FQDN...

**Comment by flimamacedo** [comment] 2023-12-08 11:47
> @flimamacedo I've created a separate issue for resolving Tailscale FQDNs in cluster #10499. I've also added a possible workaround to that issue.

Let me take a look at this. Thanks!

**Closed** 2023-12-08 19:28 UTC
Labels: L1 Very few, P1 Nuisance, T5 Usability, bug
