### ISSUE TITLE
FR: GUI for the client version of Linux

### ISSUE THREAD

**Issue by DrenMaisey** [tailscale/tailscale#6136] opened 2022-10-30 20:07 UTC
### What are you trying to do?

I would like to mange tailscale with a GUI in linux

### How should we solve this?

With a GUI

### What is the impact of not solving this?

CLI is good but tailscale is not used only in a server or in a headless rasp. pi. It's used also in a Ubuntu laptop that deserve a gui with a try icon as in windows or mac.

### Anything else?

No, TY

**Comment by DentonGentry** [comment] 2022-10-30 21:35
Duplicate of https://github.com/tailscale/tailscale/issues/1708
(which also links to a number of UI widgets which users have developed for different Linux desktop environments)

**Closed by DentonGentry** 2022-10-30 21:35 UTC
Labels: needs-triage, fr
