### ISSUE TITLE
Tailscale 1.36.0 (Mac App Store) on Ventura will not log in .

### ISSUE THREAD

**Issue by rscorer** [tailscale/tailscale#7135] opened 2023-01-31 23:14 UTC
### What is the issue?

I just upgraded to Tailscale 1.36.0 via the App Store on Ventura, and now it will not log in .

```
$  ~ /Applications/Tailscale.app/Contents/MacOS/Tailscale debug ts2021 --verbose
23:10:20.062413 HTTP proxy env: (none)
23:10:20.062679 tshttpproxy.ProxyFromEnvironment = (<nil>, <nil>)
23:10:20.062696 Fetching keys from https://controlplane.tailscale.com/key?v=56 ...
23:10:20.179700 got public key: mkey:7d2792f9c98d753d2042471536801949104c247f95eac770f8fb321595e2173b
23:10:20.181090 Dial("tcp", "[2a05:d014:386:203:4535:c15c:9ab:8258]:80") ...
23:10:20.201375 Dial("tcp", "[2a05:d014:386:203:4535:c15c:9ab:8258]:80") = [2606:4700:110:82ef:7a13:8811:7c82:efaf]:60894 / [2a05:d014:386:203:4535:c15c:9ab:8258]:80
23:10:20.242376 controlhttp.Dial = 0xc000298030, <nil>
23:10:20.242389 did noise handshake
23:10:20.242395 final underlying conn: [2606:4700:110:82ef:7a13:8811:7c82:efaf]:60894 / [2a05:d014:386:203:4535:c15c:9ab:8258]:80
```

### Steps to reproduce

Upgrade to Mac OS Ventura, Upgrade to Tailscale 1.36.0

1.34.2 was working earlier today, after the update to 1.36.0 it failed to connect.

### Are there any recent changes that introduced the issue?

Upgrading to Tailscale 1.36.0 was the only change I made.

### OS

macOS

### OS version

Ventura 13.2 (22D49

### Tailscale version

1.36.0 (AppStore)

### Bug report

BUG-8b5da49ef7daf0fe0fabcf988be5b959bdb1d05150de73a7d97b165d6fb7ecdf-20230131215638Z-4fd9640562908276

**Comment by mihaip** [comment] 2023-01-31 23:23
It looks like you downgraded to version 1.34 -- is the `debug ts2021` output from 1.34 or 1.36?

**Comment by rscorer** [comment] 2023-01-31 23:32
I haven't downgraded, not sure how to do that from the App Store! I may have run that bug report earlier in the day when I was running 1.34.2 -- sorry.

This bug report is from 1.36.0 

`BUG-8b5da49ef7daf0fe0fabcf988be5b959bdb1d05150de73a7d97b165d6fb7ecdf-20230131233102Z-5c54ef845109e70e
`

**Comment by mihaip** [comment] 2023-01-31 23:43
My apologies, I saw a 1.34 log line, but I think that's the server's view of the last client version.

What about the output of `/Applications/Tailscale.app/Contents/MacOS/Tailscale status`?

Are you running any other network extensions or content filtering systems (e.g. Screen Time)?

**Comment by rscorer** [comment] 2023-01-31 23:52
No problem :)

```
$  ~ /Applications/Tailscale.app/Contents/MacOS/Tailscale status
# Health check:
#     - not logged in, last login error=fetch control key: Get "https://controlplane.tailscale.com/key?v=56": failed to resolve "controlplane.tailscale.com": no DNS fallback candidates remain for "controlplane.tailscale.com"

unexpected state: NoState
```

There is no login option in the menu bar.

I am running Screen Time, is that filtering stuff? I can switch it off 

As far as I can remember (it is 11.45pm :) I do not think I am running any other network extensions...

I was running NextDNS a while ago but didn't care for it so that's gone.

I run "CleanMyMac", Docker, and a few brew services... 

```
$  ~ brew services ls
Name              Status  User    File
consul            started richard
dbus              none
dnsmasq           none    root
mariadb           started richard
mongodb-community started richard
nomad             started richard
postgresql@13     none
postgresql@14     started richard
redis             started richard
tor               started richard
unbound           none
vault             started richard
```

**Comment by mihaip** [comment] 2023-02-01 00:50
Does opening https://controlplane.tailscale.com/key?v=56 in a browser show a successful response (`legacyPublicKey` and `publicKey` data) or an error? It still looks like something is preventing Tailscale from reaching the control server.

**Comment by rscorer** [comment] 2023-02-01 09:01
> Does opening https://controlplane.tailscale.com/key?v=56 in a browser show a successful response (`legacyPublicKey` and `publicKey` data) or an error? It still looks like something is preventing Tailscale from reaching the control server.

```
{
	"legacyPublicKey": "mkey:...70",
	"publicKey": "mkey:...3b"
}
```

That is from Safari, while the Tailscale app is still trying to connect.

1.36 works on both iPad and iPhone using same WiFi, so it looks like it has to be my Mac somehow. I switched off "Limit address tracking" and the Mac still can't connect, and "Private Relay" in iCloud+ is also OFF.

I had Ghostery on, but removing that didn't let the Mac connect either.

**Comment by timReynolds** [comment] 2023-02-01 16:51
Downgrading to 1.34.0 presented me with the following system extensions warning on startup;
![Uploading Screenshot 2023-02-01 at 16.48.24.png…]()

After I resolved the issue in System Preferences everything worked as expected.

**Comment by mihaip** [comment] 2023-02-02 17:28
@rscorer: since you're now using TestFlight, you can download older versions using the "View Previous Builds" link. Can you try 1.34.2 to see if that build does indeed work?

Also, you mentioned you had previously been using NextDNS -- do you still have a configuration profile for it still installed?

**Comment by rscorer** [comment] 2023-02-02 18:07
> @rscorer: since you're now using TestFlight, you can download older versions using the "View Previous Builds" link. Can you try 1.34.2 to see if that build does indeed work?
> 
> Also, you mentioned you had previously been using NextDNS -- do you still have a configuration profile for it still installed?

@mihaip Sure, I just installed the `Mac App version 1.34.2` from the Tailscale packages earlier today, and that worked.

After your suggestion I just used TestFlight to install `1.33.369 (App Store)` which was the RC for 1.34 as there was no 1.34.2 version.

This also is working - however there is a _**long**_ pause after hitting login to Tailscale before the browser page is opened -  I have no idea what its doing...  there was also a long pause for the 1.34.2 app earlier today.

For a few moments I tried 1.34.2 from the command line tool, and that refused to connect at all. 

In order to make sure I'm not mixing versions of extensions etc I do a complete uninstall including removing the extension from System Preferences, reading things from the keychain and deleting `~/Library/Containers/io.tailscale.ipn.macos*` and then reboot.

I do not have anything left from NextDNS.

**Comment by DentonGentry** [comment] 2023-02-12 03:14
Possible duplicate of https://github.com/tailscale/tailscale/issues/6706

**Comment by mihaip** [comment] 2023-02-13 16:21
We've released an unstable build (1.37.101) that may help with this. https://tailscale.com/kb/1083/install-unstable/ has the installation instructions, we'd appreciate reports either way (if it helps or if the behavior persists).

**Comment by rscorer** [comment] 2023-02-14 08:47
> We've released an unstable build (1.37.101) that may help with this. https://tailscale.com/kb/1083/install-unstable/ has the installation instructions, we'd appreciate reports either way (if it helps or if the behavior persists).

I tried version 1.37.101

BUG-62c970cc8905e6f7b6744caa061c6b771ac708dd7a83dc0ebfd557dd9d650ba5-20230214083112Z-3ef1a09b418facd0

No luck I'm afraid, so I reinstalled 1.33.369 - that is the most recent version which works for me.

I tried 1.35.4 which also didn't work. I tried that again just now, here's a bug id.

BUG-62c970cc8905e6f7b6744caa061c6b771ac708dd7a83dc0ebfd557dd9d650ba5-20230214084702Z-00054146fc435896

HTH

**Comment by mihaip** [comment] 2023-02-15 18:53
Thanks for trying 1.37.101. With it installed, could you also run `/Applications/Tailscale.app/Contents/MacOS/Tailscale bugreport --diagnose`? That will include additional information in the bug report, including the routing table (it looks like you have Tailscale is for some reason deciding that your DNS requests should be sent over the Tailscale interface instead of your actual Ethernet/Wi-Fi one)

**Comment by rscorer** [comment] 2023-02-15 21:20
> 



> Thanks for trying 1.37.101. With it installed, could you also run `/Applications/Tailscale.app/Contents/MacOS/Tailscale bugreport --diagnose`? That will include additional information in the bug report, including the routing table (it looks like you have Tailscale is for some reason deciding that your DNS requests should be sent over the Tailscale interface instead of your actual Ethernet/Wi-Fi one)

np - I reinstalled 1.37.101 and ran `/Applications/Tailscale.app/Contents/MacOS/Tailscale bugreport --diagnose`

`BUG-62c970cc8905e6f7b6744caa061c6b771ac708dd7a83dc0ebfd557dd9d650ba5-20230215211837Z-a75992f86aade820`

**Comment by mihaip** [comment] 2023-02-16 18:40
Thanks. That's showing that a different VPN interface (`utun0`) is the default route in a lot of cases:

```
21:18:37 | diag: routetable: {Family: IPv4, Dst: 0.0.0.0/5, Interface: utun0, Sys: {GatewayInterface: utun0, GatewayIdx: 15, Flags: [global up {RTF_PRCLONING}]}}
21:18:37 | diag: routetable: {Family: IPv4, Dst: 0.0.0.0/0, Gateway: 192.168.138.1, Interface: en0, Sys: {Flags: [gateway global static up {RTF_PRCLONING}]}}
21:18:37 | diag: routetable: {Family: IPv4, Dst: 0.0.0.0/0, Interface: utun0, Sys: {GatewayInterface: utun0, GatewayIdx: 15, Flags: [global ifscope static up {RTF_CLONING}]}}
```

Do you have any other VPN software enabled? If possible, could you check in the "Network" section of the macOS system report (accessible from the About This Mac window) and see if it reports a service active with the BSD device name being `utun0`? Here's an example of what I see:

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/513813/219457642-3deac4ab-0ef6-4377-8671-c2940725a32e.png">

**Comment by rscorer** [comment] 2023-02-16 20:30
With 1.37.101:

￼

And with a working setup:

￼

I don’t have any VPN services running… 

Would any of these brew services cause a conflict?

> $ brew services ls
> Name          Status  User    File
> dbus          none
> dnsmasq       started root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
> mariadb       started richard ~/Library/LaunchAgents/homebrew.mxcl.mariadb.plist
> ***@***.*** none
> ***@***.*** started richard ***@***.***
> rabbitmq      started richard ~/Library/LaunchAgents/homebrew.mxcl.rabbitmq.plist
> redis         started richard ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
> tor           started richard ~/Library/LaunchAgents/homebrew.mxcl.tor.plist
> unbound       none

**Comment by rscorer** [comment] 2023-03-01 16:52
Tailscale 1.35.4 also doesn't work with Mac OS: 13.3 Beta (22E5230e) so I can't use Tailscale on my Mac any more which saddens me.

```
$ /Applications/Tailscale.app/Contents/MacOS/Tailscale bugreport --diagnose
BUG-62c970cc8905e6f7b6744caa061c6b771ac708dd7a83dc0ebfd557dd9d650ba5-20230301165115Z-13f960c77a3cf1be
```

```
$ /Applications/Tailscale.app/Contents/MacOS/Tailscale debug ts2021 --verbose
16:51:44.386449 HTTP proxy env: (none)
16:51:44.386841 tshttpproxy.ProxyFromEnvironment = (<nil>, <nil>)
16:51:44.386858 Fetching keys from https://controlplane.tailscale.com/key?v=51 ...
16:51:44.526069 got public key: mkey:7d2792f9c98d753d2042471536801949104c247f95eac770f8fb321595e2173b
16:51:44.527797 Dial("tcp", "[2a05:d014:386:202:24dd:46aa:f98e:9997]:80") ...
16:51:44.561809 Dial("tcp", "[2a05:d014:386:202:24dd:46aa:f98e:9997]:80") = [2606:4700:110:82ef:7a13:8811:7c82:efaf]:50224 / [2a05:d014:386:202:24dd:46aa:f98e:9997]:80
16:51:44.601645 controlhttp.Dial = 0xc000014058, <nil>
16:51:44.601656 did noise handshake
16:51:44.601664 final underlying conn: [2606:4700:110:82ef:7a13:8811:7c82:efaf]:50224 / [2a05:d014:386:202:24dd:46aa:f98e:9997]:80
```

```
$ /Applications/Tailscale.app/Contents/MacOS/Tailscale status
# Health check:
#     - not logged in, last login error=fetch control key: Get "https://controlplane.tailscale.com/key?v=51": failed to resolve "controlplane.tailscale.com": no DNS fallback candidates remain for "controlplane.tailscale.com"
#     - This is an unstable (development) version of Tailscale; frequent updates and bugs are likely

unexpected state: NoState
```

**Comment by mihaip** [comment] 2023-03-01 21:27
Can you try disabling Tailscale's DNS settings override in the macOS menu UI and see if that helps?

![image](https://user-images.githubusercontent.com/513813/222268653-4335a6b7-c4d9-423a-9c0b-447e31a30178.png)

**Comment by rscorer** [comment] 2023-03-03 19:45
> Can you try disabling Tailscale's DNS settings override in the macOS menu UI and see if that helps?
> 

It did not help :(

**Comment by rscorer** [comment] 2023-03-04 13:55
> Can you try disabling Tailscale's DNS settings override in the macOS menu UI and see if that helps?
> 

I also tried rebooting with no extensions loaded, and re-installed Tailscale:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/1592698/222906315-afb02d23-aee1-4653-bb22-0cfa203e9b5e.png">

`1.35.4`

BUG-62c970cc8905e6f7b6744caa061c6b771ac708dd7a83dc0ebfd557dd9d650ba5-20230304134818Z-0726620e4792a5a9


`1.37.182`

BUG-62c970cc8905e6f7b6744caa061c6b771ac708dd7a83dc0ebfd557dd9d650ba5-20230304135040Z-a9a6901b650fa91b

**Comment by quartermarsh** [comment] 2023-03-04 21:16
If I may, a possible troubleshooting step here. Install Little Snitch (https://www.obdev.at/products/littlesnitch/index.html) and run it in free trial mode to see what incoming and outgoing connection activity can tell you. Run it in 'Observe' mode while you try other troubleshooting steps. The Network Monitor will show you a live view of connection activity.
Best of luck! 
Oh, one other thing, you might try flushing DNS as well, in case there’s a holdover from running NextDNS. ¯\_(ツ)_/¯

**Comment by rscorer** [comment] 2023-03-05 09:13
> @rscorer If I may, a possible troubleshooting step here. Install Little Snitch 

![image](https://user-images.githubusercontent.com/1592698/222951352-31faba92-7e9e-47a7-9893-4a375cc9b058.png)

@quartermarsh - Amazing! I had forgotten two things.

1. Little Snitch - I think its a great app, I used it years ago and will sign up again now!
2. Cloudflare WARP. The app wasn't running, but WARP was on - apparently that was the culprit.

So my apologies @mihaip - it's been WARP all this time!

**Comment by quartermarsh** [comment] 2023-03-05 10:05
@rscorer OMG that’s good news. 😊

**Comment by mihaip** [comment] 2023-03-06 18:55
@rscorer thanks for confirming. We've recently added some detection code for Cloudflare WARP, so that hopefully the next time this happens we'll have some log data to help track it down.

**Closed by mihaip** 2023-03-06 18:55 UTC
Labels: OS-macos, L1 Very few, P3 Can't get started, T5 Usability, bug
