### ISSUE TITLE
Add the confirmation dialogue on removed of machine from admin console.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2674] opened 2021-08-18 17:55 UTC
When we remove a machine from the dashboard, there is no confirmation. Thinking it would make sense to add an “Are you sure?” confirmation dialogue for actions that affect a node like this. 

This will help users to avoid deletion of node by mistake and get double confirmation before deleting it.

**Comment by DentonGentry** [comment] 2021-10-14 00:26
Duplicate of https://github.com/tailscale/tailscale/issues/2842 (which has more discussion)

**Closed by DentonGentry** 2021-10-14 00:26 UTC
Labels: admin UI, L3 Some users, P2 Aggravating, T2 Visual Polish
