### ISSUE TITLE
tailscale cert doesn't work in docker image

### ISSUE THREAD

**Issue by yidongw** [tailscale/tailscale#5334] opened 2022-08-10 08:13 UTC
### What is the issue?

The same issue has been mentioned in https://github.com/tailscale/tailscale/issues/5072 but it has not been fixed.

I'm opening a new issue trying to get some attention.

**Comment by DentonGentry** [comment] 2022-08-11 12:12
https://github.com/tailscale/tailscale/commit/c6648db3336bfe10b40e7cf75d3a94ad1326fcc7 fixed the identified problem in https://github.com/tailscale/tailscale/issues/5072. I don't doubt there may still be a problem: what does it do? What does it print when it fails? And please include a "tailscale bugreport" from the system where it fails.

**Comment by yidongw** [comment] 2022-08-11 18:52
exactly the same bug that is described in https://github.com/tailscale/tailscale/issues/5072. The author of that issue also commented the problem still exists

**Comment by telometto** [comment] 2022-10-09 14:08
I'm experiencing the exact same issue. For me, the issue is that I'm using TrueNAS, so it creates containers by itself. Passing the command mentioned in https://github.com/tailscale/tailscale/issues/5072#issuecomment-1214334796 inside the running container yields and error. After which, it seems to create the cert, successfully, but the cert doesn't work.

**Comment by DentonGentry** [comment] 2023-02-18 07:36
Duplicate of https://github.com/tailscale/tailscale/issues/5072

**Closed by DentonGentry** 2023-02-18 07:36 UTC
Labels: L2 Few, P2 Aggravating, T5 Usability, waiting-for-info, containers, bug
