### ISSUE TITLE
Exit Node stops working on v1.60.1 on iOS app

### ISSUE THREAD

**Issue by timttran** [tailscale/tailscale#11317] opened 2024-03-01 22:15 UTC
### What is the issue?

I updated both the server and my iPad version to this version 1.60.1, and now Exit Node stops working, internet is not working on iOS unless it’s turned off. And there’s no way to go back to previous iOS versions .  It’s a good thing that I haven’t updated my iPhone to this latest version and so it is still working fine there.

**Comment by kev-out** [comment] 2024-03-03 22:32
I am able to reproduce this issue on my iPhone running Tailscale 1.60.1 for me it seems be occurring in a specific case :
I have Tailscale DNS disabled and I am using a exit node 

When trying to browse to any site I get “Safari can’t open the page because your iPhone isn’t connected to the internet” 
However typing in an IP directly does seem to work okey

**Comment by kelivel** [comment] 2024-03-04 17:08
@timttran Can you generate a bugreport when your exit node stops working and paste that bug marker here? That will let us take a look at what your iPad is trying to do when the connection fails.

@kev-out Your report sounds like https://github.com/tailscale/tailscale/issues/9728 where MagicDNS must be enabled to use an exit node. MagicDNS is disabled when Tailscale DNS is disabled on the app.

**Comment by timttran** [comment] 2024-03-04 17:24
Hi,

Here’s the bug report
Hope you can kill the bug soon 😊

BUG-d4e74b320137dc6bb61eaf0c669f03343f2456caad31dd7d5d211add0270e2c2-20240304172117Z-dcee4b81b076321c

Sent from my iPad

On Mar 4, 2024, at 9:08 AM, Keli ***@***.***> wrote:

﻿

@timttran<https://github.com/timttran> Can you generate a bugreport when your exit node stops working and paste that bug marker here? That will let us take a look at what your iPad is trying to do when the connection fails.

@kev-out<https://github.com/kev-out> Your report sounds like #9728<https://github.com/tailscale/tailscale/issues/9728> where MagicDNS must be enabled to use an exit node. MagicDNS is disabled when Tailscale DNS is disabled on the app.

**Comment by agottardo** [comment] 2024-03-04 17:46
> I am able to reproduce this issue on my iPhone running Tailscale 1.60.1 for me it seems be occurring in a specific case : I have Tailscale DNS disabled and I am using a exit node
> 
> When trying to browse to any site I get “Safari can’t open the page because your iPhone isn’t connected to the internet” However typing in an IP directly does seem to work okey

@kev-out can you share a bug report ID from your device?

**Comment by kev-out** [comment] 2024-03-04 22:20
> @kev-out can you share a bug report ID from your device?

BUG-c78f9d833d2708dae986924c22c5626b7e8a241f97628d58bd28b32d52c05966-20240304221914Z-d4e331f51511d32e

**Comment by BusyJay** [comment] 2024-03-05 08:12
> Your report sounds like https://github.com/tailscale/tailscale/issues/9728 where MagicDNS must be enabled to use an exit node. MagicDNS is disabled when Tailscale DNS is disabled on the app.

I run into the similar situation as kev-out's. Usually I connect to tailscale without MagicDNS and Exit Node to connect to my homelab only. The reason why I disable MagicDNS is because it will slow down APPs that have a lot of images on my iPhone sometimes. If ExitNode has to be used with MagicDNS, it's better enable MagicDNS automatically when Exit Node is enabled.

**Comment by agottardo** [comment] 2024-03-05 21:45
@timttran @kev-out can you folks try [the latest TestFlight build](https://testflight.apple.com/join/tLcYLZJV) (v1.61.71)? We made a change last night that might address this.

**Comment by kev-out** [comment] 2024-03-12 21:09
Hi apologies in responding @agottardo 
Still no good in this version 

BUG-c78f9d833d2708dae986924c22c5626b7e8a241f97628d58bd28b32d52c05966-20240312210904Z-a9127f8f387afcc1

**Comment by kev-out** [comment] 2024-07-03 08:47
@timttran it seems that this issue has been fixed on me on the latest build - can you check if it's all working now from your side?

**Comment by timttran** [comment] 2024-07-03 19:56
Yes it’s been working great. The only exception I see is that it drains too much battery if I forget to turn it off at night

Keep up the his work!

On Jul 3, 2024, at 3:47 AM, Kevin Deamandel ***@***.***> wrote:

﻿

@timttran<https://github.com/timttran> it seems that this issue has been fixed on me on the latest build - can you check if it's all working now from your side?

**Closed** 2024-07-03 20:18 UTC
Labels: OS-ios, L2 Few, P2 Aggravating, T5 Usability, bug
