### ISSUE TITLE
FR: Allow funnel to proxy web apps

### ISSUE THREAD

**Issue by Milo123459** [tailscale/tailscale#6935] opened 2023-01-11 00:34 UTC
### What are you trying to do?

I have a web app running on a port locally, and after enabling funnel I noticed that it errored out due to the mime type being set to `text/plain`, meaning the CSS couldn't load.

### How should we solve this?

Allow users to proxy a port and add it to tailscale funnel.

### What is the impact of not solving this?

It drastically reduces the use cases of TS funnel.

**Comment by DentonGentry** [comment] 2023-01-11 04:09
> noticed that it errored out due to the mime type being set to text/plain

I don't understand what this means: funnel isn't even aware of what is transiting through the SSL connection, the funnel endpoint passes the encrypted data all the way through to your node. Funnel doesn't know what the mime-type is.

Can you detail what error was seen, like any error messages?

**Comment by Milo123459** [comment] 2023-01-11 07:33
<img width="612" alt="image" src="https://user-images.githubusercontent.com/50248166/211744929-a29e3443-e046-4021-a741-3f537ee82f04.png">

**Comment by Milo123459** [comment] 2023-01-11 21:02
Proxying the web server to `/` works. It's because the page is trying to access <tailnetlink.ts.net>/api when it should be <tailnetlink.ts.net>/sn1/api.

**Comment by DentonGentry** [comment] 2023-02-11 17:46
I don't see how funnel would be expected to add an extra component to the path like `sn1`. It is sending the connection through to the tailnet device. It does not modify the URL Path along the way. It does not change the MIM-type to `text/plain`

**Comment by Milo123459** [comment] 2023-02-11 18:23
If I proxy port 3000 to /sn1, and serve with funnel, then go to tailneturl/sn1/hello, the web server receives /sn1/hello, when it should only receive /hello

**Comment by DentonGentry** [comment] 2023-02-18 22:59
Duplicate of https://github.com/tailscale/tailscale/issues/6571

**Closed by DentonGentry** 2023-02-18 22:59 UTC
Labels: L1 Very few, P3 Can't get started, T5 Usability, waiting-for-info, fr, pending, funnel
