### ISSUE TITLE
FR: Get a device sharing link via API

### ISSUE THREAD

**Issue by kiweezi** [tailscale/tailscale#7466] opened 2023-03-05 18:55 UTC
### What are you trying to do?

I host game server instances and provide private access to them via sharing in Tailscale. I would like to automate this process. Currently there is no way I am aware of to do this through scripting.

### How should we solve this?

Modify the API to get and or create device sharing links.

An idea could be implimented where sharing links are created upon joining a device to the tailnet and rotated automatically (if that's even needed), therefore they always exist as an attribute of the device. Then when using the `get a device` endpoint, you could grab this link.
This could mean minimal changes to the API, but at a cost of modifying core functionality of Tailscale.

### What is the impact of not solving this?

I can continue manually creating and sharing the link. Time consuming but not the end of the world!

I've also thought that I could directly authenticate the node to the owner's Tailnet and move the sharing responsiblility onto them. It's not ideal as this would turn the device into more of a pet, so will likely go with the first option for now.

### Anything else?

Tailscale is truly a pleasure to work with both inside and outside of my job. Keep up the great work, I really appreciate it!

I understand device sharing is in beta, but saw that ssh is too and has some cli flags to work with, so I thought it was worth asking.

**Comment by DentonGentry** [comment] 2023-03-05 18:56
Duplicate of https://github.com/tailscale/tailscale/issues/5154

**Closed by DentonGentry** 2023-03-05 18:56 UTC
Labels: needs-triage, fr
