### ISSUE TITLE
FR: Timeslots on special ACL

### ISSUE THREAD

**Issue by noerdar** [tailscale/tailscale#8706] opened 2023-07-25 13:14 UTC
### What are you trying to do?

I want to be able to only allow access to some services on specific times. Like make a group that only have access to some servers between 10:00 and 12:00 for example.

### How should we solve this?

Maybe add this feature inside the ACL Policy

### What is the impact of not solving this?

None, just a nice feature

**Comment by DentonGentry** [comment] 2023-07-25 13:42
Duplicate of https://github.com/tailscale/tailscale/issues/1023

--------

There are a number of integrations which can provide this functionality now, for Tailscale users who use these services:

[Tailscale for DevOps: On-demand access to your Tailscale resources with Indent](https://tailscale.com/blog/indent/)
[Tailscale for DevOps: On-demand access to your Tailscale resources with ConductorOne](https://tailscale.com/blog/conductorone/)
[Tailscale for DevOps: On-demand access to your Tailscale resources with Sym](https://tailscale.com/blog/sym/)
[Tailscale for DevOps: On-demand access to your Tailscale resources with Opal](https://tailscale.com/blog/opal/)

**Closed by DentonGentry** 2023-07-25 13:42 UTC
Labels: needs-triage, fr
