### ISSUE TITLE
FR: Read-Only API Keys

### ISSUE THREAD

**Issue by quickchase** [tailscale/tailscale#5064] opened 2022-07-15 17:51 UTC
### What are you trying to do?

I would like if our users could generate read-only API keys so we can query the API for information without giving away more access than is required.

Currently, `Auditors` can't even create API keys, and nether `IT Admin` nor `Network Admin` can read `/api/v2/tailnet/domain/devices`

We have to give someone full blown `Admin` to be able to query device API

### How should we solve this?

Allow us to create Read-Only API keys, or grant Auditors the right to generate keys and read data from their key.

### What is the impact of not solving this?

Granting API read access to devices requires granting way more privileges than necessary.

**Comment by DentonGentry** [comment] 2022-07-15 19:13
We have a team of engineers working on API keys now, and I expect a ReadOnly attribute to be one result.

We may not hook up the plumbing for an Auditor User to be able to issue their own ReadOnly key as part of the initial deliverable, but that would not be very difficult to do in a subsequent delivery.

**Comment by kevinbringard** [comment] 2022-09-12 14:48
Forgive me for piggy-backing on this issue rather than creating a new one, but this felt related. As part of the API keys work, it would also be useful if we could create "service" account API keys which aren't tied to a specific user for use in things like CI/CD pipelines. So a specific user would create it, but it would be part of the larger organization as opposed to tied to that user (and most specifically, if that user was no longer part of the organization the key would not be impacted). This would assuredly require admin user(s) manage these keys, but the scope would be "unbound from"/"defined outside of" the user who actually created the key.

**Comment by DentonGentry** [comment] 2022-09-13 12:14
Duplicate of https://github.com/tailscale/tailscale/issues/3418

**Closed by DentonGentry** 2022-09-13 12:14 UTC
Labels: L2 Few, P1 Nuisance, T0 New feature, api, fr
