### ISSUE TITLE
FR: API for sharing a machine

### ISSUE THREAD

**Issue by StepBroBD** [tailscale/tailscale#6453] opened 2022-11-22 23:22 UTC
### What are you trying to do?

Share a machine based on a HTTP POST request, given machine ID and a list of email addresses.

### How should we solve this?

Add appropriate endpoint to allow users to share device with multiple users, please see example below.

### What is the impact of not solving this?

Have to manually share nodes and repeat multiple times for different users.

### Anything else?

Example:

To share a device to 3 other users,

```shell
curl 'https://api.tailscale.com/api/<API Version>/device/<Device ID>/share' \
-u '<API Key>' \
--data-binary '{"email": ["1@example.com", "2@example.com", "3@example.com"]}'
```

**Comment by jjhiggins** [comment] 2022-12-11 00:00
Without this feature the temptation is to use Headscale, create a tailnet and then use the Headscale API to add users to that tailnet so my application can send out invitation links automatically.

Obviously this is inferior to the way Tailscale can share machines between tailnets, but I also worry this would also dissuade people from using the Tailscale SaaS service since they already have their Tailscale client configured to talk to a Headscale server.

**Comment by nesl9** [comment] 2022-12-20 16:31
Does your issue also require sharing with users outside of your network? 

There are (at least) two related issues:
#5154
#5263

**Comment by DentonGentry** [comment] 2023-02-18 00:47
Duplicate of https://github.com/tailscale/tailscale/issues/5154

**Closed by DentonGentry** 2023-02-18 00:47 UTC
Labels: L1 Very few, P2 Aggravating, T0 New feature, api, fr
