### ISSUE TITLE
Local DNS server no longer works when using exit node on macOS

### ISSUE THREAD

**Issue by jeremycole** [tailscale/tailscale#3991] opened 2022-02-21 01:18 UTC
### What is the issue?

I have a local DNS server at 10.0.1.2 which should normally be used. I sometimes use an exit node (in Google Cloud), but for performance reasons I still want to use my local DNS server even when using the exit node. With the last update or so I did, the new "Use Tailscale DNS settings" seems to have been introduced, and I assume it is likely related.

This all used to work...

### Steps to reproduce

1. Connect to a tailnet on macOS
2. Select an exit node
3. Enable "Exit node" -> "Allow local network access"
4. Disable "Preferences" -> "Use Tailscale DNS settings"
5. Run "host google.com" and observe it times out.

### Are there any recent changes that introduced the issue?

I believe this was introduced with the most recent macOS updates related to DNS. It used to work as expected so long as "Allow local network access" was enabled.

### OS

macOS

### OS version

12.2.1

### Tailscale version

1.20.4

### Bug report

BUG-ec8c28ba5e408ad981275ae9377921062f115b9a20b415a89bc061938feec1f3-20220221011749Z-a8897316c714f2ef (this is from a non-macOS node, not sure if there's a mac equivalent)

**Comment by bradfitz** [comment] 2022-02-21 15:58
Our intention with Exit Nodes was always that using an exit node is as if you're using the internet from that point. The fact that DNS still happened from your local machine previously was something we always considered a bug and we, uh, "fixed the glitch" in 1.20.0. Because otherwise you get weird results on the web: geolocation gets split between your DNS queries & your IP packets, and sites behave inconsistently.

Argubably we should gray out/disable the "Use Tailscale DNS settings" entirely when you're using an Exit Node. We need to discuss that.

What are you actually trying to accomplish with an Exit Node? It sounds like you might be using it as a means to a different end? Perhaps there's something else you want instead?

**Comment by jeremycole** [comment] 2022-02-21 22:03
It' good to hear at least that I am not imagining that this used to work and doesn't anymore. Sometimes, I wonder.

> What are you actually trying to accomplish with an Exit Node? It sounds like you might be using it as a means to a different end? Perhaps there's something else you want instead?

Probably so, and it's okay if the answer is that I'm doing something weird and should maybe figure something else out or live with it.

I have extremely limited choice of ISPs at home, just two WISPs and nothing wired. I have two connections active-active load-balanced, and one of them is fairly hostile, and blocks SSH, DNS, ICMP, etc. I have been using an exit node in GCP (and previously an OpenVPN connection through PrivateTunnel) to tunnel my work and nerdy-personal traffic past this hostility to the real internet. Works great.

However since the connections are also fairly bad (25/5 and 25/15, both sometimes overloaded), and slightly worse through a VPN, resolving DNS through it is quite slow. So I run a local DNS server (which also happens to be using tailscale with an exit node for its DNS resolution traffic due to the same hostility). Using the local DNS server makes things feel much snappier than not. (This is actually how I noticed my DNS configuration started being changed when enabling an exit node, things felt super sluggish.)

How do I want it to work is basically to literally just use the VPN to tunnel my traffic through the exit node. My local LAN is not hostile, but the network between me and the internet is. This is probably not such a common scenario.

**Comment by DentonGentry** [comment] 2022-02-21 22:48
Do you use MagicDNS? (hostnames of the form host.example.com.beta.tailscale.net)

If not, you might consider turning Tailscale's DNS configuration off altogether and setting your hosts to use 10.0.1.2 in their local configuration. Tailscale won't redirect those packets to the exit node.

**Comment by hendryque** [comment] 2022-02-22 14:40
> If not, you might consider turning Tailscale's DNS configuration off altogether and setting your hosts to use 10.0.1.2 in their local configuration.

How can I set a Mac host to use a local DNS? I tried to set it in my Wifi configuration but that won't work.
Honestly, those new DNS settings in Tailscale are a catastrophe. I cannot tell when a specific DNS will be used or not. And after I got that working, this is silently changed after a tailscale update (and the local installation wll use 100.100.100.100 again which will NOT redirect to any of the custom DNS servers I defined). Tailscale is broken for me right now.

**Comment by bradfitz** [comment] 2022-02-22 17:49
@hendryque, it's unclear whether you're having the same issue as @jeremycole. Let's not pile on this bug because it's tangentially related somehow. Feel free to open a new bug specific to your issue (with details!), or if you just want to opine that things are a catastrophe, feel free to use the forum or reddit where we don't track the resolution of fixes.

**Comment by bradfitz** [comment] 2022-02-22 21:49
@jeremycole, I also have multiple ISPs at home and I've long wanted to use both better for both HA and LB reasons. (e.g. latest is https://twitter.com/bradfitz/status/1490911949642940417)

I've put this on our agenda to talk about tomorrow.

But doing fun things with multiple uplinks is on our minds. There are a few other reasons we want to do "multi socket magicsocket", even outside of fun.

I'll keep this open and think about it.

I might be able to provide some debug knob escape to keep your old workflow (https://xkcd.com/1172/) working, but every time we add one of those, there's a risk of it becoming load bearing and needing to support it forever. If possible I'd like to figure out what we want to support first.

The topic for tomorrow is "What does 'Use Tailscale DNS settings?' even mean when an Exit Node is in use?", and what should, could it, etc.

**Comment by jeremycole** [comment] 2022-02-23 01:07
> The topic for tomorrow is "What does 'Use Tailscale DNS settings?' even mean when an Exit Node is in use?", and what should, could it, etc.

Sounds great. If the real answer is that my configuration was not something sane people would want that's fine and I will figure something out, it was mainly surprising that it suddenly stopped working and wasn't clear that was a bug or intended behavior.

**Comment by sbweeden** [comment] 2022-06-10 03:56
> This might be working-as-designed though, because if I ssh to the pihole itself and run nslookup, it doesn't use it's own dns server, it uses the one the pihole is configured to proxy to for addresses that it doesn't override locally. So if the intention is to make name resolution work "as it would from the node you're exiting from", then I guess you could say it is doing that and I should probably use a different machine (not the pihole) on my local network as the exit node. That's a bit of a pain though.

I believe it is working as designed. I addressed the problem by making my PiHole's /etc/resolv.conf have:
```
nameserver 127.0.0.1
```

After that, everything worked as expected when resolving on my local machine even after also configuring the PiHole as the exit node.

**Comment by DentonGentry** [comment] 2023-02-12 23:34
I think the remaining issues on this bug are tracked in https://github.com/tailscale/tailscale/issues/4335, about a feature request to not send DNS queries to the exit node.

Duplicate of https://github.com/tailscale/tailscale/issues/4335

**Closed by DentonGentry** 2023-02-12 23:34 UTC
Labels: OS-macos, L1 Very few, P2 Aggravating, T5 Usability, dns, exit-node, bug
