### ISSUE TITLE
FR: direct access to DNS servers via subnet routers when using an exit node

### ISSUE THREAD

**Issue by jilyaluk** [tailscale/tailscale#4807] opened 2022-06-07 00:36 UTC
### What is the issue?

Let's assume three nodes in tailnet:
* `c1` — regular client node
* `r1` — subnet router, announces 10.0.0.0/8, there is DNS resolver host in that subnet, 10.0.0.1
* `e1` — exit node, does not have direct access to 10.0.0.1, nor is allowed by ACL

The following `tailcfg.DNSConfig` is set:
```go
{
	Resolvers: {{Addr: "1.1.1.1"}},
	Routes: {
		"test.internal.": {{Addr: "10.0.0.1"}},
	},
	Proxied: true,
}
```

If `c1` connects to Tailscale without exit node, internal DNS will work just fine and resources behind `r1` will be accessible. However, when `c1` selects `e1` as an exit node, internal DNS stops working (access to 10.0.0.0/8 is intact and direct queries to 10.0.0.1 work, but client can't resolve any hosts from `test.internal` zone via MagicDNS forwarder).
I tested this behaviour on macOS `c1` (both App Store and compiled versions), but seems that this affects all platforms.

A workaround is to allow udp:53 from `e1` to `10.0.0.1` in ACL, however that's not always desirable, for example if exit nodes are treated as untrusted and should not have any access to internal network.

As far as I understand, that is because in current DNS code all queries are sent over DoH to selected exit node (if selected): [in ipnlocal](https://github.com/tailscale/tailscale/blob/v1.24.2/ipn/ipnlocal/local.go#L2220-L2225), [in tsdial](https://github.com/tailscale/tailscale/blob/v1.24.2/net/tsdial/tsdial.go#L233-L243).

In ipn it's possible to iterate over split DNS configuration, check for any internal or routed IPs in Resolver.Addr and direct these queries directly to nodes. tsdial would probably require passing DNS config to Dialer for resolver selection.
Or, resolver could be configured such as if exit node refuses to answer query due to `ExitNodeFilteredSet`, retry query using regular resolvers, but that would slow down queries for split zones.
If any of that is a fine solution, I could send a PR.

### OS

macOS

### Tailscale version

1.24.2

**Comment by jilyaluk** [comment] 2022-06-07 00:40
Related: #4335

**Comment by DentonGentry** [comment] 2022-06-08 02:37
From what I can see, this is working as intended. A client device using an exit node is intended to "teleport to the location of the exit node" as fully as possible. All egress should be from the exit node and all DNS handling should happen at the location of the exit node (for any Geo IP and/or Anycast behaviors).

**Comment by jilyaluk** [comment] 2022-06-08 10:16
In the described case, zone `test.internal.` is handled by 10.0.0.1, which is intra-Tailscale IP, not egress.

For example, if `c1` tries to open `http://host.test.internal` (10.0.0.2) while `e1` is selected exit node, the DNS query will be sent to `e1`, which will forward it to 10.0.0.1 via `r1`, after that `c1` will directly connect to 10.0.0.2:80 via `r1`.
So, if want to allow `c1` to access `host.test.internal`, we need to create obscure set of ACLs:
* `c1 -> 10.0.0.2:tcp/80`
* `e1 -> 10.0.0.1:udp/53` (if exit node is selected, queries will be originated from `e1`)
* `c1 -> 10.0.0.1:udp/53` (if exit node is not selected, queries will be direct)

**Comment by DentonGentry** [comment] 2022-06-10 03:22
> obscure set of ACLs

Exactly one of those ACLs is related to exit node DNS, and is hardly obscure: `e1 -> 10.0.0.1:53`

**Comment by jilyaluk** [comment] 2022-06-10 09:28
Nonetheless, this is unexpected ACL and not always desirable, as I outlined earlier.

Would it be okay to send a PR implementing this?

**Comment by DentonGentry** [comment] 2023-06-03 15:04
Fundamentally, this intends the same thing as https://github.com/tailscale/tailscale/issues/4335
Duplicate of https://github.com/tailscale/tailscale/issues/4335

**Closed by DentonGentry** 2023-06-03 15:04 UTC
Labels: L1 Very few, P1 Nuisance, T0 New feature, fr, pending
