### ISSUE TITLE
FR: Allow setting debug flag via env var

### ISSUE THREAD

**Issue by jaxxstorm** [tailscale/tailscale#11391] opened 2024-03-11 15:26 UTC
### What are you trying to do?

I'd like to gather prometheus metrics from an operator installed tailscale instance. Currently, it seems the only way to do this is via `--debug`

If we could leverage this via env vars, it would be trivial to support this via the kubernetes operator

### How should we solve this?

The simplest way seems to be just doing a env var lookup here?

https://github.com/tailscale/tailscale/blob/7429e8912acb74a61c7928852a02ceaf3c144e81/cmd/tailscaled/tailscaled.go#L406

### What is the impact of not solving this?

It won't be possible to scrape metrics from Tailscale instances

**Comment by irbekrm** [comment] 2024-03-12 19:23
Duplicate of https://github.com/tailscale/tailscale/issues/11292?

For the proxies, we'll probably want to support this via a new field to the [declarative config](https://github.com/tailscale/tailscale/blob/7429e8912acb74a61c7928852a02ceaf3c144e81/cmd/k8s-operator/sts.go#L648-L683). We should avoid new env vars if we can.

Closing this one in favour of the other metrics issue to keep discussion in one place

**Closed by irbekrm** 2024-03-12 19:23 UTC
Labels: needs-triage, fr
