### ISSUE TITLE
FR: Enforce minimum version in Tailnet

### ISSUE THREAD

**Issue by jdgiddings** [tailscale/tailscale#6542] opened 2022-11-28 17:31 UTC
### What are you trying to do?

Due to the recent CVEs patched in the latest version of Tailscale, I'd like to only allow clients running Windows version greater than 1.32.3, and prevent Windows clients running any older versions from connecting at all. 

Obviously the IT dept can ask/require users to update Tailscale, but some users remain unmotivated

### How should we solve this?

Ideally it would be a dropdown list under https://login.tailscale.com/admin/settings/general

I could also see it being implemented via ACLs

### What is the impact of not solving this?

Clients running older, insecure versions of Tailscale could connect to the Tailnet. This is bad lol

**Comment by DentonGentry** [comment] 2022-11-28 19:55
Substiantially duplicate of https://github.com/tailscale/tailscale/issues/6455, we'll discuss further there.

**Closed by DentonGentry** 2022-11-28 19:55 UTC
Labels: needs-triage, fr
