### ISSUE TITLE
support split domains in api

### ISSUE THREAD

**Issue by kevinschoonover** [tailscale/tailscale#2702] opened 2021-08-24 04:52 UTC
I was looking for a way to programmatically add a split dns record in the [magic dns](https://tailscale.com/kb/1081/magic-dns/) for [consul domains](https://www.consul.io/) `service.consul` via the api. I tried:
+ creating one manually on the admin dns page to reverse engineer what was happening and see its sending a request to a private endpoint (https://login.tailscale.com/admin/api/dns).
+ looking at the [current api documentation](https://github.com/tailscale/tailscale/blob/main/api.md#post-apiv2tailnettailnetdnsnameservers---replaces-the-list-of-dns-nameservers-for-a-tailnet) for the nameservers route (`POST /api/v2/tailnet/:tailnet/dns/nameservers`), but dont see any reference to split DNS

**Comment by matutter** [comment] 2022-01-13 03:16
**+1** Also looking for this API and just like @kevinschoonover also went through reversing the admin UI to access it. Details about my situation below.

Use case:

I would like to automate the deployment of multiple web-services accessed by a reverse proxy on a single machine running tailscale. I would like to access each service on that machine at a different subdomain.

This API is a limiting-factor because:

When I deploy these infra-as-code environments there's a stage that will rely on DNS & specifically split-DNS for that instance of the infrastructure. So currently when I get to that stage the deployment has to stop, I have to find the randomly assigned IP of the proxy-machine, manually configured split-DNS for that machine, then resume the next stage of the deployment.

**Comment by DentonGentry** [comment] 2022-02-06 05:33
Duplicate of https://github.com/tailscale/tailscale/issues/2661

**Closed by DentonGentry** 2022-02-06 05:33 UTC
Labels: L2 Few, P3 Can't get started, T5 Usability, api
