### ISSUE TITLE
iOS client routing through exit node has no DNS

### ISSUE THREAD

**Issue by joeshaw** [tailscale/tailscale#1533] opened 2021-03-17 23:24 UTC
I've set up exit nodes on two Linux machines running 1.6.0.  I'm also running the iOS 1.6.0 build from TestFlight.

One exit node is in my home network and the other is on a DigitalOcean VPS outside of my home network.  My iOS device is in my home network.  I don't have nameservers configured through Tailscale, as I want devices to have DNS servers from their local environment (home network or DO).

When I activate Tailscale on iOS routing through either the VPS or local exit nodes, I can access the network through IP addresses, but DNS doesn't work.

It's not easy to see what the network configuration is when a VPN is activated on iOS, but I have an app installed called "Network Tools" which lets me ping/traceroute/etc. and displays network config.  When Tailscale is activated, it lists no nameservers.  What I'd expect is to continue to have my wifi nameservers.

**Comment by joeshaw** [comment] 2021-03-17 23:33
The IP of the iOS client is 100.102.99.22 and the IPs of the exit nodes are 100.87.131.102 (in my home network) and 100.87.8.88 (my DO box).

At first I thought it was a reachability issue, because my home network DNS server is 192.168.55.5 so I wouldn't expect it to work if I am routing through my DO box (this is a separate issue -- I'd like to be able to override the DNS server just for routing through exit nodes) but it also happens with the exit node in my home network.

**Comment by danderson** [comment] 2021-03-18 00:28
If I'm understanding correctly, you have two different configurations running, both of which break DNS:
 - iOS connected to your LAN (right?), using LAN DNS as its resolver, and DO as its exit node.
 - iOS connected to your LAN, using LAN DNS as its resolver, and home router as its exit node.

Assuming I'm following the topology correctly, I think what you're seeing is a combination of a couple of by-design behaviors that are combining badly.

### iOS to DO

Since you don't override DNS via Tailscale, we leave your resolver settings alone. That means that your phone is still trying to talk to 192.168.55.5, but those packets are flowing to the DO exit node, which then goes "wha?" and drops them. This is "by design", in that we do want to slurp up all traffic when exit nodes are enabled - but when we're not managing the DNS configuration, we need to do something about your resolver settings, and we currently don't.

Two main options:
 - Allow DNS traffic to continue using the local resolver (i.e. "leak" DNS requests from the exit node catchall). We should be able to do a quick fix for that in 1.6.x, but the fully clean solution for that will be in 1.8.
 - When using an exit node, switch the local resolver configuration to use "whatever the exit node is doing for DNS". Unclear exactly how we'd plumb that in from a data plane perspective, but that gives you something closer to a "classic VPN" experience.

### iOS to home

Again, we're leaving iOS's DNS settings alone. Again, requests go to 192.168.55.5 (we route all traffic to the exit node), but this time the exit node drops the traffic because of our "exit node LAN protection" behavior: exit nodes do not allow clients to access the LAN they're sitting on, only the upstream internet connection (think of it as a sort of "guest wifi"). So even though at first glance this should work, the DNS requests are still being dropped, in a different way.

Three options. The first two are the same as the other case. The third:
 - Add a configuration flag on exit nodes to allow access to specific LAN destinations, overriding the default LAN protection. This is something we wanted anyway, and I can get that in fairly easily.

### Workaround

Can you test a workaround for me, to verify that I've got this right? In your tailscale admin panel, can you temporarily set DNS resolvers there to some public DNS service (8.8.8.8, 1.1.1.1, 9.9.9.9, ...) ? If I got the above diagnostic right, your phone should work correctly with both your exit nodes with that DNS configuration. Obviously it's not ideal in that you can't use your private DNS resolver, but it gives you an option while we figure out the next steps above.

**Comment by joeshaw** [comment] 2021-03-18 01:53
@danderson Thanks for going through that, I appreciate the explanation and you got my environment correct.  The workaround you suggested worked (though I hit #1522 testing it, which stumped me for a bit).

> * When using an exit node, switch the local resolver configuration to use "whatever the exit node is doing for DNS". Unclear exactly how we'd plumb that in from a data plane perspective, but that gives you something closer to a "classic VPN" experience.

Could another option be to attach DNS configuration to an exit node and switch the local resolver configuration when using that exit node?  For example, I'd love to keep using my local DNS but attach 8.8.8.8 to my exit nodes and use that instead.  I think that'd be a close analog to "classic VPN" as well.  It seems like this would be a sufficient solution to my case without needing the "split DNS" functionality.

**Comment by danderson** [comment] 2021-03-18 23:43
Attaching resolver configs to exit nodes is an interesting idea, although it adds more implementation work and UX complexity than our other options.

Would you want an exit-node-using client to be using a different DNS server than "whatever the exit node is configured to use" ? Naively to me that seems like a similar setup.

**Comment by joeshaw** [comment] 2021-03-18 23:45
No, using the same resolver would be fine.

**Comment by danderson** [comment] 2021-03-18 23:46
Got it, thanks for the feedback. I'm still thinking on the way forward here, and how to sequence things.

**Comment by DentonGentry** [comment] 2021-07-21 05:12
Another option available in Tailscale 1.10 or later is to set the Tailscale IP addresses of the Digital Ocean and home systems as DNS servers in https://login.tailscale.com/admin/dns

For iOS this did not work in older releases, but in 1.10 it does. A Tailscale IP address is reachable whether the exit node is in use or not. If you disconnect from the Tailnet, the previous set of DNS servers supplied by the ISP will be configured to use instead.

**Comment by joeshaw** [comment] 2021-07-21 16:22
Neat idea, and it works well.  The downside is increased latency of using a DNS server not in my local network (for example: DNS server in home network, exit node in DO, I am in a third location) but it's definitely something I can live with.

**Comment by DentonGentry** [comment] 2021-07-31 05:17
At this point I'll mark this resolved.

**Closed by DentonGentry** 2021-07-31 05:17 UTC
Labels: L1 Very few, P2 Aggravating, T5 Usability, dns, exit-node
