### ISSUE TITLE
FR: iOS app widget

### ISSUE THREAD

**Issue by pinwale** [tailscale/tailscale#5059] opened 2022-07-15 00:00 UTC
### What are you trying to do?

I have to turn on tailscale every so often on my iOS device (“active”) as it occasionally turns off somehow. I haven’t spent any time trying to figure it out as all I need to do is go into the app and tap the toggle button.

But… I always forget that I need to find an app named “tailscale” to do that.

### How should we solve this?

An iOS widget with a toggle would be nice.

### What is the impact of not solving this?

I have to remember that tailscale is the name of the app that controls the VPN settings. Very hard, I know.

**Comment by DentonGentry** [comment] 2022-07-15 02:31
Duplicate of https://github.com/tailscale/tailscale/issues/1935

**Closed by DentonGentry** 2022-07-15 02:31 UTC
Labels: needs-triage, fr
