### ISSUE TITLE
Instead of saying `docker-proxy` in tailscale services, put container name

### ISSUE THREAD

**Issue by Milo123459** [tailscale/tailscale#6906] opened 2023-01-06 23:29 UTC
### What are you trying to do?

In Tailscale services, a docker container is currently picked up as `docker-proxy`. This is quite useless.

### How should we solve this?

It would be cool that instead of saying `docker-proxy`, the type of the service could be `Docker container`, and the name could be the name of the container, or if one is not available the container ID.

### What is the impact of not solving this?

It means that finding out what container is running on each service is quite annoying/hard.

**Comment by DentonGentry** [comment] 2023-01-06 23:50
The services feature is considered Alpha. When it is next iterated on, one of the expected enhancements is better handling of services in containers.
Duplicate of https://github.com/tailscale/tailscale/issues/1361

**Closed by DentonGentry** 2023-01-06 23:50 UTC
Labels: needs-triage, fr
