### ISSUE TITLE
FR: monitor subnet router status

### ISSUE THREAD

**Issue by jaymefSO** [tailscale/tailscale#8231] opened 2023-05-29 17:29 UTC
### What are you trying to do?

It would be nice to have a way to monitor the status of subnet routers and alert if not connected

### How should we solve this?

added monitoring capabilities for machines/subnet routers

### What is the impact of not solving this?

low impact, currently using external monitoring system

**Comment by DentonGentry** [comment] 2023-05-29 18:33
Part of the difficulty we have is the mismatch in what people want versus what the coordination server knows.
- What people want: "notification when a node can no longer be reached by other nodes on the tailnet."
- What the coordination server knows: "whether the node is in contact with the coordination server."

The design of the system is such that the coordination server is not necessary for moment-to-moment operation of the tailnet. There are deployments where devices are out of contact for long periods of time, and nonetheless manage to set up Wireguard tunnels to peers during that entire time.

Closing as a duplicate of https://github.com/tailscale/tailscale/issues/5967

**Closed by DentonGentry** 2023-05-29 18:33 UTC
Labels: needs-triage, fr
