### ISSUE TITLE
FR: iOS on-demand connection

### ISSUE THREAD

**Issue by mvidovicfive** [tailscale/tailscale#4530] opened 2022-04-26 13:49 UTC
### What are you trying to do?

I want on-demand connection similar what wireguard app does. 

Basically when i am on local network (home wifi) i want to disconnect from VPN, and as soon i leave my network i want it to connect to VPN.

### How should we solve this?

Similar how wireguard app is working. You can set on which network it will be deactivated and on which activated. 

### What is the impact of not solving this?

Currently i have to manually connect or disconnect based where i am. I loved using wireguard because of this feature, but Tailscale provide so much more and if it would provide this feature i would call it "one vpn to rule them all" solution. 

### Anything else?

Take a look at this https://tinyurl.com/mukzyjzj how it works in the app

**Comment by DentonGentry** [comment] 2022-04-26 13:50
Duplicate of https://github.com/tailscale/tailscale/issues/1534

**Closed by DentonGentry** 2022-04-26 13:50 UTC
Labels: needs-triage, fr
