### ISSUE TITLE
[MagicDNS] Cannot set ipv6 hostname with port number for global nameservers

### ISSUE THREAD

**Issue by LumaKernel** [tailscale/tailscale#4084] opened 2022-03-07 15:49 UTC
### What is the issue?

There is no way to specify ipv6 DNS server names with port number.
This is UI problem that may be resolvable technically easily.

### Steps to reproduce

- Enable magic DNS
- Go to https://login.tailscale.com/admin/dns
- Click "add nameserver"
- Type ipv6 address with port number
  - Adding `:${port}` does not work. e.g. `2001:db8:::5353` (not good format because of ambiguity)
  - Can't type `[${ipv6}]${port}` like `[2001:db8::]:5353` (`curl` or web browsers' style)
  - Can't type `#${port}` like `2001:db8::#5353` (`dig -b` style?)

### OS

Other

**Comment by DentonGentry** [comment] 2022-03-07 15:54
It isn't specific to IPv6, support for alternate port numbers for DNS has not been implemented yet.

Duplicate of https://github.com/tailscale/tailscale/issues/1666

**Closed by DentonGentry** 2022-03-07 15:54 UTC
Labels: needs-triage, bug
