### ISSUE TITLE
FR: Subnet Router functionality for Apple TV

### ISSUE THREAD

**Issue by gitkohster** [tailscale/tailscale#9496] opened 2023-09-20 21:22 UTC
### What are you trying to do?

It doesn't appear to be possible to set up an Apple TV as a subnet router.  Right now I have a Mac on my network set up to do this, but doing it via the Apple TV would be much more convenient (not to mention power saving and probably more reliable).  Running the Apple TV as an exit node works to a certain extent, but I'd prefer not to send all of my traffic through the Apple TV as a full blown exit node.

### How should we solve this?

Based on my read of the docs, all the other platforms that serve as subnet routers require the CLI to be used.  Since there is no CLI on an Apple TV, some other method of configuring the routes to advertise would need to be implemented.  

### What is the impact of not solving this?

Low impact to not implementing this functionality, since other devices can act as subnet routers.

### Anything else?

I really appreciate all of the work that has gone into Tailscale.  It is a truly useful product/service for all sorts of purposes.

**Comment by adamfeldman** [comment] 2023-09-30 12:51
See also #8929

**Comment by agottardo** [comment] 2023-11-20 19:09
Duplicate of #8929 

As I mentioned there:

> Tailscale 1.55.54 for tvOS has been submitted to TestFlight for review, and will hopefully be available for install shortly. This update includes subnet routing for Apple TV.
> 
> If you experience any issues with this feature, please open a new issue.

**Closed by agottardo** 2023-11-20 19:09 UTC
Labels: needs-triage, fr
