### ISSUE TITLE
macOS - Switching wifi networks kills internet connectivity even when Tailscale reports it's connected

### ISSUE THREAD

**Issue by shorthandguy** [tailscale/tailscale#2413] opened 2021-07-13 15:40 UTC
When using the macOS Tailscale client (1.10.1) and switching between one WiFi network to another (in my particular case, when roaming between a base router and a wifi extender, so it all shares the one network, just has its own IP address range) the Tailscale menu shows that it's connected ("Connected, using exit node"), yet no traffic actually gets through, and the user is left without a working Internet connection.

Not an issue i've experienced with other VPN clients on this same Mac (running macOS Catalina). 

The only way i've found so far to 'fix' it is to disconnect and reconnect. This is highly frustrating for people who jump between wifi networks or use wifi extenders and have their machines roaming between networks. 

What is even stranger, whilst your Internet connectivity is down, a lot of traffic still seems to be going through the xpcproxy process on macOS (that presumably Tailscale uses) (this is a lot higher network activity than before the network connection was switched, so it's not even apparent where the traffic is coming from). See the following screencast..
![Screen Recording 2021-07-14 at 01 33 18 (1)](https://user-images.githubusercontent.com/56828019/125481833-3cf67606-704f-4200-a88f-68d8b21eed61.gif)

**Comment by vysecurity** [comment] 2021-07-27 13:42
I have observed this problem too. Thought Tailscale was exfiltrating something.

**Comment by bradfitz** [comment] 2021-07-27 15:54
This looks like a dup of #1526.

@shorthandguy, is this easily reproducible for you? We would've fixed this sooner but we've never been able to reproduce it ourselves so it's difficult to be confident that our fix is correct. We don't know what macOS is doing.

**Comment by shorthandguy** [comment] 2021-07-27 16:54
> This looks like a dup of #1526.
> 
> @shorthandguy, is this easily reproducible for you? We would've fixed this sooner but we've never been able to reproduce it ourselves so it's difficult to be confident that our fix is correct. We don't know what macOS is doing.

It seems to be happening _less_ frequently now, it's something that was happening daily for me and several times a day (and it may be down to what network my laptop happened to roam onto one day vs. the next), but I _can_ still reproduce it at will (e.g. just reproduced it whilst testing this now by switching between wifi extender #1 -> main router -> wifi extender 2). 

FWIW, my home network is made up of the main router and two wifi extenders (one is DD-WRT, the other is TP-Link).

**Comment by bradfitz** [comment] 2021-07-27 17:00
@shorthandguy, could you capture a tcpdump while reproducing it?

First:

```
$ sudo tcpdump -i all -w tailscale-bug.pcap
```

Then reproduce it, then Control-C the tcpdump, then email that `tailscale-bug.pcap` file to me? (github username at tailscale.com)

**Comment by DentonGentry** [comment] 2023-02-12 17:14
At the time this was filed there was no bugreport mechanism in the app. There is a newer report of similar behavior, which does have bugreports attached. I'm going to close this as a duplicate of the newer bug, which we have more ability to followup on.

Dup of [#6075](https://github.com/tailscale/tailscale/issues/6075)

**Closed by DentonGentry** 2023-02-12 17:14 UTC
Labels: OS-macos, L3 Some users, P2 Aggravating, T6 Major usability
