### ISSUE TITLE
tailscale up fails if the certificate is not yet valid

### ISSUE THREAD

**Issue by Justinzobel** [tailscale/tailscale#9652] opened 2023-10-04 05:33 UTC
### What is the issue?

I had a time/date issue on my local device (that I didn't know about) until I started digging.

I ran tailscale up to connect it to the network but nothing happened, no output, no logs or anything.

I fixed the timezone issue and ran tailscale up and it connected

### Steps to reproduce

Set your time/date outside the certificate for the control plane server and attemmpt to setup the device.

### OS

Linux

### OS version

Alpine Linux Edge

### Tailscale version

1.50.0

### Other software

None.

### Bug report

N/A

**Comment by DentonGentry** [comment] 2023-10-04 05:38
This is the motivation for the feature request in https://github.com/tailscale/tailscale/issues/3152

Duplicate of https://github.com/tailscale/tailscale/issues/3152

**Closed by DentonGentry** 2023-10-04 05:38 UTC
Labels: needs-triage, bug
