### ISSUE TITLE
tsnet: Panic after resuming from suspend to RAM

### ISSUE THREAD

**Issue by Merovius** [tailscale/tailscale#5933] opened 2022-10-13 22:19 UTC
### What is the issue?

I had an experiment using tsnet running when I suspended my laptop and went home. When re-opening it 15m later, I was greeted by a panic in that terminal:

```go
2022/10/13 23:06:07 wgengine: error setting DNS config after major link change: getting OS base config is not supported
2022/10/13 23:06:07 Rebind; defIf="", ips=[]
2022/10/13 23:06:07 magicsock: closing connection to derp-14 (rebind-default-route-change), age 1m51s
2022/10/13 23:06:07 magicsock: 0 active derp conns
2022/10/13 23:06:07 magicsock: adding connection to derp-14 for home-keep-alive
2022/10/13 23:06:07 magicsock: 1 active derp conns: derp-14=cr0s,wr0s
2022/10/13 23:06:07 [v1] v1.32.0-dev20221013-t5f1d8704f-dirty peers: 2068/5916
2022/10/13 23:06:07 derphttp.Client.Recv: connecting to derp-14 (ams)
2022/10/13 23:21:22 netcheck: netcheck: UDP is blocked, trying HTTPS
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x966d58]

goroutine 601 [running]:
tailscale.com/derp/derphttp.(*Client).Close(0xc0008ee000)
	/home/mero/pkg/mod/tailscale.com@v1.32.0/derp/derphttp/derphttp_client.go:988 +0x38
tailscale.com/net/netcheck.(*Client).measureHTTPSLatency(0xc0001b1e00, {0xea3778, 0xc00035a840}, 0x0?)
	/home/mero/pkg/mod/tailscale.com@v1.32.0/net/netcheck/netcheck.go:1195 +0xa7c
tailscale.com/net/netcheck.(*Client).GetReport.func8(0xc0001b3310)
	/home/mero/pkg/mod/tailscale.com@v1.32.0/net/netcheck/netcheck.go:1033 +0x97
created by tailscale.com/net/netcheck.(*Client).GetReport
	/home/mero/pkg/mod/tailscale.com@v1.32.0/net/netcheck/netcheck.go:1031 +0x1c72
```

I'm not sure if this is enough to usefully debug anything, but given that I got the stacktrace, I thought I might as well report it.

<details>
    <summary>Version infos</summary>

```
$ go version
go version go1.19.2 linux/amd64
$ uname -a
Linux hix 5.19.8-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 8 19:02:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Go modules:

```
require (
	filippo.io/edwards25519 v1.0.0-rc.1 // indirect
	github.com/akutz/memconn v0.1.0 // indirect
	github.com/alexbrainman/sspi v0.0.0-20210105120005-909beea2cc74 // indirect
	github.com/aws/aws-sdk-go-v2 v1.11.2 // indirect
	github.com/aws/aws-sdk-go-v2/config v1.11.0 // indirect
	github.com/aws/aws-sdk-go-v2/credentials v1.6.4 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.8.2 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.2 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.0.2 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.3.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.5.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/ssm v1.17.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.6.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.11.1 // indirect
	github.com/aws/smithy-go v1.9.0 // indirect
	github.com/cloudflare/cloudflare-go v0.52.0 // indirect
	github.com/coreos/go-iptables v0.6.0 // indirect
	github.com/fxamacker/cbor/v2 v2.4.0 // indirect
	github.com/go-ole/go-ole v1.2.6 // indirect
	github.com/godbus/dbus/v5 v5.0.6 // indirect
	github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da // indirect
	github.com/google/btree v1.0.1 // indirect
	github.com/google/go-cmp v0.5.8 // indirect
	github.com/google/go-querystring v1.1.0 // indirect
	github.com/google/renameio v1.0.1 // indirect
	github.com/hashicorp/go-cleanhttp v0.5.2 // indirect
	github.com/hashicorp/go-retryablehttp v0.7.1 // indirect
	github.com/hdevalence/ed25519consensus v0.0.0-20220222234857-c00d1f31bab3 // indirect
	github.com/insomniacslk/dhcp v0.0.0-20211209223715-7d93572ebe8e // indirect
	github.com/jmespath/go-jmespath v0.4.0 // indirect
	github.com/josharian/native v1.0.0 // indirect
	github.com/jsimonetti/rtnetlink v1.1.2-0.20220408201609-d380b505068b // indirect
	github.com/klauspost/compress v1.15.4 // indirect
	github.com/kortschak/wol v0.0.0-20200729010619-da482cc4850a // indirect
	github.com/mdlayher/genetlink v1.2.0 // indirect
	github.com/mdlayher/netlink v1.6.0 // indirect
	github.com/mdlayher/sdnotify v1.0.0 // indirect
	github.com/mdlayher/socket v0.2.3 // indirect
	github.com/mitchellh/go-ps v1.0.0 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/tailscale/certstore v0.1.1-0.20220316223106-78d6e1c49d8d // indirect
	github.com/tailscale/golang-x-crypto v0.0.0-20221009170451-62f465106986 // indirect
	github.com/tailscale/goupnp v1.0.1-0.20210804011211-c64d0f06ea05 // indirect
	github.com/tailscale/netlink v1.1.1-0.20211101221916-cabfb018fe85 // indirect
	github.com/tcnksm/go-httpstat v0.2.0 // indirect
	github.com/u-root/uio v0.0.0-20220204230159-dac05f7d2cb4 // indirect
	github.com/vishvananda/netlink v1.1.1-0.20211118161826-650dca95af54 // indirect
	github.com/vishvananda/netns v0.0.0-20211101163701-50045581ed74 // indirect
	github.com/x448/float16 v0.8.4 // indirect
	go4.org/mem v0.0.0-20210711025021-927187094b94 // indirect
	go4.org/netipx v0.0.0-20220725152314-7e7bdc8411bf // indirect
	golang.org/x/crypto v0.0.0-20221012134737-56aed061732a // indirect
	golang.org/x/exp v0.0.0-20220722155223-a9213eeb770e // indirect
	golang.org/x/net v0.0.0-20221002022538-bcab6841153b // indirect
	golang.org/x/sync v0.0.0-20220601150217-0de741cfad7f // indirect
	golang.org/x/sys v0.0.0-20220728004956-3c1f35247d10 // indirect
	golang.org/x/term v0.0.0-20210927222741-03fcf44c2211 // indirect
	golang.org/x/text v0.3.8-0.20211105212822-18b340fc7af2 // indirect
	golang.org/x/time v0.0.0-20220224211638-0e9765cccd65 // indirect
	golang.zx2c4.com/wintun v0.0.0-20211104114900-415007cec224 // indirect
	golang.zx2c4.com/wireguard v0.0.0-20220904105730-b51010ba13f0 // indirect
	golang.zx2c4.com/wireguard/windows v0.5.3 // indirect
	gonih.org/rnd v0.0.0-20220219101358-d0033f7bc410 // indirect
	gvisor.dev/gvisor v0.0.0-20220817001344-846276b3dbc5 // indirect
	nhooyr.io/websocket v1.8.7 // indirect
	tailscale.com v1.32.0 // indirect
)
```

</details>

### Steps to reproduce

I can't seem to reproduce it reliably. Maybe I'd have to wait long enough for TCP connections to time out.

### OS

Linux

### OS version

Fedora 36

### Tailscale version

v1.32.0

### Bug report

BUG-07b5a76c88bc4c3445a5798cfac1b8aa70436fa5c8ba26eb0a38a91ec3bb55e2-20221013221900Z-1427bae2e84bb03c

**Comment by maisem** [comment] 2022-10-13 22:20
Dupe of #5919

**Closed by maisem** 2022-10-13 22:20 UTC
Labels: needs-triage, bug
