### ISSUE TITLE
with resolved set to use unbound on 127.0.0.1, tailscale dns manager sets Nameservers=[]

### ISSUE THREAD

**Issue by nothingmuch** [tailscale/tailscale#8466] opened 2023-06-28 03:06 UTC
### What is the issue?

MagicDNS does not work.

The `resolvectl` nameservers entry for the `tailscale0` interface is empty.

The OScfg values in the logs indicate `Nameservers=[]`, and IIUC tailscale is effectively clearing it. This of course happens repeatedly, so using `resolvectl dns tailscale0 100.100.100.1000` is only a temporary fix.

Before switching to networkd, and IIRC with resolved and split DNS, 100.100.100.100 was configured in resolvectl. I believe I was using network manager throughout, but it took me a few days to notice this issue.

I tried to find the origin of this empty slice, it appears to be coming from saved configuration, but I didn't have enough time to track down why, and with a fresh state file I see the same results.

I'm using the following as a hacky workaround for now:

```diff
diff --git a/net/dns/manager.go b/net/dns/manager.go
index d1aa73ca..9b26f412 100644
--- a/net/dns/manager.go
+++ b/net/dns/manager.go
@@ -227,6 +227,10 @@ func (m *Manager) compileConfig(cfg Config) (rcfg resolver.Config, ocfg OSConfig
 		// Split DNS configuration requested, where all split domains
 		// go to the same resolvers. We can let the OS do it.
 		ocfg.Nameservers = toIPsOnly(cfg.singleResolverSet())
+		if len(ocfg.Nameservers) == 0 {
+			ocfg.Nameservers = []netip.Addr{cfg.serviceIP()}
+			m.logf("FIXME replaced Nameservers=[] with %+v", ocfg.Nameservers)
+		}
 		ocfg.MatchDomains = cfg.matchDomains()
 		return rcfg, ocfg, nil
 	}
```

### Steps to reproduce

This is extracted from my NixOS configuration:

```nix
  services.tailscale.enable = true;
  systemd.services.tailscaled.serviceConfig.Environment =
    [ "TS_NO_LOGS_NO_SUPPORT=true" ];

  # Disable wait online as it's causing trouble during nixos-rebuild switch
  # See: https://github.com/NixOS/nixpkgs/issues/180175
  systemd.services.NetworkManager-wait-online.enable = false;
  systemd.network.wait-online.ignoredInterfaces = [ "tailscale0" ];

  networking.networkmanager = {
    enable = true;
    dns = lib.mkForce "systemd-resolved";
  };

  networking.useNetworkd = true;

  services.resolved.enable = true; # i think this is what breaks tailscale DNS

  # This does not fix it, because it keeps getting cleared:
  systemd.network.networks."tailscale-dns" = {
    matchConfig.Name = "tailscale0";
    dns = [ "100.100.100.100" ]; # tailscale sets this inconsistently
  };

  services.unbound.enable = true;

  systemd.network.networks."wlan-dns" = {
    matchConfig.Name = "wlp3s0";
    dns = [ "127.0.0.1" ]; # this is unbound
    dhcpV4Config.UseDNS = false;
    dhcpV6Config.UseDNS = false;
  };
```

### Are there any recent changes that introduced the issue?

Not that I'm aware of, I switched to resolved because I couldn't get a recursive resolver & mdns working together without it, although it broke MagicDNS that was much easier to work around.

### OS

Linux

### OS version

NixOS unstable

### Tailscale version

1.44.0, and also:, 1.45 (1f57088cbd7ea9c03033c4d4cd0285927e55861f)

**Comment by DentonGentry** [comment] 2023-10-16 00:08
Duplicate of https://github.com/tailscale/tailscale/issues/8468

**Closed by DentonGentry** 2023-10-16 00:08 UTC
Labels: L1 Very few, P2 Aggravating, T5 Usability, dns, bug
