### ISSUE TITLE
Cannot send files between tagged devices.

### ISSUE THREAD

**Issue by cesaryuan** [tailscale/tailscale#12494] opened 2024-06-16 07:32 UTC
### What is the issue?

Tagging deivces will make Send Files not work anymore.

### Steps to reproduce

1. Tag devices 1 and 2
2. Right-click on the file  and choose Send with tailscale.
3. We can see there are no devices on the right panel.
4. Untag device 1 and 2 by re-login.
5. The devices appear.
![image](https://github.com/tailscale/tailscale/assets/35998162/5dab772a-acef-4a6c-af1b-1b423fca93ec)

PS: The acl I use is as following:
```
	"tagOwners": {
		"tag:server": ["autogroup:admin"],
		"tag:mine":   ["autogroup:admin"],
	},
	// Define access control lists for users, groups, autogroups, tags,
	// Tailscale IP addresses, and subnet ranges.
	"acls": [
		// Allow all connections.
		// Comment this section out if you want to define specific restrictions.
		{
			"action": "accept",
			"src": [
				"*",
			],
			"dst": [
				"*:*",
			],
		},
	],
```

### OS

Windows

### OS version

Windows 11 23H2

### Tailscale version

Version 1.68.1 (tf02ad8397-g8f9cb4763)

### Bug report

BUG-d43a2be8563ea8abe0ca2df1da83d56e14d7d4ed25a7df72e40819d6861ede9b-20240616073143Z-1bd20bdf20621534

**Comment by shladek** [comment] 2024-06-17 01:48
This is expected behavior with Taildrop. 

Taildrop permits you to share files between devices that you are logged in to, even if ACLs are used to restrict access to the devices. **_You cannot use Taildrop to send files to and from nodes you have tagged._**

[Source](https://tailscale.com/kb/1106/taildrop#send-files-with-taildrop):

**Comment by cesaryuan** [comment] 2024-06-17 01:52
> You cannot use Taildrop to send files to and from nodes you have tagged.

Understood. So why did we add this restriction.

**Comment by bradfitz** [comment] 2024-06-17 04:01
Marking this as a duplicate of #10695.

Some work was underway on supporting this recently, though.

**Closed by bradfitz** 2024-06-17 04:01 UTC
Labels: needs-triage, bug
