### ISSUE TITLE
Subnet router on Apple TV

### ISSUE THREAD

**Issue by m9ac** [tailscale/tailscale#9918] opened 2023-10-23 07:53 UTC
Please, oh Please, oh Please, let there be a subnet router in the works on Apple TV. Tailscale keeps getting better and better. This is a feature that NEEDS to be! Thanks for all the hard work.

**Comment by bradfitz** [comment] 2023-10-23 13:12
Yes, we all want it too. Cc @agottardo

**Comment by agottardo** [comment] 2023-11-26 23:20
Duplicate of #8929

**Closed by agottardo** 2023-11-26 23:20 UTC
