### ISSUE TITLE
FR: auto start feature for Android Tv

### ISSUE THREAD

**Issue by itsmerickysoy** [tailscale/tailscale#12937] opened 2024-07-28 13:29 UTC
### What are you trying to do?

I am using mi box as tv box for my OnePlus TV.
Fortunately mi box is allowing me to run tailscale for my connection with jellyfin.
However unlike phone or laptop, there is no automatic startup for the app in TV or mi box.

### How should we solve this?

If you can make tailscale run automatically in the background as soon as I turn on the tv it will be a great advantage 

### What is the impact of not solving this?

Probably try looking for something better like emby or twin gate

**Comment by agottardo** [comment] 2024-07-29 02:27
Duplicate of https://github.com/tailscale/tailscale/issues/7824

**Closed by agottardo** 2024-07-29 02:27 UTC
Labels: needs-triage, fr
