### ISSUE TITLE
Crash when exposing kubernetes service using annotations

### ISSUE THREAD

**Issue by kzh** [tailscale/tailscale#14257] opened 2024-12-01 23:06 UTC
### What is the issue?

I'm running the latest operator helm chart `v1.76.6` and have been bumping into a `CrashLoopBackoff` whenever I try to expose a service with annotations `tailscale.com/expose: "true"`. It appears that to expose these services, the operator spawns pods with tailscale running in kernel mode. I'm unsure if this is the cause for the crash. It's possible that the pod is missing some container configuration needed for kernel mode to work like privileges.

Exposing via ingress works fine. These pods have tailscale running using user mode.
```
boot: 2024/11/30 10:35:12 skipping file "..data" in tailscaled config directory "/etc/tsconfig": input does not match format
boot: 2024/11/30 10:35:12 skipping file "_current-profile" in tailscaled config directory "/etc/tsconfig": input does not match format
boot: 2024/11/30 10:35:12 skipping file "_machinekey" in tailscaled config directory "/etc/tsconfig": input does not match format
boot: 2024/11/30 10:35:12 skipping file "_profiles" in tailscaled config directory "/etc/tsconfig": input does not match format
boot: 2024/11/30 10:35:12 skipping file "device_fqdn" in tailscaled config directory "/etc/tsconfig": input does not match format
boot: 2024/11/30 10:35:12 skipping file "device_id" in tailscaled config directory "/etc/tsconfig": input does not match format
boot: 2024/11/30 10:35:12 skipping file "device_ips" in tailscaled config directory "/etc/tsconfig": input does not match format
boot: 2024/11/30 10:35:12 skipping file "profile-8f85" in tailscaled config directory "/etc/tsconfig": input does not match format
boot: 2024/11/30 10:35:12 Using tailscaled config file '_' for capability version 'j'
boot: 2024/11/30 10:35:12 Starting tailscaled
boot: 2024/11/30 10:35:12 Waiting for tailscaled socket
2024/11/30 10:35:12 logtail started
2024/11/30 10:35:12 Program starting: v1.76.6-t1edcf9d46, Go 1.23.1: []string{"tailscaled", "--socket=/tmp/tailscaled.sock", "--state=kube:ts-rook-ceph-rgw-objectstore-vr22z-0", "--statedir=/tmp", "--config=/etc/tsconfig/cap-95.hujson"}
2024/11/30 10:35:12 LogID: 6b2a3afd3692c696b1789405f478b421c705f59fe0f39e6165ef39994c18242d
2024/11/30 10:35:12 logpolicy: using system state directory "/var/lib/tailscale"
logpolicy.ConfigFromFile /var/lib/tailscale/tailscaled.log.conf: open /var/lib/tailscale/tailscaled.log.conf: no such file or directory
logpolicy.Config.Validate for /var/lib/tailscale/tailscaled.log.conf: config is nil
2024/11/30 10:35:12 dns: [rc=unknown ret=direct]
2024/11/30 10:35:12 dns: using "direct" mode
2024/11/30 10:35:12 dns: using *dns.directManager
2024/11/30 10:35:12 dns: inotify new: too many open files
2024/11/30 10:35:12 wgengine.NewUserspaceEngine(tun "tailscale0") ...
2024/11/30 10:35:12 Linux kernel version: 6.8.0-49-generic
2024/11/30 10:35:12 is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: can't change directory to '/lib/modules': No such file or directory
2024/11/30 10:35:12 wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): operation not permitted
2024/11/30 10:35:12 flushing log.
2024/11/30 10:35:12 logger closing down
2024/11/30 10:35:12 getLocalBackend error: createEngine: tstun.New("tailscale0"): operation not permitted
boot: 2024/11/30 10:36:12 Timed out waiting for tailscaled socket
```

### Steps to reproduce

I installed the operator and then annotated a service with `tailscale.com/expose: "true"`. The tailscale pod spawned by the operator crashed with the above logs.

### OS

Linux

### OS version

Ubuntu 24.04

### Tailscale version

v1.76.6

**Comment by kzh** [comment] 2024-12-02 02:02
The root cause seems to be same as #14256 being a change in the latest version of containerd.

**Comment by irbekrm** [comment] 2024-12-02 13:49
Thank you for opening the issue @kzh as you say this seems to be a duplicate of https://github.com/tailscale/tailscale/issues/14256 so closing this to keep discussion in one place

**Closed by irbekrm** 2024-12-02 13:49 UTC
Labels: kubernetes, needs-triage, bug
