### ISSUE TITLE
deactivating Tailscale network adapter results in more and more Tailscale interfaces in Windows Control Panel

### ISSUE THREAD

**Issue by chrisbley** [tailscale/tailscale#3834] opened 2022-01-28 10:49 UTC
### What is the issue?

When deactivating Tailscale network adapter in Windows Control Panel, the adapter will be removed. When clicking "connect" on the Tailscale client, the client behaves as if it's connected but there's no internet connection. Reinstalling the Client will get things back to normal.
(I need to deactivate Tailscale as it's interfering with my Dante Virtual Soundcard, which I'm using for pro-audio device testing and documentation. Dante Virtual Soundcard doesn't work at all while Tailscale adapter is active, saying "a non Dante device is on the same subnet" (169.254.x.x))

![image](https://user-images.githubusercontent.com/97885880/151532479-1bd63cc9-3271-49bc-9234-271d951e7412.png)

### Steps to reproduce

right-click on Tailscale adapter in Control Panel / network adapters, "deactivate"
![image](https://user-images.githubusercontent.com/97885880/151532479-1bd63cc9-3271-49bc-9234-271d951e7412.png)

Tailscale adapter has disappeared, error message "the connection couldn't be deactivated. possibly the connection is using protocols that don't support plug&play, or the connection was initialized by another user or the system account"
![image](https://user-images.githubusercontent.com/97885880/151532748-67ab4b04-14e0-495f-be3e-b11e70a5b53c.png)

### Are there any recent changes that introduced the issue?

no, just started using Tailscale this week.

### OS

Windows

### OS version

Win 10 21H2

### Tailscale version

1.20.2

### Bug report

BUG-e32e430c6e79d08cb08abc7e80bac8e83a2b6395f6ef4bb42cf0d85da9556eec-20220128104901Z-09440fd30b55c02f

**Comment by jepeneter** [comment] 2022-07-28 22:01
I am seeing this exact same behavior on 1.28.0 as well.

**Comment by marshy919** [comment] 2023-06-05 13:04
I'm having this issue too.
Wanted to disable Tailscale to see if it fixed my networking issues - which it did.
Went back to the device manager to re-enable the driver - and it no longer existed.
Checked via control panel - not there either.
Reinstalled 1.42.0 - still no there and Tailscale obviously not working. 
Just want to change the network metric to something other than automatic, as it's taking over Windows.

**Comment by SiwyBoy** [comment] 2023-07-11 06:22
I experienced the same problem on my Win10 machine. When troubleshooting some other network issues, I deactivated the Tailscale NIC, and it disappeared... 
I tried to reinstall Tailscale with the newest 1.44 installer, but the NIC does not seem to appear again. The app seems to be active and connected, but it's not possible to ping or connect to any of the hosts.

**Comment by pikeai** [comment] 2023-08-10 06:14
> I experienced the same problem on my Win10 machine. When troubleshooting some other network issues, I deactivated the Tailscale NIC, and it disappeared... I tried to reinstall Tailscale with the newest 1.44 installer, but the NIC does not seem to appear again. The app seems to be active and connected, but it's not possible to ping or connect to any of the hosts.

my adapter reappear after i restart Tailscale service

**Comment by kahao84** [comment] 2023-08-30 11:56
disable Tailscale adaptor and adaptor lost still show in v1.48.1, 
restart services no adaptor show,
reinstall tailscale not works, show error **The version of Tailscale is already installed**, 
have to go Program & Features repair and done

![image](https://github.com/tailscale/tailscale/assets/55909214/18fdb734-62d4-44eb-a00f-72d08f2f20bf)

**Comment by HaWaKv78** [comment] 2024-07-19 12:33
I'm also having this issue with v1.70.0 I only got my dante controller working for some time by exiting tailscale and disabling  IPv4 in the ethernet properties.

**Comment by WilliUreta** [comment] 2024-12-19 22:25
I'm seeing something similar. When I exit the tailscale service, there are 2 Tailscale services still running. Forcing them to shutdown, remove the interface.
So maybe those services shouldn't be running after exiting?

**Comment by nickkhyl** [comment] 2024-12-19 23:56
The Tailscale adapter cannot be disabled or removed while the service is running. The original behavior has been fixed in v1.62 earlier this year, and the network adapter will be re-created automatically.

The service runs independently of the GUI by design, as the GUI is not required for Tailscale to be operational.
One may choose to (or have to, e.g., on servers) use the [CLI](https://tailscale.com/kb/1080/cli?tab=windows) instead of the GUI, configure unattended mode to be able to access the device remotely even if no one is logged in locally and so on.

We currently have no plans to change this behavior. If your situation requires temporarily stopping the Tailscale service (e.g., to remove the network adapter or for other reasons), you can do so using Task Manager, `Services.msc`, the `sc stop Tailscale` command, or the PowerShell cmdlet: `Stop-Service Tailscale`.

**Closed by nickkhyl** 2024-12-19 23:56 UTC
Labels: OS-windows, L1 Very few, P1 Nuisance, T5 Usability, bug
