### ISSUE TITLE
macOS client fails to login, need to force "tailscale up --reset" on CLI

### ISSUE THREAD

**Issue by rafaelgarrido** [tailscale/tailscale#3249] opened 2021-11-03 02:29 UTC
### What is the issue?

Hello!

My tailscale client fails to login and keep spinning until I go to my terminal and run `tailscale up --reset`.

Here is the /Applications/Utilities/Console.app, filtering by "IPN", logging output after leaving the app trying to login for ~1 minute:
https://gist.github.com/rafaelgarrido/4221b91ec2d712f4b9de7722c8393d1f

### Steps to reproduce

- Open Tailscale App
- Click Login
- Wait... go to CLI and run `tailscale up --reset`
- Run `tailscale status` to confirm everything is OK
- Close the Tailscale App
- Open the Tailscale App and notice the behavior persists

### Are there any recent changes that introduced the issue?

Nothing that I noticed, but this is happening here I'd say for around two months... I upgrade the Tailscale App as soon as I get a notification from App Store.

### OS

macOS

### OS version

10.15.7

### Tailscale version

1.16.1

### Bug report

BUG-d0cdeac48b8a4900fb87e12b4977eee90f9bce5a6910845b3dbb3feb298b66d3-20211103021618Z-134a6974f1a1175d

**Comment by RobertClarke** [comment] 2021-11-04 08:56
Seeing the same issue.

**Comment by DentonGentry** [comment] 2022-03-27 04:49
Duplicate of https://github.com/tailscale/tailscale/issues/1403 regarding app not coming back up after upgrade from the App Store.

**Closed by DentonGentry** 2022-03-27 04:49 UTC
Labels: OS-macos, L1 Very few, P2 Aggravating, T6 Major usability
