### ISSUE TITLE
FR: Expose API key creation as part of the public API.

### ISSUE THREAD

**Issue by davidsbond** [tailscale/tailscale#3845] opened 2022-01-30 18:44 UTC
### What are you trying to do?

I would like to be able to programmatically rotate my API keys for the Tailscale API. 

* I've built a plugin for HashiCorp Vault which allows for the generation of device authentication keys. The best practice for these kind of plugins is to provide an initial API key then have Vault rotate that initial key, so that Vault is the only thing with access to the API key. Currently, users will have to manually update the API key once it expires.

* Any other integrations that require the use of API keys will eventually expire and require manual updates.

### How should we solve this?

Make the API the administrator dashboard uses for creating/revoking API keys part of the public API

### What is the impact of not solving this?

API keys will have to be manually replaced once they expire. It's also not easy to keep track of when these keys will expire as you cannot programmatically query them.

**Comment by DentonGentry** [comment] 2022-01-30 19:50
I expect to provide some way to do this, in the future. We've concluded not to allow an API key to create a new API key in perpetuity, it might instead require running on a Tailscale-enabled host on the tailnet and leverage the existence of the node key to allocate a new API key.

Duplicate of https://github.com/tailscale/tailscale/issues/3243

**Closed** 2022-01-30 19:52 UTC
Labels: needs-triage, fr

**Comment by Kranzes** [comment] 2023-04-15 16:44
Is this possible now? I want to be able to create new oauth2 clients with an API, I am writing a tool that will automate token rotation for me with CURL.

**Comment by DentonGentry** [comment] 2023-04-15 17:10
An OAuth client can be used to create an Access Token which lasts for one hour, and can be used to perform [API operations](https://github.com/tailscale/tailscale/blob/main/api.md).

> I want to be able to create new oauth2 clients with an API, I am writing a tool that will automate token rotation for me with CURL.

I think this means:
1. manually create [an OAuth client](https://tailscale.com/blog/oauth/) in the admin panel, just once.
1. use curl to post to the OAuth endpoint to allocate an Access Token
1. use the API token to perform API operations.

For example:
`curl -d "client_id=<client-id>" -d "client_secret=<secret>"  \`
`    "https://api.tailscale.com/api/v2/oauth/token" | jq -r '.access_token'`

**Comment by Kranzes** [comment] 2023-04-15 17:25
I was thinking of something not as ephemeral. I would like to have a token in terrafrom tvfars which will last for some time and then whenever i want to rotate i can just run a curl command and get a new one.

**Comment by DentonGentry** [comment] 2023-04-15 17:37
This is an example of using an OAuth endpoint in a terraform module: https://github.com/tailscale/terraform-provider-tailscale/pull/215/files

That PR added OAuth client support to the Tailscale Terraform provider.

**Comment by Kranzes** [comment] 2023-04-15 17:40
> This is an example of using an OAuth endpoint in a terraform module: https://github.com/tailscale/terraform-provider-tailscale/pull/215/files
> 
> That PR added OAuth client support to the Tailscale Terraform provider.

Yes I saw that, but I want to be able to revoke and generate a new OAuth client secret from the CLI instead of going on the web dashboard.

**Comment by DentonGentry** [comment] 2023-04-15 20:13
Could you explain why? OAuth endpoints are not intended to be temporary.

**Comment by Kranzes** [comment] 2023-04-15 21:12
> Could you explain why? OAuth endpoints are not intended to be temporary.

I am not sure I explained myself right.

basically, I want to have 2 tokens to interact with the API, 1 is only used for generating the 2nd one, the 2nd one is used with terraform to manage ACL and whatever. I want to have this workflow: I want a long-lasting token that can manage the tailnet ACL with something like terraform and If I ever want to rotate it I can use the 1st token to revoke the 2nd one (one used for tailnet management via terraform) and then generate a brand new one (that will last more than an hour) and use it as a new 2nd one (for terraform).
