### ISSUE TITLE
FR:  Allow multiple tailscale ip for one device.

### ISSUE THREAD

**Issue by dbz2k** [tailscale/tailscale#4892] opened 2022-06-20 17:03 UTC
### What are you trying to do?

this is probably a niche, but I would like to have multiple tailscale ip so I can bind multiple webservers to a different to avoid having to do :8080.

### How should we solve this?

using tailscale web ui, or cli allow the user to add a new tailscale ipv4, or ipv6 address.

**Comment by DentonGentry** [comment] 2022-06-20 17:09
Another common way to handle multiple web servers on one IP is nginx/Traefik/etc and use the SNI in an https negotiation.

**Comment by DentonGentry** [comment] 2022-08-28 04:10
Duplicate of https://github.com/tailscale/tailscale/issues/465

**Closed by DentonGentry** 2022-08-28 04:10 UTC
Labels: L2 Few, P1 Nuisance, T0 New feature, fr
