### ISSUE TITLE
FR: description field on tag or on machine - tailscale ui

### ISSUE THREAD

**Issue by danield555** [tailscale/tailscale#10079] opened 2023-11-02 08:02 UTC
### What are you trying to do?

it would be great to have free text ( one or 2-3 lines) description fields, 
one liner on tag to add to the acl, or as a free text on machines. could also be taken from aws tags ( owner, description), or allows to dd a web link to asset management database.

### How should we solve this?

for tags : add a field in json.
for machines : either add in acl, or as a free text form in machines web UI that could be prepopulated via API ( that way we could prepopulate with existing documentaion links, aws tags, etc. ) 

### What is the impact of not solving this?

the machines names , taken from local hostname , makes it quiet hard to maintain and be able to get a useful view of all the routers for instance with the environment they are related to. doing it with tags only is very cumbersome.

**Comment by DentonGentry** [comment] 2024-01-12 12:41
Duplicate of https://github.com/tailscale/tailscale/issues/4077

**Closed by DentonGentry** 2024-01-12 12:41 UTC
Labels: needs-triage, fr
