### ISSUE TITLE
Magicdns broke connection over wifi on android phone, 4g sometime broke also

### ISSUE THREAD

**Issue by ForteDexe** [tailscale/tailscale#7154] opened 2023-02-01 23:52 UTC
### What is the issue?

I install tailscale on phone, test around a bit, everything working fine, then I use it with exit node for about a week.
Today I install tailscale on my windows machine (first time I use window in my network, I am not sure if this is the cause)
Then tailscale on my phone (with exit node turn off) cant connect to the internet or local network, turn on exit node will make it connect to the internet again.

To fix the issue:
_Disable magicdns, or use global dns with overwrite local dns.

### Steps to reproduce

Not sure, but if I use magicdns, thing will stop working.

### OS

Android

### OS version

Galaxy note 10 plus, android 12

### Tailscale version

Current version

### Other software

No app on my phone will affect this.

### Bug report

BUG-4e4ff1d335b72bc6ea90d8a9767ee2d055f507afd6c12e409b3e8939d4d461e9-20230201235208Z-2f542a5d1994fa20

**Comment by lightshark85** [comment] 2023-02-05 11:24
Same here on Xiaomi mi-9t

**Comment by DentonGentry** [comment] 2023-02-12 03:40
Around the time the bug was filed:
```
2023-02-01 19:18:59.449681705 +0000 UTC: getDnsConfigFromLinkProperties: 192.168.1.1
2023-02-01 19:18:59.45023535 +0000 UTC: getDnsServersFromSystemProperties:
2023-02-01 19:18:59.453101028 +0000 UTC: getDnsServersFromNetworkInfo: 192.168.1.1
2023-02-01 19:18:59.45935259 +0000 UTC: 21.0M/188.7M dns: Resolvercfg: {Routes:{.:[192.168.1.1] ts.net.:[199.247.155.53 2620:111:8007::53]} Hosts:6 LocalDomains:[tail12345.ts.net.]+65arpa}
2023-02-01 19:18:59.45946535 +0000 UTC: 21.0M/188.7M dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[tail12345.ts.net.] MatchDomains:[] Hosts:[]}
...
2023-02-01 19:24:17.756415802 +0000 UTC: getDnsConfigFromLinkProperties: 10.1.27.27 10.149.205.129 2001:ee0:100:7::1 2001:ee0:1840:4::ffff
2023-02-01 19:24:17.756860281 +0000 UTC: getDnsServersFromSystemProperties:
2023-02-01 19:24:17.764099552 +0000 UTC: getDnsServersFromNetworkInfo:
2023-02-01 19:24:17.776315177 +0000 UTC: 21.8M/192.4M dns: Resolvercfg: {Routes:{.:[10.1.27.27 10.149.205.129 2001:ee0:100:7::1 2001:ee0:1840:4::ffff] ts.net.:[199.247.155.53 2620:111:8007::53]} Hosts:6 LocalDomains:[tail12345.ts.net.]+65arpa}
2023-02-01 19:24:17.776523042 +0000 UTC: 21.8M/192.4M dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[tail12345.ts.net.] MatchDomains:[] Hosts:[]}
```

It pulls those DNS server addresses from the Android platform. I imagine one of those is the DNS servers used on Wi-fi and the other on mobile data.

However we also see:
```
2023-02-01 19:24:17.77621476 +0000 UTC: 21.8M/192.4M Accept: TCP{100.125.109.79:44882 > 100.100.100.100:853} 64 ok out
```

853 is DNS-over-TLS. Is Private DNS turned on? That does not currently work: https://github.com/tailscale/tailscale/issues/915

**Comment by DentonGentry** [comment] 2023-06-04 03:32
Duplicate of https://github.com/tailscale/tailscale/issues/915

**Closed by DentonGentry** 2023-06-04 03:32 UTC
Labels: OS-android, L1 Very few, P2 Aggravating, T5 Usability, waiting-for-info, bug
