### ISSUE TITLE
Ubuntu 18.04 systemd-resolved: setLinkDomains: Argument list too long

### ISSUE THREAD

**Issue by atroche** [tailscale/tailscale#3188] opened 2021-10-26 03:31 UTC
### What is the issue?

I was expecting there to be no warnings / errors shown by `tailscale status`.

```
Oct 26 14:18:26 murphy tailscaled[9490]: derphttp.Client.Connect: connecting to derp-8 (lhr)
Oct 26 14:18:26 murphy tailscaled[9490]: wgengine: Reconfig: configuring DNS
Oct 26 14:18:26 murphy tailscaled[9490]: dns: Set: {DefaultResolvers:[] Routes:{seermedical.com.beta.tailscale.net.:[]}+65arpa SearchDomains:[seermedic
Oct 26 14:18:26 murphy tailscaled[9490]: dns: Resolvercfg: {Routes:{} Hosts:24 LocalDomains:[seermedical.com.beta.tailscale.net.]+65arpa}
Oct 26 14:18:26 murphy tailscaled[9490]: dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[seermedical.com.beta.tailscale.net.] MatchDomains:[0.e.1.a.c.5.1.1.a.7.d.f.ip6.arpa. 100.100.in-addr.arpa. 101.100.in-addr.arpa <SNIP>
Oct 26 14:18:26 murphy tailscaled[9490]: control: controlclient: restarting map request for "dns" health change to new state: setLinkDomains: Argument
Oct 26 14:18:26 murphy tailscaled[9490]: health("dns"): error: setLinkDomains: Argument list too long
```

### OS

Linux

### OS version

Ubuntu 18.04

### Tailscale version

1.16.1

### Bug report

BUG-fd142d4c5a93f433244c975ce9bc9362c90527e25835b63151b5208e9ac7f0db-20211026033129Z-6cbf8d0528145c22

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3pf2p)

**Comment by DentonGentry** [comment] 2021-11-03 12:50
I added more Split DNS domains to better match some of the earlier reports, but still cannot get it to fail.

One earlier report is arm64, the other x86_64, I'm using x86_64.

**Comment by matsimitsu** [comment] 2021-11-10 20:01
Getting the same errors with magic DNS enabled, also on `18.04.5`. The tunnel refuses to come up

```
<snip>@<snip>:~# tailscale status
# Health check:
#     - dns: setLinkDomains: Argument list too long
```

```
<snip>@<snip>:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

```
<snip>@<snip>:~# systemd-resolve --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

```
Nov 10 19:41:56 connect1 tailscaled[20241]: wgengine: Reconfig: configuring DNS
Nov 10 19:41:56 connect1 tailscaled[20241]: dns: Set: {DefaultResolvers:[] Routes:{<snip>.com.beta.tailscale.net.:[]}+65arpa SearchDomains:[<snip>.com.beta.tailscale.net.] Hosts:2}
Nov 10 19:41:56 connect1 tailscaled[20241]: dns: Resolvercfg: {Routes:{} Hosts:2 LocalDomains:[<snip>.com.beta.tailscale.net.]+65arpa}
Nov 10 19:41:56 connect1 tailscaled[20241]: dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[<snip>.com.beta.tailscale.net.] MatchDomains:[0.e.1.a.c.5.1.1.a.7.d.f.ip6.arpa. 100.100.in-addr.arpa. 101.100.in-addr.arpa. 102.100.in-addr.arpa. 103.100.in-addr.arpa. 104.100.in-addr.arpa. 105.100.in-addr.arpa. 106.100.in-addr.arpa. 107.100.in-addr.arpa. 108.100.in-addr.arpa. 109.100.in-addr.arpa. 110.100.in-addr.arpa. 111.100.in-addr.arpa. 112.100.in-addr.arpa. 113.100.in-addr.arpa. 114.100.in-addr.arpa. 115.100.in-addr.arpa. 116.100.in-addr.arpa. 117.100.in-addr.arpa. 118.100.in-addr.arpa. 119.100.in-addr.arpa. 120.100.in-addr.arpa. 121.100.in-addr.arpa. 122.100.in-addr.arpa. 123.100.in-addr.arpa. 124.100.in-addr.arpa. 125.100.in-addr.arpa. 126.100.in-addr.arpa. 127.100.in-addr.arpa. 64.100.in-addr.arpa. 65.100.in-addr.arpa. 66.100.in-addr.arpa. 67.100.in-addr.arpa. 68.100.in-addr.arpa. 69.100.in-addr.arpa. 70.100.in-addr.arpa. 71.100.in-addr.arpa. 72.100.in-addr.arpa. 73.100.in-addr.arpa. 74.100.in-addr.arpa. 75.100.in-addr.arpa. 76.100.in-addr.arpa. 77.100.in-addr.arpa. 78.100.in-addr.arpa. 79.100.in-addr.arpa. 80.100.in-addr.arpa. 81.100.in-addr.arpa. 82.100.in-addr.arpa. 83.100.in-addr.arpa. 84.100.in-addr.arpa. 85.100.in-addr.arpa. 86.100.in-addr.arpa. 87.100.in-addr.arpa. 88.100.in-addr.arpa. 89.100.in-addr.arpa. 90.100.in-addr.arpa. 91.100.in-addr.arpa. 92.100.in-addr.arpa. 93.100.in-addr.arpa. 94.100.in-addr.arpa. 95.100.in-addr.arpa. 96.100.in-addr.arpa. 97.100.in-addr.arpa. 98.100.in-addr.arpa. 99.100.in-addr.arpa. <snip>.com.beta.tailscale.net.]}
Nov 10 19:41:56 connect1 tailscaled[20241]: peerapi: serving on http://<snip>:33861
Nov 10 19:41:56 connect1 tailscaled[20241]: peerapi: serving on http://[<snip>]:33861
Nov 10 19:41:56 connect1 tailscaled[20241]: control: controlclient: restarting map request for "dns" health change to new state: setLinkDomains: Argument list too long
Nov 10 19:41:56 connect1 tailscaled[20241]: health("dns"): error: setLinkDomains: Argument list too long

[...]

Nov 10 19:42:06 connect1 tailscaled[20241]: dns: error: upstream nameservers not set
Nov 10 19:42:06 connect1 tailscaled[20241]: dns: error: upstream nameservers not set
Nov 10 19:42:16 connect1 tailscaled[20241]: dns: error: upstream nameservers not set
Nov 10 19:42:16 connect1 tailscaled[20241]: dns: error: upstream nameservers not set
Nov 10 19:42:16 connect1 tailscaled[20241]: dns: error: upstream nameservers not set
Nov 10 19:42:18 connect1 tailscaled[20241]: netcheck: probePortMapServices: skipping portmap; gateway range likely lacks support
Nov 10 19:42:26 connect1 tailscaled[20241]: dns: error: upstream nameservers not set
Nov 10 19:42:26 connect1 tailscaled[20241]: dns: error: upstream nameservers not set
Nov 10 19:42:36 connect1 tailscaled[20241]: dns: error: upstream nameservers not set
Nov 10 19:42:38 connect1 tailscaled[20241]: netcheck: probePortMapServices: skipping portmap; gateway range likely lacks support
Nov 10 19:42:46 connect1 tailscaled[20241]: dns: error: upstream nameservers not set
Nov 10 19:42:46 connect1 tailscaled[20241]: dns: error: upstream nameservers not set
Nov 10 19:42:46 connect1 tailscaled[20241]: dns: error: upstream nameservers not set
Nov 10 19:42:46 connect1 tailscaled[20241]: [RATELIMIT] format("dns: error: %v")
Nov 10 19:42:56 connect1 tailscaled[20241]: [RATELIMIT] format("dns: error: %v") (1 dropped)
Nov 10 19:42:56 connect1 tailscaled[20241]: dns: error: upstream nameservers not set
Nov 10 19:42:56 connect1 tailscaled[20241]: dns: error: upstream nameservers not set
Nov 10 19:42:56 connect1 tailscaled[20241]: [RATELIMIT] format("dns: error: %v")
Nov 10 19:43:01 connect1 tailscaled[20241]: netcheck: probePortMapServices: skipping portmap; gateway range likely lacks support
Nov 10 19:43:06 connect1 tailscaled[20241]: [RATELIMIT] format("dns: error: %v") (2 dropped)
Nov 10 19:43:06 connect1 tailscaled[20241]: dns: error: upstream nameservers not set
Nov 10 19:43:06 connect1 tailscaled[20241]: [RATELIMIT] format("dns: error: %v")
Nov 10 19:43:16 connect1 tailscaled[20241]: [RATELIMIT] format("dns: error: %v") (4 dropped)
Nov 10 19:43:16 connect1 tailscaled[20241]: dns: error: upstream nameservers not set
Nov 10 19:43:16 connect1 tailscaled[20241]: [RATELIMIT] format("dns: error: %v")
Nov 10 19:43:17 connect1 tailscaled[20241]: Accept: TCP{100.xx.xx.xx:35334 > 100.100.100.100:53} 60 ok out
Nov 10 19:43:18 connect1 tailscaled[20241]: Accept: TCP{100.xx.xx.xx:35334 > 100.100.100.100:53} 60 ok out
Nov 10 19:43:20 connect1 tailscaled[20241]: Accept: TCP{100.xx.xx.xx:35334 > 100.100.100.100:53} 60 ok out
Nov 10 19:43:22 connect1 tailscaled[20241]: netcheck: probePortMapServices: skipping portmap; gateway range likely lacks support
Nov 10 19:43:22 connect1 tailscaled[20241]: open-conn-track: timeout opening (TCP 100.xx.xx.xx:35334 => 100.100.100.100:53); no associated peer node
Nov 10 19:43:25 connect1 tailscaled[20241]: open-conn-track: timeout opening (TCP 100.xx.xx.xx:35334 => 100.100.100.100:53); no associated peer node
Nov 10 19:43:36 connect1 tailscaled[20241]: Accept: TCP{100.xx.xx.xx:35340 > 100.100.100.100:53} 60 ok out
Nov 10 19:43:39 connect1 tailscaled[20241]: Accept: TCP{100.xx.xx.xx:35340 > 100.100.100.100:53} 60 ok out
```

Let me know if you need anything else!

**Comment by DentonGentry** [comment] 2021-11-10 20:10
The most immediate problem is that I haven't been able to produce the failure. I'm not entirely sure what we can do to address it, but not being able to produce it means I can't even try potential solutions.
- For `<snip>.com.beta.tailscale.net`, how many characters is it?
- how much RAM does the system have? Maybe its buffers and limits are dynamic.

**Comment by matsimitsu** [comment] 2021-11-10 20:13
> For <snip>.com.beta.tailscale.net, how many characters is it?

It's 9 characters

> how much RAM does the system have? Maybe its buffers and limits are dynamic.

```<snip>@<snip>:~# free -m
              total        used        free      shared  buff/cache   available
Mem:           3944         369         498           0        3076        3318
Swap:          4095          20        4075
```

**Comment by nicewrld** [comment] 2021-11-10 21:15
> The most immediate problem is that I haven't been able to produce the failure. I'm not entirely sure what we can do to address it, but not being able to produce it means I can't even try potential solutions.

> - For `<snip>.com.beta.tailscale.net`, how many characters is it?

xxx.xx.beta.tailscale.net 25 char (x is not the actual value)

> - how much RAM does the system have? Maybe its buffers and limits are dynamic.

I can't get a free -m as I have apparently accidentally killed this pi and am away from home, but this is a RPi 2GB. I will take a look when I am home. I should have an 18.04.5 ISO somewhere that should have been made at the same time as the arm image. I can spin a few of those up as well to test.

I will try to report back on my findings tonight or tomorrow.

**Comment by matsimitsu** [comment] 2021-11-10 21:40
I'm able to reproduce it on a fresh DigitalOcean droplet with the 18.04 distro selected, if that helps. 

It won't show the message in the log the first time, but restarting `tailscaled` while the magic dns option is disabled will result in the message shown in the log and DNS not working

**Comment by DentonGentry** [comment] 2021-11-13 17:07
Unfortunately I just created a Digital Ocean droplet with Ubuntu 18.04, and I don't run into the issue. There is no error from `setLinkDomains`.

The domain names I'm using are longer than the ones noted above, so there is something more subtle about the tailnet involved than just the length of the names.

```
root@dgentry-ubuntu18:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by matsimitsu** [comment] 2021-11-16 15:37
I still have the droplet running and can give you access if that helps, it's just running Tailscale, nothing else. My email is is my profile, if you're interested.

**Comment by danderson** [comment] 2021-11-16 20:18
I'm not sure why it only reproduces sporadically, but this is a known bug of very old systemd-resolved versions. It was fixed around the 19.10/20.04 timeframe.

We don't have any good options to work around this bug. The domains list is long because we want to capture all of 100.64.0.0/10 for reverse DNS lookups, and that prefix doesn't decompose cleanly in the form that systemd-resolved understands (per-quad wildcarding), so we have an explosion of prefixes we have to give to systemd-resolved... which makes the argument list too long.

The only option we realistically have is to detect this condition and resubmit the config without the IP patterns, which will break reverse DNS lookups - but at least forward lookups would work.

**Comment by bradfitz** [comment] 2021-11-16 20:55
This will be in the next [unstable build](https://pkgs.tailscale.com/unstable/). (something numbered greater than 1.17.223)

**Closed** 2021-11-16 20:54 UTC
Labels: OS-linux, L1 Very few, P3 Can't get started, T5 Usability, bug

**Comment by DentonGentry** [comment] 2021-11-16 23:14
1.17.232 is now available on https://pkgs.tailscale.com/unstable/ and contains this fix.
