### ISSUE TITLE
FR: SCIM for Azure AD

### ISSUE THREAD

**Issue by nauxliu** [tailscale/tailscale#6375] opened 2022-11-18 00:25 UTC
### What are you trying to do?

Sync identity provider groups and user deactivations from Azure AD

### How should we solve this?

Add SCIM support for AAD, seem the SCIM feature only supports Okta now.

### What is the impact of not solving this?

We need to manually manage the ACL group membership in ACL, though we already have the info in AAD.

### Anything else?

We'd love to upgrade our plan to the business if this is supported.

**Comment by DentonGentry** [comment] 2022-11-18 00:26
Duplicate of https://github.com/tailscale/tailscale/issues/979

**Closed by DentonGentry** 2022-11-18 00:26 UTC
Labels: needs-triage, fr
