### ISSUE TITLE
App does not load on firestick

### ISSUE THREAD

**Issue by mattmole** [tailscale/tailscale#10012] opened 2023-10-29 12:50 UTC
### What is the issue?

After installing the latest fdroid version of the tailscale client on an Amazon Firestick, on loading the screen just turns black and nothing happens.

I did see a guide that showed earlier versions have worked. Is there any information anywhere about installing on a firestick?

### Steps to reproduce

Install apk as downloaded from fdroid website and open the app

### Are there any recent changes that introduced the issue?

Never worked for me

### OS

Other

### OS version

First stick

### Tailscale version

1.48.x

**Comment by DentonGentry** [comment] 2023-10-29 13:07
It likely depends more on the model of Firestick than it does the version of the app. https://github.com/tailscale/tailscale/issues/4332 concerns the graphics hardware in the Android device and whether it supports OpenGL ES2, and matches the symptoms described here.

**Comment by DentonGentry** [comment] 2024-01-12 12:43
Duplicate of https://github.com/tailscale/tailscale/issues/4332

**Closed by DentonGentry** 2024-01-12 12:43 UTC
Labels: needs-triage, bug
