### ISSUE TITLE
FR: add an option to force tailscale using DERP

### ISSUE THREAD

**Issue by IceCodeNew** [tailscale/tailscale#3992] opened 2022-02-21 03:47 UTC
### What are you trying to do?

The ISP of my office is kindly shitty, making the SSH connection over tailscale hang up after several minutes.
It seems like some sort of QoS strategy as I gradually draw the conclusion that there is nothing I can do to solve this problem. Which does make sense as most Chinese ISPs are not friendly to UDP traffic.

I would like to ask for an option to force tailscale using DERP, so I can confirm it is a problem with ISP's UDP processing strategy.

### How should we solve this?

Add an option to force tailscale using DERP.

### What is the impact of not solving this?

tailscale may not perform an acceptable quality.
Currently, I did not found any workaround for this problem.

**Comment by DentonGentry** [comment] 2022-02-21 03:59
Duplicate of https://github.com/tailscale/tailscale/issues/2270

**Closed by DentonGentry** 2022-02-21 03:59 UTC
Labels: needs-triage, fr

**Comment by IceCodeNew** [comment] 2022-02-21 04:00
Thanks for pointing it out.
How did I miss that issue...
