### ISSUE TITLE
Android App - "Run exit node" doesn't allow other devices to connect to the internet (no DNS)

### ISSUE THREAD

**Issue by jbd7** [tailscale/tailscale#6119] opened 2022-10-28 23:57 UTC
### What is the issue?

Issue: Setting Tailscale's Android App as an Exit node doesn't allow connected nodes to use the internet. 

**Context:**
- Android9 and Android12 in the Tailscale network
- Android9 set up as exit node
- Android12 using Android9 a exit node
- Android12 can ping Android9's 100.x.y.z IP

**Expected:**
- Android12 can connect to the internet and get Android9's public IP

**What happens**:
- Android12 cannot get internet connectivity 

**Notes:**
- IP leakage: While being using Android9 as an exit node, without being able to connect to the internet, setting Android12 as a hotspot allows a Laptop connected to Android12 via wifi to get internet. But, Laptop gets Android12's original IP, meaning that the Android hotspot feature doesn't route connected clients via Tailscale. 
- Reverting the roles of Android12 and Android9 gives the same situation (Android9 doesn't get internet connection when using Android12 as exit node)
- Android12 connecting to an exit node of the same network running on Linux works very fine. That what makes me think it's related to the Android App.
- This is possibly a DNS issue as I can connect to the internet using an IP in Chrome instead of a domain name. I tried changing the Android "Private DNS" setting from Automatic to None, in both Android devices, without success.

### Steps to reproduce

- Create Tailscale node with Android9, Android12. Both Android devices being non-rooted, running Tailscale 1.32.
- Set Android9 as Exit Node. Approve Exit Node on the browser
- Connect both devices (i.e. set Android toggle to Active)
- On Android12, tap "Use Exit node" and select Android9
- Ping Android9. Ping is successful
- Open Chrome app and visit ipinfo.io. The page doesn't load. No app gets internet connectivity on Android 12.

### Are there any recent changes that introduced the issue?

N/A 

### OS

Android

### OS version

Android 12 and Android 9

### Tailscale version

1.32.2

### Bug report

BUG-1f5cfe3523fbdb2ce26b26989d71ef8d804abd3325992450d2a82a30a57e2dd6-20221028234534Z-94f91d5706051092

**Comment by jbd7** [comment] 2022-10-29 02:43
I discovered that I no longer have this issue is I enable "Override local DNS" in my account settings. Is this how Tailscale is supposed to work? If so the issue can be closed.

**Comment by DentonGentry** [comment] 2022-10-29 02:58
The problem is related to fetching the list of DNS servers from the underlying platform. When "Override local DNS" is not checked, the Tailscale app is supposed to figure out the list of DNS servers which Android received from DHCP or other sources.

In a broken case, note that there is no interface in interfaces.State other than the Tailscale interface. `getDnsConfigFromLinkProperties`, `getDnsServersFromSystemProperties`, and `getDnsServersFromNetworkInfo` all return empty.

```
2022-10-28 19:13:06.987665911 +0000 UTC: 23.0M/185.5M LinkChange: major, rebinding. New state: interfaces.State{defaultRoute= ifs={tun1:[100.116.x.y/32 fd7a:115c:a1e0:ab12:q:r:s:t/128]} v4=true v6=false}
2022-10-28 19:13:06.991903671 +0000 UTC: 23.1M/185.5M dns: Set: {DefaultResolvers:[] Routes:{tail00000.ts.net.:[] ts.net.:[]}+65arpa SearchDomains:[tail00000.ts.net.] Hosts:4}
2022-10-28 19:13:06.993195859 +0000 UTC: getDnsConfigFromLinkProperties:
2022-10-28 19:13:06.993967161 +0000 UTC: getDnsServersFromSystemProperties:
2022-10-28 19:13:06.994385286 +0000 UTC: getDnsServersFromNetworkInfo:
2022-10-28 19:13:06.996004661 +0000 UTC: 23.1M/185.5M dns: Resolvercfg: {Routes:{.:[]} Hosts:4 LocalDomains:[tail00000.ts.net. ts.net.]+65arpa}
2022-10-28 19:13:06.996218671 +0000 UTC: 23.1M/185.5M dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[tail00000.ts.net.] MatchDomains:[] Hosts:[]}
```
In this non-working case I'm guessing the phone is on Wi-Fi? We don't seem to be finding the Wi-Fi interface.

--------

In a working case we see several rmnet_data* interfaces, which are the mobile LTE/4G/5G/etc radios. `getDnsConfigFromLinkProperties` is able to return the two DNS servers for that link.
```
2022-10-28 19:13:08.302637889 +0000 UTC: 23.5M/185.7M LinkChange: major, rebinding. New state: interfaces.State{defaultRoute= ifs={rmnet_data1:[10.83.x.y/30] rmnet_data2:[2a02:498:1f84:66fa:q:r:s:t/64] tun1:[100.116.x.y/32 fd7a:115c:a1e0:ab12:q:r:s:t/128]} v4=true v6=true}
2022-10-28 19:13:08.302930389 +0000 UTC: 23.5M/185.7M dns: Set: {DefaultResolvers:[] Routes:{tail00000.ts.net.:[] ts.net.:[]}+65arpa SearchDomains:[tail00000.ts.net.] Hosts:4}
2022-10-28 19:13:08.327677941 +0000 UTC: getDnsConfigFromLinkProperties: 84.241.x.y 84.241.x.y
2022-10-28 19:13:08.329167421 +0000 UTC: getDnsServersFromSystemProperties:
2022-10-28 19:13:08.330425962 +0000 UTC: getDnsServersFromNetworkInfo:
2022-10-28 19:13:08.334776743 +0000 UTC: 23.5M/185.7M dns: Resolvercfg: {Routes:{.:[84.241.x.y 84.241.x.y]} Hosts:4 LocalDomains:[ts.net. tail00000.ts.net.]+65arpa}
2022-10-28 19:13:08.335720389 +0000 UTC: 23.5M/185.7M dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[tail00000.ts.net.] MatchDomains:[] Hosts:[]}
```

**Comment by DentonGentry** [comment] 2022-10-29 03:38
What model of phone are these two devices? We can look at why the Wi-Fi doesn't appear to be detected.

**Comment by jbd7** [comment] 2022-10-29 03:47
> In this non-working case I'm guessing the phone is on Wi-Fi? We don't seem to be finding the Wi-Fi interface.

Correct, the phone Android9 doesn't have mobile data, and is on Wifi. 

For your second example, these 2 IPs are the DNS of the telco provider, therefore coming from the phone Android12. Around the time of these logs, I had the wifi disabled.

> What model of phone are these two devices? We can look at why the Wi-Fi doesn't appear to be detected.

Both phones are from OnePlus (A3003 and AC2003)

**Comment by DentonGentry** [comment] 2023-02-18 19:26
That there is an exit node involved isn't really involved in the problem, the problem is that no DNS servers are found. We'll handle that on https://github.com/tailscale/tailscale/issues/6143

Duplicate of https://github.com/tailscale/tailscale/issues/6143

**Closed by DentonGentry** 2023-02-18 19:26 UTC
Labels: OS-android, L1 Very few, P2 Aggravating, T5 Usability, exit-node, bug
