### ISSUE TITLE
Allow log file path to be configured

### ISSUE THREAD

**Issue by anaisbetts** [tailscale/tailscale#1463] opened 2021-03-07 13:11 UTC
**Is your feature request related to a problem? Please describe.**

I run Tailscale on a Raspberry Pi with an SD card and in order to prevent SD card wear, I put most of the log file directories under tmpfs. However, Tailscale doesn't write log files to /var/log, it writes them to /var/lib/tailscale, and it mixes these log files with files that Seem Important To Not Delete like tailscaled.state

**Describe the solution you'd like**

It would be nice to move these log files to a separate directory so I can tmpfs them away 

**Describe alternatives you've considered**

I can certainly tmpfs'ify the /var/lib/tailscale directory but I don't want to bork my installation

**Comment by llewxam-kache** [comment] 2021-03-16 18:06
+1 an option to write to a dedicated log file would be great. On my Ubuntu 18.04 servers, the syslog gets packed full of tailscaled messages. Yes, `grep -v tailscaled` works to cut them out if I'm looking for something else, but still balloons a decent amount on heavily used systems.
```
Mar 16 10:51:55 ub18-server tailscaled[7600]: Accept: TCP{100.93.145.24:674 > 100.82.175.42:2049} 60 tcp ok
Mar 16 10:51:55 ub18-server tailscaled[7600]: open-conn-track: flow TCP (100.82.175.42:2049 => 100.93.145.24:674) got RST by peer
Mar 16 10:51:56 ub18-server tailscaled[7600]: [pR2Rr] - Sending keepalive packet
Mar 16 10:51:57 ub18-server tailscaled[7600]: magicsock: want call-me-maybe but endpoints stale; restunning
Mar 16 10:51:57 ub18-server tailscaled[7600]: [WfQeb] - Sending keepalive packet
Mar 16 10:51:57 ub18-server tailscaled[7600]: magicsock: STUN done; sending call-me-maybe to d:39e6670d61bf5753 [ru71b]
Mar 16 10:52:03 ub18-server tailscaled[7600]: open-conn-track: timeout opening (100.82.175.42:2049 => 100.93.145.24:674) to node [Gsk/T]; lastSeen=2m3s, lastRecv=10s
Mar 16 10:52:08 ub18-server tailscaled[7600]: [Gsk/T] - Sending keepalive packet
Mar 16 10:52:09 ub18-server tailscaled[7600]: [ru71b] - Sending keepalive packet
Mar 16 10:52:12 ub18-server tailscaled[7600]: [WfQeb] - Sending keepalive packet
Mar 16 10:52:12 ub18-server tailscaled[7600]: [pR2Rr] - Sending keepalive packet
Mar 16 10:52:16 ub18-server tailscaled[7600]: Accept: TCP{100.68.180.88:884 > 100.82.175.42:2049} 232 tcp non-syn
Mar 16 10:52:16 ub18-server tailscaled[7600]: Accept: TCP{100.82.175.42:2049 > 100.68.180.88:884} 216 ok out
Mar 16 10:52:18 ub18-server tailscaled[7600]: [Gsk/T] - Sending keepalive packet
Mar 16 10:52:26 ub18-server tailscaled[7600]: [pR2Rr] - Sending keepalive packet
Mar 16 10:52:27 ub18-server tailscaled[7600]: [WfQeb] - Sending keepalive packet
Mar 16 10:52:29 ub18-server tailscaled[7600]: Accept: TCP{100.104.98.78:785 > 100.82.175.42:2049} 52 tcp non-syn
Mar 16 10:52:35 ub18-server tailscaled[7600]: [X/tJb] - Received handshake initiation
Mar 16 10:52:35 ub18-server tailscaled[7600]: [RATE LIMITED] format string "%s" (example: "[X/tJb] - Sending handshake response")
Mar 16 10:52:35 ub18-server tailscaled[7600]: magicsock: disco: d:089645a8846dbd05<-d:d72b6f0def782a6a ([X/tJb], derp-2)  got call-me-maybe, 0 endpoints 
```

**Comment by ChaosZero112** [comment] 2021-06-05 10:20
Adding my voice to this request as I would like to get tailscaled out of my syslog and just log it to a file (under /var/log)

**Comment by DentonGentry** [comment] 2021-10-14 00:41
Duplicate of https://github.com/tailscale/tailscale/issues/2936 (which was filed later but has more details and a workaround)

**Closed by DentonGentry** 2021-10-14 00:41 UTC
Labels: L2 Few, P2 Aggravating, T0 New feature
