### ISSUE TITLE
FR: acl per exit node

### ISSUE THREAD

**Issue by danield555** [tailscale/tailscale#9338] opened 2023-09-11 08:24 UTC
### What are you trying to do?

currently we can only give access to all exit nodes or none in the acl.

### How should we solve this?

define acl on exit node so it would be visible only to a specific team/acl group.

### What is the impact of not solving this?

all or nothing access to exit node , as it is now.

**Comment by DentonGentry** [comment] 2023-09-11 13:38
Duplicate of https://github.com/tailscale/tailscale/issues/1567

**Closed by DentonGentry** 2023-09-11 13:38 UTC
Labels: needs-triage, fr
