### ISSUE TITLE
FR: Option to force overwrite MagicDNS hostname

### ISSUE THREAD

**Issue by mrgasparov** [tailscale/tailscale#5981] opened 2022-10-18 08:12 UTC
### What are you trying to do?

I would like the option to define immutable MagicDNS hostnames for my machines. Often I am redeploying a certain service and the new VM is automatically assigned a suffix, such as `bastion-dev` --> `bastion-dev-1` which makes life harder for anyone looking for that specific machine, particularly when wanting to use Tailscale SSH.

### How should we solve this?

It would be very useful to have an option on the CLI such as `--force-hostname=<name>` where we could choose to force overwrite an existing hostname.

### What is the impact of not solving this?

Bad UX, particularly when wanting to use Tailscale SSH.

**Comment by mayakacz** [comment] 2022-10-18 15:49
There is an option `tailscale up --hostname`, that forces a particular device name, which also applies to MagicDNS. It _will not_ overwrite with a name that is already in use on another device. See https://tailscale.com/kb/1080/cli/

**Comment by mrgasparov** [comment] 2022-10-19 10:44
Thanks for the reply @mayakacz. I am aware of that but I'm specifically requesting the ability to overwrite, so that the hostname definition is deterministic. We use Terraform to deploy our VMs, and if a VM needs to be recreated, the hostname for the new instance will inevitably have a suffix.

**Comment by jdgiddings** [comment] 2022-10-25 15:53
@mrgasparov If you're already using Terraform, you may look into the Tailscale Terraform provider and see if that has a solution to your issue

**Comment by DentonGentry** [comment] 2022-10-26 04:49
Duplicate of https://github.com/tailscale/tailscale/issues/4778

**Closed by DentonGentry** 2022-10-26 04:49 UTC
Labels: needs-triage, fr
