### ISSUE TITLE
Specifying multiple --advertise-routes flags silently drops all but last invocation

### ISSUE THREAD

**Issue by tim-seoss** [tailscale/tailscale#4391] opened 2022-04-11 08:49 UTC
### What is the issue?

    tailscale up --advertise-routes 172.60.0.0/20 --advertise-routes 172.40.0.0/20

... runs without error, but doesn't advertise the `172.60.0.0/20` route.

I think that it should do one of:
- Combine all subnets from all instances of the ` --advertise-routes` switch.
- Warn that all but the final invocation will be ignored.

### OS

Linux

### OS version

Debian 11.3

### Tailscale version

1.22.2

### Bug report

BUG-2104ffbc53952d142cea5bf778c9d0404de16d8ab1ba2be44071960daff240a5-20220411084625Z-857afb8152b8c1c8

**Comment by DentonGentry** [comment] 2022-04-11 11:08
We're likely to add a "tailscale set" https://github.com/tailscale/tailscale/issues/2096 which will allow finer-grained modification of exiting CLI flags. We can't really change the existing behavior without breaking workflows.

Duplicate of https://github.com/tailscale/tailscale/issues/2096

**Closed by DentonGentry** 2022-04-11 11:08 UTC
Labels: needs-triage, bug

**Comment by tim-seoss** [comment] 2022-04-11 11:13
Outputting something like:

    WARNING:  --advertise-routes has been specified multiple times, only the last instance will be used.

... to STDERR would seem very unlikely to break existing workflows tho?
