### ISSUE TITLE
Taildrop reception on MacOS will drop files in inconsistent places contraruy to documentation

### ISSUE THREAD

**Issue by kennyluk** [tailscale/tailscale#7822] opened 2023-04-08 08:58 UTC
### What is the issue?

On MacOS, using versino 1.38.4 standalone (System Extension), Taildrop will sometimes drop files into the "/System/Volumes/Data/Library/Tailscale/files/[$username]-uid-[$uidnum]" directories instead of ~/Downloads.

### Steps to reproduce

Fresh install of tailscale, same network and id, one iPhone as sender, one MacOS as receiver.

1. send one photo via Taildrop from iPhone to MacOS.
2. file received in ~/Downloads.
3. send 5 photos at once via Taildrop from iPhone to MacOS.
4. No files in ~/Downloads on MacOS but you will find the files in /System/Volumes/Data/Library/Tailscale/files/[$username]-uid-[$uidnum]". The directory will be owned by root.

### Are there any recent changes that introduced the issue?

None

### OS

macOS, iOS

### OS version

MacOS 12.6.3, iOS 16.4

### Tailscale version

1.38.4 standalone (System Extension) on MacOS and 1.38.2 on iOS

**Comment by bradfitz** [comment] 2023-04-08 15:44
That's the holding area where files are written while they're received. It's then the GUI process's job to move them from there to the Desktop.

@mihaip, does another bug track any problems with macsys Taildrop receive?

**Comment by mihaip** [comment] 2023-04-10 17:34
Sounds like a duplicate of #7511 (specifically https://github.com/tailscale/tailscale/issues/7511#issuecomment-1474289715 - the files that were not received were stuck in that directory).

**Closed by mihaip** 2023-04-10 17:34 UTC
Labels: OS-macos, needs-triage, taildrop, bug
