### ISSUE TITLE
Excessive data consumption on iOS

### ISSUE THREAD

**Issue by philletourneau** [tailscale/tailscale#6160] opened 2022-11-01 14:17 UTC
### What is the issue?

I found that Tailscale on my iPhone has consumed gigabytes of data usage in the course of a month that completely decimated my data allowance on my cellular provider.

I was using either version 1.32.0 or 1.32.1 on iOS 16 or 16.1 (hard to nail down exactly when it started, but roughly the month of October 2022)

### Steps to reproduce

I tend to leave the VPN connection connected most of the time.

### Are there any recent changes that introduced the issue?

Maybe iOS 16.1 or a version of the Tailscale iOS app >= 1.30.2?

### OS

iOS

### OS version

16 or 16.1

### Tailscale version

>= 1.30.2?

**Comment by bradfitz** [comment] 2022-11-01 15:34
What's your phone's Tailscale IP so we can look up details? We were discussing this on our internal Slack, though, after seeing your tweet. We'd love to figure out what's happening here. On some network transitions we've in the past seen evidence of the Network Extension traffic get into some sort of loop but we've never been able to reproduce it.

**Comment by philletourneau** [comment] 2022-11-01 16:57
Hi! thanks for reaching out, it's 100.108.242.70

I love Tailscale, I _really_ want to be able to have it enabled on my phone 24/7, but this was a big PIA...

**Comment by nicholasgcotton** [comment] 2022-11-04 19:26
Pretty sure I also expeirenced this on iPhone and iPad last month… 100.97.85.95 and 100.118.220.114

**Comment by philletourneau** [comment] 2022-11-26 18:39
Any updates here? I don't want to be paranoid about this occurring again, and it doesn't empower me to make the best use of the service if I can't run it.

**Comment by mihaip** [comment] 2022-11-28 22:18
@philletourneau We've reproduced at least one scenario where Tailscale will keep using cell data even after WiFi is available (see https://github.com/tailscale/tailscale/issues/6152#issuecomment-1320757851). Is that a likely explanation for the behavior that you saw (i.e. is there a node that you did a large transfer while transitioning from cell data to WiFi)?

**Comment by philletourneau** [comment] 2022-11-29 03:29
I mean, it's possible something was transferring as some point, but I don't remember a specific scenario. Is there an estimated timeframe for a fix for this?

**Comment by bradfitz** [comment] 2022-11-29 05:22
> Is there an estimated timeframe for a fix for this?

Once we understand the problem, we'll fix it right away. We're trying to understand the problem.

**Comment by DentonGentry** [comment] 2023-02-18 19:36
There is considerably more investigation into this in https://github.com/tailscale/tailscale/issues/6565

Duplicate of https://github.com/tailscale/tailscale/issues/6565

**Closed by DentonGentry** 2023-02-18 19:36 UTC
Labels: OS-ios, L2 Few, P2 Aggravating, T5 Usability, bug
