### ISSUE TITLE
windows: configuring the firewall can sometimes take minutes

### ISSUE THREAD

**Issue by gordon8452** [tailscale/tailscale#785] opened 2020-09-23 20:18 UTC
**Describe the bug**
For the last few unstable updates (I think last time it ran normal was .117) I have the following error when trying to run tailscale.  Even though the error says the service is not running, checking the task manager shows that it clearly is.   I've tried reinstalling and updating to newer builds, with the same behavior.

Tailscale service is not running.
safesocket.Connect: dial tcp 127.0.0.1:41112: connectex: No connection could be made because the target machine actively refused it.

**To Reproduce**
Not sure what would reproduce this, but it happens every time I've tried to start tailscale for the last few updates (.286, .335, .432).

**Expected behavior**
Normal start

**Screenshots**
![image](https://user-images.githubusercontent.com/6172898/94063679-73638a80-fdb6-11ea-9fc5-c23328e40b16.png)
![image](https://user-images.githubusercontent.com/6172898/94063862-bfaeca80-fdb6-11ea-8ad8-56917f86e0d1.png)

**Version information:**
 - Device: Desktop
 - OS: Windows
 - OS version: 10.0.19041.508
 - Tailscale version: 1.1.432

**Additional context**

**Comment by bradfitz** [comment] 2020-09-23 20:28
Could you try 1.1.439? We made that error message dialog a bit more useful.

Also, see anything interesting in `C:\Windows\System32\config\systemprofile\AppData\Local\Tailscale\Logs` ?

**Comment by gordon8452** [comment] 2020-09-23 20:47
Error box now shows:

Failed to connect to Tailscale service.

Version 1.1.439 (g381e2c9ef)
LogID: cc230e326e122b8767c26fced1c8cdde491fef906f3b194507eca771700df5b1


Latest entries in the log show (this block repeats):

2020-09-23T16:36:52.102-04:00: 1.1M/0.0M Starting userspace wireguard engine with tun device "Tailscale"
2020-09-23T16:36:52.328-04:00: 1.3M/0.0M CreateTUN ok.
2020-09-23T16:36:52.387-04:00: 1.6M/0.0M link state: &{InterfaceIPs:map[Bluetooth Network Connection:[fe80::65b3:3f0e:894d:53bd 169.254.83.189] Ethernet 2:[fe80::2cef:34b1:3d0:6af6 192.168.0.2] Loopback Pseudo-Interface 1:[::1 127.0.0.1] vEthernet (Default Switch):[fe80::392c:e955:2249:b379 172.23.16.1]] InterfaceUp:map[Bluetooth Network Connection:false Ethernet 2:true Loopback Pseudo-Interface 1:true vEthernet (Default Switch):true] HaveV6Global:false HaveV4:true IsExpensive:false DefaultRouteInterface:Ethernet 2 (Intel(R) I211 Gigabit Network Connection) HTTPProxy:}
2020-09-23T16:36:52.417-04:00: 2.4M/0.0M Routine: event worker - started
2020-09-23T16:36:52.423-04:00: 2.5M/0.0M router: dns: using dns.windowsManager
2020-09-23T16:36:52.423-04:00: 2.7M/0.0M UDP bind has been updated
2020-09-23T16:36:58.789-04:00: 2.8M/0.0M monitor: got windows change event after 6.4018628s
2020-09-23T16:36:58.790-04:00: 2.8M/0.0M monitor: starting quick poll, waiting for WPAD change
2020-09-23T16:37:02.300-04:00: 2.8M/0.0M monitor: got windows change event after 3.5012638s
2020-09-23T16:37:02.300-04:00: 2.8M/0.0M monitor: starting quick poll, waiting for WPAD change
2020-09-23T16:38:54.749-04:00: 3.2M/0.0M router: ConfigureInterface: deleting route {169.254.255.255 ffffffff}: iphlpapi.GetIpForwardEntry2: Element not found.
2020-09-23T16:38:54.751-04:00: 3.2M/0.0M Device closing
2020-09-23T16:38:54.829-04:00: 3.2M/0.0M Routine: event worker - stopped
2020-09-23T16:38:54.829-04:00: 3.2M/0.0M Interface closed
2020-09-23T16:38:54.829-04:00: 3.2M/0.0M wgengine.NewUserspaceEngine: (try 1) deleting route {169.254.255.255 ffffffff}: iphlpapi.GetIpForwardEntry2: Element not found.

**Comment by gordon8452** [comment] 2020-09-23 21:04
After letting it run it eventually spit out an additional error, matching the log.  During the timestamps associated with each retry it caused a noticeable system stutter for a few seconds.

Tailscale backend error:

wgengine.NewUserspaceEngine: deleting route {169.254.255.255 ffffffff}: iphlpapi.GetIpForwardEntry2: Element not found.

logid: f78619d1460d7f92badbafe52222caf22d829e6ac63f8f09d586b656fe322c69

**Comment by bradfitz** [comment] 2020-09-23 21:04
@gordon8452, perfect, thanks! Build 1.1.440 is going up now with a fix for that. (And then we'll see if you hit something else....)

Download link: https://pkgs.tailscale.com/unstable/tailscale-ipn-setup-1.1.440.exe

Let me know how it goes?

**Comment by gordon8452** [comment] 2020-09-23 21:14
This seems to have resolved the issue.  Upon initial startup of .440 it continued to say the service wasn't running, though after about two minutes and another noticeable second or two of stutter it seems to have sorted itself out.  I'm not sure if the poll for WPAD change caused the stutter or not, I did not see any accompanying cpu or ram usage spikes.  The two log rows below show the time difference it took to resolve itself.

2020-09-23T17:06:43.292-04:00: 2.9M/0.0M monitor: starting quick poll, waiting for WPAD change
2020-09-23T17:08:27.944-04:00: 3.3M/0.0M magicsock: starting endpoint update (initial)

**Comment by bradfitz** [comment] 2020-09-23 22:31
@gordon8452, hmm, something is being slow that shouldn't be slow. I'm pushing 1.1.441 now with more logging around those areas:

https://pkgs.tailscale.com/unstable/tailscale-ipn-setup-1.1.441.exe

(will be available shortly)

**Comment by gordon8452** [comment] 2020-09-23 23:40
So I still get the initial error, just like last time, and it says the service isn't running, then after awhile it connects.  Here's the log from after the waiting for change (everything prior was similar to the other logs).  I guess since it still pops the initial service not running error it's not fully resolved yet.

2020-09-23T19:33:10.304-04:00: 2.8M/0.0M monitor: starting quick poll, waiting for WPAD change
2020-09-23T19:36:43.566-04:00: 2.8M/0.0M router: after 3m43.104s, removed firewall rule (wasPresent=true)
2020-09-23T19:36:43.580-04:00: 2.9M/0.0M router: monitorDefaultRoutes done after 14ms
2020-09-23T19:36:43.581-04:00: 2.9M/0.0M Clearing router settings...
2020-09-23T19:36:43.599-04:00: 3.0M/0.0M Starting link monitor...
2020-09-23T19:36:43.599-04:00: 3.0M/0.0M Starting magicsock...
2020-09-23T19:36:43.600-04:00: 3.1M/0.0M Starting resolver...
2020-09-23T19:36:43.601-04:00: 3.2M/0.0M magicsock: starting endpoint update (initial)
2020-09-23T19:36:43.606-04:00: 3.7M/0.0M Engine created.
2020-09-23T19:36:43.607-04:00: 3.7M/0.0M Listening on 127.0.0.1:41112
2020-09-23T19:36:43.624-04:00: 3.9M/0.0M magicsock: endpoints changed: 172.23.16.1:52749 (localAddresses), 192.168.0.2:52749 (localAddresses)
2020-09-23T19:36:43.635-04:00: 4.0M/0.0M Accept: UDP{169.254.83.107:51583 > 239.255.255.250:3702} 1108 ok out
2020-09-23T19:36:43.649-04:00: 4.3M/0.0M LinkChange: minor
2020-09-23T19:36:43.649-04:00: 4.4M/0.0M magicsock: starting endpoint update (link-change-minor)
2020-09-23T19:36:43.649-04:00: 4.4M/0.0M monitor: interface state changed (on poll)
2020-09-23T19:36:43.673-04:00: 4.6M/0.0M Accept: UDP{169.254.83.107:64975 > 239.255.255.250:1900} 165 ok out
2020-09-23T19:36:43.746-04:00: 4.7M/0.0M Accept: UDP{169.254.83.107:64975 > 239.255.255.250:1900} 165 ok out
2020-09-23T19:36:43.775-04:00: 5.0M/0.0M LinkChange: minor
2020-09-23T19:36:43.775-04:00: 5.0M/0.0M magicsock: starting endpoint update (link-change-minor)
2020-09-23T19:36:43.914-04:00: 5.3M/0.0M LinkChange: minor
2020-09-23T19:36:43.914-04:00: 5.3M/0.0M magicsock: starting endpoint update (link-change-minor)

**Comment by bradfitz** [comment] 2020-09-23 23:44
3m43.104s to remove a firewall rule is pretty broken. It usually takes 300ms which I still found too slow. But minutes! Will investigate.

Any super aggressive antivirus on your machine?

**Comment by gordon8452** [comment] 2020-09-23 23:45
Just the standard windows defender built in.  Any idea why it doesn't pick up that the service is running and still throws the first error popup dialog?

**Comment by bradfitz** [comment] 2020-09-23 23:50
The pop up dialog is the easy part. It pops up it it can't connect to the service in a reasonable amount of time. The service is failing to start quickly, though.

**Comment by gordon8452** [comment] 2020-09-24 12:59
Adding some additional event viewer log entries from this trying it again this morning, it seems that the firewall rule does get deleted quickly according to the event viewer.  The timestamps in the two logs don't seem to quite match either.

2020-09-24T08:15:28.612-04:00: 1.2M/0.0M Starting userspace wireguard engine with tun device "Tailscale"
...
...
2020-09-24T08:15:38.797-04:00: 2.7M/0.0M monitor: starting quick poll, waiting for WPAD change
2020-09-24T08:19:07.610-04:00: 2.7M/0.0M router: after 3m38.363s, removed firewall rule (wasPresent=false)

Source:        Microsoft-Windows-Windows Firewall With Advanced Security
Date:          9/24/2020 8:15:12 AM
Event ID:      2006
Description: A rule has been deleted in the Windows Defender Firewall exception list.
Deleted Rule:
	Rule ID:	{0844C474-66A3-4624-AB3C-F43F78BC5C05}
	Rule Name:	Tailscale-In
	Modifying User:	SYSTEM
	Modifying Application:	C:\Windows\System32\netsh.exe

Source:        Microsoft-Windows-Windows Firewall With Advanced Security
Date:          9/24/2020 8:15:23 AM
Event ID:      2010			
Description: Network profile changed on an interface.				
Adapter GUID:	{37217669-42da-4657-a55b-0d995d328250}			
Adapter Name:	iftype53_32768			
Old Profile:	Private			
New Profile:	None

Source:        Microsoft-Windows-Windows Firewall With Advanced Security
Date:          9/24/2020 8:17:15 AM
Event ID:      2002
Description: A Windows Defender Firewall setting has changed.
New Setting:
	Type:	Current Profile
	Value:	Public
	Modifying User:	NT SERVICE\mpssvc
	Modifying Application:

Source:        Microsoft-Windows-Windows Firewall With Advanced Security
Date:          9/24/2020 8:17:15 AM
Event ID:      2010
Description: Network profile changed on an interface.
Adapter GUID:	{37217669-42da-4657-a55b-0d995d328250}
Adapter Name:	iftype53_32768
Old Profile:	None
New Profile:	Private

Source:        Microsoft-Windows-Windows Firewall With Advanced Security
Date:          9/24/2020 8:19:07 AM
Event ID:      2002
Description: A Windows Defender Firewall setting has changed.
New Setting:
	Type:	Current Profile
	Value:	Private,Public
	Modifying User:	NT SERVICE\mpssvc
	Modifying Application:

Source:        Microsoft-Windows-Windows Firewall With Advanced Security		
Date:          9/24/2020 8:19:15 AM
Event ID:      2004
Description: A rule has been added to the Windows Defender Firewall exception list.	
Added Rule:
	Rule ID:	{93EB9AA5-99E2-458C-B7EB-EF2681F0AAE0}
	Rule Name:	Tailscale-In
	Origin:	Local
	Active:	Yes
	Direction:	Inbound
	Profiles:	Private
	Action:	Allow
	Application Path:
	Service Name:
	Protocol:	Any
	Security Options:	None
	Edge Traversal:	None
	Modifying User:	SYSTEM
	Modifying Application:	C:\Windows\System32\netsh.exe

**Comment by apenwarr** [comment] 2020-10-22 08:51
I was able to reproduce the slowness (at least, 18 or 22 seconds, maybe 30) on my Windows 7 and Windows 8.1 VMs in 1.1.556:

```
2020-10-22T01:34:35.491-07:00: 1.3M/0.0M monitor: got windows change event after 6.069336s
2020-10-22T01:34:35.491-07:00: 1.3M/0.0M monitor: starting quick poll, waiting for WPAD change
2020-10-22T01:34:38.982-07:00: 1.3M/0.0M monitor: got windows change event after 3.4912109s
2020-10-22T01:34:38.982-07:00: 1.3M/0.0M monitor: starting quick poll, waiting for WPAD change
2020-10-22T01:34:47.511-07:00: 1.3M/0.0M router: after 18.071s, removed firewall rule (wasPresent=true)
2020-10-22T01:34:47.516-07:00: 1.3M/0.0M router: monitorDefaultRoutes done after 5ms
```

Since this seems to be at least somewhat reproducible and new in 1.1, I'll mark it as 1.2 release blocking. As a (perhaps temporary) workaround, can we just run the firewall change operation in the background rather than blocking on it?

**Comment by bradfitz** [comment] 2021-03-02 22:13
We made this async and @danderson figured out why it's being slow, so closing this.

**Closed by bradfitz** 2021-03-02 22:13 UTC
Labels: OS-windows
