### ISSUE TITLE
Tailscale 1.44.0 on macOS Sonoma 14.0 beta 2 crashes after connecting

### ISSUE THREAD

**Issue by eon-pixel** [tailscale/tailscale#8416] opened 2023-06-22 22:22 UTC
### What is the issue?

This issue also occurs with the previous version, 1.42.0. When opening the application on 14.0 beta 2, it launches and shows in the menu bar, but after trying to connect to Tailscale, the menu no longer opens, making it impossible to disconnect without manually doing so in macOS System Settings. It also quite commonly locks up the keyboard for most open applications until Tailscale is forcefully disconnected. It worked fine in beta 1 but not so much in beta 2. 

### Steps to reproduce

1. Update/install macOS Sonoma 14.0 beta 2
2. Open Tailscale (or install, doesn't matter which version it seems)
3. Log in to Tailscale if not already done
4. Connect to Tailscale
5. Result

### Are there any recent changes that introduced the issue?

macOS 14.0 beta 1 to 2 update

### OS

macOS

### OS version

Sonoma 14.0 beta 2

### Tailscale version

1.44.0

### Bug report

BUG-b0cfb65a0d947bf65f9c0f1200f4eb449fc06153e0efb645b013f5f09499ded7-20230622222157Z-f4a7cee32e98d564

**Comment by agottardo** [comment] 2023-06-22 22:27
@eon-pixel thanks for the report, will take a look.

**Comment by elohmeier** [comment] 2023-06-23 09:22
Same issue here. I'm able to close Tailscale from the Activity Monitor.app to restore keyboard functionality after clicking on the icon in the menu bar.

If I don't click on the icon after starting Tailscale, I notice no other issues - e.g. network connectivity to other Tailscale hosts is working fine.

**Comment by JVH-Insurance** [comment] 2023-06-25 09:13
Same issue here, Tailscale unusable since no keyboard access anymore !!
When I manually stop the VPN connection, I regain keyboard access, but can't Remote Access any of my other Macs again.

Restarting Tailscale blocks my keyboard input again, pls HELP.

**Comment by slobodan-jeeves** [comment] 2023-06-26 12:59
Temporary workaround is not to click on the Tailscale icon, and use the [Tailscale CLI](https://tailscale.com/kb/1080/cli/#using-the-cli).

Using the terminal for `tailscale up` and `tailscale down` is all I need for now.

**Comment by JVH-Insurance** [comment] 2023-06-26 14:06
The major issue is that the keyboard input does not works anymore when tailscale is enabled !!Verstuurd via iCloud vanaf mijn iPhone 8 Plus, iPhoneOS 17 Dev. Op 26 jun. 2023 om 15:00 heeft Slobodan Stanojevikj ***@***.***> het volgende geschreven:﻿
Temporary workaround is not to click on the Tailscale icon, and use the Tailscale CLI.
Using the terminal for tailscale up and tailscale down is all I need for now.

**Comment by slobodan-jeeves** [comment] 2023-06-26 16:43
Oh, that's bad! For me the keyboard stops working if I click on the Tailscale icon, but everything seems fine from terminal with CLI. If I click the icon I need to kill the Tailscale process 😞

**Comment by Hl2run** [comment] 2023-07-03 13:39
Same here, keyboard stops working when starting Tailscale. Weird bug...

Sonoma, developer beta 2

**Comment by cheesycod** [comment] 2023-07-03 17:35
I can reproduce

**Comment by rstoeber** [comment] 2023-07-03 23:04
Yes, exactly the same thing here. Keyboard stops working after launching Tailscale on macOS Sonoma 14.0 beta 2 (MacBook Pro M1).

I didn't see this for some reason so I just posted a duplicate report. Will try to delete that.

**Comment by agottardo** [comment] 2023-07-05 03:00
Thanks for all your reports. Looks like this is a regression caused by a change in macOS Sonoma.

As soon as you click to open the menu, AppKit tries to compute the height of the top menu item, but it ends up throwing an out-of-bounds exception (stack trace attached here in case another developer stumbles upon it). And it looks like as a side-effect the main thread is hanging, causing the behaviour you're seeing.

I'm working to come up with a workaround, in case Apple doesn't fix this promptly in the next macOS beta update. I'll ship it in a TestFlight update as soon as it's ready to go.

```
*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
(
    0   CoreFoundation                      0x0000000183568a80 __exceptionPreprocess + 176
    1   libobjc.A.dylib                     0x0000000183061fa4 objc_exception_throw + 60
    2   CoreFoundation                      0x00000001834950cc -[NSTaggedPointerString hash] + 0
    3   AppKit                              0x00000001871b7760 -[NSContextMenuImpl _updateHeightForMenuItemAtIndex:withNewPreferredHeight:] + 84
    4   AppKit                              0x00000001871b793c -[NSContextMenuImpl _updateSizeEstimateForItemAtIndex:includingHeight:] + 248
    5   CoreFoundation                      0x00000001834e8ca0 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
    6   CoreFoundation                      0x000000018357cc2c ___CFXRegistrationPost_block_invoke + 88
    7   CoreFoundation                      0x000000018357cb74 _CFXRegistrationPost + 440
    8   CoreFoundation                      0x00000001834b78f0 _CFXNotificationPost + 764
    9   AppKit                              0x0000000186c39660 -[NSView _postFrameChangeNotification] + 240
    10  AppKit                              0x0000000186c344d8 -[NSView setFrameSize:] + 1696
    11  AppKit                              0x0000000186c4208c -[NSView setFrame:] + 304
    12  AppKit                              0x0000000186c90ac8 NSViewActuallyUpdateFrameFromLayoutEngine + 236
    13  AppKit                              0x000000018764f090 __56-[NSView _layoutSubtreeIfNeededAndAllowTemporaryEngine:]_block_invoke + 756
    14  AppKit                              0x0000000186c4b890 NSPerformVisuallyAtomicChange + 108
    15  AppKit                              0x0000000186c4ff08 -[NSView _layoutSubtreeIfNeededAndAllowTemporaryEngine:] + 100
    16  AppKit                              0x0000000186c4b890 NSPerformVisuallyAtomicChange + 108
    17  AppKit                              0x0000000186c4fe98 -[NSView layoutSubtreeIfNeeded] + 96
    18  AppKit                              0x00000001871b86ec -[NSContextMenuImpl _optimalSizeForMenuItemAtIndex:] + 1840
    19  AppKit                              0x00000001871ba1c8 -[NSContextMenuImpl _recalculateOptimalSize] + 412
    20  AppKit                              0x00000001871b2cc0 __32-[NSContextMenuImpl _reloadData]_block_invoke + 40
    21  AppKit                              0x00000001873c3fa4 -[NSCocoaMenuImpl forEachLinkedMenuDo:includingSelf:] + 184
    22  AppKit                              0x00000001871b2b58 -[NSContextMenuImpl _reloadData] + 44
    23  AppKit                              0x00000001871b2b0c -[NSContextMenuImpl _populateMenuPresentationIfNeeded] + 60
    24  AppKit                              0x00000001871b2ab0 -[NSContextMenuImpl _prepareForPresentation] + 24
    25  AppKit                              0x00000001871b0eb0 -[NSContextMenuImpl viewWillAppear] + 340
    26  AppKit                              0x00000001872b0c80 -[NSPopupMenuWindow _orderFrontWithParentWindow:screenFrame:] + 88
    27  AppKit                              0x00000001872b0af8 -[NSPopupMenuWindow _commonPresentFromView:animated:] + 536
    28  AppKit                              0x00000001872b08a8 -[NSPopupMenuWindow presentAsPopUpRelativeToView:animated:] + 88
    29  AppKit                              0x00000001871b05c8 +[NSContextMenuImpl presentPopup:fromView:withContext:animated:] + 500
    30  AppKit                              0x00000001873ceaf0 _NSPopUpMenu + 1852
    31  AppKit                              0x00000001873ce2e0 -[NSCocoaMenuImpl popUpMenu:atLocation:width:view:selectedItemIndexProvider:font:positioningRect:flags:options:] + 432
    32  AppKit                              0x00000001873ce108 -[NSCocoaMenuImpl popUpMenu:atLocation:width:forView:withSelectedItem:withFont:withFlags:withOptions:] + 96
    33  AppKit                              0x00000001873986a0 +[NSStatusBarButtonCell popUpStatusBarMenu:ofItem:ofBar:inRect:ofView:withEvent:] + 320
    34  AppKit                              0x0000000187397a98 -[NSStatusBarButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 168
    35  AppKit                              0x0000000186daa55c -[NSControl mouseDown:] + 448
    36  AppKit                              0x0000000186da9328 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 3472
    37  AppKit                              0x0000000186d34c5c -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 364
    38  AppKit                              0x0000000186d34a24 -[NSWindow(NSEventRouting) sendEvent:] + 268
    39  AppKit                              0x0000000187399cb4 -[NSStatusBarWindow sendEvent:] + 704
    40  AppKit                              0x00000001873a410c -[NSApplication(NSEventRouting) sendEvent:] + 1556
    41  Tailscale                           0x0000000104cb6e1c $s9Tailscale11ApplicationC9sendEventyySo7NSEventCF + 1688
    42  Tailscale                           0x0000000104cb6f7c $s9Tailscale11ApplicationC9sendEventyySo7NSEventCFTo + 52
    43  AppKit                              0x000000018700054c -[NSApplication _handleEvent:] + 60
    44  AppKit                              0x0000000186bfc7c0 -[NSApplication run] + 512
    45  AppKit                              0x0000000186bd3c44 NSApplicationMain + 880
    46  Tailscale                           0x0000000104cb7924 main + 56
    47  dyld                                0x000000018309d058 start + 2224
)
```

**Comment by cheesycod** [comment] 2023-07-05 18:02
@agottardo Seems like dev beta 3 fixes this

**Comment by cheesycod** [comment] 2023-07-05 18:03
Still one more bug, clicking 'About' leads to a couple seconds of lag

**Comment by agottardo** [comment] 2023-07-05 18:06
> @agottardo Seems like dev beta 3 fixes this

> Still one more bug, clicking 'About' leads to a couple seconds of lag

Oh lovely! I was already in swizzling hell. I'll install beta 3, verify and then close.

Also yeah, I noticed the lag opening the About window too. I'll be tracking it.

**Comment by agottardo** [comment] 2023-07-05 18:21
Verified as fixed in beta 3.

**Closed by agottardo** 2023-07-05 18:21 UTC
Labels: OS-macos, L3 Some users, P3 Can't get started, T8 Crash, bug

**Comment by roberttoups** [comment] 2023-07-05 20:25
I am using Tailscale Version 1.44.0 (App Store), which now works with macOS Sonoma Beta 3. Previously it failed with macOS Sonoma Beta 2, as mentioned above.

**Comment by bobbyl140** [comment] 2023-07-05 20:34
Me too, seems all fixed. 

> Still one more bug, clicking 'About' leads to a couple seconds of lag

I am also noticing this but to be honest I don't mind it so long as the Menu Bar app opens.
