### ISSUE TITLE
FR: get through MITM offering an invalid *.tailscale.com certificate

### ISSUE THREAD

**Issue by dfo-db** [tailscale/tailscale#7354] opened 2023-02-23 18:32 UTC
### What is the issue?

Sorry I would have put this through troubleshooting but I cannot access any Tailscale domain, including through a browser.

This has happened a few times, where I use public wifi, such as a library, and I get the following on tailscale status:

`Health check:`
     - `not logged in, last login error=register request: Post "https://controlplane.tailscale.com/machine/register": all connection attempts failed (HTTP: unexpected HTTP response: 200 OK, HTTPS: x509: certificate signed by unknown authority)`

I assume this is happening because they are blocking all tailscale domains on their network.

I just want to connect to my server!

Is there any alternative to use for logging in?

### Steps to reproduce

1. Use public wifi
2. Check tailscale status

### Are there any recent changes that introduced the issue?

No

### OS

Linux

### OS version

Ubuntu Server 22.10

### Tailscale version

1.36.0

**Comment by DentonGentry** [comment] 2023-06-04 04:04
Duplicate of https://github.com/tailscale/tailscale/issues/3198

**Closed by DentonGentry** 2023-06-04 04:04 UTC
Labels: L3 Some users, P2 Aggravating, waiting-for-info, T0 New feature, fr
