### ISSUE TITLE
Don’t make a “My Devices” submenu if they’re all my devices

### ISSUE THREAD

**Issue by avidrissman** [tailscale/tailscale#6830] opened 2022-12-22 19:22 UTC
### What is the issue?

The Tailscale menu’s structure is:

Main
> identity stuff
> This Device: namenamename
> Network Devices
>> My Devices
>>> device1
>>> device2

etc

I am a one-person Tailscale, and even though I’m signed in via Google with a Apps For Your Domain domain on “drissman.com”, right now and for the foreseeable future _all_ of the network devices will be my devices.

I vaguely remember reading somewhere that if you sign in via gmail or github the Mac UI collapses the “my devices” submenu directly into the “network devices” submenu. Can you do so in the case where all the devices are “my devices”?

### OS

macOS

### OS version

13.1 (22C65)

### Tailscale version

Version 1.34.1 (macsys)

**Comment by DentonGentry** [comment] 2022-12-22 19:35
I do expect to implement something like this as part of the next UI refresh, but it is not something we'll be working on just yet.

Duplicate of https://github.com/tailscale/tailscale/issues/3319

**Closed by DentonGentry** 2022-12-22 19:35 UTC
Labels: needs-triage, bug, needs-dedup
