### ISSUE TITLE
Tailscale DNS resolution blocked Lumo (UK train) captive portal

### ISSUE THREAD

**Issue by ebroder** [tailscale/tailscale#4978] opened 2022-06-29 20:46 UTC
### What is the issue?

Lumo (UK train carrier) has a two-stage captive portal. The first stage allows access to the on-train media server and the second stage allows access to the internet. macOS's captive portal detection closes after the first stage, and clearing the second stage requires opening a browser and attempting to navigate to a website.

Having the Tailscale agent running with MagicDNS enabled prevents Lumo's DNS hijacking from working, which results in the browser hanging when attempting to clear the second stage of their captive portal.

### Steps to reproduce

Connect to Lumo wifi network. Use macOS captive portal detection to accept initial terms. Attempt to open http://neverssl.com or similar.

### OS

macOS

### OS version

macOS Monterey 12.4 (21F79)

### Tailscale version

1.26.1

### Bug report

BUG-d4e69d6c6f2117a3e7a3404f81e0866aa747a49fd792a7be33d28a8ca020c696-20220629204024Z-b3d63098742221ec

**Comment by danderson** [comment] 2022-06-29 20:52
If you're still on that network: could you check, without tailscale, if `ipv4only.arpa` is hijacked as well? We'll need a target name to probe in order to find captive portals, and ipv4only.arpa is nicely neutral (not owned by a private corp, no privacy worries).

**Comment by danderson** [comment] 2022-06-29 21:26
Going to classify this as a feature request since we currently make no efforts at all to detect captive portals, so there's a fair bit of new legwork required to make this just work.

**Comment by ebroder** [comment] 2022-06-30 07:33
Unfortunately I'm not on the network anymore - I didn't think to file a ticket until a couple of days after my train ride. (If it does come up that checking the logs would be useful, I was on the train on June 28, roughly 10:00-2:00 UTC)

**Comment by DAlperin** [comment] 2022-07-09 18:08
I'd like to bump this. I couldn't connect to any captive portal networks on a flight or hotel until I took back control of dns from tailscale. This is a bit of a usability problem when travelling.

**Comment by DentonGentry** [comment] 2022-07-10 04:52
Duplicate of https://github.com/tailscale/tailscale/issues/1634

**Closed by DentonGentry** 2022-07-10 04:52 UTC
Labels: connectivity, fr
