### ISSUE TITLE
Mutually-shared devices between two networks lose connectivity

### ISSUE THREAD

**Issue by TJC** [tailscale/tailscale#8485] opened 2023-06-29 02:25 UTC
### What is the issue?

We have two separate Tailscale accounts / networks.
We have these devices:
Account 1 - Device 1.
Account 2 - Device 2.

Each device has been shared, so it's visible on the other account.

When logging into the devices, one one of them a `tailscale ping` to the other device reports success. However a regular Linux `ping` fails.
On the other device, both succeed.

If we logout on one device, and add it directly to the different account, then both devices work fine.
(ie. Account 1 has both Device 1 and 2)

This has been duplicated on two different pairs of devices, so I don't think it was a one off. 

### OS

Linux

### OS version

HiSilicon Linux

### Tailscale version

1.42

### Other software

Nothing else is touching routing or iptables. (Apart from the initial DHCP client)

### Bug report

BUG-544fa8b3d77a84a8ef31df404e4cb98d293ed89fd8980f00d70589daf7c0c223-20230629022147Z-bf659d81cf14286a

**Comment by DentonGentry** [comment] 2023-07-09 03:36
Possibly https://github.com/tailscale/tailscale/issues/1453

**Comment by DentonGentry** [comment] 2023-07-09 08:30
Duplicate of https://github.com/tailscale/tailscale/issues/1453

**Closed by DentonGentry** 2023-07-09 08:30 UTC
Labels: needs-triage, bug
