### ISSUE TITLE
FR: More readable and easier to remember DNS suffix

### ISSUE THREAD

**Issue by fnfontana** [tailscale/tailscale#4758] opened 2022-05-30 19:07 UTC
### What are you trying to do?

Today I've downloaded and set up the Tailscale VPN and I found it awesome, very easy to install and make use of it. 
I have used my Google account to sign in, and after enable the MagicDNS feature, my DNS suffix is something like: `username.gmail.com.beta.tailscale.net`, 

### How should we solve this?

I think it will be less confusing if "gmail.com.beta" was removed from the string, becoming `username.tailscale.net`.

**Comment by DentonGentry** [comment] 2022-05-30 19:10
Duplicate of https://github.com/tailscale/tailscale/issues/1543

**Closed by DentonGentry** 2022-05-30 19:10 UTC
Labels: needs-triage, fr
