### ISSUE TITLE
FR: Add iCloud as an authentication provider

### ISSUE THREAD

**Issue by vernonstinebaker** [tailscale/tailscale#4143] opened 2022-03-11 00:46 UTC
### What are you trying to do?

1. Google services are blocked in some locations, making authentication difficult when traveling internationally.
2. Tailscale works great on MacOS, iOS, and iPadOS. Further integration with the Apple ecosystem would create an even smoother experience on these devices.

### How should we solve this?

Add Apple's iCloud as an alternative authentication provider.

### What is the impact of not solving this?

Unable to authenticate to Tailscale in some circumstances, particularly when traveling.

**Comment by DentonGentry** [comment] 2022-03-11 00:47
Duplicate of https://github.com/tailscale/tailscale/issues/598

**Closed by DentonGentry** 2022-03-11 00:47 UTC
Labels: needs-triage, fr
