### ISSUE TITLE
Can't start tailscaled on Linux read-only filesystem

### ISSUE THREAD

**Issue by miguelfazenda** [tailscale/tailscale#3843] opened 2022-01-30 17:05 UTC
### What is the issue?

Hello!
I have a Raspberry Pi that has a read-only filesystem in order to prevent the SD card from getting corrupted. Running version 1.16.2 (tailscale commit: f449111792f662c8552514cf3691c3c1bd7f38e4).

When I try and run 
 `sudo systemctl start tailscaled.service`
I get
```
Job for tailscaled.service failed because the control process exited with error code.
See "systemctl status tailscaled.service" and "journalctl -xe" for details.
```

The journalctl shows the following log:
```
...
-- A start job for unit tailscaled.service has finished with a failure.
jan 30 16:54:08 raspberrypi systemd[1]: tailscaled.service: Service RestartSec=100ms expired, scheduling restart.
jan 30 16:54:08 raspberrypi systemd[1]: tailscaled.service: Scheduled restart job, restart counter is at 4.
-- Automatic restarting of the unit tailscaled.service has been scheduled, as the result for
-- Subject: A stop job for unit tailscaled.service has finished
-- A stop job for unit tailscaled.service has finished.
-- Subject: A start job for unit tailscaled.service has begun execution
-- A start job for unit tailscaled.service has begun execution.
jan 30 16:54:08 raspberrypi systemd[6538]: tailscaled.service: Failed to set up special execution directory in /var/lib: Read-only file system
jan 30 16:54:08 raspberrypi systemd[6538]: tailscaled.service: Failed at step STATE_DIRECTORY spawning /usr/sbin/tailscaled: Read-only file system
-- Subject: Process /usr/sbin/tailscaled could not be executed
-- The process /usr/sbin/tailscaled could not be executed and failed.
jan 30 16:54:08 raspberrypi systemd[1]: tailscaled.service: Control process exited, code=exited, status=238/STATE_DIRECTORY
-- An ExecStartPre= process belonging to unit tailscaled.service has exited.
jan 30 16:54:08 raspberrypi systemd[6539]: tailscaled.service: Failed to set up special execution directory in /var/lib: Read-only file system
jan 30 16:54:08 raspberrypi systemd[6539]: tailscaled.service: Failed at step STATE_DIRECTORY spawning /usr/sbin/tailscaled: Read-only file system
-- Subject: Process /usr/sbin/tailscaled could not be executed
-- The process /usr/sbin/tailscaled could not be executed and failed.
jan 30 16:54:08 raspberrypi systemd[1]: tailscaled.service: Control process exited, code=exited, status=238/STATE_DIRECTORY
-- An ExecStopPost= process belonging to unit tailscaled.service has exited.
jan 30 16:54:08 raspberrypi systemd[1]: tailscaled.service: Failed with result 'exit-code'.
-- The unit tailscaled.service has entered the 'failed' state with result 'exit-code'.
-- Subject: A start job for unit tailscaled.service has failed
-- A start job for unit tailscaled.service has finished with a failure.
jan 30 16:54:08 raspberrypi systemd[1]: tailscaled.service: Service RestartSec=100ms expired, scheduling restart.
jan 30 16:54:08 raspberrypi systemd[1]: tailscaled.service: Scheduled restart job, restart counter is at 5.
-- Automatic restarting of the unit tailscaled.service has been scheduled, as the result for
-- Subject: A stop job for unit tailscaled.service has finished
-- A stop job for unit tailscaled.service has finished.
jan 30 16:54:08 raspberrypi systemd[1]: tailscaled.service: Start request repeated too quickly.
jan 30 16:54:08 raspberrypi systemd[1]: tailscaled.service: Failed with result 'exit-code'.
-- The unit tailscaled.service has entered the 'failed' state with result 'exit-code'.
-- Subject: A start job for unit tailscaled.service has failed
-- A start job for unit tailscaled.service has finished with a failure.
```

Anyone has any clue of what could solve this? I tried creating a sym-link from /var/lib/tailscale to a read-write folder, but the error persisted. When I set the filesystem to read-write mode it runs just fine.

### Steps to reproduce

1. Set the filesystem to read-only (I followed [https://medium.com/swlh/make-your-raspberry-pi-file-system-read-only-raspbian-buster-c558694de79](https://medium.com/swlh/make-your-raspberry-pi-file-system-read-only-raspbian-buster-c558694de79) for my Raspberry Pi on Raspbian Buster)
2. Run `sudo systemctl start tailscaled.service`

### OS

Linux

### OS version

Raspbian Buster

### Tailscale version

1.16.2

**Comment by DentonGentry** [comment] 2022-01-30 17:06
tailscaled has to be able to write its node keys into a filesystem.

**Comment by miguelfazenda** [comment] 2022-01-30 17:08
Is it possible to write on a tmpfs?

**Comment by DentonGentry** [comment] 2022-01-30 17:10
The node key needs to be persistent, tmpfs is not likely to be pleasant as it will need to be reauthenticated afresh on every reboot.

A loopback mount of a writable filesystem on /var/lib/tailscale might work.

**Comment by miguelfazenda** [comment] 2022-01-30 17:37
Thanks for the reply.
Doing as suggested I was able to do make tailscale run, by running the commands bellow.
However, I can't ping the device, although it shows as connected in the tailscale admin console, which is very odd.

```
sudo mount --bind /media/disk/tailscale/ /var/lib/tailscale
sudo mount --bind /media/disk/tailscale-cache/ /var/cache/tailscale
```
or adding to /etc/fstab
```
/media/disk/tailscale/ /var/lib/tailscale none defaults,bind 0 0
/media/disk/tailscale-cache/ /var/cache/tailscale none defaults,bind 0 0
```

**Comment by DentonGentry** [comment] 2022-03-27 05:47
Remaining work is a duplicate of https://github.com/tailscale/tailscale/issues/2936

**Closed by DentonGentry** 2022-03-27 05:47 UTC
Labels: OS-linux, L1 Very few, P3 Can't get started, T5 Usability, bug
