### ISSUE TITLE
Android network stops working after going through subway

### ISSUE THREAD

**Issue by jglamine** [tailscale/tailscale#8312] opened 2023-06-09 00:04 UTC
### What is the issue?

This is an odd one, but I'm able to consistently reproduce it and it seems like tailscale is the cause.

I have a Pixel 7 phone with tailscale set as the vpn. I'm not using an exit node. When I go though the subway and loose cellular connection, internet won't work once my phone re-connects to the cell tower. It shows full bars but web pages don't load. Rebooting the phone fixes the problem.

The odd thing is this only happens if I have tailscale enabled. If I disconnect from tailscale, going through subway tunnels works fine - it reconnects once I'm out of the tunnel and I don't need to reboot the phone.

This also sometimes happens when moving from wifi to the mobile network - for example when leaving a building.

### Steps to reproduce

1. Enable the tailscale vpn on android.
2. Verify that you can load web pages
3. Go somewhere without cell service - for example a subway or put your phone in a faraday cage
4. Observe that your phone has no cell signal.
5. Try to load a web page - observe that it fails.
6. Go back to somewhere where there is cell service.
7. Observe that your phone claims to be connected with full bars
8. Try to load a web page - observe that it fails
9. Disconnect from tailscale - web pages should work again. If not, rebooting the phone fixes the problem.

### Are there any recent changes that introduced the issue?

I got a new phone 1-2 months ago and that's when I started seeing the issue.

### OS

Android

### OS version

Android 13 - May 5, 2023 security update

### Tailscale version

Tailscale 1.40.0-t9bdaece3d-ge0ba590be3e

**Comment by RaheelJameel** [comment] 2023-08-21 11:50
I am also facing a similar issue on the Android client. I would like to add more info about this.

It appears that the Android client is not able to re-initiate an interrupted connection.

Example:

1. Start the Tailscale Android app and turn on the VPN.
2. Verify that the Tailscale app shows "Active" status and you are able to connect to clients and/or services in the Tailscale network.
3. Switch Wi-Fi networks or turn off Wi-Fi and then turn it back on again
4. Try to connect to clients and/or services in the Tailscale network, the connection will fail.
5. Check the Tailscale app, it will still show "Active"
6. Turn off the VPN in the app and then turn it on again
7. Now the Tailscale app will show the status "Starting..." and this never changes to "Active".
8. Turn off the VPN in the app and then close the app. 
9. Open the app again and turn on the VPN.
10. Verify that the Tailscale app shows "Active" status and you are able to connect to clients and/or services in the Tailscale network.
11. Sometimes even on closing and reopening the app the connection still fails and you need to go to Android settings and force stop the Taiscale app and then try again.

Tested these app versions and both have the issue:
1.44.1-ta377e1363-g584245cc823
1.48.0-t77c732357-g388b71affe8 (latest at time of comment)

**Comment by taydy00** [comment] 2023-09-05 15:28
I have this same issue, GrapheneOS (Android 13) on a Pixel 6. It makes it hard to switch fully to Tailscale, and I still have to leave my Home Assistant and other services exposed to the open web until this can be fixed.

**Comment by kelivel** [comment] 2023-09-07 20:49
I'll close this one as a duplicate of https://github.com/tailscale/tailscale/issues/8283. @taydy00 and I did some troubleshooting over email and for them, overriding their tailnet's local DNS settings seemed to help in the interim. We'll continue investigating on #8283.

**Closed by kelivel** 2023-09-07 20:49 UTC
Labels: bug, needs-triage-support

**Comment by lucaslgr** [comment] 2024-05-05 20:03
I'm having this issue nowadays, but it happens for all my devices, not only android ones. I've configured a local DNS IP and marked to override it in Tailscale but nothing has changed. At the first time that I setup my local server, everything was working properly when I was accessing my local applications through another remote networks using Tailscale VPN.
Anyone could help me with this issue please?
