### ISSUE TITLE
Linux v1.0.0: Locked out after update

### ISSUE THREAD

**Issue by dkerwin** [tailscale/tailscale#621] opened 2020-07-30 08:19 UTC
**Describe the bug**

I've updated a bunch of linux systems to v1.0.0 and after the update it was no longer possible to reach these systems. Exposed subnets were not reachable too. The status output looked ok and I suspect a problem with the ACL.

**To Reproduce**
1. Update linux system to v1.0.0
2. Try to connect
3. Connection fails

**Expected behavior**
Connect to the machines and exposed services as normal.

**Version information:**
 - OS: Debian Buster
 - OS version: 10.4
 - Tailscale version: 1.0.0

**Comment by apenwarr** [comment] 2020-07-30 08:45
Sorry. v1.0.0 was released prematurely. I've un-launched it for now. Please downgrade to v0.100 for now. Sorry for the mess :(

**Comment by dkerwin** [comment] 2020-07-30 08:51
I've already rolled back. I would suggest to remove the `Update Available` tag from the admin UI too. Thanks.

**Comment by danderson** [comment] 2020-07-30 15:37
I'm unable to reproduce this :/ . I've tried to get a failure on Debian Buster, ubuntu 18.04 and NixOS, and they all seem to upgrade happily. I must be missing something compared to your environment.

@dkerwin can you give me the name or IP of one of your machine that failed after the upgrade? You can send to support@tailscale.com if you prefer to not say in a public bug.

**Comment by danderson** [comment] 2020-07-30 16:17
I think I have an idea of what is wrong, it might be an issue where the client didn't correctly update the network engine on a change notification from the control plane, so network configs weren't installed properly. It's fixed at head already, but I'm trying to reproduce now to confirm this.

**Comment by dkerwin** [comment] 2020-08-04 07:23
I've just updated to `1.0.3-gc2dfc2bc3` and it looks good so far. Access to exposed subnets and individual hosts works as expected.

**Comment by bradfitz** [comment] 2020-08-04 15:09
I'll close this but let us know if anything comes up. Thanks!

**Closed by bradfitz** 2020-08-04 15:09 UTC
Labels: L5 All users, P4 Halts deployment, T7 Crash
