### ISSUE TITLE
windows: adding route fd7a:115c:a1e0:ab12:4843:cd96:6240:264/128: The object already exists

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1185] opened 2021-01-21 18:49 UTC
Seen on a Windows v1.3.147 machine, but not when they were running v1.2.x:

```
2021-01-21 10:27:09.1492079 -0500 -0500: router: ConfigureInterface: encountered multiple errors:
2021-01-21 10:27:09.1492079 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6240:264/128: The object already exists.
2021-01-21 10:27:09.1492079 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6245:b35e/128: The object already exists.
2021-01-21 10:27:09.1492079 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6247:667c/128: The object already exists.
2021-01-21 10:27:09.1492079 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6249:2e1d/128: The object already exists.
2021-01-21 10:27:09.1492079 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6249:ab44/128: The object already exists.
2021-01-21 10:27:09.1492079 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:624d:825f/128: The object already exists.
2021-01-21 10:27:09.1492079 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:624f:904c/128: The object already exists.
2021-01-21 10:27:09.1492079 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6250:ef35/128: The object already exists.
2021-01-21 10:27:09.1492079 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6253:23e/128: The object already exists.
2021-01-21 10:27:09.1492079 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6253:e27f/128: The object already exists.
2021-01-21 10:27:09.1492079 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6253:fc5d/128: The object already exists.
2021-01-21 10:27:09.1492079 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6255:83a/128: The object already exists.
2021-01-21 10:27:09.1492079 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6258:1d70/128: The object already exists.
2021-01-21 10:27:09.1492079 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6258:6728/128: The object already exists.
2021-01-21 10:27:09.1492079 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:625b:2226/128: The object already exists.
2021-01-21 10:27:09.1502089 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:625d:c24f/128: The object already exists.
2021-01-21 10:27:09.1502089 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6260:430b/128: The object already exists.
2021-01-21 10:27:09.1502089 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6264:6d40/128: The object already exists.
2021-01-21 10:27:09.1502089 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6265:6667/128: The object already exists.
2021-01-21 10:27:09.1502089 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6273:1a6b/128: The object already exists.
2021-01-21 10:27:09.1502089 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6273:ef37/128: The object already exists.
2021-01-21 10:27:09.1502089 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:6274:8e05/128: The object already exists.
2021-01-21 10:27:09.1502089 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:627a:e332/128: The object already exists.
2021-01-21 10:27:09.1502089 -0500 -0500:        ... adding route fd7a:115c:a1e0:ab12:4843:cd96:627e:da21/128: The object already exists.
```

/cc @danderson @peske

**Comment by danderson** [comment] 2021-01-21 18:59
That's the new IPv6 programming, but I'm puzzled as to why we're trying to readd already existing routes, and why it seems to break for v6 but not v4. Will dig in a bit.

**Comment by bradfitz** [comment] 2021-01-21 19:04
Is control already sending v6 routes to everybody?

Maybe we need to stop doing that for Windows clients.

**Comment by danderson** [comment] 2021-01-21 19:06
It's sending v6 routes to sufficiently recent windows clients (some 1.3+ version). Argh, but we released a 1.3 as stable, didn't we. Great.

Well, I did test that setup on my windows VM and didn't encounter this, so it still _should_ have been fine, but evidently not. Let's turn windows back off until I can debug further.

**Comment by bradfitz** [comment] 2021-01-21 19:10
And we'll have to bump mapver again before turning it back on. Should we make this a 1.4.0 blocker? How much IPv6 do we care about for 1.4?

/cc @crawshaw @josharian

**Comment by danderson** [comment] 2021-01-21 19:12
Current plan is to not block on v6/default routing for 1.4, some late requirements changes have added a bunch of work. So I'd say let's turn off v6 configuration in control (there's a mapcap for that), and I'll turn it back on later and figure out what makes windows mad.

**Comment by peske** [comment] 2021-01-29 08:56
If you take a look at the method where this error happens (https://github.com/tailscale/tailscale/blob/main/wgengine/router/ifconfig_windows.go#L664), you will see that the method first loads the existing routes from Windows API, then creates a diff between the existing list and the desired list, and then deletes / adds routes based on the diff. In other words, error "Object already exist" should not happen ever (we've queried the existing routes just few lines above).

So I have no doubt that the problem is that we're not getting the correct list of the existing routes form Windows, which is very similar to https://github.com/tailscale/tailscale/issues/1187 where we don't get the interface itself. The key question is why it happens - is it about our wrong usage of the Windows API, or some Windows APIs are simply _not ready yet_.

I wouldn't be surprised if this happens only in unattended mode as the other one. Also it may happen that this issue will go away with the latest fix made by @bradfitz , where he implemented attempting calling the same API again and again until it magically starts working (which happens after about minute or so).

**Comment by peske** [comment] 2021-01-29 09:13
It would be great if you have to provide additional info about this issue:
- Does this happen only for IPv6 and not for IPv4? If so it may turn out to be a different cause...
- Does this happen only during an early reboot, or it happens also later, if the agent is started manually when Windows settles down?

If it turns out that this is only during early boot, then it can be fixed by extending @bradfitz 's patch to include more methods. To introduce some kind of _initialization_ in `ifconfig_windows.go` and access the problematic methods only after we've ensured that it's _initialized_ (that the Windows API started working).
On the other hand, if it turns out to be that it happens always for IPv6, then I will recheck and retest our API access to find the error.

**Comment by danderson** [comment] 2021-02-05 23:00
@bradfitz got more details on where you saw this failure, per ^ ? I'm trying to reproduce on my own machines, but so far, no luck, everything works fine.

**Comment by danderson** [comment] 2021-02-05 23:29
Just to confirm again: unable to reproduce this at head, with IPv6 configuration enabled. So, ENEEDMOREINFO.

**Comment by bradfitz** [comment] 2021-02-08 19:48
It was a customer issue.

You can look it up by the IP addresses above.

**Closed** 2021-02-25 04:41 UTC
Labels: OS-windows

**Comment by Omarorj3** [comment] 2025-04-11 04:31
fd7a:115c:a1e0::b001:1c06
