### ISSUE TITLE
sporadically can’t resolve MagicDNS hostnames using Tailscaled-on-macOS

### ISSUE THREAD

**Issue by sellout** [tailscale/tailscale#7000] opened 2023-01-18 20:00 UTC
### What is the issue?

I am online and have tailscaled running. Everything will work fine for days at a time, then suddenly I just can’t access hosts via MagicDNS names (connecting to the IP listed in https://login.tailscale.com/admin/machines continues to work). 
```sh
$ ssh <hostname>
ssh: Could not resolve hostname <hostname>: nodename nor servname provided, or not known
$ 
```
It’s never been consistent, so it might just be my imagination, but I toggle wifi off and on, restart `tailscaled`, maybe poke at some other things, and then it starts working again. But sometimes it doesn’t, or sometimes it just stops working a few times in a day.

`cat /etc/resolv.conf`
```
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
search tail74a3.ts.net
nameserver 100.100.100.100
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844
```
`scutil --dns`
```
DNS configuration

resolver #1
  search domain[0] : tail74a3.ts.net
  nameserver[0] : 100.100.100.100
  nameserver[1] : 8.8.8.8
  nameserver[2] : 8.8.4.4
  nameserver[3] : 2001:4860:4860::8888
  nameserver[4] : 2001:4860:4860::8844
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #2
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300000

resolver #3
  domain   : 254.169.in-addr.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300200

resolver #4
  domain   : 8.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300400

resolver #5
  domain   : 9.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300600

resolver #6
  domain   : a.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300800

resolver #7
  domain   : b.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 301000

resolver #8
  domain   : search.tailscale
  search domain[0] : tail74a3.ts.net
  search domain[1] : sellout.github.beta.tailscale.net
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)

DNS configuration (for scoped queries)

resolver #1
  search domain[0] : tail74a3.ts.net
  nameserver[0] : 100.100.100.100
  nameserver[1] : 8.8.8.8
  nameserver[2] : 8.8.4.4
  nameserver[3] : 2001:4860:4860::8888
  nameserver[4] : 2001:4860:4860::8844
  if_index : 11 (en0)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)
```
I notice in this that I have two tailscale-related resolvers. I’m _guessing_ that `#1` is my explicit system configuration and `#8` is perhaps added by tailscaled itself (although it has no nameservers listed, even though I have “Override local DNS” enabled on https://login.tailscale.com/admin/dns).

### Steps to reproduce

I’m not sure. It seems to be random as far as I can tell.

### Are there any recent changes that introduced the issue?

I don’t think so. This has been happening for a while (months), but I end up working around it, or getting my weird wifi/tailscaled dance to appear to fix it.

### OS

macOS

### OS version

macOS Ventura 13.1

### Tailscale version

1.32.3 (installed via nix-darwin)

### Bug report

BUG-e671486f71ef5ae52de9f6a210001dfbcd11de8b9df90718e9795cf8f5cf2b05-20230118195332Z-4d911bcd985d45e1

**Comment by DentonGentry** [comment] 2023-02-11 21:53
>  should I even be explicitly adding tail74a3.ts.net and 100.100.100.100 to my search domains and nameservers, respectively?

No, the Tailscale-provided search domain and resolver will be handled automatically and should not be added manually.

If he DNS issue happens again, please reopen.

**Comment by sellout** [comment] 2023-02-15 01:26
I don’t think I can re-open, but I am still seeing this behavior.

I’ve since upgraded to tailscale 1.36.1, removed my manual addition of the search domain and nameserver, so resolv.conf is now
```
search hsd1.co.comcast.net
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844
```
and `scutil --dns` now shows me
```
resolver #8
  domain   : search.tailscale
  search domain[0] : tail74a3.ts.net
  search domain[1] : sellout.github.beta.tailscale.net
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
```
(that “Not Reachable” sounds ominous)

BTW, since this is installed via Nix, it’s the CLI on Mac, not the GUI app bundle.

I can successfully ssh to the machines via the shiny browser-based tailscale SSH, but locally, it’s like this:
```
$ ssh my-host
ssh: connect to host my-host port 22: Operation timed out
$ tailscale ssh my-host
ssh: Could not resolve hostname my-host.tail74a3.ts.net.: nodename nor servname provided, or not known
$ tailscale status
100.66.66.31    my-other-host   sellout@     macOS   -
100.96.79.69    my-host         sellout@     linux   -
100.87.3.18     another-host    sellout@     linux   offline
100.95.166.11   hostess         sellout@     iOS     offline
100.111.4.111   tastykake       sellout@     linux   -
100.104.203.155 tailscale-ssh-console-sellout-github-7c673mev3k sellout@     js      -
$
```

Let me know what else I can do to help diagnose this. Here’s a new `tailscale bugreport`: BUG-e671486f71ef5ae52de9f6a210001dfbcd11de8b9df90718e9795cf8f5cf2b05-20230215012157Z-819089f13edbf69f

Thanks!

**Comment by sellout** [comment] 2023-06-30 21:11
I think this is perhaps the same issue as #8436.

**Comment by erikkrieg** [comment] 2023-07-21 14:42
I'm a new user of tailscale and have run into similar issue. I was only able to get MagicDNS working after directly modifying `/etc/resolv.conf` similar to what OP has. Before that I was able to do something like `host <hostname>` and get the expected IP, but `curl -vv <hostname>` would always resolve to `127.0.0.2` and fail (until I modified my resolv.conf).

That said, I'm a new user _and_ I'm setting things up with headscale so there is probably more than one issue with my current configuration.

**Comment by loranmutafov** [comment] 2024-04-09 13:41
For anyone Googling, check you don't have a VPN enabled

(upvote this to remind me how stupid I am 🤦‍♂️)

**Comment by rscorer** [comment] 2024-06-30 11:52
I encountered this, and I had to disable `Little Snitch DNS Proxy` 

<img width="474" alt="image" src="https://github.com/tailscale/tailscale/assets/1592698/43c66a63-77a0-418d-b45a-e5d8c7b3aa16">

This may be part of a recent upgrade to Little Snitch as it was all working perfectly well together.

Little Snitch version: Version 6.0.2

I also recently enabled Berkeley Packet Filter Monitoring, but I don't think that affected Tailscale.

**Comment by agottardo** [comment] 2024-08-20 17:56
Closing because this is a duplicate of other DNS issues that have since been resolved (mostly related to wake ups from sleep).

**Closed by agottardo** 2024-08-20 17:56 UTC
Labels: OS-macos, L1 Very few, P2 Aggravating, T5 Usability, dns, bug

**Comment by sellout** [comment] 2024-08-20 17:58
I haven’t had this issue in quite a while, so I think at least whatever the original problem was has been fixed.

Thanks!

**Comment by bpatwa-sanimax** [comment] 2024-09-20 19:47
This has been happening to us on Serverless containers with tailscale running in userspace-networking mode. It sporadically cannot resolve hostnames and is incredibly random.

**Comment by ditsuke** [comment] 2024-10-26 19:36
Ran into this on 1.76.3 on OSX 14.4
```
❯ tailscale ssh dt@tbvm           
ssh: Could not resolve hostname tbvm.tail9f9f.ts.net.: nodename nor servname provided, or not known

```

```
> tailscaled --version
1.76.3
  tailscale commit: 02acaa00eebb5146f7d41885aa3ed190cc107df6
  go version: go1.23.2
```

```
❯ cat /etc/resolv.conf --plain 
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
nameserver 100.100.100.100
nameserver 1.1.1.1
```

```
❯ scutil --dns
DNS configuration

resolver #1
  nameserver[0] : 100.100.100.100
  nameserver[1] : 1.1.1.1
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #2
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300000

resolver #3
  domain   : 254.169.in-addr.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300200

resolver #4
  domain   : 8.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300400

resolver #5
  domain   : 9.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300600

resolver #6
  domain   : a.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300800

resolver #7
  domain   : b.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 301000

resolver #8
  domain   : search.tailscale
  search domain[0] : tail9f9f.ts.net
  search domain[1] : oraclevcn.com
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)

DNS configuration (for scoped queries)

resolver #1
  nameserver[0] : 100.100.100.100
  nameserver[1] : 1.1.1.1
  if_index : 13 (en0)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)
```

**Comment by oleoneto** [comment] 2025-04-02 15:23
> I encountered this, and I had to disable `Little Snitch DNS Proxy`
> 

@rscorer
If you’re using **DNS Proxy** for DNS Encryption, you could just add an exception for your tailscale domain in the Little Snitch settings.

**Comment by kaxing** [comment] 2025-06-06 01:27
Adding the exception fixed it for me,
<img width="512" alt="Image" src="https://github.com/user-attachments/assets/e197001f-d74c-4d9a-a60b-24e3fd89a91c" />

Can keep the proxy filter on:
<img width="512" alt="Image" src="https://github.com/user-attachments/assets/5861bc84-efe9-416b-953c-bf232d933270" />

Versions:
- AppStore Tailscale 1.84
- Little Snitch 6.2.3 (7153)
- macOS 15.5 (24F74)
