### ISSUE TITLE
FR: Auth key need to have longer, potentially infinite long expiration time

### ISSUE THREAD

**Issue by wsmlby** [tailscale/tailscale#6902] opened 2023-01-06 05:02 UTC
### What are you trying to do?

We are using tailscale to connect 2 server clusters, and having to change config every 90 days for new auth keys are hard to maintain and automate

### How should we solve this?

allow auth key to be non-expiry just like others

### What is the impact of not solving this?

Not able to use this for servers in production.

**Comment by DentonGentry** [comment] 2023-01-06 05:16
The intent is to use an OAuth endpoint to issue API tokens. The client id and secret for the OAuth endpoint will have an indefinite lifetime: https://github.com/tailscale/tailscale/issues/3243#issuecomment-1253946534

Duplicate of https://github.com/tailscale/tailscale/issues/3243

**Closed by DentonGentry** 2023-01-06 05:16 UTC
Labels: needs-triage, fr
