### ISSUE TITLE
FR: Users, Owners, and AuthKeys

### ISSUE THREAD

**Issue by rnhurt** [tailscale/tailscale#6085] opened 2022-10-27 15:17 UTC
### What are you trying to do?

I have a set of EC2 instances that I'm using to proxy Tailscale traffic to my VPC.  The problem is that in order to make this work I have to create an Auth Key every 90 days.  Another problem is that key is tied to my user, so if I leave the company or change roles, the key stops working and our Tailscale network goes down.

### How should we solve this?

I think there are two solutions.  One is to allow AuthKeys to be configured at the account or team level, instead of just the user level.  This would allow me to create an auth-key that is not associated with a user and won't go away when the user does.

Another possibility is to allow account owners to be non-users.  For example, most of our SaaS providers allow us to use our DevOps group to "own" the account.  That way it's not tied to any specific user and account access can easily be granted to another user in our domain.

### What is the impact of not solving this?

I'm not working around the issue currently, I'm just dealing with it.  However, it will bite us in the butt hard if/when I decided to change roles.  There really is no workaround in that case, beyond having a different user create an AuthKey and using that instead of mine.

**Comment by DentonGentry** [comment] 2022-10-27 15:20
Duplicate of https://github.com/tailscale/tailscale/issues/3243, particularly https://github.com/tailscale/tailscale/issues/3243#issuecomment-1253946534

**Closed by DentonGentry** 2022-10-27 15:20 UTC
Labels: needs-triage, fr
