### ISSUE TITLE
DNS: TCP Connection to 100.100.100.100#53 timeout

### ISSUE THREAD

**Issue by AgentConDier** [tailscale/tailscale#3744] opened 2022-01-15 15:31 UTC
### What is the issue?

My upstream resolver setup is an OpenWRT VM with dnsmasq > stubby > Cloudflare over TLS
On some domain lookups, the UDP response is truncated, so a query is sent over TCP. The tailscale 100.100.100.100#53 resolver doesn't seem to listen to TCP connections, so the DNS lookup takes forever and in cases where the IP address wasn't contained in the truncated response fails entirely.

This domain does not result in a truncated response and works fine:
<pre>
$ nslookup paypal.com
Server:		100.100.100.100
Address:	100.100.100.100#53

Non-authoritative answer:
paypal.com	rdata_46 = A 5 2 300 20220124040404 20211225040031 11811 paypal.com. DzJ3GDL06GCP4w0msVIvm1GAYLRr84sXvgRiMKr0T8tIXekrBwLCVTzB i5l50muB+8brjRpsUe26O7smx3bgmSLKtRV1uWMQJ2mQ1fZJ7s4LgrQF nNYCs3JeQDFrJvnR8OwJkMZckxhR+zFVXWccOjG7CeLHg/qFtyw/rkFm uI0=
Name:	paypal.com
Address: 64.4.250.36
Name:	paypal.com
Address: 64.4.250.37
</pre>
This domain doesn't work at all:
<pre>
$ nslookup www.paypal.com
;; Truncated, retrying in TCP mode.
;; Connection to 100.100.100.100#53(100.100.100.100) for www.paypal.com failed: timed out.
;; Connection to 100.100.100.100#53(100.100.100.100) for www.paypal.com failed: timed out.
;; connection timed out; no servers could be reached

;; Connection to 100.100.100.100#53(100.100.100.100) for www.paypal.com failed: timed out.
</pre>
<code>www.paypal.com</code> with tailscale disconnected:
<pre>
$ nslookup www.paypal.com
;; Truncated, retrying in TCP mode.
Server:		192.168.178.38
Address:	192.168.178.38#53

Non-authoritative answer:
www.paypal.com	canonical name = www.glb.paypal.com.
www.paypal.com	rdata_46 = CNAME 5 3 3600 20220201090627 20220102085557 11811 paypal.com. YKM6EEPCbg7mfMrMNw7Y79/zNnANm4gKJ1Mhu9CZCA6HfJlAPXO7KXrf 9TccewQ3x2Nwp6E5X/vEOd1Yf49QfRUOIiz804tURuCzxWG7i3eDEAG6 THGeSUsrAQnCmRwhITEN4qsQTmtq+6lwHjFzFffTvTD+Q/dXW7HXki8P T0k=
www.glb.paypal.com	canonical name = www-fastly.glb.paypal.com.
www.glb.paypal.com	rdata_46 = CNAME 13 4 300 20220116151101 20220114151101 44688 glb.paypal.com. ndhZpOdVoDs+8xCFUmSIspI6wKbvFxTjSuSPqTD/TL68E/MiWJ0F7b1Y vqPa/oMik3khuGBUW4h5MuQ3ITcBZw==
www-fastly.glb.paypal.com	rdata_46 = A 13 4 300 20220116151101 20220114151101 44688 glb.paypal.com. dDhqi8sNMP65+OUBb8mllGdZXfks5lWhNu2ilBysiOCm7dtNz8IB0CpV +TwZUSJK/A11DD6RrYBxTlqkGEGJlQ==
www-fastly.glb.paypal.com	rdata_46 = A 13 4 300 20220116151101 20220114151101 44688 glb.paypal.com. s2KXZMzpgeG9D5Y9g0SmHVSPdb5ebbjonepAGKQND1/A2pvgm/rCBOmH N6Zz1lDtd+t2g+hr0Q07IbUPAcdQ6Q==
Name:	www-fastly.glb.paypal.com
Address: 151.101.65.21
www.paypal.com	canonical name = www.glb.paypal.com.
www.paypal.com	rdata_46 = CNAME 5 3 3600 20220201090627 20220102085557 11811 paypal.com. YKM6EEPCbg7mfMrMNw7Y79/zNnANm4gKJ1Mhu9CZCA6HfJlAPXO7KXrf 9TccewQ3x2Nwp6E5X/vEOd1Yf49QfRUOIiz804tURuCzxWG7i3eDEAG6 THGeSUsrAQnCmRwhITEN4qsQTmtq+6lwHjFzFffTvTD+Q/dXW7HXki8P T0k=
www.glb.paypal.com	canonical name = www.paypal.com-a.edgekey.net.
www.glb.paypal.com	rdata_46 = CNAME 13 4 300 20220116151249 20220114151249 44688 glb.paypal.com. otWPHxto2n9OKQ441iEBY+EWpMdfQlOmPcCn6D4dtj9koacFeEfjgyVP dP6afMsTJXUCqnOhV15bzYIRrQWZhw==
www.paypal.com-a.edgekey.net	canonical name = e5308.x.akamaiedge.net.
</pre>
This domain works but takes 40 seconds:
<pre>$ nslookup imap.gmx.net
Server:		100.100.100.100
Address:	100.100.100.100#53

Non-authoritative answer:
imap.gmx.net	rdata_46 = A 8 3 600 20220127075307 20220113075307 13905 gmx.net. nqpB8sHpi7vnvWAbHckZDu2yFCIRQh1kvttiRnQ6MhMw6E+Mic6lf4sb gUKilwWfkJVYVHPcyp/WHHxVo3ERn/iJRzmefA3fhzTY+gMp7pX4rPeE ZBs6NqAm8H0MSnV0hR/P2ea8jtKdKOPJSCf2i0f5A+W6MSeQ6iqAFsIr lJ6ga4xGHXVDRBM6hFWmywH11eRZcRzRKiZIGls17lkFRrJVOe3yDwd5 9i3KZAXccAwspTQ39CJkc7vLYrFZvxfFWw2lCahbE50vKZY++yREoGyD eE6H4oa8pel6a+yttYBMSrST0WBBz7mmj0CT1cuq5DuKW0fLLqrouvd2 rTj1Jw==
Name:	imap.gmx.net
Address: 212.227.17.186
Name:	imap.gmx.net
Address: 212.227.17.170
;; Truncated, retrying in TCP mode.
;; Connection to 100.100.100.100#53(100.100.100.100) for imap.gmx.net failed: timed out.
;; Connection to 100.100.100.100#53(100.100.100.100) for imap.gmx.net failed: timed out.
;; connection timed out; no servers could be reached

;; Connection to 100.100.100.100#53(100.100.100.100) for imap.gmx.net failed: timed out.
</pre>
The relevant section from my tailscale log:
<pre>2022/01/15 16:16:38 Accept: TCP{100.83.23.111:45801 > 100.100.100.100:53} 60 ok out
2022/01/15 16:16:39 Accept: TCP{100.83.23.111:45801 > 100.100.100.100:53} 60 ok out
2022/01/15 16:16:41 Accept: TCP{100.83.23.111:45801 > 100.100.100.100:53} 60 ok out
2022/01/15 16:16:43 open-conn-track: timeout opening (TCP 100.83.23.111:45801 => 100.100.100.100:53); no associated peer node
2022/01/15 16:16:46 open-conn-track: timeout opening (TCP 100.83.23.111:45801 => 100.100.100.100:53); no associated peer node
2022/01/15 16:16:48 Accept: TCP{100.83.23.111:48671 > 100.100.100.100:53} 60 ok out
2022/01/15 16:16:53 open-conn-track: timeout opening (TCP 100.83.23.111:48671 => 100.100.100.100:53); no associated peer node
2022/01/15 16:16:56 open-conn-track: timeout opening (TCP 100.83.23.111:48671 => 100.100.100.100:53); no associated peer node
2022/01/15 16:17:04 dns: error: context deadline exceeded
2022/01/15 16:17:04 [RATELIMIT] format("dns: resolver: forward: recv: response code indicating server failure: %d") (1 dropped)
2022/01/15 16:17:04 dns: resolver: forward: recv: response code indicating server failure: 2
2022/01/15 16:17:04 dns: resolver: forward: recv: response code indicating server failure: 2
2022/01/15 16:17:09 dns: error: response code indicates server issue
2022/01/15 16:17:10 Accept: TCP{100.83.23.111:51419 > 100.100.100.100:53} 60 ok out
2022/01/15 16:17:11 Accept: TCP{100.83.23.111:51419 > 100.100.100.100:53} 60 ok out
2022/01/15 16:17:15 open-conn-track: timeout opening (TCP 100.83.23.111:51419 => 100.100.100.100:53); no associated peer node
2022/01/15 16:17:18 open-conn-track: timeout opening (TCP 100.83.23.111:51419 => 100.100.100.100:53); no associated peer node
2022/01/15 16:17:20 Accept: TCP{100.83.23.111:48285 > 100.100.100.100:53} 60 ok out
2022/01/15 16:17:25 open-conn-track: timeout opening (TCP 100.83.23.111:48285 => 100.100.100.100:53); no associated peer node
2022/01/15 16:17:28 open-conn-track: timeout opening (TCP 100.83.23.111:48285 => 100.100.100.100:53); no associated peer node
2022/01/15 16:17:30 Accept: TCP{100.83.23.111:44995 > 100.100.100.100:53} 60 ok out
2022/01/15 16:17:35 open-conn-track: timeout opening (TCP 100.83.23.111:44995 => 100.100.100.100:53); no associated peer node
2022/01/15 16:17:38 open-conn-track: timeout opening (TCP 100.83.23.111:44995 => 100.100.100.100:53); no associated peer node
2022/01/15 16:19:17 [RATELIMIT] format("portmapper: failed to get PCP mapping: %v") (1 dropped)
2022/01/15 16:19:17 portmapper: failed to get PCP mapping: PCP response not ok, code 2
2022/01/15 16:19:17 portmapper: failed to get PCP mapping: PCP response not ok, code 2
</pre>

### Expected Behavior
The tailscale resolver accepts the TCP DNS query, forwards it to the upstream resolver and returns the response.

### Steps to reproduce

1. Obtain a resolver + domain combination that results in a truncated response
2. Connect to Tailscale with MagicDNS enabled
3. Do a DNS lookup

### OS

Linux

### OS version

MX Linux with Debian 11 5.14.16-1~mx21+1 (2021-11-05) x86_64 GNU/Linux

### Tailscale version

1.20.1

### Bug report

BUG-05d69888c5fe78fb3db3f893fc4ca73b335cfc79dee80c39d90a83ba7f091707-20220115152649Z-3a1830abdba54ae9

**Comment by DentonGentry** [comment] 2022-01-15 15:33
MagicDNS doesn't implement DNS-over-TCP yes. That is something we plan to do in the future, but isn't done yet.

Duplicate of https://github.com/tailscale/tailscale/issues/1123

**Closed by DentonGentry** 2022-01-15 15:33 UTC
Labels: needs-triage, bug

**Comment by DentonGentry** [comment] 2022-01-15 15:34
In the meantime, if you set up systemd-resolved on the Linux system then MagicDNS will push the DNS configuration to it and not insert itself as a recursive resolver. Lack of DNS-over-TCP support won't impact you, as 100.100.100.100 won't be involved in most DNS queries.
