### ISSUE TITLE
derp/derphttp: data race

### ISSUE THREAD

**Issue by maisem** [tailscale/tailscale#10053] opened 2023-11-01 06:09 UTC
cc @knyar @bradfitz 

```
=== RUN   TestBreakWatcherConnRecv
    derphttp_client.go:388: derphttp.Client.Recv: connecting to http://127.0.0.1:3[96](https://github.com/tailscale/tailscale/actions/runs/6716320493/job/18252375419#step:8:97)17
    derphttp_test.go:296: add: [ugSip]
    derphttp_client.go:388: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:39617/
    mesh_client.go:59: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:301: remove: [ugSip]
    mesh_client.go:123: Recv: derp.Recv: read tcp 127.0.0.1:51118->127.0.0.1:39617: use of closed network connection
    derphttp_test.go:296: add: [ugSip]
    derphttp_client.go:388: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:39617/
    mesh_client.go:59: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:301: remove: [ugSip]
    mesh_client.go:123: Recv: derp.Recv: read tcp 127.0.0.1:51132->127.0.0.1:39617: use of closed network connection
    derphttp_test.go:296: add: [ugSip]
    derphttp_client.go:388: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:39617/
    mesh_client.go:59: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:301: remove: [ugSip]
    mesh_client.go:123: Recv: derp.Recv: read tcp 127.0.0.1:51136->127.0.0.1:39617: use of closed network connection
    derphttp_test.go:296: add: [ugSip]
    derphttp_client.go:388: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:39617/
    mesh_client.go:59: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:301: remove: [ugSip]
    mesh_client.go:123: Recv: derp.Recv: read tcp 127.0.0.1:51138->127.0.0.1:39617: use of closed network connection
    derphttp_test.go:296: add: [ugSip]
    derphttp_client.go:388: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:39617/
    mesh_client.go:59: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:301: remove: [ugSip]
    mesh_client.go:123: Recv: derp.Recv: read tcp 127.0.0.1:5[114](https://github.com/tailscale/tailscale/actions/runs/6716320493/job/18252375419#step:8:115)6->127.0.0.1:39617: use of closed network connection
    derphttp_test.go:296: add: [ugSip]
    derphttp_client.go:388: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:39617
    mesh_client.go:59: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:301: remove: [ugSip]
    mesh_client.go:123: Recv: derp.Recv: read tcp 127.0.0.1:5[115](https://github.com/tailscale/tailscale/actions/runs/6716320493/job/18252375419#step:8:116)8->127.0.0.1:39617: use of closed network connection
    derphttp_test.go:296: add: [ugSip]
    derphttp_client.go:388: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:39617
    mesh_client.go:59: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:301: remove: [ugSip]
    mesh_client.go:123: Recv: derp.Recv: read tcp 127.0.0.1:5[116](https://github.com/tailscale/tailscale/actions/runs/6716320493/job/18252375419#step:8:117)8->127.0.0.1:39617: use of closed network connection
    derphttp_test.go:296: add: [ugSip]
    derphttp_client.go:388: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:39617
    mesh_client.go:59: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:301: remove: [ugSip]
    mesh_client.go:123: Recv: derp.Recv: read tcp 127.0.0.1:5[117](https://github.com/tailscale/tailscale/actions/runs/6716320493/job/18252375419#step:8:118)6->127.0.0.1:39617: use of closed network connection
    derphttp_test.go:296: add: [ugSip]
    derphttp_client.go:388: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:39617
    mesh_client.go:59: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:301: remove: [ugSip]
    mesh_client.go:123: Recv: derp.Recv: read tcp 127.0.0.1:5[118](https://github.com/tailscale/tailscale/actions/runs/6716320493/job/18252375419#step:8:119)8->127.0.0.1:39617: use of closed network connection
    derphttp_test.go:296: add: [ugSip]
    derphttp_client.go:388: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:39617/
    mesh_client.go:59: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:301: remove: [ugSip]
    mesh_client.go:123: Recv: derp.Recv: read tcp 127.0.0.1:5[119](https://github.com/tailscale/tailscale/actions/runs/6716320493/job/18252375419#step:8:120)4->127.0.0.1:39617: use of closed network connection
==================
WARNING: DATA RACE
Read at 0x000000da6580 by goroutine 51:
  tailscale.com/derp/derphttp.(*Client).RunWatchConnectionLoop()
      tailscale.com/derp/derphttp/mesh_client.go:[124](https://github.com/tailscale/tailscale/actions/runs/6716320493/job/18252375419#step:8:125) +0x64f
  tailscale.com/derp/derphttp.TestBreakWatcherConnRecv.func2()
      tailscale.com/derp/derphttp/derphttp_test.go:303 +0x27a

Previous write at 0x000000da6580 by goroutine 46:
  tailscale.com/derp/derphttp.TestBreakWatcherConnRecv.func1()
      tailscale.com/derp/derphttp/derphttp_test.go:288 +0x30
  runtime.deferreturn()
      runtime/panic.go:477 +0x30
  testing.tRunner()
      testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      testing/testing.go:1648 +0x44

Goroutine 51 (running) created at:
  tailscale.com/derp/derphttp.TestBreakWatcherConnRecv()
      tailscale.com/derp/derphttp/derphttp_test.go:292 +0x535
  testing.tRunner()
      testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      testing/testing.go:1648 +0x44

Goroutine 46 (running) created at:
  testing.(*T).Run()
      testing/testing.go:1648 +0x82a
  testing.runTests.func1()
      testing/testing.go:2054 +0x84
  testing.tRunner()
      testing/testing.go:1595 +0x238
  testing.runTests()
      testing/testing.go:2052 +0x896
  testing.(*M).Run()
      testing/testing.go:1925 +0xb57
  main.main()
      _testmain.go:53 +0x2bd
==================
    testing.go:[146](https://github.com/tailscale/tailscale/actions/runs/6716320493/job/18252375419#step:8:147)5: race detected during execution of test
--- FAIL: TestBreakWatcherConnRecv (0.49s)
```

**Comment by irbekrm** [comment] 2023-11-01 06:45
I think Anton is already fixing that https://github.com/tailscale/tailscale/issues/10041

**Comment by knyar** [comment] 2023-11-01 08:18
Duplicate of #10041

**Closed by knyar** 2023-11-01 08:18 UTC
