### ISSUE TITLE
I have a cert mismatch with hostname problem when using Nginx proxy

### ISSUE THREAD

**Issue by MilkTeaNo7** [tailscale/tailscale#7309] opened 2023-02-18 06:52 UTC
### What is the issue?

I have a cert mismatch with hostname problem when using Nginx proxy

My derp server is deployed using docker rum
His code is as follows
```
docker run --restart always \
  --name derp \
  -p 8443:8443 \
  -p 3478:3478/udp \
  -v /etc/nginx/SSL:/app/certs \
  -e DERP_CERT_MODE=manual \
  -e DERP_ADDR=:8443 \
  -e DERP_DOMAIN=depe.cc.163.top \
```

  For this I applied for a single domain certificate from ZeroSSL, who is not pan-domain, and then the results were the same

  When docker deployed derp is running with IP address + 8443, he behaves very well

  But after proxying through nginx, there is a problem
  Here is the Nginx configuration

```
  server {
    #listen 80;
    listen 443 http2 ssl;
    server_name depe.cc.163.top; # write the domain name to be processed
    client_max_body_size 500M;
    
    ssl_certificate /etc/nginx/SSL/depe.cc.163.top.crt;
    ssl_certificate_key /etc/nginx/SSL/depe.cc.163.top.key;

   
    location / { 
        proxy_pass https://127.0.0.1:8443;
        index index.html index.htm;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";        
    }
}
```

The Nginx error is as follows
```
2023/02/18 01:32:40 [error] 2
9772#29772: *1 SSL_do_handshake() failed 
(SSL: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:SSL alert number 80) 
while SSL handshaking to upstream, client: 152.89.196.211, server: depe.cc.wowxql.top, 
request: "GET /favicon.ico HTTP/2.0", upstream: "https://127.0.0.1:8443/favicon.ico",
 host: "depe.cc.163.top", 
referrer: "https://depe.cc.163.top/"
```

The error reported by derp is as follows
```
2023/02/18 06:32:40 http: TLS handshake error from 172.17.0.1:51070: cert mismatch with hostname:
```

I found some talk about self-signed certificates, but it doesn't feel like this aspect is causing it?

Is it possible that nginx doesn't support it and needs to be switched to something else?

Translated with www.DeepL.com/Translator (free version)

**Comment by DentonGentry** [comment] 2023-02-18 07:03
Duplicate of https://github.com/tailscale/tailscale/issues/4072, the information there may help.

We do not run DERPers behind NGINX, that isn't something we'll be able to help with very much.

**Closed by DentonGentry** 2023-02-18 07:03 UTC
Labels: needs-triage, bug

**Comment by Philosjay** [comment] 2023-09-24 07:18
https://zhuanlan.zhihu.com/p/604101736
