### ISSUE TITLE
T-Mobile LTE breaks tailscale connectivity due to CGNAT and/or IPv6-only

### ISSUE THREAD

**Issue by jeremydk** [tailscale/tailscale#302] opened 2020-04-15 19:36 UTC
Sorry for the rough title, there's layers here.

TMobile's IPV6 implementation is breaking SSH down the tailscale provided tunnel. After finding a client that exposed some connection logs, I noted that I was being provided a v6 address to connect to, regardless of if I was using my tailscale IP directly or an A record pointing to the tailscale IP.

Interestingly, HTTP(s) requests via Chrome iOS to the same host were working.

I was able to work around this by applying a device profile (for testing) which allows for ipv4/ipv6 rather than v6 only, but, if possible, the iOS client application should attempt to navigate this network.

**To Reproduce**
iPhone on T-Mobile, connected to LTE.
Tailscale tunnel active.
SSH to CentOS7 host via tailscale IP

**Version information:**
 - Device: iPhone 11 Pro Max

 - OS version: 13.3.1
 - Tailscale version: 0.97.78

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171686338663719) by [Unito](https://www.unito.io/learn-more)

**Comment by danderson** [comment] 2020-04-15 19:46
cc @crawshaw smells like iOS weirdness in handling IPv4 when connected to a v6-only APN, even if tailscale0 offers v4 connectivity. Could also be 464xlat or DNS64 related, but from the sound of things that's what the dual v4/v6 device profile is, so I assume the v6-only profile is doing plain DNS64+NAT64, which should not break connectivity on tailscale0... Unless iOS is doing something weird when presented with a v6-only APN.

**Comment by rlopezro** [comment] 2020-04-19 10:25
I'm hitting the same issue. The weird thing is that it's only ssh. ping and http traffic works as expected. I can load pages hosted on the destination machine in my iPhone using Chrome when connected through T-Mobile LTE, but the only thing that does not work is ssh.

**Comment by jeremydk** [comment] 2020-04-22 20:25
@rlopezro I've tried with Terminus and Shelly, both repro.

**Comment by ackmxqz** [comment] 2020-04-23 05:48
I'm having the same issue as well on Rogers LTE. I am able to SSH to a Linux server from my laptop if I tether through LTE.

**Comment by rlopezro** [comment] 2020-04-23 09:10
@jeremydk Thank you! I was able to see the logs using Shelly.

In my case, the ssh client is trying to establish a connection to the ipv6 address first. Once this one times out it tries the ipv4 address and that one is successful. Why is it trying the ipv6 address when using tailscale? I tried to force it on the ssh server side to use ipv4 only but it didn't work.

Here are the redacted logs:

```
Looking up host "100.100.100.100” for SSH connection
Connecting to 2691:3402:4:3c:1:0:5385:9271 port 22
We claim version: SSH-2.0-PuTTY_Release_0.70
Failed to connect to 2691:3402:4:3c:1:0:5385:9271:5554: Operation timed out
Connecting to 100.100.100.100 port 22
Server version: SSH-2.0-OpenSSH_8.1
Using SSH protocol version 2
Doing ECDH key exchange with curve Curve25519 and hash SHA-256
Server also has ecdsa-sha2-nistp256/ssh-rsa host keys, but we don't know any of them
Host key fingerprint is:
ssh-ed25519 256 
Initialised AES-256 SDCTR client->server encryption
Initialised HMAC-SHA-256 client->server MAC algorithm
Initialised AES-256 SDCTR server->client encryption
Initialised HMAC-SHA-256 server->client MAC algorithm
```

Thanks!

**Comment by apenwarr** [comment] 2020-04-23 14:34
Do you have some kind of ssh proxy defined in ssh_config or .ssh/config?

On Thu, Apr 23, 2020 at 5:10 AM rey <notifications@github.com> wrote:
>
> @jeremydk Thank you! I was able to see the logs using Shelly.
>
> In my case, the ssh client is trying to establish a connection to the ipv6 address first. Once this one times out it tries the ipv4 address and that one is successful. Why is it trying the ipv6 address when using tailscale? I tried to force it on the ssh server side to use ipv4 only but it didn't work.
>
> Here are the redacted logs:
>
> Looking up host "100.100.100.100” for SSH connection
>
> Connecting to 2691:3402:4:3c:1:0:5385:9271 port 22
>
> We claim version: SSH-2.0-PuTTY_Release_0.70
>
> Failed to connect to 2691:3402:4:3c:1:0:5385:9271:5554: Operation timed out
>
> Connecting to 100.100.100.100 port 22
>
> Server version: SSH-2.0-OpenSSH_8.1
>
> Using SSH protocol version 2
>
> Doing ECDH key exchange with curve Curve25519 and hash SHA-256
>
> Server also has ecdsa-sha2-nistp256/ssh-rsa host keys, but we don't know any of them
>
> Host key fingerprint is:
>
> ssh-ed25519 256
>
> Initialised AES-256 SDCTR client->server encryption
>
> Initialised HMAC-SHA-256 client->server MAC algorithm
>
> Initialised AES-256 SDCTR server->client encryption
>
> Initialised HMAC-SHA-256 server->client MAC algorithm
>
> Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Avery Pennarun // CEO @ Tailscale
   Book a meeting! calendly.com/apenwarr

**Comment by jeremydk** [comment] 2020-04-23 18:42
@apenwarr Not on my end -- extremely standard ssh config on both server and client.

**Comment by rlopezro** [comment] 2020-04-23 19:42
@apenwarr I don't have any proxies. Just a fresh Fedora 31 install.

**Comment by rlopezro** [comment] 2020-04-24 07:09
I also see `* IPv6: no` when running `tailscale netcheck` on the Linux instance

**Comment by whatrocks** [comment] 2020-06-15 03:37
> I was able to work around this by applying a device profile (for testing) which allows for ipv4/ipv6 rather than v6 only

Do you mind sharing details on this workaround? I'm experiencing the same issue using Termius on iOS with T-Mobile. Thanks!

**Comment by jeremydk** [comment] 2020-06-16 21:23
It's a bit dirty, but you can use Configurator on a mac to create an APN
profile for ipv4/ipv6 on tmobile. It's not the safest to download/share one
since they are capable of applying arbitrary configuration to your device.
The APN details can be found online, but this isn't a long term solution.

**Comment by DentonGentry** [comment] 2021-02-08 22:33
From bug scrub: 464xLAT seems possible, pushing NAT rewrites down to the client device and so they end up rewriting our 100.x.x.x addresses.

I have an Android and an iOS device with T/Mobile as a carrier, to try to reproduce.

**Comment by jroes** [comment] 2021-08-18 14:19
I’m seeing this as well. Can’t SSH into devices in my Tailscale mesh.

Shelly on iOS, on T-Mobile’s 5G network in the US.

I don’t know how to pull logs out of Shelly, but if someone gives me instructions I’d be happy to.

**Comment by jroes** [comment] 2021-08-19 22:11
As another quick datapoint in case it's useful - if I turn on my hotspot and connect via my laptop, I am able to access Tailscale nodes over SSH. Laptop is a MacBook Pro M1 on Big Sur.

**Comment by knoxx333** [comment] 2021-08-22 18:09
I have exactly the same issues with SSH on TMO US. I believe I found a solution: You have to switch off IP6 on IOS.
Not an easy undertaking, especially because TMO is hiding the network configuration on their IOS devices.
I built a provisioning profile for IOS14 that selects IP4 only :
- [Here](https://sunknudsen.com/privacy-guides/how-to-disable-ipv6-on-ios-cellular-only-and-macos) is how it's done: 
- I used [this](https://www.t-mobile.com/support/devices/android/t-mobile-revvl-5g/network-apn-and-volte-t-mobile-revvl-5G) APN information (assuming you are on 5G).

Slightly tested with Termius and ServerCat. 
I also switched off IP6 routing on my WIFI network. But that shouldn't have an impact.

**Comment by clarkezone** [comment] 2021-10-31 16:10
I’ve been hitting this for a while myself and it’s pretty bad / annoying it basically means i can’t access my tailnet from my phone when out and about.

**Comment by dhruvb14** [comment] 2021-11-12 22:48
So I have been having the same issue, my workaround was to go to desktop version of tailscale.com, click on the machine, and get the IPV6 version of theIP address on the machine and connect via that. On my home network I have IPV6 explicitly disabled however you can see the snippet below works even if the machine or network/ISP doesn't support it. 

My issue was related to iOS RDP application on T-Mobile 5G not allowing connection outside of http(s). 

This solved it without an APN change

![image](https://user-images.githubusercontent.com/4459649/141574091-54c56f5d-3238-4fed-962f-e9751ff923fa.png)

**Comment by castanley** [comment] 2022-04-23 02:35
Confirmed this is still an issue with T-Mobile, enabling magic DNS does work, but not ideal :)

**Comment by sounddroid** [comment] 2022-06-27 03:43
Ran into this just now. T-Mobile iOS 15.5.

**Comment by paulverket** [comment] 2022-07-18 00:00
Also ran into this just now. T-mobile (Ting), iOS 15.5. Terminus fails. Setting up hotspot and using macOS 12.4 terminal.app works fine with ssh.

**Comment by LoopControl** [comment] 2022-08-16 22:14
Also having same issue - Using Mint Mobile (which is really TMobile) on iPhone/iOS, I can't SSH to tailscale servers -- it times out.

**Comment by travelingflwr** [comment] 2022-08-17 00:00
Mint mobile is a MVNO so while they lease the network, they have their own proxy servers at a POP close to a tMobile major POP.  Similar to Consumer Cellular as well as other providers.T-Mobile proves layers 1-3 and handoff the rest to the MVNO providers.Sent from my iPhoneOn Aug 16, 2022, at 3:14 PM, LoopControl ***@***.***> wrote:﻿
Also having same issue - Using Mint Mobile (which is really TMobile) on iPhone/iOS, I can't SSH to tailscale servers -- it times out.

**Comment by DentonGentry** [comment] 2022-08-27 14:57
In release 1.28.0 the macOS and iOS clients switched to an adaptive strategy:
- if any other interface in the system is using a CGNAT address, like a mobile carrier for example, install all Tailscale routes as /32s to try to interoperate (this is what 1.26 and before did uncondititionally)
- otherwise, install a 100.64.0.0/10 route for the Tailscale interface. This attempts to avoid ERR_NETWORK_CHANGED glitches in web browsers as routes are added and removed.

**Comment by LoopControl** [comment] 2022-08-27 20:36
@DentonGentry I tested on an iPhone with the 1.28.0 and a connection can't be established with Mint Mobile while not on Wifi.

One interesting thing though is that if I connect to WIFI, establish an (SSH) connection to the same Tailscale IP then turn off the Wifi, the connection is maintained while on LTE. So it seems it's the IP resolution that is failing while on cell data.

**Comment by mihaip** [comment] 2022-08-30 23:45
@DentonGentry: the change in 1.28 was for macOS clients only (https://github.com/tailscale/tailscale/blob/70ed22ccf9aac94724057aa4e5b219cf8e79201b/ipn/ipnlocal/local.go#L2334-L2339 has `macOS` check). We can broaden this to iOS, but the original issue was reported as only affecting Chrome on the Mac.

**Comment by bradfitz** [comment] 2022-08-31 02:02
One thing I don't see mentioned on this bug is MTU.

Do we not lower the MTU on iOS?

You know, @mihaip, @nickoneill, @danderson?

**Comment by bradfitz** [comment] 2022-08-31 02:03
(SSH has some large exchanges early in the protocol that frequently trip up SSH users using wireguard; that'd also explain why the SSH handshake works over Tailscale over wifi but then keeps working over Tailscale-over-LTE but can't initiate with Tailscale-over-LTE)

**Comment by mihaip** [comment] 2022-08-31 22:26
As far as I can tell, we're setting the 1280 MTU.  The `/v0/interfaces` peerapi endpoint on an iPhone peer reports:

Index | Name | MTU | Flags | Addrs
-- | -- | -- | -- | --
25|utun5|1280|up,pointtopoint,multicast|[100.91.214.84/32 fd7a:115c:a1e0:ab12:4843:cd96:625b:d654/48 fe80::c2a6:ff:fe36:ac79/64]

Also empirically I can only send pings of 1280-28 = 1252 bytes

```
~$ ping -s 1253 -D 100.91.214.84 -c 1
PING 100.91.214.84 (100.91.214.84): 1253 data bytes
ping: sendto: Message too long
~$ ping -s 1252 -D 100.91.214.84 -c 1
PING 100.91.214.84 (100.91.214.84): 1252 data bytes
1260 bytes from 100.91.214.84: icmp_seq=0 ttl=64 time=15.909 ms
```

**Comment by LoopControl** [comment] 2022-09-01 21:17
I’m still unable to connect to SSH with 1.30 unfortunately.

I tested reaching an HTTP server hosted on the same Tailscale IP through Safari on LTE network and there are no issues.

I’d be happy to do any testing of prerelease/TestFlight type releases if you need a beta tester for this issue.

**Comment by rphillips** [comment] 2022-09-02 00:27
I also tested out 1.30.0 and it also failed for me over 5G and LTE. Though, an interesting data point, if I use an Exit Node (has ipv6 enabled) on the same subnet as the SSH server it works.

**Comment by DentonGentry** [comment] 2022-10-30 11:40
I believe the original issue reported in this bug about CGNAT conflicts was resolved in 1.30 by adaptively adding /32 or /10 routes.

Later comments bring up conflating issues about SSH and exit nodes, but at this point I can't disentangle what all of the root causes are. If something is still not working on T/Mobile LTE please file it as a new issue.

**Closed by DentonGentry** 2022-10-30 11:40 UTC
Labels: connectivity, OS-ios, L2 Few, P5 Halts deployment, T6 Major usability

**Comment by rphillips** [comment] 2022-10-30 12:11
I don’t think this bug should have been closed. SSH connections to Tailscale nodes still fail for me over LTE and 5G. If I use an exit node then those connections work. If I use a direct connection to the Tailscale IP without the exit node they still fail.

**Comment by DentonGentry** [comment] 2022-10-30 12:21
Too many conflated issues in this report.

Please file it as a new issue, and include a bugreport.
>Later comments bring up conflating issues about SSH and exit nodes, but at this point I can't disentangle what all of the root causes are. If something is still not working on T/Mobile LTE please file it as a new issue.

**Comment by paulverket** [comment] 2022-10-30 14:36
> > Also ran into this just now. T-mobile (Ting), iOS 15.5. Terminus fails. Setting up hotspot and using macOS 12.4 terminal.app works fine with ssh. tailscale 1.26.2
> 
> Works with iOS tailscale 1.30.0 -- Thanks!!

Still works with ssh to node from phone (t-mobile LTE). Also works with exit node.

**Comment by chtzvt** [comment] 2023-07-22 20:44
I'm able to reproduce and am currently experiencing this issue. At the moment, my workaround is to use an exit node while connected to my phone for tethering.

**Comment by stevennyman** [comment] 2025-03-07 01:34
I'm experiencing a similar issue connecting to SSH on a device using Termius and Tailscale while on T-Mobile's network. I found that connecting to my SSH device using its Tailscale IPv6 address worked. Using an exit node also works.

**Comment by Awesome-guyy** [comment] 2025-07-28 00:51
Any updates with this? This issue affects Moonlight Streaming  and probably other stuff.

Also I think it affects general connection / direct connections aren’t possible. Probably wrong but it’s an issue

**Comment by wynlb** [comment] 2026-08-12 19:13
Validated that Run Script over SSH works on T-mobile LTE/5G works if the Tailnet DNS name is used in place of the IP address (100...)
