### ISSUE TITLE
Cellular on iPhone appears to be broken (again?)

### ISSUE THREAD

**Issue by NotLazy** [tailscale/tailscale#9032] opened 2023-08-23 13:48 UTC
I'm facing the same issue as in #7184

Connecting to Tailscale causes a full loss of internet access however connection to Tailscale devices is still functional.

Bug report if it helps/works

BUG-59f0cebc4d1a442245cf27fceb3447a02757eee5ed8161d8d1e8ffd5503393de-20230823134459Z-9983a8dbdc27d3d3

**Comment by kelivel** [comment] 2024-03-18 18:33
Hi @NotLazy! We shipped an improvement to DNS on iOS devices with version 1.62, can you update and let us know if the issue is resolved now?

**Comment by kelivel** [comment] 2024-09-03 18:48
We've shipped several DNS issues since this issue was opened, so I'll go ahead and close this one out. If you're experiencing issues with DNS connectivity in the latest Tailscale version, please create a new issue and include a bugreport and we'll take a closer look!

**Closed by kelivel** 2024-09-03 18:48 UTC
Labels: OS-ios, dns, bug
