### ISSUE TITLE
tailscaled overwrites /etc/resolv.conf but systemd-resolved is in use

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2678] opened 2021-08-18 21:02 UTC
On Tailscale 1.12.3 ,  it looks like  server is using systemd-resolved, but tailscaled didn't figure that out which overwrote /etc/resolv.conf.

tailscaled decides at startup whether it should work with NetworkManager or systemd-resolved, or whether it should overwrite /etc/resolv.conf. Any bug is likely to happen at tailscaled startup.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3hhe9)

**Comment by bradfitz** [comment] 2021-08-19 15:54
@pmaene, to summarize, your 100.86.84.74 machine (running Ubuntu 20.04.2 LTS (Focal Fossa) is not detecting the DNS resolver mechanism correctly resulting in the "direct manager" (/etc/resolv.conf overwriting) to be used, and the 100.100.100.100 resolver ended up being your global resolver:

```
Global
       LLMNR setting: no
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 100.100.100.100
         DNS Servers: 100.100.100.100
          DNS Domain: pmaene.github.beta.tailscale.net
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      d.f.ip6.arpa
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 57 (tailscale0)
      Current Scopes: none
DefaultRoute setting: no
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
```

Your logs at startup say:

```
2021-08-16 09:53:18.307809036 +0200 +0200: Program starting: v1.12.3-td91ea7286-ge1bbbd90c, Go 1.16.6-tsedbc3e1: []string{"/usr/sbin/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailscale/tailscaled.sock", "--port", "41641"}
2021-08-16 09:53:18.3084042 +0200 +0200: LogID: 7dffe5e0f3587315d257d4877343cf50d47936a197ea19496dd32d3a5c4f2647
2021-08-16 09:53:18.308482198 +0200 +0200: logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
2021-08-16 09:53:18.310307391 +0200 +0200: wgengine.NewUserspaceEngine(tun "tailscale0") ...
2021-08-16 09:53:18.367641721 +0200 +0200: router: v6nat = false
2021-08-16 09:53:18.509188623 +0200 +0200: dns: [rc=unknown ret=dns.directManager]
2021-08-16 09:53:18.510016559 +0200 +0200: dns: using dns.directManager
2021-08-16 09:53:18.510438951 +0200 +0200: link state: interfaces.State{defaultRoute=eno0 ifs={eno0:[xxx/24 yyy::1/58]} v4=true v6=true}
2021-08-16 09:53:18.512144865 +0200 +0200: logtail: dialed "log.tailscale.io:443" in 190ms
2021-08-16 09:53:18.603218126 +0200 +0200: Creating wireguard device...
2021-08-16 09:53:18.603807646 +0200 +0200: Bringing wireguard device up...
2021-08-16 09:53:18.603943439 +0200 +0200: UDP bind has been updated
```

Notably, the:
 
```
2021-08-16 09:53:18.509188623 +0200 +0200: dns: [rc=unknown ret=dns.directManager]
2021-08-16 09:53:18.510016559 +0200 +0200: dns: using dns.directManager
```

This means your `/etc/resolv.conf` file has no obvious owning process. What are its contents? Who do you think should be managing it based on your system config?

/cc @danderson

**Comment by pmaene** [comment] 2021-08-19 16:58
Hi @bradfitz, thanks for picking up this issue! `/etc/resolv.conf` currently contains the following, so Tailscale is indeed overwriting it.

```
# resolv.conf(5) file generated by tailscale
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100
search pmaene.github.beta.tailscale.net
```

I believe the default on Ubuntu 20.04 is for it to be managed by `systemd-resolved`, which is also what I'm seeing on another Ubuntu machine I manage. However, this server was initialised with an image compiled by my hosting provider, so it's possible they changed the default behaviour. Both machines set up with static public IPs (this machines also has IPv6 configured) through netplan.

Is there any other information that would be useful to figure this out?

**Comment by bradfitz** [comment] 2021-08-19 18:30
Yes, it's obvious we did in fact overwrite it. I'm more curious what led us to do that initially and what the original contents of the file were. I guess the only way to go back to that state is to stop tailscaled, perhaps `systemctl disable` it so it doesn't start back up on boot, then restart various networking things (or reboot?) and see what the system tries to make `/etc/resolv.conf` be.

If you have some cloudy thing in `cloud-init` overwriting it when systemd-resolved is supposed to own it then Tailscale won't be able to do tell which DNS manager is in charge. We try to detect how we're supposed to cooperate (details: https://tailscale.com/blog/sisyphean-dns-client-linux/) but apparently something's hiding info from us.

Maybe an explicit tailscaled argument would help to force us to use a certain layer? But we in general dislike config knobs so I'd really like to figure out how to detect this better automatically.

**Comment by pmaene** [comment] 2021-08-19 19:41
Sorry about that! I stopped tailscaled and disabled the service, and `/etc/resolv.conf` now contains a single `nameserver` line to configure a server managed by the provider as the global resolver. I did in fact notice before that there also was a `/etc/resolv.pre-tailscale-backup.conf` file with the exact same contents, but it was timestamped November 11th, so I assumed it was no longer relevant no longer be relevant. What's curious is that I only only started seeing this behaviour in the last week or so. Aside from pulling in Ubuntu's regular updates and switching to a GitHub-based tailnet, I did not change the machine's configuration as far as I remember.

The machine did have `cloud-init` installed, but it reported being disabled. To make sure that it wasn't interfering regardless, I removed it from the machine and rebooted. This did not change the resolver configuration, though. I read the DNS client blog post and followed along with @danderson's Tweets. It's ridiculous how hard this is to get right across different platforms and and am amazed by your persistence 😉.

I definitely agree with you that Tailscale's simplicity makes it such a great product to use and that introducing client-side configuration takes away from that.

I'll dig a little further to try and figure out what is writing this `nameserver` line and keep you updated!

**Comment by bradfitz** [comment] 2021-08-19 19:48
Thanks. Let us know what you find!

At this point Tailscale is at least working as intended: we see an `/etc/resolv.conf` that looks like it's hand-written/unmanaged so we decide to take it over and be the manager of it.

If you have alternative heuristic ideas that'd help your system, we're all ears.

**Comment by danderson** [comment] 2021-08-19 20:05
Most likely, what happened is that your cloud provider / virt platform set up a one-shot cloud-init run, which only runs on the machine's first boot, and wrote a static piece of config to /etc/resolv.conf. That would be why disabling cloud-init after the fact did nothing, because the actual overwrite happened during the first boot of the machine, not on every boot.

Since cloud-init is a glorified shell script, I can't predict whether anything will work reliably, but if you do want to switch to resolved now, the incantation for that would be:

```
sudo systemctl stop tailscaled
sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
sudo systemctl restart systemd-resolved
sudo systemctl start tailscaled
```

The above switches resolv.conf to use resolved's "stub" config that points DNS clients to resolved, restarts resolved so that it notices that it's in charge of DNS (if resolv.conf doesn't point to resolved on startup, resolved goes into a "follower" mode where it still offers DNS resolution services over DBus, but delegates resolution to "whatever is in resolv.conf". Restarting resolved with the symlink in place makes it notice that it's now in full control of system DNS).

Similarly, stopping/starting tailscale makes it rerun its "figure out what the DNS stack is" logic, and gracefully switch to using resolved.

Also note that if this VM doesn't use DHCP for configuration, you may want to edit /etc/systemd/resolved.conf or /etc/systemd/network/... configs to tell it what you want the default system resolver to be. By default, if it can't find any other config, resolved falls back to using Google Public DNS by default, which works fine but may be objectionable to you depending on your views of the various public DNS providers.

As @bradfitz says, I think from our POV this is all "working as intended": something set up the system to use a static DNS configuration, resolved noticed this and went into its "follower mode", and tailscaled did the only thing it can do with a static config, which is replace it entirely and do DNS routing itself. Even if we knew exactly who did this to the DNS config, I don't think we'd want to do anything different: the OS around us clearly expressed the intent that it does _not_ want resolved in charge of system DNS configuration, so we obeyed that and worked with the few tools left to us :(

**Comment by pmaene** [comment] 2021-08-19 20:27
I actually decided to check the timestamp on the "new" `/etc/resolv.conf` and it has the same November 11th date, so I'm guessing Tailscale neatly restored that backup file upon stopping? Its contents changing therefore had nothing to do at all with the system reboot and can indeed probably be traced back to the initial system bringup.

Thanks you for those instructions to get resolved to take over resolution. After restarting tailscaled again, it  no longer configures itself as the global resolver 🎉!

I also did not know about resolved falling back to Google's Public DNS, thanks! I do configure explicit DNS servers for the physical link in the netplan configuration, but this probably means Google's servers are used for requests going to different interfaces?

Thanks again for figuring this out!

**Comment by bradfitz** [comment] 2021-08-19 20:34
Yay, glad this mystery is solved. Closing. But let us know if anything else comes up.

**Closed by bradfitz** 2021-08-19 20:34 UTC
Labels: OS-linux, L1 Very few, P2 Aggravating, T5 Usability, dns

**Comment by danderson** [comment] 2021-08-19 20:36
You can check what resolved is doing with `resolvectl`. If there are any global resolvers configured on any interface, the fallback resolvers don't get used. They only get used if resolved has absolutely no idea of any upstream resolvers to use at all.

The exact name resolution algorithm resolved uses is documented in delightful detail in `man systemd-resolved`, so that combined with the output of `resolvectl` should enable you to predict what resolved will do given some arbitrary query!

Good luck! DNS on linux is, uh, fun :)

**Comment by pmaene** [comment] 2021-08-19 20:38
I will have a look at that, thanks for the suggestions! Judging from your blog post and Tweets, it seems to have its challenges on every platform 😊. Thank you both again for the help!
