### ISSUE TITLE
cmd/tailscale: let tailscale up accept oauth creds

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#7982] opened 2023-04-26 18:35 UTC
It should be possible to use `tailscale up --auth-key=` with oauth creds.

**Comment by shubb30** [comment] 2023-08-04 17:11
Looks like this has already done in #8403.

**Comment by DentonGentry** [comment] 2023-08-04 17:59
Duplicate of https://github.com/tailscale/tailscale/issues/8403
Fixed in 1.46

**Closed by DentonGentry** 2023-08-04 17:59 UTC
Labels: L3 Some users, P2 Aggravating, T0 New feature, fr
