### ISSUE TITLE
When using MagicDNS on Windows 10, you can't ping yourself by bare hostname

### ISSUE THREAD

**Issue by Xe** [tailscale/tailscale#4647] opened 2022-05-09 15:00 UTC
### What is the issue?

When using MagicDNS, you can't ping your own machine by hostname.

```
[xena@xatci ~] $ ping xatci

Pinging xatci [fe80::99d0:ec2d:b2e7:536b%5] with 32 bytes of data:
Request timed out.

Ping statistics for fe80::99d0:ec2d:b2e7:536b%5:
    Packets: Sent = 1, Received = 0, Lost = 1 (100% loss),
Control-C
```

### Steps to reproduce

1. Create fresh windows VM from either the Windows 10 MSIX packaging environment or [this vagrant box](https://app.vagrantup.com/gusztavvargadr/boxes/windows-10)
2. run `ping (hostname)`
3. see it work
4. install Tailscale and log in
5. run `ping (hostname)`
6. see it not work

### OS

Windows

### OS version

10, 11

### Tailscale version

1.25.0

### Bug report

BUG-495ff6490a5112f9cb8a60d1e2598749bd609d5110641115b67dffe609b339be-20220509150038Z-0e69a407d89e9728

**Comment by bradfitz** [comment] 2022-05-09 15:01
Works for me on Windows 10 but not on Windows 11.

So quite likely the Windows version is not relevant.

/cc @dblohm7 @danderson

**Comment by raggi** [comment] 2022-05-09 17:32
I can reproduce.

The reason it's hitting the Tailscale interface is that the interface has the lowest metric.
I noticed it also hits it when Tailscale is disconnected - we should probably consider downing the interface in that state, as we also haven't deconfigured the last dns suffix, which is the first to be searched for the same reason.

The behavior visible in Wireshark is curious:

![image](https://user-images.githubusercontent.com/348/167465290-43d0f7e8-c665-4efe-aba7-d8f94189e882.png)

**Comment by michaeldelago** [comment] 2022-05-10 13:14
I'm able to replicate this on Windows 10. It appears that disabling IPv6 for the Tailscale interface is a workaround, though it doesn't persist reboots.

```pwsh
PS C:\Users\vagrant> ping (hostname)

Pinging DESKTOP-6JAK6B8 [fe80::99d0:ec2d:b2e7:536b%6] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for fe80::99d0:ec2d:b2e7:536b%6:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
PS C:\Users\vagrant> Disable-NetAdapterBinding -Name 'Tailscale' -ComponentID 'ms_tcpip6'
PS C:\Users\vagrant> ping (hostname)

Pinging DESKTOP-6JAK6B8 [fe80::49e0:c18c:10a7:a109%4] with 32 bytes of data:
Reply from fe80::49e0:c18c:10a7:a109%4: time<1ms
Reply from fe80::49e0:c18c:10a7:a109%4: time<1ms
Reply from fe80::49e0:c18c:10a7:a109%4: time<1ms
Reply from fe80::49e0:c18c:10a7:a109%4: time<1ms

Ping statistics for fe80::49e0:c18c:10a7:a109%4:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```

**Comment by raggi** [comment] 2022-05-10 22:20
I'm also curious to see that you have the same link local address. My assumption is that Windows isn't defaulting to privacy preserving for these interfaces for some reason, and that Wintun is always using the same MAC address.

Perhaps we should explicitly unconfigure this link local address.

**Comment by twitchyliquid64** [comment] 2022-05-26 16:45
Given that each node will have a different IPv6 Tailscale address, could we just use that? It seems that MagicDNS is responding with all our localhost IPs, including link-local:

![image](https://user-images.githubusercontent.com/6328589/170534772-515fe964-8635-4b33-8abb-aa34cdbadf8d.png)

Unless theres a reason we're putting in DNS already, maybe we can skip providing link-local addresses in response to magic DNS? At the very least for the hardcoded Wintun MAC address?

**Comment by raggi** [comment] 2022-05-26 18:18
@twitchyliquid64 yeah, definitely skip it - I don't think we're actually routing traffic for that address, so we should really remove it completely, but definitely not serving it from dns is a good step.

**Comment by twitchyliquid64** [comment] 2022-05-26 18:34
Upon more digging it seems we're (tailscaled) is not even aware of this IP, and the DNS resolution is coming from LLMNR.

Removing the address from the interface table entirely fixes this, as you suggested in https://github.com/tailscale/tailscale/issues/4647#issuecomment-1122952322.

I'm inclined to fix this by having our Windows interface code make sure that address is never present on our tun.

**Comment by twitchyliquid64** [comment] 2022-05-27 21:43
The fix for this should go out in 1.26.

**Comment by raggi** [comment] 2022-06-14 00:12
User reported that this still occurs on their system, as their system chose a different link local address. Further discussion with folks suggests that we did not disable all link-local addresses so as to avoid thrashing if the OS starts adding it back.

I added a note here: https://github.com/tailscale/tailscale/issues/4829#issuecomment-1154559305 about a flag that can be set through `netsh` or PowerShell called `SkipAsSource` that _may_ do what we want, but we will need to test that. In addition it also does not have a documented registry interface, so we will either need to call out to PowerShell or look at what it performs under the hood.

**Comment by bradfitz** [comment] 2022-06-14 04:33
>  In addition it also does not have a documented registry interface, so we will either need to call out to PowerShell or look at what it performs under the hood.

The Go library we use supports it:

https://pkg.go.dev/golang.zx2c4.com/wireguard/windows/tunnel/winipcfg#MibUnicastIPAddressRow.SkipAsSource

Microsoft docs:

https://docs.microsoft.com/en-us/windows/win32/api/netioapi/ns-netioapi-mib_unicastipaddress_row

**Comment by raggi** [comment] 2022-06-14 18:29
Thanks @bradfitz. I found it being reported in WMI then went past this and recency of WMI in mind I incorrectly translated MIB to SNMP, which it was not.

**Closed** 2022-06-22 22:26 UTC
Labels: OS-windows, L3 Some users, P1 Nuisance, T5 Usability, dns, bug
