### ISSUE TITLE
Android: black screen on SM-J105B with OS 5.1.1 

### ISSUE THREAD

**Issue by Gersonzao** [tailscale/tailscale#5920] opened 2022-10-13 14:35 UTC
### What is the issue?

Device model: SM-J105B

I tried both F-Droid and Play Store versions o

### Steps to reproduce

1. Open the app

### Are there any recent changes that introduced the issue?

No

### OS

Android

### OS version

Android Lollipop 5.1.1

### Tailscale version

1.32 and 1.31.40

**Comment by DentonGentry** [comment] 2022-10-13 16:19
Most likely an incompatibility with OpenGL version and Gio support, given the age of the device. This usually manifests as a `glError` in logcat output.

Is there a way to download older F-Droid releases? https://f-droid.org/repo/com.tailscale.ipn_125.apk is 1.31.41. In 1.22 we turned off Vulkan, which we believed would help with compatibility with older devices, but could try it with Vulkan enabled. Build 90, which would presumably be https://f-droid.org/repo/com.tailscale.ipn_90.apk, would have Vulkan on but there is no APK at that link.

**Comment by Gersonzao** [comment] 2022-10-13 17:34
I tried 1.21.114 and I still have t

**Comment by Gersonzao** [comment] 2022-10-13 17:39
I accidentally closed the issue, sorry. By the way, AFAIK, you can only see 3 or 4 previous versions of an app in the web version of F-Droid, but in the client, you can see most of them (if not all)

**Comment by DentonGentry** [comment] 2023-02-18 18:10
We're handling these OpenGL ES2 devices on https://github.com/tailscale/tailscale/issues/4332

Duplicate of https://github.com/tailscale/tailscale/issues/4332

**Closed by DentonGentry** 2023-02-18 18:10 UTC
Labels: OS-android, L1 Very few, P3 Can't get started, T6 Major usability, bug
