### ISSUE TITLE
The --no-logs-no-support parameter is invalid, and the user's information can still be displayed in the log

### ISSUE THREAD

**Issue by ilanni2460** [tailscale/tailscale#6121] opened 2022-10-29 15:25 UTC
The `--no-logs-no-support` parameter is invalid, and the user's information can still be displayed in the log

Running tailscale in docker mode
![1](https://user-images.githubusercontent.com/5058391/198840092-5c583125-644e-47c8-8cc9-ca7ecdce222f.png)
![2](https://user-images.githubusercontent.com/5058391/198840110-1a7d1255-0a2d-4582-aef7-bf18af127612.png)

**Comment by DentonGentry** [comment] 2022-10-29 15:29
```
# tailscale version
1.33.102
  tailscale commit: cfef47ddcc09256377f0dd4514e1a712d3d92fc0
  other commit: 6a93549f0b3816a357c6a2e71d89ba2c188a1e37
  go version: go1.19.2-ts3fd24dee31

# tailscaled --no-logs-no-support
2022/10/29 15:28:00 You have disabled logging. Tailscale will not be able to provide support.
logtail started
Program starting: v1.33.102-tcfef47ddc-g6a93549f0, Go 1.19.2-ts3fd24dee31: []string{"tailscaled", "--no-logs-no-support"}
```

What error do you see?

**Comment by DentonGentry** [comment] 2022-10-29 15:33
The process still writes to stdout, its output is visible locally.
With `--no-logs-no-support` nothing is uploaded for Tailscale support.
You can also block log.tailscale.com in firewall rules if desired.

**Comment by bradfitz** [comment] 2022-10-31 03:00
The flag's docs are clear:

```
  -no-logs-no-support
        disable log uploads; this also disables any technical support
```

It doesn't say it stops logging. It stops uploading them.

Closing as working as intended.

**Closed by bradfitz** 2022-10-31 03:00 UTC
Labels: L1 Very few, P2 Aggravating, waiting-for-info, bug

**Comment by kgersen** [comment] 2022-11-16 16:38
I got confused too and spent some times finding the explanation here.
I checked the online documentation at https://tailscale.com/kb/1011/log-mesh-traffic/?tab=linux#opting-out-of-client-logging

imho, "Opting out of client logging" isn't the same as: "disable log uploads" and it's confusing.
