### ISSUE TITLE
1.36.2 "Prevent using an exit node while being an exit node" breaks functionality on macOS

### ISSUE THREAD

**Issue by rweirtbg** [tailscale/tailscale#7425] opened 2023-03-02 11:49 UTC
### What is the issue?

We have been using Tailscale in this configuration for quite sometime. Why is this feature being removed from macOS Tailscale?

### OS

macOS

### OS version

13.21

### Tailscale version

1.36.2

**Comment by DentonGentry** [comment] 2023-03-02 13:33
Simultaneously using an exit node and being an exit node worked poorly on several platforms. It led to a neverending series of support tickets, because it was not intentionally a feature — Tailscale is not intended to be an onion router.

If you want to continue using an older release you are welcome to. We currently maintain compatibility back to Tailscale 0.100, because there are still several nodes out there running that version. Older App Store releases can be loaded using TestFlight, older macSys releases can be downloaded:  https://pkgs.tailscale.com/stable/Tailscale-1.36.2-macos.zip
Replace 1.36.2 with the earlier version desired.

**Comment by mihaip** [comment] 2023-03-02 18:21
Note that 1.36.2 merely updated the UI disallow trying to set this combination, it was already not possible to configure the app into this state with 1.36.0 or later (when the fix for #3569) was picked up. So if you'd like to go back to an older version, it'd need to be a 1.34.x release or earlier.

**Comment by DentonGentry** [comment] 2023-03-23 01:20
Closing as working as intended.

**Closed by DentonGentry** 2023-03-23 01:20 UTC
Labels: needs-triage, bug
