### ISSUE TITLE
Android TV v9.0 - Tailscale v1.24.0, Tailscale does not work on Android TV v9

### ISSUE THREAD

**Issue by csp5me** [tailscale/tailscale#4510] opened 2022-04-25 04:39 UTC
After succesfully installing Tailscale on Android TV v9.0, Tailscale starts with a white screen, then black screen and will exit. 
Clearing data and cache does not solve the issue.

Tailscale does not have problem with Android [TV] v10+.

**Comment by DentonGentry** [comment] 2022-04-25 12:23
We see similar behavior on an NVideia Shield with Android 8, but haven't figured out how to fix it yet: https://github.com/tailscale/tailscale/issues/4332

**Comment by DentonGentry** [comment] 2022-04-30 17:38
Duplicate of https://github.com/tailscale/tailscale/issues/4332

**Closed by DentonGentry** 2022-04-30 17:38 UTC
Labels: OS-android, L1 Very few, P3 Can't get started, T5 Usability
