### ISSUE TITLE
Support Mullvad exit node in Mexico

### ISSUE THREAD

**Issue by DouweM** [tailscale/tailscale#9616] opened 2023-10-02 03:02 UTC
### What are you trying to do?

Enable Mullvad exit node on my account, from Mexico.

It doesn’t work, as Mexico is not supported per the support page.

**Comment by DentonGentry** [comment] 2023-10-02 03:19
Duplicate of https://github.com/tailscale/tailscale/issues/9314

**Closed by DentonGentry** 2023-10-02 03:19 UTC
Labels: needs-triage, fr
