### ISSUE TITLE
FR: [Android] Group Mullvad exit nodes in UI

### ISSUE THREAD

**Issue by aw1cks** [tailscale/tailscale#10214] opened 2023-11-12 10:43 UTC
### What are you trying to do?

On desktop clients, the Mullvad exit nodes have a nice integration where you can select a fly-out menu, pick the country, then select the exit node you want. On Android, no such feature exists and all the Mullvad nodes show up in the same list as the rest of your exit nodes, making it extremely difficult to find anything.

### How should we solve this?

Ideally, the Mullvad exit nodes should be grouped separately, to make it easier to traverse your list of exit nodes. The best solution would be to group by country, but at least grouping all Mullvad exit nodes on their own would be a huge improvement.

### What is the impact of not solving this?

It's really difficult to find the exit node you want - especially given there's no search or favorite feature. This is especially painful on android TV devices where you have to scroll with a remote, which takes a very long time given the hundreds of Mullvad exit nodes.

**Comment by felschr** [comment] 2024-01-08 13:50
Looks like this is implemented in a nice way on iOS already:
https://github.com/maxgallup/tailscale-status/assets/3314323/9a489d56-2db3-4e31-91ab-79b033d70145

Would love to see the same thing for Android.

**Comment by catzkorn** [comment] 2024-02-07 21:59
Closing this as a dupe of #9421. All discussion around grouping Mullvad exit nodes will happen there! Thanks

**Closed by catzkorn** 2024-02-07 21:59 UTC
Labels: needs-triage, fr, mullvad
