### ISSUE TITLE
WSL2 w/ Windows Server 2019: module tun not found

### ISSUE THREAD

**Issue by yacrdnl** [tailscale/tailscale#4832] opened 2022-06-09 23:04 UTC
### What is the issue?

Tailscale Backend Error: 
TUN: Error creating interface: Catastrophic failure

I have looked at deleting Tailscale files from Windows, and trying to ensure interfaces are deleted as well, and uninstalled / reinstalled a number of times. I have the same error each time. I am not able to delete any interfaces because no interfaces can be made. 

I am reporting for Windows Server 2019. Also attempted to run tailscale from WSL2 inside Windows Server 2019, and received another TUN error, maybe this is helpful additional info? Sorry if it is not I am not very experienced reporting bugs:

Program starting: v1.26.0-te635c1a0b-g63b494195, Go
1.18.3-ts04d67b90d8: []string{"tailscaled"}
LogID: 898ca950bcc7e4664773f5955f728624c8cceb897e94defba3be08281795ecf7
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
Linux kernel version: 4.4.0-17763-Microsoft
is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with:
modprobe: FATAL: Module tun not found in directory
/lib/modules/4.4.0-17763-Microsoft
tun module not loaded nor found on disk
wgengine.NewUserspaceEngine(tun "tailscale0") error:
tstun.New("tailscale0"): CreateTUN("tailscale0") failed; /dev/net/tun
does not exist
flushing log.
logger closing down
createEngine: tstun.New("tailscale0"): CreateTUN("tailscale0") failed;
/dev/net/tun does not exist

### Steps to reproduce

1. Install Tailscale via either the .exe or .msi
2. Reboot
3. Confirm service is running in Microsoft Windows 2019 Services 
4. Run Tailscale application as administrator (opens and fails automatically on boot / login also)
5. Icon will appear in tray until failure 
6. Right clicking icon has few options, most greyed out, says "Please Restart the Tailscale WIndows Service"
7. Within a few minutes, sometimes seconds, will receive the Tailscale Error popup

### Are there any recent changes that introduced the issue?

First attempt trying to install on Windows Server 2019. 

### OS

Windows

### OS version

Windows Server 2019

### Tailscale version

1.26.0 tailscale-setup-1.26.0-amd64

### Bug report

c615d8c47fca53e34c58bfd5416877f1a6e6753001939530d10cbcadce7a721b

**Comment by DentonGentry** [comment] 2022-10-31 04:49
The only other case of `is CONFIG_TUN enabled in your kernel? modprobe tun failed with:
modprobe: FATAL: Module tun not found in directory` for WSL2 we've had reported was https://github.com/tailscale/tailscale/issues/562#issuecomment-955729454 where the solution was to run it with sudo.

**Comment by DentonGentry** [comment] 2023-02-17 23:36
I believe this is a duplicate of #562.

**Closed by DentonGentry** 2023-02-17 23:36 UTC
Labels: OS-windows, L3 Some users, P3 Can't get started, T5 Usability, bug
