### ISSUE TITLE
Make the App more usefull

### ISSUE THREAD

**Issue by sissiwup** [tailscale/tailscale#2982] opened 2021-10-02 07:39 UTC
Hello,

I love tailscale. Some optimizations would help me in daily business

- Home-WLAN: Disable tailscale when the device is in the home-wlan, when a roadwarrior comes home, there is no need to use vpn
- Allways on when connecting to the internet. I have to start the tailscale App (ios) when I want a connection to the vpn network. F.e. with the wireguard app you are always in the network (when not in specific wlans)

**Comment by gvccvwangmingn2** [comment] 2021-10-02 09:07
> * Home-WLAN: Disable tailscale when the device is in the home-wlan, when a roadwarrior comes home, there is no need to use vpn

What's hard with manually turning Tailscale off when you enter your home network? It's not worth the time & money for tailscale devs to create that feature.

>*Allways on when connecting to the internet. I have to start the tailscale App (ios) when I want a connection to the vpn network. F.e. with the wireguard app you are always in the network (when not in specific wlans)

From what I know, it is always on. Everytime I switch between different wifi or cellular networks, tailscale is still connected, maybe some few drops while switching.

**Comment by sissiwup** [comment] 2021-10-02 13:55
Hello,

it´s not hard but comfortable when it will do automatically.
In IOS I often have to recall the App, then the VPN is started. And no, the Handy was not turned off between.

**Comment by DentonGentry** [comment] 2021-10-02 15:57
Turning off subnet relays when on the local LAN is tracked in https://github.com/tailscale/tailscale/issues/1227

Having the app be always-on is tracked in https://github.com/tailscale/tailscale/issues/1698

Duplicate of https://github.com/tailscale/tailscale/issues/1698 and https://github.com/tailscale/tailscale/issues/1227

**Closed by DentonGentry** 2021-10-02 15:57 UTC
Labels: needs-triage
