### ISSUE TITLE
tailscale policy routing on linux will result in external machines not being able to access this server via the subnet router

### ISSUE THREAD

**Issue by hzgongsha** [tailscale/tailscale#12450] opened 2024-06-13 10:04 UTC
### What is the issue?

Currently, all the subnet routers are used in the intranet, and windows and macos can access each other through physical IP normally, but after ubuntu installs tailscale and sets accept-outers=true, both windows and macos can't access to ubuntu through physical IP normally. However, ubuntu can access it normally, the result we want is to be able to access this ubuntu machine normally.  maybe my description is not too clear, you can refer to the following sample diagrams
![tailscale (1)](https://github.com/tailscale/tailscale/assets/43987223/d182827c-029a-4e80-9326-17282a00d483)

### Steps to reproduce

subnet router node : 10.107.100.20 (tailscale up && accept-routes=false && advertise-routes=10.107.0.0/16)
my windows node ： 10.107.25.177 （tailscale up && accept-routes=true）
my ubuntu node: 10.107.19.20 (tailscale up & accept-routes=true)
I can't access or ping my ubuntu node from my own Windows node, but the ubuntu node can access my Windows node in reverse.  
I found that on my Windows node the routes are put together with all, on the ubuntu machine there is a separate routing table with the name 52, the cut priority is higher than the main routes，This will cause requests where the dst IP is the local physical IP to not packetize back properly, would like to know what's causing this, should be good to reproduce
![image](https://github.com/tailscale/tailscale/assets/43987223/86c1ff73-4246-450b-a660-1211cd5b6562)

### Are there any recent changes that introduced the issue?

No response

### OS

Linux

### OS version

ubuntu20.04 and CentOS7

### Tailscale version

1.66.4

**Comment by timtailscale** [comment] 2024-08-12 18:33
This appears to be a duplicate of #1227, you can use the [troubleshooting doc here](https://tailscale.com/kb/1023/troubleshooting#lan-traffic-prioritization-with-overlapping-subnet-routes) for details on how to prioritize LAN connections on your Ubuntu node which will solve this.

**Closed by timtailscale** 2024-08-12 18:33 UTC
Labels: bug, subnet
