### ISSUE TITLE
windows: Failed to write packet to TUN device: file already closed

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1852] opened 2021-05-05 16:54 UTC
The customer lost the connections from multiple windows machines. Logs are as follows;

2021-05-04T20:27:53.469+03:00: 2021/05/04 20:27:53 Failed to receive packet: read udp4 0.0.0.0:41641: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress.
2021-05-04T20:27:53.541+03:00: 2021/05/04 20:27:53 netcheck: probePortMapServices: failed to look up gateway address
2021-05-04T20:27:53.813+03:00: 2021/05/04 20:27:53 Drop: Unknown{???} 97 unknown
2021-05-04T20:27:53.813+03:00: 2021/05/04 20:27:53 Failed to write packet to TUN device: packet dropped by filter
2021-05-04T20:27:53.813+03:00: 2021/05/04 20:27:53 Failed to write packet to TUN device: file already closed
2021-05-04T20:27:53.814+03:00: 2021/05/04 20:27:53 Failed to write packet to TUN device: file already closed
2021-05-04T20:27:53.814+03:00: 2021/05/04 20:27:53 Failed to write packet to TUN device: file already closed
2021-05-04T20:27:53.814+03:00: 2021/05/04 20:27:53 Failed to write packet to TUN device: file already closed

Tailscale version of the source machine: 1.6.0
Tailscale version of the destination machine: 1.6.0
OS : Windows 10  & other end is Windows Server 2016 Standard Version: 1607

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_340b5)

**Comment by apenwarr** [comment] 2021-05-06 01:51
TUN devices should never close during runtime as far as I know, so whatever this is, is probably a serious bug.

Not a regression since it happened in v1.6.0.

**Comment by apenwarr** [comment] 2021-05-06 02:39
I suggest we save fixing this until v1.8.1 at the earliest.

**Comment by yefimg** [comment] 2021-05-06 06:03
A quick comment on the initial report:
1. Both machines are Windows Server 2016
2. Linux machines in the same tailscale account and data center are not affected, seems to be Windows-only bug

**Comment by DentonGentry** [comment] 2021-10-13 22:25
wintun has been updated several times since 1.6 and will be updated again in 1.18. I don't think this bug has occurred recently. Barring further updates, we'll plan to close this during the next bug scrub.

**Comment by DentonGentry** [comment] 2021-11-10 00:40
Closing during bug scrub.

**Closed by DentonGentry** 2021-11-10 00:40 UTC
Labels: OS-windows, L3 Some users, P2 Aggravating, T5 Usability
