### ISSUE TITLE
Exit nodes and subnets unavailable in iOS app when disableIPv4 set to true

### ISSUE THREAD

**Issue by w1ndy** [tailscale/tailscale#4094] opened 2022-03-08 05:55 UTC
### What is the issue?

When `disableIPv4` is set to true in ACL, the exit node menu item disappears from the iOS app. I can't access subnets either.

### Steps to reproduce

1. Add `"disableIPv4": true` to ACL
2. Open the menu in the iOS app
3. `Use exit node` disappeared from the menu

### OS

iOS

### OS version

iOS 15.3.1

### Tailscale version

1.22.0

**Comment by DentonGentry** [comment] 2022-05-08 01:19
To make progress we would need some information to go on, either a bugreport of the IP address of the device.

**Comment by sroracle** [comment] 2022-05-23 21:17
I am seeing the same issue on macOS 12.3.1 and Tailscale 1.24.2. This is on the tailnet linked to this GitHub account.

**Comment by DentonGentry** [comment] 2022-10-30 23:44
Duplicate of https://github.com/tailscale/tailscale/issues/5723 (which has more detail)

**Closed by DentonGentry** 2022-10-30 23:44 UTC
Labels: connectivity, L1 Very few, P2 Aggravating, T5 Usability, waiting-for-info, exit-node, bug
