### ISSUE TITLE
android: route deletions not propagated to the OS

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1046] opened 2020-12-20 02:04 UTC
With the change in https://github.com/tailscale/tailscale-android/pull/5 applied, it's possible to advertise a default route from a linux machine (`tailscale up --advertise-routes=0.0.0.0/0,::/0`, then approve the routes in the admin panel), and Android with Tailscale enabled will correctly route through that default route.

However, if you then disable the routes in the admin panel, the phone loses internet connectivity.

Using `adb shell`, what I saw is:
 - When default routes are enabled in the admin panel, the Tailscale app receives a netmap update, and correctly installs the default routes in the VPN routing table (visible with `ip route show table all` in adb shell - can't remember what routing table number it is).
 - When default routes are disabled in the admin panel, the Tailscale app receives a netmap update, passes the correct routes to VpnService.Builder (/32 to nodes, but no default routes; I verified this by adding debug statements to tailscale.apk, and by checking system logs to prove that ConnectivityService received the correct route set from us). However, after applying this change, **the default routes are still present in the OS network stack** (visible with `ip route show table all` in adb shell). But because we disabled the default routes, Tailscale no longer allows traffic to flow along that route, and so we lose internet connectivity.
 - Disable Tailscale using the app slider. Internet connectivity comes back, as all VPN routes are deleted in the OS (see `ip route show table all` again).

Expected behavior: when we get the netmap update that removes the default routes, the default routes should get removed from the OS as well, so that Android goes back to using the non-Tailscale internet.

This is either an Android bug, or we're not doing the correct lifecycle operations to update VPN routes when the VPN is already established.

I produced this bug using the Android emulator, running a fake Pixel 3a, loaded with a tailscale apk built at HEAD + https://github.com/tailscale/tailscale-android/pull/5. Without that PR, enabling default routes will cause the phone to lose internet connectivity due to a routing loop, so it's necessary to debug this further.

/cc @eliasnaur, as I've kind of run out of ideas for how to diagnose/fix.

**Comment by eliasnaur** [comment] 2020-12-26 12:02
Thank you for the detailed reproduction steps. However, I failed to reproduce the error on an Android API 30 (Android 11) emulator.

Here's my routes after running `tailscale up --advertise-routes=0.0.0.0/0,::/0`, before enabling the default route in the admin panel:

```
$ adb shell ip route show table all
default dev dummy0 table 1002 proto static scope link 
default via 10.0.2.2 dev radio0 table 1017 proto static mtu 1500 
10.0.2.0/24 dev radio0 table 1017 proto static scope link 
10.0.2.0/24 dev radio0 proto kernel scope link src 10.0.2.15 
100.79.134.64 dev tun0 table 1023 proto static scope link 
100.81.132.94 dev tun0 table 1023 proto static scope link 
100.100.100.100 dev tun0 table 1023 proto static scope link 
100.101.102.103 dev tun0 table 1023 proto static scope link 
broadcast 10.0.2.0 dev radio0 table local proto kernel scope link src 10.0.2.15 
local 10.0.2.15 dev radio0 table local proto kernel scope host src 10.0.2.15 
broadcast 10.0.2.255 dev radio0 table local proto kernel scope link src 10.0.2.15 
local 100.79.134.64 dev tun0 table local proto kernel scope host src 100.79.134.64 
broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1 
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1 
fe80::/64 dev dummy0 table 1002 proto kernel metric 256 pref medium
default dev dummy0 table 1002 proto static metric 1024 pref medium
fe80::/64 dev radio0 table 1017 proto kernel metric 256 pref medium
fe80::/64 dev radio0 table 1017 proto static metric 1024 pref medium
fec0::/64 dev radio0 table 1017 proto kernel metric 256 expires 86018sec pref medium
fec0::/64 dev radio0 table 1017 proto static metric 1024 pref medium
default via fe80::2 dev radio0 table 1017 proto ra metric 1024 expires 1418sec hoplimit 64 pref medium
fe80::/64 dev tun0 table 1023 proto kernel metric 256 pref medium
local ::1 dev lo table local proto kernel metric 0 pref medium
local fe80::1c71:85ff:feee:568c dev radio0 table local proto kernel metric 0 pref medium
local fe80::38f2:bbff:fe39:702 dev dummy0 table local proto kernel metric 0 pref medium
local fe80::8540:ef43:ca18:e0a9 dev tun0 table local proto kernel metric 0 pref medium
local fec0::1c71:85ff:feee:568c dev radio0 table local proto kernel metric 0 pref medium
local fec0::dd99:4464:4de9:f7fb dev radio0 table local proto kernel metric 0 pref medium
ff00::/8 dev dummy0 table local metric 256 pref medium
ff00::/8 dev radio0 table local metric 256 pref medium
ff00::/8 dev tun0 table local metric 256 pref medium
```

And here they are after enabling the default route:

```
$ adb shell ip route show table all
default dev tun0 table 1024 proto static scope link 
100.79.134.64 dev tun0 table 1024 proto static scope link 
100.81.132.94 dev tun0 table 1024 proto static scope link 
100.100.100.100 dev tun0 table 1024 proto static scope link 
100.101.102.103 dev tun0 table 1024 proto static scope link 
default dev dummy0 table 1002 proto static scope link 
default via 10.0.2.2 dev radio0 table 1017 proto static mtu 1500 
10.0.2.0/24 dev radio0 table 1017 proto static scope link 
10.0.2.0/24 dev radio0 proto kernel scope link src 10.0.2.15 
broadcast 10.0.2.0 dev radio0 table local proto kernel scope link src 10.0.2.15 
local 10.0.2.15 dev radio0 table local proto kernel scope host src 10.0.2.15 
broadcast 10.0.2.255 dev radio0 table local proto kernel scope link src 10.0.2.15 
local 100.79.134.64 dev tun0 table local proto kernel scope host src 100.79.134.64 
broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1 
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1 
fe80::/64 dev tun0 table 1024 proto kernel metric 256 pref medium
default dev tun0 table 1024 proto static metric 1024 pref medium
fe80::/64 dev dummy0 table 1002 proto kernel metric 256 pref medium
default dev dummy0 table 1002 proto static metric 1024 pref medium
fe80::/64 dev radio0 table 1017 proto kernel metric 256 pref medium
fe80::/64 dev radio0 table 1017 proto static metric 1024 pref medium
fec0::/64 dev radio0 table 1017 proto kernel metric 256 expires 85977sec pref medium
fec0::/64 dev radio0 table 1017 proto static metric 1024 pref medium
default via fe80::2 dev radio0 table 1017 proto ra metric 1024 expires 1377sec hoplimit 64 pref medium
local ::1 dev lo table local proto kernel metric 0 pref medium
local fe80::8e3:9601:e919:4d7b dev tun0 table local proto kernel metric 0 pref medium
local fe80::1c71:85ff:feee:568c dev radio0 table local proto kernel metric 0 pref medium
local fe80::38f2:bbff:fe39:702 dev dummy0 table local proto kernel metric 0 pref medium
local fec0::1c71:85ff:feee:568c dev radio0 table local proto kernel metric 0 pref medium
local fec0::dd99:4464:4de9:f7fb dev radio0 table local proto kernel metric 0 pref medium
ff00::/8 dev dummy0 table local metric 256 pref medium
ff00::/8 dev radio0 table local metric 256 pref medium
ff00::/8 dev tun0 table local metric 256 pref medium
```

At this point internet connectivity is gone from the Android device, presumably because my Linux machine is not configured to route foreign packets.

After disabling the default route again:

```
$ adb shell ip route show table all
100.79.134.64 dev tun0 table 1025 proto static scope link 
100.81.132.94 dev tun0 table 1025 proto static scope link 
100.100.100.100 dev tun0 table 1025 proto static scope link 
100.101.102.103 dev tun0 table 1025 proto static scope link 
default dev dummy0 table 1002 proto static scope link 
default via 10.0.2.2 dev radio0 table 1017 proto static mtu 1500 
10.0.2.0/24 dev radio0 table 1017 proto static scope link 
10.0.2.0/24 dev radio0 proto kernel scope link src 10.0.2.15 
broadcast 10.0.2.0 dev radio0 table local proto kernel scope link src 10.0.2.15 
local 10.0.2.15 dev radio0 table local proto kernel scope host src 10.0.2.15 
broadcast 10.0.2.255 dev radio0 table local proto kernel scope link src 10.0.2.15 
local 100.79.134.64 dev tun0 table local proto kernel scope host src 100.79.134.64 
broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1 
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1 
fe80::/64 dev tun0 table 1025 proto kernel metric 256 pref medium
fe80::/64 dev dummy0 table 1002 proto kernel metric 256 pref medium
default dev dummy0 table 1002 proto static metric 1024 pref medium
fe80::/64 dev radio0 table 1017 proto kernel metric 256 pref medium
fe80::/64 dev radio0 table 1017 proto static metric 1024 pref medium
fec0::/64 dev radio0 table 1017 proto kernel metric 256 expires 86393sec pref medium
fec0::/64 dev radio0 table 1017 proto static metric 1024 pref medium
default via fe80::2 dev radio0 table 1017 proto ra metric 1024 expires 1793sec hoplimit 64 pref medium
local ::1 dev lo table local proto kernel metric 0 pref medium
local fe80::1c71:85ff:feee:568c dev radio0 table local proto kernel metric 0 pref medium
local fe80::38f2:bbff:fe39:702 dev dummy0 table local proto kernel metric 0 pref medium
local fe80::d821:feb0:8d94:8b83 dev tun0 table local proto kernel metric 0 pref medium
local fec0::1c71:85ff:feee:568c dev radio0 table local proto kernel metric 0 pref medium
local fec0::dd99:4464:4de9:f7fb dev radio0 table local proto kernel metric 0 pref medium
ff00::/8 dev dummy0 table local metric 256 pref medium
ff00::/8 dev radio0 table local metric 256 pref medium
ff00::/8 dev tun0 table local metric 256 pref medium
```

At this point the device regained internet connectivity, as I would have expected absent this bug report.

What version of Android did you run during your tests?

**Comment by danderson** [comment] 2021-01-18 22:16
Hmm, that routing state looks correct, so there's something else going on I guess. I'm working on verifying other stuff on Android now, so I'll try to repro this again and get you more details (or close this bug if I can't repro).

**Comment by danderson** [comment] 2021-01-18 23:07
Yeah, never mind, on a Pixel 3a with API 30, I'm unable to reproduce. {Enabling,disabling} {tailscale in app,routes in admin panel} all update the Android network stack correctly.

**Comment by DentonGentry** [comment] 2021-05-20 21:51
As this hasn't been reproducible for months, going to close it.

**Closed by DentonGentry** 2021-05-20 21:51 UTC
Labels: OS-android
