### ISSUE TITLE
Tailscale SSH not working on the newest WSL2 from the Microsoft store

### ISSUE THREAD

**Issue by btaylor84** [tailscale/tailscale#6189] opened 2022-11-03 21:31 UTC
### What is the issue?

I installed the newest WSL2 (version 0.70.4.0) in order to use systemd to have a persistent tailscaled.

however, when I try to SSH to an endpoint that is using tailscale-ssh, SSH hangs. When I use the -v flag, it's hanging on 
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
Googling for solutions to this, I found that changing the MTU size might help. The tailscale0 MTU was 1280, changing it to 1200 using: 
sudo ip li set mtu 1200 dev tailscale0
seems to fix the issue. 

### Are there any recent changes that introduced the issue?

updating WSL2 to the newest store version 0.70.4.0

### OS

Linux, Windows

### OS version

Ubuntu 20.04 instance under WSL2

### Tailscale version

1.32.2

### Bug report

BUG-05ef904c54385458fca59ef126de501d869de9b9fcd89f5aa93fbef12d51698b-20221103213125Z-7a4f490f068d3a6f

**Comment by btaylor84** [comment] 2022-11-13 18:26
Last night, my windows machine updated to Windows 11 Pro version 10.0.22621 and the issue seems to be resolved. 
I SSH'd to a tailscale-ssh machine with the default MTU 1280, and there were no issues.

**Comment by btaylor84** [comment] 2022-11-13 18:29
I spoke too soon. While it's true that a tailscale ssh worked, a more routine SSH to a server on my tailnet still failed, requiring a change to the tailscale mtu to work.

**Comment by neersighted** [comment] 2022-11-22 04:56
I've spent some time debugging this myself; this is an interaction of running Tailscale (or a VPN adapter) on the Windows host, as well as in the WSL 2 VM:

* Tailscale on the Windows host has a MTU of 1280 (the default).
* `eth0` in WSL 2 is helpfully given a MTU of 1280 by Windows so that packets to `100.64.0.0/10` can be successfully routed.
* `tailscale0` in WSL 2 is set up with Tailscale's default MTU of 1280.
* Because of this, packets at the `tailscale0` MTU are dropped by the `eth0` interface.

To solve this, you can increase the MTU of your WSL 2 `eth0` device. I don't know that there's an elegant fix (I'm using a `systemd-networkd` `.link` unit to set the MTU on startup), but ideally Microsoft would create some sort of easy escape hatch here, or Tailscale would detect this situation and give advice, or decrease the WSL `tailscale0` MTU (this is not great, but at least it doesn't surprise users).

**Comment by neersighted** [comment] 2022-11-22 04:58
This is likely a duplicate of #4833.

**Comment by btaylor84** [comment] 2022-11-22 16:04
> This is likely a duplicate of #4833.

Thanks for this pointer. I've been manually changing the tailscale0 MTU with a ZSH alias, but a systemd change makes more sense.

**Comment by aki-k** [comment] 2022-12-30 13:14
> sudo ip li set mtu 1200 dev tailscale0

Thank you, thank you, thank you. I'm running Tailscale inside WSL 2 and have docker swarm worker in WSL 2.
Now the connection doesn't jam any more.

**Comment by DentonGentry** [comment] 2023-02-18 19:48
Duplicate of https://github.com/tailscale/tailscale/issues/4833

**Closed by DentonGentry** 2023-02-18 19:48 UTC
Labels: OS-windows, OS-linux, L2 Few, P2 Aggravating, T5 Usability, bug, ssh
