### ISSUE TITLE
FR: Give more specific error message on cert mismatch

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#7138] opened 2023-02-01 14:04 UTC
### What are you trying to do?

Currently, if there is a DPI or SSL terminating proxy, the client fails with a generic "connection reset by peer" error. Having an explicit "SSL Certificate Mismatch" error would speed up troubleshooting connectivity problems. 

### How should we solve this?

Add a logline to specify that it's an SSL failure. Possibly add command line feedback or GUI error message. 

### What is the impact of not solving this?

Troubleshooting connectivity errors remain difficult when the client can't reach the log server.

**Comment by cidesaasoptics** [comment] 2023-02-01 14:14
When a firewall or some other network component decrypts/re-encrypts the ssl traffic it makes tailscale unable to connect.  Ensuring that this does not happen requires firewall configuration changes which tailscale's current documentation says are not required but clearly they are in some cases.

The challenge when this happens is that the client is silent on the error type and the tailscale admin console shows nothing.  It requires several back-and-forths with tailscale support plus resolution requires someone with knowledge of https inspection configuration settings.  

This needs to be easier to diagnose.  More importantly, there must be sufficient information in the log messages and/or documentation to give to the IT/networking staff to correct their configuration.

In particular, for what URLs must HTTPS inspection be disabled and in what direction (in or out)?

**Comment by bradfitz** [comment] 2023-02-01 17:28
Dup of #3198 I think

**Comment by DentonGentry** [comment] 2023-02-12 03:12
Duplicate of https://github.com/tailscale/tailscale/issues/3198

**Closed by DentonGentry** 2023-02-12 03:12 UTC
Labels: needs-triage, fr

**Comment by cidesaasoptics** [comment] 2023-02-12 13:16
This was not related to a self-signed certificate which is what the other issue identified.  You might want to change the title of that if multiple issues can cause the same problem.

**Comment by DentonGentry** [comment] 2023-02-12 13:21
I updated the title, but the solution will be the same to better surface when certificate validation fails.
