### ISSUE TITLE
FR: Add an --accept-routes-filter flag

### ISSUE THREAD

**Issue by alex-richman-onesignal** [tailscale/tailscale#3607] opened 2021-12-22 18:46 UTC
### What are you trying to do?

Currently when --accept-routes is passed the client will accept all routes advertised to it.  It would be nice to have a way to apply a client-side filter so that it would only accept a subset of the advertised routes.

I think this would primarily be useful from a security/privacy perspective where multiple administrators have access to approve new routes in the console (for example, in a company with an ops team).  Presently an administrator could (for example) grab routes for some public IPs and MITM all the traffic.

### How should we solve this?

This could be solved by adding a client-side filter for the accepted routes, presumably in CIDR format which are AND'd with the advertised routes to produce the routes to apply to the client.

For example:

Advertised routes:
10.1.0.0/16
10.2.0.0/16
104.154.0.0/15 # Google routes, let's filter these

tailscale up ... --accept-routes --accept-routes-filter=10.0.0.0/8

Applied routes:
10.1.0.0/16
10.2.0.0/16

**Comment by DentonGentry** [comment] 2021-12-22 19:01
Duplicate of https://github.com/tailscale/tailscale/issues/286

**Closed by DentonGentry** 2021-12-22 19:01 UTC
Labels: needs-triage, fr

**Comment by jorhett** [comment] 2023-04-22 18:04
Please reopen this, as #286 was closed with a solution that does not address the need expressed in this issue:
> The uses of this feature described earlier in this issue involve overlapping IPv4 subnets as the main concern, allowing the client to select which specific subnet router it will use [...] At this point I'm going to close this feature request as completed, using 4via6 routing.

**Comment by DentonGentry** [comment] 2023-04-22 18:09
You are at this point commenting on every issue involving subnet routing. I understand that you are upset and want a different solution. I don't expect to carry out that discussion spread across ever such GitHub issue.

**Comment by jorhett** [comment] 2023-04-23 09:36
> You are at this point commenting on every issue involving subnet routing. I understand that you are upset and want a different solution. I don't expect to carry out that discussion spread across ever such GitHub issue.

I'm sorry, how does your reply relate to the point stated here by the OP?  This topic deserves an answer that addresses the point raised.

**Comment by ApolloF** [comment] 2023-06-12 09:01
Yeah I guess they just have absolutely no interest in adding this. If you still need to, NetBird allows filtering router for each node.
