### ISSUE TITLE
tailscale requires always-on (v1.23.152-.... (beta), android12

### ISSUE THREAD

**Issue by MatthewHannigan** [tailscale/tailscale#4365] opened 2022-04-07 00:51 UTC
### What is the issue?

With always "Always on" off in VPN settings, Tailscale will not turn on manually.  The switch on key flicks back to off immediately.

If it is "Always On" I can start manually. However turning "Always On" off then disconnects Tailscale immediately.

I had the same issue with non-beta.

### OS

Android

### OS version

12

### Tailscale version

1.23.152....

### Bug report

BUG-53159e8d36e0284ea96b1f122185e1eee6e864bf6c066ab1af2e92c199af17dc-20220407004545Z-69eaa455a789d9b0

**Comment by DentonGentry** [comment] 2022-04-07 00:56
The Intent for always on VPN support isn't correct yet: https://github.com/tailscale/tailscale/issues/2481
Even with the VPN marked as always on, it only starts at boot if it was running when the system rebooted.

I cannot duplicate the issue described here, on a Pixel 3a running Android 12 and Tailscale 1.23.152. I can turn the Always-on control in VPN Settings on or off, and Tailscale is able to be turned to Active regardless.

**Comment by MatthewHannigan** [comment] 2022-04-07 06:19
Thanks @DentonGentry .  I'll attempt to get some logs. And maybe remove app cache.
Phone is a Pixel 5, FWIW.

**Comment by DentonGentry** [comment] 2022-04-13 12:14
I think the fundamental issue here is that the Always-On setting doesn't work quite correctly. Duplicate of https://github.com/tailscale/tailscale/issues/818

**Closed by DentonGentry** 2022-04-13 12:14 UTC
Labels: needs-triage, bug
