### ISSUE TITLE
Android: GitHub login fails with default browser set to Vivaldi

### ISSUE THREAD

**Issue by sybenx** [tailscale/tailscale#4835] opened 2022-06-11 13:59 UTC
### What is the issue?

I had GitHub installed and logged in on Android. When attempting to login to tailscale through GitHub it failed to login

Error: 

`bad tailscale-authstate2 cookie: http: named cookie not present`

![Screenshot_20220611-075202_Mull](https://user-images.githubusercontent.com/2048087/173190956-3ac4bd31-e769-439b-990c-03e4b3fa15eb.jpg)

### Steps to reproduce

Install GitHub 
Login to github
Install tailscale
Login to tailscale with Other provider - GitHub
Click authorize after logging in
Error - cookie not present

### Are there any recent changes that introduced the issue?

Unknown

### OS

Android

### OS version

Android 10, 12

### Tailscale version

1.24.2

**Comment by DentonGentry** [comment] 2022-06-11 16:41
I'm not able to reproduce this. With the GitHub app installed on an Android 12 device and logged into my GitHub account, I can still use the Tailscale app to log into a tailnet using my GitHub account.

**Comment by sybenx** [comment] 2022-06-11 16:50
I have a Samsung S10e and a Note9, I can replicate this on both. I believe the issue is because GitHub doesn't respect the default browser. I have Vivaldi set as my default browser, but GitHub doesn't respect the default browser setting and attempts to open chrome. So the beginning of the request goes through Vivaldi and the authorization happens through chrome (or in my case Mull).

https://user-images.githubusercontent.com/2048087/173197111-e9e09cd9-e454-4119-b168-49f6fb6dfc46.mp4

.

**Comment by kelivel** [comment] 2022-11-03 13:47
I talked with a user today (HS 6295) who had the Github app installed and got the same error `bad tailscale-authstate2 cookie: http: named cookie not present` when logging in to Tailscale.

While reproducing this I installed the Github app and got the same error, and I noticed the Github (that was closed prior) opened in the background while I went through the Github auth flow in the Tailscale app. I assume it was trying to pass auth there, instead of back to Chrome, but failed. When I opened the Github app tab there was a popup asking if I wanted to open something in Chrome. Tapping Chrome removed the popup but did nothing. 

Logging out of the Github app let me log in successfully. I eventually cleared Chrome's entire history/cookies and after that, I could log in to Tailscale _with_ the Github app installed and authenticated. No more issues after.

**Comment by DentonGentry** [comment] 2023-02-13 05:25
I think this issue will be about as discoverable after closing it as it is open. Since I don't see anything we can do (the problem appears to be within the GitHub Android app), I'll close it as not being something we can fix.

**Closed by DentonGentry** 2023-02-13 05:25 UTC
Labels: OS-android, L1 Very few, P3 Can't get started, T5 Usability, bug

**Comment by sybenx** [comment] 2023-02-13 15:20
To avoid having users blaming Tailscale, a warning of some kind could be implemented by Tailscale in the login flow. 

> "If the GitHub app is installed, you may have to set your default browser to Chrome to login." 

Having a different default browser while GitHub is installed is likely a common scenario, e.g. Samsung phones by default use Samsung Internet.

**Comment by jonathan-morton** [comment] 2023-07-09 15:33
I am currently having this issue on Firefox on my desktop

**Comment by DentonGentry** [comment] 2023-07-09 15:37
> I am currently having this issue on Firefox on my desktop

Then it is not the same issue. This issue is very specific to the GitHub Android app.

Please open a new issue, describe the problem, and include a Tailscale bugreport.
