### ISSUE TITLE
FR: I want to add a Custom Identity Provider using OIDC or SAML protocol.

### ISSUE THREAD

**Issue by ujji8055** [tailscale/tailscale#6871] opened 2023-01-02 16:34 UTC
### What are you trying to do?

I want to add a custom Identity Provider using OIDC and SAML protocol.
Can you please suggest how can I add one?
Thanks

### How should we solve this?

Enable custom Identity Provider Feature.

**Comment by DentonGentry** [comment] 2023-01-02 17:45
We do expect to do this, but the functionality is not yet available.
Duplicate of https://github.com/tailscale/tailscale/issues/823

**Closed by DentonGentry** 2023-01-02 17:45 UTC
Labels: needs-triage, fr
