### ISSUE TITLE
Losing IP address on docker restart even though I am using a persistent volume

### ISSUE THREAD

**Issue by vladkosarev** [tailscale/tailscale#6362] opened 2022-11-17 01:56 UTC
### What is the issue?

I am running tailscale in docker and any time the container restarts it gets a new IP and a duplicate entry appears in TS UI.

### Steps to reproduce

Here's my docker-compose.yml
```
version: '3'                                                                    
services:  
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    hostname: tailscale
    environment:
      - PUID=1000
      - PGID=1000
      - TS_USERSPACE=true
      - TS_AUTH_KEY=redacted
      - TS_ROUTES=192.168.0.0/24
    volumes:
      - /docker/data/tailscale:/var/lib
      - /dev/net/tun:/dev/net/tun
    privileged: true
    restart: unless-stopped
```

If I run
`docker compose up -d`
and then
`docker compose down`
the next 
`docker compose up -d`
will create a new machine in tailscale and assign it a new IP

The volume contains the following files under tailscale folder
```
-rw------- 1 dockeruser dockeruser    0 Nov 16 20:54 tailscaled.log1.txt
-rw------- 1 dockeruser dockeruser    0 Nov 16 20:54 tailscaled.log2.txt
-rw------- 1 dockeruser dockeruser  209 Nov 16 20:33 tailscaled.log.conf
```
The conf file doesn't change between restarts

### OS

Linux

### OS version

Debian 11

**Comment by DentonGentry** [comment] 2022-11-17 01:59
```
-rw------- 1 dockeruser dockeruser    0 Nov 16 20:54 tailscaled.log1.txt
-rw------- 1 dockeruser dockeruser    0 Nov 16 20:54 tailscaled.log2.txt
-rw------- 1 dockeruser dockeruser  209 Nov 16 20:33 tailscaled.log.conf
```

There should be a `tailscale.state` file. That there isn't is the reason it gets a new IP address each time. My guess would be that this:
```
      - /docker/data/tailscale:/var/lib
```

should be this:
```
      - /docker/data/tailscale:/var/lib/tailscale
```

**Comment by vladkosarev** [comment] 2022-11-17 03:20
I should've clarified - the volume contains the files I listed under tailscale folder.
I did try to change the folder to tailscale as you proposed but that didn't make any difference.

For some reason tailscale is not creating tailscale.state even though we know it is able to write to the volume.

The only thing I can see in the log that has to do with this is the following -
if the volume is clean
```
2022/11/17 03:15:01 logpolicy: using system state directory "/var/lib/tailscale"
logpolicy.ConfigFromFile /var/lib/tailscale/tailscaled.log.conf: open /var/lib/tailscale/tailscaled.log.conf: no such file or directory
logpolicy.Config.Validate for /var/lib/tailscale/tailscaled.log.conf: config is nil
```
if the volume already has data
```
2022/11/17 03:19:40 logpolicy: using system state directory "/var/lib/tailscale"
```

**Comment by vladkosarev** [comment] 2022-11-17 03:48
Here's what happens inside the container
```
/ # ls /var/lib/tailscale/
tailscaled.log.conf  tailscaled.log1.txt  tailscaled.log2.txt
```

I tried both a mounted volume and default docker behavior. Same issue.

**Comment by TheMrDrProf** [comment] 2022-11-27 00:27
Hi @vladkosarev I had this same issue. I resolved it by setting the follow env variables:

TS_SOCKET: /var/lib/tailscale/tailscaled.sock
TS_STATE_DIR: /var/lib/tailscale

Presumably, you would only need to set the STATE_DIR, although I was unable to use the in-container tailscale cmd util as it was looking for the socket file at /var/lib/tailscale/tailscaled.sock when it was actually at /tmp/tailscaled.sock

These default locations are set by the /tailscale/run.sh file which may need to be updated by the dev team in the container.

**Comment by vladkosarev** [comment] 2022-11-28 15:50
Thank you @TheMrDrProf !
Just adding `TS_STATE_DIR: /var/lib/tailscale` did the trick!
This is definitely a bug but at least we have a workaround.
Thanks again!

**Comment by DentonGentry** [comment] 2022-12-03 15:20
Duplicate of https://github.com/tailscale/tailscale/issues/4913

**Closed by DentonGentry** 2022-12-03 15:20 UTC
Labels: needs-triage, bug
