### ISSUE TITLE
ephemeral pod on k8s cannot use Funnels 

### ISSUE THREAD

**Issue by asg0451** [tailscale/tailscale#6975] opened 2023-01-16 06:35 UTC
### What is the issue?

i'm trying to have a k8s ts proxy as described in https://github.com/tailscale/tailscale/blob/main/docs/k8s/proxy.yaml expose the port it's forwarding to the wider internet using Funnels. when i try to do so, nothing happens:

```
/ # tailscale --socket=/tmp/tailscaled.sock status
100.84.178.254  ntfy-ts-proxy-0      ntfy-ts-proxy-0.redacted.ts.net linux   -
...other machines redacted

/ # tailscale --socket=/tmp/tailscaled.sock serve / proxy 80
/ # tailscale --socket=/tmp/tailscaled.sock serve status
No serve config
```

i can access the proxy from inside the tailnet, however.

### Steps to reproduce

spin up a tailscale proxy pod, run the above commands.

### OS

Linux

### OS version

whatever's packaged in ghcr.io/tailscale/tailscale. host is ubuntu 20.04

### Tailscale version

1.34.1

### Bug report

BUG-efbe9ffd78d5e8c5420e1cd3c636286514074c3816af1be9714c888d5c0fb201-20230116063310Z-203c87cc6b1b78a5

**Comment by asg0451** [comment] 2023-01-22 05:08
bump :pray:

**Comment by rodrigomencos** [comment] 2023-01-27 05:28
Im also having the same outcome you described while using the v1.34.1 as a sidecar. 

I also did try it on 1.36.0 and got the following:
```
tailscale --socket=/tmp/tailscaled.sock serve / proxy 80

sending serve config: updating config: writing ServeConfig to StateStore: Secret "tailscale-auth" is invalid: data[_serve/5c18]: Invalid value: "_serve/5c18": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
```

**Comment by james-martinez** [comment] 2023-02-28 17:19
Getting the same results on 

1.36.2
  tailscale commit: 0438c67e2517c78feeaf0d9f61ea2a6303dd875c
  go version: go1.19.4-tsdc0ce6324d

**Comment by rodrigomencos** [comment] 2023-03-03 07:28
Disabling secret storage does seem to work but I end up getting the following cert error:

**Comment by rodrigomencos** [comment] 2023-03-03 07:34
Disabling the secret storage made it work but I ended up getting a certificate error:

`Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours`

[The cert bug seems to be fixed on the current 1.37.x](https://github.com/tailscale/tailscale/issues/3974#issuecomment-1427163825) unstable builds but that means for the funnel to work, we would need to disable the secret storage anyways.

**Comment by DentonGentry** [comment] 2023-06-04 01:30
Probably related, add support for funnel in containerboot: https://github.com/tailscale/tailscale/issues/6468

**Comment by knyar** [comment] 2023-11-29 19:05
This does seem like a duplicate of #6468, so I am going to close it.

**Closed by knyar** 2023-11-29 19:05 UTC
Labels: OS-kubernetes, L1 Very few, P3 Can't get started, T5 Usability, bug, funnel

**Comment by irbekrm** [comment] 2023-11-29 19:27
If you use the Tailscale Kubernetes operator, you can expose a Kubernetes workload over Funnel using Ingress https://tailscale.com/kb/1236/kubernetes-operator/#exposing-a-service-to-the-public-internet-using-ingress-and-tailscale-funnel
