### ISSUE TITLE
Can't select specific mullvad exit node in a city

### ISSUE THREAD

**Issue by iamstonecutter** [tailscale/tailscale#12400] opened 2024-06-07 16:51 UTC
### What is the issue?

Previously I was able to connect to mullvad exit nodes with no restriction. Meaning, I could pick the specific server in my city or any city. Now I am forced to choose just the city name, and it seems to always pick the same server.

### Are there any recent changes that introduced the issue?

Not sure.

### OS

Linux, Android

### OS version

Debian 12 and GrapheneOS

### Tailscale version

1.66.4

### Other software

Pi-Hole on my tailnet

### Bug report

BUG-beda928a68057863f43c81f7e1191a165a773dc28779f34f6f886b62c1a0c80c-20240607164226Z-77407a0b5a61e02b

**Comment by timtailscale** [comment] 2024-07-03 17:20
Duplicate of #9913

**Closed by timtailscale** 2024-07-03 17:20 UTC
Labels: needs-triage, bug
