### ISSUE TITLE
FR: Allow creating share links using the api.

### ISSUE THREAD

**Issue by HyptexPvP** [tailscale/tailscale#5263] opened 2022-08-02 17:49 UTC
### What are you trying to do?

Im trying to let people use my exit node through a simple link, so i used the share feature but you can only use once, and can't create one using the API.

### How should we solve this?

Creating an API route for creating share links or allowing share links to last more time.

### What is the impact of not solving this?

Just giving out links that i generated, it gets annoying.

**Comment by DentonGentry** [comment] 2022-08-02 17:53
Duplicate of (subset of) https://github.com/tailscale/tailscale/issues/5154

**Closed by DentonGentry** 2022-08-02 17:53 UTC
Labels: needs-triage, fr
