### ISSUE TITLE
Android Quick Setting Tile Gone

### ISSUE THREAD

**Issue by kpcenti** [tailscale/tailscale#12082] opened 2024-05-10 04:32 UTC
### What is the issue?

The Quick Setting Tile suddenly disappeared. It is not in my Quick Settings Tiles or in the "Available Buttons" section. I cannot quickly toggle Tailscale on and off anymore.

### Steps to reproduce

N/A

### Are there any recent changes that introduced the issue?

N/A

### OS

Android

### OS version

Android 13

### Tailscale version

166.0te2a0fc0bc-g6bd50e8026d

### Bug report

BUG-1babe8d75264dac267d805d7f780b17070ea6867740f20136663c6172241a600-20240510043219Z-8d78c2dc19830d9d

**Comment by bradfitz** [comment] 2024-05-10 05:51
See https://github.com/tailscale/tailscale-android/commit/edb3f5b0c52ae5cb9cc2fa89310e395df5c08c6e ("android: simply viewing Quick Settings Tile turns on VPN")

**Comment by bradfitz** [comment] 2024-05-10 23:15
@s00se, yes. Because it's an all new rewrite of the app about to launch and it's better to launch it without a broken feature than with a broken feature. The broken state was blocking the release process (Play Store review, etc.) so it was better to get that process moving when it wasn't known how long the fix would take.

**Comment by ahsee** [comment] 2024-05-12 00:20
Bummer! While the state wasn't always correct, I could at least press the button once or twice and it would cycle and connect. Now I don't have any shortcut 😢

Looking forward to this being restored

**Comment by DarkMatterMatt** [comment] 2024-05-12 01:41
Hey all 👋 This feature was consistently working correctly on my S22 (Android 13). 

With the most recent update, the "workaround" has taken a feature that was working for some users and broken it completely. Respectfully, removing a feature is not a workaround.

Given that users can choose not to use the quick settings tile, perhaps a better temporary solution would be to add one-time popup (or a banner in settings) explaining that this is a known problem and linking to the relevant GitHub ticket.

Another option would be to disable it by default, but allow users to enable the setting after accepting a warning that due to device/OS limitations, the feature may not work correctly on all devices.

I would love to see any solution that restores this functionality 🙏

**Comment by bradfitz** [comment] 2024-05-12 02:46
It will be fixed and restored soon enough.

We're not going to add UI to confirm whether you want to enable buggy features.

**Comment by bradfitz** [comment] 2024-05-13 17:51
Duplicate of #11920

Fixed by https://github.com/tailscale/tailscale-android/commit/f684bf696d6e90982306eb419f8e6af8d0dea01a

**Closed by bradfitz** 2024-05-13 17:51 UTC
Labels: OS-android, needs-triage, bug
