### ISSUE TITLE
FR: Override DNS for mobile applications

### ISSUE THREAD

**Issue by northys** [tailscale/tailscale#9258] opened 2023-09-06 15:59 UTC
### What are you trying to do?

We have DNS set in tailscale, but we haven't set "Override local DNS" which would break some servers (cloud) or containers (kubernetes). We have custom DNS records in our company-internal.com domain which contains tailscale 100.x.x.x IPs. Some ISP providers are wise enough to filter out those DNS responses containing private CIDR ranges so for example in SSH client on my phone I have to access servers using IP not hostname.

Being able to enable "Override local DNS" in phone application would allow me accept DNS set in tailscale controlplane (e.g. 1.1.1.1) which doesn't behave like this.

### How should we solve this?

There could be option to set DNS manually (some input) or to override local DNS (toggle switch).

### Anything else?

`hostname` nor `hostname.tailCustomerIDc.ts.net` won't resolve for me on my phone while being connected to tailscale.

I have Google Pixel 7a without any special modifications.

**Comment by DentonGentry** [comment] 2023-09-08 00:46
Moving the "Override local DNS" setting to the local client isn't as likely as providing a way to get different DNS behavior per device, going to mark this as a duplicate of https://github.com/tailscale/tailscale/issues/6125

**Closed by DentonGentry** 2023-09-08 00:46 UTC
Labels: needs-triage, fr
