### ISSUE TITLE
Internet connection crash with android app and private dns function

### ISSUE THREAD

**Issue by cavedano8** [tailscale/tailscale#8410] opened 2023-06-22 10:10 UTC
### What is the issue?

Hi all,
if i setting custom private DNS on my android phone (pixel 3a) and i activate tailscale app, the internet connection crashes.
what i'm wrong in settings?
thanks

### OS

Android

### OS version

Android 13

### Tailscale version

1.42.0

**Comment by DentonGentry** [comment] 2023-06-22 16:56
You have PrivateDNS set to On, to require DNS-over-TLS? That is https://github.com/tailscale/tailscale/issues/915: we don't currently have a way to issue a valid certificate to the tiny DNS server running within the Tailscale app.

**Comment by cavedano8** [comment] 2023-06-23 07:42
Sorry @DentonGentry , I didn't pay attention to the other similar problems already open. Can it be closed then?

**Comment by DentonGentry** [comment] 2023-06-23 12:03
Duplicate of https://github.com/tailscale/tailscale/issues/915:

**Closed by DentonGentry** 2023-06-23 12:03 UTC
Labels: bug, needs-dedup
