### ISSUE TITLE
systray doesn't show profile flyout menu on KDE

### ISSUE THREAD

**Issue by tendstofortytwo** [tailscale/tailscale#14431] opened 2024-12-19 21:44 UTC
### What is the issue?

![image](https://github.com/user-attachments/assets/f797a4f6-4b76-4f12-8fd5-c60e305a031c)

I expect to see a flyout menu with all my profiles when I hover or click over the active profile. This doesn't happen -- hovering does nothing and clicking dismisses the dropdown.

### Steps to reproduce

1. Have multiple profiles.
2. Open the systray, hover or click on profile.

### OS

Linux

### OS version

Fedora 41 KDE

**Comment by willnorris** [comment] 2024-12-19 23:24
oddly, this seems to be caused by the `time.Sleep` added in #14353 to fix submenus in waybar.  I can't explain why a sleep would prevent KDE front rendering the menus, but removing it seems to fix it for me.

**Comment by willnorris** [comment] 2024-12-27 20:41
I think this was fixed in #14439

**Closed by willnorris** 2024-12-27 20:41 UTC
Labels: needs-triage, bug
