### ISSUE TITLE
Support multiple accounts

### ISSUE THREAD

**Issue by DatanoiseTV** [tailscale/tailscale#1129] opened 2021-01-14 11:15 UTC
I have mutitple accounts for Tailscale and would like to use them in one client. Is there already a way to do it?

**Comment by bradfitz** [comment] 2021-01-14 15:44
We'd eventually like to support both fast user switching between multiple accounts, as well as simulataenous multi-login. Neither are possible now.

**Comment by DentonGentry** [comment] 2021-02-08 18:11
Duplicate of https://github.com/tailscale/tailscale/issues/713

**Closed by DentonGentry** 2021-02-08 18:11 UTC
Labels: L3 Some users, P1 Nuisance, T5 Minor usability, enhancement
