### ISSUE TITLE
FR: Adding node ipv6 resolution to internal DNS

### ISSUE THREAD

**Issue by j4m3s-s** [tailscale/tailscale#6338] opened 2022-11-16 00:58 UTC
### What are you trying to do?

Make DNS server @100.100.100.100 return the ipv6 address of node when queried.

### How should we solve this?

By implementing AAAA resolution support on the internal DNS server.

### What is the impact of not solving this?

I'm currently hardcoding the IP addresses (since they don't change), but that's not very convenient. To discover them I ssh on the node and do `tailscale ip -6`.

### Anything else?

Thanks by advance! Keep up the good work.

**Comment by DentonGentry** [comment] 2022-12-03 10:02
Duplicate of https://github.com/tailscale/tailscale/issues/1152

**Closed by DentonGentry** 2022-12-03 10:02 UTC
Labels: needs-triage, fr
