### ISSUE TITLE
shared device does not show in network device list in UI

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2821] opened 2021-09-09 01:08 UTC
User shared the MacMini from his domain to another domain and shared RPi from another domain to his domain.

When he open the connected devices from his tray menu , he did not find the RPi device on MacMini which was shared from another domain to his domain, but he is able to connect to it.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3jc0h)

**Comment by darshinimashar** [comment] 2021-09-09 01:09
We are able to fix the issue once by deleting the Tailscale and key pair from MacMini and reinstalling it but the issue happened again.

**Comment by davexre** [comment] 2021-09-09 13:16
Providing a bit more detail - I'm the reporter. The MacMini in question is running MacOS 10.15.7 and Tailscale 1.12.3 (installed from the AppStore). 

I also have a MacBook Pro in my domain that does not show the symptom reported here - it can see the shared RPi system in the tray menu correctly. It's also running MacOS 10.15.7 and Tailscale 1.12.3, also installed from the AppStore. 

Please let me know if I can provide additional assistance.

**Comment by DentonGentry** [comment] 2023-02-12 19:22
This is a symptom of https://github.com/tailscale/tailscale/issues/1453
Closing as duplicate of https://github.com/tailscale/tailscale/issues/1453

**Closed by DentonGentry** 2023-02-12 19:22 UTC
Labels: L1 Very few, P2 Aggravating, T5 Usability
