### ISSUE TITLE
ssh: CentOS 7: no shell, permission denied

### ISSUE THREAD

**Issue by alexander-alvarez** [tailscale/tailscale#6802] opened 2022-12-20 05:43 UTC
### What is the issue?

Unable to ssh into a CentoOS 7 machine using `tailscale ssh <user>@<hostname>`

### Steps to reproduce

- Install tailscale on remote and client machine.
- run `tailscale up --ssh` on remote machine.
- Confirm remote machine is connected and has ssh badge in Tailscale Admin UI
- Confirm ACLs allow access to machine (should not be getting `Permission denied (tailscale)`
- execute `tailscale ssh <user>@<hostname>`

### OS

Linux

### OS version

CentOS 7

### Tailscale version

1.34.1

### Bug report

BUG-1377e8f707f8ea71c728625b19e909723881c2b396ece26e6c773bf138c192d4-20221220053927Z-c91556c107a79d89

**Comment by JayWStapleton** [comment] 2022-12-22 18:04
As an immediate workaround, it looks like `ssh user@100.x.y.z -t` will work. This has to do with how CentOS handles the default shell. We will be looking further into this.

**Comment by bradfitz** [comment] 2022-12-22 21:13
Does it work with the latest 1.35.89 (unstable) or so build?

**Comment by alexander-alvarez** [comment] 2022-12-27 03:10
Thanks all. @JayWStapleton I get the below when I do this
```
$ tailscale ssh <user>@100.<x.y.z>

<user>: no shell: Permission denied
Connection to <host>.tail<>.ts.net. closed.
```

@bradfitz would the latest unstable need to be installed on the host, client, or both?

**Comment by DentonGentry** [comment] 2022-12-27 03:21
It would need to be installed on the host system one is SSHing to. I think the issue Brad mention is a fix to PATH.

Tailscale SSH works with any SSH client, such as the OpenSSH `ssh` command.

**Comment by alexander-alvarez** [comment] 2023-01-02 19:07
Confirming when updating to unstable build `1.35.99` ssh still does not work.

@JayWStapleton I got my default shell from /etc/passwd and used it in the command you provided
```sh
ssh <user>@100.x.y.z -t bash
```
yields a connection timed out. SSH to this machine via it's internal LAN IP address works fine.


I generated the below after a recent attempt
```
BUG-1377e8f707f8ea71c728625b19e909723881c2b396ece26e6c773bf138c192d4-20230102190552Z-b45f7e64b60e8453
```

**Comment by alexander-alvarez** [comment] 2023-01-02 19:21
FWIW I'm also seeing tihs:
```
$ tailscale ping <host>
error looking up IP of "<host>": lookup <host> on 127.0.0.53:53: server misbehaving
```

**Comment by bradfitz** [comment] 2023-01-03 05:39
I can reproduce on a Centos 7 VM.

The issue is SELinux.

If I run `sudo setenforce 0` to disable SELinux, then it works. And then once I restore it with `sudo setenforce 1`, then it's back to broken as described above.

So closing this as a dup of #4908.

**Closed by bradfitz** 2023-01-03 05:39 UTC
Labels: OS-linux, L2 Few, P2 Aggravating, T5 Usability, bug, ssh
