### ISSUE TITLE
UDM Pro routing to tailscale not working

### ISSUE THREAD

**Issue by Maltahl** [tailscale/tailscale#3031] opened 2021-10-08 20:43 UTC
### What is the issue?

I have used this wonderful project https://github.com/SierraSoftworks/tailscale-udm to get Tailscale on my UDM Pro.

Tailscale Version: 1.10, 1.14.0 and 1.16.0

```
# info

Model:       UniFi Dream Machine PRO
Version:     1.10.0.3686
MAC Address: 24:5a:4c:XX:XX:XX
IP Address:  192.168.8.115
Hostname:    ubnt
Uptime:      4382 seconds

Status:      Connected (http://localhost:8080/inform)
# 
```

Things that work:

exit-node and route advertisements
tailscale ping command

Thing that dont work:

Regular ping commands and routing to any tailscale host that is started from the UDM Pro will fail.

it looks like a routes for tailscale hosts are not installed and the tailscale interface is not created for some reason.

```
tailscale ping ams1me1nl
pong from ams1me1nl (100.106.77.106) via 209.250.XXX.XXX:41641 in 29ms
```
this works but 

```
ping 100.106.77.106
PING 100.106.77.106 (100.106.77.106): 56 data bytes
^C
--- 100.106.77.106 ping statistics ---
10 packets transmitted, 0 packets received, 100% packet loss
```

does not.

### Steps to reproduce

Take a UDM Pro with version 1.10 software and install https://github.com/boostchicken/udm-utilities on it
then run through the guide from https://github.com/SierraSoftworks/tailscale-udm to install tailscale on the UDM Pro and run the command /mnt/data/tailscale/upgrade.sh 1.16.0 to upgrade to latest version.

use /mnt/data/tailscale/tailscale status to verify connectivity
use /mnt/data/tailscale/tailscale or create alias with: alias tailscale="/mnt/data/tailscale/tailscale" to execute commands.

### OS

- Linux
- Other

### OS version

UDM Pro 1.10.0.3686 - Linux ubnt 4.19.152-al-linux-v10.2.0-v1.10.0.3686-a2edd0c #1 SMP Fri Jul 9 04:40:55 UTC 2021 aarch64 GNU/Linux

### Tailscale version

1.16

### Bug report

BUG-ce5ba116b828cdea7ab8088c0a695b2f9e2f524f4e4e1d762a5b3de6c9068977-20211008204346Z-c5b3b02afa37e130

**Comment by Maltahl** [comment] 2021-10-08 22:14
> 
> 
> To set expectations: we do not provide packages for Unifi devices because Ubiquiti does not want third party software being installed on UDM. The next time there is a UDM software update it will remove all of the Tailscale configuration, for example.

That is understandable, thanks if you take a look at it.

**Comment by DentonGentry** [comment] 2021-11-03 23:35
Duplicate of https://github.com/tailscale/tailscale/issues/735

**Closed by DentonGentry** 2021-11-03 23:35 UTC
Labels: L2 Few, P2 Aggravating, T5 Usability, bug
