### ISSUE TITLE
FR: MagicDNS should selectively choose LAN vs Tailscale IPs

### ISSUE THREAD

**Issue by StraightfaceStudios** [tailscale/tailscale#6104] opened 2022-10-28 00:55 UTC
### What is the issue?

MagicDNS takes priority over interface search domains on LAN interfaces. 

Tailscale should use its control plane information and regularly in the background intelligently update a table of not just IPs that it can connect to, but also how it should connect to them.   In psuedo code:

```
if ( $TailNode.LAN.searchdomains.includes($Self.LAN.searchdomain) ) then { return Self.LAN.DNS($DNSname) } }
else {
   if ( $TailNode.isConnected() ) then { return $Tailnode.IP } 
   else { 
      if ( Tailnet.SubnetRoutes.includes($TailNode.LAN.Subnet) ) then { return tailnet.SubnetRoutes.splitDNS($DNSname) }
      else { return $Tailnode.IP }
   }
}
```

1) The first priority should be to connect directly to LAN devices.  
2) If the other device is not on the LAN then it should check with tailscale to see if that device is even online.  If it is, then connect directly. 
3) If it isn't then it should check and see if it's reachable via the splitDNS subnet router. 

2 & 3 could also theoretically be improved by not just using whether the device can connect directly or not.   It's better to connect through a subnet router directly than to connect directly through a Derp by a nearly 10x factor for bandwidth.  Just how Tailscale will establish a connection via Derp and then upgrade to Direct, it would be great if DNS also intelligently delivered the optimal IP address for two nodes to connect. 

### Steps to reproduce

1.  Connect a computer to Internal.Corp.com search domain NIC 192.168.1.0/24
2.  Type in http:\\ComputerName

Result:  ComputerName.Corp.ts.net is returned. 
Expected result: ComputerName.InternalCorp.com should be the priority. 

This is especially frustrating when Tailscale isn't even running on the target machine.  Not only is it not using the local search domain, but it's also overriding it for an interface that's down.   In an ideal world as a device migrates (say off of corporate wifi onto 5G) then it should automagically update DNS to use the tailscale interface. 

### OS

Linux, macOS, Windows, iOS, Android, Synology

### Tailscale version

1.32.2

**Comment by DentonGentry** [comment] 2023-06-03 21:50
I believe the problem being encountered is the same as https://github.com/tailscale/tailscale/issues/2697.

Duplicate of https://github.com/tailscale/tailscale/issues/2697

**Closed by DentonGentry** 2023-06-03 21:50 UTC
Labels: L2 Few, P2 Aggravating, T0 New feature, fr, pending
