### ISSUE TITLE
Cannot login via system proxy in Mac

### ISSUE THREAD

**Issue by Vxider** [tailscale/tailscale#5221] opened 2022-07-29 02:42 UTC
### What is the issue?

Because `https://log.tailscale.io` cannot be directly accessed in somewhere (China),  and the tailscale will not use the system proxy in mac, caused the tailscale cannot login.

This will also happen in Windows and Linux, setting env HTTPS_PROXY and ALL_PROXY doesn't fix.

```
logtail: upload: log upload of 347 bytes not-compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/fceeacd067ce3da60488709d82428aa010e3d5fe342bf4c99655db1b17ad38dc": dial tcp: lookup log.tailscale.io: i/o timeout
```

### OS

Linux, macOS, Windows

**Comment by DentonGentry** [comment] 2022-07-29 02:56
Duplicate of https://github.com/tailscale/tailscale/issues/4811

**Closed by DentonGentry** 2022-07-29 02:56 UTC
Labels: needs-triage, bug

**Comment by steom** [comment] 2022-08-31 18:51
1.30 don't fix. 1.22.2 works okay.
