### ISSUE TITLE
 Is the tailscale server open source and the web controller open source?

### ISSUE THREAD

**Issue by chenxudong2020** [tailscale/tailscale#3643] opened 2021-12-31 12:00 UTC
### What is the issue?

tailscale 服务端是否开源 还有网页控制器是否开源？
Is the tailscale server open source and the web controller open source?

**Comment by DentonGentry** [comment] 2021-12-31 15:14
Duplicate of https://github.com/tailscale/tailscale/issues/498

**Closed by DentonGentry** 2021-12-31 15:14 UTC
Labels: needs-triage, bug
