### ISSUE TITLE
Tailscale won't connect on reboot - macOS Ventura

### ISSUE THREAD

**Issue by mstgrv** [tailscale/tailscale#6706] opened 2022-12-12 01:35 UTC
Tailscale app on macOS does not work properly after rebooting

- Issue is occurring on 2 different macOS systems, both running Ventura 13.0.1, both running the standalone macOS version from pkgs.tailscale.com/stable/#macos
- Start on Login is enabled
- After rebooting, the app is visible in the menu bar, but it has a little exclamation mark on the icon showing an error
- Clicking the icon to display the app menu, there is a "Log in" option, but when I try clicking it, nothing happens
- Only way to force Tailscale to work is to quit and relaunch the app

**Comment by bradfitz** [comment] 2022-12-12 01:56
What version? Can you include a 'tailscale bugreport' when it's in the broken state?

**Comment by mstgrv** [comment] 2022-12-12 02:09
1.34 for both machines. Will 'tailscale bugreport' next time it happens

**Comment by DentonGentry** [comment] 2022-12-12 03:00
For the standalone macOS app which puts a Tailscale icon in the menubar, you hold option while clicking on it to get a Debug menu selection with a Bug report item.

**Comment by mstgrv** [comment] 2022-12-12 03:35
Thanks @DentonGentry - trying the Debug option from the menubar icon produces a different error:

<img width="229" alt="Screenshot 2022-12-12 at 14 35 00" src="https://user-images.githubusercontent.com/31542657/206955108-e0e43359-a291-4e11-bcdc-78c48cdf9c80.png">

**Comment by mihaip** [comment] 2022-12-13 00:05
Can you attempt to re-sen the bug report after you restart Tailscale and it's able to connect?

Alternatively, does searching Console.app for any messages about Tailscale show anything interesting?

**Comment by mstgrv** [comment] 2022-12-13 01:03
- looked at Console and there's no reports relating to Tailscale that I can find

- in System Settings -> VPN, I noticed there were 2 Tailscale Tunnel items listed, one of which had no icon. Not sure why that would have been the case, but I did used to use the Mac App Store version of Tailscale before I migrated to the Standalone version, so perhaps it was left over from that. I deleted both, and then the next time I started Tailscale it wanted to add the VPN tunnel again, but the issue is still there

- I also have the NextDNS client installed, and have been running it alongside Tailscale, so I tried disabling Start on Login for NextDNS just to eliminate that as an issue, but it seems to have no effect - still getting the issue on reboot

- I have noticed another way to get Tailscale working when the issue does occur - in addition to quitting & restarting Tailscale, you can also go to System Settings -> VPN and manually enabling Tailscale Tunnel. Tailscale then connects without needing to quit & restart it. I also just did a bug report after forcing Tailscale to connect in this way: BUG-3cead1714473a7388ee570ea02280e78565d092577efa9e668abfcb8308f9f15-20221213005749Z-e5eca903a81ae0eb

**Comment by mstgrv** [comment] 2022-12-15 06:19
I upgraded to Ventura 13.1 and Tailscale 1.34.1, and the issue appears not to be happening anymore on at least 1 of my Mac systems. Not sure whether that's related to the upgrades, or the other things I tried above (e.g. stopping using the NextDNS Mac client alongside Tailscale) but if it does pop up again I'll post back.

**Comment by monkbent** [comment] 2022-12-15 08:23
I am having the same issue. Unfortunately I did already upgrade to 13.1 and 1.34.1 (standalone). I also tried the Mac App Store version, but am having the same issue.

**Comment by eric** [comment] 2022-12-15 08:29
I'm having this problem with Ventura 13.1 and the Tailscale App Store version of 1.34.0. I'm unable to generate a bug report because it gives the same error that @mstgrv reported.

**Comment by monkbent** [comment] 2022-12-15 08:35
Update: I just rebooted and it worked, so must be some sort of race condition. I'm at about 80% of the time not work 20% work. Just submitted another bug report for comparison (unfortunately on remote computer so I wasn't able to copy the number).

**Comment by JamesCoons** [comment] 2022-12-16 14:28
I see this after updating to Ventura and have to enable VPN/Tailscale Tunnel Manually in the Settings every time I log in. Doing So fixes the problem until the next time I log in.

**Comment by h12o** [comment] 2022-12-19 15:57
Not sure if the cause is the same, the same thing happens when I switch to another user with macOS fast user switching and then switch back to the original user. It's okay to have tailscale turned off while switching to another user, but it's a bit annoying that tailscale is turned off when I switch back to the original user.

I got this error message after returning to the original user:

```
h12o@******** ~ % tailscale status
2022/12/20 00:22:31 failed to connect to local Tailscale service; is Tailscale running?
h12o@******** ~ % tailscale ip
2022/12/20 00:22:39 Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial tcp 127.0.0.1:58340: connect: connection refused
h12o@******** ~ % tailscale down
2022/12/20 00:24:08 error fetching current status: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial tcp 127.0.0.1:58340: connect: connection refused
h12o@******** ~ % 
```

(Annotation: `tailscale` command is below.

```sh:/usr/local/bin/tailscale
#!/bin/sh

exec /Applications/Tailscale.app/Contents/MacOS/Tailscale "${@}"
```

It simply launches `/Applications/Tailscale.app/Contents/MacOS/Tailscale` and passes arguments)

I have no choice but to quit tailscale and restart it every time I return to the original user.

- MacBook Pro 13-inch, M1, 2020
- macOS : Ventura 13.1（22C65）
- Tailscale : 1.34.1 (Mac App Store version)
  - tailscale commit: 328b49c4d69bd7fe1cbc8474ee36854dc52eb22c
  - other commit: 921b59a2ebc3eb4a703d93f504fc9e10fddf64f6
  - go version: go1.19.2-ts3fd24dee31

**Comment by cyckl** [comment] 2023-01-09 02:37
Have experienced the same issue here since getting the machine:
* Macbook Pro 14-inch, M1 Pro, A2442
* macOS 13.1 (22C65)
* Tailscale 1.34.1 (App Store)

Always occurs on boot-up, sometimes appears when waking from a long sleep as well. `Log in` option doesn't work. Tailscale.app must be restarted for it to connect successfully.

Bug report filed after restarting the client: `BUG-b277e54dba98cdbdb07ecd825de0180aef76d906dc639ed34ce6614d31e5f01c-20230109023127Z-0a454b53eaeacac6`

I could not file a bug report while it failed to connect, had to restart client as well.

**Comment by mattronome52** [comment] 2023-01-12 02:58
Update MacBook M1 Pro 14 inch 2021 to Ventura 13.1 and Tailscale didn't connect until I re-enabled it in Settings > VPN.

Filed: BUG-105c12c25f19d17eb11137ebe856d3cf81fc03c771da48093b30a7b0a677374a-20230112025558Z-5221f85b29c8a9dd

**Comment by WesleyMConner** [comment] 2023-01-13 13:17
> * I have noticed another way to get Tailscale working when the issue does occur ... go to System Settings -> VPN and manually enabling Tailscale Tunnel. Tailscale then connects without needing to quit & restart it. ...

This solution worked for me. Thanks!

**Comment by simoncoulton** [comment] 2023-01-16 23:24
I'm having this issue as well on Monterey 12.2.1, Tailscale 1.34.2. It seems to be "random", usually after a reboot and when it hasn't expired yet.

Happy to provide any more debugging information that I can.

**Comment by rscorer** [comment] 2023-01-25 12:14
i am logged in but cannot connect to tailscale.

BUG-1c4abd35fb4cac49c06c07a96ce20f46ba01624485f9f8eb66326ad6d05f729c-20230125120836Z-cd51066a826ea30a

Version 1.36.0 (macsys

MacOS 13.2 (22D49) (Intel)

**Comment by rscorer** [comment] 2023-01-25 13:40
I uninstalled the Tailscale App and installed the CLI version. Still can't login to Tailscale:


```
$ tailscale bugreport
BUG-d67b5b92125dd5484aa310d49f80de1903272abdb5148fff976de37d5c726f7c-20230125133759Z-302f47d559f7ab6a
```

`tailscale up --force-reauth --reset` does nothing.

`tailscale web` shows the web UI, with a login button, which does nothing when clicked.

**Comment by atjbramley** [comment] 2023-01-26 18:39
In case this is useful, here's a video of this in action.

I _think_ that this happens when tailscale is up before I've got an internet connection established.  If I have an internet established before tailscale tries to launch, then it logs in successfully.

https://user-images.githubusercontent.com/71517198/214917359-7dcfcfe7-7a50-4627-b7b5-47eb2a201841.mov

**Comment by mihaip** [comment] 2023-01-31 02:30
There are a number of reports here, so there may be multiple (separate issues). The one I'll focus on is @atjbramley's observation, where if the machine does not have network connectivity right at startup Tailscale does not come up correctly (even after the network connection is available).

The behavior that I see is that if the network is not available, macOS will not start Tailscale's network extension, which is where the bulk of Tailscale's logic lives. That's a longstanding limitation, though I can't find a citation for it (@crawshaw may know).

Perhaps with Ventura Apple changed the sequencing during boot, and login items (like Tailscale) are started sooner, before the network interface is fully brought up (Ventura had a lot of other login item changes).

There is a longstanding TODO about handling this better in the macOS client (https://github.com/tailscale/corp/blob/7e34c4052177ef4e694884e28bb69c2a6bf59c62/xcode/IPN/Tunnel/BackendClient.swift#L281-L288), it looks like it's time to handle it (by listening for offline -> online transitions and trying again to start the network extension).

**Comment by rscorer** [comment] 2023-01-31 21:58
I just upgraded to Tailscale 1.36.0 via the App Store on Ventura, and now it will not log in .

Bug Report ID: BUG-8b5da49ef7daf0fe0fabcf988be5b959bdb1d05150de73a7d97b165d6fb7ecdf-20230131215638Z-4fd9640562908276

It was working perfectly well with Tailscale 1.34.2, the only change has been the upgrade and subsequent relaunch of Tailscale.

**Comment by rscorer** [comment] 2023-01-31 22:02
> There are a number of reports here, so there may be multiple (separate) issues. The one I'll focus on is @atjbramley's observation, where if the machine does not have network connectivity right at startup Tailscale does not come up correctly (even after the network connection is available).
> 
> The behavior that I see is that if the network is not available, macOS will not start Tailscale's network extension, which is where the bulk of Tailscale's logic lives. That's a longstanding limitation, though I can't find a citation for it (@crawshaw may know).
> 
> Perhaps with Ventura Apple changed the sequencing during boot, and login items (like Tailscale) are started sooner, before the network interface is fully brought up (Ventura had a lot of other login item changes).
> 
> There is a longstanding TODO about handling this better in the macOS client (https://github.com/tailscale/corp/blob/7e34c4052177ef4e694884e28bb69c2a6bf59c62/xcode/IPN/Tunnel/BackendClient.swift#L281-L288), it looks like it's time to handle it (by listening for offline -> online transitions and trying again to start the network extension).

I had this happen to me earlier today on Ventura, didn't get a bug report sorry.

I was connected using Tailscale 1.34.2 from App Store, and my router upgraded itself which disconnected the internet.

Since Tasilscale was logged in and active, Firefox could not load any pages. I switched off Tailscale and the pages immediately loaded. However, when I switched Tailscale back on - the pages were blocked again, nothing would load.

I had to quite and restart Tailscale, at which time everything continued working.

So this is not at boot time, this was during an already working system when the internet was disconnected.

Hope that helps, sorry I didn't trap the bug report...  I would try and recreate this, but I've since been upgraded to 1.36.0 which simply doesn't work at all in Ventura :(

**Comment by mihaip** [comment] 2023-01-31 22:53
@rscorer you appear to be experiencing a different issue (the Tailscale extension appears to be able to start up, otherwise the bug report generation would not work). What I see in your logs is that the the extension is not able to contact our centralized coordination server:

```
control: TryLogin: fetch control key: Get "https://controlplane.tailscale.com/key?v=56": context canceled
```

Could you file a new GitHub issue and also include the output of `/Applications/Tailscale.app/Contents/MacOS/Tailscale debug ts2021 --verbose`?

**Comment by rscorer** [comment] 2023-01-31 23:14
> @rscorer you appear to be experiencing a different issue (the Tailscale extension appears to be able to start up, otherwise the bug report generation would not work). What I see in your logs is that the the extension is not able to contact our centralized coordination server:
> 
> ```
> control: TryLogin: fetch control key: Get "https://controlplane.tailscale.com/key?v=56": context canceled
> ```
> 
> Could you file a new GitHub issue and also include the output of `/Applications/Tailscale.app/Contents/MacOS/Tailscale debug ts2021 --verbose`?

https://github.com/tailscale/tailscale/issues/7135

**Comment by mihaip** [comment] 2023-02-01 17:02
@atjbramley and others that are experiencing this: we have an unstable build (version 1.37.32) with a possible fix that's available on TestFlight if you'd like to try it: https://tailscale.com/kb/1083/install-unstable/. Tailscale will now monitor the network connection, and attempt to connect when it actually comes up.

If it works well we may consider cherrypicking it into a patch release for 1.36, instead of waiting for the 1.38 cycle (which is a few weeks away).

**Comment by zigg** [comment] 2023-02-01 18:38
@mihaip I can't shut down right now to test the problem that led me here (frequent client stops), but here are a few cases that are working great with the TestFlight version that I believe were not in the shipping version:

- turn off WiFi, quit and restart Tailscale (⚠️ appears), turn on WiFi, Tailscale connects when WiFi is settled
- in Settings > VPN, flip Tailscale off and on
- in Settings > VPN, flip Tailscale off, and restore it using "Log in…" from the Tailscale menu

I think this looks great so far, thanks!

When disabling WiFi with an established Tailscale connection, Tailscale does not drop—this seems like reasonable intended behavior, but just wanted to check.

**Comment by zigg** [comment] 2023-02-01 19:40
@mihaip Rebooted just a moment ago, watched the sequence of WiFi and Tailscale, and that's working great too. ✔️

**Comment by brainsik** [comment] 2023-02-06 00:25
@mihaip The TestFlight version — 1.37.32 (273.32.57) — mostly fixes this for me! 🎉

There is one cosmetic issue where my avatar doesn't load:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/162998/216855173-353e5527-8d6f-452c-bc4d-ef9ba8f1b5b4.png">

Quitting and restarting causes the avatar to load properly:

<img width="272" alt="image" src="https://user-images.githubusercontent.com/162998/216854971-845a7df5-5351-42ea-847c-bd447390408f.png">

I'm guessing this is due to the same issue where the network isn't available when it tries to load the avatar, so uses a placeholder image. It would be great if this also got retried so the account looks correct. Seeing a different image makes it look like it's using a different account than expected.

Thanks for your help!

**Comment by mattieb** [comment] 2023-02-07 00:21
@brainsik Strange—I have an empty circle until Tailscale connects on both Google and GitHub logins, at which point it fills in the correct avatar.

**Comment by brainsik** [comment] 2023-02-07 19:24
@mattieb Hmm. Just rebooted again and this time it loaded the avatar once the network was available. Interestingly, before it loaded it was an empty circle with a dashed border, not the solid circle with a "J" like above. Maybe it was an issue on the GitHub side?

**Comment by atjbramley** [comment] 2023-02-08 13:23
Can confirm that 1.37.74 (missed the slightly earlier version mentioned above) behaves as I'd expect:

- Doesn't manage to connect when macOS loads and no internet connection is present
- Connects as soon as an internet connection becomes available, without now needing to restart the application

**Comment by mihaip** [comment] 2023-02-17 00:00
Fix for this was picked up in the 1.36.1 stable release.

**Closed by mihaip** 2023-02-17 00:00 UTC
Labels: OS-macos, L2 Few, P3 Can't get started, T5 Usability

**Comment by 9Somboon** [comment] 2023-10-28 04:21
same issue

**Comment by DentonGentry** [comment] 2023-10-28 04:57
@9Somboon This issue was fixed months ago. Please open a new bug, describe the problem, and include a bugreport: hold option while clicking on the Tailscale icon in the menubar, then choose Debug > bugreport.
