### ISSUE TITLE
[iOS] Tailscale doesn't fully disconnect system VPN, causing battery drain 

### ISSUE THREAD

**Issue by dvcrn** [tailscale/tailscale#7386] opened 2023-02-27 01:13 UTC
### What is the issue?

I'm not sure if this is something new, or I just noticed it recently because of shortcuts support (in https://github.com/tailscale/tailscale/issues/2504)

Even when tailscale is disconnected, my battery on my iPhone drained extremely fast. I wasnt able to make it through a full workday (8 hours) without charging. Of course, there are other factors at play and background activity reported tailscale at only 1%, but this was still odd.

![image](https://user-images.githubusercontent.com/688326/221449712-cc59967d-9fe7-4e31-822b-1f3763e5000c.png)

The graph also shows that something has been constantly causing activity, but no clear indication what that was.

Noticed that even after tailscale is disconnected (and the VPN symbol from the menu disappears), the system setting still has the VPN through tailscale marked as "connected" to 127.0.0.1

![IMG_9375](https://user-images.githubusercontent.com/688326/221449911-23718ded-0413-41cd-b46d-ca7f68eb1737.PNG)

Changing this to off manually stopped the battery drain and my phone is back to lasting through the day. I'm guessing that even if this is switched to 'on' it shouldn't actually drain battery because Tailscale doesn't have the VPN active, but it still had an impact on my battery life. 

### OS

iOS

### Tailscale version

1.37.101

**Comment by mayakacz** [comment] 2023-03-08 22:38
Duplicate of https://github.com/tailscale/tailscale/issues/3363. See https://github.com/tailscale/tailscale/issues/3363#issuecomment-1149022384 for how you can gather data to help us debug this.

**Closed by mayakacz** 2023-03-08 22:38 UTC
Labels: needs-triage, bug
