### ISSUE TITLE
Tailscale seemingly preventing an Internet connection on reboot

### ISSUE THREAD

**Issue by ericlagergren** [tailscale/tailscale#6788] opened 2022-12-19 20:25 UTC
### What is the issue?

I've had Tailscale installed on my MacBook Air (M1, 2020) for a few years now. Recently, whenever I power it on I've been able to connect to Wi-Fi, but macOS reports that I don't have an Internet connection. After exiting Tailscale, macOS reports that I have an Internet connection. (And macOS is correct: I can't connect to the Internet until I close Tailscale). Reopening Tailscale afterward doesn't cause any problems.

This this has happened with macOS Ventura (all stable releases). The only Tailscale version that I've confirmed this with is 1.34.0, but I use Tailscale through the App Store so I'm almost always on the latest release. I never used to power off my MacBooks, so I don't know if this affects older macOS versions.

I did notice something similar on macOS Monterey, however, where I'd occasionally lose my Internet connection (after sleeping I think?) and the only way to fix it was by closing Tailscale. If I remember correctly, I noticed something weird about the system interfaces or routes. Not sure why I didn't file a bug report then.

I know it's not a lot to go on, sorry!

### OS

macOS

### OS version

13.1

### Tailscale version

1.34.0

### Bug report

BUG-577fadab42b9b2b8b830873715f3ca7d62784ea3eb9521a9f6dd65fcc184ebf7-20221219201859Z-0d1c1d8c8ef33336

**Comment by ericlagergren** [comment] 2022-12-20 05:23
I think there might be a race condition or something because it doesn't occur every single time.

**Comment by DentonGentry** [comment] 2023-02-11 17:01
Duplicate of https://github.com/tailscale/tailscale/issues/6706, which is fixed in release 1.36.1.

**Closed by DentonGentry** 2023-02-11 17:01 UTC
Labels: needs-triage, bug
