### ISSUE TITLE
FR: dns entry (alias to one of the machine/service)

### ISSUE THREAD

**Issue by a1exus** [tailscale/tailscale#11999] opened 2024-05-03 19:50 UTC
### What are you trying to do?

my host is running few different webapps and in theory each of them _must_ support "path", otherwise I won't be able to use single hostname to serve different webapps, so ideally if there was a way to add an alias (like cname) where i can map it to that machine

### How should we solve this?

that'd be very helpful as i can have fqdns such as wordpress.tailnet.ts.net vs tailnet.ts.net/wordpress as again some of the apps may not have support or claims to have support yet i find out different and there is a lot of bug reports to file.

### What is the impact of not solving this?

having a need to support path vs using cname like alias

### Anything else?

thank you in advance!

**Comment by agottardo** [comment] 2024-05-04 17:59
Duplicate of https://github.com/tailscale/tailscale/issues/1543

Thank you for filing this.

**Closed by agottardo** 2024-05-04 17:59 UTC
Labels: needs-triage, fr
