### ISSUE TITLE
Error creating Wintun interface: The device is not ready for use.

### ISSUE THREAD

**Issue by fixtatedunderbedsheet** [tailscale/tailscale#2959] opened 2021-09-29 07:16 UTC
Just tried to do a fresh install of Tailscale on Windows 7, and even after installing the advised hotfix mentioned on the Wiki page, the taskbar status report that I need to restart Tailscale service (which to no avail) and then a error window pop up with the following message: 

![image](https://user-images.githubusercontent.com/91590736/135220629-84ab1bae-3b44-4a9f-a85f-5836d81a8f8e.png)
logid: a05274255b6b39f2e8e4ba5914bb809185efee74011ddd98130fb6b24b7d24f0

An excerpt in the install log (which may help explain the problem I'm experiencing) is as follow: 

"Installing wintun driver...
[Wintun] WintunCreateAdapter: Creating adapter
[Wintun] SelectDriver: Using existing driver 0.13
[Wintun] EnsureDeviceObject: Failed to determine adapter ROOT\NET\0007 device object: The device is not ready for use. (Code 0x000010DF)
[Wintun] WintunCreateAdapter: Device object file did not appear: The device is not ready for use. (Code 0x000010DF)
installWintunDriver: CreateAdapter: The device is not ready for use."

Any good idea on how to troubleshoot this one?

**Comment by fixtatedunderbedsheet** [comment] 2021-09-29 07:55
Problem solved - apparently I should first search for an existing solution; and that solution involve installing KB4474419 so that code signed with SHA-2 signature will behave properly in Windows 7 which might have something to do with the Wintun code signature. 

The solution I mentioned is down below this link:
https://github.com/tailscale/tailscale/issues/1976#issuecomment-859757070

I'm leaving this issue open until the devs decide it no longer needs to be.

**Comment by DentonGentry** [comment] 2021-10-01 03:21
Duplicate of https://github.com/tailscale/tailscale/issues/1976

**Closed by DentonGentry** 2021-10-01 03:21 UTC
Labels: needs-triage
