### ISSUE TITLE
macOS app stays logged out after upgrade on App Store

### ISSUE THREAD

**Issue by damomurf** [tailscale/tailscale#1403] opened 2021-02-26 04:33 UTC
I raised this issue previously on the forum but then got distracted and didn't follow through:
https://forum.tailscale.com/t/macos-app-store-upgrade/188/4

I sent the following to support over a couple of emails and Brad requested that I raise a ticket here.

Tailscale has updated itself via the Mac App Store to v1.4.5 and the app was then sitting in my Menu Bar logged out. When I click on Log in, nothing would seem to happen. In the past this has required a full reboot of the machine to get it to connect again (which seems to happen fine automatically after the reboot).

The machine in question is Tailscale IP 100.111.179.81 and according to the Tailscale Machines Web UI, the last time it was seen was 7:15AM ACDT which is probably about when the upgrade occurred automatically.

Checking /var/log/install.log, the installation seemed to be "complete" at 2021-02-26 07:15:51+10:30.

Doing some more debugging on my side with this, it seems to be a DNS issue:
```
default 10:36:51.684820+1030 IPNExtension control: authRoutine: state:authenticating; wantLoggedIn=true
default 10:36:51.685110+1030 IPNExtension control: direct.TryLogin(token=false, flags=2)
default 10:36:51.685184+1030 IPNExtension control: LoginInteractive -> regen=true
default 10:36:51.685255+1030 IPNExtension control: doLogin(regen=true, hasUrl=false)
default 10:36:59.762377+1030 IPNExtension logtail: upload: log upload of 14100 bytes not-compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/b5a051dacd3cec7a9113d39c1e8021b364b494eed7fedc0ee8b6871dea236217": dial tcp: i/o timeout
default 10:36:59.762443+1030 IPNExtension logtail: backoff: 17546 msec
default 10:37:01.685576+1030 IPNExtension Received error: TryLogin: fetch control key: Get "https://login.tailscale.com/key": failed to resolve "login.tailscale.com": i/o timeout
default 10:37:01.685626+1030 IPNExtension control: authRoutine: backoff: 43218 msec
default 10:37:44.905693+1030 IPNExtension control: authRoutine: state:authenticating; wantLoggedIn=true
default 10:37:44.906157+1030 IPNExtension control: direct.TryLogin(token=false, flags=2)
default 10:37:44.906222+1030 IPNExtension control: LoginInteractive -> regen=true
default 10:37:44.906286+1030 IPNExtension control: doLogin(regen=true, hasUrl=false)
default 10:37:47.311831+1030 IPNExtension logtail: upload: log upload of 14100 bytes not-compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/b5a051dacd3cec7a9113d39c1e8021b364b494eed7fedc0ee8b6871dea236217": dial tcp: i/o timeout
default 10:37:47.311898+1030 IPNExtension logtail: backoff: 40353 msec
default 10:37:54.907430+1030 IPNExtension Received error: TryLogin: fetch control key: Get "https://login.tailscale.com/key": failed to resolve "login.tailscale.com": i/o timeout
default 10:37:54.907569+1030 IPNExtension control: authRoutine: backoff: 22177 msec
default 10:38:17.090162+1030 IPNExtension control: authRoutine: state:authenticating; wantLoggedIn=true
default 10:38:17.090272+1030 IPNExtension control: direct.TryLogin(token=false, flags=2)
default 10:38:17.090332+1030 IPNExtension control: LoginInteractive -> regen=true
default 10:38:17.090404+1030 IPNExtension control: doLogin(regen=true, hasUrl=false)
default 10:38:27.091011+1030 IPNExtension Received error: TryLogin: fetch control key: Get "https://login.tailscale.com/key": failed to resolve "login.tailscale.com": i/o timeout
default 10:38:27.091114+1030 IPNExtension control: authRoutine: backoff: 18009 msec
```

It's somewhat strange because I could happily resolve login.tailscale.com absolutely fine in a Terminal on the same machine. 

This machine runs a Corporate VPN client also, but I tried disconnecting that and the same thing occurs, with more logs like above.

The problem could be a result of some problems interacting with Corporate DNS that seems to take over the machine completely as a result of the Corp VPN. To my knowledge, though: there was no issue with that at the time and it normally doesn't present an issue (except with Magic DNS, but that's a different story).

Once the Corp VPN was disabled, I discovered I had a different upstream DNS issue causing resolution to fail. Once I fixed that, I still needed to restart Tailscale, but everything logged in fine automatically after that.

Maybe if there's one recommendation it's to show a friendly message if the login fails rather than... just doing nothing.

Thanks!

**Comment by bradfitz** [comment] 2021-02-26 05:17
@damomurf, thanks again!

@crawshaw, the interesting logs start at:

`89631ba4f74ea975698dbcdd11f5c70b433d8c5c39f00f25e9b72518558d6b0f`
```
2021-02-26 07:15:50.618872 +1030 +1030: frontend Peek got EOF; shutting down
2021-02-26 09:54:32.604016 +1030 +1030: initSameUserProofToken: done=true
2021-02-26 09:54:32.604082 +1030 +1030: setupLogs: logging configured: loaded
2021-02-26 09:54:32.604158 +1030 +1030: setupControlURL:
2021-02-26 09:54:32.604207 +1030 +1030: goSetupControlURL: https://login.tailscale.com (builtin)
...
2021-02-26 09:54:38.690011 +1030 +1030: starting forever-blocked frontend Peek for shared fate shutdown
2021-02-26 09:54:42.602709 +1030 +1030: ^NaNM up=1614295472+10 Sys=72.6M HeapAlloc=1.1M HeapSys=62.7M HeapIdle=60.3M HeapInuse=2.4M HeapReleased=60.3M StackInuse=1.3M StackSys=1.3M MSpanInuse=0.1M MSpanSys=0.1M BuckHashSys=1.4M GCSys=4.4M OtherSys=2.7M NumGC=3 goroutines=97
2021-02-26 09:54:42.646314 +1030 +1030: control: TryLogin: fetch control key: Get "https://login.tailscale.com/key": failed to resolve "login.tailscale.com": i/o timeout
```

More reasons to build more robust fallback mechanisms to resolve our own DNS names at startup.

**Comment by bradfitz** [comment] 2021-02-26 16:45
Filed #1405 for the DNS component of this, which might be the main component. But it also seems like there's a macOS-specific thing we could be doing here to listen to the App Store notification that we're being restarted for an update and perhaps we could shut down better/faster/cleaner and restore the DNS before we exit?

/cc @nickoneill

**Comment by apenwarr** [comment] 2021-06-08 06:02
@bradfitz Looking at your last comment above, I'm not sure that makes sense. macOS should always be clearing out all our network stuff as soon as the NetworkExtension goes away, so we don't need to clean it up ourselves.

It looks to me like if DNS isn't working at startup for this person, this is almost certainly caused by something outside Tailscale.

**Comment by DentonGentry** [comment] 2023-02-12 12:50
I think most of the issue tracked here was from DNS misconfiguration, which was fixed in https://github.com/tailscale/tailscale/issues/1405. I'm not sure anything is left in this bug to be addressed.

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Closed** 2023-06-02 23:02 UTC
Labels: OS-macos, L2 Few, P1 Nuisance, T5 Usability
