### ISSUE TITLE
macOS: get a DMG version working for distribution outside App Store (required for beta testing)

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#718] opened 2020-08-27 13:38 UTC
History, as best I've been able to figure it: Apple introduced the NetworkExtension as an _App Extension_ for iOS to make it possible to run background networking code. This was then ported to macOS in the name of compatibility, so the exact same appex could run in the Mac Store sandbox. Since then, there appears to have been a slight shift in Apple's thinking: compatibility is done by Mac Catalyst (think: Android-on-ChromeOS), and for the future of macOS-specific apps Apple have introduced a _System Extension_ variant of the NetworkExtension in macOS 10.15 Catalina.

For the NetworkExtension in particular, the System Extension is very similar to the App Extension. The same APIs for invoking the packet tunnel work, so code can be shared. However there are several notable differences that make sysex interesting:

1. A System Extension can run when the user is not logged in. (I haven't tested this, but it may get us headless mac mode for Tailscale.)
2. It is accepted by Apple that you can do your own IPC. See IPCConnection.swift in the [FilteringNetworkTraffic example](https://developer.apple.com/documentation/networkextension/filtering_network_traffic). This means we could use our common protocol from Linux/Windows for talking between the frontend and the sysex.
3. With care, a NetworkExtension sysex can be signed by a Developer ID, meaning it can be deployed outside the (see the comment by eskimo in [this thread](https://developer.apple.com/forums/thread/125508?page=3) that mentions `app-proxy-provider-systemextension`, I've tested this, it works.) This is not possible with an appex.
4. There is formal "replacement" logic in the sysex API that may make store upgrades smoother. (Untested hypothesis.)

The significant downside: this only works on 10.15. New macOS versions roll out a lot slower than iOS, so far only [~55%](https://gs.statcounter.com/macos-version-market-share/desktop/worldwide) of macs run Catalina. So we cannot switch to it yet. However, it is worth maintaining a minimal sysex variant of our app today for the sole reason of letting users beta test our code outside the mac store. Eventually, I believe we should migrate completely to sysex on macOS.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2hx1t)

**Comment by apenwarr** [comment] 2020-10-16 19:48
I played with this a bit a couple of weeks ago. My main discoveries were:

* the SystemExtension UI is *very* fiddly, requiring about 4 levels of confirmation (in addition to dragging the app into the /Applications folder first, or it won't work, unlike every other macOS app). This will confuse users for sure.

* if you have more than one app installed with the same SystemExtension name, macOS gets totally confused, as it does with NetworkExtensions. I got myself into a situation a couple of times where rebooting seemed to be the only fix. (It's slightly better than NetworkExtensions because only apps in /Applications can have a SystemExtension at all, which makes the registration/unregistration process easier to understand.)

* SystemExtensions run as root, not as the user, so they don't have access to the user's keychains. We can fudge this into working by adopting the same mechanism we use on Windows (where the backend also runs as a system user), where the frontend keeps a "session key" that indexes into the backend's private storage, which contains the real keys. This is arguably an improvement over our current design: it allows "server mode" (ie. Tailscale works before a user logs in) and it could work exactly like Windows, ie. one less variation in the state machine.

* On the other hand, SystemExtensions cannot be distributed in the app store (as far as I know), and the app store app would not be able to store its keys in the system keychain. This creates major differences between the NetworkExtension (app store) version and the SystemExtension (separate .dmg) version.

Another variation on the same theme would be to simply distribute tailscaled (the command line daemon) and a launchd profile for it, and install using a .pkg script. This would work on pre-macOS-10.15 systems, but would be even more different from the NetworkExtension app, because we'd have to use the darwin unix-like APIs rather than the NetworkExtension APIs. Support for that was contributed by open source users, but I don't think the network namespace stuff is implemented there (so there can be routing loops, at the moment). Also, installing the launchd profile requires root access, so we'd have to tell people to run a particular command, or make a GUI that captures your password and sends it to sudo, both of which are pretty gross.

**Comment by apenwarr** [comment] 2020-10-16 19:52
A final option, which is pretty tempting, is to collect the macOS system ids from a small, hand-curated set of beta testers (Apple limits us to a max of 100 registered macOS devices, sigh, and lets us reset it only once a year). Then we could distribute the *actual* dmg that really goes in the app store.

The downside of *that* option is we run into the "multiple installed apps using the same NetworkExtension name" problem. This will definitely happen, because users will surely install the app store app and the beta app at the same time. Or, you could have two or more betas downloaded onto the filesystem at the same time.

I don't know if we've tried this, but we might be able to avoid these conflicts by giving the NetworkExtension a different name (eg. including the version number) every time we make a build.

**Comment by apenwarr** [comment] 2020-10-16 19:55
Oh, yet another option we considered is to upload a different variation of the app to the app store (call it "Tailscale leading edge" or something, and hopefully make it unsearchable so people can only find it if they really know they're looking for the beta. That would allow an unlimited number of testers, but we'd have to go through app store review every time. On the up side, we'd get automatic updates pushed by Apple.

As a possible side benefit, people could install both versions at once and (I think) be able to connect to personal and corporate tailscale networks at the same time.

**Comment by hartshorne** [comment] 2020-10-25 20:21
We are using a Raspberry Pi as a relay node to access our office Macs at the moment. Happy to help test any of the above to help get access to the machines directly.

**Comment by fitzn** [comment] 2020-12-17 20:56
Just adding our use case:
We want to automatically install Tailscale on our new employee laptops through our MDM (in this case, Fleetsmith). Fleetsmith has an app catalog for official apps, but also allows installing custom apps from a .pkg file. Either route would work for us.

**Comment by DentonGentry** [comment] 2021-02-08 15:51
Mentioning for completeness: https://github.com/tailscale/tailscale/issues/177

I believe https://github.com/tailscale/tailscale/issues/505 discusses this same issue, next time that bug is scrubbed I'd expect to close it.

**Comment by thehilll** [comment] 2021-02-08 16:58
I had been following 505, but just to add some issues here...

Our use case is really to be able to deploy outside of the App store (so for example the testing builds or leading edge app would not work for us).

We push the App store version via our MDM now, but the issue is getting updates installed.  These are supposed to happen automatically, but in practice they never seem to be.  Researching this for other apps it seems to be an extremely common problem, so I'm sure it is an Apple issue and not you.

Currently we are having people manually install from the app store because those installs do get updated (it's just the MDM initiated ones that don't).  That isn't ideal b/c it adds steps to the new-user setup process (and in some cases requires them to set up an Apple ID if they don't already have one).

The MDM-initiated installs will not update, and they won't even allow manual updates (they show "Get" as the option if you go directly to the Tailscale page).

So our use case for a non-app store version isn't so much for testing (though that would be good to), it is to make roll out and updates more automated.

Thanks.

**Comment by bradfitz** [comment] 2021-02-18 22:02
Somewhat tangential, but instructions are now available for running `tailscaled` on macOS: https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS

**Comment by DentonGentry** [comment] 2021-05-20 22:40
Substantial progress has been made on a System Extension based MacOS build, suitable for distribution outside of the app store. I expect to begin using it for 1.9.x (unstable) releases in the next few weeks.

The main remaining item is that we want to get some kind of update mechanism, likely Sparkle, working before using it more widely. Otherwise we'd risk stranding users on an aging binary with nothing to nudge an upgrade.

**Comment by rickybright** [comment] 2021-06-08 22:59
TestFlight for Mac announced

**Comment by DentonGentry** [comment] 2021-06-08 23:04
I mean, of course. We were just finishing Sparkle support, so of course.

**Comment by rickybright** [comment] 2021-06-09 02:44
To be fair. I don’t think they actually specified that TestFlight for Mac
would be out this summer.

**Comment by mayakacz** [comment] 2021-10-19 17:40
It seems like TestFlight on macOS will be supported in macOS 12.0.

**Comment by thehilll** [comment] 2021-10-19 23:04
I'm not certain about this, but wouldn't TestFlight be for App store apps?  Our need is to get something that isn't in the app store b/c Apple's MDM-triggered App store installs are hopeless at getting upgraded.

Manually installed app store apps work fine w/updates, but our users where we pushed the install via MDM never get updated (this seems to be a generic issue with VPP installs, nothing that is Tailscale's fault).

If we have something out of the app store we can push it with our standard software installs.  If it self-updates via Sparkle that's great, or we could push updates.

Thanks a lot.

**Comment by DentonGentry** [comment] 2022-05-07 17:37
The main holdup for this has been Sparkle autoupdate, as we didn't want to have a binary out there which would never update itself. We think Sparkle is working now. If it holds up throughout the 1.25.x development cycle, we'll expect this to be released with 126.0.

**Comment by DentonGentry** [comment] 2022-05-19 23:04
The DMG version outside of the App Store is working now and available for download at https://pkgs.tailscale.com/unstable/#macos

It is currently released on the unstable track, which we use for test builds between releases. We expect the 1.26 release on the stable track to include a macSys release.

**Comment by marcus-crane** [comment] 2022-05-20 00:21
On a side note, thanks for not using stalebot!

**Closed** 2022-06-09 17:25 UTC
Labels: OS-macos, L3 Some users, P2 Aggravating, T0 New feature
