### ISSUE TITLE
tailscale up --exit-node on unauthorized machine changes iptables immediately

### ISSUE THREAD

**Issue by EliaOnceAgain** [tailscale/tailscale#5953] opened 2022-10-15 21:58 UTC
### What is the issue?

Current Behavior
New machine, still not authorized. Installed Tailscale and ran a script with `tailscale up --exit-node <ip>`
iptables rules were applied immediately before being able to authorize 

Expected Behavior
iptables rules are not applied till after the machine authorize steps are over

### Steps to reproduce

Unauthorized ubuntu22 fresh install run `sudo tailscale up --exit-node <ip>`

### OS

Linux

### OS version

Ubuntu 22.0.1

### Tailscale version

1.32.0

**Comment by DentonGentry** [comment] 2023-06-03 21:23
Duplicate of https://github.com/tailscale/tailscale/issues/4152

**Closed by DentonGentry** 2023-06-03 21:23 UTC
Labels: L1 Very few, P2 Aggravating, T5 Usability, exit-node, bug
