### ISSUE TITLE
Ping times over tailscale keep increasing before dropping and then increasing again

### ISSUE THREAD

**Issue by maisem** [tailscale/tailscale#1838] opened 2021-05-03 18:40 UTC
**Describe the bug**
Ping times over tailscale keep increasing before dropping and then increasing again:
```
PING 100.X.Y.Z (100.X.Y.Z): 56 data bytes
64 bytes from 100.X.Y.Z: icmp_seq=0 ttl=64 time=26.677 ms
64 bytes from 100.X.Y.Z: icmp_seq=1 ttl=64 time=73.857 ms
64 bytes from 100.X.Y.Z: icmp_seq=2 ttl=64 time=118.254 ms
64 bytes from 100.X.Y.Z: icmp_seq=3 ttl=64 time=165.929 ms
64 bytes from 100.X.Y.Z: icmp_seq=4 ttl=64 time=210.212 ms
64 bytes from 100.X.Y.Z: icmp_seq=5 ttl=64 time=254.906 ms
64 bytes from 100.X.Y.Z: icmp_seq=6 ttl=64 time=2.336 ms
64 bytes from 100.X.Y.Z: icmp_seq=7 ttl=64 time=3.248 ms
64 bytes from 100.X.Y.Z: icmp_seq=8 ttl=64 time=11.150 ms
64 bytes from 100.X.Y.Z: icmp_seq=9 ttl=64 time=2.284 ms
64 bytes from 100.X.Y.Z: icmp_seq=10 ttl=64 time=4.123 ms
64 bytes from 100.X.Y.Z: icmp_seq=11 ttl=64 time=2.014 ms
64 bytes from 100.X.Y.Z: icmp_seq=12 ttl=64 time=45.248 ms
64 bytes from 100.X.Y.Z: icmp_seq=13 ttl=64 time=94.260 ms
64 bytes from 100.X.Y.Z: icmp_seq=14 ttl=64 time=137.738 ms
64 bytes from 100.X.Y.Z: icmp_seq=15 ttl=64 time=184.273 ms
64 bytes from 100.X.Y.Z: icmp_seq=16 ttl=64 time=230.180 ms
64 bytes from 100.X.Y.Z: icmp_seq=17 ttl=64 time=277.528 ms
64 bytes from 100.X.Y.Z: icmp_seq=18 ttl=64 time=2.260 ms
64 bytes from 100.X.Y.Z: icmp_seq=19 ttl=64 time=3.029 ms
64 bytes from 100.X.Y.Z: icmp_seq=20 ttl=64 time=2.059 ms
^C
--- 100.X.Y.Z ping statistics ---
21 packets transmitted, 21 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 2.014/88.170/277.528/94.528 ms
```

`tailscale status` shows a direct connection to the subnet router.

```
100.X.Y.Z    nix                  maisem@      linux   active; direct 10.0.6.1:41641, tx 20968 rx 33640
```

Pinging the node directly works fine.

```
PING 10.0.6.1 (10.0.6.1): 56 data bytes
64 bytes from 10.0.6.1: icmp_seq=0 ttl=64 time=0.514 ms
64 bytes from 10.0.6.1: icmp_seq=1 ttl=64 time=0.902 ms
64 bytes from 10.0.6.1: icmp_seq=2 ttl=64 time=0.626 ms
64 bytes from 10.0.6.1: icmp_seq=3 ttl=64 time=0.677 ms
64 bytes from 10.0.6.1: icmp_seq=4 ttl=64 time=0.731 ms
64 bytes from 10.0.6.1: icmp_seq=5 ttl=64 time=0.712 ms
64 bytes from 10.0.6.1: icmp_seq=6 ttl=64 time=0.759 ms
64 bytes from 10.0.6.1: icmp_seq=7 ttl=64 time=0.603 ms
^C
--- 10.0.6.1 ping statistics ---
8 packets transmitted, 8 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.514/0.691/0.902/0.109 ms
```

**To Reproduce**
1. Make sure tailscale is connected
2. Ping any machine on the tailnet
3. See increasing ping times

**Expected behavior**
Ping times should be ~1ms.

**Version information:**
 - Device: mac-mini
 - OS: macOS
 - OS version: macOS 11.2.3
 - Tailscale version: 1.6.0

**Comment by apenwarr** [comment] 2021-05-04 03:03
As discussed today, seems to be reproducible in v1.6.0 so not a regression. Thus doesn't block 1.8.0.

**Comment by DentonGentry** [comment] 2023-02-12 14:14
Given the packet handling changes in 1.36 I'm inclined to close this and expect to open a new bug if the ping behavior is seen again.

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Closed** 2023-06-02 23:03 UTC
Labels: connectivity, L2 Few, P2 Aggravating, T3 Performance/Debugging
