### ISSUE TITLE
After upgrade to QTS 5.0.1.2145, tailscale is not compatible anymore

### ISSUE THREAD

**Issue by scheini1972** [tailscale/tailscale#5673] opened 2022-09-17 08:28 UTC
### What is the issue?

After upgrade to the QTS version QTS 5.0.1.2145, tailsacle is reported as not compatible anymore.

However, it worked with the previous version 5.0.0.2131

### Steps to reproduce

upgrade to the lates Firmware from Qnap.
Try to install the tailscale package, created from Ivo's github
https://github.com/ivokub/tailscale-qpkg

### OS

Other

### OS version

QTS

### Tailscale version

1.30.2

### Bug report

no possible

**Comment by case** [comment] 2022-09-17 15:54
@scheini1972 can you share the errors or logs you're seeing from this issue?

**Comment by ivokub** [comment] 2022-09-18 06:47
For further reference, see https://github.com/ivokub/tailscale-qpkg/issues/46.

**Comment by wingcomm** [comment] 2022-09-18 06:56
These are the only logs that I am getting...

<img width="1170" alt="Screen Shot 2022-09-18 at 2 55 43 AM" src="https://user-images.githubusercontent.com/9159510/190889723-897c5ddb-74d9-4382-9f0b-68339ef303df.png">

**Comment by wingcomm** [comment] 2022-09-18 07:01
I figured it out!

I read over the release notes.

https://www.qnap.com/en-us/release-notes/qts/overview/5.0.1

In "Other Changes"  they mentioned the following: "In App Center, the option "Allow installation of applications without a valid digital signature" is now disabled by default after firmware update."

Sure enough...it was disabled in App Center -> (Gear Icon) -> 
<img width="743" alt="Screen Shot 2022-09-18 at 2 58 19 AM" src="https://user-images.githubusercontent.com/9159510/190889854-08ee1194-059e-46a5-8f72-2cfc98cbf263.png">

Re-enabled it and we're back in business!

**Comment by bradfitz** [comment] 2022-09-18 16:55
Great! Glad to hear that it still works. I'll close this then.

**Comment by ivokub** [comment] 2022-09-18 19:13
> Great! Glad to hear that it still works. I'll close this then.
> 

@bradfitz, the original commenter indicated another problem, see https://github.com/ivokub/tailscale-qpkg/issues/46#issuecomment-1250226062.

**Comment by wingcomm** [comment] 2022-09-19 00:14
@scheini1972 I am running 1.30.1. Have you tried downgrading?

**Comment by DentonGentry** [comment] 2023-02-18 16:41
https://github.com/tailscale/tailscale-qpkg/issues/46#issuecomment-1345180325 indicates the problem is resolved.

**Closed by DentonGentry** 2023-02-18 16:41 UTC
Labels: L1 Very few, P3 Can't get started, T6 Major usability, os-qnap, bug
