### ISSUE TITLE
FR: Support for ~OpenWRT/lede

### ISSUE THREAD

**Issue by garrett-ts** [tailscale/tailscale#6747] opened 2022-12-14 21:41 UTC
### What are you trying to do?

OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux stargate 5.4.188 #0 SMP Sat May 14 10:23:43 2022 aarch64 GNU/Linux

NAME="OpenWrt"
VERSION="21.02-SNAPSHOT"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt 21.02-SNAPSHOT"
VERSION_ID="21.02-snapshot"
HOME_URL="https://openwrt.org/"
BUG_URL="https://bugs.openwrt.org/"
SUPPORT_URL="https://forum.openwrt.org/"
BUILD_ID="r16699-1d12cfdce2"
OPENWRT_BOARD="bcm27xx/bcm2711"
OPENWRT_ARCH="aarch64_cortex-a72"
OPENWRT_TAINTS=""
OPENWRT_DEVICE_MANUFACTURER="OpenWrt"
OPENWRT_DEVICE_MANUFACTURER_URL="https://openwrt.org/"
OPENWRT_DEVICE_PRODUCT="Generic"
OPENWRT_DEVICE_REVISION="v0"
OPENWRT_RELEASE="OpenWrt 21.02-SNAPSHOT r16699-1d12cfdce2"

**Comment by bradfitz** [comment] 2022-12-14 21:42
Hopefully this bug report doesn't get buried.

**Comment by DentonGentry** [comment] 2022-12-15 03:31
Though this FR supplies the install.sh information, we have more to do in `tailscaled` before it will interoperate well with other OpenWRT features. Closing as a duplicate of https://github.com/tailscale/tailscale/issues/6252, but we also need to handle https://github.com/tailscale/tailscale/issues/391 (OpenWRT 22 no longer has an `iptables` binary).

Dup of https://github.com/tailscale/tailscale/issues/6252

**Closed by DentonGentry** 2022-12-15 03:31 UTC
Labels: needs-triage, fr

**Comment by bradfitz** [comment] 2022-12-15 03:36
oh no, @DentonGentry buried the lede

**Comment by DentonGentry** [comment] 2022-12-15 03:39
Looking back at the [setup earlier today](https://github.com/tailscale/tailscale/issues/6747#issuecomment-1352244941), I have to admire the dedication to the joke.
