### ISSUE TITLE
Black screen on android 7

### ISSUE THREAD

**Issue by danbulant** [tailscale/tailscale#10666] opened 2023-12-21 10:41 UTC
### What is the issue?

Nothing shows, just black screen. Looks similar to other graphic issues like #1008

### Steps to reproduce

1. Open the app
2. Get black screen

### OS

Android

### OS version

Android 7.1.2 lineageos 14.1

### Tailscale version

1.56.0 (fdroid)

### Other software

Most notably I don't have google apps, just plain lineageos 14 on am old nexus 7 (2012).

**Comment by cherjr** [comment] 2024-01-09 09:27
+1 (SM-J320F, Android 7.1.2 - LineageOS 14.1, no google apps)

**Comment by DentonGentry** [comment] 2024-01-09 12:26
Duplicate of https://github.com/tailscale/tailscale/issues/4332

**Closed by DentonGentry** 2024-01-09 12:26 UTC
Labels: needs-triage, bug

**Comment by drogers0** [comment] 2026-07-28 18:17
@danbulant — this is fixable now, for anyone finding this thread with the same symptom on Android 7.

The black screen is the Gio UI needing OpenGL ES 3 (or ES 2 plus `EXT_sRGB`) and not getting it. Upstream fixed it by replacing Gio with Compose, which renders through the standard hardware canvas and needs no GLES 3. The catch is that `minSdkVersion` went 22 → 26 in `bf0e56469f`, one commit after that rewrite — so Android 7 (API 24/25) ended up below the floor and never received the fix.

I've backported the Compose app to API 22: https://github.com/drogers0/tailscale-firetv-fireos5

Anything on API 22–25 with an `armeabi-v7a` slot is in scope; the table lists model codes and verdicts so you can find your device: https://github.com/drogers0/tailscale-firetv-fireos5/blob/main/docs/DEVICES.md — or run `scripts/device-check.sh <ip>:5555`, which reports API level, ABI and `ro.opengles.version`.

Verified on 1.98.8 on a Fire TV Stick 2nd gen including exit-node routing; other devices are untested. Unofficial and debug-signed, caveats in the README. If the device turns out to be Android 8+, the official client already works and you don't need this.
