### ISSUE TITLE
Twitter user reports that 'bionic' apt repo didn't upgrade to 1.2.x, but 'focal' repo does

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#970] opened 2020-11-27 01:28 UTC
https://twitter.com/KevinHoffman/status/1332133403651690497

"When I look at the @Tailscale admin console, it says all my devices have an update available... yet when I run the apt update install it says I'm on the latest version 'tailscale is already the newest version (1.0.5).' Is there something else I should be doing to upgrade?"
...
"my tailscale.list file is referring to codename bionic. I'm on Ubuntu 20.10 (PopOS)"
...
"I removed that and replaced it with focal (20.04?) and now I seem to be on the latest (1.2.8)"

I don't actually know how the pkgs.tailscale.com repo generates the indexes. Is it possible that the bionic index is out of date while focal works?

**Comment by apenwarr** [comment] 2020-11-27 01:30
Perhaps it's possible that apt isn't downloading the latest version because it thinks it already has it cached? This could happen if we eg. screwed up our etags or If-modified-since, I guess.

**Comment by bradfitz** [comment] 2020-11-27 04:26
@danderson, got any ideas? I got nothing. Unless the user forgot to do `apt-get update` (or perhaps it had a 500 error that wasn't noticed in the output?) before the `apt-get install`?

**Comment by DentonGentry** [comment] 2021-02-08 17:37
As this hasn't come up again to my knowledge, it seems likely the user had not run apt-get update.

Will close this on the next bug scrub barring comments to the contrary.

**Comment by DentonGentry** [comment] 2021-05-20 22:18
Has not recurred, believe lack of `apt update` is the root cause.

**Closed by DentonGentry** 2021-05-20 22:18 UTC
Labels: OS-linux
