### ISSUE TITLE
FR: Description field for Auth Keys

### ISSUE THREAD

**Issue by ljtill** [tailscale/tailscale#5317] opened 2022-08-08 12:34 UTC
### What are you trying to do?

Assign 'short description' to a generated Auth Key within the Tailscale admin site.

### How should we solve this?

Provide a text box for each Auth Key which is generated so that it's possible to enter a small description such as where / how the key was used.

### What is the impact of not solving this?

Having to note down the Key ID in an external location to recall where the key was implemented. I'm using reusable keys as part of Kubernetes deployments and so being able to provide a description field would help with which key is used with which cluster.

**Comment by DentonGentry** [comment] 2022-08-28 05:54
Duplicate of https://github.com/tailscale/tailscale/issues/4314

**Closed by DentonGentry** 2022-08-28 05:54 UTC
Labels: L3 Some users, P1 Nuisance, T0 New feature, fr
