### ISSUE TITLE
FR: Split tunnelling on Linux

### ISSUE THREAD

**Issue by Victor239** [tailscale/tailscale#9402] opened 2023-09-14 08:16 UTC
### What are you trying to do?

I currently use Mullvad VPN which has [split tunnelling on Linux](https://github.com/mullvad/mullvadvpn-app/pull/1581). I'd like to move to Tailscale and utilise Mullvad VPN through it.

### How should we solve this?

Copy Mullvad VPN's methodology. I see that [split tunnelling on Android](https://github.com/tailscale/tailscale-android/pull/89) is currently WIP, but it's also needed for Linux for feature parity with Mullvad VPN.

### What is the impact of not solving this?

I'm still using Mullvad VPN.

### Anything else?

N/A

**Comment by DentonGentry** [comment] 2023-09-14 10:49
Duplicate of https://github.com/tailscale/tailscale/issues/7766

**Closed by DentonGentry** 2023-09-14 10:49 UTC
Labels: needs-triage, fr
