### ISSUE TITLE
`--advertise-routes` overrides App Connector routes

### ISSUE THREAD

**Issue by joshuajung** [tailscale/tailscale#11006] opened 2024-02-01 20:03 UTC
### What is the issue?

I would like to use a Tailscale machine both as a subnet router to subnets defined by IP and as a domain-based App Connector. However, as the routes created automatically by the App Connector are kept in the same list as my manual subnets (which I need to update regularly), I keep deleting them. 

That would be okay if they would be reinstated the next time an app is launched via the connector, but it seems like they stay removed until I completely delete the app from the Admin Dashboard and recreate it.

### Steps to reproduce

1. Define an app in the dashboard.
2. `tailscale up --advertise-connector`.
3. Launch the app form another machine, so its routes are identified and added to the `Subnet` section in the machine details.
4. Manually add some routes to advertise, e.g. `tailscale set --advertise-routes 10.156.0.0/20`. 

Expected result: the app routes remain available or are recreated the next time they are needed.
Actual result: the app routes are removed and never return.

### OS

Linux

### OS version

Debian

### Tailscale version

1.58.2

### Other software

The client is running on MacOS.

### Bug report

BUG-ee2376a44a2cf581f0df0b4e66491789659d4c5b853fe21b011181356bff40a2-20240201195758Z-cf5a974f2a4f4fa6

**Comment by KevinLiang10** [comment] 2024-03-15 16:52
Hi @joshuajung . we can reproduce your issue here. We are working on a fix for this behaviour to be more reasonable. 

The problem seems to be we have an in memory record to stop the advertised route from re-advertising. The way you can make it work for now is you can do a tailscaled restart after `tailscale set --advertise-routes 10.156.0.0/20` to make tailscale re-learn the routes for app connectors. (You probably should approve the routes again tho).

**Closed** 2024-04-29 18:40 UTC
Labels: bug, app-connector
