### ISSUE TITLE
FR: Update SplitDNS records?

### ISSUE THREAD

**Issue by XBeg9** [tailscale/tailscale#8243] opened 2023-05-31 16:48 UTC
### What are you trying to do?

I am trying to control SplitDNS records

### How should we solve this?

Make API endpoint

### What is the impact of not solving this?

Unable to control SplitDNS

**Comment by DentonGentry** [comment] 2023-05-31 16:49
Duplicate of https://github.com/tailscale/tailscale/issues/2661

**Closed by DentonGentry** 2023-05-31 16:49 UTC
Labels: needs-triage, fr
