### ISSUE TITLE
install.sh: 65: VERSION_CODENAME: parameter not set

### ISSUE THREAD

**Issue by mithro** [tailscale/tailscale#5836] opened 2022-10-05 02:25 UTC
### What is the issue?

When trying to use the install.sh script on a bookworm/sid debian install running on an arm64 platform I get the following output;
```
root@ten64p:/home/tim# curl -fsSL https://tailscale.com/install.sh | sh
sh: 65: VERSION_CODENAME: parameter not set
root@ten64p:/home/tim# 
```

### Steps to reproduce

Try to run the install script on a debian machine (potentially an arm64 debian?).

### OS

Linux

### OS version

bookworm/sid

### Tailscale version

None

**Comment by DentonGentry** [comment] 2022-10-29 15:25
Duplicate of https://github.com/tailscale/tailscale/issues/5522

**Closed by DentonGentry** 2022-10-29 15:25 UTC
Labels: OS-linux, L2 Few, P1 Nuisance, T5 Usability, bug
