### ISSUE TITLE
macOS Monterey 12.5.1 periodically stops sending traffic with tailscale 1.30.0

### ISSUE THREAD

**Issue by wingcomm** [tailscale/tailscale#5594] opened 2022-09-11 07:17 UTC
### What is the issue?

Tailscale up and tailscale ping <host> works with hosts responding but OS does not pass packets through the VPN.

### Steps to reproduce

Wake/sleep your mac on different networks until it stops connecting.

### Are there any recent changes that introduced the issue?

This did start after upgrading to 1.30.0 but I'm not sure if its related.
I tried Disconnecting and Reconnecting in Tailscale but it could not reconnect until I restarted the Tailscale app.

### OS version

macOS Monterey 12.5.1

### Tailscale version

1.30.0

### Bug report

BUG-01deeb523b3f156423d6c2bef9f667b8000f4a39bb42f4f8e1d457b5fc1dedaa-20220911071152Z-8bf0d4e62b58221a

**Comment by bradfitz** [comment] 2022-09-11 14:45
Three minutes before filing this bug you'd commented at https://github.com/tailscale/tailscale/issues/2524#issuecomment-1242903718 saying:

> I'm still seeing this here on macOS Monterey 12.5.1 and tailscale 1.30.0

So should we close this bug as a duplicate of that bug?

#2524 is titled "MacOS Monterey intermittent stops due to other network extensions".

Do you have other network extensions running?

**Comment by wingcomm** [comment] 2022-09-12 06:52
So, after reading that bug  I was under the impression that that bug was closed since it referred to a case where macOS allegedly patched this issue in 12.2. So, its hard to say if this is the same bug or a new one so I decided open a new case since I thought it may new issue.

**Comment by joaocc** [comment] 2022-09-12 21:08
I have a similar/related issue on BigSur (11.6.8) where Cloudflare Warp (gateway mode) prevents communication with remote hosts via tailscale, even when network ranges are added to exclusion list, so maybe this is more generic than Monterey. Please let me know if you prefer I move the report to it's own issue.

**Comment by wingcomm** [comment] 2022-09-24 10:06
Got a new bugreport from 1.30.1 when the issue recurred.

**Comment by DentonGentry** [comment] 2022-11-01 11:55
Around the time of the bugreport, the machine periodically reports having no IPv4 addresses:
```
2022-09-24 05:56:27.473564 -0400 -0400: LinkChange: major, rebinding. New state: interfaces.State{defaultRoute=en6 ifs={en0:[2601:199:q:r::s/64] en6:[2601:199:q:r::s/64 2601:199:q:r:s:t:u:v64 2601:199:q:r:s:t:u:v/64] utun3:[100.100.x.y/32 fd7a:115c:a1e0:ab12:w:x:y:z/48]} v4=false v6=true}

2022-09-25 06:02:20.747665 -0400 -0400: LinkChange: major, rebinding. New state: interfaces.State{defaultRoute=en6 ifs={en6:[192.168.10.105/24 2601:199:q:r::s/64 2601:199:q:r:s:t:u:v/64 2601:199:q:r:s:t:u:v/64 2601:199:q:r:s:t:u:v/64] utun3:[100.100.x.y/32 fd7a:115c:a1e0:ab12:w:x:y:z/48]} v4=true v6=true}
```

Tailscale can work with only IPv6, but I think this indicates a more general instability in the machine's connectivity.

**Comment by DentonGentry** [comment] 2023-06-03 20:19
At this point I do not expect to be able to diagnose what was going wrong last September. We saw the machine repeatedly losing and regaining its IPv4 address.

If similar issues are noted, please reopen or open a new issue and include a fresh bugreport.

**Closed by DentonGentry** 2023-06-03 20:19 UTC
Labels: OS-macos, L1 Very few, P2 Aggravating, T5 Usability, vpn-interop, bug
