### ISSUE TITLE
Android app stuck on black screen on Lineage OS 16 (Android 9)

### ISSUE THREAD

**Issue by GoTVm** [tailscale/tailscale#9216] opened 2023-09-02 19:41 UTC
### What is the issue?

The application never loads/shows anything. It stays stuck on the initial black screen.

### Steps to reproduce

Download the app from the Play Store
Open it

### OS

Other

### OS version

Lineage OS 16 (Android 9)

**Comment by DentonGentry** [comment] 2023-09-02 19:49
The issue with with devices using OpenGL ES2
Duplicate of https://github.com/tailscale/tailscale/issues/4332

**Closed by DentonGentry** 2023-09-02 19:49 UTC
Labels: needs-triage, bug
