### ISSUE TITLE
Figure out how to plumb environment variables into IPNExtension for debugging

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1165] opened 2021-01-19 17:26 UTC
On Linux and Windows it's possible to run tailscaled with environment variables set to tweak various esoteric knobs inside Tailscale, useful for debugging.

On macOS, the GUI starts the IPNExtension (effectively "tailscaled") but does so in a way that doesn't seem to propagate the GUI environment's environment variables. (tested by starting the GUI app from Terminal.app with some environment variables set).

This bug is about figuring out a way to set some environment variables in IPNExtension, before any Go code runs.

/cc @nickoneill @crawshaw

**Comment by DentonGentry** [comment] 2023-02-12 05:34
Duplicate of https://github.com/tailscale/tailscale/issues/3707 (which, though filed later, has had more activity and updates).

**Closed by DentonGentry** 2023-02-12 05:34 UTC
Labels: OS-macos, L3 Some users, P1 Nuisance, T3 Performance/Debugging
