### ISSUE TITLE
FR: AutoUpdate

### ISSUE THREAD

**Issue by ajnadox** [tailscale/tailscale#4097] opened 2022-03-08 13:36 UTC
### What are you trying to do?

it would be completely great if there was an autoupdate function in the tailscale client on windows because our users are 85%  non tech and if we install tailscale today they will run the exactly same version after a year if we don't remote every user and update it manually, that is a real pain and unnecessary workload when autoupdate would solve this.

### How should we solve this?

 when check for new version is made today why not just launch a new process that updates it to the new version at the same time, then when user reboots computer or when tailscale is idle,  the process with old tailscale is killed and new launched

### What is the impact of not solving this?

manually updating, that is a real pain and unnecessary workload when autoupdate would solve this.

**Comment by DentonGentry** [comment] 2022-03-08 13:39
Duplicate of https://github.com/tailscale/tailscale/issues/755

**Closed by DentonGentry** 2022-03-08 13:39 UTC
Labels: needs-triage, fr
