### ISSUE TITLE
exit node in microk8s with Calico iptables rules not working

### ISSUE THREAD

**Issue by mcfedr** [tailscale/tailscale#5632] opened 2022-09-14 10:47 UTC
### What is the issue?

Trying to use Linux server as exit node, but internet doesnt work.

I have
 - linux machine with tailscale, subnet and exit node enabled
 - mac with app store version of tailscale, exit node enabled
 - android

### Steps to reproduce

1. on the mac enable linux machine as the exit node
2. no internet 

1. on android enable linux machine as the exit node
2. no internet

Tests

DNS works from the mac

```
$ dig google.com

; <<>> DiG 9.10.6 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63324
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4095
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		222	IN	A	216.58.208.206

;; Query time: 59 msec
;; SERVER: 100.100.100.100#53(100.100.100.100)
;; WHEN: Tue Aug 30 22:50:05 BST 2022
;; MSG SIZE  rcvd: 55
```

but connection gets lost

```
traceroute to google.com (216.58.208.206), 64 hops max, 52 byte packets
 1  gandi (100.121.121.127)  54.507 ms  53.490 ms  54.135 ms
^C
```

I've used both mac store and non-mac store version, doesnt change anything.

If I use the mac as an exit node for my phone, that works fine.

reported before in https://github.com/tailscale/tailscale/issues/4010#issuecomment-1232208353

### OS

Linux, macOS, Android

### OS version

Ubuntu 20.04.5 LTS, Macos 12.5, Android 12

### Tailscale version

1.30.1

### Bug report

BUG-4d9897018902d79e7f7926e364623a1d0a772d5f256aa3e45d6a7e76c861726d-20220914103201Z-3dacbe210d9cb68c

**Comment by bradfitz** [comment] 2022-09-14 17:06
Have you enabled IP forwarding on Linux?

See https://tailscale.com/kb/1019/subnets/?q=sysctl&tab=linux

**Comment by mcfedr** [comment] 2022-09-15 10:11
Forgot to mention, but yes

```shell
$ cat /proc/sys/net/ipv4/ip_forward
1
$ cat /proc/sys/net/ipv6/conf/all/forwarding
1
```

**Comment by DentonGentry** [comment] 2022-11-01 12:17
I'm not really able to make sense of the iptables output given that it is hundreds of lines long, but I'd agree it is a reasonable suspicion that tailscaled and the Calico k8s rules are interacting.

**Comment by mohd-akram** [comment] 2022-11-20 20:30
I'm having the same issue on a freshly installed CentOS Stream 9 server (no k8s or anything).

**Comment by JordyEGNL** [comment] 2023-01-26 18:17
Are you all using a Tailscale account that was created with your Github account? I just created a new account using Microsoft and it works perfectly fine now

**Comment by TJackhammer** [comment] 2023-02-10 21:27
I am also having this issue on openSUSE Tumbleweed. My setup is using the openSUSE machine as an exit node, and trying to connect via my Macbook.  I see the same symptoms described above. I have confirmed that the IP forwarding and masquerading are turned on for the openSUSE machine.

Below is the bug report from my MAC when it is happening: 
BUG-b81c5dfde2538bb842df98ff5a54fc3d2bb4288ba1860738c50f25c5ed001c1d-20230210212551Z-4a47fb37b99757f6


And below is the bug report from the Linux machine:
BUG-261acb3cb7c5f4f7eb27d374fcfad2cad7542cb91bf51862f6f597d01f8b8b13-20230210212647Z-7607de8b74171030

Any thoughts on what I should try here?

**Comment by mohd-akram** [comment] 2023-02-11 11:12
I was able to resolve the issue by fiddling with firewalld. Check the active zones:

```
sudo firewall-cmd --get-active-zones
```

The main (eg. enp1s0) and tailscale (eg. tailscale0) interfaces needed to be in the same zone. Then, make sure both `masquerading` and `forward` are set to `yes` (replace `$zonename` with the name of the zone that both interfaces are in):

```
sudo firewall-cmd --info-zone=$zonename
```

If you have `masquerade: no`, run:

```
sudo firewall-cmd --add-masquerade --zone=$zonename --permanent
```

If you have `forward: no`, run:

```
sudo firewall-cmd --add-forward --zone=$zonename --permanent
```

Reload for the changes to take effect:

```
sudo firewall-cmd --reload
```

The firewalld forward was the missing piece for me.

@DentonGentry perhaps a `firewall-cmd --permanent --add-forward` step should be added to the docs.

**Comment by TJackhammer** [comment] 2023-02-13 14:42
Thank you so much for your help! It  turns out my issue was that my Tailscale and Ethernet interfaces were not in the same zone (in fact they weren't in any zone at all). Following these instructions got the Exit Node to work for me.

Just a note for anyone following in the future, I also had to bring Tailscale down and back up again on the Linux machine before it would work. (`tailscale down` followed by `tailscale up --accept-routes --advertise-exit-node`)

**Comment by DentonGentry** [comment] 2023-02-18 15:53
> Thank you so much for your help! It turns out my issue was that my Tailscale and Ethernet interfaces were not in the same zone (in fact they weren't in any zone at all). Following these instructions got the Exit Node to work for me.

Closing as resolved.

**Closed by DentonGentry** 2023-02-18 15:53 UTC
Labels: OS-linux, L1 Very few, P2 Aggravating, T5 Usability, exit-node, bug

**Comment by mcfedr** [comment] 2023-09-06 13:08
I'm coming back to try this again, still not working for me. I dont have `firewall-cmd` or `firewalld` installed so I'm assuming thats not my problem - @mohd-akram maybe you know? 

I have a new network node, very similar setup, but this one is interesting 

using it has exit node

1. IPv6 connectivity works!
2. But no IPv4 :(

the node is on a CGNAT network, i wonder if it could be DNS - but no, IPv4 pings dont work using the exit node

```
$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
^C
--- 8.8.8.8 ping statistics ---
5 packets transmitted, 0 packets received, 100.0% packet loss
```
