### ISSUE TITLE
FR: Add the Tailscale Interface to the Dashboard on Ubiquiti Edgerouters (EdgeOS)

### ISSUE THREAD

**Issue by argiedoubleya** [tailscale/tailscale#8330] opened 2023-06-12 19:24 UTC
### What are you trying to do?

It would be great if the Tailscale Interface was listed and visibile in the Dashboard of Ubiquiti EdgeOS devices (Edgerouters)

### How should we solve this?

The wireguard package interface is visible in the Dashboard so it should be possible

**Comment by DentonGentry** [comment] 2023-06-12 20:06
This would be pretty compelling, but we'd have to come to workable terms with Ubiquiti Inc. EdgeOS and the software used on the Unifi products removes third party software upon every OS upgrade.

> The wireguard package interface is visible in the Dashboard so it should be possible

That isn't as relevant as one might think, Tailscale uses a userspace implementation of Wireguard called wireguard-go on all platforms: https://tailscale.com/blog/throughput-improvements/

Closing as a duplicate of https://github.com/tailscale/tailscale/issues/735

**Closed by DentonGentry** 2023-06-12 20:06 UTC
Labels: needs-triage, fr
