### ISSUE TITLE
Android TV Client change server functionality does not work

### ISSUE THREAD

**Issue by dmitrijoseph** [tailscale/tailscale#7861] opened 2023-04-14 05:24 UTC
### What is the issue?

I am unable to change my server url on my android TV device, there are seemingly two issues, first due to this bug #7818  you can't open and close the kebab menu for the option to change server to ever appear,  next even if you can open and close the kebab the option simply never appears. This can be tested using scrcpy  from a pc, without the bug from #7818 interfering, opening and closing the kebab menu never causes the change server option to ever appear. I tested this way on 1.38.2, and then I downgraded my apk to 1.33 and 1.32 which allowed me to open and close the kebab menu without the interference of the current bug, but change server never appears on those versions either

### OS

Android

### OS version

Android 11

### Tailscale version

1.38.2

**Comment by DentonGentry** [comment] 2023-06-04 07:31
Duplicate of https://github.com/tailscale/tailscale/issues/7818

**Closed by DentonGentry** 2023-06-04 07:31 UTC
Labels: OS-android, L1 Very few, P3 Can't get started, T5 Usability, bug
