### ISSUE TITLE
Exit node DNS not working in Docker container with no '/lib/modules' directory

### ISSUE THREAD

**Issue by RMNB** [tailscale/tailscale#5237] opened 2022-07-30 15:34 UTC
### What is the issue?

When I connect to an exit node on a linux host (Ubuntu 22.04) running in a docker container, the internet does not work. It seems like DNS is not resolved. Enabling/disabling "Override local DNS" in the control panel does not resolve the issue.

The Linux host has the following in the log:
`tailscale    | 2022/07/30 14:32:33 Accept: TCP{100.112.192.38:50150 > 100.86.236.121:65128} 64 tcp ok
tailscale    | 2022/07/30 14:32:33 [RATELIMIT] format("peerapi: handleDNS fwd error: %v") (20 dropped)
tailscale    | 2022/07/30 14:32:33 peerapi: handleDNS fwd error: upstream nameservers not set
tailscale    | 2022/07/30 14:32:33 peerapi: handleDNS fwd error: upstream nameservers not set`

I enabled an exit node on a Windows computer and everything works as expected. 

I then installed tailscale the regular way on Ubuntu and which also does not work, but in this case enabling "Override local DNS" it does start working. This does not help the docker setup and is not necessary for the windows setup.

### Steps to reproduce

- Made the following updates to sysctl.conf:

`net.ipv6.conf.all.forwarding = 1
net.ipv4.conf.all.forwarding=1`

- Run official docker image with docker compose.

- Authenticate and enable exit node (also enable in control panel)

`tailscale up --authkey=$KEY --advertise-exit-node`

On Windows and iOS I can connect to the linux tailscale IP, but I can't use the exit node for internet. Something's wrong with the DNS.

### Are there any recent changes that introduced the issue?

This is a new install

### OS

Linux

### OS version

Ubuntu 22.04

### Tailscale version

1.28.0

### Bug report

BUG-227215c6ddd6b0ae380a5553fa06b05aaac67b379870236423e7d74afe6f9955-20220730153152Z-af93a31f52652ce0

**Comment by DentonGentry** [comment] 2022-08-05 23:31
Shortly after startup of tailscaled:
`2022-07-30 14:16:28.397005074 +0000 UTC: authReconfig: ra=false dns=true 0x01: setting up filter/ts-input: running [/sbin/ip6tables -t filter -N ts-input --wait]: exit status 3: modprobe: can't change directory to '/lib/modules': No such file or directory ip6tables v1.8.8 (legacy): can't initialize ip6tables table 'filter': Table does not exist (do you need to insmod?) Perhaps ip6tables or your kernel needs to be upgraded.`

`2022-07-30 14:16:28.397059321 +0000 UTC: control: controlclient: restarting map request for "router" health change to new state: setting up filter/ts-input: running [/sbin/ip6tables -t filter -N ts-input --wait]: exit status 3: modprobe: can't change directory to '/lib/modules': No such file or directory ip6tables v1.8.8 (legacy): can't initialize ip6tables table 'filter': Table does not exist (do you need to insmod?) Perhaps ip6tables or your kernel needs to be upgraded.`

`2022-07-30 14:16:28.397123932 +0000 UTC: health("router"): error: setting up filter/ts-input: running [/sbin/ip6tables -
t filter -N ts-input --wait]: exit status 3: modprobe: can't change directory to '/lib/modules': No such file or directory`

tailscaled doesn't currently handle this case well, it ends up returning early and can leave MagicDNS not fully initialized.

Adding ip6tables in the Dockerfile is likely to help.

**Comment by RMNB** [comment] 2022-08-07 00:26
> 

Are you suggesting I make my own Docker image based on the official tailscale image?

**Comment by DentonGentry** [comment] 2022-08-07 00:39
I'm suggesting that the lack of ip6tables leads to tailscaled exiting its initialization early and is likely what results in DNS not working. Adding `apt install ip6tables` or equivalent to the Dockerfile is likely to help.

**Comment by bradfitz** [comment] 2022-08-07 00:47
The ip6tables exists, no? It's just failing to run.

**Comment by RMNB** [comment] 2022-08-07 20:25
> I'm suggesting that the lack of ip6tables leads to tailscaled exiting its initialization early and is likely what results in DNS not working. Adding `apt install ip6tables` or equivalent to the Dockerfile is likely to help.

I’d do this by making my own Docker image based on the official one right?

Shouldn’t this be added to the official docket image? Or is this issue unique to me somehow?

**Comment by RMNB** [comment] 2022-08-09 13:20
Looks like ip6tables is being installed. From the official dockerfile:

`RUN apk add --no-cache ca-certificates iptables iproute2 ip6tables `

as @bradfitz says it’s just not running

**Comment by DentonGentry** [comment] 2022-08-09 13:26
It is failing:
`2022-07-30 14:16:28.397005074 +0000 UTC: authReconfig: ra=false dns=true 0x01: setting up filter/ts-input: running [/sbin/ip6tables -t filter -N ts-input --wait]: exit status 3: modprobe: can't change directory to '/lib/modules': No such file or directory ip6tables v1.8.8 (legacy): can't initialize ip6tables table 'filter': Table does not exist (do you need to insmod?) Perhaps ip6tables or your kernel needs to be upgraded.`

Presumably this is something in the host, like no kernel module.

**Comment by DentonGentry** [comment] 2022-08-28 15:35
According to the error output there is no /lib/modules and no ability to use the TUN device. You need a container able to open /dev/net/tun.

**Comment by bradfitz** [comment] 2022-08-28 16:32
I think the container is using iptables-legacy but the host is using iptables-nft. We should make Tailscale detect which mode to operate in to match the host.

(@andrew-d, this is the class of problem I was talking to you about the other day.)

**Comment by DentonGentry** [comment] 2022-10-30 12:44
Duplicate of https://github.com/tailscale/tailscale/issues/5621

**Closed by DentonGentry** 2022-10-30 12:44 UTC
Labels: L2 Few, P2 Aggravating, T5 Usability, containers, bug
