### ISSUE TITLE
Mi box s blank screen

### ISSUE THREAD

**Issue by glasernet** [tailscale/tailscale#7550] opened 2023-03-13 20:58 UTC
### What is the issue?

Mi box s 4k tv box running android 9 after installing the app and opening it a white screen and then a black screen tried restarting and reinstalling didn’t help

### Steps to reproduce

Open the app

### Are there any recent changes that introduced the issue?

First time trying on android tv

### OS version

Android tv 9

**Comment by DentonGentry** [comment] 2023-03-14 03:57
Duplicate of https://github.com/tailscale/tailscale/issues/4332

**Closed by DentonGentry** 2023-03-14 03:57 UTC
Labels: needs-triage, bug
