### ISSUE TITLE
Android TV Issue - White/Black Screen

### ISSUE THREAD

**Issue by denzoid** [tailscale/tailscale#5539] opened 2022-09-03 00:48 UTC
I installed Tailscale from the official Play Store but when I launch it all I get is a completely white screen then after a few seconds it turns completely black, no prompts to activate a VPN or anything at all. This is a MiBox4 running Android 9. I am new to TS and unsure if I am doing something wrong, or if there is some setting I need to adjust. The reason I need TS on this box is I have an Unraid server running TS with all my media and want access to it for playback with VLC.

**Comment by DentonGentry** [comment] 2022-09-03 00:53
Duplicate of https://github.com/tailscale/tailscale/issues/4332, which we don't yet have a fix for.

**Closed by DentonGentry** 2022-09-03 00:53 UTC
