### ISSUE TITLE
FR: Allow hostnames defined for ACLs to be used with MagicDNS

### ISSUE THREAD

**Issue by dfcarney** [tailscale/tailscale#2866] opened 2021-09-17 01:11 UTC

**Comment by DentonGentry** [comment] 2022-02-06 05:45
Hostnames defined in ACLs are typically used to provide a name for an IP address reachable via a subnet router, not usually to provide an alternate hostname for a Tailscale IP address.

Do we know the original reason for this request? Presumably a user inquiry around Sept 16, 2021, but there is no Front link.

**Comment by DentonGentry** [comment] 2023-02-12 19:38
Duplicate of https://github.com/tailscale/tailscale/issues/3800

**Closed by DentonGentry** 2023-02-12 19:38 UTC
Labels: L3 Some users, P1 Nuisance, T0 New feature, fr
