### ISSUE TITLE
fatal error: glGetError: 0x501

### ISSUE THREAD

**Issue by athuljayaram** [tailscale/tailscale#10496] opened 2023-12-07 16:17 UTC
### What is the issue?

seeing white screen on android tv 

adb logcat -s "com.tailscale.ipn:*"
--------- beginning of system
--------- beginning of main
12-07 21:42:59.864  6761  6782 I com.tailscale.ipn: logtail started
12-07 21:42:59.865  6761  6782 I com.tailscale.ipn: goSetupLogs: success
12-07 21:42:59.871  6761  6782 I com.tailscale.ipn: 8.8M/108.2M dns: using *router.CallbackRouter
12-07 21:42:59.872  6761  6782 I com.tailscale.ipn: 8.8M/108.2M link state: interfaces.State{defaultRoute=eth0 ifs={eth0:[192.168.0.100/24 2405:201:f025:501a:c549:2931:68a6:59ef/64 2405:201:f025:501a:d224:15cd:7eea:22ec/64 llu6]} v4=true v6=true}
12-07 21:42:59.885  6761  6782 I com.tailscale.ipn: 8.9M/109.9M magicsock: [warning] failed to force-set UDP read buffer size to 7340032: operation not permitted; using kernel default values (impacts throughput only)
12-07 21:42:59.887  6761  6782 I com.tailscale.ipn: 9.0M/109.9M magicsock: [warning] failed to force-set UDP write buffer size to 7340032: operation not permitted; using kernel default values (impacts throughput only)
12-07 21:42:59.890  6761  6785 I com.tailscale.ipn: 9.0M/109.9M magicsock: [warning] failed to force-set UDP read buffer size to 7340032: operation not permitted; using kernel default values (impacts throughput only)
12-07 21:42:59.891  6761  6785 I com.tailscale.ipn: 9.0M/109.9M magicsock: [warning] failed to force-set UDP write buffer size to 7340032: operation not permitted; using kernel default values (impacts throughput only)
12-07 21:42:59.893  6761  6785 I com.tailscale.ipn: 9.0M/109.9M magicsock: disco key = d:f567abda3871d087
12-07 21:42:59.894  6761  6785 I com.tailscale.ipn: 9.0M/109.9M Creating WireGuard device...
12-07 21:42:59.896  6761  6785 I com.tailscale.ipn: 9.1M/109.9M Bringing WireGuard device up...
12-07 21:42:59.901  6761  6783 I com.tailscale.ipn: 9.1M/109.9M Bringing router up...
12-07 21:42:59.907  6761  6785 I com.tailscale.ipn: 9.4M/109.9M Clearing router settings...
12-07 21:42:59.908  6761  6785 I com.tailscale.ipn: 9.5M/109.9M Starting network monitor...
12-07 21:42:59.910  6761  6785 I com.tailscale.ipn: 9.5M/110.5M Engine created.
12-07 21:43:00.088  6761  6781 I com.tailscale.ipn: fatal error: glGetError: 0x501
12-07 21:43:03.070  6761  6785 I com.tailscale.ipn: 9.5M/118.5M pm: migrating "ipn-android" profile to new format
12-07 21:43:03.071  6761  6785 I com.tailscale.ipn: 9.5M/118.5M logpolicy: using UserCacheDir, "/data/user/0/com.tailscale.ipn/files/cache/Tailscale"
12-07 21:43:03.463  6761  6788 I com.tailscale.ipn: 9.6M/118.5M Start
12-07 21:43:04.474  6761  6783 I com.tailscale.ipn: 11.9M/119.5M timeout waiting for initial portlist
12-07 21:43:04.480  6761  6785 I com.tailscale.ipn: 11.9M/119.5M Backend: logs: be:6d7b32d48c2244e6fdf359c6eef4c8ef682be0ff1f221c65d3be2aaa4a267956 fe:
12-07 21:43:04.483  6761  6788 I com.tailscale.ipn: 11.9M/119.6M Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
12-07 21:43:04.484  6761  6788 I com.tailscale.ipn: 11.9M/119.6M health("overall"): error: state=NeedsLogin, wantRunning=false
12-07 21:43:04.491  6761  6788 I com.tailscale.ipn: 11.9M/119.8M SetPrefs: Prefs{ra=true dns=true want=false host="Xiaomi MiTV-AXSO0" update=check Persist=nil}
12-07 21:43:04.493  6761  6785 I com.tailscale.ipn: 12.0M/119.9M blockEngineUpdates(true)
12-07 21:43:04.497  6761  6785 I com.tailscale.ipn: 12.0M/119.9M wgengine: Reconfig: configuring userspace WireGuard config (with 0/0 peers)
12-07 21:43:04.498  6761  6788 I com.tailscale.ipn: 12.0M/119.9M wgengine: Reconfig: configuring router

**Comment by DentonGentry** [comment] 2024-01-09 12:26
Duplicate of https://github.com/tailscale/tailscale/issues/4332

**Closed by DentonGentry** 2024-01-09 12:26 UTC
Labels: needs-triage, bug
