### ISSUE TITLE
100.100.100.100 not working in 1.8.0 when MagicDNS off

### ISSUE THREAD

**Issue by sylr** [tailscale/tailscale#1886] opened 2021-05-08 10:53 UTC
Hi,

I have a pi-hole host that I advertise as DNS server on tailscale.

On the pi-hole I have a Coredns  server running the following conf to forward xxxx.company.fr.beta.tailscale.net to 100.100.100.100:

```
orange.fr.:5052 {
	forward orange.fr. 80.10.246.2 81.253.149.2 80.10.246.132
}

beta.tailscale.net.:5052 {
	forward beta.tailscale.net. 100.100.100.100
}

.:5052 {
	forward . tls://9.9.9.9 tls://2620:fe::fe {
		tls_servername dns.quad9.net
		health_check 5s
	}
	cache 30
	prometheus localhost:9253
}
```

It used to work nicely on 1.6.0 but does not anymore on 1.8.0:

1.6.0:
```
root@bdx-val-dns1:~# dig bdx-val-pi1.company.fr.beta.tailscale.net @100.100.100.100

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Raspbian <<>> bdx-val-pi1.company.fr.beta.tailscale.net @100.100.100.100
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61220
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;bdx-val-pi1.company.fr.beta.tailscale.net. IN A

;; ANSWER SECTION:
bdx-val-pi1.company.fr.beta.tailscale.net. 600 IN A	100.113.100.126

;; Query time: 0 msec
;; SERVER: 100.100.100.100#53(100.100.100.100)
;; WHEN: Sat May 08 12:43:25 CEST 2021
;; MSG SIZE  rcvd: 124
```

1.8.0:
```
root@bdx-val-dns1:~# dig bdx-val-pi1.company.fr.beta.tailscale.net @100.100.100.100

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Raspbian <<>> bdx-val-pi1.company.fr.beta.tailscale.net @100.100.100.100
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Regards.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_35s9d)

**Comment by danderson** [comment] 2021-05-08 12:07
I'm confused how this ever worked. If you disabled MagicDNS in the admin panel, we don't generate any DNS records for the quad-100 resolver. Can you confirm that you have MagicDNS disabled in the admin panel?

I'll have to look at the 1.6 code on Monday to figure out why this used to work, and if we should do the same in 1.8.

**Comment by sylr** [comment] 2021-05-08 16:01
> Can you confirm that you have MagicDNS disabled in the admin panel?

Yes, it is definitively disabled but It has been enabled in the past.

**Comment by ivokub** [comment] 2021-05-12 00:10
I can confirm that the 100.100.100.100 resolver worked before 1.8.1 (do not know about 1.8.0 as I missed the update). I am running unstable packages and it was also working with 1.7.NNN releases.

The 100.100.100.100 resolver used to support reverse resolving of IPs which was my primary use case for it.

I do not recall enabling MagicDNS, but I can not say definitely that I haven't done that. Would toggling MagicDNS allow me to keep using quad-100 for resolving tailnet (reverse) addresses?

**Comment by DentonGentry** [comment] 2021-05-12 11:50
I suspect this is an instance of https://www.hyrumslaw.com/
That Magic DNS would respond to queries sent directly to it even if disabled was never an intentional choice, though it may have happened to do so.

Reading the threads above I think some of the intended uses can be met using Split DNS https://tailscale.com/blog/tailscale-v1.8/ which should be activated in the admin panel soon. It will allow Magic DNS to be enabled without using it for everything.

**Comment by danderson** [comment] 2021-05-12 16:39
Split DNS will help somewhat, yeah. More generally, I don't think we can serve MagicDNS records unconditionally from 100.100.100.100, because in certain configurations we have to use 100.100.100.100 as a DNS relay for all DNS traffic, and in those scenarios we can't serve MagicDNS records if the user hasn't enabled MagicDNS.

I'm still thinking about possible solutions that preserve our past behavior, but I haven't come up with anything so far that doesn't also break actual product features.

**Comment by sylr** [comment] 2021-05-12 17:59
Then a new `100.100.100.10x` which would only resolve tailscale names would be convenient :)

**Comment by danderson** [comment] 2021-05-17 19:07
After discussion with the team, what we're going to do is change the definition of "MagicDNS is on". Previously, it meant "generate internal records for quad-100 and add search+routing config in the OS". We're going to change it to just "add search+routing config in the OS", and unconditionally add MagicDNS records to quad-100.

If MagicDNS is off in the admin panel, we do not guarantee that the OS will be able to resolve MagicDNS, but FQDN queries sent directly to quad-100 will continue to resolve.

**Closed** 2021-05-18 21:15 UTC
Labels: OS-linux, P2 Aggravating, T5 Minor usability, dns
