### ISSUE TITLE
Unable to create tuntap device file: operation not permitted

### ISSUE THREAD

**Issue by bingkunyangvungle** [tailscale/tailscale#11733] opened 2024-04-14 11:29 UTC
### What is the issue?

When tailscale operator trying to create proxy, the pod has issue launching with the error:
`Unable to create tuntap device file: operation not permitted`

The issue comes from this line:
```
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
```
From this [proxy.yaml](https://github.com/tailscale/tailscale/blob/a6739c49dfa74a32e6a51a0afbe22145b6f0cf60/docs/k8s/proxy.yaml#L32) file.

After I change it to:
```    
    securityContext:
      privileged: true
```
The pod started successfully.

Could you please to fix this issue in the new release? Thank you.

### Steps to reproduce

I'm using the k8s with version 1.28.6 and with Tailscale operator with version 1.56.1
Created the ExternalName and the proxy pod has the issue to launch.

### Are there any recent changes that introduced the issue?

N/A

### OS

Linux

### OS version

Ubuntu 22.04

### Tailscale version

1.56.1

### Bug report

BUG-7bc3cf19434092f3ece48c0cce07d88a2134bfa93ecadedbd5717d9410200841-20240414112916Z-59f33c2eaee63e9f

**Comment by irbekrm** [comment] 2024-04-15 07:42
Duplicate of https://github.com/tailscale/tailscale/issues/10814

**Closed by irbekrm** 2024-04-15 07:42 UTC
Labels: needs-triage, bug
