### ISSUE TITLE
Eset Antivirus,  "wingo/hacktool.reversessh.f" 

### ISSUE THREAD

**Issue by krsuhjunho** [tailscale/tailscale#11001] opened 2024-02-01 08:45 UTC
### What is the issue?

I work for a company that uses Eset Antivirus.

When I tried to reinstall the problem because Tailscale is not available today, Tailscaled.exe was recognized as wingo/hacktool.reversesh.f and automatically deleted!

---------------------------
Tailscale Error
---------------------------
Tailscale service not installed on this machine.

Version 1.58.2 (t6a2a8457f-g8c7d4563e)

LogID: 1d119ac0546e40895c675447b555237cace3226a0eaae5520de59f4f53a27576

(Ctrl-C to copy this text)

---------------------------
OK   
---------------------------

### Steps to reproduce

I made it possible to install by adding C:\Program Files\Tailscale\ to the exclusion option in Eset Antivirus

### OS version

Windows 11

### Tailscale version

1.52.2

**Comment by kevinbosman** [comment] 2024-02-01 09:18
This is a duplicate of #10987

**Comment by catzkorn** [comment] 2024-02-02 00:55
Closing as dupe of https://github.com/tailscale/tailscale/issues/10987

**Closed by catzkorn** 2024-02-02 00:55 UTC
Labels: needs-triage, bug
