### ISSUE TITLE
Tailscale Android client VPN profile does not survive reboots

### ISSUE THREAD

**Issue by maxwell5555** [tailscale/tailscale#8260] opened 2023-06-02 22:18 UTC
### What is the issue?

I run Tailscale on an Android Pixel 6 and Pixel 4. When the phones reboot, the Tailscale app does not automatically bring up the VPN. Only when I open Tailscale manually does the VPN come back up.

### Steps to reproduce

Prereq: Tailscale is running and active on an Android phone (VPN key icon showing in the notification area)

1. Reboot phone
2. Observe that Tailscale is no longer active

### Are there any recent changes that introduced the issue?

I believe this has always been the behavior. I have been running Tailscale for @2 months.

### OS

Android

### OS version

Android 13

### Tailscale version

1.40.0

### Other software

N/A

### Bug report

BUG-b89e8ca1043c78a1269102502f5cdd5af09f6ce24802fe0466ee843ea1d3a1e4-20230602221536Z-8bdb4fbea3479919

**Comment by DentonGentry** [comment] 2023-06-04 20:42
Duplicate of https://github.com/tailscale/tailscale/issues/2481

**Closed by DentonGentry** 2023-06-04 20:42 UTC
Labels: needs-triage, bug

**Comment by tom-hampton** [comment] 2023-09-16 19:00
@DentonGentry this is not a duplicate of #2481.   That issue noted that tailscale was stopped before reboot.  This issue specifically notes that tailscale was active prior to the reboot.  

I'm having the exact same issue with 1.48 on Samsung s21ultra. 

1.  Tailscale is set as always on VPN in settings
2. Tailscale is active and connected
3. Restart android
4. Tailscale is stopped after reboot.

I get an error in notifications pull down from the VPN system stating "tailscale is setup to stay connected all the time, but it can't connect right now.  Your phone will use the public internet until tailscale can connect."

From that dialog I can "change VPN settings" or open the app.  If I open the app I can the set tailstale from stopped to active, and everything works fine, until I reboot again....which repeats the experience.
