### ISSUE TITLE
Private DNS servers do not work with Magic DNS

### ISSUE THREAD

**Issue by eh8** [tailscale/tailscale#1887] opened 2021-05-08 23:53 UTC
I have DNS servers for my local network that are not accessible to the outside world. Tailscale is pointed to these in the DNS configuration section. Enabling an exit node via the Tailscale app breaks DNS resolution if Magic DNS is enabled.

If I add a public resolver like 1.1.1.1 or 8.8.8.8, DNS works fine.

I think this is related to the `--exit-node-allow-lan-access` flag that Linux uses. But this is strange, since I can use my iPhone to ping the `192.168.x.x` and `100.x.x.x` addresses of my DNS servers.

Everything is using the recent 1.8.0 version of Tailscale.

Things I've tried:

- Deleting the Tailscale VPN profile from iOS settings to force a re-provision
- Reauthenticating
- Restarting the app

EDIT: it looks like Magic DNS can upset things even without an exit node enabled

**Comment by DentonGentry** [comment] 2021-05-20 12:40
Are you adding DNS server addresses from a private LAN like 192.168.1.2 to https://login.tailscale.com/admin/dns, or Tailscale IP addresses like 100.1.2.3 ?

The current exit node feature is aimed at cases where one is out in public and connected to an untrusted network like a public Wi-Fi hotspot. The assumption is that other users connected to that Wi-Fi network are completely unknown and should not be trusted, so access to the local LAN is blocked while the exit node is active.

However this doesn't match how some users want to use the feature, for example sitting in a trusted environment like the home but using the exit node feature to connect to a remote environment like an office. We're working on optionally allowing the local LAN to be active while the exit node is connected.

**Comment by eh8** [comment] 2021-05-21 01:07
I’ve added DNS servers with both types of addresses
(192.168.1.2/100.1.2.3) pointing to the same set of machines. I’ve made
sure my firewall permits port 53 traffic. Same issue persists :/

On May 20, 2021, GitHub ***@***.***> wrote:
> Are you adding DNS server addresses from a private LAN like
> 192.168.1.2 to <https://login.tailscale.com/admin/dns>, or Tailscale
> IP addresses like 100.1.2.3 ?
>
> The current exit node feature is aimed at cases where one is out in
> public and connected to an untrusted network like a public Wi-Fi
> hotspot. The assumption is that other users connected to that Wi-Fi
> network are completely unknown and should not be trusted, so access to
> the local LAN is blocked while the exit node is active.
>
> However this doesn't match how some users want to use the feature, for
> example sitting in a trusted environment like the home but using the
> exit node feature to connect to a remote environment like an office.
> We're working on optionally allowing the local LAN to be active while
> the exit node is connected.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tailscale/tailscale/issues/1887#issuecomment-
845074151>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AFPM55NAB6YOFSVYXVJXLT3TOT7NTANCNFSM44OEWXGQ>.

**Comment by maisem** [comment] 2021-05-21 18:45
@eh8 do you have Magic DNS turned on? If so, can you check if temporarily disabling Magic DNS helps?

On a separate note, you shouldn't need the 192.168.1.2 address in your dns config, that will only work if you have subnet routes enabled or if you happen to be on the same LAN. It could also lead to unexpected behavior if you're on an unknown network.
On my personal tailnet I use 100.1.2.3 and that works fine even when exit nodes are enabled.

**Comment by eh8** [comment] 2021-05-21 18:47
Yes, only the combination of exit node + private DNS + Magic DNS leads to trouble on iOS. If I disable Magic DNS I can resolve things normally.

**Comment by maisem** [comment] 2021-05-21 21:45
Ok I can repro it as well, enabling Magic DNS with Global DNS pointing to a Tailscale ip breaks DNS resolution on iOS. Don't even have to enable exit nodes.

**Comment by maisem** [comment] 2021-05-22 11:45
It's not just iOS, I was able to also repro it on NixOS and macOS.

**Comment by maisem** [comment] 2021-05-22 16:19
From what I gather, once we receive a DNS request on 100.100.100.100 we don't use the routing table anymore so all forwarding requests that should be sent to the Tailscale interface are instead being sent to the physical interface.

cc @danderson

**Comment by DentonGentry** [comment] 2021-06-16 19:22
To me this looks like netns, preventing the socket sending DNS queries from using the Tailscale namespace maybe?

**Comment by DentonGentry** [comment] 2021-06-17 04:03
Any netns issues with DNS forwarding should have been resolved by https://github.com/tailscale/tailscale/commit/6def64751446bba6914cccd51f5f4640298a3a5f

**Comment by DentonGentry** [comment] 2021-06-18 17:45
I've been assuming that this issue and https://github.com/tailscale/tailscale/issues/2102 on Android had the same root cause, but at this point we've identified https://github.com/tailscale/tailscale/issues/2102 as being very Android-specific. So this is something else.

**Comment by DentonGentry** [comment] 2021-06-18 18:06
Summarizing what we think the problem is:

- the NetworkExtension for MacOS/iOS has loop avoidance. We add routes for Tailscale IP addresses, but packets sent from within the Network Extension are not allowed to use routes added by the Network Extension.
- the DNS server involved here uses a route which was added by the Network Extension, pointing to the remote subnet relay

To fix this, we'll need to make MagicDNS consult an internal routing table to decide whether the destination is public and it should use a MacOS/iOS socket, or whether the destination is reached via Tailscale and we need to hand the packet straight to wireguard-go. Note that the check isn't just going to be for 100.64/10, #1887 concerns cases using subnet relays where non-Tailscale addresses are supposed to traverse the Tailnet.

Getting the packet sent via wireguard-go is the easier part, grabbing the responses out of wireguard-go to hand back to Magic DNS is likely to be more difficult.

**Comment by DentonGentry** [comment] 2021-06-24 00:52
Fixed by https://github.com/tailscale/tailscale/pull/2226

**Closed by DentonGentry** 2021-06-24 00:52 UTC
Labels: L2 Few, OS-ios, OS-macos, P3 Can't get started, T5 Usability, dns
