### ISSUE TITLE
FR: Allow users to access specified exit nodes with ACLs

### ISSUE THREAD

**Issue by HZ1Q** [tailscale/tailscale#4066] opened 2022-03-04 06:01 UTC
### What are you trying to do?

I have multiple exit nodes, but only want my users to be allowed to use the exit node I specify in ACLs. We have different exit nodes for different use cases in my organization and would like to limit our remote users to only the exit nodes they should be using.

Example 
exit nodes A, B, and C.
User 1, 2, and 3.

User 1 should only be allowed access to exit node A
User 2 should only be allowed access to exit node A and C
User 3 should only be allowed access to exit node A and B
user 4 should only be allowed access to exit node C

### How should we solve this?

Create ACL rules to enable specifying which users are allowed to access which exit nodes.

### What is the impact of not solving this?

Leaving a part of configuration to the remote users which allows for misconfigurations.

**Comment by DentonGentry** [comment] 2022-03-04 10:10
Could I ask what the end goal is?

Often when a request is made to control access to individual exit nodes, the use-case is for an external Software-as-a-Service vendor which needs to have a fixed IP address available which they have added to an allowlist. An exit node has been set up, and the IP address of the exit node given to the SaaS vendor to put in their allowlist. The goal of controlling access to the exit node is therefore to control access to that SaaS application.

Is it something like that?

**Comment by jakedgy** [comment] 2022-03-04 18:44
I've got that exact SaaS allowlist use-case right now as well.  Exit-node ACLs would be a big win for us.

**Comment by HZ1Q** [comment] 2022-03-04 21:10
> 

Exactly that! 
I have 2 exit nodes that are allowed to access ~120 PFSense firewalls via TCP/22 and TCP/443 and this is the only allowed outbound connection from the exit nodes other than to update services. I have a dedicated exit node for user VPN and will likely implement another soon.

**Comment by mayakacz** [comment] 2022-03-04 21:17
Closing as a dupe of https://github.com/tailscale/tailscale/issues/1748

**Closed by mayakacz** 2022-03-04 21:17 UTC
Labels: needs-triage, fr

**Comment by DentonGentry** [comment] 2022-03-04 22:31
For SaaS allowlisting, I understand the thought to use an exit node: it is clear how an exit node will set the source IP address. However, exit nodes aren't otherwise a great fit for this, as you have to send all traffic not just the SaaS provider traffic.

We recommend a different solution for SaaS allowlisting: when you use `--advertise-routes=...`, they don't have to be **your** routes. You can advertise any IP address, even public IP addresses, like for example the public IP address of your SaaS provider:
`tailscale up --advertise-routes=1.2.3.4/32,1.2.3.5/32`
You can then use ACLs to limit who is allowed to access the public IP address of the SaaS provider.

**Comment by HZ1Q** [comment] 2022-03-09 14:24
> 

Denton,

Thank you for this extremely informative reply! I had no idea we could advertise routes that are not our own, and I have confirmed this meets requirements for what I need! I'm currently building this out in my infrastructure! 
Thanks again!!
