### ISSUE TITLE
tailscale on Synology DSM 7 dns still not working == RESOLVED

### ISSUE THREAD

**Issue by IcarusR** [tailscale/tailscale#12498] opened 2024-06-16 17:54 UTC
### What is the issue?

Unable to resolve tailscale full domain addresses. This is due to tailscale user not having privilages to re-write /etc/resolv.conf 
Numerous bugs have been filed, but all closed saying resolved, but without a resolution so tailscale is will not resolve magicdns  on DSM 7

Relevant log entry
ignoring SetDNS permission error on Synology (Issue 4017); was: rename /etc/resolv.conf /etc/resolv.pre-tailscale-backup.conf: permission denied

### Steps to reproduce

Install tailscale on DSM 7 
start service

### Are there any recent changes that introduced the issue?

No

### OS

Synology

### OS version

Synology DSM 7

### Tailscale version

1.68.0-700068000

### Bug report

BUG-1caf71ea7be433ab07e671b06f052057491b571ee4dd70eeb1f024969ea5c670-20240616175052Z-7b9a893be24c0f56

**Comment by BernardTeske** [comment] 2024-08-09 20:50
Same Problem. Any news? Can't reach my devices in other networks. Tried the magic dns 100.100.100.100 as an alternate dns. Did not work...

**Comment by sbourdette** [comment] 2024-08-27 07:22
Same here

**Comment by AlisaCat-S** [comment] 2024-08-28 13:05
Same here.

**Comment by monocodes** [comment] 2024-09-02 22:06
Same here.
I'm trying to reach `ts-exit-node-eu-de-w10-a.*****-****.ts.net` from Synology itself with no success. My Synology is a Subnet router to home LAN btw.

**Comment by pjdubya** [comment] 2024-10-05 23:19
Same here too. I can ssh into my DSM7 NAS using the magic DNS FQDN but when I'm in that ssh session and nslookup that same FQDN I get a response from my local gateway (not 100.100.100.100) that gives me the IP for ingress-nyc-01.tailscale.com rather than the expected 100.x.x.x IP for that node. If I nslookup other FQDN that are valid like the name of the machine I'm ssh'ing in from, it can't find it, NXDOMAIN, again because it's asking the local gateway and not 100.100.100.100.

In my DSM6 NAS, I can nslookup all of my nodes and get 100.x.x.x IP responses back as expected.

**Comment by jimmybrancaccio** [comment] 2024-10-09 19:57
This may be a duplicate of #3602 or at least related.

**Comment by yenba** [comment] 2024-10-13 22:17
Just wanted to add a "same here".

**Comment by pjdubya** [comment] 2024-10-15 01:04
For those who still need a solution, give this a shot: https://github.com/tailscale/tailscale/issues/3602#issuecomment-2412611986

**Comment by IcarusR** [comment] 2024-10-19 21:25
@pjdubya has the solution that works for me at present, till Synology break that as well. Thanks

**Comment by IcarusR** [comment] 2024-10-19 21:27
@pjdubya has the solution that works for me at present, till Synology break that as well. Thanks

**Comment by IcarusR** [comment] 2024-10-28 18:20
@pjdubya with your fix I loose Quickconnect when tailscale is running. This means Synology apps will not connect.
I guess you can not have it all ways !!

**Comment by ukanuk** [comment] 2024-12-29 14:19
Who is supposed to close resolved issues like this one? Maybe @bradfitz who is listed at https://github.com/orgs/tailscale/people and started #1995?

**Comment by bradfitz** [comment] 2024-12-29 17:23
Closing as dup of #3602

**Closed by bradfitz** 2024-12-29 17:23 UTC
Labels: OS-linux, dns, OS-synology, bug, support
