### ISSUE TITLE
Windows: suddenly logged out, "tailscale is stopped", "tailscale up" and login doesn't fix it

### ISSUE THREAD

**Issue by colemickens** [tailscale/tailscale#3567] opened 2021-12-15 00:01 UTC
### What is the issue?

Oh no indeed. I got back from a walk, tailscale icon is missing in systray, connectivity is down.

Windows Services thinks its running.

`tailscale up` allows me to re-auth, but then `tailscale status` still just says its down.

Something bad happened. Please send help.

### Steps to reproduce

No idea.

### Are there any recent changes that introduced the issue?

Not on my end.

### OS

Windows

### OS version

Windows 11 22000.376

### Tailscale version

tailscale commit: 22d9699759fa34247153a542e9c4af5696c01fdf

### Bug report

BUG-bfefe0c1b08ef8f3e50c08611d06e69f106a2eacb15a58275b38151e4df9b2fd-20211215000139Z-b975da5a355b6209

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_40rpt)

**Comment by colemickens** [comment] 2021-12-15 00:06
(random, but it would increase my confidence around this process if I could see what is included in the report that corresponds to that BUG-... identifier)

**Comment by DentonGentry** [comment] 2021-12-15 00:16
`tailscale bugreport` adds the string BUG-bfefe0c1b08ef8f3e50c08611d06e69f106a2eacb15a58275b38151e4df9b2fd-20211215000139Z-b975da5a355b6209 to the telemetry, so that we can be absolutely clear on the timestamp of where the reporter considered there to be a problem.

Unfortunately this is all we're getting:
```
2021-12-14 14:22:40.4075052 -0800 PST: Program starting: v1.18.0-t22d969975-g7022e5a4c, Go 1.17.2-ts7037d3ea51: []string{"C:\\Program Files (x86)\\Tailscale IPN\\tailscaled.exe"}
2021-12-14 14:22:40.4075052 -0800 PST: LogID: X
2021-12-14 14:22:40.4075052 -0800 PST: logpolicy: using dir C:\ProgramData\Tailscale
2021-12-14 14:22:40.4075052 -0800 PST: Running service...
2021-12-14 14:22:40.4175796 -0800 PST: exec: "C:\\Program Files (x86)\\Tailscale IPN\\tailscaled.exe" [/subproc X]
2021-12-14 14:22:40.449345 -0800 PST: logtail: dialed "log.tailscale.io:443" in 27ms
2021-12-14 15:58:10.1319086 -0800 PST: subprocess exited: exit status 1
2021-12-14 15:58:10.132414 -0800 PST: exec: "C:\\Program Files (x86)\\Tailscale IPN\\tailscaled.exe" [/subproc X]
2021-12-14 15:58:10.1581854 -0800 PST: logtail: dialed "log.tailscale.io:443" in 17ms
2021-12-14 15:58:12.7436517 -0800 PST: subprocess exited: exit status 1
2021-12-14 15:58:12.7528712 -0800 PST: exec: "C:\\Program Files (x86)\\Tailscale IPN\\tailscaled.exe" [/subproc X]
```

Which isn't very informative.

In C:\ProgramFiles\Tailscale\Logs there will probably be some text files. Could you open the one with the youngest timestamp and look around near the bottom of the file? What is it saying is wrong?

If not comfortable pasting it into a public bug report, you can email it to support@tailscale.com and reference bug 3567.

**Comment by colemickens** [comment] 2021-12-15 00:22
I don't have that dir. Did you maybe mean `%APPDATA%\Tailscale`? I have some things here?

They're all 0kb though, presumably from tailscaled.exe running. Shall I stop the Windows Service and then see if these log files are openable?

**Comment by DentonGentry** [comment] 2021-12-15 00:26
Sorry: `C:\ProgramData\Tailscale\Logs`

The log files are likely a few megabytes, just the last few lines of the most recent one will likely be informative of what it is doing.

**Comment by colemickens** [comment] 2021-12-15 00:31
uhhhh, yeah.... see attached
[tailscale-service-20211214T155816-1639526296.txt](https://github.com/tailscale/tailscale/files/7715608/tailscale-service-20211214T155816-1639526296.txt)

**Comment by colemickens** [comment] 2021-12-15 00:32
I really, really wish Tailscale would just leave my DNS alone. Really, I can manage it.

**Comment by bradfitz** [comment] 2021-12-15 00:34
There's an option for that. But is that related to this issue?

**Comment by colemickens** [comment] 2021-12-15 00:37
I don't know. It was sort of a reactive comment from seeing the error/spew from trying to call wsl.exe for what seems like doing DNS stuff.

**Comment by colemickens** [comment] 2021-12-15 00:39
Is this a dupe of https://github.com/tailscale/tailscale/issues/3170 ?

**Comment by bradfitz** [comment] 2021-12-15 00:42
That wsl.exe error/spew is fixed in the latest builds (not yet released to the stable branch).

> Oh no indeed. I got back from a walk, tailscale icon is missing in systray, connectivity is down.
>
> Windows Services thinks its running.

When Tailscale on Windows is not running in "Run Unattended" mode, the service shuts down when the GUI disconnects.

So if your systray icon is gone, which I see it is, then the Tailscale service shuts down by design (but stays running, idle):

```
2021-12-14T15:58:53.582-08:00: Switching ipn state Starting -> Running (WantRunning=true, nm=true)
2021-12-14T15:58:53.583-08:00: ipnserver: conn8: ReadMsg: read tcp 127.0.0.1:41112->127.0.0.1:62516: wsarecv: An existing connection was forcibly closed by the remote host.
2021-12-14T15:58:53.583-08:00: client disconnected; stopping server
2021-12-14T15:58:53.583-08:00: LocalBackend.ResetForClientDisconnect
```

So the question is why the system tray GUI app shut down.

**Comment by bradfitz** [comment] 2021-12-15 00:43
Can you search your log directory and look for your `FrontendLogID` value? Some big hex thing.

**Comment by bradfitz** [comment] 2021-12-15 00:44
> Is this a dupe of #3170 ?

Not really. That was already fixed (coming out soon), but that's just cosmetic in this bug. It's making your logs ugly, but it's not the problem.

**Comment by bradfitz** [comment] 2021-12-15 00:50
By chance, when you came back from your walk, was Windows in the middle of an aborted upgrade reboot attempt that some app blocked due to unsaved work?

**Comment by colemickens** [comment] 2021-12-15 00:50
```
PS C:\Users\colem> findstr /i "FrontendLogID" C:\Users\colem\AppData\Local\Tailscale
PS C:\Users\colem> findstr /i "FrontendLogID" C:\ProgramData\Tailscale\Logs
PS C:\Users\colem> findstr /i "FrontendLogID" C:\ProgramData\Tailscale
PS C:\Users\colem>
```

Oh dear, oof, I'm sorry - I just remembered. I had 60GB+ of stuff in `C:\Users\colem\Temp\` that I forcibly (admin PS, `Remove-Item -Recurse -Force -Confirm:$false` style) cleared out ~60-90 minutes ago probably. I'm going to guess that I deleted something that the tray wanted.

Given that, feel free to close this unless you want proof or further data.

**Comment by bradfitz** [comment] 2021-12-15 00:55
From memory and from grepping around just now, I don't think anything in the GUI systray app depends on `Temp`.

I broke part of our Windows logging in 1.18.0 so I'm debugging a bit blind right now. Normally `tailscale bugreport` is useful to let us see what's happening, but it's not right now. (a 1.18.2 is coming out very soon fixing the Windows logging among other things)

If you start the Windows GUI again, does it all work? It looks like 100.96.145.20 is still not connected again.

**Comment by colemickens** [comment] 2021-12-15 00:58
Heh, I'd tried restarting the Windows Service, but never tried just relaunching the app. For some reason I assume the Service spawned the tray. Anyway, as you can probably see now, simply starting "Tailscale" from the Start Menu fixed it.

(I did have to re-auth one final time though, maybe I managed to kill the cookie or it got culled during this mixup?)

**Comment by DentonGentry** [comment] 2021-12-15 13:12
Could be.

**Closed by DentonGentry** 2021-12-15 13:12 UTC
Labels: needs-triage, bug
