### ISSUE TITLE
Tailgate on Synology DSM 7 prevents HDD to go to sleep

### ISSUE THREAD

**Issue by roxiruda** [tailscale/tailscale#4344] opened 2022-04-02 15:31 UTC
### What is the issue?

As can be seen in multiple blog post and discussions, activating the Tailgate package on DSM 7 will prevent the HDDs from going to sleep. As soon as I disable the Tailscale package, my HDDs go back to sleep after i.e. 15 minutes. 

A bug fix would be much appreciated as I don't want my HHDs to run 24/7 due to Tailscale being active. 

THANKS!

### Steps to reproduce

Install and activate Tailscale package on DSM 7 via Package Manager.

### OS

Synology

### OS version

DSM 7

### Tailscale version

latest available on Package Manager

**Comment by DentonGentry** [comment] 2022-04-02 15:32
I'm assuming Tailgate == Tailscale
Duplicate of https://github.com/tailscale/tailscale/issues/3551

**Closed by DentonGentry** 2022-04-02 15:32 UTC
Labels: needs-triage, bug
