### ISSUE TITLE
DNS resolution going to ISP nameservers even with "override DNS" enabled

### ISSUE THREAD

**Issue by lincolnmantracer** [tailscale/tailscale#4616] opened 2022-05-05 16:18 UTC
### What is the issue?

We have "override DNS" enabled pointing to GCP's local DNS (forwarded by a subnet relay), and split DNS turned off (but we had it turned on, and there was the same issue). Name resolution for our internal DNS zone works on on my machine, but not my coworker's.

I have the following:
```
scutil --dns
DNS configuration

resolver #1
  search domain[0] : home
  nameserver[0] : 169.254.169.254
  if_index : 19 (utun4)
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 102000

resolver #2
  nameserver[0] : 10.0.0.1
  if_index : 11 (en0)
  flags    : Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  order    : 200000
```

And resolution works fine (with the answer coming from google's `169`).

But my coworker has ISP DNS coming through (telus, in Canada):

```
resolver #1
  nameserver[0] : 169.254.169.254
  if_index : 15 (utun4)
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 102600

resolver #2
  nameserver[0] : 2001:568:ff09:10c::68
  nameserver[1] : 2001:568:ff09:10b::124
  nameserver[2] : 192.168.1.254
  if_index : 4 (en0)
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)
  order    : 200000
```

Asking google directly from my coworker's machine works fine (`dig example.com @169.254.169.254`), as does `dscacheutil -q host -a name example.com`, but `dig`, and at least go's resolver, ask the ipv6 nameserver instead of tailscale:

```
$ dig example.com

; <<>> DiG 9.10.6 <<>> example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 15492
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;example.com.			IN	A

;; Query time: 510 msec
;; SERVER: 2001:568:ff09:10c::68#53(2001:568:ff09:10c::68)
;; WHEN: Thu May 05 09:07:13 PDT 2022
;; MSG SIZE  rcvd: 38
```

Confusingly, this issue just appeared suddenly - DNS resolution was working fine and then abruptly stopped working.

### OS

macOS

### OS version

10.15.7 Catalina (!!) (coworker's machine)

### Tailscale version

1.24.2 (coworker's machine)

### Bug report

BUG-4a9ff88f9ea57f000854fac125f1e7286ece3e7e9893a857aba328c18f93808a-20220505161709Z-b9557b187d3e08b6 (my machine, they don't have the tailscale cli)

**Comment by lincolnmantracer** [comment] 2022-05-05 16:26
I got to the end of the bug report before I realized my coworker is running Catalina... it feels like that could be the problem. Feel free to close if that sounds right.

**Comment by DentonGentry** [comment] 2022-05-07 16:37
Catalina should work, though might be part of the behavioral differences noted. The App Store is set to only allow installation on macOS versions where the app is expected to work.

**Comment by DentonGentry** [comment] 2022-05-12 11:34
Duplicate of https://github.com/tailscale/tailscale/issues/4499

**Closed as completed by DentonGentry** 2022-05-12 11:34 UTC
Labels: OS-macos, L2 Few, P2 Aggravating, T5 Usability, bug
