### ISSUE TITLE
Hostname detected as localhost-0 on android

### ISSUE THREAD

**Issue by kd5pev** [tailscale/tailscale#10292] opened 2023-11-16 21:31 UTC
### What is the issue?

Appears to be a duplicate of #7875
Tailscale Version 1.52.0
Android 14

### Steps to reproduce

Upon logging in after logging out the hostname is detected as localhost.
Same as #7875

### OS

Android

### OS version

14

### Tailscale version

1.52.0

### Bug report

BUG-a558834fa14bf62fe3c7653fc42764ee5f273293a7a2814c3a101b5f5012af3-20231116212855Z-9bb54a0d566d1e7

**Comment by DentonGentry** [comment] 2023-11-16 22:51
Duplicate of https://github.com/tailscale/tailscale/issues/7875

**Closed by DentonGentry** 2023-11-16 22:51 UTC
Labels: needs-triage, bug
