### ISSUE TITLE
FR: VPN On Demand for iOS customize hostname matching

### ISSUE THREAD

**Issue by Morpheus8** [tailscale/tailscale#8930] opened 2023-08-17 09:27 UTC
### What are you trying to do?

The new VPN on demand feature on iOS is great. VPN On Demand automatically connect Tailscale when iOS detects a connection to a hostname that ends in `*.ts.net`. Here I would like to customize the URL to trigger the VPN. When I try to reach a Server in my HomeLAN behind the subnet router I need a trigger like this `*.home.lan` as example.

### How should we solve this?

Make the trigger URL `*.ts.net` customizable

### What is the impact of not solving this?

I can't automatically establish a VPN connection when I try to reach a server behind a subnet router.

### Anything else?

https://tailscale.com/kb/1291/ios-vpn-on-demand/#using-magicdns-hostname-matching

**Comment by DentonGentry** [comment] 2023-08-17 10:57
Duplicate of https://github.com/tailscale/tailscale/issues/8915

Is home.lan configured as a SplitDNS domain, or a Search Domain, in https://login.tailscale.com/admin/dns ?
I ask because we try to avoid adding extra configuration knobs, if the defaults can be made more applicable using configuration information which already exists.

**Comment by Morpheus8** [comment] 2023-08-17 11:20
Yes `home.lan` is configured as SplitDNS and Search Domain. But iOS VPN on demand doesn't get triggered with anything configured in SplitDNS or Search Domain. iOS just trigger the VPN Tunnel with `*.ts.net `hostnames.

**Comment by DentonGentry** [comment] 2023-08-24 05:59
Duplicate of https://github.com/tailscale/tailscale/issues/8915

**Closed by DentonGentry** 2023-08-24 05:59 UTC
Labels: needs-triage, fr
