### ISSUE TITLE
FR: Tailscale unique ID is duplicated when restored by timemachine

### ISSUE THREAD

**Issue by bsnresearcher** [tailscale/tailscale#10914] opened 2024-01-21 04:16 UTC
### What are you trying to do?

I restored my data from old mac PC to new PC by timemachine backup.

Then, the one login was exclusive between New and old PC.

That is to say, If new PC login to tailscale, the old pc was forced logout. On the other hand, If old PC login to tailscale, the new pc was forced logout.

### How should we solve this?

I had to start the PC setup all over again.

### What is the impact of not solving this?

Very Important. The setup is very heavy, A lot of time was consumed.

### Anything else?

I want to tell me about renewal method of tailscale login UUID(?).

**Comment by DentonGentry** [comment] 2024-01-21 04:18
Duplicate of https://github.com/tailscale/tailscale/issues/506

**Closed by DentonGentry** 2024-01-21 04:18 UTC
Labels: needs-triage, fr

**Comment by bsnresearcher** [comment] 2024-01-21 04:32
Thank you very much.
