### ISSUE TITLE
FR: Bypass blocking of the domain 

### ISSUE THREAD

**Issue by dolceAlka** [tailscale/tailscale#12634] opened 2024-06-27 04:31 UTC
### What are you trying to do?

Some networks will block tailscale.com for whatever reasons they have, meaning that tailscale cannot go online because message with the control server is blocked.

### How should we solve this?

1. Possibly have a semi-online mode where endpoints of devices on the tailnet are cached
2. fwmark/whatever other routing differentiator on the OS it's on the packets that go to controlplane.tailscale.com to make it routable via some user-defined proxying
3. Allow settings an HTTP proxy for this (potentially already covered under featureset)

### What is the impact of not solving this?

Common networks such as public wifi blocking tailscale.com will mean unusability

**Comment by bradfitz** [comment] 2024-06-27 05:07
(1) is already planned

(3) is already possible. Tailscaled should respect proxy env vars and windows settings.

So I think this is basically a duplicate.

**Comment by dolceAlka** [comment] 2024-06-27 06:29
Personally I'd like to see 2 implemented for more options in freedom, especially because it seems nothing special is being done with the DNS/coordination side of tailscaled like routing it through the exit node.

**Comment by bradfitz** [comment] 2024-06-27 14:50
For (1), I filed https://github.com/tailscale/tailscale/issues/12639 because I realized we didn't have a public issue about this yet. Or at least not one that stated it so explicitly.

(2) is very OS specific and most OSes don't permit that. And it's a testing / Linux compatibility matrix nightmare. We won't be doing (2).

If you find a bug about (3) not working, feel free to open a new bug with details about that.

But otherwise I'd like to close this bug as effectively a dup of #12639

**Closed by bradfitz** 2024-06-27 14:50 UTC
Labels: needs-triage, fr

**Comment by dolceAlka** [comment] 2024-06-27 15:06
> For (1), I filed #12639 because I realized we didn't have a public issue about this yet. Or at least not one that stated it so explicitly.
> 
> (2) is very OS specific and most OSes don't permit that. And it's a testing / Linux compatibility matrix nightmare. We won't be doing (2).
> 
> If you find a bug about (3) not working, feel free to open a new bug with details about that.
> 
> But otherwise I'd like to close this bug as effectively a dup of #12639

Thanks for addressing that on point 2, it's very much an issue for cross platform. To clarify, is the http_proxy environment variable for the wireguard connections too? There doesn't seem to be much if any documentation on it. I've tried it out and it seems that only http connections on tailnet nodes are reachable and not other traffic like icmp. Either the entire wireguard connection is getting weirdly proxied through TCP/UDP layers in which pinging icmp should work, or the http_proxy just makes connection to tailnet devices proxied over the socks proxy which would explain why icmp is not going through.

**Comment by dolceAlka** [comment] 2024-06-28 05:21
I'm just stupid, it was ACL issues

**Comment by GustavoWidman** [comment] 2024-10-17 12:54
In my case, the controlplane domain is blocked network-wide and HTTP/SOCKS5 proxy usage doesnt seem to resolve it (even though if i access it through the browser using my proxy it works just fine). Is this intentional? I also tried running tailscaled inside proxychains to no avail. If the controlplane is blocked is there really nothing I can do about it?

**Comment by GustavoWidman** [comment] 2024-10-25 19:00
iirc the caching/semi-online mode is working as intended when the controlplane is not reachable but DERPs and other devices are, tailscale now shows this on tailscale status only if you are in the semi-online mode:
`
100.x.x.x   laptop-arch          gustavowidman@ linux   offline
100.x.x.x  desktop-windows      gustavowidman@ windows -

# Health check:
#     - Unable to connect to the Tailscale coordination server to synchronize the state of your tailnet. Peer reachability might degrade over time.
`

**Comment by bulutthecat** [comment] 2024-10-25 19:20
> iirc the caching/semi-online mode is working as intended when the controlplane is not reachable but DERPs and other devices are, tailscale now shows this on "tailscale status" only if you are in the semi-online mode:
> 
> ```
> 100.x.x.x   laptop-arch          gustavowidman@ linux   offline
> 100.x.x.x  desktop-windows      gustavowidman@ windows -
> 
> # Health check:
> #     - Unable to connect to the Tailscale coordination server to synchronize the state of your tailnet. Peer reachability might degrade over time.
> ```
> 
> here is the netcheck result
> 
> ```
> Report:
> 	* UDP: true
> 	* IPv4: yes, a.b.c.d:e
> 	* IPv6: no, but OS has support
> 	* MappingVariesByDestIP: false
> 	* PortMapping: 
> 	* CaptivePortal: true
> 	* Nearest DERP: São Paulo
> 	* DERP latency:
> 		- sao: 11.8ms  (São Paulo)
> 		...
> ```

This does work, but services on remote systems are not reachable still from cold launching tailscale on a blocked network.. (RDP, SMB, HTTP/S, etc..)
