### ISSUE TITLE
net/dns: MagicDNS can get in traffic loop with misconfigured systemd-resolved

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4955] opened 2022-06-28 02:59 UTC
In ticket http://go/hs/3222, user (running 1.26.1) had a systemd-resolved reporting:

```
2022-06-26 21:15:59.711633578 +0000 UTC: dns: resolvedIsActuallyResolver error: resolv.conf doesn't point to systemd-resolved; points to [8.8.8.8 8.8.4.4 1.1.1.1 127.0.0.53]
2022-06-26 21:15:59.711671174 +0000 UTC: dns: [resolved-ping=yes rc=resolved resolved=not-in-use ret=direct]
2022-06-26 21:15:59.711692971 +0000 UTC: dns: using *dns.directManager
```

... and whenever MagicDNS was enabled, CPU went to nearly 100% and DNS queues got full, presumably in a packet loop with systemd-resolved.

The system was misconfigured but we should try to behave a bit better if possible.

/cc @danderson @twitchyliquid64

**Comment by DentonGentry** [comment] 2023-06-03 16:02
Duplicate of https://github.com/tailscale/tailscale/issues/2729

**Closed by DentonGentry** 2023-06-03 16:02 UTC
Labels: OS-linux, dns, needs-fix
