### ISSUE TITLE
Tailscaled fails to start after updating to Ver 1.18.0 (arm32) [when IP_MULTIPLE_TABLES is not set]

### ISSUE THREAD

**Issue by apocnz** [tailscale/tailscale#3351] opened 2021-11-19 10:37 UTC
### What is the issue?

Tailscale fails to start with version 1.18.0 (arm32 linux)

### Steps to reproduce

Running tailscaled from cli/console produces the following

```
Program starting: v1.18.0-t22d969975-g7022e5a4c, Go 1.17.2-ts7037d3ea51: []string{"tailscaled", "-tun", "tailscale0"}
LogID: d08b1955d71bacd9a9c60294120db178bcb58730919f538c76aaff1277cd740a
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
router: disabling tunneled IPv6 due to system IPv6 config: kernel doesn't support IPv6 policy routing: operation not supported
dns: [rc=unknown ret=direct]
dns: using *dns.directManager
link state: interfaces.State{defaultRoute=eth0 ifs={eth0:[192.168.0.101/24 192.168.88.88/24]} v4=true v6=false}
magicsock: disco key = d:2851c9d8f76971fc
Creating wireguard device...
Bringing wireguard device up...
Bringing router up...
external route: up
wgengine.NewUserspaceEngine(tun "tailscale0") error: operation not supported
wgengine.New: operation not supported
flushing log.
logger closing down
logtail: dialed "log.tailscale.io:443" in 291ms
```

### Are there any recent changes that introduced the issue?

Updated from 1.16.2_arm to 1.18.0_arm

### OS

Linux

### OS version

Custom Linux distro, based on Kernel 3.18.20

### Tailscale version

1.18.0_arm

**Comment by bradfitz** [comment] 2021-11-19 16:53
Hm, mystery. I read through the code & the changes and I'm not seeing the issue.

But I sent https://github.com/tailscale/tailscale/pull/3355 to make it more clear in the error messages which initialization path is generating the error.

We'll roll an unstable build with that change and that should point us toward where the problem is.

**Comment by bradfitz** [comment] 2021-11-19 16:55
Does it work if you run `tailscaled` with the `TS_DEBUG_USE_IP_COMMAND=1` environment variable set?

**Comment by apocnz** [comment] 2021-11-19 17:25
Hi Brad, 

> Does it work if you run `tailscaled` with the `TS_DEBUG_USE_IP_COMMAND=1` environment variable set?

Setting the TS_DEBUG_USE_IP_COMMAND=1 env variable does the trick.  Does that give any clue on cause ?

**Comment by bradfitz** [comment] 2021-11-19 17:30
Indeed, that helps. I'm temporarily even more confused now, but I know exactly where the problem is at least.

**Comment by bradfitz** [comment] 2021-11-19 17:56
Testing on a linux/arm Raspberry Pi, hoping I can repro there.

So far it works, though. But the Pi's kernel & network has IPv6, so I'll try disabling that next.

**Comment by bradfitz** [comment] 2021-11-19 17:58
Well, disabling IPv6 with the sysctl might be too graceful. We detect that early and it works:

```
Program starting: v1.18.0-t22d969975-g7022e5a4c, Go 1.17.2-ts7037d3ea51: []string{"tailscaled"}
LogID: 73a672a72e5e32fc16eb927e3bcfae3ae6c840640c791f9be24a271c56860a40
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
router: disabling tunneled IPv6 due to system IPv6 config: disable_ipv6 is set
dns: [rc=resolvconf resolvconf=openresolv ret=openresolv]
dns: using dns.openresolvManager
link state: interfaces.State{defaultRoute=eth0 ifs={eth0:[10.0.0.36/16]} v4=true v6=false}
magicsock: disco key = d:e4922d466e3544b9
Creating wireguard device...
Bringing wireguard device up...
Bringing router up...
external route: up
logtail: dialed "log.tailscale.io:443" in 20ms
Clearing router settings...
Starting link monitor...
Engine created.
netmap packet filter: (not ready yet)
Start
using backend prefs
```

**Comment by bradfitz** [comment] 2021-11-19 18:27
@apocnz, so far I can't repro, and we have hundreds of users who are already running 1.18.0 on linux/arm devices with Linux kernels as far back as 3.2.40.

If there was stuff missing in your kernel config, I don't see how the `ip` command would still be working. (btw: is it busybox or somthing?)

In any case, we want to figure this out.

Can you share your kernel config?

**Comment by apocnz** [comment] 2021-11-19 18:38
Yes its busybox., 

I'm just digging into the kernel config now to check (but fair point, ip works ...).  
Going to crank out a new compile of the kernel and see if that does the trick.

**Comment by bradfitz** [comment] 2021-11-19 18:59
We think we know the issue.

I suspect you're missing `IP_MULTIPLE_TABLES` (which depends on `IP_ADVANCED_ROUTER`)

**Comment by apocnz** [comment] 2021-11-19 19:06
Hit the nail on the head. Compiling out a kernel with those two tidbits.  
Thanks guys.

**Comment by bradfitz** [comment] 2021-11-19 19:07
I sent https://github.com/tailscale/tailscale/pull/3357 to fix it so it'll still start & run without `IP_MULTIPLE_TABLES` and instead warn that you really want `IP_MULTIPLE_TABLES`.  But we shouldn't require it.

**Comment by apocnz** [comment] 2021-11-19 19:22
Not sure if this complicates this...  but still no go after compiling the kernel with ADVANCED_ROUTING and IP_MULTIPLE_TABLES, although different outcome..

```
~ # tailscaled
logtail started
Program starting: v1.18.0-t22d969975-g7022e5a4c, Go 1.17.2-ts7037d3ea51: []string{"tailscaled"}
LogID: b10ed03a358cdfa9efe37d3b6473d632a8a08a2fe73d1c8bb6fe46e61ff3357e
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
router: v6nat = true
dns: [rc=unknown ret=direct]
dns: using *dns.directManager
link state: interfaces.State{defaultRoute=eth0 ifs={eth0:[192.168.0.103/24]} v4=true v6=false}
magicsock: disco key = d:1c854117645f437d
Creating wireguard device...
Bringing wireguard device up...
Bringing router up...
external route: up
wgengine.NewUserspaceEngine(tun "tailscale0") error: address family not supported by protocol
wgengine.New: address family not supported by protocol
flushing log.
logger closing down
logtail: dialed "log.tailscale.io:443" in 298ms
```

**Comment by bradfitz** [comment] 2021-11-19 19:28
@apocnz, now I think you're hitting #3358 which #3359 should fix.

I guess you also don't have IPv6 in your kernel :)

**Comment by apocnz** [comment] 2021-11-19 19:56
Funny enough mine did that with IPv6 enabled in the kernel. Removed Ipv6 support and its happy as now,

**Comment by bradfitz** [comment] 2021-11-19 21:19
Okay, 1.19.10 is built now for unstable at https://pkgs.tailscale.com/unstable/ (which is effectively 1.18.0 with these fixes). Can you try that and see if it works now?

**Comment by charlieporth1** [comment] 2021-11-20 02:14
I'm having this issue as well

**Comment by DentonGentry** [comment] 2021-11-20 02:18
@charlieporth1 does 1.19.10 from the unstable track https://pkgs.tailscale.com/unstable/  work?

**Comment by bradfitz** [comment] 2021-11-20 02:24
Also, out of curiosity: what distro, kernel version, kernel config, etc?

**Comment by charlieporth1** [comment] 2021-11-20 04:06
ASUS tinker board however it also happens on a GCP instance along with tailscale improperly replacing rapidly and repidedly  /etc/resolv.conf on GCP and bear metals ubuntu x86 and making dns useable 
This is the tinkerboard 
```
uname -a
Linux neat-xylophone 4.14.98-imx #1 SMP PREEMPT Wed Jul 1 02:33:43 UTC 2020 aarch64 GNU/Linux
The programs included with the Mendel GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Mendel GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
```

**Comment by DentonGentry** [comment] 2021-11-20 04:09
@charlieporth1 if you can send the Tailscale IP address of either the GCP instance or the Ubuntu machine to support@tailscale.com we can look into what is happening with /etc/resolv.conf

**Comment by charlieporth1** [comment] 2021-11-20 04:09
Sure! Huge thanks for this help

**Comment by bradfitz** [comment] 2021-11-20 04:47
We'll release a 1.18.1 early next week probably, cherry-picking the fix for this.

In the meantime, if anybody else hits this, use 1.19.x (unstable).

**Comment by apocnz** [comment] 2021-11-20 05:10
Cheers.  Did another compile of kernel, IPV6 was missing policy routing, now runs 1.18.0 happily.  
Thanks again

**Comment by jswinner** [comment] 2021-11-21 19:14
Same issue, back to 1.16.2 until next stable
Linux 4.9.182-armada375 #1 SMP Thu Jun 20 10:57:36 CEST 2019 armv7l GNU/Linux

**Comment by bradfitz** [comment] 2021-11-21 23:17
@jswinner, what Linux distro and kernel config? Does 1.19.10 also fix it for you?

**Comment by bradfitz** [comment] 2021-11-22 21:59
1.18.1 is now out with the fix. Somebody else want to confirm that it now fixes it?

**Comment by jswinner** [comment] 2021-11-23 00:52
Yes confirmed, fixed my issue on Debian 9 w/o IP_MULTIPLE_TABLES set

**Comment by bradfitz** [comment] 2021-11-23 01:45
Thanks!

**Closed by bradfitz** 2021-11-23 01:45 UTC
Labels: OS-linux, L2 Few, P5 Halts deployment, T8 Crash, bug
