### ISSUE TITLE
ACL: Tests for "autogroup:members" incorrectly include external users

### ISSUE THREAD

**Issue by kelivel** [tailscale/tailscale#5931] opened 2022-10-13 21:14 UTC
### What is the issue?

HS # 5909

User wrote an ACL deny test to confirm an external user can't see a node that _isn't_ shared with them. External users can only connect to nodes explicitly shared with them so this test should have passed. However, the user also had a line that accepted all connections to the node from autogroup:members. 

The ACL test denying the shared user access fails as long as `autogroup:members` are allowed to reach the node. ACL `autogroup:members` should only include direct tailnet members.

### Steps to reproduce

1. Write ACL to allow autogroup:members access to a node (not shared with external user)

		{
			"action": "accept",
			"src":    ["autogroup:members"],
			"dst":    ["*:*"],
		},
3. Write a "deny" test against an external user ("user@email.com")
```
	"tests": [{"src": "user@email.com", "deny": ["100.90.158.24:5000"]},
```
4. Try to save changes

![image](https://user-images.githubusercontent.com/104461838/195698481-1e5014bb-e24f-427d-af93-e0ba54983f30.png)

**Expected**: Test passes because the external user doesn't have shared access to the node

**Current behavior**: Test fails with error that test was accepted and not dropped

**Comment by bradfitz** [comment] 2022-10-14 04:17
cc @maisem

**Comment by DentonGentry** [comment] 2023-05-01 12:05
Duplicate of https://github.com/tailscale/tailscale/issues/4558

**Closed by DentonGentry** 2023-05-01 12:05 UTC
Labels: admin UI, L3 Some users, P2 Aggravating, T5 Usability, bug
