### ISSUE TITLE
Tailscale fails keeps trying to use ethernet connection, not connected to the internet

### ISSUE THREAD

**Issue by MaxwellHogan** [tailscale/tailscale#12353] opened 2024-06-05 07:00 UTC
### What is the issue?

My situation may be unique however, it is worth recording as I believe I am not alone with this phenomenon,

I am connected to the internet via wifi on my windows 10 machine,

In addition I am have a wireless hub connected to an ethernet port on my machine - this hub is not connected to the internet, it is used for me to connect to other devices around my lab. 

When the wireless connection is made, Tailscale does not work at all, it appears it is trying to use this connection. 

it could be an IP issue also - the hub uses 192.168.1.1 (so all devices on this connection are 192.168.1.XX)

I feel a solution would be for me to be able to block tailscale from using this specific ethernet interface but unsure how to do this or if it is supported. 

### Steps to reproduce

Windows 10 PC 22H2
have a wifi connection to internet 
have a ethernet connection to a local network 

### Are there any recent changes that introduced the issue?

I don't believe so 

### OS

Windows

### OS version

Windows 10 PC 22H2

### Tailscale version

1.66.4

### Other software

VScode remote desktop <- typically what I use tailscale with

**Comment by timtailscale** [comment] 2024-07-03 17:02
Duplicate of #1552

**Closed by timtailscale** 2024-07-03 17:02 UTC
Labels: needs-triage, bug

**Comment by jradxl** [comment] 2024-09-16 12:06
I've just found this while experimenting with Nebula via the free managed service, dnclient

`100.98.NNN.NNN  XXX               yyyy@      linux   active; direct 10.0.0.4:41641,`

Ubuntu 24.04
tailscaled --version
1.74.0
  tailscale commit: 28e0bab29dcadfb98c997c142b64b91c0c341652
  other commit: bfc27063c4fd342c9e0e94578e8f22a47d7a0fea
  go version: go1.23.1

None of suggested work rounds above work.
Really rather annoying
