### ISSUE TITLE
FR: Automatically switch to using an exit node when connected to specific WiFi or mobile network 

### ISSUE THREAD

**Issue by ulfklose** [tailscale/tailscale#7597] opened 2023-03-18 15:55 UTC
### What are you trying to do?

Before using Tailscale I was using my Raspberry Pi at home as a regular WireGuard server. I configured the WireGuard client on my devices to automatically connect to my home network and use it as an internet router when I’m connected to any Wi-Fi network other than my home network. 

I’d like to use this workflow with Tailscale and the exit node feature. 

### How should we solve this?

Implement an option to enable this workflow in the Tailscale clients. 

### What is the impact of not solving this?

I have to manually enable the usage of an exit node.

**Comment by DentonGentry** [comment] 2023-03-18 15:58
Duplicate of https://github.com/tailscale/tailscale/issues/3302

**Closed by DentonGentry** 2023-03-18 15:58 UTC
Labels: needs-triage, fr
