### ISSUE TITLE
iPhone - internet break after leave wi-fi range

### ISSUE THREAD

**Issue by kwladyka** [tailscale/tailscale#8022] opened 2023-05-02 19:28 UTC
### What is the issue?

Tailscale on iPhone make internet connection for apps not work.

Apps like chrome, inpost, binance, youtube etc. can't use internet, but messages and ping 8.8.8.8 work. Strange.

This is happening after I drive a car with CarPlay.

fix: switch tailscale to off and on again.

The same issue is with `exit node` and without.

PS If I will figure out something more I will edit.

### Steps to reproduce

Not sure. Drive a car with CarPlay for a long time? Fast connect and disconnect doesn't make this issue.

### Are there any recent changes that introduced the issue?

no

### OS

iOS

### OS version

16.4.1, iPhone 13 Pro

### Tailscale version

1.40.0

### Bug report

`BUG-75eea8bf205435440f38dab8c1fbe33984d6d8cd4562b65bf0786579d36d02c8-20230510095249Z-4b5761ea04a0c25e`

**Comment by FinalPoint** [comment] 2023-05-05 01:03
I have been observing the same problem on my iPhone 11 Pro / iOS 16.4.1 (a) with Tailscale 1.40.0

	⁃	When my Tailscale VPN is UP and I am using an an exit node, I lose Internet connectivity when I get out of the range of my Wi-Fi network and switch to LTE. The "VPN" status icon on the top left stays up, tho.
	⁃	Starting the Tailscale app, stopping the VPN connection and restarting it fixes the problem.
	⁃	Switching "Use exit node" to none, and back to the same exit node that was used fixes the problem
	⁃	Switching "Use exit node" to another exit node _doesn't_ fix the problem
	⁃	Simply waiting (I tried to wait for about 15 minutes) _doesn't_ fix the problem
	⁃	The reverse, going from LTE to Wi-Fi doesn't cause the same problem
	⁃	I only observe that problem when an exit node is enabled


Same problem on TestFlight version 1.41.12

Rolling back to TestFlight version 1.39.146 fixes the issue on my device

**Comment by 617a7a** [comment] 2023-05-17 09:35
I get this same issue as of recent. My iPhone loses connectivity often as I'm switching between wifi/cellular/none while walking and it's incredibly annoying. Reverted back to 1.39.146 and will have to see if that fixes it. Using iOS 16.5 (20F65)

**Comment by FinalPoint** [comment] 2023-05-21 21:34
Just tested TestFlight version 1.41.69: I still experience the exact same issue.

**Comment by FinalPoint** [comment] 2023-05-30 00:04
Same issue with 1.42.0.

**Comment by sethwm2** [comment] 2023-05-30 15:05
I signed in to comment on this because I had the same thing happen to me with the 1.40.0 update on iOS and it is driving me insane. The issue still persists with the newest update 1.42.0. I have been in a 14 email conversation with a support engineer from Tailscale. I submitted bug reports from the Tailscale client and sysdiagnose from iOS and was told the results from those have been inconclusive.

**Comment by sethwm2** [comment] 2023-05-30 15:12
> I have been observing the same problem on my iPhone 11 Pro / iOS 16.4.1 (a) with Tailscale 1.40.0
> 
> ```
> ⁃	When my Tailscale VPN is UP and I am using an an exit node, I lose Internet connectivity when I get out of the range of my Wi-Fi network and switch to LTE. The "VPN" status icon on the top left stays up, tho.
> ⁃	Starting the Tailscale app, stopping the VPN connection and restarting it fixes the problem.
> ⁃	Switching "Use exit node" to none, and back to the same exit node that was used fixes the problem
> ⁃	Switching "Use exit node" to another exit node _doesn't_ fix the problem
> ⁃	Simply waiting (I tried to wait for about 15 minutes) _doesn't_ fix the problem
> ⁃	The reverse, going from LTE to Wi-Fi doesn't cause the same problem
> ⁃	I only observe that problem when an exit node is enabled
> ```
> 
> Same problem on TestFlight version 1.41.12
> 
> Rolling back to TestFlight version 1.39.146 fixes the issue on my device

This is exactly what is happening to me it is enraging especially because the whole point of having devices on tailscale is for them to always be connected.

**Comment by FinalPoint** [comment] 2023-05-30 15:29
> > I have been observing the same problem on my iPhone 11 Pro / iOS 16.4.1 (a) with Tailscale 1.40.0
> > ```
> > ⁃	When my Tailscale VPN is UP and I am using an an exit node, I lose Internet connectivity when I get out of the range of my Wi-Fi network and switch to LTE. The "VPN" status icon on the top left stays up, tho.
> > ⁃	Starting the Tailscale app, stopping the VPN connection and restarting it fixes the problem.
> > ⁃	Switching "Use exit node" to none, and back to the same exit node that was used fixes the problem
> > ⁃	Switching "Use exit node" to another exit node _doesn't_ fix the problem
> > ⁃	Simply waiting (I tried to wait for about 15 minutes) _doesn't_ fix the problem
> > ⁃	The reverse, going from LTE to Wi-Fi doesn't cause the same problem
> > ⁃	I only observe that problem when an exit node is enabled
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Same problem on TestFlight version 1.41.12
> > Rolling back to TestFlight version 1.39.146 fixes the issue on my device
> 
> This is exactly what is happening to me it is enraging especially because the whole point of having devices on tailscale is for them to always be connected.

Could you specify the model of the device you are using and it's OS version?

Also, if you are still in contact with a support engineer, could you point him to this page? I am not sure it is on their radar. And knowing that multiple users are experiencing the same issue generally help to increase the priority of an issue...

**Comment by sethwm2** [comment] 2023-05-30 15:41
> > > I have been observing the same problem on my iPhone 11 Pro / iOS 16.4.1 (a) with Tailscale 1.40.0
> > > ```
> > > ⁃	When my Tailscale VPN is UP and I am using an an exit node, I lose Internet connectivity when I get out of the range of my Wi-Fi network and switch to LTE. The "VPN" status icon on the top left stays up, tho.
> > > ⁃	Starting the Tailscale app, stopping the VPN connection and restarting it fixes the problem.
> > > ⁃	Switching "Use exit node" to none, and back to the same exit node that was used fixes the problem
> > > ⁃	Switching "Use exit node" to another exit node _doesn't_ fix the problem
> > > ⁃	Simply waiting (I tried to wait for about 15 minutes) _doesn't_ fix the problem
> > > ⁃	The reverse, going from LTE to Wi-Fi doesn't cause the same problem
> > > ⁃	I only observe that problem when an exit node is enabled
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Same problem on TestFlight version 1.41.12
> > > Rolling back to TestFlight version 1.39.146 fixes the issue on my device
> > 
> > 
> > This is exactly what is happening to me it is enraging especially because the whole point of having devices on tailscale is for them to always be connected.
> 
> Could you specify the model of the device you are using and it's OS version?
> 
> Also, if you are still in contact with a support engineer, could you point him to this page? I am not sure it is on their radar. And knowing that multiple users are experiencing the same issue generally help to increase the priority of an issue...

I am running an iPhone 11 Pro Max NWGK22LL/A on iOS 16.5 (20F66) Tailscale client 1.42.0

Every time I disconnect and reconnect to wifi or cell network, I have to turn Tailscale off in the client and back on again to have any internet to my phone. This is an issue that cropped up first in 1.40.0 of the client. 1.42.0 has not fixed this issue. I just sent the link of this issue to the support engineer. I feel like another bug report should be opened for this and have this consolidated because the network issue when going out of range of wifi or reconnecting to wifi is not just a CarPlay specific issue.

**Comment by 617a7a** [comment] 2023-05-30 15:49
Yeah, I don't use CarPlay and I still get the same issue.

iPhone 13 Pro Max MLL03LL/A, iOS 16.5 (20F66), TS 1.42.0

**Comment by FinalPoint** [comment] 2023-06-22 16:59
Just tested TestFlight version 1.44.0: The new UI looks good. **But I still experience the exact same issue.**

Back to 1.39.146 for a working setup. Sadly, it expires in 19 days. Not sure what I'll do after that :-/

**Comment by snachx** [comment] 2023-07-08 16:36
I have experienced exactly the same issue, every time I switched from wifi to cellular network, my iPhone lost internet connection. I have to toggle tailscale off and on to recover it. 

1.39.146 works well as expected.

**Comment by bobbyl140** [comment] 2023-07-28 16:17
Same issue, Tailscale doesn’t work anymore once I leave Wi-Fi and I have to disconnect and reconnect. This alone is enough to make me use my old VPN solution in lieu of Tailscale, at least on my phone.

**Comment by lonord** [comment] 2023-08-14 10:33
Same issue after upgrading to version 1.46.1 (iOS version 16.6).

**Comment by FinalPoint** [comment] 2023-08-16 19:33
Still experiencing the same issue with version 1.48.0 (iOS 16.6)

**Comment by agottardo** [comment] 2023-08-24 21:47
Hi folks, thanks for reporting this. This is one of those problems where we cannot do any meaningful investigation without diagnostics. That's because I cannot reliably reproduce the issue on my devices, so we need to gather logs around the time the network transition happens.

Would love if you could generate a **bug report ID** the next time you happen to see this problem. You can create one from the settings in the Tailscale app, by tapping on the _Bug Report_ menu item. Please attach the bug report ID in a comment to this GitHub issue, along with date and time the issue verified. This is enough for us to correlate log entries with the issue.

**Comment by FinalPoint** [comment] 2023-08-24 21:53
HI, I just reproduced the problem 5:49 PM EST

bug report id: BUG-b64e902406c500582fcd230df9d19fb2e34b9d872664e2c3622c3c8306fecfd7-20230824215034Z-1d684cc832abd54d

The "VPN" badge stays on when the connection breaks.

Thanks

**Comment by MicroAutoE** [comment] 2023-08-26 02:41
I reproduced this problem while trying to use the Kroger app after I switched to cellular from my home wifi.  
8/25/23 around 7:47 pm.

Tailscale version 1.48.1

iOS 16.6

BUG-9f35d1238d89d8abe6704b31ccb107d4de9fb325aaf2730a7cc1ddd22a2954b2-20230826004828Z-cb2db65746ec6027

**Comment by snachx** [comment] 2023-08-29 04:09
HI @agottardo, I just reproduced the problem 08.28 23:02 EST

bug report id: BUG-c4aaf3212811da9f0d7a9d32aced13eb87541a7c447a963fe81a9d93562a2f39-20230829040312Z-bc7ebd7887898460

The "VPN" badge stays on when the connection breaks.

Tailscale version: 1.49.113

iOS 17 developer beta 7 21A5319a

Thanks

**Comment by agottardo** [comment] 2023-08-29 23:28
Thank you folks! I was able to reproduce this as well so we should have enough data for us to investigate, that said, feel free to submit additional reports. I'll update as we find out more.

**Comment by Kevin10187** [comment] 2023-09-03 17:55
Report bud ID: BUG-e027e09409bdfe1f7161970fc12f99c67a64910896d878a7d20339d5b361da12-20230903174409Z-8bd02c222679b9c5

**Comment by RobEarth0815** [comment] 2023-09-13 19:48
BUG-87b1befea5f804191272d0d64c44fcb79dd21ffc8cec478589fdae17cca36f3e-20230913194414Z-8e226ba8351929f2

**Comment by bobbyl140** [comment] 2023-10-25 03:41
This bug still seems to exist, I can provide logs too, but it is impacting me greatly as Tailscale on a *cellphone* is now basically unusable without roaming capability.

**Comment by bobbyl140** [comment] 2023-11-06 18:48
It seems like, after a period of this bug being fixed, it exists again. No clue what happened

**Comment by bobbyl140** [comment] 2023-11-07 18:50
Tailscale team, is there any update on this? I hate to badger but this issue has been open since May 2nd... TestFlight version 1.51.204 does in fact contain the fix, but 1.52.0 on the App Store and the later TestFlight builds do not, and this TestFlight build will eventually expire.

**Comment by iluvatyr** [comment] 2023-11-11 13:11
Not sure if 100% the same thing, but I have the same problem that I have no connection when I switch wifi and I have to toggle the VPN on and off

**Comment by TheNinth7** [comment] 2023-11-23 10:48
I have a similar issue, for me Internet connectivity drops when I connect my phone with CarPlay with the Tailscale VPN active.

https://github.com/tailscale/tailscale/issues/10209

I use an old iPhone SE first generation with iOS 15.7.8, Tailscale 1.52.0 and CarPlay from VW (ID.Buzz and ID.4).

**Comment by bobbyl140** [comment] 2023-11-23 17:25
> I have a similar issue, for me Internet connectivity drops when I connect my phone with CarPlay with the Tailscale VPN active.

I don't know how CarPlay works so this is a wild guess, but assuming it's wireless CarPlay I *think* iOS uses AWDL (peer-to-peer WiFi and Bluetooth) for that, and the "interface change" might be causing this same bug. If it's wired CarPlay then I got no idea. 

My point is I think these bugs are, in fact, the same bug.

**Comment by TheNinth7** [comment] 2023-11-23 17:40
Yes, I use wireless CarPlay. 

Any news on when the fix will be put in a release available on the App Store?

**Comment by bobbyl140** [comment] 2023-11-23 18:04
> Tailscale team, is there any update on this? I hate to badger but this issue has been open since May 2nd... TestFlight version 1.51.204 does in fact contain the fix, but 1.52.0 on the App Store and the later TestFlight builds do not, and this TestFlight build will eventually expire.

I don't know about a public build, the latest TestFlight builds don't seem to work and when I downloaded 1.51.204 a second time it didn't work again.

**Comment by agottardo** [comment] 2023-12-21 22:55
I'm happy to report we have identified the issue and we have a fix for it. We are currently testing it and hope to land it soon.

**Comment by TheNinth7** [comment] 2023-12-22 19:41
Great news, thanks! Please keep us posted once the fix is available.

**Comment by agottardo** [comment] 2023-12-22 20:23
@TheNinth7 you can follow along in that PR! :)

**Comment by TheNinth7** [comment] 2023-12-22 20:38
Ah, thanks. However I am not sure if that is the same as the issue I am seeing, since I am not using an exit node ...

**Comment by bobbyl140** [comment] 2023-12-22 22:01
@TheNinth7 I looked through the PR and apparently there are a bunch of other related issues, some of which involve an exit node, some of which don't. Most of these are old, but the two still open seem related. Once again this is an educated guess, but I bet this will also solve your issue with CarPlay when not using an exit node. 
The issues are #6075 and #8691.
And thank you @agottardo for the fix!

**Comment by TheNinth7** [comment] 2023-12-23 05:58
@bobbyl140 thanks for the heads up, I'll keep my fingers crossed and will test the fix as soon as it becomes available.

**Comment by l4kr** [comment] 2023-12-31 17:40
I do not use CarPlay but I still have issues.

**Comment by skaeight** [comment] 2023-12-31 21:51
Great to see this is being addressed. I’m seeing this problem. Looking forward to the fix being released.

**Comment by agottardo** [comment] 2024-01-04 18:44
Tailscale 1.57.44 for iOS has been submitted for TestFlight testing and should include a potential fix for this issue. It will be available for download shortly, as soon as Apple approves it. If you have been affected by this problem, try switching to the [TestFlight builds](https://testflight.apple.com/join/tLcYLZJV) once 1.57.44 is available. I would love if you could let me know here if the problem has been addressed or not.

**Comment by bobbyl140** [comment] 2024-01-04 18:46
I'm on TestFlight updates, I'll provide feedback once that gets pushed out.

**Comment by agottardo** [comment] 2024-01-05 03:57
1.57.44 is now available on TestFlight.

**Comment by snachx** [comment] 2024-01-05 06:32
@agottardo I'm certain that the issue has been resolved in version 1.57.44, at least in my specific usage scenario. Many thanks.

**Comment by FinalPoint** [comment] 2024-01-05 13:36
Same here. That issue is fixed for me in 1.57.44

Thanks!

**Comment by skaeight** [comment] 2024-01-05 18:47
Fixed for me too.  Thanks for taking care of this 😀

**Comment by agottardo** [comment] 2024-01-05 18:50
Thank you folks for the feedback. 

I'll close this since a fix is now available on TestFlight and users have been reporting the problem is solved there. If you don't want to use TestFlight, the fix will land for everyone in our next stable release, Tailscale 1.58. 

If you still experience issues with CarPlay or the Android client, please comment on the issues already open for each of those.

**Closed by agottardo** 2024-01-05 18:50 UTC
Labels: OS-ios, L1 Very few, bug

**Comment by l4kr** [comment] 2024-01-08 09:32
Uhm it appears that there's now the complete opposite problem - the app won't let me turn off VPN On-Demand :D

**Comment by agottardo** [comment] 2024-01-08 17:34
> Uhm it appears that there's now the complete opposite problem - the app won't let me turn off VPN On-Demand :D

That's an intended change we added in 1.57/1.58. We are now doing what the majority of iOS VPN apps does: we always keep On-Demand enabled behind the scenes with an Always On configuration, unless you created a custom On-Demand configuration using the in-app configuration editor. This Always On config allows Tailscale to automatically restart if iOS decides to kill the app overnight (which it very often does to reduce memory utilization, search for related issues mentioning `SystemMemoryReset`). 

If you don't want Tailscale to run anymore, you must disconnect it using the in-app toggles (or shortcuts, widgets, Siri). Alternatively, if you are disconnecting Tailscale from the Settings app, turn off On-Demand and _then_ disconnect.

**Comment by ouvoun** [comment] 2024-01-21 18:23
(Reposting from the wrong thread)

Unfortunately this does not seem to fix my issue when transferring from Cellular -> Wi-Fi. Wi-Fi -> Cellular works just fine. I still need to disable + reenable Tailscale to recover my internet. Let me know if logs would be helpful.

**Comment by agottardo** [comment] 2024-01-22 00:20
> (Reposting from the wrong thread)
> 
> Unfortunately this does not seem to fix my issue when transferring from Cellular -> Wi-Fi. Wi-Fi -> Cellular works just fine. I still need to disable + reenable Tailscale to recover my internet.
> 
> Attaching a bug report from when this recently occurred (about 10 minutes prior to snagging the ID): `BUG-4b71e5c143e1f53da5df9d03c918df937301f3fdc2f3ce1aff9231ddd5ecbf5a-20240121182406Z-c750db72c157ab31`

@ouvoun Please open a new issue with this information. It is likely that you're hitting a different root cause given that the earlier fix discussed here has addressed the problem for many other users.

**Comment by r3n3x** [comment] 2024-01-22 01:51
Just to confirm:
The initial problem of blocked connectivity when switch between Wifi and Mobile data is resolved for me with the Tailscale Testflight app from 2 weeks ago. Now on 1.58.0 and it works well. 
iOS 17.3 RC on 14pro.

**Comment by TheNinth7** [comment] 2024-02-04 07:23
Unfortunately my issue with Car Play still exists in 1.58.2, albeit there is a little change in the behavior.

When connecting to Car Play with the VPN active, Car Play connectivity works, also the VPN connectivity works, but cellular Internet does not. When I then deactivate VPN, cellular Internet works. What is NEW is that when I then try to activate the VPN again, it DOES NOT connect, it just shows "Connecting ...". With older versions I was able to reconnect VPN when in Car Play, and it just stopped cellular Internet again.

If there is anything I can provide to help debugging this, I'd be happy to ...

I also updated issue https://github.com/tailscale/tailscale/issues/10209, which I originally created for this.

**Comment by FinalPoint** [comment] 2024-05-30 22:01
Unfortunately, I need to report a regression. That problem is back with version 1.67.52.

I hope you'll be able to track it down quickly and that it won't slip in production 🤞


Thanks.

cc: @agottardo

**Comment by agottardo** [comment] 2024-05-30 22:01
@FinalPoint bug report identifier please

**Comment by FinalPoint** [comment] 2024-05-30 22:55
Sorry, I didn't get a report identifier.

I first re-experienced the problem yesterday evening. Didn't think much of it at the time. Then, again, this afternoon.
And I was able to reproduce it about an hour later when I got back home.

But, before reporting the issue here, I tried downgrading to the previous build, to see if it was also affected. I wasn't able to reproduce it.

I reinstalled the latest build when you requested a bug report identifier. But had no luck recreating the problem since.


I'll make sure to generate one and report it here next time it happens...

**Comment by r3n3x** [comment] 2024-05-31 02:02
iPho14p,  iOs 17.5.1, TS TF 1.67.52, Mullvad ExNode

I experienced the issue of "no internet connectivity" on 5G with Tailscale on when I tried to scan a QR code food menu on 30/05 around 0615UTC. 
The waiter assisted me and said "look Sir you have a VPN on, perhaps that's the issue". I replied "for sure not", anyhow he politely gave me their WiFi password. I connected to WiFi and magically the food menu linktr.ee opened well. 
When I left the restaurant I had "no connectivity" at Waze/Google Maps while driving on & off. 

I tried to "trigger" the issue with manually turning off WiFi at my iPhone right now - but that doesn't seem to trigger the loss off connectivity.

Will observe more.

**Comment by agottardo** [comment] 2024-05-31 02:25
@r3n3x can I get a bug report ID from your device?

**Comment by r3n3x** [comment] 2024-05-31 02:28
> @r3n3x can I get a bug report ID from your device?

BUG-682b4aec417fec210550c7b72646446cf88eeffa828e5673a94cd6766fcd0eae-20240531022730Z-0c78c2466a426c88

**Comment by agottardo** [comment] 2024-05-31 02:28
Thank you!

**Comment by agottardo** [comment] 2024-05-31 02:39
@r3n3x appreciate you sending the bug report ID, there appears to be something off with DNS over HTTPS during the timeframe you indicated. We're looking into it.

**Comment by r3n3x** [comment] 2024-05-31 03:00
Thanks. 
Yes, I had configured to use my NextDNS (DoH) profile with Tailscale&Mullvad. 

Perhaps @FinalPoint uses NextDNS or other custom DNS, too?

**Comment by agottardo** [comment] 2024-05-31 15:31
> Interesting.
> 
> Yes, I have a DoH configuration profile installed on my iPhone. It's pointing to a (publicly accessible) server I manage myself.

@FinalPoint Do you have DoH configured in the Tailscale admin console, and is Override Local DNS enabled?

**Comment by FinalPoint** [comment] 2024-05-31 15:45
@agottardo In the Tailscale admin console, I see that I have "Cloudflare Public DNS" configured as my Nameservers, with "Override Local DNS" enabled. I am not using the "NextDNS (DoH)" servers.

**Comment by FinalPoint** [comment] 2024-06-02 10:56
Experienced the problem a few minutes ago.  Like before, disabling the use of my exit node for a few seconds and reenabling it got me back network connectivity.

@agottardo : BUG-b64e902406c500582fcd230df9d19fb2e34b9d872664e2c3622c3c8306fecfd7-20240602104734Z-690b0b8ca9f418f4

Thanks!

**Comment by r3n3x** [comment] 2024-06-04 22:00
https://www.reddit.com/r/ProtonVPN/s/EjOaaDxZvS

ProtonVPN app users experience a similar behavior. Is it perhaps a iOS update related matter for Wireguard VPNs?

**Comment by agottardo** [comment] 2024-06-04 22:11
@r3n3x no, this is not caused by an iOS update and we encourage you to always use the latest iOS version available. Tailscale engineers run on the iOS beta to identify issues caused by upcoming updates. Generally speaking, there are tens of dozens of different reasons why network transitions will break a VPN on iOS. Any VPN client doing more than a bare minimum implementation using the public Apple APIs is bound to break when moving between networks. We got several of these things wrong in the past, and oh well, other VPNs are bound to experience the same.

We are investigating the issue reported by you and @FinalPoint. Your bug report IDs indicate it is specifically caused by using DNS over HTTPS, and the forwarder attempting to re-use a connection that was broken by a network transition. For now as a temporary workaround, you'll likely see a benefit from disabling "Use Tailscale DNS Settings" in the app (yes I know, you'll lose the ability to access resources using their name...). We likely won't land a fix in time for this in v1.68. Stay on TestFlight so you can get a fix when we ship it.

**Comment by FinalPoint** [comment] 2024-06-04 22:29
@agottardo, is your recommendation to disable "Use Tailscale DNS Settings" also for me? As I understand it, I do use "Tailscale DNS Settings", but I am using a "traditional" plain text / udp DNS, and not DoH.

Also wondering: is there another bug to track this issue? If not, should this one still be marked as "closed"?

**Comment by agottardo** [comment] 2024-06-05 05:05
@FinalPoint I opened https://github.com/tailscale/tailscale/issues/12352 to track this for you and @r3n3x. You can track progress there.

**Comment by agottardo** [comment] 2024-06-05 05:06
I'll be locking this as the original issue has been addressed, and I don't want to keep re-use this issue # to track a different problem (it is confusing for us to make sense of what has been fixed and what hasn't).
