### ISSUE TITLE
Windows taskbar menu malfunctions when shift+F10 is used to open it, breaks screen reader support

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#4993] opened 2022-07-01 03:17 UTC
### What is the issue?

From a report to support@tailscale.com:

I use a screen reader, and have been trying to set up an exit node. Here's a very non-obvious bug:
1. Exit and restart Tailscale.
1. press Windows+b to move to the system tray, find Tailscale with the arrows, and press shift+F10 to bring up the context menu.
After doing that, the screen reader reads the menus but Network Devices is unavailable and Exit Node doesn't activate the submenu when I try.

Repeating this, but right click the icon with the mouse or equivalent screen reader keys instead of shift+F10. After that, the Exit node and Network devices work.

It doesn't affect all the submenus. Preferences works, for example.

### OS

Windows

### Tailscale version

1.26.1

**Comment by DentonGentry** [comment] 2022-10-31 05:47
>press Windows+b to move to the system tray, find Tailscale with the arrows, and press shift+F10 to bring up the context menu.

When I do this, I see very similar behavior to that described:
1. The Network Devices menu is greyed out and using the arrow keys to navigate the menu skips over it.
2. Though I can use the arrow keys to select Exit Node, it won't open the sub-menu
3. I can navigate to and open the Preferences menu
<img width="251" alt="Screen Shot 2022-10-30 at 10 43 44 PM" src="https://user-images.githubusercontent.com/1140756/198940007-985eedd2-60b0-4178-b728-acacc7e091aa.png">

**Comment by dblohm7** [comment] 2023-02-10 18:58
The problem is that the prep work that we do just prior to showing our context menu is attached to a right-click mouse event instead of an event to be run when the menu is to be shown. I'll dig into `walk` a bit more to see how I want to deal with this, especially with respect to my owner-drawn menu changes that are going to be in an upcoming PR.

**Comment by dblohm7** [comment] 2023-02-10 19:06
Yeah, this is going to need to parts; a `walk` update, then a change to the GUI.

**Comment by dblohm7** [comment] 2023-02-10 23:15
I've got this all working, but the PRs need to be landed in order. First [walk](https://github.com/tailscale/walk/pull/19), then I'll update corp.

**Comment by DentonGentry** [comment] 2023-02-17 23:49
https://github.com/tailscale/corp/pull/8720 imported the new walk into the Windows build.
So far as I can tell, Tailscale 1.38 will fix this issue.

**Closed** 2023-03-03 17:44 UTC
Labels: OS-windows, L1 Very few, P3 Can't get started, T5 Usability, bug, accessibility
