### ISSUE TITLE
FR: auto enable exit node

### ISSUE THREAD

**Issue by krugster** [tailscale/tailscale#9978] opened 2023-10-26 09:09 UTC
### What are you trying to do?

On my iPhone, most of the time I don’t want to use an exit node. However, I need to enable it when my current WiFi’s subnet overlaps with my home network’s. 

### How should we solve this?

It would be a nice feature to automatically enable my exit node if the subnets overlap, and not if they don’t. 

Similarly, it would be nice to have a setting to always default exit node to on, off, or “last setting”.  

### What is the impact of not solving this?

Make it easier to connect more often in the most optimal way with fewer clicks and overrides.

**Comment by TechByTom** [comment] 2023-10-26 14:17
This might be solvable using Shortcuts. Have you tried using the "Use Exit Node" shortcut feature in combination with maybe your location as a trigger?

**Comment by krugster** [comment] 2023-10-26 21:15
The problem is, I don’t necessarily know that the subnets overlap. My home
network is 10.0.0.0, most public WiFi is 192.168.x.x but right now I’m at
an Airbnb that also uses 10.0.0.0. So when I’m at the Airbnb, I need to use
an exit node, when I travel around the city, I don’t. And since I’m so far
away from home, I don’t want to use an exit node for all my network traffic
all the time.

**Comment by stevetrease** [comment] 2023-10-29 20:46
What about a Shortcuts Automation that runs whenever you connect to any WiFi which then checks your IP address and enables the Tailscale exit node if appropriate for you?

**Comment by DentonGentry** [comment] 2024-01-12 12:43
Substantially a duplicate of https://github.com/tailscale/tailscale/issues/3302, one more criteria to use.

**Closed by DentonGentry** 2024-01-12 12:43 UTC
Labels: needs-triage, fr
