### ISSUE TITLE
FR: snat-subnet-routes support for FreeBSD

### ISSUE THREAD

**Issue by mallendeo** [tailscale/tailscale#2758] opened 2021-08-31 16:03 UTC
Hi, I'm trying to create a Site-to-Site VPN, I followed the [OPNsense install instructions](https://tailscale.com/kb/1097/install-opnsense/). Both sites are running OPNsense 21.7.1 and Tailscale 1.14.0.

SiteB can ping SiteA firewall from the OPNsense CLI, so the connection is working. However I can't reach or ping the same firewall or any SiteA's IP from a SiteB device on any subnet. I tried setting wide open firewall rules on LAN and TLSCL interfaces with no luck.

![opnsense-tailscale](https://user-images.githubusercontent.com/1578018/131535492-34b57668-3656-4fe5-a675-6a7d247c6bd0.png)

I also tried isolating the issue with two OPNsense VMs with the same results.

**Comment by mallendeo** [comment] 2021-09-02 02:30
It seems to be more of a problem with opnsense than tailscale, so I'm closing this issue.

**Comment by DentonGentry** [comment] 2021-09-02 02:34
In 1.14 we added hybrid netstack support in https://github.com/tailscale/tailscale/issues/2498, to implement FreeBSD operating as an exit node. That shouldn't have had an impact on subnet routing, which was known to work in earlier releases, but I'd like to look into it.

**Comment by Strider3000** [comment] 2021-09-15 13:45
I came here to comment that I am now seeing this same behavior described by @mallendeo in OPNsense on 1.14.2. 
This was not an issue when I previous used 1.12.2.

In my setup I have two different Opnsense boxes with two different public IPs and two different subnets.
On 1.12.2, I could ping from the cli of either Opnsense directly into the other's remote subnet and hosts on those subnets.
I could also ping from the hosts in one subnet into the hosts of other subnets.
After upgrading to 1.14.2 I can still ping from the opnsense cli directly into the other remote subnet and hosts on the remote subnet. However, I can no longer ping from hosts in one subnet to the hosts on the other subnet. I have even tried refactoring the firewall rules with no results.

This does seem like an issue with 1.14.2 on opnsense.
Is there a way to downgrade from 1.14.2 to 1.12 on opnsense?

**Comment by DentonGentry** [comment] 2022-10-30 13:35
The fundamental problem appears to be related to `--snat-subnet-routes=false` not being implemented for FreeBSD.

SNAT is enabled by default because otherwise, we have no way to tell LAN nodes on 10.10.1.0/24 to add a route to 192.168.1.0/24.

![snat-subnet-routes site-to-site](https://user-images.githubusercontent.com/1140756/198881350-8300f0fd-a745-4b02-a690-6405d857b491.png)

**Comment by DentonGentry** [comment] 2023-06-03 04:17
Duplicate of https://github.com/tailscale/tailscale/issues/5573 (which, while filed later, has more recent status about process).

**Closed by DentonGentry** 2023-06-03 04:17 UTC
Labels: OS-freebsd, L1 Very few, P2 Aggravating, T0 New feature, fr
