### ISSUE TITLE
FR: iOS option to not automatically try and connect when the app is opened or switched to accidentally

### ISSUE THREAD

**Issue by chris-c-thomas** [tailscale/tailscale#7228] opened 2023-02-09 18:13 UTC
### What are you trying to do?

For majority of the day I'm connected with a different  VPN service. If I open the Tailscale or switch to it accidentally it automatically boots me from the other connection. 

### How should we solve this?

Have an option to not automatically try and connect.

### What is the impact of not solving this?

I'm disconnected from other VPNs

### Anything else?

Maybe I'm doing something wrong or there is a way around this but so far I can't see one.

**Comment by DentonGentry** [comment] 2023-02-12 04:45
Duplicate of https://github.com/tailscale/tailscale/issues/539

**Closed by DentonGentry** 2023-02-12 04:45 UTC
Labels: OS-ios, needs-triage, fr, needs-dedup
