### ISSUE TITLE
FR: Ensure direct connection between offices/sites/CPD/Clusters with server hosts acting as routers

### ISSUE THREAD

**Issue by lordraiden** [tailscale/tailscale#4554] opened 2022-04-27 22:00 UTC
### What are you trying to do?

Ensure that always direct connection is used to get best network bandwidth and latency when using hosts (servers) acting as routers

A possible use case could be someone wanting to interconnect 3 offices branches with 1 server in each with tailscale acting as router. Or 3 instances of kubernetes clusters...
Other use case could be a user that always want to have direct connection to get better performance when he connects to an specific host.

### How should we solve this?

Since we a under a server environment I understand that you need 1 port open to internet per wireguard connection so lets assume we have 3 offices that we want to interconnect.

Each server acting as a router and will require 2 open ports, 1 for each of the other 2 servers. UPnP and derivates are not an option in corporate environments, for many reasons including security ones. Even if you can do it more or less safe, it won't go throughout any serious security audit.

What would require at least:

- A setting to disable the use of relays in a host would be required
- Should be supported in the configuration to establish "several" fixed ports in each host to establish de connection.
- The ability to assign a fix port to a host (remote), so the remote host always use that port to establish the connection
- The ability to configure the source port and destination port in every host, so I can harden even more the security in the firewall filtering the incoming connection by source . So if someone tries to establish a connection to one of the host and the source port is different from what I have configured it will be blocked. Although in an environment like this we would be probably have fixed IP.

Other remote hosts could connect to this mesh of 3 or 10... servers via direct o relay, but the 3 servers between them will always be direct connection to ensure maximum performance

### What is the impact of not solving this?

Poor performance and inconsistent experience. 
Inability to ensure a fast an reliable interconnection between branches or cpd, clusters, etc.

### Anything else?

I have read the documentation I see that there are some partial workarounds but nothing really covers this use case, or at least is not clearly explained.

**Comment by DentonGentry** [comment] 2022-04-28 00:20
Duplicate of https://github.com/tailscale/tailscale/issues/3624

**Closed by DentonGentry** 2022-04-28 00:20 UTC
Labels: L1 Very few, P1 Nuisance, T0 New feature, fr
