### ISSUE TITLE
New iPhone has the same Tailscale address as the old iPhone

### ISSUE THREAD

**Issue by vincentlu** [tailscale/tailscale#2984] opened 2021-10-03 00:12 UTC
I got a new iPhone and set it up by choosing “transfer data from another iPhone directly” (as opposed to iCloud backup). Once it’s done I found both phones had the same Tailscale address, even after I removed the device in the admin UI and reinstalled Tailscale on both phones. (The old phone had had the Tailscale app installed before I got the new phone. So once the new phone is set up using the old phone it too had the app.)

They finally got different addresses after I erased the old phone and set it up without transferring data from iCloud backup or another phone.

Old device: iPhone 12 Pro Max
New device: iPhone 13 Pro Max
iOS: 15.0.1

**Comment by DentonGentry** [comment] 2021-10-03 00:16
Duplicate of https://github.com/tailscale/tailscale/issues/969, that cloning the Keychain also clones the machine key and node keys.

What I think would have worked:
- In https://login.tailscale.com/admin/machines find the entry for the iOS device, click on the three dot menu to the far right of its entry, and click Remove.
- On the iOS device click the three dot menu and select "Reauthenticate." This makes it get a new node key.

**Closed by DentonGentry** 2021-10-03 00:16 UTC
