### ISSUE TITLE
[IOS] 17 Beta hostname is localhost-0 not device name

### ISSUE THREAD

**Issue by deasmi** [tailscale/tailscale#9251] opened 2023-09-06 09:17 UTC
### What is the issue?

Using tailscale on the iPadOS 17 beta 6 the device name in the tailscale admin console shows are localhost-0 and not the device name as set on Settings->General as before.

### OS

iOS

### OS version

17 beta 6

### Tailscale version

1.48.1

### Bug report

BUG-62764db31e45c081825a8108a1314b48fbc1d73579019de9f0b41750c0849efc-20230906091203Z-ed5e0ee80ad22784

**Comment by knyar** [comment] 2023-09-06 11:37
Thanks for reporting this. I believe it's a duplicate of #8293, so I will close this one.

**Closed by knyar** 2023-09-06 11:37 UTC
Labels: needs-triage, bug
