### ISSUE TITLE
FR: Allow AND in ACLs

### ISSUE THREAD

**Issue by sopeters** [tailscale/tailscale#5290] opened 2022-08-04 01:34 UTC
### What are you trying to do?

Say we have 2 environments (staging and production) and each environment contains 2 hosts (HostA and HostB).
They all get deployed via pipelines so tags are applied for function and environment. I will tag each of the hosts with the following environment tag and function/host tag, 

Staging 
* Host A - tag:staging tag:HostA
* Host B - tag:staging tag:HostB

Production
* Host A - tag:production tag:HostA
* Host B - tag:production tag:HostB

I now want to ensure that a user/group has only access to a specific host in one environment, e.g HostA only in staging.
Currently this is not possible since all ACL rules allowing access to any one of the tags on a node, access will be granted

### How should we solve this?

Having ACLs where you can specify an AND rule so you can ensure more complex access can be configured

### Anything else?

I received the response to use a different host specific tag for the hosts. This is a workaround but makes things more complex

**Comment by DentonGentry** [comment] 2022-08-28 05:51
related: https://github.com/tailscale/tailscale/issues/5108

**Comment by DentonGentry** [comment] 2023-02-18 00:42
Duplicate of https://github.com/tailscale/tailscale/issues/5108

**Closed by DentonGentry** 2023-02-18 00:42 UTC
Labels: L3 Some users, P1 Nuisance, T0 New feature, fr
