### ISSUE TITLE
FR: Android: Automatically enable/disable and/or use exit node when on Wifi

### ISSUE THREAD

**Issue by mato** [tailscale/tailscale#4615] opened 2022-05-05 10:10 UTC
### What are you trying to do?

It'd be cool if Tailscale could have a toggle / other UI to automatically switch on when I'm connected via Wifi, and switch off again when I'm back on mobile data. Or, if that is not possible, then at least toggle a specified exit node on/off when on Wifi.

Bonus points if it could do that for "all except this list of trusted SSIDs / BSSIDs".

I don't want the VPN / exit node always on when on mobile data, as I consider the telco's tunnel to be good enough in that case, and prefer to save battery. Also, when roaming and thousands of miles away from the home network the extra latency from going through the exit node is not always worth it.

### How should we solve this?

See above.

### What is the impact of not solving this?

Manually toggling.

### Anything else?

Might be a touch fiddly working out the interaction with captive portals, otherwise should be fairly straightforward?

**Comment by DentonGentry** [comment] 2022-05-05 11:31
Duplicate of https://github.com/tailscale/tailscale/issues/3302

**Closed by DentonGentry** 2022-05-05 11:31 UTC
Labels: needs-triage, fr
