### ISSUE TITLE
Tailscale SSH doesn't work on FreeBSD

### ISSUE THREAD

**Issue by ethindp** [tailscale/tailscale#6193] opened 2022-11-03 23:16 UTC
So I've set up my ACL for Tailscale SSH, have set up a tag, and tagged the server I want to SSH into:

```json
{
	"acls": [
		// Match absolutely everything.
		// Comment this section out if you want to define specific restrictions.
		{"action": "accept", "users": ["*"], "ports": ["*:*"]},
	],
	"ssh": [
		{
			"action": "accept",
			"src":    ["autogroup:members"],
			"dst":    ["tag:gdn-auth"],
			"users":  ["autogroup:nonroot"],
		}
	],
	"tagOwners": {
		"tag:gdn-auth": ["redacted"]
	}
}
```

(I also tried to keep the more permissive ACL for general SSH but that didn't work either.) I do have `sshd(8)` running on my server on port 22, so that might be the problem. Have I screwed up the ACL?

**Comment by DentonGentry** [comment] 2022-11-04 02:33
The issue template asked for a bugreport because it lets us look up the node and the tailnet to help diagnose what is wrong.

>I do have sshd(8) running on my server on port 22, so that might be the problem.

OpenSSH running on port 22 to handle other interfaces in the system is fine. So long as it was started using `tailscale up --ssh`, then`tailscaled` will itself handle port 22 for the Tailscale IP address.

**Comment by ethindp** [comment] 2022-11-04 03:34
@DentonGentry Oops... I wasn't given an issue template. Will find it and use it next time.

**Comment by DentonGentry** [comment] 2022-11-04 12:56
Ah, the email address was in the ACLs in the initial filing (which I've now redacted since this is a public bug).

The tagged server on the account is running FreeBSD, where Tailscale SSH doesn't work yet. There is an open source contribution underway in https://github.com/tailscale/tailscale/pull/6155 to add FreeBSD support.

**Comment by DentonGentry** [comment] 2023-02-18 19:50
I believe this was fixed by https://github.com/tailscale/tailscale/pull/6155 and should be in Tailscale 1.36.

**Closed by DentonGentry** 2023-02-18 19:50 UTC
Labels: OS-freebsd, L2 Few, P2 Aggravating, T5 Usability, ssh

**Comment by BasixKOR** [comment] 2023-02-18 23:08
I believe the docs should be updated too: https://tailscale.com/kb/1193/tailscale-ssh/#devices

**Comment by Stunt0265** [comment] 2023-05-28 14:07
Based on this, should Tailscale SSH to a FreeBSD machine be working?  I'm getting:

failed to look up root
Permission denied (tailscale)

And I get this for all users on the FreeBSD machine that I know exist.  SSH working for all my other Tailscale machines so confident my ACLs are configured correctly.

**Comment by bradfitz** [comment] 2023-05-28 14:18
@Stunt0265, a recent release had a regression for FreeBSD SSH support but was fixed in the most recent release. Please file a new bug if it doesn't work with the latest release but let's not debug here in a closed bug.

**Comment by Stunt0265** [comment] 2023-05-28 15:41
Thanks.  I upgraded to v1.42 and it's working now.  Thanks
