### ISSUE TITLE
Mullvad: no IPv6?

### ISSUE THREAD

**Issue by pshirshov** [tailscale/tailscale#9511] opened 2023-09-21 22:40 UTC
### What is the issue?

Currently I'm using tailscale on mac laptop connected to IPv4-only network.

When I use my own dual-stack v4/v6 exit node, my laptop has v6 connectivity.

When I switch to a Mullvad exit node, the laptop gets only v4 connectivity.
 
I guess that should't work this way?..

### OS version

macOS

### Tailscale version

1.48.2

### Bug report

BUG-647a40c70adc4b93c0b5b48f2932dfb7679713b3273ac8eb0e29385d965ade80-20230921224053Z-2c894086f49cfbb9

**Comment by aofei** [comment] 2023-09-23 11:26
I believe IPv6 isn't currently supported for generic WireGuard peers. Maybe it's due to some technical difficulties. There's only one [`tailscale.com/tailcfg.Node.SelfNodeV4MasqAddrForThisPeer`](https://pkg.go.dev/tailscale.com/tailcfg#Node.SelfNodeV4MasqAddrForThisPeer) available.

**Comment by pshirshov** [comment] 2023-09-23 12:14
I kinda didn't get it. It works for my own nodes but doesn't work for mullvad. At the same time mullvad supports ipv6.

**Comment by aofei** [comment] 2023-09-23 16:36
Mullvad, or non-Tailscale WireGuard nodes, are not like your Tailscale nodes. They don't speak Disco or DERP, and they don’t have knowledge about the Tailscale IP ranges (`100.64.0.0/10` and `fd7a:115c:a1e0:ab12::/64`). Therefore, you can't simply route packets originating from a Tailsacle IP to them, as they don't recognize Tailscale IPs at all.

In order to use non-Tailscale WireGuard nodes as exit nodes, you need to __masquerade__ your packets. This is where [`SelfNodeV4MasqAddrForThisPeer`](https://pkg.go.dev/tailscale.com/tailcfg#Node.SelfNodeV4MasqAddrForThisPeer) comes in. Tailscale modifies your packets to make them appear as if they originated from the provided `SelfNodeV4MasqAddrForThisPeer`, which should be known to those nodes.

However, as mentioned earlier, there is currently only one `SelfNodeV4MasqAddrForThisPeer`, which means that only IPv4 is supported at the moment. To support IPv6, I believe that at least `SelfNodeV6MasqAddrForThisPeer` needs to be added as well.

**Comment by aofei** [comment] 2023-09-25 22:41
It appears that [SelfNodeV6MasqAddrForThisPeer](https://pkg.go.dev/tailscale.com/tailcfg#Node.SelfNodeV6MasqAddrForThisPeer) has just been added in [v1.50.0](https://github.com/tailscale/tailscale/releases/tag/v1.50.0). But I'm not sure if it will work, as it's not mentioned in the release notes. You can upgrade your Tailscale client to v1.50.0 and try again.

**Comment by pshirshov** [comment] 2023-09-26 17:38
Still not working on 1.50

**Comment by aofei** [comment] 2023-09-26 23:50
Yeah, it doesn't work yet. https://github.com/tailscale/tailscale/commit/c08cf2a9c6209e4fdef896921af66bbe737b8a24:

> This PR plumbs through awareness of an IPv6 SNAT/masquerade address from the wire protocol
through to the low-level (tstun / wgengine). This PR is the first in two PRs for implementing
IPv6 NAT support to/from peers.
>
> A subsequent PR will implement the data-plane changes to implement IPv6 NAT - this is just plumbing.

You'll have to wait for another version or two. Not sure about the ETA.

**Comment by pallorc** [comment] 2023-11-20 21:49
I'm loving the Mullvad exit node support in Tailscale.

And, I'd just like to add that I'm very much looking forward to ipv6 support for Mullvad exit nodes.

**Comment by r3n3x** [comment] 2023-12-16 02:23
<img width="1071" alt="Screenshot 2023-12-16 at 10 21 37" src="https://github.com/tailscale/tailscale/assets/23291787/f185312e-323d-40f6-89ca-1804276f7441">

Confirmed, with MULLVAD Exit nodes we don't get IPV6 connectivity. 
On my own AWS EC2 exit nodes servers I managed to configure correct IPV6 - so it's probably not a Tailscale problem but an issue at MULLVAD side?

**Comment by r3n3x** [comment] 2024-01-07 01:53
https://tailscale.com/kb/1258/mullvad-exit-nodes?tab=macos mentions
"IPv6 is not currently supported. Tailscale will be removing this restriction in the future."

-> What's the outlook for the removal of this restriction?   ;-)

**Comment by Aubermean** [comment] 2024-03-12 14:21
While Mullvad exit node is enabled, IPv6 breaks completely for me. So much that certain things like apt repos from my host also break.

**Comment by purple-emily** [comment] 2024-03-15 12:38
Would also like IPV6 support for exit nodes :)

**Comment by sanitybit** [comment] 2024-07-29 07:26
While I appreciate the tight integration with the tailscale client, the lack of IPv6 support, with no updates in 6+ months, is pushing me towards dropping the Mullvad addon SKU. 

Is this still being worked on?

**Comment by r3n3x** [comment] 2024-07-29 12:09
The fact that the admin "hid" my comment from 7/Jan and the DentonGentry's reply said "I promise we will update the bug when there is something to report." made me not ask further questions here...

I am not sure what's the hindrance. Would love to know of course.

**Comment by bradfitz** [comment] 2024-08-04 00:49
We tend to hide "What's the status on this?" comments because they're a distraction from the thread and spam everybody watching the bug for actual updates. As Denton said earlier, when there are updates to share, we'll share.

And an update: #13014 was just merged, so there's been progress on this.

**Comment by r3n3x** [comment] 2024-08-04 03:22
UPDATE: Tailscale Version 1.71.58 MacOS standalone now shows a 10/10 IPv6-support score at https://test-ipv6.com while connected to a Mullvad exit node. Great job & thanks team @bradfitz @DentonGentry

**Comment by bradfitz** [comment] 2024-08-14 15:50
Thanks for confirming! I'll close this bug. The stable release (1.72.0) will be out with the fix soon.

**Closed by bradfitz** 2024-08-14 15:50 UTC
Labels: L3 Some users, P2 Aggravating, T0 New feature, bug, mullvad
