### ISSUE TITLE
Implement mdns-based candidate endpoint discovery

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1252] opened 2021-02-02 20:01 UTC
WebRTC exchanges candidate endpoints similarly to magicsock, for NAT traversal. However, it's implemented a very cool idea to preserve peer privacy for private LAN endpoints: https://tools.ietf.org/html/draft-ietf-rtcweb-mdns-ice-candidates-04

TL;DR: instead of peers telling each other "I might be reachable on 192.168.0.15:1234" (which leaks private LAN information), nodes register a UUID hostname in their local mdns resolver (e.g. `<uuid4>.local -> 192.168.0.15:1234`), then give their peer the UUID. The peer can then query their local mdns for that UUID, and if they're on the same LAN as their peer, they'll learn the ip:port that they can use.

This is pretty great because it hides information from peers that are not in a position to make use of that information, while still offering a way to upgrade to a direct LAN connection.

We should do that as well. There may be complications for things like communication between a Docker container and its host (which are LAN IPs, but mdns seems less likely to work on that link), and this functionality depends on nodes being able to register new names in their local mdns resolver, which may not be true on all OSes.

**Comment by DentonGentry** [comment] 2021-07-21 05:37
Closing as a duplicate of https://github.com/tailscale/tailscale/issues/1482, which has had more discussion.

**Closed by DentonGentry** 2021-07-21 05:37 UTC
Labels: L3 Some users, T0 New feature, connectivity, enhancement
