### ISSUE TITLE
No tailscaled.sock found when running tailscale in docker

### ISSUE THREAD

**Issue by baltazartroisville** [tailscale/tailscale#9559] opened 2023-09-27 18:54 UTC
### What is the issue?

hello, and thanks in advance for help, i tried to setup tailscale for the first time in my life but it was no good experience :)

i tried to follow the description on docker hub for setting tailscale up but it seems to be a complete mess. the first error was solvable by adding `--device /dev/net/tun:/dev/net/tun` to the docker run script, i found that out after extensive googleing in some forums, not on the tailscale website.

`sudo docker run -d --name=tailscaled --restart=always -v /var/lib/tailscale:/var/lib/tailscale -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --device /dev/net/tun:/dev/net/tun -e TS_STATE_DIR=/var/lib/tailscale -e TS_USERSPACE=0 -e TS_AUTH_ONCE=1 -e TS_ACCEPT_DNS=1 -e TS_HOSTNAME=love --network=host --cap-add=NET_ADMIN --cap-add=NET_RAW --env TS_AUTHKEY=examplekey tailscale/tailscale:stable`
this docker run command allows to connect the device to the mesh, in the tailscale admin overview everything seems to be fine.

but when i tried to run `sudo docker exec -it tailscaled tailscale up --ssh` i get the following error: `failed to connect to local tailscaled (which appears to be running as tailscaled, pid 14). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory`

and when i tried to run `sudo docker exec -it tailscaled tailscale cert love.tailscale-example.ts.net` i get this error: `Failed to connect to local Tailscale daemon for /localapi/v0/cert/love.tailscale-example.ts.net; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory`

after that i tried to create a bugreport with `sudo docker exec -it tailscaled tailscale bugreport` but got the same error as above.

i then tried to check `sudo docker exec -it tailscaled journalctl -u tailscale(d)` but that didnt work either.

at last i checked the docker logs with `sudo docker logs tailscaled` and found 3 errors:

`health("overall"): error: state=NeedsLogin, wantRunning=false`

`dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory`

`health("router"): error: setting up filter/ts-input: running [/sbin/iptables -t filter -N ts-input --wait]: exit status 3: iptables v1.8.8 (legacy): can't initialize iptables table ´filter': Table does not exist (do you need to insmod?)`

im no expert but they all seem to be related.

### OS

Linux

### OS version

Fedora 38

### Tailscale version

1.48.2

### Other software

docker, cloudflared, cockpit, portainer-ee, teleport client, lynis, chkrootkit, fail2ban, pcp

**Comment by guest42069** [comment] 2023-09-28 05:39
probably #6849 see the comments on that issue for some solutions.

**Comment by baltazartroisville** [comment] 2023-09-28 13:08
> probably #6849 see the comments on that issue for some solutions.

Thank you, that solved some of the problems, maybe that should be added to the documentation to make it clearer so that even people less technically gifted like me can solve it.

Still `dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory` in the docker logs persists and floods the log with thousands of the same error message.

Additionally it isn't possible to connect with ssh, neither with the web console nor with direct ssh access. It seems tailscale tries to establish a connection to the container in which tailscale is running itself and of course no host user can be found there.
I'm not sure why it is like this, i tried to strictly follow the docs and the blogpost.

It seems tailscale in docker is more like a beta status software, if I install it directly on the host everything is working perfectly.

Thanks again! 😊

**Comment by hrcdigital** [comment] 2023-09-29 09:57
Are you using the correct internal IP address in your container?

**Comment by baltazartroisville** [comment] 2023-09-29 11:12
thank you for trying to help me! :)

yes, the connection can be established, the port is open, client and ssh server agree upon encryption but then tailscale ssh says that the user "mynameislara" cant be found, which makes sense because in the tailscale container im pretty sure no user named like this exists, it exists only directly on the host system.

im not quite sure what you mean with the correct internal ip? i take the ip address from the machine overview of the tailscale admin website, my pc is successfully connected to the mesh as well and then i try to connect with ssh. 
the greeting phase works with the hostname through magic dns, the long domain name works and even the ip works. the only problem is that the connection cant be established because the user cant be found.

**Comment by hrcdigital** [comment] 2023-09-29 14:22
First uninstall Tailscaile from your container, let's call it your server.
Then connect SSH from outside your container to your server.
If that works, then install Tailscale.
Try connect via SSH the same way you did as before. 
So not via name or IP of Tailscale but the same as before installing Tailscale.
If that's not working try via the Tailscal name of your server.
If that's also not working you probably have an adapter issue or hostfile issue.

Be sure to make SSH available from outside your server (SSH config).
Just use the normal SSH and not the specific Tailscale SSH functionality.
Just use username and password and later on you can change it to a key.

**Comment by baltazartroisville** [comment] 2023-09-30 17:36
> First uninstall Tailscale from your container, let's call it your server. Then connect SSH from outside your container to your server. If that works, then install Tailscale. Try connect via SSH the same way you did as before. So not via name or IP of Tailscale but the same as before installing Tailscale. If that's not working try via the Tailscale name of your server. If that's also not working you probably have an adapter issue or hostfile issue.
> 
> Be sure to make SSH available from outside your server (SSH config). Just use the normal SSH and not the specific Tailscale SSH functionality. Just use username and password and later on you can change it to a key.

im a bit confused now, sorry. 
should i remove the tailscale container completely or should i remove tailscale inside the tailscale container? I thought that the container is optimized from and for tailscale? 

i dont even know which package manager they built in the tailscale container. and how should i install it again afterwards? i tried to run apt and dnf but neither seems to be installed in the tailscale container, it seems to be a really stripped down linux system. maybe there isnt much left if i remove tailscale from the container?

and my goal is not to ssh in the container, i want to ssh in the host. which is already working fine with pubkey, but not via tailscale ssh.

and this error still persists in the docker logs. `dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory`

thank you!

**Comment by hrcdigital** [comment] 2023-10-03 11:38
Looks like you have a different approach.
A container is just a virtual machine.
So, Tailscale is not a container but just a piece of software to make network connections.
Let say you want a Ubuntu container, then you add the connector to this Ubuntu container and spin it up.
Just like a normal VM.
That's how you should use it.

Then you should be able to connect to your container using Tailscale.

**Comment by DentonGentry** [comment] 2023-11-18 16:33
Duplicate of https://github.com/tailscale/tailscale/issues/6849

**Closed by DentonGentry** 2023-11-18 16:33 UTC
Labels: needs-triage, bug

**Comment by cubimol** [comment] 2024-10-17 15:01
This additional parameter fixes the error for me when I create the tailscale container:

...
-v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
...
