### ISSUE TITLE
MacOS Ventura dragging Tailscale icon to the notch makes it disappear and not come back

### ISSUE THREAD

**Issue by eltonajmenezes** [tailscale/tailscale#8339] opened 2023-06-14 10:46 UTC
### What is the issue?

The menu bar icon of Tailscale doesn't show up sporadically even after using activity monitor to force quit the app and reopen it. 

### OS

macOS

### OS version

macOS Ventura 13.4

### Tailscale version

1.42

**Comment by bradfitz** [comment] 2023-06-14 14:12
Running anything on the https://github.com/tailscale/tailscale/wiki/OtherSoftwareInterop list or similar?

**Comment by StdioA** [comment] 2023-06-15 01:05
Seems this problem is not caused by tailscale but macOS.   
After upgrading to 13.4, dragging any icons into notch will lead to the icon disappearing, and I didn't find a way to recover yet.

**Comment by jcyh0120** [comment] 2023-10-25 16:04
+1 and my solution is remove unused icons in the control center settings.
<img width="706" alt="截圖 2023-10-26 上午12 01 13" src="https://github.com/tailscale/tailscale/assets/4725814/8bbeba37-9a14-4e4c-ae60-15eb20e21eb9">

If there are still too many icons on your menubar,  press cmd key and drag those icon left. Repeat until you see the tailscale icon show up. (The icons are hide but they still exist in an order.)

**Comment by agottardo** [comment] 2023-11-13 22:54
Closing. This is not something actionable on our end. As described above, the solution is to use the control center settings to make room for the icon to reappear.

**Closed by agottardo** 2023-11-13 22:54 UTC
Labels: OS-macos, L3 Some users, P3 Can't get started, T5 Usability, bug
