### ISSUE TITLE
F-Droid: App instantly crashes since Version 1.76.x

### ISSUE THREAD

**Issue by pmffromspace** [tailscale/tailscale#13878] opened 2024-10-22 10:05 UTC
### What is the issue?

unable to Start app.

### Steps to reproduce

Im on eOS Android (without google)

### Are there any recent changes that introduced the issue?

Update

After downgrade to 1.72 works again

### OS version

2.4.1-t-20241008439851-official-FP5

### Tailscale version

1.76.*

**Comment by nagisa** [comment] 2024-10-22 19:02
Duplicate of https://github.com/tailscale/tailscale/issues/13850

**Closed** 2024-10-22 19:11 UTC
Labels: needs-triage, bug
