### ISSUE TITLE
FR: Start on Boot for Android

### ISSUE THREAD

**Issue by charlieporth1** [tailscale/tailscale#4238] opened 2022-03-20 19:28 UTC
### What are you trying to do?

Automatically start tailscale on boot when a device reboots to be remotely accessed

### What is the impact of not solving this?

A remotely accessed tailscale device can be unavailable after a reboot or powerloss

**Comment by DentonGentry** [comment] 2022-03-20 19:29
Duplicate of https://github.com/tailscale/tailscale/issues/2481

**Closed by DentonGentry** 2022-03-20 19:29 UTC
Labels: needs-triage, fr

**Comment by charlieporth1** [comment] 2022-03-20 19:39
@DentonGentry Actually this is a bit different from the Always-on VPN feature of Android. Because Always-on VPN has to do with the "VPN part of the network stack" on Android it only is included in devices with full Android network settings (Underneath VPN settings) like Phones and Tablets. This would be a switch to start a VPN service on boot.  Which would be different and useful for devices without full access like devices like Chromebooks and Android/Google TVs. While officially you don't support Android/Google TV. Going to create a FR as well for that if there was not one
