### ISSUE TITLE
Accepting a node sharing request fails with "failed to accept invite"

### ISSUE THREAD

**Issue by blin** [tailscale/tailscale#3638] opened 2021-12-29 21:52 UTC
### What is the issue?

I'm trying to share a node between two personal accounts.

Sharing a node and then accepting on the other side produces a "failed to accept invite" error. The shared node then appears in the list of nodes in the admin panel of the person accepting the invite, but both `tailscale ping` and accessing services(http get requests) exposed by the node fails.

I expect accepting the invite to not fail with an error.

Both tailscale ping and accessing services succeed for the shared node within the account that has the node.

### Steps to reproduce

1. Create share invite link
2. Send link to another person
3. Person clicks "accept invite", the error is displayed

### Are there any recent changes that introduced the issue?

N/A, was trying this feature for the first time.

### OS

Linux, Android

### OS version

Debian 11, Chrome OS with the android app

### Tailscale version

1.18+

### Bug report

BUG-e005c124c77733edda19296a9f0426a9fa42c2097f23880ebabc155bc0c98d7b-20211229214810Z-4d0c40bf09981a14

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_435e9)

**Comment by DentonGentry** [comment] 2021-12-29 22:15
The bug report was generated on the system that was shared with another tailnet?

**Comment by arunsathiya** [comment] 2021-12-30 13:34
Noting that I see the issue as well. Happened on two instances:

- a GitHub-based tailnet sharing a node to a Google-based tailnet (personal account to a personal account)
- a GitHub-based tailnet sharing a node to a GitHub organization-based tailnet (personal account to an organization account)

The invite actually gets accepted; refreshing the page shows the correct status.

I am not sure how to generate a bug report because the node being shared is an Android device.

**Comment by blin** [comment] 2021-12-30 17:53
@DentonGentry , I am not sure what the status was at the moment I generated the report id. I have been sharing/unsharing various nodes in various directions to see if I could find a combination that works (I didn't).

BUG-04ac9a5c79d9caee28de08b8c5c300cf8d9292fa3cd5d873f2d633eec541d0a7-20211230174748Z-9ec611363863a17c was generated on a node that is shared (reported shared in https://login.tailscale.com/admin/machines ).

**Comment by FerriteGiant** [comment] 2022-01-03 06:40
I just saw this as well. I generated an invite from a Tailscale account authenticated with a Google account and then clicked accept from a Github authenticated account. After clicked several times and seeing the error each time, I exited the page and went back to the list of machines. The new machine was there and I'm able to access it just fine.

**Comment by DentonGentry** [comment] 2022-01-10 14:01
I think we've identified the root cause for this, it should be resolved in the next production push.

**Comment by blin** [comment] 2022-01-16 11:29
Tried sharing the node again just now after updating all participating nodes to 1.20.x . No error was displayed, success message was displayed instead.

After purging data from the android app (on Chrome OS) everything works, thanks!

I think this can be marked fixed now.

**Closed** 2022-01-16 14:41 UTC
Labels: L2 Few, P2 Aggravating, T5 Usability, bug

**Comment by ctrochalakis** [comment] 2024-04-03 09:05
Hello all,

I am having the same issue today sharing a node from a github org to a personal (google) account. When hitting the invitation accept button the remote endpoint fails with a 500 response code, I am including a request-id from such a call.

```
x-tailscale-request-id REQ-12152fab2-4597-4370-9b74-65093f055770
```

**Comment by rbnhln** [comment] 2024-04-03 09:09
> Hello all,
> 
> I am having the same issue today sharing a node from a github org to a personal (google) account. When hitting the invitation accept button the remote endpoint fails with a 500 response code, I am including a request-id from such a call.
> 
> ```
> x-tailscale-request-id
> 	REQ-1bfddd7d6-6f72-406d-a926-2bc3be6a55db
> ```

Experienced the same just a minute ago.

**Comment by cesarandreslopez** [comment] 2024-04-03 12:06
Same thing now.

**Comment by Sh4yen** [comment] 2024-04-03 12:58
Hey,

getting the same issue when sharing a node between two personal GitHub accounts.

**Comment by akmzero** [comment] 2024-04-03 15:48
Started getting the same error this morning.  

However the invite is between 2 google accounts.

**Comment by luisaugustos** [comment] 2024-04-03 15:48
I have the same situation here. 
the request returns `{"status":"error","error":"Internal Server Error"}`

**Comment by branflakem3** [comment] 2024-04-03 17:23
Same issue here too

**Comment by Its-Ankush** [comment] 2024-04-03 18:47
I tried to send my invite code to my friend and it says this. This is on Chrome Android. Im yet to ask him to test this on other browsers/laptop

![IMG_20240404_001649](https://github.com/tailscale/tailscale/assets/68053631/20f8ad52-e9a3-458a-bc2c-4ff4ab22eff1)

**Comment by branflakem3** [comment] 2024-04-03 18:51
> I tried to send my invite code to my friend and it says this. This is on Chrome Android. Im yet to ask him to test this on other browsers/laptop
> 
> ![IMG_20240404_001649](https://private-user-images.githubusercontent.com/68053631/319313793-20f8ad52-e9a3-458a-bc2c-4ff4ab22eff1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzA1NTQsIm5iZiI6MTcxMjE3MDI1NCwicGF0aCI6Ii82ODA1MzYzMS8zMTkzMTM3OTMtMjBmOGFkNTItZTlhMy00NThhLWJjMmMtNGZmNGFiMjJlZmYxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE4NTA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmY2RjMzY4MDQ4YTY1OWI1ZjVkZWNmNGE2MjE4YWVlODFkOTcxNDMyZDcwNWNkNmVmYjQxNDM0MmE5OTc2YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bj8kQdD7OmrWV_E1m0FQWr6InxzsLgEuCjAiHBZGDJI)

Yep, identical results here.

**Comment by kelivel** [comment] 2024-04-03 20:36
Hi folks, we're tracking the new issue over at https://github.com/tailscale/tailscale/issues/11606 and will keep this one closed as it's unrelated.
