### ISSUE TITLE
tailscale update on Ubuntu did not restart tailscaled

### ISSUE THREAD

**Issue by porwig-kintsugiyama** [tailscale/tailscale#5095] opened 2022-07-19 18:02 UTC
### What is the issue?

Ubuntu 22.04 LTS, updating tailscale from 1.26.1 to 1.28.0 failed to restart tailscaled.
Server was configured with tailscale SSH, upgrade was run over tailscale SSH.

SSH connection was lost during upgrade, but upgrade appeared to complete.

I expected to be able to reconnect to the server over tailscale ssh after the update, but needed to manually restart the service.

### OS

Linux

### OS version

Ubuntu 22.04 LTS and 20.04

### Tailscale version

1.28.0

**Comment by DentonGentry** [comment] 2022-07-20 00:28
Closing as duplicate of #5029

**Closed by DentonGentry** 2022-07-20 00:28 UTC
Labels: needs-triage, bug
