### ISSUE TITLE
FR: Support for openWRT routers

### ISSUE THREAD

**Issue by KayLEvans** [tailscale/tailscale#6252] opened 2022-11-09 20:03 UTC
### What are you trying to do?

Per user issue: 

> I have installed tailscale on my Oracle server but then when I wanted to connect it from my router which runs on the OpenWRT. Somehow my router's traffic is not routing through my oracle server even though I specifically used CLI command to use exit node

Reproduction steps:

> Install Tailscale using OpenWRT addons. Then authenticate with your acct and move forward with tailscale up command with --exit-node=(MyOracleServerIP) which I have marked as Exit node.

**Comment by DentonGentry** [comment] 2022-11-25 01:51
Likely prerequisite: https://github.com/tailscale/tailscale/issues/391

**Comment by DentonGentry** [comment] 2023-06-03 23:16
Duplicate of https://github.com/tailscale/tailscale/issues/724

**Closed by DentonGentry** 2023-06-03 23:16 UTC
Labels: OS-linux, L2 Few, P3 Can't get started, T0 New feature, fr
