### ISSUE TITLE
Docker builds broken in 0.98

### ISSUE THREAD

**Issue by deasmi** [tailscale/tailscale#368] opened 2020-05-10 11:10 UTC
**Describe the bug**
Changes introduced since 0.97 prevent tailscaled from starting in Docker
Tested on Ubuntu 20.04
Tested on Unraid - https://github.com/deasmi/unraid-tailscale

**To Reproduce**
1. Install Ubuntu 20.04
2. Clone tailscale repo
3. docker build -t tailscale .
4.  docker run -it --name=tailscaled  -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --network=host --privileged tailscale /bin/sh
5. tailscaled

**Expected behavior**
Tailscaled should start correctly

**Version information:**
 - Device: PC
 - OS: Ubuntu
 - OS version: 20.04
 - Tailscale version: 0.98

**Additional context**
Seems that STUN behaviour has changed and is no longer playing nice inside of Docker
Output attached

[tslog.txt](https://github.com/tailscale/tailscale/files/4605527/tslog.txt)

**Comment by westonsteimel** [comment] 2020-05-10 15:04
I have also been unable to start tailscaled on Linux since commit https://github.com/tailscale/tailscale/commit/7618d7e67754ce8d1681cc3830d68ad5d14c737c

**Comment by westonsteimel** [comment] 2020-05-10 20:11
So after looking into this further, it seems that the iptables commands were failing in previous versions with `No chain/target/match by that name`; however, `tailscaled` was still starting successfully.  After https://github.com/tailscale/tailscale/commit/7618d7e67754ce8d1681cc3830d68ad5d14c737c, this now causes `tailscaled` to fail.  In my case, I discovered that `CONFIG_NETFILTER_XT_MATCH_COMMENT` needed to be enabled in the kernel.

**Comment by danderson** [comment] 2020-05-10 20:54
@westonsteimel was the error shaped the same in your case? It's not clear to me if these are the same failure or different ones.

The change you linked made router setup stricter, certainly. Previously we'd just silently fail but keep going with a broken configuration, now we refuse to proceed instead.

What distro/system is this on? I'm surprised to see the netfilter comment module disabled, of all things, as it's the most harmless no-op possible. That leads me to wonder what other modules and behaviors are missing.

**Comment by subdavis** [comment] 2020-05-10 21:00
Just in case it's useful for debugging, I'm seeing this as well.

```
~$ docker run -d --name=tailscaled -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --network=host --privileged tailscale:tailscale tailscaled
7519257ebb1a77b7fabcf612f006ec812b592e5a7d2b6c7785f0d90c2168c952

~$ docker logs tailscaled
2020/05/10 20:44:16 logpolicy.Read /root/.cache/Tailscale/tailscaled.log.conf: open /root/.cache/Tailscale/tailscaled.log.conf: no such file or directory
2020/05/10 20:44:16 logtail started
2020/05/10 20:44:16 Program starting: vdate.20200410, Go 1.14.2: []string{"tailscaled"}
2020/05/10 20:44:16 LogID: [REDACTED]
2020/05/10 20:44:16 14.7M/19.9M Starting userspace wireguard engine with tun device "tailscale0"
2020/05/10 20:44:16 15.1M/19.9M CreateTUN ok.
2020/05/10 20:44:16 15.4M/19.9M Routine: event worker - started
2020/05/10 20:44:16 15.3M/19.9M Interface set up
2020/05/10 20:44:16 magicsock: starting endpoint update (initial)
2020/05/10 20:44:16 16.0M/19.9M UDP bind has been updated
2020/05/10 20:44:16 16.1M/20.9M Device closing
2020/05/10 20:44:16 16.1M/20.9M Routine: event worker - stopped
2020/05/10 20:44:16 magicsock.Conn.determineEndpoints: updateNetInfo: got STUN error: context canceled; missing replies from: derp2.tailscale.com:3478, derp3.tailscale.com:3478, derp4.tailscale.com:3478, derp5.tailscale.com:3478
2020/05/10 20:44:16 magicsock: endpoint update (initial) failed: got STUN error: context canceled; missing replies from: derp2.tailscale.com:3478, derp3.tailscale.com:3478, derp4.tailscale.com:3478, derp5.tailscale.com:3478
2020/05/10 20:44:16 16.0M/20.9M Interface closed
2020/05/10 20:44:16 16.0M/20.9M NewUserspaceEngineAdv: exit status 255
panic: close of closed channel

goroutine 1 [running]:
github.com/tailscale/wireguard-go/tun.(*NativeTun).Close(0xc000182100, 0x19, 0xc0000201b0)
	/go/pkg/mod/github.com/tailscale/wireguard-go@v0.0.0-20200424121617-8d10f231531a/tun/tun_linux.go:377 +0xcb
tailscale.com/wgengine.NewUserspaceEngine(0xc0000caac0, 0xa02f1e, 0xa, 0x0, 0xc0000caac0, 0x73, 0xc0000fdef0, 0x1)
	/go/src/tailscale/wgengine/userspace.go:109 +0x336
main.main()
	/go/src/tailscale/cmd/tailscaled/tailscaled.go:86 +0x904
```

OS/kernel:

```
OS: Ubuntu 18.04.4 LTS x86_64 
Kernel: 5.3.0-40-generic 
```

```
~$ grep CONFIG_NETFILTER_XT_MATCH_COMMENT /boot/*config*
/boot/config-5.2.8-050208-generic:CONFIG_NETFILTER_XT_MATCH_COMMENT=m
/boot/config-5.3.0-28-generic:CONFIG_NETFILTER_XT_MATCH_COMMENT=m
/boot/config-5.3.0-40-generic:CONFIG_NETFILTER_XT_MATCH_COMMENT=m
```

**Comment by westonsteimel** [comment] 2020-05-10 21:29
> @westonsteimel was the error shaped the same in your case? It's not clear to me if these are the same failure or different ones.

My error looked very similar, but mine had a bit more detail:

```
20.2M/20.7M Starting userspace wireguard engine with tun device "tailscale0"
20.4M/21.5M CreateTUN ok.
magicsock: starting endpoint update (initial)
21.2M/21.8M Routine: event worker - started
21.2M/21.8M Interface set up
21.4M/21.8M UDP bind has been updated
22.4M/22.5M Device closing
22.4M/22.5M Routine: event worker - stopped
magicsock.Conn.determineEndpoints: updateNetInfo: got STUN error: context canceled; missing replies from: derp2.tailscale.com:3478, derp3.tailscale.com:3478, derp4.tailscale.com:3478, derp5.tailscale.com:3478, derp1.tailscale.com:3478
magicsock: endpoint update (initial) failed: got STUN error: context canceled; missing replies from: derp2.tailscale.com:3478, derp3.tailscale.com:3478, derp4.tailscale.com:3478, derp5.tailscale.com:3478, derp1.tailscale.com:3478
22.4M/22.5M Interface closed
22.4M/22.5M NewUserspaceEngineAdv: running [/sbin/iptables -t filter -A ts-input ! -i tailscale0 -s 100.115.92.0/23 -m comment --comment ChromeOS VM connectivity -j RETURN --wait]: exit status 1: iptables: No chain/target/match by that name.
panic: close of closed channel

goroutine 1 [running]:
github.com/tailscale/wireguard-go/tun.(*NativeTun).Close(0xc00019a400, 0x19, 0xc0005ec140)
	/home/weston/.go/pkg/mod/github.com/tailscale/wireguard-go@v0.0.0-20200424121617-8d10f231531a/tun/tun_linux.go:377 +0xcb
tailscale.com/wgengine.NewUserspaceEngine(0xc0001887c0, 0x9fc05e, 0xa, 0xa2a9, 0xc0001887c0, 0x73, 0xc00008def0, 0x1)
	/home/weston/github/westonsteimel/tailscale/wgengine/userspace.go:109 +0x336
main.main()
	/home/weston/github/westonsteimel/tailscale/cmd/tailscaled/tailscaled.go:86 +0x904
```

> The change you linked made router setup stricter, certainly. Previously we'd just silently fail but keep going with a broken configuration, now we refuse to proceed instead.
> 
> What distro/system is this on? I'm surprised to see the netfilter comment module disabled, of all things, as it's the most harmless no-op possible. That leads me to wonder what other modules and behaviors are missing.

I wouldn't worry too much on this just yet.  I'm using Gentoo for some reason.  I guess I like pain.

**Comment by danderson** [comment] 2020-05-10 21:40
Okay so combo of several things here.
 - CONFIG_NETFILTER_XT_MATCH_COMMENT seems to be disabled in Gentoo. This is a puzzling choice (assuming it's the default?).
 - When running in docker, iptables can't load the comment module even if it exists, because the modules aren't present in the container.
 - Router setup is supposed to log the command that failed and its output, but isn't.
 - We're double-closing the wireguard-go device, causing a panic on shutdown. The panic isn't the cause of the problem, rather it's just an unfortunate side-effect of aborting startup at this particular point.

Still digging.

**Comment by danderson** [comment] 2020-05-10 22:52
With more error reporting:

```
12.9M/24.6M router up failed: listing ip rules: exit status 255
ip: ignoring all arguments
```

That's possibly the best error I've ever seen. `ip` is choosing to just ignore what I'm telling it, and prints a statement to that effect. WTF?

**Comment by danderson** [comment] 2020-05-10 22:53
... oooh this is going to be because this is an Alpine container, and `ip` is being reimplemented badly by busybox, isn't it...

**Comment by danderson** [comment] 2020-05-10 22:55
Bingo, busybox's reimplementation of `ip` doesn't understand rule priorities.

The sensible fix is to just switch the container to debian-slim, and have a sensible distro as our base.

**Comment by danderson** [comment] 2020-05-10 23:14
Oh, right, that makes it _much_ worse, because switching to debian in the container introduces the breakage where the OS's and container's iptables aren't the same, and end up using different kernel subsystems. Sigh.

**Comment by westonsteimel** [comment] 2020-05-10 23:23
I think you could install `iproute2` in alpine to get the implementation of `ip` that you need.

**Comment by danderson** [comment] 2020-05-10 23:34
Yup, switched to doing that just now. It still won't fix the problem of incompatible iptables implementations, but I'm definitely not going to fix that today.

**Closed** 2020-05-11 00:12 UTC
Labels: L3 Some users, P4 Halts deployment, T7 Crash
