### ISSUE TITLE
"Cannot connect to" error with Airplay from macOS to Hisense TV while Exit Node active

### ISSUE THREAD

**Issue by louy2** [tailscale/tailscale#10962] opened 2024-01-27 10:26 UTC
### What is the issue?

Trying to mirror screen to a Hisense TV with Airplay. I expect the screen to be mirrored. While no Exit Node enabled, the screen is mirrored properly. While an Exit Node is enabled, I get "Cannot connect to" error. Maybe related to #1013, #10770.

### Steps to reproduce

1. Enable Exit Node
2. From Control Center > Screen Mirroring, pick "Living Room TV"
3. A pop up appears with 'Cannot connect to "Living Room TV"'

### Are there any recent changes that introduced the issue?

No.

### OS

macOS

### OS version

macOS Sonoma 14.2.1 (23C71)

### Tailscale version

1.58.2, Mac App Store Variant

### Other software

TripMode (An application level firewall, disabled, used as traffic volume monitor)
Malwarebytes (No Premium, Protection disabled, used for scanning only)

### Bug report

BUG-cca10a715335611a2482fd43591de771e14bf9bfd60dde4f3a77c569405c0f3a-20240127101329Z-371dd5fd06845e13, BUG-cca10a715335611a2482fd43591de771e14bf9bfd60dde4f3a77c569405c0f3a-20240127101411Z-fd63d905cc4451fb

**Comment by kelivel** [comment] 2024-02-08 20:51
Hi @louy2 

We've identified the problem and will work towards a fix. I'll close this one out as a duplicate of https://github.com/tailscale/tailscale/issues/10770, and I'd encourage you to subscribe to that issue for updates. We'll post an update there with more information once we have it. Thanks for reporting!

**Closed by kelivel** 2024-02-08 20:51 UTC
Labels: OS-macos, L1 Very few, P2 Aggravating, bug
