### ISSUE TITLE
FR: Tailscale should provide the controlplane as software

### ISSUE THREAD

**Issue by sspreitzer** [tailscale/tailscale#7828] opened 2023-04-09 14:57 UTC
### What are you trying to do?

I am looking for a solution to run Tailscale in an isolated environment which is not allowed to communicate with the internet or the Tailscale Inc. infrastructure (controlplane.tailscale.com).

### How should we solve this?

Tailscale should provide the controlplane as (open source) software.

### What is the impact of not solving this?

Some use cases will not be able to be covered by Tailscale, as security governance would not allow to contact the internet or Tailscale Inc. infrastructure.

**Comment by DentonGentry** [comment] 2023-04-09 15:48
I expect https://github.com/tailscale/tailscale/issues/498 will provide a solution.

Duplicate of https://github.com/tailscale/tailscale/issues/498

**Closed by DentonGentry** 2023-04-09 15:48 UTC
Labels: needs-triage, fr
