### ISSUE TITLE
Android Client change server functionality broken in v1.38.1

### ISSUE THREAD

**Issue by senorsmile** [tailscale/tailscale#7818] opened 2023-04-07 22:28 UTC
### What is the issue?

The exact same problem described in https://github.com/tailscale/tailscale/issues/6671 and presumably solved there is happening for me on 2 different devices.  

### Steps to reproduce

* Set up headscale
* join a desktop computer to confirm working
* install tailscale on android device
* click hamburger menu many times until the option to "change server" appears
* change server option to point to your new headscale server
* close app
* reopen app
* *should* get an option to log in, but only options are
  * sign in with google
  * sign in with other (which opens a webpage to tailscale.com

### Are there any recent changes that introduced the issue?

This is the first time I've tried this, so I'm not sure if previous versions worked or if the issue just started happening in 1.38.1

### OS

Linux, Android

### OS version

NixOS 22.11, Android 12

### Tailscale version

1.38.1

**Comment by TheUserDead** [comment] 2023-04-10 10:14
Confirm. Click on "sign in with other" opens my webserver, but nothing inside.

**Comment by TheUserDead** [comment] 2023-04-10 10:22
MIUI 13.0.4 Android 12
App ver 1.38.1
Try steps, open hampurger\kebab menu few times
- enter my server
- close app
- open app + click "sign in with other"
- opened my website where headscale hosted and see blank screen but, after few try, finally see nodekey
- create user and register nodekey 
- return back to menu - i logged in

**Comment by jaen** [comment] 2023-05-14 15:05
Still doesn't work on 1.40, exact version:
![Screenshot_20230514_170355_Settings](https://github.com/tailscale/tailscale/assets/227236/95fd1e6c-09ee-486f-b3d7-73ffc408a0f1)

When I try to use "Sign in with other" immediately, it hangs. If I close and re-open, it opens Tailscale login instead.

**Comment by wisemonkey** [comment] 2023-06-24 06:01
just confirming that this is still an issue.
I searched for tailscale android app version 1.32 and used that to login.
But latest apps don't work

**Comment by csszep** [comment] 2023-07-28 18:27
Same issue here with Pixel 6a and Tailscale client 1.44.1

**Comment by derekcrovo** [comment] 2023-10-02 16:39
I have the same issue. When I select "Sign in with other" it just hangs. This behavior started when I added Authelia to do SSO for the headscale server, but now I can't log in even with the SSO removed.

**Comment by derekcrovo** [comment] 2023-10-04 04:15
Some behavior notes and a reliable workaround!

The problems started when I logged out of my headscale tailnet in the Tailscale client.
* When I open the Tailscale client and try to "Sign in with other" I always get redirected to the Tailscale login site even if my server name has been added.
* If I then edit my server name and save without making any changes, and "Sign in with other" it does try to connect to my server, but the spinner clocks forever.
* When I delete my phone's node in headscale and repeat the dance from above, it connects to headscale. I can see the nodekey in the headscale log and when I register the node, the client logs in.

I'm on a Galaxy S21 using Tailscale 1.48.2. Headscale is v0.22.3 on NixOS 23.05.

**Comment by unixfox** [comment] 2024-01-15 21:29
I spent a little bit of time analyzing all the working versions.

For me, it works until 1.44.1 (version from July 2023 so still somewhat ok). Past this version, the logging server is forgotten on the second fresh launch of the app, so when using 1.48.2.

I'm using ionscale as an open source control plane, but that shouldn't matter: https://github.com/jsiebens/ionscale

If it can help, I have attached a screen recording of the issue:

https://github.com/tailscale/tailscale/assets/4016501/2029e380-f545-480e-adda-f87f92c71d48

**Comment by agottardo** [comment] 2024-04-12 19:44
@unixfox @StarkZarn @derekcrovo @csszep @Midou36O Can you please test with [our new Android app](https://mastodon.social/@tailscale@hachyderm.io/112259739383441517), and let us know if the issue is still present? Thanks

**Comment by Midou36O** [comment] 2024-04-13 18:30
Adding an account doesn't even work.
For those who want to try: Go to settings > Accounts > three little dots on the top right > Custom URL > Add account

Doing so for me only redirects me to login.tailscale.com, which is not what should be happening. It didn't fix a bug, just introduced a new one :P

**Comment by agottardo** [comment] 2024-04-13 19:39
We are aware. Duplicate of https://github.com/tailscale/tailscale/issues/11716, fixed in https://github.com/tailscale/tailscale-android/pull/325.

**Closed by agottardo** 2024-04-13 19:39 UTC
Labels: OS-android, L1 Very few, P3 Can't get started, T5 Usability, bug

**Comment by Midou36O** [comment] 2024-04-13 22:59
That still does not solve the problem for the stable release of Tailscale android, The beta version requires you to enroll on Google Play and there is no release in F-Droid or any binary available to test the beta versions (that i'm aware of). If the issue isn't fixed in a stable release, it shouldn't be closed already. Thank you.

**Comment by unixfox** [comment] 2024-04-26 12:39
Has a stable version of tailscale for android landed for fixing this bug? Or is it exclusive to beta users for the moment?

**Comment by RomeoV** [comment] 2024-08-05 19:50
FYI, currently the latest version on FDroid seems to fix this.

**Comment by deskil** [comment] 2024-08-26 21:50
> FYI, currently the latest version on FDroid seems to fix this.

what version do you see on FDroid? I'm seeing 1.70.0 and I don't see a way to change server

**Comment by DeWir3** [comment] 2024-08-26 22:08
Settings -> Accounts -> Three-dot-menu -> Use an alternate server

Aug 26, 2024 23:51:07 deskil ***@***.***>:

FYI, currently the latest version on FDroid seems to fix this.

what version do you see on FDroid? I'm seeing 1.70.0 and I don't see a way to change server

**Comment by agottardo** [comment] 2024-08-26 22:38
@DeWir3 answered the question. I'll lock this issue. Please open a new issue if you experience issues with the [current version](https://pkgs.tailscale.com/stable/#android).
