### ISSUE TITLE
FR: Connect to multiple tailnets simultaneously (Workaround for #183)

### ISSUE THREAD

**Issue by entrptaher** [tailscale/tailscale#5721] opened 2022-09-22 08:00 UTC
### What are you trying to do?

Connect to multiple company networks.

### How should we solve this?

Currently this is my workaround is to create a different service with different socket, and the previous issue https://github.com/tailscale/tailscale/issues/183 is locked only a few days ago.

On my personal projects:
```
sudo tailscale up --shields-up
```

On Company A:
```
sudo tailscaled -port 40000 -tun client1 -socket /var/run/tailscale/client1.sock -statedir /var/run/tailscale/client1
sudo tailscale --socket /var/run/tailscale/client1.sock up --shields-up
```

On Company B:
```
sudo tailscaled -port 40001 -tun client2 -socket /var/run/tailscale/client2.sock -statedir /var/run/tailscale/client2
sudo tailscale --socket /var/run/tailscale/client2.sock up --shields-up
```

I just keep the shield up to ensure there is no network attack vectors by someone tapping my network.

That's it! If there is a way to switch between the sockets, it would be great.

### What is the impact of not solving this?

Just shared tailscale to my clients and realized it just took away my freedom to switch between them.

### Anything else?

You may close this issue as this is actually duplicate.

**Comment by DentonGentry** [comment] 2022-09-22 10:56
Duplicate of https://github.com/tailscale/tailscale/issues/183

**Closed by DentonGentry** 2022-09-22 10:56 UTC
Labels: needs-triage, fr
