### ISSUE TITLE
[DS916+] error: running "ip link set dev tailscale0 up" failed: fork/exec /sbin/ip: invalid argument

### ISSUE THREAD

**Issue by ThomasDalla** [tailscale/tailscale#3120] opened 2021-10-17 08:17 UTC
Was working fine with 1.12, but since I upgraded to 1.16 (current latest), the `tailscale0` interface does not come up.
It looks good with the `tailscale` command (like `tailscale status` or `tailscale ping xxx` work), but because the `tailscale0` interface is not up, it doesn't work outside of the tailscale command (can't ping the tailscale IP for example).

Tailscale version
```
# tailscale --version
1.16.0
  tailscale commit: 86bcf6a964468c86ac4cc97adadc7d7a47c10178
  other commit: f787a582e80a6baed9ff81d9dd2db06ba789df3e
  go version: go1.17.1-ts097d1284f9
```

Error in the logs:
```
2021/10/17 07:05:34 wgengine.NewUserspaceEngine(tun "tailscale0") error: running "ip link set dev tailscale0 up" failed: fork/exec /sbin/ip: invalid argument
2021/10/17 07:05:34 wgengine.NewUserspaceEngine(tun "userspace-networking") ...
```

NAS info
```# uname -a
Linux NAS916 3.10.105 #25556 SMP Sat Aug 28 02:13:34 CST 2021 x86_64 GNU/Linux synology_braswell_916+
```

/sbin/ip info
```
# /sbin/ip -help
Usage: ip [ OPTIONS ] OBJECT { COMMAND | help }
       ip [ -force ] -batch filename
where  OBJECT := { link | addr | addrlabel | route | rule | neigh | ntable |
                   tunnel | tuntap | maddr | mroute | mrule | monitor | xfrm |
                   netns | l2tp | tcp_metrics | token }
       OPTIONS := { -V[ersion] | -s[tatistics] | -d[etails] | -r[esolve] |
                    -f[amily] { inet | inet6 | ipx | dnet | bridge | link } |
                    -4 | -6 | -I | -D | -B | -0 |
                    -l[oops] { maximum-addr-flush-attempts } |
                    -o[neline] | -t[imestamp] | -b[atch] [filename] |
                    -rc[vbuf] [size]}
```

**Comment by maisem** [comment] 2021-10-17 16:36
@ThomasDalla can you share the kernel version of your machine?

Looks like a dupe of #2922

**Comment by ThomasDalla** [comment] 2021-10-17 16:39
Looks like it yes.

Kernel version was in my original post:
```
Linux NAS916 3.10.105 #25556 SMP Sat Aug 28 02:13:34 CST 2021 x86_64 GNU/Linux synology_braswell_916+
```

Any particular command I can run for more details you might want?

**Comment by ThomasDalla** [comment] 2021-10-18 17:41
DSM6.

**Closed as completed** 2021-10-18 18:03 UTC
