### ISSUE TITLE
FR: Add install.sh support for VenusOS ARM 64 bit

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#8199] opened 2023-05-24 17:20 UTC
### What are you trying to do?

OS=other-linux
VERSION= Victron Venus OS
PACKAGETYPE= opkg
UNAME=Linux raspberrypi2 5.10.110-rpi-venus-3 #1 SMP Wed Apr 12 23:30:20 UTC 2023 armv7l GNU/Linux

**Comment by DentonGentry** [comment] 2023-05-24 17:24
It looks like VenusOS is built on OpenWRT, which means I think this would be covered when https://github.com/tailscale/tailscale/issues/6252 is done.

https://github.com/tailscale/tailscale/issues/6252 in turn needs https://github.com/tailscale/tailscale/issues/391, which we're working on now.

Duplicate of https://github.com/tailscale/tailscale/issues/6252

**Closed by DentonGentry** 2023-05-24 17:24 UTC
Labels: needs-triage, fr

**Comment by Mike-Bou** [comment] 2023-05-26 08:54
i did get it working fine, from the static package. Only problem was started tailscaled from ssh login, ( a rat ate through my flat network cable ) so when my WiFi turned off at night the DNS was left unresolved. Am using the VenusOS with an external USD SSD, and rsync to backup a M1 MacBook. So having vpn is useful. A x86 Hacintosh also is easy to connect with tailscale. its a DNS Server, with Adguard. A Cloudflare Tunnel provides access to my webserver.
Anything else: My M1 MacBook is usually connected via Cloudflare WARP, which is incompatible with Tailscale.
Thanks.
