### ISSUE TITLE
Failed to get cert on Synology

### ISSUE THREAD

**Issue by JrRayz** [tailscale/tailscale#4060] opened 2022-03-03 17:18 UTC
### What is the issue?

My win10 device can get the cert file successfully, but the Synology failed...
Running the command on Synology:
```
root@myNas:~# tailscale cert                                                                                                                                    
Usage: tailscale cert [flags] <domain>
For domain, use "mynas.****.ts.net".

root@myNas:~# tailscale cert mynas.****.ts.net
unexpected output: no delimiter

```

### Steps to reproduce

Run `tailscale cert <domain>` on a Synology device.  
Then it returns
 `unexpected output: no delimiter`

### OS

Synology

### OS version

DSM6

### Tailscale version

1.22.0

### Bug report

BUG-4107f35d6ef47f772854e72ba476b9a07037c6ddfc410801bf5c252697827bcb-20220303170343Z-096b0250aa682d28

**Comment by bradfitz** [comment] 2022-03-03 18:46
@JrRayz, interesting.

What do you see when you run:

```
$ curl -v --unix-socket /var/packages/Tailscale/var/tailscaled.sock http://foo/localapi/v0/cert/mynas.****.ts.net?type=pair
```

Be sure to redact the `BEGIN EC PRIVATE KEY` section, if any.

**Comment by JrRayz** [comment] 2022-03-04 02:34
> @JrRayz, interesting.
> 
> What do you see when you run:
> 
> ```
> $ curl -v --unix-socket /var/packages/Tailscale/var/tailscaled.sock http://foo/localapi/v0/cert/mynas.****.ts.net?type=pair
> ```
> 
> Be sure to redact the `BEGIN EC PRIVATE KEY` section, if any.


Hi, I get this message
`curl: (7) Error`

**Comment by bradfitz** [comment] 2022-03-04 14:10
@JrRayz, I think that's a permission issue. Can you re-run as root or with `sudo curl ...` ?

**Comment by JrRayz** [comment] 2022-03-04 14:57
> @JrRayz, I think that's a permission issue. Can you re-run as root or with `sudo curl ...` ?

Thanks for replying, but I did run it as root, like this

```
root@myNas:~# tailscale cert
Usage: tailscale cert [flags] <domain>
For domain, use "mynas.****.ts.net".

root@myNas:~# tailscale cert mynas.****.ts.net
unexpected output: no delimiter

root@myNas:~# curl -v --unix-socket /var/packages/Tailscale/var/tailscaled.sock http://foo/localapi/v0/cert/mynas.****.ts.net?type=pair                       
curl: (7) Error
```

**Comment by bradfitz** [comment] 2022-03-04 15:09
Oh, you're using DSM6, so use `/var/packages/Tailscale/etc/tailscaled.sock` instead.

Try that?

**Comment by JrRayz** [comment] 2022-03-04 15:20
That's right,  I can see the message now

```
root@myNas:~# curl -v --unix-socket /var/packages/Tailscale/etc/tailscaled.sock http://foo/localapi/v0/cert/mynas.****.ts.net?type=pair                       
> GET /localapi/v0/cert/mynas.****.ts.net?type=pair HTTP/1.1
> Host: foo
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< Tailscale-Version: 1.22.0-t4e0b00ad8
< X-Content-Type-Options: nosniff
< Date: Fri, 04 Mar 2022 15:13:52 GMT
< Content-Length: 23
< 
failed to get cert dir

```

**Comment by davidosomething** [comment] 2022-03-04 15:21
i get the same 500 error from curl ^
one thing i wonder is if `/var/packages/Tailscale/scripts/start-stop-status` should be using `statedir` param as in https://github.com/tailscale/tailscale/issues/2932

**Comment by kverb** [comment] 2022-03-04 22:50
What do your TS logs indicate?  I've got the same problem trying to issue a ts cert on my "exit" node, which also happens to be my AdGuard DNS node. With all the velocity of changes happening to DNS on TS, i should probably separate those systems. But anyways,`journalctl -ru tailscaled` shows DNS errors in my case: 

```
Mar 04 17:25:45 exit tailscaled[92674]: cert("exit.ratfish-<redacted>.ts.net"): getCertPEM: acme.GetReg: Get "https://acme-v02.api.letsencrypt.org/directory": dial tcp: lookup acme-v02.>
Mar 04 17:25:40 exit tailscaled[92674]: [RATELIMIT] format("dns: error: %v")
Mar 04 17:25:40 exit tailscaled[92674]: dns: error: upstream nameservers not set
```

On this node, `/etc/resolve.conf` had the nameserver line set to `100.100.100.100`. I did have both "magic DNS" enabled, and "override local DNS" in the tailscale admin pages. However, this node was started with `tailscale up --advertise-exit-node  --accept-dns=false` . I assumed with the latest 1.22 changes to DNS, that `--accept-dns=false` would allow me to continue using adguard with how my exit node worked in  TS 1.18.

Here's what ended up working for me:

- disable magic DNS
- disable "override local DNS" (idk if this is mutually exclusive with above)
- manually edit `/etc/resolve.conf` to use `1.1.1.1` instead of TS's `100.100.100.100`. 
- cert is issued without problems

[rant] FWIW, everything was working great on tailscale v1.18. I had "magic DNS" enabled, and "override local DNS" nameservers were pointing to the adguard exit node TS IP address.  I could enable "use exit node" on my iOS device, pick the exit node with adguard, and i enjoyed proxied internet traffic without ads. TS v1.20 or 21 totally broke exit node internet traffic, so i downgraded to 1.18. Now that 1.22 is out, proxied exit node internet traffic seems to work again, but all kinds of DNS issues have been cropping up. It's been whack-a-mole just trying to get things straight and toggling the magic DNS switches has sort of helped, but clearly things are not configured 100% on my end. To make matters worse,  the myriad KB articles, [blog posts](https://tailscale.com/blog/sisyphean-dns-client-linux/), forum / reddit posts are not steering users in a uniformly correct direction, especially now that certain behaviors have been "corrected".

**Comment by JrRayz** [comment] 2022-03-06 14:08
@kverb Sorry for replying late, I disable the magic DNS following your suggestions but, it doesn't work for me. 
I wonder that [this blog ](https://tailscale.com/kb/1153/enabling-https/) says the `mynas.****.ts.net`  should be accessed with magic DNS, how do you access your device when the magic DNS is disabled.

**Comment by DentonGentry** [comment] 2022-03-06 14:14
@kverb The main work being done on Linux DNS support now is trying to better handle the myriad ways that DNS on Linux can be configured:
- systemd-resolved, or NetworkManager, or NetworkManager configuring systemd-resolved, or the long tail of {openresolv, dnsmasq, etc}
- working around behaviors specific to certain older versions of systemd-resolved or NetworkManager which are still in common use
- with or without an exit node.

If you found 1.18 to work stably in your environment, you're welcome to continue using it. The combinatorial space of all of those options is large, and certain portions of it have been working well for a while. Your environment may be in the part of that space which has been working well for a while.

**Comment by kverb** [comment] 2022-03-06 14:15
@JrRayz Firstly, I would confirm that the cause of your cert issues is the same as mine, by checking your `tailscaled` logs (should be able to see the systemd journal with `journalctl -ru tailscaled`). 

If you are using SSH or similar to access a shell for your synology, you can either use the TS IP address (100.XXX.YYY.ZZZ) directly ( `ssh <user>@100.XXX.YYY.ZZZ`), or keep magic DNS enabled, ssh in (`ssh <user>@mynas.****.ts.net`), then toggle the magic DNS features off. But again, I would only do this if you can confirm that the issue is related to the `tailscale cert` command failing due to a DNS resolution error when calling the ACME/letsEncrypt http api.

**Comment by kverb** [comment] 2022-03-06 14:38
@DentonGentry although I rant (and apologies for threadjacking), believe me I completely understand and appreciate your comment. The TS blog post I referenced does a great job of explaining the complexity involved (I learned a lot from it!).
What gets harder, now, however, is searching for solutions to problems, especially for users new to tailscale. If you have one set of users (e.g. sticking to 1.18), extolling the virtues of TS saying "this works great! go download tailscale and happy networking") without mentioning these complexities, I predict new users are going to get frustrated when things don't work as they expected or like they had been told.
I've been a TS fanboy for the last 4 or 5 months, and while I am still enamoured with the software, it's been quite an exercise to piece together information from reddit, forums, github, knowledge base, blog posts, just to understand how the software **should** work.

**Comment by galactorus83** [comment] 2022-03-11 09:56
@kverb I totally agree with you!
I am new to Tailscale, and I couldn't configure HTTPS to access my Synology device due to the same issue discussed in this thread.
I also tried with v1.18 but no luck.
I hope this cert issue will get solved soon.
I have https all over the place in my Synology device, I simply cannot have my browser always warn me of refuse my connection through Tailscale because https is not enabled...

**Comment by galactorus83** [comment] 2022-06-09 11:24
Did anyone find a solution to this issue?
I have tried v1.26 on DSM6 but still getting `500 Internal Server Error: failed to get cert dir`

**Comment by iangelov** [comment] 2022-06-09 11:57
[This](https://github.com/tailscale/tailscale/issues/4322#issuecomment-1109803147) worked for me

**Comment by ping13** [comment] 2022-07-09 12:46
I had the same problem and this is what I did, I have v1.26 on DSM6:

In `/var/packages/Tailscale/scripts`, I edited the file `start-stop-status` to include the flag `—statedir`: 

The diff between old and edited file (`diff start-stop-status start-stop-status~`) is:
```
19d18
< --statedir=${PKGVAR} \
```

Not sure, if `$PKGVAR` is the proper directory. Then I restarted the service with

```
sudo synoservice --restart pkgctl-Tailscale
```

and I could create the certificate as described in the manual with `sudo tailscale cert <url>`.

**Comment by galactorus83** [comment] 2022-07-16 04:14
> I had the same problem and this is what I did, I have v1.26 on DSM6:
> 
> In `/var/packages/Tailscale/scripts`, I edited the file `start-stop-status` to include the flag `—statedir`:
> 
> The diff between old and edited file (`diff start-stop-status start-stop-status~`) is:
> 
> ```
> 19d18
> < --statedir=${PKGVAR} \
> ```
> 
> Not sure, if `$PKGVAR` is the proper directory. Then I restarted the service with
> 
> ```
> sudo synoservice --restart pkgctl-Tailscale
> ```
> 
> and I could create the certificate as described in the manual with `sudo tailscale cert <url>`.

Thanks a lot @ping13 ! This solution worked for me.
Now I will try to discover how to login with HTTPS on Synology iOS apps and trying to get them not to reject the connection because of an untrusted certificate.
Thanks again.

**Comment by bradfitz** [comment] 2022-07-17 19:16
Looked into this again. Random notes to myself:

On DSM6, according to https://help.synology.com/developer-guide/integrate_dsm/fhs.html, there's no SYNOPKG_PKGVAR. That was added in DSM7.

But we don't really use those much anyway.

Our start-stop-status script passes:

```
SERVICE_COMMAND="${SYNOPKG_PKGDEST}/bin/tailscaled \ 
--state=${STATE_FILE} \ 
--socket=${SOCKET_FILE} \ 
--port=$PORT"
```

We use the older `--state=` flag to `tailscaled` instead of `--statedir`.

Even if we fixed that, it's not obvious which path to use for statedir on DSM6. Basically the only choice is "etc":

```
bradfitz@ds21bi:/$ ls -l /var/packages/Tailscale/
total 52
drwxr-xr-x 2 root root  4096 Jul 15 08:26 conf
-rw-r--r-- 1 root root     0 Jul 15 08:26 enabled
lrwxrwxrwx 1 root root    32 Jul 15 08:12 etc -> /usr/syno/etc/packages/Tailscale
-rw-r--r-- 1 root root 41125 Jul 15 08:12 INFO
drwxr-xr-x 2 root root  4096 Jul 13 20:56 scripts
lrwxrwxrwx 1 root root    28 Jul 15 08:12 target -> /volume2/@appstore/Tailscale
```

But etc is a symlink to a tiny partition on DSM6:

```
bradfitz@ds21bi:/$ df -h /usr/syno/etc/packages/Tailscale
Filesystem      Size  Used Avail Use% Mounted on
/dev/md0        2.3G  1.1G  1.1G  51% /
```

So we wouldn't want to use it for the Taildrop cache directory. It might be fine for certs, but then on DSM6 to DSM7 upgrade would lose certs if we had a different default on DSM7.

**Comment by bradfitz** [comment] 2022-07-18 16:50
Okay, this'll be fixed in Tailscale 1.28.0 on DSM6. You'll need DSM6 Update 3 or higher.

**Closed** 2022-07-18 16:51 UTC
Labels: L1 Very few, P2 Aggravating, T5 Usability, OS-synology, bug

**Comment by junktrunk202** [comment] 2022-09-24 19:25
This is great to hear it's ready to go - thanks @bradfitz ! Any clue why my DSM 6 box is on DSM 6.2.4-25556 Update 6 but the most recent tailscale package is 1.22.2-220026 via Package Center? I suspect this is a question for Synology about why their package listing is out of date (I see 1.22 is from Mar but there have been many releases since then) so I'll reach out to them too.

Thank you in general for making this product so responsive to user input too BTW. Really great to see.

**Comment by DentonGentry** [comment] 2022-09-24 19:27
The Package Center is very difficult to update, we're trying to get the next update to appear in November.

I'd suggest manually loading the package downloaded from https://pkgs.tailscale.com/stable/

**Comment by junktrunk202** [comment] 2022-09-24 19:39
Thanks @DentonGentry . I'll look into that then too. Much appreciated.
