### ISSUE TITLE
Macbook Pro 2020 M1 unable to connect to the public network when tailscale is on.

### ISSUE THREAD

**Issue by dathan** [tailscale/tailscale#3856] opened 2022-02-01 03:15 UTC
### What is the issue?

Macbook Pro 2020 M1 unable to connect to the public network when tailscale is on. When I turn off tailscale, everything works. When I look at the admin console, I see that the m1 laptop connected, yet that laptop cannot reach the tailscale.com website.

Below are some logs. When context deadline exceeded is thrown, this illustrates how my laptop is unable to reach the public net.
```

default	18:55:03.822438-0800	IPNExtension	dns: error: context deadline exceeded
default	18:55:03.824291-0800	IPNExtension	dns: error: context deadline exceeded
default	18:55:03.825330-0800	IPNExtension	dns: error: context deadline exceeded
default	18:55:08.951317-0800	IPNExtension	no previous integrity acl exists; making a new one
default	18:55:08.964010-0800	IPNExtension	0x12161ae90 commited /Users/dathan/Library/Keychains/login.keychain-db.sb-e7835e26-K89bht to /Users/dathan/Library/Keychains/login.keychain-db
default	18:55:08.967099-0800	IPNExtension	Keychain.saveData: update tailscale-preferences: success, saved 779 bytes
default	18:55:08.967422-0800	IPNExtension	SetPrefs: Prefs{ra=true dns=true want=false routes=[0.0.0.0/0 ::/0] snat=true Persist{lm=[MMN7j], o=[HZhu6], n=[kBA8R] u="dathanvp@HIDDEN_EMAIL_ADDRESS"}}
default	18:55:08.968095-0800	IPNExtension	control: setPaused(true)
default	18:55:08.968133-0800	IPNExtension	Switching ipn state Running -> Stopped (WantRunning=false, nm=true)
default	18:55:08.968208-0800	IPNExtension	magicsock: SetPrivateKey called (zeroed)
default	18:55:08.968234-0800	IPNExtension	magicsock: closing connection to derp-2 (zero-private-key), age 3m33s
default	18:55:08.968271-0800	IPNExtension	magicsock: 0 active derp conns
default	18:55:08.968316-0800	IPNExtension	wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
default	18:55:08.968375-0800	IPNExtension	control: mapRoutine: paused
default	18:55:08.968475-0800	IPNExtension	control: mapRoutine: awaiting unpause
default	18:55:08.968525-0800	IPNExtension	health("overall"): error: state=Stopped, wantRunning=false
default	18:55:08.968760-0800	IPNExtension	wgengine: Reconfig: configuring router
default	18:55:08.968816-0800	IPNExtension	setRoutesFunc called
default	18:55:08.969033-0800	IPNExtension	[Extension io.tailscale.ipn.macos.network-extension]: provider set tunnel configuration to 
    tunnelRemoteAddress = <9-char-str>
    DNSSettings = {
        protocol = cleartext
        server = (
            <15-char-str>,
        )
        searchDomains = (
            <38-char-str>,
            <15-char-str>,
            <13-char-str>,
        )
        matchDomains = (
            <0-char-str>,
            <38-char-str>,
            <15-char-str>,
            <13-char-str>,
        )
        matchDomainsNoSearch = NO
    }
    MTU = 1280
default	18:55:08.970012-0800	IPNExtension	wgengine: Reconfig: configuring DNS
default	18:55:08.970050-0800	IPNExtension	dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
default	18:55:08.970072-0800	IPNExtension	dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
default	18:55:08.970101-0800	IPNExtension	dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
default	18:55:08.970124-0800	IPNExtension	setRoutesFunc called
default	18:55:08.970216-0800	IPNExtension	[Extension io.tailscale.ipn.macos.network-extension]: provider set tunnel configuration to 
    tunnelRemoteAddress = <9-char-str>
    DNSSettings = {
        protocol = cleartext
        server = ()
        searchDomains = ()
        matchDomains = (
            <0-char-str>,
        )
        matchDomainsNoSearch = NO
    }
    MTU = 1280
default	18:55:08.990830-0800	IPNExtension	magicsock: ReSTUN("link-change-minor") ignored; stopped, no private key
default	18:55:09.241740-0800	IPNExtension	magicsock: ReSTUN("link-change-minor") ignored; stopped, no private key
default	18:55:09.395677-0800	IPNExtension	control: HostInfo: {"IPNVersion":"1.20.2-t312750ddd-g2c164d9c7","BackendLogID":"454ac2852718db93360cc430573bb6470b0eccb22c79a42a85d3be998b0a78b9","OS":"macOS","OSVersion":"11.6.0","Package":"IPNExtension","DeviceModel":"MacBookPro17,1","Hostname":"dathan-m1","GoArch":"arm64","RoutableIPs":["0.0.0.0/0","::/0"],"Services":[{"Proto":"peerapi-dns-proxy","Port":1}],"NetInfo":{"MappingVariesByDestIP":false,"HairPinning":false,"WorkingIPv6":false,"WorkingUDP":true,"UPnP":false,"PMP":false,"PCP":false,"PreferredDERP":2,"DERPLatency":{"1-v4":0.4028635,"10-v4":0.380968125,"11-v4":0.527176208,"12-v4":0.405811584,"2-v4":0.363305292,"3-v4":0.528885792,"4-v4":0.507329417,"5-v4":0.536736541,"6-v4":0.603819833,"7-v4":0.475318959,"8-v4":0.496409583,"9-v4":0.375005833}}}
default	18:56:29.359571-0800	IPNExtension	^NaNM up=1643682389+1800 Sys=20.6M HeapAlloc=2.9M HeapSys=10.8M HeapIdle=6.2M HeapInuse=4.6M HeapReleased=5.7M StackInuse=1.2M StackSys=1.2M MSpanInuse=0.1M MSpanSys=0.2M BuckHashSys=1.4M GCSys=5.2M OtherSys=1.9M NumGC=376 cpuU=4995648000 cpuS=4880881000 goroutines=62
default	18:56:36.394268-0800	IPNExtension	no previous integrity acl exists; making a new one
default	18:56:36.406702-0800	IPNExtension	0x11160d700 commited /Users/dathan/Library/Keychains/login.keychain-db.sb-e7835e26-mTUe7Y to /Users/dathan/Library/Keychains/login.keychain-db
default	18:56:36.409605-0800	IPNExtension	Keychain.saveData: update tailscale-preferences: success, saved 778 bytes
default	18:56:36.409948-0800	IPNExtension	SetPrefs: Prefs{ra=true dns=true want=true routes=[0.0.0.0/0 ::/0] snat=true Persist{lm=[MMN7j], o=[HZhu6], n=[kBA8R] u="dathanvp@HIDDEN_AGAIN"}}
default	18:56:36.410439-0800	IPNExtension	transitioning to running; doing Login...
default	18:56:36.410470-0800	IPNExtension	control: client.Login(false, 0)
default	18:56:36.410500-0800	IPNExtension	control: setPaused(false)
default	18:56:36.410526-0800	IPNExtension	Switching ipn state Stopped -> Starting (WantRunning=true, nm=true)
default	18:56:36.410573-0800	IPNExtension	control: mapRoutine: unpaused
default	18:56:36.410659-0800	IPNExtension	control: mapRoutine: state:authenticated
default	18:56:36.410782-0800	IPNExtension	control: authRoutine: state:authenticated; wantLoggedIn=true
default	18:56:36.410846-0800	IPNExtension	control: direct.TryLogin(token=false, flags=0)
default	18:56:36.410900-0800	IPNExtension	magicsock: SetPrivateKey called (init)
default	18:56:36.410937-0800	IPNExtension	magicsock: private key changed, reconnecting to home derp-2
default	18:56:36.411006-0800	IPNExtension	magicsock: adding connection to derp-2 for home-keep-alive
default	18:56:36.411087-0800	IPNExtension	control: doLogin(regen=false, hasUrl=false)
default	18:56:36.411166-0800	IPNExtension	wgengine: Reconfig: configuring userspace wireguard config (with 0/1 peers)
default	18:56:36.411267-0800	IPNExtension	magicsock: 1 active derp conns: derp-2=cr0s,wr0s
default	18:56:36.411381-0800	IPNExtension	derphttp.Client.Recv: connecting to derp-2 (sfo)
default	18:56:36.412137-0800	IPNExtension	control: RegisterReq: onode=[HZhu6] node=[kBA8R] fup=false
default	18:56:36.413402-0800	IPNExtension	wgengine: Reconfig: configuring router
default	18:56:36.413450-0800	IPNExtension	setRoutesFunc called
default	18:56:36.413711-0800	IPNExtension	[Extension io.tailscale.ipn.macos.network-extension]: provider set tunnel configuration to 
    tunnelRemoteAddress = <9-char-str>
    DNSSettings = {
        protocol = cleartext
        server = ()
        searchDomains = ()
        matchDomains = (
            <0-char-str>,
        )
        matchDomainsNoSearch = NO
    }
    IPv4Settings = {
        configMethod = PPP
        addresses = (
            <14-char-str>,
        )
        subnetMasks = (
            255.255.255.255,
        )
        includedRoutes = (
            {
                destinationAddress = <13-char-str>
                destinationSubnetMask = 255.255.255.255
            },
            {
                destinationAddress = <15-char-str>
                destinationSubnetMask = 255.255.255.255
            },
        )
        overridePrimary = NO
    }
    IPv6Settings = {
        configMethod = automatic
        addresses = (
            <39-char-str>,
        )
        networkPrefixLengths = (
            48,
        )
        includedRoutes = (
            {
                destinationAddress = <16-char-str>
                destinationNetworkPrefixLength = 48
            },
        )
    }
    MTU = 1280
default	18:56:36.414144-0800	IPNExtension	wgengine: Reconfig: configuring DNS
default	18:56:36.414186-0800	IPNExtension	dns: Set: {DefaultResolvers:[100.66.154.2:53 100.75.241.10:53] Routes:{dathanvp.gmail.com.beta.tailscale.net.:[] origin.joinnet.:[100.66.154.2:53 100.75.241.10:53] work.joinnet.:[100.66.154.2:53 100.75.241.10:53]}+65arpa SearchDomains:[dathanvp.hidden.hidden.beta.tailscale.net. origin.joinnet. work.joinnet.] Hosts:2}
default	18:56:36.414221-0800	IPNExtension	dns: Resolvercfg: {Routes:{.:[100.66.154.2:53 100.75.241.10:53] origin.joinnet.:[100.66.154.2:53 100.75.241.10:53] work.joinnet.:[100.66.154.2:53 100.75.241.10:53]} Hosts:2 LocalDomains:[dathanvp.hidden.hidden.beta.tailscale.net.]+65arpa}
default	18:56:36.414246-0800	IPNExtension	dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[dathanvp.gmail.com.beta.tailscale.net. origin.joinnet. work.joinnet.] MatchDomains:[]}
default	18:56:36.414288-0800	IPNExtension	setRoutesFunc called
default	18:56:36.414463-0800	IPNExtension	[Extension io.tailscale.ipn.macos.network-extension]: provider set tunnel configuration to 
    tunnelRemoteAddress = <9-char-str>
    DNSSettings = {
        protocol = cleartext
        server = (
            <15-char-str>,
        )
        searchDomains = (
            <38-char-str>,
            <15-char-str>,
            <13-char-str>,
        )
        matchDomains = (
            <0-char-str>,
            <38-char-str>,
            <15-char-str>,
            <13-char-str>,
        )
        matchDomainsNoSearch = NO
    }
    IPv4Settings = {
        configMethod = PPP
        addresses = (
            <14-char-str>,
        )
        subnetMasks = (
            255.255.255.255,
        )
        includedRoutes = (
            {
                destinationAddress = <13-char-str>
                destinationSubnetMask = 255.255.255.255
            },
            {
                destinationAddress = <15-char-str>
                destinationSubnetMask = 255.255.255.255
            },
        )
        overridePrimary = NO
    }
    IPv6Settings = {
        configMethod = automatic
        addresses = (
            <39-char-str>,
        )
        networkPrefixLengths = (
            48,
        )
        includedRoutes = (
            {
                destinationAddress = <16-char-str>
                destinationNetworkPrefixLength = 48
            },
        )
    }
    MTU = 1280
default	18:56:36.414793-0800	IPNExtension	peerapi: serving on http://100.110.136.40:34177
default	18:56:36.414855-0800	IPNExtension	peerapi: serving on http://[fd7a:115c:a1e0:ab12:4843:cd96:626e:8828]:34177
default	18:56:36.415214-0800	IPNExtension	control: HostInfo: {"IPNVersion":"1.20.2-t312750ddd-g2c164d9c7","BackendLogID":"454ac2852718db93360cc430573bb6470b0eccb22c79a42a85d3be998b0a78b9","OS":"macOS","OSVersion":"11.6.0","Package":"IPNExtension","DeviceModel":"MacBookPro17,1","Hostname":"dathan-m1","GoArch":"arm64","RoutableIPs":["0.0.0.0/0","::/0"],"Services":[{"Proto":"peerapi4","Port":34177},{"Proto":"peerapi6","Port":34177},{"Proto":"peerapi-dns-proxy","Port":1}],"NetInfo":{"MappingVariesByDestIP":false,"HairPinning":false,"WorkingIPv6":false,"WorkingUDP":true,"UPnP":false,"PMP":false,"PCP":false,"PreferredDERP":2,"DERPLatency":{"1-v4":0.4028635,"10-v4":0.380968125,"11-v4":0.527176208,"12-v4":0.405811584,"2-v4":0.363305292,"3-v4":0.528885792,"4-v4":0.507329417,"5-v4":0.536736541,"6-v4":0.603819833,"7-v4":0.475318959,"8-v4":0.496409583,"9-v4":0.375005833}}}
default	18:56:36.416364-0800	IPNExtension	Switching ipn state Starting -> Running (WantRunning=true, nm=true)
default	18:56:36.496494-0800	IPNExtension	magicsock: derp-2 connected; connGen=1
default	18:56:36.602355-0800	IPNExtension	control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
default	18:56:36.602627-0800	IPNExtension	control: No AuthURL
default	18:56:36.603152-0800	IPNExtension	control: authRoutine: state:authenticated; goal=nil paused=false
default	18:56:36.605894-0800	IPNExtension	control: mapRoutine: state:authenticated
default	18:56:36.795339-0800	IPNExtension	health("overall"): ok
default	18:56:42.226042-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:42.226439-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:42.226999-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:42.663692-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:42.664021-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:42.819319-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:42.822202-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:42.842833-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:42.843034-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:42.843126-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:42.843214-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:42.843300-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:42.843477-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:42.843647-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:42.843863-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:43.240081-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:43.240365-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:43.240461-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:43.707634-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:43.707995-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:43.859493-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:43.859877-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:43.860024-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:43.860553-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:43.860671-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:43.860795-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:43.860964-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:43.861048-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:43.861133-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:43.861216-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:44.851742-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:44.852139-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.338268-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.338941-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.339045-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.715235-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.715671-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.895265-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.895431-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.895473-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.895512-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.895700-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.896048-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.896244-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.896302-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.897819-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.897900-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.897943-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:45.897980-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:46.190500-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:46.190916-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:46.191385-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:46.206595-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:46.206815-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:46.206902-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:47.233226-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:47.233521-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:47.233639-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:47.233943-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:47.234869-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:47.234951-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:47.984862-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:47.985109-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:49.162543-0800	IPNExtension	no previous integrity acl exists; making a new one
default	18:56:49.180010-0800	IPNExtension	0x11161f490 commited /Users/dathan/Library/Keychains/login.keychain-db.sb-e7835e26-7iPPnD to /Users/dathan/Library/Keychains/login.keychain-db
default	18:56:49.183628-0800	IPNExtension	Keychain.saveData: update tailscale-preferences: success, saved 779 bytes
default	18:56:49.183971-0800	IPNExtension	SetPrefs: Prefs{ra=true dns=true want=false routes=[0.0.0.0/0 ::/0] snat=true Persist{lm=[MMN7j], o=[HZhu6], n=[kBA8R] u="dathanvp@HIDDEN_EMAIL_AGAIN"}}
default	18:56:49.184629-0800	IPNExtension	control: setPaused(true)
default	18:56:49.184675-0800	IPNExtension	Switching ipn state Running -> Stopped (WantRunning=false, nm=true)
default	18:56:49.184919-0800	IPNExtension	control: mapRoutine: paused
default	18:56:49.185200-0800	IPNExtension	control: mapRoutine: awaiting unpause
default	18:56:49.185260-0800	IPNExtension	magicsock: SetPrivateKey called (zeroed)
default	18:56:49.185297-0800	IPNExtension	magicsock: closing connection to derp-2 (zero-private-key), age 13s
default	18:56:49.185333-0800	IPNExtension	magicsock: 0 active derp conns
default	18:56:49.185384-0800	IPNExtension	wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
default	18:56:49.185724-0800	IPNExtension	health("overall"): error: state=Stopped, wantRunning=false
default	18:56:49.186436-0800	IPNExtension	wgengine: Reconfig: configuring router
default	18:56:49.186486-0800	IPNExtension	setRoutesFunc called
default	18:56:49.186670-0800	IPNExtension	[Extension io.tailscale.ipn.macos.network-extension]: provider set tunnel configuration to 
    tunnelRemoteAddress = <9-char-str>
    DNSSettings = {
        protocol = cleartext
        server = (
            <15-char-str>,
        )
        searchDomains = (
            <38-char-str>,
            <15-char-str>,
            <13-char-str>,
        )
        matchDomains = (
            <0-char-str>,
            <38-char-str>,
            <15-char-str>,
            <13-char-str>,
        )
        matchDomainsNoSearch = NO
    }
    MTU = 1280
default	18:56:49.186764-0800	IPNExtension	wgengine: Reconfig: configuring DNS
default	18:56:49.186798-0800	IPNExtension	dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
default	18:56:49.186821-0800	IPNExtension	dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
default	18:56:49.186846-0800	IPNExtension	dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
default	18:56:49.186866-0800	IPNExtension	setRoutesFunc called
default	18:56:49.186934-0800	IPNExtension	[Extension io.tailscale.ipn.macos.network-extension]: provider set tunnel configuration to 
    tunnelRemoteAddress = <9-char-str>
    DNSSettings = {
        protocol = cleartext
        server = ()
        searchDomains = ()
        matchDomains = (
            <0-char-str>,
        )
        matchDomainsNoSearch = NO
    }
    MTU = 1280
default	18:56:49.208005-0800	IPNExtension	magicsock: ReSTUN("link-change-minor") ignored; stopped, no private key
default	18:56:49.330481-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:49.332487-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:49.332582-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:49.332626-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:49.332664-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:49.332701-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:49.381978-0800	IPNExtension	control: HostInfo: {"IPNVersion":"1.20.2-t312750ddd-g2c164d9c7","BackendLogID":"454ac2852718db93360cc430573bb6470b0eccb22c79a42a85d3be998b0a78b9","OS":"macOS","OSVersion":"11.6.0","Package":"IPNExtension","DeviceModel":"MacBookPro17,1","Hostname":"dathan-m1","GoArch":"arm64","RoutableIPs":["0.0.0.0/0","::/0"],"Services":[{"Proto":"peerapi-dns-proxy","Port":1}],"NetInfo":{"MappingVariesByDestIP":false,"HairPinning":false,"WorkingIPv6":false,"WorkingUDP":true,"UPnP":false,"PMP":false,"PCP":false,"PreferredDERP":2,"DERPLatency":{"1-v4":0.4028635,"10-v4":0.380968125,"11-v4":0.527176208,"12-v4":0.405811584,"2-v4":0.363305292,"3-v4":0.528885792,"4-v4":0.507329417,"5-v4":0.536736541,"6-v4":0.603819833,"7-v4":0.475318959,"8-v4":0.496409583,"9-v4":0.375005833}}}
default	18:56:49.465992-0800	IPNExtension	magicsock: ReSTUN("link-change-minor") ignored; stopped, no private key
default	18:56:49.510843-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:49.510974-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:49.511200-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:49.807980-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:49.808549-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:50.071420-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:50.071664-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:50.071743-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:50.072009-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:50.072062-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:50.072107-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:50.072149-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:50.072187-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:50.072228-0800	IPNExtension	dns: error: context deadline exceeded
default	18:56:50.072268-0800	IPNExtension	dns: error: context deadline exceeded
```

### Steps to reproduce

I recently upgraded my personal laptop to a mac book pro 16 GB, 2020 version 11.6

My upgrade path was backup my old 2015 mac and restore on my new 2020 mac. Both my old mac and new mac are still connected to the same network. The old one sleeps often, but probes the network from time to time. 

After re-installing the tailscale client and re-authing on the m1, nothing worked. I removed the old auth entry for the same laptop name, re-auth, everything workds. The next day connecting to tailscale freezes up my public connections. So, doing the same work around of re-authing did not work today.

I am not sure that this is reproducible from tailscales end. Tailscale could attempt to follow my upgrade path, but that's a lot of effort and there is probably another method.

### Are there any recent changes that introduced the issue?

ran the os update to the latest patch

### OS

macOS

### OS version

11.6

### Tailscale version

1.20.2

### Bug report

BUG-454ac2852718db93360cc430573bb6470b0eccb22c79a42a85d3be998b0a78b9-20220201030808Z-ac38d0e8f39c20f3

**Comment by DentonGentry** [comment] 2022-02-01 03:50
I suspect the root cause is still related to having cloned the keys.

To resolve this I'd recommend clearing the Tailscale state on the new laptop, and letting it create a new identity for itself. To do this you can use Applications > Utilities > Keychain Access and use the search box in the upper right to search for "tailscale".

There is a set of selections across the top for "All Items", "Passwords", "Secure Notes", etc. The ones you are looking for are in Passwords.

They are named:
- tailscale-daemon
- tailscale-logdata
- tailscale-machinekey
- tailscale-preferences

Quit the Tailscale app, remove those four items from Keychain Access, and then start the Tailscale app again. It should recover and let you log in again. The new Mac will get its own IP address.

Depending on how the old Mac was configured you may only see three of the items. That is fine, just remove those three.

**Comment by rayqusa** [comment] 2022-02-06 13:36
easy, add public dns on your magic dns. e.g 8.8.8.8

it happen on me

**Comment by DentonGentry** [comment] 2022-05-08 00:33
I'm going to close this on the assumption that the cloned keys were the issue. If it is still not working, please re-open.

**Closed by DentonGentry** 2022-05-08 00:33 UTC
Labels: OS-macos, L1 Very few, P3 Can't get started, T6 Major usability, waiting-for-info, bug
