### ISSUE TITLE
FR: Show the exit node in the persistent notification or Quick Settings tile on Android

### ISSUE THREAD

**Issue by praneetloke** [tailscale/tailscale#4642] opened 2022-05-08 18:11 UTC
### What are you trying to do?

I'd like to see quickly from the notification that the app creates which exit node I am currently using (if any.) It would be great to have this support for the Quick Settings tile as well as Android Tile supports a content description too. (Maybe iOS could use something like this too? I haven't see the app on iOS.)

### How should we solve this?

If I could see the exit node ID in the notification content and the Quick Settings Tile description, that would be great!

### What is the impact of not solving this?

User experience is not ideal right now. I have to launch the app to see which exit node I am currently using, if at all. That is, there is no difference in the notification when I _am_ using an exit node vs. when I am _not_ using an exit node.

### Anything else?

I have a [fork](https://github.praneetloke/tailscale-android) in which I have made changes to support the display of the exit node ID in the notification content. However, it has the following bugs. Feel free to use any or no part of my fork. I was originally planning to submit a PR against the `tailscale-android` repo but unfortunately having run into bugs with my changes I don't believe it would be too helpful. Perhaps it could give someone somewhat of a start...

- When I start the VPN with no exit node selected but then select one after the fact, the notification does not update itself. If I toggle the status of the VPN then the notification correctly shows the exit node ID.
- When I choose `None` for exit node, the notification does not update itself. Moreover, when I toggle the status of the VPN the notification still has the exit node ID. I have to kill the Tailscale app and re-launch to get the correct notification. Killing the app and re-launching doesn't seem to require me to toggle the VPN on/off. Simply restarting the app seems to work.

**Comment by DentonGentry** [comment] 2022-05-08 19:25
I'm going to mark this as a duplicate of https://github.com/tailscale/tailscale/issues/4383, but noted the existence of the repository.

**Closed by DentonGentry** 2022-05-08 19:25 UTC
Labels: needs-triage, fr
