### ISSUE TITLE
Use the app icon on iOS to represent connection status 

### ISSUE THREAD

**Issue by rmvdesign** [tailscale/tailscale#9278] opened 2023-09-07 12:17 UTC
### What are you trying to do?

Much like an unlit logo means disconnected, a lit logo means connected, and the little arrow means Exit Node Connected, you could implement these easily with the icon changing feature in SwiftUI. Entirely a cosmetic change, but it could be pretty cute. 

### How should we solve this?

Use the SwiftUI app icon changing feature to indicate when the connection status changes. 

### What is the impact of not solving this?

It wouldn’t be as cute.

**Comment by agottardo** [comment] 2023-09-07 17:05
Duplicate of #935. We cannot do this, Apple APIs do not allow apps to change their icon without showing a prominent alert banner to the user.

**Closed by agottardo** 2023-09-07 17:05 UTC
Labels: needs-triage, fr
