### ISSUE TITLE
FR: Create groups of DNS server settings which can be used indivdually on a device/user basis. 

### ISSUE THREAD

**Issue by zooper** [tailscale/tailscale#9540] opened 2023-09-26 13:37 UTC
### What are you trying to do?

Add flexibility for the devices/users in the same tailnet to use different DNS settings.
Maybe not all devices/users should have splitdns, while others should. 

Reasoning behind this:
Split-dns zone: site.foo.bar

For client A I want
system.site.foo.bar A 10.0.0.01

For client B I want:
system.site.foo.bar A 1.1.1.1 

Client B has limited access  (b/c firewalls ) and can therefor not reach most of the destinations returned returned back from the split-dns server and that breaks the experience for client B. 
A public resolvers would instead return public ip's for that particular query, which would be reachable by client B as well.

### How should we solve this?

Have the DNS settings being groups/profiles instead which you refer to.

Let's say 
Group: **Default**
Global dns server: 8.8.8.8

Group: **Custom1**
Global dns server: 8.8.8.8
Split-dns: site.foo.bar : 1.1.1.1

Then use an ACL similar to what's already being done with NextDNS

```
    {
        "acls": ["..."],
        "nodeAttrs": [
            {
                "target": ["client-a"],
                "attr": [
                    "dnsgroup:Custom1",
                ],
            },
        ],
    }
```

So any device/user that doesn't have a nodeAttrs would use the **Default** group instead while Client-A in this case would get it's DNS settings from **Custom1**

### What is the impact of not solving this?

Users have to disconnect from the vpn, or their privileges must be over-provisioned for them to be able to reach the service.

### Anything else?

Might be an edge-case, but I believe in the flexibility this could add to the product.

**Comment by DentonGentry** [comment] 2023-09-26 13:48
Duplicate of https://github.com/tailscale/tailscale/issues/6125

**Closed by DentonGentry** 2023-09-26 13:48 UTC
Labels: needs-triage, fr
