### ISSUE TITLE
Allow mapping subnets or individual hosts on subnets to Tailscale addresses and MagicDNS names

### ISSUE THREAD

**Issue by tlrobinson** [tailscale/tailscale#2931] opened 2021-09-25 21:12 UTC
It would be great if you could map two overlapping subnets to different Tailscale internal 100.x.y.z subnets, or at least individual hosts on that subnet, as well as MagicDNS names for hosts on those subnets.

Related to #2337

**Comment by DentonGentry** [comment] 2021-09-25 21:16
NAT of subnets is possible, though we wouldn't map them to 100.x.y.z addresses they'd map to something else. Unique IPv6 ranges for each overlapping IPv4 subnet is also possible.

Duplicate of https://github.com/tailscale/tailscale/issues/826

**Closed by DentonGentry** 2021-09-25 21:16 UTC
Labels: needs-triage
