### ISSUE TITLE
net/dns: actively watch, update /etc/resolv.conf on Linux with direct manager

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3956] opened 2022-02-16 18:31 UTC
One of my Debian Bullseye servers doesn't have systemd-resolved and something on the machine (presumably `dhclient` from package `isc-dhcp-client`) rewrites the `/etc/resolv.conf` file regularly (on DNS renewal?).

I then have to restart tailscaled to get MagicDNS working again.

We should actively monitor it.

I thought we had a bug for this but I couldn't find it.

/cc @danderson

**Comment by danderson** [comment] 2022-02-16 18:32
Yes, on a system with no DNS facilities at all, we're not that good at fighting for DNS supremacy. As a quick workaround, installing resolvconf should get both dhclient and tailscale to play nice with each other (and by that I mean tailscale hacks up resolvconf to ensure it always wins)

**Comment by DentonGentry** [comment] 2022-03-27 06:06
Duplicate of https://github.com/tailscale/tailscale/issues/2334

**Closed by DentonGentry** 2022-03-27 06:06 UTC
Labels: OS-linux, dns
