### ISSUE TITLE
Windows 10 Machines behind a strict firewall can't receive connections

### ISSUE THREAD

**Issue by Xe** [tailscale/tailscale#1274] opened 2021-02-05 15:40 UTC
**Describe the bug**
When a Windows 10 machine is behind a strict firewall (KVM NAT or Hyper-V NAT), it does not receive incoming connections until the machine behind the firewall makes a connection to the machine that is trying to connect to it. It feels like the source machine cannot punch through to the target machine behind the firewall (though I am unsure why it doesn't just fall back to the DERP relay).

**To Reproduce**
Steps to reproduce the behaviour:
1. Install libvirtd KVM or Hyper-V on Windows
2. Set up a Windows 10 VM on that hypervisor
3. Ensure that VM is behind nat somehow
4. Install Tailscale on that VM
5. Set up RDP on that VM
6. Try to connect to that VM using RDP over Tailscale
7. Eternal hang

**Expected behaviour**
I expected RDP to work.

**Screenshots**

**Version information:**
 - Device: VM behind NAT
 - OS: Windows 10 (though other OSes may actually be affected, I can only replicate this reliably on Windows 10)
 - OS version: Windows 10
 - Tailscale version: 1.4.0

**Additional context**
It can be worked around by having the VM behind the firewall do a continuous ping (`ping -t`) to the source machine that wants to connect over RDP.

**Workaround:**
- Start ping from remote to the local machine. (initiate the outbound connection from a remote machine.)
- Try RDP to VM from the local machine.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2rjv5)

**Comment by bradfitz** [comment] 2021-02-05 15:51
My Windows VMs at home (running on Linux KVM) are behind NAT and don't hit this. I can RDP to them remotely.

What's a logid for one of yours where you can reproduce this?

**Comment by Xe** [comment] 2021-02-05 16:13
VM: f6ec2cbeea211e7a2d404669d002e377ddc834594ec98cbc610d239a664aab40,be16d6f9bd90d3159841426a67ef28f9c6ef2958b3e6cef65d09444a3aba3be2
Non-VM machine: 130e298a6aa8d9f752ca711f8b1ba370c97cbafaddb9a3e6ac599b98c09cee35,00e86d2b022c1ef11a5b6c5995181842b2df94911e59017363fd8863e24a1f89

**Comment by bradfitz** [comment] 2021-02-08 21:37
@Xe, we need times to look at logs, otherwise it's like looking for a needle in a haystack.

And then what doesn't work at that time? Ping? Tailscale ping?

**Comment by bradfitz** [comment] 2021-02-08 21:38
@Xe, @darshinimashar, if you easy repro steps, can you tell @peske what they are so he can work on diagnosing the problem?

**Comment by DentonGentry** [comment] 2021-02-08 21:39
Notes from bug scrub:
1. The logids are good but timestamps of what to look at is needed.
2. 1.4.x fixed several pretty wide-ranging Windows networking issues, we should make sure that is being used here.

**Comment by peske** [comment] 2021-02-10 13:41
I've tested with Windows 10 VM in Hyper-V, and couldn't reproduce. My first impression is that this issue isn't caused by virtualization, but more likely by some routing issues (i.e. wrongly configured routes somewhere in the infrastructure). But I might be wrong.

@Xe , can you please try the following:

- Start the Windows 10 VM that you want to RDP to as usual, without any _continuous `ping` patch_ you've mentioned;
- Give it some time to boot and start all the services (about one minute because networking services in Windows are in some cases slow);
- Check the machine status in the [admin console](https://login.tailscale.com/admin/machines) (and share it here);
- On another machine (from which you're trying to RDP) execute the following commands and share the output here:
  - `tailscale.exe status`
  - `tailscale.exe ping <ip-of-the-target-vm>`
  - `ping <ip-of-the-target-vm>`
- Then on the RDP target machine (the VM) execute the following: `tailscale.exe netcheck`

Thanks!

**Comment by peske** [comment] 2021-02-10 13:53
The key things that I would like to conclude from the outputs above are:

- If the Tailscale service is started on the problematic VM;
- If it's able to ping DERPs.

**Comment by bradfitz** [comment] 2021-03-02 22:14
ETIMEOUT. Closing until there's something actionable here.

**Closed by bradfitz** 2021-03-02 22:14 UTC
Labels: OS-windows
