### ISSUE TITLE
Tailscale crashes on Android (GrapheneOS)

### ISSUE THREAD

**Issue by glidingthrough** [tailscale/tailscale#11771] opened 2024-04-17 09:20 UTC
### What is the issue?

User updated Tailscale to v1.64 using Droid-ify and then Android warns that Tailscale keeps stopping.

Output details below:
```
type: crash
osVersion: google/bluejay/bluejay:14/AP1A.240405.002/2024040900:user/release-keys
package: com.tailscale.ipn:202
process: com.tailscale.ipn
processUptime: 0 + 0 ms
installer: com.looker.droidify

signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------

backtrace:
      #00 pc 0000000000526398  /data/app/~~K5YUra9JdqezZdXuxURlZA==/com.tailscale.ipn-hB2qpBGX44fb43x0Q0LMqQ==/lib/arm64/libgio.so
```

Attempts to uninstall and reinstall have been unsuccessful in fixing the issue, with both Droid-ify and F-Droid apps, and with attempts to revert to older versions.

### Steps to reproduce

In this case, just running Tailscale reproduces the issue. Cannot reproduce on near-identical phone.

### Are there any recent changes that introduced the issue?

Update to v1.64 using Droid-ify. Perhaps the update went wrong somehow and now Tailscale won't work?

### OS

Android

### OS version

14

### Tailscale version

1.64

### Other software

GrapheneOS Build Number 2024040900
ESET Security 9.0.21.0

**Comment by jeremypenner** [comment] 2024-04-17 12:13
I'm seeing this on LineageOS 21 with the last two F-Droid builds:
1.64.0-t78dc8622d-gfd2ca6fa940
1.61.105-t7429e8912-g12210d3f26b
Going three versions back to 1.58.2-tb0e1bbb62-gcd1f0649958 seems to work.

Version 1.64 from Google Play doesn't crash for me, so this seems to be an F-Droid specific problem.

**Comment by kelivel** [comment] 2024-04-17 13:27
Hi folks, this is a duplicate of https://github.com/tailscale/tailscale/issues/11719. We aren't involved in updating the F-Droid repository but there is a fix on the way, detailed in https://github.com/tailscale/tailscale/issues/11719.

**Closed** 2024-04-17 13:35 UTC
Labels: needs-triage, bug
