### ISSUE TITLE
FR: Force re-authentication after iOS device transfer/upgrade

### ISSUE THREAD

**Issue by rajiv** [tailscale/tailscale#6041] opened 2022-10-24 19:20 UTC
### What is the issue?

I upgraded from one iPhone to a new iPhone, both running iOS 16.0.3 and last connected to my tailnet using Tailscale 1.28.0. The upgrade process used the built in "Quick Start to transfer data to a new iPhone or iPad" feature documented at https://support.apple.com/en-us/HT210216. (This is a common upgrade path when purchasing a new device.) I did not wipe the old iPhone at the completion of the transfer.

Upon running Tailscale for the first time on the new iPhone, the application retained all settings and authentication to my tailnet. _Even the new phone's IP address is the same IP address of the old phone._ This seems wrong. I was able to activate Tailscale on both phone simultaneously, at which point the admin console displayed the new client version of 1.32.1, showed a warning of "Duplicate node key", and the old phone took the name of the new phone. I had to log out on both phones, remove the single machine from the admin console, and re-authenticate on both devices to clean everything up.

Ask: Tailscale should store device authentication information in the iOS storage area that is not transferred on device upgrade. Doing so would force a re-authentication, and new device identification after the data transfer to a new device.

### Steps to reproduce

- Upgrade from one iPhone to another.
- Use the built in "Quick Start to transfer data to a new iPhone or iPad" feature documented at https://support.apple.com/en-us/HT210216. 

### OS

iOS

### OS version

iOS 16.0.3

### Tailscale version

1.28.0

### Bug report

New iPhone: BUG-d65fd032d37a3dd71fbb65d8d5bf8ad29b5df12aa465a856de771404491b53a2-20221024185324Z-e9d769501074bd6e

Old iPhone: BUG-d65fd032d37a3dd71fbb65d8d5bf8ad29b5df12aa465a856de771404491b53a2-20221024185444Z-47aa9fe74a026098

**Comment by DentonGentry** [comment] 2022-10-24 23:29
Duplicate of https://github.com/tailscale/tailscale/issues/969

I understand that it probably seems obvious, of course the new device shouldn't inherit the node key of the previous.

For every person believing this, there is another person who expects the new device to replace the old — the old device will be subsequently wiped and never thought of again. So of course the new device should inherit the node key of the old.

**Comment by DentonGentry** [comment] 2022-10-26 05:04
Duplicate of https://github.com/tailscale/tailscale/issues/969

**Closed by DentonGentry** 2022-10-26 05:04 UTC
Labels: OS-ios, L2 Few, P1 Nuisance, T0 New feature, needs-triage, fr
