### ISSUE TITLE
NixOS machines with firewall management enabled can't use exit nodes

### ISSUE THREAD

**Issue by Xe** [tailscale/tailscale#4432] opened 2022-04-18 16:28 UTC
### What is the issue?

When trying to use an exit node with a NixOS machine, all traffic to the outside world stops working.

The only workaround is to disable `networking.firewall.enable`, which is on by default.

### Steps to reproduce

1. Set up a NixOS vm with all default configuration except authentication [link](https://gist.github.com/Xe/96ec8586a5341aaf7201e8b993a091a2)
2. Enable Tailscale (`services.tailscale.enable = true;`)
3. Log in to Tailscale
4. Try to use an exit node
5. The internet stops working, including log uploads

### OS

Linux

### OS version

NixOS Unstable

### Tailscale version

1.22.2

### Bug report

BUG-c0601693c68cc9f6f1c4407f8af3804f06fbc6fc192a4a9c4476ed9154bd91fd-202204141517362-552ebdf5e2c22a6d

**Comment by averagechris** [comment] 2022-04-18 16:52
Thank you for looking into this @Xe I really appreciate it!

**Comment by danderson** [comment] 2022-04-29 02:18
Okay, I just hit this myself completely at random, and so as a result I went and debugged it. TL;DR: NixOS's reverse path filtering logic is too strict, and doesn't make allowances for policy routing.

More detail: Tailscale has to be careful to avoid routing loops with itself: when we add a default route into `tailscale0` for exit node use, the traffic generated by `tailscaled` (wireguard tunnels, control plane connection...) must _not_ use that route, otherwise we'll create a routing loop where the wireguard tunnels are trying to use themselves.

To make this work, we use Linux policy routing: we place all tailscale0 related routes into route table 52, and then set up a set of policy routing rules that say: if a packet has the packet mark 0x80000, then look up routes _without_ consulting table 52, so you get a routing decision as if tailscale didn't exist. Otherwise, use table 52 in route lookups.

So, by default, packets use Tailscale routes when deciding where to go, but tailscaled can set mark 0x80000 on its "underlay" connections, and those will not loop back into tailscale0, but rather will get routed as if tailscale didn't exist.

Separately, the NixOS firewall apparently recently added reverse path filtering logic very early in the firewall ruleset:

```
$ iptables -t raw -L PREROUTING
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
nixos-fw-rpfilter  all  --  anywhere             anywhere

$ iptables -t raw -L nixos-fw-rpfilter
Chain nixos-fw-rpfilter (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere             rpfilter validmark
RETURN     udp  --  anywhere             anywhere             udp spt:bootps dpt:bootpc
RETURN     udp  --  0.0.0.0              255.255.255.255      udp spt:bootpc dpt:bootps
DROP       all  --  anywhere             anywhere
```

Roughly translated, these rules mean: for every incoming packet to the machine, do a reverse lookup and see if responses to this packet would go out on the same interface. If not (this packet arrived from a surprisingly different interface), then it's spoofed traffic and will be dropped.

The problem is that our wireguard etc. tunnels all fail this check. The packets coming in from the network don't have any packet marks, because marking is something done in netfilter or by userspace. So, the reverse route lookup _does_ include tailscale routes from table 52, and concludes "this packet arrived on eno1, but RPF lookup says it should have arrived on tailscale0", and drops the packet.

So, the second you turn on exit nodes, NixOS's reverse path filter immediately starts dropping all incoming traffic related to wireguard tunnels, tailscale's control plane connection, etc. etc.


The quick fix for NixOS users is to set the following option in your NixOS config:

```
networking.firewall.checkReversePath = "loose";
```

This will switch the reverse path check from "strict" (reverse path check must match exactly) to "loose" (there must be any route back to the source of the traffic, but not necessarily the same interface). Loose filtering is basically the only sensible option these days, so IMO the default should really be changed upstream. Blindly applying strict RPF to all traffic just doesn't work any more in modern network environments, especially desktops which usually have multiple active interfaces at once and complex things like Tailscale going on.


To fix this within Tailscale, the least we can do is detect and report it as a health issue. Going further, if we transferred the 0x80000 on outgoing packets to a connmark (a mark, but on the whole connection as seen by the kernel's conntrack subsystem), we could then reapply the connmark to _incoming_ packets and have them inherit the correct routing policies for reverse path purposes. This would be fairly fiddly, and I'm actually not sure if the nftables RPF logic obeys packet marks... But it's a possibility to experiment with, at least.

**Comment by alarsyo** [comment] 2022-05-15 17:43
Hi! Thanks for the insights into why this breaks. I have one question:

Say I have two NixOS machines, one wanting to use the other as an exit node. Would that `loose` reverse path check setting be needed on both machines, or only the exit node / only the "client" machine?

**Comment by fufexan** [comment] 2022-05-15 17:51
@alarsyo I have the setup you described. `loose` checking is only needed on the client.

**Comment by ncfavier** [comment] 2022-10-14 20:36
> Going further, if we transferred the 0x80000 on outgoing packets to a connmark (a mark, but on the whole connection as seen by the kernel's conntrack subsystem), we could then reapply the connmark to _incoming_ packets and have them inherit the correct routing policies for reverse path purposes.

:+1: this is what WireGuard (wg-quick) does. I mentioned this in [this other issue](https://github.com/tailscale/tailscale/issues/3310#issuecomment-1271412885) which looks like a duplicate.

**Comment by DentonGentry** [comment] 2022-10-15 01:46
Also related: https://github.com/tailscale/tailscale/issues/591

**Comment by DentonGentry** [comment] 2022-10-31 00:51
Remaining work on this will be tracked on https://github.com/tailscale/tailscale/issues/3310
Duplicate of https://github.com/tailscale/tailscale/issues/3310

**Closed by DentonGentry** 2022-10-31 00:51 UTC
Labels: OS-linux, L1 Very few, P2 Aggravating, T5 Usability, bug
