### ISSUE TITLE
FR: Add Japan to the support area of Mullvad Exit Nodes

### ISSUE THREAD

**Issue by Tabr3d** [tailscale/tailscale#10125] opened 2023-11-05 11:22 UTC
### What are you trying to do?

I am trying to use Mullvad exit node in Japan region .

### How should we solve this?

Please add Japan to the support area of Mullvad exit node.

### What is the impact of not solving this?

No workaround

**Comment by DentonGentry** [comment] 2023-11-05 12:37
Duplicate of https://github.com/tailscale/tailscale/issues/9314

**Closed by DentonGentry** 2023-11-05 12:37 UTC
Labels: needs-triage, fr
