### ISSUE TITLE
FR:  OAUTH/SSO/MICROSOFT Based Groups

### ISSUE THREAD

**Issue by mattronix** [tailscale/tailscale#7514] opened 2023-03-09 09:38 UTC
### What are you trying to do?

Trying to get groups from users for firewall policies from MICROSOFT/OIDC/SSO.

### How should we solve this?

Use the roles and or groups attribute from SSO/OAUTH/MICROSOFT. 

### What is the impact of not solving this?

management overhead for security policies/firewall policies for customer.
less overall security due to none dynamic security updates.

**Comment by DentonGentry** [comment] 2023-03-09 13:15
The next SCIM integration is expected to be for Active Directory, tracked in https://github.com/tailscale/tailscale/issues/979

Duplicate of https://github.com/tailscale/tailscale/issues/979

**Closed by DentonGentry** 2023-03-09 13:15 UTC
Labels: needs-triage, fr
