### ISSUE TITLE
Repository Debian Stretch no longer signed? v1.40.0

### ISSUE THREAD

**Issue by picree** [tailscale/tailscale#8086] opened 2023-05-07 12:18 UTC
### What is the issue?

Unable to update to v1.40.0.  Response is:

W: GPG error: https://pkgs.tailscale.com/stable/debian stretch Release: The following signatures were invalid: BADSIG 458CA832957F5868 Tailscale Inc. (Package repository signing key) <info@tailscale.com>
E: The repository 'https://pkgs.tailscale.com/stable/debian stretch Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

I then ran the following command assuming there was a key issue but tailscale would not update:

sudo curl -fsSL https://pkgs.tailscale.com/stable/debian/stretch.asc | sudo apt-key add -

### Steps to reproduce

run: $sudo apt-get update

### Are there any recent changes that introduced the issue?

Just trying to update

### OS

Linux

### OS version

Debian GNU/Linux 9 (stretch) 9.13

### Tailscale version

1.36.2

### Other software

Running on an EdgeRouter X

**Comment by DentonGentry** [comment] 2023-05-07 12:21
I don't understand why the signature error is happening, but the reason there isn't an updated version is that we accidentally broke MIPS package builds in a refactor after 1.36: https://github.com/tailscale/tailscale/issues/8005

No new MIPS packages have appeared since. We expect to restore MIPS in time for 1.42.

**Comment by DentonGentry** [comment] 2023-05-07 12:39
Since it is an EdgeRouter: Ubiquity's OS upgrades generally remove any third-party software which has been installed, or leave it partially broken. If that happened you'll likely need to:
- completely remove the tailscale package
- follow the steps in https://pkgs.tailscale.com/stable/#debian-stretch again
- maybe also `apt clean && apt update`

**Comment by picree** [comment] 2023-05-07 12:40
After curling the gpg key and trying again I no longer got the error but maybe that is just because apt-get update disabled the repository?  I'm not smart enough to know.

**Comment by picree** [comment] 2023-05-07 12:42
> Since it is an EdgeRouter: Ubiquity's OS upgrades generally remove any third-party software which has been installed, or leave it partially broken. If that happened you'll likely need to:
> 
> * completely remove the tailscale package
> * follow the steps in https://pkgs.tailscale.com/stable/#debian-stretch again
> * maybe also `apt clean && apt update`

OK thanks but I am not upgrading Ubiquity's OS.  Just simply updating tailscale.

**Comment by DentonGentry** [comment] 2023-05-07 12:45
Great. Repeating the steps in https://pkgs.tailscale.com/stable/#debian-stretch should handle the signing error.

1.36 is the most recent release for EdgeRouter. New releases will appear when https://github.com/tailscale/tailscale/issues/8005 is fixed.

Duplicate of https://github.com/tailscale/tailscale/issues/8005

**Closed by DentonGentry** 2023-05-07 12:45 UTC
Labels: needs-triage, bug
