### ISSUE TITLE
macOS 12.7.2: Complete network halt upon (dis-)connect unsolvable unless a hard reset

### ISSUE THREAD

**Issue by Haarolean** [tailscale/tailscale#12867] opened 2024-07-19 21:47 UTC
### What is the issue?

Sometimes switching the state of VPN (off->on) can result in a complete network freeze and OS being unavailable generally. When this happens:
1) restarting tailscale doesn't quite work (I get "The application tailscale is not open any more)
<img width="326" alt="Screenshot 2024-07-19 at 22 24 09" src="https://github.com/user-attachments/assets/16ef7a8d-ba96-47a0-82ea-6c2330d94b61">
2) switching wifi off/on doesn't work either
3) next observing network properties shows no adapters available at all anymore
<img width="715" alt="Screenshot 2024-07-19 at 22 24 57" src="https://github.com/user-attachments/assets/c4b4035f-8459-4f3c-9f56-9043a2a5dd39">
4) closing network properties later quite hangs the os with a beach ball of death
5) trying to exit the user session doesn't work as well, closing apps and quitting takes an indefinite amount of time, which results in the need for a complete reboot

### Steps to reproduce

I have multiple (two) profiles, which I have to switch sometimes. But I strongly believe it's reproducible even with one.
So how it goes in general:
1. I have tailscale off (the bug always happens when turning it off to on)
2. I click the toggle to switch it from off to on
3. The status doesn't change right away (it stays with "not connected" rather than switching to "waiting for network")
4. If I get impatient here, I click the toggle twice (to go off and back to on) this bug might happen. I believe waiting for a few seconds here helps to avoid it.

Considering the last point, the core issue might be that the state doesn't get changed when toggling the toggle to on. This part (the state not changing, not the network freeze happening right after in some occasional cases) is quite easy to reproduce, to do so, keep clicking the toggle, sometimes the state doesn't change for a few seconds.

### OS

macOS

### OS version

12.7.2

### Tailscale version

1.68.0

### Other software

- little snitch
- oversight

### Bug report

BUG-116f0ab36d3a4cc6296ee2e17ff817d6832b8270ca2097e14296116ed21fe7da-20240719201554Z-b71ea7f074dbc931

**Comment by agottardo** [comment] 2024-07-20 00:29
Note that Little Snitch is listed in our [list](https://tailscale.com/kb/1023/troubleshooting#interoperability-with-other-software) of applications that are incompatible or may cause conflicts with Tailscale. Especially on older macOS versions such as yours, there are many interoperability issues between network filters and network extensions such as Tailscale or other VPN apps. Please uninstall Little Snitch and verify if the issue persists.

Tailscale runs as a sandboxed network extension, and doesn't have enough access to macOS internals to cause something as bad as crashing the entire networking stack of your Mac. We only read/write the VPN configuration using the proper Apple APIs, so there is likely something on your system causing this hang in the network frameworks when our VPN tunnel is disconnected.

My feeling is that this is a bug affecting legacy versions of macOS like yours, and an interaction between Tailscale and other networking software installed on your Mac. If you want to email me a sysdiagnose I can take a further look out of curiosity, but unfortunately our ability to properly support old macOS versions is limited.

**Comment by Haarolean** [comment] 2024-09-05 20:10
Thanks for the feedback!

Sorry, I don't quite buy the Little Snitch interoperability issues thing for several reasons:
1) I'm running it in blacklist mode, not whitelist. So tailscale (and any other VPN client) is not limited at all.
2) I've been running it for years alongside with WireGuard even before Tailscale was a thing. And since Tailscale is claiming it's running WireGuard under the hood, I expect it to behave the same way. This week I had to cold boot my PC at least 3 times due to Tailscale making it unusable, while this happened for WireGuard like zero times in many years.

I can't upgrade at the moment, so I'm sending you the sysdiagnose report since you proposed to take a look at it. Thank you.

**Comment by Haarolean** [comment] 2024-09-27 20:18
@agottardo have you got a chance to take a look at my diag report? This is highly irritating since I have to cold boot at least twice a week (I can't upgrade to newer OS versions atm). Besides, I believe tailscale should provide support for Monterey as it's still supported by Apple as well.

**Comment by agottardo** [comment] 2024-09-27 20:47
I didn't get any sysdiagnose mentioning this issue number.

**Comment by Haarolean** [comment] 2024-09-27 22:08
@agottardo sent one on sep 5th to the email address available in your github profile

**Comment by agottardo** [comment] 2024-09-27 22:53
Logs around the time of the hang show hundreds of lines indicating that Little Snitch is blocking attempts from Tailscale to establish a DNS over HTTPS connection to CloudFlare DNS. Perhaps irrelevant, but the blocking will definitely cause you connectivity issues:
```
default	2024-09-04 19:24:03.169651 +0300	at.obdev.littlesnitch.networkextension	at.obdev.littlesnitch.networkextension	6281: Socket closed during DPI without data: LSSocketFlow /Library/SystemExtensions/1EAB0238-29DC-4AD2-80A9-998988BC4377/io.tailscale.ipn.macsys.network-extension.systemextension/Contents/MacOS/io.tailscale.ipn.macsys.network-extension (pid: 50965 uid: 0) → 1.0.0.1:443 status=DPI connectName=<nil>: 6/443
```
Tailscale complaining about the blocking around the same time, and a DNS health warning gets thrown a bit later:
```
default	2024-09-04 19:24:12.136475 +0300	io.tailscale.ipn.macsys.network-extension	io.tailscale.ipn.macsys.network-extension	dns udp query: resolving using "https://cloudflare-dns.com/dns-query": Post "https://cloudflare-dns.com/dns-query": read tcp 192.168.1.246:52396->1.1.1.1:443: read: connection reset by peer
```
Additionally, a Little Snitch crash:
```
Application Specific Backtrace 0:
0   CoreFoundation                      0x00000001af3e90b8 __exceptionPreprocess + 240
1   libobjc.A.dylib                     0x00000001af1338dc objc_exception_throw + 60
2   CoreFoundation                      0x00000001af47494c -[__NSSingleObjectEnumerator init] + 0
3   at.obdev.littlesnitch.networkextens 0x0000000104b1aee8 at.obdev.littlesnitch.networkextens + 110312
4   at.obdev.littlesnitch.networkextens 0x0000000104c44a7c at.obdev.littlesnitch.networkextens + 1329788
5   at.obdev.littlesnitch.networkextens 0x0000000104c513b0 at.obdev.littlesnitch.networkextens + 1381296
6   at.obdev.littlesnitch.networkextens 0x0000000104be4760 at.obdev.littlesnitch.networkextens + 935776
7   at.obdev.littlesnitch.networkextens 0x0000000104be4780 at.obdev.littlesnitch.networkextens + 935808
8   libdispatch.dylib                   0x00000001af0d81b4 _dispatch_client_callout + 20
9   libdispatch.dylib                   0x00000001af0e7a58 _dispatch_sync_invoke_and_complete + 56
10  at.obdev.littlesnitch.networkextens 0x0000000104bd2ae8 at.obdev.littlesnitch.networkextens + 862952
11  at.obdev.littlesnitch.networkextens 0x0000000104bd238c at.obdev.littlesnitch.networkextens + 861068
12  at.obdev.littlesnitch.networkextens 0x0000000104bd11b8 at.obdev.littlesnitch.networkextens + 856504
13  at.obdev.littlesnitch.networkextens 0x0000000104bd0584 at.obdev.littlesnitch.networkextens + 853380
14  at.obdev.littlesnitch.networkextens 0x0000000104bd0938 at.obdev.littlesnitch.networkextens + 854328
15  at.obdev.littlesnitch.networkextens 0x0000000104bd0e38 at.obdev.littlesnitch.networkextens + 855608
16  at.obdev.littlesnitch.networkextens 0x0000000104c0fa14 at.obdev.littlesnitch.networkextens + 1112596
17  at.obdev.littlesnitch.networkextens 0x0000000104bc1850 at.obdev.littlesnitch.networkextens + 792656
18  at.obdev.littlesnitch.networkextens 0x0000000104bc33c8 at.obdev.littlesnitch.networkextens + 799688
19  at.obdev.littlesnitch.networkextens 0x0000000104bc3390 at.obdev.littlesnitch.networkextens + 799632
20  libswiftDispatch.dylib              0x00000001c1a427dc $sxs5Error_pIgrzo_xsAA_pIegrzo_lTRTA + 28
21  libswiftDispatch.dylib              0x00000001c1a42908 $sxs5Error_pIgrzo_xsAA_pIegrzo_lTRTA.50 + 16
22  libswiftDispatch.dylib              0x00000001c1a40c4c $sSo17OS_dispatch_queueC8DispatchE11_syncHelper33_F417D752D2C4E9330E1C700411CE0C6ALL2fn7execute6rescuexyyyXEXE_xyKXExs5Error_pKXEtKlFyxyKcXEfU_yyXEfU_ + 188
23  libswiftDispatch.dylib              0x00000001c1a42688 $sIg_Ieg_TRTA + 28
24  libswiftDispatch.dylib              0x00000001c1a3c634 $sIeg_IyB_TR + 28
25  libdispatch.dylib                   0x00000001af0d81b4 _dispatch_client_callout + 20
26  libdispatch.dylib                   0x00000001af0e7414 _dispatch_lane_barrier_sync_invoke_and_complete + 56
27  libswiftDispatch.dylib              0x00000001c1a4171c $sSo17OS_dispatch_queueC8DispatchE4sync7executexxyKXE_tKlFyyyXEcABcfu_yyyXEcfu0_Tm + 180
28  libswiftDispatch.dylib              0x00000001c1a41ecc $sSo17OS_dispatch_queueC8DispatchE4sync7executexxyKXE_tKlFyyyXEcABcfu_yyyXEcfu0_TA + 56
29  libswiftDispatch.dylib              0x00000001c1a40a8c $sSo17OS_dispatch_queueC8DispatchE11_syncHelper33_F417D752D2C4E9330E1C700411CE0C6ALL2fn7execute6rescuexyyyXEXE_xyKXExs5Error_pKXEtKlF + 396
30  libswiftDispatch.dylib              0x00000001c1a4128c $sSo17OS_dispatch_queueC8DispatchE4sync7executexxyKXE_tKlF + 168
31  at.obdev.littlesnitch.networkextens 0x0000000104bc1ad8 at.obdev.littlesnitch.networkextens + 793304
32  NetworkExtension                    0x00000001bd90f878 __114-[NEFilterDataExtensionProviderContext handleData:offset:forFlow:direction:reply:controlSocket:completionHandler:]_block_invoke + 120
```

I don't see any crash reports from Tailscale, the process properly quit when you turned off the VPN. 

Theory: an unhandled edge case in the macOS VPN state machine is causing the hang, probably caused by the combo of content filter and packet tunnel provider. Definitely something that was fixed in more recent versions of macOS. Otherwise, we would be getting many more reports like yours, as we have thousands of enterprise customers who use firewalls and EDRs relying on the same socket filter APIs as Little Snitch.

We're not going to invest engineering time looking into this, as it involves both third-party software and an obsolete operating system version used on less than 0.01% of active Tailscale nodes, sorry.

**Closed by agottardo** 2024-09-27 22:53 UTC
Labels: OS-macos, needs-triage, vpn-interop, bug

**Comment by Haarolean** [comment] 2024-09-27 22:59
Thanks for the detailed analysis! I'm surprised Little Snitch is blocking anything, as I'm running the blacklist mode (everything is allowed unless blacklisted, which is a few selected apps). I'll be taking a look at the possible solutions, really appreciate your analysis once again!
