### ISSUE TITLE
tailscale stopped working after few minutes since installation - it is connected, but can't ping other stations and other stations can't ping it

### ISSUE THREAD

**Issue by marcowy** [tailscale/tailscale#11346] opened 2024-03-06 14:17 UTC
### What is the issue?

C:\Program Files\Tailscale>tailscale status

100.74.48.5     serdel               marcowy@     windows -
100.120.196.99  marcinn              marcowy@     windows -
100.115.215.72  perfektcloud         marcowy@     linux   -

# Health check:
#     - haven't heard from home DERP region 22 in 8m6s

C:\Program Files\Tailscale>tailscale netcheck

Report:
        * UDP: true
        * IPv4: yes, 91.215.3.72:54741
        * IPv6: no, but OS has support
        * MappingVariesByDestIP: false
        * HairPinning: false
        * PortMapping:
        * Nearest DERP: Warsaw
        * DERP latency:
                - waw: 22ms    (Warsaw)
                - fra: 29.6ms  (Frankfurt)
                - par: 36.1ms  (Paris)
                - ams: 39.3ms  (Amsterdam)
                - mad: 55.4ms  (Madrid)
                - lhr: 68ms    (London)
                - nyc: 104.9ms (New York City)
                - tor: 110.3ms (Toronto)
                - ord: 123.1ms (Chicago)
                - dfw: 134.6ms (Dallas)
                - dbi: 135.6ms (Dubai)
                - den: 140.3ms (Denver)
                - sfo: 164.4ms (San Francisco)
                - sea: 166.6ms (Seattle)
                - lax: 167ms   (Los Angeles)
                - mia: 172.6ms (Miami)
                - sin: 177.5ms (Singapore)
                - nai: 185.5ms (Nairobi)
                - blr: 197.9ms (Bangalore)
                - jnb: 199.2ms (Johannesburg)
                - sao: 211.5ms (São Paulo)
                - hnl: 214.5ms (Honolulu)
                - hkg: 264.9ms (Hong Kong)
                - syd:         (Sydney)
                - tok:         (Tokyo)

### OS

Windows

### OS version

Server 2022

### Tailscale version

1.60.1

### Bug report

BUG-96da27300c7e764e81c3c24e213d8a9ba371e9dab741c5237d55096f4b40df6e-20240306141600Z-03567fa456913bda

**Comment by nickkhyl** [comment] 2024-03-19 18:05
This is essentially a duplicate of #11222 which has been fixed in 1.62.

However, in this case, it appears that the Tailscale network adapter might have been removed by some third-party software installing an outdated version of the WinTun driver, specifically version 0.8 released in 2019. The most recent version, 0.14.1, was released in 2021. As only one version of the driver can be installed on a machine at the same time, it also removes all existing network adapters that use WinTun.

If you experience any related issues, I would advise updating the installed third-party software or working with the vendor of the other software to have them update the WinTun driver they use.

**Closed** 2024-03-19 18:06 UTC
Labels: connectivity, OS-windows, bug
