### ISSUE TITLE
Certificates not stored in custom IPN State Store

### ISSUE THREAD

**Issue by matty234** [tailscale/tailscale#8254] opened 2023-06-02 09:33 UTC
Hi,

We're running tailscale as a fargate task and I've created a state store that uses aws systems manager parameters. Most things get stored correctly in the state store but for some reason, certificates get stored in the filesystem regardless. I think this is due to this function:

https://github.com/tailscale/tailscale/blob/d06fac0edef0bb9927f93d1a0f1351cbbdaadb89/ipn/ipnlocal/cert.go#L156-L173

where it seems only instances running in Kubernetes can use the provided store to cache certificates and keys.

Would it be ok to always fall back on the ipn state store? Happy to make this PR if it would help.

Matt

**Comment by DentonGentry** [comment] 2023-06-02 14:39
From PR https://github.com/tailscale/tailscale/pull/8255
> Also, given the size of a certificate, a state store that can store 4KB+ is needed.

This would break AWS Parameter store, which [was failing when it had a 4K limit](https://github.com/tailscale/tailscale/issues/6784).

[We recently increased the AWS Parameter Store to 8k](https://github.com/tailscale/tailscale/pull/7955), but storing certificates in it would take it back to having < 4K available for parameters.

Always putting the certificate in the state store also wouldn't work for the macOS App Store version, which store their state in the system Keychain. This would store the certificate in the Keychain but as a binary blob for which there aren't tools to extract it for use as an actual certificate.

**Comment by DentonGentry** [comment] 2023-06-03 14:03
Duplicate of https://github.com/tailscale/tailscale/issues/4597

**Closed by DentonGentry** 2023-06-03 14:03 UTC
Labels: L2 Few, P1 Nuisance, T0 New feature
