### ISSUE TITLE
Magic DNS not working > v1.72.x (MacOS)

### ISSUE THREAD

**Issue by pkpowell** [tailscale/tailscale#13653] opened 2024-10-02 15:28 UTC
### What is the issue?

Magic DNS has stopped working on my macs ts versions > v1.72.2. 
I've tried both v1.74.x and the main branch v1.75.0-pre-60-ge66fe1f2e.
Newer Linux builds seem unaffected.

Here are the results of `scutil --dns` on MacOS. It seems there are a lot of entries missing in v1.75 compared to 1.72

1.75.0
````
DNS configuration

resolver #1
  search domain[0] : lan
  nameserver[0] : 192.168.44.1
  if_index : 6 (en0)
  flags    : Request A records, Request AAAA records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

resolver #2
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300000

resolver #3
  domain   : 254.169.in-addr.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300200

resolver #4
  domain   : 8.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300400

resolver #5
  domain   : 9.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300600

resolver #6
  domain   : a.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300800

resolver #7
  domain   : b.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 301000

resolver #8
  domain   : search.tailscale
  search domain[0] : tail3b1a8.ts.net
  search domain[1] : lan
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)

DNS configuration (for scoped queries)

resolver #1
  search domain[0] : lan
  nameserver[0] : 192.168.44.1
  if_index : 6 (en0)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
````

1.72.2
````
DNS configuration

resolver #1
  search domain[0] : lan
  nameserver[0] : 192.168.44.1
  if_index : 6 (en0)
  flags    : Request A records, Request AAAA records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

resolver #2
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300000

resolver #3
  domain   : 254.169.in-addr.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300200

resolver #4
  domain   : 8.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300400

resolver #5
  domain   : 9.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300600

resolver #6
  domain   : a.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300800

resolver #7
  domain   : b.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 301000

resolver #8
  domain   : 111.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #9
  domain   : 78.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #10
  domain   : 81.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #11
  domain   : 67.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #12
  domain   : 124.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #13
  domain   : 73.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #14
  domain   : 95.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #15
  domain   : 105.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #16
  domain   : 101.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #17
  domain   : 68.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #18
  domain   : 77.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #19
  domain   : 91.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #20
  domain   : 120.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #21
  domain   : 85.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #22
  domain   : 115.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #23
  domain   : 66.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #24
  domain   : 80.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #25
  domain   : tail3b1a8.ts.net
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #26
  domain   : binz
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #27
  domain   : ts.net
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #28
  domain   : 79.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #29
  domain   : 110.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #30
  domain   : 104.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #31
  domain   : 94.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #32
  domain   : 72.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #33
  domain   : 125.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #34
  domain   : 121.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #35
  domain   : 90.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #36
  domain   : 76.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #37
  domain   : pkp
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #38
  domain   : 69.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #39
  domain   : 100.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #40
  domain   : 114.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #41
  domain   : 84.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #42
  domain   : 88.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #43
  domain   : 107.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #44
  domain   : 126.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #45
  domain   : 118.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #46
  domain   : 97.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #47
  domain   : 71.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #48
  domain   : 65.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #49
  domain   : 83.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #50
  domain   : 113.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #51
  domain   : 98.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #52
  domain   : 117.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #53
  domain   : 108.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #54
  domain   : 87.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #55
  domain   : 93.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #56
  domain   : 75.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #57
  domain   : 122.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #58
  domain   : 103.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #59
  domain   : lan
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #60
  domain   : 70.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #61
  domain   : 96.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #62
  domain   : 127.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #63
  domain   : 119.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #64
  domain   : 106.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #65
  domain   : 89.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #66
  domain   : 112.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #67
  domain   : 82.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #68
  domain   : 64.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #69
  domain   : 86.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #70
  domain   : 109.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #71
  domain   : 116.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #72
  domain   : 0.e.1.a.c.5.1.1.a.7.d.f.ip6.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #73
  domain   : 99.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #74
  domain   : search.tailscale
  search domain[0] : tail3b1a8.ts.net
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)

resolver #75
  domain   : 102.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #76
  domain   : 123.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #77
  domain   : 74.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #78
  domain   : 92.100.in-addr.arpa
  nameserver[0] : 100.100.100.100
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

DNS configuration (for scoped queries)

resolver #1
  search domain[0] : lan
  nameserver[0] : 192.168.44.1
  if_index : 6 (en0)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
````

### OS

Linux, macOS

### OS version

MacOS 13, 14, 15

### Tailscale version

1.72.2, v1.74

**Comment by agottardo** [comment] 2024-10-02 19:45
Please provide a bug report identifier. Is this happening on the Standalone or App Store variant?

**Comment by pkpowell** [comment] 2024-10-03 09:42
BUG-895275a17e1b0821a97b74a754ba4a806a3b306520fd4824f3fc8716bcfeb1de-20241003005421Z-fd06e55c87103773

Standalone, built via build script `./build_dist.sh`
1.72.2
  tailscale commit: 899255bc798542998372872c475991a745fefeeb-dirty
  go version: go1.23.1

**Comment by pkpowell** [comment] 2024-10-03 10:22
I just installed the latest version from `https://tailscale.com/download` on a machine and magic dns works fine.
So I guess the tailscale / tailscaled combo > 1.72 I like to use on macos changed it's magic dns behaviour?

**Comment by darthShadow** [comment] 2024-10-19 18:55
Seeing the same behaviour on my system too with the tailscaled utun variant. The standalone variant works fine, as reported. Similar DNS resolver differences (as reported) in the `scutil --dns` output.

**Comment by ksylvan** [comment] 2024-10-25 21:15
I have both App Store (standalone 1.76.1) and "brew install" variant (1.76.3) running on two different macs.

MagicDNS works on the standalone variant just fine.

The `tailscaled` variant does not resolve MagicDNS hosts on my tailnet.

**Comment by Dadams2** [comment] 2024-11-20 03:36
I am on 1.76.6 installed with homebrew and have the same issue with magic dns. I switched to the standalone from the app store and magic DNS started working again.

**Comment by agottardo** [comment] 2024-11-20 19:54
Duplicate of #13461

**Closed by agottardo** 2024-11-20 19:54 UTC
Labels: OS-macos, needs-triage, bug
