### ISSUE TITLE
Tailscale fails to start on login in Windows 11

### ISSUE THREAD

**Issue by davidsbond** [tailscale/tailscale#3409] opened 2021-11-25 18:21 UTC
### What is the issue?

I logged in to my Windows 11 user and was presented with this error

![image](https://user-images.githubusercontent.com/6227720/143487287-9fd400d4-77d7-4ab5-bed8-b38723707668.png)

When I manually started Tailscale afterwards it worked fine. I suspect it's down to `explorer.exe` due to the error talking about the notify icon. I'm using a program called `StartAllBack` which brings back some of the functionality for the start bar that Windows 11 removed.

### Steps to reproduce

* Upgrade to Windows 11
* Get frustrated with the start bar and install tools that mess with how it works (`StartAllBack`)
* Restart the machine
* Login, see error

### OS

Windows

### OS version

11

### Tailscale version

1.16.0

### Bug report

BUG-52486661015e697550c12f333ca942a53bea7103601af2aab949e668ae5b8168-20211125182054Z-ff33611030cbf519

**Comment by DentonGentry** [comment] 2021-11-25 18:24
The stack trace mentions lxn/walk and looks like https://github.com/tailscale/tailscale/issues/1073, which was fixed in Tailscale 1.18. This bug report says 1.16, where the issue was still present.

I understand that Tailscale is working now so no need to do anything else. Closing as a duplicate of https://github.com/tailscale/tailscale/issues/1073

**Closed by DentonGentry** 2021-11-25 18:24 UTC
Labels: needs-triage, bug
