### ISSUE TITLE
FR: Tailscale client available to download using Microsoft Store

### ISSUE THREAD

**Issue by sachingharge** [tailscale/tailscale#8134] opened 2023-05-15 08:46 UTC
### What are you trying to do?

It would ease out the Software life cycle management if user can download the Tailscale client from Windows store
https://tailscale.com/download/windows

Currently we need to package the Tailscale client and ship through Intune our MDM solution so it will ease out the packaging and keep the client up to date work if it is available to download in Microsoft store

**Comment by DentonGentry** [comment] 2023-05-15 11:44
Duplicate of https://github.com/tailscale/tailscale/issues/2969

**Closed by DentonGentry** 2023-05-15 11:44 UTC
Labels: needs-triage, fr
