### ISSUE TITLE
FR:Allow Authorization keys expiration to durations to be set and renewed

### ISSUE THREAD

**Issue by DarkNeedle** [tailscale/tailscale#5446] opened 2022-08-26 17:19 UTC
### What are you trying to do?

Long running services should not have fixed duration key expiration. Some would argue it is more secure this way. However, to avoid disruption in services do to re-authentication via key, it would be beneficial to have the ability to extend key expiration, set key expiration by duration and date, renew existing keys for duration or until-date. This allows create flexibility and will cover a number of use cases.

### How should we solve this?

To avoid disruption in services do to re-authentication via key, it would be beneficial to have the ability to extend key expiration, set key expiration by duration and date, renew existing keys for duration or until-date. This allows create flexibility and will cover a number of use cases.

### What is the impact of not solving this?

Proactive redirection of traffic to new services while retiring old ones. As we many workloads will be containerized or orchestrated on Kubernetes, allowing a more robust authentication key management scheme would provide a good deal of benefit.

### Anything else?

Awesome what you all have done, much appreciated

**Comment by DentonGentry** [comment] 2022-08-27 22:55
Duplicate of https://github.com/tailscale/tailscale/issues/3427

**Closed by DentonGentry** 2022-08-27 22:55 UTC
Labels: needs-triage, fr
