### ISSUE TITLE
FR: API Device Connection Status

### ISSUE THREAD

**Issue by grahambrown11** [tailscale/tailscale#7209] opened 2023-02-08 09:52 UTC
### What are you trying to do?

Get the connection status of a device via the API.

### How should we solve this?

The admin console shows `Connected` under `Last Seen` when the device is connected.
Checking the network requests in the browser the are requests to 
`https://login.tailscale.com/admin/api/machines` that return a list of machines and one of the fields with in that is `connectedToControl`
can that same field be exposed in the API response to `https://api.tailscale.com/api/v2/tailnet/:tailnet/devices`

### What is the impact of not solving this?

 I'd like to create a monitoring script that notifies me when the device is no longer connected so before I'm away from the device I can resolve why it's not connected

**Comment by DentonGentry** [comment] 2023-02-12 02:10
Duplicate of https://github.com/tailscale/tailscale/issues/7004

**Closed by DentonGentry** 2023-02-12 02:10 UTC
Labels: needs-triage, fr
