### ISSUE TITLE
FR: Option to disable IPv6 for exit node running on Android

### ISSUE THREAD

**Issue by nsauk** [tailscale/tailscale#5581] opened 2022-09-09 00:57 UTC
### What are you trying to do?

After spending several hours trying to get what is the pattern of DNS issues I have with Android-running exit node, I realized that the cause is the broken IPv6. I saw an IPv6 address during yet another test with `curl -v`. Then I go to https://test-ipv6.com/ and get the message "Our tests show that you will have a broken or misconfigured IPv6 setup, and this will cause problems as web sites enable IPv6." To be honest, I don't even want to know what exactly is broken. I'm pretty sure my mobile carrier doesn't support IPv6 at a reliable level, so I'd be happy to disable any attempt of Tailscale to use it.

### How should we solve this?

Add a secret code 'exit-node-no-ipv6' which will disable IPv6 for DNS and forwarding with Android-running exit node when entered in the search field. Please keep this setting until the application data is cleared. Or add something like a dialog or checkbox for option to run an exit node.

### What is the impact of not solving this?

My goal is connecting internet via mobile network, so I can use the phone as a USB-modem or Wi-Fi hotspot for this. Obviously this is not a full workaround, because with Tailscale I can route my traffic via my phone _in another country_, and USB/Wi-Fi don't allow this.

**Comment by DentonGentry** [comment] 2022-09-09 01:03
I believe you are running into the issue which https://github.com/tailscale/tailscale/pull/5503 should fix. Android uses netstack to run as an exit node, and https://github.com/tailscale/tailscale/pull/5503 fixes an issue with IPv6 in netstack exit nodes.

We'll be building an Android 1.30.1 release to resolve this.

**Comment by DentonGentry** [comment] 2022-09-14 02:33
Root cause should be resolved in the 1.30.1 release in the Play Store.

**Closed by DentonGentry** 2022-09-14 02:33 UTC
Labels: needs-triage, fr
