### ISSUE TITLE
MacOS 15.0 Beta . No relay home server

### ISSUE THREAD

**Issue by jmooves** [tailscale/tailscale#12987] opened 2024-07-31 23:17 UTC
### What is the issue?

After upgrading to MacOS 15.0 Beta, Tailscale client shows 2 warnings. 

1. No relay home server
2. Relay Server unavailable 

<img width="500" alt="Screenshot 2024-07-31 at 5 27 35 pm" src="https://github.com/user-attachments/assets/7fcf30c6-f26c-49ff-bc26-aab47a13a26d">

### Steps to reproduce

Upgrade to MacOS 15.0 Beta (24A5298h)

### Are there any recent changes that introduced the issue?

Yes, upgrade from MacOS 14 to 15.0 Beta

### OS

macOS

### OS version

15.0 Beta (24A5298h)

### Tailscale version

1.70.0

### Bug report

BUG-75695991f93ba55495a4475e3c2a596818a39621994cf551a28b704b296af73d-20240731231635Z-23b0c483c98372c5

**Comment by agottardo** [comment] 2024-08-01 06:25
Duplicate of #12977

**Closed** 2024-08-01 06:25 UTC
Labels: needs-triage, bug
