### ISSUE TITLE
FR: Tailscale start up on boot for raspberry pi 

### ISSUE THREAD

**Issue by Albusaidi30** [tailscale/tailscale#5335] opened 2022-08-10 13:07 UTC
### What are you trying to do?

iam try to reduce connectivty time when raspberry boot up.

its seems when ras-pi bootup won't connect to Tailscale directly , it takes 2 min to connect to VPN unlike zerotier it connects at bootup. 

please help me to write the command and im not that expirt in linux. 

my project is:
Tailscale setup on both gaming PC and raspberry , and im streaming games to raspberry pi through moonlight stream and Nivida sheild streaming. i have sucess on get gaming over internet by setup this VPN . i tried Zerotier and Tailscale.

Tailscale is better in terms of latency rather than zerotier. but zerotier connect directly when pi boot up becouse i put some command like this "sudo touch /var/lib/zerotier-one/networks.d/[Network ID].conf" when i was setup zerotier.

i want Tailscale to connect to VPN directly and fast when pi bootup , becouse i have setup secript command when pi bootup like this 
nano .bash_login

window open then i put " moonlight stream -1080 VPN IP" and when pi login it will stream directly to gaming Pc since the network already connected (zerotier VPN)

End of Story.
 
is there a way like this command to let Tailscale do the same of zertier ??

**Comment by DentonGentry** [comment] 2022-08-10 13:24
tailscaled is started by systemd at boot. On the RPi when you run `systemctl status tailscaled` you should see something like:
```
  tailscaled.service - Tailscale node agent
     Loaded: loaded (/lib/systemd/system/tailscaled.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-07-23 19:33:11 PDT; 2 weeks 3 days ago
       Docs: https://tailscale.com/kb/
    Process: 456 ExecStartPre=/usr/sbin/tailscaled --cleanup (code=exited, status=0/SUCCESS)
   Main PID: 487 (tailscaled)
     Status: "Connected; dgentry@tailscale.com; 100.119.173.29 fd7a:115c:a1e0:ab12:4843:cd96:6277:ad1d"
      Tasks: 16 (limit: 77034)
     Memory: 31.7M
        CPU: 6h 12min 6.331s
     CGroup: /system.slice/tailscaled.service
             └─487 /usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port 41641
```

**Comment by Albusaidi30** [comment] 2022-08-20 10:15
Actually not exactly what are you saying. When i startup raspberry , it's not connect to to VPN immediately , i dont know why ??🤷🏼‍♂️

How do i know that ? 
I was monitoring from tailscale dashboard , when i restart pi it goes to disconnect than after pi boot up it takes two min to reconnect again to VPN

**Comment by DentonGentry** [comment] 2022-08-20 12:40
When the Raspberry Pi starts, `systemd` spends time starting up the various system services. On the RPi you have and with the other services it has been configured to run, I guess it takes two minutes to get through its boot process.

If you want it to be joined to the tailnet more quickly, turn off other services to reduce the amount of work it has to do at boot:
- `systemctl list-units --type=service` will show what services it starts at boot
- `systemctl disable <name>` can turn services off

This is fairly far from a tailscale support question, I'm going to close this as working as intended. Raspberry Pi forums may be of more help in determining what your device doesn't need to run.

**Closed by DentonGentry** 2022-08-20 12:40 UTC
Labels: OS-linux, L1 Very few, P2 Aggravating, T5 Usability, waiting-for-info, fr
