### ISSUE TITLE
Windows: Tailscale generates infinite error dialogs on failure

### ISSUE THREAD

**Issue by mtlynch** [tailscale/tailscale#1953] opened 2021-05-19 02:48 UTC
First, love Tailscale. Thanks so much for making it and offering it free for personal use!

I just upgraded to 1.8.3 today on my Win10 machine, and it worked fine for a few hours.

A few seconds ago, I started hearing an error dinging in the background every few seconds and didn't know why, After minimizing enough windows, I saw that Tailscale was popping a new error dialog every 10 seconds or so with the same error:

![image](https://user-images.githubusercontent.com/7783288/118749053-c4832b80-b82a-11eb-9d56-50c1bb101f64.png)

```
---------------------------
Tailscale Error
---------------------------
Failed to connect to Tailscale service.



Version 1.8.3 (td0e86b08c-g03346d1fb)



LogID: 1014ffc57f62e6eb082ec44fae1efc396d6a3fe8b2546241cb084c4a3245572d

(Ctrl-C to copy this text)


---------------------------
OK   
---------------------------
```

Tailscale is a background service, so I'd prefer it not to pop errors at all. If it does need to pop errors, I'd prefer it to pop one error dialog at most.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_364y9)

**Comment by DentonGentry** [comment] 2021-05-19 02:50
Oh, that isn't cool.

**Comment by dewitt** [comment] 2021-05-19 15:48
For me, the error that triggers the dialogs seems to occur when a second user signs in on Windows 10. I can try to track down a narrow repro case, unless this is already well understood.

**Comment by mtlynch** [comment] 2021-05-19 16:23
>when a second user signs in on Windows 10

Oh, this was true in my case. I had two users signed in. Although that's a common on my machine, and I never saw this issue prior to 1.8.3.

**Comment by darshinimashar** [comment] 2021-05-20 18:00
20 May 21 08:17 -0700: ui: ReadMsg: read tcp 127.0.0.1:54275->127.0.0.1:41112: wsarecv: An existing connection was forcibly closed by the remote host.
20 May 21 08:17 -0700: ui: Control connection done.
20 May 21 08:17 -0700: ui: stateChanged: Running -> NoState
20 May 21 08:17 -0700: ui: disconnected after 8.1037887s
20 May 21 08:17 -0700: ui: ipnclient: backoff: 7026 msec
20 May 21 08:17 -0700: ui: UI still alive.
20 May 21 08:17 -0700: ui: safesocket.Connect: dial tcp 127.0.0.1:41112: connectex: No connection could be made because the target machine actively refused it.
20 May 21 08:17 -0700: ui: service state: Running
20 May 21 08:17 -0700: ui: stateChanged: NoState -> NoState
20 May 21 08:17 -0700: ui: ipnclient: backoff: 6645 msec
20 May 21 08:17 -0700: ui: Handle: logs: be:2f3d72714a0d5f00283b118f0116cd68a2c793d312ea3ba9826aa628617167e4 fe:d85bb3cfd11e29bfb67d64996a62efbacb158c7141885b61b542086f1027d1cf
20 May 21 08:17 -0700: ui: ReadMsg: read tcp 127.0.0.1:62465->127.0.0.1:41112: wsarecv: An existing connection was forcibly closed by the remote host.
20 May 21 08:17 -0700: ui: Control connection done.
20 May 21 08:17 -0700: ui: stateChanged: NoState -> NoState
20 May 21 08:17 -0700: ui: disconnected after 2.940325s
20 May 21 08:17 -0700: ui: ipnclient: backoff: 14243 msec
20 May 21 08:17 -0700: ui: UI still alive.
20 May 21 08:17 -0700: ui: UI still alive.
20 May 21 08:17 -0700: ui: safesocket.Connect: dial tcp 127.0.0.1:41112: connectex: No connection could be made because the target machine actively refused it.
20 May 21 08:17 -0700: ui: service state: Running
20 May 21 08:17 -0700: ui: stateChanged: NoState -> NoState
20 May 21 08:17 -0700: ui: ipnclient: backoff: 5987 msec
20 May 21 08:18 -0700: ui: safesocket.Connect: dial tcp 127.0.0.1:41112: connectex: No connection could be made because the target machine actively refused it.
20 May 21 08:18 -0700: ui: service state: Running
20 May 21 08:18 -0700: ui: stateChanged: NoState -> NoState
20 May 21 08:18 -0700: ui: ipnclient: backoff: 10574 msec
20 May 21 08:18 -0700: ui: UI still alive.
20 May 21 08:18 -0700: ui: Handle: logs: be:2f3d72714a0d5f00283b118f0116cd68a2c793d312ea3ba9826aa628617167e4 fe:d85bb3cfd11e29bfb67d64996a62efbacb158c7141885b61b54

**Comment by DentonGentry** [comment] 2021-05-20 19:34
There is a panic message in the logs which matches the fix in https://github.com/tailscale/tailscale/commit/256db54c9d25e06297017c3145028ab3ed41b259

We're not sure this will fix the entire problem, but it will fix one panic and at least make the actual problem more clear.

**Comment by darshinimashar** [comment] 2021-05-20 20:50
Steps to Reproduce : 

1. Install Taiscale on OS (I used server 2019).
2. Enable "Run Unattended" 
3. Try to remote the desktop into the server using another user.

The remote connection will be interrupted and you will find the Tailscale services are kept restarting on the host and causing failure to turn on.


Same issue reproduced by , having "Run Unattended " mode enabled in Administrator and login in server as a different user (i.e. test1) and try to turn on Tailscale services from that login.

**Comment by darshinimashar** [comment] 2021-05-20 21:16
This issue occurs when windows have multiple user environments with "Run Unattended" enabled.
Workaround: disabled Run UNattended OPtion or remove Tailscale from startup app.

**Comment by bradfitz** [comment] 2021-05-26 22:22
@darshinimashar, what version did you repro with? Please include that info in future bug reports.

**Comment by crawshaw** [comment] 2021-06-01 13:41
I'll attempt to replicate this today.

**Comment by darshinimashar** [comment] 2021-06-01 13:43
@bradfitz I replicated this with Windows Server 2019.

**Comment by crawshaw** [comment] 2021-06-02 19:55
I am not able to replicate this on Win10 Pro by changing sessions. Possibly this was fixed by the panic fix deployed in 1.8.5. @darshinimashar if you can't replicate this with 1.8.5 I think it's time to close this.

**Comment by mtlynch** [comment] 2021-06-02 20:03
I haven't experienced this since upgrading to 1.8.5.

**Comment by crawshaw** [comment] 2021-06-03 17:00
Closing this. Please re-open if it is seen again at 1.8.5 or newer.

**Closed by crawshaw** 2021-06-03 17:00 UTC
Labels: L2 More users, OS-windows, P2 Aggravating, T6 Major usability
