### ISSUE TITLE
Enforce the use of exit nodes for compliance purposes

### ISSUE THREAD

**Issue by zrost85** [tailscale/tailscale#1745] opened 2021-04-20 14:08 UTC
I think it would be great for admins to be able to easily enforce the use of exit nodes, instead of having it only be optional.  To comply with certain policies we have to enforce full tunnel VPN, whereas right now I basically have to ask and trust my users to use exit nodes.

**Comment by mrbluecoat** [comment] 2021-04-23 21:39
Ref #1698

**Comment by DentonGentry** [comment] 2022-06-12 00:14
Duplicate of https://github.com/tailscale/tailscale/issues/1698

**Closed by DentonGentry** 2022-06-12 00:14 UTC
Labels: L1 Very few, P2 Aggravating, T5 Usability
