### ISSUE TITLE
Can't upgrade or install tailscale v1.56.1

### ISSUE THREAD

**Issue by liangchaPLUS** [tailscale/tailscale#10848] opened 2024-01-13 09:32 UTC
### What is the issue?

[Tailscale_20240113163833.log](https://github.com/tailscale/tailscale/files/13927530/Tailscale_20240113163833.log)
[Tailscale_20240113163833_000_MsiAMD64.log](https://github.com/tailscale/tailscale/files/13927531/Tailscale_20240113163833_000_MsiAMD64.log)

I've installed tailscale_v1.48.2 on my PC and want to upgrade it to v1.56.1.
When trying to upgrade tailscale by running "tailscale-setup-full-1.56.1.exe", ends in giving an error [Product: Tailscale -- Error 1920. Service 'Tailscale' (Tailscale) failed to start.  Verify that you have sufficient privileges to start system services.]
I'm running it with admin privileges.
And I notice that the "tailscale tunnel" virtual network device is missing when this error pop up.
I've tried windows network reset but didn't work out.
Tried running "tailscale upgrade" in cmd, also failed.

I've tried uninstall the current version(1.48.2), then install v1.56.1, still failed, same error situation.
But uninstall 1.48.2 and reinstall 1.48.2(tailscale-setup-1.48.2.exe) works just fine.
I've tried installing the pkg downloaded "tailscale-setup-full-1.56.1.exe" on another PC, it works.

### OS

Windows

### OS version

Windows10 22H2 19045.3930

### Tailscale version

1.56.1

```[tasklist]
### Tasks
```

**Comment by Duan2baka** [comment] 2024-01-16 11:32
I upgraded my tailscale from 1.50.1 and the same issue occurs

**Comment by nickkhyl** [comment] 2024-01-16 19:25
Tailscale depends, and has always depended, on the following Windows services:
- iphlpsvc (IP Helper)
- netprofm (Network List Service)
- WinHttpAutoProxySvc (Windows HTTP Web Proxy Auto-Discovery Service)

However, we only made these dependencies explicit in [1.52.0](https://github.com/tailscale/tailscale/wiki/1.52.0#windows).

When one or more of the services Tailscale explicitly depends on is disabled, Windows fails to start it, resulting in a generic and very unfortunate error message of `Service 'Tailscale' (Tailscale) failed to start. Verify that you have sufficient privileges to start system services`.

The upcoming 1.58 release will enhance user experience by checking dependencies before installation and displaying a list of services that need enabling. But for the time being, please check and enable the dependencies in the Services console (services.msc).

Duplicate of #10165

**Closed by nickkhyl** 2024-01-16 19:25 UTC
Labels: needs-triage, bug
