### ISSUE TITLE
Auth keys need a mechanism to auto-renew before 90 day expiry

### ISSUE THREAD

**Issue by jack1902** [tailscale/tailscale#1151] opened 2021-01-18 18:44 UTC
**Describe the bug**
Old Never expiring Keys appear to have an expiry date, although it is in the past, it should actually have one.

I have just re-created a new `reusable` key and it is set to expire in 3 months 👎

**To Reproduce**
1. Go to 'https://login.tailscale.com/admin/authkeys'
2. Click on 'Re-usable-key'
3. Click on `Generate reusable key`

**Expected behavior**
I expected the `reusable key` to NEVER expire, as the description states:

![Screenshot 2021-01-18 at 18 42 00](https://user-images.githubusercontent.com/39212456/104952690-dc51bc80-59bc-11eb-95d8-d696718c26d7.png)

**Screenshots**

![Screenshot 2021-01-18 at 18 40 28](https://user-images.githubusercontent.com/39212456/104952833-2e92dd80-59bd-11eb-99e3-94313eae26bb.png)

**Version information:**
All related to the web-app, nothing to do with the client itself

**Comment by rosszurowski** [comment] 2021-02-11 00:13
We updated these labels to be less confusing a little while back. The labels no longer say that keys never expire, since all our keys expire after 90 days for security reasons.

If this bug was about that confusion, we can consider it fixed. If this bug was about the fact that our keys expire after 90 days, then we can discuss that. We have plans to build systems for automated key renewal, but they're not ready yet.

**Comment by jack1902** [comment] 2021-02-11 10:03
So in terms of how i am using `tailscale` at the company i work, we use a Relay Node in our Cloud environment which advertises routes so that our developers can access relevant resources in our Cloud environments. This works great as our VM installs `tailscale` and then grabs the `key` from the secret store. This means we never store the key in the base image or in the initial script.

Whilst i still have to go to `/admin` to enable the routes for this VM (Something i believe being considered so a `key` can auto-enable routes [without me having to intervene at 2am in the morning because the node got cycled and developers can't access resources]). i'd ideally like the method to `auto-renew` a key to be implemented before enforcing me to make sure someone manually goes in and updates the key in the secrets store. I understand the security reason behind cycling keys but an old key that is old vs a dead key resulting in my VM no longer working if it got cycled means downtime that i'm not a fan of.

Currently have ~40 people using the relay to access resources like Databases, Kuberenetes APIs and other such network level restricted resources (These obviously have additional layers of authentication but thats besides the point)

**Comment by rosszurowski** [comment] 2021-02-11 15:50
Gotcha. That's really helpful context. I'll update the title of this bug to track our work on an automated system for renewing keys.

A few notes that might help you (or others reading):

* Nodes authorized with auth keys [stay authorized even after the key expires](https://tailscale.com/kb/1085/auth-keys), so part of the cause here is that this VMs getting spun down and then spun up requires it to reauth from scratch. That's where the expiring keys get tricky.
* Re: routes, we may have a key auto-enable routes in the future, but in the meantime, you could also consider using [our API's POST /routes](https://github.com/tailscale/tailscale/blob/main/api.md#device-routes-post) endpoint to automate the acceptance of the routes. We haven't done a great job of advertising our API just yet, but it should give you some of the hooks needed to make this process a little easier.

Thanks for your patience with this difficult workflow in the meantime.

**Comment by jack1902** [comment] 2021-02-11 17:56
@rosszurowski Thanks!

So i've got this now which will work nicely for the "lets not force me to go to admin to enable some routes" 👍 

```sh
API_KEY=""
TAILNET=""
ROUTES='[]'

# Get the current devices ID
DEVICE_ID=$(
    curl -s "https://api.tailscale.com/api/v2/tailnet/${TAILNET}/devices" -u "${API_KEY}:" \
        | \
    jq -r --arg HOSTNAME $(hostname) '.devices[] | select(.hostname==$HOSTNAME) | .id'
)

echo "Enabling routes:"
curl -s "https://api.tailscale.com/api/v2/device/${DEVICE_ID}/routes" -u "${API_KEY}:" \
    --data-binary "{\"routes\": ${ROUTES}}" | jq .
```

Points to note:
- I would prefer it if i could just do `tailscale whoami` or something to that effect to get my current `deviceId` without having to scrape the API using `jq` like i am
- `tailnet` - https://github.com/tailscale/tailscale/blob/main/api.md#tailnet

**Comment by DentonGentry** [comment] 2021-07-25 01:35
At this point I expect to implement https://github.com/tailscale/tailscale/issues/1369, to allow auth-keys to be created using the API. I suspect that one-time authkeys will be most useful, allowing a Terraform or other script to generate a key to authorize just the one node it is provisioning.

I suspect that this feature request stems from the capabilities we offered at the time, where authkeys could only be generated manually from the admin panel and therefore one-time keys were not very helpful. Once a reusable key is generated manually, it would be useful to be able to automatically extend it in order to let the automation keep using it.

If we provide a way to generate new authkeys programmatically, would that meet the need?

**Comment by DentonGentry** [comment] 2021-07-26 00:45
I'm going to close this with the expectation that we'll provide an automatable mechanism to generate new authkeys, rather than allow an existing authkey to be extended.

**Closed by DentonGentry** 2021-07-26 00:45 UTC
Labels: L1 Very few, P1 Nuisance, T2 Visual Polish
