### ISSUE TITLE
Custom headscale services cannot be used in the latest version of tailscale ios client

### ISSUE THREAD

**Issue by sp391607254** [tailscale/tailscale#10613] opened 2023-12-15 11:30 UTC
### What is the issue?

I upgraded the latest tailscale ios client and configured my own headscale service in the settings. When I opened the tailscale app, I could not connect to my headscale service. The page displayed the tailscale.com URL.

### OS

iOS

### OS version

ios 17

### Tailscale version

1.56.0

### Bug report

BUG-75631d2514c75a7baac69e4e32de6b73d97fa819407f26561823fbf21b5f44fd-20231215112956Z-75cd1e50748c2e7b

**Comment by adipierro** [comment] 2023-12-15 15:11
might be related? https://github.com/tailscale/tailscale/issues/10594

**Comment by agottardo** [comment] 2023-12-15 16:33
Duplicate of #10592

**Closed by agottardo** 2023-12-15 16:33 UTC
Labels: needs-triage, bug
