### ISSUE TITLE
Occasionally, a single route seems to 'go bad'

### ISSUE THREAD

**Issue by magnayn** [tailscale/tailscale#2359] opened 2021-07-08 15:34 UTC
I have 

on my home network:
nigels-air (mac m1 air)
pve (debian linux - proxmox)

on my work network:
proxmox1 (debian linux)
nmdockerbox (ubuntu LXC container within proxmox1).

In general, and most of the time, everything works, and I :heart: tailscale.
Very occasionally, a single route "goes bad". Currently every device can ping every other device, *apart from* (pve, nmdockerbox) who mutually can't ping each other. It's all very strange as it was working right until it wasn't!

In writing this, I have noted proxmox1 is running v1.8.0, and the rest are 1.10.1. Is there a forwards/backwards compatibility issue here. Is there anything I can run to diagnose?

**Comment by DentonGentry** [comment] 2021-07-08 15:42
There shouldn't be a backwards compatibility problem: we work very hard to maintain compatibility, and the oldest Tailscale node still operating (version 0.900) is in our production infrastructure so that if we break it, alarms will go off and we'll know it.

Also 1.8 isn't that old. We have lots of 1.8 and 1.10 systems operating.

The things which would be most helpful:
- `tailscale status` and `tailscale netcheck` output from both pve and nmdockerbox during one of the times they cannot contact each other
- run `tailscale bugreport` on both pve and nmdockerbox during one of the times they cannot contact each other, and paste the text strings it outputs here.

**Comment by magnayn** [comment] 2021-07-08 15:54
Cool, I'll do just that. Predictably it's started working again!

**Comment by diegomontoya** [comment] 2021-07-10 01:20
@DentonGentry Ever since 1.10.x release, we have had multiple linux/mac nodes randomly unreachable from external wan network. LAN to LAN to the problem node still work via tailscale. We did not experience this before 1.10.x release and this has happend with both Mac and Linux nodes all on 1.10.1.  Perhaps a regression since restarting tailscaled or performing tailscale down/up immediately fixed the node WAN connect issues. This issue not just a specific node-to-node. For this sample, when the connection error happens, Rat5 node is completely unconnectable or ping-able from any other tailcsale node via WAN. LAN to LAN is not affected.

Rat5: Linux Ubuntu 20.04
Mac-Air: Mac Air M1 BigSur

Tailscale Version: all 1.10.1

For the report below I have obfuscated node names and real non-tailscale ip values. 

Status/Netcheck when mac-air is  unable to reach rat5. Notice the relay via tokyo which doesn't work.  

```
root@rat5:~# tailscale status 
100.123.99.66   rat5              x@        linux   -
100.86.82.109   mac-air           x@        macOS   active; relay "tok", tx 6660 rx 0

root@rat5:~# tailscale bugreport
BUG-6136627057856b22409fba54852f1a291b21132c87e73a261d65ef05b8cf1338-20210710010342Z-20177595cfc14dbe


root@rat5:~# tailscale netcheck

Report:
	* UDP: true
	* IPv4: yes, 11.12.13.14:18851
	* IPv6: no
	* MappingVariesByDestIP: false
	* HairPinning: true
	* PortMapping: 
	* Nearest DERP: San Francisco
	* DERP latency:
		- sfo: 13.9ms  (San Francisco)
		- sea: 30ms    (Seattle)
		- dfw: 31.1ms  (Dallas)
		- nyc: 71.5ms  (New York City)
		- sin:         (Singapore)
		- fra:         (Frankfurt)
		- syd:         (Sydney)
		- blr:         (Bangalore)
		- tok:         (Tokyo)
		- lhr:         (London)
		- sao:         (São Paulo)
```

After rat5 tailcsale down/up, connection from mac-air now immediately works. Notice that direct connections work.

```
root@rat5:~# tailscale status | grep air
100.123.99.66   rat5              x@        linux   -
100.86.82.109   mac-air           x@        macOS   active; direct 12.13.14.15:27804, tx 10636 rx 11476

root@rat5:~# tailscale bugreport
BUG-6136627057856b22409fba54852f1a291b21132c87e73a261d65ef05b8cf1338-20210710010748Z-08ba8038c1ea0305

root@rat5:~# tailscale netcheck

Report:
	* UDP: true
	* IPv4: yes, 11.12.13.14:39938
	* IPv6: no
	* MappingVariesByDestIP: false
	* HairPinning: true
	* PortMapping: 
	* Nearest DERP: San Francisco
	* DERP latency:
		- sfo: 13.7ms  (San Francisco)
		- dfw: 28.6ms  (Dallas)
		- sea: 30.4ms  (Seattle)
		- nyc: 76.4ms  (New York City)
		- sin:         (Singapore)
		- fra:         (Frankfurt)
		- syd:         (Sydney)
		- blr:         (Bangalore)
		- tok:         (Tokyo)
		- lhr:         (London)
		- sao:         (São Paulo)

```

**Comment by DentonGentry** [comment] 2022-05-07 21:43
The symptoms of both problems reported in this bug match an overly aggressive netmap suppression issue which was fixed about 6 months ago. Connections could not be made in one direction but would work instantly in the other.

I'm going to close this in the belief that it was this issue. If you see similar behavior again please don't reopen this bug, please file a new one.

**Closed by DentonGentry** 2022-05-07 21:43 UTC
Labels: connectivity, OS-linux, L2 Few, P2 Aggravating, T5 Usability
