### ISSUE TITLE
FR: Add "Send with Tailscale" Button in the Windows 11 Context menu

### ISSUE THREAD

**Issue by CKraft11** [tailscale/tailscale#6219] opened 2022-11-07 19:46 UTC
### What are you trying to do?

It would be pretty cool if there was an option to, or by default, add the "Send with Tailscale" button to the windows 11 context menu. 

### How should we solve this?

I didn't think this was possible for 3rd party applications to do but projects like [nanazip](https://github.com/M2Team/NanaZip) and others have seemed to have pulled it off.

### What is the impact of not solving this?

I think it takes away from the integration that could be had with a solution like this and should make it much easier to use the tailscale send functionality.

### Anything else?

[Here](https://github.com/M2Team/NanaZip/blob/0fdf0881f491262fcd4f6c33737478edea3b85c6/SevenZip/CPP/7zip/UI/FileManager/PanelMenu.cpp) is the code used by nanazip to implement this feature

**Comment by DentonGentry** [comment] 2022-11-09 06:27
Duplicate of https://github.com/tailscale/tailscale/issues/3065

**Closed by DentonGentry** 2022-11-09 06:27 UTC
Labels: needs-triage, fr
