### ISSUE TITLE
Tailscale Sidecar in Kubernetes Suddenly Stopped Working

### ISSUE THREAD

**Issue by jdgiddings** [tailscale/tailscale#7192] opened 2023-02-06 20:39 UTC
### What is the issue?

We have a kubernetes workload that uses a Tailscale sidecar. According to our logs, the workload has been unable to reach Tailscale since 1/28. As far as we're aware, nothing in the workload or the tailscale configuration changed. 

The workload is trying to reach a database through a Tailscale subnet router. Other Tailscale clients are able to reach the database, just not the one in kubernetes

The sidecar is running with the following configuration:
image: tailscale/tailscale:v1.36.0
TS_EXTRA_ARGS : --accept-routes
TS_USERSPACE : false

TS_AUTH_KEY and TS_KUBE_SECRET are set as well

### Steps to reproduce

Run a kubernetes pod with a tailscale sidecar with the following configuration:

image: tailscale/tailscale:v1.36.0
TS_EXTRA_ARGS : --accept-routes
TS_USERSPACE : false

### Are there any recent changes that introduced the issue?

No

### OS

K8s Node: Ubuntu 18.04
Container image: tailscale/tailscale:v1.36.0 

### OS version

K8s Node: Ubuntu 18.04
Container image: tailscale/tailscale:v1.36.0 

### Tailscale version
1.36.0

### Bug report

BUG-14c77eab7b389aa11a00a09ce684a88e36f48a2141d6b7d78b163f1a210934a3-20230206202045Z-2952d5979ff628a7

**Comment by DentonGentry** [comment] 2023-02-07 21:54
The node key had expired. Around the time of the bugreport:
`2023-02-06 20:19:41.831425055 +0000 UTC: control: RegisterReq: got response; nodeKeyExpired=true, machineAuthorized=false; authURL=false`

By default, nodes are created with a 6 month node key expiration and will need to be reauthorized after that. In https://login.tailscale.com/admin/machines in the three dot menu to the right of the node's entry, one can select "Disable key expiry." This would be appropriate for infrastructure machines, and probably not appropriate for portable devices which might be left forgotten in a drawer for a year.

If a node is created using an authkey with tags applied, the assumption is that it is a server and it is created with a node key with expiry disabled. https://tailscale.com/kb/1068/acl-tags/

**Comment by DentonGentry** [comment] 2023-02-07 21:54
Closing, root cause believed to be node key expiration.

**Closed by DentonGentry** 2023-02-07 21:54 UTC
Labels: needs-triage, bug

**Comment by jdgiddings** [comment] 2023-02-10 18:03
I generated a new auth key and deleted the old state to force creation of a new node key. I'm getting a similar issue

BUG-40a2d110d45d16ddbf6ff1d06bf380fb18efe912018f794806d5a673f02bf818-20230210180056Z-d88ae98e292d3a9d

Everything looks good in the admin panel

![image](https://user-images.githubusercontent.com/79322633/218163859-72e84754-d1c9-48c2-9ca0-585542dcaeb5.png)
