### ISSUE TITLE
FR: Tailscale Browser Extension 

### ISSUE THREAD

**Issue by SpaceNerden** [tailscale/tailscale#10921] opened 2024-01-22 13:34 UTC
### What are you trying to do?

I am often using devices that provision Windows for that session only. This means that I cannot install applications because they would be deleted by next boot. 

I have a portable Firefox install on my USB stick and thought it would be nice if Tailscale ran on the browser as an extension, negating the need to install anything on the system.

### How should we solve this?

Using webextensions to proxy requests to a `tsnet` + proxy server

To be honest, I'm not so sure how to do the transport of requests between the extension and the wasm-compiled go code. Not even sure if you _can_ make a proxy server in webextensions.

### What is the impact of not solving this?

Impact: probably not much in the grand scale of things. I'd probably try find a way to make TS portable (e.g with the portableapps.com installer) or make a tsnet+socks binary and carry that around.

**Comment by DentonGentry** [comment] 2024-01-22 13:35
Duplicate of https://github.com/tailscale/tailscale/issues/7426

**Closed as completed by DentonGentry** 2024-01-22 13:35 UTC
Labels: needs-triage, fr

**Comment by SpaceNerden** [comment] 2024-01-22 13:54
I see, it's a browser limitation. I'll try the other workarounds then. Thanks!
