### ISSUE TITLE
User invite via Github is not possible. 

### ISSUE THREAD

**Issue by blur231** [tailscale/tailscale#10766] opened 2024-01-06 00:45 UTC
### What is the issue?

Hello dear, 

a friend and me wanted to invite each other, but there just came the following error "
Error 403 - not allowed to join tailnet". This error was not by Google but we trust Github more.

**Comment by Lynnesbian** [comment] 2024-01-06 02:30
I'm having this issue too. My tailnet is connected to my GitHub account, and when I try to invite a friend, they can't join. They get an error simply stating "403 - not allowed to join tailnet".

If they authenticate with Google or another provider, it works fine. The tailnet is working otherwise, and I can e.g. ping devices within my network.

My friend then made a tailnet, connected to their GitHub account, and tried to invite me. I joined with my GitHub account, and the same issue occurred.

**Comment by pippcat** [comment] 2024-01-08 10:08
Same here. Any ideas if and when it will be fixed?

**Comment by worthc21** [comment] 2024-01-08 18:05
Can confirm the same issue when using GitHub as the SSO. Any invites result in the 403 - "not allowed to join tailnet"

**Comment by huJjV3Au1zVoCzCSGUJ74H92VkhQOi** [comment] 2024-01-16 11:00
I am running into the same issue. Attempting to accept an invite from a non-personal tailnet while authenticating via Github (this account). Please let me know if there is anything I can do to help track this down!

**Comment by marwan-at-work** [comment] 2024-01-16 17:51
Hi all 👋🏼 
Thank you for taking the time to report this! 

For the time being, GitHub invites only work for personal-to-personal accounts. We will improve the error messaging on our side so that it explains _why_ you may not be able to join the tailnet. 

If you are failing to create a personal-to-personal invite, please let us know! 

Thanks,
Marwan

**Comment by ioExpander** [comment] 2024-01-16 21:56
Hi @marwan-at-work 
Thank you for your feedback. I'm also facing the same issue. Can you please elaborate on "personal-to-personal" ? Is it on the tailscale side or on the github side ?

I'm running tailscale free tier on my homelab, using a personal github account and failed to invite a friend also using a personal github account. Using google auth for him worked fine.
Thank you.

**Comment by Lynnesbian** [comment] 2024-01-16 22:01
I *thought* I had a personal account, however, I'm not so sure now.

My Github account is personal, not an organisation: 
![image](https://github.com/tailscale/tailscale/assets/24567627/b4015a44-673e-4c9c-b105-5a6bdce455b8)

However... the Tailscale web UI has a field for my "organisation name":

![image](https://github.com/tailscale/tailscale/assets/24567627/e02e5e8f-e4ba-4378-9929-437d32baf6a2)

Does this mean my account is an organisation? If so, why would that be? I didn't intend to create an organisation account. Is there a way to convert it to a personal account?

**Comment by pippcat** [comment] 2024-01-17 09:17
> If you are failing to create a personal-to-personal invite, please let us know!

That's exactly what I'm trying to do. I try to add https://github.com/pippcat to a tailscale account made by https://github.com/Fabmobil , both authenticated via Github obviously. If I open the invite link with the pippcat account I get 

```
Error 403

not allowed to join tailnet
```

**Comment by marwan-at-work** [comment] 2024-01-17 22:50
@pippcat and @Lynnesbian  thank you for the response! I was able to reproduce your issue and just rolled out a fix :) would be great if you had the chance to retry and let me know :) 

> Thank you for your feedback. I'm also facing the same issue. Can you please elaborate on "personal-to-personal" ? Is it on the tailscale side or on the github side ?

Yes of course :) So when you log in to Tailscale via GitHub, we create a "personal Tailnet" that's tied to your "GitHub handle" which in this case is @ioExpander -- so your "login name" in Tailscale is `ioExpander` and your Tailnet is called `ioexpander.github`.  This tailnet is personal, and not shared with anyone unless you manually invite someone to it through the Tailscale Admin UI. 

However, you can also create tailnets based on "GitHub Organizations". WIth those organizations, we let you manage your Tailnet users by directly mapping your GitHub org members as Tailnet user members. This way, if you want to add a user to your Tailnet, you don't have to do it twice (once in GitHub, and once in Tailscale Admin UI). You would just do it once via your GitHub org settings. 

Here's a link to our docs for more info: https://tailscale.com/kb/1284/sso-github

Hope that helps.

**Comment by Lynnesbian** [comment] 2024-01-17 22:53
@marwan-at-work I can confirm that this works for me! Thank you!

**Comment by pippcat** [comment] 2024-01-22 10:28
I also can confirm the fix worked. Thank you @marwan-at-work :pray:

**Closed** 2024-02-28 14:26 UTC
Labels: L3 Some users, P3 Can't get started, T5 Usability, bug
