### ISSUE TITLE
FR: Enable Mullvad for AUSTRALIA regaion

### ISSUE THREAD

**Issue by marvin8** [tailscale/tailscale#9938] opened 2023-10-23 20:37 UTC
### What are you trying to do?

I am trying to use Mullvad as an exit node in my tailnet.

### How should we solve this?

Please add the Australia region to your Mullvad VPN service

### What is the impact of not solving this?

Needing to run a selfhosted exit node (with all risks involved)

**Comment by DentonGentry** [comment] 2023-10-23 20:38
Duplicate of https://github.com/tailscale/tailscale/issues/9314

**Closed by DentonGentry** 2023-10-23 20:38 UTC
Labels: needs-triage, fr

**Comment by Tompennyau** [comment] 2024-03-16 09:15
also need this
