### ISSUE TITLE
Mullvad exit nodes do not work on Tailscaled on Mac version

### ISSUE THREAD

**Issue by arunsathiya** [tailscale/tailscale#9662] opened 2023-10-04 19:28 UTC
### What is the issue?

When using [Tailscaled on Mac](https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS) (unsandboxed Darwin), setting a Mullvad exit node does not seem to have any impact.

### Steps to reproduce

- Install [Tailscaled on Mac](https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS)
- Configure DNS with Quad100 (MagicDNS) as outlined here: https://github.com/tailscale/tailscale/issues/1338
- Start tailscaled (instructions on the first link) and run `tailscale up`
- Connect to any exit node with a command like `tailscale set --exit-node=us-sjc-wg-003.mullvad.ts.net`
- Notice that the connection does not break, but the traffic isn't tunnelled through the exit node. Can verify at https://mullvad.net/en/check

### Are there any recent changes that introduced the issue?

N/A

### OS version

Sonoma 14.0

### Tailscale version

1.50.0-ERR-BuildInfo

### Bug report

BUG-c496985eeeb84c2ca113d748a7d400ae1076b2e2a32734babf8e9d0240e2bd52-20231004192828Z-ecf979ea9e6af781

**Comment by pjaspers** [comment] 2024-01-09 14:02
+1

**Comment by agottardo** [comment] 2024-08-20 18:01
Duplicate of tailscale/tailscale#1650

**Closed by agottardo** 2024-08-20 18:01 UTC
Labels: OS-macos, L2 Few, P2 Aggravating, T5 Usability, bug, mullvad
