### ISSUE TITLE
FR: BRDIGE/FORWARD function required to add

### ISSUE THREAD

**Issue by feodorren** [tailscale/tailscale#6208] opened 2022-11-06 04:44 UTC
### What are you trying to do?

Due to we  already have a function of EXIT NODE, which we can send all our outflows to this node.
I am thinking if it is possible to transfer/forward data from some internal nodes within the subnet. Like an internal brige function for nodes, we can set up similar like exit node.

### How should we solve this?

When the client send the request, first, the client will contact with Derp, then contac directly with Exit node.
Can we add another step to find a thrid node to acting as a forward node then improve the internet connection?

### What is the impact of not solving this?

Somehow the internet in different place are bad or excellet. A bad BGP may waste too much time. But if we have different nodes, then we can share it to as a internal brdige, internal forward to advice transits.

### Anything else?

Good luck to all you guys. Tailscale is so amazing.

**Comment by DentonGentry** [comment] 2022-11-09 06:09
Duplicate of https://github.com/tailscale/tailscale/issues/5302

**Closed by DentonGentry** 2022-11-09 06:09 UTC
Labels: needs-triage, fr
