### ISSUE TITLE
Raspberry PI Docker error: could not get iptables version

### ISSUE THREAD

**Issue by mxrlkn** [tailscale/tailscale#4292] opened 2022-03-26 20:33 UTC
### What is the issue?

Running the docker image on a Raspberry Pi ARMv6 results in this error:

`docker run -d --name=tailscaled --network=host -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --privileged tailscale/tailscale tailscaled`

```
2022/03/26 20:17:41 logtail started
2022/03/26 20:17:41 Program starting: v1.22.1-tc8fb4f8c7, Go 1.17.8-tsdce70b6d32: []string{"tailscaled"}
2022/03/26 20:17:41 LogID: 2de2318fe3e53371be69a1219854c73900e41b0674b60c53ab837569ac23b821
2022/03/26 20:17:41 logpolicy: using system state directory "/var/lib/tailscale"
2022/03/26 20:17:41 wgengine.NewUserspaceEngine(tun "tailscale0") ...
2022/03/26 20:17:41 wgengine.NewUserspaceEngine(tun "tailscale0") error: creating router: could not get iptables version: signal: segmentation fault (core dumped)
2022/03/26 20:17:41 flushing log.
2022/03/26 20:17:41 logger closing down
2022/03/26 20:17:42 logtail: upload: log upload of 511 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/802bbb1013a03c79809ab42a8e29a6e14b9d1ba4f36d5b0d7c59faf8e3b23357": context canceled
2022/03/26 20:17:42 createEngine: creating router: could not get iptables version: signal: segmentation fault (core dumped)
```

Tailscale works fine without docker with this tutorial: https://tailscale.com/download/linux/rpi

### Steps to reproduce

`docker run -d --name=tailscaled --network=host -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --privileged tailscale/tailscale tailscaled`

### OS

Linux

### OS version

Raspbian GNU/Linux 10 (buster)

### Tailscale version

1.22.1-tc8fb4f8c7

**Comment by DentonGentry** [comment] 2022-03-26 21:15
> 2022/03/26 20:17:41 wgengine.NewUserspaceEngine(tun "tailscale0") error: creating router: could not get iptables version: signal: segmentation fault (core dumped)

Does iptables run within some other docker container on that device?

**Comment by bradfitz** [comment] 2022-03-26 21:25
Notes: it's "Raspberry Pi Model B Rev 2".

What does `docker run --rm --privileged tailscale/tailscale iptables -L` say, @mxrlkn?

And what does `sudo iptables -L` say?

**Comment by mxrlkn** [comment] 2022-03-26 21:37
@DentonGentry Not sure. I don't know what I could test with.

@bradfitz

Right, it's a Model B Rev 2.

`docker run --rm --privileged tailscale/tailscale iptables --version` prints nothing.

`sudo iptables --version` says: iptables v1.8.2 (nf_tables)

**Comment by bradfitz** [comment] 2022-03-27 00:42
@raggi, yet another case where us doing the iptables/nftables ourselves would help :)

@maisem, which ARM platform variants is `mkctr` using? I don't exactly follow. (aside: `comma-seperated` in mkctr flags is misspelled :))

**Comment by maisem** [comment] 2022-03-27 20:21
We build `linux/386`, `linux/amd64`, `linux/arm/v7`, `linux/arm64`. https://github.com/orgs/tailscale/packages/container/alpine-base/versions

The alpine image also supports other platforms including `linux/arm/v6` which we could also add.
https://hub.docker.com/layers/alpine/library/alpine/latest/images/sha256-cf85c9af31123ce4216c49232080b9b7b2bce5fb1f6e11e3c9bc493a00ddfc70?context=explore

I'm not sure if that would work on a Model B Rev 2, would need to confirm. I don't have one lying around though. If someone does, can they try to build the [Dockerfile.base](https://github.com/tailscale/tailscale/blob/main/Dockerfile.base) and check if `iptables` works?

```bash
docker build -t ts-alpine https://raw.githubusercontent.com/tailscale/tailscale/main/Dockerfile.base
docker run --rm -it ts-alpine iptables --version
# Cleanup
docker rmi ts-alpine
```

**Comment by mxrlkn** [comment] 2022-03-27 20:24
@maisem I get this error on my PI:

```
docker build -t ts-alpine https://raw.githubusercontent.com/tailscale/tailscale/main/Dockerfile.base
Downloading build context from remote url: https://raw.githubusercontent.com/tailscale/tailscale/main/Dockerfile.base     253B
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine:3.15
 ---> b1b9f739da99
Step 2/2 : RUN apk add --no-cache ca-certificates iptables iproute2 ip6tables
 ---> Running in cef8d5e35f20
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/armhf/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/main: temporary error (try again later)
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/armhf/APKINDEX.tar.gz
3069678480:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069678480:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069678480:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069678480:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069678480:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/community: Permission denied
ERROR: unable to select packages:
  ca-certificates (no such package):
    required by: world[ca-certificates]
  ip6tables (no such package):
    required by: world[ip6tables]
  iproute2 (no such package):
    required by: world[iproute2]
  iptables (no such package):
    required by: world[iptables]
The command '/bin/sh -c apk add --no-cache ca-certificates iptables iproute2 ip6tables' returned a non-zero code: 4
```

**Comment by DentonGentry** [comment] 2022-03-30 03:49
`3069678480:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:` looks like https://github.com/alpinelinux/docker-alpine/issues/110

**Comment by DentonGentry** [comment] 2022-08-28 01:32
I don't expect to make more progress on this, we'd need iptables to not segfault: `2022/03/26 20:17:41 wgengine.NewUserspaceEngine(tun "tailscale0") error: creating router: could not get iptables version: signal: segmentation fault (core dumped)`

Marking as a duplicate of https://github.com/tailscale/tailscale/issues/391, in that the fix for this sort of situation is to use netlink not the iptables binary.

**Closed by DentonGentry** 2022-08-28 01:32 UTC
Labels: OS-linux, packaging, L1 Very few, P3 Can't get started, T5 Usability, containers, bug
