### ISSUE TITLE
FR: add a note to each machine

### ISSUE THREAD

**Issue by vmarkovtsev** [tailscale/tailscale#9697] opened 2023-10-06 19:52 UTC
### What are you trying to do?

We want to store some extra metadata for each machine: SSH user name, hardware description, usage guidelines, etc. A simple text note would suffice. Using tags is quite inconvenient for that purpose.

### How should we solve this?

Add "Edit note..." item to the machine context menu that allows editing the plain-text note attached to the machine.
![image](https://github.com/tailscale/tailscale/assets/2793551/7eed3804-beea-4eb8-8695-c21bb101e342)

### What is the impact of not solving this?

We have to store our metadata on an external resource and switch back and forth.

**Comment by DentonGentry** [comment] 2023-10-09 03:14
Duplicate of https://github.com/tailscale/tailscale/issues/4077
(which is being considered but not currently being acted on)

**Closed by DentonGentry** 2023-10-09 03:14 UTC
Labels: needs-triage, fr

**Comment by Buzzmovies** [comment] 2024-01-28 21:50
Oh wow, this would be amazing!! Please please!
