### ISSUE TITLE
updated andoid client crashing

### ISSUE THREAD

**Issue by hs6666** [tailscale/tailscale#11742] opened 2024-04-15 11:14 UTC
### What is the issue?

updated via fdroid from 1.58.2-tb0e1bbb62-gcd1f0649958 to latest 1.61.105.t742 version and now app opens but crashed with "tailscale keeps stopping" message

### Steps to reproduce

every time I open app

### Are there any recent changes that introduced the issue?

yes app was updated once update was made availalbe on fdroid

### OS

Android

### OS version

andoid v10

### Tailscale version

1.61.105

### Other software

n/a

### Bug report

cannot run bugreport commans on android

**Comment by kelivel** [comment] 2024-04-15 13:24
Hi @hs6666 , this is a duplicate of https://github.com/tailscale/tailscale/issues/11719. We aren't directly involved in updating the F-Droid repository but there is a fix on the way, detailed in https://github.com/tailscale/tailscale/issues/11719.

**Closed by kelivel** 2024-04-15 13:24 UTC
Labels: needs-triage, bug
