### ISSUE TITLE
Configure DNS using DNS-over-TLS or DNS-over-HTTPS

### ISSUE THREAD

**Issue by ItalyPaleAle** [tailscale/tailscale#2056] opened 2021-06-06 00:26 UTC
On iOS, you can only use one VPN app at a time. The problem is that apps like 1.1.1.1 that offer secure DNS-over-HTTPS are implemented as VPN apps, so we always have to choose whether to use Tailscale (and access our private nodes) or 1.1.1.1 (and prevent our ISP from spying on us via DNS then selling that data to advertisers).

Would it be possible in the Tailscale iOS app to be able to configure what DNS server is used as fallback when split DNS is enabled? Ideally with DoH/DoT support too :) 

Note: this request is fairly different from https://github.com/tailscale/tailscale/issues/74 . The latter is about global DNS, in which the Tailscale DNS server makes upstream requests using DoT/DoH. In this case, the request is for the client itself to be configured to make split DNS requests using DoT/DoH when split DNS is being used.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_39zrl)

**Comment by DentonGentry** [comment] 2021-06-06 14:13
Seems feasible. Looking at client support:
+ MacOS Big Sur can [configure DNS-over-TLS and DNS-over-HTTPS from a Network Extension](https://developer.apple.com/documentation/networkextension/dns_settings). I don't see a way to do so from a System Extension, which we're trying to use for a beta channel version of the app, nor from [Tailscaled on MacOS](https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS).
+ Recent iOS versions are similar, DoT and DoH can be configured using the same APIs as MacOS
+ Linux systemd can support DNS-over-TLS in opportunistic mode where it just tries TLS to connect to an upstream DNS server. It looks like it will do this based on settings in /etc/systemd/resolved.conf
+ Windows implements opportunistic DNS-over-HTTPS if HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters has a EnableAutoDoh key set to 2.
+ Android implements DNS-over-TLS systemwide, though I don't see a way to turn it on from the Tailscale app. We also need to come up with some resolution for #915, that the VPN framework and Private DNS appear to be incompatible.

All of these look like opportunistic mode. Since the OS doesn't know a Common Name to expect it doesn't do any validation of the certificate the DNS server presents, a DNS server could just make one up. Opportunistic DoT only hides the DNS traffic from the ISP... unless they block TLS to port 853 ¯\_(ツ)_/¯. 

We could (probably optionally) enable secure DNS as a systemwide setting by:
- adding the Network Extension API calls to the MacOS & iOS apps
- setting the registry key on Windows.
- Android needs a workaround for #915, and then needs to be turned on manually as I don't see an API to do so. Only in Settings.
- On Linux we don't write to /etc/systemd/resolved.conf, so maybe just flag that this needs to be done.
- For MacOS System Extension or Tailscaled-on-MacOS maybe flag that manual intervention is needed.
----

I'll suggest one alternative which would work in current Tailscale versions, though: if you can run a caching DNS server which uses DoT/DoH for its own upstream lookups, maybe on a Raspberry Pi somewhere or an inexpensive hosted VM, you can configure its Tailscale IP address in https://login.tailscale.com/admin/dns as a global nameserver.

All of your Tailscale clients would send their DNS queries through the wireguard tunnel to your DNS server, so the ISP couldn't see the packets, and then your DNS server would use DoT/DoH to communicate with the upstream global resolvers.

Assuming that a DNS server you'd run would be on Linux, you'd likely need to start it with `tailscale up --allow-dns=false` to ignore the DNS settings it gets from Tailscale. That system needs to do its own DNS resolution.

**Comment by ItalyPaleAle** [comment] 2021-06-06 16:10
Thanks for responding!

> if you can run a caching DNS server which uses DoT/DoH for its own upstream lookups, maybe on a Raspberry Pi somewhere or an inexpensive hosted VM, you can configure its Tailscale IP address in https://login.tailscale.com/admin/dns as a global nameserver.

I thought about it. But there are three issues with doing that:

1. First, I'd have to maintain my own DNS server. I have experience doing that also in an enterprise setting with AD, and I know too damn well how I'd never want to do it again 🙃 it's an extra app to maintain and a very delicate one, and ideally you'd need to set it up in high availability. Ughhh
1. Second, this makes all DNS queries resolve with an IP based on where my DNS server is. So assume that the DNS server is in my home, if I am traveling (which was a frequent thing for me in "the normal times") then I always get a DNS response with the IP that is optimized for my home. I may be in Europe but the DNS response makes me connect to a server in the US west coast.
1. Lastly, there's the performance impact. One cool thing of 1.1.1.1 for example is that it's fast. Centralizing my DNS would be much slower.

**Comment by agneevX** [comment] 2021-06-15 07:29
> The problem is that apps like 1.1.1.1 that offer secure DNS-over-HTTPS are implemented as VPN apps

That's the issue right there. Apple offers the ability to set a specific DNS app, separate from VPNs. NextDNS is an example of offering this feature that lets you use a VPN alongside.

**Comment by DentonGentry** [comment] 2021-07-21 03:15
The 1.12 release makes a start on this, MagicDNS now uses DNS-over-HTTPS when querying popular upstream resolvers.

**Comment by ItalyPaleAle** [comment] 2021-07-21 05:20
This is great news.

Would you mind just confirming how this works? The fact that MagicDNS is split DNS makes this a bit confusing :)

1. Queries to the MagicDNS server still go over regular UDP
2. Queries to other domains go from the end node directly to the upstream DNS server via DoH?

If so, this should satisfy my requirements for this issue. Even if not configurable, using DoH by default when supported is just as valid.

(If I understand correctly, this is still different from #74 as that seems to be not about split DNS?)

**Comment by bradfitz** [comment] 2021-07-21 05:28
> 1. Queries to the MagicDNS server still go over regular UDP

Yes, over regular unencrypted UDP/53 to localhost, effectively. The query to 100.100.100.100 even over old-school UDP/53 doesn't leave the device.

> 2. Queries to other domains go from the end node directly to the upstream DNS server via DoH?

Yes, when the DNS server at 100.100.100.100 goes to answer a query for something that's not a Tailscale DNS name, then it looks at its upstream DNS server IPs and if you're like most people, you've set it to Google, Cloudflare, Quad9, etc. Those are now recognized (as of https://github.com/tailscale/tailscale/commit/236eb4d04d33c43b0d73fb7372353cb26b62421b) at:

https://github.com/tailscale/tailscale/commit/236eb4d04d33c43b0d73fb7372353cb26b62421b#diff-edabd7b22a013d4ba75c5c2ceadfdb6f96291fd1e5034971e8da13bb41cdefd4R514

And then instead of sending unencrypted UDP/53 to those IPs, we do DoH queries instead.

**Comment by ItalyPaleAle** [comment] 2021-07-21 05:31
Excellent! Thanks for fixing this for us :)

This solves the issue for my use cases.

In theory this issue could stay open in case people care about being able to configure what upstream DNS resolvers should use DoH. I can see some narrow scenarios in which someone set up their own DNS server and uses DoH - not sure how common this is, maybe just something for large enterprises? If you want to leave this issue open for that, your choice!

**Comment by rs** [comment] 2021-07-21 11:52
This won’t work with NextDNS for instance, as you need to specify your configuration in the DoH URL.

Why not letting users define a DoH URL instead of DNS IPs? This way, the user would have better control of the DNS protocol used instead of just hopping for a magic upgrade to happen for the IPs entered.

With DoH and DoT the coupling between DNS servers and IP does no longer exist and this is a good thing. This type of upgrade solution is not future proof and is not the direction OSes and browsers supporting encrypted DNS are taking (except for Windows, but well…).

**Comment by DentonGentry** [comment] 2022-03-27 03:24
Remaining work is a duplicate of https://github.com/tailscale/tailscale/issues/74

**Closed by DentonGentry** 2022-03-27 03:24 UTC
Labels: L2 Few, P2 Aggravating, T5 Usability, dns
