### ISSUE TITLE
FR: Time-based access control

### ISSUE THREAD

**Issue by hm-tobias** [tailscale/tailscale#6970] opened 2023-01-15 09:35 UTC
### What are you trying to do?

The requirement is that we can store usage times for Tailscale in the ACL. This would allow for additional protection, as it would allow communication within the Tailscale network only during working hours, for example. Misuse can be limited in this way.

### How should we solve this?

By expanding the options, this requirement could be implemented.

for example:

```
// Declare usage periods to restrict the ACLs.
	"time": {
	//  "example": "Date Time UTC"
		"daily": "* 08:00-17:00 +2",
		"mo-fr": "1-5 08:00-17:00 +2",
		"special": "20230115-20230415 * +2",
	},

	"acls": [
		{
			"action": ["daily:accept", "special:deny"],
			"users":  ["*"],
			"ports":  ["dns:53"],
		},
```

**Comment by DentonGentry** [comment] 2023-01-15 14:17
Time-limited access is something we may provide, and is tracked in https://github.com/tailscale/tailscale/issues/1023
There are a number of integrations which can provide this functionality now, for Tailscale users who use these services:

- https://tailscale.com/blog/sym/
- https://tailscale.com/blog/indent/
- https://tailscale.com/blog/conductorone/
- https://tailscale.com/blog/opal/

--------

Duplicate of https://github.com/tailscale/tailscale/issues/1023

**Closed by DentonGentry** 2023-01-15 14:17 UTC
Labels: needs-triage, fr
