### ISSUE TITLE
Internet connection gets lost after Android update

### ISSUE THREAD

**Issue by evgeny-goldin** [tailscale/tailscale#3379] opened 2021-11-22 19:39 UTC
### What is the issue?

Hello,

On T-Mobile Samsung Galaxy Note 20 Ultra 5G I noticed my phone loses its Internet connection (both wifi and mobile) after Android is updated and the phone restarts. It stays disconnected until the Tailscale client is manually reconnected, then everything goes back to normal. 

The Tailscale client is Always-On connected, installed through F-Droid. See the screenshot below.

Thank you!

### Steps to reproduce

- Set up Tailscale to Always-On
- Accept a system update from T-Mobile
- Wait until the update finishes and the phone restarts
- No Internet connection is available on the phone, no wifi and no mobile. Connecting and reconnecting mobile (with toggling an airplane mode) or wifi (with toggling wifi) doesn't help
- Open a Tailscale client, it appears as "connected"
- Toggle the client - disconnect and re-connect it
- The Internet connection restores

### Are there any recent changes that introduced the issue?

Android OS update

### OS

Android

### OS version

Android 11

### Tailscale version

1.16.2

**Comment by evgeny-goldin** [comment] 2021-11-22 19:41
![SmartSelect_20211120-064910_Settings](https://user-images.githubusercontent.com/117124/142924666-832f955f-da82-418a-afb8-a17c790e4a65.jpg)

**Comment by zeroZshadow** [comment] 2021-11-24 22:28
Tailscale doesn't seem to auto-start after a reboot of the phone or update of tailscale.

**Comment by DentonGentry** [comment] 2022-02-06 06:22
Duplicate of https://github.com/tailscale/tailscale/issues/2481

**Closed by DentonGentry** 2022-02-06 06:22 UTC
Labels: OS-android, L2 Few, P2 Aggravating, T5 Usability, bug
