### ISSUE TITLE
API returning 500 when DELETE requested on revoked tailnet key

### ISSUE THREAD

**Issue by dgivens** [tailscale/tailscale#5897] opened 2022-10-11 20:15 UTC
### What is the issue?

Described [here](https://github.com/tailscale/terraform-provider-tailscale/issues/162)

Using terraform-provider-tailscale to create preauth tailnet keys, I've found that I get a `500 Internal server error` response when deleting a key that has been revoked.

I believe this may be an API issue because this was working prior to 5 Oct 2022.

The following is from the debug output from terraform:

```text
2022-10-10T18:03:53.399-0500 [ERROR] plugin.terraform-provider-tailscale_v0.13.5: Response contains error diagnostic: diagnostic_summary="Failed to delete key" tf_provider_addr=provider tf_req_id=de5cd506-9e93-580b-7d8a-71d96264fdad tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/diag/diagnostics.go:55 @module=sdk.proto diagnostic_detail="internal server error (500)" diagnostic_severity=ERROR tf_proto_version=5.3 tf_resource_type=tailscale_tailnet_key timestamp=2022-10-10T18:03:53.399-0500
2022/10/10 18:03:53 [DEBUG] tailscale_tailnet_key.sample_key: apply errored, but we're indicating that via the Error pointer rather than returning it: Failed to delete key: internal server error (500)
2022/10/10 18:03:53 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Failed to delete key: internal server error (500)
2022/10/10 18:03:53 [ERROR] <root>: eval: *terraform.EvalSequence, err: Failed to delete key: internal server error (500)
2022/10/10 18:03:53 [ERROR] <root>: eval: *terraform.EvalOpFilter, err: Failed to delete key: internal server error (500)
```

### Steps to reproduce

With the terraform provider:

```hcl
terraform {
  required_providers {
    tailscale = {
      source  = "tailscale/tailscale"
      version = "0.13.5"
    }
  }
}

provider "tailscale" {
  api_key = "REDACTED"
  tailnet = "REDACTED"
}

resource "tailscale_tailnet_key" "sample_key" {
  reusable      = false
  ephemeral     = true
  preauthorized = true
}
```

If the generated auth key is not reusable, it is revoked as soon as it is used. If the key is created as `reusable = true`, it deletes fine, but if you revoke it through the admin settings, you get the described error.

### Are there any recent changes that introduced the issue?

None on my side

### OS

Linux, macOS

### OS version

Ubuntu 22.04, macOS 12.6

### Tailscale version

1.30.2

**Comment by willnorris** [comment] 2022-10-11 20:36
I can reproduce locally... fix should be pretty straightforward.

**Comment by willnorris** [comment] 2022-10-11 20:55
It looks like the previous behavior was to return a 404, which mostly seems to make sense.  Was the terraform provider handling that okay?

**Comment by dgivens** [comment] 2022-10-11 21:01
Yes. Provider handled it fine.

**Comment by willnorris** [comment] 2022-10-11 22:15
new behavior will be to treat this as a no-op and return a 200 response.  PR out for review now.

**Comment by willnorris** [comment] 2022-10-11 23:28
commit has been merged and will be in our next deploy, which should be in the next day or so.

**Closed** 2022-10-11 23:28 UTC
Labels: needs-triage, bug

**Comment by mihaip** [comment] 2022-10-12 18:54
Fix was deployed (at 11AM PDT).
