### ISSUE TITLE
FR: SSH unix socket forwarding

### ISSUE THREAD

**Issue by nward** [tailscale/tailscale#8262] opened 2023-06-03 08:54 UTC
### What are you trying to do?

I am using terraform with libvirt over SSH, which uses SSH unix socket forwarding.

This uses the `direct-streamlocal` channel type.

When attempting to use this, I get an error that the channel type is not supported.

### How should we solve this?

I don't know this code well, however, it looks like it uses gliderlabs/ssh - there appears to be a PR for gliderlabs/ssh to implement this functionality: https://github.com/gliderlabs/ssh/pull/196

Perhaps this could be merged in to the local fork?

### What is the impact of not solving this?

Some applications will not work over SSH

**Comment by DentonGentry** [comment] 2023-06-03 23:13
Duplicate of https://github.com/tailscale/tailscale/issues/6232

**Closed by DentonGentry** 2023-06-03 23:13 UTC
Labels: needs-triage, fr

**Comment by nward** [comment] 2023-06-04 01:46
Ack - sorry @DentonGentry I had searched issues for "unix forward" and GitHub's search apparently doesn't think "forwarding" matches "forward"
Cheers!
