### ISSUE TITLE
FR: shortcut integration iOS / iPadOS 

### ISSUE THREAD

**Issue by andesse** [tailscale/tailscale#4224] opened 2022-03-19 08:01 UTC
### What are you trying to do?

Hi!

It would be very useful if the app would be able to use from shortcuts. 

Like creating an automation that when I leave at home it turns on the VPN, when I am arriving at home it turns off. 

In my opinion that would be an awesome feature for all Apple users. 

### How should we solve this?

It’s an improvement for battery life on all devices. 

### What is the impact of not solving this?

Tailscale is using quite an amount of battery running in the background.

**Comment by bradfitz** [comment] 2022-03-19 14:16
Closing as duplicate of #3984.

(But we'll be fixing the battery issues soon enough, too.)

**Closed by bradfitz** 2022-03-19 14:16 UTC
Labels: needs-triage, fr

**Comment by wscott** [comment] 2022-05-26 10:40
Agreed. My use case is that I don't normally run with tailscale enabled, but a few places I go have good wifi, but they filter access to block things I use. I want to enable tailscale with an exit node whenever that wifi SSID is active and disconnect tailscale when I leave.
Shortcuts can do the automation already, I just need the ability to turn tailscale on and off.
