### ISSUE TITLE
FR:  Always on - Service - for iPhone

### ISSUE THREAD

**Issue by MickPBduece** [tailscale/tailscale#3771] opened 2022-01-20 01:38 UTC
### What are you trying to do?

Maintain network connection with iPhone without requiring phone user to start Tailscale

### How should we solve this?

Have Tailscale start when the phone starts

### What is the impact of not solving this?

Tailscale cannot easily be used to maintain a network for iPhone users. 

### Anything else?

Thanks for your consideration.  The conveniences that Tailscale provides are indeed helpful but I cannot expect that each time a phone is restarted the user will restart Tailscale.

**Comment by digitaldan** [comment] 2022-07-30 17:02
Just want to +1 on this one ( or +1000 really)  

Asking our employees to have to continually open the tailscale app on their IOS device to give it a chance to log in is causing a lot of confusion, not to mention a "hacky" experience.  Phones tend to update pretty regularly these days when people are sleeping, so it seems like our VPN is broken a lot of the time for our mobile users.  

There are a few other issues about the IOS client not running after some amount of time  ( https://github.com/tailscale/tailscale/issues/5030 , https://github.com/tailscale/tailscale/issues/4646 , https://github.com/tailscale/tailscale/issues/337  ) but its hard to know if the client has stoped or the phone has restarted.   In any case, it seems like general lifecycle management of the app would be a good focus right now ( everything else is pretty awesome!) .

**Comment by digitaldan** [comment] 2022-09-25 18:32
Hi so this is even more important as the iPhone will try and reboot at night if it perceives it has crossed a total memory threshold.  This is happening to many of us almost nightly.  I think having your VPN start at boot is pretty critical for the IOS client.  See https://github.com/tailscale/tailscale/issues/4646#issuecomment-1257251332

**Comment by gee-jay-bee** [comment] 2022-09-29 16:17
Is #1534 the iOS answer to this?

**Comment by digitaldan** [comment] 2022-09-29 18:22
>Is https://github.com/tailscale/tailscale/issues/1534 the iOS answer to this?

I think it likely is, thanks for pointing that out.

**Comment by DentonGentry** [comment] 2022-09-30 22:55
Duplicate of https://github.com/tailscale/tailscale/issues/1534

**Closed by DentonGentry** 2022-09-30 22:55 UTC
Labels: OS-ios, L3 Some users, P2 Aggravating, T5 Usability, fr

**Comment by MickPBduece** [comment] 2022-10-11 08:18
The primary app I used TS has an ability to request update from the
device.  If the request fails I send sms to the device to check TS.  Just a
work around
