### ISSUE TITLE
iOS: upon switch from Wifi to mobile data the connection is lost

### ISSUE THREAD

**Issue by BirdInFire** [tailscale/tailscale#6075] opened 2022-10-26 14:52 UTC
### What is the issue?

When the iphone switch from Wifi to 4G, LTE or 5G the connection is lost

### Steps to reproduce

Use data, move to wifi (without touching the phone (so come back at work or home)), after some time the connection drop (but remain active in the app (DNS forced by tailscale).

### OS

iOS

### OS version

16.1

### Tailscale version

Lastest

### Idea

Periodic ping of another allowed device (5min if my memory is right for app in background), if the ping fail restart the tunel (cut off and restart)

## Bug report

BUG-26104d65f6b62287f2e2a053ee4da612ac31d241bb681daee2ffae89ca648bd6-20221027062409Z-0fba8be834079026

**Comment by DentonGentry** [comment] 2022-10-26 15:39
The issue template asks for a bugreport because without that there is little chance we'll figure anything out. Shortly after you've switched to Wi-Fi and notice that connectivity is lost, please look in the Tailscale application menu for the bugreport item. That will put a marker in telemetry that tells us where to look.

**Comment by ouvoun** [comment] 2023-01-20 01:01
Something similar frequently occurs for me when I transfer from mobile data to Wi-Fi.

As soon as I join a Wi-Fi network, my device is unable to make network connections. Disabling Tailscale solves the issue. I'll occasionally need to toggle Tailscale several times before the connectivity (with Tailscale enabled) is successful.

Here's a bug ID in the midst of my toggling adventures after a network change from cellular > Wi-Fi.

BUG-2f1972be3aebc2d3725f3a32cea7254e5621a86e9ee1349941d6587b758ac885-20230120004655Z-8f2e17d10920b1da

**Comment by DentonGentry** [comment] 2023-02-12 15:15
Around the time of @ouvoun's bugreport:
```
2023-01-20 00:43:17.269342 +0000 UTC: dns: Set: {DefaultResolvers:[https://REDACTED] Routes:{beta.tailscale.net.:[] tails-scales.ts.net.:[] ts.net.:[199.247.155.53 2620:111:8007::53]}+65arpa SearchDo…+80
2023-01-20 00:43:17.269513 +0000 UTC: dns: Resolvercfg: {Routes:{.:[https://REDACTED] ts.net.:[199.247.155.53 2620:111:8007::53]} Hosts:20 LocalDomains:[tails-scales.ts.net. beta.tailscale.net.]+65ar…+4
2023-01-20 00:43:17.270758 +0000 UTC: dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[tails-scales.ts.net. example.com.beta.tailscale.net.] MatchDomains:[] Hosts:[]}
2023-01-20 00:43:17.274918 +0000 UTC: wgengine: set DNS config again after major link change
```

It is odd that the beta.tailscale.net and tails-scales.ts.net domains have no resolvers set. Is MagicDNS disabled? It is fine to disable it, I'm just trying to understand the configuration we see.

However something goes wrong with DNS lookups almost immediately:
```
2023-01-20 00:43:23.757869 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:23.788012 +0000 UTC: ^33.8M health("overall"): ok
2023-01-20 00:43:23.81745 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:23.817639 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:23.817672 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:23.9134 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:23.913501 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:23.913584 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:27.523632 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:27.524054 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:27.524146 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:28.562812 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:28.562952 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:28.563024 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:28.742719 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:28.743051 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:28.743274 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:28.803352 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:28.803633 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:28.804066 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:29.758942 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:29.759258 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:29.759511 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:29.821709 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:29.821892 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:29.822013 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:30.594867 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:30.595035 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:30.595119 +0000 UTC: dns udp query: request queue full
2023-01-20 00:43:31.211611 +0000 UTC: dns udp query: context deadline exceeded
2023-01-20 00:43:31.212016 +0000 UTC: dns udp query: context deadline exceeded
2023-01-20 00:43:31.212081 +0000 UTC: dns udp query: context deadline exceeded
```

**Comment by ouvoun** [comment] 2023-02-12 18:09
@DentonGentry I have MagicDNS enabled, along with a NextDNS global nameserver. This also occurred prior to me enabling the NextDNS configuration, for what it's worth.

**Comment by DentonGentry** [comment] 2023-02-12 18:22
> I have MagicDNS enabled

That is probably relevant, somehow. We're sending an empty MagicDNS config, but it shouldn't be empty. So something went wrong in generating the config to send to the client.

**Comment by mihaip** [comment] 2023-02-15 17:53
I believe I ran into this too (over the weekend), but have not had a chance to investigate: http://go/bug/BUG-eb5cafba4ece2a3a99c7563d0a89b796107161c359f028891ad0cd7962ce189a-20230211212443Z-81eb14523740f482

**Comment by ouvoun** [comment] 2023-04-29 22:18
Hey folks is there any further info or logs I can provide that would be helpful? I continue to experience this almost daily.

**Comment by tarzok** [comment] 2023-06-13 02:10
I ran into this issue as well when setting up a test network with an exit node (which also was a subnet router). Additionally, the configuration has a custom global nameserver set to to override local DNS.  Connection to network would consistently drop when moving between cellular/wifi on iOS, but could be mitigated via toggling tailscale.

After reading this github issue, I turned off MagicDNS and haven't had the problem reoccur.

**Comment by ouvoun** [comment] 2023-09-24 23:46
I still experience this on a daily basis. Anything info I can provide?

**Comment by r3n3x** [comment] 2023-12-05 03:01
Same here, experiencing on a daily basis.  Tailscale iOS 1.54.1 on iOS 17.2 beta.
Am desperately trying to find a solution.

(5/Dec/2023)

**Comment by BirdInFire** [comment] 2023-12-05 16:37
> Same here, experiencing on a daily basis. Tailscale iOS 1.54.1 on iOS 17.2 beta. Am desperately trying to find a solution.
> 
> (5/Dec/2023)

In my case the solution was to stop using tailscale to maintain properly the connection after more than a year the problem of the IOS app never changed (nor became less frequent), I don't know if they cannot recreate the bug properly or if it's not their priority, In any case I've let this opened since many like me have this problem.

If you don't "need" it when roaming in 4G and 5G, you can try GLINET hardware that integrate an older version of tailscale.

**Comment by r3n3x** [comment] 2023-12-06 07:12
I configured Shortcut and Automation in iOS as a workaround. Shortcut to disconnect, connect and "check status' the Tailgate app, then end the shortcut. Automate to "whenever i disconnect from [Any] Wifi network" run the shortcut.

Works for me at the moment.

Hoping to see a bugfix from @DentonGentry and team soon.

**Comment by xinmans** [comment] 2023-12-07 06:11
Same issue. Use the newest Tailscale iOS client.

**Comment by xinmans** [comment] 2023-12-07 06:21
> I configured Shortcut and Automation in iOS as a workaround. Shortcut to disconnect, connect and "check status' the Tailgate app, then end the shortcut. Automate to "whenever i disconnect from [Any] Wifi network" run the shortcut.
> 
> 
> 
> Works for me at the moment.
> 
> 
> 
> Hoping to see a bugfix from @DentonGentry and team soon. 

thanks， very good。 have set in ios。

**Comment by r3n3x** [comment] 2023-12-09 16:48
I gave up after a few days with my automation setup. When shortly losing mobile connectivity the Tailscale connection breaks. I didn't manage to find out the exact trigger (time offline between connection switches / outages ?).

So I could set up an automation to "disconnect, reconnect Tailscale" every 10 minutes just to be sure the phone won't go dark unnoticed for a long time. But that's too much of a hassle.

**Please Tailscale team, help us out here.**

(FYI Warp+ by Cloudflare handles the losses of connectivity smoothly and I never experience similar issues with their wireguard "on demand" tunnel. Perhaps there's anything to learn from their technical approach.)

**Comment by r3n3x** [comment] 2023-12-15 02:52
There's a new version 1.56.0 on iOS since today.  
https://apps.apple.com/my/app/tailscale/id1470499037
What's other users' feedback? Useable (without workaround "automation" to re-connect) for iPhones with TS & Exit Node? Bug fixed?

**Comment by r3n3x** [comment] 2023-12-16 11:18
related bug report posts:
https://github.com/tailscale/tailscale/issues/8691 
https://github.com/tailscale/tailscale/issues/10107

**Comment by agottardo** [comment] 2023-12-21 22:54
I'm happy to report we have identified the issue and we have a fix for it. We are currently testing it and will hope to land it soon.

**Comment by BirdInFire** [comment] 2023-12-22 04:10
> I'm happy to report we have identified the issue and we have a fix for it. We are currently testing it and hope to land it soon.

simple curiosity what was the issue ?

**Comment by agottardo** [comment] 2024-01-04 22:04
Duplicate of #8022

We are landing a TestFlight build with a fix for this. If you still experience issues, please use that issue to report any trouble.

**Closed by agottardo** 2024-01-04 22:04 UTC
Labels: connectivity, OS-ios, L1 Very few, P3 Can't get started, T5 Usability, waiting-for-info, bug

**Comment by floco** [comment] 2024-01-05 06:14
Great news ! What about for Android ? (suffers from similar issue)

**Comment by agottardo** [comment] 2024-01-05 18:52
The same issue on Android is already tracked in #10107.

**Comment by r3n3x** [comment] 2024-01-06 14:28
Is this https://testflight.apple.com/join/tLcYLZJV the iOS testflight version which already has the bigfix/update for this issue?
Please confirm. Happy to help test and feedback.
![Screenshot 2024-01-06 at 22 27 02](https://github.com/tailscale/tailscale/assets/23291787/6219418b-3d3b-4ec9-a140-80ca490145e5)
@agottardo

**Comment by agottardo** [comment] 2024-01-06 17:01
> Is this https://testflight.apple.com/join/tLcYLZJV the iOS testflight version which already has the bigfix/update for this issue?
> 
> Please confirm. Happy to help test and feedback.
> 
> ![Screenshot 2024-01-06 at 22 27 02](https://github.com/tailscale/tailscale/assets/23291787/6219418b-3d3b-4ec9-a140-80ca490145e5)
> 
> @agottardo 

Yep! See the last posts in #8022.

**Comment by ouvoun** [comment] 2024-01-21 18:20
> Duplicate of #8022
> 
> 
> 
> We are landing a TestFlight build with a fix for this. If you still experience issues, please use that issue to report any trouble.

Unfortunately this does not seem to fix my issue when transferring from Cellular -> Wi-Fi. I still need to disable + reenable Tailscale to recover my internet. My logs are above, but I'd be happy to share more. Would you like me to open a new issue?
