### ISSUE TITLE
FR: Add support for Okta dashboard, Okta Mobile app, or other custom URLs.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3872] opened 2022-02-04 16:03 UTC
### What are you trying to do?

 Add support for Okta dashboard, Okta Mobile app, or other custom URLs.

### How should we solve this?

Adding support for Okta dashboard, Okta Mobile app, or other custom URLs.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4e9sh)

**Comment by DentonGentry** [comment] 2022-02-06 08:06
Front link doesn't work for me, just an empty list of email messages.

**Comment by bradfitz** [comment] 2022-02-07 04:26
Same.

**Comment by DentonGentry** [comment] 2022-03-27 06:57
Duplicate of https://github.com/tailscale/tailscale/issues/4287

**Closed by DentonGentry** 2022-03-27 06:57 UTC
Labels: L1 Very few, P1 Nuisance, T0 New feature, fr
