### ISSUE TITLE
App crashes after update on macOS

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2377] opened 2021-07-09 18:10 UTC
The customer reported the same issue on 1.8 Tailscale and he runs into the Tailscale crash issue again after upgrading to 1.10.0.

BUG-8d261bbf969a28a4453a19c0a0d288f1b37af9cee3fbff4081e65c1bc3ca2276-20210707012021Z-4c9e7c2fc99f8fdd

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3czrl)

**Comment by darshinimashar** [comment] 2021-07-09 18:11
this may be related to https://github.com/tailscale/corp/issues/2166

**Comment by nshalman** [comment] 2021-07-09 20:36
Clarification:
Original report was from 1.10.0 (just after upgrading from 1.8):
BUG-5b3008f8eb1b0c4a2a04b287e3a418f2ebf69c37a34c6da781013d9baeb31ca4-20210625184826Z-e27d5c9524fbc4cb

Second report (noted above) was from 1.10.1 (just after upgrading from 1.10.0):
BUG-8d261bbf969a28a4453a19c0a0d288f1b37af9cee3fbff4081e65c1bc3ca2276-20210707012021Z-4c9e7c2fc99f8fdd

**Comment by bradfitz** [comment] 2021-07-09 20:40
Nothing was captured in that second log:

```
2021-07-06 21:19:53.653814 -0400 -0400: magicsock: disco: d:319ad439013d8350->d:120feb6aea7679fc ([AAF/r], derp-1) sent call-me-maybe
2021-07-06 21:19:53.653922 -0400 -0400: magicsock: disco: d:319ad439013d8350->d:120feb6aea7679fc ([AAF/r], 10.0.0.50:46612) sent ping tx=e6330675dbb0
2021-07-06 21:20:14.401712 -0400 -0400: logtail started
2021-07-06 21:20:14.402111 -0400 -0400: goSetupLogs: success (started with NaNM); version 1.10.1-t6b6016130-g49e1dcc20, go1.16.4-tsa2a536c
```

The crash is between the 2nd and 3rd line there, but there's no output.

**Comment by nshalman** [comment] 2021-07-09 20:47
Well, so far the major correlation is that the crashes have been happening right after upgrades and then seem to stop happening (though if it recurs I'll update this bug if you keep it open.)

**Comment by DentonGentry** [comment] 2022-03-27 03:48
Duplicate of https://github.com/tailscale/tailscale/issues/1403

**Closed by DentonGentry** 2022-03-27 03:48 UTC
Labels: OS-macos, L3 Some users, P1 Nuisance, T8 Crash
