### ISSUE TITLE
Tailscale 1.44.0 login stuck on Win11 22H2 with noise handshake

### ISSUE THREAD

**Issue by PureWhiteWu** [tailscale/tailscale#8427] opened 2023-06-23 20:36 UTC
### What is the issue?

When I tried to login with clean installed tailscale, the login button has no reponse, neither do the command line interface (`tailscale up` or `tailscale login`).

### Are there any recent changes that introduced the issue?

No, it's a clean installed windows with clean installed tailscale.

### OS

Windows

### OS version

Win11 22H2

### Other software

```
> tailscale debug hostinfo
{
  "IPNVersion": "1.44.0-t5d008cd83-g6dac82fa0",
  "OS": "windows",
  "OSVersion": "10.0.22621.1848",
  "Package": "msi",
  "Hostname": "xxxxx",
  "GoArch": "amd64",
  "GoArchVar": "v1",
  "GoVersion": "go1.20.5-ts40dc4d8"
}
```

```
> tailscale debug ts2021
04:31:46.785795 Fetching keys from https://controlplane.tailscale.com/key?v=63 ...
04:31:47.503733 Dial("tcp", "[2a0xxxe:9997]:80") ...
04:31:47.692258 Dial("tcp", "[2a05:xxxe:9997]:80") = [240e:3xxxf:6e42]:57166 / [2a05:dxxxe:9997]:80
04:31:47.909647 controlhttp.Dial = 0xc00014a230, <nil>
04:31:47.910188 did noise handshake
04:31:47.910188 final underlying conn: [240e:xxx:6e42]:57166 / [2a05:xxx:9997]:80
```

### Bug report

BUG-b83a83cfe08928ef45278443f971f3833570d9c968948a5ed0df63aa04ad71d0-20230623203555Z-5620dd720de7e956

**Comment by PureWhiteWu** [comment] 2023-06-24 09:30
I'm not sure if you need any other information to find out the problem, I'd be happy to help.

**Comment by taziobaker** [comment] 2023-07-07 21:41
If it is safe, try this:
[#8550](https://github.com/tailscale/tailscale/issues/#8550)

**Comment by PureWhiteWu** [comment] 2023-07-08 20:11
> If it is safe, try this: [#8550](https://github.com/tailscale/tailscale/issues/#8550)

Thanks, I've tried this but still doesn't work.

**Comment by kelivel** [comment] 2023-09-26 13:09
Closing this one as a duplicate of https://github.com/tailscale/tailscale/issues/8363. We'll track work over there.

**Closed by kelivel** 2023-09-26 13:09 UTC
Labels: bug, needs-triage-support
