### ISSUE TITLE
VPN doesn't connect from quick panel on Android

### ISSUE THREAD

**Issue by 5aberd2** [tailscale/tailscale#7352] opened 2023-02-23 10:34 UTC
On Android client tailscale doesn't start immediately after pressing on the quick button panel although it shows as turn on, but VPN doesn't kick in unless I go and cleck on the tailscale app itself.

Android 13
One Ui 5.1

**Comment by DentonGentry** [comment] 2023-02-23 11:24
Duplicate of https://github.com/tailscale/tailscale/issues/2646

**Closed by DentonGentry** 2023-02-23 11:24 UTC
