### ISSUE TITLE
FR: Can you add an android quick access to turn on/off tailscale?

### ISSUE THREAD

**Issue by lrosenman** [tailscale/tailscale#6083] opened 2022-10-27 01:29 UTC
### What are you trying to do?

quick access to be able to turn on / off tailscale on Android would make using the app easier when you need to flip flop

### How should we solve this?

add a quick access button

### What is the impact of not solving this?

Annoyance

**Comment by DentonGentry** [comment] 2022-10-27 01:37
duplicate of https://github.com/tailscale/tailscale/issues/2646

**Closed by DentonGentry** 2022-10-27 01:37 UTC
Labels: needs-triage, fr
