### ISSUE TITLE
Logging into macOS or iOS client activates system VPN profile

### ISSUE THREAD

**Issue by benniekiss** [tailscale/tailscale#8727] opened 2023-07-27 12:15 UTC
### What is the issue?

Logging into the tailscale client activates the system VPN profile on macOS and iOS. Likewise, deactivating the system VPN switch logs out the tailscale client.

Is the tailscale client making other connections when the tailnet connection is deactivated? What are these connections?

Associated issues:
this seems to be what is driving high iOS battery usage since the system VPN never fully disconnects even though the client is disconnected. #3363 

This also seems related #3189

### Steps to reproduce

Download iOS or macOS tailscale client >
install profile > sign into tailscale account without connecting to tailnet

Open System Preferences > VPN, see that tailscale profile is “activated” 

From here, toggle the System Preferences VPN setting and see tailscale report a logout. Or, from the tailscale client, logout and note that the System Preferences VPN has been deactivated.

What I expect:
Login to tailscale client, device VPN profile remains inactive until I connect to tailnet, similar to Wireguard behavior.

What happens:
system VPN profile activates on login and remains active until logout.

### OS

macOS, iOS

### OS version

macos 13+, iOS 16.5+

### Tailscale version

1.46.1

### Other software

Using a self-hosted headscale control server.

**Comment by agottardo** [comment] 2023-07-27 16:12
Duplicate of #1734 (we're working on this!).

**Closed by agottardo** 2023-07-27 16:12 UTC
Labels: OS-macos, OS-ios, needs-triage, bug
