### ISSUE TITLE
FR: Custom domain support for iOS on-demand VPN provider

### ISSUE THREAD

**Issue by cmsj** [tailscale/tailscale#9326] opened 2023-09-09 23:10 UTC
### What are you trying to do?

I love the new on-demand feature in the iOS client, but I don't use MagicDNS. Instead, I use various `foo.lan.mydomain.com` records that resolve to my regular LAN IPs, and publish a route for the LAN through my home Tailscale node.

It would be amazing if I could configure the on-demand settings such that Tailscale will only connect when:

1. I'm off my home wifi, and
2. I'm trying to talk to `*.lan.mydomain.com`

### How should we solve this?

I believe this should be possible by exposing a text field that feeds into a [DNSSearchDomainMatch](https://developer.apple.com/documentation/networkextension/neondemandrule/1406150-dnssearchdomainmatch?language=objc) NEOnDemandRule.

I suspect that you may already be using `*.ts.net` in a domain match, for the existing setting that only connects if a MagicDNS address is being connected to.

### What is the impact of not solving this?

I will be fine, but the world will be just a little bit less shiny.

### Anything else?

Thanks for Tailscale, it's really awesome!

**Comment by DentonGentry** [comment] 2023-09-09 23:46
Duplicate of https://github.com/tailscale/tailscale/issues/8915

**Closed by DentonGentry** 2023-09-09 23:46 UTC
Labels: needs-triage, fr
