### ISSUE TITLE
FR: Make ts.net address resolve when shared

### ISSUE THREAD

**Issue by demoulin** [tailscale/tailscale#4271] opened 2022-03-24 14:05 UTC
### What are you trying to do?

We use a server using the HTTPS Tailnet cert functionality. This provides us a domain like `https://machine-name.domain-alias.ts.net`. When we share this machine to someone outside the network only `http://machine-name` and `http://machine-name.domain.beta.tailscale.net` are reachable. The `https://machine-name.domain-alias.ts.net` url does not resolve.

### How should we solve this?

Is it possible to use split-dns to resolve everything from `ts.net` to `100.100.100.100`? This way we can have a certified domain that works for approved external users too.  

### What is the impact of not solving this?

When we use the SSL certificates it will always give a cert warning when external users cannot access the `ts.net` domain.

### Anything else?

For now I have hardcoded the Tailscale IP in my hosts file. This is a workaround that works on a desktop but not on a mobile device.

**Comment by DentonGentry** [comment] 2022-03-27 04:16
Duplicate of https://github.com/tailscale/tailscale/issues/2930

**Closed by DentonGentry** 2022-03-27 04:16 UTC
Labels: needs-triage, fr
