### ISSUE TITLE
FR: add an ACL autogroup for devices that share a tag

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#6063] opened 2022-10-25 20:13 UTC
### What are you trying to do?

looking for an equivalent to `autogroup:self` to reference devices that have the same tag.

### How should we solve this?

Add `autogroup:sametag` or something similar to allow rules which reference how nodes can communicate with their tag-mates. 

### What is the impact of not solving this?

Without this, the number of rules allowing nodes to communicate with same-tag devices grows with the number of tags on a tailnet. With it, it is a single rule for all tags.

**Comment by jacobwgillespie** [comment] 2022-10-25 20:34
We have a potential use-case for this feature - we have a dynamic number of ephemeral client and server machines that run for short durations of time (for CI builds). We want to define ACL rules such that the only the specific client launched for the specific server is able to communicate with that server.

If we have three client/server pairs today, our ACLs would look something like:

```json
{
  "acls": [
    {"action": "accept", "src": ["tag:group-1-client"], "dst": ["tag:group-1-server"]},
    {"action": "accept", "src": ["tag:group-2-client"], "dst": ["tag:group-2-server"]},
    {"action": "accept", "src": ["tag:group-3-client"], "dst": ["tag:group-3-server"]},
  ]
}
```

This list grows linearly as our number of groups grows (we potentially have 100s of these groups today).

Having `autogroup:sametag` would allow us to define one static ACL rule that paired clients and servers, so our ACL list would not grow, and we would not need to dynamically update our ACLs at all.

We would still want some way to control the direction of data flow, so we'd still want some way to say that the source needed to be the `client` tag and the destination the `server` tag. Ideally clients would be tagged with both `tag:client` and `tag:group-xxx` and servers would be tagged with `tag:server` and `tag:group-xxx`, and there would be a way of using `autogroup:sametag` to pair based on that group tag.

**Comment by mayakacz** [comment] 2022-10-25 20:53
I think we were discussed something like `autogroup:tags`, and then you could write a policy like 
```
{
  "acls": [
    {"action": "accept", "src": ["autogroup:tags"], "dst": ["autogroup:self"]},
  ]
}
```
If this is what you meant, this might be a dupe of https://github.com/tailscale/tailscale/issues/4148. See also discussion in https://github.com/tailscale/tailscale/issues/1447.

**Comment by jacobwgillespie** [comment] 2022-10-25 21:08
I'm not sure if `autogroup:tags` would work for us, since we effectively only want this for specific devices, but not all tagged devices. You could imagine our device list as something like this:

Device | Tags
--- | ---
Server 1 | `server` / `group-1`
Server 2 | `server` / `group-2`
Server 3 | `server` / `group-3`
Client 1 | `client` / `group-1`
Client 2 | `client` / `group-2`
Client 3 | `client` / `group-3`
Other device | `other` / `tags` / `etc`
Another device | `more` / `tags`

The rule we want to express is effectively "allow traffic from devices tagged `client` to devices tagged `server`, only if their `group-*` tags match".

**Comment by mayakacz** [comment] 2022-10-26 15:41
> The rule we want to express is effectively "allow traffic from devices tagged `client` to devices tagged `server`, only if their `group-*` tags match".

I think that's a different ask, that tags be treated as 'and', so that a device is define as `server` and `group-1. See https://github.com/tailscale/tailscale/issues/5290

**Comment by DentonGentry** [comment] 2023-02-18 18:56
The discussion in this bug bifurcated but I believe both forks are tracked elsewhere:
- should there be an autogroup to match all tagged nodes (and be able to use `autogroup:self` for nodes carrying the same tag) is tracked in https://github.com/tailscale/tailscale/issues/4148
- boolean and combinatorial rules in ACLs is tracked in https://github.com/tailscale/tailscale/issues/5108

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Closed** 2023-06-02 23:16 UTC
Labels: needs-decision, fr
