### ISSUE TITLE
Tailscale cannot connect on Windows Startup, probably DNS issue

### ISSUE THREAD

**Issue by VictorTomaili** [tailscale/tailscale#6037] opened 2022-10-24 09:03 UTC
### What is the issue?

A few months ago I was not had such as issue but last few months when I start my computer, the tailscale is not connecting to the network. Most of the case, it needs to restart the tailscale service to fix that. And these days, It's not enough to restart service. I need to replace my DNS as 1.1.1.1 to fix that.  After a few seconds, tailscale is connecting to the network and I revert this DNS to automatic. I use tailscale DNS settings enabled. 

### Steps to reproduce

When I start my computer each day, with same or different internet connection. 
With my desktop pc and my laptop. Both of them same operating system and latest OS/tailscale version. 

### OS

Windows

### OS version

11 22H2 OSBuilld 22623.746

### Tailscale version

1.32.1

### Bug report

BUG-e5b33479a1a688f555a1731368bbc2414dc14001558a7c5f1ef75c8b37ce7e6b-20221024085038Z-3c0a94c24d1add09

**Comment by andrew-d** [comment] 2022-10-24 16:25
I believe that this is caused by #4134, since the logs show:
```
setPrivateNetwork(try=1): GetNetwork: Element not found.
setPrivateNetwork(try=2): GetNetwork: Element not found.
[...]
user bugreport health: network-category: GetNetwork: Element not found.
```

**Comment by DentonGentry** [comment] 2022-11-01 23:26
Duplicate of https://github.com/tailscale/tailscale/issues/4134

**Closed by DentonGentry** 2022-11-01 23:26 UTC
Labels: bug
