### ISSUE TITLE
FR: Allow to set destination as host/Tailscale IP in SSH rule

### ISSUE THREAD

**Issue by trietphm** [tailscale/tailscale#8238] opened 2023-05-31 02:51 UTC
### What are you trying to do?

**Use case:** I want to grant user Alice (alice@example.com) and Bob (bob@example.com) permission to ssh to specific servers, they are not on the same team and requesting to different servers. Currently, the ssh `dest` field only [accepts user or tag](https://tailscale.com/kb/1018/acls/#tailscale-ssh) so I have to:
- Create a new tag like `alice-request` in the ACLs and add a new `ssh` rule with `src` is `alice@example.com` and `dest` is the tag `alice-request` in the policy code in the Github repo.
- Add that tag `alice-request` to the servers in Tailscale Console
- Do the same for  Bob.

It's inconvenient because:
1. If there are more users and they need to access different servers, then I need to create new tags for them, e.g. `calvin-request`, `john-request`, etc. There would be a lot of tags and cause a mess.
2. There is friction as I need to update the policy in Github code and then go to Tailscale Console UI to update the tags because I can't tag the server right in the policy code.

### How should we solve this?

Support host/Tailscale IP in the ssh destination field. 

Then I can set a policy like this without messing with the tags
```json
{
	"hosts": {
			"db1": "100.x.x.1",
            "db2": "100.x.x.2",
	},
	"acls": [
		{"action": "accept", "src": ["alice@example.com"], "dst": ["db1:22"]},
        {"action": "accept", "src": ["bob@example.com"], "dst": ["db2:22"]},
	],
	"ssh": [
		{
			"action": "check",
			"src":    ["alice@example.com"],
			"dst":    ["db1"],
			"users":  ["autogroup:nonroot", "root"],
		},
		{
			"action": "check",
			"src":    ["bob@example.com"],
			"dst":    ["db2"],
			"users":  ["autogroup:nonroot", "root"],
		},
	]
```

### What is the impact of not solving this?

- I have to manually do as described above. 
- Or I have to set up the Terraform or Pulumi to resolve point (2) as both permission rules and tagging are centralized in one place. It still does not solve point (1) though.

**Comment by DentonGentry** [comment] 2023-05-31 21:16
```
	"ssh": [
		{
			"action": "check",
			"src":    ["alice@example.com"],
			"dst":    ["100.64.1.2"],
			"users":  ["autogroup:nonroot", "root"],
		},
```

One concern would be the implication that any IP address should work, including through subnet routers to 192.168.x.y. Tailscale SSH only works when `tailscaled` itself can be the SSHd.

**Comment by DentonGentry** [comment] 2023-06-03 16:18
https://github.com/tailscale/tailscale/issues/5084 said:

> So having IPs in SSH is ACLs is deliberately restricted.
> The restriction we are working around is that Alice should never be able to login to machine owned by Bob.
>
> Say you have a machine M1 that is currently tagged, and then we let you add an IP based ACL for Alice. Sometime later that machine is untagged by Bob. This results in a policy where Alice can SSH into Bobs machine.

**Comment by DentonGentry** [comment] 2023-06-03 16:18
Duplicate of https://github.com/tailscale/tailscale/issues/5084

**Closed** 2023-06-04 20:32 UTC
Labels: L2 Few, P1 Nuisance, T0 New feature, fr, ssh
