### ISSUE TITLE
FR: Add ControlD DNS Service to Tailscale

### ISSUE THREAD

**Issue by hjasond** [tailscale/tailscale#9908] opened 2023-10-21 22:05 UTC
### What are you trying to do?

I would like to be able to add ControlD DoH DNS configurations as a Tailscale Global nameserver. This is supported today for NextDNS, I would like to be able to add ControlD profiles as well. 

### How should we solve this?

Add ControlD DoH DNS as an option in the Global Nameservers list. The user would input their ControlD resolver ID which is the equivalent of the NextDNS endpoint ID.

### What is the impact of not solving this?

Due to the nature of NextDNS or ControlD you cannot use traditional DNS resolvers without a static IP which makes them hard / impossible to use as a Tailscale DNS override.

**Comment by DentonGentry** [comment] 2023-10-21 22:10
Duplicate of https://github.com/tailscale/tailscale/issues/7946

**Closed by DentonGentry** 2023-10-21 22:10 UTC
Labels: needs-triage, fr
