### ISSUE TITLE
windows: Failed to connect to Tailscale service.

### ISSUE THREAD

**Issue by LingfengZhou0112** [tailscale/tailscale#6918] opened 2023-01-09 14:23 UTC
### What is the issue?

---------------------------
Tailscale Error
---------------------------
Failed to connect to Tailscale service.

Version 1.34.1 (t328b49c4d-g921b59a2e)

LogID: a97c93559dc84d49ce386a4cc47815502284e487a48bae71fa342b06daa5903f

(Ctrl-C to copy this text)

确定   
---------------------------

### Steps to reproduce

Originally use tailscale 1.22.2, normally for several months

Days ago, it suddenly showed there is a "backend error" （maybe after I uninstall some softwares like VMWare）and would close itself directly.

I thought it could be solved by updating the tailscale version, so I updated it to 1.34.1, and here comes the "Failed to connect to Tailscale service." shown above.

I thought maybe VMWare wasn't uninstalled totally, which left two network adapters used by the virtual machines. So I deleted them, but it didn't work, still "Failed to connect to Tailscale service."

I also tried reinstalling tailscale, but the same issue happened.

What needs to be mentioned is that when I opened the Device Manager of my Win10, I noticed that in the network adapter column, the device _Tailscale Tunnel_ is being created and then deleted (with tailscale turned on but not connecting to others, that is, the icon is at grey status)

Every time I click the grey icon, a box will appear and show the issue.

### OS

Windows

### OS version

Win 10

### Tailscale version

1.34.1

### Bug report

503 Service Unavailable: no backend

**Comment by bradfitz** [comment] 2023-01-14 22:06
@dblohm7  ....

```
2023-01-06 10:02:06.6129933 +0000 UTC: Timed out waiting for device query: 等待的操作过时。 (Code 0x00000102)
2023-01-06 10:02:06.6129933 +0000 UTC: Failed to setup adapter (problem code: 0x38, ntstatus: 0x0): 设备未就绪。 (Code 0x000010DF)
2023-01-06 10:02:06.6529082 +0000 UTC: State of service "NetSetupSvc" and its dependencies:
2023-01-06 10:02:06.6534356 +0000 UTC: [
2023-01-06 10:02:06.6534356 +0000 UTC:   {
2023-01-06 10:02:06.6534356 +0000 UTC:     "serviceName": "NetSetupSvc",
2023-01-06 10:02:06.6534356 +0000 UTC:     "serviceType": "WIN32",
2023-01-06 10:02:06.6534356 +0000 UTC:     "state": "RUNNING",
2023-01-06 10:02:06.6534356 +0000 UTC:     "startupType": "DEMAND_START",
2023-01-06 10:02:06.6539849 +0000 UTC:     "triggers": [
2023-01-06 10:02:06.6539849 +0000 UTC:       {
2023-01-06 10:02:06.6539849 +0000 UTC:         "triggerType": 7,
2023-01-06 10:02:06.6539849 +0000 UTC:         "action": 1,
2023-01-06 10:02:06.6539849 +0000 UTC:         "triggerSubtype": "{2D7A2816-0C5E-45FC-9CE7-570E5ECDE9C9}",
2023-01-06 10:02:06.6539849 +0000 UTC:         "dataItems": [
2023-01-06 10:02:06.6539849 +0000 UTC:           {
2023-01-06 10:02:06.6539849 +0000 UTC:             "dataType": 1,
2023-01-06 10:02:06.6539849 +0000 UTC:             "data": "7508bca3230a8f12"
2023-01-06 10:02:06.6539849 +0000 UTC:           }
2023-01-06 10:02:06.6539849 +0000 UTC:         ]
2023-01-06 10:02:06.6539849 +0000 UTC:       },
2023-01-06 10:02:06.6545133 +0000 UTC:       {
2023-01-06 10:02:06.6545133 +0000 UTC:         "triggerType": 7,
2023-01-06 10:02:06.6545133 +0000 UTC:         "action": 1,
2023-01-06 10:02:06.6545133 +0000 UTC:         "triggerSubtype": "{2D7A2816-0C5E-45FC-9CE7-570E5ECDE9C9}",
2023-01-06 10:02:06.6545133 +0000 UTC:         "dataItems": [
2023-01-06 10:02:06.6545133 +0000 UTC:           {
2023-01-06 10:02:06.6545133 +0000 UTC:             "dataType": 1,
2023-01-06 10:02:06.6545133 +0000 UTC:             "data": "7510bca3230a8f12"
2023-01-06 10:02:06.6550188 +0000 UTC:           }
2023-01-06 10:02:06.6550188 +0000 UTC:         ]
2023-01-06 10:02:06.6550188 +0000 UTC:       },
2023-01-06 10:02:06.6550188 +0000 UTC:       {
2023-01-06 10:02:06.6550188 +0000 UTC:         "triggerType": 6,
2023-01-06 10:02:06.6552459 +0000 UTC:         "action": 1,
2023-01-06 10:02:06.6552459 +0000 UTC:         "triggerSubtype": "{BC90D167-9470-4139-A9BA-BE0BBBF5B74D}",
2023-01-06 10:02:06.6552459 +0000 UTC:         "dataItems": [
2023-01-06 10:02:06.6552459 +0000 UTC:           {
2023-01-06 10:02:06.6552459 +0000 UTC:             "dataType": 2,
2023-01-06 10:02:06.6552459 +0000 UTC:             "data": "610031003100310066003100630035002d0035003900320033002d0034003700630030002d0039006100360038002d006400300062006100660062003500370037003900300031000000"
2023-01-06 10:02:06.6552459 +0000 UTC:           }
2023-01-06 10:02:06.6552459 +0000 UTC:         ]
2023-01-06 10:02:06.6552459 +0000 UTC:       }
2023-01-06 10:02:06.6552459 +0000 UTC:     ]
2023-01-06 10:02:06.6557532 +0000 UTC:   },
2023-01-06 10:02:06.6557779 +0000 UTC:   {
2023-01-06 10:02:06.6557779 +0000 UTC:     "serviceName": "RpcSs",
2023-01-06 10:02:06.6557779 +0000 UTC:     "serviceType": "WIN32",
2023-01-06 10:02:06.6557779 +0000 UTC:     "state": "RUNNING",
2023-01-06 10:02:06.6557779 +0000 UTC:     "startupType": "AUTO_START"
2023-01-06 10:02:06.6557779 +0000 UTC:   },
2023-01-06 10:02:06.6557779 +0000 UTC:   {
2023-01-06 10:02:06.6557779 +0000 UTC:     "serviceName": "DcomLaunch",
2023-01-06 10:02:06.6557779 +0000 UTC:     "serviceType": "WIN32",
2023-01-06 10:02:06.6557779 +0000 UTC:     "state": "RUNNING",
2023-01-06 10:02:06.6563117 +0000 UTC:     "startupType": "AUTO_START"
2023-01-06 10:02:06.6563117 +0000 UTC:   },
2023-01-06 10:02:06.6563117 +0000 UTC:   {
2023-01-06 10:02:06.6563117 +0000 UTC:     "serviceName": "RpcEptMapper",
2023-01-06 10:02:06.6563117 +0000 UTC:     "serviceType": "WIN32",
2023-01-06 10:02:06.6563117 +0000 UTC:     "state": "RUNNING",
2023-01-06 10:02:06.6563117 +0000 UTC:     "startupType": "AUTO_START"
2023-01-06 10:02:06.6568418 +0000 UTC:   }
2023-01-06 10:02:06.6568418 +0000 UTC: ]
2023-01-06 10:02:06.6568418 +0000 UTC: tstunNew: backoff: 1561 msec
2023-01-06 10:02:08.3797542 +0000 UTC: Using existing driver 0.14
2023-01-06 10:02:08.4003212 +0000 UTC: Creating adapter
2023-01-06 10:02:23.4291004 +0000 UTC: Timed out waiting for device query: 等待的操作过时。 (Code 0x00000102)
2023-01-06 10:02:23.4291004 +0000 UTC: Failed to setup adapter (problem code: 0x38, ntstatus: 0x0): 设备未就绪。 (Code 0x000010DF)
2023-01-06 10:02:23.4522676 +0000 UTC: State of service "NetSetupSvc" and its dependencies:
2023-01-06 10:02:23.4522676 +0000 UTC: [
2023-01-06 10:02:23.4522676 +0000 UTC:   {
2023-01-06 10:02:23.4522676 +0000 UTC:     "serviceName": "NetSetupSvc",
2023-01-06 10:02:23.4522676 +0000 UTC:     "serviceType": "WIN32",
2023-01-06 10:02:23.4522676 +0000 UTC:     "state": "RUNNING",
2023-01-06 10:02:23.4522676 +0000 UTC:     "startupType": "DEMAND_START",
2023-01-06 10:02:23.4522676 +0000 UTC:     "triggers": [
2023-01-06 10:02:23.4522676 +0000 UTC:       {
2023-01-06 10:02:23.4522676 +0000 UTC:         "triggerType": 7,
2023-01-06 10:02:23.4522676 +0000 UTC:         "action": 1,
2023-01-06 10:02:23.4527733 +0000 UTC:         "triggerSubtype": "{2D7A2816-0C5E-45FC-9CE7-570E5ECDE9C9}",
2023-01-06 10:02:23.4528045 +0000 UTC:         "dataItems": [
2023-01-06 10:02:23.4528045 +0000 UTC:           {
2023-01-06 10:02:23.4528045 +0000 UTC:             "dataType": 1,
2023-01-06 10:02:23.4528045 +0000 UTC:             "data": "7508bca3230a8f12"
2023-01-06 10:02:23.4528045 +0000 UTC:           }
2023-01-06 10:02:23.4528045 +0000 UTC:         ]
2023-01-06 10:02:23.4528045 +0000 UTC:       },
2023-01-06 10:02:23.4528045 +0000 UTC:       {
2023-01-06 10:02:23.4528045 +0000 UTC:         "triggerType": 7,
2023-01-06 10:02:23.4528045 +0000 UTC:         "action": 1,
2023-01-06 10:02:23.4528045 +0000 UTC:         "triggerSubtype": "{2D7A2816-0C5E-45FC-9CE7-570E5ECDE9C9}",
2023-01-06 10:02:23.4528045 +0000 UTC:         "dataItems": [
2023-01-06 10:02:23.4528045 +0000 UTC:           {
2023-01-06 10:02:23.4528045 +0000 UTC:             "dataType": 1,
2023-01-06 10:02:23.4528045 +0000 UTC:             "data": "7510bca3230a8f12"
2023-01-06 10:02:23.4528045 +0000 UTC:           }
2023-01-06 10:02:23.4528045 +0000 UTC:         ]
2023-01-06 10:02:23.4528045 +0000 UTC:       },
2023-01-06 10:02:23.4528045 +0000 UTC:       {
2023-01-06 10:02:23.4528045 +0000 UTC:         "triggerType": 6,
2023-01-06 10:02:23.4533099 +0000 UTC:         "action": 1,
2023-01-06 10:02:23.4533341 +0000 UTC:         "triggerSubtype": "{BC90D167-9470-4139-A9BA-BE0BBBF5B74D}",
2023-01-06 10:02:23.4533341 +0000 UTC:         "dataItems": [
2023-01-06 10:02:23.4533341 +0000 UTC:           {
2023-01-06 10:02:23.4533341 +0000 UTC:             "dataType": 2,
2023-01-06 10:02:23.4533341 +0000 UTC:             "data": "610031003100310066003100630035002d0035003900320033002d0034003700630030002d0039006100360038002d006400300062006100660062003500370037003900300031000000"
2023-01-06 10:02:23.4533341 +0000 UTC:           }
2023-01-06 10:02:23.4533341 +0000 UTC:         ]
2023-01-06 10:02:23.4533341 +0000 UTC:       }
2023-01-06 10:02:23.4533341 +0000 UTC:     ]
2023-01-06 10:02:23.4533341 +0000 UTC:   },
2023-01-06 10:02:23.4533341 +0000 UTC:   {
2023-01-06 10:02:23.4533341 +0000 UTC:     "serviceName": "RpcSs",
2023-01-06 10:02:23.4533341 +0000 UTC:     "serviceType": "WIN32",
2023-01-06 10:02:23.4533341 +0000 UTC:     "state": "RUNNING",
2023-01-06 10:02:23.4533341 +0000 UTC:     "startupType": "AUTO_START"
2023-01-06 10:02:23.4533341 +0000 UTC:   },
2023-01-06 10:02:23.4533341 +0000 UTC:   {
2023-01-06 10:02:23.4533341 +0000 UTC:     "serviceName": "DcomLaunch",
2023-01-06 10:02:23.4533341 +0000 UTC:     "serviceType": "WIN32",
2023-01-06 10:02:23.4533341 +0000 UTC:     "state": "RUNNING",
2023-01-06 10:02:23.4533341 +0000 UTC:     "startupType": "AUTO_START"
2023-01-06 10:02:23.4533341 +0000 UTC:   },
2023-01-06 10:02:23.4533341 +0000 UTC:   {
2023-01-06 10:02:23.4538609 +0000 UTC:     "serviceName": "RpcEptMapper",
2023-01-06 10:02:23.4538609 +0000 UTC:     "serviceType": "WIN32",
2023-01-06 10:02:23.4538609 +0000 UTC:     "state": "RUNNING",
2023-01-06 10:02:23.4538609 +0000 UTC:     "startupType": "AUTO_START"
2023-01-06 10:02:23.4538609 +0000 UTC:   }
2023-01-06 10:02:23.4538609 +0000 UTC: ]
2023-01-06 10:02:23.4538609 +0000 UTC: tstunNew: backoff: 2222 msec
2023-01-06 10:02:25.7977653 +0000 UTC: Using existing driver 0.14
```

**Comment by DentonGentry** [comment] 2023-02-13 00:41
Duplicate of https://github.com/tailscale/tailscale/issues/4225

**Closed by DentonGentry** 2023-02-13 00:41 UTC
Labels: OS-windows, L1 Very few, P3 Can't get started, T5 Usability, bug
