### ISSUE TITLE
FR: macOS/Windows collapse "My Devices" submenu if there are no siblings

### ISSUE THREAD

**Issue by pbnjay** [tailscale/tailscale#4384] opened 2022-04-08 18:24 UTC
### What are you trying to do?

I'm trying to get the tailscale IP of one of my devices, using the menu:
 sysbar icon -> "Network devices" -> "My Devices" -> "[hostname]"
 
I don't have anything shared with me (yet?!) so "My Devices" is literally the only choice in the middle there.
Since the menu is close to the edge of my screen, 3 levels actually requires me to move my mouse back and forth to get to the correct item, and inevitably I miss it on the way back and have to do it again slower. That is, the list of my hostnames is to the left of "My Devices" instead of the right.

### How should we solve this?

If "My Devices" is the only menu item at that level, instead just enumerate the devices at that point instead of adding the extra level to the menu.

### What is the impact of not solving this?

It's mostly just annoying/frustrating when I accidentally miss the menu.

### Anything else?

There's a little bit of a discrepancy between macOS / Windows: Windows does not show my account info in the list of devices, but macOS does. So in macOS I always have to go to at least the 3rd item.

**Comment by DentonGentry** [comment] 2022-05-08 02:08
Duplicate of https://github.com/tailscale/tailscale/issues/3319

**Closed by DentonGentry** 2022-05-08 02:08 UTC
Labels: L2 Few, P1 Nuisance, T2 Visual Polish, fr
