### ISSUE TITLE
Tailscale 1.1.372 installer detected by Windows Defender as Win32/Persistence.DQ!ml

### ISSUE THREAD

**Issue by tonyping** [tailscale/tailscale#771] opened 2020-09-18 02:36 UTC
**Describe the bug**
Windows Defender reports the 1.1.372 installer contains Win32/Persistence.DQ!ml

Alert Level: Severe
Status: Active
Category: Suspicious Behavior
Details: This program is dangerous and executes commands from an attacker.

The file was then immediately quarantined by Defender.

**To Reproduce**
Download installer 1.1.372. Defender will alert and send the file to the quarantine.

**Expected behavior**
Most likely a false positive, but still worth investigating what part of the new code is tripping Defender. This did not happen with v1.04 nor any of the unstable builds I downloaded before.

**Screenshots**
https://i.imgur.com/JYL9sJ2.png

**Version information:**
 - Device: [Laptop]
 - OS: [Windows 10]
 - OS version: [Windows 10]
 - Tailscale version: [1.1.372]

**Additional context**

**Comment by bradfitz** [comment] 2020-09-18 02:42
Sigh.

Yeah, I saw Defender get angry a bit the other day too, but then it went away.

FWIW, our Windows builds aren't even built on Windows. (We don't even have support for building on Windows). They're cross compiled from a Linux machine, including the NSIS packaging. So this is almost certainly a false positive.

Microsoft describes it as:

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Behavior:Win32/Persistence.DQ!ml&ThreatID=2147737492

> This generic detection for suspicious behaviors is designed to catch potentially malicious files. If you downloaded a file or received it through email, ensure that it is from a reliable source before opening it.

Kinda useless.

Virustotal says:

https://www.virustotal.com/gui/url/fe95876a62e64d45d094f44e6932a1e03dcc5ae7ab5eb2f3f848e9cd2c4a36d7/detection

> No engines detected this URL

**Comment by danderson** [comment] 2020-09-18 02:43
Looks like we can submit the false positive for evaluation at https://www.microsoft.com/en-us/wdsi/filesubmission .

cc @bradfitz I think you encountered this while hacking, maybe?

**Comment by tonyping** [comment] 2020-09-18 03:10
> Virustotal says:
> 
> [virustotal.com/gui/url/fe95876a62e64d45d094f44e6932a1e03dcc5ae7ab5eb2f3f848e9cd2c4a36d7/detection](https://www.virustotal.com/gui/url/fe95876a62e64d45d094f44e6932a1e03dcc5ae7ab5eb2f3f848e9cd2c4a36d7/detection)
> 
> > No engines detected this URL

I think it's being detected by heuristics rather than by definitions.

**Comment by jucor** [comment] 2020-09-18 18:42
Off-topic, but good job developing cross-compiled!

**Comment by 33b5e5** [comment] 2020-09-23 17:28
WIndows Defender on my Win 10 machine is alternating between Behavior:Win32/Persistence.DQ!ml and Trojan:Win32/Zpevdo.B. When it decides to mark it as the trojan, it's labeled "severe", and it quarantines the file. I've been reporting the files as safe whenever given the opportunity.

**Comment by tonyping** [comment] 2020-09-28 07:38
@33b5e5  Virustotal now 9 engines detecting.

**Comment by alexbrainman** [comment] 2020-09-30 08:46
> Looks like we can submit the false positive for evaluation at https://www.microsoft.com/en-us/wdsi/filesubmission .
> 
> cc @bradfitz I think you encountered this while hacking, maybe?

I can reproduce it here too

![image](https://user-images.githubusercontent.com/9796621/94663535-1e42ee00-034d-11eb-9ff1-624f514b6b73.png)

@danderson do you want me to try and submit false positive report?

Alex

**Comment by DentonGentry** [comment] 2021-02-08 16:34
Note that this doesn't affect current versions like 1.4.0: https://www.virustotal.com/gui/file/90d66417e89ff16c0bdb76b991206467194e93daa732425160204db354d8a7ac/detection (no engines detect a problem)

**Comment by bradfitz** [comment] 2021-03-31 17:36
Closing, as there's nothing we can do here, and the antivirus companies seem to have learned.

**Closed by bradfitz** 2021-03-31 17:36 UTC
Labels: OS-windows

**Comment by marshyon** [comment] 2021-12-04 17:15
This is blocked by McAfee as a virus and quaranteened on window
![tailscale-virus-blocked-mcafee-Screenshot 2021-12-04 171334](https://user-images.githubusercontent.com/357807/144718400-465f0b9f-4a5a-49e2-9310-3ce9c3145fcf.png)
s

**Comment by DentonGentry** [comment] 2021-12-04 17:21
This happens fairly often after a new release of Tailscale. McAfee's algorithm considers new binaries which it hasn't seen a signature for to be inherently more dangerous. McAfee will change it to passing after a while.

https://www.virustotal.com/gui/file/07d2e5ca2695a7a0002f2251f4d2032212f4a2fb894c2883f65fd7d66633e569
