### ISSUE TITLE
Error starting tailscale up on Ubuntu 18.04 LTS under Windows WSL 2

### ISSUE THREAD

**Issue by rugyoga** [tailscale/tailscale#493] opened 2020-06-21 22:46 UTC
Trying to install tailscale on my shiny new Ubuntu 18.04 LTS installation
under Windows Subsystem for Linux 2.

But the install fails with the following error:

```bash
2020/06/21 15:41:07 Failed to connect to connect to tailscaled. (safesocket.Connect: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory)
```

I tried both `stable` and `unstable` with the same result.
I would include logs but I couldn't find them.
Where are they on Ubuntu 18.04?

**Comment by bradfitz** [comment] 2020-06-22 02:35
You need to also be running the daemon, tailscaled. Did you already try that and get an error?

**Comment by mmcc** [comment] 2020-06-24 04:38
👋 Jumping in because I'm seeing the same issue when trying to follow the install directions for Ubuntu 20 in WSL2 (also tried the unstable branch as well). Other threads along these lines say that `tailscaled` should be started in the post-install, but I checked and there's nothing in journalctl logs related to `tailscaled`. 

Running `tailscaled` directly gives me:

```
logtail started
Program starting: v0.99.1-127-g42368054, Go 1.14.4-ts56db765: []string{"tailscaled"}
LogID: d4944d4521862cc2d1a526705a0587843d26ea8ac04435761bc4b48c9af130bf
--state is required
```

**Comment by bradfitz** [comment] 2020-06-24 04:45
What does `sudo systemctl status tailscaled` say?
 
And `sudo journalctl _SYSTEMD_INVOCATION_ID=$(systemctl show -p InvocationID --value tailscaled.service) | head -30`?

**Comment by mmcc** [comment] 2020-06-24 05:40
I'm guessing this is because systemd isn't enabled by default on Ubuntu images from the Microsoft store. Running `sudo tailscaled` starts the daemon and then I'm able to run `tailscale up`. 

Just for completeness, running the `systemctl status` command:

```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

**Comment by bradfitz** [comment] 2020-06-24 06:01
Good to know, thanks. Not sure what's left to do here so closing for now.

**Closed by bradfitz** 2020-06-24 06:01 UTC

**Comment by kellytrinh** [comment] 2020-08-06 03:58
Confirmed running `sudo tailscaled` manually allows `tailscale` to work  (and in this case ; provide a nice fix to the brokenness that is the WSL2 networking model)

**Comment by openaspace** [comment] 2020-11-20 14:07
`tailscaled
logtail started
Program starting: v1.2.8-tcde3a23b6-g1f7ecb611, Go 1.15.4-tsf9db43b: []string{"tailscaled"}
LogID: 423d0cce5102da9cd20b5319a40f2f316cd6a638487331c519351296e5f1b5d5
logpolicy: using system state directory "/var/lib/tailscale"
Starting userspace wireguard engine with tun device "tailscale0"
Linux kernel version: 5.4.73-1-pve
is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: FATAL: Module tun not found in directory /lib/modules/5.4.73-1-pve
tun module not loaded nor found on disk
CreateTUN: CreateTUN("tailscale0") failed; /dev/net/tun does not exist
wgengine.New: CreateTUN("tailscale0") failed; /dev/net/tun does not exist
flushing log.
logger closing down
logtail: dialed "log.tailscale.io:443" in 191ms`




`aled "log.tailscale.io:443" in 191ms
root@go:~# tailscale up
Failed to connect to connect to tailscaled. (safesocket.Connect: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory)`

**Comment by bradfitz** [comment] 2020-11-20 15:53
@openaspace, you're commenting on a closed issue (which aren't tracked), and also that looks unrelated. Your kernel is -pve, which sounds like Proxmox, not WSL.

**Comment by udkl** [comment] 2022-09-30 01:09
I landed on this via a search .... to help other seekers, the solution that worked for me : https://superuser.com/a/598412

**Comment by kenny1323** [comment] 2023-08-29 22:45
#Necromancy.
@bradfitz 

I am on debian11 (AntiX Linux).
This was the solution
sudo tailscaled 

The installation page doesn't talk about this step (sudo tailscaled).
Someone should fix the installation instructions on that page
https://tailscale.com/download   .

------------------------
#Packages are available for x86 and ARM CPUs, in both 32-bit and 64-bit variants.
#Add Tailscale’s package signing key and repository:

curl -fsSL https://pkgs.tailscale.com/stable/debian/bullseye.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
curl -fsSL https://pkgs.tailscale.com/stable/debian/bullseye.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list


#Install Tailscale:
sudo apt-get update
sudo apt-get install tailscale


#MISSING STEP
sudo tailscaled

#Connect your machine to your Tailscale network and authenticate in your browser:
sudo tailscale up

#You’re connected! You can find your Tailscale IPv4 address by running:
tailscale ip -4

--------------------------

**Comment by DentonGentry** [comment] 2023-08-29 23:13
> The installation page doesn't talk about this step (sudo tailscaled).
> Someone should fix the installation instructions on that page https://tailscale.com/download .

AntiX does not use `systemd`, which the installer script expects to have available.

- If AntiX uses `sysvinit`, we developed an init.d script for gitpod at https://github.com/tailscale/gitpod/blob/main/tailscaled.service and which might also work for Anti-X
- The gitpod script uses start-stop-daemon. If AntiX doesn't use start-stop-daemon, the QNAP qpkg has an init script which doesn't rely on it and might be useful as a basis: https://github.com/tailscale/tailscale-qpkg/blob/main/Tailscale/shared/Tailscale.sh
    Various QNAP-isms at the start of the file would need to be removed.
