### ISSUE TITLE
Support iOS on demand connections

### ISSUE THREAD

**Issue by mattradford** [tailscale/tailscale#1534] opened 2021-03-17 23:44 UTC
**Is your feature request related to a problem? Please describe.**

Submitting in response to this Twitter thread with @crawshaw: https://twitter.com/davidcrawshaw/status/1372299409451413507.

The official [Wireguard iOS app](https://apps.apple.com/us/app/wireguard/id1441195209) allows for [on-demand VPN connections](https://developer.apple.com/documentation/networkextension/personal_vpn/vpn_on_demand_rules) - auto-connecting to a VPN when switching networks. I currently use this to connect to my home Wireguard VPN whenever I leave the house, i.e. not on my home wifi.

With the release of exit node functionallity in Tailscale 1.6.0, it becomes possible to use Tailscale as a replacement for this Wireguard VPN, by routing all traffic back to an exit node at my home.

I cannot currently have this connection be automatically enabled when I leave the house.

**Describe the solution you'd like**

Quite a few other iOS VPN apps allow for on demand connections. The Tailscale iOS app does not.

In the Tailscale iOS app, allow for:

-  on demand connections
-  the ability to include or exclude cellular and specified wifi networks

If users have multiple exit nodes available, Tailscale should connect to the last one chosen.

This is how it looks in the Wireguard iOS app:

![IMG_06BDA28D8CD0-1](https://user-images.githubusercontent.com/2804540/111551904-29fa6380-8779-11eb-912f-b4cc15458fea.jpeg)

**Describe alternatives you've considered**

An alternative would be to support Shortcuts, such as Tracker VPN does: https://medium.com/@equinux/thats-what-you-ve-been-waiting-for-siri-shortcuts-in-vpn-tracker-world-connect-1-1-2eb5b56ebba0.

This means people have to set up their own shortcuts to toggle VPN. It's less discoverable, but does allow for more conditions than just changing networks. Hey, why not both? ;)

**Additional context**

I suspect this would allow some people to ditch commercial VPN providers, especially if we can share exit nodes.

**Comment by mcompton13** [comment] 2021-09-17 19:50
I would also like a feature like this, but with a slight twist. I'd like to keep tailscale always running on my phone (or laptop) all the time so I can always access servers/services on running in my personal tailscale network, but it would be awesome if it could conditionally use an exit node when I join an untrusted wifi networks. That way if I'm on my home network wifi or using LTE talescale does not need to worry about routing traffic through my exit node, but as soon as I join and use the wifi at the airport all of my traffic is encrypted and routed over my tailscale network through my exit node.

I think the UI would look similar to the one above from the wireguard UI, just that it might be titled something like "Conditional Exit Node Use" so the user could choose exactly which network situations to use the exit node routing.

**Comment by bohtho** [comment] 2021-11-30 10:54
I currently use the combination of Tailscale network and Mullvad VPN servers with the Tailscale iOS client.

To be able to "set it and forget" (especially on my iPhone) and still have both access to my Tailscale network and Mullvad VPN servers I have configured my ASUS router with (kernel level) WireGuard to selectively push only traffic coming from a Tailscale exit node on that lan into the outgoing tunnel to the Mullvad (multihop) servers, and other traffic outside the WireGuard tunnel.

Then I can just use the Tailscale client and mostly keep "Use Exit Node" on. But that switch is also the choice between obfuscating traffic or not everywhere, while always staying in the Tailscale network. This is especially handy on the iPhone which can only have one vpn connection at a time, and it needs to be the Tailscale client.

(Well, another setup would be the iOS WireGuard app to the WG server on my router, route Tailscale IPs to my lan exit node (accepting routes), and access the Tailscale network from there, I suppose, but then I lose out on features when the iOS device is part of the Tailscale network itself, and traffic to the latter would always go through my one router/lan).

What is clearly missing compared to other vpn clients is either (intricate) Apple Shortcut support (see issue #) and/or taking advantage of the on-demand feature of the host. This usually relates to the whole vpn connection but in my case I too would prefer it with regard to the "Use Exit Node" option (or separate on-demand for both!).

(Btw, Tailscale integrated support for Mullvad vpn exit nodes would be a massive improvement too but has a separate issue #)

**Comment by ellnic** [comment] 2021-12-20 23:16
+1 for this. 

I've recently been introduced to Tailscale and this is my only major gripe for what is otherwise an excellent product. 

I've been in touch with support about this and was informed that it's because there are multiple VPN profiles. I went as far as factory restoring 1 device just to say I'd ticked the box and with only 1 VPN profile present (Tailscale), after reboot the connection doesn't persist. Can replicate this across many devices so I am unsure why support see different behaviour. 

It would be great to see this sooner rather than later, seems like a pretty critical missing feature.

**Comment by gee-jay-bee** [comment] 2022-03-19 10:26
Same here, I only have one VPN profile. 

I could cope with either SSID / on-demand or shortcuts though the zero config aspiration of Tailscale would suggest the former would be better (simpler)?

**Comment by mvidovicfive** [comment] 2022-04-26 13:57
Same here, i just made duplicate request and i apologize.

I can agree that this feature is the last missing thing to call it best VPN solution ever. It would be set and forget pihole setup. Would gladly support this effort, and switch to tailscale full time from wireguard.

**Comment by digitaldan** [comment] 2022-09-29 18:33
Apologies if i posted this across a few issues, but it does seem this feature would solve a number of open issues here, specifically #5030 , #4646 , #337, #3771

One issue specifically plaguing #5030 and #4646 is that IOS will trigger a user space reboot at night if it crosses a certain memory threshold, which kills tailscale and requires a user to manually go back into the app and connect.  This is happening nightly for many of us.   I would hope that using something like https://developer.apple.com/documentation/networkextension/neondemandruleconnect in the app would cause the app to start again if a on demand rule is matched (like connect on any interface that is active)

**Comment by mattradford** [comment] 2022-09-29 20:18
Thanks @digitaldan for bringing together these issues. It would be great if VPN on Demand solved them.

**Comment by ellnic** [comment] 2022-09-30 06:48
@mattradford it would be great, but I last commented on this in December 2021 and there has been no visible progress since. 

@digitaldan thanks for doing this. The on demand feature as previous mentioned above is my only major hang up with Tailscale. If it were just implemented, it would solve every issue I have with it. I am using it on my devices, but I cannot roll it out to other devices until this is fixed as some users will not remember / cannot be relied upon to flick the switch at each boot. It’s a shame this seems to be a lower priority for the Tailscale team when it would clearly be the solution to a plethora of issues.

**Comment by MarijoVidovic** [comment] 2022-09-30 07:55
I highly doubt they will do anything on this matter. Its been more than a year, and gave feedback multiple times when contacted on email. 

So far pure wireguard is a way to go for me unfortunately.

**Comment by gee-jay-bee** [comment] 2022-09-30 10:28
I guess the "L3 some users" label is why it doesn't get the attention. For me at least, it's probably not the people who understand how to set up tailscale as a system that have a problem. It is indeed "aggravating" (per the other label) but they can put it right. It's the people who want the promise of zero-config. Enable on-demand, forget about it. For those people, it would be a showstopper ... it may not be obvious that the app they actually want to use isn't working because they didn't open Tailscale app first!

**Comment by DentonGentry** [comment] 2022-09-30 22:53
Current work on mobile is focussing on battery and energy use. Though not all iOS users experience it, there are still enough reports of trouble that those issues need to be resolved before expanding usage by implementing on-demand support.

**Comment by offbyone** [comment] 2022-09-30 23:20
I would definitely appreciate reconsidering that prioritization; right now, I'm still affected by #4646 every day, and this would be one path to mitigating that.

**Comment by mattradford** [comment] 2022-10-01 10:47
Thanks for the response @DentonGentry :)

Are you able to indicate roughly when work on this feature is likely to start?

**Comment by digitaldan** [comment] 2022-10-07 03:18
Hi @DentonGentry thanks for commenting.  I guess what i'm hearing is that the IOS client is not fully ready for prime time and enabling on-demand support would lead to increased usage, which is not desired until other issues are resolved.

Since mobile is a primary use case for us, I ended up installing wireguard for the first time and have switched us over to using it for now as the on-demand support is both simple and excellent.  If this ever gets resolved and Tailscale can run continuously on IOS i would defiantly look to come back to using Tailscale.

**Comment by UmiDevSec** [comment] 2023-01-03 23:27
Thanks digitaldan for mentioning that Wireguard for iOS has on-demand support. We just finished migrating to Wireguard from Tailscale and it works amazing!

**Comment by doodlemania2** [comment] 2023-02-06 19:50
Following - this would greatly benefit me too!

**Comment by mattradford** [comment] 2023-02-07 22:35
For those watching this issue, Tailscale has released shortcuts for iOS that enables some automation: https://tailscale.com/blog/ios-macos-shortcuts/
Owing to iOS shortcut limitations you can only perform actions when joining one/all wifi networks, or when leaving a certain area, and these triggers require a manual confirmation. So it's not perfect for turning on Tailscale automatically when you're not at home, but it's a good step forward. Thanks Tailscale 👍

**Comment by MarijoVidovic** [comment] 2023-02-08 08:40
> 

Definitely step in right direction, but not perfect yet. Thanks for heads-up!

**Comment by ezfe** [comment] 2023-02-09 01:36
Just adding my support for this, I constantly find Tailscale has been disabled on my phone.

**Comment by holocronology** [comment] 2023-07-26 17:40
this

**Comment by agottardo** [comment] 2023-08-02 22:55
For those watching here, I'm happy to announce we just shipped an update on [TestFlight](https://testflight.apple.com/join/tLcYLZJV) (v1.47.67) which adds support for VPN On-Demand on iOS. You can set up rules to connect/disconnect when joining any or specific Wi-Fi networks, or when using cellular data. This is of course the first build offering this feature, and as such, it is likely to have some bugs. 

Please report any issues! 🙏🏻 

<img src="https://github.com/tailscale/tailscale/assets/9057073/5cbaaec7-6fb3-48c7-8202-19910bae8dc1" width="250" />

**Comment by digitaldan** [comment] 2023-08-02 22:58
Thats great news @agottardo !

**Comment by ellnic** [comment] 2023-08-02 23:05
Fantastic stuff @agottardo! Well done 👏 I was excited when I noticed you’d self assigned a month ago. Thank you 🙏

**Comment by larizzo** [comment] 2023-08-02 23:48
This is awesome! I’m testing the Except On I have my wireless network name “wlan” set in the “CONNECT EXCEPT ON THESE WI-FI NETWORKS”. It still connects even when I’m connected to my wifi. Let me know if you need any more information.

My bug report is is: BUG-1a03ecc92301ac6bb2e1aa1d3e49101f72663e05d00c47038080acf50d80c76b-20230802234810Z-cf403208697ad270

**Comment by agottardo** [comment] 2023-08-02 23:50
@larizzo I'm aware of this issue. Fix will be coming in the next update.

**Comment by nunofgs** [comment] 2023-08-03 00:02
Very much appreciated. Any thoughts on more advanced configs?

I was using this on a .mobileconfig previously:

```
<!-- Connect if domain name matches the pattern -->
          <dict>
                <key>Action</key>
                <string>EvaluateConnection</string>

                <key>ActionParameters</key>
                <array>
                        <dict>
                                <key>Domains</key>
                                <array>
                                        <string>mydomain.com</string>
                                </array>
                                <key>DomainAction</key>
                                <string>ConnectIfNeeded</string>
                        </dict>
                </array>
          </dict>

<!-- Disconnect VPN when Idle for [amount of seconds] -->
                        <key>DisconnectOnIdle</key>
                        <integer>1</integer>
                        <key>DisconnectOnIdleTimer</key>
                        <integer>120</integer>
```

**Comment by agottardo** [comment] 2023-08-03 00:09
> Very much appreciated. Any thoughts on more advanced configs?
> 
> I was using this on a .mobileconfig previously

For sure, allowing extra custom trigger domains would be handy for some users. Customizing the idle timer would be too. Feel free to file an issue for each of those two settings.

**Comment by agottardo** [comment] 2023-08-03 00:11
@nunofgs oops, I deleted your comment by accident 😓

**Comment by probablypablito** [comment] 2023-08-03 04:11
This is great!

**Comment by QuanTrieuPCYT** [comment] 2023-08-03 06:19
finally

**Comment by agottardo** [comment] 2023-08-04 22:35
TestFlight v1.47.71 will be landing soon and should address some issues with the initial implementation reported here, namely:

- Improved the reliability of the tunnel startup process when the system connects Tailscale without the application running.
- Fixed an issue that could cause 'Except On' On-Demand VPN configurations to not be saved properly.
- Fixed an issue that could cause a crash in the On-Demand VPN configuration view when typing in a network name.

cc @larizzo

**Comment by ellnic** [comment] 2023-08-05 01:05
> finally

This is such an unhelpful comment. How about “Thanks”. Try it 👍

**Comment by jflattery** [comment] 2023-08-07 15:18
The keyboard for adding an SSID to the 'Except On' list should allow for emoji as an SSID may contain emoji.

**Comment by doodlemania2** [comment] 2023-08-07 15:27
I realize that VPNs use more battery, and use one frequently, but the current build seems really impactful to the battery, like almost a % per ten minutes when otherwise idle. Is it test flight logging or something that might could be optimized?

**Comment by agottardo** [comment] 2023-08-08 18:23
> The keyboard for adding an SSID to the 'Except On' list should allow for emoji as an SSID may contain emoji.

A fix for this will be coming in the next build, thanks for reporting!

> I realize that VPNs use more battery, and use one frequently, but the current build seems really impactful to the battery, like almost a % per ten minutes when otherwise idle. Is it test flight logging or something that might could be optimized?

Looking into this.

**Comment by MarijoVidovic** [comment] 2023-08-09 08:01
Good news and thanks @agottardo !

I will try to set it up and test it next week. Keep up good work

**Comment by agottardo** [comment] 2023-08-11 18:16
A new TestFlight version,  v1.47.100, was just submitted to Apple for review and will be available soon. From the change log: 

> This version includes some improvements to the VPN On Demand configuration UI based on your feedback.
> 
> - Removed the 'Save' button from the VPN On Demand configuration view.
> - Any character can now be used in the SSID textfield when setting up a 'Only On' or 'Except On' connection rule.
> - Fixed an issue that could cause 'Do Nothing' connection rules to not be persisted.

Thanks for your feedback, folks!

**Comment by jflattery** [comment] 2023-08-11 20:31
I have rolled back to 1.47.71 from 1.47.100 because the 'except on' wifi logic break when you enter the on-demand settings and close it. I suspect an issue with saving, despite not making edits when entering the menu.

**Comment by agottardo** [comment] 2023-08-11 20:45
> I have rolled back to 1.47.71 from 1.47.100 because the 'except on' wifi logic break when you enter the on-demand settings and close it. I suspect an issue with saving, despite not making edits when entering the menu.

@jflattery oof! I can't reproduce this. Can you share a video?

**Comment by jflattery** [comment] 2023-08-11 23:28
Seems like you fixed it with 1.47.100 (102) 🎉

**Comment by jflattery** [comment] 2023-08-11 23:29
Now if only I could see the status of other clients when not connected to the ts-network 😉

**Comment by agottardo** [comment] 2023-08-11 23:29
1.47.100 (103) is the one with the fix.

**Comment by jflattery** [comment] 2023-08-12 00:06
My b. That's what I meant 🤦‍♂️ lol

**Comment by agottardo** [comment] 2023-08-16 19:05
Closing because we just shipped this in Tailscale v1.48, available on the App Store!

We also have a KB entry with more details and instructions: https://tailscale.com/kb/1291/ios-vpn-on-demand/

**Closed by agottardo** 2023-08-16 19:05 UTC
Labels: OS-ios, L3 Some users, P2 Aggravating, T0 New feature

**Comment by MadSpindel** [comment] 2023-08-16 19:07
@agottardo Really excellent job with the new VPN On-Demand functionality! The only thing I'm missing is being able to enable the exit node in the same way. Do you have any plans to implement such functionality or is that a different Github issue?

**Comment by agottardo** [comment] 2023-08-16 19:11
@MadSpindel Tailscale should remember your active exit node across connections/disconnections. If you were using an exit node before disconnecting, a subsequent reconnection should still use the same exit node you were using previously.

If you need to automate this further, I suggest using our Shortcuts actions inside a personal automation on your iOS device (we have _Use Exit Node_ and _Stop Using Exit Node_ actions). If there is a specific use-case you are unable to support with Shortcuts, open a separate issue and we'll see what we can build around it.

**Comment by mattradford** [comment] 2023-08-16 19:50
This is great @agottardo - thanks for the work on this :)

**Comment by ellnic** [comment] 2023-08-16 21:13
> Closing because we just shipped this in Tailscale v1.48, available on the App Store!
> 
> We also have a KB entry with more details and instructions: https://tailscale.com/kb/1291/ios-vpn-on-demand/
> 
> Please open a separate issue if you experience any issues with this new feature.

Thanks so much! Fantastic work 🥳

**Comment by ellnic** [comment] 2023-08-17 02:39
Sorry, I know this is closed and completed now but I just have to say that I am really loving this:

![image](https://github.com/tailscale/tailscale/assets/16370944/b7f49750-3e71-489a-8a14-ae05f98839c7)

You've done a great job @agottardo  🎉 Thank you again 🙏

**Comment by agottardo** [comment] 2024-02-01 19:58
If anybody is still following this, we now support VPN On-Demand on macOS too.

It just shipped in Tailscale 1.59.22 (unstable build). You can download it [here](https://pkgs.tailscale.com/unstable/#macos). If you use Tailscale on your Mac, please let us know how it works!

**Comment by Simie** [comment] 2024-05-19 10:28
Hey - this is a great feature! Thank you for implementing it.

I was wondering if it'd be possible to support custom DNS search domains? e.g. if I have "mysite.tld" in the [Search Domains](https://tailscale.com/kb/1054/dns#search-domains) config, have the VPN automatically connect whenever a subdomain of "mysite.tld" is visited. Unless I'm missing something this is only supported for the tailnet domain at present.

**Comment by agottardo** [comment] 2024-08-22 21:14
@gabriel-vanca please see https://github.com/tailscale/tailscale/issues/12086 and upvote it if you'd like it to be prioritized.
