### ISSUE TITLE
ExitNode fail over

### ISSUE THREAD

**Issue by mrjware** [tailscale/tailscale#8744] opened 2023-07-29 06:18 UTC
Feature request to allow user to select an order of exit notes for fail over with defined priority if more than two exist. When upper priority exit nodes are available again, endpoint should move back up to higher priority exit node.

**Comment by DentonGentry** [comment] 2023-07-30 14:23
Duplicate of https://github.com/tailscale/tailscale/issues/2598

**Closed by DentonGentry** 2023-07-30 14:23 UTC
