### ISSUE TITLE
Tailscale doesn't work on DSM with build 1.64

### ISSUE THREAD

**Issue by whytf** [tailscale/tailscale#11737] opened 2024-04-14 21:01 UTC
### What is the issue?

Tailscale returns ```failed to connect to local tailscaled (which appears to be running as tailscaled, pid 14514). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial unix /var/packages/Tailscale/var/tailscaled.sock: connect: no such file or directory``` on any command, status web ui doesn't show at all

### Steps to reproduce

- Update/Clean install 1.64 on DSM

### Are there any recent changes that introduced the issue?

- Rollback to 1.62.1 fixed the issue

### OS

- Synology

### OS version

- DSM 7.2.1-69057 Update 4

### Tailscale version

- 1.64.0

### Bug report

- Can't as any tailscale command returns an error provided earlier

**Comment by irbekrm** [comment] 2024-04-15 07:46
Thanks for opening the issue. I am not super familiar with Synology, is there any way you could get logs from tailscaled/tailscaled startup logs, i.e via `synosystemctl`? (cc @kelivel )

**Comment by kelivel** [comment] 2024-04-15 13:59
@irbekrm Reproduced on my test tailnet, hostname Oryx [(bugreport)](http://go/bug/BUG-a72471f0ff1377b803678c18d14fe0aa956b9326e54bdb05af79a84e9b573007-20240415135229Z-f9babde6452a6a05)

```
2024-04-15 13:48:29	deleting [-j ts-input] in filter/INPUT: running [/sbin/iptables -t filter -D INPUT -j ts-input --wait]: exit status 4: Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied
2024-04-15 13:48:43	deleting [-j ts-forward] in filter/FORWARD: running [/sbin/iptables -t filter -D FORWARD -j ts-forward --wait]: exit status 4: Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied
2024-04-15 13:48:52	deleting [-j ts-postrouting] in nat/POSTROUTING: running [/sbin/iptables -t nat -D POSTROUTING -j ts-postrouting --wait]: exit status 4: Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied
2024-04-15 13:49:18	linuxfw: clear iptables: multiple errors: flushing filter/ts-input: running [/sbin/iptables -t filter -N ts-input --wait]: exit status 4: Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied flushing filter/ts-forward: running [/sbin/iptables -t filter -N ts-forward --wait]: exit status 4: Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied flushing nat/ts-postrouting: running [/sbin/iptables -t nat -N ts-postrouting --wait]: exit status 4: Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied
2024-04-15 13:49:27	deleting [-j ts-input] in filter/INPUT: running [/sbin/ip6tables -t filter -D INPUT -j ts-input --wait]: exit status 4: Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied
2024-04-15 13:49:37	deleting [-j ts-forward] in filter/FORWARD: running [/sbin/ip6tables -t filter -D FORWARD -j ts-forward --wait]: exit status 4: Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied
2024-04-15 13:49:49	deleting [-j ts-postrouting] in nat/POSTROUTING: running [/sbin/ip6tables -t nat -D POSTROUTING -j ts-postrouting --wait]: exit status 4: Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied
2024-04-15 13:50:19	linuxfw: clear ip6tables: multiple errors: flushing filter/ts-input: running [/sbin/ip6tables -t filter -N ts-input --wait]: exit status 4: Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied flushing filter/ts-forward: running [/sbin/ip6tables -t filter -N ts-forward --wait]: exit status 4: Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied flushing nat/ts-postrouting: running [/sbin/ip6tables -t nat -N ts-postrouting --wait]: exit status 4: Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied
```

```
2024-04-15 13:50:19	cleanup: list tables: netlink receive: operation not permitted
2024-04-15 13:50:19	wgengine.NewUserspaceEngine(tun "tailscale0") ...
2024-04-15 13:50:19	Linux kernel version: 4.4.302+
2024-04-15 13:50:19	'modprobe tun' successful
2024-04-15 13:50:19	/dev/net/tun: Dcrw-------
2024-04-15 13:50:19	wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): permission denied
2024-04-15 13:50:19	wgengine.NewUserspaceEngine(tun "userspace-networking") ...
2024-04-15 13:50:19	dns: [rc=unknown ret=direct]
2024-04-15 13:50:19	dns: using "direct" mode
2024-04-15 13:50:19	using fake (no-op) tun device
2024-04-15 13:50:19	using fake (no-op) OS network configurator
```

**Comment by bradfitz** [comment] 2024-04-15 16:43
So turns out the problem was db760d0bacd351a77f4 (#11601) that landed between Synology testing on unstable 1.63.110 and 1.64.0 being cut.

**Closed** 2024-04-15 16:49 UTC
Labels: L3 Some users, P3 Can't get started, T6 Major usability, OS-synology, bug, support

**Comment by ryankoski** [comment] 2024-04-17 05:07
I see that v1.64.1 was declared as a release (https://github.com/tailscale/tailscale/releases/tag/v1.64.1), but I do not see updated packages on pkgs.tailscale.com. Any chance we can get the fixed build published for download?

**Comment by irbekrm** [comment] 2024-04-17 07:04
Hi @ryankoski 1.64.1 was released for Synology only (only for this bug), you should be able to find them here https://pkgs.tailscale.com/stable/#spks
