### ISSUE TITLE
Using exit nodes on a machine without policy routing breaks internet connectivity

### ISSUE THREAD

**Issue by maisem** [tailscale/tailscale#1701] opened 2021-04-12 23:39 UTC
**Describe the bug**
Using exit nodes on a machine without policy routing breaks internet connectivity.

**To Reproduce**
1. Verify that internet traffic works
1. Make sure that `ip rule` is not available
1. Run `tailscale up --exit-node=<tailscale_ip_of_exit_node>`
1. Verify that internet traffic no longer works
1. Verify that local network traffic still works

**Expected behavior**
Internet connectivity continues to function and is routed via the exit node.

**Version information:**
 - Device: VM
 - OS: Linux
 - OS version: NixOS 20.09
 - Tailscale version: 1.6.0

**Comment by DentonGentry** [comment] 2023-02-12 13:54
Appears to still be a problem: https://github.com/tailscale/tailscale/blob/10b20fd1c725f1627d2fad43acbd727b13cb9dbf/wgengine/router/router_linux.go#L179

However I think the solution is the same as https://github.com/tailscale/tailscale/issues/391. I don't think we'd do anything differently to address this specifically.

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment] 2023-06-02 23:03
Duplicate of https://github.com/tailscale/tailscale/issues/391

**Closed by DentonGentry** 2023-06-02 23:03 UTC
Labels: OS-linux, distro-nixos, L1 Very few, P2 Aggravating, T5 Usability, exit-node
