### ISSUE TITLE
CLI not working on MacOS Sequoia

### ISSUE THREAD

**Issue by MarkoMekapses** [tailscale/tailscale#13924] opened 2024-10-26 23:39 UTC
### What is the issue?

Trying to run the CLI results in "Could not dlopen extension" whether use the /usr/local/bin/tailscale or the /Applications/Tailscale.app/Contents/MacOS/Tailscale command. Nonetheless, if I run it as an app, Tailscale.app works fine.

### Steps to reproduce

using any cli command, even tailscale version or --help results in the message "Could not dlopen extension"

### OS

macOS

### OS version

18.1

### Tailscale version

1.77.35 Standalone Variant

**Comment by bradfitz** [comment] 2024-10-27 16:31
Duplicate of #13920

**Closed by bradfitz** 2024-10-27 16:31 UTC
Labels: needs-triage, bug

**Comment by r3n3x** [comment] 2024-10-28 07:49
I confirm this bug occurs with MacOS 15.1 (24B83), too. Immediately after the update to 1.77.36 CLI gives "Could not dlopen extension".
With 1.77.34 I could use CLI tailscale normally.
