### ISSUE TITLE
Manual setting of service types in admin consol.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2804] opened 2021-09-07 13:53 UTC
User suggested feature for manual settings of services,

There was a prompt for feedback about services:
- Would be useful to be able to manually mark a service as HTTP (or other types).
- It's unclear how this integrates with MagicDNS (or doesn't).

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3jdqp)

**Comment by DentonGentry** [comment] 2021-11-10 02:16
Duplicate of https://github.com/tailscale/tailscale/issues/2516

**Closed by DentonGentry** 2021-11-10 02:16 UTC
Labels: admin UI, L3 Some users, P1 Nuisance, T2 Visual Polish
