### ISSUE TITLE
ChromeOS+ARCVM doesn't redirect the IPv6 default route to exit nodes

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#4925] opened 2022-06-24 19:54 UTC
On a brand new HP 14a chromebook (with "ARCVM", the new sandboxing thing for Android apps), turned on Tailscale. The routing table seen by crosh only shows Tailscale IPv4 routes, nothing for IPv6.

Further, enabling exit nodes does not capture the IPv6 default route, so the exit node routing only half works.

Unclear if this is a bug in ChromeOS/ARCVM, or if tailscale is incorrectly deciding that IPv6 is unavailable. My fear is that ARCVM only exposes IPv4 to the Android environment because "why would it need more than that", and as a result we can no longer control IPv6 routing on ChromeOS.

cc @bradfitz @raggi

**Comment by DentonGentry** [comment] 2023-02-13 13:02
Possibly the same issue as https://github.com/tailscale/tailscale/issues/3511

**Comment by DentonGentry** [comment] 2023-06-03 15:58
Duplicate of https://github.com/tailscale/tailscale/issues/3511

**Closed by DentonGentry** 2023-06-03 15:58 UTC
Labels: connectivity, OS-chromeos, L1 Very few, P5 Halts deployment, T6 Major usability, exit-node
