### ISSUE TITLE
Colliding tailscale nodes

### ISSUE THREAD

**Issue by mikkelam** [tailscale/tailscale#1498] opened 2021-03-15 15:11 UTC
**Describe the bug**
I have two raspberry pis running. I cloned the sd card of one and inserted in the other. I later change the hostname of the new one.

Now, i'm trying to re-log them both on tailscale but they seem to constantly replace eachother on the admin interface.

**To Reproduce**
Clone os and have two running on the same time

**Expected behavior**
Both nodes should coexist

**Screenshots**
here's an excerpt of the logs:
```
Mar 15 15:06:49 ris3 tailscaled[1984]: Received error: PollNetMap: initial fetch failed 404: node key not found
Mar 15 15:06:49 ris3 tailscaled[1984]: control: mapRoutine: backoff: 19375 msec
Mar 15 15:07:00 ris3 tailscaled[1984]: magicsock: endpoints changed: 87.49.146.15:57051 (stun), 87.49.146.15:41641 (port_in), 192.168.8.150:41641 (localAddresses), [fd30:a2c2:7a31:d800:8657:80cf:42db:3b4f]:41641 (localAddresses), [fe80::6035:9a77:4812:7a80]:41641 (localAddresses), [fe80::1036:8790:f1d6:5764]:41641 (localAddresses)
Mar 15 15:07:00 ris3 tailscaled[1984]: control: client.newEndpoints(0, [87.49.146.15:57051 87.49.146.15:41641 192.168.8.150:41641 [fd30:a2c2:7a31:d800:8657:80cf:42db:3b4f]:41641 [fe80::6035:9a77:4812:7a80]:41641 [fe80::1036:8790:f1d6:5764]:41641])
Mar 15 15:07:09 ris3 tailscaled[1984]: control: mapRoutine: state:authenticated
Mar 15 15:07:09 ris3 tailscaled[1984]: Received error: PollNetMap: initial fetch failed 404: node key not found
Mar 15 15:07:09 ris3 tailscaled[1984]: control: mapRoutine: backoff: 25888 msec
Mar 15 15:07:35 ris3 tailscaled[1984]: control: mapRoutine: state:authenticated
Mar 15 15:07:35 ris3 tailscaled[1984]: Received error: PollNetMap: initial fetch failed 404: node key not found
Mar 15 15:07:35 ris3 tailscaled[1984]: control: mapRoutine: backoff: 25290 msec
Mar 15 15:08:00 ris3 tailscaled[1984]: control: mapRoutine: state:authenticated
Mar 15 15:08:00 ris3 tailscaled[1984]: Received error: PollNetMap: initial fetch failed 404: node key not found
Mar 15 15:08:00 ris3 tailscaled[1984]: control: mapRoutine: backoff: 19557 msec
Mar 15 15:08:20 ris3 tailscaled[1984]: control: mapRoutine: state:authenticated
Mar 15 15:08:20 ris3 tailscaled[1984]: Received error: PollNetMap: initial fetch failed 404: node key not found
Mar 15 15:08:20 ris3 tailscaled[1984]: control: mapRoutine: backoff: 13371 msec

```

**Version information:**
 - raspberry pi 4
 - OS: RaspberryPi OS
 - OS version:`Linux ris3 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux`
 - Tailscale version: `1.4.5`

I realise this is not advised behaviour, but i'm just wondering if there is some way to fix it. Thanks

**Comment by DentonGentry** [comment] 2021-03-15 15:28
This is due to duplicating /var/lib/tailscale/tailscaled.state (see #392), removing that file from one and re-authenticating should resolve it.

**Comment by DentonGentry** [comment] 2021-03-15 15:29
Duplicate of #392

**Closed by DentonGentry** 2021-03-15 15:29 UTC

**Comment by mikkelam** [comment] 2021-03-15 15:38
Alright. That gave me enough clues.

For anyone else stumbling on this issue. What worked for me is:

1. Disconnect all nodes on the admin interface
2. `sudo rm /var/lib/tailscale/tailscaled.state`
3. uninstall tailscale https://tailscale.com/kb/1069/uninstall
4. Reinstall tailscale
5. re-auth all devices
