### ISSUE TITLE
wgengine.NewUserspaceEngine: Error starting session: The system cannot find the path specified

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#1792] opened 2021-04-24 19:11 UTC
@ho-oto reported this in #474, and wrote:

<img width="392" alt="スクリーンショット 2021-04-25 1 18 10" src="https://user-images.githubusercontent.com/22756928/115967143-de9f5600-a56b-11eb-9477-b80227092786.png">

> I failed to start Tailscale 1.6.0 on Windows with Tailscale backend error. Is it related to this issue?
>
> Windows version: Windows 10 Education (Dev version, Build 21364.1000)

logid: d6c2d40d8b

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_32u1d)

**Comment by owainc** [comment] 2021-04-25 16:46
Same issue here: 
![image](https://user-images.githubusercontent.com/72195676/116001774-249cfe00-a5ee-11eb-9bfa-88e6898c7fa3.png)

**Comment by apenwarr** [comment] 2021-04-25 20:35
WireGuard also being installed might be a clue. However, supposedly we are compatible with wireguard on Windows starting in Tailscale v1.4.0.

**Comment by Xalaxis** [comment] 2021-04-26 11:38
Hi there everyone. Also seeing this issue in that same build 21364.1000, so I think we can assume it's related to that version in some way. I do not have any other Wireguard clients installed.

![image](https://user-images.githubusercontent.com/12937964/116076458-29b08a80-a68c-11eb-8dab-a8f8f62e9806.png)

**Comment by jamestalbot3** [comment] 2021-04-26 18:14
I'm currently having this same issue with 1.6 as well. Tried installing via winget and via the downloadable from the website and still got the same issue. Currently running Build 21364 Release 210416-1504 in the Windows Insiders Dev program.

**Comment by owainc** [comment] 2021-04-26 18:19
Removing the device from the admin console appears to have fixed the issue for me.

**Comment by Xalaxis** [comment] 2021-04-26 18:58
> Removing the device from the admin console appears to have fixed the issue for me.

I can confirm this doesn't work as a workaround for me. In fact, Tailscale crashes before even getting to the prompt to login to add it to my account again.

**Comment by apenwarr** [comment] 2021-04-26 19:01
Note: not v1.8.0 specific, but from this bug and some support cases, it seems like a sudden batch of new problems even in v1.6.0. Possibly caused by a recent Windows 10 update.

All, if you could comment on whether the Tailscale >= 1.7.356 prerelease helps with this problem, we'd appreciate it. https://pkgs.tailscale.com/unstable/#windows

**Comment by Xalaxis** [comment] 2021-04-26 19:06
> Note: not v1.8.0 specific, but from this bug and some support cases, it seems like a sudden batch of new problems even in v1.6.0. Possibly caused by a recent Windows 10 update.

As we've all just updated to build 21364 released this week, I would say that's a pretty good candidate for the buggy build. The issue occurred first boot after updating for me.

> All, if you could comment on whether the Tailscale >= 1.7.356 prerelease helps with this problem, we'd appreciate it. https://pkgs.tailscale.com/unstable/#windows

Strangely, it doesn't crash but it permanently tells me to restart the Tailscale Windows Service, even if I do so.

![image](https://user-images.githubusercontent.com/12937964/116136879-d14cad80-a6ca-11eb-9188-b815862d92a6.png)

**Comment by jamestalbot3** [comment] 2021-04-26 19:39
I am getting the same behavior as Xalaxis while running 1.7.356. No amount or method of restarting the service seems to affect it.

**Comment by bradfitz** [comment] 2021-04-26 19:59
Apparently upstream Wireguard/wintun users have also been reporting this in recent Windows builds.

Jason is investigating. He has a theory (Microsoft changing behavior of SetupDiGetDevicePropertyW) and he's going to validate in the next few days. The fix appears obvious, but he wants to make sure he understands the change better.

**Comment by apenwarr** [comment] 2021-04-26 20:23
if there's an obvious fix, we could toss it into our prerelease and see if the people on this bug see an improvement. That'll validate it for the "proper" fix later.

**Comment by Xalaxis** [comment] 2021-04-29 12:30
> if there's an obvious fix, we could toss it into our prerelease and see if the people on this bug see an improvement. That'll validate it for the "proper" fix later.

I'd very much appreciate a hacky interim fix if possible. My windows PC is my main computer for VPN use, although I do appreciate that these problems are to be expected from a Dev-channel Windows build.

**Comment by owainc** [comment] 2021-04-30 09:26
Mine has broken again, same error after updating to 21634.1011.

**Comment by zx2c4** [comment] 2021-04-30 13:02
@Xalaxis @owainc I'm still unable to reproduce this myself. But if either of you _can_ reproduce it using the WireGuard client from www.wireguard.com/install/ (you'll need to make a bogus empty tunnel in it) then I'd be happy to send you a potential candidate with a maybe-fix to try out.

**Comment by Xalaxis** [comment] 2021-04-30 16:28
I've just upgraded to 21370.1 and have something very strange to report. I'm not 100% sure what's happened, so I'm going to just list everything that happened in order:

1. I open up this issue to write the following message: "Jason seems to have posted a message here, (I got an email alert), but I'm unsure if it's been deleted or filtered somehow because it doesn't seem to be here anymore."
2. As the message that doesn't seem to exist anymore asked me to try and reproduce the issue using the normal Wireguard client, I download it and create an empty tunnel. I then activate it.
3. The second I activate it, Tailscale suddenly jumps into life asking me for an admin login.
4. After logging in everything functions as normal

So *I think* that somehow activating a tunnel in Wireguard fixed whatever problem that was blocking Tailscale's startup. I can't rule out something else to do with the 21370.1 build being involved however.

**Comment by jamestalbot3** [comment] 2021-05-01 00:43
Updated to Windows build 21370.co_release.210424-1611 and Tailscale 1.7.403 and I'm back up and running. Didn't do any tunnel or anything

**Comment by sailorfrag** [comment] 2021-05-01 01:14
Unfortunately I can still repro on 21370 so we are continuing to investigate.

**Comment by Elyhaka** [comment] 2021-05-01 22:17
Recently upgraded to `21370.co_release.210424-1611`, tried the `1.7.403` unstable release and now I have the following output on the tray icon (while the service is reported running) :

![image](https://user-images.githubusercontent.com/57923898/116796258-6b519300-aadb-11eb-8ade-3031f291c133.png)

I tried resintalling, I also tried to delete all the folders mentionned [here](https://tailscale.com/kb/1069/uninstall/) and reinstall again without any luck.

Is there any known workaround, or should I resintall Windows to go back to the stable channel ?

**Comment by Xalaxis** [comment] 2021-05-02 14:00
Update: My Tailscale stopped working again today. Creating another blank tunnel in Wireguard and manually restarting the service (followed by about a minute of delay) caused it to start working again.

**Comment by Xalaxis** [comment] 2021-05-04 10:52
Note this must be a **new** empty tunnel. Simply disabling an re-enabling an old one has no effect. Creating a new one instantly solves the issue every time.

**Comment by zx2c4** [comment] 2021-05-05 09:40
Looks like a new bug in Windows. I've worked around it in Wintun 0.10.4 with this [fantastically horrible hack](https://git.zx2c4.com/wintun/commit/?id=747ba7121d1d94dac982b9148076d7006e2c170f) that I cannot wait to revert.

You can try it out today by [downloading the developer .zip from wintun.net](https://www.wintun.net/). Then, stop the tailscale service, copy wintun\bin\amd64\wintun.dll to "C:\program files (x86)\tailscale ipn\wintun.dll", overriding the old file, and start the tailscale service.

If this works for you, please let me know.

**Comment by stealthybox** [comment] 2021-05-05 20:05
I was getting this error message window whenever the Tailscale Service would start.

@zx2c4, using your copy of `wintun.dll` 0.10.4 fixed it for me.

1. Open "Services"
2. Stop the "Tailscale" service
3. replace "C:/Program Files (x86)/Tailscale IPN/wintun.dll"
4. Start "Tailscale" service

_________

Tailscale 1.6.0 Stable

Windows 10 Home
Insiders Fast Ring
OS build	21364.1011

**Comment by zx2c4** [comment] 2021-05-05 20:09
Terrific! Thanks for the report. I've [released WireGuard 0.3.12](https://www.wireguard.com/install/) with Wintun 0.10.4, and so far haven't received any emails about regressions, so I think at this point it's just a matter of Tailscale updating the version of Wintun that they ship, which should be easy enough to do.

If others are using those steps to fix the issue, please continue to report back whether it worked or not. The more data points, the better, for weird bugs like this one.

**Comment by Xalaxis** [comment] 2021-05-06 19:00
@zx2c4 I can confirm this also fixed my issues! Thanks for looking into it.

**Comment by pycke** [comment] 2021-05-07 12:57
I have the same issue and cannot make it work. My Windows version:

Edition Windows 10 Pro
Version 21H1
Installed on ‎2020-‎08-‎04
OS build 19043.964
Experience Windows Feature Experience Pack 120.2212.3740.0

This is my main work computer. 

I run Tailscale 1.8.0. 

I did the steps outlined here (replacing windtun.dll ; manually making an empty tunnel - I had to install Wireguard for that), but I could not resolve it. My IT knowledge is for sure less than others in this thread so I might also not have executed the workaround solutions entirely correctly. 

Any advice on what to do or how to resolve is most appreciated.

**Comment by zx2c4** [comment] 2021-05-07 12:58
As of tailscale 1.8.0, those steps are no longer necessary, since it runs the newer wintun, I think. Will amend my messages now to reduce confusion.

**Comment by pycke** [comment] 2021-05-07 12:59
I run tailscale 1.8.0 and still experience this issue

**Comment by pycke** [comment] 2021-05-07 13:01
I also run a pre-release Developer Channel version of Windows (as a Power User)

**Comment by Xalaxis** [comment] 2021-05-07 13:02
That OS build is way too low though, you should be running something near 21370ish right now if you're on the Dev build.

**Comment by pycke** [comment] 2021-05-07 13:03
It is the Beta Channel 

![image](https://user-images.githubusercontent.com/1793844/117453446-42028e00-af45-11eb-9712-86cefb1b8eb2.png)

**Comment by pycke** [comment] 2021-05-07 13:05
Whatever I do (reinstalling, deleting all Tailscale folders in (hidden) App folders, downgrading, upgrading), I always remain stuck at 

![image](https://user-images.githubusercontent.com/1793844/117453762-99a0f980-af45-11eb-9310-cf2e7794e6a2.png)

**Comment by sailorfrag** [comment] 2021-05-07 13:05
> OS build 19043.964
> I run Tailscale 1.8.0. 

That OS build predates the changes that seem to have caused the original issue reported here and Tailscale 1.8.0 already includes the updated wintun.dll.

So while that's rather concerning, I think this looks like a separate issue. If you can e-mail the logID along with the date and time it happened to support@tailscale.com, we can investigate further. 

Were you having problems using Tailscale versions before 1.8.0?

**Comment by sailorfrag** [comment] 2021-05-07 13:07
Also, by the way everyone, we updated the version of wintun in 1.8.0 which soft launched yesterday.

**Comment by pycke** [comment] 2021-05-07 13:13
Thanks @sailorfrag I don't get any prompt with logID so it is not clear what information I could send to  support@tailscale.com. I already emailed to support@tailscale.com and got a link to this issue as a reply. This is how I ended up here. I did not have any issues with Tailscale 1.6.0

**Comment by sailorfrag** [comment] 2021-05-07 13:15
> Thanks @sailorfrag I don't get any prompt with logID so it is not clear what information I could send to  support@tailscale.com. I already emailed to support@tailscale.com and got a link to this issue as a reply. This is how I ended up here. I did not have any issues with Tailscale 1.6.0

Ah, ok. I recommend downgrading to 1.6.0 for now and I will do some further investigation.

**Comment by DentonGentry** [comment] 2021-05-07 13:15
I have enough information from the support@tailscale.com emails, you don't need to send more.
Reluctantly, I guess this is a different issue that we'll need to look into.

For now, if 1.6 works for you please continue to use it. We maintain backwards compatibility all the way back to the very earliest versions, 1.6 will continue to work.

**Comment by DentonGentry** [comment] 2021-11-10 00:39
wintun is being updated again in 1.18.
Closing during bug scrub.

**Closed by DentonGentry** 2021-11-10 00:39 UTC
Labels: OS-windows, L3 Some users, P5 Halts deployment, T8 Crash
