### ISSUE TITLE
FR: add “on demand” function to iOS app

### ISSUE THREAD

**Issue by CaptSneeze** [tailscale/tailscale#6292] opened 2022-11-12 01:16 UTC
### What are you trying to do?

The WireGuard app allows an “on-demand” feature. The feature allows different selections for automatically connecting the VPN when “on cellular”, or “on wifi”, and even “when connected to these SSIDs” or “when connected to any wifi that isn’t one of these SSIDs”. It’s very handy. 

### How should we solve this?

Add this feature to the iOS app. 

### What is the impact of not solving this?

I can’t use Tailscale to completely replace my use of WireGuard as a VPN solution to route my phone’s traffic through my home network when I connect to a different wifi network.

**Comment by DentonGentry** [comment] 2022-11-12 01:33
Duplicate of https://github.com/tailscale/tailscale/issues/1534

**Closed by DentonGentry** 2022-11-12 01:33 UTC
Labels: needs-triage, fr
