### ISSUE TITLE
macOS app crashes when "This device" button is clicked

### ISSUE THREAD

**Issue by bkarakoc** [tailscale/tailscale#8291] opened 2023-06-07 00:31 UTC
### What is the issue?

I'm running macOS 13.4 and Tailscale 1.42.0 downloladed through App store. When I click the "This device: mac-studio (TS IP address) button, the app crashes, but the connection persists. I can see that Tailscale Tunnel shows connected under System Settings/VPN menu and I can ping devices through TS with 100.x addresses. The dashboard shows that my computer is still connected as well despite the app is not running (no entry in the Activity Monitor.)

### Steps to reproduce

1. Start Tailscale
2. Click on the menubar icon
3. Click on the “This device” button that shows your hostname and IP address

### OS

macOS

### OS version

macOS 13.4

### Tailscale version

1.42.0 (App Store)

**Comment by agottardo** [comment] 2023-06-07 00:50
Thanks for the report! This is a duplicate of https://github.com/tailscale/tailscale/issues/8256. Workaround:

> A quick workaround for you at the moment is to enable notifications for Tailscale in the notifications settings of your Mac. That should make the issue go away until you get the fix in our next update.

**Closed by agottardo** 2023-06-07 00:50 UTC
Labels: needs-triage, bug
