### ISSUE TITLE
FR: Support DNS over TLS or DNS over HTTPS

### ISSUE THREAD

**Issue by xspliff** [tailscale/tailscale#5979] opened 2022-10-18 07:23 UTC

**Comment by DentonGentry** [comment] 2022-10-18 11:04
Currently, the IP addresses for Google Public DNS, Cloudflare DNS, and NextDNS are recognized and automatically turn into DNS-over-HTTPS requests to those providers.

**Comment by xspliff** [comment] 2022-10-18 16:42
I see that, however I'm using controld which requires you enter your own custom resolver as such: 

https://dns.controld.com/xxxxxxxxx
xxxxxxxxx.dns.controld.com

**Comment by DentonGentry** [comment] 2022-11-01 17:46
Duplicate of https://github.com/tailscale/tailscale/issues/74

**Closed by DentonGentry** 2022-11-01 17:46 UTC
Labels: L3 Some users, P2 Aggravating, T0 New feature, dns, fr
