### ISSUE TITLE
Unable to resolve dns on Android 13

### ISSUE THREAD

**Issue by maple3142** [tailscale/tailscale#8006] opened 2023-04-29 11:29 UTC
### What is the issue?

Unable to resolve any domain without specifying dns server explicitly when tailscale is enabled. Private DNS is not enabled either.

### Steps to reproduce

1. Enable Tailscale
2. Open Termux
3. `ping google.com`: failed
4. `ping 8.8.8.8`: works
5. `dig google.com @8.8.8.8`: works
6. Open YouTube app: failed to show anything

### OS

Android

### OS version

Android 13

### Tailscale version

1.40.0-t9bdaece3d-ge0ba590be3e

### Other software

AdGuard Android (will be automatically disabled when Tailscale is active)

### Bug report

BUG-4cc3d4f3fd6b5ea50b2982505d0d6ffaae31e1bb5fcb6181ab4f17b70bd5c599-20230429112917Z-441b5f2258c699b5

**Comment by Akeboshiwind** [comment] 2023-04-29 14:43
I've got the same issue I think.
I've only reproduced it by navigating in Firefox thou.
I'm on Tailscale version 1.38.2.

When I disable MagicDNS I'm able to navigate to new URLs again.

**Comment by maple3142** [comment] 2023-04-29 16:45
I found some new info:

If I switched to wifi before enabling Tailscale, DNS works.

If I use mobile data before enabling Tailscale, DNS is broken.

**Comment by DentonGentry** [comment] 2023-04-29 18:34
> If I use mobile data before enabling Tailscale, DNS is broken.

Could you generate a Bugreport when using mobile data and enabling Tailscale, when DNS is broken? Ideally, generate the bugreport immediately after enabling Tailscale. That gives us a specific point in the telemetry to look at.

**Comment by maple3142** [comment] 2023-04-30 00:50
> > If I use mobile data before enabling Tailscale, DNS is broken.
> 
> Could you generate a Bugreport when using mobile data and enabling Tailscale, when DNS is broken? Ideally, generate the bugreport immediately after enabling Tailscale. That gives us a specific point in the telemetry to look at.

```
BUG-4cc3d4f3fd6b5ea50b2982505d0d6ffaae31e1bb5fcb6181ab4f17b70bd5c599-20230430005046Z-3913f775a9b2e20c
```

**Comment by maple3142** [comment] 2023-04-30 00:51
> > If I use mobile data before enabling Tailscale, DNS is broken.
> 
> Could you generate a Bugreport when using mobile data and enabling Tailscale, when DNS is broken? Ideally, generate the bugreport immediately after enabling Tailscale. That gives us a specific point in the telemetry to look at.

```
BUG-4cc3d4f3fd6b5ea50b2982505d0d6ffaae31e1bb5fcb6181ab4f17b70bd5c599-20230430005046Z-3913f775a9b2e20c
```

**Comment by DentonGentry** [comment] 2023-04-30 17:31
The tailnet in its https://login.tailscale.com/admin/dns has "Override local DNS" turned off, which means Tailscale is supposed to find the DNS servers which were already present in the underlying OS and use those.

Android makes this difficult: starting in Android 8, apps are not allowed to retrieve the DNS server properties like `net.dns1` or `net.dns4`. We instead implement a series of mechanisms in https://github.com/tailscale/tailscale-android/blob/main/android/src/main/java/com/tailscale/ipn/DnsConfig.java

Shortly before the bugreport while on mobile data, all of those mechanisms fail to find a DNS server:
```
2023-04-30 00:49:24.449414758 +0000 UTC: getDnsConfigFromLinkProperties:
2023-04-30 00:49:24.45033053 +0000 UTC: getDnsServersFromSystemProperties:
2023-04-30 00:49:24.4510717 +0000 UTC: getDnsServersFromNetworkInfo:
```

Earlier, on Wi-fi, it did find the DNS servers in use:
```
2023-04-29 16:43:19.169134333 +0000 UTC: getDnsConfigFromLinkProperties: 192.168.x.1
2023-04-29 16:43:19.169683731 +0000 UTC: getDnsServersFromSystemProperties:
2023-04-29 16:43:19.171425349 +0000 UTC: getDnsServersFromNetworkInfo: 192.168.x.1
```

One way to work around the issue would be to set "Override local DNS" in https://login.tailscale.com/admin/dns

**Comment by maple3142** [comment] 2023-05-01 01:13
Thanks for replying!

> One way to work around the issue would be to set "Override local DNS" in [login.tailscale.com/admin/dns](https://login.tailscale.com/admin/dns)

Enabling "Override local DNS" does fix the DNS issue for my Android device, but it would also override the DNS setting for other devices. Is it possible to enable this setting for one specific device instead of a whole tailnet?

**Comment by hkpanchani** [comment] 2023-05-03 10:48
> 

+1

**Comment by gvolk0** [comment] 2023-05-17 03:34
Overriding local DNS didn't help in my case.  In fact termux doesn't even attempt to use the override DNS 1.1.1.1 but instead picks up 8.8.8.8.

I found is this:
```
~ $ cat /data/data/com.termux/files/usr/etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
```
..though I don't think that's the real problem as I can't browse the web using Chrome either when tailscale is active.  Disabling Magic DNS doesn't help either oddly enough.

Additionally when tailscale is active I can't ping google but I **can** nslookup google and ping the resulting IP.
However I **can't** resolve my device names using Magic DNS (on Android only, on laptop/Linux works fine) - not the short nor the full name.

Last point, after disabling Magic DNS in the web console and restarting the service on my laptop, I can still ping my devices using the fully qualified domain (.ts.net) but not the short name - based on the documentation my impression was that neither should work?

I will add that my phone's been acting up lately so it might be b0rked in some way that's making this more convoluted.
But I hope the above is useful.

**Comment by gvolk0** [comment] 2023-05-17 03:45
forgot to add...

adding `namespace 100.100.100.100` to the reslove.conf file solves some of the problems.
I can now resolve short and full machine name from termux, and resolving google now goes via tailscale's DNS.
ping still doesn't work with any domain though, only with IPs.

**Comment by LinAGKar** [comment] 2023-06-20 11:42
I have a release that's new enough that it should have the above fix, but I'm still getting issues like this.

BUG-359798c78e334a09419d3c211ee059fb5cadf6853727d97376150db9b0422703-20230620113954Z-1c33f65207a854a9

**Comment by nwgat** [comment] 2023-07-14 21:11
just a hunch go into android tailscale app, then tap the device you want to connect to (copy to clipboard), go then back to your app then it might work, thats my workaround

**Comment by LinAGKar** [comment] 2023-07-15 11:51
That won't help with connecting to things on the internet

**Comment by elektrinis** [comment] 2023-09-26 06:11
Is there a fix for this? I don't have deep knowledge what's going on, but anyway, when I disconnect from wifi, my internet (websites etc) no longer works.
I have a similar problem on my windows machine - connections are very slow, as it looks like it is forcing some usual traffic through the tunnel.

**Comment by mishley** [comment] 2023-11-10 13:43
I have this same issue, have to stop and restart Tailscale to resolve. The issue seems to only happen occasionally when moving between networks, but not always. Most commonly I notice it when I've left my home wifi and then attempt to connect to the Internet from mobile networks like LTE.

**Comment by lxdlam** [comment] 2023-12-23 07:43
Since the issue is related with the DNS, I've disabled the MagicDNS as a temporary workaround, then it seems the tailscale will recover from any situation(Wifi -> cellular regardless whether I keep the connection or not).

**Comment by versita** [comment] 2023-12-29 05:03
I've been using Tailscale on Android for a couple of weeks now and didn't encounter this problem until I switched to a different wireless carrier. With my previous carrier, I left Tailscale connected 24/7 without issue but after switching to another carrier a few days ago, the DNS will not resolve domain names even with Private DNS set to off or automatic whilst using my cellular connection.

Disabling MagicDNS or enabling the local DNS override both solve the issue for me. For me, it makes the most sense to disable MagicDNS, and in this configuration I can still use a Private DNS on Android without issue.

**Comment by fd0** [comment] 2024-02-02 19:17
I think I've got the same issue (Pixel 7a, Android 14), always reproducible: switching from wifi in my home network to cellular breaks resolving hostnames with MagicDNS enabled. Toggling Tailscale or briefly switching to Flight Mode resolves it. Very annoying.

I've made a bugreport directly after DNS broke: BUG-0a78adbf819fc5a54b46874b03ec6d7ea87b01c55ec2bcde7cf753dd3c3f8b32-20240202191158Z-68b850446d0a04cf

Does that help? Is there anything else I can do?

**Comment by hanssonduck** [comment] 2024-03-24 14:51
Same problem but switching from GitHub to Google account worked.

**Comment by 46319943** [comment] 2024-03-29 12:09
When using my tab of Android 13 with only the WIFI network, the DNS cannot be resolved, while directly using the IP is fine.
After disabling the MagicDNS, the DNS issue is resolved.

It's wried that there is no problem on my phone, which is based on Android 12.

**Comment by agottardo** [comment] 2024-04-25 17:43
Does this issue still occur on the [latest beta version](https://play.google.com/apps/testing/com.tailscale.ipn) of the Android app?

**Comment by NimecShady** [comment] 2024-04-26 03:44
> @maple3142 @46319943 @hanssonduck @fd0 Does this issue still occur on the [latest beta version](https://play.google.com/apps/testing/com.tailscale.ipn) of the Android app?
> 
> Please attach a bug report identifier if so, we cannot identify the root cause without one.

I have been experiencing the internet drop after switching from Wifi to Cellular as well.  Will give the beta app a try tomorrow and see how it does.

**Comment by maple3142** [comment] 2024-04-26 03:53
> @maple3142 @46319943 @hanssonduck @fd0 Does this issue still occur on the [latest beta version](https://play.google.com/apps/testing/com.tailscale.ipn) of the Android app?
> 
> Please attach a bug report identifier if so, we cannot identify the root cause without one.

I am testing it on latest stable version using Cellular network with `Override local DNS` turned off, and it currently works.

**Comment by lxdlam** [comment] 2024-04-26 04:37
> @maple3142 @46319943 @hanssonduck @fd0 Does this issue still occur on the [latest beta version](https://play.google.com/apps/testing/com.tailscale.ipn) of the Android app?
> 
> Please attach a bug report identifier if so, we cannot identify the root cause without one.

It works as expected now, even when I re-enabled MagicDNS.

**Comment by agottardo** [comment] 2024-04-26 05:57
Thanks for the feedback. Please keep opening issues for any other problem with the beta app, it's much appreciated! :)

**Closed** 2024-04-26 05:57 UTC
Labels: OS-android, L2 Few, P3 Can't get started, T5 Usability, bug
