### ISSUE TITLE
Regarding Tailscale's compatibility with Ngnix Proxy Manager and Duck DNS

### ISSUE THREAD

**Issue by kingmehar** [tailscale/tailscale#3428] opened 2021-11-28 13:15 UTC
### What is the issue?

How to recreate: Install Ngnix proxy manager and any self-hosted web app [Nextcloud, Owncloud, Portainer]  in my  case  Portaniner WebGUI and put Ngnix proxy manager in front of it by using Duck DNS as a dynamic DNS client  and setting the record to the Tailscale IP  of the machine then after doing all of this when I write the domain name  in browser bar it keeps on loading forever with about: blank on the other hand if I write Tailscale IP a with the correct port it loads in a second

### Steps to reproduce

How to recreate: Install Ngnix proxy manager and any self-hosted web app [Nextcloud, Owncloud, Portainer]  in my  case  Portaniner WebGUI and put Ngnix proxy manager in front of it by using Duck DNS as a dynamic DNS client  and setting the record to the Tailscale IP  of the machine then after doing all of this when I write the domain name  in browser bar it keeps on loading forever with about: blank on the other hand if I write Tailscale IP a with the correct port it loads in a second

### OS

Linux

**Comment by DentonGentry** [comment] 2021-11-28 14:00
So:
- the machine the NGINX proxy runs on has a 100.x.y.z address
- you have a dyndns client update DuckDNS to have an A record pointing to 100.x.y.z. Can you use `dig -t A hostname.example.com` to see this?
- from another system with Tailscale installed you can get to http://100.x.y.z but http://hostname.example.com hangs forever. Are you using http, or https? An https request for a domain you've supplied like hostname.example.com won't work unless you've set up certificates, which is difficult for a non-reachable private host. If that is the issue, https://tailscale.com/blog/tls-certs/ could help

I'll note that it doesn't really look like Tailscale is involved in whatever is going wrong, since http://100.x.y.z works. The issue appears to be in the DNS record for hostname.example.com and whether it points to 100.x.y.z.

**Comment by DentonGentry** [comment] 2021-11-28 14:14
Assuming that the issue is in Duck DNS rejecting 100.x.y.z addresses, https://tailscale.com/blog/tls-certs/ and https://tailscale.com/kb/1081/magicdns/ can likely do what you're looking for.

**Comment by kingmehar** [comment] 2021-11-29 04:30
After dig command I got answer 

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6705
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;testkingnet123.duckdns.org.	IN	ANY

;; ANSWER SECTION:
testkingnet123.duckdns.org. 60	IN	A	100.66.117.58


 Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6705
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;testkingnet123.duckdns.org.	IN	ANY

;; ANSWER SECTION:
testkingnet123.duckdns.org. 60	IN	A	100.66.117.58

**Comment by kingmehar** [comment] 2021-11-29 13:53
I have solved the problem it was not of Duck DNS not working with CGNAT but I forgot to add Portainer to the Ngnix Proxy Manager network so it lead to Ngnix proxy manager not being able to connect to portainer every one who put the effort in solving the problem are appreciated

**Comment by kingmehar** [comment] 2021-11-29 13:54
I will close the issue after 24h

**Comment by DentonGentry** [comment] 2021-11-29 14:09
Since nothing more is expected here, closing.

**Closed by DentonGentry** 2021-11-29 14:09 UTC
Labels: needs-triage, bug
