### ISSUE TITLE
Moving from LAN WiFi to LTE mobile devices loose route through exit node.

### ISSUE THREAD

**Issue by picree** [tailscale/tailscale#8691] opened 2023-07-23 17:02 UTC
### What is the issue?

If I am on my WiFi I can route to the Internet via my exit node. But if my phone leaves WiFi and is on LTE the exit node no longer can route to the Internet UNLESS I disconnect from the VPN via the phone's TS app from the VPN and then reconnect while still on LTE.

### Steps to reproduce

While on WiFi connect to VPN with exit node selected.  Check IP address on Internet to confirm home ISP IP address.  Turn off WiFi and allow phone to switch to Verizon LTE.  Check IP address - no connectivity.  Disconnect phone from VPN via TS app.  Check IP address on Internet to confirm Verizon IP.  Connect to VPN via TS app.  Check IP address on Internet to confirm home ISP IP address.  I can now connect to the internet via the exit node with my home ISP IP address.

### Are there any recent changes that introduced the issue?

I think this was an issue for me on 1.44 and is now confirmed to remain on 1.46.  Also confirmed the same issue on another iPhone.  I disconnected the iPhone, logged out, deleted the app, deleted the machine from the Admin Console, reinstalled 1.46 on the phone, reconnected the phone to my VPN network via the Admin Console but the problem remains.

### OS

Mac, iOS, Linux

### OS version

16.5.1 (c )

### Tailscale version

1.46

### Other software

Exit node is running 1.46 on an EdgeRouter X.  It properly has routes turned on and is advertising its exit node.  Checking Tailscale status via CLI produces no errors and responds with the expected results.  Switching from LTE back to WiFi does not present any connectivity issues.

### Bug report

BUG-41ee70ee7640fbc5f542aacf6995c117f7fa9f4f2120474a73a0f3fdde5c7564-20230723163051Z-99d14686554779ca

**Comment by picree** [comment] 2023-07-24 16:01
The issue may be related to the testing done. I was turning off the phone’s Wi-Fi to simulate moving from Wi-Fi to LTE. If I leave Wi-Fi on and travel out of range then TS seems to work and be able to route traffic out the exit mode.

**Comment by snachx** [comment] 2023-08-17 06:43
I have encountered the same problem, maybe the same as #6075 #8022 #8283

**Comment by picree** [comment] 2023-08-22 02:17
Issue remains after updating exit node and other machines on the TS network to 1.48.1.  As @snachx says above it sound related to other open bugs.

**Comment by l4kr** [comment] 2023-10-01 19:45
This is easily fixable (atleast for the time being) by making tailscale restart whenever there's a network change in iOS. Why is it not fixed like that?

**Comment by crypt0rr** [comment] 2023-10-02 02:22
> This is easily fixable (atleast for the time being) by making tailscale restart whenever there's a network change in iOS. Why is it not implemented like that?

How can you implement this for the time being? Automation!

Create an automation based on Wi-Fi behavior. _When Wi-Fi disconnects_ > _Restart Tailscale_

**Comment by r3n3x** [comment] 2023-12-15 02:48
> > This is easily fixable (atleast for the time being) by making tailscale restart whenever there's a network change in iOS. Why is it not implemented like that?
> 
> How can you implement this for the time being? Automation!
> 
> Create an automation based on Wi-Fi behavior. _When Wi-Fi disconnects_ > _Restart Tailscale_

I have tried the AUTOMATION for iOS but while on mobile data when encountering short coverage/connection drops, I loose internet connectivity SOMETIMES when using TS with EXIT NODE.

The Automation doesn't catch that and then I stay "offline" for a long time until I notice that my phone became so quiet...

For quasi-VPN on mobile I noticed that Cloudflare 1.1.1.1 Warp+ works very smoothy with connection changes and connectivity drops.  There could be something TS can learn from the 1.1.1.1 app perhaps?  Not sure what's their different approach.

**Comment by picree** [comment] 2023-12-15 03:04
OP here:  I completely uninstalled TS from the ER X, rebooted, and removed the machine from the tailnet.  I reinstalled TS 1.54.1 on the ER X and added the new machine to the tailnet.  Issue seems to be resolved.  Sorry - don't know if it was the complete reinstall or the update to 1.54.1.  Anyone else having the issue I would recommend a complete uninstall/reboot/reinstall on the exit node.

**Comment by agottardo** [comment] 2024-01-05 18:52
Duplicate of #8022 

Fixed in Tailscale 1.57.44

**Closed by agottardo** 2024-01-05 18:52 UTC
Labels: connectivity, L1 Very few, P2 Aggravating, T5 Usability, bug
