### ISSUE TITLE
EdgeRouter: tailscaled doesn't fully connect at boot

### ISSUE THREAD

**Issue by jamesog** [tailscale/tailscale#1724] opened 2021-04-17 14:45 UTC
**Describe the bug**
Some information and troubleshooting is on jamesog/tailscale-edgeos#1.

System: Ubiquiti EdgeRouter Lite with firmware v2.0.9-hotfix.1.5371034.210122.1014 (Linux version 4.9.79-UBNT)
Tailscale 1.6.0 is installed from the apt repo on pkgs.tailscale.com (stretch repo).

At initial install, Tailscale operates correctly. After rebooting the router `tailscaled` starts up and appears to be working, however it is not connected to the Tailscale network. `tailscale status` shows other devices on the account, systemd thinks the services is operating normally, but the admin console shows it's not connected and no Tailscale IPs are reachable.

Restarting the service fixes it.

Per jamesog/tailscale-edgeos#1 I tried adding a systemd unit override to have the tailscaled service start as late as possible in case it was missing a filesystem or network dependency.

It seems like `tailscaled` isn't binding to a port at first boot. The `lsof` output after boot looks like:

```
root@testgw01:/home/ubnt# lsof -c tailscaled
COMMAND    PID USER   FD      TYPE             DEVICE SIZE/OFF  NODE NAME
tailscale 1604 root  cwd       DIR               0,13     4096    23 /
tailscale 1604 root  rtd       DIR               0,13     4096    23 /
tailscale 1604 root  txt       REG                8,2 12853861 76419 /usr/sbin/tailscaled
tailscale 1604 root    0r      CHR                1,3      0t0  1028 /dev/null
tailscale 1604 root    1u     unix 0x8000000417a9db00      0t0 11366 type=STREAM
tailscale 1604 root    2u     unix 0x8000000417a9db00      0t0 11366 type=STREAM
tailscale 1604 root    3u      REG                8,2        0 76435 /var/lib/tailscale/tailscaled.log1.txt
tailscale 1604 root    4u  a_inode                0,9        0     6 [eventpoll]
tailscale 1604 root    5r     FIFO                0,8      0t0 11370 pipe
tailscale 1604 root    6w     FIFO                0,8      0t0 11370 pipe
tailscale 1604 root    7u      REG                8,2        0 76436 /var/lib/tailscale/tailscaled.log2.txt
tailscale 1604 root    8u  netlink                         0t0 11389 ROUTE
tailscale 1604 root    9u      CHR             10,200     0t88  1524 /dev/net/tun
tailscale 1604 root   10u     unix 0x8000000417a9f600      0t0 11987 type=DGRAM
tailscale 1604 root   11u  netlink                         0t0 11410 ROUTE
tailscale 1604 root   12r     FIFO                0,8      0t0 11411 pipe
tailscale 1604 root   13w     FIFO                0,8      0t0 11411 pipe
tailscale 1604 root   14u     unix 0x8000000417739f80      0t0 12564 /run/tailscale/tailscaled.sock type=STREAM
tailscale 1604 root   15u     IPv4              11993      0t0   TCP 10.1.1.2:39526->ec2-3-121-18-47.eu-central-1.compute.amazonaws.com:https (ESTABLISHED)
tailscale 1604 root   16u  netlink                         0t0 12055 ROUTE
tailscale 1604 root   17r     FIFO                0,8      0t0 12056 pipe
tailscale 1604 root   18w     FIFO                0,8      0t0 12056 pipe
tailscale 1604 root   21u     IPv4              11484      0t0   TCP 10.1.1.2:35770->ec2-34-210-105-16.us-west-2.compute.amazonaws.com:https (ESTABLISHED)
```

Here it's not bound to any UDP sockets, but it does have some connectivity to the Tailscale control server.

After a restart:

```
root@testgw01:/home/ubnt# lsof -c tailscaled
COMMAND    PID USER   FD      TYPE             DEVICE SIZE/OFF  NODE NAME
tailscale 1974 root  cwd       DIR               0,13     4096    23 /
tailscale 1974 root  rtd       DIR               0,13     4096    23 /
tailscale 1974 root  txt       REG                8,2 12853861 76419 /usr/sbin/tailscaled
tailscale 1974 root    0r      CHR                1,3      0t0  1028 /dev/null
tailscale 1974 root    1u     unix 0x80000004171d9200      0t0 14609 type=STREAM
tailscale 1974 root    2u     unix 0x80000004171d9200      0t0 14609 type=STREAM
tailscale 1974 root    3u      REG                8,2        0 76435 /var/lib/tailscale/tailscaled.log1.txt
tailscale 1974 root    4u  a_inode                0,9        0     6 [eventpoll]
tailscale 1974 root    5r     FIFO                0,8      0t0 14613 pipe
tailscale 1974 root    6w     FIFO                0,8      0t0 14613 pipe
tailscale 1974 root    7u      REG                8,2        0 76436 /var/lib/tailscale/tailscaled.log2.txt
tailscale 1974 root    8u  netlink                         0t0 14007 ROUTE
tailscale 1974 root    9u      CHR             10,200     0t80   467 /dev/net/tun
tailscale 1974 root   10u  netlink                         0t0 14024 ROUTE
tailscale 1974 root   11r     FIFO                0,8      0t0 14025 pipe
tailscale 1974 root   12w     FIFO                0,8      0t0 14025 pipe
tailscale 1974 root   13u     IPv4              14060      0t0   UDP *:41641
tailscale 1974 root   14u     IPv6              14063      0t0   UDP *:41641
tailscale 1974 root   16u  netlink                         0t0 14107 ROUTE
tailscale 1974 root   17r     FIFO                0,8      0t0 14108 pipe
tailscale 1974 root   18u     unix 0x800000000c019680      0t0 14223 type=DGRAM
tailscale 1974 root   19w     FIFO                0,8      0t0 14108 pipe
tailscale 1974 root   20u     IPv4              14229      0t0   TCP 10.1.1.2:40096->ec2-3-121-18-47.eu-central-1.compute.amazonaws.com:https (ESTABLISHED)
tailscale 1974 root   21u     IPv4              16955      0t0   TCP 10.1.1.2:44000->ec2-34-210-105-16.us-west-2.compute.amazonaws.com:https (ESTABLISHED)
tailscale 1974 root   22u     unix 0x800000000c019b00      0t0 14198 /run/tailscale/tailscaled.sock type=STREAM
tailscale 1974 root   28u     IPv4              14742      0t0   TCP 10.1.1.2:58724->derp8-lon.tailscale.com:https (ESTABLISHED)
```

Now it's bound to UDP/41461 and has connected to a DERP relay.

I have the service running with `-verbose 2` and can't see any obvious failures from logs, but there is a notable lack of `magicsock` messages at boot (some, but not many) compared to a working instance.

These messages are missing from boot:

```
Apr 17 11:04:14 testgw01 tailscaled[2497]: magicsock: starting endpoint update (initial)
Apr 17 11:04:14 testgw01 tailscaled[2497]: magicsock: ignoring pre-DERP map, STUN-less endpoint update: [10.1.1.2:41641 [2001:8b0:XXX::2]:41641]
Apr 17 11:04:14 testgw01 tailscaled[2497]: magicsock: starting endpoint update (link-change-minor)
Apr 17 11:04:16 testgw01 tailscaled[2497]: magicsock: starting endpoint update (derp-map-update)
Apr 17 11:04:16 testgw01 tailscaled[2497]: magicsock: ReSTUN: endpoint update active, need another later ("non-zero-peers")
Apr 17 11:04:16 testgw01 tailscaled[2497]: magicsock: ReSTUN: endpoint update active, need another later ("set-private-key")
```

Common messages (at boot and after restart) include:

```
Apr 17 14:07:31 testgw01 tailscaled[1604]: Starting magicsock...
Apr 17 14:07:31 testgw01 tailscaled[1604]: magicsock: disco key = d:xxx
Apr 17 14:07:33 testgw01 tailscaled[1604]: magicsock: got updated network map; 8 peers (7 with discokey)
Apr 17 14:07:33 testgw01 tailscaled[1604]: magicsock: SetPrivateKey called (init)
Apr 17 14:07:33 testgw01 tailscaled[1604]: magicsock: CreateEndpoint: key=[+wk54]: derp-8,93.93.129.14:21749,[2a00:1098:0:80:1000:4d:0:14]:18355
```

Let me know if you need me to provide full logs. I wasn't sure if there's anything I should avoid posting publicly.

**To Reproduce**
1. Install Tailscale using [these steps](https://github.com/jamesog/tailscale-edgeos/issues/2#issuecomment-821805877)
2. Log in using `sudo tailscale up`
3. Reboot the router
4. After boot `sudo systemctl status tailscaled`, `sudo tailscale status`, etc. will show it as working, but the Tailscale admin console will show the device as not connected and no Tailscale addresses are reachable
5. `netstat` shows tailscaled is not listening on UDP/41461

**Expected behavior**
Tailscale is fully connected after the daemon has started.

**Version information:**
 - Device: Ubiquiti EdgeRouter
 - OS: EdgeOS (Vyatta)
 - OS version: v2.0.9-hotfix1
 - Tailscale version: 1.6.0 (mips)

**Comment by DentonGentry** [comment] 2021-04-20 04:28
We do get some telemetry from the device. Looking at the Apr 17 14:07 mentioned in the report, we see:

`17 Apr 21 14:07 UTC: control: PollNetMap: EOF`
`17 Apr 21 14:07 UTC: Received error: PollNetMap: EOF`

which seems odd. That happens some times, but the EdgeRouter having this trouble sees that message thousands of times in a few hours.

**Comment by DentonGentry** [comment] 2021-09-04 18:43
The overarching goal of smoother support for Ubiquiti gear is covered in https://github.com/tailscale/tailscale/issues/735
I don't think keeping this open is really useful at this point.

Duplicate of https://github.com/tailscale/tailscale/issues/735

**Closed by DentonGentry** 2021-09-04 18:43 UTC
Labels: help wanted, OS-linux, L1 Very few, P2 Aggravating, T5 Usability
