### ISSUE TITLE
Document/Make Available Debian Package Process

### ISSUE THREAD

**Issue by felicianotech** [tailscale/tailscale#1000] opened 2020-12-08 21:55 UTC
Similar to "Document how to reproduce our binaries #779", I don't believe how/where the Debian (.deb) packages get built is documented. This can help with a few things:

1. General interest. I assume this would be low priority.
2. Enablement of community packages. In the Linux world the number of distros is `n +1` where 'n' is the current number os distros. Instead of the Tailscale team creating packages for all of them, or ignoring them, community members can help create them but being let into this process is a very helpful first step.
3. This can help: "Ubuntu Snap packages #267": Like that Issue title hints, Snaps are a Linux package management system and the internal of the sandbox is not limited to but is typically Ubuntu. There's several official bases including `core`, `core18`, and `core20`, all of which are Ubuntu versions. Knowing how Tailscale is currently packaged for Ubuntu would assist in getting a Snapcraft file made to create the Tailscale snap. Just an FYI, unlike how that title hints, Snap packages aren't just for Ubuntu. They can be installed in Debian, Fedora, Pop!_OS, Raspberry Pi OS, elementary OS, and more with a single snap package.
4. This information can also help with these open GitHub Issues:
- apt-get purge does not remove existing configuration #325
- pkgs: doesn't document apt-transport-https #319

**Comment by DentonGentry** [comment] 2022-05-07 18:07
I understand the need, but there isn't a value in having a second issue tracking what is essentially a specific case of https://github.com/tailscale/tailscale/issues/779

Duplicate of https://github.com/tailscale/tailscale/issues/779

**Closed by DentonGentry** 2022-05-07 18:07 UTC
Labels: OS-linux, packaging, L1 Very few, P1 Nuisance, T4 Docs
