### ISSUE TITLE
libtailscale hit Android targetSdkVersion 30 bug

### ISSUE THREAD

**Issue by awsong** [tailscale/tailscale#8126] opened 2023-05-12 07:13 UTC
### What is the issue?

I'm trying to use libtailscale in my android app. I compiled libtailscle into shared library and call it from my app. It builds fine, but once I call `tailscale_up()` I got following error  `tsnet.Up: tsnet: route ip+net: netlinkrib: permission denied` which looks identical to #2293 

My target sdk version is 33.

**Comment by awsong** [comment] 2023-05-12 07:48
seemd duplicated with #7757

**Comment by DentonGentry** [comment] 2023-05-12 12:41
Duplicate of https://github.com/tailscale/tailscale/issues/7757

**Closed by DentonGentry** 2023-05-12 12:41 UTC
Labels: needs-triage, bug
