### ISSUE TITLE
MacOS tailscale starts using 100% CPU and lots of network looping Wireguard frames

### ISSUE THREAD

**Issue by dmd** [tailscale/tailscale#5156] opened 2022-07-23 12:47 UTC
### What is the issue?

<img width="313" alt="image" src="https://user-images.githubusercontent.com/41439/180605504-f3476e17-d11b-438f-a9de-a8ab030e306c.png">

About 3x a week on MacOS tailscale starts using 100% cpu and 20 Mbps of bandwidth for no apparent reason. Quitting and restarting it fixes the problem.

### OS

macOS

### OS version

occurred under 12.4, still occurring under 12.5

### Tailscale version

1.26.2

### Bug report

BUG-bdc30f2af8ebb0a7aa591939e9f240a3a57392e2de308db311aab847ee2a88a0-20220723124735Z-31c1419398423a01

**Comment by DentonGentry** [comment] 2022-07-23 12:51
Could you run Wireshark on the utun interface during one of the times when the network bandwidth is so high, and see what it is?

There will be a number of interfaces listed, from utun0 to (probably) utun5. You can find the right one using either `ifconfig` in Terminal.app, or leave Wireshark's initial page open for a while and watch the traffic graphs to see which one is really active.

**Comment by dmd** [comment] 2022-07-23 12:59
Yes, will do next time I see this behavior.

**Comment by mjibson** [comment] 2022-08-10 21:23
Have been seeing occasional 100% CPU on 1.28.0 on linux. `tailscale down` doesn't help, have to kill the process.

**Comment by bradfitz** [comment] 2022-08-10 21:51
@mjibson, any network traffic when it happens? Is it a DNS loop?

Can you grab a CPU profile next time it happens? `tailscale debug --cpu-profile=prof.cpu --profile-seconds=15`

**Comment by mjibson** [comment] 2022-08-11 04:49
Profile attached. wireshark on tailscale0 didn't show any packets during this.
[prof.zip](https://github.com/tailscale/tailscale/files/9306147/prof.zip)

**Comment by bradfitz** [comment] 2022-08-11 05:05
@mjibson, oh, that's #4760 which was a Go bug and now fixed upstream. The fix is in Go 1.18.5 or Go 1.19.

Our official binaries for Tailscale 1.28.0 were built at https://github.com/tailscale/tailscale/blob/v1.28.0/go.toolchain.rev (https://github.com/tailscale/go/commit/149f7d88f11384083d42ccbcdb31693510385ec6) which included the fix: https://github.com/tailscale/tailscale/commit/7fb6781bdaa4cccb61497ccf061fcd5a525a329e

So I guess you built Tailscale yourself. Update your Go.

But that seems unrelated to OP's issue here which was some packet routing loop.

**Comment by DentonGentry** [comment] 2022-08-28 05:29
Do I understand the Wireshark trace correctly:
- it was collected on the utun interface (i.e. the Tailscale interface)
- it shows Wireguard packets traversing the tailnet?

I'd expect to see Wireguard packets in a pcap from the Ethernet or Wi-Fi network. However on the utun interface, I'd expect to see decrypted frames.

This looks like Wireguard packets in a loop.

**Comment by dmd** [comment] 2022-08-28 11:38
Yes, that is correct on both counts.

**Comment by kyhwana** [comment] 2022-09-09 03:00
We're seeing this with 1.30.0 on the client side ( macos 12.5.1.) and 1.30.0 on the subnet router (linux).
Setup is:
Wired network, allows access to IP range a.b.c.x/24 that has the subnet router a.b.c.50 in it. Wired network allows direct access to stuff on a.b.c.x/24
Wifi network is internet access only, no direct access to a.b.c.x/24.

Users have macbook pros and are docked and on the wired network, when they undock and automatically switch to wifi, sometimes their laptop will flood the network with wireguard packets directed at the subnet router a.b.c.50 and the following gets logged on the .50 subnet router. This causes enough traffic to slow access to hosts "behind" the subnet router for all users. (Our network graphs show the macbook on wifi sending several hundred mbit/s of traffic to the subnet router!)


```Sep  9 14:25:59 subnetrouter tailscaled[127770]: Accept: UDP{100.64.0.32:41641 > a.b.c.50:41641} 284 ok```
We can also reproduce this by having a macbook that is ONLY on the wifi network, then turning wifi on and off repeatedly.
(No wireshark trace at this stage, but I can probably hassle someone to get one)

**Comment by woutwoot** [comment] 2022-09-27 07:25
Seems this may be related to https://github.com/tailscale/tailscale/issues/1526

**Comment by dmd** [comment] 2022-10-08 14:17
Is there anything I can do to help with this issue? This happens to me *every day* and so necessitates restarting Tailscale daily. (So what I'm saying is, if you need more data somehow, I can get it, because it's *constant* for me.)

**Comment by bradfitz** [comment] 2022-10-08 21:53
@dmd, can you reproduce it at will?

**Comment by dmd** [comment] 2022-10-08 22:00
Well, there's no *action* I can take to make it suddenly start, but if I simply wait 12-24 hours, there is a close to 100% chance that it will happen.

**Comment by woutwoot** [comment] 2022-10-11 09:22
Happened to me again, checked Wireshark and indeed lots of Wireshark frames are being sent.
As dmd is asking, if there is anything I can run that may help debug please let me know. This is a very annoying issue and it has drained my battery a few times before I noticed.

![image](https://user-images.githubusercontent.com/975741/195051043-109ea79d-104e-4248-a7cf-97febd9fcf83.png)

![image](https://user-images.githubusercontent.com/975741/195051400-a53417ce-6277-4600-85c5-7ac537beff65.png)

**Comment by DentonGentry** [comment] 2022-10-24 13:59
MacOS app version 1.32.1 was released in the App Store this morning containing a fix for https://github.com/tailscale/tailscale/issues/5879, which looks like it might have the same root cause as this.

The App Store is on a 7 day rollout where it will prompt 1% of systems to update today, 2% tomorrow, and so on. Going to the Tailscale page in the App Store app should offer to update immediately.

**Comment by woutwoot** [comment] 2022-10-26 17:29
So far so good with the new version. I would give it a few more days to make sure, but it looks like the issue is indeed fixed! 🎉

**Comment by dmd** [comment] 2022-10-26 17:32
Yes, this appears to have fixed the problem for me!

**Comment by dmd** [comment] 2022-10-27 11:17
This has **not** fixed the problem for me, unfortunately.

**Comment by woutwoot** [comment] 2022-11-09 10:09
@DentonGentry I did not have any issues for a while but I can sadly confirm what @dmd said. It is not fixed 😢

**Comment by woutwoot** [comment] 2022-11-17 06:56
I've had the issue every day for the last few days now. Very annoying.
![image](https://user-images.githubusercontent.com/975741/202377523-679a3a40-39cc-470d-9837-87c473c6d4e8.png)

**Comment by mihaip** [comment] 2022-11-17 22:44
Capturing and uploading a sample of the process when it's in this state may be helpful. You can do this either via the Activity Monitor:
![image](https://user-images.githubusercontent.com/513813/202575489-d0c44dd1-9f63-4963-bd01-b25e5af39a03.png)

Or using Tailscale's own profiling functionality: `/Applications/Tailscale.app/Contents/MacOS/Tailscale debug -cpu-profile - > /tmp/profile.pprof`

**Comment by dmd** [comment] 2022-11-20 14:52
Here's both, taken while Tailscale was in this state.

[profile.zip](https://github.com/tailscale/tailscale/files/10049958/profile.zip)

**Comment by mihaip** [comment] 2022-11-22 00:41
The profile shows equal time spent in socket reads and writes, confirming that it's a looping issue:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/513813/203186192-43805a0a-df50-44bc-9735-55b74bba0ad4.png">

**Comment by mihaip** [comment] 2022-12-09 17:02
For the next release of Tailscale we are evaluating more explicitly binding the underlying connections that Tailscale uses on macOS and iOS to a physical interface (for #6565). That may help with this issue as well. 

If you are currently experiencing networking looping, you may want to try the unstable build of 1.35.24 (or later) from https://tailscale.com/kb/1083/install-unstable/.

**Comment by bradfitz** [comment] 2023-01-04 23:17
I merged #6868 into this one as we suspect it's the same. Some pprof info is in that bug.

**Comment by bradfitz** [comment] 2023-01-04 23:23
@dmd, @offbyone, @kdrag0n, can one of do a packet capture with Wireshark or whatever next time this happens, getting at least the Tailscale `utun<N>` device? You can email it to my github username at tailscale.com if you prefer, referencing this GitHub bug.

**Comment by bradfitz** [comment] 2023-01-04 23:24
Also a `tailscale bugreport` and a few `tailscale debug metrics` outputs a few seconds apart.

**Comment by dmd** [comment] 2023-01-04 23:28
@bradfitz I have not had the issue recur since switching to the TestFlight version a few weeks ago.

**Comment by LouisFaure** [comment] 2023-01-10 20:21
I often experienced this problem in airports, when the laptop needed to reconnect to networks at several occasion. Now I found a very simple way to reproduce the issue while connected via Wi-Fi on version 1.34-2:

1. Connect to an exit node from Tailscale.
2. Disconnect from your network.
3. Reconnect to the same network.
4. Check the activity monitor:

<img width="444" alt="Screenshot 2023-01-10 at 23 09 05" src="https://user-images.githubusercontent.com/27488782/211651924-cd229cad-3114-41ab-b79b-a6222159f194.png">
Similarly, a high number of Wireshark frames are being sent.

As a side note, I encountered this issue also when not using exit node, but I cannot reproduce this particular situation unfortunately.

In any case, like @dmd I have tried with the unstable version (1.35.126), and I am happy to report that the issue is not occurring when I redo all the steps mentioned here!

**Comment by kdrag0n** [comment] 2023-01-10 20:23
I also switched to TestFlight version 1.35.99 last week and haven't encountered the issue again since then.

**Comment by woutwoot** [comment] 2023-01-14 20:00
I have not switched to any specific test version but also have not noticed the issue being there lately. Still giving it some more time though as last time I was also claiming victory a bit to soon.

**Comment by mihaip** [comment] 2023-01-25 17:55
Tentatively closing this based on the feedback with the 1.35 builds -- that change has been picked up in the [1.36 stable build](https://tailscale.com/changelog/#2023-01-24-client).

Please comment if you are still experiencing this with 1.36 and we will reopen the issue.

**Closed by mihaip** 2023-01-25 17:55 UTC
Labels: OS-macos, L2 Few, P2 Aggravating, T5 Usability, bug

**Comment by kardiojack** [comment] 2023-02-15 03:12
I am experiencing this issue with 1.36.1 (App Store), M1 Macbook Pro. I can submit logs tomorrow if that would be helpful. Only noticed it because my Macbook felt a little warm which it never does (and then Googling the process at 100% led me here).

**Comment by mihaip** [comment] 2023-02-15 17:20
That sounds like a separate issue. There have been some throughput and efficiency improvements in 1.36 (see [this blog post](https://tailscale.com/blog/throughput-improvements/) for details), but they have not been implemented for the macOS client (yet).

It would still be useful to record a CPU profile while this is happening (via `/Applications/Tailscale.app/Contents/MacOS/Tailscale debug -cpu-profile - > /tmp/profile.pprof`) and attaching it to a new bug report, in case there's anything macOS-specific that we should look into.
