### ISSUE TITLE
oauth: downscoping from ‘all’ to ‘devices’ removes access to all tags

### ISSUE THREAD

**Issue by aviau** [tailscale/tailscale#8299] opened 2023-06-07 19:48 UTC
### What is the issue?

When using an [oauth-generated API Key](https://tailscale.com/kb/1215/oauth-clients/) with the `all` scope, I cannot create an [auth key](https://tailscale.com/kb/1085/auth-keys/).

I am getting the following error:
```
requested tags [tag:prod] are invalid or not permitted (400)
```

These are my tag definitions in ACLs:
```
	"tagowners": {
		"tag:corp": [
			"autogroup:admin",
		],
		"tag:prod": [
			"autogroup:admin",
                 ],
		"tag:staging": [
			"autogroup:admin",
		],
	},
```

I tried to rule out an ACL issue by changing the tagowners to all kinds of things, including an empty list, and no dice.

I originally opened a bug in the terraform provider, but after more digging it looks like this is a tailscale bug. (ref: https://github.com/tailscale/terraform-provider-tailscale/issues/247). (Feel free to close the terraform provider bug if this is indeed a tailscale bug)

### Steps to reproduce

1. Create an API key using oauth (you can do this using terraform like documented in my [issue](https://github.com/tailscale/terraform-provider-tailscale/issues/247))
2. Try to create a tailnet auth key with tags that you defined in ACLs
3. It fails

### Are there any recent changes that introduced the issue?

Not sure. This used to work so the breakage must be recent.

**Comment by willnorris** [comment] 2023-06-08 17:27
I'm having trouble reproducing this issue.  Removing terraform from the equation...

1. Create new OAuth client with `all` scope: `tskey-client-XXXX`
2. Create new API access token from that client:
    ``` sh
    $ curl -d "client_secret=tskey-client-XXXX" "https://api.tailscale.com/api/v2/oauth/token"
    {"access_token":"tskey-api-YYYY","token_type":"Bearer","expires_in":3600,"scope":"all"}
    ```
3. Create a new auth key from that API key:
    ``` sh
    $ % curl -u "tskey-api-YYYY:" "https://api.tailscale.com/api/v2/tailnet/-/keys" --data '
    {
      "capabilities": {
        "devices": {
          "create": {
            "tags": [ "tag:server" ]
          }
        }
      }
    }'
    {"id":"ZZZ","key":"tskey-auth-ZZZ","created":"2023-06-08T17:09:16Z","expires":"2023-09-06T17:09:16Z","capabilities":{"devices":{"create":{"reusable":false,"ephemeral":false,"preauthorized":false,"tags":["tag:server"]}}}}
    ```

Can you try reproducing those and see what happens on your end?  This seems to be behaving as expected, so next step would be to dig into the terraform provider and see what it's doing.

**Comment by aviau** [comment] 2023-06-08 17:50
This example works.

However the terraform provider probably uses the tailnet key creation endpoint a bit differently.

It also  specifies `reusable`, `preauthorized`, `expiry`.

**Comment by aviau** [comment] 2023-06-08 17:55
I wish I could print the HTTP requests from the terraform provider. I tried running terraform with `TF_LOG=debug` but I don't get much more.

**Comment by willnorris** [comment] 2023-06-08 18:34
So this is about the simplest code I can come up with that uses the same tailscale go client as the terraform provider, and follows basically the same steps to [create the client](https://github.com/tailscale/terraform-provider-tailscale/blob/4a6da0fb07ced9ca90f7ba32ba988da4a533c0e0/tailscale/provider.go#L110-L131) and [create a new auth](https://github.com/tailscale/terraform-provider-tailscale/blob/4a6da0fb07ced9ca90f7ba32ba988da4a533c0e0/tailscale/resource_tailnet_key.go#L74-L88) key.  And it still works fine 😕 , so it doesn't appear to be any issue in the client.  @aviau could you try this with the OAuth client that is failing in terraform?

``` go
package main

import (
	"context"
	"flag"
	"log"
	"os"
	"strings"
	"time"

	"github.com/tailscale/tailscale-client-go/tailscale"
)

func main() {
	tags := flag.String("tags", "", "comma-separated list of tags to apply to the authkey")
	flag.Parse()

	clientSecret := os.Getenv("OAUTH_CLIENT_SECRET")
	if clientSecret == "" {
		log.Fatal("OAUTH_CLIENT_SECRET must be set")
	}

	if *tags == "" {
		log.Fatal("at least one tag must be specified")
	}

	client, err := tailscale.NewClient(
		"",
		"-",
		tailscale.WithOAuthClientCredentials("-", clientSecret, []string{"all"}),
	)
	if err != nil {
		log.Fatal(err)
	}

	var capabilities tailscale.KeyCapabilities
	capabilities.Devices.Create.Reusable = true
	capabilities.Devices.Create.Ephemeral = false
	capabilities.Devices.Create.Tags = strings.Split(*tags, ",")
	capabilities.Devices.Create.Preauthorized = true

	var opts []tailscale.CreateKeyOption
	opts = append(opts, tailscale.WithKeyExpiry(60*time.Second))

	key, err := client.CreateKey(context.Background(), capabilities, opts...)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("authkey: %v", key)
}
```

**Comment by aviau** [comment] 2023-06-08 19:16
It reproduces:
```
130|alexandre.viau@alexandreviau-Laptop:~/git/flare/tailscale-test$ go run test.go
2023/06/08 15:16:26 at least one tag must be specified
exit status 1
```

**Comment by willnorris** [comment] 2023-06-08 19:17
you need to provide a tag... `go run test.go -tags "tag:prod"`

**Comment by aviau** [comment] 2023-06-08 19:18
Yeah, I deleted my message when I realised...

**Comment by aviau** [comment] 2023-06-08 19:19
Well. It works.

**Comment by aviau** [comment] 2023-06-08 19:20
So, what if the provider wasn't built with the same tailscale client version? Or there is a client configuration problem in the provider?

**Comment by willnorris** [comment] 2023-06-08 19:23
ah, good idea... I didn't look to see which version of the client the provider is using.  I'll look at that.

and yes, the only other thing I can figure is something in how the provider is configuring the client.  But your comment about this same config working recently led me to think it was something we changed server-side.  Which is still possibly the case, but I don't yet see what is happening that's tripping it up.

**Comment by aviau** [comment] 2023-06-08 19:25
Hugh, never mind. I found it. I lied. I wasn't using the `all` scope.

Sorry for not noticing earlier. I have multiple terraform envs and I was looking at the wrong provider config 😞 

I was using the `devices` scope.

However, I think the docs say that the devices scope is enough?
- https://tailscale.com/kb/1215/oauth-clients/

**Comment by willnorris** [comment] 2023-06-08 19:28
devices scope is enough if you have tags setup properly.  See this coincidental reddit post this morning that talks about that: https://www.reddit.com/r/Tailscale/comments/144d1ks/issues_creating_tagged_tailnet_key_with_oauth/

**Comment by aviau** [comment] 2023-06-08 19:40
>  then create an OAuth client with tag:foo

I don't seem to be asked for a tag when I create a client, am I missing something?

**Comment by willnorris** [comment] 2023-06-08 19:42
it's shown when you select the "devices" scope:

<img width="522" alt="Screenshot 2023-06-08 at 12 41 10 PM" src="https://github.com/tailscale/tailscale/assets/1112/672a56c6-3022-461a-9d07-32d99dddedf0">

**Comment by aviau** [comment] 2023-06-08 19:44
Hugh. The "tags" dropdown does not appear when you select "all", I could never have found it.

**Comment by aviau** [comment] 2023-06-08 19:50
Ok so then the issue is here:
```
provider "tailscale" {
  tailnet             = "flare.systems"
  oauth_client_id     = module.pyro_secrets.secrets["tailscale"]["OAUTH_CLIENT_ID"]
  oauth_client_secret = module.pyro_secrets.secrets["tailscale"]["OAUTH_CLIENT_SECRET"]
  scopes              = ["devices"]
}
```

With this config, I am effectively downscoping my access to "devices", which includes no tags at all?

Should there be a "tags" option here?

**Comment by aviau** [comment] 2023-06-08 21:22
Cool! Thanks for being so helpful.

My immediate problem can be worked around so there is no urgency here.

I retitled the issue. Feel free to retitle again if it’s not clear.

**Comment by eblume** [comment] 2023-07-04 01:21
Hi, I seem to be running in to this same or a similar issue, but in my case I am explicitly requesting the "all" scope in my provider block, and I have confirmed that my oauth client has the "all" scope" as well.

> │   with tailscale_tailnet_key.memory_alpha,
> │   on memory_alpha.tf line 46, in resource "tailscale_tailnet_key" "memory_alpha":
> │   46: resource "tailscale_tailnet_key" "memory_alpha" {
> │
> │ requested tags [tag:vpc] are invalid or not permitted (400)

```hcl
provider "tailscale" {
  tailnet = var.tailscale_tailnet
  oauth_client_id = data.aws_ssm_parameter.tailscale_oauth_client_id.value
  oauth_client_secret = data.aws_ssm_parameter.tailscale_oauth_client_secret.value
  scopes = ["all"]
}

resource "tailscale_tailnet_key" "memory_alpha" {
  expiry = 30
  preauthorized = true
  reusable = false
  tags = ["tag:vpc"]
}
```

![image](https://github.com/tailscale/tailscale/assets/725328/b5fbab87-755f-440f-8a4b-61c47171a013)

Please let me know if I can provide any extra details or if you think this should be reported separately, etc. Thank you!

**Comment by eblume** [comment] 2023-07-04 05:11
I've run through the initial curl scripts @willnorris suggested at the top of this thread (haven't tried the Go script yet, apologies). It gives me a similar error, I suspect I am missing something about how tags work - is there an ACL I need to set first?

```bash
➜ client_id=$(aws-vault exec blumeops -- aws ssm get-parameter --name "/tailscale/oauth_
client_id" --with-decryption --query "Parameter.Value" --output text)

➜ client_secret=$(aws-vault exec blumeops -- aws ssm get-parameter --name "/tailscale/oaut
h_client_secret" --with-decryption --query "Parameter.Value" --output text)

➜ access_token=$(curl -d "client_secret=${client_secret}" "https://api.tailscale.com/api/v2/oauth/token" | jq -r '.access_token')

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   202  100   129  100    73    191    108 --:--:-- --:--:-- --:--:--   301

➜ curl -u "${access_token}:" "https://api.tailscale.com/api/v2/tailnet/-/keys" --data '
{
  "capabilities": {
    "devices": {
      "create": {
        "tags": [ "tag:server" ]
      }
    }
  }
}'

{"message":"requested tags [tag:server] are invalid or not permitted"}
```

As you can see, the error messages match, so this is either a bug in the tailscale API itself or - much more likely - some misunderstanding on my part.

**Comment by aviau** [comment] 2023-07-04 13:19
>  scopes = ["all"]

Did you try removing that line?

**Comment by willnorris** [comment] 2023-07-04 13:43
@eblume, have you [defined these tags](https://tailscale.com/kb/1068/acl-tags/#defining-a-tag) (`tag:vpc` and `tag:server`) in your policy file?  

If so, could you [share a bugreport](https://tailscale.com/kb/1227/bug-report/) from any node on your tailnet, and I can use that to see if anything else looks amiss.

**Comment by eblume** [comment] 2023-07-04 14:50
Thank you @willnorris , I missed that defining tags was a requirement for host validation. I'm fixed now by adding a `tailscale_acl resource` that defines a tagOwners section with that tag.

In case it helps anyone in the future, I got there by way of the terraform docs without having read the ACL documentation first. I wonder if a line in the [tailscale_telnet_key](https://registry.terraform.io/providers/tailscale/tailscale/latest/docs/resources/tailnet_key) resource docs pointing to ["Setting up a server on your Tailscale network"](https://tailscale.com/kb/1245/set-up-servers/) would help for people like myself.

Feel free to prune out these messages (or ask me to) from this thread, it is not related.

**Comment by willnorris** [comment] 2023-09-25 20:37
You can now provide a set of requested tags when calling the OAuth token endpoint.

The OAuth client must have permission to set the requested tags, either by having the `all` scope which grants access to all tags, or by having tags that are [set as owner](https://tailscale.com/kb/1068/acl-tags/#defining-tag-owners) of the requested tags.  Tags only make sense in the context of the `devices` oauth scope, so will return an error if you request tags without the devices scope.

More docs at https://tailscale.com/kb/1215/oauth-clients/#tailscale-oauth-token-endpoint

**Closed by willnorris** 2023-09-25 20:37 UTC
Labels: L3 Some users, P2 Aggravating, T5 Usability, api, bug
