### ISSUE TITLE
Arch Linux - IP forwarding is disabled, subnet routing/exit nodes will not work

### ISSUE THREAD

**Issue by schopenhauer** [tailscale/tailscale#4317] opened 2022-03-29 19:00 UTC
### What is the issue?

The command `tailscale up --advertise-routes=10.0.0.0/24` yields the following warning message:

```
Warning: IP forwarding is disabled, subnet routing/exit nodes will not work.
See https://tailscale.com/kb/1104/enable-ip-forwarding/
```

My `/etc/sysctl.conf` config file contains the following two lines on Arch Linux:

```
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding = 1
```

Is this a known bug / issue?

### OS

Linux

### OS version

Arch Linux

### Tailscale version

1.22.2

**Comment by DentonGentry** [comment] 2022-03-29 20:21
To make progress on this we'll need the output of `tailscale bugreport` shortly after running `tailscale up --advertise-routes=10.0.0.0/24`

**Comment by schopenhauer** [comment] 2022-03-29 20:48
BUG-db96d23cf7dacdc35cdfbe03354f24d1e51cacd5b11651c1bcb051c6eee6eead-20220329204750Z-9dd972992570167a

**Comment by DentonGentry** [comment] 2022-03-29 21:38
Some notes:
- default route is a bond0 interface
- right before the first mention of 10.0.0.0 in telemetry, the interface goes down then back up
- no errors or backtraces just before the first mention of 10.0.0.0

**Comment by bradfitz** [comment] 2022-03-30 03:41
cc @maisem who recently worked on this code (after 1.22.x) but likely still has it in his head.

**Comment by DentonGentry** [comment] 2022-08-28 01:40
I guess one possibility:

>My /etc/sysctl.conf config file contains the following two lines on Arch Linux:

is if the file has been populated as part of installing the subnet router, but not applied. So the running kernel still has forwarding set to zero.

**Comment by iphakade** [comment] 2022-10-26 18:58
The issue is that this is not persisted as the /etc/sysctl.conf in Arch / Manjaro now needs to be a config file inside /etc/sysctl.d/ ie just do sudo mv /etc/sysctl.conf /etc/sysctl.d/99-sysctl.conf

At least this worked for me when I was having the same issue. It now persists across reboots and when I enable advertising of the exit node I no longer see the ip forwarding error message.

Reference: https://wiki.archlinux.org/title/Sysctl#Configuration

**Comment by DentonGentry** [comment] 2022-10-26 19:16
That does explain the symptoms. I've filed an issue for our documentation to update the instructions if the Linux system has an /etc/sysctl.d directory.

Since this solved the issue for one person, we'll close it. If the problem persists after moving the sysctl.conf file, please reopen it.

**Closed by DentonGentry** 2022-10-26 19:16 UTC
Labels: L3 Some users, P2 Aggravating, T5 Usability, bug
