### ISSUE TITLE
FR: show version string on mobile

### ISSUE THREAD

**Issue by ericswpark** [tailscale/tailscale#6129] opened 2022-10-30 13:48 UTC
### What are you trying to do?

Show the version string on mobile

### How should we solve this?

Add a version string under a menu like "About"

### What is the impact of not solving this?

Users have to dig into the phone settings, go to the App Store, or check the Tailscale admin panel to retrieve the version string

**Comment by bradfitz** [comment] 2022-10-30 13:53
I guess you're talking about iOS specifically?

**Comment by ericswpark** [comment] 2022-10-30 13:57
@bradfitz yes, AFAI~~K~~ can tell the iOS app doesn't show the version string anywhere, which means it's rather annoying to check the version when submitting bug reports and what not. iOS will also auto-update apps and cause even more confusion.

**Comment by DentonGentry** [comment] 2022-10-30 14:43
Duplicate of https://github.com/tailscale/tailscale/issues/3190

**Closed by DentonGentry** 2022-10-30 14:43 UTC
Labels: needs-triage, fr
