### ISSUE TITLE
FR: Android TV - make choosing exit node as easy as Wireguard

### ISSUE THREAD

**Issue by csp5me** [tailscale/tailscale#4511] opened 2022-04-25 04:49 UTC
### What are you trying to do?

In Wireguard for Android [TV], making a connection to a vpn server is as easy as toggling a button.

In Tailscale v1.24.0 I have to choose a menu "Exit node" and select None, or an exit node. BTW on Android TV there is a bug with selecting an exit node [see bug report I issued].

### How should we solve this?

Make the usability on Android and Android TV just as easy as Wireguard on Android. 

Show on the main panel, instead a list of network devices, a list of toggles that represents the Exit node menu.  
Purpose of this change: make it easier to change exit node.
Hide the list of network devices behind a separate menu, or put in the main panel 2 tabs - exit nodes, network devices.

### What is the impact of not solving this?

Tailscale is more complex to use than Wireguard or any other vpn tool like nordvpn.

**Comment by DentonGentry** [comment] 2022-04-25 12:09
To set expectations: the primary functionality of Tailscale is connectivity within the tailnet. Exit nodes are a useful feature, but not the primary use as it might be using other products. I understand the feature request but we might not choose to implement it right away.

**Comment by DentonGentry** [comment] 2022-04-30 17:40
Duplicate of https://github.com/tailscale/tailscale/issues/4383

**Closed by DentonGentry** 2022-04-30 17:40 UTC
Labels: OS-android, L2 Few, P1 Nuisance, T2 Visual Polish, needs-decision, fr
