### ISSUE TITLE
On Win7 Tailscale is creating new tunnel on each restart.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2236] opened 2021-06-23 21:44 UTC
Steps to reproduce:

1. Tailscale 1.9.185 install and connect on Win7 64bit
2.Exit it 
3. Restart Windows
4. Tailscale will be creating wintun (i.e tunnel interface 213)
5. exit Tailscale
6. restart windows
7. Tailscale will be creating wintun (i.e tunnel interface 214)

Windows Version : Win 7 64-bit 
Tailscale : 1.9.185 / 1.8.7

**Comment by DentonGentry** [comment] 2022-10-30 11:54
Duplicate of https://github.com/tailscale/tailscale/issues/5678 (which has more detail, so closing this one in favor of that one)

**Closed by DentonGentry** 2022-10-30 11:54 UTC
Labels: OS-windows, L2 Few, P3 Can't get started, T5 Usability
