### ISSUE TITLE
v1.52.0 Failed to connect to Tailscale service

### ISSUE THREAD

**Issue by llllllllqq** [tailscale/tailscale#10023] opened 2023-10-31 03:43 UTC
### What is the issue?

---------------------------
Tailscale Error
---------------------------
Failed to connect to Tailscale service.

Version 1.52.0 (t3c2ff1e4a-gfccfad18e)

LogID: d7215ddcb08bb19ce0ab4ea8bcfa79f9bee1ba3764701c131f3cd9fc888038c9

(Ctrl-C to copy this text)

---------------------------
确定   
---------------------------

### Steps to reproduce

Normally start tailscale service (or after reboot)

### Are there any recent changes that introduced the issue?

After updated from 1.51.0 to 1.52.0, this bug occurs.

### OS

Windows

### OS version

Windows 10

### Tailscale version

1.52.0

### Other software

zerotier
clash for windows

### Bug report

d7215ddcb08bb19ce0ab4ea8bcfa79f9bee1ba3764701c131f3cd9fc888038c9

**Comment by DentonGentry** [comment] 2023-10-31 03:45
```
2023-10-31 03:44:01.6901014 +0000 UTC: ui: ipnclient: backoff: 12191 msec
2023-10-31 03:44:13.8971699 +0000 UTC: ui: watchBackend: Connect: Get "http://local-tailscaled.sock/localapi/v0/watch-ipn-bus?mask=14": open \\.\pipe\ProtectedPrefix\Administrators\Tailscale\tailscaled: The system cannot find the file specified.
2023-10-31 03:44:13.8976933 +0000 UTC: ui: service state: Running
2023-10-31 03:44:13.8976933 +0000 UTC: ui: localClient.ProfileStatus failed: Get "http://local-tailscaled.sock/localapi/v0/profiles/current": open \\.\pipe\ProtectedPrefix\Administrators\Tailscale\tailscaled: The system cannot find the file specified.
```

In the Task Manager, is the Tailscale Service running?

**Comment by llllllllqq** [comment] 2023-10-31 03:47
> ```
> 2023-10-31 03:44:01.6901014 +0000 UTC: ui: ipnclient: backoff: 12191 msec
> 2023-10-31 03:44:13.8971699 +0000 UTC: ui: watchBackend: Connect: Get "http://local-tailscaled.sock/localapi/v0/watch-ipn-bus?mask=14": open \\.\pipe\ProtectedPrefix\Administrators\Tailscale\tailscaled: The system cannot find the file specified.
> 2023-10-31 03:44:13.8976933 +0000 UTC: ui: service state: Running
> 2023-10-31 03:44:13.8976933 +0000 UTC: ui: localClient.ProfileStatus failed: Get "http://local-tailscaled.sock/localapi/v0/profiles/current": open \\.\pipe\ProtectedPrefix\Administrators\Tailscale\tailscaled: The system cannot find the file specified.
> ```
> 
> In the Task Manager, is the Tailscale Service running?

Yes, it is running. And restart it won't help.

**Comment by kegns** [comment] 2023-10-31 04:30
same problem here

C:\Program Files\Tailscale>tailscale status
failed to connect to local tailscaled (which appears to be running as tailscaled.exe, pid 13272). Got error: Get "http://local-tailscaled.sock/localapi/v0/status": open \\.\pipe\ProtectedPrefix\Administrators\Tailscale\tailscaled: The system cannot find the file specified.

I've tried reboot, clean install folder and re-install, downgrade, still not working

**Comment by l1nxy** [comment] 2023-10-31 05:53
Same here. 
if reboot the OS, tailscale can up, but it will broken when connecting to other node.

**Comment by DentonGentry** [comment] 2023-10-31 05:57
@l1nxy That does not sound like the same problem. It tailscale can come up, can you get a. bugreport?
Hold control while right-clicking on the Tailscale icon in the taskbar, then select Debug > Bug report.

**Comment by GD-Slime** [comment] 2023-10-31 05:58
Same problem on me. 
Surprisingly, when I searched the internet, it seems that these problems are mostly occurring among Chinese users. Could this be related to China's internet environment or system language? 
My speculation may be incorrect, but hopefully can help fix this problem.

**Comment by atomshadows** [comment] 2023-10-31 06:03
I have the same problem,, the problem seems to be related to wintun and wireguard-go, I tried reinstalling the program, rebooting the system, resetting the network settings, reinstalling the network drivers, but it didn't solve the problem.

**Comment by l1nxy** [comment] 2023-10-31 06:11
> @l1nxy That does not sound like the same problem. It tailscale can come up, can you get a bugreport? Hold control while right-clicking on the Tailscale icon in the taskbar, then select Debug > Bug report.

I  did not fount the Debug option. but i can sure the upgrade has some problem. because, i was coding use vscode with tailscale extention, and it works. after upgrade, i can connect my node with ssh, but if connecting with vscode, the tailscale will broken.
There has some info, if you need log, please tell me how to get it .
![Snipaste_2023-10-31_14-10-07]
(https://github.com/tailscale/tailscale/assets/12152770/19454cf7-dcb3-48e8-b8e7-40b3e9fc1161)
![Snipaste_2023-10-31_14-10-57](https://github.com/tailscale/tailscale/assets/12152770/b7e8796e-cbd8-4db4-bf6c-87dcfb03d78a)

**Comment by DentonGentry** [comment] 2023-10-31 06:18
@l1nxy from a cmd.exe prompt please run `tailscale bugreport` and paste the output here.

**Comment by l1nxy** [comment] 2023-10-31 06:22
@DentonGentry 
After borken, the output is : ❯ tailscale bugreport
Post "http://local-tailscaled.sock/localapi/v0/bugreport?": open \\.\pipe\ProtectedPrefix\Administrators\Tailscale\tailscaled: The system cannot find the file specified.

After reboot os, the output is: ❯ tailscale bugreport
BUG-a3d77fd3a5df963093ae0a1c80e635830bf3bb22ef1542ef888107ed5c30dab4-20231031062111Z-5545bf02f68b1bfb

**Comment by DentonGentry** [comment] 2023-10-31 06:34
@l1nxy I don't doubt there is a problem, but being able to SSH and get `tailscale status` outputs means it is a different problem than others. Please open a new issue for the difficulties with VSCode.

**Comment by l1nxy** [comment] 2023-10-31 07:03
@DentonGentry I opened a new issue here: #10025

**Comment by DentonGentry** [comment] 2023-10-31 11:59
@llllllllqq @kegns @GD-Slime could you open a `cmd.exe` shell and run `tailscaled.exe` and paste the output here?
We're looking for whether it is similar to https://github.com/tailscale/tailscale/issues/10023#issuecomment-1786504326

**Comment by kegns** [comment] 2023-10-31 12:23
> @llllllllqq @kegns @GD-Slime could you open a `cmd.exe` shell and run `tailscaled.exe` and paste the output here? We're looking for whether it is similar to [#10023 (comment)](https://github.com/tailscale/tailscale/issues/10023#issuecomment-1786504326)

logtail started
local disk logdir: C:\ProgramData\Tailscale\Logs
Program starting: v1.52.0-t3c2ff1e4a-gfccfad18e, Go 1.21.3: []string{"tailscaled"}
LogID: cfc40e7b694bbba5cdb641ce0949dd0dbb239c49a80604bd71efe5c4338a9db0
logpolicy: using LocalAppData dir C:\Users\{user}\AppData\Local\Tailscale
flushing log.
logger closing down
safesocket.Listen: namedpipe.Listen: open \\.\pipe\ProtectedPrefix\Administrators\Tailscale\tailscaled: Access is denied.

**Comment by DentonGentry** [comment] 2023-10-31 12:25
@kegns does it print a goroutine, like this?

```
goroutine 11 [running]:
golang.org/x/sys/windows.UTF16PtrToString(0x0?)
        golang.org/x/sys@v0.12.0/windows/syscall_windows.go:121 +0x25
golang.zx2c4.com/wintun.logMessage(0xc000477240?, 0xf38ebfdcc0, 0xc000477218?)
        golang.zx2c4.com/wintun@v0.0.0-20230126152724-0fa3db229ce2/wintun.go:51 +0xff
syscall.SyscallN(0x7ff9d0cc3fb0?, {0xc000477898?, 0x3?, 0xc0004778b0?})
        runtime/syscall_windows.go:544 +0x107
```

**Comment by llllllllqq** [comment] 2023-10-31 12:26
> @llllllllqq @kegns @GD-Slime could you open a `cmd.exe` shell and run `tailscaled.exe` and paste the output here? We're looking for whether it is similar to [#10023 (comment)](https://github.com/tailscale/tailscale/issues/10023#issuecomment-1786504326)

logtail started
local disk logdir: C:\ProgramData\Tailscale\Logs
Program starting: v1.52.0-t3c2ff1e4a-gfccfad18e, Go 1.21.3: []string{"C:\\Program Files\\Tailscale\\tailscaled.EXE"}
cleaning log files; number of files 51 > 50
cleaned log file C:\ProgramData\Tailscale\Logs\tailscale-service-20230916T144221-1694846541.txt (size 227329); new bytes=10937749, files=50
LogID: 7e45a7fd5ddac2e918fa0b68938649959e47f1f21d8fd8d70f5d1961602136a1
logpolicy: using dir C:\ProgramData\Tailscale
wgengine.NewUserspaceEngine(tun "Tailscale") ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x5f0605]

goroutine 22 [running]:
golang.org/x/sys/windows.UTF16PtrToString(0x0?)
        golang.org/x/sys@v0.13.0/windows/syscall_windows.go:119 +0x25
golang.zx2c4.com/wintun.logMessage(0x0?, 0xda985fd960, 0x0?)
        golang.zx2c4.com/wintun@v0.0.0-20230126152724-0fa3db229ce2/wintun.go:51 +0xff
syscall.SyscallN(0x7ffea9843fb0?, {0xc0002b1898?, 0x3?, 0xc0002b18b0?})
        runtime/syscall_windows.go:544 +0x107
syscall.Syscall(0x12c60e0?, 0xc000032aa0?, 0xc0002b1978?, 0x57df85?, 0xc2108a?)
        runtime/syscall_windows.go:482 +0x35
golang.zx2c4.com/wintun.CreateAdapter({0xc12ea4?, 0x45d964b800?}, {0xc12ea4, 0x9}, 0xc00000a760)
        golang.zx2c4.com/wintun@v0.0.0-20230126152724-0fa3db229ce2/wintun.go:95 +0xf9
github.com/tailscale/wireguard-go/tun.CreateTUNWithRequestedGUID({0xc12ea4, 0x9}, 0xd6ea90?, 0x500)
        github.com/tailscale/wireguard-go@v0.0.0-20230929223258-2f6748dc88e7/tun/tun_windows.go:69 +0x45
github.com/tailscale/wireguard-go/tun.CreateTUN(...)
        github.com/tailscale/wireguard-go@v0.0.0-20230929223258-2f6748dc88e7/tun/tun_windows.go:63
tailscale.com/net/tstun.New(0xc0000a60a0, {0xc12ea4, 0x9})
        tailscale.com@v1.52.0/net/tstun/tun.go:47 +0x85
main.tstunNewWithWindowsRetries(0xc0000a60a0, {0xc12ea4, 0x9})
        tailscale.com@v1.52.0/cmd/tailscaled/tailscaled_windows.go:93 +0x119
main.tryEngine(0xc3b35e?, 0xc000132d80, {0xc12ea4, 0x9})
        tailscale.com@v1.52.0/cmd/tailscaled/tailscaled.go:657 +0x2ef
main.createEngine(0xc0000a60a0, 0xbd1de0?)
        tailscale.com@v1.52.0/cmd/tailscaled/tailscaled.go:591 +0x19d
main.getLocalBackend({0x0?, 0x0?}, 0xc0000a60a0, {0x7e, 0x45, 0xa7, 0xfd, 0x5d, 0xda, 0xc2, ...}, ...)
        tailscale.com@v1.52.0/cmd/tailscaled/tailscaled.go:498 +0x11a
main.startIPNServer.func2()
        tailscale.com@v1.52.0/cmd/tailscaled/tailscaled.go:464 +0x259
created by main.startIPNServer in goroutine 1
        tailscale.com@v1.52.0/cmd/tailscaled/tailscaled.go:452 +0x44a

**Comment by DentonGentry** [comment] 2023-10-31 12:29
Ok. The last function in the backtrace `windows.UTF16PtrToString` could plausibly depend on the locale. We're pursuing the crash with the assumption that it may depend on the language setting.

`windows.UTF16PtrToString` is being passed a null pointer, which implies whatever it is trying to log is missing or wasn't localized or something.

**Comment by kegns** [comment] 2023-10-31 12:30
> @kegns does it print a goroutine, like this?
> 
> ```
> goroutine 11 [running]:
> golang.org/x/sys/windows.UTF16PtrToString(0x0?)
>         golang.org/x/sys@v0.12.0/windows/syscall_windows.go:121 +0x25
> golang.zx2c4.com/wintun.logMessage(0xc000477240?, 0xf38ebfdcc0, 0xc000477218?)
>         golang.zx2c4.com/wintun@v0.0.0-20230126152724-0fa3db229ce2/wintun.go:51 +0xff
> syscall.SyscallN(0x7ff9d0cc3fb0?, {0xc000477898?, 0x3?, 0xc0004778b0?})
>         runtime/syscall_windows.go:544 +0x107
> ```

no, that is all that `tailscaled.exe` returns

**Comment by DentonGentry** [comment] 2023-11-01 06:07
We've been trying to produce the problem here, and tried installing a language packet but Tailscale doesn't crash.
<img width="350" alt="Screenshot 2023-10-31 at 11 00 24 PM" src="https://github.com/tailscale/tailscale/assets/1140756/e5944376-1ce2-46f6-b6e7-a1b579e418d8">

**Comment by llllllllqq** [comment] 2023-11-01 06:11
> We've been trying to produce the problem here, and tried installing a language packet but Tailscale doesn't crash. <img alt="Screenshot 2023-10-31 at 11 00 24 PM" width="350" src="https://user-images.githubusercontent.com/1140756/279590072-e5944376-1ce2-46f6-b6e7-a1b579e418d8.png">

It seems that you're on zh_hant（繁體中文 or 正體中文）. I'm on zh_hans（简体中文）. Maybe this affects sth?

**Comment by avatasia** [comment] 2023-11-01 15:13
> We've been trying to produce the problem here, and tried installing a language packet but Tailscale doesn't crash. <img alt="Screenshot 2023-10-31 at 11 00 24 PM" width="350" src="https://user-images.githubusercontent.com/1140756/279590072-e5944376-1ce2-46f6-b6e7-a1b579e418d8.png">

Time&Language -> Language & region  
Administrative language setting.
Just test Chinese(Simplified ,China) system local.

**Comment by avatasia** [comment] 2023-11-01 15:24
This problem  occurs on Win11 23h2, and 1.50 on 22h2 does not prompt for updates

**Comment by avatasia** [comment] 2023-11-02 01:26
Ok, now I know why i can't work.  
I have test en_us system local on win11 23h2, it still not work.
So I start a vm ,it suggest me upgrade to 1.50.1. After I reinstall  1.52, all is ok.  The system version is 21H2.
So the problem is tailscale 1.52 not compatible with 23h2.

**Comment by l1nxy** [comment] 2023-11-02 02:27
@avatasia Could you please check if the `wintun.dll` file is exsists in the `C:\Program Files\Tailscale` folder?

I think it relies on the installed software. I tested version 1.52.0 on my work PC which is 23H2, and it works fine.

**Comment by l1nxy** [comment] 2023-11-02 03:26
@DentonGentry The issue is that there is a `wintun.dll` ver0.13 in the `system32` directory, which is quite strange. This is because there is also a `wintun.dll` in the installation directory of `tailscale`. I am unsure why `tailscaled` would load the library from system32 instead of its own directory.

**Comment by avatasia** [comment] 2023-11-02 05:49
> @avatasia Could you please check if the `wintun.dll` file is exsists in the `C:\Program Files\Tailscale` folder?
> 
> I think it relies on the installed software. I tested version 1.52.0 on my work PC which is 23H2, and it works fine.

Bingo.
After i rename wintun.dll in the %system32% and reinstall 1.52.0, it works now.
Thanks very much.

**Comment by kegns** [comment] 2023-11-02 06:02
+1 when I renamed that %system32%\wintun.dll, tailscale came back to life immediately

**Comment by l1nxy** [comment] 2023-11-02 06:05
@avatasia @kegns Do you have clash for windows  on your Windows? I am confused where it is from.

**Comment by kegns** [comment] 2023-11-02 06:09
> @avatasia @kegns Do you have clash for windows on your Windows? I am confused where it is from.

yes, but IMHO I know there is a wintun.dll in the C:\User\{user}\.config\clash, I don't know where does the %system32%\windun.dll come from

**Comment by avatasia** [comment] 2023-11-02 06:23
> @avatasia @kegns Do you have clash for windows on your Windows? I am confused where it is from.

yes, but I dont use tun mode。Usually I use singbox with v2rayu.
The date of wintun.dll in system32 is 2021/8/2 12:50.
It's not the probem of wintun.dll.
The rule of dependence searching is  proximity.

**Comment by llllllllqq** [comment] 2023-11-02 07:43
> @avatasia @kegns Do you have clash for windows on your Windows? I am confused where it is from.

@avatasia @kegns  I also find wintun.dll under system32, date on 2021/8/2. The digital signature shows it's related to wireguard.

**Comment by l1nxy** [comment] 2023-11-02 08:10
@DentonGentry The investigation cannot proceed because the tailscale GUI is not open source. Here's the situation: if I uninstall tailscale v1.5.20 and use `go install` to install tailscaled, it works fine and uses the `wintun.dll` in the application directory.  

However, once I install tailscale v1.5.20, everything changes - the loaded DLL is a different version located in `system32`. The strangest thing is that "process monitor" shows tailcaled loading an image from the application directory, but it prints out the old version number.  

tailscaled crashes because `wintun.dll` v1.3 has a different `log callback` with only two parameters, whereas the new version has three parameters and includes a `timestamp`, which does not exist in the old version of the DLL.  

Perhaps we should check the `wintun.dll` version in tailscaled codebase.

**Comment by DentonGentry** [comment] 2023-11-02 09:42
We're looking in to the DLL search path handling in Tailscale 1.52, and how it resulted in loading wintun.dll from system32.

**Closed** 2023-11-02 15:47 UTC
Labels: OS-windows, L1 Very few, P3 Can't get started, T5 Usability, bug

**Comment by RobinDrake** [comment] 2023-12-22 13:28
> > @avatasia Could you please check if the `wintun.dll` file is exsists in the `C:\Program Files\Tailscale` folder?
> > I think it relies on the installed software. I tested version 1.52.0 on my work PC which is 23H2, and it works fine.
> 
> Bingo. After i renamed wintun.dll in the %system32% and reinstalled 1.52.0, it works now. Thanks very much. So the install package must clean any exist dependence

Sorry, could you please tell me more directly which "wintun" should be renamed? For in %system32% I did not see any "wintun.dll", but there are files showed as the screen shot. Thank you for your help.
![image](https://github.com/tailscale/tailscale/assets/154604952/79a71009-5ceb-4471-8df0-514aca3df560)

**Comment by RobinDrake** [comment] 2023-12-22 13:30
> Sorry, could you please tell me more directly which "wintun" should be renamed? For in %system32% I did not see any "wintun.dll", but there are files showed as the screen shot. Thank you for your help.
> ![image](https://private-user-images.githubusercontent.com/154604952/292496797-79a71009-5ceb-4471-8df0-514aca3df560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNTIwMjUsIm5iZiI6MTcwMzI1MTcyNSwicGF0aCI6Ii8xNTQ2MDQ5NTIvMjkyNDk2Nzk3LTc5YTcxMDA5LTVjZWItNDQ3MS04ZGYwLTUxNGFjYTNkZjU2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQxMzI4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTgwYzI0MDdmZTNhYTQyMDIxNjM2ZTk3NzhiNzFlNTY3MGNlZDQzODMzY2YxOGQ5NzA4NDY3NDBjOTNjM2I1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wF669PX5VgGjPjR8dGtjW7A8ubVmMe5N7Aaw54yiwpk)

Sorry, could you please tell me more directly which "wintun" should be renamed? For in %system32% I did not see any "wintun.dll", but there are files showed as the screen shot. Thank you for your help.
![image](https://github.com/tailscale/tailscale/assets/154604952/09a6f208-2c94-4e52-8082-1ec16050b355)

**Comment by RobinDrake** [comment] 2023-12-22 13:31
> +1 when I renamed that %system32%\wintun.dll, tailscale came back to life immediately

Sorry, could you please tell me more directly which "wintun" should be renamed? For in %system32% I did not see any "wintun.dll", but there are files showed as the screen shot. Thank you for your help.
![image](https://github.com/tailscale/tailscale/assets/154604952/6e618423-da75-4485-87e8-058173e06e10)
