### ISSUE TITLE
High CPU usage on macOS with Tailscale 1.8.1.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2051] opened 2021-06-04 18:59 UTC
ariel% ps auxww|grep IPNE 
will             63182 225.1  0.6  5149708 101648   ??  Rs   21May21  20:32.04 /Applications/Tailscale.app/Contents/PlugIns/IPNExtension.appex/Contents/MacOS/IPNExtension
```
High CPU bursts occur indefinitely until the tailscale app is restarted.

Error from logs:

125fda8a313bcdf3d7ccdb9079a59ebca99305cced37922439575c62bb923b00

2021-06-03 11:10:56.860406 -0500 -0500: magicsock: endpoint update (link-change-major) failed: route ip+net: sysctl: cannot allocate memory

2021-06-03 12:32:43.983597 -0500 -0500: netcheck: probePortMapServices: failed to look up gateway address

2021-06-03 12:32:43.992424 -0500 -0500: netcheck: probePortMapServices: failed to look up gateway address

2021-06-03 12:32:44.002904 -0500 -0500: netcheck: probePortMapServices: failed to look up gateway address

2021-06-03 12:32:44.008611 -0500 -0500: netcheck: probePortMapServices: failed to look up gateway address

2021-06-03 12:32:44.060328 -0500 -0500: netcheck: probePortMapServices: failed to look up gateway address

2021-06-03 12:32:44.078492 -0500 -0500: netcheck: probePortMapServices: failed to look up gateway address

2021-06-03 12:32:44.125481 -0500 -0500: netcheck: probePortMapServices: failed to look up gateway address

2021-06-03 12:32:44.139075 -0500 -0500: netcheck: probePortMapServices: failed to look up gateway address

2021-06-03 12:32:44.229535 -0500 -0500: netcheck: probePortMapServices: failed to look up gateway address

2021-06-03 12:32:44.986213 -0500 -0500: netcheck: probePortMapServices: failed to look up gateway address

2021-06-04 02:16:43.980053 -0500 -0500: netcheck: probePortMapServices: failed to look up gateway address

2021-06-04 02:42:32.51882 -0500 -0500: magicsock: disco: failed to send *disco.CallMeMaybe to 127.3.3.40:1: too many DERP packets queued; dropping

2021-06-04 05:57:31.201029 -0500 -0500: magicsock: disco: failed to send *disco.CallMeMaybe to 127.3.3.40:1: too many DERP packets queued; dropping

2021-06-04 08:01:02.318477 -0500 -0500: netcheck: probePortMapServices: failed to look up gateway address

2021-06-04 09:00:38.472865 -0500 -0500: netcheck: probePortMapServices: failed to look up gateway address

2021-06-04 09:07:33.112189 -0500 -0500: magicsock: disco: failed to send *disco.CallMeMaybe to 127.3.3.40:1: too many DERP packets queued; dropping

2021-06-04 09:07:33.112228 -0500 -0500: magicsock: disco: failed to send *disco.CallMeMaybe to 127.3.3.40:1: too many DERP packets queued; dropping
```

Could be the memory issue ....
failed: route ip+net: sysctl: cannot allocate memory 

macOS  : Big Sur 11.2.3
Tailscale 1.8.1

BUG-125fda8a313bcdf3d7ccdb9079a59ebca99305cced37922439575c62bb923b00-20210604142428Z-8849801608469246

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3853l)

**Comment by bradfitz** [comment] 2021-06-05 03:36
@darshinimashar, was this from you or somebody else?

This smells like the Crowdstrike Falcon thing again. Does this machine have other VPN/firewall/AV software running on it?

**Comment by DentonGentry** [comment] 2021-06-05 10:48
Added Front link.

**Comment by wca** [comment] 2021-06-07 14:45
I had OpenVPN installed, but not active or running.  I've deleted it to see if that helps anything.  No to your other questions.

**Comment by wca** [comment] 2021-06-08 17:49
Just now:
will             69357 237.6  0.6  5149708 102208   ??  Rs   Fri01PM 2119:42.30 /Applications/Tailscale.app/Contents/PlugIns/IPNExtension.appex/Contents/MacOS/IPNExtension

BUG-125fda8a313bcdf3d7ccdb9079a59ebca99305cced37922439575c62bb923b00-20210608174756Z-c315daa54611e187

**Comment by skaag** [comment] 2021-06-11 19:52
I'd like to add some extra information I don't see above, about this issue:

- It happens when your computer goes to sleep with one network, then wakes up to another network
- You don't have to restart Tailscale itself, you just disconnect, reconnect, and CPU load drops back to normal
- This happens even with the latest version 1.8.5, on MacOS Big Sur

**Comment by coder543** [comment] 2021-07-24 20:02
I'm also seeing exactly the behavior @skaag described on Monterey with Tailscale v1.10.1.

**Comment by abreis** [comment] 2021-08-03 18:04
I can also confirm the issue on 10.15.7 Catalina, Intel Mac, Tailscale 1.12.1.

**Comment by marshall-onesignal** [comment] 2021-09-02 16:52
I (well, my entire team of a dozen developers) are having this problem too. I can reproduce the problem that @skaag reports - e.g. I connect to my phone hotspot via wifi, connect to Tailscale, put my computer to sleep, turn off the hotspot network, wake up the computer, computer automatically connects to my office WiFi network, I observe my computer starts sending data to Tailscale about as fast as it possibly can. In my case, disconnecting from Tailscale stops the massive data transmission, but reconnecting resumes it - whatever state is broken here, I think it survives disconnection and reconnection. Only by quitting Tailscale and then reconnecting do I get back to normal operation. 

Please feel free to contact me directly if there is anything I can do to help you resolve this problem - it is affecting our team on a daily basis and causing a lot of churn. I'm going to try repeating this experiment and seeing if I can gather additional data from the Console logs.

**Comment by bradfitz** [comment] 2021-09-02 20:03
@marshall-onesignal, got 15-30 minutes to debug with me on a call?

**Comment by marshall-onesignal** [comment] 2021-09-02 20:10
Yes, I am available. Today, now? You can reach me directly via email,
***@***.***

**Comment by marshall-onesignal** [comment] 2021-09-02 20:17
@bradfitz I am also free today any time. Your calendly is maybe not showing availability for you today, but I am also free to have a call tomorrow. Not sure if there's a way to move this conversation to a separate thread or private channel on GitHub where we can set something up...

**Comment by bradfitz** [comment] 2021-09-02 20:37
@marshall-onesignal, now works. I'll hang out in https://meet.google.com/agp-xuda-ktk ... my email btw is my GH username at tailscale.com

**Comment by DentonGentry** [comment] 2021-09-02 20:41
DNS request looping between MagicDNS and something else? MacOS doesn't have any equivalent to systemd-resolved that I'm aware of, but maybe something in the system registered itself as a DNS resolver.

**Comment by bradfitz** [comment] 2021-09-02 21:35
Based on pcap files that @marshall-onesignal sent, I suspect this is the same as #1526

I'm seeing tons of Wireguard traffic (reportedly maxing out the wifi):

<img width="1368" alt="Screen Shot 2021-09-02 at 2 35 08 PM" src="https://user-images.githubusercontent.com/2621/131919326-34c827fe-908e-4f39-9dcc-8401ba120315.png">

**Comment by DentonGentry** [comment] 2021-11-03 13:27
Duplicate of #1526

**Closed by DentonGentry** 2021-11-03 13:27 UTC
Labels: OS-macos, L1 Very few, P2 Aggravating, T3 Performance/Debugging, waiting-for-info
