### ISSUE TITLE
Tailscale on iOS and macOS stopped working after updating exit nodes to 1.14.0

### ISSUE THREAD

**Issue by Xenobreaker** [tailscale/tailscale#2724] opened 2021-08-27 23:05 UTC
Hello,

I just updated a couple of my Exit Nodes on linux to 1.14.0 and Tailscale has stopped working on all of my iOS and macOS devices on 1.12.3. Windows on 1.14.0 and Android on 1.12.3 are working fine. I have an Exit Node that also works as a Subnet Router with PiHole and have set Tailscale to override local DNS and use my PiHole as the DNS. 

It only stopped working on iOS and macOS after the update of the Exit Nodes to 1.14.0, but it's working fine on Windows 1.14.0 and Android 1.12.3. I also tried installing Tailscale 1.14.0 as a new Exit Node fresh on another linux device with the same results.

After an hour or so of testing, it suddenly started working for iOS and macOS so I just dismissed it as a minor issue but after a few hours, it completely stopped working again. I retested everything (on Windows, Android, iOS and macOS side by side) and I’ve also tried reinstalling Tailscale on my iOS and macOS devices. I’ve also tried both on WiFi and on Mobile Data. 

I really have no idea what is happening here as I didn’t change anything other than updating the exit nodes to 1.14.0 before the issue started happening.

Thanks in advance!

**Comment by ameech** [comment] 2021-08-30 18:49
Hello!

I seem to be running into this issue as well. Exit node works fine from my Macbook Pro, but when I try to use it with my iPhone I'm getting `nsurlerrordomain`.

**Comment by Xenobreaker** [comment] 2021-08-30 21:31
Hello again, 

Just a quick update, I retested everything again one command at a time and I think I’ve narrowed it down. It breaks on iOS and macOS when I have Tailscale run with both “—accept-routes” alongside “—advertise-routes=10.0.0.0/24,10.0.1.0/24” and “—advertise-exit-node” on my device that is running as an exit node, subnet router with PiHole. If I remove “—accept-routes”, everything works again. I’m not sure if this is the intended behaviour but the issue only presents itself on macOS and iOS devices and not on Android and Windows devices connecting to the said exit node. 

I will continue to observe it in the meantime and post updates if I notice anything else or if it breaks again. Thanks!

**Comment by ameech** [comment] 2021-09-01 16:39
Update: I didn't realize I needed to set a Global Nameserver for an exit node to work. Not sure if I missed it in the documentation or what, but I was able to find the solution here: https://reposhub.com/linux/system-utilities/patte-fly-tailscale-exit.html#4-setup-dns-in-tailscale

**Comment by DentonGentry** [comment] 2021-12-18 05:46
This is expected to be resolved for keepsies by fixing https://github.com/tailscale/tailscale/issues/1713 in the 1.20 release in January.

**Comment by DentonGentry** [comment] 2021-12-18 05:47
Duplicate of https://github.com/tailscale/tailscale/issues/1713

**Closed by DentonGentry** 2021-12-18 05:47 UTC
Labels: L1 Very few, P3 Can't get started, T5 Usability
