### ISSUE TITLE
nginx-auth: can't extract tailnet name from hostname

### ISSUE THREAD

**Issue by northys** [tailscale/tailscale#6982] opened 2023-01-16 20:06 UTC
### What is the issue?

```
journalctl -fu tailscale.nginx-auth.service
Jan 16 19:42:46 monitoring tailscale.nginx-auth[1144212]: 2023/01/16 19:42:46 can't extract tailnet name from hostname "northys-laptop.tail7365c.ts.net."
```

### Steps to reproduce

I went trough steps in blogpost https://tailscale.com/blog/tailscale-auth-nginx/ and couldn't got it to work.

### OS

Linux

### OS version

Ubuntu 22

### Tailscale version

tailscale-nginx-auth=0.1.1; tailscale=1.35.158

**Comment by DentonGentry** [comment] 2023-02-11 21:22
> tailscale-nginx-auth=0.1.1; tailscale=1.35.158

Please update to the 0.1.2 version, which includes: https://github.com/tailscale/tailscale/pull/6051

Duplicate of https://github.com/tailscale/tailscale/issues/6048

**Closed by DentonGentry** 2023-02-11 21:22 UTC
Labels: needs-triage, bug
