### ISSUE TITLE
FR: JumpCloud as an IdP

### ISSUE THREAD

**Issue by juergen-kc** [tailscale/tailscale#4524] opened 2022-04-26 02:49 UTC
### What are you trying to do?

I'd like to use JumpCloud as my preferred IdP together with tailscale

### How should we solve this?

Add JumpCloud to the supported IdP's along with the existing ones: 

Existing support
We find that almost everyone asking for SAML or OIDC integration is using one of the common providers, particularly Okta or OneLogin.

[Okta activation instructions](https://tailscale.com/kb/1066/sso-okta)
[OneLogin activation instructions](https://tailscale.com/kb/1070/sso-onelogin)
Google, Microsoft, and GitHub login work [without any activation](https://tailscale.com/kb/1013/sso-providers).

### What is the impact of not solving this?

Forced to go down the route of having an Enterprise Subscription?

**Comment by DentonGentry** [comment] 2022-04-26 02:50
Duplicate of https://github.com/tailscale/tailscale/issues/794

**Closed by DentonGentry** 2022-04-26 02:50 UTC
Labels: needs-triage, fr
