### ISSUE TITLE
Create Amazon FireTV and Android TV compatible package

### ISSUE THREAD

**Issue by Xe** [tailscale/tailscale#1611] opened 2021-03-29 19:35 UTC
It would be nice if we had an android package available for people using the [Amazon FireTV](https://www.amazon.ca/Stick-All-New-Remote-streaming-player/dp/B079QH9GG7) to connect to their devices on the go. It would also be nice to have this package be on the Amazon store.

From [the forum](https://forum.tailscale.com/t/request-firetv-client/535).

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_37qtt)

**Comment by bradfitz** [comment] 2021-03-29 19:52
We're already in the F-Droid store.

**Comment by bradfitz** [comment] 2021-03-29 19:52
Ah, you noticed that.

What's FireTV require? Is this about putting the F-Droid package in their app store?

**Comment by Xe** [comment] 2021-03-29 19:54
I think it would involve that, but we may want to test it with an actual FireTV device to ensure that Tailscale works with a remote.

**Comment by ElGordito** [comment] 2021-03-29 21:29
Is the F-Droid version the same as I pulled off of my Android phone?  I tried the one from my phone, it installed but would not run. Just blanked the screen for a second.

I will try the F-Droid one and report back what happens.

**Comment by bradfitz** [comment] 2021-03-30 02:28
The F-Droid one is the one without Google stuff. The F-Droid one will run everywhere. The Google one requires various Google services.

**Comment by ElGordito** [comment] 2021-03-30 03:42
I replied on the forum should I have replied here?  I can copy it here if it is more appropriate. Please let me know.

**Comment by bradfitz** [comment] 2021-03-30 03:58
@ElGordito wrote at https://forum.tailscale.com/t/request-firetv-client/535/7 ...

> Alright, I have some great news and some ok news.
>
> First the great news: It works! The F-Droid version allows me to connect and participate in the VPN mesh network with my FireTV 4k Stick, yay!
>
> Now for the ok news. It appears none of the buttons are selected by default signing up or using, so the remote will not select the button and I cannot navigate to the button using the d-pad. I was able to get past this by installing the mouse toggle app, allowing my remote to emulate a mouse cursor and select the buttons.
>
> Obviously, not ideal, but workable. :slight_smile:

@eliasnaur, the docs on support those events are:

https://developer.amazon.com/docs/fire-tv/remote-input.html

But does Gio support focus on widgets?

**Comment by eliasnaur** [comment] 2021-03-30 06:46
Gio doesn't, but shouldn't be too hard to add.

**Comment by buxel** [comment] 2021-06-16 11:45
Is there an update on this? I just tried the latest f-droid app (v1.8.6) and it just shows a blank screen.
I restarted & deleted cache several times.

**Comment by eliasnaur** [comment] 2021-06-16 11:56
I believe the controls will be fixed or close to fixed by #1004. I'm not sure what makes Shield TV show a blank screen, but the fix for #1008/#1035 is likely to help here as well.

**Comment by buxel** [comment] 2021-06-16 12:34
Thank you for the quick response. Your reaction time is just as pleasant as the overall UX of tailscale 😉 
If it is any help, i can try to pull logs from my shield tv. I just have to figure out how to do it remotely.

**Comment by eliasnaur** [comment] 2021-06-16 12:36
Logs would definitely help. With a bit of luck I can tell whether your issue is a duplicate of #1008.

**Comment by buxel** [comment] 2021-06-16 14:56
Here we go! I used grep because my attempts at logcat filtering either gave me everything or nothing. Is there a better way?

```
> adb logcat | grep tailscale

06-16 16:50:01.661  3712  7420 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.tailscale.ipn cmp=com.tailscale.ipn/org.gioui.GioActivity} from uid 1000
06-16 16:50:01.680  3712  3800 I WindowManager: WindowState() - found Launcher @ mAppToken:AppWindowToken{34e8940 token=Token{1b18cc3 ActivityRecord{6a63072 u0 com.tailscale.ipn/org.gioui.GioActivity t6114}}}
06-16 16:50:01.694  3712  3752 I ActivityManager: Start proc 26917:com.tailscale.ipn/u0a48 for activity com.tailscale.ipn/org.gioui.GioActivity
06-16 16:50:01.703 26917 26917 E m.tailscale.ip: Not starting debugger since process cannot load the jdwp agent.
06-16 16:50:01.800  3712  7420 I ActivityManager: Process com.tailscale.ipn (pid 26917) has died: fore TOP 
06-16 16:50:01.819  3712  3752 I ActivityManager: Start proc 26938:com.tailscale.ipn/u0a48 for activity com.tailscale.ipn/org.gioui.GioActivity
06-16 16:50:01.826 26938 26938 E m.tailscale.ip: Not starting debugger since process cannot load the jdwp agent.
06-16 16:50:01.896  3712  4568 I ActivityManager: Process com.tailscale.ipn (pid 26938) has died: fore TOP 
06-16 16:50:01.910  3712  3752 I ActivityManager: Start proc 26962:com.tailscale.ipn/u0a48 for activity com.tailscale.ipn/org.gioui.GioActivity
(.... a lot more of that)
```

**Comment by ElGordito** [comment] 2021-06-16 15:11
Originally I had the blank screen. Once I moved to the F-Droid version it came up great.  Unfortunately, I have to use a mouse emulator to click the buttons.  It would be great if the login button (and any other necessity), when first installed and then the on-off button would be the focus, so just hitting select on the remote would control it.

As an additional feature, it would be nice if it had (maybe it already does, I have not looked) an interface for other apps to control its on-off status.  Like from Kodi, Plex, or Jellyfin.

If you need a FireTV stick to make any of this happen, lets talk. :-)

**Comment by eliasnaur** [comment] 2021-06-16 15:51
Piping `adb logcat` is the best way. You can restrict it to just Tailscale output with `adb logcat -s com.tailscale.ipn:*` if you like. Judging from your description, the error is not a crash and so should appear in the filtered logs.

Thank you for your offer; I'd like to see how far #1004 gets us before a physical device is needed. Even so, [the Android emulator](https://stackoverflow.com/questions/34768013/how-to-create-an-amazon-fire-tv-virtual-device) probably suffices.

**Comment by bradfitz** [comment] 2021-12-15 05:58
I ordered a "Fire TV Stick 4K Max" with the goal of making its remote work.

/cc @DentonGentry

**Comment by ElGordito** [comment] 2021-12-15 15:27
> I ordered a "Fire TV Stick 4K Max" with the goal of making its remote work.

Awesome news!  Thank you!

**Comment by bradfitz** [comment] 2021-12-20 04:23
Watching adb logs, pressing down on the remote ...

```
12-19 20:20:36.736   498   628 D AmzPhoneWindowManager: is 20 in key list = false
12-19 20:20:36.739   498   628 D AmzPhoneWindowManager: interceptUnhandledKey: 20
12-19 20:20:36.794   498   628 D AmzPhoneWindowManager: is 20 in key list = false
12-19 20:20:36.795   498   628 D AmzPhoneWindowManager: interceptUnhandledKey: 20
12-19 20:20:36.795   498   628 D AmzPhoneWindowManager: is 20 in key list = false
```

up in 19, down 20, left 21, right 22, middle button is 23 (the unlabeled circle button on the remote in the middle of the arrow keys)

**Comment by bradfitz** [comment] 2021-12-20 04:45
Dev notes to myself primarily, but may be useful to others:

* Enable ADB-over-LAN on Fire Stick
* One-time: `adb connect 10.2.200.213:5555`

Each edit/run cycle:

```
$ make tailscale-fdroid.apk
$ adb install -r tailscale-fdroid.apk
$ scp tsdev:src/github.com/tailscale/android/tailscale-fdroid.apk . && adb install -r tailscale-fdroid.apk 
$ adb shell am start -n com.tailscale.ipn/com.tailscale.ipn.IPNActivity
```

**Comment by bradfitz** [comment] 2021-12-20 04:49
Dropped some logging in `gio`. The arrow keys seem to be all mapped to events, but not the enter key:

```
12-19 20:49:00.785 32666 32666 I com.tailscale.ipn: XXX keyCode=19, r=0, t=18471409 => converted to "↑"
12-19 20:49:01.087 32666 32666 I com.tailscale.ipn: XXX keyCode=21, r=0, t=18471711 => converted to "←"
12-19 20:49:01.343 32666 32666 I com.tailscale.ipn: XXX keyCode=22, r=0, t=18471967 => converted to "→"
12-19 20:49:01.621 32666 32666 I com.tailscale.ipn: XXX keyCode=20, r=0, t=18472245 => converted to "↓"
12-19 20:49:02.143 32666 32666 I com.tailscale.ipn: XXX keyCode=23, r=0, t=18472767 => unknown
```

**Comment by bradfitz** [comment] 2021-12-20 06:02
Well, I got the Fire TV Stick 4K's main button working, in a kinda manual way for now. Ideally Gio would handle it all, @eliasnaur, but for now I did it a bit manually, first teaching Gio about the button:

```diff
diff --git a/app/os_android.go b/app/os_android.go
index b7042f59..74435685 100644
--- a/app/os_android.go
+++ b/app/os_android.go
@@ -908,6 +909,10 @@ func convertKeyCode(code C.jint) (string, bool) {
                n = key.NameEnter
        case C.AKEYCODE_ENTER:
                n = key.NameEnter
+       case 23:
+               n = key.NameEnter // firestick circle unlabeled button in arrow wheel
        default:
                return "", false
        }
```

(I used `NameEnter` hoping it'd work by default, but the buttons don't have focus, so that alone wasn't enough)

Instead if then wired it up manually:

```diff
diff --git a/cmd/tailscale/main.go b/cmd/tailscale/main.go
index 59066cd..64890e7 100644
--- a/cmd/tailscale/main.go
+++ b/cmd/tailscale/main.go
@@ -23,6 +23,7 @@ import (
        "unsafe"
 
        "gioui.org/app"
+       "gioui.org/io/key"
        "gioui.org/io/system"
        "gioui.org/layout"
        "gioui.org/op"
@@ -896,7 +897,16 @@ func (a *App) runUI() error {
                case <-a.invalidates:
                        w.Invalidate()
                case e := <-w.Events():
+                       log.Printf("XXX app event: %T %#v", e, e)
                        switch e := e.(type) {
+                       case key.Event:
+                               switch e.Name {
+                               case key.NameEnter:
+                                       if ui.onEnter() {
+                                               // e.Cancel = true
+                                               w.Invalidate()
+                                       }
+                               }
                        case app.ViewEvent:
                                deleteActivityRef()
                                view := jni.Object(e.View)
diff --git a/cmd/tailscale/ui.go b/cmd/tailscale/ui.go
index d360bfe..4ac5990 100644
--- a/cmd/tailscale/ui.go
+++ b/cmd/tailscale/ui.go
@@ -251,6 +251,22 @@ func (ui *UI) onBack() bool {
        return false
 }
 
+func (ui *UI) onEnter() bool {
+       switch {
+       case ui.intro.show:
+               ui.dismissIntro()
+               return true
+       }
+       ui.webSignin.Click()
+       return true
+}
+
+func (ui *UI) dismissIntro() {
+       ui.store.WriteBool(keyShowIntro, false)
+       ui.intro.show = false
+}
+
 func (ui *UI) layout(gtx layout.Context, sysIns system.Insets, state *clientState) []UIEvent {
        var events []UIEvent
        if ui.enabled.Changed() {
@@ -446,8 +462,7 @@ func (ui *UI) layout(gtx layout.Context, sysIns system.Insets, state *clientStat
        // "Get started".
        if ui.intro.show {
                if ui.intro.start.Clicked() {
-                       ui.store.WriteBool(keyShowIntro, false)
-                       ui.intro.show = false
+                       ui.dismissIntro()
                }
                ui.layoutIntro(gtx, sysIns)
        }
```

But that just plops you here:

![IMG_5412](https://user-images.githubusercontent.com/2621/146718806-f5f75d4e-f7c4-4f6c-90eb-fd8cffbd094b.jpeg)

The Fire Stick remote kiiiinda work in that webview. But not really. I can't move down past the text box with the remote.

But sending some tabs works:

```
crow5k:~ $ adb shell input keyevent 61
crow5k:~ $ adb shell input keyevent 61
```

Then I can press the round button on the remote and get to Google sign-in, so that means I can map the arrow keys to Tab and Shift-Tab and at least make that sign-in view work.

But really... who wants to log in on their TV? Let's just show a QR code there and let them log in on their phones instead.

That'll get things signed in, but presumably the menu won't work (e.g. selecting an exit node) or even the on/off toggle.

@eliasnaur, are there Gio APIs for focus navigation?

**Comment by bradfitz** [comment] 2021-12-20 19:58
Did a prototype of the QR code login at https://github.com/tailscale/tailscale-android/pull/27 which lets me get logged in to Tailscale on my Fire Stick 4K with just the remote.

But then I can't turn it on/off or select exit nodes, etc. 

/cc @eliasnaur

**Comment by karnauskas** [comment] 2021-12-20 22:02
IMHO there's some xml properties for defining what's selected after clicking up/down with dpad or selected element styling. However, I felt lost with gioui implementation.

**Comment by bradfitz** [comment] 2021-12-22 05:26
So I guess Gio supports the concept of focus (based on the Kitchen wasm example at https://gioui.org/) but doesn't do any sort of highlighting that a widget has focus?

I could maintain mappings of which Gio widget gets focus next based on dpad + current focus (the UI is small enough to do it all by hand), but the user experience wouldn't be great if they couldn't even see where focus is.

Oh, I guess I could use "[Widget-local parameters](https://pkg.go.dev/gioui.org@v0.0.0-20211221091320-11bb86166a5b/widget/material)" to make focused elements a different color or something? But again pretty manual.

**Comment by eliasnaur** [comment] 2021-12-26 08:49
There is limited focus support for text fields, and there is [visual feedback for "mouse focus"/hover](https://git.sr.ht/~eliasnaur/gio/tree/main/item/widget/material/button.go#L171). There is even support for a11y focus for any interactive widget. The right fix is to add keyboard focus support to non-text fields, which I'm planning to do.

**Comment by say4n** [comment] 2022-01-17 09:21
Hi folks, any updates on this issue?

**Comment by DentonGentry** [comment] 2022-01-17 09:25
I promise we will update the bug report when there is something available.

**Comment by ohhai-kthxbai** [comment] 2022-02-12 16:22
Hello. Is this likely to get any attention soon please? I expect tailscale to be very popular with the AndroidTV community once this is working. Sharing access to self-hosted media servers (e.g. plex/jellyfin) is just the kind of problem that tailscale solves nicely. Thanks for you work so far.

**Comment by DentonGentry** [comment] 2022-02-12 16:26
I promise we will update the bug report when there is something available.

We understand that people want this. However the list of things which people want is long, and cannot all be simultaneously worked on.

**Comment by tmm1** [comment] 2022-02-16 22:37
Would love to see some progress here. Here's a guide I found floating around, and the number of steps involved is pretty intense: https://www.reddit.com/r/fireTV/comments/r5fiom/guide_on_how_to_get_tailscale_working_with_a_fire/

**Comment by tmm1** [comment] 2022-02-16 23:28
> The right fix is to add keyboard focus support to non-text fields, which I'm planning to do.

@eliasnaur Is there a gio issue tracking this work? I can poke around and help, but will need some pointers. It sounds like you're saying text fields already have keyboard focus support, and that needs to be extended to support non-text fields. If someone can point me at the code to support focus on text fields maybe I can figure out how to expand from there.

**Comment by eliasnaur** [comment] 2022-02-17 18:16
Yes: focus work is https://gioui.org/issue/195. I just completed IME support for Gio, and I plan to start working on focus support this week.

**Closed** 2022-03-16 03:02 UTC
Labels: packaging, OS-android, L1 Very few, P3 Can't get started, T0 New feature

**Comment by DentonGentry** [comment] 2022-04-02 21:05
The 1.23.152 build currently in the Open Testing track adds Android TV support, and it is expected to be in the 1.24 general release. To get early access you'll need to join the [open testing track](https://play.google.com/apps/testing/com.tailscale.ipn).

For me at least, even being part of the Open Testing track still didn't show the app as available when searching for "tailscale" on my Google TV device. However in the Play Store app on my phone after installing 1.23.152, it said the app was available for some of my other devices and showed the Google TV in that list. It included an Install button, and a few minutes later the Google TV installed the app.
