### ISSUE TITLE
Black screen or white screen on Android 7.1 stb

### ISSUE THREAD

**Issue by paul19920801** [tailscale/tailscale#4764] opened 2022-05-31 22:20 UTC
### What is the issue?

Hi 

I have an Andriod MXQ-4k box running leelbox firmware which is based on Andriod 7.1. 

I downloaded Tailscale, and expected it to work however I was met with  a blank screen, 
If I force close it, and reopen it, then I get a white screen. 

I tried both the Google Play, and F-Droid versions, and none of them work. 

If anyone can advise on what can be done, it would be much appreciated. 

Let me know what I need to submit here

Thanks

### Steps to reproduce

1.Download Tailscale from the Google Play Store. 
2.Open the file once it's finished downloading. 
3.Tailscale won't open beyond a black or white screen. 

### OS

Android

### OS version

Android 7.1.2

### Tailscale version

1.25.35

**Comment by DentonGentry** [comment] 2022-05-31 22:26
This is almost certainly the same issue as https://github.com/tailscale/tailscale/issues/4332

If you were able to at least login and the Android TV device got a Tailscale IP address assigned, visible in https://login.tailscale.com/admin/machines, we can consult telemetry to confirm it.

**Comment by paul19920801** [comment] 2022-06-01 05:40
> This is almost certainly the same issue as #4332
> 
> If you were able to at least login and the Android TV device got a Tailscale IP address assigned, visible in https://login.tailscale.com/admin/machines, we can consult telemetry to confirm it.

Unfortunately wasn't even able to login. Didn't even get that far.

**Comment by DentonGentry** [comment] 2022-06-01 15:48
If you are comfortable using adb and a USB cable, you can use: `adb logcat -s "com.tailscale.ipn:*"`
while starting the Tailscale app. The string to search for in all that output is "fatal error: glGetError: 0x501"
If you see that, then this issue is the one tracked in https://github.com/tailscale/tailscale/issues/4332

If you see a different crash or traceback then it is a different problem that we don't currently know about.

**Comment by DentonGentry** [comment] 2022-06-10 02:43
Duplicate of https://github.com/tailscale/tailscale/issues/4332

**Closed by DentonGentry** 2022-06-10 02:43 UTC
Labels: needs-triage, bug

**Comment by drogers0** [comment] 2026-07-28 18:17
@paul19920801 — for anyone still landing here with an MXQ-class box, this is solvable now, and the cause was never Android 7.1 as such.

The GLES 2.0 crash was fixed upstream by the Gio → Compose rewrite — Compose has no GLES 3 requirement and renders fine on a Mali-450. But `minSdkVersion` went 22 → 26 in `bf0e56469f`, one commit later, so no release ever shipped both. Android 7.1 (API 25) sits below that floor just like 5.1 does, which is why this thread and the Android 5.1 ones have the same root cause despite four API levels between them.

I've backported the Compose app to API 22, built from upstream source: https://github.com/drogers0/tailscale-firetv-fireos5

MXQ / M8S boxes on Amlogic S805 / S812 with Mali-450 are squarely the target — API 22–25 with an `armeabi-v7a` slot. Model-by-model table: https://github.com/drogers0/tailscale-firetv-fireos5/blob/main/docs/DEVICES.md

Verified on 1.98.8 on a Fire TV Stick 2nd gen including exit-node routing; the Amlogic boxes are untested, so `scripts/device-check.sh <ip>:5555` will tell you where yours lands. Unofficial and debug-signed — see the README for the caveats.
