### ISSUE TITLE
Fire Stick TailScale WireGuard Performance Slow

### ISSUE THREAD

**Issue by wingcomm** [tailscale/tailscale#5470] opened 2022-08-27 23:37 UTC
### What is the issue?

It seems the Tailscale/Wireguard is relatively slow on the Amazon Fire Stick 4k Max. Using the same exit node and the same Speed Test servers, I get 150-200Mbps from an iPhone and a M1 Max MacBook Pro on Wi-Fi, but I only get around 15-22 Mbps on the firestick. With the Exit Node set to "none" on the Fire Stick, I get around 200-220 Mbps. Is Tailscale using the WireGuard Go module or the Kernel module on Android?

I know the CPU on these sticks is small, but it still seems a tad slow?

### Steps to reproduce

Run a speedtest without an exit node conifgured.
Choose an exit node and re-run the speedtest. 

### OS

Other

### OS version

FIreOS 7.2.9.2

### Tailscale version

1.29.72-tb905db7a5-g9e6ef85d269 (117)

**Comment by DentonGentry** [comment] 2022-08-28 00:00
Fire Stick 4k uses a MediaTek MT8696, which is a 64 bit ARM but very likely compiled for ARM32 to reduce code size and memory. This is likely https://github.com/tailscale/tailscale/issues/414, there there is no optimized cryptography implementation for the relevant ciphers for ARM32.

**Comment by DentonGentry** [comment] 2022-08-28 06:18
Closing as a duplicate of https://github.com/tailscale/tailscale/issues/414

**Closed by DentonGentry** 2022-08-28 06:18 UTC
Labels: needs-triage, bug

**Comment by ashishjullia** [comment] 2022-10-23 13:46
Any solution to this?
