### ISSUE TITLE
Access Controls: When "acls" define a "proto" the "tests" block will fail.

### ISSUE THREAD

**Issue by DavidPesticcio** [tailscale/tailscale#5212] opened 2022-07-28 18:06 UTC
### What is the issue?

When using "acls" define a "proto" the "tests" block will fail to save with the following error:

```
Error: test(s) failed
test(s) failed for user: host1
  address "host2:443": want: Accept, got: Drop

```

### Steps to reproduce

Using the below configuration will cause error:

```
// Configuration example snippet that fails with error upon save:

{
	"hosts": {
		"host1": "100.117.222.1",
		"host2": "100.117.222.2",
	},

	"acls": [
		{
			"action": "accept",
			"src":    ["host1"],
			"proto":  "tcp",
			"dst": ["host2:443"],
		},
	],

	"tests": [
		{
			"src":    "host1",
			"accept": ["host2:443"],
			"deny":   ["host2:22"],
		},
	],
}

```

### Are there any recent changes that introduced the issue?

Unknown.

### OS

Other

### OS version

N/A

### Tailscale version

N/A

**Comment by mihaip** [comment] 2022-10-24 21:19
Duplicate of #3561

**Closed by mihaip** 2022-10-24 21:19 UTC
Labels: L2 Few, P2 Aggravating, T5 Usability, bug
