### ISSUE TITLE
FR: (Email) notification for key expiry

### ISSUE THREAD

**Issue by parkr** [tailscale/tailscale#4688] opened 2022-05-16 17:00 UTC
### What are you trying to do?

I am trying to keep my devices authorized to access my tailnet without issuing a key that doesn't expire.

### How should we solve this?

I'd love to receive some kind of notification (email is best for me) that says "Hey, your machine X is about to expire. Run `sudo tailscale renew` to reauthenticate with tailscale and renew the machine's key." I would also like to see the Tailscale admin panel more prominently indicate key expiry rather than a grey box:

<img width="213" alt="Screen Shot 2022-05-16 at 9 53 40 AM" src="https://user-images.githubusercontent.com/237985/168645039-3cac3e8d-2d50-4950-9b14-c89d86e296e2.png">

### What is the impact of not solving this?

I have twice had issues where machines seemed to "drop off". Automated work started failing (only some of which is monitored), and it took me a few tries to figure out that it was tailscale and not iptables/DNS issues/etc. Since Tailscale is rock solid, the thought hadn't occurred to me that I needed to renew my Tailscale authorization for the device.

### Anything else?

Thank you for Tailscale!

**Comment by DentonGentry** [comment] 2022-05-16 17:01
Duplicate of https://github.com/tailscale/tailscale/issues/1261

**Closed by DentonGentry** 2022-05-16 17:01 UTC
Labels: needs-triage, fr
