### ISSUE TITLE
Error in NSIS installer (start after setup) for user with insufficient rights

### ISSUE THREAD

**Issue by OwnageIsMagic** [tailscale/tailscale#4227] opened 2022-03-19 18:25 UTC
### What is the issue?

After setup completed `tailscaled.exe` is running, while `tailscale-ipn.exe` is not.
`Failed to start GUI: fork/exec F:\Program Files (x86)\Tailscale IPN\tailscale-ipn.exe: The parameter is incorrect.` in log. The path is correct.
<details>
<summary>Full log</summary>

```
InitDriverSetup: 
Output folder: F:\Program Files (x86)\Tailscale IPN
Extract: tailscale-ipn-new.exe... 100%
MakeDead: 124.1
Uninstalling service
2022/03/19 21:03:43 registry.OpenKey(SOFTWARE\Tailscale IPN): The system cannot find the file specified.
Uninstalling service... (via v1.22.2-t60b671955-gecc5d9846: ["F:\\Program Files (x86)\\Tailscale IPN/tailscale-ipn-new.exe" "/uninstall"])
Closing Tailscale GUI process(es).
No old processes running.
Deleting Tailscale executables.
Removing Tailscale from PATH...
Path was: `<...snip...>;F:\Program Files (x86)\dotnet\`
Path doesn't need changes.
No wintun driver uninstall needed; prior wintun.dll not present: The specified module could not be found.
UninstallService: 0
Rename: tailscale-ipn-new.exe->tailscale-ipn.exe
Windows major version: 10
Extract: tailscale.exe... 100%
Extract: tailscaled.exe... 100%
Extract: wintun.dll... 100%
Created uninstaller: F:\Program Files (x86)\Tailscale IPN\Uninstall-Tailscale.exe
Create shortcut: F:\ProgramData\Microsoft\Windows\Start Menu\Programs\Tailscale.lnk
Create shortcut: F:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\Tailscale.lnk
Running tailscale-ipn.exe /install
Running Tailscale /install (v1.22.2-t60b671955-gecc5d9846: ["F:\\Program Files (x86)\\Tailscale IPN\\tailscale-ipn.exe" "/install"])
Installing service...
Adding Tailscale to PATH...
Path was: `<...snip...>;F:\Program Files (x86)\dotnet\`
Updating Path to `<...snip...>;F:\Program Files (x86)\dotnet\;%PROGRAMFILES(X86)%\Tailscale IPN`
Running GUI as logged in user...
Found desktop process with pid of 13568
Failed to start GUI: fork/exec F:\Program Files (x86)\Tailscale IPN\tailscale-ipn.exe: The parameter is incorrect.
Completed
```

</details>

### OS

Windows

### OS version

10

### Tailscale version

1.22.2

**Comment by bradfitz** [comment] 2022-03-19 19:20
cc @dblohm7 for installer pains

**Comment by DentonGentry** [comment] 2022-03-27 15:59
Likely something about installing on `F:\`and not `C:\`

**Comment by dblohm7** [comment] 2022-04-05 17:52
@OwnageIsMagic things work fine if I install in a test VM on a blank `F:` volume, where the installer has to create `F:\Program Files (x86)` itself. I assume that in your case that directory probably already existed before you ran the Tailscale installer? I'm wondering if perhaps there is some kind of permissions issue with that directory.

If you're comfortable doing so, it would be useful to see the output from entering the following in a command prompt:
`icacls "F:\Program Files (x86)"`

**Comment by OwnageIsMagic** [comment] 2022-04-05 22:52
<details><summary>on the problematic pc</summary>

```
F:\>chcp 65001
Active code page: 65001
F:\>icacls "F:\Program Files (x86)"
F:\Program Files (x86) NT SERVICE\TrustedInstaller:(F)
                       NT SERVICE\TrustedInstaller:(CI)(IO)(F)
                       NT AUTHORITY\СИСТЕМА:(M)
                       NT AUTHORITY\СИСТЕМА:(OI)(CI)(IO)(F)
                       BUILTIN\Администраторы:(M)
                       BUILTIN\Администраторы:(OI)(CI)(IO)(F)
                       BUILTIN\Пользователи:(RX)
                       BUILTIN\Пользователи:(OI)(CI)(IO)(GR,GE)
                       СОЗДАТЕЛЬ-ВЛАДЕЛЕЦ:(OI)(CI)(IO)(F)
                       ЦЕНТР ПАКЕТОВ ПРИЛОЖЕНИЙ\ВСЕ ПАКЕТЫ ПРИЛОЖЕНИЙ:(RX)
                       ЦЕНТР ПАКЕТОВ ПРИЛОЖЕНИЙ\ВСЕ ПАКЕТЫ ПРИЛОЖЕНИЙ:(OI)(CI)(IO)(GR,GE)
                       ЦЕНТР ПАКЕТОВ ПРИЛОЖЕНИЙ\ВСЕ ОГРАНИЧЕННЫЕ ПАКЕТЫ ПРИЛОЖЕНИЙ:(RX)
                       ЦЕНТР ПАКЕТОВ ПРИЛОЖЕНИЙ\ВСЕ ОГРАНИЧЕННЫЕ ПАКЕТЫ ПРИЛОЖЕНИЙ:(OI)(CI)(IO)(GR,GE)

Successfully processed 1 files; Failed processing 0 files
```

</details>

<details><summary>on another pc</summary>

```
C:\>icacls "c:\Program Files (x86)"
c:\Program Files (x86) NT SERVICE\TrustedInstaller:(F)
                       NT SERVICE\TrustedInstaller:(CI)(IO)(F)
                       NT AUTHORITY\СИСТЕМА:(M)
                       NT AUTHORITY\СИСТЕМА:(OI)(CI)(IO)(F)
                       BUILTIN\Администраторы:(M)
                       BUILTIN\Администраторы:(OI)(CI)(IO)(F)
                       BUILTIN\Пользователи:(RX)
                       BUILTIN\Пользователи:(OI)(CI)(IO)(GR,GE)
                       СОЗДАТЕЛЬ-ВЛАДЕЛЕЦ:(OI)(CI)(IO)(F)
                       ЦЕНТР ПАКЕТОВ ПРИЛОЖЕНИЙ\ВСЕ ПАКЕТЫ ПРИЛОЖЕНИЙ:(RX)
                       ЦЕНТР ПАКЕТОВ ПРИЛОЖЕНИЙ\ВСЕ ПАКЕТЫ ПРИЛОЖЕНИЙ:(OI)(CI)(IO)(GR,GE)
                       ЦЕНТР ПАКЕТОВ ПРИЛОЖЕНИЙ\ВСЕ ОГРАНИЧЕННЫЕ ПАКЕТЫ ПРИЛОЖЕНИЙ:(RX)
                       ЦЕНТР ПАКЕТОВ ПРИЛОЖЕНИЙ\ВСЕ ОГРАНИЧЕННЫЕ ПАКЕТЫ ПРИЛОЖЕНИЙ:(OI)(CI)(IO)(GR,GE)

Successfully processed 1 files; Failed processing 0 files
```

</details>

The problem was only autostarting `tailscale-ipn.exe`, `tailscaled.exe` started without problems. Manual start also ok.
But at least it reproducable

```
InitDriverSetup: 
Output folder: F:\Program Files (x86)\Tailscale IPN
Extract: tailscale-ipn-new.exe... 100%
MakeDead: 124.1
Uninstalling service
Uninstalling service... (via v1.22.2-t60b671955-gecc5d9846: ["F:\\Program Files (x86)\\Tailscale IPN/tailscale-ipn-new.exe" "/uninstall"])
Closing Tailscale GUI process(es).
No old processes running.
Deleting Tailscale executables.
Removing Tailscale from PATH...
Path was: `<...snip...>F:\Program Files (x86)\dotnet\;F:\Program Files (x86)\Tailscale IPN;F:\Program Files (x86)\NVIDIA Corporation\PhysX\Common`
Updating Path to `<...snip...>F:\Program Files (x86)\dotnet\;F:\Program Files (x86)\Tailscale IPN;F:\Program Files (x86)\NVIDIA Corporation\PhysX\Common`
Removing wintun driver...
Removed orphaned adapter "Tailscale"
Removing driver oem88.inf
Uninstall: <nil>
UninstallService: 0
Delete file: F:\ProgramData\Microsoft\Windows\Start Menu\Programs\Tailscale.lnk
Delete file: F:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\Tailscale.lnk
Delete file: F:\Program Files (x86)\Tailscale IPN\wintun.dll
Delete file: F:\Program Files (x86)\Tailscale IPN\tailscale.exe
Delete file: F:\Program Files (x86)\Tailscale IPN\Uninstall-Tailscale.exe
Rename: tailscale-ipn-new.exe->tailscale-ipn.exe
Windows major version: 10
Extract: tailscale.exe... 100%
Extract: tailscaled.exe... 100%
Extract: wintun.dll... 100%
Created uninstaller: F:\Program Files (x86)\Tailscale IPN\Uninstall-Tailscale.exe
Create shortcut: F:\ProgramData\Microsoft\Windows\Start Menu\Programs\Tailscale.lnk
Create shortcut: F:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\Tailscale.lnk
Running tailscale-ipn.exe /install
Running Tailscale /install (v1.22.2-t60b671955-gecc5d9846: ["F:\\Program Files (x86)\\Tailscale IPN\\tailscale-ipn.exe" "/install"])
Installing service...
Adding Tailscale to PATH...
Path was: `<...snip...>F:\Program Files (x86)\dotnet\;F:\Program Files (x86)\Tailscale IPN;F:\Program Files (x86)\NVIDIA Corporation\PhysX\Common`
Path doesn't need changes.
Running GUI as logged in user...
Found desktop process with pid of 7760
Failed to start GUI: fork/exec F:\Program Files (x86)\Tailscale IPN\tailscale-ipn.exe: The parameter is incorrect.
Completed
```

**Comment by OwnageIsMagic** [comment] 2022-04-06 11:16
I think it related to starting as another user and incorrect parameter is not a path.
Or my unelevated account d.oesn't have enough rihts

**Comment by dblohm7** [comment] 2022-04-06 17:24
Yes, I do think that it is worth looking more closely into your non-Admin rights.

**Comment by DentonGentry** [comment] 2023-02-13 00:42
To me this looks like https://github.com/tailscale/tailscale/issues/1904, which was resolved by the MSI installer handling %PATH% correctly.

Duplicate of https://github.com/tailscale/tailscale/issues/1904

**Closed by DentonGentry** 2023-02-13 00:42 UTC
Labels: OS-windows, L1 Very few, P3 Can't get started, T8 Crash, bug
