### ISSUE TITLE
iOS VPN for tailscale keeps activating on its own

### ISSUE THREAD

**Issue by chocolatem00se** [tailscale/tailscale#6253] opened 2022-11-09 22:04 UTC
### What is the issue?

It doesn't matter if you deactivate VPN in the settings menu in ios or by deactivating it in the tailscale app, the connection keeps turning on by itself.

### Steps to reproduce

Self-explanatory, but as a temporary remedy I found that logging out of tailscale on iOS is the only way to keep the connection from reactivating.

### OS

iOS

### OS version

16.1

### Tailscale version

1.32.2

**Comment by mihaip** [comment] 2022-11-10 17:37
Duplicate of #539

**Closed by mihaip** 2022-11-10 17:37 UTC
Labels: needs-triage, bug
