### ISSUE TITLE
FR: Multicast (aka. Bonjour) across Tailnet?

### ISSUE THREAD

**Issue by elvisimprsntr** [tailscale/tailscale#8884] opened 2023-08-15 04:21 UTC
### What are you trying to do?

BACKGROUND

I currently use Tailscale between two pfSense sites (one is behind double NAT) to remotely manage my Father's network and to allow remote backups to my TrueNAS servers.  

My Father is 93 years old and sometimes has trouble navigating the menus on the Apple TV to watch baseball (MLB.TV) and Hockey (formally NHL.TV, now ESPN has made the menus even more complicated)

MY GOALS

My goal would be to allow remote control of his Apple TV, turn it on, navigate menus, and start streaming the games for him.  Tailscale itself might not be able to provided that capability, but if the Bonjour discovery services could be advertised across Tailnet, it might just be possible.  It might require some additional pfSense firewall rules to advertise Bonjour services across Tailnet.  Since I already have Tailscale installed on pfSense at both locations, it might not even be necessary to install Tailscale on his Apple TV.  Or maybe it does need to be installed on his Apple TV for it to be remotely discoverable. 

1. I could use Quicktime on my M1 Macbook to screen record his Apple TV so I can see the output of his Apple TV
2. Then use my iPhone with the Remote app to navigate his Apple TV and start the game for him.  

Is this technically possible? 

### How should we solve this?

Can Tailscale support Multicast over Tailnet?

### What is the impact of not solving this?

Not able to remote control ATV or other discoverable Apple devices on remote Tailnet

**Comment by DentonGentry** [comment] 2023-08-24 05:56
Support of general purpose multicast would be some time in the future, we'd need to implement something very much like PIM Sparse Mode and Dense Mode. However handling of mDNS packets for Bonjour specifically is much more straightforward.

Duplicate of https://github.com/tailscale/tailscale/issues/1013

**Closed by DentonGentry** 2023-08-24 05:56 UTC
Labels: needs-triage, fr

**Comment by iSynthetixx** [comment] 2024-04-13 21:59
I'd pay a premium for this
