### ISSUE TITLE
Reverse DNS queries to 100.100.100.100 time out

### ISSUE THREAD

**Issue by tavianator** [tailscale/tailscale#4722] opened 2022-05-20 18:40 UTC
### What is the issue?

I set up tailscale on a FreeBSD machine.  Suddenly, ssh into that machine over the public internet started taking forever to connect.  I tracked it down to sshd performing a reverse DNS lookup which timed out.  For now I've worked around it with `UseDNS no` in `sshd_config`, but I'm reporting the issue anyway.

It's not a big deal for me on Linux because split DNS works.  But on FreeBSD I just have `nameserver 100.100.100.100` in `/etc/resolve.conf` so regular system reverse DNS queries (e.g. `getnameinfo()`) also time out.

### Steps to reproduce

I can reproduce directly like this:

```console
$ time drill -x $MY_IP @100.100.100.100 # FreeBSD
Error: error sending query: Could not send or receive, because of network error
drill -x $MY_IP @100.100.100.100  0.00s user 0.01s system 0% cpu 15.092 total
$ time dig -x $MY_IP @100.100.100.100 # Linux

; <<>> DiG 9.18.2 <<>> -x $MY_IP @100.100.100.100
;; global options: +cmd
;; connection timed out; no servers could be reached

dig -x $MY_IP @100.100.100.100  0.00s user 0.01s system 0% cpu 15.030 total
```

### OS

Linux, Other

### OS version

Arch Linux, FreeBSD 13.1-RELEASE

### Tailscale version

1.24.2

### Bug report

BUG-c4e4b6372b7c646441002f47d0b13e818dd3966cb7a216cda19e8b5308f7b517-20220520184002Z-6346e1494f0f52cf

**Comment by bradfitz** [comment] 2022-05-21 03:20
@twitchyliquid64, is this the same as #4686 as fixed by #4708?

**Comment by bradfitz** [comment] 2022-05-21 03:21
Oh, `drill` vs `dig`. Does `drill` only do TCP?

**Comment by DentonGentry** [comment] 2022-05-21 13:04
Just to make things more perplexing, on an OPNsense system running FreeBSD 12.1 the lookup is almost instantaneous:

```
root@OPNsense:~ # time drill -x 100.92.61.18 @100.100.100.100
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 21856
;; flags: qr aa rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; 18.61.92.100.in-addr.arpa.	IN	PTR

;; ANSWER SECTION:
18.61.92.100.in-addr.arpa.	600	IN	PTR	opnsense.example.com.beta.tailscale.net.

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 2 msec
;; SERVER: 100.100.100.100
;; WHEN: Sat May 21 06:02:35 2022
;; MSG SIZE  rcvd: 122
0.000u 0.006s 0:00.03 0.0%	0+0k 19+0io 15pf+0w
```

**Comment by bradfitz** [comment] 2022-05-21 13:46
@DentonGentry, what Tailscale version is that?

**Comment by DentonGentry** [comment] 2022-05-21 14:03
That was 1.22.2, but after updating to 1.24.2 it is still a ~1 msec lookup:

```
# time drill -x 100.92.61.18 @100.100.100.100
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 60090
;; flags: qr aa rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; 18.61.92.100.in-addr.arpa.	IN	PTR

;; ANSWER SECTION:
18.61.92.100.in-addr.arpa.	600	IN	PTR	opnsense.example.com.beta.tailscale.net.

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 1 msec
;; SERVER: 100.100.100.100
;; WHEN: Sat May 21 07:02:49 2022
;; MSG SIZE  rcvd: 122
0.000u 0.004s 0:00.01 0.0%	0+0k 0+0io 0pf+0w
```

**Comment by tavianator** [comment] 2022-05-21 14:07
It seems to be fast if the lookup succeeds.  Try it for an IP without a PTR record?

**Comment by DentonGentry** [comment] 2022-05-21 14:17
That takes 15 seconds to time out on the FreeBSD 12.1 system in the same way as the original report. I misunderstood the original report as meaning that PTR lookups of Tailscale IP addresses were not working on FreeBSD.

```
# time drill -x 1.2.3.4 @100.100.100.100
Error: error sending query: Could not send or receive, because of network error
0.003u 0.001s 0:15.05 0.0%	0+0k 0+0io 0pf+0w
```

So the issue is that Linux returns NXDOMAIN almost immediately but FreeBSD never returns a result.

**Comment by tavianator** [comment] 2022-05-21 15:51
They also time out on Linux if I explicitly query 100.100.100.100, it just doesn't affect the system resolver.  I'm not sure what happens on a Linux machine without systemd-resolved/split DNS.

**Comment by twitchyliquid64** [comment] 2022-05-21 16:49
What's your upstream resolver? What response do you get if you point your query directly at the upstream?

**Comment by tavianator** [comment] 2022-05-21 20:06
On the FreeBSD box it's our lab's recursive resolver.  Querying it directly gives `SERVFAIL`:

```console
$ drill -x 192.159.180.233 @129.97.75.10
;; ->>HEADER<<- opcode: QUERY, rcode: SERVFAIL, id: 53157
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; 233.180.159.192.in-addr.arpa.        IN      PTR

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 220 msec
;; SERVER: 129.97.75.10
;; WHEN: Sat May 21 16:01:08 2022
;; MSG SIZE  rcvd: 46
```

Interestingly, for me `1.2.3.4` gives `NXDOMAIN` quickly, but my home IP times out:

```console
$ drill -x 1.2.3.4 @100.100.100.100
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 10484
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0 
;; QUESTION SECTION:
;; 4.3.2.1.in-addr.arpa.        IN      PTR

;; ANSWER SECTION:

;; AUTHORITY SECTION:
1.in-addr.arpa. 3221    IN      SOA     ns.apnic.net. read-txt-record-of-zone-first-dns-admin.apnic.net. 19727 7200 1800 604800 3600

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 100.100.100.100
;; WHEN: Sat May 21 16:01:50 2022
;; MSG SIZE  rcvd: 126
$ drill -x 192.159.180.233 @100.100.100.100
Error: error sending query: Could not send or receive, because of network error
```

**Comment by mnordhoff** [comment] 2022-05-22 00:35
The authoritative servers for `233.180.159.192.in-addr.arpa.` don't work. They return `REFUSED`. They're probably misconfigured.

(`in-addr.arpa` and `ip6.arpa` are a mess.)

https://dnsviz.net/d/180.159.192.in-addr.arpa/YomFAA/dnssec/
https://dnsviz.net/d/233.180.159.192.in-addr.arpa/YomFGw/dnssec/

Maybe your upstream resolver is responding too slowly, or incorrectly; or it's responding correctly (with `SERVFAIL`) and Tailscale is dropping it for some reason.

**Comment by twitchyliquid64** [comment] 2022-05-22 05:12
I think the `SERVFAIL` is the smoking gun here. Tailscale does not forward that error, because its the DNS equivalent to a HTTP 500 (the server says its confused and cannot give a straight answer) and if you have other resolvers its possible they might be able to get a valid answer.

https://github.com/tailscale/tailscale/blob/fc5839864bfbd5bfed512cbb6f05e32894e93938/net/dns/resolver/forwarder.go#L535-L539

Do you only have one resolver configured? perhaps we want logic to forward that error if its the only resolver (and hence the best answer youll get).

I'm at a loss to explain why your upstream is reliably returning `SERVFAIL`, is it doing that for all reverse IPs? can you double-check its configuration to make sure its properly servicing reverse DNS?

**Comment by tavianator** [comment] 2022-05-22 14:49
I think my ISP just has something configured wrong.  `dig -x 192.159.180.233` gives `SERVFAIL` no matter where I try it from.

**Comment by tavianator** [comment] 2022-05-23 12:54
> I think the `SERVFAIL` is the smoking gun here. Tailscale does not forward that error, because its the DNS equivalent to a HTTP 500 (the server says its confused and cannot give a straight answer) and if you have other resolvers its possible they might be able to get a valid answer.

I don't know DNS too well but it seems weird to hang instead of pass on an error code.  Like, an HTTP proxy would forward the 500 error, why wouldn't a DNS server?

> Do you only have one resolver configured? perhaps we want logic to forward that error if its the only resolver (and hence the best answer youll get).

```
$ cat /etc/resolv.conf
# resolv.conf(5) file generated by tailscale
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100
search tavianator.gmail.com.beta.tailscale.net rcs.uwaterloo.ca
```

> I'm at a loss to explain why your upstream is reliably returning `SERVFAIL`, is it doing that for all reverse IPs? can you double-check its configuration to make sure its properly servicing reverse DNS?

No, normal reverse IP lookups seems to work.  Just my home IP is busted:

```console
$ dig -x 192.159.180.233 @1.1.1.1 | grep status
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 9591
$ dig -x 192.159.180.233 @8.8.8.8 | grep status
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 11987
$ dig -x 192.159.180.233 @9.9.9.9 | grep status
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 34940
```

**Comment by twitchyliquid64** [comment] 2022-06-03 21:44
The reason we don't pass on `SERVFAIL` is because if you have another resolver configured, its possible that when that query comes back, that query might have a successful answer.

That said, it probably makes sense to pass on the error if you only have one resolver configured.

**Comment by bradfitz** [comment] 2022-06-04 03:07
> That said, it probably makes sense to pass on the error if you only have one resolver configured.

SGTM.

And also can we reply with _something_ when all N of our upstreams have replied with something?

**Closed** 2022-07-05 17:22 UTC
Labels: L3 Some users, P2 Aggravating, T3 Performance/Debugging, dns, bug
