### ISSUE TITLE
Copyright year in generated files

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#6865] opened 2023-01-02 00:14 UTC
### What is the issue?

We have three decisions which individually are reasonable, but taken together result in an impossible situation:
1. The [go-generate CI test](https://github.com/tailscale/tailscale/blob/main/.github/workflows/go_generate.yml) checks that `go generate` is up to date.
1. [util/codegen](https://github.com/tailscale/tailscale/blob/692eac23adf62f979dddb5b9694d084142036f10/util/codegen/codegen.go#L108) uses time.Now().Year()
1. [Software copyright headers](https://matija.suklje.name/how-and-why-to-properly-write-copyright-statements-in-your-code) should not routinely update the year every year.

Right now the CI test fails because it wants all generated files to be updated for 2023.

### Proposal
Modify util/codegen to not include the year in the copyright header at all. It is [the practice at Microsoft now](https://github.com/dsccommunity/DFSDsc/issues/79) that software copyright headers do not include the year, so there is some precedent for it.

The change in the code generator will need to go in along with an update to all generated files to remove the year from their header.

Manually produced software can — and should — continue to include the year of creation in the header. This proposal is just pragmatic, about bots producing software.

[PR#6866](https://github.com/tailscale/tailscale/pull/6866) implements this proposal.

**Comment by bradfitz** [comment] 2023-01-03 04:39
@DentonGentry, leaving this open for now for, @willnorris, et al to figure out what we want to do here long-term (if anything).

**Comment by willnorris** [comment] 2023-01-03 18:21
Copyrights should just include the first year of publication and that's it.  No need to include a range that includes the current year.

**Comment by willnorris** [comment] 2023-01-03 18:22
(or optionally no year at all.  That's fine too, but less common)

**Comment by willnorris** [comment] 2023-01-03 18:26
for reference, here are the docs we published at Google years ago: https://opensource.google/documentation/reference/copyright.  Notably, current year is marked as optional... if I remember correctly, mainly so that teams that were already using current year didn't think that they **needed** to go remove it from all of their files.  Though if I remember correctly, we mostly recommended that the next time they would normally go bump the current year, to then take that opportunity to remove it.

**Comment by DentonGentry** [comment] 2023-01-03 18:36
> the first year of publication

I think we could get this by changing:
https://github.com/tailscale/tailscale/blob/91e64ca74ffb22cf5a32f5eeee60196b12aa1636/util/codegen/codegen.go#L305

from `y > year` to `y != 0 && y < year`.

This will result in one last regeneration of the existing generated files, but should not update them again.

**Comment by willnorris** [comment] 2023-01-11 05:57
Interestingly, Daniel just removed all years from file-level copyright headers in curl: https://daniel.haxx.se/blog/2023/01/08/copyright-without-years/

**Comment by willnorris** [comment] 2023-01-27 18:57
Okay, coming back around to this after having done some more reading (most of which is linked from [various comments in Daniel's post](https://daniel.haxx.se/blog/2023/01/08/copyright-without-years/)).  My current recommendation (and what I plan to do shortly barring any strong objection) is to:

- Update copyright line in all source files to read `Copyright (c) Tailscale Inc & AUTHORS`
    - remove the year entirely.  It's not necessary, has long been removed by a number of other large projects, and creates extra burden on downstream users that try to accurately reproduce copyright statements when there are many with varying years.
    - remove the "All rights reserved" which is not a standard part of the [US copyright office guidance](https://www.copyright.gov/title17/92chap4.html) and is confusing in the context of an open source license.
- keep the single year of first publication (2020) in the LICENSE file
- remove "All rights reserved." from LICENSE file for same reason as above, and because it's not part of the [standard BSD license text](https://opensource.org/licenses/BSD-3-Clause).
- Update file headers to use `SPDX-License-Identifier: BSD-3-Clause`. This is less ambiguous than the current "BSD-style license" we have today, and is better supported by lots of compliance related tooling.

**Closed** 2023-01-27 23:36 UTC
Labels: needs-triage, needs-decision, bug

**Comment by bradfitz** [comment] 2023-01-28 00:18
Hooray, thanks!
