### ISSUE TITLE
IOS & carrier use of CGNAT

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2717] opened 2021-08-26 22:02 UTC
The customer is unable to access the Tailscale connection from IOS Device (iPad)  when connected from LTE Network.

BUG-d9d25ccbc8524e639bceaca94c767383be5ed033e482259b347604cbecbd0c7b-20210826134200Z-f3380153dbb007ba

**From Customer:**
iPads are indeed both on cellular with T-Mobile 5G I’m not using a secondary VPN intentionally.  The tailscale client is showing it’s connected and updated but I’m not able to establish connections to other devices when outside my LAN. When on the LAN the tailscale IP connects fine from the iPads to the problematic devices. From outside the LAN I can connect from my mac to the target tailscale devices that the ipads can’t connect to so this appears to be an iOS-specific issue (it repros on both iPads)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3i7v5)

**Comment by clarkezone** [comment] 2021-08-28 01:34
Both iOS tablets have T-Mobile cellular accounts.

**Comment by clarkezone** [comment] 2021-08-28 11:33
Have a live repro right now.. sitting at SEA, tailscale connected, on LTE, cannot connect back to home systems.  If i teather to my tmobile cellphone or jump on wifi all good.

**Comment by clarkezone** [comment] 2021-10-31 16:13
@bradfitz any update on this?  I was out yesterday and reminded that I basically can’t access my tailnet from my phone.

**Comment by DentonGentry** [comment] 2022-10-30 13:12
In release 1.30.0 the iOS client switched to an adaptive strategy:

- if any other interface in the system is using a CGNAT address, like a mobile carrier for example, install all Tailscale routes as /32s to try to interoperate (this is what 1.26 and before did uncondititionally)
- otherwise, install a 100.64.0.0/10 route for the Tailscale interface. This attempts to avoid ERR_NETWORK_CHANGED glitches in web browsers as routes are added and removed.

I suspect this issue was a duplicate of https://github.com/tailscale/tailscale/issues/302 and hopefully resolved by the same fix. If not please reopen, or file a new issue.

**Closed by DentonGentry** 2022-10-30 13:12 UTC
Labels: connectivity, OS-ios, L1 Very few, P2 Aggravating, T5 Usability

**Comment by sapoepsilon** [comment] 2024-11-11 03:41
I still experience the same issue on Tmobile

**Comment by zaxlofful** [comment] 2026-06-15 05:31
I also have the same problem on T-Mobile, and it prevents me from using most of the services I need.
