### ISSUE TITLE
FR: Desktop Linux GUI App

### ISSUE THREAD

**Issue by Yethal** [tailscale/tailscale#12036] opened 2024-05-07 10:43 UTC
### What are you trying to do?

Have convenient way to manage Tailscale on Linux Desktop the same way Windows and MacOS users do

### How should we solve this?

Create a GUI app for desktop Linux and distribute it via an apt/rpm repo

### What is the impact of not solving this?

Nothing much, Tailscale is still fullly usable from the CLI and Linux desktop user base is probably not that high. Still, it'd be nice

**Comment by agottardo** [comment] 2024-05-08 23:59
Duplicate of tailscale/tailscale#1708

**Closed by agottardo** 2024-05-08 23:59 UTC
Labels: needs-triage, fr
