### ISSUE TITLE
1.52 Serve not working in K8s

### ISSUE THREAD

**Issue by johnuopini** [tailscale/tailscale#10278] opened 2023-11-16 14:07 UTC
### What is the issue?

I am currently exposing my influx db server using the below "trick"

```yaml
- name: ts-sidecar
  imagePullPolicy: Always
  image: "ghcr.io/tailscale/tailscale:v1.50.1"
  lifecycle:
    postStart:
      exec:
        command: [
          "/bin/sh", "-c",
          "sleep 5 && tailscale --socket=/tmp/tailscaled.sock serve https / http://127.0.0.1:8086"
        ]
```

From 1.52.0 i had to switch to this
`"sleep 5 && tailscale --socket=/tmp/tailscaled.sock serve --https=443 127.0.0.1:8086"`

But the contain fails to start, logs below

```
│ 2023/11/16 14:02:34 serve: creating a new proxy handler for http://127.0.0.1:8086                                                                                                                                 
│ 2023/11/16 14:02:34 monitor: gateway and self IP changed: gw=10.42.0.1 self=10.42.0.115                                                                                                                           
│ 2023/11/16 14:02:34 Switching ipn state NoState -> Starting (WantRunning=true, nm=true)                                                                                                                           
│ 2023/11/16 14:02:34 magicsock: SetPrivateKey called (init)                                                                                                                                                        
│ 2023/11/16 14:02:34 wgengine: Reconfig: configuring userspace WireGuard config (with 0/33 peers)                                                                                                                  
│ 2023/11/16 14:02:34 wgengine: Reconfig: configuring router                                                                                                                                                        
│ 2023/11/16 14:02:34 control: netmap: got new dial plan from control                                                                                                                                               
│ 2023/11/16 14:02:34 control: sleeping for server-requested 5s ...                                                                                                                                                 
│ 2023/11/16 14:02:34 wgengine: Reconfig: configuring DNS                                                                                                                                                          
│ 2023/11/16 14:02:34 dns: Set: {DefaultResolvers:[] Routes:{cc.ts.net.:[] ts.net.:[...]}+65arpa SearchDomains:[...] Hosts:34}                      
│ 2023/11/16 14:02:34 dns: Resolvercfg: {Routes:{...}                                                │
│ 2023/11/16 14:02:34 dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[....]
│ 2023/11/16 14:02:34 rename of "/etc/resolv.conf" to "/etc/resolv.pre-tailscale-backup.conf" failed (rename /etc/resolv.conf /etc/resolv.pre-tailscale-backup.conf: device or resource busy), falling back to copy 
│ 2023/11/16 14:02:34 peerapi: serving on http://...                                                                                                                                          
│ 2023/11/16 14:02:34 peerapi: serving on http://...                                                                                                             │
│ 2023/11/16 14:02:34 serve listening on [...]:443                                                                                                                              
│ 2023/11/16 14:02:34 serve listening on 1...:443                                                                                                                                                        
│ 2023/11/16 14:02:34 magicsock: home is now derp-4 (fra)                                                                                                                                                           
│ 2023/11/16 14:02:34 magicsock: adding connection to derp-4 for home-keep-alive                                                                                                                                    
│ 2023/11/16 14:02:34 control: NetInfo: NetInfo{varies=true hairpin=false ipv6=false ipv6os=true udp=true icmpv4=false derp=#4 portmap= link="" firewallmode="ipt-default"}                                         
│ 2023/11/16 14:02:34 magicsock: 1 active derp conns: derp-4=cr0s,wr0s                                                                                                                                              
│ 2023/11/16 14:02:34 Switching ipn state Starting -> Running (WantRunning=true, nm=true)                                                                                                                           
│ 2023/11/16 14:02:34 magicsock: endpoints changed: 1...:2051 (stun), 1...:39261 (local)                                                                                                           
│ 2023/11/16 14:02:34 derphttp.Client.Connect: connecting to derp-4 (fra)                                                                                                                                           
│ boot: 2023/11/16 14:02:34 Startup complete, waiting for shutdown signal                                                                                                                                           
│ 2023/11/16 14:02:34 magicsock: derp-4 connected; connGen=1                                                                                                                                                        
│ 2023/11/16 14:02:34 health("overall"): ok                                                                                                                                                                         
│ boot: 2023/11/16 14:02:39 Received SIGTERM from container runtime, shutting down tailscaled                                                                                                                       
│ 2023/11/16 14:02:39 tailscaled got signal terminated; shutting down                                                                                                                                               
│ boot: 2023/11/16 14:02:39 failed to read from tailscaled: EOF`

### Steps to reproduce

Use try to serve in lifecycle using K8s wont work

### Are there any recent changes that introduced the issue?

Taiscale "serve" seems to have updated in 1.52

### OS

Other

### OS version

K3s 1.28.3

### Tailscale version

1.52.0

### Other software

_No response_

### Bug report

_No response_

**Comment by knyar** [comment] 2023-11-16 15:13
In general, I don't think this is something that we have documented as a way to expose services to the tailnet. Have you tried using the [kubernetes operator](https://tailscale.com/kb/1236/kubernetes-operator/#cluster-ingress) to configure cluster ingress?

With respect to the specific behaviour you are seeing, based on the logs it seems that the `serve` command successfully creates a proxy handler, but shortly after start something is terminating the container:

> boot: 2023/11/16 14:02:39 Received SIGTERM from container runtime, shutting down tailscaled

Do you know what sends that signal and why?

**Comment by johnuopini** [comment] 2023-11-16 15:32
> In general, I don't think this is something that we have documented as a way to expose services to the tailnet. Have you tried using the [kubernetes operator](https://tailscale.com/kb/1236/kubernetes-operator/#cluster-ingress) to configure cluster ingress?

My cluster has no ingress and my pods have no service, ingress would add complexity this approach was fairly easy, I use it only because it allows me to have valid certs which makes things easier for clients to connect.

> Do you know what sends that signal and why?

No that's the issue, till 1.50 it was working as expected, I see there is also a TS_SERVE_CONFIG env but wasn't able to use it. I guess I can keep using 1.50.

**Comment by knyar** [comment] 2023-11-16 15:38
I'd suggest looking at the logs of your container runtime around the time the container gets terminated. Perhaps starting the container without the postStart command and trying to run it manually would help understand what's happening.

**Comment by knyar** [comment] 2023-11-16 15:40
Actually, looking at the [updated docs](https://tailscale.com/kb/1242/tailscale-serve/) for `tailscale serve` perhaps adding `--bg` flag would help? By default `serve` runs in the foreground now. Just a wild theory, but perhaps your container runtime terminates the container if `postStart` has been running for too long?

**Comment by johnuopini** [comment] 2023-11-17 08:28
> Actually, looking at the [updated docs](https://tailscale.com/kb/1242/tailscale-serve/) for `tailscale serve` perhaps adding `--bg` flag would help? By default `serve` runs in the foreground now. Just a wild theory, but perhaps your container runtime terminates the container if `postStart` has been running for too long?

Thanks but unfortunately that didn't work, i tried using a different entrypoint, many serve options but for some reason 1.52.0 dies while 1.50 doesn't

Here are the logs from 1.50.0

```
│ 2023/11/17 08:24:10 Starting network monitor...                                                                                                                                                                   
│ 2023/11/17 08:24:10 Engine created.                                                                                                                                                                               
│ 2023/11/17 08:24:10 pm: using backend prefs for "profile-e638": Prefs{ra=false dns=true want=true routes=[] nf=on host="..." update=check Persist{lm=, o=, n=[/gmBi] u=""}}                 │
│ 2023/11/17 08:24:11 logpolicy: using system state directory "/var/lib/tailscale"                                                                                                                                  
│ 2023/11/17 08:24:11 got LocalBackend in 100ms                                                                                                                                                                     
│ 2023/11/17 08:24:11 Start                                                                                                                                                                                         
│ 2023/11/17 08:24:11 Backend: logs: be:... fe:                                                                                                        │
│ 2023/11/17 08:24:11 control: client.Login(false, 0)                                                                                                                                                               
│ 2023/11/17 08:24:11 control: doLogin(regen=false, hasUrl=false)                                                                                                                                                   
│ 2023/11/17 08:24:11 health("overall"): error: not in map poll                                                                                                                                                     
│ boot: 2023/11/17 08:24:11 tailscaled in state "NoState", waiting                                                                                                                                                  
│ 2023/11/17 08:24:11 control: control server key from https://controlplane.tailscale.com: ts2021=[fSeS+], legacy=[nlFWp]                                                                                           
│ 2023/11/17 08:24:11 control: RegisterReq: onode= node=[/gmBi] fup=false nks=false                                                                                                                                 
│ 2023/11/17 08:24:11 control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false                                                                                               
│ 2023/11/17 08:24:11 control: netmap: got new dial plan from control                                                                                                                                               
│ 2023/11/17 08:24:11 active login: johnuopini@github                                                                                                                                                               
│ 2023/11/17 08:24:11 serve: creating a new proxy handler for http://127.0.0.1:8086                                                                                                                                 
│ 2023/11/17 08:24:11 monitor: gateway and self IP changed: gw=10...1 self=10....                                                                                                                           
│ 2023/11/17 08:24:11 Switching ipn state NoState -> Starting (WantRunning=true, nm=true)                                                                                                                           
│ 2023/11/17 08:24:11 magicsock: SetPrivateKey called (init)                                                                                                                                                        
│ 2023/11/17 08:24:11 wgengine: Reconfig: configuring userspace WireGuard config (with 0/33 peers)                                                                                                                  
│ 2023/11/17 08:24:11 wgengine: Reconfig: configuring router                                                                                                                                                        
│ boot: 2023/11/17 08:24:11 tailscaled in state "Starting", waiting                                                                                                                                                 
│ 2023/11/17 08:24:11 serve listening on 100...:443                                                                                                                                                        
│ 2023/11/17 08:24:11 wgengine: Reconfig: configuring DNS                                                                                                                                                           
│ 2023/11/17 08:24:11 dns: Set: {DefaultResolvers:[] Routes:{...ts.net.:[] ts.net.:[...::53]}+65arpa SearchDomains:[.....] Hosts:34}                      
│ 2023/11/17 08:24:11 dns: Resolvercfg: {Routes:{.:[10...] ts.net.:[...::53]} Hosts:34 LocalDomains:[.....]+65arpa}                                                
│ 2023/11/17 08:24:11 dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[..... ...] }     │
│ 2023/11/17 08:24:11 rename of "/etc/resolv.conf" to "/etc/resolv.pre-tailscale-backup.conf" failed (rename /etc/resolv.conf /etc/resolv.pre-tailscale-backup.conf: device or resource busy), falling back to copy │
│ 2023/11/17 08:24:11 peerapi: serving on http://100...:59392                                                                                                                                              
│ 2023/11/17 08:24:11 peerapi: serving on http://[:::]:59392                                                                                                                   
│ 2023/11/17 08:24:11 serve listening on [:::]:443                                                                                                                              
│ 2023/11/17 08:24:11 magicsock: home is now derp-4 (fra)                                                                                                                                                           
│ 2023/11/17 08:24:11 magicsock: adding connection to derp-4 for home-keep-alive                                                                                                                                    
│ 2023/11/17 08:24:11 control: NetInfo: NetInfo{varies=true hairpin=false ipv6=false ipv6os=true udp=true icmpv4=false derp=#4 portmap= link="" firewallmode="ipt-default"}                                         
│ 2023/11/17 08:24:11 magicsock: 1 active derp conns: derp-4=cr0s,wr0s                                                                                                                                              
│ 2023/11/17 08:24:11 Switching ipn state Starting -> Running (WantRunning=true, nm=true)                                                                                                                           
│ 2023/11/17 08:24:11 derphttp.Client.Connect: connecting to derp-4 (fra)                                                                                                                                           
│ 2023/11/17 08:24:11 magicsock: endpoints changed: 194.34.233.203:61167 (stun), 10.42.0.143:37056 (local)                                                                                                          
│ boot: 2023/11/17 08:24:11 Running 'tailscale set'                                                                                                                                                                 
│ boot: 2023/11/17 08:24:11 Deleting authkey from kube secret                                                                                                                                                       
│ boot: 2023/11/17 08:24:11 Startup complete, waiting for shutdown signal                                                                                                                                           
│ 2023/11/17 08:24:11 magicsock: derp-4 connected; connGen=1                                                                                                                                                        
│ 2023/11/17 08:24:11 health("overall"): ok
```

**Comment by knyar** [comment] 2023-11-17 15:36
I've just tried 1.52 on k3s, and have not been able to reproduce the issue with container termination.

Pod configuration:
```
apiVersion: v1
kind: Pod
metadata:
  name: tailscale
spec:
  serviceAccountName: tailscale
  containers:
  - name: tailscale
    image: "ghcr.io/tailscale/tailscale"
    lifecycle:
      postStart:
        exec:
          command: [
            "/bin/sh", "-c",
            "sleep 5 && tailscale --socket=/tmp/tailscaled.sock serve --https=443 --bg 127.0.0.1:8086"
          ]
```

Seeing serve endpoint configured in logs. The client keeps running.
```
2023/11/17 15:23:44 Program starting: v1.52.0-t31e1690f3, Go 1.21.3: []string{"tailscaled", "--socket=/tmp/tailscaled.sock", "--state=kube:tailscale", "--statedir=/tmp", "--tun=userspace-networking"}
...
2023/11/17 15:23:49 serve: creating a new proxy handler for http://127.0.0.1:8086
```

Serve endpoint is active:
```
$ kubectl exec tailscale -- tailscale --socket=/tmp/tailscaled.sock serve status
https://tailscale.xxx.ts.net (tailnet only)
|-- / proxy http://127.0.0.1:8086
```

I suspect the behaviour you are seeing is specific to your environment, and not actually caused by the client upgrade, even though `tailscale serve` command has been substantially changed in 1.52.

I am going to close this issue now since I don't believe there is any action we can take here, but please feel free to reopen if you discover any additional information that would help identify any improvements.

**Closed by knyar** 2023-11-17 15:36 UTC
Labels: OS-kubernetes, L1 Very few, P2 Aggravating, T3 Performance/Debugging, needs-triage-eng
