### ISSUE TITLE
MagicDNS should not be required for exit nodes

### ISSUE THREAD

**Issue by samlinville** [tailscale/tailscale#9728] opened 2023-10-10 16:11 UTC
### What is the issue?

We have observed that exit nodes fail to work when MagicDNS is disabled for a tailnet. This has been raised most recently by several Mullvad Exit Node users, but we have seen users experience this behavior with normal exit nodes too. Most recently, the user who raised the issue was using macOS and iOS client devices. I do not know if all platforms experience this behavior.

### Steps to reproduce

- Disable MagicDNS in the Admin console
- Try to use an exit node; pings should fail.

### OS

macOS, iOS

**Comment by DentonGentry** [comment] 2023-10-12 20:46
We could make it that when MagicDNS is disabled, that the search domain for `tail012345.ts.net` is removed and so lookups for a hostname like `ubuntu` will not search MagicDNS.

**Comment by agottardo** [comment] 2024-10-08 18:12
Duplicate of https://github.com/tailscale/tailscale/issues/12244

**Closed by agottardo** 2024-10-08 18:12 UTC
Labels: OS-macos, OS-ios, dns, exit-node, bug
