### ISSUE TITLE
FR: inline list of devices on macOS menubar app (UX)

### ISSUE THREAD

**Issue by tosh** [tailscale/tailscale#6635] opened 2022-12-06 10:28 UTC
### What are you trying to do?

Navigating to the list of devices (e.g. to see them or to copy an IP address) requires navigation of two fold-out menus) which is a bit tricky to do.

Network Devices => My Devices => List of Devices

### How should we solve this?

I think it would be more convenient if these fold-out menus were inlined. This way you only have to navigate to the tailscale icon in the menubar (infinite y axis ftw), click on it and then move the mouse or keyboard arrows down to the device (for copying) or if you don't want to copy but just look at the list you are already done (compared to the fold-out navigation steps you currently have to take).

### Anything else?

Somewhat related: It might also be awesome to add more information to the devices similar to the admin console (status).

Could work similar to the wifi menu bar app on macOS (shows more info if you "option-click" it).

That said: inlining the list of devices will move everything further down and might cause different ux issues when the list of devices is long (e.g. if the "Quit" list item stays below the list of devices and gets moved way down).

I can see that this is not an easy design problem but I wonder if there is a better way than the current one considering that listing devices and working with them is part of key workflows (?) one does as tailscale user => opportunity to delight users.

Thank you for the platform.

**Comment by DentonGentry** [comment] 2022-12-14 05:25
Duplicate of https://github.com/tailscale/tailscale/issues/3319

**Closed by DentonGentry** 2022-12-14 05:25 UTC
Labels: needs-triage, fr
