### ISSUE TITLE
No DNS resolution after connecting to an exit node if client does not use tailscale DNS settings.

### ISSUE THREAD

**Issue by yuyue9284** [tailscale/tailscale#13471] opened 2024-09-14 15:20 UTC
### What is the issue?

On iOS/Mac, the DNS resolution failed after connect to an exit code if the client does not toggle on the `use tailscale dns settings`, after toggle it on, the browser can open the page.

When tailscale dns is not used.

Output of the dig command, it can only succeed by explicitly setting the dns server:

> dig bing.com
> 
> ; <<>> DiG 9.10.6 <<>> bing.com
> ;; global options: +cmd
> ;; connection timed out; no servers could be reached

>dig bing.com @1.1.1.1
> 
> ; <<>> DiG 9.10.6 <<>> bing.com @1.1.1.1
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6955
> ;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
> 
> ;; QUESTION SECTION:
> ;bing.com.			IN	A
> 
> ;; ANSWER SECTION:
> bing.com.		600	IN	A	204.79.197.200
> bing.com.		600	IN	A	13.107.21.200
> 
> ;; Query time: 54 msec
> ;; SERVER: 1.1.1.1#53(1.1.1.1)
> ;; WHEN: Sat Sep 14 23:15:28 CST 2024
> ;; MSG SIZE  rcvd: 58

Output of scutil --dns
> DNS configuration (for scoped queries)
> 
> resolver #1
>   search domain[0] : lan
>   nameserver[0] : 1.1.1.1
>   if_index : 6 (en0)
>   flags    : Scoped, Request A records
>   reach    : 0x00000002 (Reachable)

### OS

macOS

### OS version

Mac OS Sonoma

### Tailscale version

1.72.2

### Bug report
BUG-1161e528285122334388b7a93d5949cfe2f833d72c1868d434f1d99b7c1b1261-20240914152246Z-a844b23efd91b08e

**Comment by agottardo** [comment] 2024-09-16 07:15
Duplicate of https://github.com/tailscale/tailscale/issues/12244

This is currently expected behavior _on Apple platforms_ due to limitations imposed by Apple in the NetworkExtension framework. You must enable MagicDNS when using an exit node if you want DNS to work.

There is ongoing work to allow users to customize the DNS servers used when an exit node is enabled and Tailscale DNS is enabled. Refer to the above issue.

**Closed by agottardo** 2024-09-16 07:15 UTC
Labels: needs-triage, bug
