### ISSUE TITLE
FR: Allow setting name/description for API Keys/OAuth Credentials

### ISSUE THREAD

**Issue by giodamelio** [tailscale/tailscale#7924] opened 2023-04-19 18:11 UTC
### What are you trying to do?

When I have multiple API keys or OAuth credentials, it can be hard to remember which one is for which application when browsing them in the admin console.

### How should we solve this?

Allow storing a name/description when the keys are created and display them in the listing page.

### What is the impact of not solving this?

Currently I have a note that records a description with the key id, but that involves an extra lookup and would not scale well in a multi user environment.

**Comment by DentonGentry** [comment] 2023-04-19 18:15
Duplicate of https://github.com/tailscale/tailscale/issues/4314

**Closed by DentonGentry** 2023-04-19 18:15 UTC
Labels: needs-triage, fr

**Comment by giodamelio** [comment] 2023-04-19 18:34
Dam, didn't find that one. Sorry to bother you.
