### ISSUE TITLE
win7 service pack1 reboot lost setting of network location

### ISSUE THREAD

**Issue by daliangdaliang** [tailscale/tailscale#8696] opened 2023-07-24 11:29 UTC
### What is the issue?

win7 installs tailscale. After every connection, the win7 system requires me to select the network location, and I choose home.

However, after the reboot, all the previous network location saves of tailscale were invalid, and I had to select the network location again.

Why is that, huh? zerotier doesn't have this problem.

### Steps to reproduce

Setting the network location on the home network or the work network will not work.

As soon as win7 restarts, the original network adapter needs to reset the network location.

### Are there any recent changes that introduced the issue?

no

### OS version

win7 旗舰版 ultimate  service pack1

### Tailscale version

1.360

### Other software

I also have zerotier installed, but turning zerotier off doesn't help.

**Comment by DentonGentry** [comment] 2023-07-24 13:05
This has been reported before on some systems, as in https://github.com/tailscale/tailscale/issues/5678

At this point to set expectations: we can no longer even build for Windows 7, the tools we use like [Go 1.21](https://github.com/golang/go/issues/57003) have dropped support and removed the workarounds which allowed Windows 7 to run binaries.

We built one last Tailscale 1.44.2 release to resolve the end-of-support for Windows 7. Tailscale 1.46.0 does not run on Windows 7. I do not expect to resolve this issue on reboot of Windows 7.

Duplicate of https://github.com/tailscale/tailscale/issues/5678

**Closed by DentonGentry** 2023-07-24 13:05 UTC
Labels: needs-triage, bug
