### ISSUE TITLE
FR: Add connectedToControl field to the devices API

### ISSUE THREAD

**Issue by ArielRamatiNeuralight** [tailscale/tailscale#6167] opened 2022-11-02 11:30 UTC
### What are you trying to do?

I'm trying to create monitoring to our devices connectivity status

### How should we solve this?

add connectedToControl to the devices API

### What is the impact of not solving this?

we can't know which device is connected to tailscale.
we are using our machines in production env so we can't be aware of which machine is off grid and can't know we need to take care of it.
right now we need to solve this manually and obviously this almost impossible to find which machine went offline

**Comment by bexelbie** [comment] 2022-12-15 12:58
While not the same order of magnitude as OP, this also impacts Home Assistant users wishing to monitor for when their devices go offline.

**Comment by DentonGentry** [comment] 2023-02-18 19:39
I think the intent of this is the same as https://github.com/tailscale/tailscale/issues/7004, which supplies several possible implementations available now.

Duplicate of https://github.com/tailscale/tailscale/issues/7004

**Closed by DentonGentry** 2023-02-18 19:39 UTC
Labels: L3 Some users, P2 Aggravating, T0 New feature, api, fr
