### ISSUE TITLE
FR: Integration with Google/LDAP Groups to manage ACL with a Web UI

### ISSUE THREAD

**Issue by wesleung** [tailscale/tailscale#8354] opened 2023-06-15 17:20 UTC
### What are you trying to do?

Simplify ACL management as current json file can get huge if our company grows to over a 100 employees.  Utilize Google Groups and/or LDAP groups.  Put a UI interface to managing the groups instead of a json file where admins can make mistakes

### How should we solve this?

ACL per Google Group.  That way we can manage the users in each group in google apps instead of JSON file

### What is the impact of not solving this?

Currently I will probably check in the ACL json file into github as making modifications can become a headache as the json file grows in size

### Anything else?

For azure you probably should also support LDAP groups

**Comment by DentonGentry** [comment] 2023-06-16 05:08
https://github.com/tailscale/tailscale/issues/2861 tracks Google Groups implementation — which will be a bespoke gRPC implementation, as Google stopped accepting new SCIM partners in 2019.

**Comment by DentonGentry** [comment] 2023-06-17 16:01
Duplicate of https://github.com/tailscale/tailscale/issues/2861

**Closed by DentonGentry** 2023-06-17 16:01 UTC
Labels: needs-triage, fr
