### ISSUE TITLE
"An issue in this version of iOS is preventing the Tailscale tunnel from starting" after iOS 1.56.1 to 1.58 update

### ISSUE THREAD

**Issue by jksmurf** [tailscale/tailscale#10915] opened 2024-01-21 07:01 UTC
### What is the issue?

I have an issue on my iPhone after updating from 1.56.1 to 1.58.

"An issue in this version of iOS is preventing the Tailscale tunnel from starting. Reboot your iPhone and open Tailscale again to fix this"

I also have an error on my Windows PC Following the same update.
Windows error below reproduced by Right clicking Tailscale Icon

---------------------------
Tailscale Error
---------------------------
Failed to connect to Tailscale service.

Version 1.58.0 (te5d341d96-g01ef76851)

LogID: e4a1266ee74d52d778e98a177c528bea225541b647076c10af8847750c4d1dbf
(Ctrl-C to copy this text)

---------------------------
OK   
---------------------------

Rebooting several times makes no difference to the iPhone or Windows installation
![Error](https://github.com/tailscale/tailscale/assets/23158634/3995ce7d-5eac-4c24-a1f6-42e62b948bde)
![Oops](https://github.com/tailscale/tailscale/assets/23158634/d365cf28-b635-4456-a60c-e8e50ed2cec9)

### Steps to reproduce

On iPhone - Start Tailscale.
On Windows 11 PC. Right click Tailscale.

### Are there any recent changes that introduced the issue?

r updating from 1.56.1 to 1.58.

### OS

Windows, iOS

### OS version

iOS 17.2.1 and Windows 11

### Tailscale version

1.58

### Other software

NIL

### Bug report

"Could not connect to this server"

**Comment by harupong** [comment] 2024-01-21 09:22
I had a similar issue with my iPhone after updating the app to the latest. Deleting the app, rebooting the device, and then reinstalling the app solved the issue.

```
iPhone 13
iOS 17.2.1
Tailscale 1.58.0
```

In my case, when I tapped "Connect" button or toggle switch to connect, no error message was shown but Tailscale app wasn't able to connect to tailnet and stayed disconnected.

Hope this helps.

**Comment by jksmurf** [comment] 2024-01-21 09:33
Hi thanks for that I tried this, but as I have the App on my iPad it downloaded it as if it knew it, installed and I ended up with the same error unfortunately.

**Comment by hx00d** [comment] 2024-01-21 12:59
I have the same issue. I am running tailscale (1.58.0) on an IPhone Xr (IOS 17.2.1). I have tried uninstalling and reinstalling tailscale, removing the VPN configuration and rebooting, without success.  My tailenet does not currently have any exit nodes configured.

**Comment by jojo-swe** [comment] 2024-01-21 15:30
"I have the exact same issue. I reinstalled the older version 1.56, and it works again. On my iOS device, I can't downgrade. But strangely enough, it works when connected through mobile, but something seems to be off when using Wi-Fi. I have an Asus router running Merlin with the Skynet firewall installed. I tried to disable Skynet, but no luck there either." So there must be some settings in my router that prevents the newer version to work properly.

**Comment by DentonGentry** [comment] 2024-01-21 16:02
> strangely enough, it works when connected through mobile, but something seems to be off when using Wi-Fi

While connected to mobile can you get a bugreport and paste it here?
I suspect this is a symptom of https://github.com/tailscale/tailscale/issues/10911

**Comment by partsman123** [comment] 2024-01-21 16:20
Same problem iPad with 17.2.1 and tailscale 1.58

**Comment by jojo-swe** [comment] 2024-01-21 16:22
I don't want to install 1.58 on my windows system (to get the bugreport) until I know how to fix the problem. But on my IOS device I get the same "Oops" message. But here is the kicker, enabling upnp made it work on my IOS device! But I don't want to have it enabled for security reasons. So I guess I need to manually open a specific port in my firewall, but I don't know which one.

**Comment by DentonGentry** [comment] 2024-01-21 16:26
> enabling upnp made it work on my IOS device

This is almost certainly a symptom of https://github.com/tailscale/tailscale/issues/10911, a problem with portmapping in 1.58. I can't immediately explain why _enabling_ portmapping made the issue go away.

Can you attach a bugreport from the iOS device? It is in the application menu. https://tailscale.com/kb/1227/bug-report?tab=ios

**Comment by DentonGentry** [comment] 2024-01-21 16:30
For anyone seeing this problem on a desktop OS like Windows, macOS, or Linux, please attach the output of `tailscale debug portmap`

**Comment by jksmurf** [comment] 2024-01-22 05:42
> For anyone seeing this problem on a desktop OS like Windows, macOS, or Linux, please attach the output of `tailscale debug portmap`

```
Microsoft Windows [Version 10.0.22631.3007]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\System32>tailscale debug portmap
Get "http://local-tailscaled.sock/localapi/v0/debug-portmap?duration=5s&log_http=false&type=": open \\.\pipe\ProtectedPrefix\Administrators\Tailscale\tailscaled: The system cannot find the file specified.

C:\Windows\System32>tailscale debug portmap
monitor: monitor: gateway and self IP changed: gw=192.168.9.1 self=192.168.9.10
gw=192.168.9.1; self=192.168.9.10
portmapper: [v1] UPnP reply {Location:http://192.168.9.1:42912/rootDesc.xml Server:AsusWRT/4.1.52 UPnP/1.1 MiniUPnPd/2.3.3 USN:uuid:3ddcd1d3-2380-45f5-b069-3c7c3f6b0e30::urn:schemas-upnp-org:device:InternetGatewayDevice:1}, "HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=120\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nUSN: uuid:3ddcd1d3-2380-45f5-b069-3c7c3f6b0e30::urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nEXT:\r\nSERVER: AsusWRT/4.1.52 UPnP/1.1 MiniUPnPd/2.3.3\r\nLOCATION: http://192.168.9.1:42912/rootDesc.xml\r\nOPT: \"http://schemas.upnp.org/upnp/1/0/\"; ns=01\r\n01-NLS: 1705821337\r\nBOOTID.UPNP.ORG: 1705821337\r\nCONFIGID.UPNP.ORG: 1337\r\n\r\n"
unexpected EOF

C:\Windows\System32>tailscale debug portmap>C:\TSDebug
Get "http://local-tailscaled.sock/localapi/v0/debug-portmap?duration=5s&log_http=false&type=": open \\.\pipe\ProtectedPrefix\Administrators\Tailscale\tailscaled: The system cannot find the file specified.

C:\Windows\System32>tailscale debug portmap>C:\TSDebug
unexpected EOF

C:\Windows\System32>tailscale debug portmap>C:\TSDebug
Get "http://local-tailscaled.sock/localapi/v0/debug-portmap?duration=5s&log_http=false&type=": open \\.\pipe\ProtectedPrefix\Administrators\Tailscale\tailscaled: The system cannot find the file specified.

C:\Windows\System32>
```

I am not sure if I have captured what you need?

**Comment by jojo-swe** [comment] 2024-01-22 17:38
![image](https://github.com/tailscale/tailscale/assets/74981366/1f93edba-b71c-4864-bfdf-5d3f1ebe9134)

**Comment by jojo-swe** [comment] 2024-01-22 17:39
I was trying but I can't generate a bug report when offline.

**Comment by agottardo** [comment] 2024-01-22 20:59
@jojo-swe that's unfortunately expected, you need Tailscale to connect before you can submit a bug report. 

Would you mind sharing a [sysdiagnose archive](https://it-training.apple.com/tutorials/support/sup075) taken on your iPhone? You can email it to `andrea@tailscale.com`. You can also look yourself for suspicious log entries from the `IPNExtension` process indicating a panic. Thanks!

**Comment by jksmurf** [comment] 2024-01-22 23:28
> @jojo-swe that's unfortunately expected, you need Tailscale to connect before you can submit a bug report.
> 
> Would you mind sharing a [sysdiagnose archive](https://it-training.apple.com/tutorials/support/sup075) taken on your iPhone? You can email it to `andrea@tailscale.com`. You can also look yourself for suspicious log entries from the `IPNExtension` process indicating a panic. Thanks!

@agottardo I’ve done this and sent an email with a couple of attempts. Unless I’ve done something wrong, the sysdiagnose files are huge, 250MB, so I sent a Dropbox link.

**Comment by agottardo** [comment] 2024-01-22 23:35
@jksmurf thanks for sending these over email! Looking at your crash logs, it appears that the backend extension is crashing deep in some Go code. You're likely hitting https://github.com/tailscale/tailscale/issues/10911. We just submitted a new TestFlight unstable build to Apple (v1.59.8) which includes a fix for the issue. Apple hasn't approved it yet, but give it a try once you see it available (probably tomorrow).

**Comment by jksmurf** [comment] 2024-01-23 22:48
Can confirm TestFlight unstable build Apple (v1.59.8) fixes the issue.

**Comment by agottardo** [comment] 2024-01-24 23:03
v1.58.2 is now rolling out on the App Store. If the issue persists after installing the update, please open a new issue. Closing this.

**Closed by agottardo** 2024-01-24 23:03 UTC
Labels: OS-ios, L3 Some users, P3 Can't get started, T6 Major usability, bug

**Comment by jojo-swe** [comment] 2024-01-26 13:26
I can confirm that the new version indeed fixed the problem. Kudos!
