### ISSUE TITLE
FR: recover when iptables rules are lost

### ISSUE THREAD

**Issue by dingdang66686** [tailscale/tailscale#5424] opened 2022-08-24 11:22 UTC
### What are you trying to do?

I've installed tailscale on my router. When the network changes, the iptables rules are reset and those of tailscale will be flushed.

### How should we solve this?

 I want a command to re-apply them. I can use it in firewall script.

**Comment by DentonGentry** [comment] 2022-08-28 06:11
We're not likely to provide a set of manual commands for this, it puts too much burden on the user. We're more likely to try to correct it automatically, as we do for IP routes:
`router: somebody (likely systemd-networkd) deleted ip rules; restoring Tailscale's`

**Comment by DentonGentry** [comment] 2022-10-31 13:49
Substantially a duplicate of https://github.com/tailscale/tailscale/issues/2908, in that rules are deleted by a different tool and need to be restored.

We did this once already for `systemd-networkd` in https://github.com/tailscale/tailscale/pull/2468/

Duplicate of https://github.com/tailscale/tailscale/issues/2908

**Closed by DentonGentry** 2022-10-31 13:49 UTC
Labels: L2 Few, P2 Aggravating, T5 Usability, fr
