### ISSUE TITLE
tailscale Windows installer does not start tailscale GUI, if there are more than one user logged in to Windows

### ISSUE THREAD

**Issue by alexbrainman** [tailscale/tailscale#1070] opened 2020-12-27 03:47 UTC
**Describe the bug**

tailscale-ipn-setup-1.3.105.exe does not start tailscale GUI after installation completes, if I have 2 users logged in to my PC during installation.

**To Reproduce**

I have Windows 10 computer with 2 user: Alex and Bob. And I have both users logged in at all times. We just switch users.

I didn't have Tailscale installed when I discovered this bug. And I had both Alex and Bob users logged in before installing Tailscale. Then I run `tailscale-ipn-setup-1.3.105.exe` from Bob desktop. I run installer by clicking `Run as administrator` right click menu.

The installation completed with no errors. I see this output log

```
InitDriverSetup: 
Output folder: C:\Program Files (x86)\Tailscale IPN
Extract: tailscale-ipn-new.exe... 100%
MakeDead: 100.1
Uninstalling service
Uninstalling service... (via v1.3.105-t0dc295a64-gcfe6a707d: ["C:\\Program Files (x86)\\Tailscale IPN/tailscale-ipn-new.exe" "/uninstall"])
Path was: `%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Mercurial\;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files\Git\cmd`
Path doesn't need changes.
UninstallService: 0
Killing old tailscale-ipn.exe...
Kill: 603
Find: 603
Rename: tailscale-ipn-new.exe->tailscale-ipn.exe
Windows major version: 10
Extract: tailscale.exe... 100%
Extract: wintun.dll... 100%
Extract: RunFromProcess.exe... 100%
Created uninstaller: C:\Program Files (x86)\Tailscale IPN\Uninstall-Tailscale.exe
Create shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Tailscale.lnk
Create shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\Tailscale.lnk
Installing IPN service
Installing service... (via v1.3.105-t0dc295a64-gcfe6a707d: ["C:\\Program Files (x86)\\Tailscale IPN\\tailscale-ipn.exe" "/install"])
Path was: `%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Mercurial\;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files\Git\cmd`
Updating Path to `%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Mercurial\;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files\Git\cmd;%PROGRAMFILES(X86)%\Tailscale IPN`
Starting client
Completed
```

But I don't see Tailscale GUI running (there is no Tailscale icon in notification area) on Bob desktop.

I switched desktop to Alex. I see Tailscale GUI is running on Alex desktop.

**Expected behavior**

I expected Tacscale installer to run Tailscale GUI on the desktop where installer runs - Bob desktop.

**Version information:**
 - Device: [PC]
 - OS: [Windows]
 - OS version: [Windows 10]
 - Tailscale version: [1.3.105]

/cc @bradfitz @peske 

Alex

**Comment by DentonGentry** [comment] 2022-02-06 02:57
Duplicate of https://github.com/tailscale/tailscale/issues/662

**Closed by DentonGentry** 2022-02-06 02:57 UTC
Labels: OS-windows, L3 Some users, P2 Aggravating, T2 Visual Polish
