### ISSUE TITLE
Black screen when opening Tailscale TV app

### ISSUE THREAD

**Issue by Ne0morph** [tailscale/tailscale#10982] opened 2024-01-31 00:44 UTC
### What is the issue?

Opening the app flashes a white screen then goes to a black screen with no way to interact with anything

### Steps to reproduce

-Open Tailscale

### OS version

Android TV 9

### Tailscale version

1.57.100-t8250582fe-g4799cc1ef

**Comment by DentonGentry** [comment] 2024-01-31 03:21
Duplicate of https://github.com/tailscale/tailscale/issues/4332

**Closed by DentonGentry** 2024-01-31 03:21 UTC
Labels: needs-triage, bug
