### ISSUE TITLE
Missing JSON Output with `up --json` Command in Tailnet on Mac

### ISSUE THREAD

**Issue by nyghtowl** [tailscale/tailscale#4729] opened 2022-05-24 00:15 UTC
### What is the issue?

When in a tailnet on Mac, the `/Applications/Tailscale.app/Contents/MacOS/Tailscale up --json` has no output. It does work on Linux

### Steps to reproduce

**Step to Reproduce**
Run `/Applications/Tailscale.app/Contents/MacOS/Tailscale up --json` on a Mac 

**Result**
No output

**Expected output**

{
        "AuthURL": "https://....",
        "QR": "....",
        "BackendState": "...."
}

### OS

macOS

### OS version

macOS Monterey

### Tailscale version

1.24.2

### Bug report

BUG-d0bd1c24b81c1248b525c46c8a165f4017b867738a7158a71c894057228f355b-20220524001257Z-66fac9a57fad9b78

**Comment by mihaip** [comment] 2022-05-27 17:31
As best as I can tell, this is behaving across platforms. If Tailscale is already up/connected, `up --json` outputs nothing. If it's not, it will output JSON states:

```
~$ /Users/mihai/Library/Developer/Xcode/DerivedData/IPN-gegnlsvbjygrcefuhrpkzxtpjnqu/Build/Products/Debug/Tailscale.app/Contents/MacOS/Tailscale up --json
{
	"AuthURL": "https://login.tailscale.com/a/79cbdaddf439",
	"QR": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACAAQMAAAD58POIAAAABlBMVEX///8AAABVwtN+AAABPUlEQVR42uTUvY3sIBQF4IMIyEwHuA0HlmjJoTPIHLolJAK3YXfAZAQW58m7I+1EO5jJ3t7wi7g/HPyxkmQZNORSLLk3QoCxfpfsRohK2GgUi1zK6B4fgGV/unQLFAX9JxBg1NpHlpfm3sA1semIS/c6wntw1QARc/eyvd9BbombPyLTqPReB1x36F0uZBatkJ2xawHEiYI62LzIrtgFmJ/3cRuAyahkxlkElVAFMmiR9W59GvG85NsARXJlcIy5GhKsB/Dgc1cNYMkMBiUiawE4Nt+fs45LaQQZJgNnrIf0qQ6gvNhWwAFzMwwomDDOmqyFyzSD6+B+PtCv8B1sR7wSpkMjXEm38lTd9fo62GjgYLPm9300wjCJc2akuAHoA4r0j1b4SjoRvQ4/7b+Br4mZEQxzK/zH9S8AAP//kql8Ml4akyEAAAAASUVORK5CYII=",
	"BackendState": "Stopped"
}
{
  "BackendState": "Running"
}
```

**Comment by nyghtowl** [comment] 2022-05-31 15:25
@maisem Also noted that it outputs nothing when using non-default config for json call

``` 
$ sudo tailscale up --json --ssh
$
```

**Comment by DentonGentry** [comment] 2023-02-13 01:33
So far as I can see this is working as intended, the tailscaleup output was empty because it did not reauthenticate.

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Closed** 2023-02-22 19:37 UTC
Labels: OS-macos, L1 Very few, P1 Nuisance, T2 Visual Polish, bug
