### ISSUE TITLE
FR: DNS over HTTPS/TLS Setting

### ISSUE THREAD

**Issue by martafolf** [tailscale/tailscale#9254] opened 2023-09-06 14:03 UTC
### What are you trying to do?

Set up a specific DNS over HTTPS or TLS endpoint as a "Custom" DNS server. 

### How should we solve this?

Add an option to specify the DNS over HTTPS or TLS server address instead of just the IP of a server.

This somewhat falls in-line of how the customisations for NextDNS are allowed to set a custom endpoint, but would just openly expand it to any providers of DNS over HTTPS/TLS. 

### What is the impact of not solving this?

Unable to use custom servers with with certain providers. 

### Anything else?

It would be ideal if a choice between using HTTPS or TLS for DNS resolution would be provided, with potential for fallback between them. 

The reasoning is that DNS over TLS is typically lower impact on the performance side and closer to the wire, which is ideal if the tailscale client is run on server infrastructure.

**Comment by DentonGentry** [comment] 2023-09-06 14:25
Duplicate of https://github.com/tailscale/tailscale/issues/74

The difficulty we have is with client operating systems:
1. `tailscaled` will attempt to pass through DNS configuration to the host OS when possible.
1. `tailscaled` will set its own tiny little 100.100.100.100 DNS server if it has to.

Client operating systems have wildly differing capabilities. The most frequent pain point is Android, which supports DNS-over-TLS in all Android versions we support but only implemented DNS-over-HTTPS in recent versions.

For the DNS-over-HTTPS services we support like Google DNS or Cloudflare, the regular UDP DNS service is easily found. So we can use DNS-over-HTTPS where it is supported and fall back to 8.8.8.8 (etc) where it is not.

A DoH-only service, or one where we cannot easily locate the UDP DNS information, isn't straightforward to support.

**Closed by DentonGentry** 2023-09-06 14:25 UTC
Labels: needs-triage, fr
