### ISSUE TITLE
Broken system dns when tailscale dns is enabled

### ISSUE THREAD

**Issue by daviehh** [tailscale/tailscale#13423] opened 2024-09-10 02:22 UTC
### What is the issue?

On the release candidate version of macos Sequoia 15.0 (24A335), when the option 'Use tailscale DNS settings' is enabled, most apps (except safari) would fail to look up domain names and appears unable to connect to the internet.

### Steps to reproduce

Enable 'Use tailscale DNS settings' on macos Sequoia

### OS

macOS

### OS version

15.0 (24A335)

### Tailscale version

1.72.2

### Bug report

BUG-9dc0f99653422cce63c1887ba3a06324760a68cc01122b766947dab17779aded-20240910022237Z-870b2e930dd64400

**Comment by agottardo** [comment] 2024-09-10 17:39
We've been using Sequoia for months since the very first beta, and we are not aware of any incompatibility issue. 

- What is the output of `scutil --dns`? 
- Does a reboot solve this? 
- Are you using an exit node?
- What is your DNS configuration? 
- Do queries to 100.100.100.100 resolve properly? For instance, what's the output of `nslookup google.com 100.100.100.100`?

**Comment by mbadala** [comment] 2024-09-11 11:56
same happens to me. I think it's from client side. For me chrome doesn't work but it got fixed after I upgrade chrome to latest version.

**Comment by UpsideUp14** [comment] 2024-09-13 11:30
Also have the same issue on macOS Sonoma Version 14.6.1

**Comment by enquora** [comment] 2024-09-14 02:11
Worked with betas, can confirm (on two machines) broken under,  Sequoia release candidate (build 24A335). First noticed after updating from 1.72 to 1.74.0 (macPorts version).

**Comment by agottardo** [comment] 2024-09-14 05:32
@UpsideUp14 @enquora can you please attach bug report identifiers from the affected devices?

**Comment by UpsideUp14** [comment] 2024-09-14 08:08
@agottardo
> @UpsideUp14 @enquora can you please attach bug report identifiers from the affected devices?
BUG-988e062e0ef0e6bccc665d9543a84689b86f8396c5a6e599329b4a92451bbb75-20240914080624Z-99cb1e84fd87c4f0

Running on version 1.72.2

**Comment by enquora** [comment] 2024-09-14 15:21
> @UpsideUp14 @enquora can you please attach bug report identifiers from the affected devices?
BUG-1ae90f630a1666f8e7b575b45e2c8b7bd8f7f9a3070b0e9243b30d0c4cec7a6d-20240914151118Z-6250bbeb20dadc72

For those with a mostly superficial understanding of Tailscale, it would be beneficial to be specific when requesting things like this. This would avoid needing to guess at what is meant and hunt until finding the `tailscale bugreport` flag.

The symptoms observed here (more precisely):

Previous versions of Tailscale, when installed using a package manager (MacPorts in this case) would correctly resolve machines on a tailnet using just the hostname (e.g. `ping target_hostname`) without any additional configuration of system resolver(s).

With 1.74.0, this is no longer true. Using the App Store or .pkg installer versions of 1.74.0 **do** support the previous behaviour.

Using the tailnet FQDN does not work either.

MagicDNS is enabled in the Tailscale.com admin panel.

**Comment by lunarthegrey** [comment] 2024-09-17 05:08
Same issue here, just upgraded to Sequoia and in some applications I can no longer resolve DNS util I turn off Tailscale DNS.

**Comment by robinostlund** [comment] 2024-09-17 12:48
Same here, i also can see the same issues using wireguard so seems to be something bigger

**Comment by cfritze64** [comment] 2024-09-17 19:04
Same. Arc and Chrome not reaching any web pages when Tailscale is connected after upgrade to Sequoia

**Comment by agottardo** [comment] 2024-09-17 19:13
**When you observe that DNS queries are failing to resolve**, please generate a bug report identifier and paste it here. Then, follow these steps to gather some extra diagnostics we need:

1. Provide the output of `nslookup google.com` and `nslookup google.com 100.100.100.100`, and `scutil --dns -dv` in the Terminal
2. Provide the output of `tailscale dns status` (you might need to first install the Tailscale CLI from the Tailscale app settings).
3. Check whether this only happens in Chrome, or other apps are affected. Try to determine what DNS server the affected apps are sending DNS queries to, if the app allows you to specify a given DNS server.
4. Open the Console app in macOS, and filter for log entries matching the library `io.tailscale.ipn.macsys.network-extension` (Standalone variant), or `IPNExtension` (App Store variant). Run `nslookup google.com 100.100.100.100` to trigger a DNS query. Do you see any errors from the Tailscale process when you do that?

**Comment by agottardo** [comment] 2024-09-17 19:17
I noticed that all bug report identifiers affected here are running the Mac App Store build. Anybody hitting this on the Standalone variant? Let me know if switching from MAS to Standalone fixes this. 

(In general, we recommend using the Standalone variant on macOS.)

**Comment by cfritze64** [comment] 2024-09-17 19:19
Here the output of the terminal commands from agottardo's #1 above
`cfritze:~ BikeFixe$ nslookup google.com
Server:		192.168.4.1
Address:	192.168.4.1#53

Non-authoritative answer:
Name:	google.com
Address: 142.250.189.238

cfritze:~ BikeFixe$ 
cfritze:~ BikeFixe$ nslookup google.com 100.100.100.100,
nslookup: couldn't get address for '100.100.100.100,': not found
cfritze:~ BikeFixe$ nslookup google.com 100.100.100.100
Server:		100.100.100.100
Address:	100.100.100.100#53

** server can't find google.com: SERVFAIL

cfritze:~ BikeFixe$ scutil --dns -dv
DNS configuration

resolver #1
  nameserver[0] : 192.168.4.1
  if_index : 10 (en13)
  flags    : 0x00000002 (Request A records)
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  config id: Default: 0

resolver #2
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 300000
  config id: Multicast DNS: 0

resolver #3
  domain   : 254.169.in-addr.arpa
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 300200
  config id: Multicast DNS: 1

resolver #4
  domain   : 8.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 300400
  config id: Multicast DNS: 2

resolver #5
  domain   : 9.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 300600
  config id: Multicast DNS: 3

resolver #6
  domain   : a.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 300800
  config id: Multicast DNS: 4

resolver #7
  domain   : b.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 301000
  config id: Multicast DNS: 5

DNS configuration (for scoped queries)

resolver #1
  nameserver[0] : 192.168.4.1
  if_index : 10 (en13)
  flags    : 0x00001002 (Scoped, Request A records)
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  config id: Scoped: 5AA23F36-9837-49CA-A2B3-761F1857FCFE 0

resolver #2
  nameserver[0] : 1.1.1.1
  nameserver[1] : 1.0.0.1
  if_index : 13 (en0)
  flags    : 0x00001002 (Scoped, Request A records)
  reach    : 0x00000002 (Reachable)
  config id: Scoped: A32CB29E-B4E1-4D69-8758-F3DE21EDC0E8 0

generation = 95575392256
cfritze:~ BikeFixe$ 
`

**Comment by cfritze64** [comment] 2024-09-17 19:23
output of tailscale dns status (or do you want me to run this with "Use Tailscale settings DNS" enabled? 
`=== 'Use Tailscale DNS' status ===

Tailscale DNS: disabled.

(Run 'tailscale set --accept-dns=true' to start sending DNS queries to the Tailscale DNS resolver)

=== MagicDNS configuration ===

This is the DNS configuration provided by the coordination server to this device.

MagicDNS: enabled tailnet-wide (suffix = tail658e5.ts.net)

Other devices in your tailnet can reach this device at cef-macbook-air.tail658e5.ts.net.

Resolvers (in preference order):
  (no resolvers configured, system default will be used: see 'System DNS configuration' below)

Split DNS Routes:
  - ts.net.                        -> 199.247.155.53
  - ts.net.                        -> 2620:111:8007::53

Search Domains:
  - tail658e5.ts.net

=== System DNS configuration ===

This is the DNS configuration that Tailscale believes your operating system is using.
Tailscale may use this configuration if 'Override Local DNS' is disabled in the admin console,
or if no resolvers are provided by the coordination server.

Nameservers:
  - 192.168.4.1

Search domains:
  (no search domains found)

[this is a preliminary version of this command; the output format may change in the future]
`

**Comment by agottardo** [comment] 2024-09-17 19:24
@cfritze64 you need to run these commands when Tailscale DNS is enabled, otherwise that defeats the point of gathering these diagnostics. In your case, the output of `nslookup google.com` indicates that Tailscale DNS is disabled (192.168.4.1 answered your query instead of 100.100.100.100), and no DNS queries on your system are getting handled by Tailscale, as shown by the `scutil --dns` output: you can see that `100.100.100.100` is missing from the DNS configuration for any interface.

**Comment by cfritze64** [comment] 2024-09-17 19:28
now with Tailscale DNS settings enabled:
`Tailscale DNS: enabled.

Tailscale is configured to handle DNS queries on this device.
Run 'tailscale set --accept-dns=false' to revert to your system default DNS resolver.

=== MagicDNS configuration ===

This is the DNS configuration provided by the coordination server to this device.

MagicDNS: enabled tailnet-wide (suffix = tail658e5.ts.net)

Other devices in your tailnet can reach this device at cef-macbook-air.tail658e5.ts.net.

Resolvers (in preference order):
  (no resolvers configured, system default will be used: see 'System DNS configuration' below)

Split DNS Routes:
  - ts.net.                        -> 199.247.155.53
  - ts.net.                        -> 2620:111:8007::53

Search Domains:
  - tail658e5.ts.net

=== System DNS configuration ===

This is the DNS configuration that Tailscale believes your operating system is using.
Tailscale may use this configuration if 'Override Local DNS' is disabled in the admin console,
or if no resolvers are provided by the coordination server.

Nameservers:
  - 192.168.4.1

Search domains:
  (no search domains found)

[this is a preliminary version of this command; the output format may change in the future]
cfritze:~ BikeFixe$ tailscale dns status
-bash: tailscale: command not found
cfritze:~ BikeFixe$ scutil --dns -dv
DNS configuration

resolver #1
  search domain[0] : tail658e5.ts.net
  nameserver[0] : 100.100.100.100
  if_index : 26 (utun6)
  flags    : 0x00004006 (Supplemental, Request A records, Request AAAA records)
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 101400
  config id: Supplemental: 57889A40-88FD-42F0-AF88-00DC9353C513 0

resolver #2
  nameserver[0] : 192.168.4.1
  if_index : 10 (en13)
  flags    : 0x00000002 (Request A records)
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  order    : 200000
  config id: Default: 0

resolver #3
  domain   : tail658e5.ts.net.
  nameserver[0] : 100.100.100.100
  if_index : 26 (utun6)
  flags    : 0x00004006 (Supplemental, Request A records, Request AAAA records)
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 101401
  config id: Supplemental: 57889A40-88FD-42F0-AF88-00DC9353C513 1

resolver #4
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 300000
  config id: Multicast DNS: 0

resolver #5
  domain   : 254.169.in-addr.arpa
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 300200
  config id: Multicast DNS: 1

resolver #6
  domain   : 8.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 300400
  config id: Multicast DNS: 2

resolver #7
  domain   : 9.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 300600
  config id: Multicast DNS: 3

resolver #8
  domain   : a.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 300800
  config id: Multicast DNS: 4

resolver #9
  domain   : b.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 301000
  config id: Multicast DNS: 5

DNS configuration (for scoped queries)

resolver #1
  nameserver[0] : 192.168.4.1
  if_index : 10 (en13)
  flags    : 0x00001002 (Scoped, Request A records)
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  config id: Scoped: 5AA23F36-9837-49CA-A2B3-761F1857FCFE 0

resolver #2
  nameserver[0] : 1.1.1.1
  nameserver[1] : 1.0.0.1
  if_index : 13 (en0)
  flags    : 0x00001002 (Scoped, Request A records)
  reach    : 0x00000002 (Reachable)
  config id: Scoped: A32CB29E-B4E1-4D69-8758-F3DE21EDC0E8 0

resolver #3
  search domain[0] : tail658e5.ts.net
  nameserver[0] : 100.100.100.100
  if_index : 26 (utun6)
  flags    : 0x00001006 (Scoped, Request A records, Request AAAA records)
  reach    : 0x00000003 (Reachable,Transient Connection)
  config id: Scoped: 57889A40-88FD-42F0-AF88-00DC9353C513 0

generation = 125099324867
cfritze:~ BikeFixe$ 
`

**Comment by agottardo** [comment] 2024-09-17 19:28
Also, in Chrome, you can use `chrome://net-internals/#dns` to try looking up a DNS name like `nytimes.com`, try seeing if you get any errors there.

**Comment by agottardo** [comment] 2024-09-17 19:30
@cfritze64 is DNS resolution still broken in Chrome? If so, please follow my original instructions:

> Open the Console app in macOS, and filter for log entries matching the library io.tailscale.ipn.macsys.network-extension (Standalone variant), or IPNExtension (App Store variant). Run nslookup google.com 100.100.100.100 to trigger a DNS query. Do you see any errors from the Tailscale process when you do that?

**Comment by cfritze64** [comment] 2024-09-17 19:32
in Chrome:
`Resolved IP addresses of "nytimes.com": ["151.101.1.164","151.101.129.164","151.101.65.164","151.101.193.164"].
No alternative endpoints.
`

**Comment by cfritze64** [comment] 2024-09-17 19:38
No logs or other entries generated in Console when nslookup google.com 100.100.100.100 fails. No records of any kind in any of the console panels when i filter with either of the two strings you suggested above. Meanwhlie, even when I turn "User Tailscale DNS settings" off, Tailscale is giving me a warning:
`Tailscale can't reach the configured DNS servers. Internet connectivity may
be affected.

Code: dns-forward-failing`

**Comment by agottardo** [comment] 2024-09-17 19:41
@cfritze64 can you please provide a bug report ID? I need to see your logs to understand what's causing that.

**Comment by cfritze64** [comment] 2024-09-17 19:46
BUG-23f224baada1580d25ba9c8395b1ffa00bb2a9e391660b6c13fa902aaca7aa26-20240917194417Z-3daac5318321cfdf

...and do you want the exported Configuration Report?

**Comment by enquora** [comment] 2024-09-17 19:56
> I noticed that all bug report identifiers affected here are running the Mac App Store build. Anybody hitting this on the Standalone variant? Let me know if switching from MAS to Standalone fixes this.
> 
> (In general, we recommend using the Standalone variant on macOS.)

macOS installer pkg and MacPorts package both exhibit the problem.

**Comment by jum** [comment] 2024-09-17 20:09
It is also not limited to sequoia, I have it on Sonoma as well. It started with tailscale 1.74.0 for me.

BUG-b34fbde3c067b06dd2d2785aadf2ad3fd2f9e4c756abec7d467b205dc9fb5e77-20240917200910Z-98ab66c8406773e6

**Comment by agottardo** [comment] 2024-09-17 20:11
@enquora @jum I suspect you're hitting a different issue here, specific to the open-source `tailscaled` distribution you're using. Please provide the full set of diagnostics I requested in https://github.com/tailscale/tailscale/issues/13423#issuecomment-2356701432 so that I can identify a root cause (and potentially open a new issue **specific to tailscaled**).

**Comment by enquora** [comment] 2024-09-17 20:25
> @enquora @jum I suspect you're hitting a different issue here, specific to the open-source `tailscaled` distribution you're using. Please provide the full set of diagnostics I requested in [#13423 (comment)](https://github.com/tailscale/tailscale/issues/13423#issuecomment-2356701432) so that I can identify a root cause (and potentially open a new issue **specific to tailscaled**). Note that v1.74.0 of the opensource `tailscaled` is now able to read the system DNS resolvers (changelog [here](https://tailscale.com/changelog#2024-09-12)), so this might have been a regression introduced there, non related to macOS Sequoia).

The problem is present with Sonoma, too.
It was introduced in 1.74.0 and is only coincidental that Sequoia was released at nearly the same time.
BUG-1ae90f630a1666f8e7b575b45e2c8b7bd8f7f9a3070b0e9243b30d0c4cec7a6d-20240917202429Z-e4d9287551bd0919

I'm also regularly seeing the launch daemon stopped and having to manually reload it.

**Comment by materia-io** [comment] 2024-09-18 01:39
I don't know if this is related, but I had problems until turning off the firewall.  I found this thread on Reddit, and it seems something is flipped to block Chrome and Firefox after the update:
https://www.reddit.com/r/MacOSBeta/comments/1eca62s/macos_sequoia_beta_4_chrome_no_internet/

I couldn't override just the apps needed; menu toggles were busted.

**Comment by jum** [comment] 2024-09-18 11:23
I did the above steps on my home-brew install of tailscaled:

```
$ nslookup google.com
Server:		192.168.178.1
Address:	192.168.178.1#53

Non-authoritative answer:
Name:	google.com
Address: 142.250.184.14

$ nslookup google.com 100.100.100.100
Server:		100.100.100.100
Address:	100.100.100.100#53

Non-authoritative answer:
Name:	google.com
Address: 142.250.184.14

sh-3.2$ scutil --dns -dv
DNS configuration

resolver #1
  search domain[0] : mager.org
  search domain[1] : fritz.box
  nameserver[0] : 192.168.178.1
  flags    : 0x00000002 (Request A records)
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  config id: Default: 0

resolver #2
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 300000
  config id: Multicast DNS: 0

resolver #3
  domain   : 254.169.in-addr.arpa
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 300200
  config id: Multicast DNS: 1

resolver #4
  domain   : 8.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 300400
  config id: Multicast DNS: 2

resolver #5
  domain   : 9.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 300600
  config id: Multicast DNS: 3

resolver #6
  domain   : a.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 300800
  config id: Multicast DNS: 4

resolver #7
  domain   : b.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)
  order    : 301000
  config id: Multicast DNS: 5

resolver #8
  domain   : search.tailscale
  search domain[0] : tail6f5c6.ts.net
  search domain[1] : mager.org
  search domain[2] : fritz.box
  flags    : 0x00000002 (Request A records)
  reach    : 0x00000000 (Not Reachable)

DNS configuration (for scoped queries)

resolver #1
  search domain[0] : mager.org
  search domain[1] : fritz.box
  nameserver[0] : 192.168.178.1
  if_index : 14 (en0)
  flags    : 0x00001002 (Scoped, Request A records)
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  config id: Scoped: 1D416D79-2BC1-4026-BC62-ABB765947752 0

generation = 353625953708

sh-3.2$ tailscale dns status

=== 'Use Tailscale DNS' status ===

Tailscale DNS: enabled.

Tailscale is configured to handle DNS queries on this device.
Run 'tailscale set --accept-dns=false' to revert to your system default DNS resolver.

=== MagicDNS configuration ===

This is the DNS configuration provided by the coordination server to this device.

MagicDNS: enabled tailnet-wide (suffix = tail6f5c6.ts.net)

Other devices in your tailnet can reach this device at osiris.tail6f5c6.ts.net.

Resolvers (in preference order):
  (no resolvers configured, system default will be used: see 'System DNS configuration' below)

Split DNS Routes:
  - ts.net.                        -> 199.247.155.53
  - ts.net.                        -> 2620:111:8007::53

Search Domains:
  - tail6f5c6.ts.net

=== System DNS configuration ===

This is the DNS configuration that Tailscale believes your operating system is using.
Tailscale may use this configuration if 'Override Local DNS' is disabled in the admin console,
or if no resolvers are provided by the coordination server.

Nameservers:
  - 192.168.178.1

Search domains:
  - mager.org
  - fritz.box

[this is a preliminary version of this command; the output format may change in the future]
```

**Comment by cfritze64** [comment] 2024-09-18 18:13
Michael Tsai - Blog - macOS Firewall Regressions in Sequoiamjtsai.comOn Sep 17, 2024, at 13:12, Andrea Gottardo ***@***.***> wrote:﻿
@enquora @jum I suspect you're hitting a different issue here, specific to the open-source tailscaled distribution you're using. Please provide the full set of diagnostics I requested in #13423 (comment) so that I can identify a root cause (and potentially open a new issue specific to tailscaled).

**Comment by schmidp** [comment] 2024-09-18 18:50
Maybe it's related to: https://infosec.exchange/@wdormann/113149199491406975

**Comment by enquora** [comment] 2024-09-18 23:13
Note also that the Tailscale daemon seems to be regularly dying, requiring relaunching again.
Notably, though, using `launchctl load -w …` doesn't keep it going. 
I'm willing to retrieve specific log files, but don't have the time to diagnose using the streaming log.

**Comment by jfleitz** [comment] 2024-09-20 16:48
Hoping this may help folks that are having this issue as it worked for me. I had the exact same issue mentioned above when I upgraded to Sequoia 15, and it turned out it was the new way the Mac Firewall works with Sequoia 15 that was blocking incoming connections and responses with Tailscale DNS. Run the following to get a list of Application Firewall Rules:
`sudo /usr/libexec/ApplicationFirewall/socketfilterfw --listapps`

Look for the Tailscale entry that should be something like this:
`9 : /Applications/Tailscale.app/Contents/PlugIns/IPNExtension.appex 
             (Allow incoming connections)
`

Verify that it does Allow incoming connections. Mine was "Block incoming connections", so I gave perms by running (confirm/change to the path in your list on where Tailscale is installed):
`sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /Applications/Tailscale.app/Contents/PlugIns/IPNExtension.appex`

**Comment by cfritze64** [comment] 2024-09-20 18:06
...and then, adapting the socketfilterfw command above to /Applications/Arc.app/Contents/MacOS/Arc  (I'm using the Arc browser) also solved the blockage I had browsing with Arc when Tailscale was active. Apple's Firewall blocked Arc, but it was uneditable in the Firewall settings panel...

**Comment by agottardo** [comment] 2024-10-08 18:16
Duplicate of tailscale/tailscale#13511 which tracks issues in DNS resolution caused by regressions introduced in macOS Sequoia.

**Closed by agottardo** 2024-10-08 18:16 UTC
Labels: OS-macos, dns, bug, needs-triage-support

**Comment by pinkyellowed** [comment] 2024-10-16 18:16
i don't want to create a new bug, but this issue still persists with sequiona even with the allow incoming connections on.
all my firewalls are down to the extend that tailscale doesnt show up on sudo /usr/libexec/ApplicationFirewall/socketfilterfw --listapps, tailscale seems to work fine on bookworm-pihole and IOS
with tailscale on using the tailscale dns settings, im able to ping my pihole server, and ping everything but for some reasons when i turn tailscale on it enacts as VPN killswitch and takes me off the internet until i turn it off

**Comment by AndyIbanez** [comment] 2024-10-30 00:53
I have started seeing this issue starting on roughly October 14. I didn't realize until I saw a bunch of backup operations to a machine on my local Tailscale network started to fail, and I noticed just now.

I also saw the issue on another Mac where it suddenly stopped connecting to Google and other websites when using Safari. My ISP was being unstable then, so I didn't make the connection til now. I did a clean install of Sequoia on that machine after that (and many other issues).

Reading Michael Tsai's blog post linked above made me mess around with the firewall... And it started to work when I enabled macOS' firewall and disabled it again. It really looks like it has something to do with how the Firewall stores data like the blogpost says. Try toggling the firewall on and backoff and see how it goes. If not, clean install might be your only solution unfortunately.

**Comment by pinkyellowed** [comment] 2024-10-30 01:06
i tried toggling, i don't even run with a firewall either. i have also tried reinstalling numerous times i'm still unable to utilize the exit node to acess the pihole gui. i have also tried going completely bare butt - pihole open to listen to any port and exit node still fails, i guess for me or some tailscale either has not disclosed that either exitnode is now a paid feature or doesn't want to fix it, and Mac OS just got a update and i still have not heard from tailscale.

**Comment by enquora** [comment] 2024-10-30 01:53
Ambiguity and unreliability obviously have no place at the network level.
Add the output from `tailscale status | awk '{print $1" "$2}' | column -t` to /etc/hosts.

If the number of entries becomes problematic, you are probably at a scale justifying a custom resolver and don't need external help.
