### ISSUE TITLE
FR: Ability to add more IP addresses for internal network use

### ISSUE THREAD

**Issue by backtozero** [tailscale/tailscale#5600] opened 2022-09-12 09:56 UTC
### What are you trying to do?

The problem we are trying to solve is to aggregate many ssh-forwarded ports on one machine and use that machine to transparently connect to resources behind those forwarded ports from the entire tailnet.
Currently you are only getting two internal(tailnet) IPs(one IPv4 and one IPv6) which allows you for example to have two 443 ports binded on one machine.
<img width="212" alt="image" src="https://user-images.githubusercontent.com/9365418/189615238-986a5569-132f-4c0e-9d81-820ec5e5890b.png">

One could ask: why not to bind for example 443 port to any other port of your tailnet address?
- First answer is that some(AWS) services requires your requests to be signed and port information is included in that signing part. Therefore if you are providing different port in some software that uses AWS libraries then you will get no answer.
- Another is that it is very simple to separate dozens of different "Bastion" servers by binding them to an unique IP and keeping port mappings as it is

### How should we solve this?

Allowing to add new tailnet IPs for a particular machine either from CLI or Admin web page

### What is the impact of not solving this?

Actually I could not find any other simple solution to this problem.
And we are just using those two addresses to solve the issue currently.

### Anything else?

We could use reverse proxy of course, but not all of our connections is https. Also there are some certificate issues arise on this route.

**Comment by DentonGentry** [comment] 2022-09-12 10:25
Duplicate of https://github.com/tailscale/tailscale/issues/465

**Closed by DentonGentry** 2022-09-12 10:25 UTC
Labels: needs-triage, fr
