### ISSUE TITLE
FR: Include / Exclude certain apps on Android

### ISSUE THREAD

**Issue by Zocker1999NET** [tailscale/tailscale#4036] opened 2022-02-27 12:26 UTC
### What are you trying to do?

Other VPN providers (like WireGuard, Orbot, …) allow the user to select which apps' connections should be routed through the VPN or which should bypass the VPN. In my case, I want to use the exit node feature of Tailscale while allowing apps like KDE Connect to still access my local network as usual to connect to my devices locally.

### How should we solve this?

Allow users to include / exclude certain apps from the VPN

### What is the impact of not solving this?

In the case of KDE Connect, as all devices happen to be in the same Tailscale network, I could route the traffic explicit through the VPN, however this comes with a huge reduction of transmission speed, as I use KDE Connect to transfer bigger files from my phone to my PC and vise versa.
Some users, which cannot afford to have all devices reachable through the Tailscale network, disabling the exit node might be the only workaround.

**Comment by DentonGentry** [comment] 2022-02-27 12:27
Duplicate of https://github.com/tailscale/tailscale/issues/3828

**Closed by DentonGentry** 2022-02-27 12:27 UTC
Labels: needs-triage, fr
