### ISSUE TITLE
Please support Home Assistant OS (HassOS) as an add-on 

### ISSUE THREAD

**Issue by timesout404** [tailscale/tailscale#3604] opened 2021-12-21 17:50 UTC
### What are you trying to do?

Please support Home Assistant OS (HassOS) as an add-on from Home Assistant store

### What is the impact of not solving this?

 add Tailscale client as add-on on Home Assistant store

### Anything else?

https://www.home-assistant.io/addons/

**Comment by DentonGentry** [comment] 2021-12-21 17:56
There are several options linked from https://github.com/tailscale/tailscale/issues/1336, we'd recommend looking into those.

Duplicate of https://github.com/tailscale/tailscale/issues/1336

**Closed by DentonGentry** 2021-12-21 17:56 UTC
Labels: needs-triage, fr
