### ISSUE TITLE
Exit node breaks internet

### ISSUE THREAD

**Issue by vicentefern** [tailscale/tailscale#2564] opened 2021-08-02 05:46 UTC
Whenever I connect to my exit node running on a remote raspberry pi, my internet breaks. I have also tried running an exit node on other Linux machines in the past, connecting with both Linux and android clients with zero success. I can ping and ssh into my remote pi's Tailscale address just fine with the exit node off . Tailscale ip of the exit node is 100.72.57.74 and local tailscale ip is 100.72.166.60. Using a public Nameserver 1.1.1.1 with override local DNS running. I've read the other bug reports and tried playing around with the DNS settings accordingly but no luck there.

**Comment by DentonGentry** [comment] 2021-08-02 07:26
Could you:
1. have 100.72.166.60 connect to 100.72.57.74 as an exit node (breaking everything)
1. generate a bugreport from 100.72.166.60: `tailscale bugreport`
1. then you can disconnect from the exit node
1. paste the string the bugreport prints here

This will give us something specific to look for.

The most common reason exit nodes result in broken connectivity is DNS, particularly if the DNS server is on the local LAN like the local router. The exit node feature as currently implemented focuses on the case where one is out in public, perhaps using an Open or Guest Wifi network, and thus the local LAN is not trusted. When the exit node is turned on, access to the local LAN is blocked and all traffic is sent to the exit node. Since you're using 1.1.1.1 this shouldn't be an issue, but the symptom does otherwise match what happens if access to a local DNS server is blocked.

Connecting to the exit node with `tailscale up --exit-node=100.72.57.74 --exit-node-allow-lan-access` would avoid the issue by allowing LAN access.

**Comment by vicentefern** [comment] 2021-08-02 08:27
Done.

BUG-6ca59b0db1c0da4a48e6f293f8bb75b334de5a579de2e72a1b92b71b7a2a36b0-20210802081830Z-7566e6d157c55e5c

As you stated, the use of 1.1.1.1 should rule that out, so I am left clueless as to what other scenario could be breaking the internet. The fact that tailscale works should be ruling out an ISP block am I correct in that assumption?

Kind Regards,

**Comment by arunsathiya** [comment] 2021-08-02 12:33
I am not too sure yet, but I think I am seeing the same issue. 

- Exit node: 100.100.135.73 (a Raspberry Pi node)
- Connecting from 100.92.182.87
- Magic DNS is enabled on Tailscale admin, DNS set to 3 Tailscale nodes (all running [pi-hole](https://pi-hole.net/)), override local DNS enabled. 

Should I replace these Tailscale node DNS resolvers to a public one like 1.1.1.1, but I imagine that wouldn't work either based on the original report on this GitHub issue.

**Comment by DentonGentry** [comment] 2021-08-03 04:30
Noting a few symptoms from BUG-6ca59b0db1c0da4a48e6f293f8bb75b334de5a579de2e72a1b92b71b7a2a36b0-20210802081830Z-7566e6d157c55e5c


It probes frequently for a path to reach [+XbWr], even though it does get a response on one path.
```
2021-08-01 23:41:53.00911605 -0600 -0600: magicsock: disco: d:df55291039a8a7a2<-d:a2e090010cd26eef ([+XbWr], derp-3)  got call-me-maybe, 4 endpoints
2021-08-01 23:41:53.009400412 -0600 -0600: magicsock: disco: d:df55291039a8a7a2->d:a2e090010cd26eef ([+XbWr], w.x.y.z:41641) sent ping tx=2b6c27a4c26f
2021-08-01 23:41:53.009964825 -0600 -0600: magicsock: disco: d:df55291039a8a7a2->d:a2e090010cd26eef ([+XbWr], 192.168.0.z:41641) sent ping tx=339ba61f2b4e
2021-08-01 23:41:53.010186075 -0600 -0600: magicsock: disco: d:df55291039a8a7a2->d:a2e090010cd26eef ([+XbWr], w.x.y.z:51524) sent ping tx=eebc692c624a
2021-08-01 23:41:53.308197912 -0600 -0600: magicsock: disco: d:df55291039a8a7a2<-d:a2e090010cd26eef ([+XbWr], w.x.y.z:41641)  got pong tx=2b6c27a4c2
6f latency=299ms pong.src=w.x.y.z:41641
2021-08-01 23:41:54.304005037 -0600 -0600: magicsock: disco: timeout waiting for pong b3c252cdf29b from w.x.y.z:51524 ([+XbWr], d:a2e090010cd26eef)
2021-08-01 23:41:54.304309512 -0600 -0600: magicsock: disco: timeout waiting for pong b737a528fe30 from w.x.y.z:41641 ([+XbWr], d:a2e090010cd26eef)
2021-08-01 23:41:54.305683962 -0600 -0600: magicsock: disco: timeout waiting for pong 6795826f85e7 from 192.168.0.z:41641 ([+XbWr], d:a2e090010cd26eef)
2021-08-01 23:41:55.3064921 -0600 -0600: magicsock: disco: send, starting discovery for [+XbWr] (d:a2e090010cd26eef)
2021-08-01 23:41:55.30704325 -0600 -0600: magicsock: disco: d:df55291039a8a7a2->d:a2e090010cd26eef ([+XbWr], derp-9) sent call-me-maybe
2021-08-01 23:41:55.30753895 -0600 -0600: magicsock: disco: d:df55291039a8a7a2->d:a2e090010cd26eef ([+XbWr], w.x.y.z:51524) sent ping tx=e77588ee3d77
2021-08-01 23:41:55.308303487 -0600 -0600: magicsock: disco: d:df55291039a8a7a2->d:a2e090010cd26eef ([+XbWr], 192.168.0.z:41641) sent ping tx=ce0cf88f335a
2021-08-01 23:41:56.305016937 -0600 -0600: magicsock: disco: timeout waiting for pong 4034e8f88b1c from w.x.y.z:41641 ([+XbWr], d:a2e090010cd26eef)
2021-08-01 23:41:58.306441987 -0600 -0600: magicsock: disco: timeout waiting for pong 6ae09c817e3a from w.x.y.z:41641 ([+XbWr], d:a2e090010cd26eef)
2021-08-01 23:41:59.010845225 -0600 -0600: magicsock: disco: d:df55291039a8a7a2<-d:a2e090010cd26eef ([+XbWr], derp-3)  got call-me-maybe, 4 endpoints
2021-08-01 23:41:59.011411325 -0600 -0600: magicsock: disco: d:df55291039a8a7a2->d:a2e090010cd26eef ([+XbWr], 192.168.0.z:41641) sent ping tx=a54c5ab459e0
2021-08-01 23:41:59.011510575 -0600 -0600: magicsock: disco: d:df55291039a8a7a2->d:a2e090010cd26eef ([+XbWr], w.x.y.z:51524) sent ping tx=2bf47857c0a3
2021-08-01 23:41:59.0115978 -0600 -0600: magicsock: disco: d:df55291039a8a7a2->d:a2e090010cd26eef ([+XbWr], w.x.y.z:41641) sent ping tx=fbaefe621d51
2021-08-01 23:41:59.276663712 -0600 -0600: magicsock: disco: d:df55291039a8a7a2<-d:a2e090010cd26eef ([+XbWr], w.x.y.z:41641)  got pong tx=fbaefe621d
51 latency=266ms pong.src=w.x.y.z:41641
2021-08-01 23:42:00.306692987 -0600 -0600: magicsock: disco: timeout waiting for pong 8f69c550e3b3 from w.x.y.z:41641 ([+XbWr], d:a2e090010cd26eef)
2021-08-01 23:42:00.3071946 -0600 -0600: magicsock: disco: timeout waiting for pong e77588ee3d77 from w.x.y.z:51524 ([+XbWr], d:a2e090010cd26eef)
2021-08-01 23:42:00.308415925 -0600 -0600: magicsock: disco: timeout waiting for pong ce0cf88f335a from 192.168.0.z:41641 ([+XbWr], d:a2e090010cd26eef)
2021-08-01 23:42:01.310761862 -0600 -0600: magicsock: disco: send, starting discovery for [+XbWr] (d:a2e090010cd26eef)
2021-08-01 23:42:01.312166525 -0600 -0600: magicsock: disco: d:df55291039a8a7a2->d:a2e090010cd26eef ([+XbWr], derp-9) sent call-me-maybe
```

Just before the bugreport, all of the keys expire:
```
2021-08-01 23:49:32.967903462 -0600 -0600: [+XbWr] - Removing all keys, since we haven't received a new one in 540 seconds
```

It also doesn't seem to be accepting the route:
```
2021-08-02 00:57:04.034982287 -0600 -0600: wgcfg: skipped unselected default routes from: "hostname" ([+XbWr])
```

**Comment by vicentefern** [comment] 2021-08-03 06:27
Very odd behavior. Unwilling to take the route available to it. Cant wrap my head around the fact that it works fine when I'm not using the pi as an exit node. I had the exact same issue when using a local linux box as an exit node so its beginning to look like something related to my local network. Hopefully someone can help diagnose the problem.

**Comment by vicentefern** [comment] 2021-08-04 17:55
Just bumping to see if any progress has been made in diagnosing where the exact problem lies and correspondingly if there are any possible steps I can take in order to resolve this.

**Comment by arunsathiya** [comment] 2021-08-10 19:29
This might be solved for me. Just had to add `autogroup:internet:443,22` as an accessible host for my devices. Exit node works okay now. h/t https://github.com/tailscale/tailscale/issues/1742#issuecomment-884469202

**Comment by DentonGentry** [comment] 2021-12-18 05:33
Fixed by adding ACL access https://github.com/tailscale/tailscale/issues/2564#issuecomment-896258684

**Closed by DentonGentry** 2021-12-18 05:33 UTC
Labels: L1 Very few, P2 Aggravating, T5 Usability, exit-node

**Comment by OJFord** [comment] 2023-03-08 01:57
Fwiw I'm experiencing the same (not DNS, ping IP hangs) with `autogroup:member` allowed to `autogroup:internet:*`. (I suppose really the issue is not that specific and has multiple causes.)

Will dig more tomorrow.

**Comment by DentonGentry** [comment] 2023-03-08 02:07
Please open a new issue. Whatever you are running into now is almost certainly not the same as what this user ran into 1.5 years ago.
