### ISSUE TITLE
openresolve: DNS is broken after suspend/resume

### ISSUE THREAD

**Issue by pborzenkov** [tailscale/tailscale#3840] opened 2022-01-29 17:59 UTC
### What is the issue?

When a Linux system with `openresolve` returns from suspend, it doesn't yet have a `/var/run/resolveconf/interfaces/<if>` file for a network interface, as it's deleted before going to sleep.

At this point, `tailscaled` already queries `resolveconf` for the list of interfaces and their DNS configs, resulting in empty upstream DNS settings after resume.

Here is a log from a modified version of `tailscaled` that prints arguments to `resolveconf`.

After normal boot, when `tailscaled` is starting after `network-online.target`:

```
wgengine: Reconfig: configuring DNS
dns: Set: {DefaultResolvers:[] Routes:{lab.borzenkov.net.:[100.115.192.117:53]} SearchDomains:[lab.borzenkov.net.] Hosts:6}
!!!! resolvconf args: [-l static enp8s0.dhcp]
dns: Resolvercfg: {Routes:{.:[192.168.88.1:53 213.46.228.196:53 62.179.104.196:53] lab.borzenkov.net.:[100.115.192.117:53]} Hosts:6 LocalDomains:[]}
dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[lab.borzenkov.net.] MatchDomains:[]}
```

When system is going from suspend:

```
LinkChange: major, rebinding. New state: interfaces.State{defaultRoute=enp8s0 ifs={enp8s0:[192.168.88.45/24] tailscale0:[100.66.227.121/32 fd7a:115c:a1e0:ab12:4843:cd96:6242:e379/128]} v4=true v6=false}
control: mapRoutine: unpaused
[RATELIMIT] format("control: mapRoutine: %s") (1 dropped)
control: mapRoutine: state:authenticated
magicsock: SetNetworkUp(true)
dns: Set: {DefaultResolvers:[] Routes:{lab.borzenkov.net.:[100.115.192.117:53]} SearchDomains:[lab.borzenkov.net.] Hosts:6}
magicsock: adding connection to derp-4 for home-keep-alive
magicsock: 1 active derp conns: derp-4=cr0s,wr0s
derphttp.Client.Recv: connecting to derp-4 (fra)
!!!! resolvconf args: [-l static]
dns: Resolvercfg: {Routes:{.:[] lab.borzenkov.net.:[100.115.192.117:53]} Hosts:6 LocalDomains:[]}
dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[lab.borzenkov.net.] MatchDomains:[]}
```

And here is the `inotifywait` log during suspend/resume:

```
❯ inotifywait -mr /var/run/resolvconf/interfaces|rg enp8s0
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/var/run/resolvconf/interfaces/ DELETE enp8s0.dhcp

<at this point tailscaled queries resolveconf>

/var/run/resolvconf/interfaces/ CREATE enp8s0.dhcp
/var/run/resolvconf/interfaces/ OPEN enp8s0.dhcp
/var/run/resolvconf/interfaces/ MODIFY enp8s0.dhcp
/var/run/resolvconf/interfaces/ CLOSE_WRITE,CLOSE enp8s0.dhcp
/var/run/resolvconf/interfaces/ OPEN enp8s0.dhcp
/var/run/resolvconf/interfaces/ ACCESS enp8s0.dhcp
/var/run/resolvconf/interfaces/ ACCESS enp8s0.dhcp
/var/run/resolvconf/interfaces/ ACCESS enp8s0.dhcp
/var/run/resolvconf/interfaces/ ACCESS enp8s0.dhcp
/var/run/resolvconf/interfaces/ CLOSE_NOWRITE,CLOSE enp8s0.dhcp
```

### Steps to reproduce

Just suspend/resume a Linux system where DNS is configured via `openresolve`. Reproduces 100% on my system.

### Are there any recent changes that introduced the issue?

Don't know as I've never tried to suspend/resume the system with tailscaled before.

### OS

Linux

### OS version

NixOS unstable

### Tailscale version

1.20.2

### Bug report

BUG-092763f71fb6e3a3a62cb33e8224d0418dced993f7e7a84620ad4e1a1adeed21-20220129174928Z-be6efdb8d1f31a93

**Comment by DentonGentry** [comment] 2022-05-08 00:24
I think this is https://github.com/tailscale/tailscale/issues/2334 that resolv.conf did not have any DNS servers populated when tailscaled tried to read it.

**Comment by DentonGentry** [comment] 2022-08-27 23:56
Same root cause as https://github.com/tailscale/tailscale/issues/2334
Closing as a duplicate

**Closed by DentonGentry** 2022-08-27 23:56 UTC
Labels: OS-linux, L1 Very few, P2 Aggravating, T5 Usability, dns, bug
