### ISSUE TITLE
Add DNS-Over-HTTPS Support for NextDNS service

### ISSUE THREAD

**Issue by sreeram-boyapati** [tailscale/tailscale#2452] opened 2021-07-18 14:48 UTC
nextdns.io is a customizable dns service with private blocklists and crowdsourced adblocker and tracker blocklists. It is highly configurable and supports all major platforms.

Using NextDNS as DNS nameservers to use those custom blacklists and magicDNS on android phones as well as desktop is a major requirement (at least for me) to use tailscale in my workflow.

#2435 added support for Google DNS, Cloudflare. NextDNS would be another great addition. Firefox added it as the second DOH provider along with CloudFlare in 2019 [1].

#915 tracks private DNS support with tailscale in Android 12 and other versions.

1. https://www.zdnet.com/article/mozilla-to-add-second-dns-over-https-doh-provider-in-firefox/

**Comment by sa1** [comment] 2021-07-29 03:47
Seems like the recent PR maps IP addresses to hardcoded DoH urls.
https://github.com/tailscale/tailscale/blob/9ef3d6f412c2298c9e11cea5466498353c679bdf/net/dns/resolver/forwarder.go#L516

This wouldn't work for NextDNS because there's a custom url for everyone. It would help if the admin settings accept a DoH url instead of an IP.

**Comment by DentonGentry** [comment] 2021-07-29 03:56
That could get complex: depending on the capabilities of the OS, we often push the DNS configuration to the platform and not handle DNS ourselves out of Magic DNS. For example:
- recent Windows versions have a very flexible name resolution system and can handle most anything
- Android has very limited capabilities, we often handle DNS ourselves in the Tailscale app
- MacOS/iOS and Linux are somewhere in between

Accepting a URL in the DNS config means needing to look into OS capabilities for DoH.

**Comment by bradfitz** [comment] 2021-07-29 04:11
If the user specified an explicit DoH URL in their Tailnet config and the OS couldn't handle it natively (as most can't), we'd just have to wire up the host DNS config such that 100.100.100.100 was the DNS server and we'd then handle forwarding it. At least that's been what I've been assuming we'll do.

**Comment by DentonGentry** [comment] 2022-03-27 03:51
I believe that implementing https://github.com/tailscale/tailscale/issues/74 to support DNS-over-HTTPS and/or DNS-over-TLS handles this.

Duplicate of https://github.com/tailscale/tailscale/issues/74

**Comment by bradfitz** [comment] 2022-09-06 18:46
I'm going to reopen this one because I've been looking into it for other reasons and it turns out that NextDNS is unique enough in some ways to warrant & require some custom work.

We can this bug to track rather than opening a new one.

**Comment by DentonGentry** [comment] 2022-09-06 19:38
For anyone finding this, the following comments from #74 are particularly relevant:
- https://github.com/tailscale/tailscale/issues/74#issuecomment-1179718170
- https://github.com/tailscale/tailscale/issues/74#issuecomment-1179795268

**Comment by bradfitz** [comment] 2022-09-09 19:06
@tomcook, @sa1, @sreeram-boyapati, if you try the [Tailscale unstable build](https://pkgs.tailscale.com/unstable/) 1.31.39 or later, you can play with this today. Set your [Tailnet's DNS](https://login.tailscale.com/admin/dns) to your NextDNS config's IPv6 address and select "Override local DNS". New clients (1.31.39+) will only use DNS-over-HTTPs. And it'll use IPv4 to do DoH if it needs to. No need to include IPv4 addresses.

**Comment by sa1** [comment] 2022-09-09 20:44
@bradfitz Thanks, I tested it on mac, and it seems to be working. One additional feature I'd want is the hostname being sent to nextdns. https://github.com/tailscale/tailscale/issues/74#issuecomment-1179795268

Also looking forward to iOS, though currently nextdns' configuration profile works perfectly well for my use case.

**Comment by bradfitz** [comment] 2022-09-09 20:47
It should work on iOS too. Our internal TestFlight builds include it but I guess it's not in the iOS Beta TestFlight track yet.

Hostname support is coming.

**Comment by rgoomar** [comment] 2022-09-21 03:29
@bradfitz Any idea when the iOS is going to be ready?
Or how to get into the beta?

**Comment by DentonGentry** [comment] 2022-09-21 03:31
I promise there will be updates and instructions when it is ready.
Polling for updates is not useful.

**Comment by bradfitz** [comment] 2022-10-12 23:02
Launched: https://tailscale.com/blog/nextdns/

Update to Tailscale 1.32 and enjoy!

**Closed by bradfitz** 2022-10-12 23:02 UTC
Labels: L1 Very few, P1 Nuisance, T0 New feature, dns
