### ISSUE TITLE
Tailscale in use by unknown user random SID - Windows

### ISSUE THREAD

**Issue by louij2** [tailscale/tailscale#5896] opened 2022-10-11 18:19 UTC
When installing Tailscale under another user e.g. the Administrator 
Who are re-authenticating or logging in tailscale to a device on behalf of another user and the key expires 
You are unable to re-auth as the signed-in user unless you remove the tailscale appdata from the original user's local appdata directory.
The tailscale uninstaller should have an option to remove machine wide appdata to "factory reset" the application.
The SID that is presented does appear in the registry for the user and you can find it eventually but when referencing it to the Azure Active Directory it returns another user account so it's difficult to find the one that logged in originally and setup tailscale.

1.30.2

Thanks,

**Comment by DentonGentry** [comment] 2022-11-01 15:13
Possibly related:
- https://github.com/tailscale/tailscale/issues/2894
- https://github.com/tailscale/tailscale/issues/2346

**Comment by DentonGentry** [comment] 2023-02-18 17:51
Also related: https://github.com/tailscale/tailscale/issues/3186 which was fixed by https://github.com/tailscale/tailscale/pull/6255 and may also fix this.

**Comment by DentonGentry** [comment] 2023-06-03 21:16
I'm going to optimistically assume this was a duplicate of https://github.com/tailscale/tailscale/issues/3186 which was fixed by https://github.com/tailscale/tailscale/pull/6255.

**Closed by DentonGentry** 2023-06-03 21:16 UTC
