### ISSUE TITLE
Synology DSM7 - Armada370 - won't log in

### ISSUE THREAD

**Issue by SylvainDx** [tailscale/tailscale#2593] opened 2021-08-05 17:22 UTC
Hello

I install Tailscale on my DS213J after a DSM7 upgrade
the pakage log in successfully but automaticly stop after one attemp to connect.
I uninstall the package to install the last 1.12

now i cannot log in any more.
I've got the web page with the login button (http://mynas:admport/webman/3rdparty/Tailscale/?SynoToken=xxxx)
but nothing happen when I click.
on reload I get this message : 

Failed to log in: Failed to fetch

**Comment by maisem** [comment] 2021-08-05 17:36
Was tailscale installed before you upgraded to dsm7?

**Comment by SylvainDx** [comment] 2021-08-05 18:06
yes and working
then uninstall after the upgrade to switch to the dsm7 version

**Comment by maisem** [comment] 2021-08-05 19:49
I think you're running into #2592

**Comment by jeryd** [comment] 2021-08-09 02:06
Just did the DSM 7 upgrade on my machines. I had to uninstall tailscale and reinstall with the 7.0 pak. Had to reset up all my nodes. 

[REQUEST] the upgrade process should be automatic and should be able to keep the same IP as I had before. I have to go around now and reset up all the devices and services to use the new IP tailscale gave me during the upgrade process.

**Comment by maisem** [comment] 2021-08-09 13:39
@jeryd looks like you're also running into #2592. There are a couple of steps you can do manually to copy over state so that you do not have to relogin.

**Comment by DentonGentry** [comment] 2021-08-12 03:36
I'm going to close this as a duplicate of #2592, I think we want anyone searching for these symptoms to find that issue not this one.

**Closed by DentonGentry** 2021-08-12 03:36 UTC
Labels: L2 Few, P3 Can't get started, T6 Major usability, OS-synology
