### ISSUE TITLE
DNS server accessed via relay is not accessible when configured as split DNS

### ISSUE THREAD

**Issue by patmaddox** [tailscale/tailscale#2126] opened 2021-06-15 00:42 UTC
We are using [google private DNS](https://cloud.google.com/blog/products/networking/introducing-private-dns-zones-resolve-to-keep-internal-networks-concealed) to set up internal hostname resolution. The DNS server is ns-gcp-private.googledomains.com which is 169.254.169.254 - not accessible publicly.

We have configured a Tailscale relay running on a GCP network to advertise `169.254.169.254/32`. When doing so, we can query the DNS server directly:

`nslookup host.internal.ourdomain.com 169.254.169.254 # => 10.0.0.3`

When we configure split DNS so that `internal.ourdomain.com` gets resolved by `169.254.169.254`, we're no longer able to query `169.254.169.254`. It seems like split DNS does not use the relay if access to the DNS server is provided by the relay.

It is repeatable: add `169.254.169.254` as a DNS server, and DNS queries to that server time out. Delete `169.254.169.254` as a name server, and we can successfully query it.

I'm on MacOS 10.15 with Tailscale 1.8.5. A linux user on 1.8.7 experiences the same thing.

**Comment by DentonGentry** [comment] 2021-06-26 06:39
MacOS split DNS configuration using Tailscale routes: I believe this is a duplicate of https://github.com/tailscale/tailscale/issues/2003, and is fixed in release 1.10 by https://github.com/tailscale/tailscale/pull/2226

**Closed by DentonGentry** 2021-06-26 06:39 UTC
Labels: L2 Few, P3 Can't get started, T5 Usability
