### ISSUE TITLE
FR: Make `ControlPanelUrl` overridable for on tailscale-ios

### ISSUE THREAD

**Issue by canselcik** [tailscale/tailscale#4299] opened 2022-03-27 06:27 UTC
### What are you trying to do?

I am not sure if there is some AppStore related reason exists for it however this would be really nice to have.

We are already finding ourselves having to modify the source for `tailscale-android` for a custom `ControlPanelUrl`, and on OSX, it is possible to override the default however no such workaround exists for iOS.

Would be nice to at least get an non-FairPlay protected IPA so that it could be modified. I imagine Tailscale would have no problems doing any of these since they already have demonstrated a pretty liberal approach to custom backends.

Let me know what you think. 

### How should we solve this?

a) Open-source `tailscale-ios` so that we can modify and recompile
b) Just like the OSX client, have the iOS client look at some system-wide defaults we can modify via loading a profile.
c) At least release the non-FairPlay protected IPA for `tailscale-ios` so that we can patch the executable.

### What is the impact of not solving this?

Tailscale clients can be used with custom control planes on every other platform but iOS

**Comment by DentonGentry** [comment] 2022-03-27 07:00
Duplicate of https://github.com/tailscale/tailscale/issues/1572
(I know it may not look like it, but MDM support is how one sets configurable parameters in an iOS app)

**Closed by DentonGentry** 2022-03-27 07:00 UTC
Labels: needs-triage, fr
