### ISSUE TITLE
tailscaled hangs after SIGTERM until wgengine watchdog timeout

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#4630] opened 2022-05-06 06:33 UTC
### What is the issue?

On my machines, tailscaled periodically takes 45s to shut down on a reboot, holding up the entire machine as it does. Logs report that the wgengine watchdog fires and kills the process, suggestion something in our SIGTERM handling is locking up wgengine somewhere.

### Steps to reproduce

Run tailscaled, SIGTERM it. May be non-deterministic.

### OS

Linux

### OS version

NixOS 21.11

### Tailscale version

1.24.0

### Bug report

BUG-52fe962c211702bf89ad7f8df4f3f1ce53c2e997990f28ffb7c0292c51b3da3c-20220506063253Z-88e08fed5b6c8210

**Comment by DentonGentry** [comment] 2023-02-13 01:14
Duplicate of https://github.com/tailscale/tailscale/issues/3932

**Closed by DentonGentry** 2023-02-13 01:14 UTC
Labels: needs-fix, bug
