### ISSUE TITLE
Support running in containers (Docker, Kubernetes)

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#504] opened 2020-06-24 16:35 UTC
We have minimal support for containers, in that a Dockerfile exists. However, that Dockerfile doesn't embed correct version numbers, doesn't support authkey enrollment, and we have the same problem that Kubernetes had with incompatible host vs. container iptables. As such, we don't currently publish official images anywhere.

This is a tracking bug to make the container image good enough that we can support it as an official platform.

**Comment by bradfitz** [comment] 2020-06-24 16:38
When we do this, revisit https://github.com/tailscale/tailscale/pull/301 from @khos2ow

**Comment by hamishforbes** [comment] 2020-06-24 17:19
FWIW this is my hacky setup for running tailscale in a sidecar with nginx-ingress.
It might help other people coming across this issue.
https://gist.github.com/hamishforbes/2ac7ae9d7ea47cad4e3a813c9b45c10f
Just add a persistent vol for state + secret with your authkey.

This was enough to let me access services via ingress on an cluster with no inbound access, so i stopped tinkering there!
Only tested with EKS and the AWS VPC CNI, might make a difference...

**Comment by toonsevrin** [comment] 2020-06-25 13:09
@hamishforbes  [privileged: true, NET_ADMIN](https://gist.github.com/hamishforbes/2ac7ae9d7ea47cad4e3a813c9b45c10f#file-nginx-ingress-values-yaml-L22)

For #502 (expose a k8s service to your tailscale network), the Tailscale network only has to be accessible within the container itself. Would it be possible to get rid of these capabilities somehow in this case.

**Comment by hamishforbes** [comment] 2020-06-25 14:18
I *think* that option was required to get the `tun` kernel module visible in the container.
My setup doesn't seem give host access either, only access to the pod, the tailscale tunnel doesn't appear on the host, nor do iptables rules.

**Comment by toonsevrin** [comment] 2020-06-25 14:32
Pretty sure you won't need privileged then:
> For interacting with the network stack, instead of using --privileged they should use --cap-add=NET_ADMIN to modify the network interfaces.

Source: [Docker docs](https://docs.docker.com/engine/reference/run/)

Do you think networking setup can be done in an initContainer? Similar to [how istio only requires NET_ADMIN on init](https://istio.io/latest/docs/ops/deployment/requirements/#required-pod-capabilities)?

**Comment by hamishforbes** [comment] 2020-06-25 16:16
You're right, after a bit of messing about privileged isn't required.
Without privileged you do, however, have to create `/dev/net/tun` yourself with `mknod /dev/net/tun c 10 200`.
Otherwise this happens:

```
3.0M/19.1M Starting userspace wireguard engine with tun device "tailscale0"
3.1M/19.1M Linux kernel version: 4.14.173-137.229.amzn2.x86_64
3.1M/19.1M is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: can't change directory to '/lib/modules': No such file or directory
3.1M/19.1M CreateTUN: can't create TUN device; /dev/net/tun does not exist
wgengine.New: can't create TUN device; /dev/net/tun does not exist
```

Updated the gist!

Currently I don't think all the networking setup can be done at init.
I tried manually creating the `tailscale0` tun device in an init container with `NET_ADMIN`.
The tunnel shows up in the main container (you still have to create `/dev/net/tun` though) however `tailscaled` tries to modify it (even if you set the MTU to 1280 in init) and that fails.

```
2.9M/19.0M Starting userspace wireguard engine with tun device "tailscale0"
3.1M/19.0M Linux kernel version: 4.14.173-137.229.amzn2.x86_64
3.2M/19.0M is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: can't change directory to '/lib/modules': No such file or directory
3.2M/19.0M CreateTUN: failed to set MTU of TUN device
wgengine.New: failed to set MTU of TUN device
```

Maybe this would be feasible if tailscaled had some kind of init mode? But there might be other stuff being done during normal operation that requires `NET_ADMIN` too 🤷‍♂️.

For me the 2 biggest pain points in running tailscale in containers/k8s are the 2 command startup and the state file.

Starting `tailscaled` and then having to configure it with another command is not much fun in containers.
Some way to start `tailscaled` with all the necessary config (either flags, env vars or config file, don't really care) would be ideal.

And then having to keep the state file around to prevent the IP changing if the container is restarted also sucks.
DNS automation could fix this, I don't really care what the IP is just that my DNS entries keep working when the container restarts.

**Comment by toonsevrin** [comment] 2020-06-25 16:25
@hamishforbes I was thinking about the persistent volume (I agree that that sucks). I think it makes a lot of sense to have an operator manage the identities and push them into Secrets/ConfigMaps. That way no persistent volumes are required (not even for the Operator).

**Comment by toonsevrin** [comment] 2020-06-25 16:26
Perhaps you can create a PR to fix the MTU issue? I still have one more exam in a couple of days so won't be able to look at this myself up to then :')

**Comment by fpcr** [comment] 2020-06-25 19:49
@toonsevrin stop working for for-profit companies for free. Tailscale is the epitome of fake open source. Seriously how old are you?

**Comment by toonsevrin** [comment] 2020-06-25 20:23
@fpcr hahahahaha I kind of need these features for my own projects (which are sadly enough also for-profit).

**Comment by fpcr** [comment] 2020-06-25 20:45
@toonsevrin Enjoy working for a company that's based on child labor (college kids) while the founders are busy conducting astroturfing on Twitter.

**Comment by toonsevrin** [comment] 2020-06-25 20:54
Pretty sure this company is in no way asking nor incentivizing me to contribute. Anyways, feel free to email me some true OS alternatives that I can use to solve my company's issue.

**Comment by bradfitz** [comment] 2020-06-25 21:00
@fpcr, what did we do to piss you off so much? We never astroturfed Hacker News, as much as repeatedly claim we do. We didn't open source the server? See https://github.com/tailscale/tailscale/issues/498#issuecomment-647751584 if so. (Is that why you call us Fake Open Source?)

Anyway, please stop polluting this issue with your grievances. I'm sorry you're not happier.

**Comment by fpcr** [comment] 2020-06-25 21:05
@bradfitz Hacker News? who mentioned Hacker News? I said Twitter. The point is, you're a for-profit company, your repo here is simply gaslighting and snakeoil advertising as open source project. You want to have the best of both worlds, free labor and advertising and giving way literally nothing. Very sneaky.

**Comment by bradfitz** [comment] 2020-06-25 21:16
@fpcr, I assumed you were the same disgruntled person ("armaxt") banned from Hacker News with the same rants:

https://news.ycombinator.com/item?id=22760291
https://news.ycombinator.com/item?id=22761642

We get very little free labor from the open source community in the grand scheme of things, just like most big open source projects. Many for-profit companies produce open source. Actually that's how much of it came about. As usual, the core contributors do most of the work. Open source isn't just made from teenagers and moonlighters. Not sure what "giving away literally nothing" means when most of our code is open. The GUI wrappers? (well, the Android client's all open... and you can run the macOS code on macOS without the GUI) Again, if you mean the server, you can run Headscale. I already linked to that discussion.

We have very little closed code, so not sure how you've gotten so bothered by us.

**Comment by fpcr** [comment] 2020-06-25 21:26
What are you talking about? what rants on Hacker News? I am not even a registered user there even though I do visit it from time to time. Your project is pure OSS gaslighting and it's not the first time that this sneaky strategy is being done. Warning others that this isn't a FOSS for the sake of it is not "ranting". We do not need another for-profit company built on free labor of young contributors who don't know how the real world works.

**Comment by bradfitz** [comment] 2020-06-25 21:30
@fpcr, apologies for confusing you with a different person. Not sure what is sneaky about our strategy, though. We're pretty open about it. We all have a lot of open source history and that's how we prefer to work. You didn't reply to my earlier questions about what specifically is bothering you, so I assume I won't get an answer to them and will stop asking.

**Comment by toonsevrin** [comment] 2020-06-26 10:08
@hamishforbes just gave your Dockerfile a go and it works perfectly (aside from the issues you mentioned). I was able to expose an nginx deployment to the private network with zero effort ([deployment.yaml](https://gist.github.com/toonsevrin/cfbdea3beb5c9fb8f4f00d45712b92d7))!

**Comment by fserb** [comment] 2020-12-20 20:16
I have been running tailscale on docker for a while now, but I'm having a hard time setting the proper version string when I build (I end up with "date.2020XXXX" as the version). I've tried to build with `./build_dist.sh` build that doesn't work either.
That said, it would be great to have an official image as #295 suggests.

**Comment by StevenACoffman** [comment] 2021-01-20 16:00
The [xversion.go](https://github.com/tailscale/tailscale/blob/main/version/xversion.go) constants are intended to be overrridden at the time go build is executed by [build_dist.sh](https://github.com/tailscale/tailscale/blob/main/build_dist.sh)

```
exec go build -tags xversion -ldflags "-X tailscale.com/version.Long=${VERSION_LONG} -X tailscale.com/version.Short=${VERSION_SHORT} -X tailscale.com/version.GitCommit=${VERSION_GIT_HASH}" "$@"
```
These are set via environment variables via [version.sh](https://github.com/tailscale/tailscale/blob/main/version/version.sh)

To perform a proper Docker build, you must currently set these tags via [`GOFLAGS`](https://golang.org/cmd/go/#hdr-Environment_variables) and run the following in a script file (be careful with the quotation marks):
```
./version/version.sh
GOFLAGS='xversion -ldflags '"-X tailscale.com/version.Long=${VERSION_LONG} -X tailscale.com/version.Short=${VERSION_SHORT} -X tailscale.com/version.GitCommit=${VERSION_GIT_HASH}"
docker build -t tailscale:tailscale .
```

If any of the populated variables have spaces or certain punctuation, the escaping gets tricky, so hopefully these avoid that.

**Comment by DentonGentry** [comment] 2021-02-08 14:19
For unprivileged LXC, tun can be enabled in the conf file for the container. For example using Proxmox to host as unprivileged LXC with ID 112, the following lines would be added to /etc/pve/lxc/112.conf
lxc.cgroup.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file

Alternately this looks like it should work, though I've only used the permissions setting above in my own LXCs: 
lxc.cap.keep = net_admin

**Comment by pirate** [comment] 2021-02-18 04:37
FWIW I've been using tailscale in Docker Compose projects in production for ~4 months now with no issues.

Here's my working `docker-compose.yml` setup (builds directly from this repo, instead of using a fan-made docker hub image):
https://gist.github.com/pirate/1996d3ed6c5872b1b7afded250772f7c#file-docker-compose-yml-L15

Hopefully it helps anyone finding this issue via google.

**Comment by brybalicious** [comment] 2021-02-28 00:53
Hi all,
I've just posted a question on the [tailscale forum](https://forum.tailscale.com/t/using-tailscale-from-docker-containers/127/5) seeking an answer for how to set up the `tailscaled` daemon when building a docker image from a single Dockerfile. The purpose is to set up a VM from a container image directly on Google Cloud Compute Engine which runs a [dedicated server](https://cdn2.unrealengine.com/unreal-engine-multi-user-cloud-setup-360515954.pdf) for a component of Unreal Engine, making use of tailscale.

As per the post, everything else builds fine, but docker won’t build the layer that includes starting the tailscale daemon tailscaled. I understand that I need to enable the TUN adapter. However, it doesn’t seem to work when implemented as RUN layers in the Dockerfile:
```
RUN mkdir /var/lib/tailscale \
    && mkdir /dev/net \
    && mknod /dev/net/tun c 10 200

RUN tailscaled \
    && tailscale up -authkey "${TAILSCALE_KEY}"
```
I get the following errors upon running docker build:
![image](https://user-images.githubusercontent.com/8712034/109404549-8b43c980-7967-11eb-9bf2-175cc4f45c8b.png)

How can I set up tailscaled in the build stage? I understand that I need to run the image with flags along the lines of:
`docker run -dit -p 7000:7000/udp --cap-add=NET_ADMIN --device=/dev/net/tun:/dev/net/tun repo:imagename`
but as mentioned, it gets held up in the build stage seemingly because the adapter doesn’t exist.

Is it best to use the Tailscale docker image in a multi-stage build? Is `tailscaled` only supposed to be run in the CMD stage (not a RUN layer?). Help appreciated!

**Comment by brybalicious** [comment] 2021-02-28 01:11
https://github.com/tailscale/tailscale/issues/634#issuecomment-668236376

**Comment by brybalicious** [comment] 2021-02-28 01:55
Note, checked [`Linux kernel version: 4.19.128-microsoft-standard`](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/4.19.128-microsoft-standard) and the official docs on creating the device node for the [Universal TUN/TAP Device Driver](https://www.kernel.org/doc/html/latest/networking/tuntap.html) and realised that I don't have the latest WSL2 kernel version. This led me to https://github.com/tailscale/tailscale/issues/562 Could be an issue with WSL2 kernel (link to [update kernel version](https://github.com/microsoft/WSL2-Linux-Kernel/releases). )?

There's something I'm not understanding about Docker build then. I didn't think the kernel version of the machine where I'm performing the build would matter... so much as the FROM image at the beginning the Dockerfile. Seemingly [buildx](https://docs.docker.com/buildx/working-with-buildx/) targeting linux amd64 could help i.e. `docker buildx build --platform linux/amd64 .`?

**Comment by bradfitz** [comment] 2021-02-28 03:00
@brybalicious, you're trying to do privileged operations (use /dev/net/tun, via tailscaled) from a "docker build" step. As far as I know, that's not possible.

I don't think this is a good strategy, baking your auth key into your container:

```
RUN tailscaled \
    && tailscale up -authkey "${TAILSCALE_KEY}"
```

Just build tailscaled and then when you run it later, then do the `up` step. I filed #1412 for what you probably want.

**Comment by mikeburgh** [comment] 2021-02-28 04:15
You might find this handy as well, it builds a version with docker, and then on running handles the tun side
https://github.com/deasmi/unraid-tailscale

**Comment by brybalicious** [comment] 2021-02-28 10:48
Thanks for your prompt responses @bradfitz @mikeburgh. Ah okay. I'm using the auth key like that just for debug, but then will switch over to passing via the [--secret tag from buildkit](https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-secret-information). Does that seem reasonable?

So, a clarifying question is... how to build `tailscaled` in this manner, without running into this TUN problem during build? Do you suggest running a multi-staged build pulling from the Dockerfile provided by @mikeburgh, and then basically placing anything to do with setting up `/dev/net/tun`, `tailscaled`, `tailscale up` after the ENTRYPOINT? Or is it enough to simply use apt to install tailscale, and then place the rest after the ENTRYPOINT? Thanks

**Comment by mikeburgh** [comment] 2021-03-01 19:59
@brybalicious it should not matter if you use a package manager (apt etc) or multi stage build to get the docker image built.. but my understanding is you will need to do the TUN work in an entry point script (or similar approach) since that's when the image is actually running.

**Comment by brybalicious** [comment] 2021-03-01 20:43
gotcha. Thanks.

**Comment by brybalicious** [comment] 2021-03-02 12:47
Somehow the [ONBUILD](https://docs.docker.com/engine/reference/builder/#onbuild) instruction seems to be useful here... though perhaps this would just result in the same situation where the TUN adapter cannot be created, nor the daemon started from a RUN instruction inside the build stage...

**Comment by brybalicious** [comment] 2021-03-03 23:08
> @brybalicious, you're trying to do privileged operations (use /dev/net/tun, via tailscaled) from a "docker build" step. As far as I know, that's not possible.
> 
> I don't think this is a good strategy, baking your auth key into your container:
> 
> ```
> RUN tailscaled \
>     && tailscale up -authkey "${TAILSCALE_KEY}"
> ```
> 
> Just build tailscaled and then when you run it later, then do the `up` step. I filed #1412 for what you probably want.

Any ideas on how to pass the authkey in a secure manner to the docker container's entrypoint script at runtime without having to implement a remote secret store, or a swarm? Managed to get all the rest to work securely at build time.

**Comment by pirate** [comment] 2021-03-04 00:09
Why not use environment variables or a volume with a file in it to load the key? If you make it a one-time key you don't have to worry about it lingering around in the environment, as it would be harmless for another process to find it, the key doesn't do anything after the first use.

**Comment by brybalicious** [comment] 2021-03-04 17:01
> Why not use environment variables or a volume with a file in it to load the key? If you make it a one-time key you don't have to worry about it lingering around in the environment, as it would be harmless for another process to find it, the key doesn't do anything after the first use.

Hm good point about the one-time key... could be an easy process for a user to pass that as a runtime environment variable... but then every time they suspend or stop the VM, wouldn't this mean they'd need to generate a new key?

**Comment by pirate** [comment] 2021-03-04 17:07
Nope, just make sure you mount `/var/lib/tailscale` as a volume and the tailscale auth state will be preserved between container restarts, no need for a new key on every launch.
```yml
services:
    tailscale1:
        ...
        volumes:
            ...
            - ./tailscale_state:/var/lib/tailscale
```

**Comment by orrc** [comment] 2021-03-17 23:17
Thanks a lot for the [Gist](https://gist.github.com/hamishforbes/2ac7ae9d7ea47cad4e3a813c9b45c10f), @hamishforbes!

I'm running Tailscale 1.6.0 `arm` in a Docker container on a Raspberry Pi, and adding `--advertise-exit-node` to the entrypoint script causes the node appears as an possible exit node in the admin panel, which I could then enable.

However, the admin panel also showed an error message saying "Unable to relay traffic".
(took me a while to notice, as the "Exit Node" tag remains blue, and just shows a tiny (i) icon)

I was able to remedy this error by passing one (or both) of these to `docker run`:
- `--host=net` (with sysctl [properly configured](https://tailscale.com/kb/1104/enable-ip-forwarding) on the host)
- `--sysctl net.ipv4.ip_forward=1 --sysctl net.ipv6.conf.all.forwarding=1`

Unfortunately, my Android phone doesn't appear to have any connectivity after selecting the RPi exit node.
The only thing I seem to get in the RPi logs, after asking Android to use this exit node is this, every few seconds:
```
magicsock: disco: d:afe481bb7d9101ce<-d:a417b72737f47698 ([yeguf], derp-4)  got call-me-maybe, 3 endpoints
```

So I'm not sure whether the issue is Docker / RPi / Android / me holding it wrong, or a combination…

But aside from my exit node issue, the Docker setup is pretty nice!

**Comment by DentonGentry** [comment] 2021-05-20 23:00
userspace support debuted in 1.6 for local containers.

In 1.8 the support was broadened to include Heroku and Google Cloud Run:
- https://tailscale.com/kb/1107/heroku/
- https://tailscale.com/kb/1108/cloudrun/

**Comment by StevenACoffman** [comment] 2021-05-21 20:32
FYI - A working cillium kubernetes + tailscale setup config got posted here: https://github.com/cilium/cilium/issues/16266

**Comment by unixfox** [comment] 2021-05-21 21:24
> FYI - A working cillium kubernetes + tailscale setup config got posted here: [cilium/cilium#16266](https://github.com/cilium/cilium/issues/16266)

Small note is that this is for accessing the network of an existing cilium cluster and not for having an encrypted network between every node by using tailscale and cilium (something that I would really want).

**Comment by DentonGentry** [comment] 2021-06-26 17:00
In 1.10 the userspace-networking mode added support for AWS Lambda.

**Comment by pratikbalar** [comment] 2021-07-08 05:00
Can anyone put Dockerfile here to kick-start ?

@StevenACoffman @DentonGentry @orrc @pirate @bradfitz

**Comment by DentonGentry** [comment] 2021-07-08 05:43
https://github.com/tailscale/tailscale/blob/main/Dockerfile

**Comment by pschulten** [comment] 2021-07-08 08:28
Now, this is an example of a clean Dockerfile, 😊

**Comment by abh** [comment] 2021-07-08 09:06
Why Alpine 3.11 instead of 3.14?  (Apologies if that's covered already elsewhere and I missed it).

**Comment by Xe** [comment] 2021-07-08 10:33
That's likely because the dockerfile is older and hasn't been updated. Speaking as an experienced Alpine user the dockerfile as-is should work fine if you replace 3.11 with 3.14.

**Comment by DentonGentry** [comment] 2021-07-21 06:14
In 1.12 the userspace-networking mode handles operation in container environments which do not have CAP_NET_ADMIN set.

At this point I'm going to close this as done, I think the support for containers and for serverless environments overall is pretty good. If there are specific environments which do not work or issues encountered, please open new bugs. This one is long and covers a number of issues already.

**Closed by DentonGentry** 2021-07-21 06:14 UTC
Labels: L3 Some users, OS-kubernetes, P3 Can't get started, T6 Major usability, cloud, containers, infrastructure, on-hold

**Comment by brybalicious** [comment] 2021-08-09 10:40
Amazing. I will try out the new functionality next time I implement tailscale!

**Comment by metaskills** [comment] 2023-05-31 21:58
FWIW, I created a Lambda Container project with container packages that make it a bit easier thank Lambda layers. Details here https://github.com/rails-lambda/tailscale-extension
