### ISSUE TITLE
FR: round robin DNS addresses (maybe based on tags)

### ISSUE THREAD

**Issue by jessfraz** [tailscale/tailscale#6185] opened 2022-11-03 19:09 UTC
### What are you trying to do?

say we have deployed multiple instances of a service "vault" these each get their own unique hostname and DNS record in tailscale. but they are all the same service. 

it would be cool if there was a way to call a DNS record which round robins the addresses of the same service. kinda like consul DNS.

### How should we solve this?

I was thinking and you might have a better idea but based on tags. So for example, we would tag all these machines as "vault" then magic DNS would give us `vault.tag.{our-host}.ts.net`

and all the A records for all the machines tagged with "vault" would be returned. In the same sense that consul returns all the A records for all the "vault" services.

### What is the impact of not solving this?

we have to use consul and I'd love to rely on tailscale for all our DNS so we don't have this bifurcated system that uses some DNS from tailscale and some from consul. Also tailscale DNS comes out of the box on peoples desktops and consul is a whole _thing_ for people to set up locally for DNS.

**Comment by jessfraz** [comment] 2022-11-03 19:24
This is similar https://github.com/tailscale/tailscale/issues/5313

**Comment by DentonGentry** [comment] 2022-11-09 04:30
I think this is what https://github.com/tailscale/tailscale/issues/4324 also requests, creating a MagicDNS entry for all nodes carrying a given tag.

**Comment by DentonGentry** [comment] 2023-06-03 22:33
Duplicate of https://github.com/tailscale/tailscale/issues/4324

**Closed by DentonGentry** 2023-06-03 22:33 UTC
Labels: L3 Some users, P2 Aggravating, T0 New feature, dns, fr
