### ISSUE TITLE
Upgrade issue from version 1.50.1 to 1.56.1

### ISSUE THREAD

**Issue by metaad** [tailscale/tailscale#10746] opened 2024-01-05 09:16 UTC
### What is the issue?

Hi, I am attempting to upgrade Tailscale from version 1.50.1 to 1.56.1, but I'm encountering a fatal error 1603. The upgrade from 1.48.2 to 1.50.1 was successful. Could you please assist in resolving this issue? I am using Windows 10 64-bit OS. Attached are the logs for your reference.

[install.log](https://github.com/tailscale/tailscale/files/13840098/install.log)

### Steps to reproduce

Install 1.50.1 64Bit on win10 64bit VM
Try upgrading it using silent switches to version 1.56.1

### OS

Windows

### OS version

Windows 10

### Tailscale version

1.56.1

**Comment by nickkhyl** [comment] 2024-01-05 14:58
The [unstable build 1.57.40](https://pkgs.tailscale.com/unstable/tailscale-setup-1.57.40-amd64.msi) contains a fix for this issue. If you have a moment and are able to run an unstable release, could you try it out?

Duplicate of https://github.com/tailscale/corp/issues/16554

**Comment by metaad** [comment] 2024-01-08 04:02
Hi @nickkhyl ,

Thank you.
The unstable build has successfully upgraded the old version. Can you please let us know when it will be released as a stable version?

**Comment by DentonGentry** [comment] 2024-01-08 04:20
The 1.58 release is planned for mid January.

**Comment by agottardo** [comment] 2024-05-17 19:23
Closing due to inactivity.

**Closed by agottardo** 2024-05-17 19:23 UTC
Labels: OS-windows, L2 Few, P3 Can't get started, T5 Usability, bug
