### ISSUE TITLE
Tailscale is using about 25 % of my iPad's battery

### ISSUE THREAD

**Issue by ulfklose** [tailscale/tailscale#7810] opened 2023-04-06 09:37 UTC
### What is the issue?

I'm using Tailscale on both, my iPad and my iPhone. On my iPhone the battery usage is about 3 %, on my iPad it's more than 25 %. This behavior hasn't changed with any iOS or Tailscale update during the last three months or so. 

### Steps to reproduce

Using Tailscale on an iPad 8.

### OS

iOS

### OS version

iPadOS 16.4

### Tailscale version

1.38.4

### Bug report

BUG-e2a90e178a5c5d9b124b4ca165808df8ca203d62cc50546dbd324e571ef4f3b4-20230406093621Z-d31e02e2ed1c2226

**Comment by DentonGentry** [comment] 2023-04-06 09:58
We understand that battery consumption is still an issue in some circumstances. We have two engineers working on it and added metrics in 1.38.0 and 1.38.3 trying to diagnose what conditions lead to it.

Duplicate of https://github.com/tailscale/tailscale/issues/3363

**Closed by DentonGentry** 2023-04-06 09:58 UTC
Labels: needs-triage, bug

**Comment by mihaip** [comment] 2023-04-06 16:54
@ulfklose FWIW, the instrumentation that we added in 1.38.x shows that 70% of received data (and 55% of sent data) from Tailscale is DNS traffic. I would be curious if the battery use changes if you temporarily disable using Tailscale's DNS settings on your iPad (especially the NextDNS configuration).

**Comment by mihaip** [comment] 2023-04-07 23:45
On the admin panel's DNS settings page (https://login.tailscale.com/admin/dns) you can (temporarily) disable the "Override local DNS" option:

![image](https://user-images.githubusercontent.com/513813/230692719-d129f720-62cd-414c-bccd-7fad0dc8f059.png)
