### ISSUE TITLE
apt-get purge does not remove existing configuration

### ISSUE THREAD

**Issue by JayDoubleu** [tailscale/tailscale#325] opened 2020-04-25 16:18 UTC
**Describe the bug**
apt-get purge does not remove tailscale configuration

**To Reproduce**
1. install tailscale on ubuntu 18.04 using official instructions
2. log in to tailscale via running ```tailscale up```
3. purge tailscale via ```apt-get purge tailscale```
4. install tailscale again using ```apt-get install tailscale```
5. run ```tailscale up```

**Expected behavior**
Tailscale should prompt to login as it should be treated as new installation

**Actual behavior**
- ```tailscale up``` returnsv the following:
```
sudo tailscale up

tailscaled is authenticated, nothing more to do.
```
- tailscale is still authenticated with previous installation configuration

**Screenshots**

**Version information:**
 - Device: VM
 - OS: Linux
 - OS version: Ubuntu 18.04
 - Tailscale version: 0.98.0~0

**Comment by DentonGentry** [comment] 2021-11-10 00:49
https://github.com/tailscale/tailscale/issues/134 might make this easier.

**Comment by danderson** [comment] 2021-11-25 21:46
Dupe of #1007, fixed long ago. The debian package deletes state on purge.

**Closed by danderson** 2021-11-25 21:46 UTC
Labels: packaging, L2 Few, P1 Nuisance, T2 Visual Polish
