### ISSUE TITLE
FR: Better Grouping with Mullvad Exit Nodes

### ISSUE THREAD

**Issue by TheWaywardPilot** [tailscale/tailscale#10654] opened 2023-12-20 05:40 UTC
### What are you trying to do?

I work in the airline industry and frequently in a different US state and city, sometimes in a different country. As I'm usually trying to connect to a Mullvad exit node that is close to my location for improved upload/download speeds. The laundry list of available nodes is rather cumbersome and could use some sorting by country, state, city, etc. 

### How should we solve this?

As stated above, simply providing better sorting in the GUI for Windows and Mac (and any potential future Linux GUI) by Country, State, and/or City.

### What is the impact of not solving this?

The impact isn't huge, just saving a few minutes each day as I'm in a different location each day for half the month when I'm on the road, usually on alternate coasts of the US. I does add up over time thought. 

### Anything else?

I understand there is a good chance I'm a niche case and there isn't much demand for what I'm asking. But, if it's an easy solution I'd love to see it! I appreciate all that the Tailscale and Mullvad teams do, I'm super appreciative of the partnership. If this is an easy implementation that would be awesome, but I'm also just happy with the partnership and what I have now. Thanks to both the Tailscale and Mullvad teams!

**Comment by LrrrAc** [comment] 2024-01-18 03:34
Ill add a separate need for this: I lose my devices in the exit node list. Going from 7 in a drop down to what I'm sure is a bragging point on Mullvad's website is a bit jarring. And then finding Sweden is a task.

**Comment by catzkorn** [comment] 2024-02-07 21:33
I'm going to close this issue as a dupe of #9421, but we will update that issue when we have made improvements.

**Closed by catzkorn** 2024-02-07 21:33 UTC
Labels: OS-windows, fr
