### ISSUE TITLE
FR: Don't route subnet when connected to smaller subnet

### ISSUE THREAD

**Issue by charlespick** [tailscale/tailscale#6050] opened 2022-10-25 02:28 UTC
### What are you trying to do?

Save bandwidth and cpu cycles on subnet routers on complex networks. When I'm connected to the network that is being routed through a subnet router, don't route that traffic through Tailscale to save resources on the subnet router and improve performance for the user. 

### How should we solve this?

When the locally connected subnet is smaller than a routed subnet, don't register that subnet for routing through tailscale with the system. For example, if I route 10.3.0.0/16 through a subnet router but my ip address is 10.3.3.0/24, assume that I am locally connected to that network. If I try to reach 10.3.2.18/24, it will go through the local router. If I still need these subnets to be routed through Tailscale I would route them separately instead of together in a /16 which would give the same functionality we have today. 

### What is the impact of not solving this?

If I have a remote network or I want to connect to Tailscale only devices, I need to sacrifice performance of local resources. Or I need to setup routing for all my remote networks and the Tailscale network to my subnet router and disable snat on my subnet router which is a much more complex setup.

**Comment by DentonGentry** [comment] 2022-10-25 03:06
I think this is fundamentally https://github.com/tailscale/tailscale/issues/1227, to use local routes when available. While this is a reasonable request, it is also reasonable to be concerned about the public hotspot Wi-Fi overlapping with the corporate IPs and hijacking the routes.

**Comment by DentonGentry** [comment] 2022-10-26 05:01
Duplicate of https://github.com/tailscale/tailscale/issues/1227

**Closed by DentonGentry** 2022-10-26 05:01 UTC
Labels: needs-triage, fr, needs-dedup
