### ISSUE TITLE
Regression in DNS on Windows

### ISSUE THREAD

**Issue by mausch** [tailscale/tailscale#5575] opened 2022-09-08 16:29 UTC
### What is the issue?

I've just upgraded Tailscale to 1.30.0 from 1.28 on Windows and my internal DNS stopped working.
1.30.0 works fine on my Ubuntu machine, though two coworkers say this upgrade has broken DNS on their Ubuntu machines too.
Reverting to 1.28.0 makes it work again.

Some details about my setup:
I have a Tailscale node in AWS exposing two AWS subnets and I have an AWS DNS registered in https://login.tailscale.com/admin/dns . With this I can resolve internal AWS Route53 entries from any node connected to my tailnet.

It seems that 1.30 has changed something that broke this. Maybe something related to MagicDNS (though I never enabled it):

With 1.30:

```
>nslookup build4.elevate.internal
Server:  magicdns.localhost-tailscale-daemon
Address:  100.100.100.100

*** magicdns.localhost-tailscale-daemon can't find build4.elevate.internal: Non-existent domain
```

With 1.28:

```
>nslookup build4.elevate.internal
Server:  dns.google
Address:  2001:4860:4860::8888

*** dns.google can't find build4.elevate.internal: Non-existent domain
```

where `build4.elevate.internal` is an internal DNS entry defined in AWS Route53.
Not sure why nslookup can't resolve it but it works 🤷‍♂️ 

Many thanks.

### Steps to reproduce

Upgrade from 1.28 to 1.30

### Are there any recent changes that introduced the issue?

Something between 1.28 and 1.30 I guess?

### OS

Windows

### OS version

10

### Tailscale version

1.30.0

### Bug report

BUG-6650c1487d5a83cfe80b89f651cc91e3af41cf45d24ef87a342b3a08c73658ab-20220908162258Z-929950c0072b87c2

**Comment by bradfitz** [comment] 2022-09-08 18:01
Your tailnet's DNS config is configured with both 172.16.0.2 (via a subnet router) and Google Public DNS.

So Tailscale tells the operating system to use both of those and the operating system picks one randomly and/or races them against each other. They're not in a priority order.

I don't think this is related to 1.30.0.

More likely, this is related to a server-side bug where we were sending down some MagicDNS names even in cases where MagicDNS was disabled on a tailnet, which could've caused some tailnet configurations to go into a shove-all-DNS-through-100.100.100.100 path.

But your DNS config was basically depending on a combination of luck & a server-side bug to work as you wanted.

If you want *.internal to go to a different DNS server, you need to add configure it as Split DNS in the admin console.

I'm going to close this bug because I think code-wise everything's working as expected, but please email support@ if you the Split DNS config doesn't solve your problem.

I'll also start a discussion about making the admin console warn about such configs, as they're unlikely to do what users expect.

**Closed by bradfitz** 2022-09-08 18:01 UTC
Labels: needs-triage, bug

**Comment by mausch** [comment] 2022-09-09 08:03
Cheers, I registered the private DNS server as "Split DNS" now and things seem to work again.
I'm pretty sure that this Split DNS option didn't exist back when I set up the account initially.
I'm guessing many others will be in my same situation? Technically, if things worked with 1.28 and stopped working with 1.30 it would be a regression?
Anyway my issue is fixed so thanks again! 👍

**Comment by DentonGentry** [comment] 2022-09-09 11:57
We can't consider changes in race conditions to be regressions, the only way to fix those is to never change anything in the software.

We're planning to make changes in the admin panel to flag when a global DNS resolver is racing a local DNS resolver, as that doesn't generally do what people want it to do.
