### ISSUE TITLE
ACL preview results are inconsistent with my acls.

### ISSUE THREAD

**Issue by christopher-cavnue** [tailscale/tailscale#4573] opened 2022-04-29 16:12 UTC
### What is the issue?

My ACLs seem to be working as intended, but when I use the preview, the results don't make sense.

### Steps to reproduce

Check a user in the preview.(e.g. yiyaho@cavnue.com)  and compare to the actual ACL rules.

### Are there any recent changes that introduced the issue?

I did update the ACLs in a big way.

But I  temporarily put the old ACLs back and saw the same behavior.

### OS

Other

### OS version

N/A

### Tailscale version

N/A

**Comment by DentonGentry** [comment] 2022-05-07 13:14
To make progress on this we'll need more details on what is wrong in the preview, it isn't routinely broken for everyone. If you're not comfortable putting that on a public bug we can correspond through support@tailscale.com

**Comment by christopher-cavnue** [comment] 2022-05-09 16:30
This doesn't match what I expect:

[image: image.png]

Christopher Hoover  |  V.P. Hardware Engineering

www.cavnue.com

**Comment by ewu00** [comment] 2022-07-14 16:32
This has been broken for us since day one. Basically the resulting access and the list of users/groups/tags doesn't match up in the sense that it's offset by a few, maybe 3 or so (harder to track now). So if you look at the access for the 3rd or 4th user in the list, it corresponds to 1st and 2nd. It's consistent offset as you go down the list.

**Comment by jshayden** [comment] 2022-08-16 21:23
I have this same problem. Something as simple as adding a user to a group shows the user being in an entirely different group at the "Preview rules" screen.

Some testing confirms that the ACLs are, in fact, working, and it is the preview screen that is incorrect. But, this sure makes validating complex ACLs difficult.

**Comment by legowerewolf** [comment] 2022-10-12 23:18
Even something as simple as this seems to confuse it.

```jsonc
{ // User-owned devices can access each other
    "Action": "accept",
    "Users":  ["autogroup:members"],
    "Ports":  ["autogroup:self:*"],
},
```

I should show up as having access to a machine authenticated as myself, for example, but I get the "This service is not accessible to any users in your network." message when I check any of my devices' service lists.

**Comment by mayakacz** [comment] 2022-12-09 17:51
I've tried to replicate with no success. Can someone share an ACL that fails? (Please omit any PII if posting here, or [contact support](https://tailscale.com/contact/support) and reference this issue.)

> in the sense that it's offset by a few, maybe 3 or so (harder to track now). So if you look at the access for the 3rd or 4th user in the list, it corresponds to 1st and 2nd

I've heard this before, but can't replicate it.

> I get the "This service is not accessible to any users in your network." message when I check any of my devices' service lists.

Are you looking at who can access a "dst"?
The preview rules are directional, so you can only select a "src" from an ACL, and see what "dst" it has access to; not the "dst" and see which "src" have access to it. (There is a view of what "src" can access a particular "dst" though in the Services tab.)

**Comment by phirework** [comment] 2023-02-08 21:40
We pushed a fix for this last week, can folks confirm whether they're still experiencing this issue?

**Comment by DentonGentry** [comment] 2023-06-03 13:55
Please reopen if the issue is seen again.

**Closed by DentonGentry** 2023-06-03 13:55 UTC
Labels: L1 Very few, P2 Aggravating, T5 Usability, bug
