### ISSUE TITLE
freebsd: v6 programming fails

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1307] opened 2021-02-09 21:05 UTC
Turning off v6 programming on freebsd for now, but it's going to need a fix so that it sets IPv6 routes correctly.

**Comment by mkramlich** [comment] 2021-02-11 22:17
I'll fix this via my #1201 fixes, since the code overlaps a bit. may just need assistance by folks to run it on a FreeBSD to confirm

**Comment by bradfitz** [comment] 2021-02-12 03:56
I submitted 88ab0173a7b46b5768fa907c0b3eb655f677c708 which fixed macOS's IPv6 (I had to set `TS_DEBUG_CONTROL_FLAGS=v6-overlay` for testing), and I thought it might also fix FreeBSD so I spun up a FreeBSD VM on DigitalOcean but no go.

I've read and re-read the `ifconfig` man page but nothing I try works. e.g. a bunch of variants like:

```
 # ifconfig tailscale0 inet6 fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b prefixlen 128
ifconfig: ioctl (SIOCAIFADDR): File exists
# ifconfig tailscale0 inet6 fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b add
ifconfig: ioctl (SIOCAIFADDR): File exists
```

Then searching around, I found https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=218508 ("Tunneling and aliases using the tun device, reusing a destination address works with IPv4, but not IPv6") which sounds like maybe what we're hitting?

I really hope we don't need two TUN devices on FreeBSD.

**Comment by bradfitz** [comment] 2021-02-12 04:14
@DentonGentry, you know FreeBSD more than any of us I think. Any thoughts?

**Comment by mkramlich** [comment] 2021-02-12 04:16
@bradfitz ok nice. your commit is a smaller subset approach of what I was aiming for to address 1201, but you pushed yours up faster. if you'd like feel free to assign this to me, since the userbase percentage seems low enough you dont need a solution quite as fast. but it would give us another platform checkbox once resolved, and I'm still intimate with this area

**Comment by bradfitz** [comment] 2021-02-12 04:24
I'll leave this unassigned. Let's let FreeBSD folk hack on it.

**Comment by DentonGentry** [comment] 2021-02-22 23:10
I don't know the difference, but that exact command worked for me:

```
root@OPNsense:/home/dgentry # ifconfig tailscale0 inet6 fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b add
root@OPNsense:/home/dgentry # ifconfig tailscale0
tailscale0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1280
	options=80000<LINKSTATE>
	inet 100.92.61.18 --> 100.92.61.18 netmask 0xffffffff
	inet6 fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b prefixlen 64
	groups: tun
	nd6 options=103<PERFORMNUD,ACCEPT_RTADV,NO_DAD>
	Opened by PID 56618
root@OPNsense:/home/dgentry # uname -a
FreeBSD OPNsense.localdomain 12.1-RELEASE-p12-HBSD FreeBSD 12.1-RELEASE-p12-HBSD #0  0857355c1c2(stable/20.7)-dirty: Mon Jan 18 18:12:55 CET 2021     root@sensey:/usr/obj/usr/src/amd64.amd64/sys/SMP  amd64
```

**Comment by DentonGentry** [comment] 2021-02-23 00:04
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=218508 is specifically about an alias address, which is still broken for IPv6 on FreeBSD 12.1:

```
root@OPNsense:/home/dgentry # ifconfig tun1 create
root@OPNsense:/home/dgentry # ifconfig tun1 inet6 fdaa:abc:abc:abc::1 fe80::111:0 prefixlen /128
root@OPNsense:/home/dgentry # ifconfig tun1 inet6 alias fe80::111:1 fe80::111:0 prefixlen /128
ifconfig: ioctl (SIOCAIFADDR): File exists
root@OPNsense:/home/dgentry #
```

**Comment by DentonGentry** [comment] 2021-02-23 00:27
```
root@OPNsense:~ # ktrace -i ifconfig tun1 inet6 fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b prefixlen 128
ifconfig: ioctl (SIOCAIFADDR): File exists
root@OPNsense:~ # kdump
 64515 ktrace   RET   ktrace 0
 64515 ktrace   CALL  execve(0x65a42229f810,0x65a42229fd50,0x65a42229fd90)
 64515 ktrace   NAMI  "/sbin/ifconfig"
 64515 ktrace   NAMI  "/libexec/ld-elf.so.1"
 ...
 64515 ifconfig CALL  socket(PF_INET6,0x2<SOCK_DGRAM>,IPPROTO_IP)
 64515 ifconfig RET   socket 3
 64515 ifconfig CALL  mmap(0,0x5000,0x3<PROT_READ|PROT_WRITE>,0x1002<MAP_PRIVATE|MAP_ANON>,0xffffffff,0)
 64515 ifconfig RET   mmap 4567458488320/0x42771bda000
 64515 ifconfig CALL  ioctl(0x3,SIOCDIFADDR_IN6,0xd7d4b22328)
 64515 ifconfig RET   ioctl -1 errno 49 Can't assign requested address
 64515 ifconfig CALL  ioctl(0x3,SIOCAIFADDR_IN6,0xd7d4b22328)
 64515 ifconfig RET   ioctl -1 errno 17 File exists
 64515 ifconfig CALL  write(0x2,0x65bf7637c1e0,0xa)
 64515 ifconfig GIO   fd 2 wrote 10 bytes
       "ifconfig: "
 64515 ifconfig RET   write 10/0xa
 64515 ifconfig CALL  write(0x2,0x65bf7637c2e0,0x13)
 64515 ifconfig GIO   fd 2 wrote 19 bytes
       "ioctl (SIOCAIFADDR)"
 64515 ifconfig RET   write 19/0x13
 64515 ifconfig CALL  write(0x2,0x427717beea5,0x2)
 64515 ifconfig GIO   fd 2 wrote 2 bytes
       ": "
 64515 ifconfig RET   write 2
 64515 ifconfig CALL  write(0x2,0x65bf7637c1e0,0xc)
 64515 ifconfig GIO   fd 2 wrote 12 bytes
       "File exists
       "
```

**Comment by DentonGentry** [comment] 2021-02-23 03:23
OPNsense doesn't have DTrace enabled in its default kernel and I don't really want to screw around with my router right now rebooting into new kernels, so I installed FreeBSD 12.2 in a VM.

```
root@freebsd12:~ # dtrace -n 'fbt:::return /(int)arg1 == EEXIST / { stack(); }' -c "ifconfig tun0 inet6 fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b prefixlen 128"
dtrace: description 'fbt:::return ' matched 29364 probes
ifconfig: ioctl (SIOCAIFADDR): File exists
dtrace: pid 1175 exited with status 1
CPU     ID                    FUNCTION:NAME
  1  52657            rtrequest1_fib:return
              kernel`rtinit+0x421
              kernel`in6_update_ifa+0xc6b
              kernel`in6_control+0x96f
              kernel`ifioctl+0x47f
              kernel`kern_ioctl+0x2b7
              kernel`sys_ioctl+0xfa
              kernel`amd64_syscall+0x387
              kernel`0xffffffff8106785e

  1  52816                    rtinit:return
              kernel`in6_update_ifa+0xc6b
              kernel`in6_control+0x96f
              kernel`ifioctl+0x47f
              kernel`kern_ioctl+0x2b7
              kernel`sys_ioctl+0xfa
              kernel`amd64_syscall+0x387
              kernel`0xffffffff8106785e

  1  52599                   ifa_ref:return
              kernel`in6_update_ifa+0xcd0
              kernel`in6_control+0x96f
              kernel`ifioctl+0x47f
              kernel`kern_ioctl+0x2b7
              kernel`sys_ioctl+0xfa
              kernel`amd64_syscall+0x387
              kernel`0xffffffff8106785e

  1  55124            in6_update_ifa:return
              kernel`in6_control+0x96f
              kernel`ifioctl+0x47f
              kernel`kern_ioctl+0x2b7
              kernel`sys_ioctl+0xfa
              kernel`amd64_syscall+0x387
              kernel`0xffffffff8106785e

  1  54979               in6_control:return
              kernel`ifioctl+0x47f
              kernel`kern_ioctl+0x2b7
              kernel`sys_ioctl+0xfa
              kernel`amd64_syscall+0x387
              kernel`0xffffffff8106785e

  1  39608                   ifioctl:return
              kernel`kern_ioctl+0x2b7
              kernel`sys_ioctl+0xfa
              kernel`amd64_syscall+0x387
              kernel`0xffffffff8106785e

  1  51074                kern_ioctl:return
              kernel`sys_ioctl+0xfa
              kernel`amd64_syscall+0x387
              kernel`0xffffffff8106785e

  1  28488                 sys_ioctl:return
              kernel`amd64_syscall+0x387
              kernel`0xffffffff8106785e

  1  57861             amd64_syscall:return
              kernel`0xffffffff8106785e
```

The trace from in6_update_ifa back up to amd64_syscall makes sense, I think. Something in in6_update_ifa is returning EEXIST. I don't understand the calls to rtinit and rtrequest1_fib; routing table? I'm going to have to dig around in cscope for a while on how it gets from in6_update_ifa over there.

**Comment by DentonGentry** [comment] 2021-02-23 04:52
It was confusing because I was looking at HEAD of the FreeBSD tree, and this part of the kernel has undergone quite a bit of change since the 12.2 release. Checking out releng/12.2 is much more informative.

I think rtrequest1_fib fails because rnh->rnh_addaddr (which points to in6_addroute) returned NULL.

```
int
rtrequest1_fib(int req, struct rt_addrinfo *info, struct rtentry **ret_nrt,
                                u_int fibnum)
{
...
                if (rn == NULL) {
                        ifa_free(rt->rt_ifa);
                        R_Free(rt_key(rt));
                        uma_zfree(V_rtzone, rt);
                        return (EEXIST);
                }
```


```
root@freebsd12:~ # dtrace -n 'fbt::rn_addroute:return /(int)arg1 == 0 / { stack(); }' -c "ifconfig tun0 inet6 fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b prefixlen 128"
dtrace: description 'fbt::rn_addroute:return ' matched 1 probe
ifconfig: ioctl (SIOCAIFADDR): File exists
dtrace: pid 1312 exited with status 1
CPU     ID                    FUNCTION:NAME
  0  52916               rn_addroute:return
              kernel`rtrequest1_fib+0x9b0
              kernel`rtinit+0x421
              kernel`in6_update_ifa+0xc6b
              kernel`in6_control+0x96f
              kernel`ifioctl+0x47f
              kernel`kern_ioctl+0x2b7
              kernel`sys_ioctl+0xfa
              kernel`amd64_syscall+0x387
              kernel`0xffffffff8106785e
```

**Comment by DentonGentry** [comment] 2021-02-23 16:28
It is getting harder to pull information I want using DTrace alone, so I'm compiling a kernel with some more logging. Of course, the VM I created had too small a disk for that so I'm making a new VM first.

**Comment by DentonGentry** [comment] 2021-02-23 18:08
https://xkcd.com/303/

**Comment by DentonGentry** [comment] 2021-02-24 15:55
Current status is that the log(LOG_ERR, ...) calls I've added in /usr/src/sbin/routed/radix.c are not being hit and nothing makes sense.

I'm undoubtedly holding it wrong, in some way. I've checked that it seems to have actually booted the kernel I built, but somehow I think it is just not running what I think it is running.

**Comment by DentonGentry** [comment] 2021-02-25 00:27
I was holding it wrong. net/sbin/routed is the routing daemon and does not run in the kernel at all. I mistook it for sys/net/radix.c, which is very similar code and has many of the same routine names. Adding the same log() statements in sys/net/radix.c is much more informative.

rn_addroute: rn_addmask returned NULL
rtrequest1_fib: rnh_addaddr returned NULL

So rn_addmask does return NULL. I think DTrace might have missed this because it is a leaf routine, and maybe being inlined? Not sure.

There are a few places in rn_addmask which could return NULL, but the most obvious is if the route + mask is already present in the tree. I've added more logging, still hopeful we can find a way to avoid the problem.

https://xkcd.com/303/

**Comment by DentonGentry** [comment] 2021-02-25 12:35
Confirmed that with RADIX_MPATH defined in the kernel config we can configure the tun0 device.

```
root@freebsd12:~ # ifconfig tun0 create
root@freebsd12:~ # ifconfig tun0 inet6 fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b prefixlen 128
root@freebsd12:~ #
```

This doesn't help all that much, as we'd still have to disable distributing IPv6 routes to FreeBSD machines since they wouldn't work in the default kernel.

Presumably the kernel thinks there is a duplicate because the tunnel endpoints are the same, expecting hairpinning. Next step is to remove RADIX_MPATH again and focus on how IPv4 on tun0 manages to work.

https://xkcd.com/303/

**Comment by DentonGentry** [comment] 2021-02-25 13:12
It looks like they knew it:

```
sys/netinet6/in6.c:
/*
 * Notifies other subsystems about address change/arrival:
 * 1) Notifies device handler on the first IPv6 address assignment
 * 2) Handle routing table changes for P2P links and route
 * 3) Handle routing table changes for address host route
 */
static int
in6_notify_ifa(struct ifnet *ifp, struct in6_ifaddr *ia,
    struct in6_aliasreq *ifra, int hostIsNew)
{
...
        /*
         * If a new destination address is specified for a point-to-point
         * interface, install a route to the destination as an interface
         * direct route.
         * XXX: the logic below rejects assigning multiple addresses on a p2p.  <-- HERE
         * interface that share the same destination.
         */
        plen = in6_mask2len(&ia->ia_prefixmask.sin6_addr, NULL); /* XXX */
        if (!(ia->ia_flags & IFA_ROUTE) && plen == 128 &&
            ia->ia_dstaddr.sin6_family == AF_INET6) {
                int rtflags = RTF_UP | RTF_HOST;
                /*
                 * Handle the case for ::1 .
                 */
                if (ifp->if_flags & IFF_LOOPBACK)
                        ia->ia_flags |= IFA_RTSELF;
                error = rtinit(&ia->ia_ifa, RTM_ADD, ia->ia_flags | rtflags);
                if (error)
                        goto done;
                ia->ia_flags |= IFA_ROUTE;
        }
```

That comment was written in 2004.

**Comment by DentonGentry** [comment] 2021-02-25 15:40
I updated https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=218508 with current findings.

I'm losing hope that we will come up with a way to work around this issue in a default kernel.

**Comment by crawshaw** [comment] 2021-02-25 16:31
Could we create a new tun interface for ipv6?

**Comment by DentonGentry** [comment] 2021-02-25 16:38
It fails without IPv4 being involved:

```
root@freebsd12:~ # ifconfig tun0 create
root@freebsd12:~ # ifconfig tun0 inet6 fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b prefixlen 128
ifconfig: ioctl (SIOCAIFADDR): File exists
root@freebsd12:~ # ifconfig tun0
tun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1500
	options=80000<LINKSTATE>
	groups: tun
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
root@freebsd12:~ #
```

**Comment by bradfitz** [comment] 2021-02-25 16:50
Does IPv6 work at all for TUN? Or is it just /128s that don't work? Can we route our whole ULA into TUN?

**Comment by DentonGentry** [comment] 2021-02-25 16:55
So far as I can see, being a /128 is part of the issue. The code which returns EEXIST only runs for /128:

```
        /*
         * If a new destination address is specified for a point-to-point
         * interface, install a route to the destination as an interface
         * direct route.
         * XXX: the logic below rejects assigning multiple addresses on a p2p
         * interface that share the same destination.
         */
        plen = in6_mask2len(&ia->ia_prefixmask.sin6_addr, NULL); /* XXX */
        if (!(ia->ia_flags & IFA_ROUTE) && plen == 128 &&
            ia->ia_dstaddr.sin6_family == AF_INET6) {
```

I'd like to think that if IPv6 didn't work on TUN at all that it would have been addressed by now.

**Comment by bradfitz** [comment] 2021-02-25 16:59
Well that's an easy workaround then. I'll send a change for you to test.

**Comment by bradfitz** [comment] 2021-02-25 17:23
Actually I should stay focused. But I was thinking of something like:

```
root@brad-freebsd-test:~ # ifconfig tun0 create
root@brad-freebsd-test:~ # route -q -n add -6 fd7a:115c:a1e0::/48 -iface tun0
root@brad-freebsd-test:~ # ifconfig tun0 up
root@brad-freebsd-test:~ # ping6 fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b
PING6(56=40+8+8 bytes) 2604:a880:4:1d0::148:c000 --> fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b
ping6: sendmsg: Host is down
ping6: wrote fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b 16 chars, ret=-1
ping6: sendmsg: Host is down
ping6: wrote fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b 16 chars, ret=-1
^C
--- fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b ping6 statistics ---
```

Via something like:

```patch
bradfitz@tsdev:~/src/tailscale.com$ git di
diff --git a/wgengine/router/router_userspace_bsd.go b/wgengine/router/router_userspace_bsd.go
index fb81d62..bc02f17 100644
--- a/wgengine/router/router_userspace_bsd.go
+++ b/wgengine/router/router_userspace_bsd.go
@@ -10,6 +10,7 @@ import (
        "fmt"
        "log"
        "os/exec"
+       "runtime"
 
        "github.com/tailscale/wireguard-go/device"
        "github.com/tailscale/wireguard-go/tun"
@@ -101,9 +102,16 @@ func inet(p netaddr.IPPrefix) string {
        return "inet"
 }
 
+// See https://github.com/tailscale/tailscale/issues/1307#issuecomment-786045280
+func modifyConfigAsHackyFreeBSDBugWorkaround(cfg *Config) {
+
+}
+
 func (r *userspaceBSDRouter) Set(cfg *Config) (reterr error) {
        if cfg == nil {
                cfg = &shutdownConfig
+       } else if runtime.GOOS == "freebsd" {
+               modifyConfigAsHackyFreeBSDBugWorkaround(cfg)
        }
 
        var errq error
```

But it'd take me too long to ramp up on what works & doesn't here.

But then we'd need to also modify the TUN packet reading code to recognize when the source address isn't our own (when the kernel source address selection picked our global address, like above, rather than our ULA /128 which we don't have).

I think.

Maybe we can play with this together tomorrow as a Friday fun project if you're still interested then?

**Comment by DentonGentry** [comment] 2021-02-26 14:50
I'll try this (though maybe not today)

**Comment by DentonGentry** [comment] 2021-03-02 00:51
Since the code dealing with /128 changed significantly between FreeBSD 12.2 and HEAD, I tried it with a FreeBSD-current image built 2/25/2021. It displays the same behavior:

```
root@freebsd14:~ # ifconfig tun0 create
root@freebsd14:~ # ifconfig tun0 inet6 fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b prefixlen 128
ifconfig: ioctl (SIOCAIFADDR): File exists
root@freebsd14:~ # ifconfig tun0 inet6 fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b add
ifconfig: ioctl (SIOCAIFADDR): File exists
root@freebsd14:~ #
```

I'm working on an implementation as described in https://github.com/tailscale/tailscale/issues/1307#issuecomment-786068419

**Comment by DentonGentry** [comment] 2021-03-02 06:54
Step 1:
after 1.4.x we added credential checking, where "tailscale up" can only be executed by root. This currently supports Linux and MacOS. Minimal FreeBSD support added in https://github.com/DentonGentry/peercred/commit/4f6d60edfe502f60b62ffa4d77eab09104474bc9, so we can bring tailscale up with software built from HEAD.

At the time of this writing, FreeBSD 12.2 is the current stable release. It lacks a PID field in its Xucred structure, so the implementation above sets pid to 0. FreeBSD 13 is expected to be released at the end of March 2021, and adds a pid field. Retrieving the PID for FreeBSD 12.2 and before would need to implement a different API, likely SCM_CREDS. I'm just ignoring the PID for now, to make progress on this IPv6 issue.

In working on this I learned about how Go handles OS-specific code via file naming convention, which is trippy.

**Comment by danderson** [comment] 2021-03-03 05:13
So, we need to figure out what to do for the 1.6 release. Ideally, I'd like for freebsd to be able to advertise that it understands IPv6 configuration (i.e. won't choke on it), but skip v6 things when configuring the OS.

The reason I'd like this is that we normally indicate client capabilities via map request version, which ratchets upwards monotonically, and we don't have an obvious way to support "all except one thing from three versions ago". Conversely, if we make freebsd tell control that it understands v6, it's welcome to decline to use that configuration.

@DentonGentry WDYT? And, do we need to do something similar for openbsd?

**Comment by DentonGentry** [comment] 2021-03-03 12:23
I'm still struggling to get a workable mechanism for FreeBSD, using the method suggested in https://github.com/tailscale/tailscale/issues/1307#issuecomment-786068419

However I think I can instead make `modifyConfigForFreeBSDBugWorkaround()` just remove all of the IPv6 address config pretty quickly, in time for the bugfix/stabilization portion of the 1.6 release. Would that be workable?

----

Regarding OpenBSD, I installed OpenBSD 6.8 in a VM. It isn't affected by the same problem:
```
openbsd# ifconfig tun0 create
openbsd# ifconfig tun0 inet6 fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b prefixlen 128
openbsd# ifconfig tun0
tun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	index 5 priority 0 llprio 3
	groups: tun
	status: down
	inet6 fe80::34c5:e2ff:fe98:a32c%tun0 ->  prefixlen 64 scopeid 0x5
	inet6 fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b -> fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b prefixlen 128
```

**Comment by bradfitz** [comment] 2021-03-03 16:15
> I'm still struggling to get a workable mechanism for FreeBSD, using the method suggested in #1307 (comment)

Keep in mind I have no clue what I'm doing here so take my comment with a grain of salt. It was just a guess.

**Comment by DentonGentry** [comment] 2021-03-03 23:35
FreeBSD in main now should work even if Control sends it IPv6 addresses. The client will ignore IPv6 addresses locally, which is clearly not as good as having IPv6 really work, but is better than breaking the client.

**Comment by DentonGentry** [comment] 2021-03-03 23:48
../../wgengine/userspace.go has:

```
        if (runtime.GOOS == "darwin" || runtime.GOOS == "ios") && e.isLocalAddr(p.Dst.IP) {
                // macOS NetworkExtension directs packets destined to the
                // tunnel's local IP address into the tunnel, instead of
                // looping back within the kernel network stack. We have to
                // notice that an outbound packet is actually destined for
                // ourselves, and loop it back into macOS.
                t.InjectInboundCopy(p.Buffer())
                return filter.Drop
        }
```

Is that what we're trying to do via the equivalent of `ifconfig tun0 inet6 fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b fd7a:115c:a1e0:ab12:4843:cd96:625c:1f1b prefixlen 128` ?

If so, I guess we could make FreeBSD skip adding the /128 for itself and instead add it to the conditional there.

**Comment by DentonGentry** [comment] 2021-03-04 23:09
It is pretty dangerously hacked together at the moment, but I have something that I think will work for FreeBSD. FreeBSD is able to ping the IPv6 address of an Ubuntu system on my Tailnet.

```
root@freebsd12:~ # ifconfig tailscale0
tailscale0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1280
        options=80000<LINKSTATE>
        inet 100.95.208.20 --> 100.95.208.20 netmask 0xffffffff
        inet6 fd7a:115c:a1e0:ab12:4843:cd96:625f:d014 prefixlen 48
        groups: tun
        nd6 options=101<PERFORMNUD,NO_DAD>
        Opened by PID 927

root@freebsd12:~ # ping6 fd7a:115c:a1e0:ab12:4843:cd96:6254:d86f
PING6(56=40+8+8 bytes) fd7a:115c:a1e0:ab12:4843:cd96:625f:d014 --> fd7a:115c:a1e0:ab12:4843:cd96:6254:d86f
16 bytes from fd7a:115c:a1e0:ab12:4843:cd96:6254:d86f, icmp_seq=0 hlim=64 time=78.692 ms
16 bytes from fd7a:115c:a1e0:ab12:4843:cd96:6254:d86f, icmp_seq=1 hlim=64 time=3.449 ms
16 bytes from fd7a:115c:a1e0:ab12:4843:cd96:6254:d86f, icmp_seq=2 hlim=64 time=1.679 ms
^C
--- fd7a:115c:a1e0:ab12:4843:cd96:6254:d86f ping6 statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 1.679/27.940/78.692/35.895 ms
root@freebsd12:~ #
```

It adds the host address using `ifconfig tailscale0 inet6 fd7a:115c:a1e0:ab12:4843:cd96:625f:d014/48` instead of a 128 bit prefix, and it adds FreeBSD to the list of OSes needing userspace hairpinning in handleLocalPackets:

```
        if (runtime.GOOS == "darwin" || runtime.GOOS == "ios" || runtime.GOOS == "freebsd") && e.isLocalAddr(p.Dst.IP) {
                // macOS NetworkExtension directs packets destined to the
                // tunnel's local IP address into the tunnel, instead of
                // looping back within the kernel network stack. We have to
                // notice that an outbound packet is actually destined for
                // ourselves, and loop it back into macOS.
                t.InjectInboundCopy(p.Buffer())
                return filter.Drop
        }
```

Honestly at this moment I'm not even sure that the `handleLocalPackets` change is needed, I'm just happy to have something which appears to be working.

**Comment by bradfitz** [comment] 2021-03-04 23:15
@DentonGentry, try again with the https://github.com/tailscale/tailscale/commit/82edf94df72a52bcdc95fe37b20217e6003d92c0 change I just submitted?

Then you might only need the userspace hair pin part and removing the v6 self address in your modified FreeBSD router config?

**Comment by DentonGentry** [comment] 2021-03-04 23:41
Unless I'm misunderstanding something, I think I'm still going to need to actually assign the interface address as a /48:

```
root@freebsd12# ifconfig tailscale0
tailscale0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1280
        options=80000<LINKSTATE>
        inet 100.95.208.20 --> 100.95.208.20 netmask 0xffffffff
        groups: tun
        nd6 options=101<PERFORMNUD,NO_DAD>
        Opened by PID 1522
root@freebsd12# ping6 fd7a:115c:a1e0:ab12:4843:cd96:6254:d86f
ping6: UDP connect: Can't assign requested address
```

It could probably route IPv6 without the interface address, but local processes don't have a useable source address until I add it:

```
root@freebsd12# ifconfig tailscale0 inet6 fd7a:115c:a1e0:ab12:4843:cd96:625f:d014/48
root@freebsd12# ifconfig tailscale0
tailscale0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1280
        options=80000<LINKSTATE>
        inet 100.95.208.20 --> 100.95.208.20 netmask 0xffffffff
        inet6 fd7a:115c:a1e0:ab12:4843:cd96:625f:d014 prefixlen 48
        groups: tun
        nd6 options=101<PERFORMNUD,NO_DAD>
        Opened by PID 1522
root@freebsd12# ping6 fd7a:115c:a1e0:ab12:4843:cd96:6254:d86f
PING6(56=40+8+8 bytes) fd7a:115c:a1e0:ab12:4843:cd96:625f:d014 --> fd7a:115c:a1e0:ab12:4843:cd96:6254:d86f
16 bytes from fd7a:115c:a1e0:ab12:4843:cd96:6254:d86f, icmp_seq=0 hlim=64 time=77.663 ms
16 bytes from fd7a:115c:a1e0:ab12:4843:cd96:6254:d86f, icmp_seq=1 hlim=64 time=4.776 ms
^C
--- fd7a:115c:a1e0:ab12:4843:cd96:6254:d86f ping6 statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 4.776/41.219/77.663/36.443 ms
```

I don't see a way to do this solely by modifying the config in modifiedConfigForFreeBSDBugWorkaround. We want Darwin to add a /128, and FreeBSD to add a /48.

I don't think this is enough to want to duplicate the file into router_userspace_darwin.go and router_userspace_freebsd.go, I'd propose to add `if runtime.GOOS == "freebsd"` handling when adding the address to the interface.

**Comment by DentonGentry** [comment] 2021-03-05 23:45
Screw around with ifconfig adding and removing IPv6 addresses long enough and FreeBSD gets very cross.

```
Fatal trap 12: page fault while in kernel mode
cpuid = 0; apic id = 00
fault virtual address   = 0x0
fault code              = supervisor read data, page not present
instruction pointer     = 0x20:0xffffffff80ce8aa2
stack pointer           = 0x28:0xfffffe001b4b8640
frame pointer           = 0x28:0xfffffe001b4b8780
code segment            = base 0x0, limit 0xfffff, type 0x1b
                        = DPL 0, pres 1, long 1, def32 0, gran 1
processor eflags        = interrupt enabled, resume, IOPL = 0
current process         = 71296 (netstat)
trap number             = 12
panic: page fault
cpuid = 0
time = 1614897171
KDB: stack backtrace:
#0 0xffffffff80c0a8f5 at kdb_backtrace+0x65
#1 0xffffffff80bbeb1b at vpanic+0x17b
#2 0xffffffff80bbe993 at panic+0x43
#3 0xffffffff8108f911 at trap_fatal+0x391
#4 0xffffffff8108f96f at trap_pfault+0x4f
#5 0xffffffff8108efb6 at trap+0x286
#6 0xffffffff81067088 at calltrap+0x8
#7 0xffffffff80ce2938 at rn_walktree+0x98
#8 0xffffffff80ce81bd at sysctl_rtsock+0x20d
#9 0xffffffff80bcda3a at sysctl_root_handler_locked+0x8a
#10 0xffffffff80bcce69 at sysctl_root+0x249
#11 0xffffffff80bcd4d8 at userland_sysctl+0x178
#12 0xffffffff80bcd31f at sys___sysctl+0x5f
#13 0xffffffff810904c7 at amd64_syscall+0x387
#14 0xffffffff810679ae at fast_syscall_common+0xf8
Uptime: 7d5h56m5s
```

**Comment by DentonGentry** [comment] 2021-03-05 23:52
The final diff to make FreeBSD work is quite small:

```
diff --git a/wgengine/router/router_userspace_bsd.go b/wgengine/router/router_userspace_bsd.go
index fb81d62..32bf1d7 100644
--- a/wgengine/router/router_userspace_bsd.go
+++ b/wgengine/router/router_userspace_bsd.go
@@ -10,6 +10,7 @@ import (
        "fmt"
        "log"
        "os/exec"
+       "runtime"

        "github.com/tailscale/wireguard-go/device"
        "github.com/tailscale/wireguard-go/tun"
@@ -123,7 +124,13 @@ func (r *userspaceBSDRouter) Set(cfg *Config) (reterr error) {
                }
        }
        for _, addr := range r.addrsToAdd(cfg.LocalAddrs) {
-               arg := []string{"ifconfig", r.tunname, inet(addr), addr.String(), addr.IP.String()}
+               var arg []string
+               if runtime.GOOS == "freebsd" && addr.IP.Is6() && addr.Bits == 128 {
+                       tmp := netaddr.IPPrefix{addr.IP, 48}
+                       arg = []string{"ifconfig", r.tunname, inet(tmp), tmp.String()}
+               } else {
+                       arg = []string{"ifconfig", r.tunname, inet(addr), addr.String(), addr.IP.String()}
+               }
                out, err := cmd(arg...).CombinedOutput()
                if err != nil {
                        r.logf("addr add failed: %v => %v\n%s", arg, err, out)
```

We do not appear to need to do our own hairpinning in handleLocalPackets(), I can ping the local system's IPv6 address for tailscale0 and get responses. I recall that the BSD IP stack handles this somewhere, as the Ethernet layer doesn't need to worry about this either.

**Closed** 2021-03-06 03:34 UTC
Labels: L1 Almost no one, OS-freebsd, T0 New feature
