### ISSUE TITLE
ACLs validation silently fails if an invalid hostname is used

### ISSUE THREAD

**Issue by filviu** [tailscale/tailscale#5532] opened 2022-09-02 12:41 UTC
### What is the issue?

Consider we define a host:
```json
"hosts": {
		"host1":   "1.2.3.4",
}
```
Then we setup a rule similar to this:
```json
{
	"action": "accept",
	"src":    ["group:sales"],
	"proto":  "tcp",
	"dst":    ["host1:443"],
},
```
It all works as expected. Then I wanted to know whether I can use a FQDN host without defining in the "hosts" area:

```json
{
	"action": "accept",
	"src":    ["group:sales"],
	"proto":  "tcp",
	"dst":    ["host1:443", "host2.example.com:443"],
},
```

The ACL validates and saves but not only I don't get access to host2.example.com **I also loose access to host1** which tells me that the whole rule fails. It's not critical, now I know I can't use FQDNs but I think that the validation should catch this if undefined hosts break rules...

### Steps to reproduce

Setup hosts as above.

### Are there any recent changes that introduced the issue?

not sure, I'm new here :)

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.30

### Bug report

BUG-2e14844fc1f231bfc5adc75afdbb9d2abc3484fd2e9722398ad86beb2aab8c05-20220902123951Z-c10a5dcd43a4f5fc

EDIT: grammar

**Comment by filviu** [comment] 2022-09-29 07:11
We actually stumbled in a worse effect of this bug:

We use ACLs with user groups and a list of hosts to manage who can access what inside our infrastructure. If even one host is mistyped then the group looses access to every host in the ACL. And it's hard to debug if you are not aware of the issue.

**Comment by matshch** [comment] 2022-12-21 12:02
We have stumbled in this issue in even worse manner: not only the new rule was not working, even other rules for other sources stopped working.

**Comment by DentonGentry** [comment] 2023-02-18 15:25
ACL validation was improved earlier this year, and I cannot reproduce this issue. Starting from this (valid) ACL:
```
{
	"Hosts": {
		"host2":  "100.101.102.103",
	},
	"ACLs": [
		{
			"action": "accept",
			"users":  ["autogroup:members"],
			"ports":  ["host2:443"],
		},
	],
}
```

If I add an invalid host:
```
{
	"Hosts": {
		"host2":  "100.101.102.103",
	},
	"ACLs": [
		{
			"action": "accept",
			"users":  ["autogroup:members"],
			"ports":  ["host2:443", "host2.example.com:443"],
		},
	],
}
```

I get: `Error: ports="host2.example.com:443": "host2.example.com": invalid IPv4 address`
and cannot save the invalid ACL.

Closing as fixed, that the validation on save now matches the validation when applied.
If there is still some nuance I'm missing, please reopen.

**Comment by filviu** [comment] 2023-04-11 12:53
I think there's a regression or the `dst` field is not validated as the `ports` one but today I was able to save again the policy file with an invalid host in the dst field like this"


```json
{
    "action": "accept",
    "proto":  "tcp",
    "src":    ["existing_host1"],
    "dst":    ["existing_host2:443", "undefined_host:443"],
},
```

Tailnet policy file saves and promptly all accesses are blocked, nothing works.

**Comment by DentonGentry** [comment] 2023-04-14 05:01
It is the `"proto":  "tcp"` in the entry which is making the difference. With `"proto":  "tcp"` the ACL validates and saves, without it the ACL (correctly) fails to validate.

**Comment by DentonGentry** [comment] 2023-06-03 20:04
I believe this was resolved in a coordination server deployed in May 2023.

<img width="618" alt="Screenshot 2023-06-03 at 1 03 06 PM" src="https://github.com/tailscale/tailscale/assets/1140756/69428f27-80c3-451c-a98e-eb431554fa82">

**Closed by DentonGentry** 2023-06-03 20:04 UTC
Labels: L3 Some users, P5 Halts deployment, T6 Major usability, bug
