### ISSUE TITLE
FR: show relay vs direct in mobile apps

### ISSUE THREAD

**Issue by ericswpark** [tailscale/tailscale#5560] opened 2022-09-07 12:39 UTC
### What are you trying to do?

The mobile apps lack CLI access, so there should be something else to figure out the connectivity status between devices.

### How should we solve this?

Maybe add little labels next to the clients in the client list, like "direct"/"relay" or "active"/"idle".
If going through a relay, maybe show a flag for the DERP relay location?

### What is the impact of not solving this?

Impossible to debug connection issues with specific clients on mobile.

**Comment by DentonGentry** [comment] 2023-02-12 19:13
Duplicate of:
Android https://github.com/tailscale/tailscale/issues/2317
iOS https://github.com/tailscale/tailscale/issues/2771

**Comment by ericswpark** [comment] 2023-02-14 12:59
@DentonGentry thank you, but this FR also asks for other details, like whether a given connection is through a relay. Should I add it as a comment to the linked FRs to expand them, or can this be re-opened to focus on that specific functionality?

**Comment by DentonGentry** [comment] 2023-02-14 13:56
To set expectations: the mobile UIs are deliberately a subset of the desktop apps, it is not clear that including substantial additional factors in the status reporting is going to be possible in the design.

**Comment by Ged-fi** [comment] 2023-03-18 07:00
Basic status information in the UI would be quite helpful for troubleshooting. This is especially true on mobile devices, as network connectivity frequently changes and there are several issues open about problems related to networking.

**Comment by lazee486** [comment] 2023-09-08 19:31
knowing which are relaying would tell me to find another method to connect as the relay can be slow...alos knowing online, as the ips arent sequential i cant just nmap scan the range or set a tool...

**Closed** 2024-05-02 22:35 UTC
Labels: OS-ios, OS-android, L3 Some users, P1 Nuisance, T2 Visual Polish, fr

**Comment by agottardo** [comment] 2024-05-02 22:40
iOS support for this is landing in the next TestFlight update. Leaving this open to track for Android.

**Comment by ericswpark** [comment] 2024-07-18 03:05
@agottardo which iOS version did this feature land in? I'm on 1.68.2 but there's no visible tag for differentiation. Also seems like  the issue was closed when you mentioned leaving it open for Android (just in case this was unintentional!)

**Comment by agottardo** [comment] 2024-07-18 03:36
> @agottardo which iOS version did this feature land in? I'm on 1.68.2 but there's no visible tag for differentiation. Also seems like  the issue was closed when you mentioned leaving it open for Android (just in case this was unintentional!)

It is available on both Android and iOS as of 1.70. Hold down on a device, select "Ping" in the menu that appears.
