### ISSUE TITLE
No access through subnet router

### ISSUE THREAD

**Issue by BlueHairMinerBoy** [tailscale/tailscale#5547] opened 2022-09-05 18:03 UTC
### What is the issue?

I can't access, ping or even find anything on my local network whilst the Tailscale client is running. This is happening on multiple Windows PCs in my account.

There's a tickbox for "access local network" I've seen but clicking it doesn't seem to do anything.

### Steps to reproduce

Connect to Tailscale
Try to access any device on my local network

### OS

Windows

### OS version

Windows 10 21H2

### Tailscale version

1.30.0

### Bug report

BUG-a698419502f17194e8719e3d3e37d6abe46bf69e8d43815f7d0bd6076234432c-20220905175925Z-5aca046bd27f9b17

**Comment by rweirtbg** [comment] 2022-09-05 22:16
Are you using an exit node? Do you have more than one local subnet as part of your LAN?

**Comment by BlueHairMinerBoy** [comment] 2022-09-05 22:30
One flat /24, not using an exit node. I have one in my tailnet but this issue has been happening since before I set it up.

**Comment by cloudybyte** [comment] 2022-09-07 08:30
I've had a similar issue where I was not able to connect to locally running docker containers while being connected. Running `tailscale up --reset` fixed it for me.

**Comment by DentonGentry** [comment] 2022-10-31 14:37
Around the time of the bugreport we do see timeouts trying to access various subnet routes:
```
2022-09-05 18:54:49.2321326 +0100 +0100: open-conn-track: timeout opening (TCP 100.121.x.y:52686 => 10.x.y.78:8008) to node [RNO4d]; online=no, lastseen=13h54m49s, lastRecv=never
2022-09-05 18:54:49.2321326 +0100 +0100: open-conn-track: timeout opening (TCP 100.121.x.y:52685 => 10.x.y.219:8008) to node [RNO4d]; online=no, lastseen=13h54m49s, lastRecv=never
2022-09-05 18:54:49.2321326 +0100 +0100: open-conn-track: timeout opening (TCP 100.121.x.y:52687 => 10.x.y.180:8008) to node [RNO4d]; online=no, lastseen=13h54m49s, lastRecv=never
2022-09-05 18:54:49.2619105 +0100 +0100: open-conn-track: timeout opening (TCP 100.121.x.y:52688 => 10.x.y.117:8008) to node [RNO4d]; online=no, lastseen=13h54m49s, lastRecv=never
2022-09-05 18:54:49.3225659 +0100 +0100: open-conn-track: timeout opening (TCP 100.121.x.y:52689 => 10.x.y.213:8008) to node [RNO4d]; online=no, lastseen=13h54m49s, lastRecv=never
2022-09-05 18:54:49.9399156 +0100 +0100: open-conn-track: timeout opening (TCP 100.121.x.y:52690 => 10.x.y.216:60000) to node [RNO4d]; online=no, lastseen=13h54m50s, lastRecv=never
2022-09-05 18:54:52.2524578 +0100 +0100: open-conn-track: timeout opening (TCP 100.121.x.y:52687 => 10.x.y.180:8008) to node [RNO4d]; online=no, lastseen=13h54m52s, lastRecv=never
2022-09-05 18:54:52.2524578 +0100 +0100: open-conn-track: timeout opening (TCP 100.121.x.y:52686 => 10.x.y.78:8008) to node [RNO4d]; online=no, lastseen=13h54m52s, lastRecv=never
2022-09-05 18:54:52.2524578 +0100 +0100: open-conn-track: timeout opening (TCP 100.121.x.y:52685 => 10.x.y.219:8008) to node [RNO4d]; online=no, lastseen=13h54m52s, lastRecv=never
```

The subnet router is a firewall. Do its access controls allow the 10.x.y.0/24 subnet on the Tailscale interface?

**Comment by vampywiz17** [comment] 2023-05-02 14:53
@DentonGentry 

same problem. I can not use exit node. I found a similar forum topic, and they said that the problem is my LAN subnet is not C type local one. (we are use 100.100.0.0/16 subnet)

It possible to set somehow the tailsacle that i access my local network, if VPN active?

**Comment by DentonGentry** [comment] 2023-06-03 20:06
@vampywiz17 you would need to attach a `tailscale bugreport` for us to have any hope of identifying the problem.

Please file a new issue, it is not at all clear that you are running into the same thing.

**Comment by DentonGentry** [comment] 2023-06-03 20:08
> The subnet router is a firewall. Do its access controls allow the 10.x.y.0/24 subnet on the Tailscale interface?

I'll close this for now, as we aren't going to make progress without more information. Please reopen if still relevant.

**Closed by DentonGentry** 2023-06-03 20:08 UTC
Labels: L1 Very few, P2 Aggravating, T5 Usability, waiting-for-info, bug
