### ISSUE TITLE
FR: Host groups similar to user groups 

### ISSUE THREAD

**Issue by connor70** [tailscale/tailscale#5179] opened 2022-07-26 17:52 UTC
### What are you trying to do?

Ability to group hosts/subnets into groups, like you can for users. 

`{
	"hosts": {
		"lan1": "192.168.0.0/24",
		"lan2": "192.168.1.0/24",
		"wan1": "192.168.2.0/24",
		"wan2": "192.168.3.0/24",
		"wan3": "192.168.4.0/24",
	}, 

	"host_groups": {
		"host_group:lan_networks": [
			"lan1",
			"lan2",
		],
		"host_group:wan_networks": [
			"wan1",
			"wan2",
			"wan3",
		],
	},
	"acls": [
		{
			"Action": "accept",
			"Users": [
				"user@gmail.com",
			],
			"Ports": [
				"lan_networks:22,161",
				"wan_networks:*"
			]
		},
	]
}`

### What is the impact of not solving this?

ACL's are big, when adding new subnets/hosts multiple locations need to be edited.

**Comment by DentonGentry** [comment] 2022-07-29 03:00
Duplicate of https://github.com/tailscale/tailscale/issues/2556

**Closed by DentonGentry** 2022-07-29 03:00 UTC
Labels: needs-triage, fr
