### ISSUE TITLE
Tailscale iOS app is perpetually Loading

### ISSUE THREAD

**Issue by tbodt** [tailscale/tailscale#3439] opened 2021-11-30 00:57 UTC
### What is the issue?

The tailscale ios app displays this forever:
![29497E10-6880-40D1-9682-DFFDF576C095](https://user-images.githubusercontent.com/5678977/143966235-067e6d22-3efb-4a64-82bb-03782b4f0383.jpeg)

Restarting, reinstalling, and reauthenticating doesn't affect anything. The VPN doesn't work.

### Steps to reproduce

Open app

### OS

iOS

### OS version

iOS 15

### Tailscale version

1.18.0

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3x9ld)

**Comment by bradfitz** [comment] 2021-11-30 01:01
Have you ever had Tailscale installed on this device?

Do you have another VPN active?

Did you say "No" to the prompt about VPN access?

Do you have internet access currently?  (or is it maybe blocked/requiring auth?)

**Comment by tbodt** [comment] 2021-11-30 01:39
Tailscale was installed and working at some point before. One day I opened it and it was stuck loading, and it's been the same since.

I don't have another VPN active.

Don't think so. Here's the VPN settings page:
![CBE9A042-DD34-4097-B693-2FD4D1CDD77D](https://user-images.githubusercontent.com/5678977/143970012-2810d813-713d-44f9-b301-f26ead064444.jpeg)

I do have internet access at the moment.

**Comment by DentonGentry** [comment] 2021-11-30 02:09
Can you send either:
- the Tailscale IP address of this device, if you know it, or
- the email address or GitHub profile you use with Tailscale
to support@tailscale.com? If it is managing to contact any of the backend systems, we may be able to see what is happening.

**Comment by tbodt** [comment] 2021-11-30 03:10
My tailnet is just associated with this github account. I sent an email with the ip of the device, but I'm unsure if that's worth anything since I've reinstalled the app several times, and not successfully logged in after reinstalling.

**Comment by DentonGentry** [comment] 2021-11-30 04:30
(IP address sent in email)

Unfortunately no, the iOS device hasn't sent any telemetry for a week. I was hoping it had gotten far enough along in its startup process to start sending some, so maybe it would tell us what was going wrong.

**Comment by tbodt** [comment] 2021-11-30 04:31
Is there some way to collect logs client-side? Other than that, any other suggestions to get it working again?

**Comment by bradfitz** [comment] 2021-11-30 04:55
The macOS app `Console.app` can let you start logging. Click your iPhone (when plugged in over USB), search for "IPNExtension" or "Tailscale", hit Start, and then you'll see logs.

**Comment by tbodt** [comment] 2021-11-30 19:46
Before I tried collecting logs I rebooted, which fixed the problem. Somewhat surprised that that did it, when reinstalling didn't work. I also didn't have to reauthenticate somehow. Can probably close this now though.

**Comment by alex-tan** [comment] 2022-08-27 03:13
I second that I have this issue. The only way to resolve it is either reinstalling the app or rebooting my iPad. Force quitting doesn’t fix it.

**Comment by arunsathiya** [comment] 2022-08-27 03:20
Quick note that I haven't seen this issue for several months now. I am on the latest version.

**Comment by swetepete** [comment] 2022-10-08 16:54
It just happened to me, will try reinstalling.

**Comment by ajatoledo** [comment] 2022-12-12 03:25
I'm on the latest version and this is still happening. The tailscale profile is selected in iOS settings, but the application won't load. This has been an on-going issue for me since day 1 of using the iOS app across 3 phones and two iPads.

**Comment by DentonGentry** [comment] 2022-12-12 03:31
@ajatoledo did any of the devices get to the point of having an IP address assigned? Attaching the one you tried most recently here would let us look for any telemetry it may have sent.

If none of them appear in https://login.tailscale.com/admin/machines and never got IP addresses assigned, sending the name of the account to support@tailscale.com might let us find some kind of clue from devices trying to join.

**Comment by ajatoledo** [comment] 2022-12-12 03:38
@DentonGentry, not exactly sure what I should attach a picture of here; however, I was able to connect tailscale and get my device an ip address after restarting my phone. I notice the issue occurs when I switch off the Tailscale profile and then look to turn it back on later. I filed a big report in an effort to send device information, BUG-2224bbf5ef36aae3fa5d2aeb6211f8094eab31f8b941399af7225973dd3cb7fb-20221212033430Z-bda0fa68bc3eb231. Please let me know if you need anything else.

**Comment by kdruelle** [comment] 2023-01-06 14:11
Same issue happened to me today. I suspect it started when I started a new wireguard connection with Tailscale already running in background. I had to restart the device to recover, force quitting didn't help.

**Comment by Myp3a** [comment] 2023-01-29 09:42
Same for me.
iPad Air 5, Cellular, iOS 15.6 beta (19G69).
This device worked fine with iOS 16.2. I do not want to update to iOS 16.
After restoring app stuck in "Loading" state. After reinstalling it's stuck in "Needs authentication", and loading endlessly.
VPN configuration is installed and enabled. Happens on any network. Other IKEv2 VPNs working fine.
My bugreport ID is BUG-73e2eb8877fbf218addab01f738bf5fd493e1fbcb62fd5873ad0cba6d750e154-20230129094019Z-22e7aa5dbd336a05

<details>
<summary>App screenshot</summary>

![404C5E98-C5B2-49F8-B3C6-5DAB3234F08F](https://user-images.githubusercontent.com/28502095/215317983-b48de15f-40a1-49b9-a58e-468ba94bc2ef.png)
</details>

**Comment by Myp3a** [comment] 2023-02-05 15:25
Resolved for me. TestFlight version 1.37.32. Initially it hung at the same point, and after few days started working without iasues

**Comment by DentonGentry** [comment] 2023-02-12 20:41
Current versions of the iOS TestFlight Tailscale app 1.37.x should solve this problem.
The fix will be in 1.38.

**Closed by DentonGentry** 2023-02-12 20:41 UTC
Labels: OS-ios, L1 Very few, P3 Can't get started, T6 Major usability, bug

**Comment by SHxKM** [comment] 2023-05-12 21:49
Just happened to me as well. Will reinstall.

**Comment by ajatoledo** [comment] 2023-05-13 13:26
I've noticed that when I'm experiencing the loading issue on my iPhone and iPad, I can resolve the issue by going to: 

Settings > VPN > In VPN Configurations menu: 

- toggle Status to Not Connected 

- confirm Tailscale Tunnel is selected in the list of configurations; wait a few moments

After doing the steps above, if I switch back to the Tailscale application and the loading screen is gone, I can toggle Tailscale to active. 

- **Note**: Sometimes, after I toggle Tailscale to `Active`, the application toggles back to `Stopped`, so I need to toggle it to `Active` again.

**Comment by GeorgesAlkhouri** [comment] 2023-09-09 11:35
I am also stuck with a perpetually Log in button in version 1.48.1

**Comment by GeorgesAlkhouri** [comment] 2023-09-12 20:41
Hm with the newest TestFlight build 1.49.238(101.49.238), the problem is gone on my phone

**Comment by bithack3r** [comment] 2024-03-13 14:48
I still have the same iussue on iOS. App is stuck at 'Starting'. 

Under Settings > VPN CONFIGURATIONS, it shows 'Connected' while stuck at 'Starting' on the app

Logging out, Deleting the app, Reauthenticating etc also didn't help.

iPhone 11 Pro Max (17.3.1) and iPhone 7 Plus (15.8.1)
Tailscale 1.60.1
