### ISSUE TITLE
Synology arm packages broken with Go 1.18+

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#6792] opened 2022-12-19 21:46 UTC
Tracking bug to fix our Synology packages for 32-bit ARM. Some of those 32-bit ARM (often ARMv5) devices (like DS212j) run an old enough kernel (2.6.32.12) that accept4 doesn't exist which Go thought was safe to depend on. But it turns out for arm, accept4 didn't appear until 2.6.36.

Go fix was in https://github.com/golang/go/issues/57333

We need to bring that into our Go tree, build new packages, and document somewhere.

/cc @DentonGentry

**Comment by DentonGentry** [comment] 2023-01-05 03:53
This fix is included in the 1.34.2 stable release: https://pkgs.tailscale.com/stable/#spks
We expect to submit 1.34.2 to the Synology Package Center, though the review and release process will take some time.

**Comment by skarra** [comment] 2023-02-12 00:18
Can someone describe what is the user facing symptom of the broken package? My Synology is no longer on my tailnet and when I tried to auth it does not work (see screenshot below). Is this problem anticipated to get fixed with the new packages tracked in the present Issue?

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/633395/218286519-54745a98-1480-4a12-b4f1-7699a8f0cc2d.png">

**Comment by DentonGentry** [comment] 2023-02-12 00:21
It wouldn't even get to the point of serving the page which says "Log in"

Please open a new issue, or file a support ticket https://tailscale.com/contact/support/
You appear to be running into some other issue.

**Comment by DentonGentry** [comment] 2023-04-30 13:25
We now have a DS413j (circa 2012) running DSM 6.2.4. It has a Marvell Kirkwood 88F6282 CPU, which is 32 bit ARM5. It uses kernel 2.6.32:
```
admin@DiskStation:/$ uname -a
Linux DiskStation 2.6.32.12 #25556 Thu Mar 4 17:56:48 CST 2021 armv5tel GNU/Linux synology_88f6282_413j
```

The good news is that this issue is resolved, the Tailscale package loads and runs.

The bad news is that Synology rejected the 1.34.2 packages we'd submitted, citing ARM5 issues which I cannot reproduce using this unit. We'll keep working on that part.

**Closed by DentonGentry** 2023-04-30 13:25 UTC
Labels: OS-synology
