### ISSUE TITLE
wintun: NativeTun.Write: buffHead 4294967295 > capacity 8388608 (with WSL2)

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#780] opened 2020-09-23 18:10 UTC
A number of Windows users in #454 and other bugs have reported that Tailscale on Windows only completes one ping successfully, and then Tailscale's broken until a restart.

(cc @pnunn @33b5e5 @whollacsek @alexbrainman)

@33b5e5 ran a build with extra logging and we see:

```
2020-09-23 10:33:58.2884284 -0700 PDT: NativeTun.Write: buffHead 4294967295 > capacity 8388608
2020-09-23 10:33:58.2884284 -0700 PDT: srv: 7.5M/0.0M Failed to write packet to TUN device: file already closed
2020-09-23 10:33:59.3317873 -0700 PDT: NativeTun.Write: buffHead 4294967295 > capacity 8388608
2020-09-23 10:33:59.3317873 -0700 PDT: srv: 7.5M/0.0M Failed to write packet to TUN device: file already closed
2020-09-23 10:34:00.3713424 -0700 PDT: NativeTun.Write: buffHead 4294967295 > capacity 8388608
2020-09-23 10:34:00.3713424 -0700 PDT: srv: 7.5M/0.0M Failed to write packet to TUN device: file already closed
2020-09-23 10:34:01.4102759 -0700 PDT: NativeTun.Write: buffHead 4294967295 > capacity 8388608
2020-09-23 10:34:01.4102759 -0700 PDT: srv: 7.5M/0.0M Failed to write packet to TUN device: file already closed
2020-09-23 10:34:02.4524151 -0700 PDT: NativeTun.Write: buffHead 4294967295 > capacity 8388608
2020-09-23 10:34:02.4524151 -0700 PDT: srv: 6.5M/0.0M Failed to write packet to TUN device: file already closed
2020-09-23 10:34:09.3922441 -0700 PDT: NativeTun.Write: buffHead 4294967295 > capacity 8388608
2020-09-23 10:34:09.3922441 -0700 PDT: srv: 6.3M/0.0M Failed to write packet to TUN device: file already closed
2020-09-23 10:34:10.4170269 -0700 PDT: NativeTun.Write: buffHead 4294967295 > capacity 8388608
2020-09-23 10:34:10.4170269 -0700 PDT: srv: 6.3M/0.0M Failed to write packet to TUN device: file already closed
2020-09-23 10:34:11.4420272 -0700 PDT: NativeTun.Write: buffHead 4294967295 > capacity 8388608
2020-09-23 10:34:11.4420272 -0700 PDT: srv: 6.6M/0.0M Failed to write packet to TUN device: file already closed
```

So, some issue in wireguard-go/wintun.

(to be clear, the "file already closed" is misleading... the returned `os.ErrClosed` which stringifies to "file already closed" is returned when the `buffHead` value is bogus. The TUN device is not being closed)

So, why is `buffHead` MaxUint32?

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2bydt)

**Comment by bradfitz** [comment] 2020-09-23 20:24
For everybody here seeing the "one ping" issue, can you run:

`driverquery /v | find "wintun"` 

and right click the `wintun.sys` and look at its properties:

<img width="1224" alt="Screen Shot 2020-09-23 at 1 00 55 PM" src="https://user-images.githubusercontent.com/2621/94065478-0ba24500-fda0-11ea-9299-1ce84df0e37a.png">

<img width="423" alt="Screen Shot 2020-09-23 at 1 24 11 PM" src="https://user-images.githubusercontent.com/2621/94065495-12c95300-fda0-11ea-9c6b-984957147453.png">

What do others see there?

**Comment by 33b5e5** [comment] 2020-09-23 20:37
![image](https://user-images.githubusercontent.com/2781306/94066866-ea425880-fda1-11ea-8012-6a8f0d9819ef.png)
![image](https://user-images.githubusercontent.com/2781306/94066897-f4fced80-fda1-11ea-8e0c-f159f82596ae.png)

**Comment by whollacsek** [comment] 2020-09-23 21:23
![Capture](https://user-images.githubusercontent.com/825424/94071158-c7409480-fdf3-11ea-82c8-9a19ef5ea468.PNG)
![Capture2](https://user-images.githubusercontent.com/825424/94071167-c90a5800-fdf3-11ea-9644-aa7a1a315372.PNG)

**Comment by pnunn** [comment] 2020-09-23 21:43
![image](https://user-images.githubusercontent.com/1034315/94072643-6b98fa00-fe39-11ea-9120-070195fba716.png)
![image](https://user-images.githubusercontent.com/1034315/94072738-9a16d500-fe39-11ea-8747-404ee8111285.png)

**Comment by 33b5e5** [comment] 2020-09-24 06:45
@pnunn, @whollacsek, or anyone else experiencing the "one ping" issue: are you using WSL to ping?

I think I've narrowed down the problem a bit. If I reboot and then immediately use WSL to ping another Tailscale node, I get one ping only. However, if I reboot and use PowerShell to ping, it works fine. Furthermore I can ping from WSL after pinging from PowerShell. Basically everything works fine as long as you don't attempt the first ping from WSL. I rebooted about 10 times to make sure the pattern held.

Based on comments from Brad elsewhere, I'm guessing there's a bug in WSL or some interaction between WSL and the TUN driver.

Running Wireshark on the WSL vEthernet adapter, I can see the successful first Echo Request/Reply, then 8 MDNS requests in a row like:

`z.y.x.100.in-addr.arpa.local: type PTR, class IN, "QM" question`

WSL is looking for the PTR record for the node I'm trying to ping. Then there are "no such name" DNS responses as subsequent pings fail with "ICMP Destination unreachable". 

I'm not sure if the MDNS requests are part of the problem or just a red herring, but I kept the .pcap in case it's helpful.

I'm running Ubuntu 20.04.1 on WSL 2 on Win 10 20H2 (19042.541).

**Comment by pnunn** [comment] 2020-09-24 06:54
@33b5e5 Nice find!! Works exactly as you describe.

I am running 20.04.1 on WSL2 as well, and the networking is really an issue on it as will. I'm constantly dropping ssh connections (especially on the wired lan). It may be that WSL2 is effecting the entire network stack in fact. I must try running the ssh connections using putty without starting wsl2 and see what happens.

May be time to finally dump windows all together 😑

**Comment by 33b5e5** [comment] 2020-09-24 07:47
Yeah... looks like it may be WSL v2 specifically.

I setup another Ubuntu instance on WSL 1. The environment now looks like:

```
> wsl --list --all --verbose
  NAME            STATE           VERSION
* Ubuntu          Stopped         2
  Ubuntu-18.04    Stopped         1
```

If I do the first ping from Ubuntu 18.04 on WSL 1, everything works fine. If I do the first ping from WSL 2, I get "one ping only" and then nothing works over Tailscale.

**Comment by pnunn** [comment] 2020-09-24 08:37
Hmm.. Interestingly I can't ping any of the other machines on the network. I can ping the hello address, but nothing else (android and linux devices).

**Comment by whollacsek** [comment] 2020-09-24 12:53
@33b5e5 nice find, I can finally ssh into my linux boxes from WSL2 :)

But interestingly I just noticed the links are 0
![image](https://user-images.githubusercontent.com/825424/94147456-94d77b80-fe75-11ea-9df7-16c04210b7ee.png)
I'm on v1.1.432

**Comment by tonyping** [comment] 2020-09-28 08:23
Take a look at this WSL2 issue: https://github.com/microsoft/WSL/issues/5256. 

I ran into (not-tailscale), but still DNS /ping-related issues with WSL2 /etc/resolv.conf, and this helped immensely: https://github.com/microsoft/WSL/issues/5256#issuecomment-666545999. 

This issue is however, just one caused by a combination of several factors(summarized here: https://github.com/microsoft/WSL/issues/5256#issuecomment-675005868), but there's been a bunch of compatibility bugs with Hyper-V  alongside firewalls and/or tap clients.

**Comment by pnunn** [comment] 2020-09-28 09:15
It seems the hole network stack on wsl2 is a total cluster. I'm getting all sorts of disconnects from wsl2 to ssh clients. It's particularly bad if I forget to turn off the wifi when I plug in the wired network.  Not sure if its worth troubleshooting to be honest, I think its time to get linux working on this xps15 instead.

**Comment by alexbrainman** [comment] 2020-09-29 09:14
> It seems the hole network stack on wsl2 is a total cluster.

I use https://www.virtualbox.org on Windows. And just run whatever Linux I want. I don't push the system very hard, but I never had any compatibility problems. The only down side, that I have to disable Hyper-V to be able to run VirtualBox (which could big downside, if you want to run Docker on Windows).

I hope it helps.

Alex

**Comment by 33b5e5** [comment] 2020-10-14 04:35
> I suppose one interesting test is to see if upstream Wireguard exhibits this same issue with WSL2.

Hey @bradfitz. I tried reproducing the one ping only issue with Wireguard, but couldn't.

wireguard-amd64-0.1.1.msi from https://www.wireguard.com/install/. Uninstalled Tailscale first. Imported an existing Wireguard tunnel and was able to connect without issue. Issued the first ping over Wireguard from WSL 2, and everything seemed to work fine.

Uninstalled Wireguard, reinstalled tailscale-ipn-setup-1.1.540.exe, and was able to reproduce the one ping only by using WSL 2 for the first ping.

The issue doesn't seem to be upstream (at least, not in the current version).

Hope this helps.

Windows 10 version is 20H2 (19042.572).

**Comment by pnunn** [comment] 2020-10-14 04:39
Some more info here too.. I have now got a tailscale client running in a data center pushing a route to the management network on there. My windows machine picked up the connection and the route and is working just like I would expect it too. I can see all of the machines on that remote DC network with out any issue at all??

Peter.

**Comment by brunoenten** [comment] 2020-11-25 10:56
I've got the same issue. Strange thing is that it worked perfectly at first. Then I created a new tailscale account, signed out then signed in again with the new account, and the issue started showing up.
Go figure...

**Comment by bradfitz** [comment] 2020-12-01 17:25
@peske: plan is to try to reproduce this, then update to wintun 0.9, then see if this goes away. I think/hope it will.

**Comment by 33b5e5** [comment] 2020-12-11 23:24
Saw https://twitter.com/Tailscale/status/1337532379439644673, noticed the upgrade to wintun, and excitedly downloaded 1.3.105. I can see wintun.sys is now at 0.9.0.0 (signed by WireGuard LLC). Unfortunately though, the "one ping only" issue with WSL2 is still there.

The workaround that consistently works for me: after a reboot or upgrade, open PowerShell and ping another Tailscale node. As long as the first ping comes from outside WSL2, everything works fine . If I forget this step and generate Tailscale traffic from WSL2 first (as I normally would be doing), Tailscale is essentially wedged.

Because a single ping from outside of WSL2 seems to completely mitigate the issue, I wonder... could you just have the Windows daemon ping another Tailscale node on startup? It could be your hello server, or a round-robin alias for your relay servers, or whatever.

**Comment by josharian** [comment] 2020-12-12 01:58
@33b5e5 thanks for taking the plunge! Something is not quite right, because wintun.sys should I believe be at 0.9.2, not 0.9.0. I wonder whether the installation script failed to upgrade your wintun installation somehow. (I don't know any details, because I've only been watching the installer work from the sidelines.) cc @bradfitz @peske

**Comment by 33b5e5** [comment] 2020-12-12 02:48
@josharian interesting. wintun.sys was on 0.7.0.0 before, so I assumed 0.9.0.0 was the desired new version. As a sanity check, I just downgraded to Tailscale 1.2.9, and wintun.sys goes back to 0.7.0.0. Reinstalling Tailscale 1.3.105 again, it's at 0.9.0.0.

**Comment by bradfitz** [comment] 2020-12-12 03:19
Looks like 0.9.0.0 is expected for 0.9.2. (@zx2c4 can correct me if I'm wrong)

If you look at the diff from 0.9 to 0.9.2, you see that the version number wasn't updated anywhere:

https://github.com/WireGuard/wintun/compare/0.9...0.9.2

Contrast that to, say, 0.8 to 0.9 where wintun.props is updated:

https://github.com/WireGuard/wintun/compare/0.8...0.9#diff-aefb8d5d202bf83549fcdf62a57d6c6be83c1ccad88951e7be604e77dc3abccf

Jason, this is the WSL2 bug I was mentioning briefly to you earlier. It's apparently not fixed by 0.9.2.

**Comment by zx2c4** [comment] 2020-12-12 05:30
Thanks for looping me in. Do you have a new log for 0.9, similar to the one in the top post of this thread showing that the ring head position moved to -1?

**Comment by bradfitz** [comment] 2020-12-12 05:37
Not yet. I'll work on a repro next week, though. Ideally I could just hand you a self-contained program that triggers it. Unless you beat me to it.

**Comment by zx2c4** [comment] 2020-12-12 05:48
> Looks like 0.9.0.0 is expected for 0.9.2. (@zx2c4 can correct me if I'm wrong)

Right, we bump driver versions only when the actual driver has changed, rather than the minor tag-only bumps for when the api dll has changed. In this case, technically there's that volatile change in the driver, but I disassembled on all 4 architectures and the codegen was identical.

**Comment by zx2c4** [comment] 2020-12-12 05:51
> Thanks for looping me in. Do you have a new log for 0.9, similar to the one in the top post of this thread showing that the ring head position moved to 2**32 - 1?

If that same condition repeats itself, I'm expecting it only to show now with Write returning os.ErrClosed.

**Comment by zx2c4** [comment] 2020-12-12 11:07
At a computer now momentarily and managed to reproduce it without much hassle, thanks to the clear descriptions above:

![image](https://user-images.githubusercontent.com/10643/101982224-96ddf900-3c72-11eb-98f6-fb594b46c884.png)

Will look into it and fix.

**Comment by zx2c4** [comment] 2020-12-12 14:39
Fixed:

https://git.zx2c4.com/wintun/commit/?id=ad395dc31e7d0c1ae0d21dc8caddd021dc13cd64

**Comment by bradfitz** [comment] 2020-12-13 02:43
@zx2c4, thanks!

**Comment by zx2c4** [comment] 2020-12-17 12:44
Wintun 0.10 has been released, which contains a fix for this.

That concludes my involvement in this issue; Tailscale can take it from here for their end.

**Comment by bradfitz** [comment] 2020-12-17 15:47
Thanks, @zx2c4. I've bumped Tailscale's dep up to 0.10. New build coming in ~hour.

**Closed** 2020-12-17 16:00 UTC
Labels: L3 Some users, OS-windows, P5 Halts deployment, T6 Major usability

**Comment by bradfitz** [comment] 2020-12-17 21:08
Tailscale 1.3.122 is out now: https://pkgs.tailscale.com/unstable/tailscale-ipn-setup-1.3.122.exe

**Comment by pnunn** [comment] 2020-12-17 22:57
Thanks Brad,

that seems to be working fine (after fighting with my virus scanner to 
allow me to install it).

Peter.

-- 

	
Peter Nunn
InfoTeq Pty Ltd
Director
Tel: 0412 174 230
<https://www.instagram.com/username/>pnunn@intq.it <mailto:pnunn@intq.it>
http://infoteq.com.au



Brad Fitzpatrick wrote on 18/12/2020 8:08 AM:
