### ISSUE TITLE
[chocolatey] Is there a way to pass AuthKey during the install?

### ISSUE THREAD

**Issue by random82** [tailscale/tailscale#6631] opened 2022-12-05 23:02 UTC
I want to automate deployment to a server farm, and passing the authKey on the installation would streamline the process.

Is there a way to do it?

At this stage, I use following

```powershell
& 'choco' install tailscale -y
& 'resfreshenv.cmd'
& 'tailscale.exe' up --auth-key=$tsAuthToken --unattended --accept-routes=true
```

but unfortunately, the last line fails sometimes

**Comment by bradfitz** [comment] 2022-12-06 02:35
> but unfortunately, the last line fails sometimes

How does it sometimes fail?

And with which Tailscale version?

**Comment by random82** [comment] 2022-12-06 22:58
The approach that Azure DevOps choco package uses with passing params is a good example of passing auth credentials in one go during `choco install` command

[https://github.com/flcdrg/au-packages/blob/master/azure-pipelines-agent/README.md](https://github.com/flcdrg/au-packages/blob/master/azure-pipelines-agent/README.md)

**Comment by DentonGentry** [comment] 2023-02-18 23:22
https://github.com/tailscale/tailscale/issues/4862 would handle this.
Marking as a duplicate of https://github.com/tailscale/tailscale/issues/4862

**Closed by DentonGentry** 2023-02-18 23:22 UTC
Labels: OS-windows, L2 Few, P2 Aggravating, T0 New feature
