### ISSUE TITLE
Windows `--unattended` doesn't start on boot until at least one login

### ISSUE THREAD

**Issue by 12nick12** [tailscale/tailscale#3186] opened 2021-10-25 22:05 UTC
### What is the issue?

Have to run "C:\Program Files (x86)\Tailscale IPN\tailscale.exe" up --login-server=https://scale.domain.com --unattended for it to start.

I was under that understanding that --unattended would make it start automatically. 

### Steps to reproduce

Have to run "C:\Program Files (x86)\Tailscale IPN\tailscale.exe" up --login-server=https://scale.domain.com --unattended for it to start

### OS version

Windows 10

### Tailscale version

1.16.1

**Comment by jazzdan** [comment] 2021-11-05 15:15
I have an EC2 user data script that looks like this (Pulumi code for reference):

```typescript
  const windowsUserData = `<powershell>
Start-Transcript -Path "C:\\UserData.log" -Append
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
choco install tailscale -y
& "C:\\Program Files (x86)\\Tailscale IPN\\tailscale.exe" up --authkey=${tailscale_auth_key} --accept-dns --accept-routes --unattended
</powershell>`;

  const windows_build = new aws.ec2.Instance("windows build", {
    ami: "ami-08c213ebdf7b857c2",
    instanceType: "t2.2xlarge",
    associatePublicIpAddress: true,
    tags: {
      Name: "pulumi windows build",
    },
    rootBlockDevice: {
      volumeSize: 128,
    },
    keyName: "foo",
    vpcSecurityGroupIds: [sg.id],
    subnetId: publicSubnets[0],
    userData: windowsUserData,
    getPasswordData: true,
  });
```

When I start this EC2 instance the machine briefly appears in my Tailscale list of machines on login.tailscale.com. However it quickly disconnects. When I RDP in to the Windows box I see that Tailscale is running but is not authorized (it asks me to sign in). The logs for the user data script don't show any failures, but also don't show any output from Tailscale which is weird. If I wasn't seeing it connect briefly in the Tailscale console I would assume that my 24 hours of powershell experience has led me down a bad path, but it's clearly working at least temporarily:

```
PS C:\> cat C:\ProgramData\Amazon\EC2-Windows\Launch\Log\UserdataExecution.log
2021/11/05 14:58:07Z: Userdata execution begins
2021/11/05 14:58:07Z: Zero or more than one <persist> tag was not provided
2021/11/05 14:58:07Z: Unregistering the persist scheduled task
2021/11/05 14:58:10Z: Zero or more than one <runAsLocalSystem> tag was not provided
2021/11/05 14:58:10Z: Zero or more than one <script> tag was not provided
2021/11/05 14:58:10Z: Zero or more than one <powershellArguments> tag was not provided
2021/11/05 14:58:10Z: <powershell> tag was provided.. running powershell content
2021/11/05 15:07:04Z: Userdata execution begins
2021/11/05 15:07:04Z: Zero or more than one <persist> tag was not provided
2021/11/05 15:07:04Z: Unregistering the persist scheduled task
2021/11/05 15:07:09Z: Zero or more than one <runAsLocalSystem> tag was not provided
2021/11/05 15:07:09Z: Zero or more than one <script> tag was not provided
2021/11/05 15:07:09Z: Zero or more than one <powershellArguments> tag was not provided
2021/11/05 15:07:09Z: <powershell> tag was provided.. running powershell content
2021/11/05 15:07:56Z: Message: The errors from user scripts: Success.

2021/11/05 15:07:56Z: Message: The output from user scripts: Transcript started, output file is C:\UserData.log
Forcing web requests to allow TLS v1.2 (Required for requests to Chocolatey.org)
Getting latest version of the Chocolatey package for download.
Not using proxy.
Getting Chocolatey from https://community.chocolatey.org/api/v2/package/chocolatey/0.11.3.
Downloading https://community.chocolatey.org/api/v2/package/chocolatey/0.11.3 to C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip
Not using proxy.
Extracting C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip to C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall
Installing Chocolatey on the local machine
Creating ChocolateyInstall as an environment variable (targeting 'Machine')
  Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
WARNING: It's very likely you will need to close and reopen your shell
  before you can use choco.
Restricting write permissions to Administrators
We are setting up the Chocolatey package repository.
The packages themselves go to 'C:\ProgramData\chocolatey\lib'
  (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
  and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName'.

Creating Chocolatey folders if they do not already exist.

WARNING: You can safely ignore errors related to missing log files when
  upgrading from a version of Chocolatey less than 0.9.9.
  'Batch file could not be found' is also safe to ignore.
  'The system cannot find the file specified' - also safe.
chocolatey.nupkg file not installed in lib.
 Attempting to locate it from bootstrapper.
PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...
WARNING: Not setting tab completion: Profile file does not exist at
'C:\Users\Administrator\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
Chocolatey (choco.exe) is now ready.
You can call choco from anywhere, command line or powershell by typing choco.
Run choco /? for a list of functions.
You may need to shut down and restart powershell and/or consoles
 first prior to using choco.
Ensuring Chocolatey commands are on the path
Ensuring chocolatey.nupkg is in the lib folder
Chocolatey v0.11.3
Installing the following packages:
tailscale
By installing, you accept licenses for the packages.

Progress: Downloading tailscale 1.16.2... 11%
Progress: Downloading tailscale 1.16.2... 34%
Progress: Downloading tailscale 1.16.2... 56%
Progress: Downloading tailscale 1.16.2... 78%
Progress: Downloading tailscale 1.16.2... 100%

tailscale v1.16.2 [Approved]
tailscale package files install completed. Performing other installation steps.
[Subject]
  CN=Tailscale Inc., O=Tailscale Inc., L=Toronto, S=Ontario, C=CA, SERIALNUMBER=1131559-5, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.3=CA

[Issuer]
  CN=DigiCert EV Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US

[Serial Number]
  0E058A16664C25DA52C81DBF23ACD75F

[Not Before]
  03/11/2020 00:00:00

[Not After]
  05/18/2021 12:00:00

[Thumbprint]
  DEE8D4EF882C2C255D879EF109C1DB9CF743476E

Downloading tailscale
  from 'https://pkgs.tailscale.com/stable/tailscale-ipn-setup-1.16.2.exe'

Progress: 0% - Saving 53.88 KB of 22.87 MB
Progress: 0% - Saving 192 KB of 22.87 MB
Progress: 1% - Saving 352 KB of 22.87 MB
Progress: 2% - Saving 512 KB of 22.87 MB
Progress: 2% - Saving 672 KB of 22.87 MB
Progress: 3% - Saving 832 KB of 22.87 MB
Progress: 4% - Saving 992 KB of 22.87 MB
Progress: 4% - Saving 1.13 MB of 22.87 MB
Progress: 5% - Saving 1.28 MB of 22.87 MB
Progress: 6% - Saving 1.44 MB of 22.87 MB
Progress: 6% - Saving 1.59 MB of 22.87 MB
Progress: 7% - Saving 1.75 MB of 22.87 MB
Progress: 8% - Saving 1.91 MB of 22.87 MB
Progress: 9% - Saving 2.06 MB of 22.87 MB
Progress: 9% - Saving 2.22 MB of 22.87 MB
Progress: 10% - Saving 2.38 MB of 22.87 MB
Progress: 11% - Saving 2.53 MB of 22.87 MB
Progress: 11% - Saving 2.69 MB of 22.87 MB
Progress: 12% - Saving 2.84 MB of 22.87 MB
Progress: 13% - Saving 3 MB of 22.87 MB
Progress: 13% - Saving 3.16 MB of 22.87 MB
Progress: 14% - Saving 3.31 MB of 22.87 MB
Progress: 15% - Saving 3.47 MB of 22.87 MB
Progress: 15% - Saving 3.63 MB of 22.87 MB
Progress: 16% - Saving 3.78 MB of 22.87 MB
Progress: 17% - Saving 3.94 MB of 22.87 MB
Progress: 17% - Saving 4.09 MB of 22.87 MB
Progress: 18% - Saving 4.25 MB of 22.87 MB
Progress: 19% - Saving 4.41 MB of 22.87 MB
Progress: 19% - Saving 4.56 MB of 22.87 MB
Progress: 20% - Saving 4.72 MB of 22.87 MB
Progress: 21% - Saving 4.88 MB of 22.87 MB
Progress: 21% - Saving 5.03 MB of 22.87 MB
Progress: 22% - Saving 5.19 MB of 22.87 MB
Progress: 23% - Saving 5.34 MB of 22.87 MB
Progress: 24% - Saving 5.5 MB of 22.87 MB
Progress: 24% - Saving 5.66 MB of 22.87 MB
Progress: 25% - Saving 5.81 MB of 22.87 MB
Progress: 26% - Saving 5.97 MB of 22.87 MB
Progress: 26% - Saving 6.13 MB of 22.87 MB
Progress: 27% - Saving 6.28 MB of 22.87 MB
Progress: 28% - Saving 6.44 MB of 22.87 MB
Progress: 28% - Saving 6.59 MB of 22.87 MB
Progress: 29% - Saving 6.75 MB of 22.87 MB
Progress: 30% - Saving 6.91 MB of 22.87 MB
Progress: 30% - Saving 7.06 MB of 22.87 MB
Progress: 31% - Saving 7.22 MB of 22.87 MB
Progress: 32% - Saving 7.38 MB of 22.87 MB
Progress: 32% - Saving 7.53 MB of 22.87 MB
Progress: 33% - Saving 7.69 MB of 22.87 MB
Progress: 34% - Saving 7.84 MB of 22.87 MB
Progress: 34% - Saving 8 MB of 22.87 MB
Progress: 35% - Saving 8.16 MB of 22.87 MB
Progress: 36% - Saving 8.31 MB of 22.87 MB
Progress: 37% - Saving 8.47 MB of 22.87 MB
Progress: 37% - Saving 8.63 MB of 22.87 MB
Progress: 38% - Saving 8.78 MB of 22.87 MB
Progress: 39% - Saving 8.94 MB of 22.87 MB
Progress: 39% - Saving 9.09 MB of 22.87 MB
Progress: 40% - Saving 9.25 MB of 22.87 MB
Progress: 41% - Saving 9.41 MB of 22.87 MB
Progress: 41% - Saving 9.56 MB of 22.87 MB
Progress: 42% - Saving 9.72 MB of 22.87 MB
Progress: 43% - Saving 9.88 MB of 22.87 MB
Progress: 43% - Saving 10.03 MB of 22.87 MB
Progress: 44% - Saving 10.19 MB of 22.87 MB
Progress: 45% - Saving 10.34 MB of 22.87 MB
Progress: 45% - Saving 10.5 MB of 22.87 MB
Progress: 46% - Saving 10.66 MB of 22.87 MB
Progress: 47% - Saving 10.81 MB of 22.87 MB
Progress: 47% - Saving 10.97 MB of 22.87 MB
Progress: 48% - Saving 11.13 MB of 22.87 MB
Progress: 49% - Saving 11.28 MB of 22.87 MB
Progress: 50% - Saving 11.44 MB of 22.87 MB
Progress: 50% - Saving 11.59 MB of 22.87 MB
Progress: 51% - Saving 11.75 MB of 22.87 MB
Progress: 52% - Saving 11.91 MB of 22.87 MB
Progress: 52% - Saving 12.06 MB of 22.87 MB
Progress: 53% - Saving 12.22 MB of 22.87 MB
Progress: 54% - Saving 12.38 MB of 22.87 MB
Progress: 54% - Saving 12.53 MB of 22.87 MB
Progress: 55% - Saving 12.69 MB of 22.87 MB
Progress: 56% - Saving 12.84 MB of 22.87 MB
Progress: 56% - Saving 13 MB of 22.87 MB
Progress: 57% - Saving 13.16 MB of 22.87 MB
Progress: 58% - Saving 13.31 MB of 22.87 MB
Progress: 58% - Saving 13.47 MB of 22.87 MB
Progress: 59% - Saving 13.63 MB of 22.87 MB
Progress: 60% - Saving 13.78 MB of 22.87 MB
Progress: 60% - Saving 13.94 MB of 22.87 MB
Progress: 61% - Saving 14.09 MB of 22.87 MB
Progress: 62% - Saving 14.25 MB of 22.87 MB
Progress: 62% - Saving 14.41 MB of 22.87 MB
Progress: 63% - Saving 14.56 MB of 22.87 MB
Progress: 64% - Saving 14.72 MB of 22.87 MB
Progress: 65% - Saving 14.88 MB of 22.87 MB
Progress: 65% - Saving 15.03 MB of 22.87 MB
Progress: 66% - Saving 15.19 MB of 22.87 MB
Progress: 67% - Saving 15.34 MB of 22.87 MB
Progress: 67% - Saving 15.5 MB of 22.87 MB
Progress: 68% - Saving 15.66 MB of 22.87 MB
Progress: 69% - Saving 15.81 MB of 22.87 MB
Progress: 69% - Saving 15.97 MB of 22.87 MB
Progress: 70% - Saving 16.13 MB of 22.87 MB
Progress: 71% - Saving 16.28 MB of 22.87 MB
Progress: 71% - Saving 16.44 MB of 22.87 MB
Progress: 72% - Saving 16.59 MB of 22.87 MB
Progress: 73% - Saving 16.75 MB of 22.87 MB
Progress: 73% - Saving 16.91 MB of 22.87 MB
Progress: 74% - Saving 17.06 MB of 22.87 MB
Progress: 75% - Saving 17.22 MB of 22.87 MB
Progress: 75% - Saving 17.38 MB of 22.87 MB
Progress: 76% - Saving 17.53 MB of 22.87 MB
Progress: 77% - Saving 17.69 MB of 22.87 MB
Progress: 78% - Saving 17.84 MB of 22.87 MB
Progress: 78% - Saving 18 MB of 22.87 MB
Progress: 79% - Saving 18.16 MB of 22.87 MB
Progress: 80% - Saving 18.31 MB of 22.87 MB
Progress: 80% - Saving 18.47 MB of 22.87 MB
Progress: 81% - Saving 18.63 MB of 22.87 MB
Progress: 82% - Saving 18.78 MB of 22.87 MB
Progress: 82% - Saving 18.94 MB of 22.87 MB
Progress: 83% - Saving 19.09 MB of 22.87 MB
Progress: 84% - Saving 19.25 MB of 22.87 MB
Progress: 84% - Saving 19.41 MB of 22.87 MB
Progress: 85% - Saving 19.56 MB of 22.87 MB
Progress: 86% - Saving 19.72 MB of 22.87 MB
Progress: 86% - Saving 19.88 MB of 22.87 MB
Progress: 87% - Saving 20.03 MB of 22.87 MB
Progress: 88% - Saving 20.19 MB of 22.87 MB
Progress: 88% - Saving 20.34 MB of 22.87 MB
Progress: 89% - Saving 20.5 MB of 22.87 MB
Progress: 90% - Saving 20.66 MB of 22.87 MB
Progress: 90% - Saving 20.81 MB of 22.87 MB
Progress: 91% - Saving 20.97 MB of 22.87 MB
Progress: 92% - Saving 21.13 MB of 22.87 MB
Progress: 93% - Saving 21.28 MB of 22.87 MB
Progress: 93% - Saving 21.44 MB of 22.87 MB
Progress: 94% - Saving 21.59 MB of 22.87 MB
Progress: 95% - Saving 21.75 MB of 22.87 MB
Progress: 95% - Saving 21.91 MB of 22.87 MB
Progress: 96% - Saving 22.06 MB of 22.87 MB
Progress: 97% - Saving 22.22 MB of 22.87 MB
Progress: 97% - Saving 22.38 MB of 22.87 MB
Progress: 98% - Saving 22.53 MB of 22.87 MB
Progress: 99% - Saving 22.69 MB of 22.87 MB
Progress: 99% - Saving 22.84 MB of 22.87 MB
Progress: 100% - Completed download of C:\Users\Administrator\AppData\Local\Temp\chocolatey\tailscale\1.16.2\tailscale-ipn-setup-1.16.2.exe (22.87 MB).
Download of tailscale-ipn-setup-1.16.2.exe (22.87 MB) completed.
Hashes match.
Installing tailscale...
tailscale has been installed.
  tailscale may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of tailscale was successful.
  Software installed as 'exe', install location is likely default.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

2021/11/05 15:07:56Z: Userdata execution done
```

Is this what the issue is describing? Or is this a different issue?

**Comment by bradfitz** [comment] 2022-01-11 16:48
I'm not sure what this bug was about.

@12nick12, what did you expect to happen? What does "would make it start automatically" mean? Connect to a tailnet? Which?

Did you authenticate once already and reboot and it didn't come back up?

**Comment by 4fd81048-Brian** [comment] 2022-02-26 01:53
I might be having this problem.  Server 2019 Core, installed 1.24.0 and ran tailscale up --unattended.  Authenticated, all is well.  Reboot and tailscale doesn't run, tailscale status says logged out.

**Comment by 4fd81048-Brian** [comment] 2022-02-26 14:37
Uninstalled 1.22 and installed 1.18, where --unattended has worked before, but on this machine it still won't start on reboot.  I did try adding --login-server={default}, which the original bug reporter indicated might resolve, but that didn't work for me.

```
(logID "1452f7ae647d67815ddb410e00da45601cacf2322a9b0341f13c68c61316644b")
2022-02-26T09:31:06.531-05:00: Program starting: v1.18.0-t22d969975-g7022e5a4c: []string{"C:\\Program Files (x86)\\Tailscale IPN\\tailscaled.exe", "/subproc", "1452f7ae647d67815ddb410e00da45601cacf2322a9b0341f13c68c61316644b"}
2022-02-26T09:31:06.557-05:00: subproc mode: logid=1452f7ae647d67815ddb410e00da45601cacf2322a9b0341f13c68c61316644b
2022-02-26T09:31:06.557-05:00: tailscaled: getting engine... (try 1)
2022-02-26T09:31:06.677-05:00: Listening on 127.0.0.1:41112
2022-02-26T09:31:06.769-05:00: ipnserver: found server mode auto-start key "user-S-1-5-21-3330891392-56027452-1015139109-500" (user HV-31X3FQ1\Administrator)
2022-02-26T09:31:07.362-05:00: Using existing driver 0.14
2022-02-26T09:31:07.370-05:00: Creating adapter
2022-02-26T09:31:22.260-05:00: Timed out waiting for device query: The wait operation timed out. (Code 0x00000102)
2022-02-26T09:31:22.260-05:00: Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC0000035): Cannot create a file when that file already exists. (Code 0x000000B7)
2022-02-26T09:31:22.376-05:00: tailscaled: engine fetch error (try 1) in 15.956s (total 15.956s, sysUptime 30s): TUN: Error creating interface: Cannot create a file when that file already exists.
2022-02-26T09:31:27.218-05:00: tailscaled: getting engine... (try 2)
2022-02-26T09:31:27.333-05:00: Using existing driver 0.14
2022-02-26T09:31:27.340-05:00: Creating adapter
2022-02-26T09:31:27.646-05:00: waitInterfaceUp: TUN interface already up; no need to wait
2022-02-26T09:31:27.658-05:00: WSL: could not list distributions: wslRun([wsl.exe -l]): An attempt was made to reference a token that does not exist.: ""
2022-02-26T09:31:27.691-05:00: dns: using dns.windowsManager
2022-02-26T09:31:27.691-05:00: link state: interfaces.State{defaultRoute=vEthernet (Main) (Hyper-V Virtual Ethernet Adapter) ifs={vEthernet (Main):[192.168.223.27/24]} v4=true v6=false}
2022-02-26T09:31:27.701-05:00: magicsock: disco key = d:f163836dffabf433
2022-02-26T09:31:27.701-05:00: Creating wireguard device...
2022-02-26T09:31:27.708-05:00: Bringing wireguard device up...
2022-02-26T09:31:27.708-05:00: [v2] UDP bind has been updated
2022-02-26T09:31:27.708-05:00: [v2] Interface state was Down, requested Up, now Up
2022-02-26T09:31:27.708-05:00: Bringing router up...
2022-02-26T09:31:27.708-05:00: router: firewall: marking for removal
2022-02-26T09:31:27.708-05:00: router: firewall: starting netsh goroutine
2022-02-26T09:31:27.711-05:00: [v2] Routine: receive incoming v4 - started
2022-02-26T09:31:27.711-05:00: [v2] Routine: receive incoming receiveDERP - started
2022-02-26T09:31:27.711-05:00: router: firewall: clearing Tailscale-In firewall rules...
2022-02-26T09:31:27.711-05:00: [v2] Routine: receive incoming v6 - started
2022-02-26T09:31:27.716-05:00: router: monitorDefaultRoutes done after 5ms
2022-02-26T09:31:27.716-05:00: Clearing router settings...
2022-02-26T09:31:27.716-05:00: router: firewall: marking for removal
2022-02-26T09:31:28.303-05:00: Starting link monitor...
2022-02-26T09:31:28.303-05:00: Engine created.
2022-02-26T09:31:28.303-05:00: monitor: got windows change event after 0s: evt=route
2022-02-26T09:31:28.303-05:00: monitor: got windows change event after 0s: evt=route
2022-02-26T09:31:28.303-05:00: monitor: got windows change event after 0s: evt=route
2022-02-26T09:31:28.303-05:00: monitor: got windows change event after 0s: evt=route
2022-02-26T09:31:28.303-05:00: monitor: got windows change event after 0s: evt=route
2022-02-26T09:31:28.304-05:00: tailscaled: got engine on try 2 in 1.117s (total 1.117s)
2022-02-26T09:31:28.325-05:00: [v1] LinkChange: minor
2022-02-26T09:31:28.325-05:00: [v1] magicsock: starting endpoint update (link-change-minor)
2022-02-26T09:31:28.337-05:00: [v1] magicsock: ignoring pre-DERP map, STUN-less endpoint update: [{192.168.223.27:41641 local}]
2022-02-26T09:31:28.404-05:00: netmap packet filter: (not ready yet)
2022-02-26T09:31:28.404-05:00: Start
2022-02-26T09:31:28.449-05:00: using backend prefs
2022-02-26T09:31:28.449-05:00: backend prefs for "user-S-1-5-21-3330891392-56027452-1015139109-500": Prefs{ra=false dns=true want=true server=true Persist=nil}
2022-02-26T09:31:28.449-05:00: Start: serverMode=true
2022-02-26T09:31:28.449-05:00: got initial portlist info in 0s
2022-02-26T09:31:28.450-05:00: control: HostInfo: {"IPNVersion":"1.18.0-t22d969975-g7022e5a4c","BackendLogID":"1452f7ae647d67815ddb410e00da45601cacf2322a9b0341f13c68c61316644b","OS":"windows","OSVersion":"10.0.17763.2565","Hostname":"HV-31X3FQ1","GoArch":"amd64","Services":[{"Proto":"tcp","Port":3389,"Description":"TermService"}]}
2022-02-26T09:31:28.450-05:00: Backend: logs: be:1452f7ae647d67815ddb410e00da45601cacf2322a9b0341f13c68c61316644b fe:
2022-02-26T09:31:28.450-05:00: control: authRoutine: state:new; goal=nil paused=false
2022-02-26T09:31:28.451-05:00: control: mapRoutine: state:new
2022-02-26T09:31:28.451-05:00: Switching ipn state NoState -> NeedsLogin (WantRunning=true, nm=false)
2022-02-26T09:31:28.451-05:00: blockEngineUpdates(true)
2022-02-26T09:31:28.451-05:00: health("overall"): error: state=NeedsLogin, wantRunning=true
2022-02-26T09:31:28.451-05:00: wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
2022-02-26T09:31:28.451-05:00: wgengine: Reconfig: configuring router
2022-02-26T09:31:28.451-05:00: router: firewall: marking for removal
2022-02-26T09:31:28.473-05:00: wgengine: Reconfig: configuring DNS
2022-02-26T09:31:28.474-05:00: dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
2022-02-26T09:31:28.474-05:00: dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
2022-02-26T09:31:28.474-05:00: dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
2022-02-26T09:31:28.474-05:00: [v1] wgengine: Reconfig done
2022-02-26T09:31:28.474-05:00: running ipconfig /registerdns ...
2022-02-26T09:31:28.485-05:00: WSL SetDNS: wslRun([wsl.exe -l]): An attempt was made to reference a token that does not exist.: ""
2022-02-26T09:31:28.597-05:00: [v1] LinkChange: minor
2022-02-26T09:31:28.597-05:00: [v1] magicsock: starting endpoint update (link-change-minor)
2022-02-26T09:31:28.597-05:00: netmap packet filter: (not ready yet)
2022-02-26T09:31:28.607-05:00: router: firewall: cleared Tailscale-In firewall rules in 921ms
2022-02-26T09:31:28.607-05:00: router: firewall: deleting any prior Tailscale-Process rule...
2022-02-26T09:31:28.609-05:00: [v1] magicsock: ignoring pre-DERP map, STUN-less endpoint update: [{192.168.223.27:41641 local}]
2022-02-26T09:31:28.670-05:00: router: firewall: removed old Tailscale-Process rule in 65ms
2022-02-26T09:31:28.670-05:00: router: firewall: adding Tailscale-Process rule to allow UDP for "C:\\Program Files (x86)\\Tailscale IPN\\tailscaled.exe" ...
2022-02-26T09:31:28.732-05:00: monitor: got windows change event after 440ms: evt=addr
2022-02-26T09:31:28.756-05:00: router: firewall: added Tailscale-Process rule in 88ms
2022-02-26T09:31:28.756-05:00: router: firewall: ending netsh goroutine
2022-02-26T09:31:28.872-05:00: [v1] LinkChange: minor
2022-02-26T09:31:28.872-05:00: [v1] magicsock: starting endpoint update (link-change-minor)
2022-02-26T09:31:28.883-05:00: [v1] magicsock: ignoring pre-DERP map, STUN-less endpoint update: [{192.168.223.27:41641 local}]
2022-02-26T09:31:31.430-05:00: ran ipconfig /registerdns in 3.029s
2022-02-26T09:31:31.430-05:00: running ipconfig /flushdns ...
2022-02-26T09:31:31.458-05:00: ran ipconfig /flushdns in 29ms
2022-02-26T09:31:33.439-05:00: control: HostInfo: {"IPNVersion":"1.18.0-t22d969975-g7022e5a4c","BackendLogID":"1452f7ae647d67815ddb410e00da45601cacf2322a9b0341f13c68c61316644b","OS":"windows","OSVersion":"10.0.17763.2565","Hostname":"HV-31X3FQ1","GoArch":"amd64"}
2022-02-26T09:31:33.439-05:00: control: [v1] cancelMapSafely: synced=false
2022-02-26T09:31:33.439-05:00: control: [v1] cancelMapSafely: wrote to channel
2022-02-26T09:31:33.439-05:00: control: mapRoutine: new map needed while idle.
2022-02-26T09:31:33.439-05:00: control: mapRoutine: state:new
2022-02-26T09:31:33.629-05:00: monitor: got windows change event after 5.01s: evt=addr
2022-02-26T09:31:33.654-05:00: [v1] LinkChange: minor
2022-02-26T09:31:33.654-05:00: [v1] magicsock: starting endpoint update (link-change-minor)
2022-02-26T09:31:33.666-05:00: [v1] magicsock: ignoring pre-DERP map, STUN-less endpoint update: [{192.168.223.27:41641 local}]
2022-02-26T09:31:37.055-05:00: monitor: got windows change event after 3.486s: evt=route
2022-02-26T09:31:37.055-05:00: monitor: got windows change event after 0s: evt=route
2022-02-26T09:31:37.055-05:00: monitor: got windows change event after 0s: evt=route
2022-02-26T09:31:37.062-05:00: monitor: got windows change event after 7ms: evt=addr
2022-02-26T09:31:37.088-05:00: [v1] LinkChange: minor
2022-02-26T09:31:37.088-05:00: [v1] magicsock: starting endpoint update (link-change-minor)
2022-02-26T09:31:37.098-05:00: [v1] magicsock: ignoring pre-DERP map, STUN-less endpoint update: [{192.168.223.27:41641 local}]
2022-02-26T09:31:37.357-05:00: [v1] LinkChange: minor
2022-02-26T09:31:37.357-05:00: [v1] magicsock: starting endpoint update (link-change-minor)
2022-02-26T09:31:37.368-05:00: [v1] magicsock: ignoring pre-DERP map, STUN-less endpoint update: [{192.168.223.27:41641 local}]
2022-02-26T09:32:47.702-05:00: client disconnected; staying alive in server mode

```

**Comment by 4fd81048-Brian** [comment] 2022-02-26 15:43
Uninstalled. removed C:\ProgramData\Tailscale. Rebooted. Installed 1.18, 'tailscale up --unattended' authenticated with a different account, confirmed it was up.  sc stop tailscale, sc start tailscale and it didn't reconnect, so the problem is not the reboot, it's easy to reproduce just by stopping and starting the service.

**Comment by 4fd81048-Brian** [comment] 2022-02-26 16:10
Might be a duplicate of #2137

**Comment by rlabrecque** [comment] 2022-04-24 18:51
Hey there, more info here:

I run the following on a machine (both Windows 10 and Windows Server 2019) without tailscale installed:

```
msiexec /i "tailscale-setup-1.24.0-amd64.msi" /quiet
& "C:\Program Files\Tailscale\tailscale.exe" up --authkey="tskey-redacted" --unattended
```

My machine is successfully connected to tailscale, when I reboot my machine is not connected to tailscale until after I manually log in to Windows.

If I run `tailscale down`, then launch the GUI, then connect, then [optionally?] toggle the unattended preference off, and then back on, it presents a dialog asking if I'm sure, then I reboot, unattended works as expected.

The issue seems isolated to the command line tailscale.exe with --unattended. (My thinking is that --unattended doesn't take because we don't get to confirm it like the GUI?) Or maybe related to using --authkey ?

**Comment by rlabrecque** [comment] 2022-04-29 04:51
Update: My issue does seem to be specifically related to using `--unattended` and `--authkey` at the same time. Doing `tailscale up --unattended` then logging in with the link provided seems to work for me. OPs issue might be explained by using `--unattended` and `--login-server` at the same time.

**Comment by seansaleh** [comment] 2022-05-25 10:18
@rlabrecque and @jazzdan I think I have a workaround for you in https://github.com/tailscale/tailscale/issues/2137#issuecomment-1137058471

One thing you had wrong, even if this bug is fixed, is in Powershell you need to wait for the MSI installer to finish. You can do this with `& msiexec /i "tailscale-setup-1.24.2-amd64.msi" /quiet | Out-Host`

**Comment by DentonGentry** [comment] 2022-10-30 12:15
Possibly related to use of HKLM before anyone has logged in: https://github.com/tailscale/tailscale/issues/2346

**Closed as completed** 2022-11-10 16:43 UTC
Labels: OS-windows, L3 Some users, P2 Aggravating, T5 Usability, bug

**Comment by catscandrive** [comment] 2024-11-15 03:09
This is still broken on 1.76.6

**Comment by ilCosmico** [comment] 2026-08-15 05:48
Confirming this workaround fixed it for me. Tailscale 1.102.2 on Windows 11, tailscaled stayed `Logged out.` after a reboot triggered non-interactively (no console login involved), and only reconnected once someone logged in physically at the console.

Toggling "Run unattended" off then back on once from the tray GUI fixed it: tested a reboot afterward with no interactive login and Tailscale came back online on its own.
