### ISSUE TITLE
iOS connection switch becomes inoperable occasionally when tunnel is disconnected

### ISSUE THREAD

**Issue by jacewalker** [tailscale/tailscale#6532] opened 2022-11-27 19:58 UTC
Since iOS 16, Tailscale for iOS appears to be authenticated and connected, however switching the connection to ‘on’ doesn’t initiative the VPN connection in iOS and it just hangs.

It appears the authenticated session expires however the app doesn’t notify the user which leads to guessing a solution 

Reauthenticating fixes the issue.

1. Can it be more obvious that the authenticated session has expired?
2. Since IOS 16, has the auth session expiry been reduced? I’ve never had this happen so often, previously I would rarely need to re auth. 

All issues started the day after iOS 16 update
(Another issue was that you could not actually disconnect from the VPN in the TS app, only through the iOS settings app, but I believe this has been fixed)

BUG-f213c6de826a44bc447550951a8d77eb8126ba0e9ba751eed64cf61634128b74-20221127195809Z-4addc4e696c8bbd9

**Comment by nickoneill** [comment] 2022-11-28 17:36
I don't think this is expiry, but it might be hitting #4646 where iOS 16 has started more aggressively shutting down extensions during periods where the system needs more resources. We do get into a state where we don't try to start the extension again sometimes (I don't have a clear repro case for this), and that leads to the switch issue you mentioned. Going to slightly rework the title here too

**Comment by DentonGentry** [comment] 2023-06-03 23:58
Duplicate of https://github.com/tailscale/tailscale/issues/4646

**Closed by DentonGentry** 2023-06-03 23:58 UTC
Labels: OS-ios, L1 Very few, P1 Nuisance, T5 Usability, bug
