### ISSUE TITLE
FR: Please Open UDP ports (20000-40000) to use Pikvm via Funnel

### ISSUE THREAD

**Issue by edwinrivera19955** [tailscale/tailscale#13771] opened 2024-10-10 14:24 UTC
### What are you trying to do?

I am trying to connect to Pikvm over Internet.
I made a funnel and 443 port works well. However, I need to use H264 streaming in Pikvm and Funnel needs to listen to 20000-40000 ports for UDP.

### How should we solve this?

Please make Funnel listen to 20000-40000 ports.

### What is the impact of not solving this?

I can't expose Pikvm service over Internet.

**Comment by agottardo** [comment] 2024-10-10 20:40
Duplicate of https://github.com/tailscale/tailscale/issues/6953

**Closed by agottardo** 2024-10-10 20:40 UTC
Labels: needs-triage, fr
