### ISSUE TITLE
FR: custom assigns ip range to avoid network segment conflict

### ISSUE THREAD

**Issue by cloverzrg** [tailscale/tailscale#8229] opened 2023-05-29 03:27 UTC
### What are you trying to do?

use tailscale in my company

### How should we solve this?

ability to custom assigns ip range

### What is the impact of not solving this?

some company  website can not access when i am using tailscale in office
<img width="507" alt="image" src="https://github.com/tailscale/tailscale/assets/13957666/75d9cffc-b215-4ab5-9b32-242161fe7e9b">

**Comment by DentonGentry** [comment] 2023-05-29 04:18
Duplicate of https://github.com/tailscale/tailscale/issues/1381

**Closed by DentonGentry** 2023-05-29 04:18 UTC
Labels: needs-triage, fr
