### ISSUE TITLE
tailscale enables the selection of a specific NIC device

### ISSUE THREAD

**Issue by Firsgith** [tailscale/tailscale#8889] opened 2023-08-15 15:53 UTC
### What are you trying to do?

The computers in the office have two NICs, one of which can only access intranet resources, while the other is just the opposite and can only connect to the extranet. All outgoing network is routed through that one NIC that can only access intranet resources, which results in tailscale not being able to network with the extranet. I wish tailscale would select a specific NIC device for networking, so that computers with more than one NIC could use the correct NIC to set up a tailnet.

### How should we solve this?

Add a NIC device selector

### What is the impact of not solving this?

Computers or Servers that have multiple NIC devices accessing different network resources will allow tailscale to correctly form the tailnet.

**Comment by DentonGentry** [comment] 2023-09-01 02:35
Duplicate of https://github.com/tailscale/tailscale/issues/1552

**Closed by DentonGentry** 2023-09-01 02:35 UTC
Labels: needs-triage, fr
