### ISSUE TITLE
FR: Only add OS routes for nodes that are visible with ACL rules

### ISSUE THREAD

**Issue by Xe** [tailscale/tailscale#4316] opened 2022-03-29 17:07 UTC
### What are you trying to do?

Large deployments of Tailscale can have a lot of subnets routed and thrown around. It would be nice to be able to have machines on the tailnet not get the metadata of all the routes that the tailnet has exposed.

### How should we solve this?

Limit the routes programmed into the OS routing table to the routes that the ACL allows.

### What is the impact of not solving this?

There is no workaround for this.

### Anything else?

[Front Conversation](https://app.frontapp.com/open/msg_1531okup)

**Comment by DentonGentry** [comment] 2022-05-08 01:51
Duplicate of https://github.com/tailscale/tailscale/issues/1357

**Closed by DentonGentry** 2022-05-08 01:51 UTC
Labels: L3 Some users, P2 Aggravating, T5 Usability, fr
