### ISSUE TITLE
Tailscale will not start on MX linux - need SysVinit support!

### ISSUE THREAD

**Issue by Danathar** [tailscale/tailscale#9695] opened 2023-10-06 19:00 UTC
### What is the issue?

MX Linux, a widely recognized distribution, utilizes SysVinit as its default init system. While it's possible to boot into systemd when MX Linux is installed on an SSD, the live-USB version strictly operates with the traditional SystemV init system and cannot use systemD.

Tailscale is not compatible with SysVinit, which can cause issues for users (Well..it doesn't work!) attempting to run Tailscale on MX Linux due to this compatibility.

Thanks for looking into this! Ahem...... zerotier checks to see if sysVinit is being used and their script works accordingly ;)

### Steps to reproduce

Executing `tailscale up` results in `failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)`

### OS

Linux

### OS version

MX Version 23

### Tailscale version

1.5

**Comment by bradfitz** [comment] 2023-10-06 20:58
This is effectively a duplicate of #9502 where you've already commented so I'll just close this of a dup of that one and rename its title to broaden its scope slightly.

> Ahem...... zerotier checks to see if sysVinit is being used and their script works accordingly ;)

This is a tired strategy online. Be better.

**Closed by bradfitz** 2023-10-06 20:58 UTC
Labels: needs-triage, bug

**Comment by Danathar** [comment] 2023-10-06 21:40
> This is effectively a duplicate of #9502 where you've already commented so I'll just close this of a dup of that one and rename its title to broaden its scope slightly.
> 
> > Ahem...... zerotier checks to see if sysVinit is being used and their script works accordingly ;)
> 
> This is a tired strategy online. Be better.

My apologies. It WAS in bad taste. I do appreciate the quickness that you saw it though.
