### ISSUE TITLE
FR: Australian Support for Mullvad 

### ISSUE THREAD

**Issue by calejoh** [tailscale/tailscale#10390] opened 2023-11-27 12:23 UTC
### What are you trying to do?

Hi,

Tailscale/Mullvad support would be great for Australia. Just tried to purchase and was alerted Australia is not a support region. So just putting the request out there. 

Thanks. 

Cale.

**Comment by DentonGentry** [comment] 2023-11-27 12:26
Duplicate of https://github.com/tailscale/tailscale/issues/9314

**Closed by DentonGentry** 2023-11-27 12:26 UTC
Labels: needs-triage, fr
