### ISSUE TITLE
Tailnet lock. Nodes suddenly and randomly getting locked out

### ISSUE THREAD

**Issue by Triarii1** [tailscale/tailscale#13541] opened 2024-09-21 06:40 UTC
### What is the issue?

Tailnet lock has been working flawlessly for months across all of my devices.

Linux servers - Debian Bookworm
NAS - Qnap
Android
Windows

Over the past 24 - 48h, some of them get suddenly locked out, NAS, android or Linux servers. I have to each time manually sign again to re allow. 

This is clearly a bug as have seen users report the same on Reddit.

All of my servers/android etc are the latest version.

### Steps to reproduce

As above

### OS

Linux, Windows, Android, Other

### OS version

Debían 12 Bookworm, Android 14, Windows 11, QNAP Nas Docker 

### Tailscale version

Latest across devices

**Comment by sailorfrag** [comment] 2024-09-21 19:37
A bug report at the first moment you notice a device is locked out would really help so we can look at the logs.

Can you elaborate on what was happening when the device got locked out? Did its key expire and you logged it back in? Did you recently update Tailscale versions? Did it happen while you were actively doing something or just sometime in the background?

There are a few things that changed recently which could be related, but there isn't enough detail here to narrow that down.

**Comment by sailorfrag** [comment] 2024-09-21 19:39
Also, please run `tailnet lock status` and `tailnet lock log` on as many devices as you can. You can redact personal details (e.g. device names) here or send the information to support@tailscale.com and reference this issue.

**Comment by nifoc** [comment] 2024-09-22 00:11
I'm seeing basically the same people thing.

For me it's only my new phone that seemingly randomly looses access to my locked tailnet.

**Comment by Patriot2407** [comment] 2024-09-22 01:38
Keeps happening to me on linux nodes only, android and windows seems fine

**Comment by sailorfrag** [comment] 2024-09-22 01:51
There were some changes in progress on the server side over the past week that could affect tailnet lock. They are now complete. Although I have not determined the cause of the problems being reported yet, finishing the rollout of those changes may have solved the issue, so please check again. If the problem reappears, a bugreport and description of what you were doing at the time would be helpful.

**Comment by udf2457** [comment] 2024-09-22 11:05
> description of what you were doing at the time

I can't speak for everyone here, but I think the point is @sailorfrag  that "what you were doing at the time" equates to nothing, nada, zilch.

In my case it has been a repetitive case of signing nodes and then after $time, those nodes switch back to locked-out status.  Sign them again, they come back online, then the whole saga repeats itself again.   Rinse and repeat ad-infinitum.

**Comment by sailorfrag** [comment] 2024-09-22 14:51
Thanks for the additional information. Based on that, I suspect the changes made yesterday are not likely to affect this problem, it would be more likely to apply when changing a device's IP address or adding/removing it from another tailnet via sharing. 

When the problem occurs, do you find that you need to re-sign all nodes or just one? 

An example tailnet in this broken state would be immensely helpful, along with `tailnet lock log` and `tailnet lock status` from as many devices as possible. Also, any details about if the devices getting locked out are involved in sharing: have you shared it to anyone?
Has anyone shared a device with you? If you can send that along with a `tailscale bugreport` or the name of your tailnet to support@tailscale.com referencing this issue, it will help a lot. It would only need to stay broken for long enough for me to collect some details. 

Where are you seeing that it is locked out? On the device itself? On the admin panel? Both? If only on the admin panel, can you still connect to other devices?

**Comment by ttxxaa** [comment] 2024-09-22 17:08
I am affected the same way. 

Here are 2 bug reports (tailscale bugreport --record):
Before lock-out:
BUG-c3d98c6d94b5e678de1795eed11f6100ad8323d827643e4e6f3dcc690e99fabc-20240921211546Z-667e7bfb07a96800
After lock-out.
BUG-c3d98c6d94b5e678de1795eed11f6100ad8323d827643e4e6f3dcc690e99fabc-20240921213413Z-e67a5402a056b683

The node is mainly serving a DNS service in my tailnet.
I resigned the machine already. 
On the admin panel and on the device itself it showed the status "locked out". The node was not reachable anymore in the tailnet. I only hat to resign that affected node. I don't have any shares and nobody shares with me.

Next time it happens, I can provide "tailnet lock log" and "tailnet lock status" in broken state.

**Comment by sailorfrag** [comment] 2024-09-22 19:00
> BUG-c3d98c6d94b5e678de1795eed11f6100ad8323d827643e4e6f3dcc690e99fabc-20240921211546Z-667e7bfb07a96800

@ttxxaa From those logs, that looks like tailscale coming up with no existing configuration and it'll need a signature because you signed it in for the first time. I think that is expected.

**Comment by ttxxaa** [comment] 2024-09-22 20:48
@sailorfrag argh then i toggled bug report numbers i guess. I removed it after it happenend the 2nd time. Since then no lock out so far. Will come back if it happens again.

**Comment by udf2457** [comment] 2024-09-24 08:27
> Where are you seeing that it is locked out? On the device itself? On the admin panel? Both?

Both.

**Comment by sailorfrag** [comment] 2024-09-24 15:11
We found a bug that was fixed by the deployment over this past weekend, so problem should not reappear for any nodes that were signed after 2024-09-21 21:19:06 UTC. Unfortunately, we can not retroactively fix tailnets that are affected by this because the signatures are lost and we do not have the ability to recreate them (by design, since that's the purpose of Tailnet Lock).

Nodes signed before 2024-09-16 01:33:45 UTC should also be unaffected. Signatures made between those two times were not stored, due to a programming error.

If you do discover this problem continuing to occur, please respond and we can investigate further.

**Closed by sailorfrag** 2024-09-24 15:11 UTC
Labels: waiting-for-info, needs-triage, bug, tailnet-lock

**Comment by raeraex2** [comment] 2024-09-25 16:53
As I had this issue, I simply disabled tailnet lock.

Concurrently, I'm also trying to understand why one of my shared node is no more accessible. I saw these messages in the log:

```
raspnew tailscaled[3204]: Network lock is dropping peer nodeid:1693bf722320b3(nthPJrS9dr11CNTRL) due to missing signature
```

That's highly suspicious as tailnet lock is disabled.

**Comment by sailorfrag** [comment] 2024-09-25 18:27
> That's highly suspicious as tailnet lock is disabled.

Can you check if `tailnet lock status` indicates that the device believes tailnet lock is enabled? If so, you can recover with `tailnet lock local-disable` but how it failed to learn that tailnet lock was disbled should be investigated.

**Comment by raeraex2** [comment] 2024-09-25 18:50
You are right, I found at least two nodes (linux, 1.74.1) that believed that lock was enabled. Your command solved the issue and sharing works again.

(as an aside, sharing is still supposed to work if I enable tailscale lock again in the future, right?)

**Comment by Patriot2407** [comment] 2024-10-08 13:53
Coming back to report this does indeed seem to have resolved my issues
