### ISSUE TITLE
M1/M2 doesn't connect on macOS startup

### ISSUE THREAD

**Issue by zigg** [tailscale/tailscale#7107] opened 2023-01-29 13:29 UTC
### What is the issue?

When logging in, Tailscale shows the icon with the ⚠️ sign in the menu bar instead of connecting to the tailnet.

Quitting and restarting Tailscale solves the issue.

### Steps to reproduce

1. Preferences > Start At Login on
2. Restart Mac

### Are there any recent changes that introduced the issue?

This seems to be a 1.36.0 issue. I'm also for the first time using this on a new M2 MacBook Pro, so I'm not sure if that's an issue or not.

**MORE:** Confirmed that it is _not_ an issue on my 2018 i9 MacBook Pro, also running Ventura 13.2.

Here's what the Tailscale menu looks like on login on the M2:

<img width="232" alt="image" src="https://user-images.githubusercontent.com/56017/215337792-4910b96f-47a0-42f9-9071-5d467c8eb53d.png">

Quitting Tailscale and reopening it always fixes the issue.

### OS

macOS

### OS version

Ventura 13.2

### Tailscale version

1.36.0 (App Store)

### Bug report

BUG-10bf099df1b3d17775160fa23ac75ae2da07e70f607d4062c059d82f00664e7f-20230129132846Z-4c3b36128b000875

**Comment by gkoster** [comment] 2023-01-29 15:50
Have the same issue on MacOS Ventura 13.2, MBP M1 Pro, TailScale version 1.36.0 (App Store). I updates from a 1.34 version, with which I had the same problem, so upgraded to the 1.36 version.

**Comment by zigg** [comment] 2023-01-29 16:36
@gkoster Thanks for the note. I updated the bug info to reflect that this seems to be an M1/M2 issue.

**Comment by bradfitz** [comment] 2023-01-29 23:09
cc @mihaip

**Comment by cp0k** [comment] 2023-01-30 23:28
Thanks to my colleague @rx294 I was able to successfully log back into Tailscale using the following version:

```
➜  ~ tailscale -V                                                
1.30.0
  tailscale commit: 7fd4d617ac757343534966ada10a6b70092d35ed
  other commit: 7395c0dee48cc2cda49fd9b37335d9c10efc284c
  go version: go1.19-ts6dca83b256
```

**Comment by bradfitz** [comment] 2023-01-30 23:34
Let's please not muddy this bug up with a mix of issues and mix of versions.

**Comment by mihaip** [comment] 2023-01-31 02:31
This is sounding very similar to #6706 (see specifically https://github.com/tailscale/tailscale/issues/6706#issuecomment-1409652973). Do either of you observe that it takes a while for network connectivity to come up (possibly after Tailscale starts)?

**Comment by gkoster** [comment] 2023-01-31 07:33
I checked the comments in #6706 and it's the same behaviour as I see. If Tailscale does not connect during startup (with automatic start) I cannot get it working. After a few reboots reboots, and TailScale connects, it's stable and have no problems during that session. Even if the machine goes to sleep, and it wakes up, Tailscale is still working fine.

**Comment by zigg** [comment] 2023-01-31 12:29
> This is sounding very similar to #6706 (see specifically [#6706 (comment)](https://github.com/tailscale/tailscale/issues/6706#issuecomment-1409652973)). Do either of you observe that it takes a while for network connectivity to come up (possibly after Tailscale starts)?

Ahhhh, yeah, okay. I just did a few reboots on the M2 and watched the menu bar intently.

What's super interesting is that the WiFi icon will start coming up, then go gray ("disabled"), then start coming up one more time before finally connecting.

I _did_ observe Tailscale coming up successfully some of those times. It seemed its menu bar icon appeared after WiFi was settled in those cases.

In another case, it came up before WiFi was settled, then got stuck in ⚠️. In that case, it has the behavior above; the "Log in…" menu item will not work at all; and quitting and restarting the client gets me settled for the rest of my session.

This does sound a lot like a duplicate of #6706, @mihaip. Sorry for not spotting it!

**Comment by mihaip** [comment] 2023-01-31 17:02
Thanks for confirming, will close this as a duplicate of #6706 -- please subscribe to that issue for updates.

**Closed by mihaip** 2023-01-31 17:02 UTC
Labels: OS-macos, needs-triage, bug
