### ISSUE TITLE
Taildrop replaces spaces with %20 in filenames

### ISSUE THREAD

**Issue by gingerbeardman** [tailscale/tailscale#8621] opened 2023-07-14 19:13 UTC
### What is the issue?

- Taildrop replaces spaces with %20 in filenames

### Steps to reproduce

1. Taildrop a local file with spaces in the name, eg. "This is a test.txt"
2. Check filename of received file

### Are there any recent changes that introduced the issue?

- n/a

### OS

macOS, Synology

### OS version

macOS 12.6.7, Synology 6.2.3

### Tailscale version

1.44.0 (macOS), 1.38.4 (Synology)

**Comment by d5aqoep** [comment] 2023-07-26 13:30
This happens on QNAP too

**Comment by DentonGentry** [comment] 2023-09-01 02:43
Duplicate of https://github.com/tailscale/tailscale/issues/7874

**Closed by DentonGentry** 2023-09-01 02:43 UTC
Labels: needs-triage, bug
