### ISSUE TITLE
VPN On-Demand doesn't retain settings

### ISSUE THREAD

**Issue by bekuhl** [tailscale/tailscale#9257] opened 2023-09-06 14:38 UTC
When turning VPN On-Demand off and back on it does not retain settings for wifi and cellular networks. 
Additionally it should retain which wifi networks you have customized for when to engage.

**Comment by agottardo** [comment] 2023-09-07 17:09
Duplicate of #8956.

**Closed by agottardo** 2023-09-07 17:09 UTC
