### ISSUE TITLE
FR: Slow package download from Asia - maybe CDNs?

### ISSUE THREAD

**Issue by morpig** [tailscale/tailscale#8268] opened 2023-06-04 11:01 UTC
### What are you trying to do?

I noticed that while updating my tailscale client on MacOS, downloading the update takes forever.

Looking at pkgs.tailscale.com, apparently it is hosted in the US, while I'm downloading it from Asia.

```
 5. 180.87.12.233                                                                                            0.0%    68   47.7  56.6  44.9  84.7  10.1
 6. ix-hge-0-0-0-2.ecore2.svw-singapore.as6453.net                                                          88.1%    68   50.6  68.0  43.6 144.0  32.0
 7. if-ae-25-2.tcore1.svw-singapore.as6453.net                                                              68.7%    68   45.4  61.9  45.4 101.2  16.2
 8. if-be-45-2.ecore2.esin4-singapore.as6453.net                                                            50.0%    68   58.5  60.5  46.9 154.3  18.2
 9. ae-5.r23.sngpsi07.sg.bb.gin.ntt.net                                                                     65.7%    68   49.0  59.7  45.6  87.0  10.8
10. ae-17.r31.tokyjp05.jp.bb.gin.ntt.net                                                                     0.0%    68  134.2 128.0 111.0 206.4  17.4
11. ae-2.r30.tokyjp05.jp.bb.gin.ntt.net                                                                      0.0%    68  125.9 137.8 121.5 192.7  13.7
12. ae-5.r24.sttlwa01.us.bb.gin.ntt.net                                                                      7.4%    68  217.5 226.2 212.2 282.5  13.0
13. ae-11.r20.nwrknj03.us.bb.gin.ntt.net                                                                    14.9%    68  276.4 277.7 263.1 328.3  12.3
14. ae-0.a01.nycmny17.us.bb.gin.ntt.net                                                                      0.0%    68  286.5 278.2 261.3 336.6  14.8
15. (waiting for reply)
16. (waiting for reply)
17. pkgs.tailscale.com                                                                                      11.9%    67  311.7 291.2 275.7 334.5  12.9
```

### How should we solve this?

Put pkgs repo under a CDN? 

Highly recommend Cloudflare R2 to keep costs low as they don't charge for egress (and caching non-HTML is possible under R2.)

### What is the impact of not solving this?

Slow downloads from distant countries

**Comment by DentonGentry** [comment] 2023-06-04 20:44
Duplicate of https://github.com/tailscale/tailscale/issues/4247

**Closed by DentonGentry** 2023-06-04 20:44 UTC
Labels: fr
