### ISSUE TITLE
FR: Android application exclusion 

### ISSUE THREAD

**Issue by Oren2048** [tailscale/tailscale#11208] opened 2024-02-23 10:23 UTC
### What are you trying to do?

Set certain applications to "ignore" the tailscale tunnel

### How should we solve this?

In the official Wireguard application for Android there is a feature where you can select certain applications which will be excluded from the Wireguard tunnel, would it be possible to add such into the Tailscale app as well?

### What is the impact of not solving this?

When using an exit node in other countries than where you are currently at, all traffic is routed through that country. however, certain apps (such as government, banks) are blocked to IPs from outside the country. the only solution is to shutdown Tailscale. however in the official Wireguard app you can simply tell it that this and that app should be excluded and you can stay connected 24/7 knowing all your traffic other than those apps are going via Tailscale

**Comment by stp-ip** [comment] 2024-03-08 12:32
Duplicate of #6912?

**Comment by agottardo** [comment] 2024-06-26 16:58
Duplicate of #6912

**Closed by agottardo** 2024-06-26 16:58 UTC
Labels: OS-android, needs-triage, fr
