### ISSUE TITLE
FR: Automatically forward particular domains through subnet relay

### ISSUE THREAD

**Issue by sailorfrag** [tailscale/tailscale#1748] opened 2021-04-20 19:41 UTC
**Is your feature request related to a problem? Please describe.**

A couple customers have recently requested a way to route connections to a 3rd party SaaS product via a subnet router. This is needed because the SaaS product is restricted to only allow incoming connections from a particular IP range (typically that of the office and/or a subnet router). That's not too hard if the SaaS product uses a small range of IPs that don't change but is difficult in the presence of location-aware DNS load balancers, CDNs, etc.

Configuring an exit node can achieve this goal but captures far more traffic than required.

**Describe the solution you'd like**

A nicely packaged feature that will automatically redirect traffic going to a particular domain through an exit node or subnet relay. Maybe it could look at the DNS responses within that domain and automatically add them as /32 routes (caution: with CDNs this could grab unrelated traffic), or maybe the request could be modified to return a special IP address that the relay can DNAT (caution: complex).

This could be a magical experience if done well.

**Describe alternatives you've considered**

It's possible to get this result through a combination of
1. Configure a proxy server on the subnet router (or something reachable via the subnet router) that will redirect requests to the SaaS product by DNS name.
2. Use split DNS to generate DNS responses that send all traffic for the SaaS product's domain to the proxy server. Or, I suppose, a PAC file could accomplish that too.

But it's clunky

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_31sgh)

**Comment by Silvian** [comment] 2021-04-21 07:01
This is exactly what we all need!!!

**Comment by bradfitz** [comment] 2021-04-21 14:47
A number of customers have asked for this in the past and what we've told them as a workaround is to run their own DNS server with records for the service they want to proxy, pointing to a self-hosted rinetd or https://github.com/inetaf/tcpproxy proxying to the origin. It's involved, but works. Making that all automatic would be awesome.

I thought we had some related bugs in this space, but maybe not. #1543 is about adding custom DNS records but that's all I found.

**Comment by sailorfrag** [comment] 2021-04-23 13:08
I'm thinking about this some more and one of the cleaner ways to implement this might actually be to implement a "Magic HTTP(S) proxy" that would remove the need for DNS to be involved. Maybe we auto generate a proxy config for the browser to evaluate, maybe we just proxy all HTTP(S), not sure. But it sure makes it easy to control which subnet relay or exit node handles the traffic based on hostname.

**Comment by jack1902** [comment] 2021-04-26 10:21
@sailorfrag that sounds great (i'm currently needing this more and more so i'm just building a hacky solution as a "for now")

My main use cases are:
- Website traffic to Test environments of third parties (so HTTP/HTTPS traffic)
- SFTP traffic to third parties (They specifically mentioned to use their DNS name not the IP behind it, but in truth i'm happy for stuff to break if it changes for now as its fairly easy for me to swap out an IP thats hard coded)

**Comment by Nisden** [comment] 2021-05-19 13:02
Twingate has this feature, and we have previously been using it to access Azure SQL Databases from a Virtual Network.
My personal preference for implementation would be a "Magical IP", that gets routed to subnet relay.

**Comment by mayakacz** [comment] 2021-11-11 23:05
I'm exploring what we could do in this space, and have a few questions.

* Will you be requiring all devices/users to use exit nodes, or only certain devices/users on your network?
* Will you be requiring that certain specific devices use certain specific exit nodes? Why?
* Should users be able to pick an exit node of their choice?
* If all exit nodes are deleted or not available, what should happen to traffic?
* Do you need the ability to host non-Linux exit nodes?
* Do you need the ability for containers using userspace networking to use exit nodes?

Thanks!

**Comment by Nisden** [comment] 2021-11-12 07:54
I can answer this from our point of view.
  * Yes, we would limit this to certain user groups
  * No, just one of the exit node's that advertises the domain
  * No
  * We would be okay with the traffic routing over the internet
  * No
  * Not for us.

As a side note, for this to be functional for us, this feature would have to support wildcard domains.
Ex: *.database.windows.net

**Comment by james-lawrence** [comment] 2021-11-30 03:30
@mayakacz a non-business user point of view:
- indifferent.
- no, same as @Nisden, but if i was a company I could see geolocation mattering just for performance reasons.
- indifferent.
- fall back to internet routing is fine.
- yes. exit node runs macosx.
- no.

**Comment by LMSSonos** [comment] 2022-02-09 09:12
@sailorfrag do you have any update on this feature? ;-)

**Comment by DentonGentry** [comment] 2022-02-09 13:26
I promise that when we have updates, we fill post them on the bug. We are not working simultaneously on every open feature request. This one is being discussed now internally, but delivery is not imminent.

**Comment by wknapik** [comment] 2022-06-09 10:38
We're using dnsmasq (`address=/domain1/.../domainN/sniproxy_ip`) + https://github.com/brave/sniproxy. It works, but it would be great to have this as a Tailscale feature.

**Comment by dapirian** [comment] 2022-08-16 20:35
This is exactly what we need too. We want to make our staging site available on our VPN without using an exit node. It uses cloudfront, so there's no way to use regular subnet routing unless I just route all the cloudfront edge servers, which would then route half the internet instead of just my staging site.

**Comment by anthonysexton** [comment] 2022-08-24 00:57
> * Will you be requiring all devices/users to use exit nodes, or only certain devices/users on your network?
> * Will you be requiring that certain specific devices use certain specific exit nodes? Why?
> * Should users be able to pick an exit node of their choice?
> * If all exit nodes are deleted or not available, what should happen to traffic?
> * Do you need the ability to host non-Linux exit nodes?
> * Do you need the ability for containers using userspace networking to use exit nodes?

For us, this would be:
1. All devices would be fine
2. We wouldn't have a requirement to use a specific exit node, but our preference would be the one closest to them for latency
3. Yep
4. Falling back to internet only is fine
5. No
6. Not for us

**Comment by aukaost** [comment] 2022-10-15 09:52
> Will you be requiring all devices/users to use exit nodes, or only certain devices/users on your network?
Will you be requiring that certain specific devices use certain specific exit nodes? Why?
Should users be able to pick an exit node of their choice?
If all exit nodes are deleted or not available, what should happen to traffic?
Do you need the ability to host non-Linux exit nodes?
Do you need the ability for containers using userspace networking to use exit nodes?

* group or ACL based routing would be swell
* No
* No
* fall back to internet routing
* no
* no

Same as @dapirian, Cloudfront is our limiting factor.

**Comment by bayeslearner** [comment] 2023-02-19 13:26
Since the issue is still open, can I assume that this is not implemented? Is there a summary of how or whether a plan to implement a solution is in place?  
I would like to see a named-based routing using a "magic IP" as well.  This "magic IP" or "IP"s would have a higher priority (being more specific) than the default gateways, thus there is no need to up the priority of the subnet relay network's default gateway (use exitnode). 

Thanks.

**Comment by DentonGentry** [comment] 2023-02-19 13:29
When we have updates, we will post them to the bug.

> I would like to see a named-based routing using a "magic IP" as well.
This means to make DNS return the Magic IP for a given domain, so that the packets will be sent to the subnet router advertising a /32 or similar more specific route?

**Comment by bayeslearner** [comment] 2023-02-19 13:40
I am new to this wonderful software.  I apologize in advance if it makes little sense.  This is how I would go about crafting a solution: 
1. on an exist node: 
add advertise  route by name;   --advertise-by-name=service.servicecompany.com
the exist node will generate: 
* a magic IP for this service;
* other nodes will be informed of this magic IP. 
* tailscale DNS will return the magic IP for the given domain

2. on other nodes:
*  should work because of 1?

**Comment by bayeslearner** [comment] 2023-02-19 13:51
right now, as a workaround, one can use establish an ssh socks proxy to any server on the same subnet as the exit node, including the exit node itself. 
1. ssh -N -p 22 -D 2080 aaa@aneighborof.aexitnode.ip  (or  use  split DNS )
2. And in the browser (chrome), one can use tools like SwitchyOmega to selectively proxy *.service.saas.com to the local 2080.

**Comment by DentonGentry** [comment] 2023-03-21 02:21
Something that works right now is a subnet router, if `*.somedomain.com` publishes a set of IP addresses they use.

One can have a subnet router advertise one of more /32 routes, and they don't have to be YOUR routes. If one wanted to always access Google DNS via a specific IP address belonging to one node on the tailnet, that node could advertise subnet routes: `tailscale up --advertise-routes=8.8.8.8/32,8.8.4.4/32`

**Comment by strich** [comment] 2023-03-21 03:28
> Something that works right now is a subnet router, if `*.somedomain.com` publishes a set of IP addresses they use.
> 
> One can have a subnet router advertise one of more /32 routes, and they don't have to be YOUR routes. If one wanted to always access Google DNS via a specific IP address belonging to one node on the tailnet, that node could advertise subnet routes: `tailscale up --advertise-routes=8.8.8.8/32,8.8.4.4/32`

Unfortunately the specific problem here is that I don't know the set of IP addresses ahead of time. It's annoying but the third party simply demands all subdomains go through a VPN and don't bother to maintain the various IPs they spin up and down there.

**Comment by strich** [comment] 2023-03-21 07:08
I've moved to TwinGate as it provides the features to support this. I would love to support TailScale at some point as it seems like the more powerful (and open source) product, but this is a feature our company requires right now unfortunately.

**Comment by DentonGentry** [comment] 2023-06-03 05:43
We have a DNS-based solution working in prototype form, which can direct specific domains to a node on the tailnet from which they will egress to the Internet. The public IP address of that node on the tailnet can be added to allowlists in Internet services.

As currently implemented, the proxy handles only HTTPS. Applications using other ports or protocols would not be proxied correctly, but we believe HTTPS represents most such traffic of interest today.

The intent is to package this as a feature in the admin panel. It can be used early if desired, but requires some manual setup. Please contact support@tailscale.com for details, but please be understanding that a response won't be forthcoming immediately. We're still in the early stages of exercising the functionality.

**Comment by strich** [comment] 2023-06-03 05:56
Thanks. But it is likely that in our case https is not guaranteed. Which makes the feature sadly not useful at this stage. Hopefully over time you can make the feature more wide reaching in protocols.

**Comment by hazcod** [comment] 2023-06-03 08:36
> We have a DNS-based solution working in prototype form, which can direct specific domains to a node on the tailnet from which they will egress to the Internet. The public IP address of that node on the tailnet can be added to allowlists in Internet services.
> 
> As currently implemented, the proxy handles only HTTPS. Applications using other ports or protocols would not be proxied correctly, but we believe HTTPS represents most such traffic of interest today.
> 
> The intent is to package this as a feature in the admin panel. It can be used early if desired, but requires some manual setup. Please contact [support@tailscale.com](mailto:support@tailscale.com) for details, but please be understanding that a response won't be forthcoming immediately. We're still in the early stages of exercising the functionality.

FWIW, we've been test driving the SNIproxy and it's working perfectly for our use cases.

**Comment by james-lawrence** [comment] 2023-06-03 11:43
I'm also in the non-https bucket ;)

**Comment by catzkorn** [comment] 2023-12-12 16:41
Closing this FR as it is now covered by our new App Connector feature!

[Blog post](https://tailscale.com/blog/saas/) & [Docs](https://tailscale.com/kb/1281/app-connectors/)!

**Closed by catzkorn** 2023-12-12 16:41 UTC
Labels: L2 Few, P2 Aggravating, T0 New feature, fr

**Comment by ChillarAnand** [comment] 2025-02-04 05:26
Right now, this is supported on Linux. But when are you planning to release it on Windows? Is there a separate ticket for it?
