### ISSUE TITLE
iOS 16 beta - won’t disconnect?

### ISSUE THREAD

**Issue by travisboss** [tailscale/tailscale#5419] opened 2022-08-23 19:06 UTC
### What is the issue?

I am aware I am using a beta os but when I disconnect Tailscale it does not actually disconnect if I go to setting general vpn I still see Tailscale is connected. I noticed this since when disconnected from a vpn and not home I use nextdns apple profile. This will not work when a vpn is being used.

If I force disconnect I get inside the app saying "Need Authentication"

My exit node is pfsense and a docker container of tailscale.

I do understand I am using a beta ios.

### Steps to reproduce

1. Add tailscale VPN
2. Wait for it to load
3. Turn on tailscale
4. Turn off tailscale through app
5. Go to settings > VPN
6. Shows tailscale is still connected

### OS

iOS

### OS version

16 beta 5

### Tailscale version

1.28.0

### Bug report

BUG-e1b1acbfd593ddaceb345065be1750cfd235f4c0a2575aefd695ea0cbf2e915e-20220823190513Z-f6b1e82a6b312393

**Comment by travisboss** [comment] 2022-08-24 19:48
https://www.reddit.com/r/Tailscale/comments/wvtepq/comment/ilmwldh/?context=3

Per this thread (that is me), this issue is present in an older version of iPad OS too.

**Comment by takov751** [comment] 2022-09-05 07:13
Same issue here. After recent  iOS beta release it worked once at first boot after upgrade , then I had to restart the phone and from there on its connects ui shows , but I lose connection.

**Comment by travisboss** [comment] 2022-09-07 02:51
Just checked and it is also the same behavior on iOS 15, is there a solution to this besides turning off in settings?

**Comment by DentonGentry** [comment] 2022-09-12 02:42
Duplicate of https://github.com/tailscale/tailscale/issues/1734

**Closed by DentonGentry** 2022-09-12 02:42 UTC
Labels: OS-ios, L2 Few, P1 Nuisance, T5 Usability, bug
