### ISSUE TITLE
tstest/integration: annoying pop-ups on macos, `codesign` to fix it

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2043] opened 2021-06-03 15:27 UTC
Running `go test ./...` is now a bit annoying on macOS, now that we have the integration tests that run stock tailscaled listening on all interfaces:

<img width="390" alt="Screen Shot 2021-06-03 at 8 24 23 AM" src="https://user-images.githubusercontent.com/2621/120670365-340d3380-c445-11eb-8745-da9ca55a5b4f.png">

Not sure best answer here.

The tests still pass, but with that pop-up.

We could:

* set some env var that makes tailscaled only listening on `127.0.0.1:0`, like other tests. But this isn't like reality.
* make integration tests opt-in
* try to run some macOS commands to permit it, or detect when it'll do those pop-ups and then be opt-in?

In any case, we want to make sure CI continues to run all tests like normal.

/cc @crawshaw @danderson @maisem

**Comment by DentonGentry** [comment] 2022-02-06 03:23
Still happens.

<img width="671" alt="Screen Shot 2022-02-05 at 7 23 11 PM" src="https://user-images.githubusercontent.com/1140756/152666605-fe00f826-bf15-4d60-a319-35adef057386.png">

**Comment by uhthomas** [comment] 2023-04-21 19:48
Not sure if it's helpful, but apparently macOS won't show this warning dialog if the application binary is signed. Something like the following could help? 

```sh
codesign -s - tailscaled
```

**Comment by DentonGentry** [comment] 2023-06-04 05:46
https://github.com/tailscale/tailscale/issues/7752 has some other options, going to close this in favor of that.

Duplicate of https://github.com/tailscale/tailscale/issues/7752

**Closed by DentonGentry** 2023-06-04 05:46 UTC
Labels: testing, OS-macos, needs-fix
