### ISSUE TITLE
Android Application Heavy Battery Drain

### ISSUE THREAD

**Issue by kycfree1** [tailscale/tailscale#7598] opened 2023-03-18 21:11 UTC
Leaving the Tailscale application operating as a primary "always on" VPN, connected to a personal exit node, seems to be heavily draining battery. After a 10 hour period of phone usage tailscale was accountable for 36% of my devices battery drain in that period.
This seems to be very heavy for a VPN application and is causing a dramatic drop to my typical charge to charge period and much higher than the wireguard application and other VPN applications that I have used.

**Comment by DentonGentry** [comment] 2023-04-02 00:53
Duplicate of https://github.com/tailscale/tailscale/issues/3363

**Closed by DentonGentry** 2023-04-02 00:53 UTC
Labels: needs-dedup
