### ISSUE TITLE
FR: AAAA DNS records for nodes

### ISSUE THREAD

**Issue by SurenNihalani** [tailscale/tailscale#6867] opened 2023-01-02 02:04 UTC
### What are you trying to do?

Trying to resolve db-govtron.tail6c4e9.ts.net to a ipv6 address

**Comment by DentonGentry** [comment] 2023-01-02 03:33
Duplicate of https://github.com/tailscale/tailscale/issues/1152

**Closed by DentonGentry** 2023-01-02 03:33 UTC
Labels: needs-triage, fr
