### ISSUE TITLE
v1.8.1 failed on Ubuntu 20.04

### ISSUE THREAD

**Issue by cg31** [tailscale/tailscale#1877] opened 2021-05-07 03:58 UTC
After updating to 1.8.1, I am seeing unexpected error on two Ubuntu 20.04.

$ uname -a
Linux ubuntu2 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ cat /var/log/syslog | grep tailscaled
```
[...]
May  7 11:36:03 ubuntu2 tailscaled[1340842]: [RATELIMIT] format("router: %s add failed: %v")
May  7 11:36:03 ubuntu2 tailscaled[1340842]: [unexpected] peerapi listen("100.90.23.75") error: listen tcp4 100.90.23.75:0: bind: cannot assign requested address
May  7 11:36:03 ubuntu2 tailscaled[1340842]: [unexpected] peerapi listen("fd7a:115c:a1e0:ab12:4843:cd96:625a:174b") error: listen tcp6 [fd7a:115c:a1e0:ab12:4843:cd96:625a:174b]:0: bind: cannot assign requested address
May  7 11:36:03 ubuntu2 tailscaled[1340842]: Switching ipn state Starting -> Running (WantRunning=true)
May  7 11:36:03 ubuntu2 tailscaled[1340842]: control: authRoutine: state:synchronized; goal=nil paused=false
May  7 11:36:03 ubuntu2 tailscaled[1340842]: control: mapRoutine: state:authenticated
May  7 11:37:47 ubuntu2 tailscaled[1340842]: logtail: dialed "log.tailscale.io:443" in 263ms
May  7 11:39:50 ubuntu2 tailscaled[1340842]: logtail: dialed "log.tailscale.io:443" in 258ms
```

**Comment by cg31** [comment] 2021-05-07 04:04
I just found v1.8.1 works on another two ubuntu 20.04 in different location.

The failed machines are all behind coperate firewall. Maybe relating to #1875

**Comment by danderson** [comment] 2021-05-07 04:09
Building an ubuntu 20.04 VM now to debug, thanks for the report.

**Comment by danderson** [comment] 2021-05-07 04:23
Confirmed this is the same as the other issue, continuing discussion there.

Duplicate of #1875

**Closed by danderson** 2021-05-07 04:23 UTC
Labels: needs-triage
