### ISSUE TITLE
FR: support SSH check mode for tagged destinations

### ISSUE THREAD

**Issue by rmb938** [tailscale/tailscale#5234] opened 2022-07-30 03:01 UTC
### What is the issue?

When SSHing between machines with the `check` action. If both machines have tags (even if it's the same tag) ssh is not allowed, if only the destination machine is tagged ssh works fine.

This seems like a bug in the SSH ACLs? Source tags shouldn't matter when the ssh source is set to `autogroup:members`?

### Steps to reproduce

1. Apply the following Access Control file
  ```
  // Example/default ACLs for unrestricted connections.
  {
	  "tagOwners": {
		  "tag:desktops":      ["autogroup:members"],
		  "tag:servers":       ["autogroup:members"],
	  },
  
	  // Access control lists.
	  "acls": [
		  // Match absolutely everything.
		  // Comment this section out if you want to define specific restrictions.
		  {"action": "accept", "users": ["*"], "ports": ["*:*"]},
	  ],
	  "ssh": [
		  // Allow members to ssh into servers, with auth checking
		  {
			  "action": "check",
			  "src":    ["autogroup:members"],
			  "dst":    ["tag:servers"],
			  "users":  ["autogroup:nonroot"],
		  },
	  ],
  }
  ```
1. Tag a machine with the `servers` tag
1. Tag a different machine with the `desktops` tag
1. Try to ssh from a `desktops` machine to a `servers` machine

### OS

Linux

### OS version

Fedora 35

### Tailscale version

1.28.0

### Bug report

BUG-b020b213256667e8ee009e8954f42818870f95f965347c15a3b26358bdfa3fd5-20220730031340Z-fbd59be08c745376

**Comment by DentonGentry** [comment] 2022-07-30 03:24
This was a choice to be able to launch the feature for initial use.

For a device owned by a User, the Check action is to have the User login via SSO.
What would you suggest that the Check action for a Tag be?

**Comment by rmb938** [comment] 2022-07-30 03:39
Well my assumption was tagging a machine wouldn't change ownership. I auth'd the machine and added the tag, doesn't seem intuitive that tagging changes ownership. 

By applying the tag to a machine I expected that the User based acls/checking would still apply but now also tag should apply.

**Comment by bradfitz** [comment] 2022-07-30 03:41
Yeah, once a node is tagged, it loses its human identity. That's reflected in the admin console web UI too: note that the email or email-ish address under a node name then gets replaced by its tag(s).

We don't support tagged human nodes, at least yet.

**Comment by rmb938** [comment] 2022-07-30 03:44
Ah gotcha. That makes more sense for why the behavior is like this then.

**Comment by DentonGentry** [comment] 2023-02-18 05:01
Duplicate of

**Closed by DentonGentry** 2023-02-18 05:01 UTC
Labels: L3 Some users, P2 Aggravating, T0 New feature, fr, ssh
