### ISSUE TITLE
FR: Trying to refer to nodes in nodeAttrs

### ISSUE THREAD

**Issue by adminy** [tailscale/tailscale#6472] opened 2022-11-23 22:11 UTC
### What are you trying to do?

```json
	"nodeAttrs": [
		{"target": ["tag:nodeName"], "attr": ["nextdns:hash"]},
        ]
```
So I'm having difficulties understanding how I can refer to a specific node.
I don't have multiple users, I have multiple machines, so here I'm trying to tell each machine to go to a different nextdns hash but I couldn't find anywhere in the docs on how I can refer to a single machine.

### How should we solve this?

Find a way to tag or refer to a machine in Talescale nodeAttrs config.

### What is the impact of not solving this?

Everything currently is going to the same global nextdns target, I'd prefer if each machine can go to its own nextdns hash.

### Anything else?

I currently found a way to do this via UI:

I create empty tags in `tagOwners` config. Then I go to each machine, press the gear button and click on Edit ACL tags then I pick the empty tag I created in config.

**Comment by bradfitz** [comment] 2022-11-23 22:24
Cc @maisem

**Comment by DentonGentry** [comment] 2023-02-18 18:35
Duplicate of https://github.com/tailscale/tailscale/issues/6038

**Closed by DentonGentry** 2023-02-18 18:35 UTC
Labels: L2 Few, P2 Aggravating, T0 New feature, fr
