### ISSUE TITLE
When exit node is in use, always forward DNS through the exit node's DNS resolver

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#2161] opened 2021-06-17 16:38 UTC
We've been talking about this for a while, but I don't see a bug for it.

When activating an exit node, we currently don't change the client device's DNS settings. If you're lucky, the client's DNS server is set to something like 8.8.8.8, which will be accessible over the exit node, and it'll be fine. But if you're using a LAN DNS server (192.168.0.1), or your ISP's DHCP-provided DNS server, it might not be accessible at all.

The new "allow LAN access" feature might make a LAN-based DNS server work, but at severe cost to privacy/security. People don't expect their DNS requests to originate from the LAN's DNS server when they have an exit node enabled.

The correct fix for this is to send Internet-facing DNS over the same resolver settings that the Exit Node itself would be using.

A separate reason to use the exit node's DNS is to ensure that DNS-based load balancing works as expected.

cc: @maisem @danderson

**Comment by ryankoski** [comment] 2021-06-19 21:24
#1713 ?

**Comment by DentonGentry** [comment] 2021-06-19 22:34
True, duplicate of https://github.com/tailscale/tailscale/issues/1713
(updated #1713 labels to match the ones here)

**Closed by DentonGentry** 2021-06-19 22:34 UTC
Labels: L4 Most users, P3 Can't get started, T6 Major usability
