### ISSUE TITLE
FR: Taildrop directory feature

### ISSUE THREAD

**Issue by AllySakura** [tailscale/tailscale#13345] opened 2024-09-02 21:25 UTC
### What are you trying to do?

I'm having a problem with Taildrop's default directories for recieving files and images.

### How should we solve this?

There should be a feature that allows the user to edit the default directory, if possible. Like, the default direction that the files are recieved for Windows is in the download folder. The feature should allow us to change where the files are recieved in the end, like its own dedicated folder _inside_ the download folder.

### What is the impact of not solving this?

It really negatively affect the way files are sent through the tailnet since some users prefer to keep their files organized but its more simple just drop and forget.

### Anything else?

Since the Taildrop feature is still in alpha, I'm sure in the future this feature will be available. I just believe that addressing this issue first while its in its early developments is a great idea!

**Comment by agottardo** [comment] 2024-09-05 00:42
Thanks for the feedback

Duplicate of https://github.com/tailscale/tailscale/issues/13101

**Closed by agottardo** 2024-09-05 00:42 UTC
Labels: needs-triage, fr
