### ISSUE TITLE
FR: Siri Shortcuts integration

### ISSUE THREAD

**Issue by dvcrn** [tailscale/tailscale#6106] opened 2022-10-28 03:06 UTC
### What are you trying to do?

- Connect Tailscale when iPhone is connected to power
- Disconnect tailscale when battery is low (it's a battery hog)
- The OS sometimes disconnects tailscale, so I want to automate reconnecting it if that happens before I run stuff that needs my tailnet

### How should we solve this?

Provide Siri Shortcut integration to: 

- Connect tailscale
- Disconnect tailscale
- Get current connection status

### What is the impact of not solving this?

- Tailscale randomly getting disconnected on iOS (reliability)
- Less control over when the network is up

**Comment by mihaip** [comment] 2022-10-31 20:25
Duplicate of #2504

**Closed by mihaip** 2022-10-31 20:25 UTC
Labels: OS-ios, L2 Few, P1 Nuisance, T0 New feature, fr
