### ISSUE TITLE
FR: Machine Connection Alerts

### ISSUE THREAD

**Issue by thawthorn** [tailscale/tailscale#4702] opened 2022-05-18 02:17 UTC
### What are you trying to do?

I would like to be able to set alerts for machine states. We have autonomous devices that we deploy to the field. I would like to enable per-machine alerts that send emails when:

- A machine comes online for the first time
- A machine goes offline for longer than a specific number of hours
- A machine comes back online after being offline for a specific number of hours

### How should we solve this?

Add an "Alerts" configuration option to the Machines page (for a specific machine) that allows the user to enable email alerts for certain events as described above. The email alert should provide the user what the event was (e.g., "The machine remote01 connected for the first time at 05/17/22 at 4:45pm"). The email may include a link to the machine so the user can quickly access the device's details page. 

### What is the impact of not solving this?

We must manually check the machine list page to see if a device has connected before we know it's available for use. If alerts were enabled, we can be proactive and take advantage of the machine sooner.

**Comment by DentonGentry** [comment] 2022-05-18 02:36
Duplicate of https://github.com/tailscale/tailscale/issues/312

**Closed by DentonGentry** 2022-05-18 02:36 UTC
Labels: needs-triage, fr
