### ISSUE TITLE
FR: DNS for 4via6 Subnet Routers

### ISSUE THREAD

**Issue by thewilli** [tailscale/tailscale#7956] opened 2023-04-24 14:12 UTC
## Original Scenario

I want to connect to target systems exposed by a Subnet Router, and resolve them by a custom DNS server. 

**Solution**
- Setup Split DNS and setup a custom DNS server for the target domain

## Advanced Scenario

I want to connect to multiple target systems with overlapping IPv4 ranges, each exposed by a 4via6 Subnet Router, and resolve them by individual custom DNS servers. 

**Solution**
None, as the custom DNS server will return the original IPv4 address, not the custom IPv6 address to be used with the 4via6 Subnet Router

An example scenario could be multiple customer environments, where each 4via6 SR holds a Site2Site VPN connection to a customer network.

### How should we solve this?

As the resulting IPv6 addresses can be addressed by the schema [Q.R.S.T.via-X](https://tailscale.com/kb/1201/4via6-subnets/?q=4via6#magicdns-name-for-the-ipv4-subnet-devices), you could add an optional "Site ID" parameter to the Split DNS dialog. All responses could be rewritten to match the 4via6 schema. 

![image](https://user-images.githubusercontent.com/1206639/234022116-6d573f6b-c4a7-4d86-a668-76d2cfa877dc.png)

### What is the impact of not solving this?

The benefits of Subnet Routers cannot be fully made use of in the 4via6 scenario. Custom workarounds would be required.

**Comment by DentonGentry** [comment] 2023-04-24 19:46
Possibly a duplicate of https://github.com/tailscale/tailscale/issues/5392

**Comment by DentonGentry** [comment] 2023-04-25 06:39
Closing as a duplicate of https://github.com/tailscale/tailscale/issues/5392

**Closed by DentonGentry** 2023-04-25 06:39 UTC
Labels: needs-triage, fr
