### ISSUE TITLE
MacOS Monterey 12.0.1 Tailscale 1.18.0 Login not working 

### ISSUE THREAD

**Issue by tobiasReichel** [tailscale/tailscale#3402] opened 2021-11-24 22:23 UTC
### What is the issue?

Installed App Via Appstore
Restarted Mac 
Login is not working like not even clickable

via cli 
MacBook-Pro ~ % /Applications/Tailscale.app/Contents/MacOS/Tailscale up 
2021/11/24 23:13:50 failed to connect to local Tailscale service; is Tailscale running?

### OS

macOS

### OS version

MacOS Monterey 12.0.1

### Tailscale version

Tailscale 1.18.0

### Bug report

BUG-ce330328263f52b949b38d61b83f171733aee79827c41ef1ee808d1872a60e33-20211124222049Z-b765c0c0bd7594c0

**Comment by jaerod95** [comment] 2021-12-01 18:22
I have the same issue running the same macOS Monterey 12.0.1 as well. Looks like the local daemon isn't running as I also received this when using Tailscale's CLI `Tailscale up`:
`2021/12/01 11:02:07 failed to connect to local Tailscale service; is Tailscale running?`

**Comment by DentonGentry** [comment] 2021-12-01 18:57
Did it just update to macOS Monterey? One change in macOS Monterey is that applications using a Network Extension, which is the software technology Tailscale uses to connect to the VPN, are much more likely to conflict with each other than in previous macOS versions.

Does this Mac use Avast, Bitdefender, Crowdstrike, AdGuard, or have Apple's Private Internet Access enabled? They are likely conflicting. https://github.com/tailscale/tailscale/issues/3192 describes a number of these conflicts, and how people have resolved them. Turning off HTTPS scanning for the Tailscale app is a common refrain.

A way to check for this is via systemextensionsctl list, where we'd expect to see the Tailscale IPN extension:

```
% systemextensionsctl list
--- com.apple.system_extension.network_extension
enabled active teamID bundleID (version) name [state]
* * W5364U7YZB io.tailscale.ipn.macsys.network-extension (1.19.19/101.19.19) IPNExtension [activated enabled]
```

If you only see Avast or Bitdefender or similar, that is likely the issue.

**Comment by DentonGentry** [comment] 2021-12-01 19:36
On other possibility if the issue is just intractable and an alternative is needed: the CLI version of the Tailscale daemon can be compiled and run on macOS: https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS

There is no GUI and some features don't work, but it would provide connectivity.

**Comment by eugene1g** [comment] 2021-12-03 19:12
> On other possibility if the issue is just intractable and an alternative is needed: the CLI version of the Tailscale daemon can be compiled and run on macOS: https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS

@DentonGentry I had the same issue as OP, and can confirm that using the CLI version of Tailscale fixed it.

In my case, I have AdBlock running and since upgrading to Monterey it started blocking/breaking/conflicting with Tailscale. If I disable AdBlock, Tailscale app works as before. As soon as I re-enable AdBlock, the Tailscale UI client becomes unable to login or connect to the network. I tried tweaking different AdBlock setting with no success, so uninstall the Tailscale app from App Store and started the CLI version - that works.

Do you have any rough idea/roadmap for when the App Store version might be updated to work in the same way as the CLI version? The CLI version work OK, but it's nice to have my Tailscale client auto-updated, get the UI benefits etc.

**Comment by khoi** [comment] 2021-12-05 07:33
I have Adguard installed (it uses a dummy VPN). Tailscale and Adguard refuses to work together, only 1 can be enabled at once.

**Comment by DentonGentry** [comment] 2021-12-18 06:43
Duplicate of https://github.com/tailscale/tailscale/issues/3192

**Closed by DentonGentry** 2021-12-18 06:43 UTC
Labels: OS-macos, L3 Some users, P3 Can't get started, T6 Major usability, bug
