### ISSUE TITLE
SSH and SCP commands to tailscale ssh endpoints do not return correct error / success codes

### ISSUE THREAD

**Issue by SebastianZaha** [tailscale/tailscale#6054] opened 2022-10-25 09:05 UTC
### What is the issue?

Issue found while testing the [mutagen](https://github.com/mutagen-io/mutagen) file synchronization tool with a server where I use `tailscale --ssh`.

That program attempts to run a remote agent via a ssh command `ssh user@tailscalehost agent` and handles the 127 POSIX error code for when the command does not exist. tailscale ssh just returns an exit code of 1, although I think it writes the correct exit code in stderr. (see below).

Aside from that, a normal (and **successful**) scp command to a tailscale --ssh host also returns EOF with exit code 1 on my machine.

Local ssh version on arch linux: `core/openssh 9.1p1-1 [installed]`.

### Steps to reproduce

```
sebi@archdesktop ~/devel/mutagen $ ssh deckbox@a1 boguscommand
/bin/bash: boguscommand: command not found
exit status 127
sebi@archdesktop ~/devel/mutagen $ echo $?
1
sebi@archdesktop ~/devel/mutagen $ ssh deckbox@a1.bifolia.net boguscommand
bash: boguscommand: command not found
sebi@archdesktop ~/devel/mutagen $ echo $?
127
```

```
sebi@archdesktop ~/devel/mutagen $ scp README.md deckbox@a1.bifolia.net:
README.md                                                                     100% 5058   189.3KB/s   00:00    
sebi@archdesktop ~/devel/mutagen $ echo $?
0
sebi@archdesktop ~/devel/mutagen $ scp README.md deckbox@a1:
README.md                                                                     100% 5058   158.6KB/s   00:00    
EOF
sebi@archdesktop ~/devel/mutagen $ echo $?
1
```

### OS

Linux

### OS version

Ubuntu 18.04

### Tailscale version

1.32.1

### Bug report

BUG-b56db22c2e3ba12f87fd30ea839658e217bf7311f497485a617add42aac24bdb-20221025090330Z-0104a27f39e6c969

**Comment by DentonGentry** [comment] 2022-11-02 02:48
I cannot reproduce the scp part of the issue:
```
% scp ./README.md ubuntu:
README.md                                                                             100% 8834     1.2MB/s   00:00
% echo $?
0
```

**Comment by jfbus** [comment] 2022-11-28 12:36
I have the same issue with scp

```
% scp /tmp/foo rousseau-1:.
foo                                                                                                                                            100% 8576KB 531.9KB/s   00:16
EOF
% echo $?
1
```

Server:
```
$ cat /etc/issue
Raspbian GNU/Linux 11
$ arch
armv6l
$ tailscale version
1.32.3
  tailscale commit: a07555f434843c2d049bfb04b0b17b61dd362824
  other commit: 093d1e978538b249ab628c721e2f49d97b2cd16d
  go version: go1.19.2-ts3fd24dee31
```
Client:
```
MacOS 1.32.2
```

**Comment by bradfitz** [comment] 2022-11-28 13:19
This is likely an sftp issue. The scp command switched to using sftp in a recent ssh release.

**Comment by bradfitz** [comment] 2022-12-23 17:58
Ignoring sftp, we definitely have an issue with exit statuses:

```
$ echo "exit 5" | ssh 10.0.0.52 bash ; echo $?      
5
$ echo "exit 5" | ssh tailscale-ssh-server bash ; echo $?    
exit status 5
1
```

scp/sftp complicates the debugging because OpenSSH is in the middle of transitioning to using the sftp protocol for scp instead of the scp binary in server mode on the remote side. So let's fix the exit status thing first and see where we're at.

**Comment by Soypete** [comment] 2022-12-23 19:18
```
echo "exit 5" | ssh tailscale-ssh-server bash ; echo $? 
```
calls this [line](https://github.com/tailscale/tailscale/blob/main/ssh/tailssh/tailssh.go#L1117) before it fails. I am trying to create a test that will reproduce this so we can mitigate the problem in the future

**Comment by nshalman** [comment] 2022-12-23 20:08
be-child is swallowing the error:

```
root@host:~# cat failure
#!/bin/bash
exit 7
root@vhost:~# tailscaled be-child ssh --uid=0 --gid=0 --groups=0 --cmd=/root/failure ; echo $?
exit status 7
1
```

**Comment by bradfitz** [comment] 2022-12-23 20:17
ah! Nice.

**Comment by bradfitz** [comment] 2022-12-23 20:19
So this seems to do it:

```patch
diff --git a/ssh/tailssh/incubator.go b/ssh/tailssh/incubator.go
index 5c975046..42568192 100644
--- a/ssh/tailssh/incubator.go
+++ b/ssh/tailssh/incubator.go
@@ -283,7 +283,12 @@ func beIncubator(args []string) error {
                        Foreground: true,
                }
        }
-       return cmd.Run()
+       err = cmd.Run()
+       if ee, ok := err.(*exec.ExitError); ok {
+               code := ee.ProcessState.ExitCode()
+               os.Exit(code)
+       }
+       return err
 }
 
 // launchProcess launches an incubator process for the provided session.
```

**Comment by bradfitz** [comment] 2022-12-23 20:21
.... but then I still think we might have a problem relaying the signal (if any) that caused the process to die. That is, all this sort of stuff (from Go's syscall_linux.go):

```go
const (
	mask    = 0x7F
	core    = 0x80
	exited  = 0x00
	stopped = 0x7F
	shift   = 8
)

func (w WaitStatus) Exited() bool { return w&mask == exited }

func (w WaitStatus) Signaled() bool { return w&mask != stopped && w&mask != exited }

func (w WaitStatus) Stopped() bool { return w&0xFF == stopped }

func (w WaitStatus) Continued() bool { return w == 0xFFFF }

func (w WaitStatus) CoreDump() bool { return w.Signaled() && w&core != 0 }

func (w WaitStatus) ExitStatus() int {
	if !w.Exited() {
		return -1
	}
	return int(w>>shift) & 0xFF
}

func (w WaitStatus) Signal() Signal {
	if !w.Signaled() {
		return -1
	}
	return Signal(w & mask)
}

func (w WaitStatus) StopSignal() Signal {
	if !w.Stopped() {
		return -1
	}
	return Signal(w>>shift) & 0xFF
}

func (w WaitStatus) TrapCause() int {
	if w.StopSignal() != SIGTRAP {
		return -1
	}
	return int(w>>shift) >> 8
}
```

**Comment by nshalman** [comment] 2022-12-23 20:31
@bradfitz I still don't understand where the `exit status` string is coming from.

**Comment by bradfitz** [comment] 2022-12-23 20:37
@nshalman, that's the stringification of the error value (the exec.ExitError) when it returns to the childproc package.

**Comment by bradfitz** [comment] 2022-12-23 20:38
... it gets written here ultimately:

```
	if len(os.Args) > 1 {
		sub := os.Args[1]
		if fp, ok := subCommands[sub]; ok {
			if *fp == nil {
				log.SetFlags(0)
				log.Fatalf("%s not available on %v", sub, runtime.GOOS)
			}
			if err := (*fp)(os.Args[2:]); err != nil {
				log.SetFlags(0)
				log.Fatal(err)
			}
			return
		}
	}
```

**Comment by bradfitz** [comment] 2022-12-24 18:50
Okay, the latest unstable build (1.35.99) contains this fix. Can people here verify? (works for me, at least)

Once we've confirmed that scp is also happy for people then we can close this.

**Comment by DentonGentry** [comment] 2023-01-27 04:32
Tailscale 1.36.0 shipped with this fix. Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment] 2023-02-18 18:45
Closing as fixed.

**Closed by DentonGentry** 2023-02-18 18:45 UTC
Labels: L3 Some users, P2 Aggravating, T5 Usability, bug, ssh
