### ISSUE TITLE
FR: Make `--netfilter-mode=off` not use iptables binary at all

### ISSUE THREAD

**Issue by qiuxiangling** [tailscale/tailscale#7708] opened 2023-03-28 03:03 UTC
### What are you trying to do?

Not applicable for iptables as the default firewall

### How should we solve this?

After adding the --netfilter mode=off parameter, the runtime does not check whether iptables exist

### What is the impact of not solving this?

After adding the parameter "--netfilter mode=off", iptables must exist, otherwise it cannot be started

### Anything else?

system： debian 11

**Comment by DentonGentry** [comment] 2023-03-28 03:30
Can I ask why you are turning netfilter off?

**Comment by qiuxiangling** [comment] 2023-03-28 05:44
> Can I ask why you are turning netfilter off?

I have been using nftables all the time and want to completely remove iptables from the system

Tailscale does not generate a default firewall by adding the parameter --netfilter mode=off
To support other firewalls or create them manually

After adding -- netfilter mode=off
After all, I no longer need tailscale to automatically create a firewall
there is no need to check iptables during startup. I think it is a reasonable requirement

**Comment by qiuxiangling** [comment] 2023-03-28 05:46
> Can I ask why you are turning netfilter off?

I have been using nftables all the time and want to completely remove iptables from the system

Tailscale does not generate a default firewall by adding the parameter --netfilter mode=off
To support other firewalls or create them manually

After adding -- netfilter mode=off
After all, I no longer need tailscale to automatically create a firewall
there is no need to check iptables during startup. I think it is a reasonable requirement

**Comment by DentonGentry** [comment] 2023-03-29 03:07
iptables is not only used to set up a firewall, it is used to maintain routes and policy rules.

I suspect this feature request is effectively a duplicate of https://github.com/tailscale/tailscale/issues/391, a desire to not need to have an `iptables` binary at all.

**Comment by csrutil** [comment] 2023-03-29 04:24
> there is no need to check iptables during startup. I think it is a reasonable requirement

Yes, indeed. we set the parameter `--netfilter mode=off`, it still checks the iptables binary is existing or not, it does not make any sense to me.

**Comment by qiuxiangling** [comment] 2023-03-29 08:32
> iptables is not only used to set up a firewall, it is used to maintain routes and policy rules.
> 
> I suspect this feature request is effectively a duplicate of #391, a desire to not need to have an binary at all. Barring further comment, we'll expect to close this as a duplicate during the next regular bug scrub.`iptables`

Okay, if policy rules and routes depend on iptables binaries, it is reasonable to still check iptables binaries after adding --netfilter mode=off

Sorry, --netfilter mode=off, I understand that it is completely disabled and does not use netfilter

Thank you for your precise explanation

**Comment by DentonGentry** [comment] 2023-04-22 08:42
Duplicate of https://github.com/tailscale/tailscale/issues/391

**Closed by DentonGentry** 2023-04-22 08:42 UTC
Labels: L1 Very few, P2 Aggravating, T0 New feature, fr
