### ISSUE TITLE
Admin panel services list uses http to connect to https services

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1947] opened 2021-05-18 17:16 UTC
When opening a machine view, and look at the listed services, the link for a service running on port 443 incorrectly uses the “http” prefix instead of “https”.

![image](https://user-images.githubusercontent.com/75628398/118695938-bc4fcf80-b7db-11eb-8154-6f0416b3ea14.png)

**Comment by DentonGentry** [comment] 2021-10-13 22:48
Duplicate of https://github.com/tailscale/tailscale/issues/3048
(which was filed later but contains more detail and discussion)

**Closed by DentonGentry** 2021-10-13 22:48 UTC
Labels: admin UI
