### ISSUE TITLE
Exit node - devices can access tailscale network but not internet

### ISSUE THREAD

**Issue by necropolina** [tailscale/tailscale#4345] opened 2022-04-03 17:03 UTC
### What is the issue?

BUG-68efde5962d4539b0a717d99d21faa17392d7ab77697e0c780e100ec85c9bbe8-20220403164247Z-0324c9e640a814b3

I've got a raspberry pi set up as an exit node as well as a pihole. The pi's Tailscale IP is set as the DNS in the Tailscale admin panel, and the pihole stuff is all working fine (android mobile traffic is going through pihole when using tailscale).

When setting the pihole as an exit node for my android device (seems my macbook as well, when using mobile hotspot or my home wifi that the pi is on), I'm still able to access any devices in the Tailscale network, but unable to access the internet.

I've enabled IP forwarding for the pi, am using the `autogroup:internet:443,22` recommended in some threads, and have tried removing all access controls.

### OS

Linux, macOS, Android

### Tailscale version

1.22.2 (pi), 1.23.148 (android)

### Bug report

BUG-68efde5962d4539b0a717d99d21faa17392d7ab77697e0c780e100ec85c9bbe8-20220403164247Z-0324c9e640a814b3

**Comment by necropolina** [comment] 2022-04-03 17:12
Well, I've been trying to get this working all day... just reauthed in the android app and now it's working. No idea what caused or fixed the issue, tho.

**Comment by necropolina** [comment] 2022-04-03 19:56
Welp, I restarted my phone and it's not working again. Was fun while it laster.

**Comment by engineeringsys** [comment] 2022-04-06 14:09
@necropolina I've had the same problem on multiple hosts.  I setup an exit as I've done forever.  Setup a device to use it as an exit node, I cannot route traffic through it.  I re-auth and/or reset and it starts working for a while.  

I've done the same with a mobile phone (android) exit node will work for a while then I have to re-auth.

**Comment by engineeringsys** [comment] 2022-04-07 18:38
Any movement on this by chance? I'm on Debian 11 (Exit and Client) and now when I try building from scratch both machines and following the guide which I've done several times with success as soon as I route traffic through an exit all networking halts.

Nothing has changed in my environments.

**Comment by DentonGentry** [comment] 2022-04-17 16:53
The most commonly encountered issues with exit nodes can be resolved by:

On the exit node:
- firewall-cmd --permanent --add-masquerade
- sysctl -w net.ipv4.conf.eth0.rp_filter=2     (replace "eth0" with the name of the LAN interface)

In the ACLs:
- if you've set up ACLs, make sure to allow access to `autogroup:internet`
- try allowing all ports `*`, not just 443,22. Depending on how your DNS is configured port 53 and 853 may be needed, or other ports.

**Comment by GlidLov** [comment] 2022-05-11 09:38
hi all, i'm having the same issues on an android device. No Rpi device in the middle, just the android device which uses a 4G dongle or eventually an ethernet router

BUG-b70b9f72ee5e08592cfa0d958b9bcebad9dbd99d3eb2c288d1d5038c589b160d-20220511093451Z-639a89764ae53643

**Comment by bigjimmy546** [comment] 2022-09-20 03:45
when I connect to an exit node on iOS, I can't access internet.

**Comment by bradfitz** [comment] 2022-09-20 03:50
This was almost certainly the exit node bug fixed in 1.30.1.

Please make sure your exit node is updated and if there are still problems, file a new issue with details.

**Comment by DentonGentry** [comment] 2023-02-13 00:57
Most likely this was https://github.com/tailscale/tailscale/issues/5425

Duplicate of https://github.com/tailscale/tailscale/issues/5425

**Closed by DentonGentry** 2023-02-13 00:57 UTC
Labels: L1 Very few, P2 Aggravating, T5 Usability, bug

**Comment by xz-dev** [comment] 2024-05-09 15:23
> The most commonly encountered issues with exit nodes can be resolved by:
> 
> On the exit node:
> 
>     * firewall-cmd --permanent --add-masquerade
> 
>     * sysctl -w net.ipv4.conf.eth0.rp_filter=2     (replace "eth0" with the name of the LAN interface)
> 
> 
> In the ACLs:
> 
>     * if you've set up ACLs, make sure to allow access to `autogroup:internet`
> 
>     * try allowing all ports `*`, not just 443,22. Depending on how your DNS is configured port 53 and 853 may be needed, or other ports.

Also see: https://tailscale.com/kb/1192/acl-samples#application-allowlisting-for-third-party-saas-application-ip-allowlisting
```json5
// all employees can use exit nodes
{ "action": "accept", "src": ["autogroup:member"], "dst": ["autogroup:internet:*"] },
```
