### ISSUE TITLE
IPv4 is preferred when using an exit node even when IPv6 is available and otherwise preferred

### ISSUE THREAD

**Issue by LucasMZReal** [tailscale/tailscale#8245] opened 2023-05-31 21:10 UTC
### What is the issue?

When using an exit node, IPv4 ends up being preferred by the OS/Applications instead of IPv6 in IPv6-enabled hosts.
This is not expected. I expected to see the same type of preference and priority than just browsing natively in that exit node.

### Steps to reproduce

1. Set up an exit node in a device with IPv6 support, and in a network that uses proper IPv6
2. Connect to the exit node in a device
3. See it preferring IPv4. (You can notice this behaviour searching "What is my ip" on Google, using IPvFoo, accessing icanhazip.com, and a bunch of other forms, interestingly, test-ipv6.com would usually report this issue, but most of the time it believes that IPv4 is not preferred.)

### Are there any recent changes that introduced the issue?

No.

### OS

Windows, Android

### OS version

Windows 11, Android 12

### Tailscale version

1.42.0

### Other software

I don't have anything that messes with this, only really Jellyfin, and Adguard Home, but I can rule those out.

### Bug report

BUG-6a87fd7994fede15a501cb063695c422cf2773d3c6384e8f3d012179f649b8b6-20230531211003Z-f5373331dade31e4

**Comment by DentonGentry** [comment] 2023-05-31 21:13
My suspicion would be that it is somehow MTU related. When using an exit node, the MTU will be 1280 bytes. When going directly to a site, the MTU would most likely be 1500 bytes.

https://github.com/tailscale/tailscale/issues/2633 is a similar issue with exit nodes and MTU.

**Comment by LucasMZReal** [comment] 2023-05-31 21:17
I believe that this issue is because Tailscale seems to use ULAs. And they are, actually, weirdly, less preferred than IPv4 commonly on most OSes.

I believe you can see the same effect IIRC, if you were to put an A and an AAAA record to Tailscale IPs in a domain, and then tried acessing that on the web, you would see it prefer IPv4; and I would guess that goes for both having that IP as yours, and also accessing something on ULA.

IPv6-only websites work, only the preference is weird.

**Comment by DentonGentry** [comment] 2023-05-31 21:50
Barring further comment, we'll expect to close this as a duplicate of https://github.com/tailscale/tailscale/issues/2633 during the next regular bug scrub.

We have plans for Peer MTU probing to allow the packet size to be larger than 1280 bytes. This would be especially beneficial on LANs which support jumbo frames, but it will allow a moderate increase in packet size even on otherwise normal Wi-Fi and Ethernet links. It should be able to reach the 1350 byte MTU which Q3 wants to see.

**Comment by DentonGentry** [comment] 2023-06-02 23:21
Root cause is believed to be handled in https://github.com/tailscale/tailscale/issues/2633

**Closed by DentonGentry** 2023-06-02 23:21 UTC
Labels: L2 Few, P1 Nuisance, T5 Usability, exit-node, bug
