### ISSUE TITLE
Mullvad support for Mexico region

### ISSUE THREAD

**Issue by edefford** [tailscale/tailscale#9791] opened 2023-10-13 15:24 UTC
Hi,

Mullvad exit nodes feature is currently not available for  Mexico region, it'd be great to be able to use the service from over here, hence  I'm submitting this request per the oficial Mullvad doc.

**Comment by DentonGentry** [comment] 2023-10-13 15:26
Duplicate of https://github.com/tailscale/tailscale/issues/9314

**Closed by DentonGentry** 2023-10-13 15:26 UTC
