### ISSUE TITLE
FR: support configuring conditional DNS forwarding rules via the API

### ISSUE THREAD

**Issue by RutledgePaulV** [tailscale/tailscale#4900] opened 2022-06-21 23:37 UTC
### What are you trying to do?

I'd like to be able to manage my conditional forwarding rules via the API (actually I use Terraform which uses the API) because I have some AWS VPC interface endpoints that I'd like to send traffic to over tailscale via my subnet routers.

Using conditional dns configs for AWS interface endpoints allows me to route AWS API traffic over my internal network which then allows me to use AWS Service Control Policies to block access to certain AWS APIs over the public internet (instead requiring access via my interface endpoints) which adds a layer of security to my environment.

### How should we solve this?

From a quick glance at what the UI does, it seems like the API would make sense as these two uris:

```
GET /api/v2/tailnet:tailnet/dns/routes
POST /api/v2/tailnet/:tailnet/dns/routes
``` 

Which would return/accept a map containing "domain suffixes" to "list of resolver IPs for that domain" 

```json
{"example.com" ["10.1.0.2"]}
```

### What is the impact of not solving this?

I use the UI to do this by hand.

**Comment by DentonGentry** [comment] 2022-08-28 04:12
Duplicate of https://github.com/tailscale/tailscale/issues/2661

**Closed by DentonGentry** 2022-08-28 04:12 UTC
Labels: L2 Few, P2 Aggravating, T0 New feature, api, fr
