### ISSUE TITLE
Magicsock function not running

### ISSUE THREAD

**Issue by cblinq** [tailscale/tailscale#13204] opened 2024-08-21 07:50 UTC
### What is the issue?

Ever since updating to 1.72 on my devices I noticed this error [
![IMG_7230](https://github.com/user-attachments/assets/22b3bef0-406a-44bf-ac8d-b0940e7974fb)
](url)

### Are there any recent changes that introduced the issue?

The 1.72 update

### OS

Linux, iOS, Other

### OS version

Arch Linux - 6.10.6-arch1-1, Ubuntu - 6.8.0-40-generic, iOS 18 Developer Beta 6, iPadOS 17.6.1, tvOS 17.6.0

### Tailscale version

1.72.0

### Bug report

BUG-97d6dff337a3030448c463355f1807f200e75f823fdf339cb3a05b9679ba2676-20240821075005Z-846068805659392d

**Comment by agottardo** [comment] 2024-08-21 16:58
Did you notice anything not working, besides the error message?

**Comment by cblinq** [comment] 2024-08-21 17:14
Nope, no issues. Everything is working as before the update.

**Comment by cblinq** [comment] 2024-08-21 20:39
Should have mentioned that I also use Mullvad addon.

**Comment by ev-w** [comment] 2024-08-23 13:20
Seeing this on my iPhone as well. App version 1.72.0, iOS 17.6.1

I haven't actually noticed any sort of connectivity issues thus far, thankfully.

**Comment by ssnkhan** [comment] 2024-08-25 15:22
Seeing the same on iOS 17.6.1.

**Comment by nikitavoloboev** [comment] 2024-08-26 14:42
See the same. Perhaps something has to be updated in tailscale linux program? I run latest version now.

**Comment by bradfitz** [comment] 2024-08-26 16:11
This is bad and shouldn't ever happen.

If it gets into this state, direction connections won't work and you'll always go through DERP relays.

We need to figure out what is causing this.

I added more logging in 2dd71e64ac11675e22e17fd4c2b2afd1d99009e6 for #10976 (which is this bug is probably a duplicate of)

/cc @agottardo @raggi @jwhited

**Comment by ev-w** [comment] 2024-08-26 16:38
> If it gets into this state, direct connections won't work and you'll always go through DERP relays.

I'm still seeing this message on my iPhone but tailscale status shows a direct connection, fyi

**Comment by agottardo** [comment] 2024-08-26 16:39
@ev-w @nikitavoloboev @ssnkhan can you please attach a bug report identifier?

**Comment by bradfitz** [comment] 2024-08-26 16:41
I see no "exiting with error" in the logs for `BUG-97d6dff337a3030448c463355f1807f200e75f823fdf339cb3a05b9679ba2676-20240821075005Z-846068805659392d` so looks like 2dd71e64ac11675e22e17fd4c2b2afd1d99009e6 (which was in 1.72.0) never triggered.

So maybe it's the health warning's detection that's wrong here and the func is actually running fine.

**Comment by ssnkhan** [comment] 2024-08-26 16:59
> I see no "exiting with error" in the logs for `BUG-97d6dff337a3030448c463355f1807f200e75f823fdf339cb3a05b9679ba2676-20240821075005Z-846068805659392d` so looks like [2dd71e6](https://github.com/tailscale/tailscale/commit/2dd71e64ac11675e22e17fd4c2b2afd1d99009e6) (which was in 1.72.0) never triggered.
> 
> So maybe it's the health warning's detection that's wrong here and the func is actually running fine.

BUG-e5ea68ef8ea1f19b2c320b6b5989dd4be955141ee87b82c276c06cd9f8655030-20240826165835Z-54d44f42a2d14722, thanks for your help!

**Comment by jwhited** [comment] 2024-08-26 17:03
> > I see no "exiting with error" in the logs for `BUG-97d6dff337a3030448c463355f1807f200e75f823fdf339cb3a05b9679ba2676-20240821075005Z-846068805659392d` so looks like [2dd71e6](https://github.com/tailscale/tailscale/commit/2dd71e64ac11675e22e17fd4c2b2afd1d99009e6) (which was in 1.72.0) never triggered.
> > So maybe it's the health warning's detection that's wrong here and the func is actually running fine.
> 
> `BUG-e5ea68ef8ea1f19b2c320b6b5989dd4be955141ee87b82c276c06cd9f8655030-20240826165835Z-54d44f42a2d14722`, thanks for your help!

Thanks. I see the same for this. No `Receive func %s exiting with error: %T, %v` log message found.

**Comment by raggi** [comment] 2024-08-27 15:30
i did notice

```
2024-08-27T15:03:19Z | starting forever-blocked frontend Peek for shared fate shutdown
2024-08-27T15:03:19Z | [unexpected] frontend Peek returned (1, <nil>); continuing
```

in the original report, I'm not sure what implications it would have yet

**Comment by madjetey** [comment] 2024-08-30 17:23
Getting same in iOS app version 1.72.2

Connections to other nodes (home assistant instances) don't last more than 30secs before restarting the VPN connection

```
BUG-2ca1903c33996251a9be82fda7e41b579577da49d76c835b144d40b28ef0e447-20240830171903Z-e5600bd0fb7ea541
```

**Comment by agottardo** [comment] 2024-08-30 19:29
> BUG-2ca1903c33996251a9be82fda7e41b579577da49d76c835b144d40b28ef0e447-20240830171903Z-e5600bd0fb7ea541

@madjetey I do see issues in your diagnostics reaching out to other nodes in the tailnet, but it also appears you're still running iOS 17.1, please update to the latest and report back.

**Comment by madjetey** [comment] 2024-08-31 13:02
Updated to iOS 17.6.1
Issue persists 

BUG-2ca1903c33996251a9be82fda7e41b579577da49d76c835b144d40b28ef0e447-20240831130106Z-4ce993a7cadb4bc1

**Comment by ssnkhan** [comment] 2024-09-01 08:47
Just as an update, I am no longer seeing this error (iOS 17.6.1, TailScale 1.72.2).

**Comment by cblinq** [comment] 2024-09-02 05:45
I just received it again with iOS 18 Public Beta 5:

BUG-97d6dff337a3030448c463355f1807f200e75f823fdf339cb3a05b9679ba2676-20240902054027Z-ce1d0596cd9b8d25


I also didn’t have internet connectivity, had to disable and enable Mullvad node.

**Comment by Smart1e** [comment] 2024-09-02 15:10
I am running the latest iOS 18 developer beta and am facing the same issue. Beta 8 I believe.

**Comment by dalto12593** [comment] 2024-09-03 05:52
Same issues here, can't use any connections after 30 seconds or so, internal or external. iOS 18 22a5326f Tailscale 1.72.2

**Closed** 2024-09-05 00:08 UTC
Labels: connectivity, needs-triage, bug

**Comment by offbyone** [comment] 2024-10-29 02:25
I'm not sure if it's going to be the precise same issue but on iOS 18.1 and tailscale 1.76.1 I was seeing this as well, alongside very degraded networking until I disconnected from my tailnet. Reconnecting didn't show the error. 

Bug report BUG-94195d4c4b808e66cb7d733a16b055409beba6e4997e9413ac9334db81cf0c3e-20241029022401Z-40dc70e9e060fb51

**Comment by offbyone** [comment] 2024-10-29 19:23
And again today: BUG-94195d4c4b808e66cb7d733a16b055409beba6e4997e9413ac9334db81cf0c3e-20241029192229Z-3ec497930dbd776a

**Comment by AIR4Nick** [comment] 2025-03-10 18:05
Same issue. MagicSock RecieveIPv4 error and also DERP error.
UDP connection continually drops, then reconnects after an irregular period of time.

CLIENT CONNECTIVITY STATUS when failing
UDP = No. 
UPnP = Yes. 
All other client connectivity status = No

iOS 17.5.1 ~18.3.1, TS 1.80.2. Same errors on iPad 9th Gen, iPad 10th Gen, iPad Pro.

**Comment by bradfitz** [comment] 2025-03-10 20:12
@AIR4Nick, we don't track bugs that are closed. This bug is closed.

We might happen to see replies, but it doesn't show up in any dashboards as a thing to fix.

Can you file a new bug? And include a bug report identifier from the app.

**Comment by AIR4Nick** [comment] 2025-03-10 21:46
> [@AIR4Nick](https://github.com/AIR4Nick), we don't track bugs that are closed. This bug is closed.
> 
> We might happen to see replies, but it doesn't show up in any dashboards as a thing to fix.
> 
> Can you file a new bug? And include a bug report identifier from the app.

Thanks Daniel. We did file a separate report via support but have gotten zero traction and this seem like the same bug.
