### ISSUE TITLE
Tailscale SSH closes immediately

### ISSUE THREAD

**Issue by AndroidKitKat** [tailscale/tailscale#6145] opened 2022-10-31 13:02 UTC
### What is the issue?

I'm having issues using Tailscale SSH from one of my existing nodes to another. I can use Tailscale SSH Console from the web browser just fine, but going onto one of my other machines and running `ssh me@magic-dns-name` makes SSH close immediately. I can also SSH in normally using my machine's LAN IP (192.168...)

Here's a log from me using `-vvv` with SSH to try and debug this: [sxsf4.txt](https://github.com/tailscale/tailscale/files/9901172/sxsf4.txt)

I've also looked through the tailscaled logs in `journalctl`: [7kea.txt](https://github.com/tailscale/tailscale/files/9901207/7kea.txt)

And here's a corresponding SSH session (it doesn't really provide much value but I figured): [ssh-session-1667221222176525931-4044534581.txt](https://github.com/tailscale/tailscale/files/9901231/ssh-session-1667221222176525931-4044534581.txt)

### Are there any recent changes that introduced the issue?

I did upgrade Tailscale via a `pacman -Syu` this morning.

Here's the excerpt from my `pacman.log` 

```
[2022-10-31T11:03:35+0000] [ALPM] upgraded tailscale (1.32.1-1 -> 1.32.2-1)
```
But I did roll back tailscale to 1.32.1-1 (where it was working) and that did not fix the issue.

I also changed my ACL to allow logging in to non-root users without requiring checks, and I've tried reverting that no joy.

### OS

Linux

### OS version

Linux alarm 5.19.0-asahi-5-1-ARCH #1 SMP PREEMPT_DYNAMIC Sat, 20 Aug 2022 09:23:11 +0000 aarch64 GNU/Linux

### Tailscale version

1.32.2 , commit version 54e8fa172b725b354598daaa7007d261fd932d10

### Bug report

BUG-57afac1f1e8308d662f5fc8b55e80e09d77eb6ddbbb2a2aeb5ade87ff8f59d59-20221031124327Z-577e91f716882390

**Comment by DentonGentry** [comment] 2023-02-18 19:35
Duplicate of https://github.com/tailscale/tailscale/issues/5224

**Closed by DentonGentry** 2023-02-18 19:35 UTC
Labels: OS-linux, L1 Very few, T5 Usability, bug, ssh
