### ISSUE TITLE
Tailscale fails to detect/use Sagemcom FAST3890V3 UPnP

### ISSUE THREAD

**Issue by Nisden** [tailscale/tailscale#3557] opened 2021-12-13 08:41 UTC
### What is the issue?

Tailscale is not detecting UPnP for the modem provided by my internet provider.

### Steps to reproduce

Get an Sagemcom FAST3890V3 and have UPnp enabled

**Troubleshooting information:**

_Tailscale reports no UPnP devices_
```
tailscaled debug --portmap
2021/12/13 09:35:34 gw=192.168.0.1; self=fd7a:115c:a1e0:ab12:4843:cd96:6251:1568
2021/12/13 09:35:34 Probe: {PCP:false PMP:false UPnP:false}
2021/12/13 09:35:34 no portmapping services available
```

_miniupnpc finds the UPnP device_
```
upnpc-shared.exe -s
upnpc : miniupnpc library test client, version 1.9.
 (c) 2005-2014 Thomas Bernard.
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.1:49153/69692b70/gatedesc0b.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.1:49153/upnp/control/WANIPConn1
Local LAN ip address : 192.168.0.23
Connection Type : IP_Routed
Status : Connected, uptime=5191862s, LastConnectionError : ERROR_NONE
  Time started : Thu Oct 14 08:21:07 2021
MaxBitRateDown : 0 bps   MaxBitRateUp 0 bps
ExternalIPAddress = 80.161.155.165
Bytes:   Sent: 4294967295       Recv: 4294967295
Packets: Sent: 388868309        Recv: 946803671
```

_miniupnpc can add mapping_
```
.\upnpc-shared.exe -a 192.168.0.23 8083 8083 tcp 1000
upnpc : miniupnpc library test client, version 1.9.
 (c) 2005-2014 Thomas Bernard.
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.1:49153/69692b70/gatedesc0b.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.1:49153/upnp/control/WANIPConn1
Local LAN ip address : 192.168.0.23
ExternalIPAddress = 80.161.155.XXX
InternalIP:Port = 192.168.0.23:8083
external 80.161.155.165:8083 TCP is redirected to internal 192.168.0.23:8083 (duration=1000)
```

### OS

Windows

### OS version

10.0.19043 Build 19043

### Tailscale version

1.18.0

### Bug report

BUG-d68dea0a5c811e06de0741923c33361f4f02f0eb407143d70a7b07c029b0c0f3-20211213083644Z-66a0c05abe6ae281

**Comment by DentonGentry** [comment] 2021-12-13 13:49
We're not likely to be able to acquire a Sagemcom FAST3890V3 with an ISP to use it.
Are you comfortable running Wireshark https://www.wireshark.org/ ?
Capturing traffic to UDP port 1900, while running `tailscale netcheck` to ensure tailscaled sends a UPnP discovery packet, would be most useful.

**Comment by Nisden** [comment] 2021-12-13 14:28
Sure, I'll get you a captured later.

**Comment by Nisden** [comment] 2021-12-13 18:52
Here is a capture of running `tailscale netcheck`
[Tailscale netcheck.zip](https://github.com/tailscale/tailscale/files/7706165/Tailscale.netcheck.zip)

The output of running `tailscale netcheck`
```
tailscale netcheck

Report:
        * UDP: true
        * IPv4: yes, 80.161.155.XXX:64716
        * IPv6: no
        * MappingVariesByDestIP: false
        * HairPinning: false
        * PortMapping:
        * Nearest DERP: Frankfurt
        * DERP latency:
                - fra: 34.7ms  (Frankfurt)
                - lhr: 39.6ms  (London)
                - nyc: 115ms   (New York City)
                - ord: 124.8ms (Chicago)
                - dfw: 136.9ms (Dallas)
                - blr: 165.3ms (Bangalore)
                - sea: 173.6ms (Seattle)
                - sfo: 173.6ms (San Francisco)
                - sao: 239.3ms (São Paulo)
                - tok: 262.5ms (Tokyo)
                - sin: 290.2ms (Singapore)
                - syd: 348.5ms (Sydney)
```

**Comment by bradfitz** [comment] 2021-12-13 21:51
Thanks, @Nisden!

Maybe also a capture of `miniupnpc` adding a mapping?

Are there _four_ UPnP service types, @danderson? 😨

**Comment by Nisden** [comment] 2021-12-14 08:03
Okay, new capture file that contains the actions miniupnc does (Think I got all the relevant packages selected)
[miniupnpc_on_FAST3890V3.zip](https://github.com/tailscale/tailscale/files/7709711/miniupnpc_on_FAST3890V3.zip)

**Comment by DentonGentry** [comment] 2022-06-11 21:28
The first issue is that when we send an SSDP Discovery packet for `ssdp:all`, the Sagemcom responds with only `urn:schemas-wifialliance-org:device:WFADevice:1` (possibly the first profile in its list).

miniupnpc sends a discovery packet for `urn:schemas-upnp-org:device:InternetGatewayDevice:1` specifically and gets an answer. I think we can make tailscaled send both, so avoid breaking any existing cases where `ssdp:all` is working and something else might not.

**Comment by DentonGentry** [comment] 2022-08-27 23:02
The portmapper update to send a discovery packet for urn:schemas-upnp-org:device:InternetGatewayDevice:1 specifically went into Tailscale 1.28.

**Comment by Nisden** [comment] 2022-08-29 06:03
I just tried testing this and its still not working correctly. 
Without my port forwarding rule I still end up relaying all my packages via a DERP

**Comment by Nisden** [comment] 2022-08-29 06:08
This is the SSDP transmission sent and received.

```SSDP
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: ssdp:all
MAN: "ssdp:discover"
MX: 2

HTTP/1.1 200 OK
Cache-Control: max-age=600
Date: Mon, 29 Aug 2022 06:02:14 GMT
Ext: 
Location: http://192.168.0.1:1990/1472fce4-26f3-4922-a9e9-d24af1c8143d/WFADevice.xml
Server: POSIX UPnP/1.0 UPnP Stack/7.14.170.1009
ST: urn:schemas-wifialliance-org:device:WFADevice:1
USN: uuid:6fe0a5a7-8899-c9d1-db6a-1f3fddf2c9fa::urn:schemas-wifialliance-org:device:WFADevice:1

HTTP/1.1 200 OK
Cache-Control: max-age=600
Date: Mon, 29 Aug 2022 06:02:14 GMT
Ext: 
Location: http://192.168.0.1:1990/1472fce4-26f3-4922-a9e9-d24af1c8143d/WFADevice.xml
Server: POSIX UPnP/1.0 UPnP Stack/7.14.170.1009
ST: uuid:6fe0a5a7-8899-c9d1-db6a-1f3fddf2c9fa
USN: uuid:6fe0a5a7-8899-c9d1-db6a-1f3fddf2c9fa

HTTP/1.1 200 OK
Cache-Control: max-age=600
Date: Mon, 29 Aug 2022 06:02:14 GMT
Ext: 
Location: http://192.168.0.1:1990/1472fce4-26f3-4922-a9e9-d24af1c8143d/WFADevice.xml
Server: POSIX UPnP/1.0 UPnP Stack/7.14.170.1009
ST: upnp:rootdevice
USN: uuid:6fe0a5a7-8899-c9d1-db6a-1f3fddf2c9fa::upnp:rootdevice

HTTP/1.1 200 OK
Cache-Control: max-age=600
Date: Mon, 29 Aug 2022 06:02:14 GMT
Ext: 
Location: http://192.168.0.1:1990/1472fce4-26f3-4922-a9e9-d24af1c8143d/WFADevice.xml
Server: POSIX UPnP/1.0 UPnP Stack/7.14.170.1009
ST: urn:schemas-wifialliance-org:service:WFAWLANConfig:1
USN: uuid:6fe0a5a7-8899-c9d1-db6a-1f3fddf2c9fa::urn:schemas-wifialliance-org:service:WFAWLANConfig:1
```

**Comment by simondubrulle** [comment] 2022-12-05 00:26
Hi @Nisden @DentonGentry, I also have a similar sagem router shipped by main Belgian ISP (Proximus) and I can tell you a lot of Belgian people own this one. 

I am also facing the exact same issue and I've done some extra debugging. I can confirm the commit from @DentonGentry is a big step forward but **I now know why the fix is not completely fixing** the issue. What happens is :

- New SSDP is properly sent and received by the gateway (confirmed with Wireshark)
- Gateway now sends the expected response (containing the ":InternetGatewayDevice:" string (confirmed with Wireshark)
- However the gateway is not sending it on expected UPnP (default) port (1900). Therefore the  response packet is not checked in the switch at [`net/portmapper.go` line 797](https://github.com/tailscale/tailscale/blob/main/net/portmapper/portmapper.go#L797). It should enter the first case (`c.upnpPort()`) but it does not because the port is different than 1900. Which means the packet is not seen at all and UPnP device is not detected.

The port used by the gateway seems random to me, at least it is changing run after run. When I am forcing the first case to match any port (which is obviously not a solution), then it is checking the packet, detecting the UPnP device and `tailscale netcheck` returns `* PortMapping: UPnP`.

I am not sure what would be a proper solution for that. I can only think of a quick and 'dirty' solution such as 'checking if port == 1900 OR ( ip == gw && mem.Contains(mem.B(buf[:n]), mem.S(":InternetGatewayDevice:") )'. Any idea?

@Nisden Maybe you can also confirm via Wireshark that the response is also not sent on default port 1900?

Best regards,
Simon

**Comment by DentonGentry** [comment] 2023-03-04 04:00
If you're able to install an unstable build, 1.37.214 and later contain what might be a fix to let UPnP work https://github.com/tailscale/tailscale/pull/7447.

https://pkgs.tailscale.com/unstable/

**Comment by DentonGentry** [comment] 2023-06-03 06:06
I'm going to assume that 1.38 resolved this. Please reopen if not.

**Closed by DentonGentry** 2023-06-03 06:06 UTC
Labels: connectivity, L2 Few, P2 Aggravating, T3 Performance/Debugging, bug
