### ISSUE TITLE
tags carry over after switching accounts

### ISSUE THREAD

**Issue by dave-andersen** [tailscale/tailscale#3035] opened 2021-10-09 23:53 UTC
### What is the issue?

(1) Have two tailscale accounts; login with account1
(2) Add tags to the local machine using the command line. --advertise-tags="tag:account1_tag"
(2) Tailscale menu -> Log in to a different account (account2)
[do the thing]
(3) Machine still tries to advertise the "tag:account1_tag" that is only valid in the account1 tailscale network, but not valid in the account2 tailscale account.

Note that this is not attempting to use two networks concurrently; it's trying to switch from a work profile to a personal profile.

### OS

macOS

### OS version

MacOS Big Sur 11.6

### Tailscale version

1.14.6

### Bug report

BUG-a3b6aa84d53d8309f1e3c20c596390ead9aec1cd6411c2c87a0f582a36142253-20211009235321Z-0f9c813612baffd4

**Comment by DentonGentry** [comment] 2022-02-06 05:51
I think this was a duplicate of https://github.com/tailscale/tailscale/issues/2485

However it was fixed during the tags-v2 effort. If I follow these steps:
```
1. tailscale up --advertise-tags=tag:example
2. tailscale logout
3. tailscale up
4. ```
On the second tailnet the node did not try to advertise tag:example

**Closed by DentonGentry** 2022-02-06 05:51 UTC
Labels: L1 Very few, P2 Aggravating, T5 Usability, bug
