### ISSUE TITLE
macOS Monterey Tailscale conflicts with Avast, Bitdefender, Adguard

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3192] opened 2021-10-26 16:38 UTC
Login is failing after upgrading macOS to Monterey.

The user is trying to click on the Tailscale tray icon after the upgrade, and nothing happens (no action is taking place).

Uninstall and reinstall it does not fix it but slightly changes the behaviour, but it still won’t log in.

![image](https://user-images.githubusercontent.com/75628398/138922673-3745da3b-0ec5-4afb-87ac-a566cf415c34.png)

Tailscale Version: 1.16.1

macOS: Monterey (12.0)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3pgi9)

**Comment by gilby101** [comment] 2021-11-02 04:17
My failure is when PIA (Private Internet Access) VPN is active.  I have, so far, failed to find a way past this. PIA does support split tunnelling but maybe it is not working correctly.

With just AdGuard active, I can connect with Tailscale.

**Comment by DentonGentry** [comment] 2021-11-03 12:56
For those finding this bug report later: it does look like something in macOS Monterey is less tolerant of having multiple Network Extensions present. You can use `systemextensionsctl list` to see what applications have installed extensions.

**Comment by jorge-lok** [comment] 2021-11-25 10:32
I had the same problem with Sophos Endpoint. `systemextensionsctl list` was showing:
- `com.sophos.endpoint.networkextension`
- `com.sophos.endpoint.scanextension`

I uninstalled them but I guess they could be stopped somehow. I followed this steps to uninstall them: https://community.sophos.com/intercept-x-endpoint/big-sur-eap/f/recommended-reads/124391/how-to-remove-system-extensions

**Comment by mhat** [comment] 2021-12-10 17:24
Similar issue with CarbonBlack's endpoint product -- though it seems like this is more of a macOS issue than an issue with any specific extension. With CB I first disabled endpoint monitoring but left the agent/extension in place. No love. Once I removed the extension, then Tailscale started working again.

With CarbonBlack
- ✅  Signin worked. 
- ✅ Tailscale was up.
- ✅ running ./Tailscale ping to other Tailscale devices worked fine
- ❌  Unable to send traffic (TCP, UDP) (nc, curl, etc)

With CarbonBlack Extension Removed 
- ✅  Everything works again!

**Comment by mhat** [comment] 2021-12-14 07:00
I don't think anyone expected otherwise but I can report that updating to macOS `12.1` does not improve the situation.

**Comment by EdEngle** [comment] 2021-12-15 18:08
> I had the same issue using AdGuard, the only way to make Tailscale work is to disable "Automatically filter application" in the Network tab of AdGuard.

Hey @betrisey, I was having issues with AdGaurd blocking some of my TailScale traffic.  I found if I added TailScale to the Filtered Applications, everything worked for me.

**Comment by betrisey** [comment] 2021-12-16 11:48
> > I had the same issue using AdGuard, the only way to make Tailscale work is to disable "Automatically filter application" in the Network tab of AdGuard.
> 
> Hey @betrisey, I was having issues with AdGaurd blocking some of my TailScale traffic.  I found if I added TailScale to the Filtered Applications, everything worked for me.   

Thanks a lot! @EdEngle

**Comment by vysecurity** [comment] 2022-01-20 07:28
> > > I had the same issue using AdGuard, the only way to make Tailscale work is to disable "Automatically filter application" in the Network tab of AdGuard.
> > 
> > 
> > Hey @betrisey, I was having issues with AdGaurd blocking some of my TailScale traffic.  I found if I added TailScale to the Filtered Applications, everything worked for me.
> 
> Thanks a lot! @EdEngle

How did you guys do this?

**Comment by mhat** [comment] 2022-01-24 20:23
On the CarbonBlack side it appears that the issue comically also affects ethernet interfaces. It's [being tracked here](https://community.carbonblack.com/t5/Knowledge-Base/Carbon-Black-Cloud-Network-is-Slow-or-Disconnects-after-Sensor/ta-p/109745). No much to report beyond "they are looking into it".

**Comment by EdEngle** [comment] 2022-01-24 21:42
> How did you guys do this?

@vysecurity I opened AdGuard's Preferences page.  
From there I selected the Network tab.  
There is an option for Automatically filter applications and on the right of that check box there is a button for Applications...  Click that button.  
It will bring up a dialog box where you can add Tailscale to the Filtered Applications.

**Comment by gilby101** [comment] 2022-01-24 22:04
> > I had the same issue using AdGuard, the only way to make Tailscale work is to disable "Automatically filter application" in the Network tab of AdGuard.
> 
> Hey @betrisey, I was having issues with AdGaurd blocking some of my TailScale traffic. I found if I added TailScale to the Filtered Applications, everything worked for me.

Seems counterintuitive to me - but hey it works!  Thanks.

**Comment by vysecurity** [comment] 2022-01-25 06:09
Keeps forcing me to use a DERP when I have Adguard on.

**Comment by mintplo** [comment] 2022-03-17 09:04
I also had this issue after bitdefender installed. disabling network module in setting for Bitdefender DCI off resolved it.

but, on Bigsur, it works. (Tailscale + Bitdefender).

what's the cause of this? 🤔

**Comment by Mehuge** [comment] 2022-05-13 13:30
Is the only option with Avast to disable Web Shield?

**Comment by mhat** [comment] 2022-05-23 21:16
Finally, as of `macOS 12.4`, CarbonBlack appears to no longer interfere with Tailscale. It's likely that other filtering extensions that were previously problematic will start working.

**Comment by DentonGentry** [comment] 2022-05-31 16:03
Can anyone else confirm whether macOS 12.4 improved compatibility between Network Extensions?

**Comment by MReschenberg** [comment] 2022-07-27 17:28
I'm having this issue (running 12.5 on a M1 Pro) and I don't have anything listed under `systemextensionsctl list` :( 
Any idea what other services might be causing this issue? 
Tailscale is one of the first apps I'm trying to set up on this machine, so my existing config is pretty minimal.

**Comment by bradfitz** [comment] 2022-07-27 17:30
@MReschenberg, what is "this issue"? This bug has gotten muddied. What issue in particular are you having? With what other software running?

**Comment by MReschenberg** [comment] 2022-07-27 17:39
Ah sorry, I'm getting the error `failed to connect to local Tailscale service; is Tailscale running?` when trying to `tailscale up` (or any other tailscale command). 
I'm not running anything else -- this machine has a fresh install of macOS, and I don't have any network-level ad blocking or firewalls. MacOS firewall is off. 
The only other stuff I've installed is fish, homebrew, and tailscale from `brew install`.

That said, I just uninstalled tailscale from homebrew and downloaded the mac app from the app store, which works flawlessly. So not sure what issue I was hitting there :(

**Comment by bradfitz** [comment] 2022-07-28 03:06
I think you were hitting a mix of Tailscale versions running (homebrew vs App Store)

**Comment by DentonGentry** [comment] 2023-02-12 20:13
At this point:
- macOS versions between 12.0 through 12.3 or 12.4 had relatively significant conflicts between network extensions. We do not expect to be able to resolve those conflicts, and ask that people upgrade macOS.
- current macOS versions have mostly fixed those issues, to the point that most people now finding and commenting on this bug are actually encountering very different issues.

I'm going to close this as resolved. If you note a problem, even if it resembles something you see in this issue, please open a new bug.

**Closed by DentonGentry** 2023-02-12 20:13 UTC
Labels: OS-macos, L1 Very few, P3 Can't get started, T5 Usability, vpn-interop
