### ISSUE TITLE
cmd/tailscale: status --peers=false prints out userid:XXX for self node

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#7056] opened 2023-01-24 20:59 UTC
Similar to #4311, `tailscale status --peers=false` suppresses gathering certain peers data, which includes not returning the UserProfile of your self node, causing this CLI command to stringify your own node's username oddly:

```
Z:\>tailscale status -peers=false
100.107.196.119 winmox               userid:c7fd  windows -

# Health check:
#     - This is an unstable (development) version of Tailscale; frequent updates and bugs are likely

Z:\>tailscale version
1.35.158
  track: unstable (dev); frequent updates and bugs are likely
  tailscale commit: b657187a69a34993999cc9fa48e4d28dd914c266
  other commit: 7f1e2fd64ddcbf8368a9c3da66b85e3046f98cf1
  go version: go1.19.4-tsdc0ce6324d
```

/cc @maisem @clairew

**Comment by DentonGentry** [comment] 2023-02-19 04:02
Related: https://github.com/tailscale/tailscale/issues/4603 is also related to `tailscale status --peers=false`

**Comment by DentonGentry** [comment] 2023-06-04 03:22
Duplicate of https://github.com/tailscale/tailscale/issues/4603

**Closed by DentonGentry** 2023-06-04 03:22 UTC
