### ISSUE TITLE
logging in to a different user should be atomic

### ISSUE THREAD

**Issue by dsnet** [tailscale/tailscale#5070] opened 2022-07-17 00:07 UTC
### What are you trying to do?

I accidentally added a family friend's device to my tailnet. I'm trying to remote log in as a separate tailnet created for that family member. However, clicking on "log in different account" causes the current auth session to be logged out before the new auth session could be established. Consequently, I lost all remote access to the device.

### How should we solve this?

We should make logging in to a different account an atomic operation. That is, you are logged in as the previous user until you successfully login as the new user.

### What is the impact of not solving this?

I lost all connectivity and the remote device is unreachable.

### Anything else?

This is on Windows 11, running v1.26.2.

**Comment by DentonGentry** [comment] 2022-07-19 04:13
Duplicate of https://github.com/tailscale/tailscale/issues/3849

**Closed by DentonGentry** 2022-07-19 04:13 UTC
Labels: L3 Some users, P2 Aggravating, T5 Usability

**Comment by fuzzy122672** [comment] 2026-08-22 00:34
@DentonGentry I don't actually think this is a duplicate? Alex marked #3849 as already resolved as of 1.90, but I just triggered this same issue in 1.102.2. It's evidently two separate issues. That or the bug got reintroduced, somehow.
