### ISSUE TITLE
When stopping Tailscale app vpn still connected 

### ISSUE THREAD

**Issue by hgareeballa** [tailscale/tailscale#8316] opened 2023-06-10 06:39 UTC
### What is the issue?

When stopping the app and checking the vpn status from iOS settings still shows connected !
Despite that the app is stopped 

### Steps to reproduce

Connect from iOS app
Disconnect or stop the app
Check vpn profile status from settings 

### Are there any recent changes that introduced the issue?

Non

### OS

iOS

### OS version

16.5

### Tailscale version

1.42.0

### Bug report

BUG-6c54bac7a1224d9f934fefcece92ca484b2cb05e736d4e1b98248793c8bf6762-20230610063121Z-f57e5234d585563c

**Comment by hgareeballa** [comment] 2023-06-10 06:40
![IMG_3188](https://github.com/tailscale/tailscale/assets/6079147/8711da50-3e71-4110-86a0-2adb8d026db7)
![IMG_3189](https://github.com/tailscale/tailscale/assets/6079147/18f06359-4298-4cc9-9ed4-4984d47507a6)

**Comment by DentonGentry** [comment] 2023-06-11 14:36
Duplicate of https://github.com/tailscale/tailscale/issues/1734

**Closed by DentonGentry** 2023-06-11 14:36 UTC
Labels: needs-triage, bug
