### ISSUE TITLE
iOS: ping does not work to specific device 

### ISSUE THREAD

**Issue by Bogidon** [tailscale/tailscale#5331] opened 2022-08-10 03:36 UTC
### What is the issue?

I have a single user tailnet with five devices and an internal DNS set up. It was all working great until recently my iPhone stopped establishing connections with other devices within the tailnet. I don't believe I made any modifications to the configuration leading to this breakage. The iOS app shows that the VPN status is "active". `tailscale ping` even works from a connected Linux device. However `tailscale ping --tsmp`, `tailscale ping --icmp`, and `ping` do not work from the Linux device to the iPhone nor does a ping work from the iPhone to the Linux device (run through the [Network Utilties](https://apps.apple.com/us/app/network-utilities-analyzer/id1246455042) app).

I have re-installed tailscale on my iPhone multiple times without luck. However tailscale does work on my iPad, which I recently added to my tailnet and is running the same version of iOS as my iPhone (15.4.1). Most of the time the iPhone appears with a connection status of "-" in `tailscale status`, sometimes it appears "active" with a nonzero `tx` but a zero `rx`. 

In addition to the tailscale bugreport below from the iPhone, here's a bugreport generated by the Linux device, in case that helps: 
```
BUG-43a6755c2b34122650ba8204926ee6c802292dc335a8c95393998b878be6875f-20220810033418Z-5193a0f95e7881eb
```

Please let me know what else other information I can provide. I know this is probably not a whole lot to go on, but the issue is mystifying. Thank you in advance for any help.

### Steps to reproduce

1. Activate tailscale vpn from iOS app
2. Attempt to ping iPhone from Linux device

### Are there any recent changes that introduced the issue?

Don't believe so.

### OS

iOS

### OS version

iOS 15.4.1

### Tailscale version

1.28.0

### Bug report

BUG-1f04a74cff78fe53f02ab011fa7de7ec2138c9471f2df4debc05d306bcbeb1ae-20220809212009Z-bb0803698f3dda63

**Comment by DentonGentry** [comment] 2022-08-10 05:18
On the Linux machine:
```
2022-08-09 22:58:50.59083153 -0400 -0400: ping(100.75.x.y): sending TSMP ping to [cON4Z] phone ...
2022-08-09 22:58:50.59123098 -0400 -0400: [cON4Z] - Sending handshake initiation
2022-08-09 22:58:50.988862337 -0400 -0400: magicsock: starting endpoint update (periodic)
2022-08-09 22:58:51.157393974 -0400 -0400: Accept: UDP{100.90.q.r:49457 > 100.101.s.t:53} 75 ok out
2022-08-09 22:58:51.157448738 -0400 -0400: Accept: UDP{100.90.q.r:43955 > 100.101.s.t:53} 75 ok out
2022-08-09 22:58:51.240970498 -0400 -0400: netcheck: report: udp=true v6=false mapvarydest=false hair=false portmap=U v4a=24.191.87.205:1081 derp=1 derpdist=1v4:17ms,8v4:93ms,10v4:86ms
2022-08-09 22:58:55.626642492 -0400 -0400: [cON4Z] - Handshake did not complete after 5 seconds, retrying (try 2)
2022-08-09 22:58:55.6267504 -0400 -0400: [cON4Z] - Sending handshake initiation
2022-08-09 22:58:58.206644901 -0400 -0400: ping(100.75.x.y): sending ICMP ping to [cON4Z] phone ...
```

On the phone, we see it reporting difficulty connecting to anything:
```
2022-08-09 21:15:53.410839 +0000 UTC: dns: dns query: context deadline exceeded
2022-08-09 21:15:53.410998 +0000 UTC: dns: dns query: context deadline exceeded
2022-08-09 21:15:53.411063 +0000 UTC: dns: dns query: context deadline exceeded
2022-08-09 21:15:53.411098 +0000 UTC: dns: dns query: context deadline exceeded
2022-08-09 21:15:53.411545 +0000 UTC: dns: dns query: context deadline exceeded
2022-08-09 21:15:53.411859 +0000 UTC: dns: dns query: context deadline exceeded
...
2022-08-09 21:15:58.612159 +0000 UTC: magicsock: [0x1302824b0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): dial tcp6 [2604:a880:800:10::873:4001]:443: connect: no route to host
2022-08-09 21:15:58.612192 +0000 UTC: derp-1: backoff: 649 msec
2022-08-09 21:15:59.263259 +0000 UTC: derphttp.Client.Recv: connecting to derp-1 (nyc)
2022-08-09 21:15:59.264113 +0000 UTC: magicsock: [0x1302824b0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): dial tcp6 [2604:a880:800:10::873:4001]:443: connect: no route to host
```

We also see a number of other VPN interfaces named "ipsec#"
```
2022-08-09 21:15:56.0824 +0000 UTC: LinkChange: major, rebinding. New state: interfaces.State{defaultRoute=pdp_ip0 ifs={ipsec10:[2607:fc20:2472:2db4:1c9e:b82b:872b:d57d/64] ipsec3:[fd74:6572:6d6e:7573:c:ba34:c150:8755/128 fd74:6572:6d6e:7573:d:ba34:c150:8755/128] ipsec5:[2607:fc20:2472:2db4…+517
2022-08-09 21:15:56.083833 +0000 UTC: Rebind; defIf="pdp_ip0", ips=[192.0.0.1/32 2607:fb90:24ad:60f6:4f:21e:8e02:7f98/64 2607:fb90:24ad:60f6:25e1:7b95:9dbb:80b8/64 fe80::13:2662:be01/64]
```

Is there another VPN active, like Apple Private Relay perhaps? The two VPNs might be fighting over the routing table.

**Comment by bduffy** [comment] 2022-08-22 01:41
I have the same problem. I’m pretty sure it started with the 1.28 release.

**Comment by shev-pro** [comment] 2022-10-02 18:50
Same problem here. Device doesn't reach neither tailscale internal ipaddresses nor routed once.

iPhone X with iOS 16.0
Tailscale 1.30.2

Tried also reauth with removing from admin panel and reinstall

**Comment by augs** [comment] 2022-11-23 22:30
Similar problem.  I have 2 iOS devices.  One works as expected, second only will route traffic to tailnet if I enable routing through an exit node and only that tailnode is reachable via 100.64.0.0 address. non-working device is ipad.  Have fully removed client multiple times, tried testflight vs production.  IIRC this device has been ~broken for about 6 months with this behavior.

If I inspect routing table using “he.net network tools app” the utunX interface on the working device shows an explicit /32 route for each device in my tenet.  On the broken device, I only see one for 100.100.100.100/32

BUG-fa551ac934ab374266c50840c5378276a285a6721e000046f06b9ff48fabf580-20221123222218Z-7b496df5ee128518

**Comment by DentonGentry** [comment] 2023-02-18 07:23
> If I inspect routing table using “he.net network tools app” the utunX interface on the working device shows an explicit /32 route for each device in my tenet. On the broken device, I only see one for 100.100.100.100/32

If the iOS app figures out that there is another user of CGNAT addresses on the device, like a CGNAT ISP, it will add specific /32 routes for each tailnet node. If the iOS app thinks it is the only user of CGNAT in the device, it will add 100.64.0.0/10.

The behavior sounds like the one device which doesn't work has mis-identified itself as being the only user of CGNAT, when in reality there is another.

**Comment by DentonGentry** [comment] 2023-02-18 07:34
> BUG-0c13207da2e65651b7652f82e4ab91672b5a4a8ad98a3a3b149f581f5351f89d-20221202155254Z-7a89c6cc418112af

That system was reporting:
`wgcfg: skipped node IPs: 100.68.87.xx from "ipad" ([FcRc1]), fd7a:115c:a1e0:ab12:4843:cd96:6244:xxxx from "ipad" ([FcRc1]), 100.124.67.xx from "REDACTED-macbook-air" ([rO94U]), fd7a:115c:a1e0:ab12:4843:cd96:627c:xxxx from "REDACTED-macbook-air" ([rO9…+890`

`using backend prefs for "ipn-go-bridge": Prefs{ra=false mesh=false dns=true want=true Persist{lm=, o=, n=[Czx/+] u="shevchenkser@gmail.com"}}`

which is the symptom of https://github.com/tailscale/tailscale/issues/6203

Duplicate of  https://github.com/tailscale/tailscale/issues/6203

**Closed by DentonGentry** 2023-02-18 07:34 UTC
Labels: OS-ios, L1 Very few, P2 Aggravating, T5 Usability, bug
