### ISSUE TITLE
FR: Add Ubuntu 24.10 support

### ISSUE THREAD

**Issue by RichardShortlandNeal** [tailscale/tailscale#13751] opened 2024-10-09 16:44 UTC
### What are you trying to do?

Install Tailscale client on Ubuntu 24.10

### How should we solve this?

Add Ubuntu 24.10 to supported OSes

### Anything else?

OS=ubuntu
VERSION=oracular
PACKAGETYPE=apt
UNAME=Linux XXXXXX-XXXXXX 6.11.0-8-generic #8-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep 16 13:41:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

PRETTY_NAME="Ubuntu 24.10"
NAME="Ubuntu"
VERSION_ID="24.10"
VERSION="24.10 (Oracular Oriole)"
VERSION_CODENAME=oracular
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=oracular
LOGO=ubuntu-logo

**Comment by Erisa** [comment] 2024-10-09 17:03
Duplicate of #12896

**Closed by Erisa** 2024-10-09 17:03 UTC
Labels: OS-linux, needs-triage, fr
