### ISSUE TITLE
iOs 16 bug - on/off switch doesn’t work. 

### ISSUE THREAD

**Issue by yuanboyong** [tailscale/tailscale#6004] opened 2022-10-20 23:45 UTC
Tailscale app doesn’t switch on/off regularly. When disconnecting. 
When the switch is clicked off, no more VPN sign on system status display (top right corner), but in settings - VPN, it still shows Tailscale connected. Testing connection verifies. 
Tried to switch it on, the switch goes to the right side, but status shows stopped. 
to make it work, I always have to: 1. Go to System Setting - VPN, manually disconnect tailscale, then kill (swipe up) tailscale app.
2. Relaunch the app, reauthorize (login), and connect. 
But the issue remains when I was to disconnect. 

Bug report
BUG-0911d25762222e5c675f85da92ff28d4ded968d0166c2f9ac74bb3cba01d0936-20221020233210Z-5972fbce0e46c8c4

I have a screen recording ready to upload if it helps.

**Comment by pilif** [comment] 2022-10-21 09:05
see https://github.com/tailscale/tailscale/issues/3363, https://github.com/tailscale/tailscale/issues/539

**Comment by DentonGentry** [comment] 2022-11-01 23:23
Duplicate of https://github.com/tailscale/tailscale/issues/539

**Closed by DentonGentry** 2022-11-01 23:23 UTC
Labels: OS-ios, L1 Very few, P1 Nuisance, T5 Usability
