### ISSUE TITLE
Add a "disconnect" command to the tailscale client

### ISSUE THREAD

**Issue by voigt** [tailscale/tailscale#466] opened 2020-06-16 09:26 UTC
**Is your feature request related to a problem? Please describe.**

I'm currently automatically adding Nodes to a Kubernetes Cluster which are connected via Tailscale. While joining the network via authkey works well, there is no similar approach for a node to leave the network.
The problem here is, that Kubernetes/Cluster-Autoscaler deprovisions nodes as part of a normal cluster lifecycle. This means those nodes are not part of Kubernetes anymore, but are still part of the Tailscale network (nodes are terminated, but they are listed in the admin panel).

At the moment this makes it necessary to identify nodes that are not existent anymore and manually remove them via admin panel.

The same issue occurs, when the tailscale client is running in a container and this container is killed at some point.

**Describe the solution you'd like**

In my opinion a Tailscale client should be enabled to deregister itself from the Tailscale network. This deregistration should lead to a removal of the entry in the admin panel.

This enables a user to create a hook on node termination, that is taking care for deregistration of the client.

This could be realised with a tailscale command similar to `tailscale up` - e.g. `tailscale down` or `tailscale rm`.

**Describe alternatives you've considered**

A restful API endpoint that could be triggered from "outside" as a cluster admin. Haven't thought that through.

**Additional context**

-

**Comment by multani** [comment] 2020-11-13 08:39
483141 added a `down` command.

**Comment by artis3n** [comment] 2021-02-03 02:37
> This deregistration should lead to a removal of the entry in the admin panel.

I assume this is the case because the issue is still open and the feature is not yet fully implemented, but the current `down` command does not remove nodes from the admin panel.

**Comment by DentonGentry** [comment] 2021-02-08 14:10
There is also an API in Beta, which might provide a way to automate removal.

**Comment by DentonGentry** [comment] 2021-04-19 21:45
Assigning to Naman because I expect the project he's working on to meet this need.

**Comment by DentonGentry** [comment] 2021-05-20 23:06
The project Naman implemented is Ephemeral Authkeys, which will auto-remove the node a short time after we stop hearing from it: https://tailscale.com/kb/1111/ephemeral-nodes/

The 1.8 release added a `tailscale logout` command which expires the nodekey.

I think that is everything called for in this issue, closing it now.

**Closed by DentonGentry** 2021-05-20 23:06 UTC
Labels: L4 Most users, P2 Aggravating, T5 Minor usability
