### ISSUE TITLE
tailscaled  creating router: exec: "iptables": executable file not found in $PATH

### ISSUE THREAD

**Issue by sheiy** [tailscale/tailscale#7934] opened 2023-04-20 09:18 UTC
### What is the issue?

```
root@OpenWrt:~# tailscaled 
logtail started
Program starting: v1.38.4-tc439a3a9c-g9275ff8bd, Go 1.20.3-tsddff070: []string{"tailscaled"}
LogID: 31ea5ca134b03c632d029bcda4670459095c015c10b3261ec1212c86c2366c3f
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
wgengine.NewUserspaceEngine(tun "tailscale0") error: creating router: exec: "iptables": executable file not found in $PATH
flushing log.
logger closing down
logtail: upload: log upload of 522 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/c0e6ca05ee4c6e5b01de7a2aa73a018ff07d60c91bcd28ce3382059583857b70": context canceled
getLocalBackend error: createEngine: creating router: exec: "iptables": executable file not found in $PATH
```
How to use nftables to run tailscaled?

### OS

Linux

### OS version

openwrt

### Tailscale version

1.38.4

**Comment by sheiy** [comment] 2023-04-20 09:33
or is there some way to start tailscaled with nftables?

**Comment by DentonGentry** [comment] 2023-04-22 08:42
Duplicate of https://github.com/tailscale/tailscale/issues/391

**Closed by DentonGentry** 2023-04-22 08:42 UTC
Labels: needs-triage, bug
