### ISSUE TITLE
Android 12: Tailscale app doesn't authenticate successfully with Brave default browser

### ISSUE THREAD

**Issue by kelivel** [tailscale/tailscale#5022] opened 2022-07-08 17:00 UTC
### What is the issue?

Reported in support ticket: # 3490

**Reported OS**: Android 12

User reported that when their phone's default browser is set to Brave, they can authenticate with their Github account but reach the sign-in page again afterwards, and can't see the devices on their tailnet. They _can_ see the Android device authenticated successfully in their tailnet admin console, however. 

Important note: When they click on the "Sign in with other" option their default browser opens instead of the embedded browser in the app. Changing their default browser to Chrome resolved the issue and they were able to log in inside of the embedded browser.

I was unable to reproduce on Android 9 with a fresh Brave installation.

### Steps to reproduce

According to the user: 

1. Set Brave as your default browser
2. Open Tailscale app and choose "Sign in with other"
3. Brave should open externally instead of the built-in browser
4. Sign in to Tailscale using Github
5. Go back to Tailscale app which shows the sign in screen again

### Are there any recent changes that introduced the issue?

Phone's default browser is Brave

### OS

Android

### OS version

12 - Build SP1A.210812.016.C2

### Tailscale version

1.26.1-t5b81baa7d-gd2fd1453038

**Comment by miskreant** [comment] 2022-07-08 19:16
Brave version: 1.40.111

https://user-images.githubusercontent.com/294747/178056341-c746803f-e41e-4445-afca-4a26ea3c42d0.mp4

**Comment by DentonGentry** [comment] 2022-10-31 05:57
Related: https://github.com/tailscale/tailscale/issues/4835

**Comment by DentonGentry** [comment] 2023-02-13 23:40
This is a duplicate of https://github.com/tailscale/tailscale/issues/4835 : GitHub login redirecting through the Android GitHub app breaks if the default browser is anything other than Chrome.

Dup of https://github.com/tailscale/tailscale/issues/4835

**Closed by DentonGentry** 2023-02-13 23:40 UTC
Labels: OS-android, L1 Very few, P2 Aggravating, T5 Usability, bug
