### ISSUE TITLE
FR: Add command line parameter to see what flags tailscale is already running with

### ISSUE THREAD

**Issue by digirave** [tailscale/tailscale#3857] opened 2022-02-01 15:17 UTC
### What are you trying to do?

Check what flags tailscale is already running with

### How should we solve this?

Add a parameters such as --showflags

and when
tailscale --showflags

is run show the what tailscale is running like
```
# tailscale --showflags
flags: --advertise-routes=10.0.0.0/24,10.0.1.0/24 --accept-routes
```
### What is the impact of not solving this?

There is no official way of seeing what flags tailscale is running

### Anything else?

Similar function but different output:
tailscale debug prefs

Workaround:
tailscale up + some random flag makes the error pop up showing the current running flags(output: Error: changing settings via 'tailscale up' requires mentioning all non-default flags...).

**Comment by mayakacz** [comment] 2022-02-03 18:01
This would probably be a flag for `tailscale up`.

Another thought for what could be implemented - if you run `tailscale status`, you should see what *other* nodes are running as exit nodes (but not advertised routes), but you don't see status about your own node - which would include some of the information in flags you are looking for.

**Comment by DentonGentry** [comment] 2022-02-06 03:33
Duplicate of https://github.com/tailscale/tailscale/issues/2130

**Closed by DentonGentry** 2022-02-06 03:33 UTC
Labels: T2 Visual Polish, fr

**Comment by NathanSweet** [comment] 2025-08-09 15:57
Years later it's still annoying to need to try to change the config so you can see an error so you can get the current config to add to it.
