### ISSUE TITLE
OSX: Don't hide network devices under a two-level menu

### ISSUE THREAD

**Issue by wizzard0** [tailscale/tailscale#2234] opened 2021-06-23 19:46 UTC
I always have to choose [menubar tailscale icon] > Network devices > My devices > Device.
The double-nesting looks like a totally unnecessary nuisance (esp given that otherwise Tailscale UI is clean and logical)

**Comment by bradfitz** [comment] 2021-06-23 19:59
FWIW, the menu structure works a lot better in multi-user companies with everybody having lots of devices.

Perhaps the single-user use case wasn't considered.

/cc @tailscale/frontend

**Comment by wizzard0** [comment] 2021-06-23 20:02
Oh, I see. Initially I thought the separation was by network not by the user.

**Comment by rosszurowski** [comment] 2021-06-23 22:12
The UI decision to do nested dropdowns dates back to Tailscale's very beginnings, and I agree: it's not great for most uses.

We've discussed a few approaches in the past, which we have no timeline for, but I'd love to tackle:
- Build a custom native UI to allow organizing devices outside of a nested set of dropdowns. Having a flat list with a prefix-based search mechanism would work well here. For single-users or small networks, it's just a flat list of devices. For large corporate use-cases, you can find devices by searching, rather than hunting through menus.
- Allow users to "favourite" devices that matter to them and show them up-front. This might not do much for small networks, but for larger ones, most folks only need to access a small subset of servers anyways (the gitlab server, the web server, etc), so this would make commonly accessed devices easier to get to.

**Comment by wizzard0** [comment] 2021-06-24 10:32
thanks! agree it's far from the first priority. On OSX it seems possible to add a search box as a menu item? unsure if that is available for menus of menubar icons or only for main app menus though.

**Comment by DentonGentry** [comment] 2022-05-08 03:19
I think this is best handled by making the menu different for single user tailnets.
Duplicate of https://github.com/tailscale/tailscale/issues/3319

**Closed by DentonGentry** 2022-05-08 03:19 UTC
Labels: OS-windows, OS-macos, L4 Most users, P1 Nuisance, T2 Visual Polish
