### ISSUE TITLE
Incompatibility with Cloudflare WARP

### ISSUE THREAD

**Issue by doinkythederp** [tailscale/tailscale#7252] opened 2023-02-11 00:56 UTC
### What is the issue?

I've just installed the Tailscale app from the app store and am trying to log in. However, the UI login button doesn't do anything (I'm stuck on the page below) and the CLI `/Applications/Tailscale.app/Contents/MacOS/Tailscale login` command hangs.
![43499](https://user-images.githubusercontent.com/75394401/218228047-393eb495-32af-4660-b93b-514123ded18b.png)

### Steps to reproduce

I accidentally downloaded the verson from Homebrew first (that one didn't work either) but I followed the uninstall instructions by deleting `io.tailscale.*` in `~/Library/Containers`, etc.

### OS

macOS

### OS version

macOS 13.2 (22D49)

### Tailscale version

Version 1.36.1 (App Store)

### Other software

I'm running Cloudflare WARP, and my default browser is Safari.

### Bug report

BUG-0152040540e4caab703dd11bec9396128858d4424095efe5533f892ca442c430-20230211005539Z-29d2cfd7662575e7

**Comment by doinkythederp** [comment] 2023-02-11 00:58
Okay, I've disabled Cloudflare WARP so it seems like this is an incompatability

**Comment by doinkythederp** [comment] 2023-02-11 01:05
If this can't be fixed it'd be nice to at least inform users of the incompatability when they try and set up the app

**Comment by bradfitz** [comment] 2023-02-11 01:13
cc @mihaip, likely that same issue?

**Comment by mihaip** [comment] 2023-03-06 19:31
Duplicate of #5631

**Closed by mihaip** 2023-03-06 19:31 UTC
Labels: L1 Very few, P2 Aggravating, T5 Usability, vpn-interop, bug

**Comment by Or1nge** [comment] 2023-04-29 04:36
Yeah same. However, tailscale seems to work with warp on Linux 22.04.

**Comment by happymy** [comment] 2023-12-15 13:09
1 disable  warp
2 enable Tailscale
3 Tailscale-> setting-> Tailscale DNS setting IS NOT choose.
4 enable warp

**Comment by owlboy** [comment] 2024-02-22 00:52
> 1 disable  warp
> 
> 2 enable Tailscale
> 
> 3 Tailscale-> setting-> Tailscale DNS setting IS NOT choose.
> 
> 4 enable warp

This does not work on iOS.
